### ISSUE TITLE
Animal Crossing New Horizons

### ISSUE THREAD

**Issue by Mitwirker** [Ryujinx/Ryujinx#1006]
Hi,
    nothing happens on the screen and than this error appears:
**Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2**

![Unbenannt2](https://user-images.githubusercontent.com/24736834/77249462-6caa5e00-6c41-11ea-865c-3720f0f68676.png)

Logfile:
[Ryujinx_2020-03-22_13-24-54.log](https://github.com/Ryujinx/Ryujinx/files/4365213/Ryujinx_2020-03-22_13-24-54.log)

**Comment by AcK77** [comment]
As you can read here https://github.com/Ryujinx/Ryujinx-Games-List/issues/250 it’s still WIP.
In that case I close the issue.
Thanks.
