### ISSUE TITLE
Hotswaping between docked and undocked is not implemented

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1036]
Exclusively touch control games need to be undocked, They do have a way of telling users that it must be undocked but Ryujinx can't hot-swap Between docked and undocked forcing the user to restart Ryujinx on top of this it can help for testing purposes

https://github.com/Ryujinx/Ryujinx-Games-List/issues/377

**Comment by AcK77** [comment]
Superseded by #1149
