### ISSUE TITLE
Implement VMAD shader instruction

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#1037]
The VMAD shader instruction is currently not properly implemented, it is not a big issue because they are usually only used on geometry shaders, and for what it is used for on geometry shaders, what we have right now is fine (just move the third operand), however we should implement it properly in case something else uses it.

**Comment by ameisen** [comment]
Just putting this here for reference, I believe that this is a correct implementation of it:

`
        public static void Vmad(EmitterContext context)
        {
            OpCodeVideo op = (OpCodeVideo)context.CurrOp;

            Operand srcA = Extend(context, GetSrcA(context), op.RaSelection, op.RaType);
            Operand srcC = GetSrcC(context);

            Operand srcB = op.HasRb ?
                Extend(context, Register(op.Rb), op.RbSelection, op.RbType) :
                Const(op.Immediate);

            Operand res = context.IMultiply(srcA, srcB);
            res = context.IMultiply(res, srcC);

            const int Shr7 = 1;
            const int Shr15 = 2;

            int shr = op.RawOpCode.Extract(51, 2);

            if (shr == Shr7 || shr == Shr15)
            {
                var shift = Const((shr == Shr7) ? 7 : 15);
                res = context.ShiftRightS32(res, shift);
            }

            InstEmitAluHelper.SetZnFlags(context, res, setCC: true);

            context.Copy(GetDest(context), res);
        }
`

**Comment by ameisen** [comment]
I have an implementation locally, but I used GPL2'd source code as a reference so I suspect that there's legal issues there.

**Comment by gdkchan** [comment]
You can ask @ReinUsesLisp for permission to do a implementation based on his work.
