### ISSUE TITLE
Pressing ESC should not end emulation

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#1042]
It's easy to press it by accident. It is also used to exit full screen mode, so it's also easy to press it twice by accident and end emulation that way. This was a bad decision and I think we should just remove it or add a confirmation dialog.

Relevant line of code:
https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx/Ui/GLRenderer.cs#L139

**Comment by Thog** [comment]
Fixed by #1044
