### ISSUE TITLE
Ryujinx.exe Entry Point Not Found. The procedure entry point InflateValidate could not be located in the dynamic link library.  libpng16-16.dll

### ISSUE THREAD

**Issue by fenderspeed** [Ryujinx/Ryujinx#1052]
Hi- I cannot get Ryujinx to run for the life of me and have spend hours googling possible solutions to no avail, does anyone know what I need to do? When I run the exe it gives me the error below. Log attached. 

Ryujinx.exe Entry Point Not Found
the procedure entry point InflateValidate could not be located in the dynamic link library
libpng16-16.dll

[Ryujinx_2020-03-26_21-33-42.log](https://github.com/Ryujinx/Ryujinx/files/4390948/Ryujinx_2020-03-26_21-33-42.log)

**Comment by B3astTech** [comment]
This is a issue tracker not a support tracker. Please close when able to

**Comment by polyh3dron** [comment]
this is a legit issue. I'm also experiencing this. Seems to be depending on some path variable setting that isn't present on all Windows installations for whatever reason. Not sure how to fix, but the user shouldn't have to dive into their PATH variable just to run Ryujinx as intended.
