### ISSUE TITLE
Custom builds on AppVeyor

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1055]
Right now AppVeyor knows the building number scheme. when others use it. it does not know from ryujinx master from a dirty build using the same way to be built as our masters are being built. finding a way to identify our master from dirty builds.

Custom made by VS
![Annotation 2020-03-27 105000](https://user-images.githubusercontent.com/45114656/77785011-bebffa80-7018-11ea-9aff-6b84efd6c6c9.png)

Custom made by AppVeyor
![Annotation_2020-03-04_104058](https://user-images.githubusercontent.com/45114656/77784928-9afcb480-7018-11ea-813c-0b5dd7e0023f.png)

**Comment by AcK77** [comment]
Lock the building number is nearly impossible, in that way I close this issue.
