### ISSUE TITLE
Custom system date/time

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1057]
Overridden time of the system weather the user wants it to be at a specific time.

- UI: Add date/time picker
- Config: CustomDateTimeTicksOffset = Custom DateTime - Local Computer DateTime
- Service Call: return LocalSystemTime + CustomDateTimeTicksOffset

**Comment by k00lagin** [comment]
I think it'd be great to have separate timer for each game.

**Comment by AcK77** [comment]
Fixed in #1101
