### ISSUE TITLE
moonlight stream sound device SoundIOSharp.SoundIOException: incompatible device

### ISSUE THREAD

**Issue by rufengsuixing** [Ryujinx/Ryujinx#1061]
[Ryujinx_2020-03-28_10-36-17.log](https://github.com/Ryujinx/Ryujinx/files/4396546/Ryujinx_2020-03-28_10-36-17.log)

**Comment by AcK77** [comment]
This is for development issue. If you need support please come to our discord server (https://discord.gg/N2FmfVc).

To fix your issue, install OpenAL (https://www.openal.org/downloads/oalinst.zip) and it should be good.
Thanks.
