### ISSUE TITLE
[AC-NH] V-Sync on increases odds of crashing during intro

### ISSUE THREAD

**Issue by TyrantNomad** [Ryujinx/Ryujinx#1064]
This is an anecdotal report collected from the experience a few Discord members have shared, including myself.

With V-Sync on and no save files, Animal Crossing NH freezes during the first frames of showing the Nook Inc. sign; I tried this myself 5 times with V-Sync on and not once did it even fully show the sign itself, with the emulator then crashing.

With V-Sync off, the first try was a clear improvement - with the game showing the full Nook Inc. sign and then 20% of the background; on the second try - also without any crashes.

I was able to get through the intro on the second try with V-Sync off.

Other users have also reported crashing as soon as the sign shows with V-Sync on, and either getting further or getting through the intro with V-Sync off.

**Comment by Thog** [comment]
This is a known issue of ACNH but is entirely unrelated to VSync.

Please note that if you want to comment about an issue on the game, you should post it in comment of this issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/250.

As such I'm closing this issue.
