### ISSUE TITLE
appletAE ISelfController: 100 (SetAlbumImageTakenNotificationEnabled) is not implemented

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1065]
appletAE ISelfController: 100 (SetAlbumImageTakenNotificationEnabled) is not implemented.

[Switchbrew](https://switchbrew.org/w/index.php?title=Applet_Manager_services#SetAlbumImageTakenNotificationEnabled)

## Service description:

```
Takes an input u8 bool, no output.
See #AppletMessage.
```

## Required by: 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/465

**Comment by gdkchan** [comment]
Fixed by #1411
