### ISSUE TITLE
I'm trying to play animal crossing, but when I double-click on the game ryujinx closes, what do I do? :(

### ISSUE THREAD

**Issue by choraoSK8** [Ryujinx/Ryujinx#1071]
fatal error. system.accessviolationexception: attempted to read or write protected memory
![Screenshot_2](https://user-images.githubusercontent.com/62860044/77864691-1a94aa00-71f8-11ea-996f-6f5560de5b05.png)

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.

**Comment by choraoSK8** [comment]
ok :(

**Comment by choraoSK8** [comment]
> This is for development issues.
> If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
> Thanks.

ok :(
