### ISSUE TITLE
Publishing Ryujinx on Flathub

### ISSUE THREAD

**Issue by FinixFighter** [Ryujinx/Ryujinx#1077]
Hi! I wanted to ask you if you can create a flatpak version of Ryujinx, it would be easier for people using Linux to find the app, install and update it, because they'll have it in their repo. This is the submission wiki: https://github.com/flathub/flathub/wiki/App-Submission :)

**Comment by albfan** [comment]
app submited flathub/flathub#1778

**Comment by albfan** [comment]
Flatpak is ready, but error running remains:

```
00:00:00.957 |N| Application : Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

Any ideas @Thog? I opened a bug on opentk, but you commented there as that is a wrong place https://github.com/opentk/opentk/issues/1116

**Comment by anthr76** [comment]
Any progress on this? Can I help out anywhere? It would be great to have this built!

**Comment by albfan** [comment]
That main problem was already solved with

https://github.com/flathub/flathub/pull/1778/files#diff-8a6702c7dee1571e5ff071f3702bb0a52fdd5b95dd21c4cbbd5543ca910dc4e7R48

thanks to @refi64 https://github.com/Ryujinx/Opentk/issues/6#issuecomment-695846112

but there're still some non standard paths that needs to be corrected (as in a proper install like flatpak uses you cannot just write things on current working directory)

This kind of patches (like the one for Log files)

https://github.com/flathub/flathub/pull/1778/files#diff-aa2d3a3ee89aa2d88517e59964a8368cb39ac4f1afad60cc1fc63b053981a537R10

needs to be addressed (probably upstream so it can be working dir by default but standard dir for other installations) to ease distribution. @Thog might now better.

to be a reproducible build it needs to create the list of dependencies (there's a tool to collect them) but I can't remember how it is called.

**Comment by anthr76** [comment]
As I'm on a immutable OS I would love to try Ryujinx. I have no idea where to get started do the maintainers have an idea on how they want this addressed?

**Comment by albfan** [comment]
@anthr76, read comments: https://github.com/flathub/flathub/pull/1778

But latest changes would need more patches for non standard things (like run on current dir and create dirs there)

**Comment by albfan** [comment]
You can't make Windows/Mac developers design an app based on Linux standards. Libraries, user config files, they just rebuild everything.

These environments force you to reinvent the wheel, put files wherever you want, rebuild all your dependencies.

If your work rewards 50€/hour in 6 hours is more rewarding to buy a Nintendo switch than support an emulator.

Sad fact. I know all is needed to do to build ryujinx on Linux environment (aka flatpak) but an app that works as a rolling release is not worth to waste the effort.

**Comment by ghtesting2020** [comment]
Any updates? I got my Steam Deck and although I hear Ryujinx is much better than Yuzu I cannot try it because you guys aren't on Flathub. I'm sure you would gain a lot of patreon supporters (like me) that have a Steam Deck if you would cater to us as well. Even if you decide to do an alt like snap, let's be honest. Flatpaks are the future of Linux.
https://flathub.org/apps/details/org.yuzu_emu.yuzu

**Comment by MetrosexualGarbodor** [comment]
@ghtesting2020 https://github.com/flathub/flathub/pull/2884
>  I'm sure you would gain a lot of patreon supporters that have a Steam Deck 
I'm sure we won't. Thank you for your optimism though.

**Comment by CapitaineJSparrow** [comment]
> Any updates? I got my Steam Deck and although I hear Ryujinx is much better than Yuzu I cannot try it because you guys aren't on Flathub. I'm sure you would gain a lot of patreon supporters (like me) that have a Steam Deck if you would cater to us as well. Even if you decide to do an alt like snap, let's be honest. Flatpaks are the future of Linux app distribution. https://flathub.org/apps/details/org.yuzu_emu.yuzu

You can use the deck in desktop mode and download Ryujinx from aur using pacman or from Ryujinx website using browser and add it as non steam game meanwhile

**Comment by piplup55** [comment]
> > Any updates? I got my Steam Deck and although I hear Ryujinx is much better than Yuzu I cannot try it because you guys aren't on Flathub. I'm sure you would gain a lot of patreon supporters (like me) that have a Steam Deck if you would cater to us as well. Even if you decide to do an alt like snap, let's be honest. Flatpaks are the future of Linux app distribution. https://flathub.org/apps/details/org.yuzu_emu.yuzu
> 
> You can use the deck in desktop mode and download Ryujinx from aur using pacman or from Ryujinx website using browser and add it as non steam game meanwhile. I recommend to use PineJinx by the way https://github.com/edisionnano/Pine-jinx

please don't download ryujinx from the aur (you will just cause more problems for yourself especially if you use ryujinx-git which builds from source meaning you don't get any support in the discord server) just use pinejinx please

**Comment by Master811129** [comment]
Steam deck has a good amount of potetial. I think You can't do any root-install on steam deck making this application as flatpak will be a great idea for the software and hundreds of users that this console will bring into the linux ecosystem.

**Comment by Thog** [comment]
This is getting kind of very out of topic here, please reserve your discussions to private message or our discord server.

I did an initial integration based on 1.1.56 that you can install via the testing channel of flathub.

I am still waiting for news from the flathub team to know if it needs any other changes.

**Comment by albfan** [comment]
Interesting: https://github.com/flathub/flathub/pull/2884

**Comment by Thog** [comment]
We now have a package on FlatHub, waiting deployment but it should be here soon.

The CI still need some work to automatically publish new releases on flathub but I think this issue can be closed.
