### ISSUE TITLE
Unimplemented ASRS ARM32 instruction

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1081]
Requires the ARM32 ASRS instruction (immediate variant).

```
The instruction at 0x00000000009cfdc8 (opcode 0xe1011042) is undefined!
```

#### Description:
```
ASRS	R2, R0, #1
B	#0x208
```

## Required by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/511

**Comment by piyachetk** [comment]
Since ASRS is just an alias of MOVS with arithmetic shift, the existing MOV opcode already covers this opcode. I think this issue should be closed.
