### ISSUE TITLE
Breath of the Wild Random Shader Corruption

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#1083]
![image](https://user-images.githubusercontent.com/18043258/78170496-6bd7b000-7429-11ea-8734-ce7828f3d833.png)
at random boots, you will get good graphics or broken ones like in the image not sure what causes it i will attach a log here soon

**Comment by AcK77** [comment]
Since we can’t know which build is used, how to reproduce the issue and no provided logs, I close the issue. Thanks.

(I’ll reopen it if more informations will be given)

**Comment by ReaperOfSouls1909** [comment]
still on a power trip after making a fool of your self last night eh go figure
