### ISSUE TITLE
Animal Crossing New Horizons not using all my ram and cpu

### ISSUE THREAD

**Issue by Ladriverni** [Ryujinx/Ryujinx#1085]
Specs: GTX970, 24gb ram, i7 3770k
Animal crossing running at 15 - 20 fps
check at task manager, it's only using 4gb of ram.
Is there a way to tell the program to use more ram? or a way to make it faste? I've seen youtubers with worse specs get a regular decent 30fps

**Comment by Ghostotakoi** [comment]
if you want support please go to ryujinx discord server https://discord.gg/VkQYXAZ. But anyhow, your cpu is not fast enought to run the game at full speed, emulation relies on cpu clock, as higher cpu clocks and ipc better performance, gpu not so important but is important as well.
