### ISSUE TITLE
Crash on game start, System.NotImplementedException: android.gui.IGraphicBufferProducer 2

### ISSUE THREAD

**Issue by omnipeach** [Ryujinx/Ryujinx#1090]
[Ryujinx_2020-04-04_03-09-42.log](https://github.com/Ryujinx/Ryujinx/files/4430888/Ryujinx_2020-04-04_03-09-42.log)
 
Not too sure what to do about this, i've followed what seems like everything i could find

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
