### ISSUE TITLE
JIT: Operand assignment not getting cleaned up

### ISSUE THREAD

**Issue by FICTURE7** [Ryujinx/Ryujinx#1092]
I was messing around with optimizations after the PreAllocator and it seems that operand assignments are not cleaned up when the destination of an operation is set to null.

An instance where this happens is in `PreAllocator.Delete`. After `PreAllocator.HandleLoadArgument*` removes the `LoadArgument` operation at the end of the method using `PreAllocator.Delete`, the destination still has 2 assignments, i.e `[HandleLoadArgument, Copy]` instead of a single one `[Copy]`.

Presumably there is missing clean up code in `Node.Destination_set` when `value` is `null`.
https://github.com/Ryujinx/Ryujinx/blob/e99e6d0ad1fb0e0245469a67526de2dc03bc0658/ARMeilleure/IntermediateRepresentation/Node.cs#L11-L28

Also `_clearedDest` should be set to `true` instead of `false` right? Or am I missing something here?
https://github.com/Ryujinx/Ryujinx/blob/e99e6d0ad1fb0e0245469a67526de2dc03bc0658/ARMeilleure/IntermediateRepresentation/Node.cs#L124-L134

**Comment by gdkchan** [comment]
You're right, in fact for set it can just call SetDestination and pass the value directly without any checks, since it can handle the case where value is null.
```cs
public Operand Destination
{
    get => _destinations.Count != 0 ? GetDestination(0) : null;
    set => SetDestination(value);
}
```
`_clearedDest` seems correct to me (since it does assign a new destination operand after this method is called, thus requiring a subsequent "clear" in the future if it is ever changed again). It would be possible to optimize it a bit in the case where destination is set to null, this case doesn't need a "clear" (removing the old assignment).

**Comment by FICTURE7** [comment]
Looking more into it, it is not clear how much value does `_clearedDest` add. It can be replaced by `_destinations.Count == 0` and `_destinations` is never null, it is assigned only once in the constructor.

`SetSource(Operand)` and `SetDestination(Operand)` too seems to be missing "housekeeping" code, they do not handle `MemoryOperand` instances.

For `SetSource`:
https://github.com/Ryujinx/Ryujinx/blob/468d8f841ffcbebf4130371eb64ab04165bce3e9/ARMeilleure/IntermediateRepresentation/Node.cs#L174-L186

For `SetDestination`:
https://github.com/Ryujinx/Ryujinx/blob/468d8f841ffcbebf4130371eb64ab04165bce3e9/ARMeilleure/IntermediateRepresentation/Node.cs#L136-L148

**Comment by gdkchan** [comment]
Those methods seems to have been added on #978, but were not updated after the memory operand optimization landed to also handle the `MemoryOperand` type, I guess it was an oversight during rebase.
