### ISSUE TITLE
Pokémon: Let's Go, Eevee! and Pokémon: Let's Go, Pikachu! Crash 

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#1096]
![SharedScreenshot5](https://user-images.githubusercontent.com/61922384/78703368-69b99980-78e0-11ea-926c-c8e06cacd1fc.jpg)
[Ryujinx_2020-04-07_14-58-28.log](https://github.com/Ryujinx/Ryujinx/files/4446287/Ryujinx_2020-04-07_14-58-28.log)
[Ryujinx_2020-04-07_15-01-02.log](https://github.com/Ryujinx/Ryujinx/files/4446288/Ryujinx_2020-04-07_15-01-02.log)
[Ryujinx_2020-04-07_15-02-11.log](https://github.com/Ryujinx/Ryujinx/files/4446289/Ryujinx_2020-04-07_15-02-11.log)

**Comment by gdkchan** [comment]
Install OpenAL.
