### ISSUE TITLE
Allow configuration of XInput controllers

### ISSUE THREAD

**Issue by lostromb** [Ryujinx/Ryujinx#1099]
As it is, XInput controllers are supported but there's nothing in the GUI to indicate that that is the case. New users might be confused and think they can only use the keyboard for controls. It would be nice to have some basic configuration to map Switch controller ID to XInput device ID, and maybe also configure things like deadzones and rumble. I have a minor issue in Animal Crossing where player steering is way too sensitive because there is no deadzone and it would be nice to have a setting for it.

**Comment by Th3d0nGsT3R** [comment]
There is an open pr to allow this. It's in Xpl0itR's repo.

**Comment by tarocco** [comment]
related to #849

**Comment by AcK77** [comment]
Closed because it’s already implemented in #849
