### ISSUE TITLE
Trouble starting Ryujinx by spawning a command in Node.js

### ISSUE THREAD

**Issue by quinton-ashley** [Ryujinx/Ryujinx#1106]
I'm developing a frontend launcher for emulators called [Nostlan](https://github.com/quinton-ashley/nostlan/releases/tag/beta-1.8.x) and I really want to support Ryujinx.  I can't get it to run a game by spawning this command.  Is there something else I need to do?
```
$ ./Ryujinx.exe ../games/MK8.xci
```
nodejs docs on spawning commands:
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

This is the launcher file for launching all the emulator apps.
https://github.com/quinton-ashley/nostlan/blob/master/core/launcher.js

For Ryujinx the command is just:
$ {app} {game}

I make the current working directory the one the app is in and Nostlan also inherits standard out and launches the command detatched so if an emulator crashes it doesn't take Nostlan down too.

**Comment by quinton-ashley** [comment]
Will this be fixed soon?

**Comment by ertherod** [comment]
You need to set working directory to the one where is located ryujinx i think. I get it working on non-Steam program with the same command but setting working directory to which where ryujinx is

**Comment by ertherod** [comment]
`const {spawn} = require("child_process");

const acnh = spawn('./Ryujinx.exe', ['../acnh1.1.2.xci'], {cwd: "D:\\switch roms\\ryu-acnh"});`

Ive tried with this, and it is working

**Comment by quinton-ashley** [comment]
I actually found that it can't be run in detatched mode.  I run emulators in detatched mode cause if Nostlan crashes for some reason then it wouldn't take down the emulator with it.  It seems that I'll have to launch Ryujinx attached to Nostlan for now.  Maybe it's because when you close the Ryujinx console it closes the whole app so when node.js detatches the child process Ryujinx just quits.
https://nodejs.org/api/child_process.html#child_process_options_detached

**Comment by ertherod** [comment]
Indeed, the problem comes from the console, tried to build ryujinx without it and it's working in detached mode

**Comment by quinton-ashley** [comment]
Perhaps their could be a command line option to run Ryujinx without the console?

**Comment by ertherod** [comment]
Unfortunately, it would need changes because it's changing the type of build in VS. (console app > windows app)

**Comment by quinton-ashley** [comment]
Ah I see.  Well maybe in the future the non-dev version of Ryujinx should just be the windows app and not have the console attached.  For now it's fine, Nostlan shouldn't even be able to crash while in the background it's just precautionary.  Thanks for your help!
