### ISSUE TITLE
Reading uninitialised variables leads to misrendering on Mesa drivers

### ISSUE THREAD

**Issue by sigexp** [Ryujinx/Ryujinx#1109]
I've been analysing renderdoc capture of an Animal Crossing apitrace, provided in the [mesa issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/2708). Some textures appear to have severe misrenderings such as random black noise over the texture, that on some GPUs might cover the texture completely. 

<details>
<summary>Misrendering example</summary>

![Ry_misrender](https://user-images.githubusercontent.com/10928134/79140925-726b0d80-7dc1-11ea-8692-3f6fe4746ecb.jpg)

</details>

Looking at the call, where one of the major misrenderings first appeared, I've found that the fragment shader operates on a variable, passed from the vertex shader, where it wasn't properly initialised. Initialising this variable does indeed fix the defects for a particular texture:

<details>
<summary>Partially fixed</summary>

![Ry_partfixed](https://user-images.githubusercontent.com/10928134/79142301-f4f4cc80-7dc3-11ea-9492-21356a28d56c.jpg)

</details>

Applying `glsl_zero_init` workaround in `00-mesa-defaults.conf` also fixes the problem.

I've attached [both vertex and fragment shaders](https://github.com/Ryujinx/Ryujinx/files/4470760/Ryujinx_issue.zip). The variable, that was causing trouble is `out_attr2`: only `x` component was initialised in the vertex shader.

According to the GLSL spec, uninitialised variables have undefined value. From Section 5.8 "Assignments" of the GLSL 4.60.7 spec (page 122 of the PDF):

> Reading a variable before writing (or initializing) it is legal, however the value is undefined.

**Comment by jduncanator** [comment]
Thanks for reporting the issue @sigexp. I'm currently working on (re)implementing our shader cache, and this issue actually leads into some work that has to be done anyway, so I'll tackle this issue there!

**Comment by ReinUsesLisp** [comment]
I think Nvidia GPUs automatically default output attributes as `vec4(0,0,0,1)` (or `vec4(0)`, it might be different than `gl_Position`), similar to what D3D seems to do.

It probably is a matter of initializing output attributes.

I'm working on 3D unit tests, I can report in a few weeks if it's `vec4(0)` or `vec4(vec3(0), 1)` what it defaults to.
