### ISSUE TITLE
friend IFriendService: 10700 (GetPlayHistoryRegistrationKey) is not implemented

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1110]
friend IFriendService: 10700 (GetPlayHistoryRegistrationKey) is not implemented

[SwIPC](https://reswitched.github.io/SwIPC/ifaces.html#nn::friends::detail::ipc::IFriendService(10700))

## Service description:

```
GetPlayHistoryRegistrationKey(b8, nn::account::Uid) -> buffer<nn::friends::PlayHistoryRegistrationKey, 0x1a>
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/679

**Comment by EmulationFanatic** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/90
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1578
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1328
