### ISSUE TITLE
How to map 2 controllers for local multiplayer 

### ISSUE THREAD

**Issue by Brenyd** [Ryujinx/Ryujinx#1127]
I can only get one controller mapped for player 1 but I would like to figure out how to map a second controller for player 2 so me and my friend can play games together through parsec I know Yuzu has way more controller options and can easily do exactly what I want to to but Yuzu will not run the games I am trying to play how do I set up 2 inputs for Ryujinx i.e Procontroller1 = Player1
Procontroller2 = Player2 or Leftjoycon = Player1 Rightjoycon = Player2

**Comment by B3astTech** [comment]
This isn't a how to. And you cant atm in master. we are working on it [Here](https://github.com/Ryujinx/Ryujinx/pull/849)
