### ISSUE TITLE
General Way to Support Network Multiplayer Between Emulators

### ISSUE THREAD

**Issue by minmossi** [Ryujinx/Ryujinx#1128]
Almost all multiplayer games for Nintendo Switch are designed by P2P model.

That means, one of, or several of clients themselves deal processing for multiplayer things within their ROM codes, except for the matching server function.

It's probably not possible to connect emulators with regit consoles due to global identifiers in the authentic matching server.

But, we can emulate P2P networking with 2 approaches:
1. Someone, who is willing to, hosts private matching server with fixed netwrok address, which is registered to the emulator.
2. The emulator itself drives temporal matching server and prepares for incoming matching request from any network address of other emulator client(which should require other side's network address which can be pre-designated by the emulator's external UI).

This way, we can (hopefully) emulate networking function of all P2P-based Nintendo Switch multiplayer games, without redundant works for each game's compatibility.

**Comment by MetrosexualGarbodor** [comment]
Closing as LDN multiplayer is a thing now.
