### ISSUE TITLE
Optimize JitCache TryFind method

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#1129]
This method is currently used to find cached function information from a (host) address. The unwind handler function uses it to find unwinding information for a given function.

Currently `TryFind` is not very optimal since it does linear search. It can be optimized by doing binary search for example.

**Comment by ameisen** [comment]
While PR #740 presently does not merge (and cannot work because of changes to how pointers are passed around internally), the changes it made to `JitCache.cs` fix this, by only storing the most recently allocated offset for any particular address.

**Comment by gdkchan** [comment]
Fixed on #1518.
