### ISSUE TITLE
Animal Crossing - New Horizons Console Error

### ISSUE THREAD

**Issue by Omrikoo** [Ryujinx/Ryujinx#1136]
Hello there everyone!
My friend is willing to play Animal Crossing - New Horizons on Ryujinx and he is having a problem, I helped him set everything up as it should be but when he launches the game everything goes well for about 20 seconds and then it crashes and the console shows a screen (Included in this post). I'm not sure how to help him, we have tried everything but nothing had worked

I would be really glad if someone could figure out the issue and let me know the source of the problem, Have a wonderful day! ~Omrikoo

![image](https://user-images.githubusercontent.com/63965499/79691423-104e5480-8268-11ea-80c6-a95b382ea0e8.png)

**Comment by RatishISURI** [comment]
You can try disabling either multicore scheduling or fs...
it worked for on older version of ryujinx for me
(if you see a black screen wait for a loooooooooooooooooooooooooong time)

**Comment by ertherod** [comment]
Using the patreon build fixes that : [https://www.patreon.com/posts/animal-crossing-35196813](url)
But btw, issues on github arent meant to support but only for development purpose, support should be on discord

**Comment by Omrikoo** [comment]
> Try
> 1 updating
> 2 enable ignore missing service
> 3You can try disabling either multicore scheduling or fs...
> it worked for on older version of ryujinx for me
> (if you see a black screen wait for a loooooooooooooooooooooooooong time)

Ryujinx is updated to as much as it could be, he enabled ignore missing services, What's multicore scheduling and fs? Do you mind explaining a bit more?

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
