### ISSUE TITLE
Getting this console errors trying to play Animal Crossing

### ISSUE THREAD

**Issue by RyzenXI** [Ryujinx/Ryujinx#1137]
I get both this errors when i followed all the steps as they where told.
![xddd](https://user-images.githubusercontent.com/63966463/79691974-beef9680-8262-11ea-9f8f-0c214ed5c1b1.png)
![xd2](https://user-images.githubusercontent.com/63966463/79691975-bf882d00-8262-11ea-9750-4b155cd710be.png)

**Comment by ertherod** [comment]
Github issues are only for things like not implemented things, support on the discord [(](https://discordapp.com/invite/VkQYXAZ)). In this case, using the patreon build should solve your problem : [https://www.patreon.com/posts/animal-crossing-35196813](url)

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
