### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by liyutg** [Ryujinx/Ryujinx#1161]
![企业微信截图_15878315034716](https://user-images.githubusercontent.com/23010064/80284986-94b34280-8754-11ea-8158-9c43e63cc4ea.png)

**Comment by liyutg** [comment]
![image](https://user-images.githubusercontent.com/23010064/80285123-59654380-8755-11ea-84f9-653bf38b520f.png)

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
