### ISSUE TITLE
am IApplicationFunctions: 90 (EnableApplicationCrashReport) is not implemented

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1163]
am IApplicationFunctions: 90 (EnableApplicationCrashReport) is not implemented

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#EnableApplicationCrashReport) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::am::service::IApplicationFunctions(90))
```c
// Takes an input u8 bool, no output.
EnableApplicationCrashReport(b8)
```

## Required by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/860

**Comment by gdkchan** [comment]
Fixed by #1411
