### ISSUE TITLE
am ILibraryAppletAccessor: 160 (GetIndirectLayerConsumerHandle) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#1165]
am ILibraryAppletAccessor: 160 (GetIndirectLayerConsumerHandle) is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#GetIndirectLayerConsumerHandle) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::am::service::ILibraryAppletAccessor(160))
```
GetIndirectLayerConsumerHandle(nn::applet::AppletResourceUserId, pid) -> u64
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/893

**Comment by gdkchan** [comment]
Fixed by #1411
