### ISSUE TITLE
Ryujinx Crashes on startup

### ISSUE THREAD

**Issue by EgGHub** [Ryujinx/Ryujinx#1169]
My Ryujinx crashes on startup of ACNH New Version with 

 00:00:00.204 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Utf8Json.JsonParsingException: expected:'{', actual:' ', at offset:0 at Utf8Json.JsonReader.ReadIsBeginObjectWithVerify() at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver ) at Utf8Json.Resolvers.Internal.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) at Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver) at Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, IJsonFormatterResolver resolver) at Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver) at Ryujinx.Configuration.ConfigurationFileFormat.Load(String path) at Ryujinx.Program.Main(String[] args) Unhandled exception. Utf8Json.JsonParsingException: expected:'{', actual:'

Please Help

**Comment by Leischii** [comment]
Github is for development. Please join the Discord for help.
Regarding your problem, I think changing your firmware to below 10.0.0 seemed to work for some users.

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
