### ISSUE TITLE
sound out of sync in animal crossing new horizons

### ISSUE THREAD

**Issue by properchopsticks** [Ryujinx/Ryujinx#1170]
hi,

in animal crossing new horizons the sound is often out of sync with the gameplay. for example when you're outside near the waterfall sometimes you can hear it and sometimes not. other times you can hear the waterfall even when you're inside a tent. other times you can hear a radio from a tent even when you got outside. other times other sounds from inside the tent play when outside.

i'm using the patreon build anch4 on windows 10. i don't have open al installed. i'm also using the save file from patreon, otherwise the game gets stuck at the initial cutscene.

thank you

**Comment by Leischii** [comment]
Hey, 
Github is for development, not bug report. Please go to the Discord for help.
Regarding your problem, this is known and a new audio engine is in the works that should fix issues like that :)

**Comment by properchopsticks** [comment]
got it, thanks. :)
