### ISSUE TITLE
NSZ archive support

### ISSUE THREAD

**Issue by ToppestOfDogs** [Ryujinx/Ryujinx#1185]
NSZ is a compressed version of NSP. In many cases an NSZ will be a couple gigabytes smaller than an NSP, for example Links Awakening is 5.84GB as an NSP, and 2.75GB as an NSZ.
Since Ryujinx loads games and updates from NSPs without permanently installing them, converting a collection of games and updates to NSZ can take up much less space than using all NSPs or XCIs.
More information is available at: https://github.com/nicoboss/nsz

**Comment by Thog** [comment]
NSZ is a format created by pirate for pirate.

As such, Ryujinx will never support such format.
