### ISSUE TITLE
Max: The Curse Of Brotherhood GPU test master custom 

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#1195]
Game Works well master custom right after certain moments game blurs black screens bug gpu 
![SharedScreenshot12](https://user-images.githubusercontent.com/61922384/80847646-ce69ca80-8be6-11ea-9f31-aeaccc7152ed.jpg)
![SharedScreenshot13](https://user-images.githubusercontent.com/61922384/80847647-cf026100-8be6-11ea-81f7-33aaa8a230ff.jpg)
![SharedScreenshot11](https://user-images.githubusercontent.com/61922384/80847497-4d123800-8be6-11ea-902c-32abe2ac88c7.jpg)

**Comment by EmulationChannel** [comment]
Test Ryujinx master 81cba3c3
![SharedScreenshot13](https://user-images.githubusercontent.com/61922384/80848090-6caa6000-8be8-11ea-974c-5482c211ccf9.jpg)
![SharedScreenshot15](https://user-images.githubusercontent.com/61922384/80848091-6ddb8d00-8be8-11ea-9ec8-986d95fd7b39.jpg)
![SharedScreenshot16](https://user-images.githubusercontent.com/61922384/80848095-6ddb8d00-8be8-11ea-9cfa-460052addf1e.jpg)
![SharedScreenshot17](https://user-images.githubusercontent.com/61922384/80848098-6f0cba00-8be8-11ea-8f21-fbf1a6228579.jpg)
![SharedScreenshot18](https://user-images.githubusercontent.com/61922384/80848101-6f0cba00-8be8-11ea-941c-086b56076a3b.jpg)

**Comment by B3astTech** [comment]
I fail to see why this is on the issue. If anything it should go into our gamedb

**Comment by AcK77** [comment]
Since we can’t understand the issue, I close it.
