### ISSUE TITLE
System.IndexOutOfRangeException in Animal Crossing

### ISSUE THREAD

**Issue by neversphere** [Ryujinx/Ryujinx#1200]
I keep getting a random crash in ACNH. Last bits from the log:

00:01:38.123 | ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:39.479 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:39.479 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4752
		Current Value : 4751
		Waiter Valid  : True

00:01:40.111 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:40.111 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4771
		Current Value : 4770
		Waiter Valid  : True

00:01:40.278 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:40.278 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4776
		Current Value : 4775
		Waiter Valid  : True

00:01:40.477 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:40.477 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4782
		Current Value : 4781
		Waiter Valid  : True

00:01:40.578 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:40.578 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4785
		Current Value : 4784
		Waiter Valid  : True

00:01:40.677 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:40.677 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4788
		Current Value : 4787
		Waiter Valid  : True

00:01:41.758 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:41.758 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4820
		Current Value : 4819
		Waiter Valid  : True

00:01:41.956 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:41.956 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4826
		Current Value : 4825
		Waiter Valid  : True

00:01:42.112 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:42.112 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4831
		Current Value : 4830
		Waiter Valid  : True

00:01:42.248 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:42.248 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4835
		Current Value : 4834
		Waiter Valid  : True

00:01:42.744 | ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:01:42.744 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Waiting
	Fence:
		Id            : 26
		Threshold     : 4850
		Current Value : 4849
		Waiter Valid  : True

00:01:42.775 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.NvGpuFifo.SendMacroCodeData(Int32 index, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 155
   at Ryujinx.Graphics.Gpu.Engine.Methods.SendMacroCodeData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodFifo.cs:line 32
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by neversphere** [comment]
00:00:00.003 | Application Main: Ryujinx Version: 1.0.4409
00:00:01.249 | Application Main: Operating System: Microsoft Windows 10.0.17134 (X64)
00:00:01.249 | Application Main: CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
00:00:01.249 | Application Main: Total RAM: 16198 MB

**Comment by neversphere** [comment]
00:00:00.700 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.752 | Loader LoadNca: Application Loaded: Animal Crossing: New Horizons v1.0.0 [01006f8002326000] [64-bit]
00:00:00.760 | GUI.WindowThread Hid InitController: Connected ControllerType Handheld to PlayerIndex Handheld
00:00:01.435 | GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation Quadro P1000/PCIe/SSE2 (4.6.0 NVIDIA 419.17)
00:00:01.455 | ServiceAm GetAppletResourceUserId: Stubbed.
00:00:01.665 | ServiceAm AcquireForegroundRights: Stubbed.
00:00:01.688 | ServiceAm SetFocusHandlingMode: Stubbed.
00:00:01.719 | ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed.
00:00:01.790 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:01.793 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:01.793 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:01.794 | ServicePctl Initialize: Service is already initialized!

**Comment by Thog** [comment]
This is currently addressed by https://github.com/Ryujinx/Ryujinx/pull/1197

Closing as it's the wrong issue tracker.
