### ISSUE TITLE
Emulator Keeps Crashing

### ISSUE THREAD

**Issue by jtrent238** [Ryujinx/Ryujinx#1209]
It worked earlier now it keeps crashing with this:

```00:00:00.016 | Application Main: Ryujinx Version: 1.0.4447
00:00:01.294 | Application Main: Operating System: Microsoft Windows 10.0.19592 (X64)
00:00:01.295 | Application Main: CPU: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
00:00:01.295 | Application Main: Total RAM: 16357 MB
00:00:02.464 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.FormatException: Unrecognized hex char )
   at LibHac.Util.ToBytes(String input)
   at LibHac.ExternalKeyReader.ReadMainKeys(Keyset keyset, String filename, Dictionary`2 keyDict, IProgressReport logger)
   at LibHac.ExternalKeyReader.ReadKeyFile(Keyset keyset, String filename, String titleKeysFilename, String consoleKeysFilename, IProgressReport logger)
   at LibHac.ExternalKeyReader.ReadKeyFile(String filename, String titleKeysFilename, String consoleKeysFilename, IProgressReport logger, Boolean dev)
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.ReloadKeySet() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 261
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.Reload() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 207
   at Ryujinx.HLE.FileSystem.VirtualFileSystem..ctor() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 34
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.CreateInstance() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 291
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 114
   at Ryujinx.Ui.MainWindow..ctor() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 83
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 96
Unhandled exception. System.FormatException: Unrecognized hex char )
   at LibHac.Util.ToBytes(String input)
   at LibHac.ExternalKeyReader.ReadMainKeys(Keyset keyset, String filename, Dictionary`2 keyDict, IProgressReport logger)
   at LibHac.ExternalKeyReader.ReadKeyFile(Keyset keyset, String filename, String titleKeysFilename, String consoleKeysFilename, IProgressReport logger)
   at LibHac.ExternalKeyReader.ReadKeyFile(String filename, String titleKeysFilename, String consoleKeysFilename, IProgressReport logger, Boolean dev)
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.ReloadKeySet() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 261
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.Reload() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 207
   at Ryujinx.HLE.FileSystem.VirtualFileSystem..ctor() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 34
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.CreateInstance() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 291
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 114
   at Ryujinx.Ui.MainWindow..ctor() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 83
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 96
```

**Comment by AcK77** [comment]
Your keys file seems to be wrong.
Remember this is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.

**Comment by jtrent238** [comment]
; NINTENDO SWITCH KEY LIST
; ========================
; @ub3r1337 - v201805.14r2
; ••••••••••••••••••••••••
; Keys Only Without Hashes

master_key_00                                   = C2CAAFF089B9AED55694876055271C7D
master_key_01                                   = 54E1B8E999C2FD16CD07B66109ACAAA6
master_key_02                                   = 4F6B10D33072AF2F250562BFF06B6DA3
master_key_03                                   = 84E04EC20B9373818C540829CF147F3D
master_key_04                                   = CFA2176790A53FF74974BFF2AF180921

master_key_seed                                 = D8A2410AC6C59001C61D6A267C513F3C
masterkey_4x_seed                               = 2DC1F48DF35B69334210AC65DA904666

devicekey_seed                                  = 4F025F0EB66D110EDC327D4186C2F478
devicekey_4x_seed                               = 0C9109DB93930781073CC416227C6C28

dev_master_key_seed                             = 5FF9C2D94EF90027A71FCBE678D5DA28
dev_package1_key_seed                           = F5B1EABDB9378B6466BBEF9136DAF22F
dev_per_console_key_seed                        = 6E4A9592960F4527D502F15B7587C676

package1_key_00                                 = F4ECA1685C1E4DF77F19DB7B44A985CA 
package1_key_01                                 = F8C60322F75CD548B821AF9162E16F76
package1_key_02                                 = C580CB1E2D9AA9866FFEF920010FC409
package1_key_03                                 = C32009C8CB268ED053052C9237DFD8BC 
package1_key_04                                 = EDE36C3677495784B838D7265C6BA7A1

package2_key_source                             = FB8B6A9C7900C849EFD24D854D30A0C7
package2_key_00                                 = A35A19CB14404B2F4460D343D178638D
package2_key_01                                 = A0DD1EACD438610C85A191F02C1DB8A8
package2_key_02                                 = 7E5BA2AAFD57D47A85FD4A57F2076679
package2_key_03                                 = BF03E9889FA18F0D7A55E8E9F684323D
package2_key_04                                 = 09DF6E361E28EB9C96C9FA0BFC897179

titlekek_source                                 = 1EDC7B3B60E6B4D878B81715985E629B
titlekek_00                                     = 62A24D6E6D0D0E0ABF3554D259BE3DC9
titlekek_01                                     = 8821f642176969b1a18021d2665c0111
titlekek_02                                     = 5D15B9B95A5739A0AC9B20F600283962
titlekek_03                                     = 1B3F63BCB67D4B06DA5BADC7D89ACCE1
titlekek_04                                     = E45C1789A69C7AFBBF1A1E61F2499459

rsa_oaep_kek_generation_source                  = A8CA938434127FDA82CC1AA5E807B112
rsa_private_kek_generation_source               = EF2CB61A56729B9157C38B9316784DDD

eticket_rsa_kek_source                          = DBA451124CA0A9836814F5ED95E3125B
eticket_rsa_kekek_source                        = 466E57B74A447F02F321CDE58F2F5535
eticket_rsa_kek                                 = 19C8B441D318802BAD63A5BEDA283A84

ssl_rsa_kek                                     = B011100660D1DCCBAD1B1B733AFA9F95
ssl_aes_key_x                                   = 7F5BB0847B25AA67FAC84BE23D7B6903
ssl_rsa_key_y                                   = 9A383BF431D0BD8132534BA964397DE3

aes_kek_generation_source                       = 4D870986C45D20722FBA1053DA92E8A9
aes_key_generation_source                       = 89615EE05C31B6805FE58F3DA24F7AA8

key_area_key_application_source                 = 7F59971E629F36A13098066F2144C30D
key_area_key_application_00                     = EF979E289A132C23D39C4EC5A0BBA969
key_area_key_application_01                     = CDEDBAB97B69729073DFB2440BFF2C13
key_area_key_application_02                     = 75716ed3b524a01dfe21456ce26c7270
key_area_key_application_03                     = F428306544CF5707C25EAA8BC0583FD1
key_area_key_application_04                     = 798844EC099EB6A04B26C7C728A35A4D

key_area_key_ocean_source                       = 327D36085AD1758DAB4E6FBAA555D882
key_area_key_ocean_00                           = B33813E4C9C4399C75FABC673AB4947B
key_area_key_ocean_01                           = C54166EFA8C9C0F6511FA8B580191677
key_area_key_ocean_02                           = 3061CE73461E0B0409D6A33DA85843C8
key_area_key_ocean_03                           = 06F170025A64921C849DF168E74D37F2
key_area_key_ocean_04                           = DC857FD6DC1C6213076EC7B902EC5BB6

key_area_key_system_source                      = 8745F1BBA6BE79647D048BA67B5FDA4A
key_area_key_system_00                          = 6DD02AA15B440D6231236B6677DE86BC
key_area_key_system_01                          = 4AB155E7F29A292037FD147592770B12
key_area_key_system_02                          = B7A74ADEAF89C2A198C327BDFF322D7D
key_area_key_system_03                          = D5AAB1ACD23A8AEC284A316DF859D377
key_area_key_system_04                          = 9B44B45B37DE9D14754B1D22C2CA742C

header_kek_source                               = 1F12913A4ACBF00D4CDE3AF6D523882A
header_key_source                               = 5A3ED84FDEC0D82631F7E25D197BF5D01C9B7BFAF628183D71F64D73F150B9D2
header_key                                      = AEAAB1CA08ADF9BEF12991F369E3C567D6881E4E4A6A47A51F6E4877062D542D

sd_card_kek_source                              = 88358D9C629BA1A00147DBE0621B5432
sd_card_save_key_source                         = 2449B722726703A81965E6E3EA582FDD9A951517B16E8F7F1F68263152EA296A
sd_card_save_key                                = 8F696AEED967F492041CD7DACE7BAFB2F20A25AD13108ED9BAB662A09C28CC86
sd_card_nca_key_source                          = 5841A284935B56278B8E1FC518E99F2B67C793F0F24FDED075495DCA006D99C2
sd_card_nca_key                                 = 2A34D7A63F1F6C87EA8068E8A67DD66F9637EAFF943686D74F5AB43FCBCEC6DA

capsrv_hmac_key                                 = 287AABF9FED34D4E995CC7BE0D914A3221B9822A45524649B0A2CBCDD4B98E4A

keyblob_mac_seed                                = 59C7FB6FBE9BBE87656B15C0537336A5
keyblob_seed_00                                 = DF206F594454EFDC7074483B0DED9FD3
keyblob_seed_01                                 = 0C25615D684CEB421C2379EA822512AC
keyblob_seed_02                                 = 337685EE884AAE0AC28AFD7D63C0433B
keyblob_seed_03                                 = 2D1F4880EDECED3E3CF248B5657DF7BE
keyblob_seed_04                                 = BB5A01F988AFF5FC6CFF079E133C3980

normalseed_dev_00                               = 0542A0FD34E99BA87AFE08DFE9E0A94D
normalseed_dev_01                               = 678C5A031E18C873C290E88A9E175A57
normalseed_dev_02                               = CD8B155B2B83FF6ADBD05C4F5C8829CA

simpleseed_dev0_00                              = AFF1142380240F4C36AD6854DC2DA93F
simpleseed_dev0_01                              = DE00216A11EC7B3F19663995122F5234
simpleseed_dev0_02                              = E045F5BA009A72953A76A39D3C90A7B0

simpleseed_dev1_00                              = 5E177EE1D18FB73FF539B4108E9388C4
simpleseed_dev1_01                              = 2DB7C9A131EFBDF0C3CA69FCD68C8A45
simpleseed_dev1_02                              = 84D92E0DE9C5827D88BAA3E476D11773

**Comment by jtrent238** [comment]
It worked with these key list

```
; NINTENDO SWITCH KEY LIST
; ========================
; @ub3r1337 - v201805.14r2
; ••••••••••••••••••••••••
; Keys Only Without Hashes

master_key_00                                   = C2CAAFF089B9AED55694876055271C7D
master_key_01                                   = 54E1B8E999C2FD16CD07B66109ACAAA6
master_key_02                                   = 4F6B10D33072AF2F250562BFF06B6DA3
master_key_03                                   = 84E04EC20B9373818C540829CF147F3D
master_key_04                                   = CFA2176790A53FF74974BFF2AF180921

master_key_seed                                 = D8A2410AC6C59001C61D6A267C513F3C
masterkey_4x_seed                               = 2DC1F48DF35B69334210AC65DA904666

devicekey_seed                                  = 4F025F0EB66D110EDC327D4186C2F478
devicekey_4x_seed                               = 0C9109DB93930781073CC416227C6C28

dev_master_key_seed                             = 5FF9C2D94EF90027A71FCBE678D5DA28
dev_package1_key_seed                           = F5B1EABDB9378B6466BBEF9136DAF22F
dev_per_console_key_seed                        = 6E4A9592960F4527D502F15B7587C676

package1_key_00                                 = F4ECA1685C1E4DF77F19DB7B44A985CA 
package1_key_01                                 = F8C60322F75CD548B821AF9162E16F76
package1_key_02                                 = C580CB1E2D9AA9866FFEF920010FC409
package1_key_03                                 = C32009C8CB268ED053052C9237DFD8BC 
package1_key_04                                 = EDE36C3677495784B838D7265C6BA7A1

package2_key_source                             = FB8B6A9C7900C849EFD24D854D30A0C7
package2_key_00                                 = A35A19CB14404B2F4460D343D178638D
package2_key_01                                 = A0DD1EACD438610C85A191F02C1DB8A8
package2_key_02                                 = 7E5BA2AAFD57D47A85FD4A57F2076679
package2_key_03                                 = BF03E9889FA18F0D7A55E8E9F684323D
package2_key_04                                 = 09DF6E361E28EB9C96C9FA0BFC897179

titlekek_source                                 = 1EDC7B3B60E6B4D878B81715985E629B
titlekek_00                                     = 62A24D6E6D0D0E0ABF3554D259BE3DC9
titlekek_01                                     = 8821f642176969b1a18021d2665c0111
titlekek_02                                     = 5D15B9B95A5739A0AC9B20F600283962
titlekek_03                                     = 1B3F63BCB67D4B06DA5BADC7D89ACCE1
titlekek_04                                     = E45C1789A69C7AFBBF1A1E61F2499459

rsa_oaep_kek_generation_source                  = A8CA938434127FDA82CC1AA5E807B112
rsa_private_kek_generation_source               = EF2CB61A56729B9157C38B9316784DDD

eticket_rsa_kek_source                          = DBA451124CA0A9836814F5ED95E3125B
eticket_rsa_kekek_source                        = 466E57B74A447F02F321CDE58F2F5535
eticket_rsa_kek                                 = 19C8B441D318802BAD63A5BEDA283A84

ssl_rsa_kek                                     = B011100660D1DCCBAD1B1B733AFA9F95
ssl_aes_key_x                                   = 7F5BB0847B25AA67FAC84BE23D7B6903
ssl_rsa_key_y                                   = 9A383BF431D0BD8132534BA964397DE3

aes_kek_generation_source                       = 4D870986C45D20722FBA1053DA92E8A9
aes_key_generation_source                       = 89615EE05C31B6805FE58F3DA24F7AA8

key_area_key_application_source                 = 7F59971E629F36A13098066F2144C30D
key_area_key_application_00                     = EF979E289A132C23D39C4EC5A0BBA969
key_area_key_application_01                     = CDEDBAB97B69729073DFB2440BFF2C13
key_area_key_application_02                     = 75716ed3b524a01dfe21456ce26c7270
key_area_key_application_03                     = F428306544CF5707C25EAA8BC0583FD1
key_area_key_application_04                     = 798844EC099EB6A04B26C7C728A35A4D

key_area_key_ocean_source                       = 327D36085AD1758DAB4E6FBAA555D882
key_area_key_ocean_00                           = B33813E4C9C4399C75FABC673AB4947B
key_area_key_ocean_01                           = C54166EFA8C9C0F6511FA8B580191677
key_area_key_ocean_02                           = 3061CE73461E0B0409D6A33DA85843C8
key_area_key_ocean_03                           = 06F170025A64921C849DF168E74D37F2
key_area_key_ocean_04                           = DC857FD6DC1C6213076EC7B902EC5BB6

key_area_key_system_source                      = 8745F1BBA6BE79647D048BA67B5FDA4A
key_area_key_system_00                          = 6DD02AA15B440D6231236B6677DE86BC
key_area_key_system_01                          = 4AB155E7F29A292037FD147592770B12
key_area_key_system_02                          = B7A74ADEAF89C2A198C327BDFF322D7D
key_area_key_system_03                          = D5AAB1ACD23A8AEC284A316DF859D377
key_area_key_system_04                          = 9B44B45B37DE9D14754B1D22C2CA742C

header_kek_source                               = 1F12913A4ACBF00D4CDE3AF6D523882A
header_key_source                               = 5A3ED84FDEC0D82631F7E25D197BF5D01C9B7BFAF628183D71F64D73F150B9D2
header_key                                      = AEAAB1CA08ADF9BEF12991F369E3C567D6881E4E4A6A47A51F6E4877062D542D

sd_card_kek_source                              = 88358D9C629BA1A00147DBE0621B5432
sd_card_save_key_source                         = 2449B722726703A81965E6E3EA582FDD9A951517B16E8F7F1F68263152EA296A
sd_card_save_key                                = 8F696AEED967F492041CD7DACE7BAFB2F20A25AD13108ED9BAB662A09C28CC86
sd_card_nca_key_source                          = 5841A284935B56278B8E1FC518E99F2B67C793F0F24FDED075495DCA006D99C2
sd_card_nca_key                                 = 2A34D7A63F1F6C87EA8068E8A67DD66F9637EAFF943686D74F5AB43FCBCEC6DA

capsrv_hmac_key                                 = 287AABF9FED34D4E995CC7BE0D914A3221B9822A45524649B0A2CBCDD4B98E4A

keyblob_mac_seed                                = 59C7FB6FBE9BBE87656B15C0537336A5
keyblob_seed_00                                 = DF206F594454EFDC7074483B0DED9FD3
keyblob_seed_01                                 = 0C25615D684CEB421C2379EA822512AC
keyblob_seed_02                                 = 337685EE884AAE0AC28AFD7D63C0433B
keyblob_seed_03                                 = 2D1F4880EDECED3E3CF248B5657DF7BE
keyblob_seed_04                                 = BB5A01F988AFF5FC6CFF079E133C3980

normalseed_dev_00                               = 0542A0FD34E99BA87AFE08DFE9E0A94D
normalseed_dev_01                               = 678C5A031E18C873C290E88A9E175A57
normalseed_dev_02                               = CD8B155B2B83FF6ADBD05C4F5C8829CA

simpleseed_dev0_00                              = AFF1142380240F4C36AD6854DC2DA93F
simpleseed_dev0_01                              = DE00216A11EC7B3F19663995122F5234
simpleseed_dev0_02                              = E045F5BA009A72953A76A39D3C90A7B0

simpleseed_dev1_00                              = 5E177EE1D18FB73FF539B4108E9388C4
simpleseed_dev1_01                              = 2DB7C9A131EFBDF0C3CA69FCD68C8A45
simpleseed_dev1_02                              = 84D92E0DE9C5827D88BAA3E476D11773
```

**Comment by jduncanator** [comment]
@jtrent238 Please do not post keys publicly. They are sensitive material, and it's against our rules to share them.
