### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by avalonv** [Ryujinx/Ryujinx#1213]
While trying to install the firmware. I'm using Void Linux, which uses LibreSSL (not sure if that affects anything, but mentioning just in case).

**Comment by AcK77** [comment]
I don't really understand your issue but it's seems to be related to your Linux.
Remember this is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.

**Comment by Godnyx** [comment]
> While trying to install the firmware. I'm using Void Linux, which uses LibreSSL (not sure if that affects anything, but mentioning just in case).

Lol don't know If you are gonna get a notification about this but I use Void and have the same problem. Have you fixed it?

**Comment by Thog** [comment]
@Godnyx can you provide logs about your issue?
