### ISSUE TITLE
Redundant BasicBlock sometimes emitted on Tailcall

### ISSUE THREAD

**Issue by FICTURE7** [Ryujinx/Ryujinx#1228]
This code sample:
```asm
adrp  x16, #0x6a3000
ldr   x17, [x16, #0x2a0]
add   x16, x16, #0x2a0
br    x17
```

Produces the following IR in HCQ for the dynamic table call:
```
 block9 (next block10) (branch block13):
  i64 %8 = Phi (block6: i64 %4), (block8: i64 %7)
  i64 %9 = CompareAndSwap i64 0x1B223600010, i64 0x0, i64 %8 ;; DYN_TABLE_1
  i32 %10 = CompareEqual i64 %9, i64 %8
  i32 %11 = CompareEqual i64 %9, i64 0x0
  i32 %12 = BitwiseOr i32 %10, i32 %11
  BranchIfFalse i32 %12
 block10 (next block11):
  i64 %13 = Load i64 0x1B223600018 ;; DYN_TABLE_1+8
  i64 %14 = LoadArgument i32 0x0
  Store i64 [i64 %14 + 0x404], i64 0x1B223600010 ;; DYN_TABLE_1
  i64 %15 = LoadArgument i32 0x0
  Store i64 [i64 %15 + 0x80], i64 0x6A32A0
  Store i64 [i64 %15 + 0x88], i64 %8
 block11 (next block12):
  Tailcall i64 %13, i64 %14
 block12 (branch block15):
  Branch 
 block13 (next block14):
  i64 %16 = BitwiseOr i64 %8, i64 0x1
  i64 %17 = Call i64 0x7FFE224D3204, i64 %16 ;; GetFunctionAddress
  i64 %18 = LoadArgument i32 0x0
  i64 %19 = LoadArgument i32 0x0
  Store i64 [i64 %19 + 0x80], i64 0x6A32A0
  Store i64 [i64 %19 + 0x88], i64 %8
 block14 (next block15):
  Tailcall i64 %17, i64 %18
 block15:
```
It seems `block12` and `block15` are not necessary, and the codegen for the `Branch` in `block12` produces is a `jmp` which jumps pass the translation. Although this never happens because of the `Tailcall` before.

Presumably there is a missing case for `Instruction.Tailcall` here:
https://github.com/Ryujinx/Ryujinx/blob/8b81819716a82c4d0232f0c65a6401738ef86610/ARMeilleure/Translation/EmitterContext.cs#L610-L621

Though am not entirely sure.

**Comment by gdkchan** [comment]
Yes, you're correct. This method should be extended to also consider Tailcall a "Unconditional" instruction, since it will never return, and so executing the next block is not possible. That should be enough to remove the useless block.

**Comment by FICTURE7** [comment]
Adding the case for tailcall, causes a -3.1mb of textual assembly diff over 1053 dumps (41 of them is in HCQ). The diff is caused by unreachable blocks getting removed, will have to check if its actually removing dead stuff for good measure.

Also, if the `EmitterContext` did some constant folding on the fly, the dynamic table call would become a jump table call instead (could be wrong tho, haven't checked).
