### ISSUE TITLE
Frame skip for low-end computers [SUGGESTION]

### ISSUE THREAD

**Issue by Animelici804** [Ryujinx/Ryujinx#1243]
I don't technically have a low-end computer but a frame skip option would be better for having at least 30 FPS in the overworld. Thanks for reading.

**Comment by B3astTech** [comment]
We won't support a Frame skipping. It's hacky and we rather non-hacky solution. And it is borderline impossible on modern hardware like the switch to frame skip. You would have to mess with a lot of stuff that shouldn't be messed with.

In short - None one is intrested in doing such a tedious task and instead actually do work to be emulated properly and faster. This may be acceptable to be closed sooner or later

**Comment by Animelici804** [comment]
Alright. I'm closing this then. Thanks for your comment.
