### ISSUE TITLE
AC:NH - The emulator crashes after taking a photo in-game.

### ISSUE THREAD

**Issue by Animelici804** [Ryujinx/Ryujinx#1244]
When I am on my NookPhone, and I take a picture for Nook Miles, the emulator crashes. I am assuming that the reason why it crashes is the game cannot show the UI of Nintendo Switch System ROM. I know it is illegal to run a System ROM into the emulator, but the developers could just make the System ROM inaccessible.

**Comment by Joshi234** [comment]
They impossibly can put the system ROM in because it's open source and uncle Nintendo is always watching and searching anything how they can shutdown the emulator. The whey to go would be to just do nothing.

**Comment by GamerzHell9137** [comment]
Wrong place to post https://github.com/Ryujinx/Ryujinx-Games-List/issues/250

**Comment by Thog** [comment]
Closing as not valid.
