### ISSUE TITLE
Mario Kart 8 Deluxe Several graphic Issues

### ISSUE THREAD

**Issue by Ghostotakoi** [Ryujinx/Ryujinx#1248]
I have been playing MK8 deluxe lately and I had encountered this graphical issues, I know they aren´t deal breakers but I just like to report them.
**Black coins and Gold**
![ScreenShot_20200513192427_compressed](https://user-images.githubusercontent.com/20958581/82008538-020f1080-963b-11ea-8c5d-46333564ea2b.jpg)
**Weird Green Outline on the characters after I finish 1 cup.**
![ScreenShot_20200513192503_compressed](https://user-images.githubusercontent.com/20958581/82008558-105d2c80-963b-11ea-8952-ee731917d44a.jpg)
![ScreenShot_20200513192600_compressed](https://user-images.githubusercontent.com/20958581/82008568-15ba7700-963b-11ea-9694-50ee3ec2ccdf.jpg)
![ScreenShot_20200513192658_compressed](https://user-images.githubusercontent.com/20958581/82008573-16eba400-963b-11ea-9d68-01f653e2a5f2.jpg)

**Comment by GamerzHell9137** [comment]
![image](https://user-images.githubusercontent.com/2002038/82018932-905cb400-9686-11ea-8791-426daf4a9bc6.png)
![image](https://user-images.githubusercontent.com/2002038/82018993-a8ccce80-9686-11ea-9565-44353efa8b39.png)
![image](https://user-images.githubusercontent.com/2002038/82019025-b8e4ae00-9686-11ea-9c6c-40f5af8e2da3.png)
