### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by arfs15** [Ryujinx/Ryujinx#1250]
Hello,

When I try to play Animal Crossing using the emulator I get the following error on startup: `Attempted to read or write protected memory. This is often an indication that other memory is corrupt`.

I uploaded the full log to [gdrive](https://drive.google.com/file/d/1ObtGX4dxCJmnlXhAxIVcEaRmr5A6Q_bU/view?usp=sharing).

**Comment by Thog** [comment]
Not enough information to reproduce, closing.
