### ISSUE TITLE
Game not opening on elementary os 5.1.4

### ISSUE THREAD

**Issue by andrewdylanvianaamorim** [Ryujinx/Ryujinx#1260]
When I try to open New Super Mario Bros Deluxe U, the error below appears:

The error:
![Captura de tela de 2020-05-19 13-46-26](https://user-images.githubusercontent.com/57813749/82355074-1a36b500-99d8-11ea-8732-3671866ac7a8.png)
Information about my pc and SO:
![Captura de tela de 2020-05-19 13-52-31](https://user-images.githubusercontent.com/57813749/82355127-2e7ab200-99d8-11ea-8b0b-c6fab7b8aa27.png)

ps:Nivida driver 440

**Comment by Thog** [comment]
Are you using Wayland?

**Comment by andrewdylanvianaamorim** [comment]
No

**Comment by hanaral** [comment]
This may because of a missing or outdated library, as elementary is based on the Ubuntu LTS. I'll try the same game on my own elementary install to see if it is any difference.

**Comment by edisionnano** [comment]
Does your issue still occur?

**Comment by edisionnano** [comment]
This is an opentk error, this issue can be closed

**Comment by MetrosexualGarbodor** [comment]
Fixed by #2194.
