### ISSUE TITLE
Impossible to manually set a controller (MSI GC30)

### ISSUE THREAD

**Issue by DeadWrath** [Ryujinx/Ryujinx#1261]
Hi,

with the latest Ryujinx build and the new configuration panel of controllers, it's impossible to set up correctly some controlers like mine (MSI GC 30).

In game that appear it's impossible to do anything more than go left and up with left joystick and right and down with right joystick.

Please add possibility to set up all joysticks directions like in the past with :

Joystick Left :
- Left
- Right
- Up
- Down

Joystick Right :
- Left
- Right
- Up
- Down

**Comment by GoffyDude** [comment]
Please come to Discord for assistance on this. The functionality is available already

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
