### ISSUE TITLE
No browsing option for games

### ISSUE THREAD

**Issue by LauraKitten** [Ryujinx/Ryujinx#1263]
Hello, I just recently downloaded Ryujinx to be able to play animal crossing, using this tutorial:
https://www.youtube.com/watch?v=SO0IddnJeIg
At 2:46, he opens the settings, wich look at my version significally other than the one of the guy in the video.
![Capture](https://user-images.githubusercontent.com/65675289/82475882-77606280-9acd-11ea-8356-49d3ad0405a3.PNG)
I don't have the browsing button, and I also can't put the game in via drag&drop. I tried to add it by the "add" button, but it doesn't show me the game after I save, even when I wait for a while. I also didn't got any error in the console.

**Comment by GoffyDude** [comment]
Please come to discord for support on this. The UI has changed somewhat recently.
