### ISSUE TITLE
Mario Odyssey black screen, audio working.

### ISSUE THREAD

**Issue by FabioSedia** [Ryujinx/Ryujinx#1264]
If I start Mario Odyssey my screen is black, however I can move trough the menu as I hear the option select sound. My console loops this message:  | ServiceHid SendVibrationValues: Stubbed. appletResourceUserId: 0 - VibrationDeviceHandleBufferLength: 8 - VibrationValueBufferLength: 32
What I have to do? thanks

**Comment by Ghostotakoi** [comment]
It should be because you are using some sort of overlay like msi afterburner, fraps or any others... anyway github is not for support, if you want support please go to Discord. https://discord.gg/VkQYXAZ

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
