### ISSUE TITLE
Minecraft Dungeons Fails to start

### ISSUE THREAD

**Issue by gamingshifty7** [Ryujinx/Ryujinx#1288]
The Moment I Start Minecraft Dungeons, Ryujinx Crashes...

LogFile: [Ryujinx_2020-05-30_10-26-23.log](https://github.com/Ryujinx/Ryujinx/files/4705204/Ryujinx_2020-05-30_10-26-23.log)

**Comment by Shrek5InTheatres2019** [comment]
Known issue, this happens because nn:ssl:Context::ImportServerPki is not yet stubbed or implemented in the emulator. Issue is already open at #1144

**Comment by gamingshifty7** [comment]
oh so i guess I close this and subscribe to the other thread ig.
