### ISSUE TITLE
parsing firmware failed

### ISSUE THREAD

**Issue by Hakdogboi** [Ryujinx/Ryujinx#1295]
Hi I've been having this issue for awhile now. Every time I try to extract the firmware this always poops up. I tried the latest one up to 9.2.0 but this always pops up. Can you please help me.
![Ryujinx 1 0 4683 6_17_2020 12_10_56 PM](https://user-images.githubusercontent.com/65489376/83943937-671ce700-a832-11ea-8c7a-3a4ac0fd0d70.png)

**Comment by EmulationFanatic** [comment]
You need to dump your Switch keys. https://github.com/Ryujinx/Ryujinx/blob/master/KEYS.md

Also, please come to Discord as this is not the place for end user issues.
