### ISSUE TITLE
Add feature - change username (nickname) with GUI

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx#1304]
**Add new feature to change username (nickname) with GUI:**

- Add a place to change the **default username** in the **setting menu** before starting any game, like the below picture

![image](https://user-images.githubusercontent.com/5413459/84814832-b7f2c380-b01a-11ea-959f-cad9682151f3.png)

- Add ability to change the **username** when the **game asked** using the keyboard with **popup windows** (small windows to enter new nickname), see below picture

![image](https://user-images.githubusercontent.com/5413459/84814640-7104ce00-b01a-11ea-9345-41b83bb05349.png)

- Also, add a virtual keyboard to change the nickname when game asking can be controlled through a controller (wireless Xbox), also **keyboard can be used**, see below examples

![image](https://user-images.githubusercontent.com/5413459/84815821-44ea4c80-b01c-11ea-994e-212b011e9296.png)

![image](https://user-images.githubusercontent.com/5413459/84816038-9397e680-b01c-11ea-8b66-7673098b457c.png)
.

**Comment by gdkchan** [comment]
The first one is easy to do, the other 2 are much more complicated (and I'm not sure if we'd want to go that route). I think the first solution would suffice for now.
