### ISSUE TITLE
key file was not found

### ISSUE THREAD

**Issue by CRAWLER-V** [Ryujinx/Ryujinx#1308]
Hello
i've dumped my keys from my switch right now and following the KEYS.md sems to put them in the Ryujinx/system folder.
The folder no exist in the package. so i've create it and put inside the 2 files.
the popup Key file was not fount continue to appear.
i try to put the 2 file in the root of publish folder, near Ryujinx.exe, but is the same.

where is wrong?
thanks.

**Comment by EmulationFanatic** [comment]
Please come to Discord for support with running the Emulator. And be sure to read the rules carefully when you join.
