### ISSUE TITLE
Virtual XBOX 360 Controller doesn't work after input (menu) update

### ISSUE THREAD

**Issue by NiemandTV** [Ryujinx/Ryujinx#1310]
My (virtual) XBOX 360 Controller (through ViGEm/UsendMii) does not work after the input menu was updated recently. It works flawlessly with older builds. 

I'm not really sure what information I should provide you with, but I did multiple tests and the virtual controller itself works just fine. Windows lists it as "Xbox 360-Controller for Windows" under the "XBOX 360 peripherals" tab in the device manager.
To make sure that the configurations/buttons work correctly, I tested it using [this website](https://html5gamepad.com/) and got positive/correct results: 

![image](https://user-images.githubusercontent.com/49598842/84890942-69393e00-b09b-11ea-8f0b-5197497096d6.png)

Please let me know if you need more information.

**Comment by EmulationFanatic** [comment]
Please come to Discord and we can assist with this

**Comment by NiemandTV** [comment]
solved
