### ISSUE TITLE
Implement loading screen

### ISSUE THREAD

**Issue by Ghostotakoi** [Ryujinx/Ryujinx#1312]
## Feature Request

Implement a loading screen

#### Overview:
Would be nice instead just a black screen sort of a loading screen, or loading text, or bar, or whatever that indicate that is loading. Also now that FINALLY a shader cache has been implemented, could be awesome to also add a loading shaders on boot bar, and how many has been loaded.

#### Smaller Details: 
Could be awesome to also add a loading shaders on boot bar, and how many shaders has been loaded.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
It could be awesome for the experienced users, and also for the regular user to know how long it will take to boot your game due shaders or just loading the game itself.

**Comment by Thog** [comment]
This could be a possibility if we implement the necessary AM calls probably. However, this need more research to be fully understood + that would require multi layer support to be done correctly.

**Comment by Ghostotakoi** [comment]
@Thog I have update the request with the new template and also added a little request ;)

**Comment by Thog** [comment]
This is implemented as part of the Avalonia new UI, see https://github.com/Ryujinx/Ryujinx/pull/2507

**Comment by IsaacMarovitz** [comment]
Avalonia UI has this feature, and is now the default UI.
