### ISSUE TITLE
Build ryujinx error

### ISSUE THREAD

**Issue by violetrose16** [Ryujinx/Ryujinx#1315]
I typed dotnet build -c Release -r win10-x64 then enter after cloned git. 
Enter at bash command: 
 Ryujinx.Memory -> C:\Ryujinx\Ryujinx.Memory\bin\Release\netcoreapp3.1\Ryujinx.Memory.dll
  Ryujinx.Debugger -> C:\Ryujinx\Ryujinx.Debugger\bin\Release\netcoreapp3.1\Ryujinx.Debugger.dll
  Gtk has not been detected, downloading and installing it, set SkipGtkInstall to True to skip theese steps.
  Ignore Gtk extract errors, bug msbuild/issues/3884
C:\Users\rainb\.nuget\packages\gtksharp\3.22.25.56\build\GtkSharp.targets(12,5): error MSB3923: Failed to download file "https://github.com/GtkSharp/Dependencies/raw/master/gtk-3.24.zip".  The process cannot access the file 'C:\Users\.....\AppData\Local\Gtk\3.24\gtk.zip' because it is being used by another process. [C:\Ryujinx\Ryujinx.Debugger\Ryujinx.Debugger.csproj]
  Ryujinx.Memory.Tests -> C:\Ryujinx\Ryujinx.Memory.Tests\bin\Release\netcoreapp3.1\win10-x64\Ryujinx.Memory.Tests.dll
  Ryujinx.Graphics.Texture -> C:\Ryujinx\Ryujinx.Graphics.Texture\bin\Release\netcoreapp3.1\win10-x64\Ryujinx.Graphics.Texture.dll
  ARMeilleure -> C:\Ryujinx\ARMeilleure\bin\Release\netcoreapp3.1\ARMeilleure.dll
  Ryujinx.Cpu -> C:\Ryujinx\Ryujinx.Cpu\bin\Release\netcoreapp3.1\Ryujinx.Cpu.dll
  Ryujinx.Cpu -> C:\Ryujinx\Ryujinx.Cpu\bin\Release\netcoreapp3.1\win10-x64\Ryujinx.Cpu.dll
  Ryujinx.Tests -> C:\Ryujinx\Ryujinx.Tests\bin\Release\netcoreapp3.1\win10-x64\Ryujinx.Tests.dll
C:\Ryujinx\Ryujinx.Tests\Ryujinx.Tests.csproj(45,5): warning MSB3030: Could not copy the file "..\Ryujinx.Tests.Unicorn\libs\windows\libunicorn.dylib" because it was not found.
C:\Ryujinx\Ryujinx.Tests\Ryujinx.Tests.csproj(46,5): warning MSB3030: Could not copy the file "..\Ryujinx.Tests.Unicorn\libs\windows\libunicorn.so" because it was not found.
NvGpuFifo.cs(86,21): warning CS0169: The field 'NvGpuFifo._currMacroBindIndex' is never used [C:\Ryujinx\Ryujinx.Graphics.Gpu\Ryujinx.Graphics.Gpu.csproj]
NvGpuFifo.cs(85,21): warning CS0169: The field 'NvGpuFifo._currMacroPosition' is never used [C:\Ryujinx\Ryujinx.Graphics.Gpu\Ryujinx.Graphics.Gpu.csproj]
  Ryujinx.Graphics.Gpu -> C:\Ryujinx\Ryujinx.Graphics.Gpu\bin\Release\netcoreapp3.1\win10-x64\Ryujinx.Graphics.Gpu.dll
  Ryujinx.Graphics.Nvdec -> C:\Ryujinx\Ryujinx.Graphics.Nvdec\bin\Release\netcoreapp3.1\win10-x64\Ryujinx.Graphics.Nvdec.dll

Build FAILED.

C:\Ryujinx\Ryujinx.Tests\Ryujinx.Tests.csproj(45,5): warning MSB3030: Could not copy the file "..\Ryujinx.Tests.Unicorn\libs\windows\libunicorn.dylib" because it was not found.
C:\Ryujinx\Ryujinx.Tests\Ryujinx.Tests.csproj(46,5): warning MSB3030: Could not copy the file "..\Ryujinx.Tests.Unicorn\libs\windows\libunicorn.so" because it was not found.
NvGpuFifo.cs(86,21): warning CS0169: The field 'NvGpuFifo._currMacroBindIndex' is never used [C:\Ryujinx\Ryujinx.Graphics.Gpu\Ryujinx.Graphics.Gpu.csproj]
NvGpuFifo.cs(85,21): warning CS0169: The field 'NvGpuFifo._currMacroPosition' is never used [C:\Ryujinx\Ryujinx.Graphics.Gpu\Ryujinx.Graphics.Gpu.csproj]
C:\Users\rainb\.nuget\packages\gtksharp\3.22.25.56\build\GtkSharp.targets(12,5): error MSB3923: Failed to download file "https://github.com/GtkSharp/Dependencies/raw/master/gtk-3.24.zip".  The process cannot access the file 'C:\Users\rainb\AppData\Local\Gtk\3.24\gtk.zip' because it is being used by another process. [C:\Ryujinx\Ryujinx.Debugger\Ryujinx.Debugger.csproj]
    4 Warning(s)
    1 Error(s)

Time Elapsed 00:04:16.70

C:\Ryujinx>

How I can do it or fixing?

**Comment by Thog** [comment]
@violetrose16 "C:\Users\rainb.nuget\packages\gtksharp\3.22.25.56\build\GtkSharp.targets(12,5): error MSB3923: Failed to download file "https://github.com/GtkSharp/Dependencies/raw/master/gtk-3.24.zip". The process cannot access the file 'C:\Users\rainb\AppData\Local\Gtk\3.24\gtk.zip' because it is being used by another process. [C:\Ryujinx\Ryujinx.Debugger\Ryujinx.Debugger.csproj]"

Try to run it again and make sure there isn't another build process active in parallel.

As this is not a Ryujinx error, closing.
