### ISSUE TITLE
Unable to browse C:\ to add Rom Directory

### ISSUE THREAD

**Issue by Hukuma1** [Ryujinx/Ryujinx#1323]
When going to click add directory to roms and selecting my Local Disk (C:) drive to add a folder, I get this error:

<img width="326" alt="ryuerror" src="https://user-images.githubusercontent.com/54511555/85618460-b0807b00-b615-11ea-8968-f8977b2ac0ce.png">

`(Ryujinx:18296): Gdk-WARNING **: 12:24:08.417: gdkdisplay-win32.c:572: GetClipboardOwner failed with code 203: The system could not find the environment option that was entered.`

Windows 10 May 2020 update (2004)

Workaround is to add the folder path(s) manually via `Config.json`.

**Comment by Hukuma1** [comment]
Disabling Windows 10 hibernation makes the error move from `hiberfil.sys` to `pagefile.sys`.

**Comment by EmulationFanatic** [comment]
I can't duplicate this error on Windows 10 2004, but you are highly recommended NOT to add the root of your C: drive as a game directory. Point to a subdirectory where your games are located instead.

**Comment by Th3d0nGsT3R** [comment]
I can't add roots of my drive on 1903, so that might be the issue. I just made a subdirectory, and now it works fine. I can't speak about 2004, as I haven't done any testing on this update yet.

**Comment by Hukuma1** [comment]
I'm unable to browse the drive to get to the proper directory. As soon as I hit C:\ it gives me that error message and I cannot move past it.

**Comment by EmulationFanatic** [comment]
What version number of Ryujinx are you using?

**Comment by Hukuma1** [comment]
Ryujinx Version: 1.0.4761

**Comment by EmulationFanatic** [comment]
Can you share your full system specs including CPU model, motherboard chipset, and GPU?

**Comment by Hukuma1** [comment]
AMD Ryzen 3900x
Gigabyte x470
1070 Ti

**Comment by Hukuma1** [comment]
I'm thinking it's some file permission issue maybe? Clicking on D:\ enumerates the folders and files just fine. But not C:\

**Comment by EmulationFanatic** [comment]
I cannot duplicate this no matter what I've tried. I even un-hid protected operating system files in "change folder and search" options. I'm able to click C:\ and browse without an issue.

**Comment by Hukuma1** [comment]
Any way of having Ryujinx exclude scanning swap and hibernation files? Normally I'd just say whatever and stick to json editing the folder, but this currently affects the DLC paths too.

**Comment by MerryMage** [comment]
Related gtk bug https://gitlab.gnome.org/GNOME/gimp/-/issues/1700

**Comment by Hukuma1** [comment]
> Related gtk bug https://gitlab.gnome.org/GNOME/gimp/-/issues/1700

Ah! I did remove OneDrive. Scrolling through there, it still isn't fixed?

**Comment by AcK77** [comment]
I'm not able to reproduce the issue, only errors I've got are:
```
...
00:00:52.143 | GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows\Temp"
00:00:52.185 | GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows\SysWOW64\Tasks"
and more...
```
Anyone still got the issue ?

**Comment by Hukuma1** [comment]
Same message as originally. Just tried latest v1.0.5011. Can only manually add the path. Is there at least a workaround for adding different base path for update/DLC locations as well?

**Comment by AcK77** [comment]
Could you create an empty folder named `o` at the root of `C:\` ?
It's a GTK issue and apparently the empty folder seems to fix it... Yeah, it's dumb...

**Comment by Hukuma1** [comment]
That works! Stupid, but works. I'll close this issue since it's not related to Ryujinx. Thank you for the workaround.
