### ISSUE TITLE
IApplicationProxy IApplicationFunctions: 123 (GetPreviousProgramIndex) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1324]
IApplicationProxy IApplicationFunctions: 123 (GetPreviousProgramIndex) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#IApplicationFunctions) | 

## Service description:
```
No input, returns an output s32.

Gets the ProgramIndex of the Application which launched this title. The output ProgramIndex is -1 when there was no previous title.
```

## Required by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1841

**Comment by gdkchan** [comment]
Fixed by #1411
