### ISSUE TITLE
2x speed in ACNH (in some areas)

### ISSUE THREAD

**Issue by herosilas12** [Ryujinx/Ryujinx#1329]
When the game runs at 60fps (in small areas like houses and tents) the speed jumps to 2x 
as a side issue the audio is messed up and plays audio that should have ended seconds ago and is occasionally delayed

**Comment by Doctorwho1909** [comment]
the game is only 30fps ....

**Comment by herosilas12** [comment]
for whatever reason it was running at 60
I fixed it by setting the max FPS in nvidia control panel

**Comment by EmulationFanatic** [comment]
Did you have vsync enabled in Ryujinx?

**Comment by herosilas12** [comment]
yeah. why?

**Comment by EmulationFanatic** [comment]
Vsync in Ryujinx basically acts as a frame limiter. I'm surprised it allowed ACNH to go over 30FPS if it was enabled.

**Comment by herosilas12** [comment]
I think I disabled it at some point to fix some stuttering

**Comment by Thog** [comment]
That's an expected behaviour if you disable Game VSync, as such do not disable it.
