### ISSUE TITLE
Feature - Implement standard JoyCon support with motion controls.

### ISSUE THREAD

**Issue by Shrek5InTheatres2019** [Ryujinx/Ryujinx#1332]
Basically, connecting actual JoyCons to the emulator, to use all the motion controls available to them. Could do some sort of integration with https://github.com/fossephate/JoyCon-Driver , or just look at how the driver works, and implement our own solution. Could be pretty epic.

Edit: also useful: https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering

**Comment by AcK77** [comment]
Duplicate of #582

**Comment by ljmerza** [comment]
so was this ever added? this issue was closed because duplicate but the "duplicate" issue was closed and referenced this issue.

**Comment by Bitwolfies** [comment]
> so was this ever added? this issue was closed because duplicate but the "duplicate" issue was closed and referenced this issue.

Wondering this too, the other thread said “closed with #1332” which links here. Seems like they got confused cause this isn’t a pr.
