### ISSUE TITLE
Mario Kart 8 Deluxe: Severe Rendering Issues on Linux/RadeonSI

### ISSUE THREAD

**Issue by RealJohnGalt** [Ryujinx/Ryujinx#1347]
### Screenshots
![image1](https://cdn.discordapp.com/attachments/410208534861447170/727932554488971295/Screenshot_20200701_130158.png)
![image2](https://cdn.discordapp.com/attachments/410208534861447170/727934324774797342/Screenshot_20200701_131055.png)
![image3](https://cdn.discordapp.com/attachments/410208534861447170/727937383940489276/Screenshot_20200701_132249.png)

### Specs

```
System:    Host: miniarch Kernel: 5.8.0-rc3-1-tkg-pds x86_64 bits: 64 compiler: N/A Desktop: KDE Plasma 5.19.2 tk: Qt 5.15.0 
           wm: kwin_x11 dm: SDDM Distro: Arch Linux 
CPU:       Topology: 6-Core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 2 L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 105590 
           Speed: 4399 MHz min/max: 2200/4400 MHz Core speeds (MHz): 1: 4398 2: 4399 3: 4395 4: 4394 5: 4399 6: 4399 7: 4399 
           8: 4399 9: 4396 10: 4397 11: 4398 12: 4397 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: XFX Pine 
           driver: amdgpu v: kernel bus ID: 26:00.0 chip ID: 1002:67df 
           Display: x11 server: X.Org 1.20.8 compositor: kwin_x11 driver: amdgpu unloaded: fbdev,modesetting,vesa 
           alternate: ati resolution: 1: 3840x2160~60Hz 2: 2560x1440~60Hz s-dpi: 96 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.38.0 5.8.0-rc3-1-tkg-pds LLVM 11.0.0) 
           v: 4.6 Mesa 20.2.0-devel (git-7a5e6fd25f) direct render: Yes
```

### Troubleshooting Steps
 - Tried running on Mesa 19.3.4 (llvm 9), Mesa 20.0.4 (llvm 10) and current mesa git (llvm git).
 - Launched with all combinations of the following:
    - MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d"
    - glsl_zero_init=true (when 20+ was used)
    - AMD_DEBUG=nofmask,nohyperz

### Apitrace Info
I recorded an apitrace of the issue, which gave many severe errors on playback: https://bpa.st/Y6LA .
These were why I decided not to submit as a Mesa issue.

Full apitrace: https://www.mediafire.com/file/hy5uk6udxmotnpd/ryumk8d.tar.xz/file

**Comment by Thog** [comment]
Could you test again to see if the issue wasn't fixed?

**Comment by B3astTech** [comment]
Tbh. This probably needs closed since it's been soo long ago.

**Comment by Essasetic** [comment]
I have an AMD GPU Linux setup at home. I'll check tonight to see if this issue is still valid.

**Comment by Essasetic** [comment]
**Screenshots:**
![Ryujinx 1](https://user-images.githubusercontent.com/34970796/150832434-9762b0dc-ae06-4607-894f-793def943b79.png)
![Ryujinx 2](https://user-images.githubusercontent.com/34970796/150832440-4cff6a01-8ecc-4072-8703-d779c8646bb7.png)
![Ryujinx 3](https://user-images.githubusercontent.com/34970796/150832445-0c81d803-a037-491c-8c2c-2162230e9cc3.png)

Using an RX 6800 with Mesa 21.3.4 with pinejinx optimisations.

I will note that the game crashed twice (once while I left it idle for like two minutes on the menu and once after I took the screenshot on MKTV) and there is some flickering here and there. But apart
