### ISSUE TITLE
MainWindow.cs ERROR

### ISSUE THREAD

**Issue by AthenaCN** [Ryujinx/Ryujinx#1357]
./Ryujinx 
00:00:00.043 | Application Main: Ryujinx Version: 1.0.0-dirty
00:00:00.060 | Application Main: Operating System: Linux 5.4.10-200.fc31.x86_64 #1 SMP Thu Jan 9 19:58:12 UTC 2020 (X64)
00:00:00.060 | Application Main: CPU: Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
00:00:00.060 | Application Main: Total RAM: 3728 MB
00:00:01.423 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /home/athena/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 91
   at Ryujinx.Ui.MainWindow..ctor() in /home/athena/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 85
   at Ryujinx.Program.Main(String[] args) in /home/athena/Ryujinx/Ryujinx/Program.cs:line 97
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /home/athena/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 91
   at Ryujinx.Ui.MainWindow..ctor() in /home/athena/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 85
   at Ryujinx.Program.Main(String[] args) in /home/athena/Ryujinx/Ryujinx/Program.cs:line 97
Aborted (core dumped)

When I start the Ryujinx which was builded from the source code, the program crashs and feedback the MainWIndow error. Do I miss some dependancies ? Please Help ! The pre-build version also has the same error.

And by the way, dose Ryujinx support arm PC ? I imagine that I can compile and run it on NVIDIA AGX xaiver..... Will it come true in the future ?

**Comment by Thog** [comment]
Do you have GTK3 installed?

**Comment by AthenaCN** [comment]
@Thog Yes, gtk3 is a default package of the Fedora 32.
[root@bogon athena]# dnf install gtk3
Last metadata expiration check: 1:34:39 ago on Sat 04 Jul 2020 05:06:33 PM CST.
Package gtk3-3.24.20-1.fc32.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by AthenaCN** [comment]
[athena@bogon Ryujinx]$ dotnet build -c Release -r linux-x64
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 194.61 ms for /home/athena/Ryujinx/Ryujinx.Cpu/Ryujinx.Cpu.csproj.
  Restore completed in 14.72 ms for /home/athena/Ryujinx/Ryujinx.Debugger/Ryujinx.Debugger.csproj.
  Restore completed in 28.43 ms for /home/athena/Ryujinx/Ryujinx.Graphics.GAL/Ryujinx.Graphics.GAL.csproj.
  Restore completed in 300.97 ms for /home/athena/Ryujinx/ARMeilleure/ARMeilleure.csproj.
  Restore completed in 300.97 ms for /home/athena/Ryujinx/Ryujinx.Audio/Ryujinx.Audio.csproj.
  Restore completed in 300.97 ms for /home/athena/Ryujinx/Ryujinx.Common/Ryujinx.Common.csproj.
  Restore completed in 3.64 ms for /home/athena/Ryujinx/Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj.
  Restore completed in 18.58 ms for /home/athena/Ryujinx/Ryujinx.Graphics.Shader/Ryujinx.Graphics.Shader.csproj.
  Restore completed in 22.06 ms for /home/athena/Ryujinx/Ryujinx.Graphics.Gpu/Ryujinx.Graphics.Gpu.csproj.
  Restore completed in 21.7 ms for /home/athena/Ryujinx/Ryujinx.Graphics.Nvdec/Ryujinx.Graphics.Nvdec.csproj.
  Restore completed in 79.17 ms for /home/athena/Ryujinx/Ryujinx.Memory/Ryujinx.Memory.csproj.
  Restore completed in 88.75 ms for /home/athena/Ryujinx/Ryujinx.Graphics.Texture/Ryujinx.Graphics.Texture.csproj.
  Restore completed in 36.45 ms for /home/athena/Ryujinx/Ryujinx.ShaderTools/Ryujinx.ShaderTools.csproj.
  Restore completed in 105.17 ms for /home/athena/Ryujinx/Ryujinx.Memory.Tests/Ryujinx.Memory.Tests.csproj.
  Restore completed in 22.73 ms for /home/athena/Ryujinx/Ryujinx.Tests.Unicorn/Ryujinx.Tests.Unicorn.csproj.
  Restore completed in 158.16 ms for /home/athena/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj.
  Restore completed in 24.49 ms for /home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj.
  Restore completed in 33.27 ms for /home/athena/Ryujinx/Ryujinx/Ryujinx.csproj.
  Ryujinx.Common -> /home/athena/Ryujinx/Ryujinx.Common/bin/Release/netcoreapp3.1/Ryujinx.Common.dll
  Ryujinx.Common -> /home/athena/Ryujinx/Ryujinx.Common/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Common.dll
  Ryujinx.Audio -> /home/athena/Ryujinx/Ryujinx.Audio/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Audio.dll
  Ryujinx.Tests.Unicorn -> /home/athena/Ryujinx/Ryujinx.Tests.Unicorn/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Tests.Unicorn.dll
  Ryujinx.Graphics.Shader -> /home/athena/Ryujinx/Ryujinx.Graphics.Shader/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Graphics.Shader.dll
  ARMeilleure -> /home/athena/Ryujinx/ARMeilleure/bin/Release/netcoreapp3.1/ARMeilleure.dll
  Ryujinx.Memory -> /home/athena/Ryujinx/Ryujinx.Memory/bin/Release/netcoreapp3.1/Ryujinx.Memory.dll
  Ryujinx.Debugger -> /home/athena/Ryujinx/Ryujinx.Debugger/bin/Release/netcoreapp3.1/Ryujinx.Debugger.dll
  Ryujinx.Graphics.Texture -> /home/athena/Ryujinx/Ryujinx.Graphics.Texture/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Graphics.Texture.dll
  Ryujinx.Debugger -> /home/athena/Ryujinx/Ryujinx.Debugger/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Debugger.dll
  Ryujinx.Memory -> /home/athena/Ryujinx/Ryujinx.Memory/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Memory.dll
  ARMeilleure -> /home/athena/Ryujinx/ARMeilleure/bin/Release/netcoreapp3.1/linux-x64/ARMeilleure.dll
  Ryujinx.Graphics.GAL -> /home/athena/Ryujinx/Ryujinx.Graphics.GAL/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Graphics.GAL.dll
  Ryujinx.ShaderTools -> /home/athena/Ryujinx/Ryujinx.ShaderTools/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.ShaderTools.dll
  Ryujinx.Cpu -> /home/athena/Ryujinx/Ryujinx.Cpu/bin/Release/netcoreapp3.1/Ryujinx.Cpu.dll
  Ryujinx.Cpu -> /home/athena/Ryujinx/Ryujinx.Cpu/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Cpu.dll
  Ryujinx.Graphics.OpenGL -> /home/athena/Ryujinx/Ryujinx.Graphics.OpenGL/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Graphics.OpenGL.dll
  Ryujinx.Memory.Tests -> /home/athena/Ryujinx/Ryujinx.Memory.Tests/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Memory.Tests.dll
  Ryujinx.Tests -> /home/athena/Ryujinx/Ryujinx.Tests/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Tests.dll
/home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj(44,5): warning MSB3030: Could not copy the file "../Ryujinx.Tests.Unicorn/libs/linux/unicorn.dll" because it was not found.
/home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj(45,5): warning MSB3030: Could not copy the file "../Ryujinx.Tests.Unicorn/libs/linux/libunicorn.dylib" because it was not found.
/home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj(46,5): warning MSB3030: Could not copy the file "../Ryujinx.Tests.Unicorn/libs/linux/libunicorn.so" because it was not found.
  Ryujinx.Graphics.Gpu -> /home/athena/Ryujinx/Ryujinx.Graphics.Gpu/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Graphics.Gpu.dll
  Ryujinx.HLE -> /home/athena/Ryujinx/Ryujinx.HLE/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.HLE.dll
  Ryujinx.Graphics.Nvdec -> /home/athena/Ryujinx/Ryujinx.Graphics.Nvdec/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.Graphics.Nvdec.dll
  Ryujinx -> /home/athena/Ryujinx/Ryujinx/bin/Release/netcoreapp3.1/linux-x64/Ryujinx.dll

Build succeeded.

/home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj(44,5): warning MSB3030: Could not copy the file "../Ryujinx.Tests.Unicorn/libs/linux/unicorn.dll" because it was not found.
/home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj(45,5): warning MSB3030: Could not copy the file "../Ryujinx.Tests.Unicorn/libs/linux/libunicorn.dylib" because it was not found.
/home/athena/Ryujinx/Ryujinx.Tests/Ryujinx.Tests.csproj(46,5): warning MSB3030: Could not copy the file "../Ryujinx.Tests.Unicorn/libs/linux/libunicorn.so" because it was not found.
    3 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.72

**Comment by AthenaCN** [comment]
[athena@bogon Ryujinx]$ uname -a
Linux bogon 5.7.6-201.fc32.x86_64 #1 SMP Mon Jun 29 15:15:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AthenaCN** [comment]
The compile process is posted up there, 3 warnings, but seems no relationship with the MainWindow.cs ERROR

Pre-build has the same problem......

**Comment by Thog** [comment]
Looked a bit at the error, it looks like the Display instance is null for some odd reasons (even if GTK3 was initialized???)

**Comment by AthenaCN** [comment]
GTK3 seems OK. Ryujinx crashed after "Key file was not found", "Please refer to `KEYS.md` for more info" window pop out. If GTK3 is improper, the info window will never show. The bug seems at the line 97 of MainWindow.cs, Ryujinx abort at there.
MainWindow mainWindow = new MainWindow();
mainWindow.Show();
Should set something at there ?
I know less about C#, just sit and wait for bug fixing......

**Comment by AthenaCN** [comment]
The bug seems has been fixed since ryujinx-1.0.4864-linux_x64.
![Screenshot from 2020-07-08 18-53-03](https://user-images.githubusercontent.com/18543480/86910678-a2ba1200-c14c-11ea-9955-051c0ab87242.png)
