### ISSUE TITLE
Console profiles for two player games like AC:NH

### ISSUE THREAD

**Issue by SrAlvaritop** [Ryujinx/Ryujinx#1368]
Hi there,
I want to know if Ryujinx have any way I can create a new profile to create another secondary player in animal crossing new horizons?

I hope you can help me, thanks :D

**Comment by AcK77** [comment]
Ryujinx currently don’t support multiple users account in our HOS emulation. There is just one as default.

**Comment by Shahil-Ayato** [comment]
I believe this should be closed as for one Animal crossing doesn’t support multiple islands per system and custom user profiles was implemented in #2227.
