### ISSUE TITLE
Input mapping GUI incorrectly registering button presses [linux, dualshock4]

### ISSUE THREAD

**Issue by ghost** [Ryujinx/Ryujinx#1374]
Steps to recreate:
Settings > Input > Player 1 Configure > Select Input Device (Controller/0 PS4 Controller) > Select A 'unbound'
Whatever button I set A to gets populated into every field as soon as I press the 'unbound' button

I used various other programs to verify that I did not in fact have a sticky button.
I also verified that the issue persists both with the DS4 kernel driver as well as with the Steam controller driver.

**Comment by logos88** [comment]
I also have the same problem in Manjaro Linux. I have a DS4 and every button automatically when I click them appears as Button1, and I can't configure my Dualshock 4 controller.

**Comment by realToadtoad** [comment]
Can confirm the same issue. As a workaround, you can set a button, save, exit ryujinx, and repeat. It's really tedious, but it works (except for the d-pad but that's another issue.) Here's the controller profile I made for a dualshock 4 using this method (and fixing the d-pad). Just drop the json file to ~/.config/Ryujinx/profiles/controller/

[DS4.zip](https://github.com/Ryujinx/Ryujinx/files/4945395/DS4.zip)

**Comment by RealJohnGalt** [comment]
I can also confirm this issue with both ds4 and ds3.

**Comment by jgoyvaerts** [comment]
Doesn't happen on Windows DS4. Probably Linux specific?

**Comment by Dravonic** [comment]
Happens to me on Linux Mint 20 if I have Steam open, without Steam on the background it works mostly fine. Mostly because I still can't set the d-pad and trigger buttons properly. Trigger buttons are registering as a button instead of axis, but they work fine that way for any game I tried.

**Comment by d3ce1t** [comment]
I can also confirm this issue with ds3 in Fedora 32

**Comment by macabeus** [comment]
PR related: https://github.com/Ryujinx/Ryujinx/pull/1751
