### ISSUE TITLE
Switch Pro Controller not detected  [linux]

### ISSUE THREAD

**Issue by jordan-bauer** [Ryujinx/Ryujinx#1375]
Using Manjaro and latest auto build package.
Switch Pro controller not being detected and made select-able in input device menu.

Issue persists using hid-nintendo-dkms driver as well as Steams Switch Pro controller driver.

**Comment by SeraUX** [comment]
the Config.json needs to have full read/write permissions to work properly

**Comment by insanemal** [comment]
That's not an answer. I have full RW permissions on Config.json and Ryujinx cannot see my Pro controller. Yuzu can. So its not RW permissions on a config file preventing that.

**Comment by Melechtna** [comment]
Can confirm that it's not the config, I'm unable to either, I'm using the same driver.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I have the same issue on Windows 10.
- Windows sees Pro Controller connected
- Yuzu detects Controller and I can use it in game
- Steam detects Controller and all Test works

But Ryujinx doesn't list it in Inputs, and even worse powers it off when i go into Inputs and if I then press a Button on the Controller to re-enable it, it freaks out and randomly switches Player Indicator LEDS and powers it off again.

When I don't go into Inputs and simply start a Game, then Ryujinx says Pro Controller connected for Player 1 upon start up in the logs, but in game no buttons or anything works.
