### ISSUE TITLE
Add feature - Run Ryujinx without GUI

### ISSUE THREAD

**Issue by thegamingrestoration** [Ryujinx/Ryujinx#1386]
Ryujinx lets you run games directly using the command line, but there's no option to disable the graphical interface and play inside a simple window (similar to yuzu-cmd).

![Screenshot_20200711_001824](https://user-images.githubusercontent.com/37403401/87252622-ce066f00-c474-11ea-98be-885be03dc50a.png)

**Comment by AcK77** [comment]
Fixed in #2310
