### ISSUE TITLE
Games completely broken on Mesa 20 and higher on AMD graphics cards

### ISSUE THREAD

**Issue by gurannsan** [Ryujinx/Ryujinx#1389]

**Comment by B3astTech** [comment]
This is most likely not our issue. This issue most likely is AMD's with there opengl being so bad, They have neglected to fix any of there opengl issues, You may want to give AMD feedback aswell.

**Comment by gurannsan** [comment]
Oh ok👍🏻

**Comment by B3astTech** [comment]
You may want to also give Mesa devs feedback

**Comment by gurannsan** [comment]
I’ll do that then👍🏻

**Comment by B3astTech** [comment]
We would like to know more about this issue just to look into it. Could you give us a detailed explanation so we can look into it?

**Comment by gurannsan** [comment]
Looks something like this:
![Capture](https://user-images.githubusercontent.com/25590393/87464019-b664ed00-c612-11ea-8a4a-36b1f5bbb9b2.PNG)

**Comment by B3astTech** [comment]
If this is a game specific issue please go to 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/250

And post it here.

**Comment by gurannsan** [comment]
No it’d like that everywhere

**Comment by ReaperOfSouls1909** [comment]
In support check pins for mesa 20 flags to solve graphic issues

**Comment by gurannsan** [comment]
Ok, thanks!
