### ISSUE TITLE
Improve CPU translation speeds

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#139]
Currently every time a new subroutine needs to be executed on the CPU, it will:
- Decode the instructions inside the basic block.
- Generate the CIL for that code and create the managed method.
- Try to execute said method, which in turn triggers compilation on the .NET JIT.

This is a expensive and slow process, and causes short pauses/lag on games at startup, and may also cause minor lags during gameplay aswell. We should investigate and implement ways to improve this situation. Some of my current ideas are:
- Implementing an interpreter - this is a lot of work and something I really didn't want to do, but I think it may be worth it. With a interpreter, we can avoid wasting time translating cold functions (where most of the time would be spent translating it instead of executing, which is not profitable). I expect something like this to also improve startup time, since most of the functions that runs at startup are cold. Currently some games takes up to 2~4 minutes to actually show something which is just not acceptable.
- Background translation - Currently as there is no interpreter we have no choice but translating the function. With a interpreter we can then do the translation of the higher quality code on the background, thus not affecting normal execution (avoiding the pauses). One possible problem with this is that .NET doesn't seems to expose any method to trigger pre-JITing of code. The closest thing is `RuntimeHelpers.PrepareMethod` but it's not possible to use it with dynamic methods, so it's not useful for us. One possible solution is doing a dummy executing of the method to force the JIT to compile it on another thread, but that's tricky to do without inserting dummy code (which could hurt perf).

**Comment by strubelz** [comment]
I'm really no expert on this topic, but could it maybe be possible to do some kond of "speculative translation"? Basically just trying to guess which code will be executed next and then translating it in the background.

**Comment by gdkchan** [comment]
I believe that this could improve it a bit. But we'd still have the problem i mentioned, "One possible problem with this is that .NET doesn't seems to expose any method to trigger pre-JITing of code. The closest thing is RuntimeHelpers.PrepareMethod but it's not possible to use it with dynamic methods, so it's not useful for us." So we would still pay (part of) the JITing cost at the first call of the method. So in the end I think that the improvement would still not be even close to the ideal.

I believe that an interpreter is the way to go as we won't waste time translating code that will just run once or just a few times, spending more time on translation than on execution. For the hot code that is JITed, we can implement other techniques (like the speculative translation you mentioned) to improve it even more if we feel its needed,

**Comment by strubelz** [comment]
Hmm ok. So i dug arou d a bit and found out that it's apparently possible to pre-JIT dynamic methods in Mono. And it seems that the folks over at [Harmony](https://github.com/pardeike/Harmony) were able to port it over to .NET. I found a method called PrepareDynamicMethod in this class: https://github.com/pardeike/Harmony/blob/master/Harmony/Tools/DynamicTools.cs

**Comment by gdkchan** [comment]
They seem to use reflection to call some protected methods on the class, this is fragile as any new version of .net that modifies it may break the code.

**Comment by strubelz** [comment]
Yeah, that would be the best way to do it. But even a simple change can take a long time.

**Comment by lostromb** [comment]
What's the drawback of just invoking the method like normal to warm it up? Is it because execution would have side effects on the environment that would need to be isolated?

**Comment by gdkchan** [comment]
Yes, thats the proble, we don't know what the method will do. It may contain a loop that depends on some specific state to exit, and without such state it may just run forever for example.

**Comment by lostromb** [comment]
A random idea I just had - could the dynamic methods be serialized into an assembly on disk for each game and thus built up in the same way as a shader / program cache? Then you could at least save what functions have been seen before and run PrepareMethod on those at startup time to reduce jitter on subsequent playthroughs

**Comment by gdkchan** [comment]
PrepareMethod doesn't work on DynamicMethods as it was discussed above. It's possible to save it on disk with `AssemblyBuilder.Save` on .NET but those APIs are not available on .NET Core (or at least wasn't last time I checked, maybe that changed recently, I will check again).

**Comment by lostromb** [comment]
Yeah, I just checked it there was a possible workaround using GetObjectData() and SerializationInfo but those throw NotImplemented exceptions

**Comment by gdkchan** [comment]
Closing as the issue is no longer relevant for the most part, since we don't generate IL anymore, and the translation speed has improved a lot since then.
