### ISSUE TITLE
Cannot open emulator on Linux

### ISSUE THREAD

**Issue by potatoeggy** [Ryujinx/Ryujinx#1393]
The precompiled build returns the following while a manual build returns something similar:
```
00:00:00.063 | Application Main: Ryujinx Version: 1.0.4902
00:00:00.085 | Application Main: Operating System: Linux 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 (X64)
00:00:00.085 | Application Main: CPU: AMD Ryzen 5 4500U with Radeon Graphics
00:00:00.085 | Application Main: Total RAM: 7386 MB
00:00:00.366 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 91
   at Ryujinx.Ui.MainWindow..ctor() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 85
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 97
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 91
   at Ryujinx.Ui.MainWindow..ctor() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 85
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 97
[1]    3150290 abort (core dumped)  ./Ryujinx
```
This issue looks like it might be the same as #1357. GTK 3 is definitely installed:
```
pacman -Q gtk3
gtk3 1:3.24.21-1
```

**Comment by abderrahim** [comment]
The bug is here:
```
            int monitorWidth  = Display.PrimaryMonitor.Geometry.Width  * Display.PrimaryMonitor.ScaleFactor;
            int monitorHeight = Display.PrimaryMonitor.Geometry.Height * Display.PrimaryMonitor.ScaleFactor;
```

`Display.PrimaryMonitor` can be null according to [the documentation](https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-primary-monitor), but the code doesn't check for it. In my tests, it is null when running under wayland.

**Comment by Thog** [comment]
As a note: If we fix that, it's possible the OpenGL context creation will not work when starting a game because our version of OpenTK doesn't handle Wayland

**Comment by abderrahim** [comment]
Which I would expect to look like #1333

**Comment by abderrahim** [comment]
Forgot to add: the workaround is to force using the X11 backend: 

`GDK_BACKEND=x11 ./Ryujinx`

**Comment by potatoeggy** [comment]
That solved it, thanks!

**Comment by kevincox** [comment]
It seems that this wasn't actually resolved. Forcing the x11 backend via environment variable seems like a workaround. At the very least the app should do that automatically.

**Comment by bpavuk** [comment]
> It seems that this wasn't actually resolved. Forcing the x11 backend via environment variable seems like a workaround. At the very least the app should do that automatically.

What about Ryujinx read its logs and launched with x11 mode if it found "00:00:00.005 |W| Application GetActualScaleFactor: Couldn't determine monitor DPI: Wayland not yet supported"? It could be nice built-in workaround 'til Wayland will be supported by Ryujinx
