### ISSUE TITLE
[Linux] Adding Game Filepath Causes Error

### ISSUE THREAD

**Issue by psppwner300** [Ryujinx/Ryujinx#1396]
Getting this after adding a path to my Switch game dump file path:
![error](https://user-images.githubusercontent.com/12868939/87812136-bdb41280-c82d-11ea-81d9-1b7cc9ba3f72.png)

I have dumped both Paper Mario and Smash Ultimate with `nxdumptool` as .nsp files. Checking the latest log on Ryujinx, this is the output:
`00:00:00.016 | Application Main: Ryujinx Version: 1.0.4952
00:00:00.040 | Application Main: Operating System: Linux 5.4.0-7634-generic #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC  (X64)
00:00:00.040 | Application Main: CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
00:00:00.040 | Application Main: Total RAM: 23966 MB
00:00:10.879 | GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. Errored File: /home/cowkiller/Desktop/switch_backup/games/Super Smash Bros. Ultimate v0 (01006A800016E000) (BASE).nsp
00:00:10.887 | GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. Errored File: /home/cowkiller/Desktop/switch_backup/games/Paper Mario_ The Origami King v0 (0100A3900C3E2000) (BASE).nsp`

I'm running `nxdumptool` in applet mode, and my settings are as follows:
Split output dump: No
Verify dump: No
Remove console specific data: No
Change NPDM RSA key/sig in Program NCA: Yes

Up-to-date `prod.keys`, `console.keys` and `title.keys` are in `~/.config/Ryujinx/system`, and firmware 10.0.1.0 is installed. Trying to run either of the games directly results in a black screen, even after waiting the normal two or three minutes for the game to load. Any ideas?

**Comment by AcK77** [comment]
In NxDumpTool you should turn on « Remove console specific data », « Generate ticket-less dump » and « Change NPDM RSA key/sig in Program NCA » and dump again.
It’s not related to linux or something, you just made a wrong dump.
Feel free to post any new informations here.

**Comment by psppwner300** [comment]
Okay, I re-dumped using the settings you mentioned and can confirm I can get Paper Mario to run. Thank you!
