### ISSUE TITLE
Animal Crossing: New Horizons Don't Start

### ISSUE THREAD

**Issue by CloudySky34** [Ryujinx/Ryujinx#1412]
Hello, i don't know if it is an issue due to my specs' or due to something else but i am having an error. Whenever i try to start **Animal Crossing New Horizons**, it don't start but some stuff like this appear in the console

![bandicam 2020-07-21 23-45-43-461](https://user-images.githubusercontent.com/67684302/88094106-7078cd80-cbac-11ea-8400-f3b37e965446.jpg)

If i don't have complete specs or it's an error, please reply the required specs

**Comment by MelonSpeedruns** [comment]
Your PC is not good enough to use Ryujinx. You don't seem to have enough RAM.

**Comment by AcK77** [comment]
For support and technical issues please go to our discord (https://discord.gg/N2FmfVc).
This is for development related issues. Thanks.

**Comment by Leischii** [comment]
You are also using an outdate build of the emulator. The seperate AC builds are no longer needed. Download the latest version from the Ryujinx Website. Might not fix it but has way higher chances.
