### ISSUE TITLE
Lumo: Broken graphics after a couple of minutes in-game

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1417]
EDIT: currently on 1.0.6455, this issue has been subdued somewhat, with the blue/invalid looking textures occurring only on boxes now.
![2021-01-29 16_47_31-Ryujinx 1 0 6455 - Lumo v1 0 0 (0100FF00042EE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106338767-e2178f80-6251-11eb-9685-ad03a575a6fe.png)
![2021-01-29 16_48_31-Ryujinx 1 0 6455 - Lumo v1 0 0 (0100FF00042EE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106338782-ecd22480-6251-11eb-8171-4e7b79e04a8b.png)

**Comment by EmulationFanatic** [comment]
This issue has been subdued somewhat, with the blue/invalid looking textures occurring only on boxes now.
![2021-01-29 16_47_31-Ryujinx 1 0 6455 - Lumo v1 0 0 (0100FF00042EE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106338767-e2178f80-6251-11eb-9685-ad03a575a6fe.png)
![2021-01-29 16_48_31-Ryujinx 1 0 6455 - Lumo v1 0 0 (0100FF00042EE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106338782-ecd22480-6251-11eb-8171-4e7b79e04a8b.png)

**Comment by EmulationFanatic** [comment]
> Appears to be fixed in 1.1.24. ![unknown](https://user-images.githubusercontent.com/79612681/153529340-323abfbd-0fc0-4efa-963c-7c4ed3c1207f.png)

How long did you test for? In previous examples it could take up to 30-40 minutes before finally exhibiting the bug.

**Comment by edisionnano** [comment]
> > Appears to be fixed in 1.1.24. ![unknown](https://user-images.githubusercontent.com/79612681/153529340-323abfbd-0fc0-4efa-963c-7c4ed3c1207f.png)
> 
> How long did you test for? In previous examples it could take up to 30-40 minutes before finally exhibiting the bug.

A bit more than 20 minutes

**Comment by EmulationFanatic** [comment]
> > 
> > How long did you test for? In previous examples it could take up to 30-40 minutes before finally exhibiting the bug.
> 
> A bit more than 20 minutes

I would reopen for now until someone with NVIDIA on Windows plays for >1 hour without seeing any corruption.

**Comment by EmulationFanatic** [comment]
Okay, I just played through for about an hour and did not see any corruption in rooms or between rooms during transitions. It's fixed!
