### ISSUE TITLE
Games render in a small window mode

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#1421]
every game that i load starts off in a small windowed mode
so i have to change it to full screen then get out of that for it to be normal again
using 1.0.5000 
using Radeon RX 580 with latest drivers 20.7.2
![windows](https://user-images.githubusercontent.com/2696404/88368869-77c4f480-cdc1-11ea-8f21-fd7ab7cab161.PNG)

**Comment by AcK77** [comment]
Could you provide a log file please ?

**Comment by benderscruffy** [comment]
[Ryujinx_2020-07-25_15-35-21.zip](https://github.com/Ryujinx/Ryujinx/files/4975048/Ryujinx_2020-07-25_15-35-21.zip)

**Comment by benderscruffy** [comment]
has been fixed
