### ISSUE TITLE
Super Mario Bros. U Deluxe: Shaders don't work when I go underground

### ISSUE THREAD

**Issue by Charmalow** [Ryujinx/Ryujinx#1435]
Hello, 
I hope you can help me solve this situation. The game itself runs perfectly smooth, the only thing I can't solve is the shader thing. I explain, when I go underneath the ground to get some more coins for example, there is normaly a circle giving me more vision to see through textures to keep going. Using the latest ryujinx build with the 8.1.1 firmware, I can't get this circle, it means that i'm blind in some parts of the game, not able to see through some textures.
Can you help a student who loves ryujinx and mario please ?
Charmalow.

**Comment by AcK77** [comment]
Any logs file? Screenshots?
You should goes to our discord for support !

**Comment by benderscruffy** [comment]
can this be closed as no support from original poster

**Comment by GamerzHell9137** [comment]
Not an issue anymore. Can be closed.
