### ISSUE TITLE
fsp-srv IFileSystemProxy: 71 (ReadSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1441]
fsp-srv IFileSystemProxy: 71 (ReadSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Filesystem_services#fsp-srv) | [SwIPC](https://reswitched.github.io/SwIPC/ifaces.html#nn::fssrv::sf::IFileSystemProxy)

## Service description:
```

```

## Required by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/250

**Comment by Thog** [comment]
Closed by #1443
