### ISSUE TITLE
Local multiplayer doesn't work in Mario Tennis Aces

### ISSUE THREAD

**Issue by artik** [Ryujinx/Ryujinx#1448]
I tried various configurations (both controllers in joycon mode, both in pro controller mode...) But I can't make it.

Local multiplayer game menu loads, I select 2 local players, it loads the caracters selection screen, but 2nd player is set as "com" and impossible to make a selection with the second controller to activate the second player selection.

I tried other games, and they work with my 2 controller.

https://i.imgur.com/Z7sMSci.png

Using the latest 1.0.5123 version

**Comment by EmulationFanatic** [comment]
I was able to replicate this issue. Even tried the MK8D trick using P2 controller to press L+R first. 
In one case the game crashed while attempting to get this working, with ```error applet not found```
