### ISSUE TITLE
Add Feature -  Add support for the audio input service to allow microphones to work

### ISSUE THREAD

**Issue by jobisingh** [Ryujinx/Ryujinx#1455]
I would like to request that USB device pass through for non-controller devices be added. Specifically for microphones and headsets. This may sound like a strange request to some, but it arises from my desire to be able to play "Lets Sing 2019". It requires a microphone, either connected via USB, or WiFi. I feel adding WiFi capabilities would be a much more difficult solution.

**Comment by BeckysFootSlave** [comment]
Yes please!

**Comment by TheChatty** [comment]
Even better would be a [UAC](https://www.google.com/search?q=%22USB+Audio+Class%22) emulation. It's probably not a good idea if an emulated system operates a time-critical device.

**Comment by gdkchan** [comment]
I'm not sure if games get access to USB devices directly. If the game is using microphone, it is probably through `audin` and the OS service handles actually interfacing with the microphone that is connected to the system.

**Comment by TheChatty** [comment]
Let's Sing is actually talking about "Connect up to two USB microphones" and it detects neither my Mac's built-in microphone nor my external USB soundcard.

**Comment by gdkchan** [comment]
The emulator does not implement the `audin` service right now, so it won't detect any microphone. But I think the actual inteded feature request here is "Add support for the audio input service to allow microphones to work" rather than "USB pass through".

**Comment by TheChatty** [comment]
You're right. Then @jobisingh should change the title, please.

**Comment by jobisingh** [comment]
> You're right. Then @jobisingh should change the title, please.

Yall really asking me to update of a 3 year old feature request. I mean I'll do it, but its still really funny.

**Comment by jobisingh** [comment]
Did not mean to close it there, github mobile is wacky.

**Comment by AcK77** [comment]
superseeded by #4254
