### ISSUE TITLE
Intrinsics & ConstantRegCopy

### ISSUE THREAD

**Issue by FICTURE7** [Ryujinx/Ryujinx#1457]
Currently the PreAllocator does not handle constant operands on intrinsics and this can be problematic when optimizations are applied. I ran into this by forcing HCQ in the Translator and running the tests, some of the CRC32 tests fails.

Here is a repro.
```csharp
public static void Test()
{
  static ControlFlowGraph GetCFG()
  {
    var emitter = new EmitterContext();

    var op0 = emitter.Copy(Const(0L)); // These gets copy propagated into their use in HCQ. i.e, res.
    var op1 = emitter.Copy(Const(0L));

    var res = emitter.AddIntrinsicLong(Intrinsic.X86Crc32, op0, op1);

    emitter.Return(res);

    return emitter.GetControlFlowGraph();
  }

  var cfg0 = GetCFG();
  var cfg1 = GetCFG();

  var argTypes = new OperandType[] { OperandType.I64 };
  var retType  = OperandType.I64;

  Compiler.Compile<GuestFunction>(cfg0, argTypes, retType, CompilerOptions.None);   // Ok
  Compiler.Compile<GuestFunction>(cfg1, argTypes, retType, CompilerOptions.HighCq); // Fail
}
```

If we get unlucky, the 1st operand becomes a constant and the instruction is silently incorrectly encoded when the 2nd operand is a register (asserts fires in Debug builds). If the 2nd operand becomes a constant an exception in the Assembler is thrown.

I believe most use of intrinsics in the code do not run into this issue because they work on V128 which cannot be constants. Or work on I32/64/FP32/64 which have been extracted from a V128 and so these also cannot be constants.

**Comment by gdkchan** [comment]
Most of the other intrinsic instructions that were implemented work on XMM registers so they don't have this issue (in fact I think CRC32 is the only one that doesn't right now). I think it should be handled on the pre-allocator aswell by inserting copies. Nice catch.
