### ISSUE TITLE
requesting accessibility in the main UI

### ISSUE THREAD

**Issue by Gamulation** [Ryujinx/Ryujinx#1459]
Hi. I am Gamulation. I am a blind user and rely on a screen reader to use a computer and a phone.
I am always looking into emulators and loves to play games.
What I noticed about ryujinx is that the main interface is completly in accessible. What I mean about this is that my screen reader isn't able to read anything. When I open the emulator I hear the emulator name and version, but that's it. I can't use a mouse and can't do anything in this UI.
I am using NVDA screen reader.
Can I ask: What interface was it made with? QT?
Other emulators have shortcuts for navigating the UI. The alt menu is a great example of this, and would be very good here.
In this way you can interact with the UI in a accessible way, but we can't do that without speach. For instance. The RPCS3 emulator has an alt menu, and when I press alt on my keyboard, my screen reader anounces the menu item. For instance file. Then I can use the errows to move around the menu, and the screen reader folows. I hope that this issue  get's resolved quickly, so that all players have a fair chanse to try out this amazing emulator.
let's all play equally
to find the NVDA screen reader go to: https://www.nvaccess.org/

**Comment by Gamulation** [comment]
Hi.
I am just wondering if this has gotten any better? I still can't use Ryujinx, is this beeing worked on?

**Comment by CartridgeSoft** [comment]
Yea, i have the same question. I can't use this emulator without accessibility, and use OCR to navigate arround him is very frustrating

**Comment by twilightsophie** [comment]
Since this is a year later I'm not sure if it will be helpful but Yuzu has menus that use the ALT key and then all the menu options have a letter underlined to quick jump to them. I didn't find Ryujinx until recently and it's great for Miis for Miitopia and Amiibos being easy to select but I find myself (as a sighted user) defaulting back to Yuzu because it's easier to use keyboard shortcuts for menu items (like fullscreen??).

**Comment by MutantAura** [comment]
#2507 may solve this? 

May be worth testing :)

**Comment by AcK77** [comment]
Superseeded by #4352
