### ISSUE TITLE
(Question) Create a single project for Ryujinx.Graphics?

### ISSUE THREAD

**Issue by Laxes** [Ryujinx/Ryujinx#1463]
I did notice that there are, at the moment, 12 .csproj files for the Ryujinx.Graphics.XXX namespace.
Is there a specific reason for this? Most projects that I have seen or worked on would in this case just create a single .csproj file (Ryujinx.Graphics) with a separate sub directory for the .XXX namespace.

**Comment by AcK77** [comment]
This is for development issues.
Please come to our discord server for questions (https://discord.gg/N2FmfVc).
Thanks.

**Comment by gdkchan** [comment]
The main goal is separating things that are useful on their own. This like shader decompilation (`Ryujinx.Graphics.Shader`) and texture decoding (`Ryujinx.Graphics.Texture`) are useful for stand-alone tools aswell, and might be useful for other projects. Separating them like that allows other projects to use them without bringing in the entire GPU emulation project + a lot of things it does not need. `Ryujinx.ShaderTools` currently makes use of `Ryujinx.Graphics.Shader` for example, it is a stand-alone shader decompilation tool.
