### ISSUE TITLE
Hatsune Miku: Project DIVA Mega Mix: Animations play faster than they should

### ISSUE THREAD

**Issue by ActualMandM** [Ryujinx/Ryujinx#1496]
### What's the issue you encountered?

The animations for music videos in Mega Mix play faster than they should compared to hardware. Some songs have it worse than others.

https://github.com/Ryujinx/Ryujinx-Games-List/issues/237

### How can the issue be reproduced?

Play a song in music video/PV mode.

### Log file

[Ryujinx_2020-08-22_12-11-08.zip](https://github.com/Ryujinx/Ryujinx/files/5112835/Ryujinx_2020-08-22_12-11-08.zip)

### Environment?

- Ryujinx version: 1.0.5191
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 3950X
  - GPU: NVIDIA RTX 2080
  - RAM: 32GB
- Applied Mods: No

### Additional context?

[Footage comparing the speed between Ryujinx and Switch](https://streamable.com/3501c4)

**Comment by slashiee** [comment]
I've checked, it happens with Vsync enabled and disabled. It's worse with it disabled though
<img width="641" alt="2020-08-23_15-31-02" src="https://user-images.githubusercontent.com/15317421/90990365-c34ff700-e555-11ea-806d-4f8f40da33ab.png">

**Comment by ActualMandM** [comment]
Issue no longer happens as of 1.0.6369, unsure what exactly fixed it. Closing.
<img width="641" alt="2021-01-19_18-53-49_Ryujinx" src="https://user-images.githubusercontent.com/15317421/105120755-afb6a700-5a87-11eb-9a55-83d46c96eab6.png">
