### ISSUE TITLE
Mario Kart 8 Deluxe: Softlocks on Controller Applet invoke

### ISSUE THREAD

**Issue by mageven** [Ryujinx/Ryujinx#1499]
## Bug Report

Mario Kart 8 Deluxe softlocks on any Controller Applet invoke. Bug exists pre and post #1453.

### What's the issue you encountered?

Any time the game invokes Controller applet, it softlocks. This manifests as a total or partial screen freeze depending on game UI elements. Game FPS does not go to 0 (during applet and after locking).

Also seems to freeze before the applet returns. This can be tested by triggering a controller applet dialog. The game stops working even before closing the dialog.

### How can the issue be reproduced?

There are many ways to trigger controller applet. The following list is a small subset (while docked).

1. After splash screen (i.e., after pressing L+R), disconnect/change the primary controller.
2. Press L+R with Player3 or Player4 controller (on splash screen). [strange that this triggers applet]
3. After pressing L+R with Player1 (on splash screen), arrive at kart customization (in split-screen multiplayer). [most frequently encountered by users]
4. After pressing L+R with Player2 (on splash screen), but press -/+ during kart customization (in split-screen multiplayer).

### Environment

Bug doesn't seem to depend on environment. Multiple users with various hardware have reported the same.

### Additional context

AFAIK, MK8D is the only game affected.

**Workaround:** A workaround exists for this issue. You can avoid triggering the controller applet by pressing L+R (at splash screen) with Player2's controller (while docked).
You don't have to restart the game if entered incorrectly. Going back to splash screen and following the above still prevents softlocks.

**Comment by AcK77** [comment]
Fixed in #2218
