### ISSUE TITLE
Add an option to hide mouse cursor on inactivity

### ISSUE THREAD

**Issue by Banz99** [Ryujinx/Ryujinx#1508]
Having the mouse cursor showing up on the screen at all times can be a bit annoying. Is it possible to add an option to make it invisible when the mouse hasn't been moved for X seconds?

**Comment by EmulationFanatic** [comment]
I second this motion.

**Comment by mhvuze** [comment]
+1 from me. This would be a great QoL enhancement, especially when playing in full screen.
