### ISSUE TITLE
 Add an option to go in/out fullscreen when double clicking game window

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#1509]
The only way to fullscreen right now is to ALT+RE-ENTER but it would be great to be able to get in and out of fullscreen by double clicking the game window. PPSSPP is one of the emulators that has the option.

**Comment by LeDragoX** [comment]
The **F11** button also works too.

**Comment by emmauss** [comment]
Do you mean the game screen, where the game is rendered? The switch is a touch screen device, and some games use the touch screen. triggering touch screen by double clicking could make the game go fullscreen unexpectedly, esp when the game being played require double taps to play.

**Comment by GamerzHell9137** [comment]
Ahh yes, guess FS that way wouldn't work.

**Comment by EmulationFanatic** [comment]
Closing as this is not possible due to double taps being used in some games.

**Comment by GamerzHell9137** [comment]
> 
> 
> Closing as this is not possible due to double taps being used in some games.

It could be possible if only a specific area triggers fullscreen when double clicked.
Like top right corner 
![image](https://user-images.githubusercontent.com/2002038/101176876-67623780-3647-11eb-85ef-dd5618430f03.png)
