### ISSUE TITLE
The Legend of Zelda : Link's Awakening: Runs too fast, about 1.5x times than original

### ISSUE THREAD

**Issue by BennyAlex** [Ryujinx/Ryujinx#1510]
### What's the issue you encountered?

Links Awakening runs to fast, about 1.5x times than original.

### How can the issue be reproduced?

I run the game with multicore and in docked mode.

### Environment?

- Ryujinx version: 1.0.5239</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-9900k
  - GPU: NVIDIA GTX 1080 TI
  - RAM: 32GB
- Applied Mods : no depth of field

**Comment by EmulationFanatic** [comment]
Did you disable vsync?

**Comment by Ghostotakoi** [comment]
@BennyAlex press TAB and watch the magic happen
