### ISSUE TITLE
Allow matchmaking over a local network, without an internet connection

### ISSUE THREAD

**Issue by Ghostotakoi** [Ryujinx/Ryujinx#1512]
### What feature are you suggesting?

I will love to have some kind of REAL local Multiplayer sever over LAN instead of WAN. Me and my little brother live in the same house and we have a LAN network and we use to play a lot of games using it, mostly because our ISP is pretty bad.

#### Overview:

Add an embedded server on the emulator itself that can handle online connections but also LAN connections or direct IP connections, similar of what Citra has. Example below.

![ScreenShot_20200828220123](https://user-images.githubusercontent.com/20958581/91626289-b8dd9500-e97b-11ea-833a-3009f884f2cd.png)

![ScreenShot_20200828220420](https://user-images.githubusercontent.com/20958581/91626252-643a1a00-e97b-11ea-9ff4-4bfb1995c399.png)

![ScreenShot_20200828220458](https://user-images.githubusercontent.com/20958581/91626253-656b4700-e97b-11ea-8798-18e77e706666.png)

#### Smaller Details: 
- Would be also nice to add some kind of Ping or connection indicator maybe on ms (Latency) and/or bars. Example below (Made in photoshop)

![ScreenShot_20200829190014](https://user-images.githubusercontent.com/20958581/91647856-f995e680-ea2d-11ea-93f8-d07b1f73fbee.png)

#### Nature of Request:  
- Addition

### Why would this feature be useful?
I think this feature will be very useful for people (Like me) with limited or slow internet access.

**Comment by jduncanator** [comment]
Thanks! We'll take it on board when we continue to develop the LDN implementation :)

**Comment by MetrosexualGarbodor** [comment]
This is now implemented to the main build of the emulator with "enable guest internet access", which allows playing games that support LAN mode on a local network. Closing this as a result. 

However it's worth noting that there's no ping indicator in the UI yet. That would be a valid new feature request.
