### ISSUE TITLE
Requesting supports Action-Replay style cheat codes

### ISSUE THREAD

**Issue by FengYuu** [Ryujinx/Ryujinx#1513]
#### Overview:
- A few months ago，Ryujinx implement modding support，It follows Atmosphère's structure，support romfs and exefs files.
So is it possible to increase the cheat code function according to the file structure of the Atmosphère?

#### Smaller Details: 
- Unkown

#### Nature of Request:  
- Addition
  - https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/cheats.md

### Why would this feature be useful?
When I play MHGU, 60 fps and 30 fps are almost different levels of game experience, but the method of unlocking the frame limit of this game can only be achieved by using cheat codes.
Requesting this support may bring players a more free gaming experience:）

**Comment by perkel666** [comment]
Would love to see such feature ! Few decent games have 60fps mods done this way.

**Comment by GamerzHell9137** [comment]
This and mod menu like the other menus you can enable/disable.

**Comment by RavenMacDaddy** [comment]
Another good example is the 60 FPS cheat for Kirby: Star Allies which is sadly not possible in Ryujinx at the moment.

**Comment by AcK77** [comment]
You can try #1928 build if you want.

**Comment by AcK77** [comment]
Fixed in #1928
