### ISSUE TITLE
WiFi play menu crashes

### ISSUE THREAD

**Issue by FabioSedia** [Ryujinx/Ryujinx#1514]
### What's the issue you encountered?

When I try to access the wireless play menu on both mk8d and ssbu Ryujinx freezes and then crashes</br>

### How can the issue be reproduced?
Don't know, I just booted ryujinx ldn patreon version and got this issue

### Log file

Here's the relevant log (looks like a permission denied issue)
00:02:13.498 |E| Application : Unhandled exception caught: System.Net.Sockets.SocketException (13): Permission denied

### Environment?

- Ryujinx version: 1.0.0-ldn1</br>

- Game version: 1.7.1</br>

- System Specs:
  - OS: Arch Linux kernel 5.8 
  - CPU: Ryzen 5 2400G
  - GPU: RX 570 8GB
  - RAM: 8GB
- Applied Mods : No

**Comment by AcK77** [comment]
What about your firewall? If the socket request is rejected it’s probably because your firewall block it!
You should come to our Discord for more support.

**Comment by FabioSedia** [comment]
I came on discord, and I don't think I have any kind of firewall but I'll check. Rip peri peri said it's due to TCP_NODELAY requiring permissions on linux or something and he'll have a workaround next version... Let's hope it works. Will check the firewall settings anyway 😃

**Comment by FabioSedia** [comment]
> What about your firewall? If the socket request is rejected it’s probably because your firewall block it!
> You should come to our Discord for more support.
I came on discord, and I don't think I have any kind of firewall but I'll check. Rip peri peri said it's due to TCP_NODELAY requiring permissions on linux or something and he'll have a workaround next version... Let's hope it works. Will check the firewall settings anyway 😃

**Comment by FabioSedia** [comment]
> What about your firewall? If the socket request is rejected it’s probably because your firewall block it!
> You should come to our Discord for more support
Rip in Peri peri said it's due to TCP_NODELAY requiring permissions on linux or something

**Comment by EmulationFanatic** [comment]
This was resolved in newer versions of LDN.
