### ISSUE TITLE
It's too hard for me to use this Emulator

### ISSUE THREAD

**Issue by EndlessMISAKA** [Ryujinx/Ryujinx#1516]
## Feature Request

Could you write an useful manual?
I mean it can include some pictures to show what should I do, and include some advices when it was error.
Do you know how much time I had cost for found the Firmware and Keys?
Do you know what I thought when error occurred after install the Firmware and Keys?
I feel so sad, and regret why I want to use this emulator.

**Comment by AcK77** [comment]
Just looks at https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide and it will be easier to use ;)

**Comment by Ghostotakoi** [comment]
@EndlessMISAKA your firmware and keys should not be found, you should dump them from your ACTUAL Nintendo Switch.
