### ISSUE TITLE
Undertale: FPS drops to 0.05FPS in the laboratory level

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1524]
### What's the issue you encountered?

Undertale (any version): walk into the laboratory and FPS drops to about 1 frame every 10 seconds.

### How can the issue be reproduced?

Walk right to the laboratory and enter it (save file included here):
[undertale.save.zip](https://github.com/Ryujinx/Ryujinx/files/5156006/undertale.save.zip)

### Log file

[Undertale.log](https://github.com/Ryujinx/Ryujinx/files/5156017/Undertale.log)

### Environment?

- Ryujinx version: 1.0.5266</br>
- Game version: 1.09</br>

- System Specs:
  - OS: Windows 10 2004
  - CPU: i5-6600K
  - GPU: NVIDIA GTX 1080
  - RAM: 16GB
- Applied Mods : [ No ]

### Additional context?

Here is a video showing the issue:
https://streamable.com/srw2jk

**Comment by riperiperi** [comment]
There's a screen in this area that is meant to display the region around the player's head. The performance drop might be related.

**Comment by gdkchan** [comment]
Fixed by #2926.
