### ISSUE TITLE
Feature request: Razer Hydra controllers support

### ISSUE THREAD

**Issue by r57zone** [Ryujinx/Ryujinx#1532]
Hi, it would be great to add Razer Hydra controllers support. They are very similar to joycons. Their API gives calibrated quaternions. Thanks.

Latest SDK - https://github.com/r57zone/Razer-Hydra-SteamVR-driver/releases/download/1/SixenseSDK_102215.zip
Razer Hydra C# headers https://github.com/n1ckfg/HydraUnity/blob/master/Assets/Sixense/Plugins/SixensePlugin.cs
Sample in C++ https://github.com/yuzu-emu/yuzu/issues/4109

**Comment by Thog** [comment]
As of https://github.com/Ryujinx/Ryujinx/pull/2194, we use SDL2 for inputs and therefore support Razer Hydra thanks to it.a

**Comment by r57zone** [comment]
Gamepad without gyro? The Razer Hydra has very accurate gyroscopes, no drift that give a quaternion, they can mimic full-fledged JoyCons.
