### ISSUE TITLE
CPU JIT performance enhancement and code size reduction with more efficient memory access using multiple registers

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#1540]
## Feature Request

Introduce `LoadMany`/`StoreMany` IR instructions on the CPU JIT, or improve memory access using existing instructions (see "alternative implementation" on the section below).

#### Overview:

Arm32 has the `LDM` and `STM` instruction that can be used to load memory contents and write them to multiple registers, or store the contents from multiple registers in memory, respectively. This was removed on Arm64, but it has `LDP` and `STP` that can be used to load or store a pair of registers.

Right now, all those instruction will produce *multilple memory accesses*, which means that it will do *software address translation* using the *guest page table* for each register involved on the operation. This will result in a lots of host instructions, large code size and poor performance.

The solution: `LoadMany` and `StoreMany` can load/store all the registers for `LDM`, `STM`, `LDP` and `STP` doing a single lookup on the *guest page table*, a single *software address translation* and a single *validation of the address*, this results in a greatly reduced amount of host instruction, and increased performance as fewer operations needs to be done for the memory access.

On top of that, it is also possible to optimize sequences of `LDP` or `STP` with sequential addresses to behave like `LDM`/`STM`, this would result in similar improvements on Arm64 as those seem on Arm32. Of course, care would need to be taken to preserve the behavior of each individual instruction (for example, some might do a pre or post-increment or decrement of the address).

Alternative implementation: It is possible to still have most of those improvements without introducing new IR instructions, by simply doing a single address translation, and then using multiple `Load` and `Store` instructions. This produces more instructions, but would be simpler to implement with slightly worse throughput. Performance should be the same in theory.

#### Smaller Details:

One possible concern is a increased number of jumps to the fallback path. This would happen because, right now, it calls the slow fallback functions when the address is not aligned to the size of the data being accessed. With a `LoadMany` and `StoreMany` approach, the size of the data being accessed would be potentially much larger as we are talking of multiple register, so it has greater likelyhood of being not aligned, and call the slow path. The purpose of the alignment check is checking if the access might cross a page boundary. It might be necessary to use a new validation mechanism that only calls the slow path when the access actually crosses a page boundary.

Another potential issue is that the JIT is not prepared to handle a IR instruction with multiple destination operands. This is somewhat supported as it is required by some x86 instructions with multiple outputs, but anything before register allocation is not prepared to handle it yet. It is required by the `LoadMany` IR instruction, that will do multiple assignments. I don't think supporting it would be too complicated, but it is one thing to keep in mind. It is worth noting that supporting this would also help 128-bit `CompareAndSwap`, right now it needs to insert and extract the data into a XMM register just because there's no way to have a instruction with 2 outputs right now. Allowing that would enable us to implement a proper 128-bit CAS instruction that outputs to 2 registers, and improve the codegen.

It might be also worth to limit the amount of operands that `LoadMany` and `StoreMany` may have to avoid choking the register allocation. A large number of live registers on a single instruction is not very good.

#### Nature of Request:

Performance improvement.

### Why would this feature be useful?

This improves performance, throughput and reduces JIT code size. By how much is hard to estimate, it depends on the frequency of the load/store multiple instructions. I know that for both Arm32 and Arm64, they are always used on the function prolog and epilog (assuming that it needs to save and restore more than one register, which is often the case). So I think this would benefit most complex guest functions.

**Comment by FICTURE7** [comment]
Another alternative perhaps might be to do something similar to what we do with registers. We could initially emit `Load` and `Store` as the guest code does it, then have a pass (like `RegisterUsage`) which expands/modify these `Load` and `Store` to interact with the host memory manager. In the same pass we could attempt to figure out if a set/sequence of loads and stores might occur on the same page.

The pros is that it simplifies instruction emission in the frontend somewhat, the caveats is that it introduces a new pass and the analysis might be non-trivial.

**Comment by jduncanator** [comment]
> We could initially emit Load and Store as the guest code does it, then have a pass (like RegisterUsage) which expands/modify these Load and Store to interact with the host memory manager.

This was the line of thought that initially stood out to me. I'm not sure what impact an additional pass might have on translation performance, nor, as FICTURE7 states, how non-trivial the analysis might be, but it seems like the right compromise between both of the suggested approaches in the OP.

**Comment by riperiperi** [comment]
The common use case for these instructions is reading from and moving the stack pointer. I don't think we'll be able to make any decisions about page boundaries at compilation time.

**Comment by FICTURE7** [comment]
Certainly, most of the time, we won't be able to prove with absolute confidence that a set of load/store will occur on the same page. We would need to prove the upper bits of the guest addresses are the same. However we can optimistically assume that they will, depending on their access spatial locality. e.g

```wasm
i64 r2 = Load i64 r1
i64 %1 = Add i64 r1, i64 0x8
i64 r3 = Load i64 %1
```

Chances are both of these loads lie on the same page. This of course will still require the runtime alignment check or a more relaxed cross page boundary check as suggested above, to fallback to the slow path. Unless I missed something here.

**Comment by riperiperi** [comment]
I think to analyze these, we'd need accesses to guest memory to be their own IR instruction (VirtualLoad/VirtualStore or something), with translation, write tracking and fallback built in, or emitted as part of said future pass. Then we have two options for the output code:

- VirtualLoad/VirtualStore emits the address translation as IR (an IR instruction that generates IR). This would be backend agnostic and end up costing the same as our current approach in the case where memory instructions are not combined.
- VirtualLoad/VirtualStore emits in the backend. This could remove most the JIT cost for processing memory (which is about 2/3rds of JIT time in MK8 from my testing) but would also be insanely complicated for one IR instruction.

**Comment by gdkchan** [comment]
It should be possible to do this optimization without needing those special instructions. The output from the decoder stage is already a control flow graph with enough information about the instruction to perform the optimization. The typical Arm64 function prolog looks like this:
```
sub sp, sp, #0xb0
stp x24, x23, [sp, #0x70]
stp x22, x21, [sp, #0x80]
stp x20, x19, [sp, #0x90]
stp x29, x30, [sp, #0xa0]
```
One can detect that the base register is the same for all the stores (SP), and the offset is incrementing by the store size (16 bytes), therefore this sequence could be just one large sequential store of 8 registers. Of course, doing the optimization this way would have some limitations and would probably catch less cases than a potential dedicated pass later on, but I think it's doable.

That said, I do prefer a cleaner approach, potentially one that  does this optimization later on as a separate pass.

Also, thinking a bit more about this idea, I think it would be also worth to expose new methods on `NativeInterface` to allow sequential load/store, which would look like this:
```cs
void ReadMany32(ulong baseAddress, IntPtr dest, int stride, uint registerMask);
void ReadMany64(ulong baseAddress, IntPtr dest, int stride, uint registerMask);
void ReadMany128(ulong baseAddress, IntPtr dest, int stride, uint registerMask);
void WriteMany32(ulong baseAddress, IntPtr src, int stride, uint registerMask);
void WriteMany64(ulong baseAddress, IntPtr src, int stride, uint registerMask);
void WriteMany128(ulong baseAddress, IntPtr src, int stride, uint registerMask);
```
`baseAddress` is the virtual address where the read/write will happen.
`dest` is a pointer to the first register, where the value being read is written to on the `NativeContext` struct. It should point to X0 or V0.
`src` is the same as `dest`, but it is read from instead of written to.
`stride` is the distance in bytes between each register value. Should be 8 bytes or 16 bytes.
`registerMask` is a 32-bits bitmask, where each bit N set indicates that the respective register N should be read/written.

Sequential `Load` instructions would call the respective `Read` functions, and then read each respective register value from the `NativeContext`, while sequential `Store` instructions would write the register values to the `NativeContext` and then call the respective `Write` function.

For sequential access, the above approach would improve the slow path, by greatly reducing the amount of calls to only one.

**Comment by FICTURE7** [comment]
I slapped together something similar to what is described in the "alternative implementation" FICTURE7@7c81f277f8c906c7e8142961e4e9867e823e98c4, seems to be quite promising. The idea is to allow instruction emitters to bundle load/stores together and have a memory emitter which handles the actual emission. Sample [diff](https://www.diffchecker.com/AEULnhuq) (I've only updated gpr `STP` to use the new stuff). We probably want to limit how much of load/store we want to bundle together, to reduce the chance of data being unaligned.

**Comment by gdkchan** [comment]
I will close this because since #2286 we compile most memory accesses to a single x86 instruction, so they would not benefit from this optimization. This mainly benefits the software memory manager mode which we don't use by default anymore.

**Comment by gdkchan** [comment]
That said, if someone is willing to do that, it's still welcome. It just won't have a significant benefit for most users anymore.
