### ISSUE TITLE
Feature Request: Menu option for log folder

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#1543]
A lot of the times when a log is necessary its a bit annoying to get to the folder where Ryujinx is located. An option like "Open Ryujinx Folder" called "Open Log Folder" in the File menu would be really appreciated and would improve the user experience.
![image](https://user-images.githubusercontent.com/2002038/92493034-5777ba80-f1f4-11ea-9eed-a03461da4e7e.png)

**Comment by qurious-pixel** [comment]
Ryujinx has this function.  Options > Settings > Logging > Open Logs Folder

![Ryujinx-Open_logs](https://user-images.githubusercontent.com/62252937/92667916-24036180-f2c2-11ea-9341-371c2f100521.png)
