### ISSUE TITLE
Pokémon Let's Go Eevee "Continue" Screen freezes

### ISSUE THREAD

**Issue by Colmines92** [Ryujinx/Ryujinx#1544]
## Bug Report

Pokémon Let's Go Eevee "Continue" Screen freezes

### What's the issue you encountered?

When I got to main menu, where the Continue and Options are, if I let the emulator load the player model, the image will freeze, but the game will still be working, you can hear everything that happens ingame, but screen is still at Main screen showing your main character. However, if I repeatedly start tapping 'A' button before the character loads, it loads my game correctly and I can play for a while with a lot of lags, but the same error occurs at some points in the game and the screen freezes again, while the game is still running.

### How can the issue be reproduced?

Just launch the game and get to the main menu, and let it load your character model.

### Log file

[Ryujinx_2020-09-11_13-03-29.log](https://github.com/Ryujinx/Ryujinx/files/5210981/Ryujinx_2020-09-11_13-03-29.log)

### Environment?

- Ryujinx version: 1.0.5306</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10)
  - CPU: i5-4640
  - GPU: Intel (R) HD Graphics 4600
  - RAM: 6 GB
- Applied Mods : No

**Comment by GamerzHell9137** [comment]
![image](https://user-images.githubusercontent.com/2002038/92965583-56ee5680-f476-11ea-8888-77785ed30f0c.png)
![image](https://user-images.githubusercontent.com/2002038/92965646-6ec5da80-f476-11ea-8c31-1b7228c30b43.png)

**Comment by AcK77** [comment]
This should be posted in https://github.com/Ryujinx/Ryujinx-Games-List/issues/115 since freezes are related to your specs.
