### ISSUE TITLE
[Feature Request] Lower the minimum window size

### ISSUE THREAD

**Issue by Colmines92** [Ryujinx/Ryujinx#1545]
#### Overview:
Lower the minimum window size, currently locked at 1280x720 (not the internal resolution, but the window size)

### Why would this feature be useful?
Specially for users using 1920x1080 monitors, and need to use one screen half for other things, using the windows 10 ability to dock the window, it maintains the screen size of 1280x720, however building a custom ryujinx and modifyng the minimum window size to something like 960x540 (1920x1080 / 2) I can dock it to one half of the screen and the game contents adjusts automatically maintaining its aspect ratio.

**Comment by phasermaniac83** [comment]
Yes please! 
This would be also useful to users who want to display Switch pixelart games in 15khz Crts

**Comment by HelmicNewciv** [comment]
This causes issues on older/cheaper televisions that need the OS to set an underscan to properly display stuff due to an inability to turn off the overscan on the TV itself, since it'll actually be somewhat smaller than true 720p, meaning games displayed on that television have a sliver of the bottom and right edges cut off.

**Comment by Heidar-An** [comment]
Hi there,
I'm new around here (and to open source in general), I'd be happy to work on this issue if I had a few pointers first (e.g., where to look etc)

**Comment by Heidar-An** [comment]
--ping ping

**Comment by JazzGlobal** [comment]
> Hi there,
> I'm new around here (and to open source in general), I'd be happy to work on this issue if I had a few pointers first (e.g., where to look etc)

New too but you can probably start by searching for key terms in the project after cloning. 

Perhaps performing a search for different resolution sizes?

**Comment by MutantAura** [comment]
Fixed in https://github.com/Ryujinx/Ryujinx/pull/6425
