### ISSUE TITLE
[Feature Request] Mod Manager

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#1566]
The only thing that doesn't have a manager now is mods so whenever you wanna disable something you need to either move it or delete it and put it back in if you wanna enable it.
Having an option to make it togleable like DLC and Updates would be nice.

**Comment by theboy181** [comment]
BUMP!

**Comment by jojodunet** [comment]
Devs please check this PR #3819, it completes the feature request

**Comment by edisionnano** [comment]
> Devs please check this PR #3819, it completes the feature request

That's an issue

**Comment by vesper8** [comment]
A mod manager like CEMU's that self-updates and auto-downloads mods for all games would be an incredible addition to Ryujinx! I hope this is added at some point.

**Comment by Linx-ESP** [comment]
Would be possible something like ignoring folders starting with a dot o hidden folders?

**Comment by GamerzHell9137** [comment]
Fixed by https://github.com/Ryujinx/Ryujinx/pull/4390
