### ISSUE TITLE
InvalidMemRange bug in game Hatsune Miku: Project DIVA Mega Mix/MEGA39's

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx#1567]
## Bug Report

I first reported this issue earlier this year and most recently @GamerzHell9137. Also reported on https://github.com/Ryujinx/Ryujinx-Games-List/issues/237#issuecomment-675453937, I'm afraid the dev may not notice any of the errors below. I'm not sure to call it a bug or not since it won't boot up.

### What's the issue you encountered?

I ran into this issue while booting the USA version with `Loader LoadNsos: Process initialization returned error "InvalidMemRange"` and if I added Update and Dlc I got the same error in both versions (USA / JPN). Now JPN base game. That can boot and play well I don't know what the problem is. Dev's Opinion Needed
I have tried changing several settings and trying to boot the game in all sorts of ways. But still no luck
It seems that older versions of Ryujinx have also had problems since version 1.0.432 or earlier.

### How can the issue be reproduced?

Just booting the base game USA version and all DLC / UPDATE will get the same error, including the JPN version of DLC / UPDATE.

### Log file

[Ryujinx_2020-09-22_13-25-41.log](https://github.com/Ryujinx/Ryujinx/files/5259485/Ryujinx_2020-09-22_13-25-41.log)

### Environment?

- Ryujinx version: 1.0.5398

- Game version: 1.0.0 Or later version

- System Specs:
  - OS: WINDOWS 10 PRO
  - CPU: INTEL I5 8400
  - GPU: GTX 1660 SUPER 6GB
  - RAM: KINGSTON DDR4 16GB
- Applied Mods : No 

### Screenshots : 

![bandicam 2020-09-22 13-27-35-768](https://user-images.githubusercontent.com/35269098/93850219-d6cabb00-fcd7-11ea-94c2-d57431540d99.jpg)

**Comment by jduncanator** [comment]
For bugs on specific games, they're best to be left on the games entry in the Game Compatibility list. This issue tracker is more for tracking generic emulator bugs that affect all/multiple games.
