### ISSUE TITLE
Unimplemented FCVTNS instruction

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx#1570]
### What CPU instruction is missing?

Requires the *FCVTNS* instruction.</br>

```
The instruction at 0x000000000aa6d684 (opcode 0x1e200148) is undefined!
```

### Instruction name
```
fcvtns w8, s10
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/2549

**Comment by benderscruffy** [comment]
can be closed by #2953
