### ISSUE TITLE
IFriendService: 10500 (GetProfileList) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1575]
### What service call is missing?

IFriendService: 10500 (GetProfileList) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Friend_services#IFriendService) | [SwIPC](https://reswitched.github.io/SwIPC/ifaces.html#nn::friends::detail::ipc::IFriendService(10500))

### Service description
```
(nn::account::Uid, buffer<nn::account::NetworkServiceAccountId, 9>) -> buffer<nn::friends::detail::ProfileImpl, 6>
```
### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/358
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1374
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2913
https://github.com/Ryujinx/Ryujinx-Games-List/issues/298

**Comment by benderscruffy** [comment]
@AcK77 
can you stub this aswell like #2896 ??
just wondering
