### ISSUE TITLE
Wrong compression error

### ISSUE THREAD

**Issue by Flocke28** [Ryujinx/Ryujinx#1583]
Since few releases some game won’t starts anymore. Error unsupported compression method..

Issue on [Twitter](https://twitter.com/brausepulver666/status/1307558089789505536?s=21)

**Comment by EmulationFanatic** [comment]
Please have this person come to our Discord server for support. This may be fixable without any modifications to Ryujinx.

**Comment by Flocke28** [comment]
Hi. I don’t use discord. May it possible to write here the solution?

**Comment by EmulationFanatic** [comment]
We need more information. What game(s) does this occur on? Have you tried purging the PPTC cache (right-click the game in the list > Cache Management > Purge PPTC cache) ?

**Comment by Th3d0nGsT3R** [comment]
Also what file format is the game in?

**Comment by Flocke28** [comment]
Purging the cache fixed the issue. Thanks
