### ISSUE TITLE
fsp-srv IFileSystemProxy:205 (OpenDataStorageWithProgramIndex) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1596]
### What service call is missing?

fsp-srv IFileSystemProxy: 205 (OpenDataStorageWithProgramIndex) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Filesystem_services#OpenDataStorageWithProgramIndex) | 

### Service description
```
Takes an input u8, returns an #IStorage.
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/2578
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2921

**Comment by CrusadingNinja** [comment]
Required by https://github.com/Ryujinx/Ryujinx-Games-List/issues/3836

**Comment by EmulationFanatic** [comment]
Bit.Trip Runner and Bit.Trip Void working fine now:

![2022-10-17 06_22_13-Ryujinx 1 1 0+3f4cb61 - BIT TRIP RUNNER v1 0 0 (0100E62012D3C000) (64-bit)](https://user-images.githubusercontent.com/62343878/196177396-aae8d80c-bd7f-4b69-96f5-666852f35da8.png)
![2022-10-17 06_28_57-Ryujinx 1 1 0+3f4cb61 - BIT TRIP VOID v1 0 0 (01000AD012D3A000) (64-bit)](https://user-images.githubusercontent.com/62343878/196177403-c5f709a8-9dd7-42a8-b5a3-490fc2e4f779.png)
