### ISSUE TITLE
hey so

### ISSUE THREAD

**Issue by QuillzHearts** [Ryujinx/Ryujinx#1601]
i dont know what specs are, and i only just downloaded it, 
![image](https://user-images.githubusercontent.com/72473692/95262660-2938cb00-07f2-11eb-88ce-706441c7e0e8.png)
but i didnt get the prod file

**Comment by QuillzHearts** [comment]
WAIT WE HAVE TO HAVE A SWITCH TO DO THIS?

**Comment by ReaperOfSouls1909** [comment]
Yes you need a switch as piracy isnt supported please visit the discord for any more questions in the support channel

**Comment by AcK77** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
