### ISSUE TITLE
Add option to pause emulation

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1604]
### What feature are you suggesting?

Adding a pause emulation function.

#### Overview:
Ryujinx would benefit from having a menu option, with an associated hotkey, that pauses & unpauses emulation. 

#### Smaller Details: 

Making the pause toggle hotkey programmable would be beneficial to allow the end user to customize the feature to their liking.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
Some games do not allow pausing with the + button, and pausing emulation would be a useful feature for end users within said games. Additionally, even in games where pausing is possible, pausing emulation should (in-theory) lower CPU usage so that if another program or game needs to be run, it is not fighting for resources against the emulator.

**Comment by HiHiKazumaDesu** [comment]
I play a lot of single player games during work that do not let me pause during combat, for example Xenoblade, having an option to pause the emulation would really come in handy for when things get a little busy. This Feature would be much appreciated :D

**Comment by CeruleanSky** [comment]
@HiHiKazumaDesu 

As a work around, if you are in windows you can get  [pssuspend from sysinternals](https://docs.microsoft.com/en-us/sysinternals/downloads/pssuspend)

Create two shortcuts to pssuspend.exe , edit their shortcut properties and name one Suspend and have it go "pssuspend.exe Ryujinx.exe" and the other Resume "pssuspend.exe -r Ryujinx.exe"  you can also edit the shortcut properties to have a hotkey combo that invokes them.  If you run Ryujinx as admin for performance reasons you'll have to make them run as admin as well.

**Comment by HiHiKazumaDesu** [comment]
@CeruleanSky Works like a charm, thank you so much for the very detailed instructions :D

**Comment by edisionnano** [comment]
On Linux you can use killall -STOP Ryujinx to pause and killall -CONT Ryujinx to resume
