### ISSUE TITLE
Xenoblade Chronicles Definitive Edition: Textures bug 

### ISSUE THREAD

**Issue by eruxxn36** [Ryujinx/Ryujinx#1620]
### What's the issue you encountered?

xenoblade chronicles in Ryujinx (mostly ok)

but sometime has wrong 
 
main problem is in the Texture (like picture)

![001](https://user-images.githubusercontent.com/72922836/96121641-ee860f80-0f22-11eb-90b5-f96ca8d36724.jpg)

![002](https://user-images.githubusercontent.com/72922836/96121660-f6de4a80-0f22-11eb-8352-579f685e5fc4.jpg)

![003](https://user-images.githubusercontent.com/72922836/96121681-fc3b9500-0f22-11eb-8700-965534660362.jpg)

![004](https://user-images.githubusercontent.com/72922836/96121705-02317600-0f23-11eb-9b16-5eeb969d0e7b.jpg)

![005](https://user-images.githubusercontent.com/72922836/96121722-08275700-0f23-11eb-88b5-7387fee3a963.jpg)

![006](https://user-images.githubusercontent.com/72922836/96137147-e207b400-0f2e-11eb-9890-ad7924f79da5.jpg)

### How can the issue be reproduced?

in game

the first village and big map 

### Log file

[Ryujinx_xenoblade.log](https://github.com/Ryujinx/Ryujinx/files/5384660/Ryujinx_xenoblade.log)

### Environment?

- Ryujinx version: ryujinx-1.0.5525-win_x64</br>

- Game version: 1.0</br>

- System Specs:
  - OS: *Windows 7 SP 1 (6.1)*
  - CPU: *Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz*
  - GPU: *NVIDIA GTX 1066*
  - RAM: *16GB*
- Applied Mods : [  No ]

### Additional context?

hope the bug can fix

Thanks the devs for making the Ryujinx

**Comment by Doctorwho1909** [comment]
Also add an image

**Comment by eruxxn36** [comment]
Thank you very much for gdkchan and others response

but I try ryujinx-1.0.5545-win_x64

There are still some problems

shadow

![shadow001](https://user-images.githubusercontent.com/72922836/96422460-9e60c300-122a-11eb-89ee-683342ef01b6.jpg)
![shadow002](https://user-images.githubusercontent.com/72922836/96422478-a3be0d80-122a-11eb-9049-c4ec832436c5.jpg)

log
[shadow.log](https://github.com/Ryujinx/Ryujinx/files/5400385/shadow.log)

my save
[shadow.zip](https://github.com/Ryujinx/Ryujinx/files/5400400/shadow.zip)




black grass

![black grass](https://user-images.githubusercontent.com/72922836/96422839-1fb85580-122b-11eb-8b8f-e0a7f4c3a692.jpg)

log
[black grass.log](https://github.com/Ryujinx/Ryujinx/files/5400407/black.grass.log)

my save
[black grass.zip](https://github.com/Ryujinx/Ryujinx/files/5400412/black.grass.zip)


Thanks again for your response

Thanks

**Comment by AcK77** [comment]
It’s because you use the wrong build, this seems to be fixed in a PR who isn’t merge in master now.
Try this build https://ci.appveyor.com/project/gdkchan/ryujinx/builds/35781446/artifacts and it should fix some (maybe all?) of your issues 😊!

**Comment by eruxxn36** [comment]
ok

Thank you for AcK77 response

5536 fix some problems

but some problems is also

![001](https://user-images.githubusercontent.com/72922836/96428353-41690b00-1232-11eb-83e9-ffbd00b54fef.jpg)

![005](https://user-images.githubusercontent.com/72922836/96428400-4d54cd00-1232-11eb-8b3b-9bb49e44c8e3.jpg)

![007](https://user-images.githubusercontent.com/72922836/96428467-5f367000-1232-11eb-9e6c-14f3e888b094.jpg)

thnkns again for your response

**Comment by Doctorwho1909** [comment]
Can you take a better screenshot please of the full ryujinx window the gpu is mentioned in the bottom and that part is missing

**Comment by gdkchan** [comment]
> and it should fix some (maybe all?) of your issues 😊!
It only fixes the black artifacts on the ground. Broken grass is likely due to transform feedback buffer being shared with other buffers (which OpenGL spec does not allow). Broken textures is likely due to texture management, and the line at the middle I don't know, never looked at it.

**Comment by riperiperi** [comment]
The lines are due to something it's doing with what seems like lighting volumes. Adding bitwise pixel operations seemed to fix isolated cases, though for some reason it is still breaking down when multiple volumes overlap.

**Comment by tazevam** [comment]
I also tested,
It does rendering something superfluous, may be different situations in different locations.
![1](https://user-images.githubusercontent.com/73407337/97659536-30c65980-1aaa-11eb-941f-56176c157419.PNG)
![2](https://user-images.githubusercontent.com/73407337/97659540-3328b380-1aaa-11eb-9d4d-fef585d19cda.PNG)
![3](https://user-images.githubusercontent.com/73407337/97659541-33c14a00-1aaa-11eb-9bbe-3633f1f59f04.PNG)
![4](https://user-images.githubusercontent.com/73407337/97659545-3459e080-1aaa-11eb-87ad-8cf4fae8a234.PNG)

**Comment by ExE-Boss** [comment]
This also happens in **Xenoblade Chronicles 2**, probably because they use similar engines.

**Comment by SiemJanssen** [comment]
I got the same in Xc2

**Comment by gdkchan** [comment]
Fixed by #2001.
