### ISSUE TITLE
The Longest Five Minutes: Title screen/menus no longer render

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1629]
### What's the issue you encountered?

There is a regression introduced in 1.0.4921 [PR 1198](https://github.com/Ryujinx/Ryujinx/pull/1198) that stops title screen and menu graphics from being rendered in the game [The Longest Five Minutes](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1591), making the game unplayable.

### How can the issue be reproduced?

Fire up The Longest Five Minutes on Ryujinx 1.0.4921 or newer. Earlier versions of Ryujinx render the game fine.

### Log file

[TLFM.log](https://github.com/Ryujinx/Ryujinx/files/5408676/TLFM.log)

### Environment?

- Ryujinx version: 1.0.4921

- Game version: 1.0.0

- System Specs:
  - OS: Windows 10
  - CPU: i5-6600K
  - GPU: NVIDIA GTX 1080
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Before PR 1198:

![2020-06-03 15_00_14-Ryujinx 1 0 4675 - The Longest Five Minutes v1 0 0 (0100CE1004E72000) (64-bit)](https://user-images.githubusercontent.com/62343878/96587140-2c769100-129f-11eb-8ac0-37123e03e656.png)

After PR 1198:

![2020-10-20 06_13_19-Ryujinx 1 0 5545 - The Longest Five Minutes v1 0 0 (0100CE1004E72000) (64-bit)](https://user-images.githubusercontent.com/62343878/96587144-2da7be00-129f-11eb-8775-c50c9aa5d45e.png)

**Comment by GamerzHell9137** [comment]
Still the same on 1.1.23

**Comment by GamerzHell9137** [comment]
void tRrLM(); can be added to the list.
Same company, game doesn't show stuff but once reverted its fine.

![image](https://user-images.githubusercontent.com/2002038/176316101-57aa18f0-25db-4081-8253-22fe1137c6bf.png)

**Comment by EmulationFanatic** [comment]
Still broken on 1.1.208
![image](https://user-images.githubusercontent.com/62343878/183421014-7c343bdd-0333-46b4-868c-fa1596ea9a19.png)
