### ISSUE TITLE
Yomi Wo Saku Hana: Dungeon are randomly too dark

### ISSUE THREAD

**Issue by tazevam** [Ryujinx/Ryujinx#1639]
### What's the issue you encountered?

When you enter the dungeon, sometimes the too dark problem will reappear. It's random. try it a few times and you'll meet it.(especially after various operations in camp)
![1](https://user-images.githubusercontent.com/73407337/97125546-44eb1d80-176f-11eb-8e2c-524bd106edfa.PNG)
![2](https://user-images.githubusercontent.com/73407337/97125550-46b4e100-176f-11eb-9c47-11e3fbb47c7e.PNG)

### How can the issue be reproduced?

try it a few times and you'll meet it.(especially after various operations in camp)

### Log file
[Ryujinx_2020-10-26_08-06-25.log](https://github.com/Ryujinx/Ryujinx/files/5436355/Ryujinx_2020-10-26_08-06-25.log)

### Environment?

- Ryujinx version: 1.0.5563-x64

- Game version: 1.01

- System Specs:
  - OS:  Windows 10
  - CPU: I3-8350k
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : [ / No ]

### Additional context?
no

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
