### ISSUE TITLE
Monster Hunter Generations Ultimate: Random texture position error

### ISSUE THREAD

**Issue by FengYuu** [Ryujinx/Ryujinx#1640]
### What's the issue you encountered?

 - **Texture issues**

    A few days ago, [pull1584](https://github.com/Ryujinx/Ryujinx/pull/1584) fixed the environment texture error of some maps</br>
    But when playing for a long time or frequently entering and exiting certain areas, the position of the texture will be wrong (as shown in the figure, grass appears in the snow)</br>

![image](https://user-images.githubusercontent.com/31071847/97128400-399bf000-1777-11eb-8d13-7fa424e1ea22.png)</br>
![image](https://user-images.githubusercontent.com/31071847/97128423-4587b200-1777-11eb-88f1-50f6f235b68c.png)</br>
![image](https://user-images.githubusercontent.com/31071847/97128434-4d475680-1777-11eb-830a-e95e9c565aca.png)</br>

<del>
 - **Keyboard issues**

    Enter the game appears popover</br>

![image](https://user-images.githubusercontent.com/31071847/97129058-e9be2880-1778-11eb-9b8a-15ff0e026353.png)

    When entering a name or chatting in the game, the keyboard cannot be called and the game is soft locked

![image](https://user-images.githubusercontent.com/31071847/97129082-f3e02700-1778-11eb-9a14-e697c56792b2.png)

</del>

### How can the issue be reproduced?

 - **Texture issues**

    Quickly reproduce: Frequently enter and exit areas 5 and 6 of the snow mountain map

<del>

 - **Keyboard issues**

    Quickly reproduce: Change the name of the cat or create a new archive and enter the name
    
</del>

### Log file

 - **Texture issues**

[Textures issues log Ryujinx_2020-10-26_09-52-06.log](https://github.com/Ryujinx/Ryujinx/files/5436603/Textures.issues.log.Ryujinx_2020-10-26_09-52-06.log)

<del>

 - **Keyboard issues**

[Keyboard issues Ryujinx_2020-10-26_10-06-06.log](https://github.com/Ryujinx/Ryujinx/files/5436605/Keyboard.issues.Ryujinx_2020-10-26_10-06-06.log)

</del>

### Environment?

- Ryujinx version: 1.0.5573</br>
- Game version: 1.4.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i5-8400*
  - GPU: *NVIDIA GTX 1050Ti*
  - RAM: *16GB*
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
Thanks for the hard work of the developers!

**Comment by Caian** [comment]
From what I'm seeing, it is trying to use configure the InlineKeyboard Applet, because it calls `GetIndirectLayerConsumerHandle`

**Comment by gdkchan** [comment]
Should be fixed by #2001, please open a new issue if not, without the swkbd error (which was also already fixed a few months ago).
