### ISSUE TITLE
 Hyrule Warriors: Age of Calamity: Rendering issues

### ISSUE THREAD

**Issue by shukenmg** [Ryujinx/Ryujinx#1652]
### What's the issue you encountered?

Attack effects and effects related to Sheikah tech (Egg guardians eye, bombs, Impa's clones, tower's blue glow, etc...) don't render or are black and sometimes transparent.
</br>
### How can the issue be reproduced?
Play through the demo's first mission, you will see that even if the attack effects and the Sheikah tech blue do not render correctly. 
If at the start the attack renders properly eventually the effects will stop rendering correctly. 
</br>
### Log file

[Ryujinx_2020-11-01_13-39-46.log](https://github.com/Ryujinx/Ryujinx/files/5470259/Ryujinx_2020-11-01_13-39-46.log)

It seems the main problem is this:
`|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x000698 (0xED01000000900404).`
`|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x004318 (0xED01000001F00424).`
`|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002978 (0xED01000000300003).`
`|E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).`
`|E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).`
`|E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24928 (sRGB: True).`
`|E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24928 (sRGB: True).`
`|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x005C28 (0xED01000000500001).`

### Environment?

- Ryujinx version: 1.0.5584</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i7-8700k*
  - GPU: * NVIDIA GTX 1060*
  - RAM: *32 GB*
- Applied Mods : No

### Temporary workaround
Set Resolution Scale to Native.

**Comment by shukenmg** [comment]
It appears that the texture format 0x7FF8F (sRGB: True) encodes to the texture uint 0xFFF8F, and that it isn't implemented in the Emulator.
This is the `encoded` value before the sRGB AND operator.
![image](https://user-images.githubusercontent.com/18000205/97802801-e9de8c80-1c80-11eb-9ae9-efebcecd95c6.png)
After
![image](https://user-images.githubusercontent.com/18000205/97802834-21e5cf80-1c81-11eb-8905-70587e40ca2c.png)

**Comment by shukenmg** [comment]
More invalid textures,
00:02:50.297 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:03:13.706 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:03:15.427 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FFAF (sRGB: True).
00:04:09.599 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:05:26.829 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:06:41.731 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24927 (sRGB: True).
00:06:48.061 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:06:48.253 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:08:05.766 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x2493A (sRGB: True).

**Comment by shukenmg** [comment]
Any idea on how to fix this?

**Comment by EmulationFanatic** [comment]
There's nothing to do on your end but wait for further fixes in the emulator.

**Comment by riperiperi** [comment]
Do you have resolution scale enabled? I've heard from a few people that these errors don't happen with it disabled, but it's a whole other story if they do.

**Comment by shukenmg** [comment]
@riperiperi Yep that fixed many issues.

![image](https://user-images.githubusercontent.com/18000205/97807202-7ba6c380-1c9a-11eb-9792-edcc304c9660.png)
The icon above the head of the bokoblin has issues.
the log during this scene:
00:08:21.881 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:08:29.036 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:08:29.240 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:08:55.751 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:09:09.138 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24A29 (sRGB: True).
00:09:18.269 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:09:18.608 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:23.356 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:09:27.759 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:29.871 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:34.003 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:34.165 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:34.384 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:37.264 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:09:47.397 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:47.813 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:47.911 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:09:50.276 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:09:58.122 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24903 (sRGB: True).
00:10:09.482 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:10:10.492 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:10:15.107 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:10:21.563 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:10:21.696 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:29.004 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24928 (sRGB: True).
00:10:30.711 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:30.720 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:10:41.707 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:41.876 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:41.973 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:10:42.575 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:47.651 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:10:48.916 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:49.152 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:54.536 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:10:55.440 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:56.071 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:10:58.407 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:11:04.124 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:11:05.721 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:11:05.959 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:11:06.590 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:11:06.765 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).

Resolution scale set to Native.

**Comment by shukenmg** [comment]
Also on an unrelated note, the brightness of the game seems to be a bit too bright compared to the switch, although that could also just be a screen issue I'm not sure.

**Comment by shukenmg** [comment]
Vertex explosions and invisible weapons with Resolution scale at 2x 
![image](https://user-images.githubusercontent.com/18000205/97824893-23061380-1cf8-11eb-82fb-8279d42b81fe.png)

Log:
|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x000698 (0xED01000000900404).
|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002978 (0xED01000000300003).
|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x004318 (0xED01000001F00424).
|W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x005C28 (0xED01000000500001).

**Comment by shukenmg** [comment]
#1657 Fixes most of these issues, will need more testing but it looks promising.

**Comment by shukenmg** [comment]
![image](https://user-images.githubusercontent.com/18000205/97948869-caed1100-1dcc-11eb-8883-0515b83684ae.png)
Impa clones vertex explosion.

Ryujinx 1.0.5604

Log:
00:19:49.901 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x2493A (sRGB: True).
00:19:52.444 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:19:55.587 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF84 (sRGB: True).
00:19:56.350 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:19:57.547 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:19:59.886 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:19:59.898 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:20:00.378 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24903 (sRGB: True).
00:20:00.740 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x2493A (sRGB: True).
00:20:02.084 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:20:05.101 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:20:06.501 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:20:09.280 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:20:10.197 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:20:14.139 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:20:18.137 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FFA1 (sRGB: True).
00:20:47.870 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:20:48.634 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:20:48.816 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:20:49.957 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:20:51.045 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:20:56.341 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:20:57.107 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24928 (sRGB: True).
00:20:59.862 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF84 (sRGB: True).
00:21:03.704 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:04.999 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:05.235 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:21:06.889 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:07.222 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:07.225 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:14.196 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:21:22.405 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:25.519 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:21:26.989 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:21:43.729 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:21:44.536 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:22:03.718 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:22:03.854 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:22:19.786 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:22:20.534 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:22:25.660 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24A29 (sRGB: True).
00:22:43.769 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:22:45.929 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:22:46.890 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:22:56.250 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF84 (sRGB: True).
00:22:56.892 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:23:01.724 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:23:05.504 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:23:15.209 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8C (sRGB: True).
00:23:21.428 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:23:21.906 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:23:31.218 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:23:31.527 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:23:35.674 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x24928 (sRGB: True).
00:23:54.538 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:23:55.081 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:23:58.994 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:24:00.383 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x2493A (sRGB: True).
00:24:02.400 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:24:04.811 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:24:07.240 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:24:11.818 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8C (sRGB: True).
00:24:18.283 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:24:30.531 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x2493A (sRGB: True).
00:24:35.334 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:24:35.470 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF8F (sRGB: True).
00:24:36.248 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:24:49.784 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).
00:24:50.640 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:24:50.934 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:24:52.722 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4920F (sRGB: True).
00:24:59.225 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FF81 (sRGB: True).

**Comment by Lenksi** [comment]
Also game has huge RAM hog issue. Even with 32GB of memory that was filled I needed to create huge virtual memory page file (5
0GB) in order for me to be able to complete the game.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
