### ISSUE TITLE
Can't start any game with an HD 6900 and Crt Emudriver

### ISSUE THREAD

**Issue by phasermaniac83** [Ryujinx/Ryujinx#1654]
## Bug Report

Whe I launch any game, Ryujinx crashes

### What's the issue you encountered?

I can't start any game. When I launch any game it crashes Ryujinx.

### How can the issue be reproduced?
In my side, with any game.

### Log file
[Ryujinx_2020-10-30_22-36-32.log](https://github.com/Ryujinx/Ryujinx/files/5470612/Ryujinx_2020-10-30_22-36-32.log)

### Environment?

- Ryujinx version: 1.0.5584-win_x64</br>

- System Specs:
  - OS: Windows 10
  - CPU: i5-3470
  - GPU: AMD HD 6900
  - RAM: 16GB
- Applied Mods :  No

### Additional context?

Additional info about your environment:</br>
My environment is something special: I have a 15khz monitor, so I must use an Ati card, which is the only that works with crt emudriver (a customgpu driver to use 15khz screens)

**Comment by AcK77** [comment]
The issue and the log file don't contains crash messages.
Since your GPU is 10 years old it's probably related... We can't do anything without more informations.
In that way I close the issue, we can reopen it later if more informations will be provided.
Thanks.
