### ISSUE TITLE
Add an option to hide the console window

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1669]
#### Overview:
Add an option to completely hide the console window.

#### Smaller Details: 
A checkbox within options > settings would be a good place for it.

#### Nature of Request:  
- Addition
  - Add a menu checkbox to completely hide the the console window.

### Why would this feature be useful?
This benefits end users who only want to see the main Ryujinx window, as well as those who are using an aggregating emulator frontend (e.g. Hyperspin, Launchbox) and wish for a cleaner experience. 
It would also reduce the number of support questions regarding harmless console output messages that tend to attract attention.

**Comment by Quest79** [comment]
I dont understand why this is still not an option considering how often this is updated. A huge number of people have the game windowed, mousing over the icon in the taskbar, waiting for the preview to pop up and then selecting the game rathe rthan just clicking the ryu button is pretty annoying 100s of times a gaming session. Not to mention it clutters up alt-tab. 

PLEASE add this basic feature. I appreciate all the efforts you've provided.

**Comment by defunky** [comment]
This would be super nice to have as it lets you use Steam Remote Play with Ryujinx

**Comment by HVR88** [comment]
Great, nice to be able to get ride of this unpolished element. I can guarantee you that the people who want to see the console output are less than 1% of the people actually downloading and using ryujinx.

**Comment by GF-Huang** [comment]
Same issue, how to hide it?
