### ISSUE TITLE
low end pc support

### ISSUE THREAD

**Issue by Lulbit8** [Ryujinx/Ryujinx#1678]
## Feature Request

soooooo you should make run switch games on low end pc with no gtraphichs errors LIKE I SAID IN THE LAST ISSUE
anddd make ryujinx games like animal crossing new horyzons or Pokemon sheild and sword on 4 gb ram like fortnite . Fortnite now is a big game that is like 45 gb on pc and i have 4 gb ram and the game runs very well so if you can make a resolution scroll ui so we chìan change it more easly then a graphic changer so to fast to fastes to low to very low to ultra and ecc then done this is just what the emulator need .
I known its a lot of coding bc i program games and i known of code is sifficoult to write ecc but the emulator will have more succes and whos known you can open a community where every one can acces and not only big rams player so known im gonna play animal crosing NH in this state
![tfdjlòliuy](https://user-images.githubusercontent.com/73791936/98437980-2e39b480-20e7-11eb-984d-f9d0ebe0880d.PNG) but i can still have a fun

**Comment by AcK77** [comment]
Emulate the Switch environment on a PC is different and not as simple as run a game made for your PC. That’s why the support of a low end PC isn’t something really possible.
Btw, please, stop posting issues which aren’t real issues.
Thanks.

**Comment by Lulbit8** [comment]
i dunno what is a issue or not i have just 15 years old SOOOO idunno im gonna play the game like this but ok
