### ISSUE TITLE
Error starting the game

### ISSUE THREAD

**Issue by LightBull** [Ryujinx/Ryujinx#1679]
Opening the emulator is fine, but once you select the game to start an exception occurs. I attach the log file.

Win 10 Pro 64 bit
i5-3470
8 GB
[Ryujinx_2020-11-07_16-31-46.log](https://github.com/Ryujinx/Ryujinx/files/5505056/Ryujinx_2020-11-07_16-31-46.log)

**Comment by AcK77** [comment]
You needs to install OpenAL. Check our guides in the wiki (https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#dependencies).
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
