### ISSUE TITLE
Stop Emulation closes Ryujinx

### ISSUE THREAD

**Issue by rodyt** [Ryujinx/Ryujinx#1681]
### What's the issue you encountered?

On Ubuntu 20, clicking Options -> Stop Emulation causes Ryujinx to close. The correct behavior is to stop the game and return to the game directory screen.

### How can the issue be reproduced?

Start a game, then press the stop emulation button from the options dropdown.

### Log file

[Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/5505375/Ryujinx.log)

### Environment?

- Ryujinx version: 1.0.5639</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Ubuntu 20*
  - CPU: *Ryzen Threadripper 1920x*
  - GPU: *NVIDIA GTX 1080 ti*
  - RAM: *32 GB*
- Applied Mods : No

### Additional context?

NA

**Comment by EmulationFanatic** [comment]
Fixed by https://github.com/Ryujinx/Ryujinx/pull/1900
