### ISSUE TITLE
BAD SERVICE

### ISSUE THREAD

**Issue by Lulbit8** [Ryujinx/Ryujinx#1682]
Yuzu say to me evrything that i should do and ryujinx dont ok im playng the game in orrible condition but i play it Yuzu told to me that this is not an hardwaree problem bc is good for me ITS YOUR EMULATOR THATS DONT WORK yuzu told me to redump the game and you closed my issue without tolding me anityng but yuzu make my issue (that the emulator crash) opned 4 DAYS you dont im considering to use yuzu BC IS A BETTER EMULATOR

**Comment by jduncanator** [comment]
Unless you have a specific issue with enough information for us to reproduce, I’m going to have to close this one.

Ryujinx is free software, and no one is forcing you to use it. If you’d prefer to use Yuzu, which you mention is working better for you, then you are completely free to do so.

If you have some more information on a specific issue that we can look into, please do leave it here, and I’ll re-open your issue if it’s something we can action. If you’re looking for general support with the emulator, please visit our Discord where we can better provide end user support, as this issue tracker is for development issues.

Thanks.

**Comment by Lulbit8** [comment]
ok i say this becouse some emploee say ITS NOT AN OUR PROBLEM but im trying to play animal crossing new horyzons on 4 gb of ram on ryujinx but the graphic not render and... i like this emulator mìbut the emploee beeds to understand im only 13 years old and they make me just mad on this emulator bcouse they treated me like trash soooo now im gonna put a screenshot that what happend when i play and if you emulatore wanna be famous the emploee needs to be funny and not serius bc its an emulator and of switch and kid or teens like me download this and the can fill treated like trash just like me you not trated me like trash so now im chnging my mind so now im gonna put LOG files and screenshots
![ANIMALLLLLLLLL](https://user-images.githubusercontent.com/73791936/98464480-7928fa00-21c3-11eb-9165-ae286e799b9c.PNG)
[Ryujinx_2020-11-08_13-08-37.log](https://github.com/Ryujinx/Ryujinx/files/5506284/Ryujinx_2020-11-08_13-08-37.log)
[Ryujinx_2020-11-07_11-05-50.log](https://github.com/Ryujinx/Ryujinx/files/5506285/Ryujinx_2020-11-07_11-05-50.log)
[Ryujinx_2020-11-08_13-02-25.log](https://github.com/Ryujinx/Ryujinx/files/5506286/Ryujinx_2020-11-08_13-02-25.log)
this is all my log files sooo help me this time PLEASE
