### ISSUE TITLE
Fire Emblem Three houses: Corrupted Save file

### ISSUE THREAD

**Issue by Burnandfire** [Ryujinx/Ryujinx#1683]
### What's the issue you encountered?
My pc screen turn black and restart, which give me a Corrupted Save in fire emblem three houses. Anyone has any ideas how to fix this ?
![2](https://user-images.githubusercontent.com/74136091/98463570-14879280-21f7-11eb-967a-9c2b37111010.JPG)

**Comment by mihir-io** [comment]
@Burnandfire If you've added the update and any DLC to the game, have you made sure those were loaded into the emulator?

**Comment by BSoDGamingYT** [comment]
You are using a save from an updated version of the game you have not installed. Install the 1.2.0 Update and this will fix your problem.

**Comment by AcK77** [comment]
If your problem isn’t fixed with the update, I’ll reopen this issue. I close it for now!
