### ISSUE TITLE
help me this time ... 7 ISSUES THAT RYUJINX NOT HELP ME WITH

### ISSUE THREAD

**Issue by Lulbit8** [Ryujinx/Ryujinx#1684]
ok i say this becouse some emploee say ITS NOT AN OUR PROBLEM but im trying to play animal crossing new horyzons on 4 gb of ram on ryujinx but the graphic not render and... i like this emulator mìbut the emploee beeds to understand im only 13 years old and they make me just mad on this emulator bcouse they treated me like trash soooo now im gonna put a screenshot that what happend when i play and if you emulatore wanna be famous the emploee needs to be funny and not serius bc its an emulator and of switch and kid or teens like me download this and the can fill treated like trash just like me you not trated me like trash so now im chnging my mind so now im gonna put LOG files and screenshots
![ANIMALLLLLLLLL](https://user-images.githubusercontent.com/73791936/98464480-7928fa00-21c3-11eb-9165-ae286e799b9c.PNG)
[Ryujinx_2020-11-08_13-08-37.log](https://github.com/Ryujinx/Ryujinx/files/5506284/Ryujinx_2020-11-08_13-08-37.log)
[Ryujinx_2020-11-07_11-05-50.log](https://github.com/Ryujinx/Ryujinx/files/5506285/Ryujinx_2020-11-07_11-05-50.log)
[Ryujinx_2020-11-08_13-02-25.log](https://github.com/Ryujinx/Ryujinx/files/5506286/Ryujinx_2020-11-08_13-02-25.log)
this is all my log files sooo help me this time PLEASE

_Originally posted by @Lulbit8 in https://github.com/Ryujinx/Ryujinx/issues/1682#issuecomment-723568924_

**Comment by jduncanator** [comment]
This is not the place to ask for support. Please come to our Discord server for support, you can access that here: https://discord.gg/N2FmfVc. Someone will be able to provide you with assistance.
