### ISSUE TITLE
The configured user limit (128) on the number of inotify instances has been reached

### ISSUE THREAD

**Issue by rodyt** [Ryujinx/Ryujinx#1691]
### What's the issue you encountered?

When trying to launch a game, Ryujinx will crash with this issue:

> 00:00:07.758 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'OpenTK.Input.Keyboard' threw an exception.
>  ---> System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
>    at System.IO.FileSystemWatcher.StartRaisingEvents()
>    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
>    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
>    at OpenTK.Platform.Linux.LinuxJoystick..ctor()
>    at OpenTK.Platform.X11.XI2Input..ctor()
>    at OpenTK.Platform.X11.X11Factory.get_InputDriver()
>    at OpenTK.Platform.X11.X11Factory.CreateKeyboardDriver()

### How can the issue be reproduced?

This issue happens in 2 main instances. The first is when I have 2 or more windows of Ryujinx open simultaneously. This eats away at the `inotify` instances. This bug also occurs after I have opened Ryujinx, started emulating a game, and then closed it, several times. After a few times, I receive this issue even though I only have a single window of Ryujinx open, suggesting a possible "zombie" issue. 

The situation can temporarily be remedied by configuring `ulimit -n 9999` and running Ryujinx from the terminal, or increasing the `fs.inotify.max_user_instances` using `sudo 
sysctl -n -w fs.inotify.max_user_instances=512`. Still this is not a good and reliable solution.

### Log file

[Ryujinx_2020-11-10_23-12-39.log](https://github.com/Ryujinx/Ryujinx/files/5522434/Ryujinx_2020-11-10_23-12-39.log)

### Environment?
- Ryujinx version: 1.0.5659</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Ubuntu 20
  - CPU: Ryzen Threadripper
  - GPU: GTX 1080 Ti
  - RAM: 32 GB
- Applied Mods : No

**Comment by MetrosexualGarbodor** [comment]
Fixed by #2194.
