### ISSUE TITLE
Built in Updated Deletes any additional files in Folder.

### ISSUE THREAD

**Issue by Demaar** [Ryujinx/Ryujinx#1692]
I have my Custom Data Directory located inside the Ryujinx folder [|N| Application PrintSystemInfo: Custom Data Directory: F:\Desktop\Yuzu\Ryujinx\Ryujinx].
After using the Built-in Updater, the entire folder seems to have been wiped.
All my Configs, Keys, Saves. All Gone.

**Comment by EmulationFanatic** [comment]
You should not have had your custom data directory inside the program directory, as the program directory is wiped when the auto-updater downloads and installs a new update.
