### ISSUE TITLE
ryujinx crashes after starting a game

### ISSUE THREAD

**Issue by ycex34** [Ryujinx/Ryujinx#1710]
## Bug Report

N/A

### What's the issue you encountered?

ryujinx crashes right after i clicked a game (pokemon sword 1.2.1 with DLC)
ryujinx was working properly yesterday though

### How can the issue be reproduced?

N/A

### Log file

[Ryujinx_2020-11-15_00-16-49.log](https://github.com/Ryujinx/Ryujinx/files/5541084/Ryujinx_2020-11-15_00-16-49.log)
[Ryujinx_2020-11-15_00-15-01.log](https://github.com/Ryujinx/Ryujinx/files/5541085/Ryujinx_2020-11-15_00-15-01.log)

### Environment?

- Ryujinx version: 1.0.5683

</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-8550U)*
  - GPU: *(e.g. Radeon 500 Series)*
  - RAM: *(e.g. 8GB)*
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
Right click on the game > Cache > Purge Shader Cache.
Please come to our Discord server for support, you can access that here: https://discord.gg/N2FmfVc. Someone will be able to provide you with assistance.
