### ISSUE TITLE
Ryujinx crashes when sorting by last played (if not all games are played yet)

### ISSUE THREAD

**Issue by smitdylan2001** [Ryujinx/Ryujinx#1727]
### What's the issue you encountered?

When you use Ryujinx with multiple games which you did not play yet, it will crash when pressing the last played section. This probably is because it will sort data that is not available, or because multiple games have not been played.
If you sort this way and then add multiple games in the game folder, you will be unable to open Ryujinx unless you remove the games again and sort by something else.
I use the latest master build

### How can the issue be reproduced?

- add multiple games which have not been played
- press 'last played' to sort on it

### Log file

[Ryujinx_2020-11-18_12-26-24.log](https://github.com/Ryujinx/Ryujinx/files/5559689/Ryujinx_2020-11-18_12-26-24.log)

### Environment?

- Ryujinx version: 1.0.5742</br>
- Game version: X.X.X</br>
- System Specs:
  - OS: *Windows 10 2004*
  - CPU: *i7 9750H*
  - GPU: *NVIDIA RTX 2070 (laptop)*
  - RAM: *16GB DDR4*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by EmulationFanatic** [comment]
I can't reproduce this issue.

**Comment by Thog** [comment]
Reproduced it.
