### ISSUE TITLE
Yoshi Crafted World: Random crashes

### ISSUE THREAD

**Issue by legend800** [Ryujinx/Ryujinx#1731]
Yoshi Crafted World (UE4 game) has constant crashes. It occurs during map loads, level loads, pause menu opening, and sometimes randomly inside levels. Usually you're lucky if you can get through 2 lvls before it crashes. No setting seems to impact the frequency. 

Looks like there might be more than 1 issue causing instability. Attaching logs below for analysis. 

Memory corruption:
[Ryujinx_2020-11-18_12-20-49-MEMORY.log](https://github.com/Ryujinx/Ryujinx/files/5563119/Ryujinx_2020-11-18_12-20-49-MEMORY.log)
[Ryujinx_2020-11-18_14-16-24-MEMORY.log](https://github.com/Ryujinx/Ryujinx/files/5563120/Ryujinx_2020-11-18_14-16-24-MEMORY.log)
[Ryujinx_2020-11-18_19-25-59-memory.log](https://github.com/Ryujinx/Ryujinx/files/5564283/Ryujinx_2020-11-18_19-25-59-memory.log)

Threading:
[Ryujinx_2020-11-18_12-00-26-THREADING.log](https://github.com/Ryujinx/Ryujinx/files/5563121/Ryujinx_2020-11-18_12-00-26-THREADING.log)

GPU related crashes:
[Ryujinx_2020-11-18_13-22-10-GPU.log](https://github.com/Ryujinx/Ryujinx/files/5563122/Ryujinx_2020-11-18_13-22-10-GPU.log)
[Ryujinx_2020-11-18_20-01-30-loading level.log](https://github.com/Ryujinx/Ryujinx/files/5564276/Ryujinx_2020-11-18_20-01-30-loading.level.log)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by EmulationFanatic** [comment]
This was resolved with a combination of PRs over the last month.
