### ISSUE TITLE
The Legend of Zelda: Breath of the Wild: The game is mostly white

### ISSUE THREAD

**Issue by EliasM108** [Ryujinx/Ryujinx#1733]
## Bug Report
The whole game except all the menus, render in white.

### What's the issue you encountered?

![Χωρίς τίτλο](https://user-images.githubusercontent.com/51413997/99675034-680fa100-2a7f-11eb-89df-b80ab3a5aea3.png)

### How can the issue be reproduced?

Using the latest update and all the dlcs, first time loading.

### Log file

[Ryujinx_2020-11-19_15-46-24.log](https://github.com/Ryujinx/Ryujinx/files/5567150/Ryujinx_2020-11-19_15-46-24.log)

**Comment by metz385** [comment]
any luck yet? i have the same issue

**Comment by EliasM108** [comment]
> any luck yet? i have the same issue

no, the problem still exists.
![image](https://user-images.githubusercontent.com/51413997/99874318-b2179480-2bef-11eb-9e7a-4527eb0cbbfd.png)

**Comment by AcK77** [comment]
Goes in the inventory menu and leave it. Do that multiple time and the white rendering disappear. I don’t know much about this issue.

**Comment by MelonSpeedruns** [comment]
Though this doesn't always work. It depends of your current location and the weather. For example, the white will never go away if it's raining.

**Comment by Doctorwho1909** [comment]
The PR that broke this was the swizzle pr a while back before that pr the white was fixed and never happened

**Comment by MelonSpeedruns** [comment]
Good to know, someone could then see what broke it in the Swizzle pr!

**Comment by EliasM108** [comment]
Fixed in 1.0.5835!
