### ISSUE TITLE
Black textures in The Legend of Zelda: Breath of the Wild

### ISSUE THREAD

**Issue by d3ce1t** [Ryujinx/Ryujinx#1745]
### What's the issue you encountered?

The Legend of Zelda: Breath of the Wild renders black textures as shown in the image below:

![image](https://user-images.githubusercontent.com/3706385/99923664-07aa8900-2d37-11eb-8c64-cb5203727cd7.png)

### How can the issue be reproduced?

Just run Ryujinx 1.0.5796 (I haven't tested previous versions)

### Environment?

- Ryujinx Version: 1.0.5796</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Fedora 32 (Linux 5.9.8-100.fc32.x86_64)
  - CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  - GPU: X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.39.0, 5.9.8-100.fc32.x86_64, LLVM 10.0.1) (4.6 (Core Profile) Mesa 20.2.2)
  - RAM: 16GB
- Applied Mods : No

**Comment by SeraUQ** [comment]
hey could you try running Ryujinx with these parameters and try BOTW again
```
R600_DEBUG=nohyperz mesa_glthread=true vblank_mode=0 glsl_zero_init=true MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d"  ./Ryujinx
```

**Comment by d3ce1t** [comment]
Sure! This is how it looks like with `R600_DEBUG=nohyperz mesa_glthread=true vblank_mode=0 glsl_zero_init=true MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d"  ./Ryujinx`

![image](https://user-images.githubusercontent.com/3706385/99924197-84d6fd80-2d39-11eb-97e2-1443fcb70a59.png)

And It comes back to black with `mesa_glthread=true vblank_mode=0 glsl_zero_init=true MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d"  ./Ryujinx`

**Comment by AcK77** [comment]
the second rendering issue is due to https://github.com/Ryujinx/Ryujinx/issues/1733

**Comment by AcK77** [comment]
Since the rendering issue seems related to the MESA driver and the other one already got an opened issue, I close this one.

**Comment by d3ce1t** [comment]
BTW Could you link the issue from mesa here? Thanks!
