### ISSUE TITLE
Mary Skelter 2 Cutscene Crash

### ISSUE THREAD

**Issue by PyrotechnicAxe** [Ryujinx/Ryujinx#1761]
Ryujinx Version: 1.0.5837
Game Version: 1.0.0

OS: Windows 10 1909
CPU: Ryzen 5 1600 
GPU: 1060 6GB      
RAM: 16 GB

Shortly after Chapter 2 is a cutscene with a greyish filter. The background will start flickering and the emulator will consistently crash.

I have attached my save file and images to help reach the cutscene:

Load Save 1
Image 1: Go down a floor
Image 2: Go down a floor
Image 3:
1)pull lever
2)walk through unlocked door
3)pick up memo (mandatory fight)
4)use bamboo weaver skill to fill in the 2 holes (button b)
5)skip cutscene
6)skip cutscene

Now you are in chapter 2.

Move forward.
Turn right at fork.
Turn left at fork.
Skip cutscenes until you reach image 4.
Crash

[save.zip](https://github.com/Ryujinx/Ryujinx/files/5612924/save.zip)
![1](https://user-images.githubusercontent.com/53982134/100554931-3f409600-324d-11eb-80d1-9f104dbf7e05.png)
![2](https://user-images.githubusercontent.com/53982134/100554932-3fd92c80-324d-11eb-9406-1778f24a4ac2.png)
![3](https://user-images.githubusercontent.com/53982134/100554933-3fd92c80-324d-11eb-92a8-5dfa6ca890f5.png)
![4](https://user-images.githubusercontent.com/53982134/100554934-3fd92c80-324d-11eb-8b95-f4e8d2459b31.jpg)
[Ryujinx_2020-11-29_13-40-32.log](https://github.com/Ryujinx/Ryujinx/files/5612925/Ryujinx_2020-11-29_13-40-32.log)

**Comment by AcK77** [comment]
The log file doesn’t contains any useful informations since you have disabled them in your settings (I don’t know why). Please send a new log file with all default logging enabled.
It could be fine to provide a save game too, since we will probably don’t play 2 chapters to reach the bug!

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
