### ISSUE TITLE
Shader cache: crash on null invalid guest shader files

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#1768]
5900 is the testing version.
Animal Crossing loaded fine with the shaders from older build and it launched fine.
Games started fine and crashed when a weird square shape object appeared on the character (shader compiled maybe?)
After that the game didn't want to load from the Ryujinx launcher.
By deleting a specific shader (recommended by ripperoni) the issue was fixed.

![image](https://user-images.githubusercontent.com/2002038/100812466-5645da80-343d-11eb-93fc-057c160a7119.png)

Logs:
[Ryujinx_2020-12-02_00-56-55.log](https://github.com/Ryujinx/Ryujinx/files/5626202/Ryujinx_2020-12-02_00-56-55.log)
[Ryujinx_2020-12-02_01-03-14.log](https://github.com/Ryujinx/Ryujinx/files/5626203/Ryujinx_2020-12-02_01-03-14.log)
[Ryujinx_2020-12-02_01-04-23.log](https://github.com/Ryujinx/Ryujinx/files/5626204/Ryujinx_2020-12-02_01-04-23.log)

**Comment by GamerzHell9137** [comment]
Same is happening on Mario Tennis Aces

**Comment by AcK77** [comment]
It's still the case in lastest master build ?

**Comment by MetrosexualGarbodor** [comment]
Closing this as there's been no mention or reports even before the new shader cache was implemented, and as the new cache rebuilds or skips broken shaders, this should not happen anymore.
