### ISSUE TITLE
Unimplemented Fminnmp instruction

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1779]
### What CPU instruction is missing?

Fminnmp

```
Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000094e2c04 (opcode 0x7eb0c8a5) is undefined!
```

### Instruction name
```
fminnmp s5, v5.2s
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/165

**Comment by saldabain** [comment]
Is this supposed to be FMIN**N**MP? I could've find a reference document for FMINMP.

**Comment by EmulationFanatic** [comment]
Yes, sorry about that. I corrected the title!
