### ISSUE TITLE
Make the Profiled Persistent Translation Cache (PPTC) actually use all of the available CPU power

### ISSUE THREAD

**Issue by voidcat0** [Ryujinx/Ryujinx#1795]
### What's the issue you encountered?

The PPTC generation, _when a game has to be checked after a Ryujinx update, or after the PPTC has run enough times to actually generate a cache_, is only using ~40-50% of the available CPU power. I have noticed this behaviour since the introduction of the PPTC, and it seems to be not specific to any Ryujinx version, OS, or game in use, as I get the same results no matter what I use.

### How can the issue be reproduced?

Open a game that either has a PPTC which has to be checked, or generate one for a game by launching it a couple of times.

### Log file

Log files don't help here. Have a screenshot of the taskmanager during generation:
![grafik](https://user-images.githubusercontent.com/75008881/101719268-45cbda80-3aa3-11eb-9697-0947ac9cf549.png)

### Environment?

- Ryujinx version: 1.0.6006
  - I noticed this with any version which includes the PPTC
- System Specs:
  - OS: Operating System: Microsoft Windows 10.0.17763 (X64)
  - CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  - GPU: NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2 (4.6.0 NVIDIA 457.09)
  - RAM: 16GB (2x8GB - 2666Mhz)

### Additional context?
I am aware that his could be a hardware bottleneck on my side, like RAM bandwidth, as any other resource **but** the CPU is not used during generation. But I don't see any good way to test whether Ryujinx is bottlenecked by that.

**Comment by NielsGx** [comment]
Same on a Ryzen 7 3700x. Half cpu usage on all threads when launching a game (so using PPTC I guess (after +3 game launch)  0fps black screen)

**Comment by Powerlated** [comment]
https://github.com/Ryujinx/Ryujinx/blob/69f8722e795b0d76b84efa4de52e199e9441fca7/ARMeilleure/Translation/PTC/Ptc.cs

Looks like the amount of threads used is 3/4 of the maximum. Not sure why it's arbitrarily limited, the OS scheduler can easily take care of all cores being loaded at 100%.

**Comment by AcK77** [comment]
Accordingly to @LDj3SNuD this is fixed as far as possible in https://github.com/Ryujinx/Ryujinx/pull/2168
