### ISSUE TITLE
sockets: Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31 is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1803]
### What service call is missing?

Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31

There is no information for this service on Switchbrew or ReSwitched.

## Service description:
```
N/A
```

## Required by:

https://github.com/Ryujinx/Ryujinx-Games-List/issues/2966

**Comment by AcK77** [comment]
duplicate of https://github.com/Ryujinx/Ryujinx/issues/1440
