### ISSUE TITLE
Ghosting effect when upscaling Super Mario Party

### ISSUE THREAD

**Issue by NSR1997** [Ryujinx/Ryujinx#1813]
### What's the issue you encountered?

Ghosting effect when upscaling Mario Party 2x
![Example](https://user-images.githubusercontent.com/75617202/102027318-93965a80-3da3-11eb-827e-8ff3049e1fc2.jpg)

### How can the issue be reproduced?

Play Mario Party and upscale it 2x

### Log file
[Ryujinx_1.0.6006_2020-12-13_23-43-23.log](https://github.com/Ryujinx/Ryujinx/files/5685759/Ryujinx_1.0.6006_2020-12-13_23-43-23.log)
[Ryujinx_1.0.6006_2020-12-14_00-05-50.log](https://github.com/Ryujinx/Ryujinx/files/5685760/Ryujinx_1.0.6006_2020-12-14_00-05-50.log)
[Ryujinx_1.0.6006_2020-12-14_00-09-39.log](https://github.com/Ryujinx/Ryujinx/files/5685761/Ryujinx_1.0.6006_2020-12-14_00-09-39.log)

### Environment?

- Ryujinx version: 1.0.6006</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i5-8400 CPU @ 2.80GHz
  - GPU: Nvidia GeForce GTX 1060 6GB
  - RAM: 15.9 GB RAM
- Applied Mods : No

Update: Just tried the latest version of Ryujinx and it's still present

**Comment by MetrosexualGarbodor** [comment]
Fixed by #2763.
