### ISSUE TITLE
Remove long <-> ulong casts from Nvservices code

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#1820]
#### Overview:
Initially, the signed `long` type was being used for addresses on the emulator, this includes nvservices structs and the GPU memory manager. At some point they were changed to `ulong` as addresses and sizes are not really signed. This change made comparisons with those values easier and reduced the likelyhood of bugs caused by things like values being negative or sign-extended when they shouldn't. However, the structs were never updated, which means that there's a lot of code casting from long to ulong on nvservices.

The idea here is updating the structs so that the casts are no longer needed, and the code is cleaner.
Example of where such casts are needed today:
https://github.com/Ryujinx/Ryujinx/blob/8a6607540ea8933ef9f1f0ff40d910d5bfc3b600/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs#L100
It could be removed if the type of `Offset` was changed to `ulong`. There are more cases like this, most of them on this same class.

#### Nature of Request:  
Refactoring.

### Why would this feature be useful?
Would make the code cleaner and easier to understand.

**Comment by saldabain** [comment]
I can include this as part of the hotfix pr if you’d like

**Comment by gdkchan** [comment]
I'd prefer a separate PR fox that, just to make the review process easier (the improvement suggested here is not supposed to change how the code behaves).

**Comment by saldabain** [comment]
Sounds good
