### ISSUE TITLE
Option to prevent (display) standby while Ryujinx is running

### ISSUE THREAD

**Issue by voidcat0** [Ryujinx/Ryujinx#1829]
#### Overview:
Add an option to prevent display standby (possibly other power save options?) while Ryujinx is running.

#### Smaller Details: 
Some info for an implementation approach here: https://docs.microsoft.com/en-us/windows/win32/power/system-sleep-criteria?redirectedfrom=MSDN

#### Nature of Request:  
- Addition
  - Configuration toggle to prevent display standby  (and possibly other power save options?)
### Why would this feature be useful?
Longer cutscenes ingame, where no input is necessary, tend to trigger display standby depending on OS timeout settings. 

Sidenote: This is a common problem while using emulators (CEMU had the same problems) and windows (at least on some versions) not preventing display standby because gamepad input is not always counted as a proper wake-up event.

**Comment by EmulationFanatic** [comment]
This was closed by #1850
