### ISSUE TITLE
AppletAE ISelfController: 80 (SetWirelessPriorityMode) is not implemented

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx#1831]
### What service call is missing?

[4.0.0+] AppletAE ISelfController: 80 (SetWirelessPriorityMode) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#SetWirelessPriorityMode)

### Service description
```
Takes an input s32 #WirelessPriorityMode, no output. 
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/3204

**Comment by CrusadingNinja** [comment]
Also required by mGBA.

**Comment by AcK77** [comment]
> Also required by mGBA.

It's require `AppletAE ISelfController: 67 (IsIlluminanceAvailable)` not call 80.
