### ISSUE TITLE
Add the ability to choose the location of the nand folder

### ISSUE THREAD

**Issue by greggameplayer** [Ryujinx/Ryujinx#1832]
### What feature are you suggesting?
It would be awesome to be able to choose the location of the nand folder which includes games updates and dlc and shader caches.

### Why would this feature be useful?
It would permit to free some space on C Drive for example if it's an only 250GB SSD like mine.

**Comment by EmulationFanatic** [comment]
None of the items you've mentioned are stored in any NAND folder. But in any event you can use portable mode to specify whatever location you want for the Ryujinx system folder.
