### ISSUE TITLE
Add Setting to Toggle Disabling the Pop-Up that Prompts the User to Confirm Exit

### ISSUE THREAD

**Issue by hifihedgehog** [Ryujinx/Ryujinx#1853]
#### Overview:
-  Add the option to disable prompt to confirm exit, akin to the "confirm on close" setting in Dolphin.

#### Smaller Details: 
-   I have a need to close the emulator without a mouse on my arcade cabinet. The current pop-up prompt that requests the user to confirm they want to close the emulator causes a break in the user experience (UX) of my arcade front-end, Launchbox's BigBox.

#### Nature of Request:  
- Addition
  - Add a setting, similar to Dolphin's "confirm on close", that allows toggling the appearance of the pop-up prompting the user to confirm they wish to close the emulator.

### Why would this feature be useful?
Users will now be able to "silently" close the emulator without having to provide manual confirmation. This makes stopping emulation easy without having to access a mouse for those running the emulator via a ten-foot interface or an arcade front-end where only game controls are available.

**Comment by macabeus** [comment]
If it's a valid issue, I can solve that. Looks like a good beginner issue.
