### ISSUE TITLE
Contra Rogue Corps crash

### ISSUE THREAD

**Issue by Johnwrnd** [Ryujinx/Ryujinx#1855]
Contra Rogue Corps makes Ryujinx crash right after the intro with a InvalidMemoryRegionException.

My specs:
Windows 10 2004
GTX 1080ti (more in the log file)
i9900k
Ryujinx version: 1.0.6200

From some YouTube videos the game used to work. 

Hope it helps.
[Ryujinx_1.0.6200_2021-01-01_23-29-34.log](https://github.com/Ryujinx/Ryujinx/files/5759525/Ryujinx_1.0.6200_2021-01-01_23-29-34.log)

**Comment by jduncanator** [comment]
Hey @Johnwrnd 

Thanks for your interest in reporting this issue!

Issues like crashes, soft locks or problems with specific games are best reported on our game compatibility database. You can find the DB entry for your game [here](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1729). Feel free to leave the same information you left here there.

I'll close this issue, in lieu of you placing a report on the game DB!

Thanks :)
