### ISSUE TITLE
ns IApplicationManagerInterface: 0 (ListApplicationRecord) is not implemented

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#1860]
### What service call is missing?

Ns.IApplicationManagerInterface: 0 (ListApplicationRecord) is not implemented

[Switchbrew](https://switchbrew.org/wiki/NS_Services#ListApplicationRecord) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::ns::detail::IApplicationManagerInterface(0))

### Service description
```
Takes a type-0x6 output buffer containing an array of the below record and an s32 entry_offset, returns an output s32 out_entrycount.

Returns an array of entries with the below format using the specified offset and count.
```

### Required by: 

https://github.com/SunTheCourier/sys-clk-Editor

**Comment by EmulationFanatic** [comment]
Reformatted and filled in appropriate links.

**Comment by benderscruffy** [comment]
thanks for that

**Comment by MutantAura** [comment]
Required for JKSV: https://github.com/J-D-K/JKSV to boot.
[Ryujinx_1.1.106_2022-04-22_00-15-52.log](https://github.com/Ryujinx/Ryujinx/files/8535655/Ryujinx_1.1.106_2022-04-22_00-15-52.log)

**Comment by AcK77** [comment]
Why is that closed?
