### ISSUE TITLE
Menu item "Simulate Wake-up Message" keeps enabled even when a game is not running

### ISSUE THREAD

**Issue by macabeus** [Ryujinx/Ryujinx#1862]
### What's the issue you encountered?

There is no reason to keep this menu item available when a game is not running otherwise, a misclick will crash the emulator.

### How can the issue be reproduced?

Just open Ryujinx and click on this item.

### Additional context?

We should follow the same behavior of the menu item "Stop Emulator" (enabling when a game is running, otherwise disabling it)

**Comment by EmulationFanatic** [comment]
Executing the simulate wake-up message while not running the game does not crash the emulator for me. Instead, there is a red error message that pops up in the console, but I am able to keep using the emulator/launch a game normally.

**Comment by equin0x80** [comment]
Still happening for me in latest 1.1.1393 on Windows 10. When I clicked it (after stopping the game), the emulator crashed (log screen disappeared too fast to read).
