### ISSUE TITLE
Contra: Rogue Corps regression: crashes before getting in-game now

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1871]
### What's the issue you encountered?

[Contra: Rogue Corps](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1729) used to be playable, but now crashes during/after intros before going in-game.

### How can the issue be reproduced?

Use any version of the emulator after version 1.0.5525 and boot the game; the range-tracking update ([PR #1272](https://github.com/Ryujinx/Ryujinx/pull/1272)/1.0.5543) was the cause of this regression. 

### Log file

[CRC.log](https://github.com/Ryujinx/Ryujinx/files/5781415/CRC.log)

### Environment?

- Ryujinx version: 1.0.6235
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10 20H2
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : No

### Additional context?

This issue was largely tracked down by Github user [@Johnwrnd](https://github.com/Johnwrnd)

**Comment by gdkchan** [comment]
Should be fixed by #2083.
