### ISSUE TITLE
FAST RMX rendering is too bright

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1874]
### What's the issue you encountered?

The graphics in FAST RMX gameplay are too bright.

### How can the issue be reproduced?

Boot up FAST RMX and start a race.

### Log file

[Ryujinx_1.0.6241_2021-01-07_09-04-14.log](https://github.com/Ryujinx/Ryujinx/files/5782693/Ryujinx_1.0.6241_2021-01-07_09-04-14.log)

### Environment?

- Ryujinx version: 1.0.6235 but also tried with the [Yo-kai fix PR](https://github.com/Ryujinx/Ryujinx/pull/1870) just in case.
- Game version: 1.0
- System Specs:
  - OS: Windows 10 20H2
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : No

### Additional context?

![2021-01-07 09_05_48-Ryujinx 1 0 6241 - FAST RMX v1 0 (01009510001CA000) (64-bit)](https://user-images.githubusercontent.com/62343878/103915104-fee3fb80-50c7-11eb-9d3b-be4c37ff0157.png)
![2021-01-07 09_06_00-Ryujinx 1 0 6241 - FAST RMX v1 0 (01009510001CA000) (64-bit)](https://user-images.githubusercontent.com/62343878/103915123-05727300-50c8-11eb-84ae-fac0c7702e01.png)

**Comment by CrusadingNinja** [comment]
Fixed by #2335
