### ISSUE TITLE
Monster Hunter Rise Demo

### ISSUE THREAD

**Issue by fuhuan416** [Ryujinx/Ryujinx#1877]
It can enter the main menu and automatically close the simulator in the loading interface after selecting weapons

[Ryujinx_1.0.6250_2021-01-09_01-08-40.zip](https://github.com/Ryujinx/Ryujinx/files/5788530/Ryujinx_1.0.6250_2021-01-09_01-08-40.zip)

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3239

**Comment by fuhuan416** [comment]
> [Ryujinx/Ryujinx-Games-List#3239](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3239)

Thank you for your reply. I think I can give further feedback later

**Comment by EmulationFanatic** [comment]
As we are tracking various issues regarding this game individually, closing this.
