### ISSUE TITLE
pctl IParentalControlService: 1018 (IsFreeCommunicationAvailable) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1883]
### What service call is missing?

pctl IParentalControlService: 1018 (IsFreeCommunicationAvailable) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Parental_Control_services#IParentalControlService) | 

### Service description
```
N/A
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/3239

**Comment by MisterPrintf** [comment]
This service returns a bool of True or False, correct?

**Comment by EmulationFanatic** [comment]
> This service returns a bool of True or False, correct?

Needs to be RE'd to determine that, as there's nothing on Switchbrew or Reswitched indicating what it returns.
