### ISSUE TITLE
Auto-updater has committed ritual seppuku

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1887]
### What's the issue you encountered?

The "Check for Updates" option is greyed out, and the application no longer checks for updates.

### How can the issue be reproduced?

Open Ryujinx. The "Check for Updates" option is greyed out, and the application no longer checks for updates.

### Environment?

- Ryujinx version: Any recent version

- System Specs:
  - OS: Windows 10 20H2
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : N/A

### Additional context?

This seems to have started when the GUI refactor part 1 PR was merged.

**Comment by AcK77** [comment]
Fixed in https://github.com/Ryujinx/Ryujinx/commit/d684d71c4f04163e35361b2c1a8bdefa7e470d82
