### ISSUE TITLE
Dpad Up and Dpad Left Inputs do not register when be pressed them in the setting up controllers GUI menus

### ISSUE THREAD

**Issue by chriswinslow** [Ryujinx/Ryujinx#1888]
### What's the issue you encountered?

[ When trying to configure my Sega Saturn joypad via USB, the Dpad Up and Dpad Left Inputs do not register. the Down and Right directions register okay and so does all the other buttons for that matter, but when I press the up or left nothing happens. Here are the following values in the config file
        "dpad_up": "Axis1",
        "dpad_down": "Axis1",
        "dpad_left": "Axis0",
        "dpad_right": "Axis0"
I'm selecting Controller/0 (Unmapped Controller) as the input device and  I'm choosing Controler Type as the Pro Controller]</br>
[ Did you make any changes related to Ryujinx itself? No ]</br>

### How can the issue be reproduced?

[ As mentioned above. ]

### Log file

"N/A"

### Environment?

- Ryujinx version: 1.0.6269</br>
- Game version: "N/A"</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i9-9900K*
  - GPU: *NVIDIA GTX 1080*
  - RAM: *32GB*

**Comment by EmulationFanatic** [comment]
Please come to Discord for support and we'll try to troubleshoot the issue.

**Comment by chriswinslow** [comment]
Wow, thanks for your help talk about having a chip on your shoulder

**Comment by EmulationFanatic** [comment]
I didn't realize that offering personalized help on Discord was a bad thing. Suit yourself.
