### ISSUE TITLE
hid IHidServer: 134 (SetNpadAnalogStickUseCenterClamp) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1891]
### What service call is missing?

HID IHidServer: 134 (SetNpadAnalogStickUseCenterClamp) is not implemented

[Switchbrew](https://switchbrew.org/wiki/HID_services#SetNpadAnalogStickUseCenterClamp) | 

### Service description
```
Takes a PID, a bool, an AppletResourceUserId, no output.
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/3242

**Comment by benderscruffy** [comment]
used in Power Pro Kun Pocket R [01000C4015030000]

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4413 is another game that asks for it.

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4930 Another game.
