### ISSUE TITLE
appletAE ILibraryAppletCreator: 12 (CreateHandleStorage) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1896]
### What service call is missing?

ILibraryAppletCreator: 12 (CreateHandleStorage) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#CreateHandleStorage) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::am::service::ILibraryAppletCreator(12))

### Service description
```
Takes an input copy-handle and an input s64, returns an #IStorage. In some cases the s64 must not have the negative bit set.

The input can be arbitrary, however official sw is only (?) known to use this for TransferMemory (with s64=size).
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/511

**Comment by GamerzHell9137** [comment]
Its necessary for MH Rise too to use the chat in game.
