### ISSUE TITLE
Xenoblade 2 : Textures bug

### ISSUE THREAD

**Issue by eruxxn36** [Ryujinx/Ryujinx#1898]
### What's the issue you encountered?

xenoblade 2 in Ryujinx 1.0.6291 (mostly ok)

but sometime has wrong

main problem is in the Texture (like picture)

![01](https://user-images.githubusercontent.com/72922836/104310837-58f12080-550f-11eb-9380-e64fb09f0d5a.jpg)

![002](https://user-images.githubusercontent.com/72922836/104310856-61e1f200-550f-11eb-880c-0053b4ab0888.jpg)

### How can the issue be reproduced?

in game everywhere

### Log file

[Ryujinx_1.0.6291_2021-01-12_19-25-53.log](https://github.com/Ryujinx/Ryujinx/files/5801840/Ryujinx_1.0.6291_2021-01-12_19-25-53.log)

### Environment?

- Ryujinx version:ryujinx-1.0.6291-win_x64</br>

- Game version: 1.0X</br>

- System Specs:
  - OS: * Windows 7 SP 1 (6.1)*
  - CPU: * Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz*
  - GPU: *NVIDIA GTX 1066*
  - RAM: *16GB*
  
- Applied Mods : [ No ]

### Additional context?

hope the bug can fix

Thanks the devs for making the Ryujinx again

thanks

**Comment by jduncanator** [comment]
Hey @eruxxn36 

Thanks for your interest in reporting this issue!

Problems like crashes, soft locks or graphical issues with specific games are best reported on our game compatibility database. You can find the DB entry for your game [here](https://github.com/Ryujinx/Ryujinx-Games-List/issues/159). Feel free to leave the same information you left here on the Game DB entry, and someone will take a look.

I'll close this issue, in lieu of you placing a report on the game DB!

Thanks 😄

**Comment by ExE-Boss** [comment]
This is because of <https://github.com/Ryujinx/Ryujinx/issues/1620>, since the two games use a similar engine.
