### ISSUE TITLE
Xenoblade Chronicles 2 grass/texture bug

### ISSUE THREAD

**Issue by RoloTelechea** [Ryujinx/Ryujinx#1904]
## Bug Report

There appears to be a glitch in the grass textures. 

### What's the issue you encountered?

The color appears yelow instead of being green. 

### How can the issue be reproduced?

This glitch moves whith the camera as well as walking arround; i think it has something to do with the way Ryujinx manage the textures; it is my humble opinion of course. I tried everything, including setting the resolution scaler to 10x; this in particular made the bug almost unnoticeable.  

It seems that, the higher the scaling is, the less noticeable the bug becomes (more info in the screenshots at the end).

I also tried uninstalling the mod that i'm using (remove AA, better bloom [all in one file]) but this doesn't seem to be the issue so i guess it's on the emulator side of things.

By the way, i first encountered this issue in the Gormott Province (one of the first areas of the game).

### Log file

https://www.docdroid.net/KOxsN4V/ryujinx-106276-2021-01-10-14-26-47-txt

### Environment?

- Ryujinx version: 1.0.6276 and 1.0.6308 (only the second screenshot with the same problem still)

- Game version: 2.0.2 w/ DLC's; XCI file. 

- System Specs:

-Operating System: Microsoft Windows 10.0.19042 (X64)
-CPU: AMD Ryzen 5 3600 6-Core Processor 
-GPU: Nvidia RTX 2060 Super             
-Total RAM: 16328 MB
-Logs Enabled: Info, Warning, Error, Guest, AccessLog, Stub
-Configured Controller ProController to Player1 (Xbox One Controller via USB)
-Using Firmware Version: 11.0.1
-Applied Mods : removeaa (modifies AA and Bloom resolution In-Game)

### Additional context?

The image below shows the game running at 2x game resolution.
![XC2-1](https://user-images.githubusercontent.com/77363955/104384675-d7de5d00-54ff-11eb-96d2-d61448db573c.png)

And this one shows the game running at 10x game resolution. As shown in this screenshot the problem is much les prominent that the one at a lower resolution.
![image](https://user-images.githubusercontent.com/77363955/104385056-87b3ca80-5500-11eb-954d-2fef161a4d6f.png)

Hope this can help the developers to fix this issue.
Thanks for the hard work at the Ryujinx Team.

**Comment by jduncanator** [comment]
Hey @RoloTelechea 

Thanks for your interest in reporting this issue!

Problems like crashes, soft locks or graphical issues with specific games are best reported on our game compatibility database. You can find the DB entry for your game [here](https://github.com/Ryujinx/Ryujinx-Games-List/issues/159). Feel free to leave the same information you left here there, and someone will take a look.

I'll close this issue, in lieu of you placing a report on the game DB!

Thanks 😄
