### ISSUE TITLE
Dragon Quest XI S problems

### ISSUE THREAD

**Issue by tazevam** [Ryujinx/Ryujinx#1907]
## Bug Report

It can run on the new version, but have some graphics problems. and when i want go to the bridge, it's stuck..

btw: maybe need 10-20minute to load game.

### What's the issue you encountered?
![1](https://user-images.githubusercontent.com/73407337/104412547-71147e80-55a7-11eb-9351-98c8fd93f9b8.PNG)
![2](https://user-images.githubusercontent.com/73407337/104412555-740f6f00-55a7-11eb-87cb-ca8bba0e74f3.PNG)
![3](https://user-images.githubusercontent.com/73407337/104412557-75409c00-55a7-11eb-8a7d-1dfd095577df.PNG)

### How can the issue be reproduced?
Start game for a while.

### Log file
[Ryujinx_1.0.6309_2021-01-13_12-19-12.log](https://github.com/Ryujinx/Ryujinx/files/5806647/Ryujinx_1.0.6309_2021-01-13_12-19-12.log)

### Environment?
- Ryujinx version: 1.0.6309
- Game version: 1.0.4

- System Specs:
  - OS: Windows 10
  - CPU: I3-8350k
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : [ No ]

### Additional context?
thank for the hardwork!

**Comment by jduncanator** [comment]
Hey @tazevam 

Thanks for your interest in reporting this issue!

Issues like crashes, soft locks or problems with specific games are best reported on our game compatibility database. You can find the DB entry for your game [here](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1723). Feel free to leave the same information you left here there.

I'll close this issue, in lieu of you placing a report on the game DB!

Thanks :)
