### ISSUE TITLE
Excessive VRAM usage in Hyrule Warriors Age of Calamity

### ISSUE THREAD

**Issue by skull-01** [Ryujinx/Ryujinx#1915]
### What's the issue you encountered?
While playing Age of Calamity, VRAM usage increases as you continue to play. This happens using native resolution and the resolution scaler. All default settings and using shader cache. Doing nothing special; the issue happens to whatever stage you play.

### How can the issue be reproduced?
Can be reproduced by just playing the game. The longer you play, the more VRAM it uses. The emulator will crash once you’ve out of VRAM.
If you use resolution scaler, VRAM will be used faster.

### Log file
I’m attaching two sets of logs.
1.	Native resolution
2.	Using x3 resolution scale
I am also attaching the VRAM log usage for both cases. 
[Test 1 Native - No Crash Shader Cache on.zip](https://github.com/Ryujinx/Ryujinx/files/5816224/Test.1.Native.-.No.Crash.Shader.Cache.on.zip)
[Test 2 res scale x3 crash.zip](https://github.com/Ryujinx/Ryujinx/files/5816229/Test.2.res.scale.x3.crash.zip)

### Environment
Ryujinx version: 1.0.6318
Age of Calamity 1.01
- System Specs:
  - OS: Windows 10 20H2
  - CPU: i7 9700
  - GPU: NVIDIA RTX 3090
  - RAM: 32 GB
- Applied Mods :  No

**Comment by gdkchan** [comment]
FIxed by #2001.
