### ISSUE TITLE
Iris Plus Gen11 broken opengl

### ISSUE THREAD

**Issue by IGCIT** [Ryujinx/Ryujinx#1916]
In latest builds opengl is broken on intel hw, at least for gen11
windows 10, latest build, latest intel driver

![Capture2](https://user-images.githubusercontent.com/76787191/104663935-5852b880-56ce-11eb-80c6-08b91a5118f9.JPG)
![Capture4](https://user-images.githubusercontent.com/76787191/104663940-5983e580-56ce-11eb-8e2f-60062b462cda.JPG)
![Capture](https://user-images.githubusercontent.com/76787191/104663951-5db00300-56ce-11eb-8421-994b144d3fa2.JPG)

pokemon has glitched shadows and other games have some issues too

logs from sky force
[Ryujinx_1.0.6318_2021-01-15_01-01-49.log](https://github.com/Ryujinx/Ryujinx/files/5817601/Ryujinx_1.0.6318_2021-01-15_01-01-49.log)

linux has opengl issues too, please let me know if you need a separate issue for that

**Comment by EmulationFanatic** [comment]
Was this working on previous builds? We are used to seeing much worse than this on most Intel iGPUs.

**Comment by IGCIT** [comment]
i tried few older windows builds and its a bit worse there, while on linux i was playing just fine with latest build from 1-2 weaks ago

**Comment by EmulationFanatic** [comment]
It is unlikely that Intel will fix their OpenGL drivers any time soon. Most Intel iGPUs won't even boot Pokemon games.
For this reason we can only recommend either using another GPU where possible, or waiting for Vulkan to be implemented (we are aiming for a 2021 release). Feel free to join our [Discord server](https://discord.gg/Ryujinx) for more up-to-the-minute news on the emulator's progress!

**Comment by IGCIT** [comment]
Intel is working hard on fixing their drivers, ogl issues in ryujinx will be fixed at some point with your help.

Since now there is a quicker and easier way to solve these problems, i opened this issue to let you know the current state of the emulator.
There are many handheld devices out there that can only use iGPUs for obvious reasons, i m aware there are many many issues, but the hardware itself is capable, it just needs some love :)

My hope is that everyone (including me :P) will be able to enjoy your amazing work on Intel GPUs, with both OGL and Vulkan!
