### ISSUE TITLE
can open settings tab ryujinx idn2 

### ISSUE THREAD

**Issue by chrisplays115** [Ryujinx/Ryujinx#1918]
when ever i try to open the settings tab it tells me this look at log file below
[Ryujinx_1.0.0-ldn2_2021-01-15_15-36-29.log](https://github.com/Ryujinx/Ryujinx/files/5823415/Ryujinx_1.0.0-ldn2_2021-01-15_15-36-29.log)
ive updated the firmware and added the product keys i have openal

**Comment by JaviBOT96** [comment]
Hey There, paste the following file in your Ryujinx ldn2 folder. It'll fix it. 




[Config.zip](https://github.com/Ryujinx/Ryujinx/files/5823467/Config.zip)

**Comment by chrisplays115** [comment]
> Hey There, paste the following file in your Ryujinx ldn2 folder. It'll fix it.
> 
> [Config.zip](https://github.com/Ryujinx/Ryujinx/files/5823467/Config.zip)

still not working

**Comment by chrisplays115** [comment]
worked thanks
