### ISSUE TITLE
Range list interval overlaps optimization

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#1925]
#### Overview:
Currently, the range list implementation performs linear search on the `FindOverlaps` method. The purpose of this method is finding all ranges that overlaps with the range that is passed as argument. This can be improved with the use of interval trees, a data structure designed for fast insertion, removal and lookup of intervals.

#### Smaller Details: 
This can be currently used by `RangeList` and `MultiRangeList`, which can be found on the `Ryujinx.Memory` project, under `Range`. The method to be optimized is the `FindOverlaps` method. There is also a `FindOverlapsNonOverlapping`, which can find overlap in O(log2(n)+m) time in the worst case, where n is the total number of intervals in the list, and m the number of overlaps. However this only works if none of the intervals in the list overlap with each other, which is the case for the buffer cache, but not for the texture cache. A fast `FindOverlaps` implementation would make the `FindOverlapsNonOverlapping` method obsolete, and all uses could be replaced by `FindOverlaps`.

#### Nature of Request:  
This is a optimization. It should greatly improve speed of texture creation. It will not improve peak performance, but should reduce stuttering caused by texture creation a little bit.

**Comment by jduncanator** [comment]
> There is also a FindOverlapsNonOverlapping, which can find overlap in O(log2(n)+m) time in the worst case, where n is the total number of intervals in the list, and m the number of overlaps. However this only works if none of the intervals in the list overlap with each other, which is the case for the buffer cache, but not for the texture cache. A fast FindOverlaps implementation would make the FindOverlapsNonOverlapping method obsolete, and all uses could be replaced by FindOverlaps.

For reference, an interval tree has the same complexity (`O(log(n)+m)`) in all instances, with overlapping and non-overlapping ranges, so is an appropriate "drop-in" replacement.

**Comment by saldabain** [comment]
I'll take a look into this one. I may need to modify the TreeDictionary class a bit so I can leverage it when creating an IntervalTree class.

**Comment by gdkchan** [comment]
Ok, assigned to you.
