### ISSUE TITLE
PS4 Controller wrong mapping

### ISSUE THREAD

**Issue by Subject-1101** [Ryujinx/Ryujinx#1941]
### What's the issue you encountered?

everytime i try to map any button on my ps4 controller it uses that one button for every time i try to set another button
like i press cross for A and every other button you press to assign will be assigned cross automatically </br>
i did not modify Ryujinx at all because i no not a single scrap of c#

### How can the issue be reproduced?

1.start computer
2.run Linux
3.Connect controller
4.run Ryujninx 
5.attempt to set up input with ps4 controller

### Log file

00:00:00.339 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-dirty
00:00:00.672 |N| Application PrintSystemInfo: Operating System: Linux 5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 (X64)
00:00:00.672 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
00:00:00.672 |N| Application PrintSystemInfo: Total RAM: 15941 MB
00:00:00.674 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub

### Environment?

- Ryujinx Version: 1.0.0-dirty</br>
- System Specs:
  - OS: *Linux 5.10.7-arch1-1 #1 SMP PREEMPT*
  - CPU: *ntel(R) Core(TM) i7-9700F CPU @ 3.00GHz*
  - GPU: *e.g. NVIDIA RTX 2060*
  - RAM: *16GB*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
NA

**Comment by Doctorwho1909** [comment]
https://ci.appveyor.com/project/gdkchan/ryujinx/builds/37322963/artifacts try this build it has a Pr that fixes many controller issues

**Comment by Subject-1101** [comment]
yeah thanks dude that release solves all my problems.
hope this gets incoperated into the main repository soon.
