### ISSUE TITLE
Add an extra support for Ryujinx 

### ISSUE THREAD

**Issue by inkling-shop** [Ryujinx/Ryujinx#1944]
## Feature Request

Add extra support 
### What feature are you suggesting?
Hello there, This issue is opened with the main objective of getting more staff for Ryujinx. Currently the most active support member is GoffyDude. I know support is volunteer but you can try to add more support staff then goffy won't be so loaded of work. 

#### Smaller Details: 
Implementation method: Right click on the member you consider > roles > add staff or role you want. 

### Why would this feature be useful?
This would be helpful for patrons and regular members which need accurate assistance, in this way they'll know who to contact if they need assistance with something related with the emulator.

**Comment by inkling-shop** [comment]
GoffyDude does an Amazing job. But big minds big backup sometimes.

**Comment by EmulationFanatic** [comment]
As much as I approve of this product and/or service, this is not a Ryujinx-related development issue. 
If someone would like to be support staff, they need only demonstrate a basic level of familiarity with support items, and hang out in the #support channel on our Discord server.

**Comment by inkling-shop** [comment]
> 
> 
> As much as I approve of this product and/or service, this is not a Ryujinx-related development issue.
> If someone would like to be support staff, they need only demonstrate a basic level of familiarity with support items, and hang out in the #support channel on our Discord server.

If  someone applies for support, how long will he/she  would need to wait?

**Comment by EmulationFanatic** [comment]
It depends on that person's quality & quantity of support offered to those who come in requesting it.
