### ISSUE TITLE
Swkbd applet does not pop-up properly in fullscreen mode

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1970]
### What's the issue you encountered?

When trying to play a game that uses the swkbd applet while in fullscreen, the moment the swkbd applet pops up the game basically goes dead and unless the end user knows what to look for, they might think the game has frozen. One must alt-tab out to get to the applet.

### How can the issue be reproduced?

Play a game in fullscreen that uses the swkbd applet like Fate/EXTELLA LINK, MHGU, etc.

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.6432
- Game version: Any
- System Specs:
N/A

**Comment by Caian** [comment]
I believe a quick solution would be to put the game back in windowed mode so the keyboard can show properly and restore to fullscreen after the input.

**Comment by Caian** [comment]
@EmulationFanatic which OS are you using? I couldn't reproduce the issue on Windows 10 / Ryu 1.0.6551. The keyboard window appears on top of the fullscreen game as expected.

Tested creating a new character on both Fate/EXTELLA LINK and MHGU.

**Comment by EmulationFanatic** [comment]
This is no longer happening.

**Comment by Caian** [comment]
I managed to reproduce this issue by toggling between windowed and back to fullscreen after a first input dialog has been shown:

- Launch a game windowed
- Toggle fullscreen
- Do something that requires input (pop-up should appear)
- Close the pop-up
- Toggle windowed and then back to fullscreen
- Do something that requires input (pop-up should not appear but should still receive input)
- Losing focus of the game window should make the pop-up appear

I believe this is a bug in GTK itself and a quirk related to how fullscreen windows work.

Are there any upcoming changes in the GUI framework that make this problem disappear by itself?
