### ISSUE TITLE
Yo Kai Gakuen Y save data could not be loaded

### ISSUE THREAD

**Issue by tfqmstrmnd** [Ryujinx/Ryujinx#1979]
### What's the issue you encountered?

Yo Kai Gakuen Y save data could not be loaded

### How can the issue be reproduced?
every start the game, choose continue and select the save data the notification pop up and said save data couldn't be loaded 

### Log file

[Ryujinx_2020-11-22_14-17-34.log](https://github.com/Ryujinx/Ryujinx/files/5897048/Ryujinx_2020-11-22_14-17-34.log)

[Ryujinx_2020-11-28_04-45-21.log](https://github.com/Ryujinx/Ryujinx/files/5897057/Ryujinx_2020-11-28_04-45-21.log)

### Environment?

    Ryujinx version: 1.0.6455

    Game version: 3.0.1

    System Specs:
        OS: (e.g. Windows 10)
        CPU: (e.g. i7-9750)
        GPU: (e.g. NVIDIA GTX 1050 Ti)
        RAM: (e.g. 8GB)

    Applied Mods : [ No ]

### Additional context?

![Ryujinx 1 0 6455 1_30_2021 7_33_00 AM](https://user-images.githubusercontent.com/74163672/106341159-dfa74b00-62ce-11eb-8d9d-20809b854adb.png)
![Ryujinx Console 1 0 6455 1_30_2021 7_35_11 AM](https://user-images.githubusercontent.com/74163672/106341164-e1710e80-62ce-11eb-86cc-02f3db67e44a.png)
![Ryujinx 1 0 6455 - 妖怪学園Y ～ワイワイ学園生活～ v3 0 1 (010051D010FC2000) (64-bit) 1_30_2021 7_31_19 AM](https://user-images.githubusercontent.com/74163672/106341176-e7ff8600-62ce-11eb-8de7-5804b315c266.png)

**Comment by gdkchan** [comment]
Does this happen 100% of the time after starting a new game, saving, then trying to load the save? Your save data might just be corrupt.

**Comment by tfqmstrmnd** [comment]
yes sir, when I compare with yuzu save data dis is
![Uploading 010051D010FC2000 2_5_2021 5_40_33 PM.png…]()
 the difference
*yuzu can't boot dis game perfectly like ryujinx

**Comment by tfqmstrmnd** [comment]
![0 2_5_2021 5_40_42 PM](https://user-images.githubusercontent.com/74163672/107024546-c45ea300-67da-11eb-9981-df2b1086f73b.png)
![010051D010FC2000 2_5_2021 5_40_33 PM](https://user-images.githubusercontent.com/74163672/107024580-ccb6de00-67da-11eb-9e77-713ee381f859.png)

**Comment by tfqmstrmnd** [comment]
is in the ptc save: save profiling info, profiled functions always smaller than the size?

**Comment by tfqmstrmnd** [comment]
USERDATA00 folder doesn't exist

**Comment by tfqmstrmnd** [comment]
any tips? maybe

**Comment by AcK77** [comment]
Could you try again with the latest Ryujinx version and tell us if the issue still occurs please ?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
