### ISSUE TITLE
Scaling issue in steam world Dig 2 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#198]
so i found a scaling issue in steam world dig 2 
![scaleing is bad on steam world dig 2](https://user-images.githubusercontent.com/18043258/42060231-8a5b2aac-7afc-11e8-9a35-4f7c5621a43e.PNG) just trying to help out again and thanks for stardew valley fix

**Comment by BSoDGaming** [comment]
The scaling issue appears to be fixed in latest Master (1.0.1138)

![desktop screenshot 2018 07 19 - 14 50 03 00](https://user-images.githubusercontent.com/30404120/42943527-4ea55376-8b63-11e8-9f2e-76c1c1db6a00.png)
