### ISSUE TITLE
Let's Go Pikachu/Eevee doesn't connect on LDN2.1 & LDN2

### ISSUE THREAD

**Issue by Priestyle** [Ryujinx/Ryujinx#1980]
Let's Go Pikachu/Eevee games don't connect with each other on LDN2.1 & LDN2
Pokemon Sword and Shield worked for me.
I also tried testing on both computers and they still didn't connect. The "Hosted Player" & "Multi Player" counts remained at 1 even though I had two instances of LDN2.1 open.

**Comment by EmulationFanatic** [comment]
There are many games that do not connect on LDN. For now we are using the tagging/labeling feature on the gamedb to keep track of this. However, others have had success with the Pokemon Let's Go franchise. In either case, We don't need an issue on the main repo at this time. We'll take this into consideration, do some testing, and adjust labels accordingly!
