### ISSUE TITLE
Super Robot Wars T - Breast Fire from Mazinger Z hangs the emulator

### ISSUE THREAD

**Issue by TimeStreamer** [Ryujinx/Ryujinx#1984]
## Bug Report
</br>

### What's the issue you encountered?

When viewing the Breast Fire attack from Mazinger Z (note that is Mazinger Z not Great Mazinger) the emulator stops responding when rendering the robot attack.

EDIT: In the exact same map using Thunder Break attack from Great Mazinger also puts the emulator into major slowdown, with 95% of the times resulting into an hang up state of "not responding". I've noticed both attacks are very graphically intensive.

### How can the issue be reproduced?

You must play the game unitl scenario 13/14 and use Breast Fire attack against any enemy.

### Log file

[Log+Save.zip](https://github.com/Ryujinx/Ryujinx/files/5908517/Log%2BSave.zip)

### Environment?

- Ryujinx version: 1.0.6471</br>
- Game version: 1.0.5</br>

- System Specs:
  - OS:  Windows 10
  - CPU: i7-8700
  - GPU: Radeon Vega 64
  - RAM: 16GB
  - 
- Applied Mods : No

### Additional context?

I also noticed that the game has MAJOR fps drops the first time it does something (first time entering the game, first time in each menu, first stage, first attack, animation cutscene etc.) . Also I'm unable to use PPTC. The game NEVER boots while I'm using it. 

Please note that the save was done with the above game version but also with all DLC's included. Unfortunately, if i try to do a mid-mission suspend save right before the issue the emulator also locks up, so this is the best I can do. You must load the game, skip past the mission story dialogs and select a bunch of units to play the mission (use the ones with most level, including Mazinger Z and Great Mazinger). Thunder Break attack from Great Mazinger requires some morale, which means in order to test it some enemies of the map must die first. However Breast Fire from Mazinger Z is available from the start, so you can try by testing with him.

</br>

**Comment by choppymaster** [comment]
Full log file as "file"?

**Comment by EmulationFanatic** [comment]
Please include a full copy of the log, as well as a save file that can be used to attempt to reproduce the issue.

**Comment by TimeStreamer** [comment]
Here is a zip with my current save and the log file. Please note that the save was done with the above game version but also with all DLC's included. Unfortunately, if i try to do a mid-mission suspend save right before the issue the emulator also locks up, so this is the best I can do. You must load the game, skip past the mission story dialogs and select a bunch of units to play the mission (use the ones with most level, including Mazinger Z and Great Mazinger). Thunder Break attack from Great Mazinger requires some morale, which means in order to test it some enemies of the map must die first. However Breast Fire from Mazinger Z is available from the start, so you can try by testing with him. I'll wait for your feedback. Best of luck.

[Log+Save.zip](https://github.com/Ryujinx/Ryujinx/files/5908510/Log%2BSave.zip)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
