### ISSUE TITLE
Not Building

### ISSUE THREAD

**Issue by PiXeL-AtOr** [Ryujinx/Ryujinx#1989]
When trying to build with NET core I get this error on mac:

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file. 

Could anyone help me, please?

**Comment by EmulationFanatic** [comment]
The macOS client is essentially in a non-working state, though I'm sure there would be a fix for the issue you're having at the build stage. Your best course of action would be to use boot camp to dual boot with Windows and build it there.
