### ISSUE TITLE
Mario Kart 8 freezes system on radeonsi

### ISSUE THREAD

**Issue by toccata10** [Ryujinx/Ryujinx#1992]
### What's the issue you encountered?
A few seconds during the bginning of a track (before the green light), the system freezes and I need to reboot.

### How can the issue be reproduced?
N/A

### Environment?

- Ryujinx version: 1.0.X</br>
Difficult to say as I compiled it.
- Game version: 1.7</br>
- System Specs:
  - OS: ArchLinux
  - CPU: i8700k
  - GPU: R9 fury
  - RAM: 16GB
- Applied Mods : 4k upscaling

### Additional context?
Additional info about your environment:</br>
I captured an apitrace: https://www.dropbox.com/s/2gwvit1b7kw3eel/Ryujinx.MK8.trace.7z?dl=0
It replays with a lot of warnings like:
```
7049338: warning: glGetError(glCopyImageSubData) = GL_INVALID_VALUE
7049364 @1 glCopyImageSubData(srcName = 6006, srcTarget = GL_TEXTURE_CUBE_MAP_ARRAY, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 7486, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 0, dstY = 0, dstZ = 11, srcWidth = 128, srcHeight = 128, srcDepth = 1)
```
So, I prefered to submit here instead of a mesa bug.

[Ryujinx-trace-replay.txt](https://github.com/Ryujinx/Ryujinx/files/5914728/Ryujinx-trace-replay.txt)
[Ryujinx_1.0.0-dirty_2021-02-02_22-38-35.log](https://github.com/Ryujinx/Ryujinx/files/5914729/Ryujinx_1.0.0-dirty_2021-02-02_22-38-35.log)
[Ryujinx_1.0.0-dirty_2021-02-02_22-28-10.log](https://github.com/Ryujinx/Ryujinx/files/5914730/Ryujinx_1.0.0-dirty_2021-02-02_22-28-10.log)

**Comment by EmulationFanatic** [comment]
Can you re-test with an official build?

**Comment by toccata10** [comment]
At least with the official build, the problem seems to be present only at x3 upscaling (but 100% reproductible: select DonkeyKong track, it freezes before starting the race). I tried a few races at x2 without problem. So I changed the title to reflect this.

**Comment by MetrosexualGarbodor** [comment]
Closing as this seems to be either solved already or a Mesa or user issue.
