### ISSUE TITLE
3D world doesnt work without missing services

### ISSUE THREAD

**Issue by mjcox244** [Ryujinx/Ryujinx#2015]
### What's the issue you encountered?

3d world crashes after player select
stock master and ldn build

### How can the issue be reproduced?

open 3dw + fury
select 3d world
pick your player
crash

### Log file
from Ga1act1c#6420
[Ryujinx_1.0.0-ldn2.1_2021-02-11_11-25-17.log](https://github.com/Ryujinx/Ryujinx/files/5967995/Ryujinx_1.0.0-ldn2.1_2021-02-11_11-25-17.log)

### Environment?

- Ryujinx version: 1.0.0-ldn2.1(log file) also 1.0.6546

- Game version: 1.0.0

- System Specs: (my one idk Ga1act1c's)
  - OS : windows 10
  - CPU:  i5 8400H
  - GPU:  GTX 1050
  - RAM:  8GB
- Applied Mods : no

**Comment by Shahil-Ayato** [comment]
For now use the ignore missing services Hack but eventually a new build with the service will come out :D

**Comment by mjcox244** [comment]
i know just reporting it for futre refrence

**Comment by AcK77** [comment]
Fixed in #2014.
LDN Build will be rebased later.
