### ISSUE TITLE
Please move all interaction between ARMeilleure and the rest of the emulator to an interface level in Ryujinx.Cpu

### ISSUE THREAD

**Issue by HorseTrain** [Ryujinx/Ryujinx#2025]
## Feature Request

I believe that ryujinx should be completely independent from the cpu, as in nothing should depend on ARMeilleure. This would make it much easier for contributors to test their own cpu emulators, and would allow changes in the cpu to not affect the rest of the project.

My ideas to implement this:

The only thing that should depend on ARMeilleure should be Ryujinx.Cpu. Ryujinx.Cpu include "Universal Interfaces"

E.g.

The interface would look like
```cs
public delegate void Hook(object Data);

interface CpuContext
{
    public int ID   { get; set; }
    public ulong GetX(int index);
    public void SetX(int index, ulong value);
    public Vector128<float> GetQ(int index);
    public void SetQ(int index,Vector128<float> Value);

    public bool N               { get; set; }
    public bool Z               { get; set; }
    public bool C               { get; set; }
    public bool V               { get; set; }
    public ulong tpidrro_el0    { get; set; }
    public ulong tpidr          { get; set; }
    public ulong dczid_el0      { get; set; }
    public ulong fpsr           { get; set; }
    public ulong fpcr           { get; set; }
    public ulong BaseAddress    { get; set; }
    public Hook SvcHook         { get; set; }

    public void StartExecution();
}
```

Ryujinx.Cpu Should also include actual implementation for cpu emulators.

```cs
public class ARMeilleureCpuContext : CpuContext
{
    public ExecutionContext context;

    //implementation 
}
```

**Comment by gdkchan** [comment]
I'm interested in this to enable using other CPU emulators (such as Unicorn and Dynarmic) easily. I don't plan to use said emulators myself, but I think we should make this process as easy as possible, and making the emulator more modular is a good thing. I think this should also take into account platforms that do not require a JIT (such as those with a Arm64 CPU), where we can do direct code execution.

About your interfaces:
- The `public` modifier is redundant on interfaces, please remove it.
- Some names do not match our current naming convention (such as `tpidrro_el0` rather than `tpidrroEl0`.
- `public void SetQ(int index,Vector128<float> Value);` -> `void SetQ(int index, Vector128<float> value);`.

There's nothing on it about how memory management will work. Right now ARMeilleure exposes a small interface that it uses do access the memory and page table (see `ARMeilleure/Memory/IMemoryManager`), it does not allocate or manage the page table, this is done by `Ryujinx.Cpu` instead. Other Arm CPU emulators will want to manage the page table themselves, and this is also the case for direct code execution (where we need to use the host page table). I think the `IVirtualMemoryManager` interface can be used for that, but any new CPU emulator backend will need to implement it. Anyway, please update it including the memory manager interface(s) aswell. I think the biggest complication will be memory tracking.

**Comment by raymondMataka** [comment]
I think the best thing to do about memory, is to also move it onto an interface level. E.g.

```cs
struct MemoryRegionInfo
{
    public ulong Address;
    public ulong Size;
    public int Permission;
    public int Type;
}

interface CpuMemoryManager
{
    public static ulong AddressSpace = 1UL << 40;
    void Map(ulong Address, ulong Size, int Permission, int Type);
    void Unmap(ulong Address, ulong Size);
    MemoryRegionInfo GetMemoryRegionInfo(ulong Info);
}
```

if the cpu emulator in question explicitly requires memory management, then you could map the existing interface to the cpu emulator in question.

E.g. With unicorn

```cs

public struct MemoryRegionInfo
{
    public ulong Address;
    public ulong Size;
    public int Permission;
    public int Type;
}

interface CpuMemoryManager
{
    public static ulong AddressSpace = 1UL << 40;
    public static unsafe void* BaseAddress;

    void Map(ulong Address, ulong Size, int Permission, int Type);
    void Unmap(ulong Address, ulong Size);
    MemoryRegionInfo GetMemoryRegionInfo(ulong Address);
}

public class UnicornMemoryManager : CpuMemoryManager
{
    Arm64Engine UcContext { get; set; }

    public UnicornMemoryManager(Arm64Engine engine)
    {
        UcContext = engine;
    }

    public void Map(ulong Address, ulong Size, int Permission, int Type)
    {
        //uc_mem_map_ptr(...)
    }

    public void Unmap(ulong Address, ulong Size)
    {
        //uc_mem_map_ptr(...)
    }

    public MemoryRegionInfo GetMemoryRegionInfo(ulong Address)
    {
        return new MemoryRegionInfo(); 
    }
}
```

Now I would say pop a CpuMemoryManager reference to the CpuContext interface, but it seems like you can't. No worries, the memory manager could easily be made static, and initialized when the first cpu context is created.

But, if the cpu emulator in question does not require explicit memory management on its end, ryujinx would have its own built in memory manager.

**Comment by jduncanator** [comment]
> I think the best thing to do about memory, is to also move it onto an interface level. E.g.
> 
> ```cs
> struct MemoryRegionInfo
> {
>     public ulong Address;
>     public ulong Size;
>     public int Permission;
>     public int Type;
> }
> 
> interface CpuMemoryManager
> {
>     public static ulong AddressSpace = 1UL << 40;
>     void Map(ulong Address, ulong Size, int Permission, int Type);
>     void Unmap(ulong Address, ulong Size);
>     MemoryRegionInfo GetMemoryRegionInfo(ulong Info);
> }
> ```
> 
> if the cpu emulator in question explicitly requires memory management, then you could map the existing interface to the cpu emulator in question.
> 
> E.g. With unicorn
> 
> ```cs
> public struct MemoryRegionInfo
> {
>     public ulong Address;
>     public ulong Size;
>     public int Permission;
>     public int Type;
> }
> 
> interface CpuMemoryManager
> {
>     public static ulong AddressSpace = 1UL << 40;
>     public static unsafe void* BaseAddress;
> 
>     void Map(ulong Address, ulong Size, int Permission, int Type);
>     void Unmap(ulong Address, ulong Size);
>     MemoryRegionInfo GetMemoryRegionInfo(ulong Address);
> }
> 
> public class UnicornMemoryManager : CpuMemoryManager
> {
>     Arm64Engine UcContext { get; set; }
> 
>     public UnicornMemoryManager(Arm64Engine engine)
>     {
>         UcContext = engine;
>     }
> 
>     public void Map(ulong Address, ulong Size, int Permission, int Type)
>     {
>         //uc_mem_map_ptr(...)
>     }
> 
>     public void Unmap(ulong Address, ulong Size)
>     {
>         //uc_mem_map_ptr(...)
>     }
> 
>     public MemoryRegionInfo GetMemoryRegionInfo(ulong Address)
>     {
>         return new MemoryRegionInfo(); 
>     }
> }
> ```
> 
> Now I would say pop a CpuMemoryManager reference to the CpuContext interface, but it seems like you can't. No worries, the memory manager could easily be made static, and initialized when the first cpu context is created.
> 
> But, if the cpu emulator in question does not require explicit memory management on its end, ryujinx would have its own built in memory manager.

The Memory manager already is an interface, and as far as I'm aware, completely abstracted away. Ryujinx supplies a MM instance to the CPU JIT.
