### ISSUE TITLE
Crash after save in pikmin 3 deluxe

### ISSUE THREAD

**Issue by RoboticPress** [Ryujinx/Ryujinx#2030]
### What's the issue you encountered?

I recently downloaded pikmin 3 deluxe, wanted to find an emu and used ryujinx, I installed the firmware and started the game, everything went well until after creating the save file, the ryujinx just crashes... if I try to start the game again it crashes without the save screen.

### How can the issue be reproduced?

yeah I just explained that.

### Log file

with the save screen
[Ryujinx_1.0.6587_2021-02-17_15-53-27.log](https://github.com/Ryujinx/Ryujinx/files/5996198/Ryujinx_1.0.6587_2021-02-17_15-53-27.log)
Without the save screen (after the save screen crash)
[Ryujinx_1.0.6587_2021-02-17_16-44-40.log](https://github.com/Ryujinx/Ryujinx/files/5996427/Ryujinx_1.0.6587_2021-02-17_16-44-40.log)
Both are identical if I can guess right

### Environment?

- Ryujinx version: 1.0.6587
- Game version: 1.0.0
- System Specs:
  - OS: windows 7 64-bit
  - CPU: Intel(R) Core(TM) i7 CPU
  - GPU: NVIDIA Quadro 600
  - RAM: 4GB
- Applied Mods : No

Thank you in advance.

**Comment by EmulationFanatic** [comment]
4GB RAM is insufficient to run the emulator, sorry! You can disable PPTC and see if it allows you in, but in general you can expect subpar performance & stability with such a low end system.

**Comment by RoboticPress** [comment]
Thanks for that, disabling PPTC did not help tho, but the game does sometimes run at 60 fps tho. so idk... thanks again

**Comment by EmulationFanatic** [comment]
It's a 30 FPS game...might want to keep vsync enabled.

**Comment by RoboticPress** [comment]
yeah I disabled Vsync to see if it helps. still tho, that means the game runs

**Comment by EmulationFanatic** [comment]
Not if it keeps crashing.

**Comment by RoboticPress** [comment]
yeah you're right, but what do the logs mean? sorry I am not good with logs and stuff

**Comment by EmulationFanatic** [comment]
The log was indicating that the PPTC process was choking on something in the game. Pikmin is known to have issues with PPTC, which is why I had you try with it disabled. Crashes occurring outside of that are likely due to running out of memory (which can't be helped). There is a reason we suggest a bare minimum of 6GB RAM to run some games, recommended minimum of 8GB to run all games that are known to be playable.

**Comment by LDj3SNuD** [comment]
That issue has been solved in https://github.com/Ryujinx/Ryujinx/pull/1990

**Comment by RoboticPress** [comment]
Oh my god thank you, I was hesitant about upgrading my ram to 8GB ram as I didn't have that big of a reason. but guess the ram is a problem to all my games... ty again

**Comment by LDj3SNuD** [comment]
Btw, not that with only 4 GB of RAM you can think of using an emulator of a console of current generation.

**Comment by RoboticPress** [comment]
@LDj3SNuD I have just read your first comment.... and read the pull request and uhhhhh....
as a person who is really bad with programming I can't understand, can you explain?

**Comment by RoboticPress** [comment]
@EmulationFanatic now I have 8 gigs of RAM
 here's crash
 
[Ryujinx_1.0.6551_2021-03-09_22-23-35.log](https://github.com/Ryujinx/Ryujinx/files/6111254/Ryujinx_1.0.6551_2021-03-09_22-23-35.log)
