### ISSUE TITLE
hid IHidServer: 211 (IsVibrationDeviceMounted) is not implemented

### ISSUE THREAD

**Issue by CeruleanSky** [Ryujinx/Ryujinx#2041]
### What service call is missing?

nn::hid IHidServer 211 (IsVibrationDeviceMounted) is not implemented.</br>

[Switchbrew](https://switchbrew.org/wiki/HID_services#IsVibrationDeviceMounted)

### Service description
```
IsVibrationDeviceMounted

Takes a PID, an #VibrationDeviceHandle, and an u64 AppletResourceUserId, returns an output u8 bool. 
```

### Required by: 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/93 SMO down pipe in Sand Kingdom for PowerMoon 52, short video guide in games-list.

**Comment by AcK77** [comment]
Any hints on how to reach the unimplemented call in SMO ?

**Comment by CeruleanSky** [comment]
@AcK77 Sure thing, I linked to a youtube guide video and details in the games-list issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/93#issuecomment-782722593
