### ISSUE TITLE
Crash during Clubhouse Games load

### ISSUE THREAD

**Issue by Ufinexa** [Ryujinx/Ryujinx#2043]
### What's the issue you encountered?
Upon attempting to open Clubhouse Games (v1.0) the program crashes.

### How can the issue be reproduced?

Launching the game through the Multiplayer and Singleplayer build of the program.

### Log file

[https://pastebin.com/6iMAyMtA](url)

### Environment?

- Ryujinx version</br>
Game version: 1.0.0 ldn 2.1 and 1.0.6659</br>

- System Specs:
  - OS: Windows 10
  - CPU: i7 7700K
  - GPU: GTX 1080
  - RAM: 32GB DDR4 3200 mhz RAM
- Applied Mods : N/A

**Comment by AcK77** [comment]
`System.IO.FileNotFoundException: System archive with titleid 0100000000000823 was not found on Storage NandSystem.`

You used an outdated firmware for the game, update it and it will works.
