### ISSUE TITLE
Bindless textures break the shader cache

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#2045]
### What's the issue you encountered?

Any game with bindless textures will render the shader cache unusable for that game. The only solution is purging the shader cache prior to booting the game each time, or disabling shader cache in the emulator options before launching the game.

### How can the issue be reproduced?

Play a game with bindless textures (Super Mario Party is one example), then exit emulation/close the emulator and launch the game again.

### Log file

[Ryujinx_1.0.6662_2021-02-21_08-46-07.log](https://github.com/Ryujinx/Ryujinx/files/6018003/Ryujinx_1.0.6662_2021-02-21_08-46-07.log)

### Environment?

- Ryujinx version: 1.0.6662
- Game version: N/A
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 7 5800X
  - GPU: GTX 1080
  - RAM: 32GB
- Applied Mods : No

**Comment by Shahil-Ayato** [comment]
Could this possibly be fixed with [#2005](https://github.com/Ryujinx/Ryujinx/pull/2005) ?

**Comment by EmulationFanatic** [comment]
> Could this possibly be fixed with [#2005](https://github.com/Ryujinx/Ryujinx/pull/2005) ?

According to gdk, no. There will still need to be a fix like a blacklist preventing bindless textures from entering the shader cache or some other solution.
