### ISSUE TITLE
Feature Request: Add a Compatibility Tab

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx#2050]
- Added a Compatibility tab to the game list page.
- Add different colored bars according to game state.
( In the section that adds color stripes This will allow players to know which games can or cannot be played. )
https://github.com/Ryujinx/Ryujinx-Games-List/issues
- Add an open option Compatibility in Options / Enable GUI Columns
- Added a game state issue behind the game state colored bar.
( In this section, users who wish to review each game issue can click to go to each game issue page. Will make it easier to detect problems )
- And more..................................... @Xpl0itR 

![bandicam 2021-02-23 07-16-55-865](https://user-images.githubusercontent.com/35269098/108790505-7229ca00-75af-11eb-927f-5d8cf8916a56.jpg)
![bandicam 2021-02-23 07-46-06-939](https://user-images.githubusercontent.com/35269098/108790511-7524ba80-75af-11eb-8c34-3428db8e2d52.jpg)

**Comment by Shahil-Ayato** [comment]
There’s a lot to do to make this work especially with GTK, hopefully when Skia comes out this will be a lot easier

**Comment by gdkchan** [comment]
From where the compatibility information will come from? The current github games list repo?

**Comment by Cronos-0** [comment]
The compatibility of each game Will link to the game list on github https://github.com/Ryujinx/Ryujinx-Games-List/issues or do the same as yuzu https://yuzu-emu.org/game/

**Comment by Shahil-Ayato** [comment]
> The compatibility of each game Will link to the game list on github https://github.com/Ryujinx/Ryujinx-Games-List/issues or do the same as yuzu https://yuzu-emu.org/game/

I believe Yuzu includes their compat list in the source code so that may be an annoyance to do on ryujinx since we use GitHub issues for compatibility reports

**Comment by choppymaster** [comment]
I talked to someone about this feature some weeks ago, but they said that it may not be possible. Or it will need a website based compatibility list, and a package to fetch the compatibility from the list.

**Comment by CeruleanSky** [comment]
Just use the api, paginate through everything to build your database, taking what is useful, then bundle it.  Whether the data is pulled from github or from a website, it will need to be well formatted so the most data can be taken from it. EmulationFantic when they open an issue seems to do a good job following a template, so you can filter for just issues by them using the `User` as a start, and they can ensure all their issues are maximized for easy parsing by giving a list of ones with titles that need fixing, or body's that can be made more parsable. Once a database is around, a  website is easy as well.


https://api.github.com/repos/Ryujinx/Ryujinx-Games-List/issues?state=open&labels=status-menus&page=1&per_page=100
Some suggested fields:
```
 {
....
     "html_url": "https://github.com/Ryujinx/Ryujinx-Games-List/issues/3409",
....
     "title": "Flying Hero X - 0100419013A8A000",
.... 
 "labels": [{
...
             "name": "crash", 
             "color": "CD2626",
....
             "name": "status-menus",
              "color": "9ED763",
...
         }
     ],
     "state": "open",
     "body": ....Game loads and plays at a high FPS. Parts of the initial intro cutscene are a low FPS...
     
 },
```

**Comment by Cronos-0** [comment]
Closed, as it is not necessary at this time.
