### ISSUE TITLE
Missing texture format on Yo-kai Watch 1

### ISSUE THREAD

**Issue by AeroRush** [Ryujinx/Ryujinx#2051]
## Feature Request
</br>

#### Overview:
Include this texture to the emulator GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x493AF (sRGB: False).

### Why would this feature be useful?
This feature could make some games as Yo-kai Watch 1 playable.

[Ryujinx_1.0.6682_2021-02-23_13-11-21.log](https://github.com/Ryujinx/Ryujinx/files/6028791/Ryujinx_1.0.6682_2021-02-23_13-11-21.log)

**Comment by gdkchan** [comment]
Implemented in #2304.

**Comment by MorZa777** [comment]
I can't find where to out the log
