### ISSUE TITLE
Analog stick range modifier

### ISSUE THREAD

**Issue by VasyaPupkins** [Ryujinx/Ryujinx#2059]
### What feature are you suggesting?

Analog sticks range modifier.

### Why would this feature be useful?

Eventually any controller analog sticks is wearing out and becomes to never reach its max value.
Even brand new controllers can have this problem.

This will cause issues like game character run slowly or even walk while you pushing analog stick to full range.

Yuzu and cemu have this feature in control settings with visualization of analog sticks. It is really useful feature.

**Comment by MutantAura** [comment]
Fixed by #2783 

If you wish to request analog stick visualisation then that should probably be a separate feature request :)
