### ISSUE TITLE
SoundIO Object Reference not set.

### ISSUE THREAD

**Issue by Mou-Ikkai** [Ryujinx/Ryujinx#2062]
### What's the issue you encountered?

I was playing Persona 5 Strikers, and after getting Sophia to join my party, the game immediately crashed as Joker started dashing. A soundIO error</br>
Fresh ryujinx install! </br>

### How can the issue be reproduced?

Play Persona 5 Strikers, then play until you get to Sophia, after moving from the battle, you should get the error. (Make sure to use SoundIO backend!)

### Log file
[Ryujinx_1.0.6732_2021-02-26_10-27-55.log](https://github.com/Ryujinx/Ryujinx/files/6050746/Ryujinx_1.0.6732_2021-02-26_10-27-55.log)
```
Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceSession.Update(Int32 minFrameCount, Int32 maxFrameCount) in C:\projects\ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceSession.cs:line 414

```
### Environment?

- Ryujinx version: 1.0.6732</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10 Professional Build 19042*
  - CPU: *Ryzen 9 3900X*
  - GPU: *5700XT*
  - RAM: *32GB*
- Applied Mods: None, I just have the DLC Legacy BGM & All-Out Attack Pack DLC.

**Comment by jms-c** [comment]
It may be related to the tryPeek
`while (availaibleSampleCount > 0 && _queuedBuffers.TryPeek(out SoundIoAudioBuffer driverBuffer))`
as nothing changes _queuedBuffers (it is initialized, afaik).

**Comment by Thog** [comment]
> It may be related to the tryPeek
> `while (availaibleSampleCount > 0 && _queuedBuffers.TryPeek(out SoundIoAudioBuffer driverBuffer))`
> as nothing changes _queuedBuffers (it is initialized, afaik).
> 
> According to SoundIoHardwareDeviceSession.cs:line 414

``SoundIoAudioBuffer`` cannot be null as all codepath adding it only push a new instance.
To me it sounds like a race condition. In fact, the Update function is missing the lock usage.
