### ISSUE TITLE
Select GPU

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#2065]
#### Overview:
- There's no option to select GPU in Ruyjinx

#### Smaller Details: 
- In my case I'm running on linux, but I think is a common issue. Probably you can configure it externally on windows, and using bumblebee if you have an hybrid graphic card for a laptop. Here the use case is a egpu connected by thunderbolt.

![image](https://user-images.githubusercontent.com/220968/109378190-d3fc7380-78d0-11eb-8607-b53faf94522f.png)

http://www.adt.link/product/R43SG-TB3.html

```
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)
	Subsystem: Lenovo Device [17aa:225a]
	Kernel driver in use: i915
	Kernel modules: i915
--
0c:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] [10de:1c02] (rev a1)
	Subsystem: Gigabyte Technology Co., Ltd Device [1458:3727]
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```

so I think you need to manually select what you want to use

#### Nature of Request:  
- Addition
  - GPU selector
 
### Why would this feature be useful?

If you have more than one GPU, select which to use would be helpful.

At least on linux, not sure but maybe Vulkan is needed, and maybe you can externally priorize what GPU to choose by default

**Comment by Benedani** [comment]
Pretty sure it's not possible for the application to select which GPU to use on OpenGL. I think you should blacklist the i915 driver so that it doesn't interfere with your nvidia card.

**Comment by jms-c** [comment]
There is definitely no way to configure an openGL gpu from ryujinx. It would be possible with Vulkan but not at the moment with ogl.

**Comment by albfan** [comment]
Thanks for clarification, so it is set at X server then.
