### ISSUE TITLE
Ryujinx application issue on macOS Big Sur on a MacBook Pro 16-inch AMD Radeon GPU, 16 Core CPU

### ISSUE THREAD

**Issue by KohlerVG** [Ryujinx/Ryujinx#2075]
Hi Ryujinx Team,

I'm trying to get Ryujinx running on my MacBook Pro but when I download the latest mac build there is no application to open from the publish file? am I doing something wrong? please help!

Thanks for any help,
Kohler

**Comment by EmulationFanatic** [comment]
macOS is currently unsupported, both on x86 and apple silicon. Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/348
