### ISSUE TITLE
Decoding issues when two or more videos are playing at once

### ISSUE THREAD

**Issue by ActualMandM** [Ryujinx/Ryujinx#2077]
### What's the issue you encountered?

When two or more videos are being decoded at one time, the videos fail to decode properly. The emulator's console also gets bombarded with h264 decoding errors.

### How can the issue be reproduced?

1. Boot up *初音ミク Project DIVA MEGA39's* (or *Hatsune Miku: Project DIVA Mega Mix*)
2. Go to the song list
3. Play *骸骨楽団とリリア* (or *Gaikotsu Gakudan to Riria*)

### Log file

[Ryujinx_1.0.6773_2021-03-04_00-06-19](https://github.com/Ryujinx/Ryujinx/files/6081854/Ryujinx_1.0.6773_2021-03-04_00-06-19.log)

### Environment?

- Ryujinx version: 1.0.6773</br>
- Game version: 1.0.7</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *AMD Ryzen 9 3950X*
  - GPU: *NVIDIA RTX 2080*
  - RAM: *32GB*
- Applied Mods: Yes
  - *1920x1080*

### Additional context?

<img width="640" alt="2021-03-04_00-09-47_Ryujinx" src="https://user-images.githubusercontent.com/15317421/109931784-1f6ea300-7c7e-11eb-8d52-4fce7d6e8682.png">

<img width="640" alt="2021-03-04_00-22-02_Ryujinx" src="https://user-images.githubusercontent.com/15317421/109932896-a53f1e00-7c7f-11eb-891e-ac92411b9db9.png">

**Comment by gdkchan** [comment]
This was noted on the NVDEC implementation PR description https://github.com/Ryujinx/Ryujinx/pull/1384
> This approach works well when only one video is decoded at once (which is what has been observed so far on all tested games). However, it does not work when multiple videos are decoded at once, unless we propagate channel information from the HLE driver to NVDEC. This would allow appropriate separation of the FFMPEG decoding contexts for each video, since each video will be decoded on a separate channel.
