### ISSUE TITLE
The Touryst Resolution Scaling not working as intended

### ISSUE THREAD

**Issue by seriousduck11** [Ryujinx/Ryujinx#2081]
### The Touryst

**What's the issue you encountered?**

Increasing the resolution means that only a portion of the camera is displayed, the one corresponding to the native resolution. The HUD scales correctly (kinda, not sure).

**How can the issue be reproduced?**

By increasing the resolution beyond the native one.

**Environment?**

- Ryujinx version: 1.0.6774</br>
- Game version: 1.1</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *R7 5800X*
  - GPU: *GTX 1060*
  - RAM: *16GB*
- Applied Mods : No

**Screenshot**

![Base Profile Screenshot 2021 03 05 - 18 04 40 94](https://user-images.githubusercontent.com/80119049/110148624-54453c00-7ddd-11eb-802d-941a07ef6729.png)

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.

**Comment by MetrosexualGarbodor** [comment]
Please post about this in #1488 if it still occurs.
