### ISSUE TITLE
[Feature Request] Add progress indicator to shader cache compilation

### ISSUE THREAD

**Issue by MisterPrintf** [Ryujinx/Ryujinx#2086]
Currently, upon GPU driver updates and similar, shader caches have to be rebuilt. While this isn't a big issue in and of itself, these caches do take quite some time to compile, even on my relatively powerful rig with an RTX 2060 and i5-10600K.

What I propose is adding a simple indicator to the end of the logs. As opposed to a percentage, since it is not easily possible to guess compile time for each shader, is simply "[x/y compiled]" or similar, where X is the number of shaders already compiled, and Y is the number of total shaders requiring compilation.

**Comment by EmulationFanatic** [comment]
This exact functionality already exists and is shown both in the console and on the progress bar.
