### ISSUE TITLE
BGRA issues in Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by ActualMandM** [Ryujinx/Ryujinx#2093]
### What's the issue you encountered?

UI assets in the boxing ring's screen still have their blue and red channels swapped.

### How can the issue be reproduced?

1. Boot up *Super Smash Bros. Ultimate*
2. Go to training mode and choose boxing ring
3. Set CPU percentage to 999 and kill said CPU

### Log file

[Ryujinx_1.0.6780_2021-03-09_22-26-09.log](https://github.com/Ryujinx/Ryujinx/files/6113661/Ryujinx_1.0.6780_2021-03-09_22-26-09.log)

### Environment?

- Ryujinx version: 1.0.6780</br>
- Game version: 11.0.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *AMD Ryzen 9 3950X*
  - GPU: *NVIDIA RTX 2080*
  - RAM: *32GB*
- Applied Mods : No

### Additional context?

<img width="1920" alt="2021-03-09_22-32-26_Ryujinx" src="https://user-images.githubusercontent.com/15317421/110586820-98ab4180-8127-11eb-801d-dfea77c00116.png">

**Comment by Shahil-Ayato** [comment]
I believe this also happens in Pokémon Stadium and the characters blue and red channels are also swapped on the big screen.
