### ISSUE TITLE
I can't play

### ISSUE THREAD

**Issue by Penguiinn** [Ryujinx/Ryujinx#2119]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?
I couldn't play because all I saw when I downloaded was a file called publish.

**Comment by EmulationFanatic** [comment]
Please come to Discord for emulator support. This is an issue repository for emulator-specific bugs & features.

**Comment by Penguiinn** [comment]
I can't go into the discord because it says "Invitation Invalid".

**Comment by pineappleEA** [comment]
https://discord.gg/ryujinx
