### ISSUE TITLE
My emulator doesnt load my games especially pokemon sword

### ISSUE THREAD

**Issue by Skellyonyt** [Ryujinx/Ryujinx#2120]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version:9.0.1
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 8.1
  - CPU: Intel i7 3500
  - GPU:Intel Hd 4000
  - RAM:8Gb
- Applied Mods :No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
Please come to Discord for emulator support. This is an issue repository for emulator-specific bugs & features.

**Comment by Skellyonyt** [comment]
> Please come to Discord for emulator support. This is an issue repository for emulator-specific bugs & features.

can you send me the link for it
