### ISSUE TITLE
Auto-updater disabled for portable mode users

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#2125]
### What's the issue you encountered?

The auto-updater was disabled in the recent "[Implement friendlier portable mode](https://github.com/Ryujinx/Ryujinx/pull/1885)" PR because, while it was being developed, the auto-updater was purging everything in the Ryujing program folder. 
Once https://github.com/Ryujinx/Ryujinx/pull/1899 was merged, this functionality inside https://github.com/Ryujinx/Ryujinx/pull/1885 was supposed to be re-enabled as it is now safe and the updater preserves subfolders within the Ryujinx program directory..

As it stands, portable mode users can no longer auto-update unless disabling portable mode.

### How can the issue be reproduced?

Enable portable mode using the method of your choice, and try to use the updater.

### Log file

N/A

### Environment?

N/A

### Additional context?

**Comment by jms-c** [comment]
I have made a quick fix!
