### ISSUE TITLE
Pokken Tournament DX blank screen

### ISSUE THREAD

**Issue by Dantttt** [Ryujinx/Ryujinx#214]
This is the log https://pastebin.com/GChni9uX
This game deadlocks after showing a blank screen and it's calling for NvDec that will show the cinematic

**Comment by greggameplayer** [comment]
@Dantttt nvdec is not implemented yet

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/53
