### ISSUE TITLE
NO DC error message

### ISSUE THREAD

**Issue by MrAdamo** [Ryujinx/Ryujinx#2154]
### What's the issue you encountered?

This weekend when playing I noticed a kind of watermark in the upper left corner of the screen: "NO DC"</br>
It happens with every game and after noticing it I tried running the yuzu emulator and the same thing also happened there.</br>
I am not running any external benchmarking or capturing software, this came out of the blue, I always update Ryujinx to the latest version as soon as it's available.</br>
I didn't change any setting.

### How can the issue be reproduced?
No idea how to reproduce.

### Log file
N/A

### Environment?

- Ryujinx version: 1.0.6809</br>
- Game version: 2.0.2</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-8700K
  - GPU: NVIDIA RTX 2080Ti
  - RAM: 32GB
- Applied Mods : No

### Additional context?
![NO DC](https://user-images.githubusercontent.com/77383911/112972675-cac12980-9150-11eb-9ec5-a93e1366b8b8.jpg)

**Comment by EliEron** [comment]
If the issue spans both Ryujinx and Yuzu then it's pretty clear it's a third party issue, and not something specific to Ryujinx.

After a bit of Googling it seems this is an issue that has occurred to quite a few people, most of them after playing games based on the RenPy VN game engine. Did you play any RenPy based games prior to this issue starting?

The solution that works for most people is to go to the folder "C:\ProgramData\NVIDIA Corporation\Drs" and delete the "nvdrssel.bin" file found there.

Alternatively restoring the Nvidia Control panel to factory settings seems to help some people, which can be done by pressing the "Restore" button located on the lower-right side of the "Manage 3D settings" panel.

**Comment by MrAdamo** [comment]
@EliEron Thank you so much! Deleting that file worked! I tried to google the issue but I didn't have any luck, it didn't happen with any other games I was going crazy for what could it possibly be.
