### ISSUE TITLE
Pokémon Sword's local connection problem

### ISSUE THREAD

**Issue by GKD507** [Ryujinx/Ryujinx#2157]
My English is not very good, so I used a translator to translate. Forgive me
The version I use is ryujin 1.0.0-ldn2.1. When I play Pokémon Sword, I want to send sprites, but I find that I cannot connect to my switch host locally. I have determined that the game version is 1.3.1 and they are all connected to the same Under one wifi
![1](https://user-images.githubusercontent.com/81673348/113101685-9a03f180-922f-11eb-93c6-d66762ca36c9.png)
![2](https://user-images.githubusercontent.com/81673348/113101708-a12aff80-922f-11eb-9bfa-533784e64aa5.png)
The game keeps popping up exchange messages in the lower left corner, but my switch has only one message sent by myself and I haven’t been able to connect to Ryujinx’s message.

**Comment by AcK77** [comment]
Already reported in #2074
