### ISSUE TITLE
Warning that a save will be deleted if you launch a game with an older update version

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#2173]
Some games when the update file is removed or moved delete the actual save of the game since its incompatible with the version it was previous on. Most of the time it happens with games that were on newer update and going back to an older one. One example is Mario Kart, game will launch and there's no warning screen right now that the save that was previously with the game on the never update version will be deleted if launched with an older update file. Would be nice to make a popup come out which will warn the user that the game version isn't compatible with the version of the saved game and that it will get deleted if launched.

**Comment by AcK77** [comment]
As far as I know there is no way to know the game version for a savegame and there is no way to know the behavior of the game concerning the game update and what will happen to the savegame.

If you have more ideas about it on more informations, please open a new issue following the template: https://github.com/Ryujinx/Ryujinx/issues/new?assignees=&labels=&template=feature_request.md
Thanks.
