### ISSUE TITLE
Nickelodeon Kart Racers 2 Grand Prix LDN doesn't work

### ISSUE THREAD

**Issue by daniel221086** [Ryujinx/Ryujinx#2175]
I have reviewed and this game works correctly with the emulator, but the multiplayer ldn function does not work, I understand that the game does have the necessary option but it is not compatible with the emulator to connect to the multiplayer, it is likely that this comes in a new update of ldn2? #1846

**Comment by daniel221086** [comment]
<img width="960" alt="Sin título" src="https://user-images.githubusercontent.com/68826006/113497871-dfe1e380-94d5-11eb-9c95-5e921a85c943.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/68826006/113497873-e2dcd400-94d5-11eb-91f6-14a4fa882a79.png">

**Comment by jms-c** [comment]
This would be better info for https://github.com/Ryujinx/Ryujinx-Games-List/issues/2675
It isn't really emulator feedback but more of a game compatibility issue.

**Comment by AcK77** [comment]
This game currently doesn't support LDN. It could be playable online using Nintendo Online Service which isn't supported by Ryujinx.
> Local multiplayer up to 4, and online multiplayer up to 8
Local multiplayer means you can play at 4 players on the same screens, not using Local Wireless Multiplayer.
