### ISSUE TITLE
game runing in 60fps will automatically double-clicking.

### ISSUE THREAD

**Issue by iiiiroya** [Ryujinx/Ryujinx#2179]
### What's the issue you encountered?
game runing in 60fps will automatically double-clicking.
For example, if I press A in 60fps it will become AA sometimes, in 90fps it will might become AAA. 
Open VSync could perfectly solved this question.

### How can the issue be reproduced?
Very obiviously in Animal crossing's name inputting scene,where my fps could easily hit 100.Just press A,and this problem happens about 30%.

### Environment?
- Ryujinx version: 1.0.6819
- 
### Additional context?
N/A

**Comment by Mou-Ikkai** [comment]
Hi! _Did you try not disabling vsync?_ It sure helps when games are actually able to stay at the fps they were programmed to run at.

**Comment by iiiiroya** [comment]
Yes,vsync could solve this problem. However higher frame rate could provide a much smoother gaming experience and the same problem doesn't happen in other simulators at 60fps.
Also, other games have the same issue so I'm thinking it might be a bug of ryujinx ,not the game or 60fps patch.
Thank you for help☺

**Comment by GamerzHell9137** [comment]
> 
> 
> Yes,vsync could solve this problem. However higher frame rate could provide a much smoother gaming experience and the same problem doesn't happen in other simulators at 60fps.
> Also, other games have the same issue so I'm thinking it might be a bug of ryujinx ,not the game or 60fps patch.
> Thank you for help☺

You do know that Animal Crossing is a 30 FPS game and disabling VSync on it only makes it run faster? It doesn't make it smoother.

**Comment by iiiiroya** [comment]
Actually I don't.Thanks for telling me that.
But I just try to use Animal Crossing as an example because it's easy to be reproduced,but same problem happens in other games too.
I'm playing FE three houses and the double-clicking is really frustrating.Also 2x speed works perfectly in some games and makes them smoother according to my personal opinion.

**Comment by AcK77** [comment]
VSync should be disabled until you know what your doing.
Since ACNH is a 30FPS game, it's normal to get multiple input if you run the game faster as it should.

**Comment by Jatoxo** [comment]
> You do know that Animal Crossing is a 30 FPS game and disabling VSync on it only makes it run faster? It doesn't make it smoother.

60 fps is 60 fps, even if the game is faster, it will certainly be smoother than 30 fps
