### ISSUE TITLE
MAGLAM LORD game crashes on starting battle

### ISSUE THREAD

**Issue by tazevam** [Ryujinx/Ryujinx#2187]
### What's the issue you encountered?

The game seems to be able to run and save/load normally, but when the game enters the 3d battle scene, it will crash. Check the log and find that it has similar problem as dq11s. 
![1](https://user-images.githubusercontent.com/73407337/114091901-d7314900-98eb-11eb-92ee-417bc63ee7bd.PNG)
![2](https://user-images.githubusercontent.com/73407337/114091916-dbf5fd00-98eb-11eb-9149-9024cf79a76a.PNG)
![3](https://user-images.githubusercontent.com/73407337/114091929-df898400-98eb-11eb-83b1-d3983a90d358.PNG)

### How can the issue be reproduced?

Just started the game. 

### Log file
[Ryujinx_1.0.6823_2021-04-09_04-03-26.log](https://github.com/Ryujinx/Ryujinx/files/6281253/Ryujinx_1.0.6823_2021-04-09_04-03-26.log)

### Environment?
- Ryujinx version: 1.0.6823
- Game version: 1.0.0

- System Specs:
  - OS: Windows 10
  - CPU: I3-8350k
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : [ No ]

### Additional context?
thank for the hardwork!

**Comment by AcK77** [comment]
Thanks for your report but game report should be done here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/new
Feel free to contact us on our discord for more informations.
