### ISSUE TITLE
Ignore games when path not found (.symlink with size 0 kb)

### ISSUE THREAD

**Issue by Cloneg** [Ryujinx/Ryujinx#2191]
#### Overview:
- Ignore games with path not found ( .symlink with size 0) ( in my case it is because they are in a external hard drive not connected bc I keep some games in my main drive and the other as symlink in the same folder)</br>
![Captura de pantalla (389)](https://user-images.githubusercontent.com/67025623/114221731-48e0b580-9933-11eb-959b-25796129a392.png)

#### Smaller Details: 
- Ignore thoses games with path not found and don't show them in the game list (ryujinx alredy does this) and don't show the Ryujinx error window every time you open Ryujinx, maybe keep the first log in yellow if it's necessary.</br>

![Captura de pantalla (387)](https://user-images.githubusercontent.com/67025623/114221690-3d8d8a00-9933-11eb-9fa5-a4ba5bb60d34.png)

### Why would this feature be useful?
Users won't need to close the Ryujinx error window **every** time they open Ryujinx if they have games in a hard drive not connected but they want to play other games that are available.

![Captura de pantalla (388)](https://user-images.githubusercontent.com/67025623/114221768-56963b00-9933-11eb-8677-1845dd45a830.png)

**Comment by AcK77** [comment]
Fixed in #2547
