### ISSUE TITLE
Monster Hunter Rise crashes AMD GPU upon entering game menu

### ISSUE THREAD

**Issue by Stooovie** [Ryujinx/Ryujinx#2195]
build 1.0.6824 as well as LDN 2.2 crash AMD GPU driver every time Monster Hunter Rise reaches the in-game menu (the prompts and intro screens display fine). 

Tried AMD drivers 21.3.1 and 21.3.2, both crash (black screen, can recover). Windows 10 build 19042.906

**Comment by jochuan** [comment]
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1114
