### ISSUE TITLE
Monster Hunter Rise v1.1.1 crash when loading a save game

### ISSUE THREAD

**Issue by neohyuga** [Ryujinx/Ryujinx#2199]
### What's the issue you encountered?

Monster Hunter Rise version 1.1.1 crashes when loading a save game. Save game was transferred from a Nintendo Switch.

### How can the issue be reproduced?

Steps:
1. Load Monster Hunter Rise version 1.1.1.
2. In main menu, select continue.
3. Select save file.

At this point, the exception occurs.

### Log file

00:01:53.584 |E| HLE.OsThread.6 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31

Guest Stack Trace:
Process: Service, PID: 83

Raw Request Data:
00000000   01 00 20 00 01 00 00 00  00 00 00 00 00 00 00 00   ·· ·············
00000010   53 46 43 49 01 00 00 00  1F 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   48 80 B6 BA 01 00 00 00                            H¶º····        

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 216
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: LDN2.2 based on 1.0.6819. Game also crashed the same way using latest non-LDN build, 1.0.6824.
- Game version: 1.1.1

- System Specs:
  - OS: Windows 10)
  - CPU: Ryzen 7 3700X
  - GPU: NVIDIA RTX 2070 SUPER
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:
Various DLCs installed.

I then set the Settings option "Ignore Missing Services", and tried again. This time I got a different exception:

00:01:26.725 |G| HLE.OsThread.5 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 86s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'nn.npln.GrpcDispatcher'
    ProgramName: 'runtime_il2cpp'
    Message: 'E0101 00:01:26.550517187  435965956880 ev_poll_posix.cc:1150]          pollset_w'

00:01:26.767 |G| HLE.OsThread.5 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 86s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'nn.npln.GrpcDispatcher'
    ProgramName: 'runtime_il2cpp'
    Message: 'ork: {"created":"@86.496296354","description":"pollset_work","file":"external/com_google_grpc_base/src/core/lib/iomgr/ev_poll_posix.cc","file_line":908,"referenced_errors":[{"created":"@86.490606197","description":"Bad file descriptor","errno":9,"file":"external/com_google_grpc_base/src/core/lib/iomgr/ev_poll_posix.cc","file_line":1034,"os_error":"Bad file descriptor","syscall":"poll"}]}'

00:01:26.767 |G| HLE.OsThread.5 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 86s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'nn.npln.GrpcDispatcher'
    ProgramName: 'runtime_il2cpp'
    Message: ''

00:01:26.780 |G| HLE.OsThread.5 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 86s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'nn.npln.GrpcDispatcher'
    ProgramName: 'runtime_il2cpp'
    Message: 'E0101 00:01:26.708604479  435965956880 completion_queue.cc:1280]       Completio'

00:01:26.787 |G| HLE.OsThread.5 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 86s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'nn.npln.GrpcDispatcher'
    ProgramName: 'runtime_il2cpp'
    Message: 'n queue next failed: {"created":"@86.496296354","description":"pollset_work","file":"external/com_google_grpc_base/src/core/lib/iomgr/ev_poll_posix.cc","file_line":908,"referenced_errors":[{"created":"@86.490606197","description":"Bad file descriptor","errno":9,"file":"external/com_google_grpc_base/src/core/lib/iomgr/ev_poll_posix.cc","file_line":1034,"os_error":"Bad file descriptor","syscall":"poll"}]}'

00:01:26.791 |G| HLE.OsThread.5 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 86s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'nn.npln.GrpcDispatcher'
    ProgramName: 'runtime_il2cpp'
    Message: ''

00:01:27.508 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:27.508 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 28 ; runtimeAddOnContentInstall: 1}
00:01:27.509 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 28}
00:01:29.019 |I| HLE.GuestThread.74 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 93
   sdk:0x0034f730 nn::os::detail::CallFiberFunction(nn::os::FiberType* (*)(void*), void*)

00:01:29.019 |E| HLE.GuestThread.74 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000020.
00:01:29.024 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:29.024 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 28 ; runtimeAddOnContentInstall: 1}
00:01:29.025 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 28}
00:01:30.039 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:30.039 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 28 ; runtimeAddOnContentInstall: 1}
00:01:30.040 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 28}
00:01:30.339 |S| HLE.OsThread.5 ServicePctl IsFreeCommunicationAvailable: Stubbed. 
00:01:31.055 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:31.055 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 28 ; runtimeAddOnContentInstall: 1}
00:01:31.056 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 28}
00:01:31.620 |E| HLE.GuestThread.74 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\project\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\project\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 468
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\project\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 292
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\project\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 150
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\project\ryujinx\ARMeilleure\Translation\Translator.cs:line 142
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by EmulationFanatic** [comment]
You need to disable LAN connectivity while playing this game.

**Comment by neohyuga** [comment]
Thank you for the quick response EmulationFanatic.

I disabled LAN connectivity, then tried to load the save again.  It still crashed. It went further, I think... the load screen went on for longer and the console window showed more output...

Last few lines:

00:01:22.449 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:22.449 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 24 ; runtimeAddOnContentInstall: 1}
00:01:22.449 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 24}
00:01:22.450 |I| HLE.OsThread.10 ServiceNv Create: Created map 141 with size 0x00400000!
00:01:22.759 |I| HLE.OsThread.10 ServiceNv Create: Created map 142 with size 0x00400000!
00:01:22.786 |I| HLE.OsThread.10 ServiceNv Create: Created map 143 with size 0x00400000!
00:01:23.029 |I| HLE.OsThread.10 ServiceNv Create: Created map 144 with size 0x00400000!
00:01:23.301 |I| HLE.OsThread.10 ServiceNv Create: Created map 145 with size 0x00400000!
00:01:23.424 |I| HLE.OsThread.10 ServiceNv Create: Created map 151 with size 0x00400000!
00:01:23.453 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:23.453 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 24 ; runtimeAddOnContentInstall: 1}
00:01:23.455 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 24}
00:01:23.540 |I| HLE.OsThread.10 ServiceNv Create: Created map 152 with size 0x00400000!
00:01:23.816 |I| HLE.OsThread.10 ServiceNv Create: Created map 153 with size 0x00400000!
00:01:23.904 |I| HLE.OsThread.10 ServiceNv Create: Created map 159 with size 0x00400000!
00:01:24.014 |I| HLE.OsThread.10 ServiceNv Create: Created map 160 with size 0x00400000!
00:01:24.080 |I| HLE.OsThread.10 ServiceNv Create: Created map 161 with size 0x00400000!
00:01:24.080 |I| HLE.OsThread.10 ServiceNv Create: Created map 162 with size 0x00400000!
00:01:24.224 |I| HLE.OsThread.10 ServiceNv Create: Created map 163 with size 0x00400000!
00:01:24.262 |I| HLE.OsThread.10 ServiceNv Create: Created map 167 with size 0x00400000!
00:01:24.262 |I| HLE.OsThread.10 ServiceNv Create: Created map 168 with size 0x00400000!
00:01:24.302 |I| HLE.OsThread.10 ServiceNv Create: Created map 169 with size 0x00400000!
00:01:24.351 |I| HLE.OsThread.10 ServiceNv Create: Created map 170 with size 0x00400000!
00:01:24.405 |I| HLE.OsThread.10 ServiceNv Create: Created map 171 with size 0x00400000!
00:01:24.465 |I| HLE.OsThread.10 ServiceNv Create: Created map 172 with size 0x00400000!
00:01:24.466 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:24.466 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 24 ; runtimeAddOnContentInstall: 1}
00:01:24.466 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 24}
00:01:24.533 |I| HLE.OsThread.10 ServiceNv Create: Created map 173 with size 0x00400000!
00:01:24.545 |I| HLE.OsThread.10 ServiceNv Create: Created map 174 with size 0x00400000!
00:01:24.557 |I| HLE.OsThread.10 ServiceNv Create: Created map 175 with size 0x00400000!
00:01:24.585 |I| HLE.OsThread.10 ServiceNv Create: Created map 176 with size 0x00400000!
00:01:24.594 |I| HLE.OsThread.10 ServiceNv Create: Created map 177 with size 0x00400000!
00:01:24.739 |I| HLE.OsThread.10 ServiceNv Create: Created map 178 with size 0x00400000!
00:01:24.868 |S| HLE.OsThread.5 ServicePctl IsFreeCommunicationAvailable: Stubbed. 
00:01:24.875 |I| HLE.OsThread.10 ServiceNv Create: Created map 179 with size 0x00400000!
00:01:24.973 |I| HLE.OsThread.10 ServiceNv Create: Created map 180 with size 0x00400000!
00:01:25.478 |W| HLE.OsThread.5 ServiceNs CountAddOnContent: RuntimeAddOnContentInstall is true. Some DLC may be missing
00:01:25.478 |S| HLE.OsThread.5 ServiceNs CountAddOnContent: Stubbed. {aocCount: 24 ; runtimeAddOnContentInstall: 1}
00:01:25.481 |S| HLE.OsThread.5 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 256 ; startIndex: 0 ; aocCount: 24}
00:01:25.775 |I| HLE.OsThread.10 ServiceNv Create: Created map 181 with size 0x00400000!


But now I do not see an exception in the logs.  That is the end of the log. The emulator process just closes.

Would it help if I attached the save data I am using?

**Comment by neohyuga** [comment]
Just tried it again on regular build (non-LDN), 1.0.6824. It crashes at the same point with this save file.

**Comment by AcK77** [comment]
Please come to Discord for emulator support.

**Comment by gdkchan** [comment]
Delete all the in-game picture files from the save data and try again.
Example:
![image](https://user-images.githubusercontent.com/5624669/114332406-910efc00-9b1c-11eb-8bd1-0c4819471d41.png)
You would delete the files inside the red rectangle.

**Comment by neohyuga** [comment]
gdkchan, deleting those files did the trick! Thank you! The game loaded just fine. Thank you for your prompt and amazing support!  :-)
