### ISSUE TITLE
Add security and versioning dependency alerts

### ISSUE THREAD

**Issue by aleks-ivanov** [Ryujinx/Ryujinx#2202]
#### Overview:
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

#### Smaller Details: 
N/A

#### Nature of Request:  
- Addition

### Why would this feature be useful?
- Dependencies often create security risks and performance problems, so dependency management automates the manual process of keeping the project secure

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by Thog** [comment]
Sorry, if I wanted dependabot integration up and running, I would already have setup it.

I should also be noted that automatizing PR and issues creation in a large scale on public repositories is against GitHub TOS and will be reported.

Closing.
