### ISSUE TITLE
X-axis inverted when using gyro to aim with the new native controller support

### ISSUE THREAD

**Issue by Haronee** [Ryujinx/Ryujinx#2210]
### What's the issue you encountered?

Using PR #2194 that has been merged in latest master, there's a bug with the new native gyro support.
When using the gyro to aim in The Legend of Zelda: Breath of the Wild, the X-axis becomes inverted if you aim too high, so aiming to the left makes Link aim to the right, and vice-versa.

This only occurs when using native gyro support, when using cemuhook aiming is fine.
I tried with a Pro Controller and other users managed to reproduce the issue with it and a DS4 controller.

### How can the issue be reproduced?

1. Launch The Legend of Zelda: Breath of the Wild.
2. Go in-game.
3. Use your bow and aim as high as possible.
4. Aim to the left and then to the right to see if the X-axis is inverted or not.

### Log file
[Ryujinx_1.0.6835_2021-04-14_17-06-23.log](https://github.com/Ryujinx/Ryujinx/files/6311846/Ryujinx_1.0.6835_2021-04-14_17-06-23.log)

### Environment?

- Ryujinx version: 1.0.6835</br>
- Game version: 1.6.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *Ryzen 5 3600*
  - GPU: *NVIDIA RTX 3060TI*
  - RAM: *16GB*
- Applied Mods : Static 30fps

### Additional context?

Clip where I aimed left-right, then aimed up and tried left-right again: https://streamable.com/dhue2b

**Comment by MetrosexualGarbodor** [comment]
Fixed by #3284.
