### ISSUE TITLE
sfdnsres IResolver: 14 (ResolverSetOptionRequest) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#2214]
sfdnsres IResolver: 14 (ResolverSetOptionRequest) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Sockets_services#sfdnsres) |

## Service description:
```
N/A
```

## Required by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1519

**Comment by LukeWarnut** [comment]
Required by Ryujinx/Ryujinx-Games-List#3194 with guest internet access on.

**Comment by EmulationFanatic** [comment]
https://github.com/Ryujinx/Ryujinx/issues/3479 was a duplicate issue. Oops! This was resolved by https://github.com/Ryujinx/Ryujinx/pull/3493 .
