### ISSUE TITLE
joycon right cant motion

### ISSUE THREAD

**Issue by rellystop** [Ryujinx/Ryujinx#2221]
in ver 1.0.6832
joycon left and joycon right，they all can motion
but，after that 1.0.6833，just joycon left can motion

ps：already use "use cemu hook compatible motion”

**Comment by BenGost** [comment]
Hello !

I have the same problem,

movements with the left jocon are not recognized.

I am using BetterJoy V6.3
And Ryujinx 1.0.6864

Thank you

![image](https://user-images.githubusercontent.com/62108660/117446389-4d9d8700-af3c-11eb-84fa-a01f9bf12afa.png)
![image](https://user-images.githubusercontent.com/62108660/117446420-568e5880-af3c-11eb-9dda-8f6a85b6fa98.png)

![image](https://user-images.githubusercontent.com/62108660/117446461-64dc7480-af3c-11eb-8294-ee5da3379b50.png)

**Comment by ryulovesjinx** [comment]
This is happening to me too.
Ryujinx version: 1.0.6909
OS: Linux Ubuntu 20.04
The right stick do not get mapped. Using a official pro controller.

**Comment by MetrosexualGarbodor** [comment]
Fixed by #2488.
