### ISSUE TITLE
Regression: Monster Hunter Rise new graphical bugs and crashes

### ISSUE THREAD

**Issue by lucaskiu** [Ryujinx/Ryujinx#2229]
## Bug Report

Crash and improvent birds e some bugs invisibles in map.

### What's the issue you encountered?

Some elements in maps still invisible like a birds buffs and insect bugs. in screen shots you can see problem. all still invisble only show icon if get close. old version still ok show normal insect(1.0.6840)

![Ryujinx_2021_04_19_15_09_40_818 (2)](https://user-images.githubusercontent.com/60316986/115283248-7c84c200-a121-11eb-81eb-97eb335c22ea.jpg)
Only icons show now (invisible insect begginer in build 6841)

![Ryujinx_2021_04_19_14_59_42_541](https://user-images.githubusercontent.com/60316986/115283512-d8e7e180-a121-11eb-96e8-0c1287b8114e.jpg)
All birds for improvement status in this list dont show anymore, only icons or sound if get close.

### How can the issue be reproduced?
Only farm or walking in map and crash (don't happen in 6842)

### Log file

[Ryujinx_1.0.6843_2021-04-19_14-00-53.log](https://github.com/Ryujinx/Ryujinx/files/6338010/Ryujinx_1.0.6843_2021-04-19_14-00-53.log)

### Environment?

- Ryujinx version: 1.0.6843</br>
- Game version: 1.1.2</br>
- System Specs:
  - OS: Windows 10 PRO
  - CPU: i5 10400f
  - GPU: NVIDIA RTX 2060 SUPER
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

This crash problem did not happen in the previous version (6842)
invisible insect begginer in version (6841)</br>

**Comment by manfred-exz** [comment]
Can confirm `invisible insect` and `Out of Memory` also happen to me with version 6843, doesn't seems to happen in 6842.

**Comment by lucaskiu** [comment]
Apparently crash ''out of memory'' is resolve in 6844.  My testes doesn't crashes anymore but bug invisible insect keep yet.

**Comment by mhvuze** [comment]
Invisible Buff Insect bug seems to be fixed by #2261 

https://cdn.discordapp.com/attachments/801087226649509889/838128392435138600/unknown.png
