### ISSUE TITLE
New Pokemon Snap - Random Crashing and Photos not registering.

### ISSUE THREAD

**Issue by Kryptuq** [Ryujinx/Ryujinx#2254]
### What's the issue you encountered?

Getting Randomly crashes while playing New Pokemon Snap. When restarting i can play further but will crash again after like 5-10minutes.
Another Problem which will probably not show in the logs: After finishing Tutorial/Expedition the photos doesnt register. They are Empty

### How can the issue be reproduced?

Just playing the Game.

### Log file

<details>
  <summary>Click to expand!</summary>

00:05:00.920 |I| Ptc Save: Saved Profiling Info (size: 58334 bytes, profiled functions: 17684).
00:05:37.988 |I| HLE.OsThread.5 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:05:38.308 |I| HLE.GuestThread.40 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x00144da4 Sub000000000a9f2da4
   sdk:0x00144f18 Sub000000000a9f2f18
   sdk:0x00349f18 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x00341878 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x008add38 Sub00000000088b1d38
   main:0x008f79fc Sub00000000088fb9fc
   sdk:0x00344708 Sub000000000abf2708
   sdk:0x00348ed4 Sub000000000abf6ed4
   ??? Sub0000000000000000

00:05:38.309 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:05:38.309 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.45 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.47 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.52 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.54 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.55 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.59 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.65 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.64 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.63 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.53 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.62 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.56 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.58 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.60 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.57 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.46 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.41 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.35 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.15 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.17 KernelSvc PrintResult: SendSyncRequest64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.38 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.42 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.49 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.311 |W| HLE.GuestThread.50 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:38.333 |E| HLE.GuestThread.40 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 160
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
</details>

Photo Problem:
![Screenshot 2021-04-30](https://user-images.githubusercontent.com/68452851/116630502-8c877780-a953-11eb-8e60-d9eccf2125e8.png)

Full Log:
[Ryujinx_1.0.6852_2021-04-30_00-55-46.log](https://github.com/Ryujinx/Ryujinx/files/6402161/Ryujinx_1.0.6852_2021-04-30_00-55-46.log)

### Environment?

- Ryujinx version: 1.0.6852</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: *Win10*
  - CPU: *i7-10700k*
  - GPU: *RTX 3070*
  - RAM: *16GB*
- Applied Mods : [ No ]

**Comment by zimmertr** [comment]
Ditto

**Comment by guilhermedsx** [comment]
This should not be closed. Yes, it detects the Pokémon in the picture just fine as of build 1.0.6855 but it keeps crashing at random for me and many other people... and just happens in this game!

**Comment by gdkchan** [comment]
You can open a new issue for the crashes since it's unrelated to the photo detection issue (only one bug per issue). And this particular crash also affects other games, so its better to have a general issue for it anyway.

**Comment by guilhermedsx** [comment]
I rebuild the PTC and Shaders and the crashing got MUCH better. I can go to the end of the first stage now, where I couldn't even finish the tutorial without Ryujinx closing on me.
