### ISSUE TITLE
Bravely Default 2 black dots in map

### ISSUE THREAD

**Issue by Jeffslash666** [Ryujinx/Ryujinx#2255]
Hi, in the previous build those black dots were not there.
![Bravely 2 black dots](https://user-images.githubusercontent.com/83434355/116632577-e1b09280-a92d-11eb-893f-b7b8c8ca3072.png)
[Ryujinx_1.0.6852_2021-04-29_20-13-58.log](https://github.com/Ryujinx/Ryujinx/files/6402269/Ryujinx_1.0.6852_2021-04-29_20-13-58.log)

- Ryujinx version: 1.0.6852</br>
- Game version: 1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i5 9600K
  - GPU: NVIDIA GTX 1060 6GB
  - RAM: 16GB DDR4
- Applied Mods : NO

**Comment by AcK77** [comment]
What if you disable Resolution Scaler ?

**Comment by Jeffslash666** [comment]
no changes

**Comment by Jeffslash666** [comment]
Do you know where i find older builds?

**Comment by AcK77** [comment]
Is this issue still occurs with latest build (1.0.6970) ?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
