### ISSUE TITLE
hid IIrSensorServer: 314 (CheckFirmwareVersion) is not implemented

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx#2268]
[3.0.0+] hid IIrSensorServer: 314 (CheckFirmwareVersion) is not implemented</br>

[Switchbrew](https://switchbrew.org/wiki/HID_services#CheckFirmwareVersion) | [SwIPC](https://reswitched.github.io/SwIPC/ifaces.html#nn::irsensor::IIrSensorServer(314))

### Service description
```
Takes a PID-descriptor, an #IrCameraHandle, and an AppletResourceUserId. No output.

sdknso uses this from the Run*Processor funcs to suspend the current Processor when the current FunctionLevel is >= 0x1, prior to starting another Processor if needed (depending on what Processor was already active via a state field). Hence, this cmd is only used with [4.0.0+].
```

### Required by: 

Ryujinx/Ryujinx-Games-List#3564

**Comment by LukeFZ** [comment]
Stubbed as of commit afd3153 and #2371
