### ISSUE TITLE
"AcquireSemaphore" scheduling/race condition bug

### ISSUE THREAD

**Issue by AkagiShiroe** [Ryujinx/Ryujinx#2276]
## Bug Report

Ryujinx random crash

### What's the issue you encountered?

ryujinx suddenly close itself

### How can the issue be reproduced?

in gameplay(exploring, navigating menu) or loading screen

### Log file

[Ryujinx_1.0.6859_2021-05-08_08-54-22.log](https://github.com/Ryujinx/Ryujinx/files/6444891/Ryujinx_1.0.6859_2021-05-08_08-54-22.log)

> 00:03:35.113 |I| HLE.GuestThread.20 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x000559c0 Sub000000000ddac9c0
   sdk:0x00055a88 Sub000000000ddaca88
   sdk:0x00055b20 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000d5f08 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x000cd898 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x021e04b8 Sub000000000a1e44b8
   main:0x021df480 Sub000000000a1e3480
   main:0x01e192cc Sub0000000009e1d2cc
   sdk:0x000d06f8 Sub000000000de276f8
   sdk:0x000d4ec4 Sub000000000de2bec4
   ??? Sub0000000000000000
 00:03:35.115 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.42 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.41 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.40 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.38 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.37 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.36 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.45 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.115 |W| HLE.GuestThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.46 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.47 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.48 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.116 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.121 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.122 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.122 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.122 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.122 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.123 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.123 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.123 |W| HLE.GuestThread.17 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:35.588 |E| HLE.GuestThread.20 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 160
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version:1.0.6859</br>
- Game version: 1.0.4</br>
- System Specs:
  - OS: Windows 10 20H2
  - CPU: AMD Ryzen 3 1200
  - GPU: NVIDIA GTX 750Ti
  - RAM: 8 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Shader Cache,PPTC Enabled

**Comment by AcK77** [comment]
Seems to be fixed in #2286

**Comment by MetrosexualGarbodor** [comment]
Fixed by #2286.
