### ISSUE TITLE
Monster Hunter GU Codes

### ISSUE THREAD

**Issue by RustColeone** [Ryujinx/Ryujinx#2283]
### What's the issue you encountered?

Unable to use any codes apart from the FPS ones I tried both the LDN version and the 1.0.6869

### How can the issue be reproduced?

Just loaded the codes

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.6869</br>
- Game version: 1.4.X0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 4900HS
  - GPU: RTX 2060
  - RAM: 16 GB
- Applied Mods : Yes

[Use of props is not reduced]
04000000 003015F8 E3A07000

[60 FPS]
58000000 018A6210
78000000 0000243C
64000000 00000000 42700000

### Additional context?

N/A

**Comment by Kryptuq** [comment]
its a known issue atm that 04xxxxxx cheat codes are not working.
all others are working without problems tho :)

**Comment by RustColeone** [comment]
Thank you, but is it going to get fixed though?

**Comment by Mou-Ikkai** [comment]
@gdkchan Hasn't this issue been fixed by the update to the cheat system? It added support for 0x4 addresses, after all.

**Comment by MetrosexualGarbodor** [comment]
Closing since this seems to be the same issue as #2559 and that has long been fixed.
