### ISSUE TITLE
ffmpeg cant find its libraries on PopOS 20.10

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx#2284]
### What's the issue you encountered?

even after https://github.com/Ryujinx/Ryujinx/commit/1769510a280ab33cb7b31a1f3e17fdb09f5b87cf, ffmpeg crashes on popos 20.10 not being able to find its libraries in `/lib`
looking more into it, setting the ffmpeg.RootPath to `/usr/lib/x86_64-linux-gnu/` in the `/Ryujinx/Program.cs` file fixes the issue on PopOS
big thanks to @EmulationFanatic for testing on PopOS 20.10

### How can the issue be reproduced?

run any ryujinx version after 1.0.6857 on PopOS 20.10

**Comment by Niwu34** [comment]
This affects quite a bunch of games - I'm using Fedora 32

A few examples (I had to use the LDN 2.2 Build for those Screenshots):
Smo Preview - makes traveling between Kingdoms impossible
![Bildschirmfoto von 2021-05-19 13-00-27](https://user-images.githubusercontent.com/67392333/118803505-b9b8ad00-b8a3-11eb-89f6-1edd394d0498.png)

Mario Kart - makes offline gaming impossible
![Bildschirmfoto von 2021-05-19 13-02-06](https://user-images.githubusercontent.com/67392333/118803584-d48b2180-b8a3-11eb-8373-550152ef159b.png)

Burnout Paradise/MHR are not able to get into the menu
