### ISSUE TITLE
[Feature Request] Provide ability to set y/x axis of sticks independently (or add "rotate" pad option)

### ISSUE THREAD

**Issue by legend800** [Ryujinx/Ryujinx#2287]
#### Overview:
Provide ability to set y/x axis of sticks independently (with invert) or provide ability to "rotate" pad. 

#### Smaller Details: 
Dolphin example:
![image](https://user-images.githubusercontent.com/20983844/118229571-13068380-b441-11eb-995f-e91bf4fb5707.png)

Related Discord discussion here with devs:
https://discord.com/channels/410208534861447168/814263228926132274/832109061687869450

#### Nature of Request:  
Allow more flexibility to map stick input as the user wishes. Example input from the other emu:
![2021-05-13 23_28_27-yuzu Configuration](https://user-images.githubusercontent.com/20983844/118230718-f4a18780-b442-11eb-822b-b12a1dbd8d27.png)

### Why would this feature be useful?
Games like Super Mario Party need sideways joycon. You could use the Pro Controller to play this game perfectly, with motion, previous to Apr 14th, but now you can't set x/y independently. This prevent you from mapping input to achieve 'sideway joycon'.

Before:
![2](https://user-images.githubusercontent.com/20983844/118230059-e2731980-b441-11eb-90f6-8da2e097d1ef.png)

After:
![1](https://user-images.githubusercontent.com/20983844/118230062-e43cdd00-b441-11eb-9677-a76d8cf0d2b8.png)

**Comment by jojorne** [comment]
I need the ability to set the "speed" that you move the stick buttons. When you use it mapped on a keyboard the current speed is set to 1 and  using it to control things like the camera become quite a challenge since the camera can move quite a lot.

**Comment by legend800** [comment]
Any chance we can see an update to the left stick mapping flexibility soon, so users can use the controllers they're comfortable with, like Pro pad over the cramp-inducing joycon? All we need is a 'sideways' or go back to being able to set each direction like other emus.

**Comment by Hackerpcs** [comment]
+1 on this. I use a cheap PS2-type controller than on the right analog stick, the axis are reverted, the vertical one functions as horizontal and the horizontal as vertical, reverting the left to be right e.g. on the horizontal one doesn't help, it's a different problem. I get can get around with X360CE but it would be nice to have it built in

**Comment by legend800** [comment]
Yep, Nintendo allows for more stick customization than Ryu since it got locked down last April. I really hope they can readd this back or provide some kind of flexibility to the users who do not want to use tiny joycons. 

https://en-americas-support.nintendo.com/app/answers/detail/a_id/49232/~/how-to-change-the-control-stick-orientation-on-the-joy-con-controller

https://www.imore.com/how-remap-buttons-nintendo-switch
