### ISSUE TITLE
Arcaea graphical errors

### ISSUE THREAD

**Issue by reflexyG** [Ryujinx/Ryujinx#2295]
### What's the issue you encountered?

White boxes covering text, images could not display properly and some texture errors.
![unknown](https://user-images.githubusercontent.com/64774291/118970126-d68ad880-b9a8-11eb-9100-9efb0bd6ae73.png)

![unknown (1)](https://user-images.githubusercontent.com/64774291/118970359-15b92980-b9a9-11eb-8d00-bf35ccee0b06.png)

![unknown3](https://user-images.githubusercontent.com/64774291/118970366-194cb080-b9a9-11eb-819a-927e3b42097c.png)

### Log file

[Ryujinx_1.0.6878_2021-05-20_20-11-19.log](https://github.com/Ryujinx/Ryujinx/files/6515423/Ryujinx_1.0.6878_2021-05-20_20-11-19.log)

### Environment?

- Ryujinx version: 1.0.6878</br>

- Game version: 1.0.0</br>

- System Specs:
  - OS: Windows 10
  - CPU:  i7-7700HQ
  - GPU: GTX 1060 6gb (laptop)
  - RAM: 16gb
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please submit this instead as a game compatibility issue on the game compatibility list (following the standard template there). The main issue repo is more meant for emulator bugs rather than game compatibility.
