### ISSUE TITLE
Monster Hunter Rise 1080p Mod (regression)

### ISSUE THREAD

**Issue by Zuyoart** [Ryujinx/Ryujinx#2297]
## Bug Report

Very recently, MHrise resolutions scaling (2x) with 1080p mod got buggy.
Some part only gets rendered 1080p and stays in the upper left quadrant (i.e. 1/4 of 4k).
Leaving an large image thats bland and then the 'same' very colorfull image small.

### What's the issue you encountered?
No 1080p mod: It works perfectly.
No scaling: Native res works perfectly
With scaling 1080p mod: regression.

60fps mod makes no difference.

Reproduction:
1 install mod 
2 start the game 
3 and/or flick between handheld and docked. (this will sometimes fix the problem too)

Everythings works so no error shows up.

**Comment by gdkchan** [comment]
Are you sure that this is a regression? It used to do that on the demo (without mods) on the character selection screen with resolution scale enabled. It also does on the full game in a few places.

**Comment by Zuyoart** [comment]
Did some retesting.

On 1.0.6877 it worked and 1.0.6878 (which I updated to 1.0.6880) it did not.

It appears on main menu singing girl, and on the charachter/save select, and in the village.
I suspect #2290 to be the cause.

I am fine on native res but I thought it is maybe something to consider.

**Comment by Zuyoart** [comment]
Fixed by #2300.

This PR seems to fix the problem for me. I am no expert, but the suspected PR was probably the cause as it changed some information collection of vertex A/B shaders to be sooner.
