### ISSUE TITLE
[Feature Request] Linux compile guide

### ISSUE THREAD

**Issue by Shoegzer** [Ryujinx/Ryujinx#2312]
A guide to compiling this project on linux systems would be helpful.  Building is of course possible since linux binaries exist, however it is currently unclear what dependencies are needed etc.

I can offer assistance in the development of such a guide where needed, just unsure where to start.

**Comment by edisionnano** [comment]
It's on the readme, you need the dotnet sdk version 5.
Just clone and do dotnet build -c Release

**Comment by Shoegzer** [comment]
Thanks @edisionnano, I should have been clearer though.  The readme could be a bit more intuitive with build sections for both Linux and Windows, with the Linux section having a link for further information that might be helpful to linux users such as [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual) which provides specific information like dependencies involved etc.

**Comment by edisionnano** [comment]
I'm in the process of writing a better guide, the current one I made which is a draft https://github.com/Ryujinx/Ryujinx/wiki/Linux-Setup-Guide-(draft) is too Arch-centric and a bit outdated. You can come at the discord to talk more about it

**Comment by Shoegzer** [comment]
Ah, perfect.  Seems like you have a great start there, but just let me know if you need help.

**Comment by Harmonia2Side** [comment]
> It's on the readme, you need the dotnet sdk version 5. Just clone and do dotnet build -c Release

I have run on an interesting problem when building from source on linux. Following the README instructions, including the above command, sucessfuly build Ryujinx. And yet, trying to run Ryujinx wields an "You must install .NET to run this application" error.
The exact error is as follows: 
```
odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ ./Ryujinx
You must install .NET to run this application.

App: /home/odnankenobi/tmp/ryujinx_build/Ryujinx/build/Ryujinx
Architecture: x64
App host version: 7.0.0
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=pop.22.04-x64&apphost_version=7.0.0
```

below are the outputs of some commands that make me believe that dotnet is actually correctly installed:
```
odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ dotnet 

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ dotnet --version
7.0.100

odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ dotnet --list-sdks
7.0.100 [/usr/lib64/dotnet/sdk]

odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ echo $PATH
/usr/lib64/dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ whereis dotnet
dotnet: /usr/lib64/dotnet /usr/lib64/dotnet/dotnet
```

The command used to install dotnet was found on the [official instructions for scripted install](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install). I might have run this script more than once tough, with differente option, the following was the most recent one:
```
sudo ./dotnet-install.sh --channel 7.0 --install-dir /usr/lib64/dotnet/
```

Also tried to run it with the dotnet command, but to no avail (dunno if it actually makes sense, but I was trying anything at that point :') ):
```
odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ dotnet run Ryujinx
Não foi possível localizar um projeto para executar. Verifique se existe um projeto em /home/odnankenobi/tmp/ryujinx_build/Ryujinx/build ou passe o caminho para o projeto usando --project.

odnankenobi@porygon:~/tmp/ryujinx_build/Ryujinx/build$ dotnet run ./Ryujinx
Não foi possível localizar um projeto para executar. Verifique se existe um projeto em /home/odnankenobi/tmp/ryujinx_build/Ryujinx/build ou passe o caminho para o projeto usando --project.
```

I do wonder what might be the issue.
