### ISSUE TITLE
Pokemon Snap Capture Preview is very low resolution

### ISSUE THREAD

**Issue by morgenman** [Ryujinx/Ryujinx#2315]
### What's the issue you encountered?
Pokemon Snap has an issue where the preview of captured images is very low resolution, as seen in this post:
[Imgur Post](https://imgur.com/a/nllpOfo)

### How can the issue be reproduced?

Run Pokemon Snap, take pictures. 

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.6895</br>
- Game version: 1.0</br>

### Additional context?

N/A

**Comment by gdkchan** [comment]
This is due to resolution scaling, it renders normally without it. That should be noted on the issue.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
