### ISSUE TITLE
Ryujinx fails after update

### ISSUE THREAD

**Issue by VikK909** [Ryujinx/Ryujinx#2338]
**What's the issue you encountered?**

It's been happening for a couple days already that every time I update Ryujinx it would throw the error shown below.

I've tried to handle with it by deleting everything and using Argente Utilities to clean, but it keeps happening, and I dont know exactly what's causing it or how do I fix it.

**How can the issue be reproduced?**

So far the only thing I've seen related to the problem goes to the memory manager. 

**Environment?**

    Ryujinx version: 1.0.6902 (and previous since the introduction of POWER system)

    System Specs:
        OS: Windows 10
        CPU: ryzen 5 2600
        GPU: . NVIDIA RTX 1660
        RAM: 16 GB

   
Thanks for everything.

Edit: Seems to have something to do with the memory manager: both the host and the host unchecked throw me the error while the software mode doesnt. Interestingly enough, it worked with previous iterations of the host and host unchecked until the update. I dont know exactly what makes it work. Also, second edit for formatting.

![console2](https://user-images.githubusercontent.com/85233413/120479631-72a3df00-c3ae-11eb-910c-71549a85bf2e.png)

**Comment by AcK77** [comment]
Please open a new issue following our template with much informations as possible. In this state your report is kind of useless because we have no log file, no game name, etc... Thanks.
