### ISSUE TITLE
Ryujinx crash on Linux trying to play any game

### ISSUE THREAD

**Issue by ryulovesjinx** [Ryujinx/Ryujinx#2340]
### What's the issue you encountered?

After try to play any game on Linux an error is thrown and the application crash.
The below error is for Dragon Ball FighterZ, but can apply for any other. (Was playable, with red screen issues but playable,  before the 3 last updates). 

### How can the issue be reproduced?

Select a game in Linux (Ubuntu 20.04) and try to play.

### Log file

>00:00:01.861 |I| Loader LoadNca: Application Loaded: DRAGON BALL FighterZ v01.27 [0100a250097f0000] [64-bit]
00:00:01.867 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
XError: 0 result is 2
XError: 0 result is 2
00:00:01.946 |E| Application : Unhandled exception caught: SPB.Graphics.Exceptions.ContextException: CreateContext() failed.
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 63
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 50
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
AL lib: (EE) alc_cleanup: 1 device not closed

### Environment?

- Ryujinx version: 1.0.6906</br>
- Game version: 1.27</br>
- System Specs:
  - OS: Linux (Ubuntu 20.04)
  - CPU: Ryzen 5 3600
  - GPU: NVIDIA GTX 670
  - RAM: 16 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Was updated to the latest version.

**Comment by ryulovesjinx** [comment]
All ryujinx settings are set as default,

**Comment by edisionnano** [comment]
Come at the discord #linux-master-race channel so we can help you

**Comment by ryulovesjinx** [comment]
thanks @edisionnano will join
I've tried other distros and is working fine. Maybe something got corrupted.
