### ISSUE TITLE
Ryujinx not working.

### ISSUE THREAD

**Issue by danielpro-rpi** [Ryujinx/Ryujinx#2341]
Hey guys. 

I'm new to this...so this may not be a problem.
When I start Animal Crossing: New Horizons on my pc, it automaticaly crashes...can you please help?
I put a vid down!
[https://www.mediafire.com/file/0ia9tydid3elins/bandicam_2021-06-03_16-11-43-697.mp4/file](url)

**Comment by EmulationFanatic** [comment]
You need a save file for this game. We have one hosted on our Patreon page (for free), or you can import one from anywhere else you like. Come to Discord if you would like more assistance!

**Comment by danielpro-rpi** [comment]
Where is the patreon page?

**Comment by edisionnano** [comment]
https://www.patreon.com/posts/animal-crossing-35196813 get only the save not the build, there are instructions too

**Comment by danielpro-rpi** [comment]
Thx man! I think i will give u 1 dollar on Patreon!
