### ISSUE TITLE
Ryujinx crashed when I playing Diablo III

### ISSUE THREAD

**Issue by may-liu** [Ryujinx/Ryujinx#2346]
### What's the issue you encountered?

Ryujinx crashes when I playing Diablo III.

### How can the issue be reproduced?
when the character selection has been finished, then entering the game , it crashed.

### LOG

00:00:00.007 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.007 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.007 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.008 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.039 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-ldn2.3
00:00:00.042 |N| Application Print: Operating System: Microsoft Windows 10.0.19043 (X64)
00:00:00.042 |N| Application Print: CPU: AMD Ryzen 7 5800X 8-Core Processor ; 16 logical
00:00:00.042 |N| Application Print: RAM: Total 16298 MB ; Available 12715 MB
00:00:00.043 |N| Application PrintSystemInfo: Logs Enabled: Error
00:00:00.043 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.268 |N| Application LoadApplication: Using Firmware Version: 11.0.0
00:00:05.227 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce RTX 3070/PCIe/SSE2 (4.6.0 NVIDIA 466.63)
00:00:17.896 |E| HLE.OsThread.17 ServiceAm OnBackgroundInteractiveData: Received invalid Software Keyboard Calc of 1256 bytes
00:06:30.643 |E| HLE.OsThread.13 SurfaceFlinger DequeueBuffer: No available buffer slots
00:06:30.643 |E| HLE.OsThread.13 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
00:00:00.067 |N| Application LoadApplication: Using Firmware Version: 11.0.0
00:00:00.599 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce RTX 3070/PCIe/SSE2 (4.6.0 NVIDIA 466.63)
00:01:16.227 |E| HLE.GuestThread.16 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFD3B6D17F000.
00:01:16.438 |E| HLE.GuestThread.16 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\project\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 214
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\project\ryujinx\ARMeilleure\Translation\Translator.cs:line 167
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1038
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: 1.X</br>
every version.
- Game version: X.X.X</br>
Diablo III 2.x
- System Specs:
  - OS: WIN10
  - CPU: *(e.g. i7-6700)*
  - GPU: NVIDIA RTX 3070
  - RAM: 32GB
- Applied Mods : NO

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by mpnico** [comment]
Maybe you can provide a savefile or additionnal way to reproduce the problem ? I tried a new game for 30 min with latest master build and game seems to work correctly

**Comment by AcK77** [comment]
Closed for now until we have much informations since game seems to works.
