### ISSUE TITLE
Ryujinx cannot boot with `libsndio` 1.8.0

### ISSUE THREAD

**Issue by IvarWithoutBones** [Ryujinx/Ryujinx#2349]
### What's the issue you encountered?
When you attempt to launch `Ryujinx` with the latest version of `libsndio` (1.8.0), it fails to load. This is because it looks for `libsndio.so.6`, which was renamed to `libsndio.so.7` with the upgrade from 1.7.0 -> 1.8.0. 

To fix this, you can symlink `libsndio.so.7` to `libsndio.so.6`, but this obviously is a rather hacky solution. For testing purposes I've tried this, and everything does seem to fuction as intended.

I think it would be nice if Ryujinx could detect either version of `libsndio`, to ensure comatibility. 

### How can the issue be reproduced?
Install the latest version of `libsdio`, and append it to `LD_LIBRARY_PATH` (Make sure to remove any outdated version from the environment). 

Afterwards, attempt to launch Ryujinx.

### Log file

https://gist.github.com/IvarWithoutBones/167a40d36dd9ab6da0dd419c5bc5a1ea

### Environment?

- Ryujinx version: 1.0.6906</br>
- Game version: N/A</br>
- System Specs:
  - OS: NixOS
  - CPU: AMD Athlon Silver 3050U
  - GPU: Radeon Graphics (Integrated)
  - RAM: 8GB
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
In case you weren't aware, you can get around all this by simply using OpenAL or SDL2 backends.

**Comment by IvarWithoutBones** [comment]
> In case you weren't aware, you can get around all this by simply using OpenAL or SDL2 backends.

As you can see in the logfile, SDL2 fails to initialise because of this. The audio backend is currently set to `OpenAl` in my `Config.json`, yet it still fails.

**Comment by AcK77** [comment]
It seems to be an issue related to SDL initialization! Is your SDL package up to date?

**Comment by IvarWithoutBones** [comment]
My SDL2 is currently on version `2.0.14`, which seems to be the latest.

**Comment by AcK77** [comment]
`I think it would be nice if Ryujinx could detect either version of libsndio, to ensure comatibility.`
This is handled by SDL not by Ryujinx since you have selected SDL backend, it’s not an issue from our LibSoundIO backend.

The only solution for now seems to be the symlink.

**Comment by IvarWithoutBones** [comment]
> Are you sure the file is named `libsndio.so.7` and not `libsndio.so.7.0` or `libsndio.so.7.1` ?

Yes, though `libsndio.so.7.1` also exists.
```
~ > ls /nix/store/1p55q3i2l3zq0gvwq9351q6llbfyl7ym-sndio-1.8.0/lib
libsndio.so  libsndio.so.7  libsndio.so.7.1  pkgconfig
```


> This is handled by SDL not by Ryujinx since you have selected SDL backend, it’s not an issue from our LibSoundIO backend.

I haven't selected the SDL backend though, the initalisation seems to get called unconditionally:
https://github.com/Ryujinx/Ryujinx/blob/eb056218a13fa145adcc9ecafd166b1b1f2caccb/Ryujinx.SDL2.Common/SDL2Driver.cs#L28
https://github.com/Ryujinx/Ryujinx/blob/eb056218a13fa145adcc9ecafd166b1b1f2caccb/Ryujinx.sln#L66

**Comment by AcK77** [comment]
The related issue is https://github.com/libsdl-org/SDL/issues/2531

Since we use SDL for input backend as default, we use it for audio too, and since the initialization fail because of an old SDL bug, that why you can’t launch Ryujinx, but as I said, it’s not a Ryujinx issue there... in that way I close this issue. Thanks for the report, maybe that could help someone else!
