### ISSUE TITLE
New Pokemon Snap No graphics output in AMD graphics card

### ISSUE THREAD

**Issue by yuwenhua653** [Ryujinx/Ryujinx#2359]
### What's the issue you encountered?
Play New Pokemon SnapWhen there is no image output, only audio, or output a few graphics but no text

### How can the issue be reproduced?
run game
### Environment

- Ryujinx version: 1.0.6910</br>
- Game version: 1.0.2</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *R7 5700U*
  - GPU: *AMD Core Graphics*
  - RAM: *16GB*
- Applied Mods :  No

**Comment by AcK77** [comment]
Have you tried another game?

**Comment by yuwenhua653** [comment]
> 你有没有尝试过其他游戏？

Other games are normal

**Comment by AcK77** [comment]
Could you provide a log file please?

**Comment by yuwenhua653** [comment]
> Could you provide a log file please?
[Ryujinx_1.0.6910_2021-06-11_12-35-29.log](https://github.com/Ryujinx/Ryujinx/files/6635876/Ryujinx_1.0.6910_2021-06-11_12-35-29.log)

**Comment by yuwenhua653** [comment]
![image](https://user-images.githubusercontent.com/30205483/121631729-39582700-cab2-11eb-9fba-c151f8613ff4.png)
No dialog

**Comment by AcK77** [comment]
You said « no graphics » but you have posted a screenshot with a rendering... So what’s the real problem then?

**Comment by yuwenhua653** [comment]
> You said « no graphics » but you have posted a screenshot with a rendering... So what’s the real problem then?

When there is an image, there is no text. The picture above is that most of it has no graphics, a black screen or

**Comment by gdkchan** [comment]
Should be fixed by https://github.com/Ryujinx/Ryujinx/pull/2433
