### ISSUE TITLE
Feature Request: Add a frameskip option/feature

### ISSUE THREAD

**Issue by CactiChameleon9** [Ryujinx/Ryujinx#2361]
#### Overview:
- A frameskip option so that not all of a game's frames have to be rendered

#### Smaller Details: 
- Most emulators I have seen allow skipping options of 0-9, along with most having an auto option. A frameskip of 2 being that for every frame that is rendered 2 frames are skipped (I think)
- "Auto" would skip just the right amount of frames so that the game is running at full speed which can be very useful

#### Nature of Request:  
- Addition

### Why would this feature be useful?
Frameskip would help games run at full speed on less powerful hardware, even if it leads to a less smooth gameplay. For example, this could help a user get through laggy cutscene in a particular game or mean that games can be still played at full speed on a laptop without dedicated graphics (or very good integrated).

**Comment by CeruleanSky** [comment]
Duplicate of #1243
The GPU and CPU share memory, and if I I understand things properly, the game code often expect the ram to be modified by GPU operations, including those needed to setup the frames to be draw. Things would destabilize and would get into unexpected states if they were not performed, and it might be tricky to figure out what you could get away with not doing. So if you have to do most of the hard work anyway, there probably isn't much speed to be gained by not showing it off.

**Comment by CactiChameleon9** [comment]
Oops, how did I not find that previous issue?? Sorry for bothering you. Your explanation makes sense, it makes sense how a feature such as this would be harder to implement on more complex consoles - along with the GPU having to render frames so that the CPU has the correct data (didn't know that was a thing). Again, sorry for bothering you and thanks for the explanation.

I will now close this issue
