### ISSUE TITLE
Can't map Right Stick Y axis on generic gamepad

### ISSUE THREAD

**Issue by kael070** [Ryujinx/Ryujinx#2365]
## Bug Report
Yes

### What's the issue you encountered?
One of the gamepads I have doesn't support the mapping of Y axis on the right stick in Ryujinx, but other games work perfectly with it, looking at Joy2Key, the Y axis on the right stick is read as Axis6(<0) and Axis6(>0), which Ryujinx doesn't recognize as a valid input
This makes some games really annoying to play.

### How can the issue be reproduced?

Using the same gamepad I used, it's a Foston generic pad, but probably happens with other gamepads too.

### Environment?

- Ryujinx version: 1.0.6910

- System Specs:
  - OS: Windows 10
  - CPU: 3200G
  - GPU: ^
  - RAM: 8x2GB
  - Applied Mods : No

### Additional context?

Attached file of me moving the right stick up+right on Joy2Key
![Screenshot_33](https://user-images.githubusercontent.com/36388317/121793148-34869680-cbca-11eb-8a8e-578dc51b7e16.png)

Please fix

**Comment by 64ghost** [comment]
On gamepad G-Shark GS-GP702  the right stick does not have a vertical axis.Playing gamepad --> xpadder --> keyboard

**Comment by benderscruffy** [comment]
this can be closed #2907

**Comment by german77** [comment]
The PR was reverted

**Comment by MutantAura** [comment]
Resolved by https://github.com/Ryujinx/Ryujinx/pull/3317
