### ISSUE TITLE
Open the game, display it like this, and jam it

### ISSUE THREAD

**Issue by xiaofeiji7** [Ryujinx/Ryujinx#2366]
## Bug Report

(Ryujinx:20016): Gtk-CRITICAL **: 11:11:00.183: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

### What's the issue you encountered?

Open the game, display it like this, and jam it
![捕获](https://user-images.githubusercontent.com/85782962/121794163-c200cf80-cc38-11eb-923f-16fa44096279.PNG)
![捕获1](https://user-images.githubusercontent.com/85782962/121794165-c2996600-cc38-11eb-8cce-1e25994cc6f3.PNG)

### Log file

00:00:00.010 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.011 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.011 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.012 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.014 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.023 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.023 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.023 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.023 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.023 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.024 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.024 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.024 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.024 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.026 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6910
00:00:00.030 |N| Application Print: Operating System: Microsoft Windows 10.0.19041 (X64)
00:00:00.030 |N| Application Print: CPU: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz ; 8 logical
00:00:00.030 |N| Application Print: RAM: Total 16221 MB ; Available 11658 MB
00:00:00.032 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.032 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### Environment?

- Ryujinx version: 1.0.X</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
This looks more than an issue at your end, please come to our discord for support, those issues are for development support only. Thanks.
