### ISSUE TITLE
Game Builder Garage freezes/crashes randomly 

### ISSUE THREAD

**Issue by Gummygamer** [Ryujinx/Ryujinx#2376]
### What's the issue you encountered?

While I run Game Builder Garage, in random moments it freezes and so the FPS goes to zero or I get a crash.
I've made no changes to the current code yet.

### How can the issue be reproduced?

From earlier experiments, I've seen Ryujinx crashing a lot in tutorials, but I run specifically the free programming mode with the help save data, it works, but in random circumstances while I edit the "game", the emulation freezes/crashes.

### Log file

This is a log for crashing on the normally downloaded version of Ryujinx.

https://www.mediafire.com/file/kgqd4hyrgcziii8/Ryujinx_1.0.6914_2021-06-19_19-30-15.log/file

This is a log for freezing, although I couldn't find in it anything specific to the issue yet. For this I ran a local build from the current normal source.

https://www.mediafire.com/file/cdxh2drd3pl9pxi/Ryujinx_1.0.0-dirty_2021-06-20_10-52-07.log/file

### Environment?

- Ryujinx version: 1.0.6914</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: i5-9300H
  - GPU: NVIDIA Geforce GTX 1650
  - RAM: 8GB
- Applied Mods : No

**Comment by Gummygamer** [comment]
At least partially solved by my latest PR.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
