### ISSUE TITLE
A crash problem occurs when running animals across the new horizon！

### ISSUE THREAD

**Issue by HelloZelda** [Ryujinx/Ryujinx#2385]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.0-ldn2.3-win_x64
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.10.0 animals across the new horizon
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS:  Microsoft Windows 10.0.19042 (X64)
  - CPU: AMD Ryzen 7 4800H with Radeon Graphics ; 16 logical
  - GPU: NVIDIA RTX 2060(laptop)
  - RAM: 24GB
- Applied Mods : No

### Additional context?

Additional info about your environment:The error message is as follows
00:01:30.429 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Templates"
00:01:30.490 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\S-1-5-21-1857413672-613737915-1279695270-500\SystemAppData\Helium\Cache"
00:01:30.491 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\S-1-5-21-1857413672-613737915-1279695270-500\SystemAppData\Helium\Cache"
00:01:30.493 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\S-1-5-21-1857413672-613737915-1279695270-1007\SystemAppData\Helium\Cache"
00:01:30.494 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\S-1-5-21-1857413672-613737915-1279695270-1007\SystemAppData\Helium\Cache"
00:01:30.506 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Packages\Microsoft.SkypeApp_kzf8qxf38zg5c\S-1-5-21-1857413672-613737915-1279695270-500\SystemAppData\Helium\Cache"
00:01:30.507 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Packages\Microsoft.SkypeApp_kzf8qxf38zg5c\S-1-5-21-1857413672-613737915-1279695270-500\SystemAppData\Helium\Cache"
00:01:30.986 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Trace"
00:01:30.987 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Trace"
00:01:30.988 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Temp\PSScriptOutputs"
00:01:30.988 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Temp\PSScriptOutputs"
00:01:30.989 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Downloads"
00:01:30.993 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Downloads"
00:01:30.994 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\DataCollection"
00:01:30.994 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\DataCollection"
00:01:30.995 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Cyber"
00:01:30.995 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Cyber"
00:01:30.996 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Cache"
00:01:30.997 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows Defender Advanced Threat Protection\Cache"
00:01:31.312 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows\SystemData"
00:01:31.313 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows\SystemData"
00:01:31.314 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows\Start Menu\程序"
00:01:31.314 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Microsoft\Windows\Start Menu\程序"
00:01:32.398 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Documents"
00:01:32.399 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\All Users\Documents"
00:01:33.461 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\「开始」菜单"
00:01:33.461 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\「开始」菜单"
00:01:33.461 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Templates"
00:01:33.462 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Templates"
00:01:33.462 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\SendTo"
00:01:33.462 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\SendTo"
00:01:33.462 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Recent"
00:01:33.462 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Recent"
00:01:33.463 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\PrintHood"
00:01:33.463 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\PrintHood"
00:01:33.463 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\NetHood"
00:01:33.463 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\NetHood"
00:01:33.463 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\My Documents"
00:01:33.464 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\My Documents"
00:01:33.464 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Local Settings"
00:01:33.464 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Local Settings"
00:01:33.466 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Documents\My Videos"
00:01:33.466 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Documents\My Videos"
00:01:33.467 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Documents\My Pictures"
00:01:33.467 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Documents\My Pictures"
00:01:33.467 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Documents\My Music"
00:01:33.467 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Documents\My Music"
00:01:33.468 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Cookies"
00:01:33.468 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Cookies"
00:01:33.469 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Application Data"
00:01:33.469 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\Application Data"
00:01:33.472 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu\程序"
00:01:33.472 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu\程序"
00:01:33.503 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\AppData\Local\Temporary Internet Files"
00:01:33.503 |W| GUI.ApplicationLibraryThread Application GetFilesInDirectory: Failed to get access to directory: "C:\Windows.old\Users\Administrator\AppData\Local\Temporary Internet Files"
00:01:35.861 |S| HLE.OsThread.17 ServiceFs ReadSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute: Stubbed.
00:01:35.899 |S| HLE.OsThread.17 ServiceOlsc Initialize: Stubbed.
00:01:35.917 |S| HLE.OsThread.17 ServiceOlsc SetSaveDataBackupSettingEnabled: Stubbed. {userId: 00000000000000000000000000000001 ; saveDataBackupSettingEnabled: 0}
00:01:37.176 |E| Application : Unhandled exception caught: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows.old\Users\Administrator\AppData\Local\Packages\Microsoft.VWDoubleCab61_8wekyb3d8bbwe\TempState'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Ryujinx.Ui.App.ApplicationLibrary.GetFilesInDirectory(String directory)+MoveNext() in C:\project\ryujinx\Ryujinx\Ui\App\ApplicationLibrary.cs:line 79
   at Ryujinx.Ui.App.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in C:\project\ryujinx\Ryujinx\Ui\App\ApplicationLibrary.cs:line 140
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by HelloZelda** [comment]
Does the game support playing in LDN mode

**Comment by HelloZelda** [comment]
Animals through new horizons Version 1.1.1 is operational

**Comment by AcK77** [comment]
Change your folder game directory path.
This is for development issue not user support so I suggest you to come to our discord.
Additionally, you don’t follow our issue template.
Thanks.
