### ISSUE TITLE
Platform specific files for libsoundio are all provided with the build

### ISSUE THREAD

**Issue by AcK77** [Ryujinx/Ryujinx#2399]
### What's the issue you encountered?

Since #2211 is merged, we can still cleanup it a bit more, we currently pack libsoundio dependencies in the repo directly, which lead, as example, to get the `.so` and the `.dylib` files in the windows build zip.

Using a nuget package could fixes the issue by return the platform specific file.

**Comment by Tatsh** [comment]
Is it possible libsoundio be made optional at compile time?
