### ISSUE TITLE
Mario Golf: Super Rush shader problem remains even updated with latest build

### ISSUE THREAD

**Issue by CK21BR** [Ryujinx/Ryujinx#2409]
Hello, I'm still having problems with Mario Golf: Super Rush shader issue. I updated the build to the latest one (1.0.6937) and the firmware to the latest one as well (12.0.3) but the game still does not show the course or the ball. Tried changing back to 12.0.2, tried other builds, tried building myself using netcore and the issue still remains. Don't know what else to do.

**Comment by edisionnano** [comment]
No log, no specs, no screenshots. You can come by the discord to talk

**Comment by CK21BR** [comment]
I apologize, I wasn't aware, I will put it on discord.
