### ISSUE TITLE
ファミコン探偵倶楽部 消えた後継者 - Audio desync

### ISSUE THREAD

**Issue by RicBent** [Ryujinx/Ryujinx#2417]
### What's the issue you encountered?

Audio slowly desyncs when playing ファミコン探偵倶楽部 消えた後継者 (Famicom Detective Club: The Missing Heir) with the audio lagging behind up to multiple seconds after a few hours. This is not related to stutters or similar as I left the game open on a menu for a few hours and the same desync happened.

I also left the game running on my Switch at the same scene over night. No desync happened there so it isn't a game bug.

### How can the issue be reproduced?

Leave the game running for ~5 hours for a ~1 second audio delay.

### Log file

Forgot to save a log. If required I can provide a log after letting the game run for a few hours.

### Environment?

- Ryujinx version: 1.0.6939</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Manjaro 21.0.7 Ornara (Linux 5.10.42-1-MANJARO)
  - CPU: i7-4790k
  - GPU: GTX 970
  - RAM: 16GB
- Applied Mods : N/A

### Additional context?

Additional info about your environment:</br>N/A

**Comment by jroberts2010** [comment]
This also occurs in Fire Emblem - Three Houses.
Specs:
Manjaro
Ryzen 3600
Rx 5700
16gb DDR4
