### ISSUE TITLE
Fire emblem Three House  CRASH

### ISSUE THREAD

**Issue by michaellongge163** [Ryujinx/Ryujinx#2421]
![Snipaste_2021-06-28_16-27-38](https://user-images.githubusercontent.com/66716069/123606862-e9a68900-d82f-11eb-8bd1-229f688970ad.jpg)
![Snipaste_2021-06-28_16-31-19](https://user-images.githubusercontent.com/66716069/123606901-f32ff100-d82f-11eb-9252-221f28504c2e.jpg)

**Comment by AcK77** [comment]
Reopen it following the template, thanks.
