### ISSUE TITLE
The Touryst - Severe memory leak

### ISSUE THREAD

**Issue by SilverBeamx** [Ryujinx/Ryujinx#2423]
### What's the issue you encountered?

The game The Touryst suffers from a severe memory leak in certain areas. For the time being, this has been observed in the "shirt shop" in the northern part of Hawayy Island. RAM starts expanding fast, 300+ MB/s, until page swap kicks in, and the drive gets hammered, slowing the whole system down to a crawl. Exiting the incriminated sub-area, all the resources are released, and everything goes back to normal.

### How can the issue be reproduced?

Go to Hawayy Island, and enter the "shirt shop" sub area located opposite to the drop-off point.

### Log file

The log doesn't report anything out of the ordinary.

### Environment?

- Ryujinx version: 1.0.6941</br>
- Game version: 1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i5-8600k
  - GPU: nVidia GTX 1060 6Gb
  - RAM: 16 Gb
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Here is a save that starts the player at Hawayy Island: 
[Touryst Save.zip](https://github.com/Ryujinx/Ryujinx/files/6733000/Touryst.Save.zip)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
