### ISSUE TITLE
Smash Ultimate Version 11.0.0 Displays Blank Screen When Selecting Smash Mode

### ISSUE THREAD

**Issue by nishantc1527** [Ryujinx/Ryujinx#2426]
### What's the issue you encountered?

When playing Smash Bros Ultimate on update 11.0.0, when trying to go to Smash mode Ryujinx just displays a blank black screen.
I did not make any changes to Ryujinx.

### How can the issue be reproduced?

1. Download Smash Bros Ultimate
2. Download update 11.0.0 for Smash Bros Ultimate
3. Open Smash Bros Ultimate
4. In the home screen in Smash Bros, select Smash, then Smash again.
5. You will see a blank dark screen.

### Environment?

- Ryujinx version: 1.0.0-ldn2.3</br>
- Game version: 11.0.0</br>
- System Specs:
  - OS: Manjaro Linux (Also tried on Windows, didn't work there either)
  - CPU: AMD Ryzen 5 5600X
  - GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
  - RAM: 16 GB
- Applied Mods : No

### Additional context?

I tried on multiple Ryujinx versions, all of which didn't work. When I set the version back to default, then it works. I tried on both Linux and Windows, and it didn't work on either.

**Comment by AcK77** [comment]
What if you use the latest version of Ryujinx and not LDN2.3 ?

**Comment by AcK77** [comment]
Hum, haven't noticed directly but I'm not sure about:

```
- Download Smash Bros Ultimate
- Download update 11.0.0 for Smash Bros Ultimate
```

We don't support piracy here. Thanks.
