### ISSUE TITLE
[Pokemon Sw/Sh] Daily events + Pokejobs broken

### ISSUE THREAD

**Issue by SinFlame** [Ryujinx/Ryujinx#2430]
### What's the issue you encountered?
RTC doesn't run ingame. This affects majority of time based events, berry picking, den resets and pokejobs.
Changing clock in Ryu settings doesn't fix it. Although weirdly, Weather changes happen. 

### How can the issue be reproduced?
Register for a pokejob in pokemon centre and wait a few hours. Check back on the job and it will still state 24 hours remaining.

### Log file
No log files given as it isn't crash related. 

### Environment?

- Ryujinx version: 1.0.6945</br>
- Game version: 1.3.2</br>
- System Specs:
  - OS: Microsoft Windows 10.0.19042 (X64)
  - CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz ; 8 logical
  - GPU: NVIDIA RTX 3060
  - RAM: 32GB
- Applied Mods : Yes

### Additional context?

Additional info about your environment:</br>

**Comment by Leischii** [comment]
This effects all events that need time to pass. So in addition to the Pokejobs problem, it also effects the respawning of berries, raids and wandering Pokemon.
Noteworthy behaviour: Pokejobs work as long as you don't close the emulator. If you close it, the time resets to the initial time.
E.g. Starting 2h Pokejob, waiting 1:59h without closing the emulator, restarting the game --> Time left is 2h again

**Comment by TheSuspect2306** [comment]
few month later, when will it be fixed, its really not fun :/

**Comment by da-welsh** [comment]
Strangely enough, last night I updated from 1.0.7082 to 1.0.7093. 

On doing so, when I launched I noticed it was night time in game, which seemed odd. Mostly due to me never having played at night. 

However, it did cause me to check my pokejobs, and lo and behold, a job that was set for 1 hour - that had been active for weeks - was complete.  This learly was not because i had been running for an hour, i had just launched the emulator after an update. It did lead me to wonder if there was something in the updates that had messed with the clock. after checking the log, i wondered if it had anything to do with the timezone implementation? Im off UTC by 1 hour, so that could be something? or maybe it was a freak action that forced it to complete? 

Either way, **something** happened in those updates that caused a 1 hour pokejob to complete.

**Comment by Begueiro** [comment]
I'm having a similar issue, on the latest Ryujinx release, 1.0.7107 (which I think came out today).

When trying to change the date, with the game running, the date doesn't change at all. The weather remains the same, the wild area vendors items don't change and the dens don't reset either. That's all I've noticed so far.

For them to change, I need to restart the emulation, with the new date. If I change the date, with the game still running, nothing happens.

**Comment by KostaSaizo7** [comment]
> This change doesn't seem to fix the issue, in-game time still doesn't work

Second that, Pokejobs stay the same. I sent a pokemon to a job with "12 hours left", saved the game, closed the emulator. After 10 hours, I loaded the save and still "12 hours left".

**Comment by KostaSaizo7** [comment]
Interesting: I started a new save file, played until pokejobs are unlocked and it works! 

So, I guess that save files, that were made before the pr was merged, are corrupted.

**Comment by SkyDragonV1** [comment]
> Interesting: I started a new save file, played until pokejobs are unlocked and it works!
> 
> So, I guess that save files, that were made before the pr was merged, are corrupted.

I was able to fix the save file with PKHeX. The value of both of these should be 0 (A7301FBD and 33068788). I noticed this by comparing saves from the newest version of Ryujinx and the version prior to the fix.

![2023-05-11_010723](https://github.com/Ryujinx/Ryujinx/assets/129783486/afb0f416-c3d4-40ba-b242-1d4e4b2b7dfc)
![2023-05-11_010640](https://github.com/Ryujinx/Ryujinx/assets/129783486/d0274a56-480f-4690-bdde-ec6e5b299009)

**Comment by KostaSaizo7** [comment]
> I was able to fix the save file with PKHeX. The value of both of these should be 0 (A7301FBD and 33068788). I noticed this by comparing saves from the newest version of Ryujinx and the version prior to the fix.

Thank you so much! This fixed my save file! @marysaka could this fix be implemented in Ryujinx?

**Comment by Lucas-Zxc** [comment]
hey, about the 15.0.0 thing, it seems to have been solved in the past, but today, the problem, at least in the Wild Area, seems to have returned

**Comment by Lucas-Zxc** [comment]
I'm still investigating, but whatever it is, I hope it can be resolved

**Comment by Double-0-seven7** [comment]
> > Interesting: I started a new save file, played until pokejobs are unlocked and it works!
> > So, I guess that save files, that were made before the pr was merged, are corrupted.
> 
> I was able to fix the save file with PKHeX. The value of both of these should be 0 (A7301FBD and 33068788). I noticed this by comparing saves from the newest version of Ryujinx and the version prior to the fix.
> 
> ![2023-05-11_010723](https://user-images.githubusercontent.com/129783486/237578843-afb0f416-c3d4-40ba-b242-1d4e4b2b7dfc.png) ![2023-05-11_010640](https://user-images.githubusercontent.com/129783486/237578857-d0274a56-480f-4690-bdde-ec6e5b299009.png)

Is there a way to do something similar if you moved the save from yuzu to ryujinx?
Even doing this with pkhex didnt help me fix the issue.
