### ISSUE TITLE
Mii Maker Applet Interface Not Showing

### ISSUE THREAD

**Issue by MemeThorn** [Ryujinx/Ryujinx#2431]
### What's the issue you encountered?

When opening the Mii Maker Applet, the initial interface for choosing a mii and choosing a lookalike, sex etc. shows, but anything beyond that shows as a blank. Navigating in and out of menus shows them briefly, but then they disappear.
![image](https://user-images.githubusercontent.com/86714320/123934421-1cdc3b80-d948-11eb-8355-1343f8e79940.png)

### How can the issue be reproduced?

Using 64-bit Ryujinx (1.0.6945) and System Firmware 12.0.3, launch the Mii Maker Applet and navigate past the lookalike/male-female screen.

### Log file

Not crash-related, log file for convenience 

[Ryujinx_1.0.6945_2021-06-30_02-05-54.log](https://github.com/Ryujinx/Ryujinx/files/6739583/Ryujinx_1.0.6945_2021-06-30_02-05-54.log)
 

### Environment?

- Ryujinx version: 1.0.6945

- Game version: N/A

- System Specs:
  - OS: Windows 10
  - CPU: i7-1165G7
  - GPU: Intel Iris Xe
  - RAM: 8GB
- Applied Mods : None

### Additional context?

Additional info about your environment:

Running on integrated graphics card, can run games perfectly fine, it's only the Mii Maker that's not working.

**Comment by Benedani** [comment]
As a temporary fix, AMD/Intel GPU users can consider running Ryujinx on Linux, where the OpenGL drivers are significantly better. You could get better performance as well.

**Comment by riperiperi** [comment]
This has been identified as an issue with texture copy dependencies, which are used on intel/amd to work around a texture view bug in their drivers.

**Comment by Benedani** [comment]
Should also be fixed by #2433 (which is in master now), can you verify?

**Comment by gdkchan** [comment]
Yea thanks, I thought the PR description had a link to this issue, but looks like it didn't.
