### ISSUE TITLE
Screenshot function does not work with gaming laptops with dedicated & integrated graphics. 

### ISSUE THREAD

**Issue by ugoplatamia** [Ryujinx/Ryujinx#2435]
### What's the issue you encountered?

Screenshot function does not work with laptops that have integrated + dedicated graphics. Tried on a conventional desktop system and works fine. No screenshots are made in the respective screenshot folder.

### How can the issue be reproduced?

Pressing either F8 or clicking "Take Screenshot" from the menu.

### Environment?

- Ryujinx version: 1.0.6945</br>
- System Specs:
  - Laptop Model: Asus TUF FX504GD 
  - OS: Windows 10
  - CPU: i5-8300H
  - GPU: NVIDIA 1050, Intel UHD Graphics 630
  - RAM: 16GB
- Applied Mods : None

### Additional context?
Ryujinx is specified to use the dedicated Nvidia GPU when running games.
NVIDIA Driver Version: 30.0.14.71111 (6/21/2021)

**Comment by Leischii** [comment]
Please remove the lines in brackets. It's noted in the template "[ Lines between [ ] (square brackets) should be removed before posting. ]"

**Comment by emmauss** [comment]
could you please upload logs. I do not experience this and I've tested this on 2 hybrid systems, Intel/Nvidia and Amd/Nvidia.

**Comment by AcK77** [comment]
Works fine here too on a laptop with Intel/Nvidia. Could we get any informations like logs as emmauss asked you ?

**Comment by ugoplatamia** [comment]
[Ryujinx_1.0.6946_2021-07-04_14-24-23.log](https://github.com/Ryujinx/Ryujinx/files/6760411/Ryujinx_1.0.6946_2021-07-04_14-24-23.log)

Here is a log. Here are some other things I've tried since the post:

-Used a different keyboard to hit F8, to rule out a physical hardware issue.
-Disabled the laptop's keyboard hotkeys.
-Instead of forcibly using the dedicated GPU for all tasks, have the preferred GPU set to "auto", the set Ryujinx to use the dedicated GPU.

**Comment by emmauss** [comment]
Do you have access to the current users picture folder?
Does the game halt for a second or less when the screenshot key is pressed?

**Comment by ugoplatamia** [comment]
I have full access to the folder. Tried deleting the folder, and Ryujinx makes the folder when I hit the screenshot button. It doesn't feel like the game halts when attempting to make a screenshot.

**Comment by emmauss** [comment]
can you try out #2447 .

**Comment by ugoplatamia** [comment]
Tried out the portable screenshot build and it works. Thanks.
