### ISSUE TITLE
Analysis of 'Ryujinx' source code by PVS-Studio static code analyzer

### ISSUE THREAD

**Issue by MrKruizer** [Ryujinx/Ryujinx#2450]
Hello, the PVS-Studio static code analyzer checked your project. You can see the results in my article on the PVS-Studio official website: https://pvs-studio.com/en/blog/posts/csharp/0840/

**Comment by emmauss** [comment]
This is not an issue. Closing.

**Comment by emmauss** [comment]
If you want to share information from external sources on the project, please do so on the discord server.

**Comment by emmauss** [comment]
Though I would say it's an interesting analysis.
