### ISSUE TITLE
Dragon Ball FighterZ - Red Screen / Flickering

### ISSUE THREAD

**Issue by codbugpatrol** [Ryujinx/Ryujinx#2454]
### What's the issue you encountered?
While on character selection screen and on fight loading, the game do not render the background correctly, flicking the correct image or with an static red screen. (**This part is fixed** (PR #2481) : Also during the game play, after a special attack, sometimes the white flickering starts and visual glitches begin.)

![DragonBallFighterZ_RedBackground_Flickering](https://user-images.githubusercontent.com/85196112/124982275-e5872200-e00c-11eb-8579-623c80996417.jpg)
![DragonBallFighterZ_RedBackground_Flickering_2](https://user-images.githubusercontent.com/85196112/124982279-e750e580-e00c-11eb-9570-826a0b672498.jpg)
![DragonBallFighterZ_RedBackground_Flickering_3](https://user-images.githubusercontent.com/85196112/124982286-e8821280-e00c-11eb-8968-2329690470ca.jpg)
![DragonBallFighterZ_RedBackground_Flickering_4](https://user-images.githubusercontent.com/85196112/124982295-e9b33f80-e00c-11eb-8641-1b5576ab36e7.jpg)

**This part is fixed** (PR #2481):
Visual Glitches after a special attack (it seems related to the above issue, as starts with flickering):
TEST WITH VEGITO (Potara Version), because it also, after any special, cause irreparable visual glitches in the round.
![image](https://user-images.githubusercontent.com/85196112/125681980-67f59e90-a172-4606-9ecc-c81fdf3f2367.png)

### How can the issue be reproduced?
Go on character selection screen in any mode. 
Select any characters you like and load the fight.

### Log file

00:01:01.014 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: GL_INVALID_VALUE error generated. <offset> is negative or <size> is less than or equal to zero or <offset> is not an integer multiple of TEXTURE_BUFFER_OFFSET_ALIGNMENT.
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   at Ryujinx.Graphics.OpenGL.Image.TextureBuffer.SetStorage(BufferRange buffer)
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitBufferTextureBindings()
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitComputeBindings()
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument)
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

    Ryujinx version: 1.0.6956

    Game version: 1.27

    System Specs:
        OS: Windows 10
        CPU: Ryzen 5 3600
        GPU: NVIDIA GTX 670
        RAM: 16GB

    Applied Mods : Yes
    All DLCs applied.

### Additional context?
[DragonBallFighterZ_RedBackground_Flickering__Ryujinx_1.0.6956.log](https://github.com/Ryujinx/Ryujinx/files/6786936/DragonBallFighterZ_RedBackground_Flickering__Ryujinx_1.0.6956.log)

**Comment by Leischii** [comment]
Please stop opeing issues for game specific issues. That's what the game compatibility list is for. Also you noted this issue already in the games issue ticket.

**Comment by ryulovesjinx** [comment]
> Please stop opening issues for game specific problems. That's what the game compatibility list is for. Also you noted this issue already in the games issue ticket.

This is an issue that still happening and it is a bug. Fixing this might fix another UE4 games. Its noted by me on the game specific page but no solution or even attention was giving. This should only be closed when the error disapear. 

Open issue on games is necessary to have real track of the gaps of the application.

**Comment by gdkchan** [comment]
I believe this is a regression that started happening after https://github.com/Ryujinx/Ryujinx/pull/2089 (I did not confirm myself though). Might be caused by some shader hiting the 32 samplers limit.

**Comment by ryulovesjinx** [comment]
Thanks @gdkchan for the quick reply on this. I am not a developer, but testing as much as I can the application to make it better.

**Comment by codbugpatrol** [comment]
PR #2481 fixes part of the problem.
Visual glitches after a special attack no longer happen.

**Comment by codbugpatrol** [comment]
An update, with Vulkan this does not happen, test in PR: https://github.com/Ryujinx/Ryujinx/pull/2518
Problem only occurs on OpenGL.

**Comment by codbugpatrol** [comment]
@gdkchan, news regarding this. Might worth a check in the BGR8 for the backscreen screen of char selection screen, other games may be affected as well, right ?The other emulator now is facing the same problem, and it is certain that the problem is in BGR (BRG8 maybe?), because of the copies being blacklisted or overlayed, not sure.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
