### ISSUE TITLE
QuriousPixel Appimage does not open in PopOS 21.04

### ISSUE THREAD

**Issue by Heroofthenexus** [Ryujinx/Ryujinx#2455]
After downloading QuriousPixel's Appimage and attempting to use it, it simply refuses to open. Occasionally an update prompt will appear, but regardless the emulator itself fails to open.

**Comment by AcK77** [comment]
Since it’s a custom package made by someone else and since we don’t have any official Appimage, we can’t give you support on your issue, you have to ask the package creator.
Thanks.

**Comment by edisionnano** [comment]
Id suggest that you join the discord and ask on the linux channel for help on using the official builds

**Comment by qurious-pixel** [comment]
> After downloading QuriousPixel's Appimage and attempting to use it, it simply refuses to open. Occasionally an update prompt will appear, but regardless the emulator itself fails to open.

Make sure to  rename the Ryujinx `.config/Ryujinx` files, or to turn off logging first. The `Config.json` attempts to write to a read-only part of the appimage and fails to launch.

**Comment by Heroofthenexus** [comment]
> > After downloading QuriousPixel's Appimage and attempting to use it, it simply refuses to open. Occasionally an update prompt will appear, but regardless the emulator itself fails to open.
> 
> Make sure to rename the Ryujinx `.config/Ryujinx` files, or to turn off logging first. The `Config.json` attempts to write to a read-only part of the appimage and fails to launch.

Thanks for the advice, I reinstalled Pop OS a while back and it ended up working just fine. I wish I had the same luck with the LDN 2.3 build, unfortunately it outright crashes every time I try to load a game. If there is an LDN version of the Appimage in the works, I'd love to try it.
