### ISSUE TITLE
Mario + Rabbids Kingdom Battle graphics bug

### ISSUE THREAD

**Issue by turkeynaruto** [Ryujinx/Ryujinx#2459]
**When you start the game in Docked Mode it has this weird black Pixels Effect.**

![Erfassen](https://user-images.githubusercontent.com/18088164/125161638-c2cb4980-e183-11eb-9d59-d65b7b483a92.PNG)

**Now you go Portable Mode and the game looks like this.**

![Erfassen2](https://user-images.githubusercontent.com/18088164/125161684-fe661380-e183-11eb-92cd-100c36471e69.PNG)

**And now you go Docked Mode again and the game looks totally normal.**

![Erfassen3](https://user-images.githubusercontent.com/18088164/125161730-366d5680-e184-11eb-81fe-ebf8c60d6293.PNG)

**Additonal Note:
You can also start the game in Portable Mode and it would have the Black Pixels.
Then go Docked and they are gone.
So its not like the Portable Mode fixes it its the change which fixes it.**

**This is also just in the non updated version of the game.
When you run the game with its newest update it seems this bug doesnt exists and it works directly fine.**

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
