### ISSUE TITLE
Animal Crossing:New Horizons Boot Freeze (Windows 11)

### ISSUE THREAD

**Issue by waaak** [Ryujinx/Ryujinx#2462]
### What's the issue you encountered?

While trying to boot AC:NH, Ryujinx Freezes instantly

### How can the issue be reproduced?

Try boot AC:NH on Windows 11 Insider beta

### Log file

[Ryujinx_1.0.6959_2021-07-11_18-00-43.log](https://github.com/Ryujinx/Ryujinx/files/6796606/Ryujinx_1.0.6959_2021-07-11_18-00-43.log)

### Environment

- Ryujinx version: 1.0.6959
- Game version: 1.10.0
- System Specs:
  - OS: Windows 11 Insider Dev channal
  - CPU: AMD Ryzen 5 3600
  - GPU: NVIDIA RTX 2070
  - RAM: 16GB
- Applied Mods : No

### Additional context

- OS Build: 22000.65 co_release
- Firmware: 12.0.3

**Comment by Benedani** [comment]
The log contains nothing useful... Did you upload the wrong file?
Does it work on Windows 10?

**Comment by AcK77** [comment]
Incomplete issue, I close it for now until more informations.

**Comment by waaak** [comment]
> The log contains nothing useful... Did you upload the wrong file?
> Does it work on Windows 10?

I don't think so. Ryujinx stops right after clicking on the game.
it works perfectly on windows 10.
