### ISSUE TITLE
Miitopia Crashing at a consistent point.

### ISSUE THREAD

**Issue by PizaPocket4** [Ryujinx/Ryujinx#2463]
### What's the issue you encountered?

Ryujinx is crashing at a consistent spot in Miitopia.</br>
I've left Ryujinx on stock settings aside from controls.</br>

### How can the issue be reproduced?

Start Miitopia with a save that has not cleared the underground maze yet. Play normally until you get to a gate in said underground maze and try to proceed. Your party will walk up, you will hear one of them talk but it will freeze before any speech bubble comes up. After that it just closes the entire emulator.

### Log file

[Ryujinx_1.0.6959_2021-07-11_08-56-35.log](https://github.com/Ryujinx/Ryujinx/files/6796953/Ryujinx_1.0.6959_2021-07-11_08-56-35.log)</br>

### Environment?

- Ryujinx version: 1.0.6959 </br>
- Game version: 1.0.3 </br>
- System Specs:
  - OS: Windows 10 Pro
  - CPU: Intel Core I7
  - GPU: GTX 1660 TI
  - RAM: 2933 MHZ (up to 32GB) DDR4
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ N/A ]

**Comment by jduncanator** [comment]
Do you have a save game you could provide us in the affected area? It allows us to quickly diagnose the issue, without having to play the game up to the problem area.

**Comment by ken152436** [comment]
Hi, I encounter similar crash issue (Show up "Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x3XXXXXXXX..0x3XXXXXXXX is not fully mapped" when it try to create texture) like him in different situation.

A save file(Mitopia_save-crash-0810.zip) is provided and you can try to reproduce the issue, thanks.

Before crash
![image](https://user-images.githubusercontent.com/88676670/128741955-8add9a2d-4f53-46c2-85fd-7458d6a06636.png)

Crash after enter the stage
![image](https://user-images.githubusercontent.com/88676670/128742197-51256a5b-e38b-4d1f-89a3-b06afbd0f15f.png)


**Environment?**
Ryujinx version: 1.0.6982
Game version: 1.0.2
System Specs:
OS: Windows 10
CPU: AMD Ryzen 7 3700X 8-Core Processor 
GPU: RTX 3080
RAM: 2400 MHZ (up to 32GB) DDR4
Applied Mods : [ No ]

**Log file**
[Ryujinx_1.0.6982_2021-08-10_00-34-27.log](https://github.com/Ryujinx/Ryujinx/files/6956041/Ryujinx_1.0.6982_2021-08-10_00-34-27.log)
[Mitopia_save-crash-0810.zip](https://github.com/Ryujinx/Ryujinx/files/6956051/Mitopia_save-crash-0810.zip)

**Comment by GamerzHell9137** [comment]
> inx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x3XXXXXXXX..0x3XXXXXXXX is not fully mapped" when it try to create texture) like

With the linked save the scene goes trough and the emulator runs fine with the new build.
![image](https://user-images.githubusercontent.com/2002038/153507940-8231ef04-6dcf-4cb8-a063-92165535143d.png)
