### ISSUE TITLE
Motion control x axis is inverted

### ISSUE THREAD

**Issue by meisiek** [Ryujinx/Ryujinx#2480]
### What's the issue you encountered?

The motion control x axis is inverted (SDL2).

### How can the issue be reproduced?

Connect a switch pro controller and start a mario kart 8 time trial. Press Y after the start to switch to motion control steering. When you tilt your controller left the kart steers right.
The same thing happens in BOTW.  You can test it with the apparatus in the Myahm Agana shrine.

The motion control X axis works fine in cemu and yuzu (same controller, same pc and both using SDL2).

### Environment?

- Ryujinx version: 1.0.6969

- System Specs:
  - OS: Windows 10
  - CPU: i7-8700
  - GPU: NVIDIA RTX 3080
  - RAM: 32GB
- Applied Mods : No mod in MK8 and 30fps mod in BOTW

**Comment by legend800** [comment]
I can confirm this issue. Native motion support has been broken since day 1 a few months ago and I've just been using betterforjoy for proper motion.

**Comment by legend800** [comment]
This is still active as of 2/5/21. I've spent an hour in Super Mario Party with a Pro Controller and tried holding it every possible direction and it never quite works right consistently. What's weird is if I do find something that works, it changes after a min. 

Using BetterJoy gives me 100% perfect motion. Something is missing with Ryujinx native impleemention like it doesn't support Pro Controllers properly or something.
