### ISSUE TITLE
Fire Emblem Three Houses Shader Crashes

### ISSUE THREAD

**Issue by Aghathis** [Ryujinx/Ryujinx#2485]
### What's the issue you encountered?

Matter of guesses but when launching Fire emblem Three houses with shader cache when it finished to compil them the emulator crash entirely. 
also if you choose to do choir in the monastery the game also crash

### How can the issue be reproduced?

Launch the game with shader caches
do choir in monastery free time.

### Log file

don't have log

### Environment?

- Ryujinx version: 1.0.6970 (also tested on 1.0.6969)</br> 
- Game version: 1.20</br>
- System Specs:
  - OS: Windows 10 v.2004 build 19041.1110 
  - CPU: i7-7700HQ
  - GPU: NVIDIA GTX 1070
  - RAM: 8gb

### Additional context?
the game work kinda perfectly (except low fps in monastery) some days ago... and work in the two version i tested if you delete the shader cache

**Comment by Aghathis** [comment]
tested on 1.0.6961 and the bug doesn't occurs...

**Comment by AcK77** [comment]
Could you provide a log file please? The issue à bit useless without one since you said « it crashes » and that could be anything...

**Comment by Aghathis** [comment]
> Could you provide a log file please? The issue a bit useless without one since you said « it crashes » and that could be anything...
