### ISSUE TITLE
Slow fps in TLoZ SSHD after PR ca5ac37

### ISSUE THREAD

**Issue by stumts** [Ryujinx/Ryujinx#2486]
Specs:

- SO: Ubuntu 20.04
- Graphics: AMD Radeon RX 580 + mesa3d-7492513
- CPU: i9-9900KF

Hi guys. My fps goes from about 60 fps to about 6-7 fps in Zelda Skyward Sword after PR ca5ac37.

Before PR ca5ac37:
![Captura de tela de 2021-07-17 18-15-08](https://user-images.githubusercontent.com/30453661/126049541-cadace44-7a49-4bb6-98d4-5999772cb606.png)

After PR ca5ac37:
![Captura de tela de 2021-07-17 18-02-27](https://user-images.githubusercontent.com/30453661/126049542-7da8ef82-2460-4d37-b940-3c9de2a543b5.png)

I've just realized that I have the same poor performance in yuzu with OpenGL:
![Captura de tela de 2021-07-17 18-26-31](https://user-images.githubusercontent.com/30453661/126049727-85256eb8-26ed-4ec2-8957-26cf1cd8779a.png)

I don't know if it's related with the emulador itself or with mesa driver.

**Comment by riperiperi** [comment]
Can you test before and after on windows? (vsync off) I need to know if this is just a quirk of the mesa driver.

**Comment by stumts** [comment]
OpenGL AMD drivers on windows is a garbage. It was always poor performance. I's the reason I've been using Linux for emulation.

**Comment by riperiperi** [comment]
I know that the drivers are awful - but that doesn’t mean they should be ignored entirely. I’m just interested whether I should make this change windows only, or just exclude amd entirely.

**Comment by stumts** [comment]
Man, I'm really impressed with the performance on windows. The last time I tried the fds was very low, now the fps is quit good and a see no difference before and after this PR, so I think that is something related with mesa driver

Before PR ca5ac37:
![Capturar](https://user-images.githubusercontent.com/30453661/126053488-aa9abeb6-56e8-4854-a272-fb75c87ec980.PNG)

After PR ca5ac37:
![Captura2r](https://user-images.githubusercontent.com/30453661/126053495-508cc5e7-4bea-4459-9181-2b6b4a23bd14.PNG)

**Comment by AcK77** [comment]
It’s seems to be a user issue instead of a Ryujinx issue. I’ll reopen it if needed.

**Comment by gdkchan** [comment]
Its not a user issue, and its fixed in https://github.com/Ryujinx/Ryujinx/pull/2489
