### ISSUE TITLE
TLoZ SSHD particles textures not render properly

### ISSUE THREAD

**Issue by tazzkiller** [Ryujinx/Ryujinx#2487]
### What's the issue you encountered?

Particles textures not render properly

### How can the issue be reproduced?

![ryujinx_capture_2021-07-18_01-42-16](https://user-images.githubusercontent.com/171819/126050724-49b8ae62-fff3-4041-9db2-caed3177a6a6.jpg)
![ryujinx_capture_2021-07-18_01-41-01](https://user-images.githubusercontent.com/171819/126050704-5b524148-8f00-4939-8ee3-cf48f0327150.png)

### Log file

Not provided

### Environment

- Ryujinx version: 1.0.6970</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: RYZEN 5 3600X
  - GPU: NVIDIA RTX 2070
  - RAM:16GB
  - Applied Mods : No

**Comment by veploxmine123** [comment]
Had the same issue. Hope they can fix this asap. I wanted to full playthrought this game on ryu

**Comment by Connor2803** [comment]
Had the same issue, doesn't affect gameplay whatsoever so at least its playable!

**Comment by kingphil006** [comment]
Had the same issue.

**Comment by veploxmine123** [comment]
Still not fixed?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
