### ISSUE TITLE
(Feature Request) Snap/Appimage Support

### ISSUE THREAD

**Issue by dtantono** [Ryujinx/Ryujinx#2491]
Hi
I know ryujinx prepared to publish it on Flatpak and Is it possible for this app available on Snap/Appimage?

**Comment by AcK77** [comment]
Please reopen an issue following the issue template. Thanks

**Comment by dtantono** [comment]
Sorry for the inconvenience and I already opened a new one (https://github.com/Ryujinx/Ryujinx/issues/2492). thanks
