### ISSUE TITLE
Crash Team Racing Nitro-Fueled wrong shadows and wrong font colors

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#2495]
### What's the issue you encountered?

text in main menu is orange

shadows are wrong (they also flickers when moving the character) 
![Screenshot_2021-07-19_18-03-30](https://user-images.githubusercontent.com/80461138/126176429-6ff69613-ca04-4842-a094-e2ba5268826a.png)

### Log file
[Ryujinx_1.0.6973_2021-07-19_17-54-16.log.zip](https://github.com/Ryujinx/Ryujinx/files/6841802/Ryujinx_1.0.6973_2021-07-19_17-54-16.log.zip) (this is a 7z archive)

### Environment?

- Ryujinx version: 1.0.6973
- Game version: 1.0.15
- System Specs:
  - OS: Archlinux
  - CPU: i7-1165g7
  - GPU: iris xe
  - RAM: 16
- Applied Mods : no

### Additional context?

mesa git

**Comment by A-w-x** [comment]
shadows are fixed

**Comment by gdkchan** [comment]
Closing as it was already fixed. Likely fixed by #2538 (but not confirmed).
