### ISSUE TITLE
The executable file is not executable after auto-updating on Linux

### ISSUE THREAD

**Issue by SergeyLatyshev** [Ryujinx/Ryujinx#2497]
This started about few weeks ago. Ryujinx performs an auto-update, closes and doesn't re-launch itself. I look into its folder and see that "Ryujinx" file doesn't have its "executable" attribute set on. I have to make it executable manually. Then it works but only until the next update.

**Comment by Thog** [comment]
That's a weird issue, maybe something changed on the 7z binary? will need to check

**Comment by A-w-x** [comment]
this happened to me too, but not today, i just updated and it reopened just fine

**Comment by Benedani** [comment]
This was a problem for me some time ago, and it still happens on github-actions builds iirc. Since I launch Ryujinx with a script, I just added `chmod +x <path>` before running Ryujinx.

**Comment by SergeyLatyshev** [comment]
Ryujinx updated today and relaunched successfully. I suppose it's fixed now?

**Comment by edisionnano** [comment]
Sometimes it launches sometimes it doesnt
