### ISSUE TITLE
Missing tesselation shader in LM3

### ISSUE THREAD

**Issue by Linear524** [Ryujinx/Ryujinx#2498]
Missing tesselation shader in Luigis mansion 3

This game uses tesselation function and vertex texture fetch (for dynamic deformation)
Currently Ryu shows empty space in sand level instead of correct deform-able sand.

![1584](https://user-images.githubusercontent.com/84367301/126428880-404fbef2-be50-463a-a900-697cb01b936a.jpg)

And this is how it works on Switch hardware and Yuzu emu:
![1585](https://user-images.githubusercontent.com/84367301/126428949-c7762ec7-586d-490d-a061-478339b12e49.jpg)

So we are asking for tesselation implementation in Ryujinx :)    ...Please :)

**Comment by AcK77** [comment]
It could be nice if you could follow our issue template! Please :)

**Comment by gdkchan** [comment]
Please attach a save on the area with the problem to allow the issue to be reproduced.

**Comment by Niwu34** [comment]
> Please attach a save on the area with the problem to allow the issue to be reproduced.

Just Spam A in the Menu unitl you can move Luigi around
You will spawn in fornt of the pyramid
[Lm3 Save.zip](https://github.com/Ryujinx/Ryujinx/files/6949764/Lm3.Save.zip)
