### ISSUE TITLE
Ryujinx.exe starting problem due to missing dll files

### ISSUE THREAD

**Issue by tezuda74** [Ryujinx/Ryujinx#2499]
Hi there,,

Unfortunately, it´s been a  brief start...After decompressing the zip file of Ryujinx last master build (ryujinx-1.0.6974-win_x64.zip) to my desktop, I double-click the on the *.exe file and it just close itself.

Here goes the Log file:

00:00:00.026 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.027 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.027 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.028 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.032 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.049 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.049 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.049 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.049 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.051 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.052 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.052 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.053 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.060 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6974
00:00:00.068 |N| Application Print: Operating System: Microsoft Windows 10.0.19041 (X64)
00:00:00.068 |N| Application Print: CPU: AMD FX(tm)-6300 Six-Core Processor ; 6 logical
00:00:00.068 |N| Application Print: RAM: Total 8092 MB ; Available 2937 MB
00:00:00.071 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.071 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.497 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args)

I´ve also tried
[Ryujinx_1.0.0-ldn2.3_2021-07-22_01-44-53.log](https://github.com/Ryujinx/Ryujinx/files/6859341/Ryujinx_1.0.0-ldn2.3_2021-07-22_01-44-53.log)
 the LDN versión, but with same results (see attached file).

- System Specs:
  - OS: Windows 10
  - CPU: AMD FX-6300
  - GPU: NVIDIA GTX 750TI
  - RAM: 8GB
- Applied Mods : No

Any help would be much appreciated...thanks in advance :-)

P.D.: Good news is that I´ve also compiled Ryujinx in Linux mint 20.1 and it runs perfectly well! 
(Excellent hard work, developers!!!) 
[Ryujinx_1.0.6974_2021-07-22_01-37-47.log](https://github.com/Ryujinx/Ryujinx/files/6859334/Ryujinx_1.0.6974_2021-07-22_01-37-47.log)

**Comment by AcK77** [comment]
Move the bin folder content near Ryujinx.exe and it should works
