### ISSUE TITLE
Left and right arrow keys brings up File menu after running the game

### ISSUE THREAD

**Issue by SeibaEX** [Ryujinx/Ryujinx#2502]
### What's the issue you encountered?
The arrow keys ← → on the keyboard keep bringing up the Ryujin menu at the top during gameplay, which causes a loss of control in any game. My workaround was to change the directional pads to a different set of keys, but I would rather go back to the arrow keys.

### How can the issue be reproduced?

1. Run any game.
2. Press the left and right arrow keys.

### Log file

[Ryujinx_1.0.6976_2021-07-24_14-59-00.log](https://github.com/Ryujinx/Ryujinx/files/6873118/Ryujinx_1.0.6976_2021-07-24_14-59-00.log)
[Ryujinx_1.0.6976_2021-07-24_15-19-44.log](https://github.com/Ryujinx/Ryujinx/files/6873127/Ryujinx_1.0.6976_2021-07-24_15-19-44.log)

### Environment?

- Ryujinx Version: 1.0.6976

- System Specs:
Operating System: Microsoft Windows 10.0.19042 (X64)
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz ; 8 logical
RAM: Total 16335 MB ; Available 10817 MB
NVIDIA Corporation NVIDIA GeForce GTX 1060 with Max-Q Design
- Applied Mods : [ romfs patch for audio ]

**Comment by GamerzHell9137** [comment]
PR that introduced the issue was #2411
