### ISSUE TITLE
Random crashes on startup of a game - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SeibaEX** [Ryujinx/Ryujinx#2503]
## Bug Report

I'm not sure if this has to do with the previous bug I mentioned [here](https://github.com/Ryujinx/Ryujinx/issues/2502), but games intermittently crash when starting them with a critical error.

### What's the issue you encountered?

I start a game and randomly it comes with a critical error.

### How can the issue be reproduced?

Load any random game.

### Log file

[Ryujinx_1.0.6976_2021-07-24_15-21-49.log](https://github.com/Ryujinx/Ryujinx/files/6873133/Ryujinx_1.0.6976_2021-07-24_15-21-49.log)

### Environment?

- Ryujinx Version: 1.0.6976

- System Specs:
Operating System: Microsoft Windows 10.0.19042 (X64)
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz ; 8 logical
RAM: Total 16335 MB ; Available 10817 MB
NVIDIA Corporation NVIDIA GeForce GTX 1060 with Max-Q Design
- Applied Mods : [ romfs patch for audio ]

**Comment by AcK77** [comment]
I suggest you to come on our discord server for support, this doesn’t seems to be an issue with the emulator itself. Thanks.
