### ISSUE TITLE
Anistropic filtering is bugged

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#2509]
### What's the issue you encountered?

Anistropic filtering is not applied when changed mid game session.

### How can the issue be reproduced?
Just try to change it mid emulation.

### Environment?

- Ryujinx version: 1.0.6976

**Comment by emmauss** [comment]
Is this on master or the new ui pr?

**Comment by GamerzHell9137** [comment]
> 
> 
> Is this on master or the new ui pr?

Seems like master too so its not an Avalonia issue atm.

**Comment by Shahil-Ayato** [comment]
Fixed by #2832
