### ISSUE TITLE
emulator crash when playing game on specify map

### ISSUE THREAD

**Issue by hoe214** [Ryujinx/Ryujinx#2511]
[Ryujinx_1.0.0-ldn2.3_2021-07-25_00-01-58.log](https://github.com/Ryujinx/Ryujinx/files/6889809/Ryujinx_1.0.0-ldn2.3_2021-07-25_00-01-58.log)

**Comment by AcK77** [comment]
Your issues doesn't follow the template. Please reopen a new one with all needed informations. Thanks.
