### ISSUE TITLE
[Graphics] Pokemon Sword game boots in black screen

### ISSUE THREAD

**Issue by DistantThunder** [Ryujinx/Ryujinx#2517]
### What's the issue you encountered?

I'm trying to play Pokemon Sword. When launching the game, Ryujinx window remains black.

### How can the issue be reproduced?

Try to run the game.
Pokemon Sword v1.3.1

### Log file

[Ryujinx_linux_amd.log](https://github.com/Ryujinx/Ryujinx/files/6909185/Ryujinx_linux_amd.log)

### Environment?

- Ryujinx version: r1760.06cd3abe6-1</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: v1.3.1</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
* Arch Linux 5.13.4
* RX 6900XT
* Mesa 21.1.5
* Ryujinx Git r1760.06cd3abe6-1
### Additional context?

Runtime options where:

>  MESA_NO_ERROR=1 mesa_glthread=true glsl_zero_init=true radeonsi_clamp_div_by_zero=true  vblank_mode=0 MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d"

**Comment by AcK77** [comment]
This seems to be an issue from the user, plus you use a custom build `Ryujinx Version: 1.0.0-dirty`. If you needs support I suggest you to come to our discord server. Thanks.

**Comment by DistantThunder** [comment]
I tried again with latest build and I reproduce thebehaviour:

![image](https://user-images.githubusercontent.com/3923810/127722472-df9bd0e1-6a33-4009-ae1e-009acbddad16.png)

**Comment by AcK77** [comment]
This is not for support, since there is a lot of chance the issue is something at your side, I REALLY suggest you to come on our discord for support. Thanks.
