### ISSUE TITLE
Kirby Star Allies incorrect rendering on Mesa (Intel/AMD)

### ISSUE THREAD

**Issue by Catiks** [Ryujinx/Ryujinx#2519]
## Bug Report

GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x7FFFF (sRGB: False).
![星之卡比](https://user-images.githubusercontent.com/12002076/127724244-d9af6187-d431-4b61-9328-b6deff7ba973.png)

### Environment?

- Ryujinx version: 1.0.6976</br>
- Game version: 4.0.0</br>
- System Specs:
  - OS: Ubuntu 20.04
  - CPU: i9-9700K
  - GPU: Intel
  - RAM: 32G
- Applied Mods : [ No ]

**Comment by Melechtna** [comment]
Have the exact same issue.

- Ryujinx version: 1.0.7107
- Game version: 4.0.0
- System Specs:
- OS: Arch
- CPU: i7-7700
- GPU: RX 6800
- RAM: 64G
- Applied Mods : [ No ]

**Comment by Essasetic** [comment]
Hey, got an update on this. On stock with no parameters (1.1.26) rendering is still broken
![2022-02-12_00-02-1644626165](https://user-images.githubusercontent.com/34970796/153689766-a02d3adf-204c-46b1-80fc-761a30bc3b55.png)

However, using the env command: `force_integer_tex_nearest=true` 
when running it completely resolves the issue.
![2022-02-12_00-02-1644625863](https://user-images.githubusercontent.com/34970796/153689824-7c3db3e1-f0e2-456e-b992-de372b8789ca.png)

- Game version - 4.0.0
- OS - EndavourOS (Arch)
- DE Sway/KDE
- CPU: 5600X
- GPU: RX 6800
- Mesa: 21.3.5

**Comment by sauradipdebnath** [comment]
How to add the command

**Comment by sauradipdebnath** [comment]
How to use on windows
