### ISSUE TITLE
The Lost Child - Crash during combat

### ISSUE THREAD

**Issue by Krusher97** [Ryujinx/Ryujinx#2522]
### What's the issue you encountered?

The emulator can randomly crash while in combat when an attack animation plays. Has happened to me thrice so far. 
I've set the Memory Manager Mode to Host(fast)

### How can the issue be reproduced?

Seems to happen after an hour or two of playtime. I haven't found a way to reliably reproduce it.
EDIT: Might be tied to attack effects on newer monsters. Got another crash while in a new dungeon.

### Log file

[log.zip](https://github.com/Ryujinx/Ryujinx/files/6916765/log.zip)
[log2.zip](https://github.com/Ryujinx/Ryujinx/files/6917421/log2.zip)

### Environment?

- Ryujinx version: 1.0.6976
- Game version: 1.0.1
- System Specs:
  - OS: *Windows 7*
  - CPU: *i5-6500*
  - GPU: *NVIDIA GTX 1050Ti*
  - RAM: *8GB*
- Applied Mods :  No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
