### ISSUE TITLE
The direction pad is always triggered with real-joycon

### ISSUE THREAD

**Issue by jk20012001** [Ryujinx/Ryujinx#2523]
### What's the issue you encountered?

When I use real-joycon, the direction pad is always triggered, cause the character to walk in one direction all the time.

### How can the issue be reproduced?

This issue happened with 6961 to 6976, but in 6890 it works fine (Other versions have not been tested)
In some games which uses joycon, the issue can be reproduced, such as SnipperClips 1.0.0, Unruly Heroes 1.0.2701, Super Mario 3D World 1.1.0, Monster Hunter Stories 2

### Environment?

- Ryujinx version: 1.0.6961-6976</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Win10 10.0.19042
  - CPU: Ryzen7 5800X
  - GPU: NVIDIA GTX 760
  - RAM: 32GB
- Applied Mods : No

**Comment by MetrosexualGarbodor** [comment]
There haven't been any reports of this happening over the months. Closing.
