### ISSUE TITLE
Paper Mario: The Origami King System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by madocelot** [Ryujinx/Ryujinx#2525]
### What's the issue you encountered?

Experiencing a repeatable crash in shangri-spa. The crash happens during a cutscene where Bowser minions storm the palace.

### How can the issue be reproduced?

In my case the crash happens during the cutscene where Bowser minions storm the palace in Shangri-Spa.

1. Go inside the palace
2. Watch the cutscene

save file: https://www.mediafire.com/file/2rxch7hcyl6hkq0/0.zip/file

### Log file

https://pastebin.com/RfqLRZVC
[Ryujinx_1.0.6976_2021-07-30_11-21-48.log](https://github.com/Ryujinx/Ryujinx/files/6918846/Ryujinx_1.0.6976_2021-07-30_11-21-48.log)
</br>

### Environment?

- Ryujinx version: 1.0.6976</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10 Pro x64 21H1*
  - CPU: *Intel Core i5-10600KF*
  - GPU: *RTX3070*
  - RAM: *16GB*
- Applied Mods : No

### Additional context?

N/A

**Comment by gdkchan** [comment]
Closing as it should be fixed by #3181. If the issue still persists, please re-open it. Thanks.

**Comment by marysaka** [comment]
Actually fixed by #3908
