### ISSUE TITLE
Bravely Default 2 - Missing Facial Animations

### ISSUE THREAD

**Issue by MoonZapdos** [Ryujinx/Ryujinx#2528]
## Bug Report

Bravely Default 2 - Missing Facial Animations

### What's the issue you encountered?

The facial animations for characters during combat and cutscenes do not occur - characters are stuck in a static expression with their mouth shut even when they speak.

### How can the issue be reproduced?

Enter any cutscene.

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.6976</br>
- Game version: 10.0</br>
- System Specs:
  - OS: *Windows 10 Professional 64-bit*
  - CPU: *AMD Ryzen 5 3600*
  - GPU: *NVIDIA GTX 1660 Super*
  - RAM: *16 GB*
- Applied Mods : Yes (60 FPS patch)

### Additional context?

N/A

**Comment by gdkchan** [comment]
This is fixed by https://github.com/Ryujinx/Ryujinx/pull/2090.

**Comment by gdkchan** [comment]
Closing as the fix was already merged.
