### ISSUE TITLE
Bravely Default 2 - Random Crashes

### ISSUE THREAD

**Issue by MoonZapdos** [Ryujinx/Ryujinx#2529]
## Bug Report

Bravely Default 2 - Random Crashes

### What's the issue you encountered?

The game sporadically crashes for no apparent reason. It is stable for quite a long time (~1 hour or so) prior to such crashes. My guess is it's something to do with the shader cache overflowing.

### How can the issue be reproduced?

Simply play the game long enough.

### Log file

[Ryujinx_1.0.6982_2021-08-04_23-57-50.log](https://github.com/Ryujinx/Ryujinx/files/6934974/Ryujinx_1.0.6982_2021-08-04_23-57-50.log)

### Environment?

- Ryujinx version: 1.0.6982
- Game version: 1.0.0
- System Specs:
  - OS: *Windows 10 Professional 64-bit*
  - CPU: *AMD Ryzen 5 3600*
  - GPU: *NVIDIA GTX 1660 Super*
  - RAM: *16GB*
- Applied Mods : Yes (60 FPS patch)

### Additional context?

N/A

**Comment by ionelush2001** [comment]
Try without 60 FPS Mod.

**Comment by MoonZapdos** [comment]
> 
> 
> Try without 60 FPS Mod.

Crash still occurs.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
