### ISSUE TITLE
The game directory cannot be specified for the drive where the pagefile.sys exists

### ISSUE THREAD

**Issue by vojo915** [Ryujinx/Ryujinx#2530]
### What's the issue you encountered?

When I select the drive where the page file exists, I get an error and cannot select the game directory.

![err](https://user-images.githubusercontent.com/84438932/128351030-0acd3f86-9d1b-47e6-9123-f6a116aa2519.png)

This error also occurs in the folder selection dialog that appears when you install the firmware.

### How can the issue be reproduced?

1. In the settings on the Windows side, set the page file on the drive to be tested.
1. On the Ryujinx side, call the game directory selection dialog from the settings and select the drive specified in 1. in the tree view.
1. An error dialog is displayed and the game directory cannot be selected.

### Environment?

- Ryujinx version: 1.0.6982 (Probably also happens in older versions)
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 3600
  - GPU: NVIDIA GeForce GTX 1660 Ti
  - RAM: 16GB
- Applied Mods : No

**Comment by jduncanator** [comment]
I can confirm this issue exists, and is mightily annoying, as I ran into this issue the other day.

**Comment by ooa113y** [comment]
Just confirming that #2507 fixes this.

**Comment by AcK77** [comment]
Could you test #2633 and tell me if the issue is fixed too ?

**Comment by vojo915** [comment]
Results of testing #2633

In any of the following cases, it could be read normally.

- Game executable file
- Game folder
- Folder where the firmware exists
