### ISSUE TITLE
Catherine Full Body  Broken Graphics 

### ISSUE THREAD

**Issue by kingphil006** [Ryujinx/Ryujinx#2550]
## Bug Report

Broken Graphics in Catherine Full Body 

### What's the issue you encountered?

There is an strange pink line in the lower border of the screen in anime cutscenes and some effects are completely broken in gameplay. 

![Captura de tela 2021-08-13 003511](https://user-images.githubusercontent.com/72477207/129303291-09f2172a-d0de-4347-b4f3-0d595b806e8d.png)
![Captura de tela 2021-08-13 004226](https://user-images.githubusercontent.com/72477207/129303293-8156c7ae-abfd-42dd-aaba-9d79cd186525.png)

### How can the issue be reproduced?

Start the game to see cutscenes and proceed to see gameplay. 

### Log file
[Ryujinx_1.0.6997_2021-08-13_00-50-02.log](https://github.com/Ryujinx/Ryujinx/files/6979769/Ryujinx_1.0.6997_2021-08-13_00-50-02.log)

### Environment?

- Ryujinx version: 1.0.6997</br>

- Game version: 1.0.1</br>

- System Specs:
  - OS: Windows 10 Home x64, 20H2
  - CPU: Ryzen 5 2600
  - GPU: NVIDIA GTX 1650 Super
  - RAM: 16GB  
- Applied Mods : No

### Additional context?

NVIDIA Game Ready Drivers: 471.41

**Comment by MetrosexualGarbodor** [comment]
Pink line is gone. 
![imagen](https://user-images.githubusercontent.com/79612681/164797314-c10d1f24-9c62-4d0f-b397-c86c253ae161.png)
Random white corruption at the right is gone. 
![imagen](https://user-images.githubusercontent.com/79612681/164798604-b690dae6-1a9b-4dbc-8fbd-00486672864c.png)

**Comment by hannihannhan** [comment]
How do I fix this? Can someone tell me how???

**Comment by hannihannhan** [comment]
> Pink line is gone. ![imagen](https://user-images.githubusercontent.com/79612681/164797314-c10d1f24-9c62-4d0f-b397-c86c253ae161.png) Random white corruption at the right is gone. ![imagen](https://user-images.githubusercontent.com/79612681/164798604-b690dae6-1a9b-4dbc-8fbd-00486672864c.png)

How do you exactly fix this? please tell me.

**Comment by GamerzHell9137** [comment]
> > How do you exactly fix this? please tell me.
> 
> In settings, CPU> CPU Mode > Memory Manager Mode > Set it to software and apply settings.

And you're wrong
![slika](https://github.com/user-attachments/assets/12188b1a-0fa5-4a62-8f03-45bfe07f1f30)

**Comment by Amey8a** [comment]
![Host Unchecked, No shader cache](https://github.com/user-attachments/assets/d3651ced-6760-4f15-add1-f2f291d74f9f)
![Software, No shader cache](https://github.com/user-attachments/assets/04277283-c10d-4309-bdef-bec4debb1dd1)
I don't like shader building and loading so PPTC and shader building is turned off. Started the game fresh and there are my results.

**Comment by Amey8a** [comment]
> And you're wrong

![Software, No shader cache](https://github.com/user-attachments/assets/6e06b63f-ebdf-479d-bcc3-460aa0810403)
![Host Unchecked, No shader cache](https://github.com/user-attachments/assets/2cb39d9d-8699-46c6-8bcd-9ab341a1de4e)

I don't like shader building and loading so PPTC and shader building is turned off. Started the game fresh and there are my results.

**Comment by Amey8a** [comment]
> > > How do you exactly fix this? please tell me.
> > 
> > 
> > In settings, CPU> CPU Mode > Memory Manager Mode > Set it to software and apply settings.
> 
> And you're wrong

Hi buddy.
This is for test purpose only.
Can you delete and disable shader cache and then run this game with Memory Management mode set to software? I am still getting the same results I mentioned before. 

https://github.com/Ryujinx/Ryujinx/issues/7144#issuecomment-2276182598

**Comment by GamerzHell9137** [comment]
> > > > How do you exactly fix this? please tell me.
> > > 
> > > 
> > > In settings, CPU> CPU Mode > Memory Manager Mode > Set it to software and apply settings.
> > 
> > 
> > And you're wrong
> 
> Hi buddy. This is for test purpose only. Can you delete and disable shader cache and then run this game with Memory Management mode set to software? I am still getting the same results I mentioned before.
> 
> [#7144 (comment)](https://github.com/Ryujinx/Ryujinx/issues/7144#issuecomment-2276182598)

With PPTC and Shader cache deleted and disabled:

![image](https://github.com/user-attachments/assets/a9b9e7e9-39b5-4eed-b340-735f33ab6cf7)
![image](https://github.com/user-attachments/assets/8157d516-4634-4af7-9d98-35bf74bae101)

Memory management modes did not change anything:
![image](https://github.com/user-attachments/assets/4ba99b91-eff8-481d-9a26-7b3756f38097)

**Comment by Amey8a** [comment]
> > > > > How do you exactly fix this? please tell me.
> > > > 
> > > > 
> > > > In settings, CPU> CPU Mode > Memory Manager Mode > Set it to software and apply settings.
> > > 
> > > 
> > > And you're wrong
> > 
> > 
> > Hi buddy. This is for test purpose only. Can you delete and disable shader cache and then run this game with Memory Management mode set to software? I am still getting the same results I mentioned before.
> > [#7144 (comment)](https://github.com/Ryujinx/Ryujinx/issues/7144#issuecomment-2276182598)
> 
> With PPTC and Shader cache deleted and disabled:
> 
> Memory management modes did not change anything:

Thanks buddy for a quick reply. I can see the only difference here as the GPU. I have an RX 6600. Just yesterday I completed the game from start to end and never got those glitches with MMU set to Software. Today I though I should try with Host Unchecked and the issue came back.

So, it seems related to graphic rendering by GPU (Vulkan/OpenGL)? 

I appreciate your quick response. I will do some other test in the mean time. Have a nice day.

**Comment by GamerzHell9137** [comment]
> > > > > > How do you exactly fix this? please tell me.
> > > > > 
> > > > > 
> > > > > In settings, CPU> CPU Mode > Memory Manager Mode > Set it to software and apply settings.
> > > > 
> > > > 
> > > > And you're wrong
> > > 
> > > 
> > > Hi buddy. This is for test purpose only. Can you delete and disable shader cache and then run this game with Memory Management mode set to software? I am still getting the same results I mentioned before.
> > > [#7144 (comment)](https://github.com/Ryujinx/Ryujinx/issues/7144#issuecomment-2276182598)
> > 
> > 
> > With PPTC and Shader cache deleted and disabled:
> > Memory management modes did not change anything:
> 
> Thanks buddy for a quick reply. I can see the only difference here as the GPU and the game version. I have an RX 6600. Just yesterday I completed the game from start to end and never got those glitches with MMU set to Software. Today I though I should try with Host Unchecked and the issue came back.
> 
> So, it seems related to graphic rendering by GPU (Vulkan/OpenGL)?
> 
> I appreciate your quick response. I will do some other test in the mean time. Have a nice day.

Catherine is corrupting Texture Data but why its doing that is unknown, commented by one of the devs.
But yeah the game is broken, i dont think AMD is not causing it but who knows. One run is fine on Nvidia and then another one is not, it depends.

**Comment by Amey8a** [comment]
> > > > > > > How do you exactly fix this? please tell me.
> > > > > > 
> > > > > > 
> > > > > > In settings, CPU> CPU Mode > Memory Manager Mode > Set it to software and apply settings.
> > > > > 
> > > > > 
> > > > > And you're wrong
> > > > 
> > > > 
> > > > Hi buddy. This is for test purpose only. Can you delete and disable shader cache and then run this game with Memory Management mode set to software? I am still getting the same results I mentioned before.
> > > > [#7144 (comment)](https://github.com/Ryujinx/Ryujinx/issues/7144#issuecomment-2276182598)
> > > 
> > > 
> > > With PPTC and Shader cache deleted and disabled:
> > > Memory management modes did not change anything:
> > 
> > 
> > Thanks buddy for a quick reply. I can see the only difference here as the GPU and the game version. I have an RX 6600. Just yesterday I completed the game from start to end and never got those glitches with MMU set to Software. Today I though I should try with Host Unchecked and the issue came back.
> > So, it seems related to graphic rendering by GPU (Vulkan/OpenGL)?
> > I appreciate your quick response. I will do some other test in the mean time. Have a nice day.
> 
> Catherine is corrupting Texture Data but why its doing that is unknown, commented by one of the devs. But yeah the game is broken, i dont think AMD is not causing it but who knows. One run is fine on Nvidia and then another one is not, it depends.

I hope it get addressed in future releases. I have a switch lite only so, can't play it on monitor natively. Ryujinx is getting better everyday and I expect it to get improved further. Thanks for replying.
