### ISSUE TITLE
Fire Emblem: Three Houses image freeze when use magic skill

### ISSUE THREAD

**Issue by CharlsXiao** [Ryujinx/Ryujinx#2554]
## Bug Report

Fire Emblem: Three Houses image freeze when use magic skill</br>

### What's the issue you encountered?
Today i'm update my Ryujinx from 1.0.6941 to 1.0697.When i paly the game and use the magic skill,the page  suddenly freeze，but I can still hear the in-game sound when I press the button.</br>
![20210815015617](https://user-images.githubusercontent.com/39261241/129456236-77a7b268-13b9-44df-b023-2af38b63c902.png)
![20210815015852](https://user-images.githubusercontent.com/39261241/129456237-d7f8c3ca-023e-4853-b8eb-700fc7b527fc.png)
I tried switching characters, switching skills, removing 60 fps mod, and shutting down Vsync, but nothing worked</br>

### How can the issue be reproduced?

Enter the game, enter the battle, choose magic characters, use magic skills

### Log file

[Ryujinx_1.0.6997_2021-08-15_01-40-14.log](https://github.com/Ryujinx/Ryujinx/files/6986985/Ryujinx_1.0.6997_2021-08-15_01-40-14.log)
[Ryujinx_1.0.6997_2021-08-15_01-56-37.log](https://github.com/Ryujinx/Ryujinx/files/6986986/Ryujinx_1.0.6997_2021-08-15_01-56-37.log)

### Environment?

- Ryujinx version: 1.0.6997</br>
- Game version: 1.2.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-10700k
  - GPU: NVIDIA RTX 3080
  - RAM: 32GB
- Applied Mods : No 

### Additional context?

Additional info about your environment:</br>
NVIDIA Game Ready Drivers: 471.68

**Comment by lagunaxii** [comment]
Found a fix, updated Nvidia driver. Went into Nvidia control panel under Manage 3D Settings. Went into Program Settings Customized the Ryujinx Nvidia Profile. Turned on Vertical sync and put Low Latency Mode on Ultra. (It still freezes on the first use of thunder, **but you just need to wait a few minutes, and it won't freeze on any subsequent uses)**
Source: Reddit
I Tested, it work :D

**Comment by EmulationFanatic** [comment]
This issue appears to be resolved.

**Comment by xCISACx** [comment]
This just happened to me for the second time now on the latest build.
It's doesn't always happen and it's quite random.
Maybe a recent pull broke it again?
