### ISSUE TITLE
Gordian Rooms too bright after loading save

### ISSUE THREAD

**Issue by urgrueA** [Ryujinx/Ryujinx#2556]
## Bug Report

Gamma (?) issue in Gordian Rooms: A Curious Heritage

### What's the issue you encountered?

When loading a saved game, the screen is almost always far too bright.

### How can the issue be reproduced?

Start Ryujinx and then GR:ACH
Start a new game in any game slot
Play introductory tutorial (letter opening) and select continue
You will arrive here:

![GR01](https://user-images.githubusercontent.com/21059548/129493638-a390d6a7-96f4-46d0-b986-7ce52a71238b.png)

Play on, save the game and close Ryujinx
Start Ryujinx and then GR:ACH
Load previously saved game
You will probably see this:

![GR02](https://user-images.githubusercontent.com/21059548/129493653-637d763f-0fb0-4228-8e5c-3f8960819c9c.png)

Impossible to continue from then on.
A new game slot may work for a while, but the problem will resurface after a restart of Ryujinx.

The gamma setting in the opening tutorial is often wrong as well. Turning on the lamp should increase brightness, but usually does not, which makes the letter impossible to see.

### Log file

[Ryujinx_1.0.6997_2021-08-15_23-11-28.log](https://github.com/Ryujinx/Ryujinx/files/6988967/Ryujinx_1.0.6997_2021-08-15_23-11-28.log)

### Environment?

- Ryujinx version: 1.0.6997</br>
- Game version: 0.1</br>
- System Specs:
  - OS: Windows 7
  - CPU: i7-4790K
  - GPU: NVIDIA GTX 1060 6GB
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Firmware 12.1.0
NVIDIA Game Ready Drivers: 471.11

**Comment by gdkchan** [comment]
Please retest, a bunch of similar texture issues were fixed recently.

**Comment by urgrueA** [comment]
That seems to have worked. A previous save loads without the blinding light issue. Many thanks.
