### ISSUE TITLE
Romancing SaGa 2 - Game speed is too fast

### ISSUE THREAD

**Issue by Krusher97** [Ryujinx/Ryujinx#2565]
### What's the issue you encountered?

The entire game seems to run at double the speed. 
Default settings.

### How can the issue be reproduced?

Start the game and go through the opening cutscene and dialogue. Everything is sped up.

### Log file

[log.zip](https://github.com/Ryujinx/Ryujinx/files/7010357/log.zip)

### Environment?

- Ryujinx version: 1.0.7000
- Game version: 1.0.0
- System Specs:
  - OS: *Windows 7*
  - CPU: *i5-6500*
  - GPU: *NVIDIA GTX 1050Ti*
  - RAM: *8GB*
- Applied Mods :  No

**Comment by Niwu34** [comment]
Are you sure that you didn't accidently disabled vsync?
Hit the Tabb-key ingame to reenable it

**Comment by Krusher97** [comment]
I didn't think disabling vsync would increase gamespeed.

Retested it with Vsync enabled and yeah it runs properly at 30FPS. Should this be closed as not being an issue then?

**Comment by gdkchan** [comment]
I will close as this is not an emulator issue, disabling VSync may have adverse effects on games, some will run too fast as they don't try to limit their frame rate and depend on surface flinger doing so.
