### ISSUE TITLE
Invisible interface after installing Vulkan

### ISSUE THREAD

**Issue by Fedoz1** [Ryujinx/Ryujinx#2581]
It runs just fine in the OpenGL graphic setting but when I change to Vulkan, it changes to an invisible interface.

(https://github.com/Ryujinx/Ryujinx/files/7025925/Ryujinx_1.0.0%2B3a175b9_2021-08-21_10-17-14.log)

![1](https://user-images.githubusercontent.com/89315039/130330247-de028806-5902-468c-996a-6b8126b7a5c0.png)
[Ryujinx_1.0.0+3a175b9_2021-08-21_10-17-14.log]

**Comment by RyzenDew** [comment]
Transparent not invisible also this issue is already known its an amd bug ￼

**Comment by Fedoz1** [comment]
so i cant do anything about it?

**Comment by Mou-Ikkai** [comment]
> so i cant do anything about it?

![image](https://user-images.githubusercontent.com/45863583/130330555-18b38d74-22af-4ea0-8f70-811c0fb7ee06.png)
Disable this option.

**Comment by Fedoz1** [comment]
Thank you very much!

**Comment by KevinTyrrell** [comment]
> > so i cant do anything about it?
> 
> ![image](https://user-images.githubusercontent.com/45863583/130330555-18b38d74-22af-4ea0-8f70-811c0fb7ee06.png) Disable this option.

You are a legend. Thank you.
