### ISSUE TITLE
[Feature Request] Change GUI popup when adding/locating files 

### ISSUE THREAD

**Issue by CassiusOtho** [Ryujinx/Ryujinx#2584]
### What feature are you suggesting?
Change GUI popup when adding/locating files 
#### Overview:
I found the Ryujinx file addition/location GUI popup to be rather tedious to use. Especially when it came to finding folders that were multiple directories deep, or if the file in question is located inside a “hidden folder.” 

I recommending  changing to the windows file addition/location GUI popup. I have attached an image below of what this popup looks like for the program "Snagit Editor" just in case. 
#### Smaller Details: 
N/A
#### Nature of Request:  
- Change
### Why would this feature be useful?
Using the windows GUI, would make finding files a breeze. Having access to the address bar would make copying and pasting directory quick and easy. The ability to go up and down directories from the address bar is also a fast way to navigate folders. Any files in the users “Quick Access” toolbar would also be readily available in the left column. 

![Windows GUI](https://user-images.githubusercontent.com/63135347/130356009-4c583f17-5abb-4a8e-b396-f268d3672aaa.JPG)

**Comment by gdkchan** [comment]
I believe this is a GTK limitation, but from what I recall, Avalonia (#2507) uses the Windows native dialogs.
