### ISSUE TITLE
Birushana Senki - Genpei Hika Muso [0100BE900C590000] bootable but image distorted

### ISSUE THREAD

**Issue by bluebanana2021** [Ryujinx/Ryujinx#2589]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

Game (xci) is bootable, can get into main menu, music and voice are both fine.
But the screen is distorted. 
No changes were made to Ryujinx other than keyboard mappings, all others are using default settings.

### How can the issue be reproduced?

Just load the game. 

### Log file
[Ryujinx_1.0.0+9bbaf15_2021-08-24_14-23-33.log](https://github.com/Ryujinx/Ryujinx/files/7036627/Ryujinx_1.0.0%2B9bbaf15_2021-08-24_14-23-33.log)

### Environment?

- Ryujinx version: 1.0.0+9bbaf15</br>
- Game version: 1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 5900X 12-Core Processor 3.70 GHz
  - GPU: AMD Radeon RX 6800 XT
  - RAM: 64 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>

This also happens to a few other games from the same maker.
- Birushana Senki - Genpei Hika Muso [0100BE900C590000] (xci)
- Katakoi Contrast collection of branch [01007FD00DB20000] (nsp)
- Kimi wa Yukima ni Koinegau [010021D01474E000] (both nsp and xci)
- Cupid Parasite [0100F7E00DFC8000] (nsp)

Screenshots:
![ryujinx_capture_2021-08-24_14-04-30](https://user-images.githubusercontent.com/87249739/130561204-bdc6a0b8-7788-471b-b08f-d204f9e447b0.png)
![ryujinx_capture_2021-08-24_14-05-09](https://user-images.githubusercontent.com/87249739/130561214-aa7a3c4e-fba9-4b5d-971b-53161e5ecbf0.png)

**Comment by gdkchan** [comment]
Looks like this issue only happens on AMD GPUs.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
