### ISSUE TITLE
Graphic artifacts on amd GPUs with Mesa driver in Luigi Mansion 3

### ISSUE THREAD

**Issue by dante3732** [Ryujinx/Ryujinx#2592]
## Bug Report
Probably due to the rays of light, artifacts are depicted.

### What's the issue you encountered?
This bug appears as soon as night falls.

### How can the issue be reproduced?
Go through the intro and wait until night falls.

### Log file
[Ryujinx_1.0.7008_2021-08-26_19-45-20.log](https://github.com/Ryujinx/Ryujinx/files/7062156/Ryujinx_1.0.7008_2021-08-26_19-45-20.log)

https://user-images.githubusercontent.com/66036249/131020562-c8913ba8-edeb-41fb-9556-5c18629241f8.mp4

### Environment?
- Ryujinx version: 1.0.7008

- System Specs:
  - OS:  Linux Ubuntu 21.04 
  - CPU: AMD Ryzen R5 3600 4.2 Ghz
  - GPU: AMD RX Vega 64
  - RAM: 16GB
  - Mesa 21.0.3 
- Applied Mods : Yes/ No (this bug with mods and without)

### Additional context?
It is also known that this glitch exists on other AMD video cards:  5700 XT, RX580.
This glitch on AMD and Vulkan.

**Comment by dante3732** [comment]
Probably the same on intel.

**Comment by Bill5122** [comment]
Still occurs on 1.1.101 with the new shader cache implementation.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
