### ISSUE TITLE
METAL MAX Xeno Reborn - Image distortion in the game

### ISSUE THREAD

**Issue by mihoutao7** [Ryujinx/Ryujinx#2598]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?
issue : The game starts normally, loads the game and comes into the screen, but when you press the +(+) key to turn on the state, when you close it, it becomes blurred.  
set:This problem also occurs when you turn on 2x scaling.  (Nothing by default)  
![image](https://user-images.githubusercontent.com/73820590/131217043-142c429e-6670-4c79-b160-84db4c9db58c.png)

### How can the issue be reproduced?
Turn on 2 times zoom, after entering the game normally, open the status menu (press start on the gamepad) and reappear after closing.  
### Log file
[Ryujinx_1.0.7018_2021-08-28_19-49-37.log](https://github.com/Ryujinx/Ryujinx/files/7070671/Ryujinx_1.0.7018_2021-08-28_19-49-37.log)
### Environment?

- Ryujinx version: 1.0.7018</br>
- Game version: 1.0.0/1.0.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz(3600 MHz)
  - GPU: NVIDIA GeForce RTX 2080 Ti (11264MB)
  - RAM: 64GB
- Applied Mods : [ Yes (Which ones) / No ]
no
### Additional context?
![image](https://user-images.githubusercontent.com/73820590/131217120-5887b96e-9754-4ea8-947b-90549b68a26f.png)
![image](https://user-images.githubusercontent.com/73820590/131217164-fd2dbca1-fafb-4f19-b48a-15cf889677d6.png)
![image](https://user-images.githubusercontent.com/73820590/131217170-3316f142-5d33-4b31-95e2-32a3b692f729.png)
![image](https://user-images.githubusercontent.com/73820590/131217180-54058a0a-55c0-458b-b0f4-69a6d7ce02a0.png)

**Comment by mihoutao7** [comment]
Any big shots to see what the problem is?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
