### ISSUE TITLE
FINAL FANTASY X/X-2 HD REMASTER - 0100BC300CB48000 - Graphical Issues

### ISSUE THREAD

**Issue by Cheezballjones** [Ryujinx/Ryujinx#2599]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

There are Graphical Issues in almost every Map. They are not Game-Breaking, only visually impairing.

Here, we can see that I am present in the "Inn" based on the Mini Map - I can move around, but I cannot be seen.
![image](https://user-images.githubusercontent.com/89695758/131220836-41bd9c9b-9b31-4e64-9a06-d6c1b478427f.png)

Here, we can see the entrance to the Farplane. Leading up to the entrance, you cannot see yourself but you are moving, based on the mini-map in the top left corner.

https://user-images.githubusercontent.com/89695758/131221154-56ccdb86-ada5-42c2-b919-41f06fc1b867.mp4

### How can the issue be reproduced?

This issue can be reproduced at all times, by playing the game. I've listed a few locations where this Issue persists.

- Opening Scenes of the game - You make your way to the Blitzball Stadium to start the Opening Video - The Ramp, just outside the stadium entrance will cut off your character model until you pass the doorway.

- All the "Inns" or "Item Shops" have this graphical error in some capacity. It may be the entire room, or just an area that cuts off a potential NPC or interactable.

- Guadosalam Inn, Item Shop AND the pathway to the Farplane, all show this Graphical Issue.

### Log file

N/A - There are no crashes to inform of, only in-game issues.

### Environment?

- Ryujinx version: 1.0.7017

- Game version: 1.0.1

- System Specs:
  - OS: Windows 10 64-bit
  - CPU: i5-9600K
  - GPU: NVIDIA RTX 2070
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
