### ISSUE TITLE
No More Heroes 3 intense glare issue

### ISSUE THREAD

**Issue by dondonpow** [Ryujinx/Ryujinx#2600]
## Bug Report
https://files.catbox.moe/lfn2fa.PNG
the camera is pointing up. if it was pointing down, the white would fill up the entire screen.

### What's the issue you encountered?

In a lot of scenes, the glare is so intense that it blinds most of the screen.

### How can the issue be reproduced?

Emulate No More Heroes 3 and get to the part on the spaceship.

### Log file

N/A
### Environment?

- Ryujinx version: 1.0.7018</br>
- Game version: 1.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i5-7400*
  - GPU: *NVIDIA GeForce GTX 1660*
  - RAM: *16GB*
- Applied Mods : none

### Additional context?

N/A, my environment is fairly normal.

**Comment by gdkchan** [comment]
Fixed on #2601.
