### ISSUE TITLE
ssl ISslService GetCertificateBufSize is not implemented

### ISSUE THREAD

**Issue by AcK77** [Ryujinx/Ryujinx#2602]
## Missing Service Call

ssl ISslService GetCertificateBufSize is not implemented.

[Switchbrew](https://switchbrew.org/wiki/SSL_services#GetCertificateBufSize)

### Service description
```
Takes a type-0x5 input buffer containing an array of #CaCertificateId, returns an output u32 for the size to use with #GetCertificates.
```

### Required by: 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2551 (using update 1.17.10)

**Comment by Thog** [comment]
Fixed by #2961.
