### ISSUE TITLE
Luigi mansion 3 random crash on AMD Vulkan Windows

### ISSUE THREAD

**Issue by dante3732** [Ryujinx/Ryujinx#2607]
### What's the issue you encountered?
The game freezes in one place, after the cutscene when Luigi and the others take the elevator to the second floor.
![Снимок экрана (1898)](https://user-images.githubusercontent.com/66036249/131353917-d6f2c228-14c1-4e7e-8a84-6f7766bda4d1.png)
If you use the Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods, then the game does not freeze at this place, but hangs in front of the door to the garage in which you need to take vacuum cleaner.
![4](https://user-images.githubusercontent.com/66036249/131353908-d663ab08-e191-4374-81be-ed742ac4ec49.png)

### How can the issue be reproduced?
This happens without any special action.

### Log file
Log crash after elevator without Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods.
[Ryujinx_1.0.03a175b9_2021-08-28_14-55-58.log](https://github.com/Ryujinx/Ryujinx/files/7077363/Ryujinx_1.0.03a175b9_2021-08-28_14-55-58.log)
Log crash next to the door to the garage with Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods.
[Ryujinx_1.0.088f1365_2021-08-28_15-37-03.log](https://github.com/Ryujinx/Ryujinx/files/7077375/Ryujinx_1.0.088f1365_2021-08-28_15-37-03.log)

### Environment?

- Ryujinx version: 1.0.088f1365
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen R5 3600
  - GPU: AMD RX Vega 64
  - RAM: 16GB
- Applied Mods : Yes/No

### Additional context?
Without the mod, the game freezes after the elevator, and with the mod, the game freezes next to the door to the garage.

Also, the emulator can freeze randomly in different places.

**Comment by AcK77** [comment]
Please report the issue in #2518.
Since it’s WIP, here isn’t really the place to give feedback. Thanks.

**Comment by dante3732** [comment]
FIxed on last vulkan PR.
