### ISSUE TITLE
RYUJINX CRASHED WHEN LAUNCHING GAME

### ISSUE THREAD

**Issue by fvkerdummy** [Ryujinx/Ryujinx#2619]
## Bug Report

GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorFeatureNotPresent".

### What's the issue you encountered?

Upon launching any game in ryujinx it will crash when I try to launch any game in ryujinx. I'm using the ryujinx vulkan 1.0.0+a5c9e25

### How can the issue be reproduced?

Launching any game in ryujinx 

### Log file
00:00:00.014 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.015 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.016 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.016 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.016 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.017 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.020 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.028 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.028 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.028 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.028 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.029 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.029 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.030 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.030 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.030 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.034 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+a5c9e25
00:00:00.038 |N| Application Print: Operating System: Microsoft Windows 10.0.18363 (X64)
00:00:00.038 |N| Application Print: CPU: AMD Ryzen 5 3500 6-Core Processor ; 6 logical
00:00:00.038 |N| Application Print: RAM: Total 16335 MB ; Available 6395 MB
00:00:00.040 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.040 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:41.709 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:41.709 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.070 |I| Gpu : Backend Threading (Auto): True
00:00:00.260 |N| Application LoadApplication: Using Firmware Version: 12.1.0
00:00:00.260 |I| Application LoadApplication: Loading as XCI.
00:00:00.351 |I| ModLoader QueryContentsDir: Searching mods for Title 0100AA5015B96000
00:00:00.363 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.447 |I| Loader LoadExeFs: Loading rtld...
00:00:00.522 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.522 |I| Loader LoadExeFs: Loading main...
00:00:00.756 |I| Loader PrintRoSectionInfo: main:
    Module: D:\GameProgram\Unity\Escape104Switch\SwitchIL2CPPCache\il2cpp_cache\linkresult_69336DB973ADF852ECD11BFC03488A23\SwitchPlayer.nss
    SDK Libraries: SDK MW+UnityTechnologies+Unity-2019_4_24_f1
                   SDK MW+Nintendo+NintendoSDK_libcurl-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
00:00:00.756 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.799 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_3-Release
00:00:00.799 |I| Loader LoadExeFs: Loading sdk...
00:00:00.872 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.3
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_3-Release
00:00:00.919 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.098 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.104 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.116 |I| Loader LoadNsos: Loading image 2 at 0x000000000a8d3000...
00:00:01.118 |I| Loader LoadNsos: Loading image 3 at 0x000000000af79000...
00:00:01.126 |I| ModLoader LoadCheats: Build ids found for title 0100AA5015B96000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    51F8BB40DB4C344A8BCF158CDBD492FF00000000000000000000000000000000
    507F19D1240D09D00992248E8A0FD77EBD784EB4000000000000000000000000
    2D369D9999E3E10E665106F840FFFF9BDAA0BB8E000000000000000000000000
00:00:01.126 |I| Loader LoadNca: Application Loaded: Cape's Escape Game 3rd Room v1.0.0 [0100aa5015b96000] [64-bit]
00:00:01.135 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.157 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:01.249 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorFeatureNotPresent".
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.CreateDevice(Vk api, PhysicalDevice physicalDevice, UInt32 queueFamilyIndex, String[] supportedExtensions, UInt32 queueCount)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: 1.0.0+a5c9e25 Vulkan
- Game version: MH Rise 3.2.0 and 1.0.0 / I tried different game still the same error
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 3500
  - GPU: RX 570 4GB
  - RAM: 16 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by GamerzHell9137** [comment]
Vulkan is still in alpha state. Any issues related to Vulkan go here https://github.com/Ryujinx/Ryujinx/pull/2518

**Comment by gdkchan** [comment]
Have you tried updating your drivers?

**Comment by fvkerdummy** [comment]
> 
> 
> Have you tried updating your drivers?

I want to update my graphics driver to latest driver but i might get issues upon updating my amd card.

**Comment by AcK77** [comment]
Issues are for the master branch, since you reporting an issue about the Vulkan PR it’s better to report it on the PR directly or at least on our Discord server. 
Your graphic card seems to don’t support Vulkan for a strange reason, update your drivers if you can or come to our discord server for support.
Thanks.
