### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by Superjack501** [Ryujinx/Ryujinx#2620]
Whenever i open ryujinx it crashes after around 15 seconds. can someone please help because it was working yesturday with Animal Crossing and Mario Kart.
[Ryujinx_1.0.7024_2021-09-04_15-28-52.log](https://github.com/Ryujinx/Ryujinx/files/7110464/Ryujinx_1.0.7024_2021-09-04_15-28-52.log)

**Comment by AcK77** [comment]
Issues aren’t for users support. You can go on our discord server for support if you needs too.
Additionally to that you don’t follow our issue template...
Based on your log file, it seems your profiles.json file in the Ryujinx (AppData) directory is corrupted, you can delete it and try again.
Thanks.
