### ISSUE TITLE
ENDER LILIES: Quietus of the Knights - Graphical corruption in Dryad Lake

### ISSUE THREAD

**Issue by Krusher97** [Ryujinx/Ryujinx#2622]
### What's the issue you encountered?
https://gfycat.com/glisteningwiltedlhasaapso

Graphical corruption starts happening the moment you enter this specific screen. 

### How can the issue be reproduced?

Here is the save file at the area : 
[save.zip](https://github.com/Ryujinx/Ryujinx/files/7114137/save.zip)

### Log file

[Ryujinx_1.0.7024_2021-09-06_12-59-09.zip](https://github.com/Ryujinx/Ryujinx/files/7114118/Ryujinx_1.0.7024_2021-09-06_12-59-09.zip)

### Environment?

- Ryujinx version: 1.0.7024
- Game version: 1.1.1
- System Specs:
  - OS: *Windows 7*
  - CPU: *i5-6500*
  - GPU: *NVIDIA GTX 1050Ti*
  - RAM: *8GB*
- Applied Mods :  No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
