### ISSUE TITLE
Sandy Plains crash 

### ISSUE THREAD

**Issue by kobyakawa** [Ryujinx/Ryujinx#2626]
i was trying to get into sandy plains to so a quest sudenly the app crash 

- Ryujinx version: 1.0.7024

Monster Hunter Rise: 3.2.0

- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3600
  - GPU: Nvdia 970
  - RAM: 16gb
- Applied Mods : none

**Comment by gdkchan** [comment]
Can you attach the log? Otherwise we have no way to tell why it crashed.

**Comment by AcK77** [comment]
No more informations from the user, we could reopen it if a log file will be provided one day.
