### ISSUE TITLE
The Legend of Heroes: Ao no Kiseki

### ISSUE THREAD

**Issue by johnwhite5116** [Ryujinx/Ryujinx#2631]
### What's the issue you encountered?

Sudden FPS dropping

### How can the issue be reproduced?

By playing the game 5~10 minutes.
I tested various ways to find out what exactly causes this issue but I've failed to specify.
It usually happens after moving to other area but not always.
Sometimes it happens after talking to NPC.
From time to time, it happens after event cutscene.
or it can also happen after monster battle.

### Environment

- Ryujinx version: 1.0.7024
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 9 3900X
  - GPU: Nvidia RTX 3090
  - RAM: 32GB
- Applied Mods : No

### Additional context
A Screenshot of normal status
![normal](https://user-images.githubusercontent.com/75278127/132907736-b871f9cc-beb6-4991-84ad-b620140c7513.png)

When this issue happened
![dropped](https://user-images.githubusercontent.com/75278127/132907780-faa4d5cd-1ad0-4237-a7b1-20ded103132a.png)

**Comment by butzman123** [comment]
Same as Trials of Mana, but there it happens after a loading screen

**Comment by JumpmanSr** [comment]
Are you sure that isn't shader compilation?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
