### ISSUE TITLE
Kirby Star Allies rendering errors (Vulkan)

### ISSUE THREAD

**Issue by notjokr** [Ryujinx/Ryujinx#2635]
### What's the issue you encountered?

Various rendering errors throughout the game

Also, the resolution seems to dip back down to native frequently. (currently have it set to 3x)

### How can the issue be reproduced?

Pause menu explosion ([example](https://gfycat.com/teemingshadybrontosaurus), make sure you click the HD toggle on gfycat, it can't be seen otherwise)

Just enter the pause menu

Black elemental trails ([example 1](https://gfycat.com/distantmintycassowary), [example 2](https://gfycat.com/giganticdistinctamurstarfish))

Use any attack that leaves behind any sort of elemental trail

Green particles ([example 1](https://gfycat.com/essentialimperfectaxolotl), [example 2](https://gfycat.com/gaseousvioletconey))

The two easiest places to reproduce this are during the Void Termina fight, or using Marx's down special

Off pitch healing sound ([example](https://gfycat.com/uncomfortableperfectblobfish), you will need to unmute the clip to hear it)

I'm not really sure how to reliably reproduce this. It just happens sometimes, but not all the time

Greens Greens flickering ([example](https://gfycat.com/animatedsillyfruitfly))

Just get to the second half of the post-story level

[Random crash](https://gfycat.com/lividbriefelephant)

Not really sure what happened here, I was playing for a few hours before I was hit with this

### Log file

I have the log file, but I'm not sure how to attach it to this issue

### Environment?

- Ryujinx version: 1.0.0+a5c9e25</br>
- Game version: 4.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 9 5950X
  - GPU: GeForce RTX 3090
  - RAM: 128GB
- Applied Mods : 60FPS

### Additional context?

Additional info about your environment: 3x resolution

**Comment by AcK77** [comment]
This is for issues related to the master branch, even if it’s still nice to get feedback, this is based on WIP feature and should be reported in the PR #2518 directly, thanks.
