### ISSUE TITLE
Sonic Forces

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#264]
A texture is needed to boot farther 0x12 A4B4G4R4 according to switch home brew site here is the error 

https://gist.github.com/ReaperOfSouls1909/bc03ad3238fa92aa8b193c4eaf64b778

**Comment by Hexagon12** [comment]
12 is not the same as 0x12. Converted to hex, it's supposed to be 0x0C, which equates to R16_G16.

**Comment by ReaperOfSouls1909** [comment]
thanks

**Comment by ReaperOfSouls1909** [comment]
pull 236 just needs to be fixed to merge and i can test again

**Comment by ReaperOfSouls1909** [comment]
after merging that format and getting to menu and trying to go in game now i have missing opcode https://gist.github.com/ReaperOfSouls1909/31564d7b3b6678f6842fa3c141735b68

`The instruction at 0x00000000089440f0 (opcode 0x6e600c21) is undefined!`

**Comment by mailwl** [comment]
`21 0C 60 6E                 UQADD           V1.8H, V1.8H, V0.8H`
https://github.com/Ryujinx/Ryujinx/pull/278

(same error in BotW)

**Comment by greggameplayer** [comment]
@AcK77 add label cpu too please

**Comment by ReaperOfSouls1909** [comment]
#278 worked then i needed #234 and after that i got a error i cant pass https://gist.github.com/ReaperOfSouls1909/2d7a861ddbe9147be5ebf2d158aff365

**Comment by urbanman2004** [comment]
Anyway you could post a video of the game performance using the emulator?

**Comment by Dantttt** [comment]
He's already done.

**Comment by AcK77** [comment]
@urbanman2004 it’s not the place to ask that... You should try to find that on YouTube or at least ask on our Discord, thanks.

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/56
