### ISSUE TITLE
H264 Video scene Crash Error 

### ISSUE THREAD

**Issue by syonkr** [Ryujinx/Ryujinx#2648]
### What's the issue you encountered?
h264 out of range, no frame, after crash

### How can the issue be reproduced?
When you start the game, a video scene appears, then crash at this time.

### Environment
- Ryujinx version: 1.0.7038, 1.0.0 vulcan applied</br>
- Game : Layton's Mystery Journey EX</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Windows 7
  - CPU: i7-7700k
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : No, but game was used 1.0.1 nsp patched

## Logs
[Ryujinx_1.0.0+a5c9e25_2021-09-16_02-15-26.log](https://github.com/Ryujinx/Ryujinx/files/7182916/Ryujinx_1.0.0%2Ba5c9e25_2021-09-16_02-15-26.log)

## Screneshot
debugged in crash
![debug](https://user-images.githubusercontent.com/8438478/133730341-4d70a538-7e1f-4ff0-af72-5a3ce4b78531.png)

**Comment by AcK77** [comment]
You seems to use a PR version (and a custom build in your screenshot), if this issue exists on master, please reopen a new issue with all correct informations and a way to reproduce. Thanks.

**Comment by syonkr** [comment]
I already used master branch and checking to same errors in PR Version. (and vulcan applied version too)
they are all same error
