### ISSUE TITLE
No More Heroes 3 Resource Allocation Issue Causing Graphical Glitches

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2658]
### What's the issue you encountered?

There is an issue where if you constantly save and load between different world states the game appears not to fully clear the loaded assets. So for example Santa Destroy might still be using resources in the background even though your are in Perfect World. This will result in graphics eventually being highly degraded and performance becoming terrible. If using a graphics increasing mod, the game will instead crash.

This likely also ties into an issue where, if using a mod to extend the lifetime of decals (such as ground cracks and blood splatters), on transitioning to a different level in-game or loading a save into a different section of the game, the decals will remain present when they shouldn't.

### How can the issue be reproduced?

Load a save into Perfect World. Ride your bike from Perfect World to Santa Destroy and enter the Lab. From the Lab, load the same save from earlier back into Perfect World. Go into a battle in Perfect World and textures will already start to be degraded. Finish the battle, and once back in Perfect World you will get many graphical glitches and degraded performance.

### Environment?

- Ryujinx version: 1.0.7047
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : Not in the first video below. The second video has the decal lifetime mod applied.

### Additional context?

Sequence of events to replicate the issue, no mods:
https://www.youtube.com/watch?v=T-VPQnGXGIo

Decal issue with decal lifetime mod (ground cracks from boss stay in open world at the end):
https://www.youtube.com/watch?v=2AEJc_NPNp8

Another example of the ground cracks staying in a cutscene after the boss with the decal lifetime mod (they shouldn't be there):
https://www.youtube.com/watch?v=zw5yrY-FznQ

Here is the log file, no mods:
[degrading issue.log](https://github.com/Ryujinx/Ryujinx/files/7192904/degrading.issue.log)

**Comment by NikkMann** [comment]
uploaded log

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
