### ISSUE TITLE
No More Heroes 3 Depth of Field Not Scaling With Resolution

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2659]
### What's the issue you encountered?

When increasing the resolution of the game via mods, as the resolution increases from the game's default of 720p, the depth of field in cutscenes becomes more wrong. It looks like the focal length moves closer to the camera as resolution increases.

### How can the issue be reproduced?

Watch cutscenes with the 4k mod. The cutscene where Gold Joe is introduced after defeating Mr. Blackhole is a good example.

### Environment?

- Ryujinx version: 1.0.7039
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : Yes, 4k Graphics Mod
### Additional context?

Here are some screenshots. Neither character should have depth of field on them in the cutscene:
https://imgur.com/a/8dzUIVO

**Comment by AcK77** [comment]
`When increasing the resolution of the game via mods`
it doesn’t sound like an emulator issue then...

**Comment by gdkchan** [comment]
> the depth of field in cutscenes becomes more wrong.

Does that mean that at the native resolution it is also wrong then?
This is a tricky issue since we can't test this on the Switch as the 4K mod is not going to work there, so it's hard to prove that this is an emulator issue.

**Comment by NikkMann** [comment]
> > the depth of field in cutscenes becomes more wrong.
> 
> Does that mean that at the native resolution it is also wrong then?
> This is a tricky issue since we can't test this on the Switch as the 4K mod is not going to work there, so it's hard to prove that this is an emulator issue.

At 720p, even with other graphics mods the depth of field looks fine in cutscenes on the emulator. Its only when you go above it.

**Comment by AcK77** [comment]
Then it’s a mod issue, I suggest you to see that with the mod creators instead. Thanks.

**Comment by NikkMann** [comment]
> Then it’s a mod issue, I suggest you to see that with the mod creators instead. Thanks.

I am the creator lol. Guess its a UE4 problem. I tried fixing it with my mod but no dice.

**Comment by german77** [comment]
Since you are duplicating issues. Test mods on HW not emulators if you want to make sure the mod is not an issue
