### ISSUE TITLE
No More Heroes 3 Travis Off-center on Bike after Ramp Jump

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2662]
### What's the issue you encountered?

After going off a bike jump on the Santa Destroy Open World, Travis will be off center from his bike. How far off center he is seems to be random.

### How can the issue be reproduced?

Go on a bike ramp in the Santa Destroy open world.

### Environment?

- Ryujinx version: 1.0.7047
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Example:
![Screenshot (67)](https://user-images.githubusercontent.com/90150509/133942477-ab44538e-9526-4992-8b87-b352fe8bc66f.png)

Here is the log file:
[Travis misplaced on bike.log](https://github.com/Ryujinx/Ryujinx/files/7192897/Travis.misplaced.on.bike.log)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
