### ISSUE TITLE
Pokemon Sword 0100abf008968000 crash InvalidMemoryRegionException

### ISSUE THREAD

**Issue by d3xMachina** [Ryujinx/Ryujinx#2667]
## Bug Report

> GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000008
> 
>    at Ryujinx.Cpu.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size)
>    at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked)
>    at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked)
>    at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 va, Boolean tracked)
>    at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress)
>    at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress)
>    at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options, TranslationCounts counts, ShaderConfig& config)
>    at Ryujinx.Graphics.Shader.Translation.Translator.CreateContext(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options, TranslationCounts counts)
>    at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, GpuChannel channel, GpuAccessorState gas, ShaderAddresses addresses)
>    at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState()
>    at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
>    at Macro(MacroJitContext , IDeviceState , Int32 )
>    at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, IDeviceState state)
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer)
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
>    at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 

### What's the issue you encountered?

The game crashed while exiting the Motorby stadium with the error (didn't happen the next 2 times I tried) : 

> Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000008

### Log file

[Ryujinx_1.0.7047_2021-09-20_10-42-53.log](https://github.com/Ryujinx/Ryujinx/files/7194862/Ryujinx_1.0.7047_2021-09-20_10-42-53.log)

### Environment?

- Ryujinx version: 1.0.7047</br>
- Game version: 1.3.2</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3900X
  - GPU: GTX 1060
  - RAM: 32GB
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
