### ISSUE TITLE
Crashed when running "Ni no Kuni: Wrath of the White Witch"

### ISSUE THREAD

**Issue by aishen944** [Ryujinx/Ryujinx#2668]
## Bug Report

"N/A" </br>

### What's the issue you encountered?

Crashed when running "Ni no Kuni: Wrath of the White Witch"</br>

### How can the issue be reproduced?

New game!

### Environment?

- Ryujinx version: 1.0.7047</br>
- Game version: 1.0.2</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 4900HS
  - GPU: NVIDIA RTX 2060
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
[Ryujinx_1.0.7047_2021-09-20_20-02-02.log](https://github.com/Ryujinx/Ryujinx/files/7195597/Ryujinx_1.0.7047_2021-09-20_20-02-02.log)

**Comment by raintrija** [comment]
## Ni No Kuni Wrath of the White Witch - 0100E5600D446000

#### Game Update Version : 1.0.2

#### Current on `master` : 1.0.7047

Game Boots in some minute but intro loops and freezes

```
Last error returned.
00:00:42.241 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 4294966296 ; timeout: -1}
00:00:42.241 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.241 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 4294966296 ; timeout: -1}
00:00:42.241 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.243 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 3875766000 ; timeout: -1}
00:00:42.243 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.507 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 3497366000 ; timeout: -1}
00:00:42.507 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.509 |S| HLE.OsThread.9 ServiceNv SetNvMapFd: Stubbed. 
00:00:42.509 |I| HLE.OsThread.9 ServiceNv Create: Created map 241 with size 0x00008000!
00:00:42.509 |I| HLE.OsThread.9 ServiceNv Create: Created map 242 with size 0x00008000!
00:00:42.510 |I| HLE.OsThread.9 ServiceNv Create: Created map 243 with size 0x00003000!
00:00:42.510 |I| HLE.OsThread.9 ServiceNv Create: Created map 244 with size 0x00001000!
00:00:42.510 |I| HLE.OsThread.9 ServiceNv Create: Created map 245 with size 0x00001000!
```

#### Hardware Specs : 

##### CPU:  Intel i5-10500@4.2GHz
##### GPU: AMD R9 290 4GB
##### RAM: 32 GB DDR4@3GHz

#### Pull requests needed :

none

#### Outstanding Issues:

Crashed when running "Ni no Kuni: Wrath of the White Witch"

#### Screenshots :

![image](https://user-images.githubusercontent.com/89759173/135010213-b9368a85-3ca9-43c3-a84d-93f5a734d0a0.png)

#### Log file :
[Ryujinx_1.0.7047_2021-09-28_08-58-35.log](https://github.com/Ryujinx/Ryujinx/files/7240405/Ryujinx_1.0.7047_2021-09-28_08-58-35.log)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
