### ISSUE TITLE
Yoshi`s crafted world crash when choose costumes on 7047 build

### ISSUE THREAD

**Issue by puzavr** [Ryujinx/Ryujinx#2675]
#### Current on `master` : Build Version : 1.0.7047

Windows 10, latest nvidia drivers.
After update from 7022 buid to 7047 the emulator crush when ingame costumes choose interface has opened.
The 7022 build has no issuses in costumes choose dialog.

```
Errors in windows event view:

A TDR has been detected.
The application must close.
Error code: 7
 (pid=12172 tid=14196 ryujinx.exe 64bit)

```
Имя сбойного приложения: Ryujinx.exe, версия: 1.0.7047.0, метка времени: 0x60e89703
Имя сбойного модуля: nvoglv64.dll, версия: 30.0.14.7212, метка времени: 0x613fda91
Код исключения: 0xc0000409
Смещение ошибки: 0x000000000123f229
Идентификатор сбойного процесса: 0x2f8c
Время запуска сбойного приложения: 0x01d7af286471c066
Путь сбойного приложения: C:\Games\Nintendo\ryujinx-1.0.7047-win_x64\publish\Ryujinx.exe
Путь сбойного модуля: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_d3ead92e8ba045de\nvoglv64.dll
Идентификатор отчета: 1c02aa97-1f20-495c-8aff-f1fad8f09d4e
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
