### ISSUE TITLE
revision 2019 in the hurry (demoscene) crashes out straight away

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2678]
using 1.0.7047
00:00:03.299 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fatal.IService: 1
https://www.pouet.net/prod.php?which=8116
[Ryujinx_1.0.7047_2021-09-23_17-21-15.log](https://github.com/Ryujinx/Ryujinx/files/7216342/Ryujinx_1.0.7047_2021-09-23_17-21-15.log)

**Comment by AcK77** [comment]
Could you please reopen an issue using our issue template, this one is a bit pointless right now. Thanks.

**Comment by benderscruffy** [comment]
no thanks its ok
will wait till it is fixed sooner or later
thanks for closing it
