### ISSUE TITLE
Mirrored screen on games like Mario Odyssey

### ISSUE THREAD

**Issue by AliciaMorelliE** [Ryujinx/Ryujinx#2683]
## Bug Report

Mirrored screen launching Mario Odyssey

### What's the issue you encountered?

Mario Odyssey is being launched all upside down including text, animations, menus, characters, maps and everything.

![Ryujinx 1 0 7047 - SUPER MARIO ODYSSEY v1 3 0 (0100000000010000) (64-bit)](https://user-images.githubusercontent.com/80989227/134752471-362f7869-67bd-4f23-8e24-34bf194da24b.jpg)

### How can the issue be reproduced?

I launched it and after it loaded shaders it started upside down.

### Log file

[Ryujinx_1.0.7047_2021-09-24_19-42-22.log](https://github.com/Ryujinx/Ryujinx/files/7228922/Ryujinx_1.0.7047_2021-09-24_19-42-22.log)

### Environment?

- Ryujinx version: 1.0.7047</br>
- Game version: 1.3.0</br>
- System Specs:
  - OS: *(Windows 11)*
  - CPU: *(i5-8600)*
  - GPU: *(NVIDIA GTX 1070ti)*
  - RAM: *(16GB)*
- Applied Mods : [ No ]

**Comment by MetrosexualGarbodor** [comment]
Don't use Nvidia drivers 510.10, they are pre-release and are known to cause these kinds of issues. Downgrade to the normal ones.

**Comment by AliciaMorelliE** [comment]
> Don't use Nvidia drivers 510.10, they are pre-release and are known to cause these kinds of issues. Downgrade to the normal ones.

Didn't thought about that, it actually worked thanks.

**Comment by PantaRei1983** [comment]
Probably related to new shadercache driver option and implemention? I hope that nvidia fix this issue for future, now I also reverted on 476 driver, Ryujinx and other games works like a charm with these on Win11.
