### ISSUE TITLE
Text corrupts in NooDS menu after a few seconds

### ISSUE THREAD

**Issue by CrusadingNinja** [Ryujinx/Ryujinx#2690]
### What's the issue you encountered?

When launching [NooDS](https://github.com/Hydr8gon/NooDS) (homebrew DS emulator) to the file selection menu, the menu is all fine as expected but after around 5 seconds the text becomes corrupted with these black boxes as shown below.
![noodscorruptedtext](https://user-images.githubusercontent.com/77567969/134797275-ab20a549-16bb-4387-ab22-2c082842e6c8.PNG)

### How can the issue be reproduced?

Open [NooDS](https://github.com/Hydr8gon/NooDS) and wait ~5 seconds after the menu loads in.

### Log file
[log](https://github.com/Ryujinx/Ryujinx/files/7230882/Ryujinx_1.0.7047_2021-09-26_01-53-40.log)

### Environment?

- Ryujinx version: 1.0.7047</br>
- System Specs:
  - OS: Windows 10 21H1
  - CPU: R7 3700X
  - GPU: GTX 1070 - 471.96
  - RAM: 16 GB

**Comment by riperiperi** [comment]
I recently made a PR that should fix this, and other buffer corruption issues with OpenGL homebrew. Can you try again with PR #2684?

It appears to be fine here on that PR:
![image](https://user-images.githubusercontent.com/6294155/134806575-ef4e5d59-54a8-4d33-b2ed-6dc6a206ed50.png)

**Comment by Niwu34** [comment]
I can confirm the above - this Pr fixes the issue!
