### ISSUE TITLE
Ryujinx and Steamlink Input conflict(possibly)

### ISSUE THREAD

**Issue by whymsical** [Ryujinx/Ryujinx#2691]
### What's the issue you encountered?
While attempting to stream ryujinx via steamlink to my android phone. Using steamlink's emulated 360 controller as input. The controls will become unresponsive unless my DS4 controller is also connected to my PC, despite not being the selected input in ryujinx. This only occurs on Main build. The LDN build does not appear to have this issue. 

### How can the issue be reproduced?
Attempt to run ryujinx through steamlink, using its emulated 360 input controller

### Log file
Not sure one can really apply to this type of issue as I'm not sure its logged that its not receiving any input. But I can provide one here if you request. 

### Environment?
- Ryujinx version: 1.0.X</br>
1.0.7047
- Game version: X.X.X</br>
N/A 
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3600 
  - GPU: 1060 SC 6gb
  - RAM: 16gb 
- Applied Mods : No

### Additional context?
N/A.

**Comment by ooa113y** [comment]
Steam Link (and Steam Input in general) do not start their controller emulation until there is an OpenGL/Vulkan/Direct3D context into which it can inject itself. You *might* see the controller if you start a game first and then go to the input menu and select it there. Failing that, use [GloSC](https://alia5.github.io/GloSC/) to allow for usage of Steam input without an active renderer.

Either way, there's not much that could be done on the Ryujinx side to fix this aside from rendering the entire GUI through GL/Vulkan, which is rather absurd. This is a problem with how Steam redirects its input, has been there for years, and Valve has shown zero interest in fixing it.

**Comment by AcK77** [comment]
Interesting, I think it's fine to close this issue then, since it's not specific to Ryujinx. Thanks.

**Comment by nero81af** [comment]
I would like to update this issue: actually pad is visible, but with enormous lag (like 2-3 seconds) while it works perfectly if another pad is connected to the host pc

**Comment by GamerzHell9137** [comment]
> 
> 
> I would like to update this issue: actually pad is visible, but with enormous lag (like 2-3 seconds) while it works perfectly if another pad is connected to the host pc

Lag is not related to Ryujinx. Am playing games with a PS Vita and Moonlight and have no issues.
