### ISSUE TITLE
No More Heroes 3 Water Puddle Texture Glitch

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2696]
### What's the issue you encountered?

Water puddles in the open world have a texture glitch around them. The puddles are interactable, in that the water deforms when you walk through them. I did not notice anything in the log when approaching or walking through it.

### How can the issue be reproduced?

Go to a water puddle in the Santa Destroy open world.

### Environment?

- Ryujinx version: 1.0.7058
- Game version: 1.0.2
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : No

### Additional context?
![Screenshot (69)](https://user-images.githubusercontent.com/90150509/135700357-f3dc0899-44af-4105-959e-b23513b1df69.png)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
