### ISSUE TITLE
No More Heroes 3 Various Stutters and Graphical Issues from the Same Log Entries

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2697]
### What's the issue you encountered?

Throughout the game, you will get various issues, whether its stuttering in certain parts of the open world and fighting arenas, shadows getting cutoff abruptly, or lighting glitches, such as lighting leaking through areas where it does not on the base game. 
For all of these issues, whenever they occur, there are always similar log entries stating that maps of varying sizes are created, followed by a map being deleted. 

For example:
00:05:14.539 |I| HLE.OsThread.9 ServiceNv Create: Created map 267 with size 0x00f10000!
00:05:14.540 |I| HLE.OsThread.9 ServiceNv Create: Created map 296 with size 0x00f10000!
00:05:14.541 |I| HLE.OsThread.9 ServiceNv Create: Created map 297 with size 0x00f10000!
00:05:14.543 |I| HLE.OsThread.9 ServiceNv Create: Created map 299 with size 0x00f10000!
00:05:14.550 |S| HLE.OsThread.15 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:05:14.593 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 98!
00:05:14.594 |S| HLE.OsThread.15 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:05:14.648 |I| HLE.OsThread.9 ServiceNv Create: Created map 98 with size 0x00781000!
00:05:14.657 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 133!
00:05:14.658 |S| HLE.OsThread.15 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:05:14.673 |I| HLE.OsThread.9 ServiceNv Create: Created map 133 with size 0x00781000!
00:05:14.684 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 209!
00:05:14.685 |S| HLE.OsThread.15 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:05:14.714 |I| HLE.OsThread.9 ServiceNv Create: Created map 209 with size 0x00781000!
00:05:14.723 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 98!
00:05:14.724 |S| HLE.OsThread.15 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:05:14.756 |I| HLE.OsThread.9 ServiceNv Create: Created map 98 with size 0x00781000!
00:05:14.765 |S| HLE.OsThread.15 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:05:14.796 |I| HLE.OsThread.9 ServiceNv Create: Created map 301 with size 0x00781000!
00:05:14.806 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 133!
00:05:14.807 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 209!

### How can the issue be reproduced?

Play the game and observe the log, its most noticeable in open world areas when panning the camera and stuttering occurs.

### Log file

[Ryujinx_1.0.7058_2021-10-01_20-43-28.log](https://github.com/Ryujinx/Ryujinx/files/7270747/Ryujinx_1.0.7058_2021-10-01_20-43-28.log)

### Environment?

- Ryujinx version: 1.0.7058
- Game version: 1.0.2
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : No

**Comment by gdkchan** [comment]
Those issues have nothing to do with logs, so I'll close this since there's nothing to track here.
