### ISSUE TITLE
FPS drops in Hyrule Warriors: AOC and get steadly low

### ISSUE THREAD

**Issue by codbugpatrol** [Ryujinx/Ryujinx#2700]
### What's the issue you encountered?

FPS drops in Hyrule Warriors: AOC

### How can the issue be reproduced?

Just enter the battlefield, reach near the mobs and the first attack from you or from the mobs at you or any guard, will start the fps to drops and stuck in 3 fps. The FPS get steadly low.

### Log file

[Ryujinx_1.0.7058_2021-10-03_14-24-12.log](https://github.com/Ryujinx/Ryujinx/files/7274230/Ryujinx_1.0.7058_2021-10-03_14-24-12.log)

### Environment?

- Ryujinx version: 1.0.7058

- Game version: 1.2.0</br>

- System Specs:
  - OS: Windows 10 or Linux 20.04 LTS, happens on both
  - CPU: Ryzen 5 3600
  - GPU: GTX 660
  - RAM: 16 GB
- Applied Mods : No

### Additional context?
See the FPS and frames below:

https://user-images.githubusercontent.com/85196112/135765032-b196eabe-05c5-4d2a-9aae-b58e937535c4.mp4

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
