### ISSUE TITLE
Opening Ryujinx on Wayland

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#2714]
## Bug Report

N/A

### What's the issue you encountered?

Running Ryujinx under wayland, Ryujinx crashes.

Wayland do not have access to Display or primary monitor.

This change allows Ryujinx to run:

```
diff --git i/Ryujinx/Ui/MainWindow.cs w/Ryujinx/Ui/MainWindow.cs
index 53a44818..0e516010 100644
--- i/Ryujinx/Ui/MainWindow.cs
+++ w/Ryujinx/Ui/MainWindow.cs
@@ -123,8 +123,8 @@ namespace Ryujinx.Ui
             ThemeHelper.ApplyTheme();
 
             // Sets overridden fields.
-            int monitorWidth  = Display.PrimaryMonitor.Geometry.Width  * Display.PrimaryMonitor.ScaleFactor;
-            int monitorHeight = Display.PrimaryMonitor.Geometry.Height * Display.PrimaryMonitor.ScaleFactor;
+            int monitorWidth  = 0;
+            int monitorHeight = 0;
 
             DefaultWidth  = monitorWidth  < 1280 ? monitorWidth  : 1280;
             DefaultHeight = monitorHeight < 760  ? monitorHeight : 760;
```

### How can the issue be reproduced?

Run Ryujinx under wayland

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.0-dirty</br>
- System Specs:
  - OS: linux
  - CPU: i7
  - GPU: nvidia
  - RAM: 16GB
- Applied Mods : No
- 
### Additional context?

[get monitor number size and scale with gtk and wayland](https://discourse.gnome.org/t/get-monitor-number-size-and-scale-with-gtk-and-wayland/2776/2)
[No monitor report by Gdk on wayland](https://gitlab.gnome.org/GNOME/gtk/-/issues/1028)

**Comment by PawBer** [comment]
The best way to go around this error is to launch the application with the GDK_BACKEND environment variable set to X11 to force use of XWayland. I still need to test if games work that way.

**Comment by e00E** [comment]
Still crashes

```
00:00:00.414 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 150
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 172
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 150
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 172
```

works with `GDK_BACKEND=x11` making it use xwayland.

**Comment by unmellow** [comment]
GDK_BACKEND=x11 SDL_VIDEODRIVER=x11
don't forget sdl

**Comment by edisionnano** [comment]
> `GDK_BACKEND=x11 SDL_VIDEODRIVER=x11` don't forget sdl

Second env isn't needed. Also, this is a hack, it doesn't fix the issus. It forces Ryujinx to run under xwayland instead of native wayland which is bad

**Comment by unmellow** [comment]
it is if you have sdl set to wayland but you could also unset it or never set it in the first place

**Comment by andercard0** [comment]
hi, is there any workaround to the following error : 

00:00:00.005 |W| Application GetWindowScaleFactor: Couldn't determine monitor DPI: Wayland not yet supported
00:00:00.353 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.411 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.416 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.416 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.416 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.417 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.419 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.425 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.426 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.426 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.426 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.426 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.426 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.427 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.427 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.427 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.427 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.427 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.430 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.199
00:00:00.443 |N| Application Print: Operating System: Linux 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 (X64)
00:00:00.443 |N| Application Print: CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
00:00:00.444 |N| Application Print: RAM: Total 32037 MB ; Available 29488 MB
00:00:00.446 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.447 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.668 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 152
   at Ryujinx.Ui.MainWindow..ctor() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 142
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 183
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 152
   at Ryujinx.Ui.MainWindow..ctor() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 142
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 183
Abortado (imagem do núcleo gravada)

I guess it's related the the open issue.

**Comment by albfan** [comment]
@andercard0 yes, the PR #3516, but emulation will break.

    GDK_BACKEND=x11 /path/to/Ryujinx

is your best workaround right now

**Comment by marysaka** [comment]
Should be fixed by https://github.com/Ryujinx/Ryujinx/pull/4013.
