### ISSUE TITLE
Using secondary GPU on linux

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#2715]
## Bug Report

In a linux system with two GPUs
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
0c:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] (rev a1)
```

Ryujinx runs correctly on Intel GPU.
nvidia 470 driver is installed for nvidia

GDK_BACKEND=x11 DRI_PRIME=0 Ryujinx  works correctly.

GDK_BACKEND=x11 DRI_PRIME=1 Ryujinx  fails with:

```
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
XError: 0 result is 167
XError: 0 result is 167
00:00:01.697 |E| Application : Unhandled exception caught: SPB.Graphics.Exceptions.ContextException: CreateContext() failed.
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GLWidget.Intialize() in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLWidget.cs:line 89
   at Ryujinx.Ui.GLWidget.OnDrawn(Context cr) in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLWidget.cs:line 47
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

Wonder if this is related with blacklisting nouveau driver, not sure why it tries to load.

### What's the issue you encountered?

Ryujinx should be able to run using secondary GPU

### How can the issue be reproduced?

    GDK_BACKEND=x11 DRI_PRIME=1 Ryujinx

### Log file

```
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
XError: 0 result is 167
XError: 0 result is 167
00:00:01.697 |E| Application : Unhandled exception caught: SPB.Graphics.Exceptions.ContextException: CreateContext() failed.
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GLWidget.Intialize() in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLWidget.cs:line 89
   at Ryujinx.Ui.GLWidget.OnDrawn(Context cr) in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLWidget.cs:line 47
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

### Environment?

- Ryujinx version: 1.0.0-dirty</br>
- System Specs:
  - OS: linux
  - CPU: i7
  - GPU: Nvidia
  - RAM: 16GB
- Applied Mods : No

### Additional context?

I tried samples from LearnOpenTK:

```
git clone /home/alberto/projects/csharp/LearnOpenTK/
cd LearnOpenTK/Chapter2/3-Materials
dotnet build .
DRI_PRIME=1 ./bin/Debug/netcoreapp3.1/LearnOpenTK 
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
```

with a simple modification to see fps:

```
diff --git i/Chapter2/3-Materials/Window.cs w/Chapter2/3-Materials/Window.cs
index 622bb1e..f87bf98 100644
--- i/Chapter2/3-Materials/Window.cs
+++ w/Chapter2/3-Materials/Window.cs
@@ -129,6 +129,7 @@ namespace LearnOpenTK
         protected override void OnRenderFrame(FrameEventArgs e)
         {
             base.OnRenderFrame(e);
+            this.Title = "LearnOpenTK - Materials (Vsync: " + VSync.ToString() + ") " + "  FPS: " + (1f / e.Time).ToString("0.");
 
             GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
 
@@ -261,4 +262,4 @@ namespace LearnOpenTK
             _camera.AspectRatio = Size.X / (float)Size.Y;
         }
     }
```
1000 FPS with NVIDIA:

![Captura de pantalla de 2021-10-07 08-00-33](https://user-images.githubusercontent.com/220968/136335013-3a9a96b3-52a1-45eb-adbb-e7bfe011133f.png)

and with intel GPU 60 FPS:

![Captura de pantalla de 2021-10-07 08-00-11](https://user-images.githubusercontent.com/220968/136335043-c6845f50-a10b-4d24-be19-83639d5fb601.png)

I get similar results for glxgears.

**Comment by ChristopherHolder** [comment]
Disculpa Alberto, tengo el mismo problema que vos tenes. Al final pudiste repararlo. Trate usando los mismos env variables que utilizaste y me crashea con el mismo error.

Uso Arch
Graphics:
  Device-1: NVIDIA TU117M [GeForce MX450] driver: nvidia v: 515.57
  Device-2: AMD Lucienne driver: amdgpu v: kernel
  Device-3: Quanta USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: amdgpu,nvidia unloaded: modesetting,vesa gpu: amdgpu resolution:
    1: 1920x1080 2: 1920x1080 3: N/A
  OpenGL: renderer: AMD RENOIR (LLVM 14.0.6 DRM 3.46 5.18.12-arch1-1)
    v: 4.6 Mesa 22.1.3

**Comment by EmulationFanatic** [comment]
> Disculpa Alberto, tengo el mismo problema que vos tenes. Al final pudiste repararlo. Trate usando los mismos env variables que utilizaste y me crashea con el mismo error.
> 
> Uso Arch Graphics: `Device-1: NVIDIA TU117M [GeForce MX450] driver: nvidia v: 515.57
> 
> Device-2: AMD Lucienne driver: amdgpu v: kernel
> 
> Device-3: Quanta USB2.0 HD UVC WebCam type: USB driver: uvcvideo
> 
> Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X: loaded: amdgpu,nvidia unloaded: modesetting,vesa gpu: amdgpu resolution: 1: 1920x1080 2: 1920x1080 3: N/A OpenGL: renderer: AMD RENOIR (LLVM 14.0.6 DRM 3.46 5.18.12-arch1-1) v: 4.6 Mesa 22.1.3`

Solamente en Inglès, por favor.

**Comment by edisionnano** [comment]
We have many options:
Use EGL
Use Wayland
Use Vulkan
Use Avalonia
Use the nvidia gpu as primary

**Comment by ChristopherHolder** [comment]
I'm gonna try some of this, thanks for the help.
