### ISSUE TITLE
Hanayaka Nari Waga Ichizoku Modern Nostalgie [01008de00c022000] [32-bit] crash at start

### ISSUE THREAD

**Issue by bluebanana2021** [Ryujinx/Ryujinx#2717]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?
Loading up the game crashes. Both in xci format or nsp format.
I did not make any custom settings to Ryujinx other than turning on the debug logging just for this report.

### How can the issue be reproduced?
Just start the game, it will crash.

### Log file
[Ryujinx_1.0.7064_2021-10-08_04-46-40.log](https://github.com/Ryujinx/Ryujinx/files/7306584/Ryujinx_1.0.7064_2021-10-08_04-46-40.log)

### Environment?

- Ryujinx version: 1.0.7064</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 5900X 12-Core Processor 3.70 GHz
  - GPU: AMD Radeon RX 6800 XT
  - RAM: 64 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues). This issue will be tracked as a missing CPU instruction [here](https://github.com/Ryujinx/Ryujinx/issues/3686). Thanks!
