### ISSUE TITLE
Pokemon Mystery Dungeon: Rescue Team DX inconsistent booting

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#2719]
### What's the issue you encountered?

RTDX seems to struggle to boot on master and consistently seems to hang on startup. There is a chance it does boot but this seems exceedingly random and no variation of settings or versions seems to help this.

### How can the issue be reproduced?

Simply attempt to boot the game a few times, you may be able to boot once or twice but as I say it seems fairly inconsistent if the startup process hangs.

### Log file
**All log files are terminated by a Stop emulation command after waiting for around 3-4 mins for change in activity.**

[Ryujinx_1.0.7065_2021-10-08_18-21-35.log](https://github.com/Ryujinx/Ryujinx/files/7313300/Ryujinx_1.0.7065_2021-10-08_18-21-35.log)

Seems to always hang on either:

HLE.OsThread.9 ServiceNv Create: Created map XX with size 0x01000000!
or some form of GPU thread "too slow" message.

Log with all debugging logs enabled: 
[Ryujinx_1.0.7065_2021-10-08_18-20-02.log](https://github.com/Ryujinx/Ryujinx/files/7313306/Ryujinx_1.0.7065_2021-10-08_18-20-02.log)

### Environment?

- Ryujinx version: 1.0.7065
- Game version: 1.0.2
- System Specs:
  - OS: Windows Version	10.0.19043 Build 19043
  - CPU: Ryzen 5 5600X
  - GPU: Nvidia RTX 3070 FE
  - RAM: 32GB DDR4 
- Applied Mods : No

### Additional context?

Works fine in LDN2.3 so I can only imagine some form of regression somewhere between then and now. That doesn't really narrow the issue down though haha

LDN2.3 boot log:
[Ryujinx_1.0.0-ldn2.3_2021-10-08_19-00-33.log](https://github.com/Ryujinx/Ryujinx/files/7313323/Ryujinx_1.0.0-ldn2.3_2021-10-08_19-00-33.log)

**Comment by GamerzHell9137** [comment]
> 
> 
> IIRC it used to hang because the table walk was broken, but it also used to crash consistently because of access violations. Maybe some kind of race condition? I am not sure.
> 
> Changing these 2 properties to `false` might fix it, since it will behave closely to the old jump tables.
> 
> https://github.com/Ryujinx/Ryujinx/blob/0d174cbd4555e69660a900577a52f3d4bf7391b9/ARMeilleure/Optimizations.cs#L9-L11

Still seems to be happening.
![image](https://user-images.githubusercontent.com/2002038/138087088-26a24075-1ff7-487b-bb75-8c07dfc7c8b5.png)
