### ISSUE TITLE
Simulated wake up message feature

### ISSUE THREAD

**Issue by Yehuhu** [Ryujinx/Ryujinx#2728]
### What's the issue you encountered?

I've just downloaded the emulator and try it with CTR nitro fueled. I barely change anything that was marked by default and the game runs perfect at about 50-60 fps. The issue is that the sound is always stuttering unless I click on "simulate wake up message". When I click it everything goes just fine for about 5 minutes, then it deactivates and sound goes laggy again. Is there a way to keep it enabled?

[ Did you make any changes related to Ryujinx itself? ]
If you mean code no, I didn't

### How can the issue be reproduced?

I just click on simulate wake up message and everything runs perfect for about 5 min. Then the sound goes laggy.

### Environment?

- Ryujinx version: 1.0.7066

- Game version: CTR Nitro Fueled 1.0.0

- System Specs:
  - OS: Windows 11
  - CPU: i5 8600k
  - 
  - GPU: Nvidia GTX1050
  - RAM: 8gb
- Applied Mods : No

**Comment by AcK77** [comment]
`50-60 fps` isn't full speed, that's probably why the sound is laggy after some minutes of playing. `Simulated wake up message` is just to simulate when the switch wake up, so it doesn't make sense to keep it enabled.
If anyone else who's running the game fullspeed could validate the issue, I'll reopened it.
Thanks.
