### ISSUE TITLE
[Feature Request] Implement downscaling and upscaling filter choice.

### ISSUE THREAD

**Issue by elexor** [Ryujinx/Ryujinx#2729]
#### Overview:
Ability to select a independant upscaling or downscaling filter when output resolution does not match fullscreen monitor resolution over or under.

#### Smaller Details: 
Recommended filter choices:
bilinear
nearest neighbor
bicubic
hermite
lanzcos
AMD fsr

The wii U emulator cemu allready has a similar feature
![cemu](https://i.imgur.com/EKMr55y.png) 

#### Nature of Request:  
- Addition

### Why would this feature be useful?
When supersampling or on limited hardware, Having the ability to choose the scaling filter gives users more options to tailor image quality to their personal tastes, whether it be softer scaling to reduce jaggies, to nearest neighbor for an ultra crisp image.

Pixel art games can greatly benefit from a customizable scaling filter.

**Comment by ibrokemypie** [comment]
+1 for this, Yuzu has the option to use Scaleforce or AMD FSR when downscaling from 1440 to 1080 which look miles better than bilinear, bicubic and whatever Ryujinx is using

For comparison, the same scene in Ryujinx:
![image](https://user-images.githubusercontent.com/7827846/141614041-7bee488b-387b-4910-b2e8-c778e04d2859.png)

Then in Yuzu using FSR:
![image](https://user-images.githubusercontent.com/7827846/141614178-e58c927d-a4d4-42c8-9c75-4ed37158df10.png)

Both rendering at 2x and downscaling to 1080p

**Comment by Foul-Tarnished** [comment]
Please, some of my games have awful aliasing, bicubic should slightly help when at 2x-3x

**Comment by riperiperi** [comment]
Only use up to 2x of your output display resolution for the best results. You can't downsample any more with a regular texture filter.
