### ISSUE TITLE
Diablo II: Resurrected black textures

### ISSUE THREAD

**Issue by SpAz47** [Ryujinx/Ryujinx#2733]
### What's the issue you encountered?
![image](https://user-images.githubusercontent.com/92412954/137050817-3e4e1f7b-cc8e-4510-b0b8-976a4d3a2278.png)

### How can the issue be reproduced?

I just start the game and that's it, latest emu and everything

### Environment?

- Ryujinx version: 1.0.7073</br>
- Game version: 1.0.0.2</br>
- System Specs:
  - OS: win10
  - CPU: i6-6200u
  - GPU: GTX 920MX
  - RAM: 8gb

**Comment by gandalfthewhite19890404** [comment]
Can you check on latest version, please?

**Comment by gandalfthewhite19890404** [comment]
An issue could still exist, but game does not boots anymore, since November 2021, so we did not report here with new builds.

**Comment by gandalfthewhite19890404** [comment]
Reopen it, as you can see - there are missing textures - missing letters, missing hair.
![image](https://user-images.githubusercontent.com/24764335/173217059-1d1cd28f-ff4c-4921-9e58-17b80813e432.png)

**Comment by Labaman** [comment]
I observe a similar problem on OS Linux:
Problem with displaying non-Latin fonts (not only Cyrillic)
![Снимок экрана от 2022-08-13 18-37-54](https://user-images.githubusercontent.com/30574992/184501428-f59b8d76-42a1-41ad-95a9-f353bf45b936.png)
![Снимок экрана от 2022-08-13 18-38-49](https://user-images.githubusercontent.com/30574992/184501439-27b74d87-5e79-41d8-b4cf-93fa0bfd9f66.png)
Also, the numbers showing the number of spell/master charges are not displayed:
For example the call of the raven of the druid numbers 1-3 on the icon spell are displayed correctly, but 4, 5, 6, etc - are not displayed. 
Please fix this problem at last!
![Снимок экрана от 2022-08-13 18-55-30](https://user-images.githubusercontent.com/30574992/184501563-d684e65a-fcdc-4421-8f26-b3201a817654.png)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
