### ISSUE TITLE
Snack World: The Dungeon Crawl unplayable on current version (and previous versions too)

### ISSUE THREAD

**Issue by p0kiehl** [Ryujinx/Ryujinx#2734]
### What's the issue you encountered?

Game opens and goes through the cinematic animation, but when you start a new game FPS drops to 0 and there's some texture corruption.
Problem persists after character creation, opening menus basically freezes the game for a while. FPS is unstable and keeps going to 0.

### How can the issue be reproduced?

Just opening the game.

### Log file

[Ryujinx_1.0.7073_2021-10-13_09-05-19.log](https://github.com/Ryujinx/Ryujinx/files/7337962/Ryujinx_1.0.7073_2021-10-13_09-05-19.log)

### Environment?

- Ryujinx version: 1.0.7073
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 3600
  - GPU: RX 580
  - RAM: 16GB
- Applied Mods : No

### Additional context?

![ryujinx_capture_2021-10-13_09-08-52](https://user-images.githubusercontent.com/87043244/137130973-3e40a0cb-c92d-47e1-b0ff-8fc4c463b7df.png)

**Comment by Niwu34** [comment]
Fixed by #3207 
![Screenshot 2022-03-16 194648](https://user-images.githubusercontent.com/67392333/158664641-a62290b9-a702-459d-968f-c28b5dc2b024.png)
