### ISSUE TITLE
Mii loader applet crashes everytime you hit enter after typing your name

### ISSUE THREAD

**Issue by SaintZeroZ** [Ryujinx/Ryujinx#2736]
## Bug Report

Mii loader applet crashes everytime you hit enter after typing your name

### What's the issue you encountered?

I'm playing Miitopia I have to switch between Yuzu and Ryujinx to play it. I can only make Miis in Ryujinx but recently everytime I make a Mii it crashes. As soon as I type the name and hit enter I get --- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### How can the issue be reproduced?

By going to File, Load Applet, Mii Editor, and trying to create a Mii. When you go to done and it asks for a name that's when it happens

### Log file

[Ryujinx_1.0.7073_2021-10-13_11-01-25.log](https://github.com/Ryujinx/Ryujinx/files/7339325/Ryujinx_1.0.7073_2021-10-13_11-01-25.log)

### Environment?

- Ryujinx version: 1.0.7073

- Game version: 1.0.4</br>

- System Specs:
  - OS: *(Windows 10)*
  - CPU: *(i5-8400)*
  - GPU: *(e.g. NVIDIA RTX 1080 3gb)*
  - RAM: *(8gb)*
- Applied Mods : [ Yes (Which ones) / (No) ] 

### Additional context?
It was working before I don't remember the exact version this happened since it updated a few times. 

Additional info about your environment:</br>
N/A

**Comment by gdkchan** [comment]
Fixed by #2732.
