### ISSUE TITLE
Hyrule Warriors Definitive Edition - In-stage missions do not progress, various softlocks

### ISSUE THREAD

**Issue by vickyorlo** [Ryujinx/Ryujinx#2744]
## Bug Report

</br>

### What's the issue you encountered?
Once in a while, seemingly at random, once a mission (in-level task) is completed, the following mission does not trigger, causing a softlock. On occasion the softlock will resolve itself after a couple minutes of nothing happening, but it feels rare. I have however found one softlock that is fully reproducible on the "Powers Collide" story mode mission, where one of the engineers that are supposed to run towards a certain point of the map simply stands there waiting for God knows what, even though there are no enemies on his way.

![softlock](https://user-images.githubusercontent.com/18310449/137594376-4024f8e7-34bb-4d2d-84cf-e739b65aca68.png)

The engineer in question is on the right side of the map, the blue bullseye icon covered by an arrow. He should be with his other two blue bullseye icon friends. Also note to the left the red dot on the map, which is supposed to represent a group of enemies. It is a lie, however, there are no enemies in that whole section of the map anymore.

I have confirmed that this issue does not appear on real hardware, and I have transplanted a suspend save to Yuzu - the issue does not happen there either. I have also cleared my PPTC as people used to report issues with the game related to it, but it did not help.

### How can the issue be reproduced?

1. Download the included save file
2. When in the main menu, pick Resume to load the suspend save
3. The Engineers should appear momentarily. The save puts you in the corridor the problematic engineer goes through, and it needs to be cleared of enemies. 
4. Even if the enemies are cleared, the eastern Engineer will not move past about halfway of the hallway, as on the screenshot.
5. One of the other Engineers might die and fail the mission, but this is unrelated. This can be easily enough prevented by defeating the other enemies on their paths.

### Log file

[Ryujinx_1.0.7074_2021-10-16_17-58-58.log](https://github.com/Ryujinx/Ryujinx/files/7357889/Ryujinx_1.0.7074_2021-10-16_17-58-58.log)

### Environment?

- Ryujinx version: 1.0.7074</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Arch Linux
  - CPU: Ryzen 5600x
  - GPU: GTX1080
  - RAM: 32GBB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
The save file with a suspend save:
[hw save file.zip](https://github.com/Ryujinx/Ryujinx/files/7357823/hw.save.file.zip)

**Comment by Shahil-Ayato** [comment]
Fixed by #2828

**Comment by vickyorlo** [comment]
Oops, I was supposed to close this when the PR was merged, but forgot.
