### ISSUE TITLE
Ori and the Will of the Wisps crashes while starting

### ISSUE THREAD

**Issue by codbugpatrol** [Ryujinx/Ryujinx#2756]
### What's the issue you encountered?

Game Ori and the Will of the Wisps [01008dd013200000] crash while trying to load the game:
Invalid memory access at virtual address

### How can the issue be reproduced?

Try to begin the game.

### Log file

[Ryujinx_1.0.7081_2021-10-18_22-39-42.log](https://github.com/Ryujinx/Ryujinx/files/7369561/Ryujinx_1.0.7081_2021-10-18_22-39-42.log)

### Environment?

- Ryujinx version: 1.0.7081</br>

- Game version: 1.0.0</br>

- System Specs:
  - OS: Windows 10
  - CPU:  Ryzen 5 3600
  - GPU: NVIDIA GTX 670
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

Additional info about your environment:</br>
No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
