### ISSUE TITLE
DOOM failed to start - "WASAPI: Unsupported audio format"

### ISSUE THREAD

**Issue by codbugpatrol** [Ryujinx/Ryujinx#2758]
### What's the issue you encountered?

Game DOOM crashes while trying to start:
![image](https://user-images.githubusercontent.com/85196112/137830242-1d847640-357d-4a65-8049-e37635fe0f0c.png)

### How can the issue be reproduced?

Try to begin the game.

### Log file

[Ryujinx_1.0.7081_2021-10-18_22-45-28.log](https://github.com/Ryujinx/Ryujinx/files/7369582/Ryujinx_1.0.7081_2021-10-18_22-45-28.log)

### Environment?

- Ryujinx version: 1.0.7081</br>

- Game version: 1.0.0</br>

- System Specs:
  - OS: Windows 10
  - CPU:  Ryzen 5 3600
  - GPU: NVIDIA GTX 670
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

Additional info about your environment:</br>
No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
