### ISSUE TITLE
Green light out of bounds on Jump Force

### ISSUE THREAD

**Issue by codbugpatrol** [Ryujinx/Ryujinx#2760]
### What's the issue you encountered?

While playing the game JUMP FORCE Deluxe Edition, green lights are shown out of the bounds:
![image](https://user-images.githubusercontent.com/85196112/137831525-8e3b1f0f-b714-4193-864b-7833b1c148cb.png)
![image](https://user-images.githubusercontent.com/85196112/137831536-4a9fafbd-d70f-4509-8ef8-6334736fcf16.png)
![image](https://user-images.githubusercontent.com/85196112/137831573-ecc7791c-ecf1-47da-8197-db656e92f48b.png)

No errors on the logs.

### How can the issue be reproduced?

Just start a new game and enter the tutorial.

### Log file

[Ryujinx_1.0.7081_2021-10-18_22-58-58.log](https://github.com/Ryujinx/Ryujinx/files/7369624/Ryujinx_1.0.7081_2021-10-18_22-58-58.log)

### Environment?

- Ryujinx version: 1.0.7081</br>

- Game version: 1.0.0</br>

- System Specs:
  - OS: Windows 10
  - CPU:  Ryzen 5 3600
  - GPU: NVIDIA GTX 670
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

Additional info about your environment:</br>
No

**Comment by MetrosexualGarbodor** [comment]
Seems to still happen. 
![imagen](https://user-images.githubusercontent.com/79612681/164802101-ac50decc-f4b5-4f66-98d8-1aea936b9ade.png)
Screenshot taken from Heavenki on discord.
