### ISSUE TITLE
Gyro sensor drifting/bobbing with DualShock controllers

### ISSUE THREAD

**Issue by KawaiiDinosaur** [Ryujinx/Ryujinx#2765]
### What's the issue you encountered?

Using a Sony DualShock ou DualSense controller to emulate the gyro pointing of JoyCons will cause drifting and bobbing on the pointer. Changing sensitivity and deadzone values doesn't remediate the issue.

### How can the issue be reproduced?

Launching a game that makes use of gyro pointers while using a DualShock controller.

### Log file

[Ryujinx_1.0.7082_2021-10-21_19-25-56.log](https://github.com/Ryujinx/Ryujinx/files/7393255/Ryujinx_1.0.7082_2021-10-21_19-25-56.log)

### Environment?

- Ryujinx version: 1.0.7082</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 11 build 22000.282
  - CPU: Ryzen 3700X
  - GPU: RX 5700 XT (Driver 21.10.2)
  - RAM: 16GB 
  - Applied Mods : No

### Additional context?

Controllers tested: DualShock 4 v1, Dualshock 4 v2, DualSense, all via USB.

https://user-images.githubusercontent.com/36821201/138366939-8c003130-0b47-462f-bc08-fa8bb096363d.mp4

**Comment by 3D8bitGamer** [comment]
Same issue here. Using Dualshock 4, motion control is drifting and bobbing itself. And making the motion controls based games unplayable.
In New Super Mario Bros U Deluxe in which motion controls are required in one of the last few levels (Red hot Elevator Ride), motion controls are even inverted ( also mentioned in post no. #2480 ).

Using DS4Windows also giving same issue.
Checked on latest version of Ryujinx available 1.1.102 as on 10 April 2022.
Specs are Intel 8950HK, 16GB RAM, turbo speed 4.8Ghz, 6 Cores 12 threads, GTX1060 6GB VRAM.

**Comment by ActualMandM** [comment]
I seemed to get a similar issue when doing the Splatoon 3 tutorial in the Splatfest World Premiere demo.

https://user-images.githubusercontent.com/15317421/186582735-ca662a37-1e4c-4523-af4e-017d50404452.mp4

**Comment by RaijinXBlade** [comment]
> I seemed to get a similar issue when doing the Splatoon 3 tutorial in the Splatfest World Premiere demo, making it look like the camera was automatically resetting itself.

I can confirm this. I'm getting the exact same issue. Using a DS4 controller, and tested with both Steam and DS4Windows. Hope this issue can be fixed, or there is some work around.

**Comment by katatin31** [comment]
Has anyone been able to solve this problem?

**Comment by MutantAura** [comment]
Fixed by #4705
