### ISSUE TITLE
Broken motion contols on Linux

### ISSUE THREAD

**Issue by AlfredoRodda** [Ryujinx/Ryujinx#2767]
### What's the issue you encountered?
Similar to closed #2226
DualShock 4 is accessible and detected by HIDAPI, motion works in other emulators
DualShock 4 controller set as a Pro Controller
Native motion controls is set in input settings but results in no motion controls. 
If I replace the supplied libSDL2.so with the one on my system motion works fine

### How can the issue be reproduced?

Connect a DualShock 4 controller and enable native motion controls in input settings.
Try to use motion controls in-game.

### Environment?

    Ryujinx version: 1.0.7082

    System Specs:
        OS: Linux
        CPU: Ryzen 3600
        GPU: AMD RX 5700XT
        
    Applied Mods : No

**Comment by Thog** [comment]
Reopening as it was reverted (SDL2 latest cause crashes for some users)
