### ISSUE TITLE
Pokémon Mystery Dungeon: Rescue Team DX render bug

### ISSUE THREAD

**Issue by yup-tm** [Ryujinx/Ryujinx#2787]
### What's the issue you encountered?

Moltres boss room on Pokémon Mystery Dungeon: Rescue Team DX does not render correctly the fire on the background
![image](https://user-images.githubusercontent.com/82262888/138974714-06e6ed07-334a-4b2e-b1c8-908b33c226db.png)

here is how it should look
![image](https://user-images.githubusercontent.com/82262888/138974818-92533baa-15ba-4537-906e-a2357e06b23c.png)

### How can the issue be reproduced?

Just go into moltres's room

### Environment?

- Ryujinx version: 1.0.7091</br>
- Game version: 1.0.2</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i5-11400F*
  - GPU: *NVIDIA GTX 1650S*
  - RAM: *16GB*
- Applied Mods : No

### Additional context?
Here is a savefile just before moltres room, it will spawn on the stairs, say no to helping the pokemon in the room and yes to go to the next room
[PMD_savefile.zip](https://github.com/Ryujinx/Ryujinx/files/7422028/PMD_savefile.zip)

**Comment by MetrosexualGarbodor** [comment]
Issue still present in 1.1.24. 
![imagen](https://user-images.githubusercontent.com/79612681/153536381-160bce73-5130-4a75-bbb2-3d4787b40303.png)

**Comment by yup-tm** [comment]
![image](https://user-images.githubusercontent.com/82262888/161977347-72fb5250-455d-4ac2-ac4c-2113255a8da6.png)
issue gone on latest 1.1.91
