### ISSUE TITLE
Pikmin 3 Deluxe - missing textures

### ISSUE THREAD

**Issue by vl3214** [Ryujinx/Ryujinx#2796]
Those data file things you collect are completely invisible, the textures are just missing. The only thing you can see indicating it is there is the glow on the floor. I checked a pretty recent gameplay video on yt and saw it had the same issue, so it's not just me. You can check that out if you want to see exactly what I'm talking about. https://youtu.be/tRMY0eB5nJE?t=924

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
