### ISSUE TITLE
Animal Crossing: New Horizons periodically crashes after Ryujinx update from 1.0.7092 to 1.0.7094

### ISSUE THREAD

**Issue by EnoughTea** [Ryujinx/Ryujinx#2800]
### What's the issue you encountered?

After updating Ryujinx to 1.0.7094 version AC: NH started to crash Ryujinx once in a while. Crash occurs randomly when leaving a building such as the museum or Nook's Cranny. If I downgrade Ryujinx to 1.0.7092, game works fine again.

### How can the issue be reproduced?

Crash seems to be random and infrequent, happens every 30 minutes or so, cannot find reliable reproduction steps. Just play for an hour entering/leaving buildings often, I guess.

### Log file

[Ryujinx_1.0.7094_2021-11-01_18-10-19.log](https://github.com/Ryujinx/Ryujinx/files/7454367/Ryujinx_1.0.7094_2021-11-01_18-10-19.log)
[Ryujinx_1.0.7094_2021-11-01_17-38-06.log](https://github.com/Ryujinx/Ryujinx/files/7454368/Ryujinx_1.0.7094_2021-11-01_17-38-06.log)

### Environment?

- Ryujinx version: 1.0.7094</br>
- Game version: 1.11.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 7 3700x
  - GPU: NVIDIA GTX 1080 Ti
  - RAM: 16GB
- Applied Mods : None.

### Additional context?
Firmware is 13.0.0
Graphics settings are as follows:
![image](https://user-images.githubusercontent.com/2484351/139700355-fad9bcb5-ff17-4f6c-aa76-a70a0f7b55ca.png)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
