### ISSUE TITLE
MP Superstars issues

### ISSUE THREAD

**Issue by RMED24** [Ryujinx/Ryujinx#2803]
### What's the issue you encountered?

There's the issue of black water effects trailing the boats in the minigame 'Puddle Paddle'. 
Which can be seen in this image: ![ryujinx_capture_2021-11-02_10-59-21](https://user-images.githubusercontent.com/81475204/139835074-74a28eb6-1149-4f89-a9e3-a8165166807c.png)
I am using Ryujinx LDN2.4 in handheld mode at 2x resolution. However, the issue still occurs with resolution scaling disabled and enabling docked mode.

There is also an issue with the warp and squish effects used in 2 player games when someone wins/loses where it tanks the performance from 60fps to 8fps, however it only occurs during that squish transition which I'm not too concerned about. I do not have an image for this as it's performance related

### How can the issue be reproduced?

It seems that just starting the minigame 'Puddle Paddle' should show the issue for the water bug

For the squish transition tanking performance, you can see that best in the minigame 'Spin Doctor' once you win or lose the minigame

### Environment?

- Ryujinx version: 1.0.LDN-2.4
- Game version: 1.1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i5-4570
  - GPU: NVIDIA GTX 1050ti
  - RAM: 16GB
- Applied Mods : No

**Comment by smiglo5** [comment]
It will be fixed with this PR
https://github.com/Ryujinx/Ryujinx/pull/2801

So that issue is already known, I've also reported some of them in these posts:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3752#issuecomment-955780588
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3752#issuecomment-956130809

**Comment by RMED24** [comment]
For some reason my mind completely forgot about the ryujinx games list. I will check that one next time before mentioning an issue

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
