### ISSUE TITLE
[Regression][Linux] Pokemon Sw/Sh cannot load saves anymore

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#2805]
### What's the issue you encountered?

The game shows a "your data is corrupted" message.
My savefile has been imported with success on real hardware, meaning this is a ryujinx regression.

### How can the issue be reproduced?

valid pokemon sword v1.3.2 save
[pkmsw132.zip](https://github.com/Ryujinx/Ryujinx/files/7461956/pkmsw132.zip)

### Log file
[Ryujinx_1.0.7096_2021-11-02_15-53-40.log.zip](https://github.com/Ryujinx/Ryujinx/files/7461870/Ryujinx_1.0.7096_2021-11-02_15-53-40.log.zip)

### Environment?

- Ryujinx version: 1.0.7096
- Game version: 1.3.2</br>
- System Specs:
  - OS: *ArchLinux*
  - CPU: *i5-1035g7*
  - GPU: *iris plus 940*
  - RAM: *16gb*
- Applied Mods : no

**Comment by chris4540** [comment]
Confirmed on a Linux Mint Machine. This issue cannot reproduce on a Windows machine with the same save file.
**Environment?**

- Ryujinx version: 1.0.7096 / 1.0.0-ldn2.4
- Game version: 1.3.2
- System Specs:
    - OS: Linux Mint 20.1
    - CPU: i5-1135G7
    - GPU: iris plus 940
    - RAM: 16gb
    - Applied Mods : no

**Comment by lordmyron** [comment]
The bug still exists on the latest master build. Happens on a fresh save too.
