### ISSUE TITLE
Legend of Mana random crashes

### ISSUE THREAD

**Issue by dangerousPoison** [Ryujinx/Ryujinx#2809]
### What's the issue you encountered?

If you are trying to beat Legend of Mana on Ryujinx you must be aware of the random crashes that make it quite hard to progress.

This save file will allow you to start a battle where the emulator always crashes. Check the video if you don't know how to start the battle.

I've been trying all newer versions of Ryujinx since the game was released but the random crashes are still there.

If you do a quick search in your discord support channel, you'll find a lot of people with the same problem. You can google "legend of mana random crashes ryujinx" and get more information.

### How can the issue be reproduced?

In order to make it crash, try to beat the monster. Using special attacks (press LB, LT, RB, RT when possible) can speed up the point where the emulator crashes.

### Environment?

- Ryujinx version: All versions since game release</br>

- System Specs:
  - OS: Windows 10
  - CPU: i9-10900KF
  - RAM: 32 GB
- Applied Mods : No

### Additional context?

Save file:
[data_000_0000.zip](https://github.com/Ryujinx/Ryujinx/files/7470190/data_000_0000.zip)

Check the video if you don't know how to start the battle:

https://user-images.githubusercontent.com/93678306/140179314-be6d581c-a437-4014-b69c-d3f0e793e159.mp4

**Comment by gdkchan** [comment]
This is missing the log with the exception message, but I'm guessing it's the same guest handle leak from nvservices that is causing it to crash with the out of handles message.
