### ISSUE TITLE
Animal Crossing New Horizon v2.0 crashing on launch

### ISSUE THREAD

**Issue by NANELLON** [Ryujinx/Ryujinx#2814]
### What's the issue you encountered?

After adding the version 2.0.0 update, ryujinx starts crashing when launching the game. Previous update was 1.11.1 and that worked fine.
Just to double check I switched back to 1.11.1 and it still launches fine.
Have tried on LDN and the latest master release (1.0.7098)
I installed the same update nsp on my switch and it works fine there, so the file is fine.

### How can the issue be reproduced?

Add the 2.0.0 update (v1441792) via the normal Title Update Manager and launch the game

### Log file

[Ryujinx_1.0.7098_2021-11-05_12-57-03.log](https://github.com/Ryujinx/Ryujinx/files/7479533/Ryujinx_1.0.7098_2021-11-05_12-57-03.log)

### Environment?

- Ryujinx version: 1.0.7098</br>
- Game version: 2.0.0</br>
- System Specs:
  - OS: Windows 10 Enterprise N LTSC
  - CPU: AMD Ryzen 9 3900X
  - GPU: NVIDIA GTX 1080 Ti
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Haven't installed any Windows updates recently, and I rolled back to NVIDIA driver version 472.12 since the latest version had the issue with the game being shown upside down

**Comment by DEAD1SIDE** [comment]
Its completely Normal. You need to enable "Ignore Missing Services" to avoid crashing on boot. See: https://twitter.com/RyujinxEmu/status/1456229754605031425

**Comment by LB7333** [comment]
Hello,

I have the same issue (first time playing here) I;ve ensured the game is up to date with the latest dlc 2.0+ Key, I have also ensured that  "Ignore Missing Services" is checked and the game still crashes after the first 2-3 seconds of the first ever cutscene. 

I jave attached the log file for info, hoping someone can help  :S

[Ryujinx_1.0.7098_2021-11-07_12-49-58.log](https://github.com/Ryujinx/Ryujinx/files/7492269/Ryujinx_1.0.7098_2021-11-07_12-49-58.log)

**Comment by LB7333** [comment]
@DEAD1SIDE

**Comment by sigs** [comment]
Here's another crash log file, crash error:
[Ryujinx_1.1.1289_2024-04-21_16-49-27.log](https://github.com/Ryujinx/Ryujinx/files/15052152/Ryujinx_1.1.1289_2024-04-21_16-49-27.log)
```
Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 349
```

This was BEFORE setting the "Ignore missing services". It actually ran nicely for quite a while.

**Comment by gdkchan** [comment]
> Here's another crash log file, crash error: [Ryujinx_1.1.1289_2024-04-21_16-49-27.log](https://github.com/Ryujinx/Ryujinx/files/15052152/Ryujinx_1.1.1289_2024-04-21_16-49-27.log)
> 
> ```
> Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
>    at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 349
> ```
> 
> This was BEFORE setting the "Ignore missing services". It actually ran nicely for quite a while.

This is unrelated to this issue. You need to disable hypervisor in the emulator settings (CPU tab) to play Animal Crossing on macOS.

**Comment by sigs** [comment]
> This is unrelated to this issue. You need to disable hypervisor in the emulator settings (CPU tab) to play Animal Crossing on macOS.

Whoa nice, thanks for the quick answer! 👍
