### ISSUE TITLE
Mortal Kombat 11 problem with update!

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx#2818]
## Bug Report

when I play MK 11 with (update 1.0.26) the Scorpion spear does not appear, but in the base version (1.0.0) it appears normally! Another problem I noticed was that even using Upscale there is no resolution increase effectively! (I'm not native English!)
![Ryujinx foto 1](https://user-images.githubusercontent.com/70231770/140602469-751a6048-3c24-4659-a40b-1d03907179a5.jpg)
![Ryujinx foto 2](https://user-images.githubusercontent.com/70231770/140602470-668ddce3-8f8f-464e-a466-8979aa69f472.jpg)
![Ryujinx foto 3](https://user-images.githubusercontent.com/70231770/140602472-dd24a787-9393-4749-b3f6-35d1dbae6256.jpg)
![Ryujinx foto 4](https://user-images.githubusercontent.com/70231770/140602474-892bac1f-313b-4dc9-83e1-40a6ffca530c.jpg)
![Ryujinx foto 5](https://user-images.githubusercontent.com/70231770/140602475-f59ff209-5ad3-4f19-ad96-a0a42fdb9b45.jpg)
![Ryujinx foto 7](https://user-images.githubusercontent.com/70231770/140602478-b65670d5-a0aa-46bc-8c98-ca1e95e9e324.jpg)

- Ryujinx version: 1.0.7098
- Game version: update 1.0.26

- System Specs:
  - OS: Windows10 x64
  - CPU: Ryzen 1600x
  - GPU: GTX 1060 6GB
  - RAM: 32 GB
- Applied Mods : No
- 
[Ryujinx_1.0.7098_2021-11-06_04-58-17.log](https://github.com/Ryujinx/Ryujinx/files/7490070/Ryujinx_1.0.7098_2021-11-06_04-58-17.log)
[Ryujinx_1.0.7098_2021-11-06_04-58-47.log](https://github.com/Ryujinx/Ryujinx/files/7490072/Ryujinx_1.0.7098_2021-11-06_04-58-47.log)
[Ryujinx_1.0.7098_2021-11-06_05-02-44.log](https://github.com/Ryujinx/Ryujinx/files/7490073/Ryujinx_1.0.7098_2021-11-06_05-02-44.log)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
