### ISSUE TITLE
FATAL FRAME / PROJECT ZERO: Maiden of Black Water

### ISSUE THREAD

**Issue by jvhellraiser** [Ryujinx/Ryujinx#2819]
### Ryujinx 1.0.7098 crashes.

[ Describe the issue in detail and what you were doing beforehand. ]</br>
I load the game and press new game and when it going to start ryujinx closes..

[ Did you make any changes related to Ryujinx itself? ]</br>
that a N/A nothing has been change..

### How can the issue be reproduced?
same as before just start a new game and the game will crash soon after..

### Log file
[Ryujinx_1.0.7098_2021-11-06_12-10-51.log](https://github.com/Ryujinx/Ryujinx/files/7490846/Ryujinx_1.0.7098_2021-11-06_12-10-51.log)

### Environment?

- Ryujinx  version 1.0.7098
- Game version: 1.0.1

- System Specs:
  - OS: (Windows 11)
  - CPU: ( i7-9700k)
  - GPU: (NVIDIA RTX 2060)
  - RAM: (16GB)
- Applied Mods : [ No ]

![Fatal-Frame-Maiden-of-Black-Water-13](https://user-images.githubusercontent.com/16488761/140616744-c12bf11a-06bd-4727-9530-dbdc6d72a580.jpg)

**Comment by gdkchan** [comment]
Does it happen at native resolution?

**Comment by MarkLanders777** [comment]
This happens if you try to use resolution scaling the first time, just use native and the game will play fine (it has issues with lightning in some parts, but that's other problem)

**Comment by jvhellraiser** [comment]
Oh wao, i thought that playing at 3x resolution was ok...it loads now. thanks
check the missing button config on ryujinx in snapshot mode there no button
to configure to take photos.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
