### ISSUE TITLE
Monster Energy Supercross - The Official Videogame 3 Black face & stuttering in the audio!

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx#2825]
## Bug Report

The game has problems on the motocross rider faces (Black face) and there is a lot of stuttering in the audio.
![Monster Energy Super Cross 1](https://user-images.githubusercontent.com/70231770/140667941-c7c9f85b-72a9-4085-b0c3-520d42446968.jpg)
![Monster Energy Super Cross 2](https://user-images.githubusercontent.com/70231770/140667943-67c0c12f-f8e6-4081-bb63-7e994e525787.jpg)
![Monster Energy Super Cross 3](https://user-images.githubusercontent.com/70231770/140667945-d95c18e5-80bc-42ed-87df-ea294b4ec56f.jpg)
![Monster Energy Super Cross 4](https://user-images.githubusercontent.com/70231770/140667946-d83a6f08-32f0-4545-84f2-f27a6e04745c.jpg)

- Ryujinx version: 1.0.7098
- Game version: 1.0.0 (Base game)

- System Specs:
  - OS: Windows Windows 10 Pro (x64) 20H2
  - CPU: Ryzen 1600x
  - GPU: NVIDIA GTX 1060 6GB
  - RAM: 32GB
- Applied Mods :  No
[Ryujinx_1.0.7098_2021-11-07_20-20-15.log](https://github.com/Ryujinx/Ryujinx/files/7493490/Ryujinx_1.0.7098_2021-11-07_20-20-15.log)
[Ryujinx_1.0.7098_2021-11-07_20-21-02.log](https://github.com/Ryujinx/Ryujinx/files/7493491/Ryujinx_1.0.7098_2021-11-07_20-21-02.log)
[Ryujinx_1.0.7098_2021-11-07_21-23-46.log](https://github.com/Ryujinx/Ryujinx/files/7493492/Ryujinx_1.0.7098_2021-11-07_21-23-46.log)

**Comment by EmulationFanatic** [comment]
This appears to be resolved. If not, please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
