### ISSUE TITLE
GTA The Trilogy The Definitive Edition (No Upscale, audio out of sync and stuttering!

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx#2836]
## Bug Report

Game no upscale, audio stuttering and out of sync (when characters are talking!).
![GTA Definitive Edition 01](https://user-images.githubusercontent.com/70231770/141385199-6b334d39-b318-4c26-ba2b-7404004d4960.jpg)
![GTA Definitive Edition 02](https://user-images.githubusercontent.com/70231770/141385202-8df1804a-b846-49dc-882d-7e605934c756.jpg)
![GTA Definitive Edition 03](https://user-images.githubusercontent.com/70231770/141385203-da51b813-de23-472f-94f9-5b97769c8e9b.jpg)
![GTA Definitive Edition 04](https://user-images.githubusercontent.com/70231770/141385205-4a6e6b75-2993-4a3c-9bd1-33bb8efd6af6.jpg)
![GTA Definitive Edition 05](https://user-images.githubusercontent.com/70231770/141385206-1116c8e0-d5cc-46e9-874b-8b83cd9bdff4.jpg)

Ryujinx version: 1.0.7098

Game version: 1.0.2 (GTAIII)

System Specs:
OS: Windows Windows 10 Pro (x64) 20H2
CPU: Ryzen 1600x
GPU: NVIDIA GTX 1060 6GB
RAM: 32GB
[Ryujinx_1.0.7103_2021-11-11_21-01-29.log](https://github.com/Ryujinx/Ryujinx/files/7523927/Ryujinx_1.0.7103_2021-11-11_21-01-29.log)
[Ryujinx_1.0.7103_2021-11-11_21-03-25.log](https://github.com/Ryujinx/Ryujinx/files/7523928/Ryujinx_1.0.7103_2021-11-11_21-03-25.log)
[Ryujinx_1.0.7103_2021-11-11_21-05-17.log](https://github.com/Ryujinx/Ryujinx/files/7523929/Ryujinx_1.0.7103_2021-11-11_21-05-17.log)

**Comment by CrusadingNinja** [comment]
For the audio issues the audio backend needs to be set to SoundIO.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
