### ISSUE TITLE
Generic usb controller  right stick only moves left or right (not detecting any other direction)

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2837]
## Bug Report
it is a generic usb controller
in Ryujinx it comes up as a G-Shark gs-gp702
it is setup properly in Windows 10 (all movement and button and axis are correctly detected)
in Pool Panic
at the very start you have to aim at the red ball
all you can do is aim left or right
keeps on spamming
00:01:48.485 |S| HLE.OsThread.8 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 4294967296 ; sixAxisSensorHandle: 131075}

same as the game Flan 
can only move the character left or right using the right stick

### How can the issue be reproduced?
just start the  tutorial 

[ Include a detailed step by step process for recreating your issue. ]

[Ryujinx_1.0.7103_2021-11-12_17-07-56.log](https://github.com/Ryujinx/Ryujinx/files/7526374/Ryujinx_1.0.7103_2021-11-12_17-07-56.log)

### Environment?

- Ryujinx version: 1.0.7103
- Game version: 1.0.2

- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?
![ryujinx_capture_2021-11-12_17-20-46](https://user-images.githubusercontent.com/2696404/141443356-b8f227a3-c494-48b1-8a5e-50122a99c41b.png)
![ryujinx_capture_2021-11-12_17-20-43](https://user-images.githubusercontent.com/2696404/141443383-475ff5ac-16f8-491b-a7eb-dff4848da33b.png)

**Comment by 64ghost** [comment]
I also have such a gamepad Solved this problem

1.Open file SDL2.dll in hex-editor and find your gamepad G-Shark
2.Change  righty:a4 on righty:a3

![2c0e0d41d2056df5642fd03b81f0658d](https://user-images.githubusercontent.com/77530734/143414633-8713df55-53e6-4a6e-950a-af764b723c94.jpg)

**Comment by AntTheAlchemist** [comment]
Hopefully this will be fixed in SDL 2.0.18. Until then, you can forcibly override the mapping for that controller in the game code. I don't know the details, but it shouldn't be too difficult; easier than hex-editing the DLL. Thanks for reporting this @64ghost - I thought it was only happening to me.

**Comment by benderscruffy** [comment]
can this be reopened as #2907 was reverted please

**Comment by Dazta33** [comment]
> I also have such a gamepad Solved this problem
> 
> 1.Open file SDL2.dll in hex-editor and find your gamepad G-Shark 2.Change righty:a4 on righty:a3
> 
> ![2c0e0d41d2056df5642fd03b81f0658d](https://user-images.githubusercontent.com/77530734/143414633-8713df55-53e6-4a6e-950a-af764b723c94.jpg)

Yeh i did that and saved the dll file. Now ryujinx wont open cmon wtf man!?

**Comment by ErickVal** [comment]
> I also have such a gamepad Solved this problem
> 
> 1.Open file SDL2.dll in hex-editor and find your gamepad G-Shark 2.Change righty:a4 on righty:a3
> 
> ![2c0e0d41d2056df5642fd03b81f0658d](https://user-images.githubusercontent.com/77530734/143414633-8713df55-53e6-4a6e-950a-af764b723c94.jpg)

Thanks, this solve my problem, using SDL2.dll 2.0.22 its righty:a3 so I back it to a4 and solve.

Playing Pokemon Scarlet [0100A3D008C5C000][v0]

**Comment by Squall-Leonhart** [comment]
> Thanks, this solve my problem, using SDL2.dll 2.0.22 its righty:a3 so I back it to a4 and solve.

It should not be a4, the control only has 4 axis which are 0, 1, 2, 3.

**Comment by Tesetman** [comment]
Hello,

My question may sound stupid but, i have this controller G-Shark GS-GP702 and this problem with the R joystick.
I understood that i must change the righty:a4 into righty:a3 in the SDL2.dll, but i have just one question :
**Where can i find this SDL2.dll ??**

Thanks for your help
