### ISSUE TITLE
Shin Megami Tensei V: Flickering corruption on AMD GPUs

### ISSUE THREAD

**Issue by Oschowa** [Ryujinx/Ryujinx#2838]
### What's the issue you encountered?

In SMTV there is flickering graphics corruption happening on AMD GPUs right at the start of the game:

https://user-images.githubusercontent.com/8129300/141647865-940988a0-fd77-4b9d-a8bc-664243c52155.mp4

It happens on both Mesa drivers and amdgpu-pro (which should be similar to the windows driver).

### How can the issue be reproduced?

Start a new game in SMTV on an AMD GPU.

### Log file

[Ryujinx_1.0.7103_2021-11-13_15-34-32.log](https://github.com/Ryujinx/Ryujinx/files/7532249/Ryujinx_1.0.7103_2021-11-13_15-34-32.log)

### Environment?

- Ryujinx version: 1.0.7103</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: *Arch Linux*
  - CPU: *Ryzen 3700x*
  - GPU: *RX 6700 XT*
  - RAM: *32GB*
- Applied Mods : No

**Comment by ImperatorOfIntellectualism** [comment]
Just wanted to mention that the game started working worse with the latest update (30 fps before and 20 fps after).

**Comment by zurce** [comment]
Reporting as well that build 7104 impacted my performance significantly, before I was getting 70 to 90 fps in open world areas, now I'm barely keeping up 60 (50 to 60)

As well, the game just looks worse now, seem that there is no aliasing anymore

**Comment by riperiperi** [comment]
In what way does the game look worse?

**Comment by zurce** [comment]
> In what way does the game look worse? Do either of you have Anisotropic Filtering set to anything but Auto?

It seem with this version, the upscale resolution resets more often to 1x 

With 7103 my resolution would stay 2x for longer, since this update after 1 cutscenes it goes to 1x and only restarting emulation fixes it

**Comment by y-salnikov** [comment]
Same flickering with RX580 on linux. There is workaround, you need to disable ambient occlusion with patch from here: https://github.com/yuzu-emu/yuzu/wiki/Switch-Mods . I tested it only in that classroom, tho.

**Comment by edisionnano** [comment]
> Same flickering with RX580 on linux. There is workaround, you need to disable ambient occlusion with patch from here: https://github.com/yuzu-emu/yuzu/wiki/Switch-Mods . I tested it only in that classroom, tho.

Does it occur on vulkan too?

**Comment by y-salnikov** [comment]
On vulkan it just crush. 
```00:00:00.254 |N| Application LoadApplication: Using Firmware Version: 11.0.1
00:00:02.930 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD RADV POLARIS10 (Vulkan v1.2.195, Driver v21.3.4)
amdgpu: The CS has been rejected, see dmesg for more information (-2).
00:00:20.100 |N| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHelper.cs:line 27
   at Ryujinx.Graphics.Vulkan.FenceHolder.Wait() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHolder.cs:line 54
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 307
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.FreeConsumed(Boolean wait) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 188
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Rent() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 213
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl(String caller) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 265
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 33
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_5(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 65
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 131
Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHelper.cs:line 27
   at Ryujinx.Graphics.Vulkan.FenceHolder.Wait() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHolder.cs:line 54
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 307
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.FreeConsumed(Boolean wait) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 188
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Rent() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 213
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl(String caller) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 265
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 33
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_5(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 65
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 131
[1]    46522 abort (core dumped)  ./Ryujinx```

dmesg:

``[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -2!``

**Comment by edisionnano** [comment]
> On vulkan it just crush.
> 
> ```
> 00:00:02.930 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD RADV POLARIS10 (Vulkan v1.2.195, Driver v21.3.4)
> amdgpu: The CS has been rejected, see dmesg for more information (-2).
> 00:00:20.100 |N| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
>    at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHelper.cs:line 27
>    at Ryujinx.Graphics.Vulkan.FenceHolder.Wait() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHolder.cs:line 54
>    at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 307
>    at Ryujinx.Graphics.Vulkan.CommandBufferPool.FreeConsumed(Boolean wait) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 188
>    at Ryujinx.Graphics.Vulkan.CommandBufferPool.Rent() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 213
>    at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl(String caller) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 265
>    at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 33
>    at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_5(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 65
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 131
> Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
>    at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHelper.cs:line 27
>    at Ryujinx.Graphics.Vulkan.FenceHolder.Wait() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/FenceHolder.cs:line 54
>    at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 307
>    at Ryujinx.Graphics.Vulkan.CommandBufferPool.FreeConsumed(Boolean wait) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 188
>    at Ryujinx.Graphics.Vulkan.CommandBufferPool.Rent() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 213
>    at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl(String caller) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 265
>    at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 33
>    at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_5(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 65
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 131
> [1]    46522 abort (core dumped)  ./Ryujinx```
> 
> dmesg:
> 
> ``[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -2!``
> ```

Try using the `RADV_PERFTEST=bolist` env

**Comment by edisionnano** [comment]
> Works but still flickering without patch.

Does it only flicker on the classroom tho?

**Comment by y-salnikov** [comment]
No, it also flickering during next cutscene in tunnel.

**Comment by edisionnano** [comment]
> No, it also flickering during next cutscene in tunnel.

Does the flicker happen in the desert too?
Have you tried amdvlk?

**Comment by y-salnikov** [comment]
With AMDVLK it is much worse, not only flickering squares of different brightness (as with RADV and OpenGL), but also disappearing 3d objects even on city map.  There is no flickering in desert.

**Comment by edisionnano** [comment]
> With AMDVLK it is much worse, not only flickering squares of different brightness (as with RADV and OpenGL), but also disappearing 3d objects even on city map. There is no flickering in desert.

Can you try `RADV_PERFTEST=bolist RADV_DEBUG=nohiz`

**Comment by y-salnikov** [comment]
No difference.

**Comment by y-salnikov** [comment]
Same.
By the way, this is hard to see on the video, but the flicker has a square pattern. There are other games with the same problem to varying degrees, such as Atelier Lydie & Suelle with slight flickering and Caligula Effect 2 with total epileptic hell in some places.

**Comment by Oschowa** [comment]
On latest Ryujinx 1.1.101 the glitches still occur, but there is also something new spammed to the log:
`00:04:02.865 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25A5A (sRGB: True).`
  
Full log:
[Ryujinx_1.1.101_2022-04-10_16-23-01.log](https://github.com/Ryujinx/Ryujinx/files/8459199/Ryujinx_1.1.101_2022-04-10_16-23-01.log)

**Comment by GamerzHell9137** [comment]
> On latest Ryujinx 1.1.101 the glitches still occur, but there is also something new spammed to the log: `00:04:02.865 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25A5A (sRGB: True).`
> 
> Full log: [Ryujinx_1.1.101_2022-04-10_16-23-01.log](https://github.com/Ryujinx/Ryujinx/files/8459199/Ryujinx_1.1.101_2022-04-10_16-23-01.log)

You should probably try it on Vulkan build.

**Comment by Oschowa** [comment]
Vulkan has exactly the same glitches, both on RADV and on the proprietary vulkan driver.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Comment by Ghaleon7771** [comment]
Exactly the same happens to me... no fix yet. Seems to be an AMD driver related issue.

**Comment by HerrIrrtum** [comment]
This is still happening - actually not only on Shin Megami Tensei V, but in the exactly same style at least here:

- Bravely Default II Town View
- Triangle Strategy Camp menu (very hefty!) and some villages

This @EmulationFanatic is definitely NOT a game specific issue. And I bet it affects the SteamDeck as well (I have 3 different AMD Systems with different AMD Graphics – 5800,6600, ZEN3 mobile - it's the same everywhere).
There is umm... another emulator which doesn't have this problem at all.

**Comment by MetrosexualGarbodor** [comment]
Unless you know exactly why it happens and can open an issue detailing the root cause for every game you listed, it's still best reported in the compatibility entries for those games.

**Comment by MNi27** [comment]
> Exactly the same happens to me... no fix yet. Seems to be an AMD driver related issue.

I had this issue for select areas of my current playthrough so I created a Github acc just to say that by using the "Forced 1080p, 60 FPS, Increased LOD, Disabled Ambient Occlusion" mod found on the Yuzu Github mod page, the flickering textures seem to be fixed. Using Ryujinx 1.1.559, Vulkan, on a RX5700XT+Ryzen 5 3600.

**Comment by Ghaleon7771** [comment]
> > Exactly the same happens to me... no fix yet. Seems to be an AMD driver related issue.
> 
> I had this issue for select areas of my current playthrough so I created a Github acc just to say that by using the "Forced 1080p, 60 FPS, Increased LOD, Disabled Ambient Occlusion" mod found on the Yuzu Github mod page, the flickering textures seem to be fixed. Using Ryujinx 1.1.559, Vulkan, on a RX5700XT (22.11.2)+Ryzen 5 3600.

Yes bro, i already fixed it that way, still, since my CPU is not powerful enough for constant 60FPS i needed to use RTTS to limit it to 30FPS instead and done, at least i can play it without those annoying textures.
