### ISSUE TITLE
Ryujinx is no longer compatable with Google Drive backup process - saves get corrupted

### ISSUE THREAD

**Issue by legend800** [Ryujinx/Ryujinx#2841]
### What's the issue you encountered?

Starting about 1-2 months ago, all Ryujinx saves get corrupted if backed up by Google Drive. This does not occur with any other program/emulator except Ryu. Ryu is too sensitive to some file being touched by something else I guess. 

Only way to resolve is to copy a backup of bis > user and bis > system > save folders.

### How can the issue be reproduced?

Have Google Drive backup Ryyjinx > save folder. Launch Ryu (error in console) then attempt to launch any game or open save directory.

![2021-11-13 18_53_29-Ryujinx 1 0 0+dee2630](https://user-images.githubusercontent.com/20983844/141665762-b9b6c793-eeca-4f5f-8a44-51f90b97b288.png)

### Log file

[Ryujinx_1.0.0+dee2630_2021-11-13_18-54-23.log](https://github.com/Ryujinx/Ryujinx/files/7533106/Ryujinx_1.0.0%2Bdee2630_2021-11-13_18-54-23.log)

### Environment?

Both Ryu and Google Drive are on the latest build. 

- Ryujinx version: 1.0.X</br>
- System Specs:
Windows 10 64-bit
GeForce GTX 3070
AMD Ryzen 5900x
32GB RAM

**Comment by Thealexbarney** [comment]
Are you able to find an older build where this doesn't happen?
I've tried to reproduce this but haven't had any errors. Which directory are you syncing with Google Drive? There is no "Ryujinx/save" directory. What program are you using to sync with Google Drive? Is it Google's own "Drive for desktop" program?

**Comment by legend800** [comment]
I'll try but given the repro steps it would take quite a while. Maybe if we can narrow down to some builds that touched the R/W system around this.

My directory is portable in the root of the Ryujinx folder. ryujinx\portable\bis\user

That's why me an the other guy are bumping into this - both using Portable mode which puts it somewhere that GD keeps in sync. 

Yes it's Google's official "Google Drive for Desktop" app.

**Comment by radio5** [comment]
I'm the other guy. Please let me know if there's any information I can provide to assist. Thanks

**Comment by Thealexbarney** [comment]
Can either one of you provide a log with the FS access log turned on and the global access log mode set to 3?

**Comment by legend800** [comment]
Here's log with those settings. Started app, attempted to open save dir from right click, attempted to start a game (all failed).

[Ryujinx_1.0.0+dee2630_2021-11-13_22-20-34.log](https://github.com/Ryujinx/Ryujinx/files/7533269/Ryujinx_1.0.0%2Bdee2630_2021-11-13_22-20-34.log)

**Comment by Thealexbarney** [comment]
I suspect this may be because of a change in the Google Drive client. You can test this by trying out an old version that previously worked.
For some reason the client is setting the read-only attribute on any synced directories, causing the error.

**Comment by legend800** [comment]
Sorry, screwing around with Google Drive versions is scary. They also did a big migration from the old desktop app to the new one a few months ago. That could have been when this started - not sure. Why does this not happen on other emus - saves, cache writes, etc. are perfectly fine. This only occurs with Ryu.

What's the easiest way to fix the RO setting? I tried reverting at the 2 parent folders but it didn't fix it. 

![2021-11-14 00_02_57-save Properties](https://user-images.githubusercontent.com/20983844/141672910-85567a99-115f-4f9f-a1c4-018a9ce729ee.png)

**Comment by Thealexbarney** [comment]
I mean try an old Ryujinx version that you know works. As for other emulators, I don't know. Maybe the built-in libraries for their languages removes the flag before deleting the directory. A bit of searching brought me across an MSVC STL commit that fixed this same issue, so some c++ programs built with MSVC could have had the issue before the fix.

There's an `attrib` command on the windows command line that should be able to remove it. The command's usage text would probably tell you how

**Comment by legend800** [comment]
Confirmed it's just Google Drive setting everything to read only. If i undo this with: attrib -r -s -h /S /D  on the folder, everything is back to normal.

**Comment by Thealexbarney** [comment]
Reopening this to track working around this issue

**Comment by legend800** [comment]
The saves (bis) folder were fixed with this BUT the game still cannot load in this state. The Portable > Games dir also needs this change. 

![2021-12-23 10_28_49-Window](https://user-images.githubusercontent.com/20983844/147279924-aee83a5c-8f97-4519-9c23-a7a4b0fe6f26.png)

If I manually reset the attribs with the following cmd on that folder too, everything works perfectly:
attrib -r -s -h /S /D
