### ISSUE TITLE
Snake Pass 0100C0F0020E8000 when updated to v1.4 doesn't go in game 

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2842]
## Bug Report
when you update to v1.4 
it freezes up on title screen after you press A
it just keeps spamming in the log
0:04:59.837 |S| HLE.OsThread.15 ServiceNifm GetResult: Stubbed. 
00:04:59.837 |S| HLE.OsThread.15 ServiceNifm Submit: Stubbed. 
00:04:59.837 |S| HLE.OsThread.15 ServiceNifm GetRequestState: Stubbed. 

### What's the issue you encountered?
it will go ingame if you just load up the base version 0.1

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[Ryujinx_1.0.7104_2021-11-14_14-33-25.zip](https://github.com/Ryujinx/Ryujinx/files/7533450/Ryujinx_1.0.7104_2021-11-14_14-33-25.zip)

### Environment?

- Ryujinx version: 1.0.7104
   Game Version 1.4
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
Fixed in #2936 using the "Enable guest Internet access" option.
