### ISSUE TITLE
Super Mario Odyssey - Small but, annoying issues.

### ISSUE THREAD

**Issue by INFINITY99K** [Ryujinx/Ryujinx#2844]
## Bug Report
- In the Cascade Kingdom the fog effect near the waterfall has some artifacts while being rendered correctly (maybe due to Increasing the internal res.)

### What's the issue you encountered?

- In the Cascade Kingdom the fog effect near the waterfall has some artifacts while being rendered correctly (maybe due to Increasing the internal res.)

### How can the issue be reproduced?

- Go to the waterfall in Cascade Kingdom.

### Environment?

- Ryujinx version: 1.0.7104</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 11 with the latest patch for AMD CPUs (tested on Cinebench R23 typical score for an R7)
  - CPU: Ryzen 7 3700X.
  - GPU: Nvidia GeForce RTX 2070 SUPER.
  - RAM: 16GB Ram DDR4.
- Applied Mods : Yes:
- Disable Dynamic Res. Scaling.
- 1080p Mod.

**Comment by poudink** [comment]
Do you mean the weird static mostly transparent triangle that appears on screen? It also appears in some odyssey flying cutscenes and is not due to custom IR, since I've been getting it with default resolution.

**Comment by EmulationFanatic** [comment]
Resolved by https://github.com/Ryujinx/Ryujinx/pull/3542
