### ISSUE TITLE
真・女神轉生Ⅴ[010038d0133c2000] Crash in cutscenes

### ISSUE THREAD

**Issue by DJYDJYD** [Ryujinx/Ryujinx#2846]
## Bug Report
Crash in cutscenes

### What's the issue you encountered?
Crash in cutscenes after entering Ginza for the first time

### How can the issue be reproduced?
For me it comes up every time

### Log file
[Ryujinx_1.0.7105_2021-11-15_10-05-45.log](https://github.com/Ryujinx/Ryujinx/files/7535442/Ryujinx_1.0.7105_2021-11-15_10-05-45.log)

### Environment?
- Ryujinx version: 1.0.7105
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10
  - CPU: Intel 8700
  - GPU: GTX 1080
  - RAM: 16GB
- Applied Mods : No

### Additional context?
https://user-images.githubusercontent.com/75201147/141714936-c9c566ea-413d-49e2-87b7-b01ada7bb53d.mp4

**Comment by gdkchan** [comment]
Hash verification errors usually means that the game ROM is corrupted.

**Comment by DJYDJYD** [comment]
Thanks for the heads up! It is indeed a ROM issue
