### ISSUE TITLE
Shin Megami Tensei V: Consistent stutter and massively lowered performance looking at specific places/objects

### ISSUE THREAD

**Issue by cself99** [Ryujinx/Ryujinx#2847]
### What's the issue you encountered?

https://gfycat.com/EducatedSplendidBactrian

When looking at a specific door in this area in the game, the performance drops by 4-5x (90-100fps in the room before then struggling to hold 20fps when looking at the door) as well as FIFO shooting to a consistent 100%. Someone I've talked to said this happens more often later in the game with more specific areas as well but I'm not far enough to say yet.

### How can the issue be reproduced?

https://drive.google.com/file/d/10G9Xv28qKNDpvdIwn1Lwd2Lu8maY49Kb/view?usp=sharing

Load the save on the first slot here and turn around to look at roughly the same place I looked at in the video above.

### Log file

https://pastebin.com/a1bT7SD3

### Environment?

- Ryujinx version: 1.0.7105</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Windows 10 21H1
  - CPU: i7-6700K
  - GPU: GTX 1080 Ti w/ 472.12 driver
  - RAM: 16GB DDR4 3200MHz
- Applied Mods : None

### Additional context?

It's maybe worth mentioning that this happens on both Switch emulators on the latest version of both. Also happens on both 1.0 and 1.0.1 of the game.

**Comment by GamerzHell9137** [comment]
Are you playing on native reso?

**Comment by cself99** [comment]
I'm playing on 1x res, yeah. CPU and GPU usage both shoot up looking at that spot, but GPU doesn't hit 100% (50%-60% ish).

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
