### ISSUE TITLE
Super Mario Party (Party & Superstars) - Missing Shadows.

### ISSUE THREAD

**Issue by INFINITY99K** [Ryujinx/Ryujinx#2848]
As the title suggests, any version above 1.0.7077 causes some Shadow issues in some games that's why when was the tesselation fix was applied to Luigi's Mansion 3 caused the shadow issue as the fix was based on 1.0.7077 which already suffered from this bug I've tested versions between 1.0.7076 and 1.0.7063 and can confirm it's a regression issue.
Another instance is represented in some shadows in Super Mario Odyssey at a certain camera angle a shadow disappears maybe it's tied to how the game renders shadows or it's a bug.
[Will provide more details ASAP]
Tested on:
- R7 3700X.
- RTX 2070 Super.

**Comment by INFINITY99K** [comment]
UPDATE: More users are reporting Shadow issues in more games the most recent one being: Super Mario Party Superstars maybe, it's a bug tied to Shadow maps or it's a whole another bug.

**Comment by gdkchan** [comment]
I don't think the issues are related. Also Mario Party Superstars issue is not new, Super Mario Party already had all those issues, see https://github.com/Ryujinx/Ryujinx-Games-List/issues/908#issuecomment-813511434 or the screenshot on the main post.

**Comment by INFINITY99K** [comment]
I think you are right, both games (Party and, Superstars) are developed by the same developer (ND Cube) and the development period is only 3 years so, they probably sticked with the same engine so, any issue there would be present on this one, I'll change the name of this issue to Super Mario Party - Shadow bugs. and won't add Luigi's Mansion 3 since it has its own issue.

**Comment by INFINITY99K** [comment]
#2791

**Comment by INFINITY99K** [comment]
#2791 [Regression] Luigi's Mansion 3 - Shadow Maps not being cleared.
