### ISSUE TITLE
Mario Party Superstars - Eatsa Pizza minigame glitch.

### ISSUE THREAD

**Issue by smiglo5** [Ryujinx/Ryujinx#2851]
## Bug Report

Eatsa Pizza minigame glitch.

### What's the issue you encountered?

Sometimes one side of the pizza does not load, the base of the pizza does not load, only the toppings do, at first I thought it was just a visual glitch, but in reality if any player encounters this glitch it will be easier to complete the game because there is less pizza to eat.

### How can the issue be reproduced?

Relaunch the minigame over and over, it will happen eventually, the probability is very high that a glitch will occur

### Log file

[Ryujinx_1.0.7106_2021-11-18_09-03-22.log](https://github.com/Ryujinx/Ryujinx/files/7561104/Ryujinx_1.0.7106_2021-11-18_09-03-22.log)

### Environment?

- Ryujinx version: 1.0.7106</br>

- Game version: 1.1.0</br>

- System Specs:
  - OS: *(Windows 10)*
  - CPU: *(i7-10700)*
  - GPU: *(NVIDIA GTX 1060 6GB)*
  - RAM: *(16GB)*
- Applied Mods : No

And here is the screenshot from this glitch.

![139661038-25bf4ec3-eb13-4eec-8b3d-4887833916e7](https://user-images.githubusercontent.com/30460684/142376296-64a031a2-502e-499e-b414-784a58e83d47.jpg)

Screenshot is from LDN, but glitch is identical on 1.0.7106 mainline.

**Comment by INFINITY99K** [comment]
How was it supposed to like? I don't have the game so, please compare with how it should like.

**Comment by smiglo5** [comment]
> How was it supposed to like? I don't have the game so, please compare with how it should like.

Nope, both sides of pizza should be exactly the same, like this:
![mpc-hc64_QWOzMEEBcQ](https://user-images.githubusercontent.com/30460684/142412065-06db7e77-5973-4c06-ac7f-c741b11e0957.jpg)

Sometimes it renders correctly on Ryujinx, sometimes it's not. That's why I've mentioned opening the game over and over to encounter that glitch in reproduce section of this issue report.

**Comment by MetrosexualGarbodor** [comment]
Reloaded the minigame several times and can confirm this does not happen anymore in master.

https://user-images.githubusercontent.com/79612681/164702964-445ddb0f-8f46-4af3-b035-0e1707c7143a.mp4
