### ISSUE TITLE
Mario Party Superstars - Missing shadows from minigames.

### ISSUE THREAD

**Issue by smiglo5** [Ryujinx/Ryujinx#2852]
## Bug Report

Some shadows are missing from certain minigames.

### What's the issue you encountered?

Shadows are missing from couple of minigames in Mario Party Superstars, in this example, in a minigame Trap Ease Artist, there should be shadows below falling traps, there are none. I will list minigames with missing shadows at the end of this report

### How can the issue be reproduced?

Launch Trap Ease Artist or any minigame listed below this report.

### Log file

[Ryujinx_1.0.7106_2021-11-18_11-18-21.log](https://github.com/Ryujinx/Ryujinx/files/7561986/Ryujinx_1.0.7106_2021-11-18_11-18-21.log)

### Environment?

- Ryujinx version: 1.0.7106</br>

- Game version: 1.1.0</br>

- System Specs:
  - OS: *(Windows 10)*
  - CPU: *(i7-10700)*
  - GPU: *(NVIDIA GTX 1060 6GB)*
  - RAM: *(16GB)*
- Applied Mods : No

And here is the screenshot from this glitch.
![Ryujinx_zPCjn08YAw](https://user-images.githubusercontent.com/30460684/142397770-33ac2832-915c-445b-9c28-3a90464b4367.jpg)

And here is the screenshot how it should look like:
![123687123678](https://user-images.githubusercontent.com/30460684/142398036-7867240e-8f1a-457c-acce-c53dc095af60.jpg)

### Minigames with this issue:

Bombs Away - Bomb shadows missing
Mush Pit - Coin block shadows missing
Hammer Drop - Coin Shadows missing
Trap Ease Artest - Missing Shadows on traps (as detailed in this issue report)
Pit Boss - Player shadows missing
Burnstile - Player shadows missing

**Comment by INFINITY99K** [comment]
Did you encounter this issue in former version?

**Comment by smiglo5** [comment]
> Did you encounter this issue in former version?

In former version of Ryujinx or game itself?

**Comment by INFINITY99K** [comment]
Well, this bug was also on Super Mario Party and this game is based on the same engine that the former has used so, it had a high probability of appearing and yep, it appeared.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
