### ISSUE TITLE
[Feature Request] Mouse Panning

### ISSUE THREAD

**Issue by Colmines92** [Ryujinx/Ryujinx#2857]
#### Overview:
- Mouse Panning. So you can control the camera with the mouse, like yuzu does.

#### Smaller Details: 
- N/A

#### Nature of Request:  
- Addition
  - Mouse Panning feature

### Why would this feature be useful?
It will be very useful when playing with Keyboard & Mouse.

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #2063.
