### ISSUE TITLE
Enable and disable mods

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx#2859]
Would it be possible to enable and disable mods, in the game's own interface without having to remove them?
 That would make it much easier!
I hope I'm making the request correctly, thanks!

**Comment by CrusadingNinja** [comment]
This is already a Work In Progress PR for this [here](https://github.com/Ryujinx/Ryujinx/pull/2651).

**Comment by momoids** [comment]
Thanks for the answer!
