### ISSUE TITLE
[Kernel][Regression] Luigi's Manison 3 - Lower Performance on master 1.0.7106, kernel error getting spammed in the logs.

### ISSUE THREAD

**Issue by INFINITY99K** [Ryujinx/Ryujinx#2862]
As the title suggests this game suffers from lower performance on 1.0.7106 compared to other versions and a kernel error is getting spammed in the logs making the log size extremely big (>=6GB).
![Screenshot 2021-11-20 042613](https://user-images.githubusercontent.com/73315805/142711332-7fb63ddd-13bb-4bcc-9475-cbfeff886fc4.png)
I thought this could be fixed by (kernel: Fix sleep timing accuracy #2828) but, apparently it wasn't
BTW, the ScareScraper mode is now working for the first time on a Nintendo Switch emulator specifically the LDN build so, that's a big plus.

**Comment by gdkchan** [comment]
This is not a kernel error, you probably just enabled debug logs in the settings which prints every syscall. Just disable it.
