### ISSUE TITLE
Texture disposal hangs Ryujinx with stop emulation on certain games after playing for some time (including Xenoblade, SMTV, Pokemon)

### ISSUE THREAD

**Issue by d3xMachina** [Ryujinx/Ryujinx#2863]
### What's the issue you encountered?

Clicking on "Stop emulation" makes Ryujinx hang without closing any of its windows.

### How can the issue be reproduced?

It happens sometimes when you do the above when playing a game (I did it with Pokemon Brillant Diamond).

### Stack trace (logs don't show anything)

> Ryujinx.Graphics.GAL.dll!Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.New<Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureReleaseCommand>() Line 162   C#
> Ryujinx.Graphics.GAL.dll!Ryujinx.Graphics.GAL.Multithreading.Resources.ThreadedTexture.Release() Line 112   C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Image.Texture.DisposeTextures() Line 1486   C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Image.Texture.Dispose() Line 1516  C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Image.TextureCache.Dispose() Line 1093   C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.Destroy() Line 325 C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.GpuContext.RunDeferredActions() Line 246 C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.GpuContext.Dispose() Line 270   C#
> Ryujinx.HLE.dll!Ryujinx.HLE.Switch.DisposeGpu() Line 151 C#
> Ryujinx.dll!Ryujinx.Ui.GlRenderer.Dispose(bool disposing) Line 124   C#
> [External Code]   
> Ryujinx.dll!Ryujinx.Ui.MainWindow.SwitchToGameTable() Line 910 C#
> Ryujinx.dll!Ryujinx.Ui.MainWindow.CreateGameWindow.AnonymousMethod__89_0(object <p0>, System.EventArgs <p1>) Line 966   C#
> [External Code]   
> Ryujinx.dll!Ryujinx.Program.Main(string[] args) Line 177 C#

Ryujinx gets stuck in this loop during the texture disposal : 
```
while (_producerPtr == (_consumerPtr + QueueCount - 1) % QueueCount)
{
    // If incrementing the producer pointer would overflow, we need to wait.
    // _consumerPtr can only move forward, so there's no race to worry about here.

    Thread.Sleep(1);
}
```

### Environment?

- Ryujinx version: commit 02d786a0861b957fbd927553ac974dff473e1f4f </br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3900x
  - GPU: GTX 1060
  - RAM: 32GB
- Applied Mods : No

**Comment by GamerzHell9137** [comment]
@d3xMachina Are you on Ryujinx Discord maybe?

**Comment by StelioKantos** [comment]
This happens to me with ANY game on Windows 11 when launching games through EmulationStation (for WIndows) frontend. The app hangs on every exit no matter the game. App closes fine if not launched from frontend. Anyone know why this may be? Thank you.

**Comment by Abyss777111** [comment]
https://github.com/Ryujinx/Ryujinx/issues/4012#event-7948942677  

Emulator closes after playing - log attached

**Comment by livni** [comment]
This bug is in need of some love...

**Comment by ahegaosensei** [comment]
Not fixed, this still occurs on Win10. Seen some suggestion it might be related to NVIDIA drivers.

**Comment by cracktorio** [comment]
Still occurs for me on Super Smash Bros. Ultimate, even though it´s not happening on mario kart 8 deluxe. Maybe something with ARCropolis, although i don´t know for sure.

**Comment by WarmWelcome** [comment]
Still happening for me. Win10 latest, ryujinx latest. Nvidia gpu amd cpu. Super smash bros nsp with arcropolis.

**Comment by TesterKanok** [comment]
Ryujinx hangs when trying to close out the emulator after a long gaming session with TotK, but eventually closes. Seems to only hang for about about two minutes after a few hours long session. If played less time, it closes faster, but still hangs. Unsure why.

Version: 1.1.1291
CPU: Ryzen 5 2600
GPU: RX 6650 XT
RAM: 32GB
OS: Debian Linux 12
Kernel: 6.1.0-20-amd64
Display: Wayland
