### ISSUE TITLE
[Pokemon Brillant Diamond] Black screen and hang when entering a building

### ISSUE THREAD

**Issue by d3xMachina** [Ryujinx/Ryujinx#2865]
### What's the issue you encountered?

Sometimes when you enter a building the screen goes black and nothing happens (the emulator stays at 0 fps).
When you enter a building it save the game, maybe it's related maybe not ?

### How can the issue be reproduced?

Enter and exit a building many times and it will happens randomly. Usually a few minutes of doing it is enough to trigger it.

### Log file

[Ryujinx_1.0.7106_2021-11-21_13-27-42.log](https://github.com/Ryujinx/Ryujinx/files/7576260/Ryujinx_1.0.7106_2021-11-21_13-27-42.log)

The warnings at the end were triggered after clicking "Stop emulation". The game properly saved before hanging.

### Environment?

- Ryujinx version: 1.0.7106</br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3900X
  - GPU: GTX 1060
  - RAM: 32GB
- Applied Mods : No

**Comment by JH98x** [comment]
Same happened to me for many many times. Really annoying..
System Specs more than good enough like Post Creator's Specs

**Comment by Chilledwaffles** [comment]
same here, but otherwise the game runs great. boot times are insane tho even on SSD

**Comment by MetrosexualGarbodor** [comment]
Fixed by #3015.
