### ISSUE TITLE
[The Legend of Zelda Breath of the Wild] Water rendering issues

### ISSUE THREAD

**Issue by kitzik** [Ryujinx/Ryujinx#2869]
## Bug Report
Water rendering issues
![ryujinx_capture_2021-11-22_14-23-29](https://user-images.githubusercontent.com/5072022/142863260-95f0e317-9e39-4da7-bc61-17d164f2ac0a.png)
![ryujinx_capture_2021-11-22_15-04-49](https://user-images.githubusercontent.com/5072022/142863322-46b55099-edd5-4cd4-8d68-d3705ec9e885.png)
![ryujinx_capture_2021-11-22_14-35-12](https://user-images.githubusercontent.com/5072022/142863314-0d4ab456-b221-48d9-bac9-e4f3c3240c20.png)

### Environment?

- Ryujinx version: 1.0.7107</br>
- Game version: 1.6.0</br>
- System Specs:
  - OS: *Windows 11*
  - CPU: *i7-10700KF*
  - GPU: *NVIDIA GTX 1060 6GB*
  - RAM: *32GB*
- Applied Mods : *Yes: Disable Dynamic Resolution, Static 30FPS*

### Additional context?

Sometime it renders ok, but for the small ponds, rivers etc. water has rendering issues. Previous versions of Ryujinx are also affected. I checked Yuzu w/ OpenGL backend and it has no such problem.

**Comment by poudink** [comment]
Interestingly, Cemu has the same issue, but only when using the OpenGL renderer with GX2DrawDone disabled.

**Comment by riperiperi** [comment]
The comparisons to other emulators don't contribute anything. This issue is due to texture flush not syncing properly, and will be resolved eventually.

**Comment by saldabain** [comment]
If I recall correctly, this should be fixed now.

**Comment by gdkchan** [comment]
Fixed by #2971.
