### ISSUE TITLE
Pokémon Sword and Shield auto save soft lock

### ISSUE THREAD

**Issue by yuwenhua653** [Ryujinx/Ryujinx#2873]
## Bug Report
Pokémon Sword and Shield auto save soft lock
### What's the issue you encountered?
In Dynamax Adventures, you need to save when you start. After you start saving, the game may fall into a soft lock state, but the music is still going on.But the fps is 0.
### How can the issue be reproduced?
Enter the Dynamax Adventures of Pokémon Sword and Shield and start the adventure, there is a chance that it will happen, and some mandatory archives will also happen, such as Max Raid Battle and Digging Duo when digging treasures.
### Log file
[Ryujinx_1.0.7107_2021-11-23_12-46-37.log](https://github.com/Ryujinx/Ryujinx/files/7585878/Ryujinx_1.0.7107_2021-11-23_12-46-37.log)
### Environment?
- Ryujinx version: 1.0.7107
- Game version: 1.3.2
- System Specs:
  - OS: Windows 11
  - CPU: AMD Ryzen 7 5700U with Radeon Graphics
  - GPU: ATI Technologies Inc. AMD Radeon(TM) Graphics (3.3.14761 Compatibility Profile Context 21.30.14.04 30.0.13014.4003)
  - RAM: 16GB
- Applied Mods : No 
screenshot ：![屏幕截图 2021-11-23 124920](https://user-images.githubusercontent.com/30205483/142973602-c6391c79-9faf-48db-a007-a9052e6c9f34.png)

**Comment by Immersion95** [comment]
Same thing happening with latest build

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
