### ISSUE TITLE
Pokémon Shining Pearl - Atmosphere Cheat-Codes: Keypress Conditional Block not working

### ISSUE THREAD

**Issue by David-XY** [Ryujinx/Ryujinx#2879]
### What's the issue you encountered?

Whilst trying out several Cheat-codes in Pokémon Shining Pearl I noticed that those using Keypress Conditions didn't work.</br>

Title: 010018E011D92000
Version: 1.1.1
Build Id: 3C70CAE153DF0B4F8A7B24C60FD8D0E700000000000000000000000000000000

### How can the issue be reproduced?

Example cheat-code using a Keypress Condition, button 'L' is supposed to be held for it to work:
```
[Shiny Pokemon (L)]
040A0000 02469BF8 54000720
040A0000 02469C08 54000820
80000040
040A0000 02469BF8 14000045
040A0000 02469C08 14000041
20000000
```
Trigger encounter whilst holding L
-> Doesn't work as it would on the console.

However if I simply remove the Condition like this:
```
[Shiny Pokemon Encounter]
040A0000 02469BF8 14000045
040A0000 02469C08 14000041
```
Trigger encounter
-> Works as expected but is turned on permanently.

For convenience:
[3C70CAE153DF0B4F.txt](https://github.com/Ryujinx/Ryujinx/files/7602307/3C70CAE153DF0B4F.txt)

Trying other examples yielded the same result as above but haven't tested it on other games.
This applies to both Docked and Handheld mode, tried other buttons too.

Controller-Settings just in case:
![Controller_Settings](https://user-images.githubusercontent.com/45044824/143430835-dde947c8-4a05-4320-a82f-52f98e305dd7.png)

### Log file

N/A</br>

### Environment?

- Ryujinx version: 1.0.7108</br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3600
  - GPU: NVIDIA RTX 2070
  - RAM: 16GB
- Applied Mods : Yes, cheat-codes mentioned above.

### Additional context?

N/A</br>

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.
