### ISSUE TITLE
Cannot use controller on Metroid Dread

### ISSUE THREAD

**Issue by wattunya** [Ryujinx/Ryujinx#2884]
### What's the issue you encountered?
I cannot use ps4 controller on Metroid Dread and the warnings pop up.  
I cab use controller on other games.
<img width="323" alt="キャプチャ" src="https://user-images.githubusercontent.com/13589068/143684111-0a009dd2-0d33-43d5-99f8-cbe7ff2d4a6c.PNG">

### How can the issue be reproduced?
When I use controller on Metroid Dread and press button, the warning pops up and if I delete it the warming come back again.

### Log file

[Ryujinx_1.0.7108_2021-11-27_22-40-37.log](https://github.com/Ryujinx/Ryujinx/files/7611829/Ryujinx_1.0.7108_2021-11-27_22-40-37.log)

### Environment?

- Ryujinx version: 1.0.7108</br>

- Game version: 1.0.0</br>

- Controller Spec:
DualShock 4
it is recognized by DS4windows.
https://ryochan7.github.io/ds4windows-site/

**Comment by Shahil-Ayato** [comment]
This seems more like a support issue please join our discord to troubleshoot issues like this and if it can’t be resolved then submit an issue report.

**Comment by wattunya** [comment]
OK. I am so sorry that  I asked my question here.
I will join your discord.
