### ISSUE TITLE
SharpZipLib throws exception on Mario Tennis Aces after .net 6.0 migration

### ISSUE THREAD

**Issue by XGSleepWalker** [Ryujinx/Ryujinx#2891]
### What's the issue you encountered?

Loading Mario Tennis Aces after the .net 6.0 migration leads to this error 
![imagem](https://user-images.githubusercontent.com/5632804/144117314-c1895221-03c6-4411-9907-3ca0090a7aae.png)

### How can the issue be reproduced?

Load Mario Tennis Aces. Error should occur immediately, and the error log is not flushed to file, only flashes briefly in the console.

### Log file

The exceptions are not flushed to the log file, it doesn't contain any relevant information.

### Environment?

- Ryujinx version: 1.0.7113</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *Ryzen 9 5900X*
  - GPU: *NVIDIA RTX 3080*
  - RAM: *32GB*
- Applied Mods : No

**Comment by AcK77** [comment]
Your shader cache is corrupted. It’s not related to the .NET 6.0 upgrade. Just purge it and generate a new one and you issue will be fix!
