### ISSUE TITLE
Severe stuttering when running via HDD.

### ISSUE THREAD

**Issue by INFINITY99K** [Ryujinx/Ryujinx#2894]
I think that the way that Ryujinx loads in assets is a bit inefficient as when the emulator tries to load stuff off a normal HDD there will be some severe stuttering until Ryujinx loads in those assets well, How did I know this? I have an external hard drive that flashes light when reading or writing and I thought that it would be fun to see if there's any difference between running off an SSD or a HDD and the difference was massive in a game like SSBU or SMO as both games need to load-in stuff quickly off the hard drive in both games you'd need to wait between 15-30 seconds I didn't include the logs since, both of them are basically identical in logs apart from difference in assets loading time (though I would include them if you wish to). Final thing to note here that doesn't happen on other programs running of an HDD so, what do I suggest? I suggest off-loading some of the assets to the ram while keeping some of the less important on the hard drive and save the name of those important assets in some sort of a cache so, the game on boot would off-load those assets to the ram some stuff like the menus in SSBU would run way better on HDD via this solution and I suggest adding min. requirements so, people would know what they are getting into I know this would increase ram utilization massively (and maybe even 16GB won't be enough anymore! btw, I am not even a developer ( yet;) ) ) but, I'd like to see how would you work around this!

**Comment by Mou-Ikkai** [comment]
There... Is no difference. The difference you "felt" in smash was most likely the TTC, since we don't have a PR to cache it yet!

**Comment by INFINITY99K** [comment]
Well, I am going to record video footage comparing the game running on an SSD and a HDD, Ok?

**Comment by INFINITY99K** [comment]
Here you go SSD vs HDD check it for yourself both were performed after a clean boot in Windows.
SSD:

https://user-images.githubusercontent.com/73315805/144509175-d559b019-c89a-4275-8b14-6ccde7130975.mp4

Perfectly fine right?
Now let's jump over to the HDD.
HDD:

https://user-images.githubusercontent.com/73315805/144509264-a29b20a2-198d-4e15-81e0-98e7e012eabd.mp4

As you can see the music when you get in the menu is chugging and the framerate is abysmal then post second 40 (after my hard drive stops blinking) you'll see that everything is normal.
If you want more evidence I will record an entire walkthrough starting from when it boots till I go to a match (but, get ready cause am terrible).
Now why probably didn't see that? simple, cause you booted from an ssd then jumped to the game on a HDD on the same boot so, any cached memory will be used and therefore, your footage won't be as chuggy as mine and will be perfectly fine.

**Comment by Leischii** [comment]
My shaders are also on an hdd and my first smash boot always looks exactly like in the hhd example video. Didnt test shaders on ssd in a while but I remember this being better in the past so it could be due to moving the shaders to the hhd some time ago.

**Comment by riperiperi** [comment]
I can't say that your suggestion to preload everything into RAM makes any sense at all. The real console doesn't do that and the game runs fine on there, on much slower storage. My bet is that the FS service calls are blocking or have some other cost that they shouldn't (should yield while loading off HDD).

**Comment by riperiperi** [comment]
> My shaders are also on an hdd and my first smash boot always looks exactly like in the hhd example video. Didnt test shaders on ssd in a while but I remember this being better in the past so it could be due to moving the shaders to the hhd some time ago.

I don't think this example is comparing where the shaders are, it's comparing where the game is. The shaders are fully preloaded before the game starts, so during gameplay there will be no difference if the shaders are in a different location.

**Comment by INFINITY99K** [comment]
> I can't say that your suggestion to preload everything into RAM makes any sense at all. The real console doesn't do that and the game runs fine on there, on much slower storage. My bet is that the FS service calls are blocking or have some other cost that they shouldn't (should yield while loading off HDD).

I didn't say off-load everything to ram I said that assets that  are constant after multiple runs their names could be registered in a file and when the emulator is booting the game the emulator loads those assets into the ram before the game eventually runs and yes, I know that off-loading everything to ram doesn't make a lick of sense.

**Comment by INFINITY99K** [comment]
Here is sth intersesting, when using an update or a dlc that's placed on an HDD it behaves the same way I am going check the logs and upload them.

**Comment by riperiperi** [comment]
Can you try with this PR?

https://github.com/Ryujinx/Ryujinx/pull/3142

**Comment by INFINITY99K** [comment]
I'll test it on a couple of games and I'll share my findings as I finish testing.

**Comment by INFINITY99K** [comment]
After testing SSBU and Marvel Ultimate Alliance 3 I can confirm that it has fixed the severe stuttering issues and shortened loading times slightly.
I'll post a video demonstrating this in the next week or so and will update you again.
