### ISSUE TITLE
Problem with gamepad G-Shark GS-GP702

### ISSUE THREAD

**Issue by 64ghost** [Ryujinx/Ryujinx#2905]
Problem:
not working right stick( up and down) on gamepad G-Shark GS-GP702
https://github.com/Ryujinx/Ryujinx/issues/2837

Solution:
Please update SDL2.dll to 2.0.18.0. This will solve the problem with gamepad

**Comment by benderscruffy** [comment]
can this be reopened as #2907 was reverted please

**Comment by JoewAlabel** [comment]
You can get the new DLL here: [https://www.libsdl.org/index.php](https://www.libsdl.org/index.php)
Just click at Download.

**Comment by GamerTillDeathIsAlive** [comment]
I don"t know where to paste dll file

**Comment by MutantAura** [comment]
you dont need to download any dll files. this issue was fixed in https://github.com/Ryujinx/Ryujinx/pull/3317
As of Ryujinx version 1.1.123 the gamepad should work fine.

**Comment by GamerTillDeathIsAlive** [comment]
Plz tell me how to update ryujinx version plz plz plz

**Comment by GamerTillDeathIsAlive** [comment]
- [ ] @@@#****

**Comment by Dazta33** [comment]
> You can get the new DLL here: https://www.libsdl.org/index.php Just click at Download.

Does not work. new dll  has not changed anything

**Comment by Dazta33** [comment]
> you dont need to download any dll files. this issue was fixed in #3317 As of Ryujinx version 1.1.123 the gamepad should work fine.

Nope, Still dont work

**Comment by HandreG** [comment]
Where is the file for editing?
