### ISSUE TITLE
Breath Of the Wild New opcode

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#291]
i have tested PR #278 and tested BOTW again Coming up with a New opcode https://gist.github.com/ReaperOfSouls1909/ecb6f02d3f1269b19901ec016978ca7b

**Comment by ReaperOfSouls1909** [comment]
after adding in #245 https://gist.github.com/ReaperOfSouls1909/63ef1ffdcebe5630a3e1eaa0f1103862 a new error comes up Unhandled Exception: System.NotImplementedException: nfp:user IUser: 2 which im guessing can be stubbed since part of it already was before with pull #133

**Comment by ReaperOfSouls1909** [comment]
last update Stubbing nfp:user IUser: 2 got botw to boot with fps for half a second and now it freezes

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/86
