### ISSUE TITLE
Xbox Series S/X controller unresponsive

### ISSUE THREAD

**Issue by ufoman** [Ryujinx/Ryujinx#2912]
What's the issue you encountered?
Xbox Series X/S controller isn't working at all with Ryujinx 1.0.7116

How can the issue be reproduced?
Connect Xbox Series X/S controller (the one with central share button) to PC (I've only tested wireless connection with official adapter). Try to remap controls or load and use defaults.

Log file
no log collected

Environment?
Ryujinx version: 1.0.7116
Game version: Issue not specific to a game
[ Replace X's with the game version at time of crash. ]
System Specs:
OS: Windows 11
CPU: i7-9700K
GPU: NVIDIA RTX 3070
RAM: 16GB
Applied Mods : No

Additional context?
I have performed some investigation using the below app: https://generalarcade.com/gamepadtool/ and SDL2.dll files downloaded from libsdl.org. It seems that the controller started to be recognized by name "Xbox Series X controller" from version 2.0.14 onwards. Since that version, input from the controller is not recognized at all. Until version 2.0.12, controller is recognized under generic name "XInput Controller" and inputs are being recognized as expected.

**Comment by ufoman** [comment]
Retested with 7144. Controller inputs are detected now.

**Comment by MetrosexualGarbodor** [comment]
Closing as this doesn't seem to be an issue currently.
