### ISSUE TITLE
Tokyo Mirage Sessions #FE: Desyncs in scripted cutscenes

### ISSUE THREAD

**Issue by Oschowa** [Ryujinx/Ryujinx#2914]
### What's the issue you encountered?

In many scripted cutscenes in the game Tokyo Mirage Sessions FE Encore [0100A9400C9C2000] there are desyncs between the character motion, the subtitles and the audio occurring. I tried all 3 Memory Manager Modes, but they don't affect the issue.
  

### How can the issue be reproduced?

Load the following savegame and walk a few step forward, the following cutscene will desync in obvious ways.

[TokyoMirageSave.zip](https://github.com/Ryujinx/Ryujinx/files/7668163/TokyoMirageSave.zip)
  
### Log file

[Ryujinx_1.0.7116_2021-12-07_13-01-13.log](https://github.com/Ryujinx/Ryujinx/files/7668170/Ryujinx_1.0.7116_2021-12-07_13-01-13.log)
  

### Environment?

- Ryujinx version: 1.0.7116</br>
- Game version:1.0.0</br>
- System Specs:
  - OS: *Arch LInux*
  - CPU: *Ryzen 3700x*
  - GPU: *RX 6700 XT (Mesa/radeonsi git)*
  - RAM: *32GB*
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Resolved by https://github.com/Ryujinx/Ryujinx/pull/3642
