### ISSUE TITLE
Pokemon Brilliant Diamond crashes in Double Fights

### ISSUE THREAD

**Issue by HiImCasul** [Ryujinx/Ryujinx#2922]
### What's the issue you encountered?
.
Everytime I go into a Doublefight the game crashes after the second person approaches me.
I didn't have any issues with it in the "early game".
But i Updated from 1.0.0 to 1.1.2 and im not sure if thats the cause.

### How can the issue be reproduced?

I can reproduce it if i just go into a double fight.
Talking with one person to not get approached by the second one works just fine.
I'm not sure if it helps, but I'm in the dueling Zone in Stark Mountain.

[ Include a detailed step by step process for recreating your issue. ]

### Log file
[Ryujinx_1.0.7125_2021-12-15_23-34-00.log](https://github.com/Ryujinx/Ryujinx/files/7723256/Ryujinx_1.0.7125_2021-12-15_23-34-00.log)

### Environment?

- Ryujinx version: 1.07125</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.1.2</br>

[ Replace X's with the game version at time of crash. ]
- System Specs:
OS: Windows 10
CPU: i7 4930k@4.4Ghz
GPU: AMD 6900XT@Stock
RAM: 32GB@1600CL9
MB:   ASUS P9X79Pro
Latest Drivers.
- Applied Mods : [No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]
It doesn't matter if i extend DRAM to 6GB, Enable Shader Chache, Change the Memory Manager Mode or adjist the Graphics Settings.

**Comment by MetrosexualGarbodor** [comment]
A save file would be helpful since you're describing a late game zone.

**Comment by HiImCasul** [comment]
No Problemo, i zipped up my save folder.
I only played Pokemon so.
[save.zip](https://github.com/Ryujinx/Ryujinx/files/8542768/save.zip)
.

**Comment by MetrosexualGarbodor** [comment]
Can confirm the issue still exists on 1.1.106. 

https://user-images.githubusercontent.com/79612681/164771855-e273f706-8c79-414c-8bbe-8d04dac51948.mp4

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
