### ISSUE TITLE
Pokemon Brilliant Diamond didn't save

### ISSUE THREAD

**Issue by ayaya-project** [Ryujinx/Ryujinx#2923]
## Bug Report

I saved in game but the emulator didn't save.

### What's the issue you encountered?

I was breeding pokemons for 6 hours , finally got a perfect IVs, I saved immediately, closed the emulator ( which hangs all the time and i have to close the console to close it ) when i came back my save file wasn't updated but it was 6 hrs prior this event.
I lost all my progress to this.
I updated to latest version when i turned on ryuujinx so i wonder if there are some issues with the update.
I also created folders to backup my save files inside the ryuujinx save file directory, can that cause any issues?
Like everytime i hit a big milestone i tend to make a new folder and copy paste the .bin files inside those folders
![explorer_2021-12-16_07-43-35](https://user-images.githubusercontent.com/49101884/146321627-bbb98ce9-2d99-4c17-91f4-da15f056d7d4.png)

i played over 140 hrs and this is the first time this has happened, and i had just updated so i wonder if that was the cause.
any way i can avoid the emulator hanging when closing it? is it safer to close ryuujinx by closing the console window?

**Comment by d3xMachina** [comment]
Probably related : #2757

**Comment by AcK77** [comment]
Is this still happen on the latest Ryujinx version (some changes have been made to the FS service) ?

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.

**Comment by marysaka** [comment]
Closing as stale.
