### ISSUE TITLE
Animal Crossing: New Horizons gets freeze when I enter any building

### ISSUE THREAD

**Issue by palcamora** [Ryujinx/Ryujinx#2924]
### What's the issue you encountered?

When I enter into a building, the loading page gets freeze for ever.
I start a new game, with the save file of the patreon page.

### How can the issue be reproduced?

Enter any building causes freeze

### Log file
![image](https://user-images.githubusercontent.com/2305629/146454872-6ca70ce3-f47c-422d-9de1-15cd015cb70e.png)
The txt file have the same output
### Environment?

- Ryujinx version: 1.0.7125</br>

- Game version: 1.0.0 and 1.10.0 (same problem)</br>

- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 5600x
  - GPU: RX 5700xt
  - RAM: 32GB
- Applied Mods : No

**Comment by MetrosexualGarbodor** [comment]
This happens because the OpenGL drivers for AMD on Windows are too slow, so it should not occur on Vulkan or on Linux.
