### ISSUE TITLE
App fails to open with error message: "The procedure entry point inflateValidate could not be located in the DLL <path>\libpng16-16.dll"

### ISSUE THREAD

**Issue by polyh3dron** [Ryujinx/Ryujinx#2931]
Upon attempting to launch Ryujinx, I receive an error dialog saying "The procedure entry point inflateValidate could not be located in the DLL <Ryujinx path>bin\libpng16-16.dll". Any ideas on a workaround for this?

**Comment by AcK77** [comment]
Move the bin folder content in the same folder as Ryujinx.exe.
It seems to be an issue of GTK for an unknown reason...
