### ISSUE TITLE
Animal Crossing: New Horizons suddenly crash and exit

### ISSUE THREAD

**Issue by wmdhs12138** [Ryujinx/Ryujinx#2934]
## Bug Report

Animal Crossing: New Horizons suddenly crash and exit.

### What's the issue you encountered?

Crash.

### How can the issue be reproduced?

Go ingame, just run around and few minutes it freeze then crash.

### Log file

[Ryujinx_1.0.7135_2021-12-25_14-59-15.log](https://github.com/Ryujinx/Ryujinx/files/7775576/Ryujinx_1.0.7135_2021-12-25_14-59-15.log)

### Environment?

- Ryujinx version: 1.0.7135</br>
- Game version: 2.0.4</br>
- System Specs:
  - OS: Windows11 21H2
  - CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  - GPU: NVIDIA GTX 1660Ti Mobile
  - RAM: 16GB
- Applied Mods : No

**Comment by OpTicGhost01** [comment]
did you find a fix for this ??

**Comment by wmdhs12138** [comment]
> did you find a fix for this ?? i'm currently having an issue click on animal crossing it opens for like a few seconds then emulator closes completely 

I read a few crash logs, they are all the same bug. I don't understand the code, I don't know if this bug is difficult to fix.

**Comment by twilightsophie** [comment]
I'm not sure if I'm allowed to recommend Yuzu but I found I could start a save in Yuzu and then move the save files to Ryujinx (use the menu option to go to Save Data once to generate folders) and it would play fine. LDN connection between my laptop and my computer both running Ryujinx works well too, so you can start multiple islands to get collectibles.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
