### ISSUE TITLE
[Regression] Menus in "Zombies Ate My Neighbors and Ghoul Patrol" broken after release 7128

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx#2945]
After master release 7128 (PR #2926), Zombies Ate My Neighbors and Ghoul Patrol's menus suffer from major graphical issues.

Before:
![image](https://user-images.githubusercontent.com/65521430/147422402-f0dd7edc-c423-486d-aa7f-7ab129c1f8be.png)
After:
![image](https://user-images.githubusercontent.com/65521430/147422639-8adbbaf7-27d6-4070-aee8-7ed5242e645f.png)

### How can the issue be reproduced?

Run the game on any Ryujinx build after PR #2926 was merged.

### Log file

[ZAMN&GPmaster.log](https://github.com/Ryujinx/Ryujinx/files/7777731/ZAMN.GP.log)

### Environment?

- Ryujinx version: 1.0.7140</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Microsoft Windows 10.0.19043 (X64)
  - CPU: AMD Ryzen 5 2600
  - GPU: NVIDIA GeForce 1660 SUPER
  - RAM: 16GB

**Comment by mooock** [comment]
Did a test on Intel I9 7900x and RTX 3090/windows 11 for version 1.0.7152 had same issue and confirm it worked for 1.0.7122

**Comment by gdkchan** [comment]
Fixed by #3328.
