### ISSUE TITLE
(Regression)Pinball FX3 - 0100DB7003828000 black screen with sound when updating from 1.0.0 to 1.0.3 and higher 

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2968]
## Bug Report

using Ryjinx 1.1.129
it has gone back to black screen with  scoreboard and playing sound using OpenGL

### What's the issue you encountered?
when you update from 1.0.0 to 1.0.3 and higher
just a black screen with sound
if you just load 1.0.0 no problems at all
but you need to update to play newer tables

![ryujinx_capture_2022-05-16_17-18-18](https://user-images.githubusercontent.com/2696404/168567391-e191b42c-5804-49a6-bb70-1de9b9821442.png)

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.1.129
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.11.0
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. Radeon RX 580)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by ItaMiyuki** [comment]
Game renders correctly on the latest ryujinx version with the latest game update applied.
![image](https://user-images.githubusercontent.com/107776035/174557147-1b38d5e7-b58d-4255-8daf-3e1626354725.png)
