### ISSUE TITLE
Rush Rally Origins [0100ea00147a8000] rainbow track and backgrounds

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2969]
## Bug Report

00:01:44.134 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: glCompressedTexSubImage2D has generated an error (GL_INVALID_OPERATION)
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Debugger.cs:line 66
   at Ryujinx.Graphics.OpenGL.Image.TextureView.ReadFrom(IntPtr data, Int32 size) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Image\TextureView.cs:line 462
   at Ryujinx.Graphics.OpenGL.Image.TextureView.SetData(ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Image\TextureView.cs:line 268
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_28(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in C:\projects\ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 117
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in C:\projects\ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131

### What's the issue you encountered?

choose any car and track then play
parts of the track are coloured rainbow and some backgrounds aswell
![ryujinx_capture_2022-01-03_17-41-56](https://user-images.githubusercontent.com/2696404/147920009-963ea6f0-8ef5-4399-831a-6307e83f3974.png)
![ryujinx_capture_2022-01-03_17-42-06](https://user-images.githubusercontent.com/2696404/147920080-f3968483-cf5b-4a83-9435-934fd99e9560.png)
![ryujinx_capture_2022-01-03_17-42-19](https://user-images.githubusercontent.com/2696404/147920110-778361bc-3265-46d1-afd1-024ed77217a0.png)
![ryujinx_capture_2022-01-03_18-05-25](https://user-images.githubusercontent.com/2696404/147920159-e15d6e3d-98d9-407c-8c29-345ba2204031.png)
![ryujinx_capture_2022-01-03_18-05-32](https://user-images.githubusercontent.com/2696404/147920194-4c38fe84-fccd-4baa-8bb8-1e1ae1fa09a3.png)
![ryujinx_capture_2022-01-03_18-15-40](https://user-images.githubusercontent.com/2696404/147920222-7d1940ed-8954-4d4e-a832-77ae93894dcf.png)

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

[Ryujinx_1.0.7154_2022-01-03_18-09-18.zip](https://github.com/Ryujinx/Ryujinx/files/7801386/Ryujinx_1.0.7154_2022-01-03_18-09-18.zip)

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.7154
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. Radeon RX 580*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MetrosexualGarbodor** [comment]
Does this occur on current master or on the Vulkan backend?

**Comment by benderscruffy** [comment]
still occurs on the master
On Vulkan track is missing

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
