### ISSUE TITLE
Rad Rodgers Radical Edition Cache/DSP Issue when game runs second time

### ISSUE THREAD

**Issue by mooock** [Ryujinx/Ryujinx#2973]
### What's the issue you encountered?
First time the game is started, everything works fine. second time its unable to boot at all, if a cache folder has been generated. From the log its mention that it's an issue with audio. I am able to fix the issue with one of two steps
1. delete the cache folder "cpu"
2. Change the sound engine to other than SDL2, or OpenAL

```
00:00:13.863 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.Command.DeviceSinkCommand.Process(CommandList context) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DeviceSinkCommand.cs:line 78
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 142
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 225
```

### How can the issue be reproduced?
Start the game once more after the cache has been generated, going into the title screen should be sufficient, cache folder should be 010000600cd54000

### Log file
[Ryujinx_1.0.7158_2022-01-04_20-51-18.log](https://github.com/Ryujinx/Ryujinx/files/7810072/Ryujinx_1.0.7158_2022-01-04_20-51-18.log)

### Environment?

- Ryujinx version: 1.0.7158</br>
- Game version: 1.0</br>
- System Specs:
  - OS: Windows 11
  - CPU: I9 7900X
  - GPU: RTX 3090
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Running portable installations, and newest switch firmware. and did try different settings. so be sure it was not graphic related.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
