### ISSUE TITLE
SslService, ISslConnection: 10 is not implemented

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2977]
## Bug Report

turn on Enable guest internet access 
load the game Evolution Board Game - 01006A800FA22000
Ryujinx/Ryujinx-Games-List/issues/3250
crashes out 

### What's the issue you encountered?
00:01:38.890 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ssl.SslService.ISslConnection: 10

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

[Ryujinx_1.0.7159_2022-01-05_15-41-23.zip](https://github.com/Ryujinx/Ryujinx/files/7812973/Ryujinx_1.0.7159_2022-01-05_15-41-23.zip)

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.7159
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
Fixed in #2961
