### ISSUE TITLE
Gems of War [0100bd800986e000] error (problem opening your account)

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2978]
## Bug Report
enable guest internet access
load game
after the title screen it keeps on coming up with the error screen

![ryujinx_capture_2022-01-05_16-03-41](https://user-images.githubusercontent.com/2696404/148182410-6f00aeba-a653-445f-a1b9-53b212d1a353.png)

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

[Ryujinx_1.0.7159_2022-01-05_16-02-14.zip](https://github.com/Ryujinx/Ryujinx/files/7813104/Ryujinx_1.0.7159_2022-01-05_16-02-14.zip)

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.7159
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MutantAura** [comment]
This should likely be opened as a compatibility report instead of an issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues
There is not currently one open for this game.

For issues affecting online it would also be helpful to test hardware to see what the usual outcome is in airplane mode vs connected :)
