### ISSUE TITLE
South Park The Stick Of Truth [010095300b6a4000] no longer boots up

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#2982]
## Bug Report

game no longer boots up
00:00:01.119 |E| Loader LoadNca: No ExeFS found in NCA

00:00:22.608 |E| GUI.NcaSectionExtractorThread Application : Unhandled exception caught: LibHac.MissingKeyException: Missing NCA title key.
Key Type: Title
Key Name: 010095300B6A40000000000000000005
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedTitleKey()
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.Ui.Widgets.GameTableContextMenu.<>c__DisplayClass14_0.<ExtractSection>b__0() in C:\projects\ryujinx\Ryujinx\Ui\Widgets\GameTableContextMenu.cs:line 287
 

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

[Ryujinx_1.0.7159_2022-01-08_13-18-03.log](https://github.com/Ryujinx/Ryujinx/files/7832599/Ryujinx_1.0.7159_2022-01-08_13-18-03.log)
[Ryujinx_1.0.7159_2022-01-08_13-21-46.log](https://github.com/Ryujinx/Ryujinx/files/7832600/Ryujinx_1.0.7159_2022-01-08_13-21-46.log)

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.7159
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by jduncanator** [comment]
Do you have the title key for your NSP in the `title.keys` file?
