### ISSUE TITLE
Bravely Default 2 graphical glitch

### ISSUE THREAD

**Issue by kaoriyae** [Ryujinx/Ryujinx#2995]
## Bug Report

Bravely Default 2 graphical glitch

### What's the issue you encountered?

Many graphical glitch, particularly when accessing menu, having encountering this error on build 1.0.7167 and up (latest build 1.0.7164 doesn't solved it), was fine in 1.0.7159 and down.

Trying to clearing all the cache doesn't work, the glitch appears 90% of the times when opening menu, sometimes glitching the overworld graphics and had to restart. This bug doesn't make the game crash though, just very annoying graphical glitch.

![ryujinx_capture_2022-01-11_13-48-45](https://user-images.githubusercontent.com/54153116/148988616-0c9a4572-03d8-4121-bc15-7b78e8a166c3.png)

![ryujinx_capture_2022-01-11_13-49-23](https://user-images.githubusercontent.com/54153116/148988637-c2e98210-6e64-4941-962a-e49846272a39.png)

### How can the issue be reproduced?

Just go to menu, most of the time the graphics will be glitched. Sometimes the glitch spread to main game screen and the game had to be restarted.

### Log file

[Ryujinx_1.0.7164_2022-01-11_14-16-04.log](https://github.com/Ryujinx/Ryujinx/files/7848588/Ryujinx_1.0.7164_2022-01-11_14-16-04.log)

### Environment?

- Ryujinx version: 1.0.7164</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10.0.19044*
  - CPU: *i7-6700*
  - GPU: *NVIDIA GeForce GTX 1060 6GB*
  - RAM: *16GB*
- Applied Mods : [ No ]

**Comment by gdkchan** [comment]
You can just paste the screenshots and attach the log here directly. No need to put them on a github repository. Btw, they are not accessible right now.

**Comment by kaoriyae** [comment]
Updated the post, sorry I'm noob with this lol. Also the problem still persist on build 1.0.7167. Thank you.

**Comment by MetrosexualGarbodor** [comment]
Does the issue still persist on current master? If it does, it might need #2932.

**Comment by kaoriyae** [comment]
Hello, I just loaded the game again, and I still encounter graphical glitches whether in overworld and in dungeon. The graphical glitch in the town seems receding but maybe it's just my luck. Overall I don't really see any improvements because I can still easily spot many graphical glitches.

**Comment by MarkLanders777** [comment]
> Hello, I just loaded the game again, and I still encounter graphical glitches whether in overworld and in dungeon. The graphical glitch in the town seems receding but maybe it's just my luck. Overall I don't really see any improvements because I can still easily spot many graphical glitches.

Did you download the lastest version of Ryujinx 1.1.106?

**Comment by kaoriyae** [comment]
> Did you try the lastest version of Ryujinx 1.1.106?
Yes. Trying to delete and rebuild cache, same results. There are still glitches everywhere everywhere (overworld, dungeon, menu, battle etc.) I don't have much time to test so I hope someone can help. The glitches are prominent so I think everyone can easily test this.
![glitch01_compressed](https://user-images.githubusercontent.com/54153116/165196419-b2946c42-241c-4886-80ac-852904d7e460.jpg)
![glitch02_compressed](https://user-images.githubusercontent.com/54153116/165196427-c273d037-7117-45a8-8119-447ceec5e822.jpg)
![glitch03_compressed](https://user-images.githubusercontent.com/54153116/165196430-76c49a6e-72ce-4302-8385-b4168920af68.jpg)

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
