### ISSUE TITLE
Beyond a Steel Sky gfx issue.

### ISSUE THREAD

**Issue by Dime333** [Ryujinx/Ryujinx#3003]
### What's the issue you encountered?

Some parts of the environment are not rendered.

Screenshot using Ryujinx.
![ryujinxbug](https://user-images.githubusercontent.com/42482063/149760570-8dfa7d2e-b368-4676-8b19-99361ea06b00.png)

Screenshot using Yuzu.
<img width="1920" alt="yuzuright" src="https://user-images.githubusercontent.com/42482063/149760699-f28b09c4-0c0f-48d1-b450-c6229f4bb43f.png">

### How can the issue be reproduced?

Just use the included save file and load the game.

### Log file

[Ryujinx_1.0.7175_2022-01-17_13-00-09.log](https://github.com/Ryujinx/Ryujinx/files/7881676/Ryujinx_1.0.7175_2022-01-17_13-00-09.log)

### Environment?

- Ryujinx version: 1.0.7175

- Game version: 1.0.29070 (But also happens without the update.)

- System Specs:
  - OS: Windows 10
  - CPU: i7-7700K
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Save file.
[save.zip](https://github.com/Ryujinx/Ryujinx/files/7881463/save.zip)

**Comment by Dime333** [comment]
This issue does not happen when using vulkan.

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
