### ISSUE TITLE
(Regression) Turok - 010085500D5F6000 missing most graphics

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#3008]
## Bug Report

load the game and most graphics are missing or corrupt

![ryujinx_capture_2022-01-19_15-05-15](https://user-images.githubusercontent.com/2696404/150081364-69efcbd0-c6f0-4570-a7a6-68ace784465e.png)
![ryujinx_capture_2022-01-19_15-05-27](https://user-images.githubusercontent.com/2696404/150081369-55d8650c-4c14-46e8-aa3b-f5987135d084.png)
![ryujinx_capture_2022-01-19_15-05-51](https://user-images.githubusercontent.com/2696404/150081372-e0805f9e-802c-4cf7-9071-a2749f0aedac.png)

### Log file

[Ryujinx_1.0.7176_2022-01-19_14-55-50.log](https://github.com/Ryujinx/Ryujinx/files/7894830/Ryujinx_1.0.7176_2022-01-19_14-55-50.log)

### Environment?

- Ryujinx version: 1.0.7175
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 2.0.0
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by GamerzHell9137** [comment]
The issue started with #2618 but it seems like the issue is not triggered because of the PR, but something else.
With the PR the game is correctly reporting 1080p resolution but shows a double invalid texture format issue.

```00:00:32.867 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).
00:00:34.786 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:34.786 |I| Hid Configure: Configured Controller ProController to Player1
00:00:34.795 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 53!
00:00:34.796 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 47!
00:00:34.799 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 1!
00:00:34.799 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 46!
00:00:34.799 |I| HLE.OsThread.15 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:34.799 |I| HLE.OsThread.9 ServiceNv Create: Created map 1 with size 0x00881000!
00:00:34.800 |I| HLE.OsThread.9 ServiceNv Create: Created map 46 with size 0x00881000!
00:00:34.800 |I| HLE.OsThread.9 ServiceNv Create: Created map 47 with size 0x00881000!
00:00:34.800 |I| HLE.OsThread.9 ServiceNv Create: Created map 53 with size 0x00870000!
00:00:34.802 |I| HLE.OsThread.9 ServiceNv Create: Created map 54 with size 0x00020000!
00:00:34.803 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 34s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'TurokEx-NX'
    Message: '[01/11/2022 04:08:57] kexSystemSDL::SetWindowSize: Resized to 1920 1080'

00:00:34.806 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).
00:00:34.847 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).```

Handheld mode is fine on master with the game and before the PR it was reporting 720p for both Docked and Handheld.

**Comment by EmulationFanatic** [comment]
This is still a valid issue as it is a regression.
