### ISSUE TITLE
Black screen on Super Mario Bros 35.

### ISSUE THREAD

**Issue by LuisMayo** [Ryujinx/Ryujinx#3009]
### What's the issue you encountered?

I was attempting to play a practice round of Super Mario Bros 35. The game didn't render anything but a black screen where the game should be. Game was properly running as I could verify via sounds that it was responding to user input.

### How can the issue be reproduced?

1. Ensure "enable guest access" option is enabled on Ryujinx
2. Boot a copy of SMB35 with the [replacement server](https://github.com/Ryujinx/Ryujinx/files/7897491/SM35SERVER.zip) and the [force network available](https://github.com/kinnay/SMB35/files/6572399/Force.Network.Available.zip) patches enabled. The game should be on its latest version (1.0.2)
2. Enter practice mode and select the first (and only) map.
3. After a while, you should see the game GUI, but not the game itself, seeing a black screen instead. Also, the game can be heard
![imagen](https://user-images.githubusercontent.com/20229636/150141319-df0b842d-227e-460d-859f-13cfcab75a1c.png)

### Log file

[Ryujinx_1.0.7176_2022-01-18_23-39-47.log](https://github.com/Ryujinx/Ryujinx/files/7897511/Ryujinx_1.0.7176_2022-01-18_23-39-47.log)

### Environment?

- Ryujinx version: 1.0.7176
- Game version: 1.0.2
- System Specs:
  - OS: Windows 10
  - CPU: FX-6300
  - GPU: Nvidia Geforce 1060 6GB
  - RAM: 16GB DDR3
- Applied Mods : Yes, as they're necessary for the game to work at all: [replacement server](https://github.com/Ryujinx/Ryujinx/files/7897491/SM35SERVER.zip) and the [force network available](https://github.com/kinnay/SMB35/files/6572399/Force.Network.Available.zip)

### Additional context?
N/A

**Comment by Niwu34** [comment]
https://github.com/Ryujinx/Ryujinx/pull/3001 fixes this

**Comment by LuisMayo** [comment]
You guys are always several steps ahead. Can't wait to get home to check if that branch fixes it 👍

**Comment by LuisMayo** [comment]
After testing it. #3001 does fix this, however the performance is suboptimal. I'm getting 10 fps win 100% GPU usage on a 1060. I hope it gets better by the time the PR is merged

**Comment by GamerzHell9137** [comment]
> After testing it. #3001 does fix this, however the performance is suboptimal. I'm getting 10 fps win 100% GPU usage on a 1060. I hope it gets better by the time the PR is merged

Is FIFO 100% or GPU usage? Two different things. Other people who tested it haven't had issues.

**Comment by LuisMayo** [comment]
GPU usage, I'll list some stats here if that is of help:
- FIFO is at around 1%, between 1% and 2%. 
- GPU at 98-100% according to Windows Task Manager and HWInfo.
- CPU between 40 and 60%, surprising considering that the CPU is not the best possible one (fx-6300)
- FPS at 5-10 range
- There is an slight video delay. Using the sound as a measurement, there is between 0.5 and 2 seconds image delay

Just for the sake of completeness I've tried with master branch's Ryujinx. Remember than as stated in the original post, in this version the GUI border is rendered, but not the game. Using this build
- FIFO at 8-10%
- GPU at 32%
- CPU at 50-70%
- FPS at 60
- No video

**Comment by riperiperi** [comment]
It's worth noting that full bindless does a _lot_ more work syncing textures than any normal game, and it can't be avoided for this one. Perhaps it's aggressively deleting textures due to the overlap rules.

**Comment by LuisMayo** [comment]
Back again.

Even while the metrics show 100% GPU and not so bad CPU, maybe the poor performance is CPU-related. Or maybe just something else entirely, as people have been able to make this work in a 850M GPU, which is way worse than a 1060 6GB. It's been working on a 1060 3GB too.

So maybe it's the fx-6300 processor even if it is not 100%. May the problem be single-core performance? That'd explain the not-100% thingie.

It's still strange however, as I'm able to get 40-50fps on Odyssey, one would think SMB35 is less demanding

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.

**Comment by gdkchan** [comment]
#6577 should have fixed this on Vulkan, but I don't have the game to test. If anyone can test it, please do and comment so that we can close this issue.
