### ISSUE TITLE
Implemement some form of frame rate limiting on the guest system

### ISSUE THREAD

**Issue by emmauss** [Ryujinx/Ryujinx#301]
Although it is nice when we see record breaking fps internally, we really need to set up a limit for the guest fps. Any ideas?

**Comment by emmauss** [comment]
One idea is to only signal the nvnFlinger queueBuffer service only when a frame needs to be queued, from the renderer thread. though this may introduce a case where the renderer is behind by a few frames. also if the hos fps drops, the guest fps significantly drops. other than that, it closely matches the host fps when running at 60fps.

**Comment by ReinUsesLisp** [comment]
Regardless of how it's implemented it should be configurable (not hardcoded) because some games run at 30 FPS. 0 or <0 should be uncapped.

**Comment by filfat** [comment]
@ReinUsesLisp Agree, it should be up to software first and foremost; but it should always be user-overridable.

**Comment by emmauss** [comment]
then we need to be able to detect the actual game speed/ if there any thing that the game uses to frame pace from the OS. like setting a timing or event?

**Comment by gdkchan** [comment]
Limiting the frame rate is the games responsability. If the game is not limiting the FPS then we're implementing some event or sync improperly, and this needs to be fixed.

**Comment by ReaperOfSouls1909** [comment]
@emmauss i tried your frame limiter and it works perfect 30fps games are capped at 30 and 60 at 60 the way you did it works fine be it a tiny bit slow feeling in sonic mania but im used to 959fps down to 60 get @gdkchan to take a look

**Comment by emmauss** [comment]
@ReaperOfSouls1909 i dont know about it capping 30fps games. it is supposed to cap the guest speed to the host speed, and the host limit is hard coded to 60fps. so unless the game itself is limiting its speed, which i wish they did, i dont think my current frame rate limiter supports 30fps.

**Comment by AcK77** [comment]
See #367
