### ISSUE TITLE
No Models In Pokemon Legends,

### ISSUE THREAD

**Issue by RoyceNeon** [Ryujinx/Ryujinx#3013]
I Just Downloaded Pokemon Legends In My System And Started To Play But Not Single Model Of Pokemon ,Player or NPC Are Showing Up

**Comment by RoyceNeon** [comment]
If Any One Can Help Me to Fix This Issue

**Comment by RoyceNeon** [comment]
Why This Issue Is Closed Without Any Explanations'

**Comment by yuwenhua653** [comment]
The game is not released please don't ask this question

**Comment by GamerzHell9137** [comment]
> Why This Issue Is Closed Without Any Explanations'

Piracy is the reason.
