### ISSUE TITLE
Pokémon Legends: Arceus Switch freezes once phone is picked up

### ISSUE THREAD

**Issue by Evernow** [Ryujinx/Ryujinx#3018]
### What's the issue you encountered?

Video freezes, audio keeps playing in the background.

Only changes made were following the quick setup wiki.

### How can the issue be reproduced?
1. Load up Pokémon Legends: Arceus Switch
2. Go through menu to setup, once in gameplay you shortly after see a phone to investigate (once done with conversation with first NPC), once you do shortly afterwards the game freezes, with sound playing in the background.

![image](https://user-images.githubusercontent.com/44484725/150590421-563f96f4-0468-42de-8967-6f9d1a0c2c8c.png)

### Log file

[Ryujinx_1.0.7180_2022-01-21_12-09-44.log](https://github.com/Ryujinx/Ryujinx/files/7916219/Ryujinx_1.0.7180_2022-01-21_12-09-44.log)

### Environment?

- Ryujinx version: 1.0.7180
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: i9-10850k
  - GPU:  NVIDIA RTX 3080
  - RAM: 64gb
- Applied Mods :No

### Additional context?

No crash file is created in Logs folder.

**Comment by MetrosexualGarbodor** [comment]
Please do not open issues for unreleased games.
