### ISSUE TITLE
Image cut in 480x270p

### ISSUE THREAD

**Issue by phasermaniac83** [Ryujinx/Ryujinx#3020]
### What's the issue you encountered?
If I use a screen resolution like 480x270p, window adjusts right horizontaly, but not vertically. vertical resolution seems to be limited to 480p so I see only the top half of the screen.
If I set aspect ratio to stretch, it looks like the image.
If I set it to 16:9, it worse as adds horizontal black bars, because the image begin at the horizontal middle of screen.
I use a 15 khz CRT, and I prefer displaying games at 240p or 270p than interlaced resolution. This way pixel art games look perfect.
### How can the issue be reproduced?
N/A

### Log file
N/A

### Environment?
- Ryujinx version: 1.0.7172-win_x64
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS:  Windows 10
  - CPU: N/A
  - GPU: ATI HD 6950
  - RAM: 16GB
- Applied Mods : No

### Additional context?
N/A
![fullscreen_stretch](https://user-images.githubusercontent.com/71989321/150599820-8752473d-c550-4de9-8634-bedcb64299bc.png)

**Comment by marysaka** [comment]
The emulator isn't expected to work at those resolutions.

The issue information weren't completed entirely, closing.
