### ISSUE TITLE
Pokemon Legends Arceus (Missing Textures) 

### ISSUE THREAD

**Issue by Lastyz** [Ryujinx/Ryujinx#3023]
## Bug Report

N/A

### What's the issue you encountered?

Game runs fine except overworld textures aren't loading, Image provided. 

### How can the issue be reproduced?

Whichever version of Ryujinx I run the I have this issue. Tried every fix I could find online. GPU = GTX 1080 CPU = i5 8600k. 

### Log file

[Ryujinx_1.0.7181_2022-01-22_10-26-23.log](https://github.com/Ryujinx/Ryujinx/files/7918147/Ryujinx_1.0.7181_2022-01-22_10-26-23.log)

### Environment?

- Ryujinx version: 1.0.7181

- Game version: 

- System Specs:
  - OS:  Windows 10
  - CPU: *i5-8600k
  - GPU: *Nvidia GTX 1080
  - RAM: 16gb
- Applied Mods :no

### Additional context?

Seems to be effecting people with Nvidia GPU's seen a few posts on reddit! 
![image](https://user-images.githubusercontent.com/98213146/150635286-29b52db0-2714-4040-9a94-472e3081cd11.png)

**Comment by MetrosexualGarbodor** [comment]
Please do not open issues for unreleased games.
