### ISSUE TITLE
Corrupted save data Legends Pokemon Arceus on Linux Garuda every update manual or automatic

### ISSUE THREAD

**Issue by Raz-Yagami** [Ryujinx/Ryujinx#3035]
### What's the issue you encountered?

Updating automatic or manual get corrupted save data on Legends Pokemon Arceus on Linux</br>
Did you make any changes related to Ryujinx itself? No </br>
https://i.ibb.co/bW5pxgF/Captura-de-pantalla-de-2022-01-23-09-27-26.png

### How can the issue be reproduced?

Just update aplication automatic or manual get save data corrupted no other game affected over linux

### Environment?

- Ryujinx version: 1.0.7181 to any version have to delete save to process</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *(Garuda Linux Gnome 5.16.2 ZEN)*
  - CPU: *(Ryzen 5 5600x)*
  - GPU: *(NVIDIA GTX 1070)*
  - RAM: *(16GB)*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Windows version don't have problems at any update aplication but Linux version it broke save data when update and can't take save data from Ryujinx to Ryujinx get the same issues Windows to Linux just Pokemon Legends Arceus it's buggy the other game save data don't have problems.

**Comment by gdkchan** [comment]
Hello, we do not allow submitting bug reports for games that were not yet released due to legal reasons.
Thanks for the comprehension.
