### ISSUE TITLE
Save file corruption in Pokemon Legends: Arceus (Linux)

### ISSUE THREAD

**Issue by riceporn** [Ryujinx/Ryujinx#3036]
### What's the issue you encountered?
If there's a save file present in Pokemon Legends: Arceus save directory, launching the game always results in the screen seen below.
![bug](https://user-images.githubusercontent.com/91975110/150756623-a68bc55a-ec84-4a8e-87d0-a99c8c17784b.png)

### How can the issue be reproduced?

1. Launch the game without a save
2. Save in game
3. Close the emulator
4. Launch the game again

**Alternatively:**
1. Copy a save file to the game's user save directory
2. Launch the game
[ Include a detailed step by step process for recreating your issue. ]

### Log file
Saving the game:
[Ryujinx_1.1.6_2022-01-24_15-03-08.log](https://github.com/Ryujinx/Ryujinx/files/7924370/Ryujinx_1.1.6_2022-01-24_15-03-08.log)

After relaunching:
[Ryujinx_1.1.6_2022-01-24_15-07-48.log](https://github.com/Ryujinx/Ryujinx/files/7924385/Ryujinx_1.1.6_2022-01-24_15-07-48.log)

### Environment?

- Ryujinx version: 1.1.6</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Arch Linux
  - CPU: Ryzen 3 3100
  - GPU: NVIDIA GeForce GTX 1650 SUPER
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
I made a [video](https://youtu.be/vWIeqGDHcV8) replicating the bug.
There was issue with Pokemon Sword similar to this one. And it only seems to be on Linux.

**Comment by MetrosexualGarbodor** [comment]
Please do not open issues for unreleased games.
