### ISSUE TITLE
[Linux] Bundled libSDL2.so breaks input with some controllers

### ISSUE THREAD

**Issue by rwinkhart** [Ryujinx/Ryujinx#3040]
### What's the issue you encountered?

With the bundled libSDL2.so on Linux, some controllers (in my case, the wired PowerA Gamecube controller) have messed up inputs. The A button does not work at all and many of the other buttons map the wrong inputs (buttons even map to sticks/triggers, and vice-versa), or nothing. The issue is not present in the Windows version. </br>

### How can the issue be reproduced?

1. Plug in affected controller
2. Start Ryujinx
3. Try to map inputs
4. Notice it doesn't work correctly (tested on multiple Arch Linux systems)

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.8</br>
- System Specs (system 1):
  - OS: *Arch Linux (kernel 5.16.2)*
  - CPU: *AMD Ryzen 9 4900HS*
  - GPU: *NVIDIA RTX 2060 Max-Q)*
  - RAM: *16GB*
- Applied Mods : [ No ]

- System Specs (system 2):
  - OS: *Arch Linux (kernel 5.16.2)*
  - CPU: *AMD Ryzen 9 3900X*
  - GPU: *NVIDIA RTX 3080)*
  - RAM: *32GB*
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>

**Solution**
After replacing the bundled libSDL2.so with a copy of my system's native copy of the same library, controller input now works perfectly. Perhaps simply bundling a newer version of libSDL2.so would fix the issue?

The PowerA wired Gamecube controller is the only controller I have that is affected (official pro controller works just fine as is).

**Comment by rwinkhart** [comment]
I believe this to also be the cause of #2930 and #2416

**Comment by Mou-Ikkai** [comment]
I can confirm this on my Ubuntu laptop, Wireless PowerA controllers have mixed inputs, with some of the buttons not even being responsive. Replacing Ryujinx's libSDL2.so with Ubuntu's own fixed it.

**Comment by Isaiahmag** [comment]
Dualsense trigger and right analog stick don't work on Arch.

**Comment by Tatsh** [comment]
You can delete the bundle libSDL2.so file and it will use the system one.

**Comment by edisionnano** [comment]
Ryujinx updated their sdl sometime ago and it fixed the issues however this was rolled back cause it caused issues to windows users. Hopefully these are fixed and they'll ship a new build of sdl2. Till then, make it use the system provided one if you have issues. Using https://generalarcade.com/gamepadtool/ to create a mapping env also helps some gamepads (this tool isn't opensource)

**Comment by Thog** [comment]
Reopening and marked for closure on https://github.com/Ryujinx/Ryujinx/pull/3317
