### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by conitsua** [Ryujinx/Ryujinx#3045]
My specs
 Processor : Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 CPUs), ~2.5GHz
NVIDIA GeForce GTX 1650

**Comment by conitsua** [comment]
![error ](https://user-images.githubusercontent.com/98486947/151357675-83578fbe-6c2d-4f0c-bb45-19cbb1ff327d.jpg)

**Comment by CrusadingNinja** [comment]
Please redownload the latest build of Ryujinx from the official website. AppVeyor, which the old builds used, is no longer supported.
