### ISSUE TITLE
Black Screen Only Sound

### ISSUE THREAD

**Issue by Skylaryel** [Ryujinx/Ryujinx#3047]
## Bug Report

Hi, I'm Having a problem on Ryujinx where I can hear the game volume but nothing appears on Screen. Is there a fix for this? Btw I'm not using NVidia GPU, Ryujinx has worked for me before perfectly fine without NVidia but now for some reason the sccreen stays black and only plays sound.

**Comment by MetrosexualGarbodor** [comment]
Make sure no overlays are active (like MSI Afterburner, RTSS overlay or Twitch Studio). Then, right-click on your desktop, select Nvidia Control Panel, click Manage 3D Settings, and in the center-right corner, click "Restore Defaults”.
Next time come to Discord for support questions.

**Comment by gdkchan** [comment]
User said they are not using an NVIDIA GPU
> I'm not using NVidia GPU
