### ISSUE TITLE
Pokemon Legends Arceus inaccurate model rendering  (LInux/Mesa)

### ISSUE THREAD

**Issue by C1fer** [Ryujinx/Ryujinx#3051]
### What's the issue you encountered?

While playing Legends Arceus on linux, you can see some inaccurate rendering on character and pokemon models.

### How can the issue be reproduced?

Can be reproduced by just playing the game. The issue is evident on  the first cutscene.
### Log file

[Ryujinx_1.1.11_2022-01-27_23-26-24.log](https://github.com/Ryujinx/Ryujinx/files/7955795/Ryujinx_1.1.11_2022-01-27_23-26-24.log)

### Environment?

- Ryujinx version: 1.1.11
- Game version: 1.0.1</br>
- System Specs:
  - OS: Arch Linux
  - CPU: i5 10400F
  - GPU: RX 480
  - RAM: 16GB
- Applied Mods : No

### Additional context?

I'm using mesa drivers version 22.0.0_devel.149446.fe3984b8cde-1

![Screenshot_20220128_004329](https://user-images.githubusercontent.com/41005657/151489060-fd5ae37b-b6ed-447e-9079-faad219efcf2.png)
![Screenshot_20220128_004306](https://user-images.githubusercontent.com/41005657/151489055-591be0c2-f96e-4a3e-9c76-3034dc370641.png)

**Comment by Slippingstones** [comment]
I also have this issue.  Kind of looks like a canvas painting overlay in the models.

**Comment by C1fer** [comment]
Seems like using the enviroment variable `force_integer_tex_nearest=true` fixes the rendering.

**Stock**
![Stock 1](https://user-images.githubusercontent.com/41005657/152082007-00a93032-6b8b-44e4-8cfc-c4214d57754d.png)

![Stock](https://user-images.githubusercontent.com/41005657/152082099-5428c744-5137-4f0b-9c02-4244e4d7b5fc.png)


**force_integer_tex_nearest=true**
![force 1](https://user-images.githubusercontent.com/41005657/152082034-856482ad-a49a-41d9-abb9-9925bbbd06b5.png)
![Screenshot_20220201_213455](https://user-images.githubusercontent.com/41005657/152082149-91bcb04e-cb1d-49e9-ba2e-c8ded3183d60.png)
