### ISSUE TITLE
Pokemon Legends Arceus freezes at the beginning

### ISSUE THREAD

**Issue by jd-apprentice** [Ryujinx/Ryujinx#3056]
### What's the issue you encountered?

- The game freezes at the beginning, after creating the character plus name (first time playing no save data before)

### How can the issue be reproduced?

- From a fresh game start withouth a save or anything

### Log file
[Ryujinx_1.1.11_2022-01-28_18-25-53.log](https://github.com/Ryujinx/Ryujinx/files/7961935/Ryujinx_1.1.11_2022-01-28_18-25-53.log)

### Environment?

- Ryujinx version: 1.1.11</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10)
  - CPU: Ryzen 5 2600
  - GPU: Rx 460 4gb 
  - RAM: 16gb
- Applied Mods : No

### Additional context?

- Picture where the game stops
![image](https://user-images.githubusercontent.com/68082746/151623539-bd955186-0b24-4f24-8703-8c3c1d54623f.png)

- I don't remember the default configuration so here is some pictures of my actual settings:
![image](https://user-images.githubusercontent.com/68082746/151624108-3dd9d02d-0133-4937-88b3-d20b73d62f3c.png)
![image](https://user-images.githubusercontent.com/68082746/151624128-9b2eae74-8a22-4ed0-9295-f469e60f6eee.png)
![image](https://user-images.githubusercontent.com/68082746/151624157-09463db4-0661-4d04-8d62-205d4d0c214d.png)
![image](https://user-images.githubusercontent.com/68082746/151624169-4e327f38-0423-4476-ba16-8cdcf90e3b6e.png)

Additional info about your environment:</br>
- N/A

**Comment by jd-apprentice** [comment]
I had to use the version mentioned here -> [This mention](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424)

Now working well!

**Comment by Luqman15334** [comment]
> I had to use the version mentioned here -> [This mention](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424)
> 
> Now working well!



which one yea? im having the same problem

**Comment by jd-apprentice** [comment]
[ryujinx-Release-1.0.0+d047323-linux_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/177597747.zip)
[ryujinx-Release-1.0.0+d047323-osx_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/177597748.zip)
[ryujinx-Release-1.0.0+d047323-win_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/177597749.zip)

One of these

**Comment by Luqman15334** [comment]
> [ryujinx-Release-1.0.0+d047323-linux_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/177597747.zip) [ryujinx-Release-1.0.0+d047323-osx_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/177597748.zip) [ryujinx-Release-1.0.0+d047323-win_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/177597749.zip)
> 
> One of these

thanks so much, im just having some fps issues and sometime crashes
