### ISSUE TITLE
Discussion forum?

### ISSUE THREAD

**Issue by asheenlevrai** [Ryujinx/Ryujinx#3060]
Hi,

I'm considering using ryujinx (on mac) and I'm looking for a place to discuss with experienced users. Is there any discussion forum that is "official" or at least considered better than average? Or should I use Reddit or Discord only?

My 1st question would be about hardware requirements. I own a late 2015 27'' 5K iMac
 - i5-6500 (4 cores - 3.2Ghz base, 3.6 turbo)
 - 16GB DDR3 1866MT
 - M.2 SSD with plenty of space
 - Radeon R9 M390 2GB

From what I could find online for windows requirements, this should be a little above minimum requirement (I don't expect stellar perfs obviously and I guess the GPU would be the most limiting factor here). Now, I don't know how current is this info I found.

Tx
-a-

**Comment by AcK77** [comment]
Hi, if you want to speak about the project with other users or devs, you can go on Discord (https://discord.gg/Ryujinx).
For now, macOS isn't supported and your GPU isn't powerful enough if you use bootcamp.
Thanks.

**Comment by asheenlevrai** [comment]
Thanks a lot :)
