### ISSUE TITLE
Gamepad R Stick Z Rotation do not work in Pokemon Legends Arceus

### ISSUE THREAD

**Issue by JoewAlabel** [Ryujinx/Ryujinx#3062]
## Bug Report

N/A

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
The Right stick up and down do not work. I am using a usb controller likas as PS3 model/layout.
The right stick do not work for up and down.
I tested it up on windows gamepad calibration settings and the gamepad is all right. Just in the emulator and the game it not works.
I do not have another game to test it, so i tested only with Pokemon Legends Arceus game.
With that problem i can`t zoom in/out the camera and can`t move the aim up and down to throw pokeballs.

[ Did you make any changes related to Ryujinx itself? ]</br>
No.

[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

Start the game.
Try moving the right stick up and down. it will not work.

### Log file
https://pastebin.com/XxEBSz3k

### Environment?

- Ryujinx version: 1.1.13</br>

- Game version: 1.0.0</br>

- System Specs:
  - OS: *Windows 11 Pro 64 bits*
  - CPU: *i9-9900KF*
  - GPU: *NVIDIA RTX 2080 Ti)*
  - RAM: *64GB*
- Applied Mods : [ No ]

### Additional context?

Thank you!

**Comment by benderscruffy** [comment]
duplicate of #2837 and #2905

**Comment by JoewAlabel** [comment]
Solution:
Please update SDL2.dll to 2.0.18.0 or latest version. This will solve the problem with gamepad
You can download the latest version of SDL2.dll here: [https://www.libsdl.org/index.php](https://www.libsdl.org/index.php)

**Comment by Dazta33** [comment]
> Solution: Please update SDL2.dll to 2.0.18.0 or latest version. This will solve the problem with gamepad You can download the latest version of SDL2.dll here: https://www.libsdl.org/index.php

Followed everything you said. nothing
