### ISSUE TITLE
fsp-srv IFileSystemProxy:201 (OpenDataStorageByProgramId) is not implemented

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#3064]
## Bug Report

Used by homebrew Borealis.
This homebrew was compiled from the source here: https://github.com/natinusala/boreali
[borealis_demo.zip](https://github.com/Ryujinx/Ryujinx/files/7965575/borealis_demo.zip)

### Log file
[Ryujinx_1.1.13_2022-01-30_16-52-50.log](https://github.com/Ryujinx/Ryujinx/files/7965579/Ryujinx_1.1.13_2022-01-30_16-52-50.log)

**Comment by AcK77** [comment]
Why is that closed?
