### ISSUE TITLE
Update to 1.1.14 breaks the emulator

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [Ryujinx/Ryujinx#3065]
### What's the issue you encountered?

I updated Ryujinx to version 1.1.14 and now can't open any game.

### How can the issue be reproduced?

Update to version 1.1.14 and open any game

### Log file

[Ryujinx_1.1.14_2022-01-30_17-38-38.log](https://github.com/Ryujinx/Ryujinx/files/7966381/Ryujinx_1.1.14_2022-01-30_17-38-38.log)

### Environment?

- Ryujinx version: 1.1.14</br>
- Game version: Pokemon Legend Arceus 1.0.1</br>
- System Specs:
  - OS: Windows 11 64 bits
  - CPU: Ryzen 5 3600X
  - GPU: NVIDIA RTX 3070 ti
  - RAM: 16 GB DDR4
- Applied Mods : No

### Additional context?
N/A

**Comment by MetrosexualGarbodor** [comment]
You have ESET antivirus.

Create HIPS exception in ESET, in:
Advanced Settings> HIPS> DEEP BEHAVIOR INSPECTION> Exclusions> Edit.
Add the Ryujinx folder.

Next time come to discord for help.

**Comment by AdrianCarmonaRoda** [comment]
Thanks it was it!
I'm so sorry I didn't know about the discord server
