### ISSUE TITLE
Splatoon 2 crashes during loading screen

### ISSUE THREAD

**Issue by blblblsdlbsdbs** [Ryujinx/Ryujinx#3070]
### What's the issue you encountered?

I just decided to launch Splatoon 2 (Update 5.5.0, system update 13.2.1, Ryujinx ver. 1.1.14) and during the loading screen with all the squid swimming up, the game just crashes.

### How can the issue be reproduced?

1. Launch Splatoon 2
2. Congrats!

### Log file

[Ryujinx_1.1.14_2022-01-30_18-49-19.log](https://github.com/Ryujinx/Ryujinx/files/7967362/Ryujinx_1.1.14_2022-01-30_18-49-19.log)
(sorry wrong log file at first lol)

(did i add it correctly?)

### Environment?

- Ryujinx version: 1.1.14</br>
- Game version: Splatoon 5.5.0</br>
- System Specs:
  - OS: Windows 10 Home (OS Build19042.1466)
  - CPU: i5-10400F
  - GPU: NVIDIA GeForce RTX 3060
  - RAM: 16 GB
- Applied Mods : No!

### Additional context?

Additional info about your environment:</br>
I deleted the Ryujinx folder many times, and also added the same Prod.keys and Firmware multiple times, none of it fixed the issue
(Also apologies if I messed up writing this issue, I've never wrote an issue for Ryujinx before)

**Comment by gdkchan** [comment]
The log file is empty.

**Comment by blblblsdlbsdbs** [comment]
> The log file is empty.

Right, I just realized that. Fixed it

**Comment by blblblsdlbsdbs** [comment]
Realized the issue was
