### ISSUE TITLE
PLA crash and give me that error

### ISSUE THREAD

**Issue by tiiolando** [Ryujinx/Ryujinx#3072]
![Desktop Screenshot 2022 02 01 - 05 54 03 92 (2)](https://user-images.githubusercontent.com/39249132/151915813-b4413cef-8bf1-42a6-8186-eeef18f1890b.png)

**Comment by Squall-Leonhart** [comment]
your ryujinx is out of date.

**Comment by yell0wsuit** [comment]
Why not try the official latest version first? Instead of this custom build?

**Comment by AcK77** [comment]
Please reopen an issue if this still happen in the last version of Ryujinx.
As is, the issue is pointless since it's a PR build and you don't give extra informations. Thanks.
