### ISSUE TITLE
PC crashes (Blue Screen) every ~ 1h while playing Pokemon Legends Arceus

### ISSUE THREAD

**Issue by MrDurma** [Ryujinx/Ryujinx#3073]
### What's the issue you encountered?

I was playing Pokemon Legends Arceus when suddenly my PC crashes, I'm 99% sure that something with loading or deleting module caused PC to crash. Previously I left PC with open game and it caused the game just to crash (I was afk for like 2h), but not causing blue screen. So I assume something connected with memory causes the blue screen. I'm not here to complain about game crashing since that is normal with emulators. My only concern is Windows crashing since those things always make me worried lol...

Anyways I'm playing games on this PC for over a year now and I run into blue screen only twice, and since yday I started using Nintendo Switch emulators (Yuzu and Ryujinx) and both of them caused my PC to crash multiple times,

I was messing with Yuzu settings and no matter what I selected after some time PC would crash.
On Ryujinx I left everything on default since it was running really great and just when I thought okay, this is really playable boom blue screen.

### How can the issue be reproduced?

I didn't run into blue screen a single time while game was running and I was afk, and I was afking for long time. Worst case scenario game would just crash.

So to reproduce the issue all I have to do is just play and at some point while loading or deleting new module my PC crashes.

### Log file

I couldn't find one, after PC crashes, so I guess they are not written when blue screen occurs.

### Environment?

- Ryujinx version: 1.1.15 (System Version 13.2.1 + keys are up to date)

- Game version: 1.0.1

- System Specs:
  - OS: Windows 11 (up to date with optional updates installed)
  - CPU: Ryzen 5 3600
  - GPU: GTX 1060 3GB (Drivers updated)
  - RAM: 16GB 3200mhz Dual Channel
- Applied Mods : No

### Additional context?
Only game I played is Pokemon Legends Arceus so that may be the cause.

**Comment by EliEron** [comment]
I would second the concern about the low amount of VRAM. 3GB is very low for switch emulation, especially for an open world game like PLA. The fact that it occurs during loading of new assets, which will lead to VRAM spikes, makes it seem even more likely to be the root of the issue.

Running out of VRAM should in theory only crash your GPU Driver, but in practice I've seen it cause all kinds of system instability. Ranging from random programs crashing, to complete system crashes.

I would recommend opening up Task Manager and keeping a view of the GPU tab while playing the game to monitor the VRAM usage. Task Manager isn't the most accurate program for GPU information, but it should be enough to get an idea if you are hitting the ceiling of VRAM usage or not.

**Comment by MrDurma** [comment]
> Contributor

I kept Task Manager open all the time, RAM usage is around 50%-60% and VRAM usage didn't cross 1.5GB, it wasn't no where near running out of VRAM at any point of playing, nor was any part of PC overheating, I used HW monitor to check every temp sensor and it was all better than when I'm playing other heavy games. However maybe logs can be used from game crashing to analyze the issue
[Ryujinx_1.1.15_2022-02-01_14-33-35.log](https://github.com/Ryujinx/Ryujinx/files/7980653/Ryujinx_1.1.15_2022-02-01_14-33-35.log)

**Comment by MrDurma** [comment]
> If you can reproduce this issue please report the blue screen error.
> 
> If you haven't follow this tutorial on how to check your RAM for errors. https://www.thewindowsclub.com/windows-memory-diagnostics-tool-in-windows-7
> 
> This method still works in windows 11, and requires no downloads. Blue screens are iffy. There could be a memory leak occurring, or your GPU could be overheating. It could also be running out of video memory itself seeing as it is a 3GB model. There isn't much to go off of here except that Blue Screen error. Do your best to recreate your issue then drop a quote on me please.
> 
> EDIT: For reference when you say loading, deleting a new module do you mean shaders, and models in the game? I believe Shader compilation uses A LOT of GPU processing, and memory. (I could be wrong not an expert) Which could lead to this problem.

I did memory diagnose and it didn't find any problems.

I really doubt 3GB VRAM is hurting the game in any way, you can see screenshot of memory usage after few minutes of playing and moving around.

What I mean by loading and deleting modules is basically moving around to force loading new parts of the map, new textures and stuff. My game was crashing even on standby tho, but after long time lol, 

Anyways after 30 minutes I managed to catch blue screen, game crashed twice normally and third time was charm with blue screen xD

![Task Manager](https://user-images.githubusercontent.com/90354591/152029419-102b8243-64e8-4980-a3c8-8d99873aeaf7.png)

![20220201_192637](https://user-images.githubusercontent.com/90354591/152029426-aaf2e309-dda1-4216-8048-1bbe11b07f00.jpg)

![20220201_192633](https://user-images.githubusercontent.com/90354591/152029450-4e7ded55-66af-41a8-8759-8026088db8f5.jpg)

**Comment by Slippingstones** [comment]
> > Contributor

It's definitely your GPU not your actual memory. I just wanted to be absolutely sure. The last thing in the log was a combination of multi threading, shaders being loaded (Objects in the world), and shaders being written into your cache (They go through memory while being processed I believe). 

You also seem to be using 8gbs of your actual memory as VRAM this is apparently allocated via the bios automatically. 
This memory is much slower then vram, and can cause lots of stuttering in games. Your actual DEDICATED GPU memory usage is maxing out. I have also read a few threads that say the GTX 1060 3GB does not support the Shared memory function so it's possible it will always stay at 0%.

I could suggest a few options in Ryujinx itself that may, or may not make a difference. Changing Graphics backend multithreading to Auto instead of On. Try changing the resolution to a custom scale of 0.5-0.7. The game will look a little gross, but you may experience less load on your GPU. Change anisotropic filtering to Auto. 

IF worst comes to worst you can turn off the Shader Cache. You will experience pop in, and lag in every area you revisit. I'm unsure how Ryujinx handles not having a cache as I have never tried it. 

These may or may not help, but if you are keen on playing games with Ryujinx these might be your best options beyond buying a GPU with 6GB of memory.

**Comment by MrDurma** [comment]
> 

I'm more confused than ever xD, I honestly can't believe that emulator needs more VRAM and that's causing blue screens. I've played many AAA open world games which are below system requirements, such as Forza Horizon 5 at high settings, I know what kind of lags occur due to low VRAM, but PC never ever crashed because of full VRAM. 

Also shared memory works, I just tested it by running 2 games at same time and you can see Shared GPU memory filling here
![Manager](https://user-images.githubusercontent.com/90354591/152118630-16c3395b-4f43-40d6-9a1e-1eea57316080.png)

Shared memory is obviously bad but it does work if its needed, it only starts filling when dedicated GPU VRAM is full, obviously for performance reasons.

I don't understand how can emulator cause PC to crash when dedicated VRAM doesn't even fill up, I mean people run emulator on iGPU and I can't on GPU with 3GB VRAM :/

**Comment by Slippingstones** [comment]
Triple A games are optimized to run on lower end consoles, and are usually more dependent on CPU processing power. Forza is extremely optimized, and runs well on AMD mobile chips. I would consider this closed since it’s no longer on topic, and hardware related. 

Emulation requires more resources then running a game via steam as these games were never made with this usage in mind.

**Comment by Squall-Leonhart** [comment]
a lack of video memory won't cause a BSOD, it'll page out to system memory, theres a hardware(Memory or CPU) or software combination issue at play here.

**Comment by MrDurma** [comment]
> 

WOW! IT WORKED :D :D :D
I updated both Chipset and BIOS, idk which one fixed it but it works! Apparently version after my BIOS was with note "memory stability update" xD so that might've fixed it. I completely forgot that you gotta update chipset manually since windows update doesn't cover it (I think it covers it partially tho). Thanks a lot! brb gotta catch em all :D, thread closed with pleasure lol

So in future whoever has same issue just update every single driver your PC has, worth mentioning that you SHOULDN'T forget to update chipset and BIOS.

**Comment by Slippingstones** [comment]
> 

I appreciate the response. I'm not as knowledgeable about these things, and am happy the posters issues where resolved.
I also am happy to learn more about these errors, and my mistakes.

Thank you for all your work!


[Unfortunately I did not think the VRAM capable, and became impatient with my misinformation as shown in a response.]
