### ISSUE TITLE
controller deadzone feels wrong

### ISSUE THREAD

**Issue by Vegita2** [Ryujinx/Ryujinx#3074]
### What's the issue you encountered?

controller deadzone implementation isn't working properly. It currently checks x and y independently
https://github.com/Ryujinx/Ryujinx/blob/686757105c83a1485117ff5f5d30b2fad4df39b1/Ryujinx.Input/HLE/NpadController.cs#L392-L399

This has the problem that when inputting one of the cardinal directions it's impossible to do small adjustments on the other axis.

Ideally the implementation should only check if the length is smaller than the deadzone, something like this (not tested)
```c#
private static JoystickPosition ApplyDeadzone(float x, float y, float deadzone) 
{ 
    if (x * x + y * y < deadzone * deadzone)
        return new JoystickPosition 
        { 
            Dx = 0, 
            Dy = 0 
        }; 
    else
        return new JoystickPosition 
        { 
            Dx = ClampAxis(x), 
            Dy = ClampAxis(y) 
        }; 
} 
```

Here is also an article describing the problem in more detail  
https://www.gamedeveloper.com/disciplines/doing-thumbstick-dead-zones-right

**Comment by german77** [comment]
Have you ever seen a solution for different deadzones for each axis?

**Comment by Vegita2** [comment]
No i have not. Why are you asking? Controller deadzone shouldn't really depend on individual axis

**Comment by iWeaker4you** [comment]
I think this is also causing the "right stick" to not work properly in Zelda BOTW. The right stick does not work to interact in the menu many times, it rarely works.
