### ISSUE TITLE
Pokémon Legends Arceus the graphics when I'm in the village are not loaded 

### ISSUE THREAD

**Issue by Aravs** [Ryujinx/Ryujinx#3076]
### What's the issue you encountered?

The graphics only when I am in the village are not loaded, as soon as I return to the exploration everything works normally.

Before version 1.1.15 I did not encounter this problem. 

### Log file

[Ryujinx_1.1.16_2022-02-02_23-19-46.log](https://github.com/Ryujinx/Ryujinx/files/7990439/Ryujinx_1.1.16_2022-02-02_23-19-46.log)

### Environment?

Ryujinx version: 1.1.15 and 1.1.16

Game version: 1.0.1

System Specs:

    OS: Windows 11 Pro
    CPU: AMD Ryzen 5 3700X
    GPU: Nvidia GeForce 1070 8 GB
    RAM: 32 GB

### Additional context?

I updated the video card drivers yesterday to version: 511.65 

Only with these new versions am I having these problems.

![Immagine 2022g-02-02 230653](https://user-images.githubusercontent.com/12687079/152247331-6247cbf0-8b48-48be-adf5-7dfa27947469.png)

**Comment by MetrosexualGarbodor** [comment]
Disable Rivatuner statistics server. And please don't open issues for help, come to Discord instead. https://discord.gg/ryujinx

**Comment by Squall-Leonhart** [comment]
RTSS doesn't cause this issue.
