### ISSUE TITLE
Ryujinx crashes when i access the mirelands crimson map Pokémon Legends Arceus

### ISSUE THREAD

**Issue by lombano** [Ryujinx/Ryujinx#3078]
Pokémon Legends Arceus

[Ryujinx_1.1.16_2022-02-03_17-57-26.log](https://github.com/Ryujinx/Ryujinx/files/7998219/Ryujinx_1.1.16_2022-02-03_17-57-26.log)

**Comment by Squall-Leonhart** [comment]
Have played through the entire game without issues, disable any mods and verify your game dump isn't corrupted.

**Comment by lombano** [comment]
I downloaded the game from another source and everything is working correctly again, thanks!
