### ISSUE TITLE
Latest Nvidia Driver [511.65 - 02/01/2022] update broke the graphics in Pokemon Legends Arceus (V1.0.0) hometown.

### ISSUE THREAD

**Issue by m-burger** [Ryujinx/Ryujinx#3081]
### What's the issue you encountered?

Using Ryujinx v 1.1.16 on pokémon Legends Arceus after updating my Nvidia driver to the latest (511.65 - 02/01/2022)
I didn't made changes to Ruyjinx.

### How can the issue be reproduced?

Load the the game Pokemon Legends Arceus (V1.0.0) and go to the hometown.

### Log file

I have none.

### Environment?

- Ryujinx version: 1.1.16</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *AMD Ryzen 5 5600X*
  - GPU: *NVIDIA RTX 2080 Super*
  - RAM: *32GB*
- Applied Mods : No

### Additional context?

![Capture](https://user-images.githubusercontent.com/32699972/152502472-9ef01bb5-e5bc-4ac2-8ba4-32fc561c96be.PNG)

**Comment by Jermnzl** [comment]
Did you add the update into the game?? as thats was the reason mine did this, took it out and boom working

**Comment by GamerzHell9137** [comment]
Don't use Rivatuner, disable it and relaunch Ryujinx.
