### ISSUE TITLE
I can't start ryujinx

### ISSUE THREAD

**Issue by CacoGam3s** [Ryujinx/Ryujinx#3083]
### What's the issue you encountered?

i tried to start ryujinx but a error appeared and the console closed i tried a lot of times but the
error was there and the i cant use ryujinx

### Log file

i see the log file of ryujinx and this i have found: 0:00:00.080 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.083 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.091 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.091 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.093 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.097 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.110 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.110 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.110 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.110 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.110 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.110 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.112 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.112 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.114 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.115 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.115 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.121 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.16
00:00:00.136 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.136 |N| Application Print: CPU: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz ; 6 logical
00:00:00.137 |N| Application Print: RAM: Total 8070 MB ; Available 2622 MB
00:00:00.140 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.141 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.297 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 148

i dont know  the solution and i dont know what mean that error, i hope the error could be solucionated

**Comment by MetrosexualGarbodor** [comment]
The program can't find files that should be there if you extracted it correctly. Make sure you don't have an antivirus deleting the files and try again. 
Next time, please come to Discord for help instead of opening an issue. https://discord.gg/ryujinx
