### ISSUE TITLE
Auto Update from 1.1.16 to 1.1.17 breaks everything

### ISSUE THREAD

**Issue by horusra** [Ryujinx/Ryujinx#3091]
Started v1.1.16 and double clicked a game, while it was loading shaders, ryujinx asked to update to 1.1.17, and I clicked yes.
After update, it didn't restart, and I went to see every file had "ryuold" extension, but no new files were added to replace them.
Had to delete all files and re-download ryujinx 1.1.17 manually to fix it.

Windows 10 21H1

**Comment by edisionnano** [comment]
Do you have any antivirus?

**Comment by GamerzHell9137** [comment]
Yup, ryuold sometimes happens. Fix is to redownload Ryujinx.

**Comment by MetrosexualGarbodor** [comment]
Why would you try to update the emulator while it's running?

**Comment by horusra** [comment]
> Do you have any antivirus?

no I do not.


> Why would you try to update the emulator while it's running?

because that is when it asked.
why does auto update not stop emulation before ruining the program?
