### ISSUE TITLE
Updating breaks custom themes

### ISSUE THREAD

**Issue by jparmstr** [Ryujinx/Ryujinx#3094]
### What's the issue you encountered?

Ryujinx supports the use of custom GTK themes for its UI, definable in the Settings window under General > Themes. I assumed that the directory "Ryujinx\share\themes" was the right place to keep these custom themes, since the default theme is located here. After updating Ryujinx (to version 1.1.19) all my custom themes were broken and I could not select them again via the GUI. After investigating I realized that while updating Ryujinx batch renames every single file in this directory with a ".ryuold" extension. After restarting the program again, all my custom theme files were deleted by Ryujinx as well.

### How can the issue be reproduced?

Install an old version of Ryujinx. Copy a folder containing a custom GTK theme ([such as this](https://www.pling.com/p/1357889)) to the "\share\themes" directory. Let Ryujinx update itself to the latest version. Every file descended from "\share\themes" will be renamed with a ".ryuold" extension. At some point (I assume after restarting again), all these files will be deleted.

### Log file

[Ryujinx_1.1.19_2022-02-06_13-17-04.log](https://github.com/Ryujinx/Ryujinx/files/8010897/Ryujinx_1.1.19_2022-02-06_13-17-04.log)
[Ryujinx_1.1.19_2022-02-06_13-29-40.log](https://github.com/Ryujinx/Ryujinx/files/8010900/Ryujinx_1.1.19_2022-02-06_13-29-40.log)

### Environment?

- Ryujinx version: 1.1.19
- Game version: N/A
- System Specs:
  - OS: Windows 10
  - CPU: i5-9600KF
  - GPU: Nvidia Geforce RTX 3060 Ti
  - RAM: 32 GB
- Applied Mods : N/A

### Additional Context

This issue is being caused by the method `EnumerateFilesToDelete` in `Updater.cs`. It returns every single file descended from the Ryujinx folder, regardless of whether the file was created by Ryujinx or not. Then `InstallUpdate` renames all these files with the ".ryuold" extension. Finally, `CleanupUpdate` deletes every file with a ".ryuold" extension. This leads to the automatic deletion of any user file stored in the Ryujinx directory.

If users aren't allowed to store their own files in the Ryujinx directory, I would suggest somehow eliminating "\share\themes", which seems like an obvious place to put themes. Otherwise I'd suggest a more robust `EnumerateFilesToDelete` that only selects files (or at least directories) that were actually created by Ryujinx.

**Comment by jparmstr** [comment]
Technically a separate issue, but a line in `ThemeHelper.cs` causes the type of the custom theme path to be reported in the error log ("Ryujinx.Common.ReactiveObject`1[System.String]") instead of the actual path.

I believe that:
`Logger.Warning?.Print(LogClass.Application, $"The \"custom_theme_path\" section in \"Config.json\" contains an invalid path: \"{ConfigurationState.Instance.Ui.CustomThemePath}\".");`

Should be:
`Logger.Warning?.Print(LogClass.Application, $"The \"custom_theme_path\" section in \"Config.json\" contains an invalid path: \"{ConfigurationState.Instance.Ui.CustomThemePath.ToString}\".");`

**Comment by marysaka** [comment]
GTK3 is being phased out in favor to Avalonia, closing as won't fix.
