### ISSUE TITLE
Updating While Start Up a Game Cause Crash and Leave .ryuold File

### ISSUE THREAD

**Issue by shinkuan** [Ryujinx/Ryujinx#3095]
### What's the issue you encountered?

I was updating from 1.1.15 to 1.1.17, meanwhile I started up Kirby Star Allies, then Ryujinx crashed after it finished loading shader caches.</br>

### How can the issue be reproduced?

Use old version of Ryujinx, and when Ryujinx ask you to update, click [Yes], then start up any game before Ryujinx complete the download.

### Log file

[Ryujinx_1.1.17_2022-02-07_16-51-12.log](https://github.com/Ryujinx/Ryujinx/files/8013754/Ryujinx_1.1.17_2022-02-07_16-51-12.log)

### Environment?

- Ryujinx version: 1.1.15</br>
- Game version: 4.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-9750H
  - GPU: NVIDIA RTX 2060
  - RAM: 32GB
- Applied Mods : Yes
  - 60FPS

### Additional context?

Additional info about your environment: After Ryujinx crashed, files in the folder got renamed to *.ryuold
![image](https://user-images.githubusercontent.com/35415788/152758273-14135575-8077-435e-9edd-d039d169a2fa.png)
How do I clean up this mess, will there be updating files left being not removed in my disk drive?

**Comment by MetrosexualGarbodor** [comment]
Redownload the emulator, the updater can sometimes fail.
