### ISSUE TITLE
Skylanders imaginator : InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000

### ISSUE THREAD

**Issue by fraf** [Ryujinx/Ryujinx#3110]
Loading skylanders with lastest version of ryujinx at this date provoke the emulator to crash.
In attachment the log file.

Resolution : native x2
Docked mode
Ignore Missing Services.

Cheers
[Ryujinx_1.1.26_2022-02-12_14-05-30.log](https://github.com/Ryujinx/Ryujinx/files/8053439/Ryujinx_1.1.26_2022-02-12_14-05-30.log)
.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
