### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by raphaelmaria** [Ryujinx/Ryujinx#3115]
## Bug Report

![2022-02-13_01-11](https://user-images.githubusercontent.com/26657697/153738270-cce28307-ea45-4446-a836-c023bd6e9f33.png)

### What's the issue you encountered?

When I download the stable version of the site, open it and try to click on settings, it shows the error.

### How can the issue be reproduced?

Downloading from the site, importing the prod.keys and trying to open the Settings menu

### Log file

[Ryujinx_1.1.26_2022-02-13_01-04-09.log](https://github.com/Ryujinx/Ryujinx/files/8054939/Ryujinx_1.1.26_2022-02-13_01-04-09.log)

### Environment?

- Ryujinx version: 1.1.26</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *Windows 10 Pro 21H2 *
  - CPU: *Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.40 GHz*
  - GPU: *Radeon RX 580 Series*
  - RAM: *32GB RAM DDR4 2133 MHz*
- Applied Mods : No

### Additional context?
I'm configuring from ground zero and having difficulties with this step, which according to the documentation, must be done before importing the games.

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
This popup doesn’t appear when you try to install the firmware instead of opening the settings window?

**Comment by raphaelmaria** [comment]
No, to install the firmware it opens right.
I'm doing the installation from scratch, to add the NSP in the future, when I try to set where it will get the games, I get this error of not opening the "Settings" menu.

But doing the import it recognizes the games but when I try to open it it freezes my whole machine.

**Comment by AcK77** [comment]
Try to go in `%AppData%\Roaming\Ryujinx\bis\system\Contents\registered`, delete everything, Do a proper dump of your switch firmware and try to reinstall it. It should fix your issue.

**Comment by raphaelmaria** [comment]
Thank you very much @AcK77, this guide solved the problem.
Flagging here as completed.

1. Close Ryujinx
2. Open "Run" in your Windows 
3. Type %AppData%
4. Then enter the "Roaming" folders
Roaming\
> -\Ryujinx
> --\bis
> ---\system
> ----\Contents
> -----\registered

5. Deletes all the contents of the directory.
6. Open Ryujinx and re-import the Firmware file.

The configuration menu will open and the games will run, without freezing the screen.
