### ISSUE TITLE
No audio in Switch Sports (Online playtest)

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#3125]
### What's the issue you encountered?

There is no audio when booting the Switch Sports online test on Ryujinx.

### How can the issue be reproduced?

Boot the NSP file (currently requires missing services) under any audio backend or volume setting.

### Environment?

- Ryujinx version: 1.1.29</br>
- Game version: 0.5</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *Ryzen 5 5600X)*
  - GPU: *RTX 3070*
  - RAM: *32GB DDR4
- Applied Mods : No

**Comment by Thog** [comment]
Related to limiter effect implementation.
