### ISSUE TITLE
olsc:u IOlscServiceForApplication: 13 (GetSaveDataBackupSetting) is not implemented

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx#3140]
olsc:u IOlscServiceForApplication: 13 (GetSaveDataBackupSetting) is not implemented [10.0.0+]

[Switchbrew](https://switchbrew.org/wiki/OLSC_services#olsc:u)

### Service description
```
n/a
```

### Required by: 
Ryujinx/Ryujinx-Games-List#250 v2.0.5

**Comment by AcK77** [comment]
How to reach this call in ACNH? Does it throw that during game boot or later in menu?

**Comment by GamerzHell9137** [comment]
> How to reach this call in ACNH? Does it throw that during game boot or later in menu?

When booting the game
