### ISSUE TITLE
(Regression) Demon's Crystals - 0100A2B00BD88000 crashes out nearly straight away 

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#3146]
### What's the issue you encountered?
just load the game and it crashes out nearly straight away

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[Ryujinx_1.1.45_2022-02-19_17-32-14.log](https://github.com/Ryujinx/Ryujinx/files/8101836/Ryujinx_1.1.45_2022-02-19_17-32-14.log)

### Environment?

- Ryujinx version: 1.1.45
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.3
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by benderscruffy** [comment]
still an issue in 1.1.240

**Comment by EmulationFanatic** [comment]
This is still a valid issue as it is a regression. However, to speed up identification of the issue, please list the last build number where this game was known to be working.

**Comment by benderscruffy** [comment]
Has been reported in the game compatibility list as a regression
Is more detailed with the build that broke it
