### ISSUE TITLE
Unhandled exception caught : System.InvalidOperationException: Cache collision found

### ISSUE THREAD

**Issue by libilibinho** [Ryujinx/Ryujinx#3147]
## Bug Report

Whenever I try to initiate the game Pokemon Legend Arceus, a error occurs and  it closes mid load.
</br>

### What's the issue you encountered?

</br>
I initialized the PC and turned on Ryujinx to play Pokemon Legend Arceus,
</br>
I updated Ryujinx to version 1.1.46

### How can the issue be reproduced?

Open Ryujinx and start Pokemon Legend Arceus.
### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.1.46</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.2</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10(e.g. Windows 10)*
  - CPU: i7-10750H(e.g. i7-6700)*
  - GPU: NVIDIA RTX 2070(e.g. NVIDIA RTX 2070)*
  - RAM: 16GB(e.g. 16GB)*
- Applied Mods : No [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]
![ryujinx error ver1 1 46](https://user-images.githubusercontent.com/100060032/154829295-c955b71a-b34c-4d8e-a9d7-8bad3ac321bb.png)

**Comment by libilibinho** [comment]
My log
[Ryujinx_1.1.46_2022-02-20_01-56-05.log](https://github.com/Ryujinx/Ryujinx/files/8103476/Ryujinx_1.1.46_2022-02-20_01-56-05.log)
[Ryujinx_1.1.46_2022-02-20_01-56-19.log](https://github.com/Ryujinx/Ryujinx/files/8103477/Ryujinx_1.1.46_2022-02-20_01-56-19.log)
[Ryujinx_1.1.46_2022-02-20_01-56-34.log](https://github.com/Ryujinx/Ryujinx/files/8103478/Ryujinx_1.1.46_2022-02-20_01-56-34.log)
s

**Comment by MetrosexualGarbodor** [comment]
Right click the game > cache management > purge shader cache.
And please don't open issues for help, come to Discord instead. https://discord.gg/ryujinx
