### ISSUE TITLE
Dont starve Switch Edition Missing Service

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#315]
https://gist.github.com/ReaperOfSouls1909/bce83df7d5a1b52076cac0fca8d86b42 
if this gets pr'ed i will update this thread also 
![unknown 1](https://user-images.githubusercontent.com/18043258/43387326-85603cbc-93bc-11e8-9c02-865b95819d27.png)

**Comment by ReaperOfSouls1909** [comment]
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/2240349/Ryujinx.log)

**Comment by ReaperOfSouls1909** [comment]
#234 solved the opcode and now Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801 log : https://gist.github.com/ReaperOfSouls1909/e8762f107aa89a4cec00e6d54b8a73de

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/60
