### ISSUE TITLE
Regression in rendering of Arcaea due to cda65995

### ISSUE THREAD

**Issue by samrose258** [Ryujinx/Ryujinx#3150]
## Bug Report

Apologies if this is not in the correct place for an issue like this.

### What's the issue you encountered?

In any Ryujinx build from commit cda65995 and newer, levels in the game Arcaea (0100E680149DC000) have incorrect rendering that was not present beforehand. This happens regardless of the NVIDIA driver version (511.79 at the time of writing).

Expected output (taken from LDN 2.4 build as suggested by a user in the Ryujinx Discord server):
![image](https://user-images.githubusercontent.com/44942762/154995787-fcc947d1-c74c-451c-a0dc-c35c77e9a619.png)

Actual output (taken from latest Ryujinx release, 1.1.46):
![image](https://user-images.githubusercontent.com/44942762/154995983-4c7c8f25-449a-4730-9fb5-e452015340dc.png)

### How can the issue be reproduced?

1. Clone the Ryujinx repository
2. Checkout to commit cda659955ced1b16839cdd1e7fea1ef6f8d99041
3. Build debug or release
4. Launch Arcaea
5. Start any level

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.0-dirty (commit cda65995 and newer)</br>
- Game version: 1.2.2</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 3600
  - GPU: NVIDIA RTX 3060
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by benderscruffy** [comment]
is this still a problem

**Comment by samrose258** [comment]
Ah, hello. After testing the Vulkan build of 1.1.233 and newer, I can confirm that this regression is no longer the case when using the Vulkan backend. Closing this issue as it will no longer affect users who use Ryujinx as they will only need to change their graphics backend to Vulkan.
