### ISSUE TITLE
Dragon Quest Hero's 1-3 needs services 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#316]
https://gist.github.com/ReaperOfSouls1909/bea2b345defdbaad0565f4b1d5dc52e9 

Unhandled Exception: System.NotImplementedException: time:u ITimeZoneService: 202

**Comment by HorrorTroll** [comment]
#327 will help u pass that error!

But the games is missing texture, crash when goes in-games

**Comment by greggameplayer** [comment]
what texture format ?

**Comment by HorrorTroll** [comment]
3D render, and 3D texture

https://i.imgur.com/UkMyF4G.png

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/58
