### ISSUE TITLE
(Regression) Pinball FX3 [0100DB7003828800] crashes out on developers screen

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#3164]
### What's the issue you encountered?
load the game and it crashes out at the first developers screen (Zen Studio screen)

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file
[Ryujinx_1.1.54_2022-02-27_12-00-52.log](https://github.com/Ryujinx/Ryujinx/files/8148019/Ryujinx_1.1.54_2022-02-27_12-00-52.log)

### Environment?

- Ryujinx version: 1.1.54
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MutantAura** [comment]
Did this start to happen on 1.1.54 or can you highlight a specific version where it broke?

**Comment by gdkchan** [comment]
This is unlikely to be a real regression, it is an issue creating save data. Creating and using a new user profile would likely solve the issue.

**Comment by benderscruffy** [comment]
deleted the save directory
still cannot get ingame
can get a bit further but keeps crashing out
[Ryujinx_1.1.54_2022-02-28_18-17-48.log](https://github.com/Ryujinx/Ryujinx/files/8152510/Ryujinx_1.1.54_2022-02-28_18-17-48.log)

**Comment by AcK77** [comment]
"Creating and using a new user profile would likely solve the issue." and sets Guest Internet Access and Ignore Missing Services to false.

**Comment by benderscruffy** [comment]
i did all of those suggestions and it still crashes out before going ingame
