### ISSUE TITLE
Shader precompilation

### ISSUE THREAD

**Issue by Alainx277** [Ryujinx/Ryujinx#3165]
#### Overview:

The shader cache allows already compiled shaders to be reused efficiently. However, when running a new game, every new shader lags the game, as it needs to be compiled synchronously.
It would be useful to have a feature that compiles all the shaders in a game's assets at once, before playing it.

#### Nature of Request:  

- Addition

### Why would this feature be useful?

This moves the laggy shader compilation to a separate step, where a user can do other things, instead of during gameplay. It is especially useful for multiplayer games, as shader compilation can dissolve the party entirely due to network lag.

**Comment by MutantAura** [comment]
This is a technical impossibility. Ryujinx or any other emulator has no way of knowing what is a shader and what isn't until one is called. You cannot simply search the game files for "shaders" and then compile them. The best you can do is make the translation process when a shader is called more efficient and find quicker paths for that.

**Comment by gdkchan** [comment]
This is technically possible by searching for shaders on the game romfs, however supporting all the different game container formats and compression would be unfeasible, as there are many different games and engines out there that stores shaders in different formats, and I don't think a solution that only supports some games would be desirable. Vulkan with SPIR-V (#2518) already reduces the shader compilation times and the stutters a lot, and is how we plan to address this issue going forward.

**Comment by D-Maxwell** [comment]
> This is a technical impossibility. Ryujinx or any other emulator has no way of knowing what is a shader and what isn't until one is called. You cannot simply search the game files for "shaders" and then compile them. The best you can do is make the translation process when a shader is called more efficient and find quicker paths for that.

Since using other's generated shader cache can cause compatibility issues ; and since knowing beforehand what constitutes a shader is impossible as you have stated ; perhaps one could instead simply *log* each shader call, and then this file which would contain a list of all shader calls could be read by other instances of the emulator to tell what to pregenerate, from what resources, and under which conditions ?
