### ISSUE TITLE
Some simulator problems in Linux Environment

### ISSUE THREAD

**Issue by HuMingYi** [Ryujinx/Ryujinx#3166]
Hello, ryujinx team
In the ryujinx form in Linux environment, right-click to open the folder where mod is located, but it will not appear. What's the reason?
I also want to know which folder mod should be placed in under linux environment? Windows is the ROMs folder under the mod storage folder opened by right clicking

**Comment by edisionnano** [comment]
You better come at the discord server for help instead of opening an issue

**Comment by HuMingYi** [comment]
OK

**Comment by HuMingYi** [comment]
> 您最好到 discord 服务器寻求帮助，而不是打开问题

OK
