### ISSUE TITLE
Dying Light does not render after intro video

### ISSUE THREAD

**Issue by adambennett08330** [Ryujinx/Ryujinx#3168]
## Bug Report
When first boot up game the intro FMV starts from start to finish then theres nothing, but a black screen. FMV has sound. Cant use controls to skip FMV. Tried waiting 30 minutes thinking it was just shaders compiling, but still black screen

### Environment?

Ryujinx version: ryujinx-1.1.54-win_x64

- System Specs:
OS: Windows 10 
Storage: NVME SSD 
CPU: AMD Ryzen 5 4600H 3GHz 
RAM: 8gb (3200MHz) 
GPU: Geforce RTX 1650 TI 4GB GDDR6 1585MHz
- Applied Mods : None

### Additional context?

Additional info about your environment:

**Comment by Mou-Ikkai** [comment]
Issue already reported on the Ryujinx-Games-List: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3743

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
