### ISSUE TITLE
Rayman Legends Definitive Edition [01005FF002E2A000] doesn't detect handheld mode

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#3169]
### What's the issue you encountered?
on the main gallery go to Murfy's Touch
it wont let me enter
it says you need to switch to handheld mode and as you can see i did that at the very start
![Capture](https://user-images.githubusercontent.com/2696404/156158890-d62d5192-eff6-4692-806b-b3de1d39e043.PNG)

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file
[Ryujinx_1.1.54_2022-03-01_18-58-21.log](https://github.com/Ryujinx/Ryujinx/files/8161103/Ryujinx_1.1.54_2022-03-01_18-58-21.log)

### Environment?

- Ryujinx version: 1.1.54
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by german77** [comment]
Make sure you turned the P1 off and handheld on in your controller config

**Comment by german77** [comment]
just click with the mouse?

**Comment by benderscruffy** [comment]
i did and nothing was happening
this matter is closed as it is not a problem
