### ISSUE TITLE
Fantasy Hero Unsigned Legacy Needs Texture format 0x3a z16

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#317]
https://gist.github.com/ReaperOfSouls1909/76797b805d7732f0e53b8c69a850a6db thats part of the log 
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/2240472/Ryujinx.log) here is the rest and it loads https://cdn.discordapp.com/attachments/468538246763249674/473418958679048195/unknown.png and right at menu crashes

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/62
