### ISSUE TITLE
Loading game crash on Linux: Xenoblade Chronicle DE

### ISSUE THREAD

**Issue by Raz-Yagami** [Ryujinx/Ryujinx#3172]
## Bug Report

Fail to run Opengl many try

### What's the issue you encountered?

Crash try running the game on Linux

### How can the issue be reproduced?

Loading the game

### Log file
[Ryujinx_1.1.55_2022-03-03_10-54-26.log](https://github.com/Ryujinx/Ryujinx/files/8182712/Ryujinx_1.1.55_2022-03-03_10-54-26.log)
[Ryujinx_1.1.55_2022-03-03_10-55-28.log](https://github.com/Ryujinx/Ryujinx/files/8182713/Ryujinx_1.1.55_2022-03-03_10-55-28.log)
[Ryujinx_1.1.55_2022-03-03_10-55-54.log](https://github.com/Ryujinx/Ryujinx/files/8182714/Ryujinx_1.1.55_2022-03-03_10-55-54.log)

### Environment?

- Ryujinx version: 1.1.55</br>

- Game version: 1.1.2</br>

- System Specs:
  - OS: Garuda Linux 5.16.11 zen
  - CPU: AMD Ryzen 5 5600x
  - GPU: Nvidia GTX 1070 8 GB driver 510.54
  - RAM: 16GB 3200 mhz
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Gnome desktop using, and always updated never try to load on linux just on Windows 11 working fine

**Comment by edisionnano** [comment]
Come to our Discord for help in the linux-master-race channel

**Comment by Raz-Yagami** [comment]
Fixed denied access only Xenoblade 1 was with it the rest game where fine
