### ISSUE TITLE
Animal Crossing: New Horizons [01006F80023226000] crashes the program when attempting to scan an Amiibo on Linux

### ISSUE THREAD

**Issue by RLarkins** [Ryujinx/Ryujinx#3183]
### What's the issue you encountered?

When attempting to scan an Amiibo at the machine in the Resident Services, the program crashes and closes. The final messages on the console are
```
00:02:45.295 |I| HLE.OsThread.9 ServiceNv Create: Created map 1426 with size 0x0006a000!
00:02:45.299 |I| HLE.OsThread.9 ServiceNv Create: Created map 1427 with size 0x00001000!
00:02:45.301 |I| HLE.OsThread.9 ServiceNv Create: Created map 1431 with size 0x00002000!
00:02:45.320 |I| HLE.OsThread.9 ServiceNv Create: Created map 1432 with size 0x00001000!
00:02:45.321 |I| HLE.OsThread.9 ServiceNv Create: Created map 2380 with size 0x00003000!
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
The messages in the log before that are related to saving data, so I'm not inclined to believe they're directly related to the situation.

### How can the issue be reproduced?

- Load a save file
- Move your character into Resident Services, and use the ABD
- Choose "Scan Amiibo"
- Choose amiibo to scan in the program's Amiibo browser

### Log file

Log file for the session up to the crash will be attached to post. Note that the "stack smashing detected" message seems to be a native Linux message, so it is not present in the log, but happened right after the final log message.

### Environment?

- Ryujinx version: *1.1.20 (Nightly as of Feb 09)*
- Game version: *2.0.4*
- System Specs:
  - OS: *Arch Linux (Kernel 5.15.25)*
  - CPU: *AMD Ryzen 5 2600*
  - GPU: *AMD RX 570*
  - RAM: *12GB*
- Applied Mods : No

**Comment by piplup55** [comment]
similar error happens on kirby and the forgotten land aswell
![image](https://user-images.githubusercontent.com/100526773/164792751-022de945-25e9-4f49-b558-c48cce10b85b.png)

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.

**Comment by TSRBerry** [comment]
This is issue is fixed by running Ryujinx with this environment variable set: `COMPlus_EnableAlternateStackCheck=1`

**Comment by gdkchan** [comment]
Why was this closed? The issue was not fixed.

**Comment by TSRBerry** [comment]
Why not?
As @riperiperi explains here https://github.com/Ryujinx/Ryujinx/pull/3437#issuecomment-1179576235 this is the only way for Linux users to make the dotnet runtime perform the correct checks.
This would also be default behavior if Microsoft didn't decide against it: https://github.com/dotnet/runtime/issues/1318

**Comment by gdkchan** [comment]
Is setting environment variables to non-default values considered a solution? If so there are a few other Linux issues that should be closed aswell.

**Comment by TSRBerry** [comment]
I see what you mean.

Since there isn't really another good way to do this, I'd say it's probably a solution? I know especially on Linux there are a few issues that can be solved setting env vars, so it might be a good idea to collect them and put them in a separate issue?
Just to make clearer that this is not specific to any game.

**Comment by Bateman421** [comment]
> This is issue is fixed by running Ryujinx with this environment variable set: `COMPlus_EnableAlternateStackCheck=1`

Sorry my ignorance, but how do I do this?, is this in a specific file or is it like a global environment variable?

**Comment by Bateman421** [comment]
Well, as of today 28/04/2023

On steam deck have the same exact issue trying to use amiibo, I'm also trying to use the environment variable fix, but still does nothing, and also on the logs it throws me nothing

I'm using 
- Ryujinx 1.1.738
- No Mods
- Whatever the specs for the steam deck are

The next is the last lines in the log file

`00:02:02.821 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 96
 UserId: 00000000000000010000000000000000
 Room: save_event_flag_player
 Report: {
    "AppCmn": {
        "VillageDaysCount": 16,
        "GameRegion": 0,
        "Language": "USes",
        "WeatherArea": 0,
        "LocalVid": 3584094176,
        "LandName": "New Rohan",
        "LandRuby": 2,
        "LocalPid": 2294276286,
        "PlayerName": "Kevin",
        "POLID": {
            "TypeCode": 0,
            "Value": "0x0000000000000000"
        },
        "POPID": {
            "TypeCode": 0,
            "Value": "0x0000000000000000"
        },
        "Gender": {
            "TypeCode": 0,
            "Value": "0x0000000000000000"
        },
        "IsLandMaker": 1,
        "IsMoveVillager": 0,
        "gc_recorded_at": "2023-04-28 21:17:37",
        "LandPlayTime": 67127,
        "PlayerPlayTimeMain": 58260,
        "PlayerPlayTimeAll": 58260
    },
    "SerialNumber": {
        "TypeCode": 0,
        "Value": "0x00000000000003B1"
    },
    "UniqueID": {
        "TypeCode": 0,
        "Value": "0x00000000000001B7"
    },
    "PreValue": 0,
    "PostValue": 1,
    "PlayerInfo": {
        "CurHaveMoney": {
            "TypeCode": 0,
            "Value": "0x000000000000520D"
        },
        "CurMilePoint": 7210,
        "HouseLevel": 3,
        "HouseExtension": 2
    }
}`
