### ISSUE TITLE
Go vacation not allowing more than 2 registered users at a time

### ISSUE THREAD

**Issue by eugenecat** [Ryujinx/Ryujinx#3195]
hello! i have been trying to add mii of my close friend, while playing go vacation nsp, and it erased my mii. and vice versa, when i attempt to add mine back, and itd casually erase mii of my close friend. any solution?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
