### ISSUE TITLE
Entering/Leaving buildings in Pokemon Sword crashes Ryujinx

### ISSUE THREAD

**Issue by Miodini** [Ryujinx/Ryujinx#3197]
## Bug Report

</br>

### What's the issue you encountered?

While playing Pokémon Sword, Ryujinx crashed when entering or leaving buildings in Motostoke City. </br>
The only change I made was set Anisotropic Filtering at 4x</br>

### How can the issue be reproduced?

On Pokémon Sword, head to Motostoke City and enter and leave buildings. It some times crashes the emulator. Most of the crashes I got was entering/leaving the gym.

### Log file
[Ryujinx_1.1.69_2022-03-13_21-54-49.log](https://github.com/Ryujinx/Ryujinx/files/8241040/Ryujinx_1.1.69_2022-03-13_21-54-49.log)
[Ryujinx_1.1.69_2022-03-13_21-38-02.log](https://github.com/Ryujinx/Ryujinx/files/8241041/Ryujinx_1.1.69_2022-03-13_21-38-02.log)
[Ryujinx_1.1.69_2022-03-13_21-51-11.log](https://github.com/Ryujinx/Ryujinx/files/8241042/Ryujinx_1.1.69_2022-03-13_21-51-11.log)
</br>

### Environment?

- Ryujinx version: 1.1.69</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-7700
  - GPU: GTX 1060 6GB
  - RAM: 16GB

- Applied Mods : No

### Additional context?

Additional info about your environment: It started after updating Ryujinx, but can't confirm this is the cause.</br>
Reverting the Anisotropic Filtering to Auto still triggers the crash. GPU usage was fine in Task Manager</br>
All crashes appear to be due to "GPU.MainThread Application : Unhandled exception caught: System.ArgumentException", but for different errors.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
