### ISSUE TITLE
Pokken tournament crash on boot

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3200]
### How can the issue be reproduced?

boot the game
ryujinx crashes

### Log file
[Ryujinx_1.1.69_2022-03-14_11-54-24.log](https://github.com/Ryujinx/Ryujinx/files/8244141/Ryujinx_1.1.69_2022-03-14_11-54-24.log)

### Environment?

- Ryujinx version: 1.1.69
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.3.3</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: archlinux
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16
- Applied Mods : no

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment]
![image](https://user-images.githubusercontent.com/4905390/158426300-36ad9c6e-bad6-435a-a0ea-574daed05600.png)

I'm unable to reproduce your issue. I suggest you to go on our discord for support.
It seems you running Ryujinx on ArchLinux so it's probably a bad settings or something with your system. Your log file is a bit strange, I suggest you to leave things as default.

**Comment by A-w-x** [comment]
i ll try other settings but have you tried on intel gpu? because it is nvidia there, maybe it is specific to intel?
