### ISSUE TITLE
Disgaea 6 frequently freezes.

### ISSUE THREAD

**Issue by ddrake2006** [Ryujinx/Ryujinx#3203]
### What's the issue you encountered?

I am playing Disgaea 6 with all the DLC and patch 1.0.5. Upon nearly any load screen and many battle events the game will freeze. The game will stay frozen unless I click the "Pause Emulation" and "Resume Emulation" buttons. 

As far as I know my Ryujinx is vanilla. 

### How can the issue be reproduced?

Simply install the game with DLC/Patch and notice how the game frequently freezes. 

### Log file

Log is attached.

[Ryujinx_1.1.69_2022-03-14_13-10-01.log](https://github.com/Ryujinx/Ryujinx/files/8247699/Ryujinx_1.1.69_2022-03-14_13-10-01.log)

### Environment?

- Ryujinx version:  1.1.69

- Game version: 1.0.5

- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 9 5900x
  - GPU: Nvidia 3080
  - RAM: 32GB
- Applied Mods : No

I would be pleased if this were something silly that I overlooked but I did a large amount of searching and did not see any other reports of this issue.

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
