### ISSUE TITLE
[Regression] Monopoly FPS tanks with #2991

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#3209]
## Bug Report

FPS tanks from 100 FPS to 15 FPS with #2991 

### Environment?

Ryujinx version: 1.1.76
Game version: 1.0.4

System Specs:

OS: Windows 10
CPU: Ryzen 3600
GPU: GTX 960 2 GB
RAM: 16 GB

Applied Mods : No

### Screenshots

Before it was merged

![image](https://user-images.githubusercontent.com/2002038/158800145-1632e7ca-ac24-4ae3-832e-fc15eb24a7d5.png)

When it got merged

![image](https://user-images.githubusercontent.com/2002038/158800333-5973ae20-59e3-4c39-8b64-51443f1a9fe4.png)

**Comment by benderscruffy** [comment]
is this still a problem

**Comment by GamerzHell9137** [comment]
Issue is still present.

![image](https://user-images.githubusercontent.com/2002038/236542804-56bf0c69-63fa-4e7d-bb74-16f0070322a7.png)

**Comment by AcK77** [comment]
Fixed by #6260
