### ISSUE TITLE
Breath of the Wild Wind/Grass particle effects are static

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#3213]
### What's the issue you encountered?

Certain particle effects like grass and other particles blowing in the wind don't seem to render correctly compared to hardware. They appear as static objects fading in and out of view. See videos below.

Switch:

https://user-images.githubusercontent.com/44103205/159062082-52ab920b-694f-4d7b-b2b8-06c9b94c65f6.mp4

Ryujinx:

https://user-images.githubusercontent.com/44103205/159062185-4f16ce5d-96a6-4c30-b646-6ec628cc1ecd.mp4

### How can the issue be reproduced?

Stand anywhere where it's windy/grass particle effects show (fast travel to Hateno Research Lab is used for the above two videos) and observe how the grass effect doesn't seem to move with the wind.

### Environment?

- Ryujinx version: 1.1.76
- Game version: 1.6.0
- System Specs:
  - OS: *Windows 10*
  - CPU: *R5 5600X*
  - GPU: *NVIDIA RTX 3070*
  - RAM: *32GB DDR4*
- Applied Mods: No 

### Additional context?

Not a regression, seems to have always been an issue.

**Comment by Haronee** [comment]
This issue has been reported to also occur on Vulkan.

https://user-images.githubusercontent.com/53187465/161390944-49a65b0c-6be6-474a-9807-87703980a5dd.mp4

**Comment by combo-pizza** [comment]
Rain also doesn't react to camera movement which is interesting. Particles in this game seem to not like emulation

**Comment by Linear524** [comment]
I remember the same issue was on CEMU with BoTW game. All dynamic particles just stays on their initial coordinate, even if wind tries to work. They called this issue "vertex streamout error" and it was quickly fixed by Exzap...
I think Ryujinx just needed the very same fix and then BoTW will be fully playable ! :)
P.S. - yuzu emu team has already fixed this issue...

**Comment by riperiperi** [comment]
I have no idea what "vertex streamout" is, and the closest thing to it is transform feedback, which this game does not use.

Please don't compare this emulator to CEMU, the graphics hardware is completely different.

**Comment by ayurai** [comment]
I suppose he means that 
![image](https://user-images.githubusercontent.com/20160968/172473509-4afb40a8-2a75-4f9d-9dca-80a3403b3265.png)
And maybe that ?
![image](https://user-images.githubusercontent.com/20160968/172473607-0df0ed60-6529-4528-a132-ce2f9ea30cb2.png)

which i dont think that help in anyway.. but who knows

**Comment by Linear524** [comment]
@ayurai 
Yup ! Exactly this feature.
Currently Ryujinx doesn't calculate coordinates of the particles with any force applied (wind, explosion, inertia, etc...)
So all particles just stays on their initial spawn position.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Comment by Linear524** [comment]
Holy S#1t !!! 
Latest master branch renders BoTW particles correctly with wind motion applied ! :)
So this means that issue with particles movement is finally fixed !!! =)

**Comment by TomTurbine** [comment]
I think there might be a regression on this. When you start a new game, lots of static.

Using the current version of Ryujinx while on an Ryzen 5900x with 64GB RAM and a RTX 2080 GPU.
