### ISSUE TITLE
Need for Vulkan-LDN build

### ISSUE THREAD

**Issue by FAB5FREDDIE14** [Ryujinx/Ryujinx#3216]
I use Ryujinx mainly for Pokemon Legends: Arceus and FAR: Changing Tides. My issue with graphics was fixed with the Vulkan Backend version, but i want to connect Legends: Arceus to the internet. There's the LDN version too, but it does not allow for the Vulkan Backend. I would like if you could make a version with both LDN and Vulkan. If such a version exists, though, then just please link it down here.
Thanks.

**Comment by MetrosexualGarbodor** [comment]
Vulkan is not ready for LDN, otherwise it would have been added already. The devs are fully aware of this and are working on it, so I'll close this.
