### ISSUE TITLE
[Feature Request] Hotkeys for Pause/Resume/Stop Emulation

### ISSUE THREAD

**Issue by Moa4sh** [Ryujinx/Ryujinx#3221]
#### Overview:
Add hotkeys for Actions menu items: Pause, Resume, and Stop Emulation.

#### Smaller Details: 
N/A

#### Nature of Request:  
- Addition

### Why would this feature be useful?
For users that regularly pause/resume emulation, just like a pause button in games, it is very handy to have as compared to having to manually mouse to the menu and choose each option each time. Especially for users that may be playing full screen and don't have the menu toolbar visible during gameplay. 

For me personally, I pause often when I tab away from Ryujinx because it makes my PC run hot and fans run on high speed unnecessarily when I'm doing other activities.

**Comment by MutantAura** [comment]
Pause/Resume = F5
Stop emulation = Escape (when not in fullscreen)

**Comment by Moa4sh** [comment]
Shoot, had no idea, thanks!

**Comment by MutantAura** [comment]
Escape is a bit bugged currently but it's fixed in the UI rewrite. It uses the same text as closing the program (it doesn't it just ends emulation) and the window also pops up whenever you open a new game. Kinda annoying but like I say both fixed in #2507

**Comment by saldabain** [comment]
The shortcut keys should really be added to the MenuItems in the UI. May not be worth it if avalonia fixes this, but it would be good to consider since hotkeys aren't really obvious to the user.
