### ISSUE TITLE
Audio is heavily delayed and choppy after launching a game

### ISSUE THREAD

**Issue by the-Astra** [Ryujinx/Ryujinx#3222]
### What's the issue you encountered?

After opening any game through the Ryujinx menu, the game itself starts up fine, but the audio is extremely choppy and does not line up with what is being displayed (for example, pressing L and R in MK8D will bring me to the main menu, but won't play the sound cue until ~5-10 seconds later). I have tried multiple things, including running fresh XCIs and purging the shader cache to no avail.

### How can the issue be reproduced?

Open any game. That's really about it.

### Log file

[Ryujinx_1.1.81_2022-03-21_00-41-16.log](https://github.com/Ryujinx/Ryujinx/files/8313224/Ryujinx_1.1.81_2022-03-21_00-41-16.log)

### Environment?

- Ryujinx version: 1.1.81</br>
- Game version: MK8D 2.0.0 (also tested with 1.7.2)</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 5900HS 
  - GPU: NVIDIA GeForce RTX 3060 Laptop
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
[ N/A ]

**Comment by the-Astra** [comment]
Adding onto this thread, this video shows what I'm talking about

https://user-images.githubusercontent.com/75325082/159208548-d47cec78-e908-4e8d-96b8-37e15fe5a089.mp4

**Comment by yell0wsuit** [comment]
Try changing audio backend to SDL2

**Comment by the-Astra** [comment]
> Try changing audio backend to SDL2

It's already on that setting

**Comment by the-Astra** [comment]
I changed the audio backend to OpenAL and that seems to have fixed it. Hopefully this helps anyone else with this problem
