### ISSUE TITLE
Bug: Kirby and the Forgotten Land - 01004D300C5AE000 spams log with in GPU.MainThread Gpu GetInfo: Invalid texture format 0x7FFFF (sRGB: False).

### ISSUE THREAD

**Issue by mstreurman** [Ryujinx/Ryujinx#3231]
### What's the issue you encountered?

The game spams the log with GPU.MainThread Gpu GetInfo: Invalid texture format 0x7FFFF (sRGB: False).

### How can the issue be reproduced?

Start the game and start a leveL

### Log file

[Ryujinx_1.1.84_2022-03-25_07-03-28.log](https://github.com/Ryujinx/Ryujinx/files/8347923/Ryujinx_1.1.84_2022-03-25_07-03-28.log)

### Environment?

- Ryujinx version: 1.0.84</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 11 Professional build 22000
  - CPU: i9-9900k
  - GPU: Gigabyte GeForce RTX2080TI Windforce with driver 512.15
  - RAM: 2*8GB DDR4 3400MHz
- Applied Mods: NO

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
