### ISSUE TITLE
Graphical bug on Dragon Quest 2 in Vulkan/Opengl

### ISSUE THREAD

**Issue by qiuyang1008** [Ryujinx/Ryujinx#3233]
## Bug Report

There're some graphical bugs in the battle interface and main maps.

Battle graphics seem to do this with the first battle upon entering the area (If I just exited a town/castle/dungeon), and the same with the map errors, though the map graphics errors stay until I exit the area (Even between fights)

![1](https://user-images.githubusercontent.com/38851431/160228770-e6f4e7ed-205e-4109-9d71-22ff36a7e716.png)
![2](https://user-images.githubusercontent.com/38851431/160228773-a55ed6ef-2a66-40e3-bbfb-04ea6e6c2ecf.png)
![3](https://user-images.githubusercontent.com/38851431/160228775-1527eab6-0be4-4a22-a23b-6ddd9596a0e5.png)
![4](https://user-images.githubusercontent.com/38851431/160228776-d3fc8aa4-8423-4e36-87d4-391cb72a82d9.png)
![5](https://user-images.githubusercontent.com/38851431/160228777-00128771-bc07-4587-b44c-69af1482e043.png)

**Comment by qiuyang1008** [comment]
Environment?
Ryujinx version: 1.1.84

System Specs:

OS: Windows 10 Version 2009
CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz | AVX512 | FMA
GPU: Nvidia Titan Xp
RAM: 32 GiB

Applied Mods : No

**Comment by EmulationFanatic** [comment]
This is probably fixed now, but please re-test and then post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
