### ISSUE TITLE
Multi-Title XCI game compilations only show one of the available titles.

### ISSUE THREAD

**Issue by ghost** [Ryujinx/Ryujinx#3234]
### What's the issue you encountered?

I was trying to load the game compilation "Danganronpa Decadence" into Ryujinx but unfortunately only one of the available titles in the compilation, Danganronpa S, appears in Ryujinx's game list.

### How can the issue be reproduced?

Load "Danganronpa Decadence" or any other cartridge collection that has multiple titles into Ryujinx.

### Log file

[Ryujinx_1.1.85_2022-03-26_16-12-59.log](https://github.com/Ryujinx/Ryujinx/files/8356265/Ryujinx_1.1.85_2022-03-26_16-12-59.log)

### Environment?

- Ryujinx version: 1.1.85</br>
- Game version: 1.0.0.</br>
- System Specs:
  - OS: *Windows 11*
  - CPU: *Ryzen 5 2600*
  - GPU: *NVIDIA RTX 2060*
  - RAM: *16 GB*
- Applied Mods : No

**Comment by gdkchan** [comment]
Is it just showing incorrectly on the game list? Because I have a few titles here with more than one NCA inside and they are working correctly.

**Comment by VermillionRED** [comment]
The only title that appears in the list is Danganronpa S. It does boot that title perfectly fine and I included that log file in my initial report.
![image](https://user-images.githubusercontent.com/29635223/160255928-af2bed2c-bd0b-40ba-9cbd-3d62d1267ec2.png)

**Comment by randomdice101** [comment]
Same issue shows up for Robotics;Notes dual pack. Dumping them as NSP shows both (that's how I got danganronpa to work)
![image](https://user-images.githubusercontent.com/4016932/181063665-54b07468-8dcb-4217-8f85-79e4fbb4b401.png)

**Comment by piplup55** [comment]
gta trilogy is also affected by this
![image](https://user-images.githubusercontent.com/100526773/213540668-44db4376-4643-4034-afc3-b8fe7dfa2fd6.png)

**Comment by Istador** [comment]
Additional multi-title XCI games affected:
- `A Good Snowman [0100423013306000][v65536] + A Monster's Expedition [0100C01013302000][v196608] + Cosmic Express [0100334013308000][v196608] + Sokobond [0100DF8013304000][v131072].xci`
  - Shows as `Sokobond` only.
- `Ankora_ Lost Days [0100D720131FC000][v262144] + Deiland [0100D150131F8000][v131072].xci`
  - Shows as `Deiland` only.
- `Chaos on Deponia [01002C900C9AC000][v65536] + Deponia [010023600C704000][v131072] + Deponia Doomsday [010024000C852000][v131072] + Goodybe Deponia [0100CA500C90C000][v131072].xci`
  - Shows as `Deponia Doomsday` only.
- `RIVE_ Ultimate Edition [010069C00401A000][v131072] + Swap This! [010005500ADDC000][v196608].xci`
  - Shows as `Swap This!` only.

**Comment by frafes** [comment]
Same issue with the following games, both XCI:

- Axiom Verge 1 & 2 Double Pack
- Final Fantasy Pixel Remaster Collection

**Comment by Volodesi** [comment]
This is happening with the Etrian Odyssey collection as well.

**Comment by KscireGamer** [comment]
Same issue with the Metal Gear Solid – Master Collection Vol.1 Switch

**Comment by joaociocca** [comment]
Same happens with Etrian Odyssey Origins Collection I II III HD REMASTER `[01007FC017FE2000+0100680017FE4000+010078A017FE6000]`. Here Ryujinx shows only the third game, despite recognizing the XCI file and the full correct size of 3.7GB

**Comment by hyde0208** [comment]
Same issue Double Dragon Collection

**Comment by bonochao** [comment]
Converting those XCI to NSP would produce separate files, which would solve this issue.
https://github.com/dezem/SAK

**Comment by joaociocca** [comment]
> Converting those XCI to NSP would produce separate files, which would solve this issue. https://github.com/dezem/SAK

too bad it's a Windows-only solution, also
