### ISSUE TITLE
Divinity Original Sin 2 - 010027400CDC6000 doesn't work anymore

### ISSUE THREAD

**Issue by SaintZeroZ** [Ryujinx/Ryujinx#3237]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
Divinity Original Sin 2 crashes when you go to story single player and press classic

[ Did you make any changes related to Ryujinx itself? ]</br>
I tried the original version and the updated version both with and without guest internet access both crashed.

### How can the issue be reproduced?
Boot up the game. Go to story, then single player, then classic mode.

### Log file
[Ryujinx_1.1.85_2022-03-27_16-23-36.log](https://github.com/Ryujinx/Ryujinx/files/8358436/Ryujinx_1.1.85_2022-03-27_16-23-36.log)

### Environment?

- Ryujinx version: 1.1.85</br>

- Game version: 1.0.0 and 1.0.10</br>

- System Specs:
    OS:   Windows 10
    CPU: i5-8400
    GPU: NVIDIA RTX 1060 3gb
    RAM: 8GB

- Applied Mods : [  No ]

### Additional context? 
![ryujinx screenshot](https://user-images.githubusercontent.com/92452497/160299916-6577dbb2-a069-4b37-b7ef-c329f59f35d5.PNG)

**Comment by MutantAura** [comment]
Closing in favour of #3236 all logs and relevant info have been copied over.
