### ISSUE TITLE
Compilation error on shaders with textureSize on multisample textures

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#3238]
### What's the issue you encountered?

OpenGL with GLSL and Vulkan with GLSL to SPIRV conversion show broken effects in Rune Factory 5.
Was randomly found by checking the SPIR V Vulkan build which does show the effect properly.

Vulkan with GLSL conversion is showing in the logs that '''GL_EXT_texture_shadow_lod''' isn't supported while OpenGL doesn't report anything. The issue seems not on happen on SPIR V since its doing the effect differently (?)

More games that use the effect:
```
Bubble Bobble 4 Friends
```
### How can the issue be reproduced?

Just executing tag attacks, weapon skills or walking next to an orb that spawns monsters

Vulkan (GLSL -> SPIR V build)(Same happens on OpenGL)
![image](https://user-images.githubusercontent.com/2002038/160410755-e8e50215-b882-40bd-8b27-60c0bfc96789.png)
![image](https://user-images.githubusercontent.com/2002038/160411416-8514d6b3-cca0-4ba1-8ff4-f3a0948a6c1d.png)

Vulkan (SPIR V)

![image](https://user-images.githubusercontent.com/2002038/160411016-67d682f4-2bf9-4c47-ac73-22b76d47d116.png)
![image](https://user-images.githubusercontent.com/2002038/160411270-983e7033-a2e1-4ea4-89b2-c512f5e81c2d.png)

```
00:02:53.682 |E| .NET ThreadPool Worker Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod
Ryu:98: error: 'textureSize' : no matching overloaded function found
Ryu:98: error: 'Helper_TextureSizeUnscale' : no matching overloaded function found
Ryu:98: error: 'assign' :  cannot convert from ' const float' to ' temp highp int'
Ryu:99: error: 'textureSize' : no matching overloaded function found
Ryu:99: error: 'g' : vector swizzle selection out of range
Ryu:99: error: 'Helper_TextureSizeUnscale' : no matching overloaded function found
Ryu:99: error: 'assign' :  cannot convert from ' const float' to ' temp highp int'
```

### Environment?

- Ryujinx version: 1.1.85</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Windows 10)
  - CPU: Ryzen 3600
  - GPU: NVIDIA GTX 960
  - RAM: 16GB
- Applied Mods : No

**Comment by gdkchan** [comment]
This is just a warning and its harmless (as it does not actually use the overloads that require texture shadow lod when it is not supported). The actual error is:
```
Ryu:98: error: 'textureSize' : no matching overloaded function found
Ryu:98: error: 'Helper_TextureSizeUnscale' : no matching overloaded function found
Ryu:98: error: 'assign' :  cannot convert from ' const float' to ' temp highp int'
Ryu:99: error: 'textureSize' : no matching overloaded function found
Ryu:99: error: 'g' : vector swizzle selection out of range
Ryu:99: error: 'Helper_TextureSizeUnscale' : no matching overloaded function found
Ryu:99: error: 'assign' :  cannot convert from ' const float' to ' temp highp int'
```
It is trying to use an invalid `textureSize` overload. But it's hard to guess what the issue is without having access to the full shader. If you could attach a save near the area with the problem, it would be helpful (preferably from the japanese version as I don't have the new one, but if you have both even better since someone else might want to take a look too).

**Comment by GamerzHell9137** [comment]
Another game that uses the effects is Bubble Bobble 4 Friend

https://user-images.githubusercontent.com/2002038/160467110-71a94840-9ccc-4726-b147-f07cfb1d0105.mp4

Behaves the same, its using a random frame from before instead of showing transparent.
SPIR V Vulkan build freezes when it happens but GLSL Vulkan build prints the same unsuported extension like Rune Factory 5 does.
