### ISSUE TITLE
SMO missing appletOE ISelfController: 19

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#324]
https://gist.github.com/ReaperOfSouls1909/21796a0c09391f86f5b1712024817f1c log

![smo](https://user-images.githubusercontent.com/18043258/43670589-c9de7962-9763-11e8-9650-754c5f17ee02.png)
also image of loading after cut scene skip when the crash happens

**Comment by greggameplayer** [comment]
@ReaperOfSouls1909 it's fixed with my #310 PR

**Comment by ReaperOfSouls1909** [comment]
@greggameplayer some days you are to far ahead of the rest of us lol thank you

**Comment by AcK77** [comment]
Fixed in https://github.com/Ryujinx/Ryujinx/pull/310
