### ISSUE TITLE
Frame/sound problems after scanning an amiibo in Animal Crossing

### ISSUE THREAD

**Issue by Leischii** [Ryujinx/Ryujinx#3241]
### What's the issue you encountered?

Scanning an amiibo in Animal Crossing causes sound problems and stuttering until the emulator is restarted. This is a regression from https://github.com/Ryujinx/Ryujinx/pull/2721

### How can the issue be reproduced?

Go to the museum and try to scan an amiibo in the cafe. Scaning an amiibo in the main house of the dlc has the same problem.

GNU/Samantas reported on Discord that scanning an amiibo in AC on linux crashes the game. Might also be caused by the Pr, but at the time of writing this issue this isn't confirmed yet.

### Log file

No logs are printed because of this error

### Save game
[AC savegame.zip](https://github.com/Ryujinx/Ryujinx/files/8371544/AC.savegame.zip)

### Environment?

- Ryujinx version: 1.0.85</br>
- Game version: 2.0.5 (affects all versions tho)</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 3600
  - GPU: NVIDIA GTX 950
  - RAM: 16GB
- Applied Mods : [ No ]

**Comment by GamerzHell9137** [comment]
Same happens on Kirby and the Forgotten Land.

Once the changes are reverted the game doesn't drop the FPS nor stutters nor the audio breaks like on master.

When reverted:
![image](https://user-images.githubusercontent.com/2002038/160666673-bcc4ce76-359c-4089-8adb-2df45b36f187.png)

Master:
![image](https://user-images.githubusercontent.com/2002038/160667335-0528ac49-9f84-4c8b-8912-bc847245c563.png)

**Comment by gdkchan** [comment]
Please check if #3267 fixes it.
