### ISSUE TITLE
Load Application From File results in Not Responding

### ISSUE THREAD

**Issue by Wallduckie** [Ryujinx/Ryujinx#3249]
### What's the issue you encountered?

I just updated Ryujinx from 1.1.79 to 1.1.85, via the prompt in the application. I pressed the File button, and then the Load Application from File button. This caused Ryujinx to become unresponsive. 
Attempting to force quit Ryujinx via alt+f4 or task manager did not close the program.
Restarting the PC, File Explorer was unable to access anything on the computer. 
Restarting the PC again fixed File Explorer.

No changes were made to Ryujinx itself, save for the update.

### How can the issue be reproduced?

Open Ryujinx, press File, press Load Application from File.

### Log file

[Ryujinx_1.1.85_2022-04-01_18-52-20.log](https://github.com/Ryujinx/Ryujinx/files/8396391/Ryujinx_1.1.85_2022-04-01_18-52-20.log)

### Environment?

- Ryujinx version: 1.1.85

- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 1600
  - GPU: NVIDIA GTX 1080
  - RAM: 16GB
- Applied Mods : No

### Additional context?

I have been noticing some performance issues with my graphics card, and my system is a little older. But it was perfectly fine before this.
I understand this is probably an issue you all can't replicate, and I'll just have to downgrade my version. It's probably just my PC, or something I did and don't know.

**Comment by Wallduckie** [comment]
I just found the same issue when running on version 1.1.79, so its more than likely my problem. Not sure what the heck it is, though.

**Comment by MetrosexualGarbodor** [comment]
Closing as this seems to be an user-specific issue. Come to Discord if you still need support. https://discord.gg/ryujinx
