### ISSUE TITLE
Cannot connect joycons

### ISSUE THREAD

**Issue by asheenlevrai** [Ryujinx/Ryujinx#3255]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

I cannot connect my joycons in Ryujinx (they work well in Yuzu).
I have 2 pairs of joycons (4 joycons total) all connected to Windows via BT.
I also have them setup in Betterjoy 7.1

Nothing happens when I try to connect them in Ryujinx (settings->input->player1->configure). I selected the 1st entry of the joycon pair generated by BetterJoy (Xbox 360 controller ...)
Even after saving, they won't work in game.
Also. the UI of the input config screen doesn't react when I press the buttons on the joycons (I guess they should show that on the image of the joycons, right?

After doing this, I get warning messages from BetterJoy about low battery every time I press a button on the Joycons and they now appear in RED in BetterJoy. I know the battery levels are OK (full). Yuzu show accurate battery levels and the joycons work well in Yuzu.

### How can the issue be reproduced?

I was not able yet to connect my joycons in Ryujinx. Ever...

[ Include a detailed step by step process for recreating your issue. ]

See above

### Log file

N/A

### Environment?

Win10 21H2

- Ryujinx version: 1.0.X</br>

1.1.85

- System Specs:
  - OS: *(e.g. Windows 10)*
 Win10 21H2

  - CPU: *(e.g. i7-6700)*
R5 5600G

  - GPU: *(e.g. NVIDIA RTX 2070)*
GTX 1060 6GB

  - RAM: *(e.g. 16GB)*
32GB

- Applied Mods : [ Yes (Which ones) / No ]
none

**Comment by german77** [comment]
Since yuzu uses the same input backend as ryujinx you shouldn't need betterjoy to use the joycons

**Comment by MutantAura** [comment]
Native dual-joycons are currently unsupported. BetterJoy or DS4Windows are required to use them as a pair at the moment. 

> I selected the 1st entry of the joycon pair generated by BetterJoy (Xbox 360 controller ...)
Did you proceed to map anything to the controller? You can load the default profile in the top right then save. 

> Also. the UI of the input config screen doesn't react when I press the buttons on the joycons (I guess they should show that on the image of the joycons, right?
No the controller images are static. They aren't coded to react to input at all, just as a reference guide for where each button is. If BetterJoy is freaking out about incorrect battery then it's likely an issue on that end rather than Ryujinx as if BetterJoy is functioning correctly Ryu will just treat it as an xinput controller.

Give DS4Windows a try if you want to sanity check yourself.

**Comment by asheenlevrai** [comment]
> Since yuzu uses the same input backend as ryujinx you shouldn't need betterjoy to use the joycons

Thanks a lot. I was hoping this is true. I asked on the ryujinx discord server and I was told I needed BetterJoy or an equivalent alternative.

When I don't use BJ, then obviously the Xbox 360 controllers do NOT appear in the list of available input devices and I only get entries corresponding to either left OR right joycons. For some reason that I don't understand, the entries for right joycons are duplicated. WEhat I mean is:
 - I have 4 physical joycons (2x left, 2x right), so 2 pairs.
 - Ryujinx lists 6 entries: 2x left, 4x right
 - entries corresponding to the right jycons are duplicates since they share the same number (2 entries/ right joycon)
If I don't need BJ, how should I trouble shoot this further then?
Thank you very much in advance for your help.

Best,
-a-

**Comment by asheenlevrai** [comment]
> Native dual-joycons are currently unsupported. BetterJoy or DS4Windows are required to use them as a pair at the moment.
> 


Thanks... So what sou say is kind of different from the previous reply from @german77 (although not necessarily exclusive).

I guess I do need BJ after all?

> > I selected the 1st entry of the joycon pair generated by BetterJoy (Xbox 360 controller ...)
> 
> Did you proceed to map anything to the controller? You can load the default profile in the top right then save.

I selected the entry corresponding to the 1st xbox 360 controller. selected "joycon pair" as type of controller. The default mapping looked OK (I couldn't change it anyway, no reaction when pressing any joycon button). However I still loaded the dafault profile and pressed save. Again , the joycons are not functional.

> 
> > Also. the UI of the input config screen doesn't react when I press the buttons on the joycons (I guess they should show that on the image of the joycons, right?
> 
> No the controller images are static. They aren't coded to react to input at all, just as a reference guide for where each button is. 

Thanks a lot. That's useful information.

> If BetterJoy is freaking out about incorrect battery then it's likely an issue on that end rather than Ryujinx as if BetterJoy is functioning correctly Ryu will just treat it as an xinput controller.

Is there anything I can do then? reinstall BJ maybe? relink the joycons in BJ?
> 
> Give DS4Windows a try if you want to sanity check yourself.

I can try that, Although I rather not multiply this kind of tools... But thanks for the tip.

**Comment by asheenlevrai** [comment]
> Since yuzu uses the same input backend as ryujinx you shouldn't need betterjoy to use the joycons

Oh, maybe I misunderstood your reply...
I'm not using BJ in Yuzu (if that's what you thought I was doing). In Yuzu, my joycons work ootb.
I use BJ for Dolphin and I'm trying with Ryujinx...

Now I don't know if this is more clear.

**Comment by Thog** [comment]
Will try to reproduce hopefully during the week.

**Comment by german77** [comment]
MutanAura refer to them as `Native dual-joycons`. I was talking on `native single joycon` support. While it's annoying to have them listed as separate as you have to map each key individually to have both controller in a single player. It's posible to use them and should have the same issues as yuzu does.

**Comment by asheenlevrai** [comment]
> MutanAura refer to them as `Native dual-joycons`. I was talking on `native single joycon` support. While it's annoying to have them listed as separate as you have to map each key individually to have both controller in a single player. It's posible to use them and should have the same issues as yuzu does.

I have no issues with joycon in Yuzu so far.

You mean I could avoid using BJ and map my joycons as individual joycons instead? But then how can I assign 2 joycons (a left one and a right one) to player 1 ?

Could you walk me through this?

Thanks a lot
-a-

**Comment by asheenlevrai** [comment]
> Give DS4Windows a try if you want to sanity check yourself.

I DLed DS4Windows in order to try it.
Install asks for .NET 5.0.0 and provides a DL link. I click yes and proceed to DL .NET 5.0.**15**.
After installing .NET (and rebooting) I relaunch the install of DS4Windows but I am still prompter for the missing .NET.
here goes my sanity ;p I can't even install DS4Windows. How lame am I?

**Comment by german77** [comment]
Just tired. Turns out ryu doesn't allow you to map input from two controllers at the same time. Sorry seems like you will have to deal with betterjoy or ds4windows. Not sure how to fix your issue with .net 5 other than using the one provided by microsoft https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by asheenlevrai** [comment]
I forgot to mention my joycons work well (via BetterJoy) also in Cemu. The only emulator were I cannot successfully use my joycons yet is Ryujinx. Please help.

**Comment by asheenlevrai** [comment]
solved.
I needed to install HIDHide
