### ISSUE TITLE
HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

### ISSUE THREAD

**Issue by Mhamhmouth** [Ryujinx/Ryujinx#3259]
This is what I see when I try to start Diablo II Resurrected on Intel Core i5-9300H 2.40GHz 8 logical cores CPU Nvidia GeForce GTX 1050 / PCI Express / SSE2 HP laptop... Yuzu is starting that game but with too many graphical errors to play it i know that it's running perfect on your ryujinx emulator ( when it would start ) good work people thank you... So I know that there is something possible to make it work on my computer... Something can be bypassed or tweaked around maybe I don't know don't understand a lot of programming... Please help me to make it work what the masters are saying ? Thank you for your grat free work I'm also playing Metroid Dread and it's running better in ryujinx than in yuzu your emulator is great so i have enough to play.... But maybe....

**Comment by MutantAura** [comment]
This is usually due to shader compilation and in itself is not an error. Make sure your GPU drivers are fully up to date and check the game compatibility first also: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3766
