### ISSUE TITLE
EmulationStation Desktop Edition - Opening a rom in flatpak not working CLI

### ISSUE THREAD

**Issue by TheDrifter363** [Ryujinx/Ryujinx#3264]
### What's the issue you encountered?

Opening a rom in CLI for the flatpak version of Ryujinx crashes. Reports RYU-0004: Application not found.

### How can the issue be reproduced?

Download flatpak ryujinx, open a terminal. navigate to flatpak/export/bin. Execute org.ryujinx.Ryujinx LOCATION_OF_ROM. Crash

### Log file

```00:00:00.080 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.082 |I| Configuration LogValueChange: ResScale set to: 3
00:00:00.089 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.089 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.091 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.094 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.104 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.104 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.104 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.104 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.106 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.106 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.108 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.108 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.108 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.114 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.91
00:00:00.132 |N| Application Print: Operating System: Linux 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) (X64)
00:00:00.132 |N| Application Print: CPU: AMD Ryzen 7 3700X 8-Core Processor ; 16 logical
00:00:00.134 |N| Application Print: RAM: Total 32098 MB ; Available 16946 MB
00:00:00.137 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.137 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.092 |I| Gpu : Backend Threading (On): True
00:00:08.138 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Horizon.Dispose(Boolean disposing) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Horizon.cs:line 462
   at Ryujinx.HLE.Switch.Dispose(Boolean disposing) in /run/build/Ryujinx/Ryujinx.HLE/Switch.cs:line 150
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in /run/build/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 761
   at Ryujinx.Program.Main(String[] args) in /run/build/Ryujinx/Ryujinx/Program.cs:line 177
```

### Environment?

- Ryujinx version: 1.0.X</br>
Ryujinx 1.1.91
- Game version: X.X.X</br>
Xenoblade Chronicles 2 2.1.0
- System Specs:
  - OS: Debian 11 - Bullseye
  - CPU: Ryzen 7 3700x
  - GPU: AMD Radeon RX 6900 XT
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Using flatpak. Error does not occur with the .tar.gz supplied on the main website.

PS: I'm not sure if you guys are the ones to contact about the flatpak, so I just posted the issue here. If not, I don't mind being redirected, to whoever's in charge. The developer in charge of emulationstation desktop edition said there's nothing he can do on his end about this issue. Let me know. Thanks for looking into this guys.

**Comment by Anthrozil7** [comment]
Having the same exact issue here with the same steps to reproduce this error.  If I run a game from within Ryujinx it works perfectly, but launching a game via CLI fails.  Notably, this breaks Steam Rom Manager integration.

**Comment by rehtlaw** [comment]
Exact same issue here, both trying to run it through the CLI as well as double clicking a .XCI in the file browser.

**Comment by loki-47-6F-64** [comment]
I have the same issue.
It appears that any space in the path breaks launching the game from the terminal.

`"/usr/bin/flatpak" run org.ryujinx.Ryujinx '/run/media/mmcblk0p1/Games/Switch/Kirby and the Forgotten Land.nsp'` will fail.
`"/usr/bin/flatpak" run org.ryujinx.Ryujinx '/run/media/mmcblk0p1/Games/Switch/Kirby_and_the_Forgotten_Land.nsp'` will succeed

**Comment by edisionnano** [comment]
> I have the same issue. It appears that any space in the path breaks launching the game from the terminal.
> 
> `"/usr/bin/flatpak" run org.ryujinx.Ryujinx '/run/media/mmcblk0p1/Games/Switch/Kirby and the Forgotten Land.nsp'` will fail. `"/usr/bin/flatpak" run org.ryujinx.Ryujinx '/run/media/mmcblk0p1/Games/Switch/Kirby_and_the_Forgotten_Land.nsp'` will succeed

Have you tried escaping the spaces using \n?
BTW thanks for Sunshine

**Comment by loki-47-6F-64** [comment]
> > I have the same issue. It appears that any space in the path breaks launching the game from the terminal.
> > `"/usr/bin/flatpak" run org.ryujinx.Ryujinx '/run/media/mmcblk0p1/Games/Switch/Kirby and the Forgotten Land.nsp'` will fail. `"/usr/bin/flatpak" run org.ryujinx.Ryujinx '/run/media/mmcblk0p1/Games/Switch/Kirby_and_the_Forgotten_Land.nsp'` will succeed
> 
> Have you tried escaping the spaces using \n? BTW thanks for Sunshine

I'm not sure what you mean with \n. If you meant "\ ", then yeah I tried that.
I also tried putting it in `''`, but that had the same result.

**Comment by Thog** [comment]
Should be fixed in the next flathub release.
