### ISSUE TITLE
Diabolik Lovers Grand Edition - Black screen bug

### ISSUE THREAD

**Issue by Almv20** [Ryujinx/Ryujinx#3272]
When the game is loaded there's nothing but a black screen (game sounds and inputs are working though). No changes made to the emulator, actually even reinstalled it.
It can be reproduced just by opening the game.

Log file
[Ryujinx_1.1.102_2022-04-12_17-24-45.log](https://github.com/Ryujinx/Ryujinx/files/8476394/Ryujinx_1.1.102_2022-04-12_17-24-45.log)

- Ryujinx version: *1.1.102*
- Game version: *1.0.0*
- System Specs:
  - OS: *Windows 10*
  - CPU: *I5-7200U*
  - GPU: *Intel(R) HD Graphics 620*
  - RAM: *12GB*
- Applied Mods : *No*

Additional info about your environment:N/A

**Comment by piplup55** [comment]
you should try vulkan https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424 since you have a intel gpu it might be different

**Comment by Blargle** [comment]
Needs Full bindless support, so try the PR for it #3001 and also update your GPU drivers since they are about 4-5 months old.

**Comment by Almv20** [comment]
Thanks, it's working :)

**Comment by AlexandraDel** [comment]
Hello, tell me please, do you have close character sprites in the first game? I have some, but for example, Ayato and Shu are missing
I wrote about it here [#481](https://github.com/Ryujinx/Ryujinx-Games-List/issues/481#issue-589767212)

**Comment by AlexandraDel** [comment]
Hello! It's a little graphical bug
I managed to install the true-bindless version of ryujinx Two years ago. https://github.com/Ryujinx/Ryujinx/pull/3001#issuecomment-1019085453
90% of the textures became fine.
10% is the close up image of some characters only in the first game Diabolik Lovers: Haunted Dark Bridal
The second game and Chaos are completely fine.
Well, I'm a very newbie in all of this. The thing is, I'm a bit scared of uninstalling and reinstalling everything.
I'd really like to find out how the DL HDB textures are doing now
(Maybe it's even my own personal AMD problem). Guys, does anyone have this problem?
![Скриншот-11-09-2023 20_13_29](https://github.com/Ryujinx/Ryujinx/assets/54117923/193b8903-9052-4bc2-ac46-fef23f54e64c)

![ryujinx_capture_2023-09-11_23-13-53](https://github.com/Ryujinx/Ryujinx/assets/54117923/5af72d23-e7fd-41d2-b6e5-b6ec36ef0761)
