### ISSUE TITLE
Enemies are invisible in Ghosts n Goblins Resurrection

### ISSUE THREAD

**Issue by Eli0t77** [Ryujinx/Ryujinx#3274]
## Bug Report
Enemies are invisible in Ghosts n Goblins Resurrection

### What's the issue you encountered?

Invisible enemies

### How can the issue be reproduced?

Start a game level

### Log file

No errors in the log

### Environment?

- Ryujinx version: 1.1.102</br>
- Game version: 1.0.3</br>
- System Specs:
  - OS: *Windows 7*
  - CPU: *i5 2500k*
  - GPU: *Nvidia GTX 560ti*
  - RAM: *8gb*
- Applied Mods :No 

### Additional context?

Previously reported in the game thread 21 Feb 2021 with a video
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3413#issuecomment-786636750

**Comment by gdkchan** [comment]
OP graphics card is very old, might be some unsupported feature.

**Comment by MetrosexualGarbodor** [comment]
Newest driver version I can find for the GTX 560 Ti is 391.35, from March 2018. Closing this as it's a driver issue and not a Ryujinx issue, plus Windows 7 is not actually supported. Apologies.
