### ISSUE TITLE
Hide UI with F4

### ISSUE THREAD

**Issue by shayded-exe** [Ryujinx/Ryujinx#3277]
Currently you can show the UI with F4 but there's no shortcut to hide it again.

It would be really nice to be able to toggle the UI with the same key.

**Comment by andOlga** [comment]
It actually used to work like this in its earliest implementation, but it was [pointed out](https://github.com/Ryujinx/Ryujinx/pull/2411#issuecomment-869142024) that there's a chance someone might hit the button by accident and then have no idea what they did, forcing them to quit Ryujinx altogether to bring it back to a normal state. Given that this was removed *on purpose*, I don't see much point bringing it back.

**Comment by rshea0** [comment]
How about an option in the settings (disabled by default) to allow the UI to be hidden by F4?
