### ISSUE TITLE
can not save

### ISSUE THREAD

**Issue by VanMesure** [Ryujinx/Ryujinx#3279]
## Bug Report

When I play my game next time, I can't continue play. I can just play it from the beginning.
Game: Kirby and the Forgotten Land

### What's the issue you encountered?

When I play my game next time, I can't continue play. I can just play it from the beginning

### Log file

00:00:05.356 |I| Application TryFindSaveData: Creating save directory for Title: Kirby and the Forgotten Land [01004d300c5ae000]
00:00:05.376 |E| Application CreateErrorDialog: There was an error finding the specified savedata: ResultFsTargetNotFound (2002-1002)

### Environment?

- Ryujinx version: 1.1.103</br>
- 
- Game version: 1.0.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU:  i5-10600KF
  - GPU: NVIDIA RTX 2060S
  - RAM: 64GB
- Applied Mods : [ Yes ]

**Comment by MetrosexualGarbodor** [comment]
Make sure your antivirus (or Windows itself) is not preventing Ryujinx from creating a save file. For further help please join [Discord](https://discord.gg/ryujinx).
Closing this as it's an issue on your end.
