### ISSUE TITLE
Sonic Mania 1.04 crashing (GetAddOnContentListChangedEvent)

### ISSUE THREAD

**Issue by slashiee** [Ryujinx/Ryujinx#328]
Attempting to run version 1.04 of Sonic mania will cause the emulator to boot upon loading.

Through stubbing GetAddOnContentListChangedEvent (https://github.com/slashiee/Ryujinx/commit/8e7ef42aa39eb9b5c5ec8ebc54f0c9fc6728c90f) the game is able to boot once again.

![2018-07-28_21-59-23](https://user-images.githubusercontent.com/15317421/43363165-e9bde958-92b2-11e8-99b0-589f230b1e63.png)
![2018-07-28_22-08-42](https://user-images.githubusercontent.com/15317421/43363162-e3640786-92b2-11e8-96e1-165289061e1a.png)

**Comment by slashiee** [comment]
I don't know if making a PR for stubbing something like this is a good idea or not.

**Comment by Cyuubi** [comment]
You should be sending a event btw.

**Comment by slashiee** [comment]
Game does boot, but shows a red screen. I don't think it'd be related though.
![2018-10-10_19-49-21](https://user-images.githubusercontent.com/15317421/46777782-9bd74480-ccc5-11e8-81a8-0a9b4fdc0cd2.png)

**Comment by HorrorTroll** [comment]
hmmm maybe your GPU bad? Because i run fine here @slashiee 
![image](https://user-images.githubusercontent.com/24840279/46903113-a75f8100-cefa-11e8-8dfe-98cccd04e550.png)

**Comment by HorrorTroll** [comment]
Just add pr #438, then use XCI Explorer and extract DLC title key on XCI file.

Then use hex editor and copy that 32 hex code title key, go to RyuFS/System create file title.keys.Then use notepad++ and write titleid,titlekey on there. Save it

Now run XCI file and done, it’s will boot the update 1.04

**Comment by AcK77** [comment]
Closed in favor of 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/95
