### ISSUE TITLE
Pokémon Sword Invalid reinterpret cast from "S32" to "F64"

### ISSUE THREAD

**Issue by megatron0000** [Ryujinx/Ryujinx#3280]
### What's the issue you encountered?

I had just won against the Melony stadium (Lapras had been giving me trouble). The screen was transitioning to the Stadium entrance, i.e. I was seeing a screen like below:

![image](https://user-images.githubusercontent.com/8161576/163586701-92e11486-7914-40d4-ab0f-8a1c0e0b29eb.png)

Then the game froze for some seconds, and closed.

### How can the issue be reproduced?

Maybe do what I did, play Sword for some time. I was at default ryujinx settings, with Xbox controller enabled, and VSync turned off.

### Log file

[logs.txt](https://github.com/Ryujinx/Ryujinx/files/8496620/logs.txt)

### Environment?

- Ryujinx version: 1.1.103</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i7-9750H*
  - GPU: *NVIDIA GeForce RTX 2060*
  - RAM: *16GB*
- Applied Mods : No

### Additional context?

N/A

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
