### ISSUE TITLE
Luigi's Mansion 3 - Motion Controls not working

### ISSUE THREAD

**Issue by iZor613** [Ryujinx/Ryujinx#3281]
### What's the issue you encountered?

When playing Luigi's Mansion 3 I have noticed that the motion controls are not working as intended. I have double checked all Input settings to see if I have made any mistakes while setting up, but it turned out to be all correctly setup. I didn't alter Ryujinx in any way and used the lastest mainline build. 

### How can the issue be reproduced?

Just boot up Luigi's Mansion 3 with everything setup correctly for motion controls and you will notice that Luigi doesn't aim when you move your controller 

### Log file
[Ryujinx_1.1.104_2022-04-17_14-53-17.log](https://github.com/Ryujinx/Ryujinx/files/8501618/Ryujinx_1.1.104_2022-04-17_14-53-17.log)

### Environment?

- Ryujinx version: 1.1.104</br>

- Game version: 1.4.0</br>

- System Specs:
  - OS: Windows 10 21H2
  - CPU: AMD Ryzen 3600 XT
  - GPU: NVIDIA RTX 3060
  - RAM: 16GB
  
- Applied Mods : Yes, Disable Dynamic Resolution Mod, 120 FPS Mod

**Comment by RedPana** [comment]
Try  https://github.com/Ryujinx/Ryujinx/pull/3284 and see if it fixes it

**Comment by iZor613** [comment]
Still not working so far

**Comment by iZor613** [comment]
Thanks to harone for finding out it is used only when sucking up ghosts
