### ISSUE TITLE
Sword Art Online: Hollow Realization - Language selection not working

### ISSUE THREAD

**Issue by MarkLanders777** [Ryujinx/Ryujinx#3287]
### What's the issue you encountered?

The language displayed is different to the one selected</br>

### How can the issue be reproduced?

Start a new game and select Spanish, the game keeps displaying English (even if I change the language in the settings of Ryujinx) in real console it works fine, spanish is selected and displayed as it should be

### Environment?

- Ryujinx version: 1.1.105</br>
- System Specs:
  - OS: *(Windows 11)*
  - CPU: *(i7 9700 non k)*
  - GPU: *(NVIDIA 1060)*
  - RAM: *(16GB)*

**Comment by Burzumm** [comment]
В какой то определенной игре или нет?

**Comment by Burzumm** [comment]
In some game or not?

**Comment by liamharper2453** [comment]
Hi,

Please try using the 'Latin American Spanish' option in Ryujinx instead of 'Spanish' for this game.

**Comment by MarkLanders777** [comment]
> Hi,
> 
> Please try using the 'Latin American Spanish' option in Ryujinx instead of 'Spanish' for this game.

Yep, that fix the issue
