### ISSUE TITLE
Shadowverse champions battle crash

### ISSUE THREAD

**Issue by sonic1385** [Ryujinx/Ryujinx#3289]
### What's the issue you encountered?

the game crash when loading 
### How can the issue be reproduced?

opening the ryujinx and choosing the game, after some minute after loading shaders it will crash

### Log file

[Ryujinx_1.1.106_2022-04-21_20-39-00.log](https://github.com/Ryujinx/Ryujinx/files/8532728/Ryujinx_1.1.106_2022-04-21_20-39-00.log)

### Environment?

- Ryujinx version: 1.1.106
- Game version: 1.3.1
- System Specs:
  - OS: *Windows 11*
  - CPU: *i3-6100*
  - GPU: *(intel hd 530)*
  - RAM: *(8GB)*
- Applied Mods : [ No ]

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
