### ISSUE TITLE
Slaps and Beans (freeze)

### ISSUE THREAD

**Issue by Dantttt** [Ryujinx/Ryujinx#329]
This game freezes with this log
Loading as cart with RomFS.
00:00:00.132 | 0001 Loader LoadCart: Loading Title Metadata...
00:00:00.153 | 0001 Loader LoadCart: Loading rtld...
00:00:00.164 | 0001 Loader LoadProgram: Image base at 0x0000000008000000.
00:00:00.169 | 0001 Loader LoadCart: Loading main...
00:00:00.448 | 0001 Loader LoadProgram: Image base at 0x0000000008005000.
00:00:00.468 | 0001 Loader LoadCart: Loading subsdk0...
00:00:00.505 | 0001 Loader LoadProgram: Image base at 0x000000000af28000.
00:00:00.537 | 0001 Loader LoadCart: Loading sdk...
00:00:00.580 | 0001 Loader LoadProgram: Image base at 0x000000000b5e6000.
00:00:01.166 | 0007 ServiceAm GetAppletResourceUserId: Stubbed.
00:00:01.216 | 0007 ServiceAm AcquireForegroundRights: Stubbed.
00:00:01.223 | 0007 ServiceAm SetFocusHandlingMode: Stubbed.
00:00:01.227 | 0007 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed.
00:00:02.518 | 0007 ServiceNv FinishInitialize: Stubbed.
00:00:02.608 | 0007 ServiceAm SetRestartMessageEnabled: Stubbed.
00:00:02.611 | 0007 ServiceAm SetPerformanceModeChangedNotification: Stubbed.
00:00:02.614 | 0007 ServiceAm SetOperationModeChangedNotification: Stubbed.
00:00:06.431 | 0007 Hid ShMemMap: HID shared memory successfully mapped to 0x0000000021604000!
00:00:06.441 | 0007 ServiceHid ActivateNpad: Stubbed.
00:00:06.448 | 0007 ServiceHid ActivateTouchScreen: Stubbed.
00:00:06.455 | 0007 ServiceHid SetSupportedNpadStyleSet: Stubbed.
00:00:06.464 | 0007 ServiceHid SetSupportedNpadIdType: Stubbed.
00:00:09.291 | 0007 ServiceNv ZcullGetCtxSize: Stubbed.
00:00:09.293 | 0007 ServiceNv ZcullGetInfo: Stubbed.
00:00:09.392 | 0007 ServiceNv InitializeEx: Stubbed.
00:00:09.393 | 0007 ServiceNv GetVaRegions: Stubbed.
00:00:09.397 | 0007 ServiceNv GetVaRegions: Stubbed.
00:00:09.484 | 0007 ServiceNv Create: Created map 1 with size 0x00001000!
00:00:09.540 | 0007 ServiceNv Create: Created map 2 with size 0x00010000!
00:00:09.575 | 0007 ServiceNv GetActiveSlotMask: Stubbed.
00:00:09.600 | 0007 ServiceNv Create: Created map 3 with size 0x00001000!
00:00:09.616 | 0007 ServiceNv BindChannel: Stubbed.
00:00:09.619 | 0007 ServiceNv SetNvMap: Stubbed.
00:00:09.621 | 0007 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:09.623 | 0007 ServiceNv AllocObjCtx: Stubbed.
00:00:09.630 | 0007 ServiceNv SetErrorNotifier: Stubbed.
00:00:09.632 | 0007 ServiceNv SetUserData: Stubbed.
00:00:09.636 | 0007 ServiceNv SetPriority: Stubbed.
00:00:09.644 | 0007 ServiceNv Create: Created map 4 with size 0x00010000!
00:00:09.687 | 0007 ServiceNv Create: Created map 5 with size 0x00049000!
00:00:09.712 | 0007 ServiceNv ZcullBind: Stubbed.
00:00:09.834 | 0007 ServiceNv Create: Created map 6 with size 0x01000000!
00:00:09.883 | 0007 ServiceNv Create: Created map 7 with size 0x00054000!
00:00:09.946 | 0007 ServiceNv Create: Created map 8 with size 0x06000000!
00:00:10.135 | 0007 ServiceNv Create: Created map 9 with size 0x021d0000!
00:00:10.704 | 0015 ServiceNv Create: Created map 10 with size 0x0c000000!

**Comment by AcK77** [comment]
Well, it's not the full log right here... We don't have enough informations!

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/61
