### ISSUE TITLE
feature request: a compile time flag for Linux packaging support

### ISSUE THREAD

**Issue by IvarWithoutBones** [Ryujinx/Ryujinx#3291]
#### Overview:
I saw a bunch of packaging functionality got added recently for flatpak, which is very useful to other package managers as well. It would be nice if there was a compile-time flag for packaging on Linux distrobutions which could mirror the flathub logic in for example https://github.com/Ryujinx/Ryujinx/blob/ac21abbb9d23432879b1026eb5bc48ad3d4583d8/Ryujinx.Common/ReleaseInformations.cs#L45  

It could also automatically disable the updater as the flathub integration does already, we currently do this manually with the `/p:ExtraDefineConstants=DISABLE_UPDATER` flag.

#### Smaller Details: 
I am one of the maintainers of the Ryujinx package in [nixpkgs](https://github.com/NixOS/nixpkgs), a deterministic Linux distribution and package repository. Here we build the app in a sandbox, and then push the binary and its DLLs to a read-only filesystem (`/nix/store/<hash>-ryujinx/`) to ensure the package remains in the same state as when we deterministically compiled it. For more information see the [build script](https://github.com/NixOS/nixpkgs/blob/b49192e9082db657363c9cc7bf6b7520c8e455ad/pkgs/applications/emulators/ryujinx/default.nix), also known as a derivation. 

The nix store being read-only makes Ryujinx unusable by default, as it will attempt to write logs to the same directory as the binary is located. We currently fix this with a [patch](https://github.com/NixOS/nixpkgs/blob/b49192e9082db657363c9cc7bf6b7520c8e455ad/pkgs/applications/emulators/ryujinx/appdir.patch) that comments out the flathub check, which works well but obviously isn't a proper solution.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
It would the streamline packaging process for Linux distrobutions. This breaks on NixOS, but it wouldn't be very clean to have logs in `/usr/bin` on other distros either.

**Comment by marysaka** [comment]
This was fixed by https://github.com/Ryujinx/Ryujinx/pull/4460.
