### ISSUE TITLE
Some known working games don't launch for me, while others do

### ISSUE THREAD

**Issue by phasermaniac83** [Ryujinx/Ryujinx#3294]
### What's the issue you encountered?

Some games like Ninja Warriors Once Again, Pocky & Rocky Reshined and Tonight We Riot won't launch, while others like Windjammers 2 or 80s Overdrive work nice at 60fps.
They worked in old Ryujinx versions until 7/5/2021 build, but on those old versions they run slow.
Newer versions can't lauch them:
In version from 5/11/2021, they don't crash, but show a black screen, in the bottom bar I can see GAME: 0,00 FPS ( [Huge numbers] ms).
In last version 1.1.106 they show black screen and crash 10s or so after launching, but the log shows the same.

### How can the issue be reproduced?

I suspect the problem is my gpu, which only supports OpenGL 4.5.
Maybe emulation of those games from 7/5/2021 is using some OpenGL extension my gpu does not support?

### Log file

[Ryujinx_1.1.106_2022-04-23_21-18-14.log](https://github.com/Ryujinx/Ryujinx/files/8549323/Ryujinx_1.1.106_2022-04-23_21-18-14.log)

### Environment?

- Ryujinx version: 1.1.106</br>
- Game version: X.X.X</br>
- System Specs:
  - OS: Windows 10
  - CPU:  i5-2500k 3.30Ghz
  - GPU: AMD Radeon HD 6950
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

My system is hooked to an 15khz CRT using CRT Emudriver, with lots of emulated classic systems, and changing the graphics card would fuck up my whole system configuration.
Ninja Warriors Once Again, Pocky and Rocky Reshined are Switch exclusive games with a 426x270 base resolution, which should display perfect in a 15khz CRT.
I know this card is not powerful enough to run 3d games, but I'm only interested in pixel art games, where performance shouldn't be a problem, as I said with this system I have Windjammers 2 running at 60fps with newer Ryujinx versions.
So, with all those clues, do you have any advise to test other than "change your gpu or whole system"?
Many Thanks!

**Comment by Itamai** [comment]
Can you open cmd or another terminal and drag and drop the ryujinx.exe and launch it from that terminal? If Ryujinx crashes, the terminal will still remain open so you can copy the exception that was thrown.
I only have(from the listed games) and tested Ninja Warriors Once Again on my AMD setup and it worked fine.
You could also try the ryujinx vulkan build as AMD's Windows OpenGL support isn't the best.
https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424

**Comment by phasermaniac83** [comment]
Thanks Itamai, I will open it in cmd and share the exception later today.
Thanks for the Vulkan build, I will test too,  but I'm pretty sure my Gpu doesn't support vulkan.

**Comment by piplup55** [comment]
> Can you open cmd or another terminal and drag and drop the ryujinx.exe and launch it from that terminal? If Ryujinx crashes, the terminal will still remain open so you can copy the exception that was thrown. I only have(from the listed games) and tested Ninja Warriors Once Again on my AMD setup and it worked fine. You could also try the ryujinx vulkan build as AMD's Windows OpenGL support isn't the best. [#2518 (comment)](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424)

their gpu doesn't support vulkan
![image](https://user-images.githubusercontent.com/100526773/164974026-4ff33c8d-0917-4d6e-bb3b-5139010e2786.png)

**Comment by MetrosexualGarbodor** [comment]
Your GPU is so old that it's unsalvageable. Last driver update I can find was in 2016. Your only choices are switching to Linux or buying a new GPU, preferably not of the AMD brand. 
And please don't open issues for support, come to Discord instead. https://discord.gg/ryujinx
