### ISSUE TITLE
Drawing doesn't work 

### ISSUE THREAD

**Issue by OctoTheBitch** [Ryujinx/Ryujinx#3295]
As seen here with the starlion splatoon 2 modmenu, drawing doesn't work and text is cut out, same goes for the debug menu in splatoon 2
![image](https://user-images.githubusercontent.com/91217129/164971788-99d4576f-a481-4fe4-adf7-9d98e3d461c2.png)

**Comment by voldemort2826** [comment]
No logs, no specs, on top of that you removed the issue template. How can anyone help you?

**Comment by MetrosexualGarbodor** [comment]
As the above commenter said, you might want to follow the template and provide a log. There's barely anything to work with here.
