### ISSUE TITLE
NOTICE: Drop support of Windows versions prior to Windows 10 1803

### ISSUE THREAD

**Issue by Thog** [Ryujinx/Ryujinx#3298]
Hello there,

This is a notice to indicate support drop for Windows versions prior to Windows 10 1803 on **June 1st 2022**.

### Why are we dropping support?
- Windows 7 EOL was on January 13, 2015
- Windows 8 EOL was on January 12, 2016
- Windows 8.1 EOL was on January 9, 2018
- Graphics driver support also were dropped by all vendors meaning that driver bugs will never get addressed.

**Comment by voldemort2826** [comment]
I think #2954 will also depend on this change, specifically the fast memory manager modes.

**Comment by gdkchan** [comment]
> I think #2954 will also depend on this change, specifically the fast memory manager modes.

The emulator will continue working on Windows 7/8 with this change, but it will always use the software memory manager mode there regardless of what the user chooses.

**Comment by voldemort2826** [comment]
Another important point to make is that dropping support makes the emulator development much easier. Having to include workarounds for old OSes is PITA, and we don't know if those might introduce other chains of bugs \*shrug*

**Comment by OCRBonk** [comment]
As a frequent user of W7 on a dual boot system. I totally get dropping support officially considering the amount of things available to newer OSes. Surprised frankly you supported it at all at any point given the age of the OS.

**Comment by dio-gh** [comment]
Hi,

I'd like to point out that some of the points raised in the ticket are somewhat disingenuous.

- Windows 7 is still receiving [Extended Security Updates](https://docs.microsoft.com/en-us/lifecycle/products/windows-7) until January 10, 2023 for VL (volume licensed) purchases of `Professional`, `Enterprise`, and `Professional for Embedded Systems` versions.
- Windows 8.1 is receiving extended support (not limited to security updates) until [January 10, 2023](https://docs.microsoft.com/en-us/lifecycle/products/windows-81) regardless of license type.
- While it is true that none of the vendors are planning to release functionality related updates for the aforementioned platforms anymore, it is incorrect to say that support has been dropped altogether - [NVIDIA vouched](https://nvidia.custhelp.com/app/answers/detail/a_id/5201/~/support-plan-for-windows-7-and-windows-8%2F8.1) they'll keep critical security updates going until September 2024, and AMD seems to be aiming for [something similar](https://hexus.net/tech/news/software/148003-amds-radeon-driver-moves-windows-7-legacy-support/) with their "legacy support model".

This isn't to say that ceasing support for these systems isn't reasonable though, just wanted to make sure these facts are also covered in this thread.

**Comment by Thog** [comment]
> Hi,
> 
> I'd like to point out that some of the points raised in the ticket are somewhat disingenuous.
> 
>     * Windows 7 is still receiving [Extended Security Updates](https://docs.microsoft.com/en-us/lifecycle/products/windows-7) until January 10, 2023 for VL (volume licensed) purchases of `Professional`, `Enterprise`, and `Professional for Embedded Systems` versions.
> 
>     * Windows 8.1 is receiving extended support (not limited to security updates) until [January 10, 2023](https://docs.microsoft.com/en-us/lifecycle/products/windows-81) regardless of license type.
> 
>     * While it is true that none of the vendors are planning to release functionality related graphics driver updates for the aforementioned platforms anymore, it is incorrect to say that support has been dropped altogether - [NVIDIA vouched](https://nvidia.custhelp.com/app/answers/detail/a_id/5201/~/support-plan-for-windows-7-and-windows-8%2F8.1) they'll keep critical security updates going until September 2024, and AMD seems to be aiming for [something similar](https://hexus.net/tech/news/software/148003-amds-radeon-driver-moves-windows-7-legacy-support/) with their "legacy support model", though they haven't specified any details or an end date.
> 
> 
> This isn't to say that ceasing support for these systems isn't reasonable though, just wanted to make sure these facts are also covered in this thread.

I think my points were self explanatory and obvious but I guess even then people would still yell at the clouds heh?

- For Windows 7 and 8.1, what you are talking about is **special paid support plan targeted for corporations**, this is out of range of Ryujinx target audience.
- For GPU drivers, I do not consider security fixes as active development support. No GPU drivers bugs will be fixed that way by any vendors.

**Comment by dio-gh** [comment]
> For Windows 7 and 8.1, what you are talking about is special paid support plan targeted for corporations

Not the case for 8.1 - as I said, 8.1 installs are still getting updates, regardless of licensing type. I get them too.

Fair enough for 7 though, albeit I'm not sure how this works for used office machines that have been put up for sale and then bought by regular folk.

> No GPU drivers bugs will be fixed that way by any vendors.

Yep, all good on that end. Just wanted to specify the kind of support that has been dropped.

> but I guess even then people would still yell at the clouds heh?

Pretty much. I've seen these counters brought up in [the Reddit thread](https://www.reddit.com/r/emulation/comments/ucit8l/ryujinx_will_officially_drop_support_for_windows/), so I figured I should them addressed here as well. Apologies if it's unwelcome.

**Comment by voldemort2826** [comment]
Either way Vulkan is becoming the next thing, and it requires latest GPU driver updates. Atm it's just unfeasible to support legacy OSes, and like Thog said, (critical) security updates are not bug fixing / active development.
And I'm pretty sure some reddit folks are either trolls or they're just too lazy to upgrade their OS lol.

**Comment by metapea** [comment]
Can you also gives an option to removed auto-updates and the warning for non window 10 users and improve load times for opening Ryujinx?
It was fine in begin of year around v1.1.9x, but now it takes a full minute to few minutes just to load Ryujinx.
And one of the reason was that Ryujinx was trying to load from github for a few minutes while the program was blank: 
![Screenshot_89](https://user-images.githubusercontent.com/35351174/171307330-d19699ae-2795-4184-8d29-188e1095bd14.png)

**Comment by gdkchan** [comment]
Checking for updates on startup can be disabled on the settings.

**Comment by metapea** [comment]
Good, just saying that since it did cause slow downs for loading the program for me, and maybe add a auto-detect for non-windows 10 users to ignore updates or only update to the last supported version if they have an older versions of Ryujinx, so they don't update to the newer windows 10 versions by accident   
also can you put an option to remove the warring or add a ''do not show this again'' option:
![Screenshot_94](https://user-images.githubusercontent.com/35351174/171308357-ef2389b5-6983-46ce-a774-0d4c09868587.png)

**Comment by MutantAura** [comment]
>  add a auto-detect for non-windows 10 users to ignore updates or only update to the last supported version

There will be no further updates or additions regarding users older than Windows 10.

> can you put an option to remove the warring or add a ''do not show this again'' option:

Same as above. Realistically you want to be using 1.1.109 anyway as this was the last version that the fastest memory manager modes worked on.
