### ISSUE TITLE
ThimbleweedPark (freeze)

### ISSUE THREAD

**Issue by Dantttt** [Ryujinx/Ryujinx#330]
This game freezes at
Loading as cart with RomFS.
00:00:00.137 | 0001 Loader LoadCart: Loading Title Metadata...
00:00:00.155 | 0001 Loader LoadCart: Loading rtld...
00:00:00.168 | 0001 Loader LoadProgram: Image base at 0x0000000008000000.
00:00:00.172 | 0001 Loader LoadCart: Loading main...
00:00:00.191 | 0001 Loader LoadProgram: Image base at 0x0000000008005000.
00:00:00.193 | 0001 Loader LoadCart: Loading subsdk0...
00:00:00.339 | 0001 Loader LoadProgram: Image base at 0x0000000008237000.
00:00:00.353 | 0001 Loader LoadCart: Loading sdk...
00:00:00.403 | 0001 Loader LoadProgram: Image base at 0x0000000009ad5000.
00:00:00.979 | 0007 ServiceAm GetAppletResourceUserId: Stubbed.
00:00:01.028 | 0007 ServiceAm AcquireForegroundRights: Stubbed.
00:00:01.035 | 0007 ServiceAm SetFocusHandlingMode: Stubbed.
00:00:01.038 | 0007 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed.
00:00:02.082 | 0007 ServiceNv FinishInitialize: Stubbed.
00:00:02.119 | 0007 ServiceAm SetOperationModeChangedNotification: Stubbed.
00:00:02.122 | 0007 ServiceAm LockExit: Stubbed.
00:00:02.130 | 0007 ServiceAcc InitializeApplicationInfo: Stubbed.
00:00:02.257 | 0007 Hid ShMemMap: HID shared memory successfully mapped to 0x0000000027a04000!
00:00:02.267 | 0007 ServiceHid ActivateTouchScreen: Stubbed.
00:00:02.371 | 0007 ServiceAcc GetUserExistence: Stubbed.
00:00:02.376 | 0007 ServiceAm EnsureSaveData: Stubbed.
00:00:05.834 | 0007 ServiceNv ZcullGetCtxSize: Stubbed.
00:00:05.836 | 0007 ServiceNv ZcullGetInfo: Stubbed.
00:00:05.925 | 0007 ServiceNv InitializeEx: Stubbed.
00:00:05.927 | 0007 ServiceNv GetVaRegions: Stubbed.
00:00:05.930 | 0007 ServiceNv GetVaRegions: Stubbed.

**Comment by AcK77** [comment]
Well, it's not the full log right here... We don't have enough informations!

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/52
