### ISSUE TITLE
Nintendo Switch Sports Crash [Game and Sometimes GPU]

### ISSUE THREAD

**Issue by marmarbrrr** [Ryujinx/Ryujinx#3305]
### What's the issue you encountered?

When I get to the nintendo Siwtch sports start screen (when choosing between different modes (online, local, etc.), when I choose a mode the game crashes and closes and in some cases the game crash my GU (RTX 2070 LAPTOP))

### How can the issue be reproduced?

1 - Get the 1.1.0 or 1.0 version (XCI or NSP) of Nintendo Switch Sports
2 - Launch the game
3 - Select any mode (local,online,etc.)
4 - Bug

### Log file

[Ryujinx_1.1.106_2022-04-29_14-22-04.log](https://github.com/Ryujinx/Ryujinx/files/8590757/Ryujinx_1.1.106_2022-04-29_14-22-04.log)

### Environment?

- Ryujinx version: 1.1.106 winx64
- Game version: 1.1.0
- 
- System Specs:
  - OS: Windows 11 x64
  - CPU: i7-10750h
  - GPU: RTX 2070 LAPTOP
  - RAM: 16GB
- Applied Mods : NO

**Comment by RaxMage** [comment]
It works fine till you enter local play and then it crashes. I have the latest build 1.1.107 and have a gtx 1650.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
