### ISSUE TITLE
Pokemon Legends Arceus GFX regression

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#3309]
### What's the issue you encountered?

Since #3302 there have been some graphical regressions in the above title (see images below).

### How can the issue be reproduced?

Load into PLA and enter and exit the main hub building (or any building to refresh the area). 

### Log file

[Ryujinx_1.1.108_2022-05-01_17-07-55.log](https://github.com/Ryujinx/Ryujinx/files/8599278/Ryujinx_1.1.108_2022-05-01_17-07-55.log)

### Environment?

- Ryujinx version: 1.1.108
- Game version: 1.1.0
- System Specs:
  - OS: *Windows 10*
  - CPU: *R5 5600X*
  - GPU: *NVIDIA RTX 3070*
  - RAM: *32GB DDR4*

### Additional context?
1.1.106: 
![image](https://user-images.githubusercontent.com/44103205/166154723-ceb328a9-d040-4959-9538-9402e101cc8a.png)
1.1.107: 
![image](https://user-images.githubusercontent.com/44103205/166154729-c450e945-ffaf-4817-9ddd-12fb1df4f66a.png)
![image](https://user-images.githubusercontent.com/44103205/166154740-df9f8f0b-68ff-48be-8210-78fdb8deec02.png)
![image](https://user-images.githubusercontent.com/44103205/166154760-3e626bae-f83a-42f8-ae7b-15333d4fb920.png)

**Comment by innerspeakerz** [comment]
I am experiencing the same problem

**Comment by ivooc** [comment]
This problem is back:
![image](https://user-images.githubusercontent.com/44483972/169920987-5c1fdd9a-6325-4d9c-9e31-919d53677745.png)
![image](https://user-images.githubusercontent.com/44483972/169921043-89f45016-547b-48fe-b056-29f1467fb4e2.png)

**Comment by riperiperi** [comment]
Can you not comment this on every PR? I think there was a very low chance of this happening even before the change to texture sync, the regression was that it became _much higher_.

**Comment by ivooc** [comment]
> Can you not comment this on every PR? I think there was a very low chance of this happening even before the change to texture sync, the regression was that it became _much higher_.

sorry, I thought it would be wise to link the related problems but I guess it was unnecessary. I played around a bit and it is happening far less than when the issue appeared before.
