### ISSUE TITLE
EVE rebirth terror stucks

### ISSUE THREAD

**Issue by harlayzhou** [Ryujinx/Ryujinx#3310]
### What's the issue you encountered?

The game stucks after press button A.
The BGM still playing.

### How can the issue be reproduced?

Load save and press button A.

### Log file

[Ryujinx_1.1.108_2022-05-02_00-45-48.log](https://github.com/Ryujinx/Ryujinx/files/8599366/Ryujinx_1.1.108_2022-05-02_00-45-48.log)

### Environment?

- Ryujinx version: 1.1.108</br>
- Game version: 1.0.2</br>
- System Specs:
  - OS: Windows 11
  - CPU: i5-11600KF
  - GPU: NVIDIA RTX 3060Ti
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>

![1](https://user-images.githubusercontent.com/8403754/166156444-0c5a888a-fe95-4d34-a645-407ae7b458c7.jpg)
Press button A.
![2](https://user-images.githubusercontent.com/8403754/166156446-893550ac-ff29-4163-9144-2ed2f263ba2c.jpg)
And stucks at this scene.

**Comment by gdkchan** [comment]
Where exactly does this happen? I can't reproduce this issue with a save I made right at the start of the game. Maybe you should attach the save.

**Comment by harlayzhou** [comment]
[eve2save.zip](https://github.com/Ryujinx/Ryujinx/files/8600832/eve2save.zip)
here is the save.

**Comment by harlayzhou** [comment]
I have through the scene by remove the update 1.0.2.
Maybe the update is broken?

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
