### ISSUE TITLE
[Feature Request] Custom path for the location of save files (Windows)

### ISSUE THREAD

**Issue by asheenlevrai** [Ryujinx/Ryujinx#3312]
Hi there :slight_smile: 
Is there any way to use a custom path for the location of save files on windows?
I'd like to save them on a 2nd SSD (different from the system SSD). This way, there would be no risk to delete my saves when reinstalling my system.

Is this doable?

If not, is this a reasonable feature request?

Thank you very much in advance for your help.

Best,
-a-

**Comment by DeGamersSpelen** [comment]
You could make the save directory a directory junction to the 2nd SSD

Else you could just make ryujinx portable with the portable folder and put ryujinx on the 2nd SSD

**Comment by asheenlevrai** [comment]
Thanks a lot :)
I had never heard of directory junctions before.

Best,
-a-
