### ISSUE TITLE
legends arceus black screen

### ISSUE THREAD

**Issue by farestatsumaki** [Ryujinx/Ryujinx#3318]
## Bug Report

no start up on the game after patch 1.1.110

### What's the issue you encountered?

started on 1.1.106 everything works fine , updated every time it was possible graphical bugs since 1.1.107 artefacts and all still playable games , since the fix on the artefact situation on legend of arceus in 1.1.110 after loading the shadrers the game just don't start anymore  black screen 0 fps the whole deal. 
if the issue could be fixed it would be helpful or i'd have to downgrade back to 1.1.106
thanks

### How can the issue be reproduced?

[ NA ]

### Log file

00:00:00.057 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.059 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.067 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.067 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.069 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.072 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.083 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.083 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.083 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.083 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.083 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.083 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.084 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.085 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.086 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.086 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.086 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.365 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.102
00:00:00.379 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.379 |N| Application Print: CPU: AMD Ryzen 7 3700X 8-Core Processor ; 16 logical
00:00:00.380 |N| Application Print: RAM: Total 16305 MB ; Available 11811 MB
00:00:00.383 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.383 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### Environment?

- Ryujinx version: 1.1.115</br>

- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ NA]

**Comment by piplup55** [comment]
join the discord for support [Discord](https://discord.gg/ryujinx) it works on 1.1.115 without expanded dram enabled

![image](https://user-images.githubusercontent.com/100526773/166856022-9fe030e1-5543-4b2a-aa81-52dc863e50b2.png)

**Comment by farestatsumaki** [comment]
thanks for your help  , i can confirm it does work that way
wouldn't that affect the performances of more fast paced games maybe ?

________________________________
De : Piplup ***@***.***>
Envoyé : jeudi 5 mai 2022 02:35
À : Ryujinx/Ryujinx ***@***.***>
Cc : farestatsumaki ***@***.***>; Author ***@***.***>
Objet : Re: [Ryujinx/Ryujinx] legends arceus black screen (Issue #3318)


join the discord for support Discord<https://discord.gg/ryujinx> it works on 1.1.115 without expanded dram enabled

[image]<https://user-images.githubusercontent.com/100526773/166856022-9fe030e1-5543-4b2a-aa81-52dc863e50b2.png>
