### ISSUE TITLE
PPTC cache causes stuttering after updating ryujinx

### ISSUE THREAD

**Issue by Eli0t77** [Ryujinx/Ryujinx#3320]
## Bug Report

I'm not sure how many users this affects but thought I'd post it anyway. I hadn't played the games I found stutters in for a while and had to go back to 1.1.85 to find where it started (this version changed basically nothing)

### What's the issue you encountered?

I have a weird pptc issue. Upgraded to 1.1.109 and found some stuttering (already had shaders and pptc cache from 1.1.105) so went back to 1.1.105 still had stutters. Cleared pptc cache and no more stutters. Upgraded to 1.1.109 again, had stutters, cleared pptc cache and no more stutters, loaded the game again and still no stutters. Used Links Awakening (in-game) and Metroid Dread (first intro movie) for testing

### How can the issue be reproduced?

Download a previous version of ryujinx eg 1.1.105
Load Metroid Dread or Links Awakening
Update to a newer version eg 1.1.109
Load Metroid Dread or Links Awakening

### Log file

No errors found in the log

### Environment?

- Ryujinx version: 1.1.109</br>
- Game version: v1 of Metroid Dread and Links Awakening</br>
- System Specs:
  - OS: *Windows 7*
  - CPU: *i5 2500k @ 4.4ghz*
  - GPU: *GTX 560ti*
  - RAM: *8gb*
  - Storage: *HDD*
- Applied Mods : [ None ]

**Comment by voldemort2826** [comment]
You won't likely to get support here because:
- you are using an outdated OS
- your Ryujinx version is old

From what you've said, clearing PPTC solves your problem.

**Comment by MutantAura** [comment]
This seems like an isolated issue that was solved by simply re-creating your PPTC cache. 
In-future please report issues while using the latest master build of Ryujinx for the most accurate report.
