### ISSUE TITLE
About ryujinx connect switch console via LDN...

### ISSUE THREAD

**Issue by nazizomieprincesskenny** [Ryujinx/Ryujinx#3324]
Recently I've downloaded ryujinx multiplayer build in order to play animal crossing with my friend.
But I (and my friend) couldn't find each other's island

here are my settings:
internet connection: Same Wi-Fi
version of game : both 2.0.5
mode: ryujinx ldn
disabled P2P: inactivated
network passphrase: _(public)_
LAN mode: activated
Network interface: Default

Is there anything wrong with my settings or I need to do anything else with my switch?

(This is my first time posting on github. If I said somthing unappropriate, plz let me know,thanks!)

**Comment by CrusadingNinja** [comment]
Github is not for support requests. Please use the discord server for that instead.
