### ISSUE TITLE
eBaseball Powerful Pro Yakyuu 2022 with graphical issues

### ISSUE THREAD

**Issue by scju** [Ryujinx/Ryujinx#3325]
### What's the issue you encountered?

Graphical issues 

with native resolution

[https://youtu.be/dNQDeXNo4s8](https://youtu.be/dNQDeXNo4s8)

with 2x resolution

[https://youtu.be/J263xgN0SFQ?t=38](https://youtu.be/J263xgN0SFQ?t=38)

### How can the issue be reproduced?

Just launch eBaseball Powerful Pro Yakyuu 2022 and start a game.

### Log file

[Ryujinx_1.1.118_2022-05-07_22-07-34.log](https://github.com/Ryujinx/Ryujinx/files/8645364/Ryujinx_1.1.118_2022-05-07_22-07-34.log)

### Environment?

- Ryujinx version: 1.1.118</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i9-9900k
  - GPU: NVIDIA RTX 3060ti
  - RAM: 32GB
- Applied Mods : No

**Comment by Threule** [comment]
Vulkan fixes this, opens new glitches with customization
Might post during next week

**Comment by scju** [comment]
> Vulkan fixes this, opens new glitches with customization Might post during next week

Okay, thanks. 👍

**Comment by scju** [comment]
Ryujinx version: 1.1.242
Game version: 1.1.5
System Specs:
OS: Windows 10
CPU: i9-9900k
GPU: NVIDIA RTX 3060ti
RAM: 32GB
Applied Mods : No

Vulkan fixed the problem in post #1. That was a huge improvement. But some baseball fields still seem too "dark". Here is an example:

[](https://youtu.be/LGHl1tbQsFk)

**Comment by Threule** [comment]
Shouldn't you open a new one? Since the old one is related to 1.1.118

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions,. Game compatibility information/per-game bugs belong on the game compatibility list.
