### ISSUE TITLE
mario plus rabbids kingdom battle visual glitch

### ISSUE THREAD

**Issue by memefloppa** [Ryujinx/Ryujinx#3329]
after i started playing mario plus rabbids kingdom battle, 
i immediatly noticed that there was a terrible visual glitch. no changes to settings were made and i can confirm that it was only this game as other games worked flawlessly. 
an easy step by step to recreating my issue would be to simply launch that game and recreate my settings from the log file i have provided. 
i am using ryujinx version 1.1.85-win_x64. 
my os is windows 11,
 my cpu is an intel i9-12900k,
 my gpu is an rtx 3090 evga ftw3,
 i have 32gb of ram.
 there are no mods on that specific game.
 i have attached a video and a log so that you can see what i am experiencing
[Ryujinx_1.1.119_2022-05-09_08-44-52.log](https://github.com/Ryujinx/Ryujinx/files/8652121/Ryujinx_1.1.119_2022-05-09_08-44-52.log)

https://user-images.githubusercontent.com/105219666/167421333-29586699-c24f-418e-a03e-6013ad641554.mp4

.

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
