### ISSUE TITLE
Cruis'n Blast v1.06-7 - Save file becoming corrupt or unloadable, causing hang during bootup

### ISSUE THREAD

**Issue by markviv** [Ryujinx/Ryujinx#3330]
### What's the issue you encountered?
Save file becoming corrupt or unloadable, causing hang during bootup

### How can the issue be reproduced?
**From the beginning**
Ryujinx v1.1.12 (Cruis'n Blast v1.06) 
Windows 10 X64 v1809 - i7-3770K CPU @ 3.50GHz ; 8 logical - GTX680 (driver v472.98 - 30.0.14.7298)
I played Cruis'n Blast for 34 hours over multiple days (1 & 2 Player) and multiple computer restarts without any problems.

**Updated to:**
Microsoft Windows 10.0.19044 (X64)
Installed VB runtime All-in-one: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/ (many of the runtimes were already installed before doing this but now all are installed)
Ryujinx v1.1.19
Cruis'n Blast HANGS when loading

**The Hang Happens Here:**
**00:01:05.996 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 139132 bytes, profiled functions: 40399).**

**Temporary solution:**
Renamed my save from Cruisn_MySaveData to Cruisn_MySaveDataBACKUP
Game boots up with no problems
Replaced Cruisn_MySaveData save file with one off the internet that has all achievements.
Game boots up with no problems.
I shutdown/restart ryujinx a few times and Cruis'n Blast starts to hang when booting.
I delete the  Cruisn_MySaveData save file
game boots up without any problems.

I put the exact dled save file from the internet (all achievments complete) again and the game will boot without any problems. Sometimes I reboot my computer to get a fresh start and clear my memory.

Updated to Cruis'n Blast v1.07 which did not fix the problem.
**I also reverted back to ryujinx 1.1.112 and 1.1.102 and tested this. The problem was not resolved.**
**When the problem happens, deleteing the save file seems to work though.**

### Log file
00:00:00.098 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.101 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.112 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.112 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.115 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.121 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.135 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.135 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.136 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.136 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.136 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.136 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.139 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.139 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.142 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.142 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.142 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.152 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.119
00:00:00.171 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.171 |N| Application Print: CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz ; 8 logical
00:00:00.173 |N| Application Print: RAM: Total 8120 MB ; Available 6273 MB
00:00:00.177 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.178 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.148 |I| Gpu : Backend Threading (Auto): True
00:00:00.470 |N| Application LoadApplication: Using Firmware Version: 14.0.0
00:00:00.470 |I| Application LoadApplication: Loading as XCI.
00:00:00.697 |I| ModLoader QueryContentsDir: Searching mods for Title 0100B41013C82000
00:00:00.704 |I| ModLoader QueryTitleDir: Found mod 'Game Fix' [E]
00:00:00.708 |I| ModLoader QueryContentsDir: Searching mods for Title 0100B41013C82000
00:00:00.729 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.754 |I| Loader LoadExeFs: Loading rtld...
00:00:00.907 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.907 |I| Loader LoadExeFs: Loading main...
00:00:01.781 |I| Loader PrintRoSectionInfo: main:
    Module: D:\CruisnConsole_build\SwitchIL2CPPCache\il2cpp_cache\linkresult_ADF9119EA77BA20F6AA578C0AF017B7F\SwitchPlayer.nss
    SDK Libraries: SDK MW+UnityTechnologies+Unity-2019_4_18_f1
                   SDK MW+Nintendo+NintendoSDK_libcurl-10_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_libz-10_4_1-Release
                   SDK MW+Nintendo+PIA_UNITY-0.30.0
                   SDK MW+Nintendo+PiaSession-5_34_0
                   SDK MW+Nintendo+PiaTransport-5_34_0
                   SDK MW+Nintendo+NEX-4_6_4-
                   SDK MW+Nintendo+54881
                   SDK MW+Nintendo+PiaCommon-5_34_0
                   SDK MW+Nintendo+Pia-5_34_0
                   SDK MW+Nintendo+PiaFramework-5_34_0
                   SDK MW+Nintendo+PiaLan-5_34_0
                   SDK MW+Nintendo+PiaLocal-5_34_0
                   SDK MW+Nintendo+PiaNex-5_34_0-forNEX-4_6_4
                   SDK MW+Nintendo+PiaReckoning-5_34_0
                   SDK MW+Nintendo+PiaSync-5_34_0
                   SDK MW+Nintendo+NEX_MM-4_6_4
                   SDK MW+Nintendo+PiaClone-5_34_0
00:00:01.782 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.850 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-10_4_1-Release
00:00:01.850 |I| Loader LoadExeFs: Loading sdk...
00:00:01.993 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 10.4.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-10_4_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-10_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-10_4_1-Release
00:00:02.019 |I| ModLoader ApplyProgramPatches: Matching IPSwitch patch '9346D69ABD4CC24B.pchtxt' in 'Game Fix' bid=9346D69ABD4CC24BA10E47C580400244
00:00:02.024 |I| ModLoader Parse: IPSwitch:    # Cruis'n Blast [0100B41013C82000] v1.07 - GameFix
00:00:02.031 |I| ModLoader Parse: IPSwitch:    print_values 0x162aea8 <= 1F2003D5
00:00:02.043 |I| ModLoader Patch: Patching address offset 162ada8 <= 1F 20 03 D5 len=4
00:00:02.096 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.897 |I| Ptc Load: Loaded Translation Cache (size: 56812131 bytes, translated functions: 45950).
00:00:02.917 |I| Ptc Load: Loaded Profiling Info (size: 139027 bytes, profiled functions: 40371).
00:00:03.480 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:03.485 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:03.528 |I| Loader LoadNsos: Loading image 2 at 0x000000000ce23000...
00:00:03.531 |I| Loader LoadNsos: Loading image 3 at 0x000000000d4d4000...
00:00:03.554 |I| ModLoader LoadCheats: Build ids found for title 0100B41013C82000:
    C1ED34FD7D1962277A4555D9EC7146571218ED5D000000000000000000000000
    9346D69ABD4CC24BA10E47C58040024400000000000000000000000000000000
    84E50460493A12F26100E5150FBFF271F4432C81000000000000000000000000
    D9ADD76FC264863D85FBBD1D70076C76ADD320CB000000000000000000000000
00:00:03.554 |I| Loader LoadNca: Application Loaded: Cruis'n Blast v1.07 [0100b41013c82000] [64-bit]
00:00:03.576 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:03.701 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:03.776 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 680/PCIe/SSE2 (4.6.0 NVIDIA 472.98)
00:00:03.820 |I| GPU.MainThread Gpu LoadShaders: Loading 602 shaders from the cache...
00:00:04.848 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:05.644 |I| HLE.GuestThread.15 Ptc LoadTranslations: 40356 translated functions loaded
00:00:05.664 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 0 of 15 functions translated | Thread count: 7
00:00:05.981 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 15 of 15 functions translated | Thread count: 7 in 0.3151501 s
00:00:06.328 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:06.362 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:06.363 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.363 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.379 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed. 
00:00:06.423 |W| HLE.GuestThread.15 KernelSvc PrintResult: MapSharedMemory64 returned error InvalidMemRange.
00:00:06.520 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:06.526 |S| HLE.OsThread.16 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:06.526 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.527 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.693 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:06.694 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:07.341 |S| HLE.OsThread.16 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:07.358 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:07.363 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:07.364 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:07.373 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Handheld,Player1,Player2,Player3,Player4
00:00:07.418 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:07.483 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.588 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:07.590 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:07.591 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:07.591 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:07.592 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:07.592 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:07.593 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:07.596 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:07.607 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:07.611 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:08.080 |I| Ptc Save: Saved Translation Cache (size: 56835927 bytes, translated functions: 45965).
00:00:09.628 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:35.801 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:35.841 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:36.006 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 139059 bytes, profiled functions: 40380).
00:00:36.344 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Handheld,Player1,Player2,Player3,Player4
00:00:36.344 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:36.348 |S| HLE.OsThread.16 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72255575182286848}
00:00:36.352 |S| HLE.OsThread.16 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:43.375 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:43.375 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:59.256 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:59.256 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:59.443 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:59.648 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:00.648 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 2644 took more than 1000ms, resuming execution...
00:01:05.996 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 139132 bytes, profiled functions: 40399).
00:13:50.966 |W| HLE.GuestThread.17 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:13:50.966 |W| HLE.GuestThread.15 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.966 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.966 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.966 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.45 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.41 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.38 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.37 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.36 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.46 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.40 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.47 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:50.967 |W| HLE.GuestThread.48 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:13:51.011 |W| GUI.WindowThread ServiceNv Close: Closing channel
00:13:51.030 |I| HLE.OsThread.7 AudioRenderer ReleaseSessionId: Unregistered output (0)

### Environment?

- Ryujinx version: 1.1.119</br>
- Game version: 1.0.7</br>
- System Specs:
  - OS: *Microsoft Windows 10.0.19044 (X64)*
  - CPU: *i7-3770K CPU @ 3.50GHz ; 8 logical*
  - GPU: *GTX 680 (driver v472,98)*
  - RAM: *8GB*
- Applied Mods : No 

### Additional context?

Additional info about your environment:</br>
00:01:00.648 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 2644 took more than 1000ms, resuming execution...

THE HANG HAPPENS HERE
**00:01:05.996 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 139132 bytes, profiled functions: 40399).**

**Comment by emuline** [comment]
Yes  I confirm this bug, you can use the Last LDN version to play with your save, it does work but not with the last ryujinxor Yuzu...

**Comment by markviv** [comment]
I also confirm that using ryujinx-1.0.0-ldn2.3-win_x64 fixed my Cruis'n Blast save file loading problem.

Cruis'n Blast Save file loading has a problem in:
ryujinx-1.0.0-ldn2.4-win_x64 
ryujinx-1.1.3-win_x64
ryujinx-1.1.120-win_x64



Cruis'n Blast Save file working correctly again using the same problematic save file with ryujinx-1.0.0-ldn2.3-win_x64

**Comment by PeeJayBonobo** [comment]
From my personal save file from my own Switch, I only had to change one byte (offset: 0x05) from 8B to 86 or 85 for my save to work, even though it's kind of annoying to do any hex editing before you can play. Save files straight from Ryujinx seem to accept 8B and 8C.

Tested on 1.1.171 (Master)

Hoo boy, there's a lot of them:
![ryujinx_capture_2022-07-09_14-57-14](https://user-images.githubusercontent.com/3814426/178119319-03f977e7-9ea4-473d-a32a-eb149819d53e.png)
![ryujinx_capture_2022-07-09_14-57-26](https://user-images.githubusercontent.com/3814426/178119320-7a3730e3-b20a-4e8b-893f-95823232314e.png)
![ryujinx_capture_2022-07-09_14-57-38](https://user-images.githubusercontent.com/3814426/178119321-401e13fc-c433-4fff-ada0-eb3ecdf0ddb3.png)
![ryujinx_capture_2022-07-09_14-57-46](https://user-images.githubusercontent.com/3814426/178119322-07616a03-1b7d-487b-a6db-fe0e478e20b4.png)
![ryujinx_capture_2022-07-09_14-57-55](https://user-images.githubusercontent.com/3814426/178119324-2622d644-6e09-4552-ab3c-51619ed83d6a.png)
![ryujinx_capture_2022-07-09_14-58-02](https://user-images.githubusercontent.com/3814426/178119325-cf078876-8a03-4430-bdb8-ea73f2317498.png)
![ryujinx_capture_2022-07-09_14-58-10](https://user-images.githubusercontent.com/3814426/178119326-d88a1acb-a4f7-40fd-a8ef-68ca35af6a3a.png)
![ryujinx_capture_2022-07-09_14-58-17](https://user-images.githubusercontent.com/3814426/178119327-856b7a85-9756-47de-ab7f-137081dfa0a8.png)
![ryujinx_capture_2022-07-09_14-58-25](https://user-images.githubusercontent.com/3814426/178119328-2fe2a646-09eb-4dc9-a9ed-ab32f8af5408.png)
![ryujinx_capture_2022-07-09_14-58-31](https://user-images.githubusercontent.com/3814426/178119330-222184d0-f3b5-43ea-9037-3df0ca3f17bf.png)
![ryujinx_capture_2022-07-09_14-58-42](https://user-images.githubusercontent.com/3814426/178119331-0a3d209d-fec7-40c1-866f-6a66d445adfe.png)
![ryujinx_capture_2022-07-09_14-58-48](https://user-images.githubusercontent.com/3814426/178119332-0343509a-77e4-4b86-b6ea-b21e4201bc13.png)

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3837). Thank you.

**Comment by Nicktamer** [comment]
After many test the save is the problem. Sometimes it work but randomly the game corrupt the save. If the game corrupt the save you Need to delete the save on the folder "1" (not folder 0 if you want to keep progress in the game) Need to do this many times the game crash at startup

**Comment by Nicktamer** [comment]
[Ryujinx_1.1.969_2023-07-30_12-27-29.log](https://github.com/Ryujinx/Ryujinx/files/12208965/Ryujinx_1.1.969_2023-07-30_12-27-29.log)
At the beginning the game run fine but more you play more you have crash. And when finish game the save won't load and game crash at startup. When finish game the save won't load and the fix on previous post no work. Issue still here
