### ISSUE TITLE
Error on launching pokemon Shield

### ISSUE THREAD

**Issue by HFMoles** [Ryujinx/Ryujinx#3331]
E/emu-cpp-HOS-11: Unsupported quantity of audio channels: 6 (Service: IAudioOutManager::OpenAudioOut) (SVC: SvcSendSyncRequest)
    Stack Trace:
    * 0x7BA8B0FC90 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from /data/app/~~QsqsSn0NkiE1YFKDG8qPlA==/skyline.emu-rFdxwtlPadlphMViRjSLMA==/lib/arm64/libskyline.so)
    * 0x8037950CC (from sdk.nso.patch)
    * 0x803826D7C (nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l>, nn::sf::cmif::detail::InHandleArgumentInfo<0, 1>, nn::sf::cmif::detail::OutRawArgumentInfo<16ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<1, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l> >, 16ul, 16ul, true>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l>, nn::sf::cmif::detail::InHandleArgumentInfo<0, 1>, nn::sf::cmif::detail::OutRawArgumentInfo<16ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<1, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l> > >::ProcessWithOutObjects(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<8ul, 4ul, void>, nn::sf::cmif::client::InHandleClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<16ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*) from sdk.nso)
    * 0x803828CD4 (from sdk.nso)
    * 0x80382D524 (nn::audio::OpenAudioOut(nn::audio::AudioOut*, char const*, nn::audio::AudioOutParameter const&) from sdk.nso)
    * 0x80382D684 (nn::audio::OpenDefaultAudioOut(nn::audio::AudioOut*, nn::os::SystemEvent*, nn::audio::AudioOutParameter const&) from sdk.nso)
    * 0x8003AC020 (from main.nso)
    * 0x800381B8C (from main.nso)
    * 0x800382788 (from main.nso)
    * 0x80038333C (from main.nso)
    * 0x80033D7D8 (from main.nso)
    * 0x80033C790 (from main.nso)
    * 0x80033AA94 (from main.nso)
    * 0x803ABFE88 (from sdk.nso)
    * 0x803AC4294 (from sdk.nso)
    * 0x803AC4240 (from sdk.nso)

help me

**Comment by gdkchan** [comment]
This is not a log file generated by Ryujinx.
