### ISSUE TITLE
Strange switch sports

### ISSUE THREAD

**Issue by Dymkar** [Ryujinx/Ryujinx#3332]
If i play Nintendo Switch Sports game has been very strange.

[Ryujinx_1.1.0+9203702_2022-05-11_18-50-29.log](https://github.com/Ryujinx/Ryujinx/files/8671614/Ryujinx_1.1.0%2B9203702_2022-05-11_18-50-29.log)

- Ryujinx version: 1.1.0+9203702
- Game version: 1.1.0
- System Specs:
  - OS: Microsoft Windows 10.0.18362 (X64)
  - CPU: AMD Ryzen 5 3600 6-Core Processor
  - GPU: NVIDIA GeForce GTX 750
  - RAM: 16307 MB
- Applied Mods : No

I used a special PR build.

**Comment by MetrosexualGarbodor** [comment]
This report is useless, the game doesn't run yet and you don't even say what's strange about it. If you have something to report about the PR build you're using, do it on the PR page.
