### ISSUE TITLE
Ryujinx closes when starting smt3

### ISSUE THREAD

**Issue by Observerrr** [Ryujinx/Ryujinx#3333]
Guys can you help when i try to open smt 3 remastered i get a black screen and ryujin instantly closes
![Untitled](https://user-images.githubusercontent.com/105403058/167978196-55c382fd-98ea-4f86-9776-473c7ed7c315.png)

**Comment by MetrosexualGarbodor** [comment]
Your game files are corrupted. Please don't open issues for help, ask on discord instead. https://discord.gg/ryujinx
