### ISSUE TITLE
No More Heroes 3 Resolution Scaling and Mods Don't Work Anymore

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#3334]
## Bug Report

Not exactly sure what happened, but my resolution mods for no more heroes 3 don't work anymore.
The resolution scaler in ryujinx does not work properly on the game, and it never did which was the point of my mods. Now they dont work.
Its likely a regression in how ryujinx handles resolution for unreal engine 4 games, since resolution is defined inside a configuration file.
This is my mod, last time I used it was several months ago so I dont know when the issue first appeared:
https://www.youtube.com/watch?v=NeEmMi4Ado0
All the other improved effects added by mod seem to still be working, so its likely something to do with a change in how ryujinx reads resolution, and there is no other way to change resolution for ue4 games than the way I have done it through the configuration file.

The mod still works properly in Yuzu so it is almost definitely something ryujinx changed.

### Environment?

- Ryujinx version: 1.1.120
- Game version: 1.0.2
- System Specs:
  - OS: Windows 11
  - CPU: AMD 5900x
  - GPU: Nvidia RTX 3090
  - RAM: 32gb
- Applied Mods : Yes, as described

**Comment by gdkchan** [comment]
The resolution is mainly controlled by the game, not the emulator.

**Comment by NikkMann** [comment]
Sorry, you can close this. Redownloaded ryujinx and now its working fine. Really weird, not sure what happened.

**Comment by GamerzHell9137** [comment]
Tested too just to be sure.
It works fine.
