### ISSUE TITLE
Mii Fighter creator in Smash crashes the emulator.

### ISSUE THREAD

**Issue by Paul51** [Ryujinx/Ryujinx#3337]
## Bug Report

N/A

### What's the issue you encountered?

Running Arcropolis in Ryujinx works fine for most cases but Mii Fighter creator crashes the emulator.

### How can the issue be reproduced?

- Run Super Smash Bros: Ultimate
- Go to Mii Fighter creator to create a new Mii Fighter, any type will work.

### Log file
[crash log](https://pastebin.com/5PXN0sck)

### Environment?

- Ryujinx version: 1.1.120 
- Game version: 13.0.1
- System Specs:
  - OS: *Windows 10*
  - CPU: *i5-9600)*
  - GPU: *NVIDIA RTX 2070*
  - RAM: *32GB*
- Applied Mods : [ Yes (Arcropolis)  ]

**Comment by MutantAura** [comment]
Closing in favour of #3369
