### ISSUE TITLE
ldn available as Flatpak or Appimage

### ISSUE THREAD

**Issue by AnthonyViniciusMuller** [Ryujinx/Ryujinx#3350]
#### Overview:
Make available the ldn version as an universal package.

### Why would this feature be useful?
I tried to play in my Fedora 36, but it was required to install a lot of dependencies. Even though it started after all the steps, couldn't play any games as all of them crashed during load.

**Comment by MetrosexualGarbodor** [comment]
This will probably only happen when LDN is merged into the main build, unfortunately.

**Comment by AcK77** [comment]
As the previous comment explain, the LDN build are like preview builds and will be merged to master branch one day.
We will never make it as an universal package. Sorry.

**Comment by autoteelar** [comment]
when do you think that would happen? LDN games seem to crash for me too

**Comment by samumatic** [comment]
Progress has not been made for over half a year: #4716
