### ISSUE TITLE
Blank "Profiles.json" in system folder crash Ryujinx

### ISSUE THREAD

**Issue by BigheadSMZ** [Ryujinx/Ryujinx#3355]
### What's the issue you encountered?
If the file "Profiles.json" contains no text within the "system" folder, Ryujinx will crash just before showing the GUI. I'm honestly not sure why it ended up blank in the first place, but deleting it allowed Ryujinx to create a new file with default information.

### How can the issue be reproduced?
Open Profiles.json and remove all the text and save it. Ryujinx will crash after loading from here on out.

### Log file
No log file was created for this issue. I had to figure out why it was crashing myself using the error message.

### Environment?
It doesn't matter, this applies to all versions including the most recent.

### Additional Info
I am using a "portable" folder to keep everything contained within the main Ryujinx folder, but I doubt that will matter.

**Comment by piplup55** [comment]
json's should have {} in the file, example:

![profile.json](https://user-images.githubusercontent.com/100526773/169671599-f13bfda1-bffe-4fc3-909e-078849e43c8b.png)

**Comment by BigheadSMZ** [comment]
I know how a JSON should look, the problem was Ryujinx (or something) cleared it which then caused it to crash on load. Something went wrong somewhere, I just have no idea what. But no matter how it happened, the contents are gone so it's become useless and just causes this issue. I think a resolution would be if Ryujinx could detect if text is missing or not, or detect if its improperly formatted, etc., and recreate the file like it does now when its missing. Currently Ryujinx already creates the file if it's missing from the folder, so it just needs further detection of whether or not the file contains text. Failing to load it currently just causes a crash, which isn't ideal.

**Comment by piplup55** [comment]
> I know how a JSON should look, the problem was Ryujinx (or something) cleared it which then caused it to crash on load. Something went wrong somewhere, I just have no idea what. But no matter how it happened, the contents are gone so it's become useless and just causes this issue. I think a resolution would be if Ryujinx could detect if text is missing or not, or detect if its improperly formatted, etc., and recreate the file like it does now when its missing. Currently Ryujinx already creates the file if it's missing from the folder, so it just needs further detection of whether or not the file contains text. Failing to load it currently just causes a crash, which isn't ideal.

afaik if your on windows, it's a bug with the way windows writes to files
