### ISSUE TITLE
Root Board Game and Internet connection

### ISSUE THREAD

**Issue by Amnesia1000** [Ryujinx/Ryujinx#3359]
In the Root board game, in order for the DLCs to be enabled, the game must be able to connect to the Dire Wolf Digital servers.

When starting the game without the "Enable guest Internet Access" option, the game starts normally but without the DLCs enabled.
When starting the game with "Enable guest Internet Access", the game goes to a black screen after the first startup screen.

### How can the issue be reproduced?

1)-
Disable the option "Enable Guest Internet Access".
Start the game
DLCs are not enabled
2)-
Enable the option "Enable Guest Internet Access".
Launch the game
The game is black screen after the first screen.

### Log file

[Ryujinx_1.1.132_2022-05-23_11-37-11.zip](https://github.com/Ryujinx/Ryujinx/files/8755479/Ryujinx_1.1.132_2022-05-23_11-37-11.zip)

### Environment?

- Ryujinx version: 1.1.132
- Game version: 1.29.1.1664
- System Specs:
  - OS: Linux 5.17.9-1-MANJARO
  - CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
  - GPU: NVIDIA GeForce GTX 1060 6GB
  - RAM: 24024 MB
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
