### ISSUE TITLE
Stopping emulation and trying to run a game again sometimes results in an error which makes the emulator window stop responding

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#3360]
### What's the issue you encountered?

The emulator crashes when running any game after stopping emulation once in a random given session, with the following error:
`00:00:00.685 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.Memory.WindowsShared.WindowsApiException: VirtualFree returned error code 0x1E7.`
Does not seem to happen on Software memory mode.

### How can the issue be reproduced?

Seems to happen randomly on any given instance of Ryujinx, but if it happens, it's always when trying to boot a game after stopping emulation once. I redownloaded the emulator, tried to reproduce it, and couldn't, but upon restarting Ryujinx, it started happening again. Now I can't get it to happen consistently.

### Log file

[Ryujinx_1.1.132_2022-05-25_21-39-26.log.txt](https://github.com/Ryujinx/Ryujinx/files/8774703/Ryujinx_1.1.132_2022-05-25_21-39-26.log.txt)

**Comment by gdkchan** [comment]
It's fixed by #3347.
