### ISSUE TITLE
Super Mario Odyssey graphical issues in handhand mode on amd

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#3363]
### What's the issue you encountered?

Super Mario Odyssey graphical issues in handhand mode on amd opengl
**Handheld:**  ![image](https://user-images.githubusercontent.com/100526773/170402692-850dbc00-37b7-4e80-b2e6-59aac2d5f23f.png)
![image](https://user-images.githubusercontent.com/100526773/170403826-217b8e4a-c917-4300-9ca7-293f3db11846.png)
**Docked:** ![image](https://user-images.githubusercontent.com/100526773/170403583-574e144d-e158-41aa-9cba-264846d4dd1f.png)
![image](https://user-images.githubusercontent.com/100526773/170403759-1635ab72-1e2d-4829-ae33-3e55fc13e513.png)

### How can the issue be reproduced?

Load a save file in docked mode then switch to handheld mode

### Log file

[Ryujinx_1.1.132_2022-05-26_03-30-31.log](https://github.com/Ryujinx/Ryujinx/files/8775805/Ryujinx_1.1.132_2022-05-26_03-30-31.log)

### Environment?

- Ryujinx version: 1.1.132

- Game version: v1.0.0/v1.1.0

- System Specs:
  - OS: Arch Linux
  - CPU: AMD Ryzen 7 3700X
  - GPU: AMD RX6600
  - RAM: 80gb
- Applied Mods : Yes
- Infinite Cap Dives (IPS Mod)

### Additional context?

Tested v1.0.0 and v1.1.0 both have the issue

**Comment by edisionnano** [comment]
You aren't using radv, this is clearly OpenGL

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format and being sure to check if the issue still occurs on native resolution. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
