### ISSUE TITLE
Mario Strikers: Battle League Football First Kick crashes after loading screen

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#3367]
### What's the issue you encountered?

Game crashes after loading screen

### How can the issue be reproduced?

load the game and it will crash after the loading screen

### Log file

[Ryujinx_1.1.132_2022-05-27_19-34-13.log](https://github.com/Ryujinx/Ryujinx/files/8789260/Ryujinx_1.1.132_2022-05-27_19-34-13.log)

### Environment?

- Ryujinx version: 1.1.132
- Game version: 1.0.0

- System Specs:
  - OS: Arch Linux
  - CPU: AMD Ryzen 7 3700X
  - GPU: RX 6600 xt
  - RAM: 80gb
- Applied Mods: no

### Additional context?

none

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
