### ISSUE TITLE
Cave / Live Wire games freeze Ryujinx and crashes

### ISSUE THREAD

**Issue by Ragnar-es** [Ryujinx/Ryujinx#3368]
### What's the issue you encountered?

Cave / Live Wire games like:

Espgaluda II
DoDonPachi Ressurrection
Mushihimesama

Freezes the emu and crashes, always at the same spot. 

### How can the issue be reproduced?

For Espgaluda II crashes at the end of the 2nd Stage, when it should appear the score count. 
For DoDonPachi Ressurrection it happens at the end of the 4th stage.
For Mushihimesama it crashes at the beginning of the game, when you select the difficulty.

### Environment?

- Ryujinx version: 1.1.32</br>
- Game version: Latest and no Title Update</br>
- System Specs:
  - OS: Microsoft Windows 10.0.19044 (X64)
  - CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  - GPU: NVIDIA GeForce GTX 1080/PCIe/SSE2 (4.6.0 NVIDIA 511.23)
  - RAM: Total 16317 MB ; Available 12400 MB
- Applied Mods : No

### Additional context?

All logs have the same error code at the end, probably it's the same problem. 
I have tried every config possible, different firmwares and different Ryujinx builds, some very old. Also tried with title updates applied and just the base game but always happen the same.

### Log file

[Ryujinx_1.1.132_2022-05-27_20-43-57.log](https://github.com/Ryujinx/Ryujinx/files/8790220/Ryujinx_1.1.132_2022-05-27_20-43-57.log)
[Ryujinx_1.1.132_2022-05-27_20-26-45.log](https://github.com/Ryujinx/Ryujinx/files/8790221/Ryujinx_1.1.132_2022-05-27_20-26-45.log)
[Ryujinx_1.1.132_2022-05-28_03-28-30.log](https://github.com/Ryujinx/Ryujinx/files/8790266/Ryujinx_1.1.132_2022-05-28_03-28-30.log)

**Comment by AcK77** [comment]
Could you provide some same games to reproduce please?

**Comment by Ragnar-es** [comment]
> Could you provide some save games to reproduce please?

There's no option for save, it's a shoot em up game. If you want to see the crash fast and easy use Mushihimesama. It will crash just at the beginning of the game.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
