### ISSUE TITLE
STAR WARS: Knights of the Old Republic has invisible textures in certain locations

### ISSUE THREAD

**Issue by CptCookies12** [Ryujinx/Ryujinx#3370]
### What's the issue you encountered?
Certain locations in KOTOR have invisible/missing textures. From the first several hours of the game that I was able to play, this only seemed to noticeably happen in cantina areas, as well as the lower sewers to a lesser extent as it only shows on the railings and parts of the floor. The texture of eyes on certain characters also seems to be missing too, but this happens far less frequently; I've only seen it on these particular alien NPCs and it also doesn't affect all of them because they can have different eye textures.

![Ryujinx_MWokACFSM6](https://user-images.githubusercontent.com/53424054/170891533-324fb4d7-8a2a-4119-9c21-abe2aad46690.png)
![Ryujinx_TwZmxEXJ8m](https://user-images.githubusercontent.com/53424054/170891399-201d02d4-92f7-401a-a6e5-d2bc0cd658ea.png)
![Ryujinx_lEtfOaPIGM](https://user-images.githubusercontent.com/53424054/170891537-40518fcc-c35c-4b97-a55f-81b98205a53a.jpg)

### How can the issue be reproduced?
Go to either any of the cantina locations on Taris (first major world in the game); they all share the same map and have the same invisible texture. The lower sewers also have this issue on the railings, and a small handful of NPCs can also be seen with this problem. I've also uploaded my save file so you can quickly load into these locations; the three save slots I have should load you directly to each location with the bugged textures.
[kotor-ryujinx-texture-bug-save.zip](https://github.com/Ryujinx/Ryujinx/files/8794318/kotor-ryujinx-texture-bug-save.zip)

### Log file
Cantina: 
[Ryujinx_1.1.132_2022-05-29_14-13-24.log](https://github.com/Ryujinx/Ryujinx/files/8794312/Ryujinx_1.1.132_2022-05-29_14-13-24.log)
Lower Sewers: 
[Ryujinx_1.1.132_2022-05-29_13-52-59.log](https://github.com/Ryujinx/Ryujinx/files/8794303/Ryujinx_1.1.132_2022-05-29_13-52-59.log)

### Environment?
- Ryujinx version: 1.1.132</br>
- Game version: 1.0.2</br>
- System Specs:
  - OS: *Windows 11 Home 64-bit, 21H2*
  - CPU: *AMD Ryzen 9 5900HS with Radeon Graphics*
  - GPU: *NVIDIA GeForce RTX 3070 Laptop GPU*
  - RAM: *16GB*
- Applied Mods : No

### Additional context?
Additional info about your environment:</br>
My computer is an Asus Zephyrus G15 (2021) with Nvidia Optimus; Ryujinx should be running with the Nvidia GPU as it's set both in the Windows Graphics settings and also Nvidia Control Panel. I haven't had an issue with this on anything else on Ryujinx.

**Comment by GamerzHell9137** [comment]
Maybe testing https://github.com/Ryujinx/Ryujinx/pull/3005 is worth a try?

**Comment by CptCookies12** [comment]
> Maybe testing it with #3005 is worth a try?

Can't seem to actually download any of the artifacts for that, probably too old? I did try the most recent Vulkan build at least to see if there was any difference and that didn't fix the issue either.

**Comment by GamerzHell9137** [comment]
> > Maybe testing it with #3005 is worth a try?
> 
> Can't seem to actually download any of the artifacts for that, probably too old? I did try the most recent Vulkan build at least to see if there was any difference and that didn't fix the issue either.

Drop your save where the issue happens here.

**Comment by CptCookies12** [comment]
> > > Maybe testing it with #3005 is worth a try?
> > 
> > 
> > Can't seem to actually download any of the artifacts for that, probably too old? I did try the most recent Vulkan build at least to see if there was any difference and that didn't fix the issue either.
> 
> Drop your save where the issue happens here.

Save was already uploaded in the first post, but I can upload it again here.
[kotor-ryujinx-texture-bug-save.zip](https://github.com/Ryujinx/Ryujinx/files/8794730/kotor-ryujinx-texture-bug-save.zip)

**Comment by MrSunabouzu** [comment]
![image](https://user-images.githubusercontent.com/34666436/171038744-b8463c14-72ee-45df-924c-b304640a0917.png)

I also get missing textures on 1.1.132. That and anytime the game has a visual overlay like for security cams it tanks performance. Otherwise seems to be functioning fine?

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
