### ISSUE TITLE
latest ffmpeg is 5, yet ryu looks for the old one (4.4)

### ISSUE THREAD

**Issue by Harsh534** [Ryujinx/Ryujinx#3377]
### What's the issue you encountered?

Any game that (I believe) uses mpeg cut-scenes instantly gets CTD, for ex. Monster hunter rise</br>

### How can the issue be reproduced?

On fedora linux by installing ryujinx using pinejinx script from terminal, set it up and launch a game with MPEG intro cut scenes (Monster hunter rise in my case) and the emulator will CTD </br>

### Log file

[Ryujinx_1.1.136_2022-06-01_19-00-34.log](https://github.com/Ryujinx/Ryujinx/files/8814761/Ryujinx_1.1.136_2022-06-01_19-00-34.log)

### Environment?

- Ryujinx version: 1.1.136</br>
- Game version: 3.9.1</br>
- System Specs:
  - OS: Fedora Linux 36
  - CPU: Ryzen 5 5600X
  - GPU: RX 580 
  - RAM: 16GB
- Applied Mods : No

**Comment by AcK77** [comment]
As the error said:
> System.DllNotFoundException: Unable to load DLL 'avutil.56 under /home/virums/.local/share/Ryujinx/': The specified module could not be found.

So I don’t think it’s related to the ffmpeg version but maybe to the way we search the library (https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Graphics.Nvdec.FFmpeg/FFmpegContext.cs#L67)

**Comment by edisionnano** [comment]
The abi has changed on ffmpeg 5, it should be looking for avutil.57.

**Comment by ActualMandM** [comment]
Can confirm that the emulator crashes whenever a video tries to be played.
![image](https://user-images.githubusercontent.com/15317421/178592965-0827a3e8-e5b4-406b-9414-b49bfb6ca998.png)
[Ryujinx_1.1.178_2022-07-12_13-52-27.log](https://github.com/Ryujinx/Ryujinx/files/9096772/Ryujinx_1.1.178_2022-07-12_13-52-27.log)
