### ISSUE TITLE
When updating ryujinx ithin the program on linux the resulting binary is not execuatble

### ISSUE THREAD

**Issue by Blad3forc3** [Ryujinx/Ryujinx#3379]
## Bug Report

Running the linux build and then accepting the update, after downloading and restarting the resulting linux binary is not executable

You have to manually set the binary as execuatble to run ryujinx again

### How can the issue be reproduced?

Update the linux build from within the program and restart, ryujinx does not restart unless you set the downloaded binary to executable

### Log file

N/A

### Environment?

- System Specs:
  - OS: *KDE NEON*
  - CPU: *i5*
  - GPU: *Nvidia 1080ti*
  - RAM: *32GB*
- Applied Mods : [ No ]

### Additional context?

N/A

Update to this, Ryujinx doesnt restart but the binary is set to executable

**Comment by mstreurman** [comment]
Running Ubuntu Jammy here and it works fine here.

**Comment by Blad3forc3** [comment]
After accepting the update and installing it, it requests "Do you want to restart?" Selecting yes just closes ryujinx without restarting

**Comment by A-w-x** [comment]
same on archlinux but the binary has exec permission, the updater is failing to run the new binary so you just run ryu again manually

**Comment by TSRBerry** [comment]
Should be fixed with #4315
