### ISSUE TITLE
A Hat in Time not working with saves imported.

### ISSUE THREAD

**Issue by Theslees** [Ryujinx/Ryujinx#3390]
### What's the issue you encountered?

[ A Hat in Time has perfect compalibility when it comes to the Vulkan build (rendering it better than the mainline build) but when trying to use any save dumps in it, the game does not load, with a not-so common error...]</br>
[ I tested both the Vukan, and mainline builds of Ryujinx. ]</br>

### How can the issue be reproduced?

[ Have A Hat in Time, the DLC, and Update all in Ryujinx. Then play the game through on hardware and get near endgame. Dump the save and fire it up on Ryujinx. Crash. ]

### Log file
Mainline;
[Ryujinx_1.1.142_2022-06-06_19-18-40.log](https://github.com/Ryujinx/Ryujinx/files/8848872/Ryujinx_1.1.142_2022-06-06_19-18-40.log)

Slightly different error for Vulkan, thought that detail alone was pretty significant so I'm leaving the log for vulkan here aswell;
[Ryujinx_1.1.0+06c2547_2022-06-06_19-36-37.log](https://github.com/Ryujinx/Ryujinx/files/8848911/Ryujinx_1.1.0%2B06c2547_2022-06-06_19-36-37.log)

### Environment?

- Ryujinx version: 1.0.142</br>

- A Hat in Time version: 1.0.4 (tested with 1.0.3 and 1.0.2 aswell, same results.)</br>
- System Specs:
  - OS: *(Arch Linux 5.18.1-arch1-1)*
  - CPU: *(AMD Ryzen 5 5600G)*
  - GPU: *(APU Radeon Vega 8 intergrated graphics)*
  - RAM: *(32GB Dual Channel)*
- Applied Mods : [ *No* ]

### Additional context?

Here is the save I'm using for testing, extract the file in this archive in the root of the save directory for AHiT ^^;
[A Hat in Time GameState.tar.gz](https://github.com/Ryujinx/Ryujinx/files/8848886/A.Hat.in.Time.GameState.tar.gz)

**Comment by DBTDerpbox** [comment]
from what i know, the drawing you create at the end of the first dead bird studio level causes issues with the game trying to display your drawing on your save icon

this is a complete guess from what information ive found about ahit crashing on ryujinx with a save file, so take it with a grain of salt
