### ISSUE TITLE
Flickering geometry on Xenoblade Chronicles Definitive Edition

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#3392]
### What's the issue you encountered?

Some walls and floors in this game suffer from flickering which looks like Z-fighting. 

https://user-images.githubusercontent.com/79612681/172356216-b8997c3f-4b24-43e9-b847-720dab6db519.mp4

Does not happen on real hardware.

https://user-images.githubusercontent.com/79612681/173209178-df820f9b-e105-418b-9d83-7ab1f72c3889.mp4

### How can the issue be reproduced?

Use this save file, load the autosave, walk forward. Saves 1 and 2 are also on spots where it can be seen, no input required.

[0.zip](https://github.com/Ryujinx/Ryujinx/files/8852317/0.zip)

### Log file

[Ryujinx_1.1.142_2022-06-07_10-43-38.log](https://github.com/Ryujinx/Ryujinx/files/8852321/Ryujinx_1.1.142_2022-06-07_10-43-38.log)

**Comment by MarkLanders777** [comment]
It flickers indeed, but a little less here

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
