### ISSUE TITLE
[Feature Request] Auto load default controller profile when a controller is selected in input devices

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#3395]
#### Overview:
Have the emulator automatically load the default profile instead of having every button unbound by default.

### Why would this feature be useful?
Many people (myself included) don't realize at first that the "Load" button can just skip 99% of the process of binding everything individually. This would make end-users' lives easier and the emulator would require even less setup than it already does.

**Comment by MutantAura** [comment]
Fixed in #3351
