### ISSUE TITLE
[Feature Request] Expose games' build ID on the UI or have an option to copy them for cheat management

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#3397]
#### Overview:
Expose or have a way for the end user to copy a game's build ID from the UI in order to create a cheats file.

### Why would this feature be useful?
Some cheats just come with the cheat code itself and people are left to figure out what their .txt file has to be named. This would help avoid that.

**Comment by gnisman** [comment]
@MetrosexualGarbodor Ava UI on master branch already expose the tittle id in games window.
We can always add a copy to clipboard button in Mange Cheats window, what do you think?

**Comment by gdkchan** [comment]
This is asking to expose the build ID on the UI, not the title ID.

**Comment by gnisman** [comment]
@gdkchan I got a question before i dive into it I want to make sure i understand the request
are we interested to show only the build id that comes from main ExeFs? (I think that is the one that used for cheats)

![08B56331-81F6-4166-95BD-1C281E44A5A5](https://user-images.githubusercontent.com/11611112/213944448-1ed568df-2229-4ca1-97ea-5fbbea2a7424.jpeg)

adding it to the Ryujinx title meets the request?

**Comment by MutantAura** [comment]
Personally I don't think the top bar is particularly useful and just adds bloat. Ideally I think it should show in the "manage cheats" page instead of the titleID which isn't relevant for cheat use.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/44103205/213945547-af9100ea-d4e4-425d-beab-9be1ab3e0088.png">

**Comment by OldManKain** [comment]
> Personally I don't think the top bar is particularly useful and just adds bloat. Ideally I think it should show in the "manage cheats" page instead of the titleID which isn't relevant for cheat use. <img alt="image" width="361" src="https://user-images.githubusercontent.com/44103205/213945547-af9100ea-d4e4-425d-beab-9be1ab3e0088.png">
> 
> So if you wanted to find out what the build ID was (for installing cheats) then your first place to check would surely be the manage cheats page.

This is where I feel it should be, as of right now the only ways of getting the current Build ID is in the console or log file it's the first 16 hexadecimal characters of line 2 here.
![image](https://user-images.githubusercontent.com/47503099/213945855-bb39021c-ba6c-45ab-95df-359e11d24336.png)

The only other way is to open the main file in a hex editor and it is the first 32 bytes at offset 0x40
![image](https://user-images.githubusercontent.com/47503099/213946049-fafe7da7-32db-4cd0-b6d9-4a73fc7c3e83.png)

I usually try to make sure to post the BID and Horizon OS Version # of the game when I post cheats but not everyone understands what to do, so I end up holding their hands to get the cheats to work.

**Comment by MetrosexualGarbodor** [comment]
I feel like the best way to go about this might be automatically creating an empty cheats file, but this is also more work than just exposing the BID.

**Comment by gdkchan** [comment]
Yea, showing it on the cheat window seems better. Maybe also with a copy button for convenience.

**Comment by OldManKain** [comment]
> 

This isn't that bad of an Idea, but I could see an issue of multiple BID.txt in the cheat folder after updates that would/could confuse users also.

**Comment by titoporky** [comment]
Hi,

Random question.

Do you experience that even you download the base  game with correct Title ID, still giving you different build ID for your cheats?

How can I download the correct build ID so I can apply the available cheats?

Thank you in advance!
