### ISSUE TITLE
Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.

### ISSUE THREAD

**Issue by Frogperson** [Ryujinx/Ryujinx#3409]
### What's the issue you encountered?

Ryujinx crashes with the following error when launching any game.
```
Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64, Int32)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

### How can the issue be reproduced?

Install a fresh version of Ryujinx
Add firmware and keys
Launch a game

### Log file

[Ryujinx_1.1.151_2022-06-21_15-51-51.log](https://github.com/Ryujinx/Ryujinx/files/8952410/Ryujinx_1.1.151_2022-06-21_15-51-51.log)

### Environment?

- Ryujinx version: 1.1.151</br>
- System Specs:
  - OS: Windows 11 Insider Preview Build 22621
  - CPU: i7-10700KF
  - GPU: NVIDIA RTX 3080
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Everything was working perfectly yesterday with the same setup. I was even able to launch it once today as well, after doing a fresh install (creating the "portable" folder as well). However, fresh installs no longer seem to be fixing it for me, and nothing I tried is working.
I did some additional troubleshooting with Blargle in #support on the Discord starting here https://canary.discord.com/channels/410208534861447168/410208610455519243/988876156562444369

**Comment by AcK77** [comment]
Is the issue still occurs?

**Comment by AcK77** [comment]
No more informations since my last comment, I never seen this issue again. I close it.
