### ISSUE TITLE
Super Zangyura - Graphical regression, almost all textures are garbage and flickery

### ISSUE THREAD

**Issue by n1ghttrap** [Ryujinx/Ryujinx#3419]
Per topic, can be reproduced in any recent build as of the last few days. Not sure when it started exactly.  Worked about a month ago.  Tried both the updated plain build 1.1.157 and the Vulkan build  1.1.0+1c895ed.   This happens on two different machines, a desktop with a 3060 + 5800x and a laptop with a 1060 + i7 8750h.  Latest Nvidia drivers (as of this post), 32gb, and Win10 for each.   JP and US versions of the game both have the same issue.

[ryulog.txt](https://github.com/Ryujinx/Ryujinx/files/8982517/ryulog.txt)
![ryuscreenshot](https://user-images.githubusercontent.com/30274474/175725041-96eeea27-434c-4968-865d-3ab9eb854285.PNG)

**Comment by gdkchan** [comment]
It was broken by #3399.
