### ISSUE TITLE
The game "Re:ZERO -Starting Life in Another World- The Prophecy of the Throne" only show a black screen, but I can hear the sound of the game and interact with it.

### ISSUE THREAD

**Issue by Arthurfogo7** [Ryujinx/Ryujinx#3426]
### How can the issue be reproduced?
The video that I recorded shows everything

### Log file

[message.txt](https://github.com/Ryujinx/Ryujinx/files/8993932/message.txt)

- Ryujinx version: 1.1.159
- Game version: 1.0.2
- 

https://user-images.githubusercontent.com/85951083/175986934-fc4c69ca-d0b7-4281-a5d4-802a7731f85d.mp4

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
