### ISSUE TITLE
Ryujinx does not build under Linux

### ISSUE THREAD

**Issue by vulpes2** [Ryujinx/Ryujinx#3427]
### What's the issue you encountered?

I tried building Ryujinx today but found out that it does not build under Linux. Tested with `dotnet build -c Release -o build` and it fails with the following error:
```
CSC : warning CS8032: An instance of analyzer Ryujinx.Horizon.Generators.Kernel.SyscallGenerator cannot be created from /home/user/src/Ryujinx/build/Ryujinx.Horizon.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/user/src/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj]
/home/user/src/Ryujinx/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallHandler.cs(34,17): error CS0103: The name 'SyscallDispatch' does not exist in the current context [/home/user/src/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj]
/home/user/src/Ryujinx/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallHandler.cs(38,17): error CS0103: The name 'SyscallDispatch' does not exist in the current context [/home/user/src/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj]

Build FAILED.

CSC : warning CS8032: An instance of analyzer Ryujinx.Horizon.Generators.Kernel.SyscallGenerator cannot be created from /home/user/src/Ryujinx/build/Ryujinx.Horizon.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/user/src/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj]
/home/user/src/Ryujinx/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallHandler.cs(34,17): error CS0103: The name 'SyscallDispatch' does not exist in the current context [/home/user/src/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj]
/home/user/src/Ryujinx/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallHandler.cs(38,17): error CS0103: The name 'SyscallDispatch' does not exist in the current context [/home/user/src/Ryujinx/Ryujinx.HLE/Ryujinx.HLE.csproj]
    1 Warning(s)
    2 Error(s)
```

Tested building on Windows with the same command and it worked fine.

### How can the issue be reproduced?

1. Install a supported version of the .NET SDK on Linux
2. Clone project
3. `dotnet build -c Release -o build`

### Log file

Not applicable.

### Environment?

- Ryujinx version: master bdc4fa81f23d61947678c03f6ebef0a5d9100124
- System Specs:
  - OS: Fedora Linux 36
  -  .NET SDK Version: 6.0.106

**Comment by vulpes2** [comment]
Went back in the commit history and 0c87bf9ea4b0655fc6b90b4ab20e93f237e7549b is the last commit that will still build under Linux.

**Comment by gdkchan** [comment]
It needs .NET SDK 6.0.300. This is not a Linux specific issue.

**Comment by vulpes2** [comment]
I see, that explains it. I was not aware of the differences between the two current releases (6.0.1xx and 6.0.3xx). Could the README be updated to reflect this specific requirement? On the download page of the .NET SDK, both 6.0.301 and 6.0.106 are listed as current releases under 6.0.6 with no clear indication of the differences.

**Comment by albfan** [comment]
Info to install manually sdk on linux:

[SyscallDispatch](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual)
