### ISSUE TITLE
Fire Emblem 3 Hopes, same graphical issues as seen in Age of Calamity under the Vulkan backend (AMD RX series-only issue?)

### ISSUE THREAD

**Issue by AutumnWolfMike** [Ryujinx/Ryujinx#3428]
### What's the issue you encountered?

The ground is messed up on both games under the Vulkan backend on RX 500 series AMD GPUs. 

It is a garbled mess. </br>

![ryujinx_capture_2022-06-28_10-35-53](https://user-images.githubusercontent.com/98867177/176235953-ac0f1469-fd0d-4c6d-b46f-05c234f41b44.png)

Did you make any changes related to Ryujinx itself?

No</br>

### How can the issue be reproduced?

Play the game on an AMD RX 500 series GPU using the Vulkan backend.

### Log file

[Ryujinx_1.1.0+1c895ed_2022-06-28_10-25-33.log](https://github.com/Ryujinx/Ryujinx/files/9003127/Ryujinx_1.1.0%2B1c895ed_2022-06-28_10-25-33.log)

### Environment?

- Ryujinx version: Ryujinx_1.1.0+1c895ed</br>
- Game version: 1.0.1</br>

- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 3500X
  - GPU: RX 570 4GB VRAM
  - RAM: 16B RAM
- Applied Mods : No

### Additional context?

The game runs well aside from that, the audio stutters a bit.

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for open PRs and comment on the PRs themselves. And yes this is a Polaris issue.

**Comment by AutumnWolfMike** [comment]
Do I post it with the same format?

**Comment by AutumnWolfMike** [comment]
Alright, thank you
