### ISSUE TITLE
Program stalls on exit/stop emulation if the shader count is greater than 10000

### ISSUE THREAD

**Issue by SteelRazor47** [Ryujinx/Ryujinx#3433]
### What's the issue you encountered?

When closing the UI application directly, after loading a game with more than 10000 shaders, the UI never closes.  
Closing the console directly works fine.

### How can the issue be reproduced?
1. Load a game with more than 10000 shaders
2. Press the exit button or the stop emulation button

### Environment?

- Ryujinx version: 1.1.146</br>
- Game version: any</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 1600
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

I've been trying to fix it myself but multithreading goes way above my head.  
The problem seems to be that on exit, the Gui.RenderLoop thread is almost instantly terminated. After that, while calling Renderer.Dispose(), the render queue gets filled(i assume with commands to delete shaders) but never emptied. If the command count gets above the renderer limit the thread sleeps until the queue is freed up, which never happens as the "consuming thread" has already been joined.

**Comment by gdkchan** [comment]
Sounds like a duplicate of #2863. Some analysis of the issue at https://github.com/Ryujinx/Ryujinx/pull/2875#issuecomment-979516342.

**Comment by SteelRazor47** [comment]
Yes looks exactly like it, i tried finding an existing issue but my keyword skills aren't great. I'll look more into it, i really enjoy trying to fix this kind of stuff.

**Comment by gdkchan** [comment]
It might be better to remove the resource (buffers, textures, shaders etc) disposal on the GPU emulator and move them to the OpenGL backend instead. Then when the renderer instance is disposed, it would dispose everything. Shouldn't run into the problem because it does not need to queue the disposal commands this way. And it would make some of the GPU disposal simpler too.
