### ISSUE TITLE
Snipperclips Plus [0100704000B3A000]: Random Shapes option not working

### ISSUE THREAD

**Issue by rna0** [Ryujinx/Ryujinx#3436]
### What's the issue you encountered?
 When selecting the option for Random Shapes from the in game menu, Snipperclips Plus with update 1.1.0, Ryujinx does not give any error and runs the game with the default shapes. I have checked this feature on a regular Nintendo Switch and the shapes are randomized.

### How can the issue be reproduced?
First, you need to finish the game once to get the option to select random shapes (I have linked my own save file in Additional context).
When opening the game "Snipperclips Plus" I selected the option for one player, then the left choice for 1-2 players and then when selecting any level When asked to play with default shapes or random ones I selected "RANDOM SHAPES" and then was presented with the default ones, after finishing the level I still got the colored mark meaning the game new I completed the game at random mode without but no matter how many times and how many levels I played they were always the Default ones.

### Log file

[Ryujinx_1.1.160_2022-07-02_12-28-15.log](https://github.com/Ryujinx/Ryujinx/files/9032757/Ryujinx_1.1.160_2022-07-02_12-28-15.log)

### Environment?

- Ryujinx version: 1.1.206</br>
- Snipperclips Plus: Game version: 1.1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 3600
  - GPU: NVIDIA RTX 2060 S
  - RAM: 16307 MB
- Applied Mods : No

### Additional context:

Here is the save file to get the Menu to Use random shapes:
[Snipperclips Plus save file.zip](https://github.com/Ryujinx/Ryujinx/files/9257284/Snipperclips.Plus.save.file.zip)

Here are some screenshots for context
Ramdom shapes:
<img width="680" alt="Ryujinx_JaHPj1FSb4" src="https://user-images.githubusercontent.com/47921907/176995432-e1a76159-d780-4dbd-980f-5d1074b2e545.png">

After choosing random (Ryujinx):
<img width="681" alt="Ryujinx_5rvsRF0BU2" src="https://user-images.githubusercontent.com/47921907/176995446-60dcdb0e-c900-47ec-aed8-855376af477b.png">

After choosing random (Switch):
![snipperclips-plus-screenshot-10-3514780235](https://user-images.githubusercontent.com/47921907/176995487-c58c4c8a-efbf-4947-85a0-2fa4525d18bb.jpg)

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
