### ISSUE TITLE
Audio issue with Taiko no Tatsujin: Nintendo Switch Version!

### ISSUE THREAD

**Issue by Kurohisui** [Ryujinx/Ryujinx#3440]
### What's the issue you encountered?

Audio doesn't sound correctly.</br>
I didn't make any changes in Ryujinx, I just updated it to its most recent version. (**1.1.164**)</br>

### How can the issue be reproduced?

Just opened the game. However this problem didn't happen in older versions, I'm not entirely sure which ones because I haven't played the game in weeks.
### Log file
[Log](https://github.com/Ryujinx/Ryujinx/files/9050603/Ryujinx_1.1.164_2022-07-05_21-56-09.log)

### Environment?

- Ryujinx version: 1.1.164</br>
- Game version: 1.4.8</br>
- System Specs:
  - OS:  Windows 10
  - CPU: Ryzen 5 | 2600
  - GPU: NVIDIA RTX 2060
  - RAM: 32GB
- Applied Mods : No

### Additional context?

I tried changing a few options such as audio output, but nothing worked.

Footage:

https://user-images.githubusercontent.com/20346785/177443949-eeb7cf56-ec62-4b7f-a4a6-a636a0ccb246.mp4

**Comment by GamerzHell9137** [comment]
Try changing audio backends?

**Comment by Thog** [comment]
> ## Bug Report
> ### What's the issue you encountered?
> 
> Audio doesn't sound correctly. I didn't make any changes in Ryujinx, I just updated it to its most recent version. (**1.1.164**)
> ### How can the issue be reproduced?
> 
> Just opened the game. However this problem didn't happen in older versions, I'm not entirely sure which ones because I haven't played the game in weeks.
> ### Log file
> 
> [Log](https://github.com/Ryujinx/Ryujinx/files/9050603/Ryujinx_1.1.164_2022-07-05_21-56-09.log)
> ### Environment?
> 
>     * Ryujinx version: 1.1.164
> 
>     * Game version: 1.4.8
> 
>     * System Specs:
>       
>       * OS:  Windows 10
>       * CPU: Ryzen 5 | 2600
>       * GPU: NVIDIA RTX 2060
>       * RAM: 32GB
> 
>     * Applied Mods : No
> 
> 
> ### Additional context?
> 
> I tried changing a few options such as audio output, but nothing worked.
> 
> Footage:
> taiko.switch3869873.mp4

This is a known issue with OpenAL, can you try with another audio backend like SDL2 to confirm it's only specific to it?

**Comment by Kurohisui** [comment]
> 

Sorry for the late reply. 
I'll try with another audio backend.

**Comment by Kurohisui** [comment]
It worked when I changed the audio backend to SDL2. I am not sure if I should close this issue now, but my problem got solved.

Thank you very much.
