### ISSUE TITLE
Ryujinx not booting any game (|E| Application : Unhandled exception caught)

### ISSUE THREAD

**Issue by Volderhein** [Ryujinx/Ryujinx#3463]
### Ryujinx suddenly stopped booting games

So, after building a new PC, I decided I wanted to try switch emulation. Read a bit about it and downloaded Ryujinx. Was working like a charm. It wasn't until this week, though, that I noticed the emulator wasn't booting up any game at all anymore.</br>
The only thing I remember doing that could actually mess with anything was updating to Nvidia's most recent drivers (516.59). I have previously struggled with other PC's I owned being stable with Nvidia's latest drivers so before updating I was using a driver version that was probably 2-3 months old. I don't remember exactly which one, though, but the issue with Ryujinx did come up 2-3 days ago, almost as the same time as I updated the drivers.</br>

### How can the issue be reproduced?

At this point I've found no way to actually boot games from the emulators as of now. It just "crashes". It even keeps doing so after purging it and deleting it in entirety from my computer and then reinstalling again from scratch. It keeps doing so even with most recent firmware (14.1.2) and keys. (Originally running 14.0.0 keys and fw before issue started)

### Log file

[Ryujinx_1.1.171_2022-07-12_20-25-38.log](https://github.com/Ryujinx/Ryujinx/files/9098128/Ryujinx_1.1.171_2022-07-12_20-25-38.log)

### Environment?

- Ryujinx version: 1.1.171</br>

- Game version: 1.0.0 (Kirby & the Forgotten land, but this also happens with games on their base and updated versions)</br>
- System Specs:
  - OS: Windows 10
  - CPU: I5-10400F
  - GPU: NVIDIA GTX 1070
  - RAM: 16GB
- Applied Mods : Yes, 60FPS mod (Also tried games without mods)

### Additional context?
Not really anything of note.
Additional info about your environment: Been having this issue as of 3-4 days ago, which means that I've tested it over all several updates that the emulator has received as of the moment of writing this. I also have ryujinx installed on drive C while my switch dumps are located in drive D. I don't think it has anything to do since it was working fine, but might as well just mention it.</br>

**Comment by gdkchan** [comment]
I would guess that your firmware is corrupted. Have you tried re-installing it? Could also be missing keys, but then you wouldn't be able to install the firmware in the first place, unless you modified the prod.keys file after installing the firmware.

**Comment by Volderhein** [comment]
@gdkchan I had a 14.0.0 firmware that worked fine but since the issue came up, I've also tried a 14.1.2 firmware (loaded from a .ZIP file) to no avail, showing the same results. I also haven't modified the keys at all, so no idea.

**Comment by Volderhein** [comment]
I've already tried reinstalling both versions of the firmware and it still doesn't work.

**Comment by Volderhein** [comment]
@gdkchan Ok I've fixed it. I went back to the older Nvidia drivers I had before updating. Went from 516.59 to 512.95. I'll be closing this thread, then.
