### ISSUE TITLE
Sid Meier's Civilization VI [010044500C182000]: Missing graphics (2D and 3D)

### ISSUE THREAD

**Issue by ChrisNonyminus** [Ryujinx/Ryujinx#3468]
## Bug Report

</br>

### What's the issue you encountered?

When in-game in Civilization VI, the game "runs", but there are missing graphics. The environment, character models, and more don't appear, leaving a black screen. </br>
</br>

### How can the issue be reproduced?

1. Open Civilization VI in Ryujinx.
2. Wait for the game to load the title screen.
3. Select "Singleplayer", and then "Play Now".
4. Wait for the game to load.
5. When "BEGIN GAME" appears, press A.

### Log file

[Ryujinx_1.1.180_2022-07-14_12-36-47.log](https://github.com/Ryujinx/Ryujinx/files/9114491/Ryujinx_1.1.180_2022-07-14_12-36-47.log)</br>

### Environment?

- Ryujinx version: 1.1.180</br>

- Game version: 1.2.14</br>

- System Specs:
  - OS: Windows 10
  - CPU: i7-8700K
  - GPU: NVIDIA GTX 1070Ti
  - RAM: 32GB
- Applied Mods : No

### Additional context?
N/A

### Screenshots:
![Ryujinx_qa7wykoi8A](https://user-images.githubusercontent.com/50080567/179059310-5c9ab3d2-9971-45cb-ad69-933c6c6946c1.png)
![Ryujinx_xeLqLxoywQ](https://user-images.githubusercontent.com/50080567/179059328-0f3d9afd-093e-4e99-b5a6-2b39283a6ac9.png)

**Comment by EmulationFanatic** [comment]
[Civ VI](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1491) has been tested to be working fine now.

**Comment by GabeThe21stGamer** [comment]
Same issue on the same game version. I tried it on Vulkan and OpenGL on Ryujinx 1.1.338

**Comment by truman526** [comment]
> [Civ VI](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1491) has been tested to be working fine now.

What's the setting ? I cannot play the game .

**Comment by altiereslima** [comment]
Confirmed, Game version: 1.2.14 missing graphics.
