### ISSUE TITLE
Sfdnsres IResolver: 14 ([5.0.0+] ResolverSetOptionRequest) is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#3479]
### What service call is missing?

Sfdnsres IResolver: 14 ([5.0.0+] ResolverSetOptionRequest) is not implemented

[Switchbrew](https://switchbrew.org/wiki/Sockets_services) | 

### Service description
```
n/a
```

### Log:

[Log.log](https://github.com/Ryujinx/Ryujinx/files/9159124/Log.log)

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/1450 crashes in early splash screens with Enable guest Internet Access. Game boots fine with this option disabled.

**Comment by GamerzHell9137** [comment]
Seems like a lot of games have this issue 
![image](https://user-images.githubusercontent.com/2002038/181119256-0f1354f8-bd0a-433c-81a9-b626a83b7223.png)

**Comment by EmulationFanatic** [comment]
There are many IResolver services. The "14" one is not very common.

**Comment by GamerzHell9137** [comment]
Ohhh its specific 14 one, my bad.
