### ISSUE TITLE
Add Chinese function options(添加汉化功能选项)

### ISSUE THREAD

**Issue by 123shuhai** [Ryujinx/Ryujinx#3484]
**Hello, author! I wonder if it is possible to develop the Chinese function, add a Chinese interface option in the simulator Settings, or develop a Chinese package to achieve the effect of the Chinese interface of the simulator.**
作者，你好！不知道能否开发一下汉化功能，在模拟器设置内添加一个中文汉化界面选项，或者开发一个中文汉化包来达到模拟器界面汉化的效果。
![捕获](https://user-images.githubusercontent.com/105191099/180636700-ea207d33-ceca-4de3-a7a0-dc3777ddd6a4.JPG)

**Comment by SiongSng** [comment]
如果你是用 Avalonia 版本的話已經有支援簡體中文了
If you are using the Avalonia version, it already supports Simplified Chinese

**Comment by 123shuhai** [comment]
真的吗？可是我找不到，

**Comment by SiongSng** [comment]
有阿，下載連結 (windows)：https://github.com/Ryujinx/release-channel-master/releases/download/1.1.186/test-ava-ryujinx-1.1.186-win_x64.zip
只不過 Avalonia 版還不是很穩定
