### ISSUE TITLE
Avalonia DLC Manager broken after 1.1.187 (Last working 1.1.185) NullReferenceException

### ISSUE THREAD

**Issue by Squall-Leonhart** [Ryujinx/Ryujinx#3491]
### What's the issue you encountered?

NullReferenceException thrown when either of these conditions are met

* Opening the Manage DLC window for a game that already has DLC added
* Selecting 1 or more DLC in the file browser and adding them
* Clicking Remove, Remove All, or Save on the DLC manager screen for a title that has no DLC added.

These issues do not replicate under the original Ryujinx GUI, or on Avalonia 1.1.185

### How can the issue be reproduced?

1. Right click a title that already has DLC added
2. Select Manage DLC

or

1. Right click a title that has not yet had DLC added, 
2. Select Manage DLC
3. Click Add (or Remove, Remove All, Save)
4. Browse to and add a DLC file.

### Log file

[Ryujinx_1.1.187_2022-07-27_06-45-26.log](https://github.com/Ryujinx/Ryujinx/files/9193220/Ryujinx_1.1.187_2022-07-27_06-45-26.log)
[Ryujinx_1.1.193_2022-07-27_22-08-33.log](https://github.com/Ryujinx/Ryujinx/files/9198518/Ryujinx_1.1.193_2022-07-27_22-08-33.log)
[Ryujinx_1.1.193_2022-07-27_22-09-07.log](https://github.com/Ryujinx/Ryujinx/files/9198519/Ryujinx_1.1.193_2022-07-27_22-09-07.log)
[Ryujinx_1.1.193_2022-07-27_22-09-28.log](https://github.com/Ryujinx/Ryujinx/files/9198520/Ryujinx_1.1.193_2022-07-27_22-09-28.log)

### Environment?

- Ryujinx version: 1.1.187+</br>
- Game version: Irrelevant</br>
- System Specs:
  - OS: Windows 10
  - CPU: E5-1680 v2
  - GPU: GTX 1060
  - RAM: 32GB
- Applied Mods : None

### Additional context?

Additional info about your environment:</br>
Australian Locale with AU:English language pack
Issue replicates from clean install

DLC.json for one of several effected titles, Fire Emblem Three Houses - 010055d009f78000

> [
>   {
>     "path": "W:\\Disk Images\\Switch\\Fire Emblem Three Houses\\DLC\\Fire Emblem Three Houses [DLC Side Story Cindered Shadows][010055D009F79001][v196608].nsp",
>     "dlc_nca_list": [
>       {
>         "path": "/8110c05d7151828750b8401605345ba8.nca",
>         "title_id": 72151946046705665,
>         "enabled": true
>       }
>     ]
>   },
>   {
>     "path": "W:\\Disk Images\\Switch\\Fire Emblem Three Houses\\DLC\\Fire Emblem Three Houses [DLC Officers Academy Uniform Byleth][010055D009F79006][v262144].nsp",
>     "dlc_nca_list": [
>       {
>         "path": "/486f71d56be343fcc8be01ba0a227e44.nca",
>         "title_id": 72151946046705670,
>         "enabled": true
>       }
>     ]
>   },
>   {
>     "path": "W:\\Disk Images\\Switch\\Fire Emblem Three Houses\\DLC\\Fire Emblem Three Houses [DLC New Attire][010055D009F79002][v262144].nsp",
>     "dlc_nca_list": [
>       {
>         "path": "/4f69c0282e2b3f5edbad3095a65b1240.nca",
>         "title_id": 72151946046705666,
>         "enabled": true
>       }
>     ]
>   },
>   {
>     "path": "W:\\Disk Images\\Switch\\Fire Emblem Three Houses\\DLC\\Fire Emblem Three Houses [DLC Auxiliary Battle Maps][010055D009F79003][v196608].nsp",
>     "dlc_nca_list": [
>       {
>         "path": "/8bc72ba649bfd211eeacffd60f525340.nca",
>         "title_id": 72151946046705667,
>         "enabled": true
>       }
>     ]
>   },
>   {
>     "path": "W:\\Disk Images\\Switch\\Fire Emblem Three Houses\\DLC\\Fire Emblem Three Houses [DLC Additional Support Items][010055D009F79005][v196608].nsp",
>     "dlc_nca_list": [
>       {
>         "path": "/6407e946907815288112412ba0ff09ca.nca",
>         "title_id": 72151946046705669,
>         "enabled": true
>       }
>     ]
>   },
>   {
>     "path": "W:\\Disk Images\\Switch\\Fire Emblem Three Houses\\DLC\\Fire Emblem Three Houses [DLC Additional Quests][010055D009F79004]v196608].nsp",
>     "dlc_nca_list": [
>       {
>         "path": "/3d390aebeb0745fc73dc6dc8fb00fc0c.nca",
>         "title_id": 72151946046705668,
>         "enabled": true
>       }
>     ]
>   }
> ]

**Comment by sakuka47** [comment]
Hi, work fine with  1.1.193

**Comment by Squall-Leonhart** [comment]
no it doesn't.

**Comment by sakuka47** [comment]
> no it doesn't.

You right, only ryujinx master not avalonia

**Comment by Squall-Leonhart** [comment]
AcK77's PR is working, but a left a feedback about the checkboxes
