### ISSUE TITLE
Upscaling on some UE games isn't consistent

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#3508]
### What's the issue you encountered?

On some games upscaling is not working and sometimes works, not sure if a regression or not.
There's 2 issues related to upscaling issue with UE games, one was posted at https://github.com/Ryujinx/Ryujinx/issues/3577 and the other one is this one.

List of games that do no upscale properly:

DRAGON QUEST® XI S: Echoes of an Elusive Age

https://github.com/Ryujinx/Ryujinx/pull/2860 does not fix upscaling in the games listed.

### How can the issue be reproduced?

Just changing the resolution from native to any other.

### Environment?

- Ryujinx version: 1.1.199</br>
- Game version: v1.0.3</br>
- System Specs:
  - OS: *Windows 10)*
  - CPU: *Ryzen 3600)*
  - GPU: *NVIDIA RTX 3060 Ti*
  - RAM: *16GB*
- Applied Mods : No

### Screenshots

Build 1.1.160
![image](https://user-images.githubusercontent.com/2002038/182031450-6e3df98b-33a3-4dd8-b8c8-dde1f50f0868.png)

Every build after it 

![image](https://user-images.githubusercontent.com/2002038/182031509-13b045cb-6d0e-43ef-a553-3dadc053e6a9.png)

**Comment by GamerzHell9137** [comment]
I've retested a bit and it seems even on 160 its doing it. Sometimes on master its fine but sometimes it isn't. Either all of the UE games are using some kind of dynamic resolution which #2860 would help (?) or there's really a regression somewhere.

Master Attempt 1 
![image](https://user-images.githubusercontent.com/2002038/183487046-75e22eb1-70b7-4ac5-8be0-6ccf357d0887.png)
Master Attempt 2
![image](https://user-images.githubusercontent.com/2002038/183487080-e2aaeeb8-86b3-47d5-842c-85e4f2cecf3e.png)
160 build Attempt from above 
![image](https://user-images.githubusercontent.com/2002038/183487113-dd31a822-8260-44f2-a84b-70a81be741c3.png)
160 build Attempt 2 
![image](https://user-images.githubusercontent.com/2002038/183487080-e2aaeeb8-86b3-47d5-842c-85e4f2cecf3e.png)

If its hard for you to see the difference just check the grass in the background, but you can see it on the dirt textures and all around the cave too if you look a bit harder. Visible on the character itself tho.

Also renamed the OP, not sure how to even call it.

**Comment by GamerzHell9137** [comment]
#2860 Doesn't solve the issue.

**Comment by Djipi71** [comment]
I can add many others:
Arise - A simple story
Little Nightmare 1
Crash 4

**Comment by GamerzHell9137** [comment]
> I can add many others: Arise - A simple story Little Nightmare 1 Crash 4

I've tested Crash and its not related to this. Crash doesn't upscale at all, this is just for games on which upscale sometimes works and sometimes doesn't.
