### ISSUE TITLE
Run on linux fails

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#3509]
### What's the issue you encountered?

.Net do not find libx11 on linux

### How can the issue be reproduced?

running ryujinx

### Log file

```
     39478:	find library=libX11.so [0]; searching
     39478:	 search cache=/etc/ld.so.cache
     39478:	 search path=/lib64:/usr/lib64		(system search path)
     39478:	  trying file=/lib64/libX11.so
     39478:	  trying file=/usr/lib64/libX11.so
     39478:	
     39478:	find library=liblibX11.so [0]; searching
     39478:	 search cache=/etc/ld.so.cache
     39478:	 search path=/lib64:/usr/lib64		(system search path)
     39478:	  trying file=/lib64/liblibX11.so
     39478:	  trying file=/usr/lib64/liblibX11.so
     39478:	
     39478:	find library=libX11 [0]; searching
     39478:	 search cache=/etc/ld.so.cache
     39478:	 search path=/lib64:/usr/lib64		(system search path)
     39478:	  trying file=/lib64/libX11
     39478:	  trying file=/usr/lib64/libX11
     39478:	
     39478:	find library=liblibX11 [0]; searching
     39478:	 search cache=/etc/ld.so.cache
     39478:	 search path=/lib64:/usr/lib64		(system search path)
     39478:	  trying file=/lib64/liblibX11
     39478:	  trying file=/usr/lib64/liblibX11
     39478:	
Unhandled exception. 00:00:00.006 |W| Application GetWindowScaleFactor: Couldn't determine monitor DPI: Wayland not yet supported
System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
   at Ryujinx.Program.XInitThreads()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 104
Abortado (`core' generado)
```

### Environment?

- Ryujinx version: master</br>
- System Specs:
  - OS: Fedora 36
  - CPU: i7
  - GPU: Nvidia
  - RAM: 32GB
- Applied Mods : No
- 
### Additional context?

Can be fixed with:

    sudo ln -s /usr/lib64/libX11.so.6 /usr/lib64/libX11.so

Additional info about your environment:</br>

Probably related with linux installation, not sure if lib search can be modified from ryujinx

**Comment by Golden-Cherry** [comment]
It's a dependency issue, it also happens on apt based systems as well (Debian, Ubuntu, etc) a better solution it's to install libx11-devel, so **sudo dnf install libX11-devel**, for Ubuntu it would be **sudo apt install libx11-dev**

**Comment by albfan** [comment]
Wonder if something should be done at Ryujinx level to find this library, and run out of the box on those linux OS, devel package fixes it.

```
$  dnf repoquery -l libX11 | grep libX11
/usr/lib/libX11.so.6
/usr/lib/libX11.so.6.4.0
/usr/lib64/libX11.so.6
/usr/lib64/libX11.so.6.4.0
```

```
$  dnf repoquery -l libX11-devel | grep so$
/usr/lib/libX11-xcb.so
/usr/lib/libX11.so
/usr/lib64/libX11-xcb.so
/usr/lib64/libX11.so
```

**Comment by cat-master21** [comment]
So I figured out that by getting libx11.a from https://packages.ubuntu.com/jammy/libx11-dev and using the `sudo ln -s /usr/lib64/libX11.so.6 /usr/lib64/libX11.so` it worked and this is on Fedora despite the libx11.a being on Ubuntu also.

**Comment by cat-master21** [comment]
So I later found that running `cp /lib64/libX11.so.6.4.0 /home/pumkinking/Downloads/ryujinx-1.1.240-linux_x64/publish/libX11.so` which copies my libX11 to Ryujinx's folder, it works but once I remove it with `rm /home/pumkinking/Downloads/ryujinx-1.1.240-linux_x64/publish/libX11.so` it all the sudden stops working and of course all of this is without libX11-devel/libX11-dev installed!

**Comment by edisionnano** [comment]
Copying libraries is a bad solution

**Comment by edisionnano** [comment]
This can be closed now

**Comment by cat-master21** [comment]
Well my pr didn't get merged and I think the `ln` solution should be in the website possibly in the faq page

**Comment by albfan** [comment]
@cat-master21 fix the world is not a duty for ryujinx. If some distros only include a symbolic link in a devel package the sdl2 package should be aware of that and look for the right library name. this is a problem with sdl2 package for some linux distros
