### ISSUE TITLE
Xenoblade Chronicles 3 [010074F013262000]: Flickering/missing graphics on OpenGL/Linux/AMD

### ISSUE THREAD

**Issue by rabidcopy** [Ryujinx/Ryujinx#3510]
### What's the issue you encountered?

Experiencing extreme flickering graphics during gameplay. Some graphical effects do not render correctly. Requires AMD_DEBUG=nohyperz to render most models correctly.

### How can the issue be reproduced?

Load into the game, move around, rotate the camera, etc.

### Log file

[Ryujinx_1.1.199_2022-07-31_14-22-37.log](https://github.com/Ryujinx/Ryujinx/files/9229593/Ryujinx_1.1.199_2022-07-31_14-22-37.log)

### Environment?

- Ryujinx version: 1.1.199</br>
- Game version: 1.1.0</br>
- System Specs:
OS: EndeavourOS Linux x86_64 
Kernel: 5.18.8-262-tkg-bmq 
Resolution: 1920x1080 
DE: Xfce 4.16 
WM: Xfwm4 
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
GPU: AMD ATI Radeon RX 570
Driver: Mesa 22.1.4-1 
Memory: 2788MiB / 15950MiB 
- Applied Mods : None

### Additional context?

Applying resolution mods does not affect the issue. Running Ryujinx with AMD_DEBUG=nonggc,nooutoforder,nodpbb,nohyperz,nodcc,nofmask does not resolve the issue or exacerbate it. Issue with flickering persists when not using AMD_DEBUG=nohyperz. Title screen has minor graphical issues with the clouds. Models are missing/blacked out if I don't run Ryujinx with AMD_DEBUG=nohyperz.

### Screenshots:

![mpv-shot0001](https://user-images.githubusercontent.com/8052832/182042660-c8e9f2d9-42c3-4869-a4bd-2a1a0e9b6c78.jpg)

Title screen issue

![ryujinx_capture_2022-07-31_14-50-08](https://user-images.githubusercontent.com/8052832/182042757-4c0b776c-3da8-4570-a8e4-6f85c95f69c5.png)

Blacked out/missing models when AMD_DEBUG=nohyperz is not used

![ryujinx_capture_2022-07-31_14-55-13](https://user-images.githubusercontent.com/8052832/182042898-46583da7-9240-47aa-aa5b-4f57e385d682.png)

![ryujinx_capture_2022-07-31_14-56-24](https://user-images.githubusercontent.com/8052832/182042949-bd475da0-3979-458d-a67a-55ae8b505856.png)

### Video:

EPILEPSY WARNING

https://user-images.githubusercontent.com/8052832/182042790-e210d1e4-9081-4cce-99e5-e39971461a3d.mp4

**Comment by yuwenhua653** [comment]
This doesn't seem to affect AMD graphics cards with Vega architecture

**Comment by rabidcopy** [comment]
> This doesn't seem to affect AMD graphics cards with Vega architecture

Such is life on older architectures. I do have a 2200G laying around I could try since that uses Vega architecture for its integrated graphics. It'll probably work, but perform somewhat poorly.

**Comment by KawaiiDinosaur** [comment]
> > This doesn't seem to affect AMD graphics cards with Vega architecture
> 
> Such is life on older architectures. I do have a 2200G laying around I could try since that uses Vega architecture for its integrated graphics. It'll probably work, but perform somewhat poorly.

I don't think it's Polaris specific. I have the same visual artifacts on my RDNA card (5700 XT).

![Screenshot_20220731_233834](https://user-images.githubusercontent.com/36821201/182062329-289f1d2e-6208-4f43-89ab-e4bbbc481fa7.png)

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3960). Thank you.
