### ISSUE TITLE
Super Mario ODdysey Online Mod lagging issue

### ISSUE THREAD

**Issue by dF-Ex** [Ryujinx/Ryujinx#3511]
hello, i was trying to play super mairo oddysey online. but it keeps laggin on ryujinx, i followed the instruction on what to do but it just not working, heres the log file:///D:/downloads/publish/publish/Logs/Ryujinx_1.1.199_2022-07-31_14-15-34.log

**Comment by piplup55** [comment]
the lag has nothing to do with ryujinx, it's the mod itself all you can do is wait for updates
