### ISSUE TITLE
Xenoblade Chronicles: Definitive Edition [0100FF500E34A000]: Flickering / Missing grass on title screen

### ISSUE THREAD

**Issue by SomeoneIsWorking** [Ryujinx/Ryujinx#3518]
### What's the issue you encountered?

Flickering / Missing grass on title screen on the ground.
https://youtu.be/sWfVh_Iq4ec
This glitch was only happening in Vulkan until 22.7.1 driver.
Now it happens with both Vulkan and OpenGL

### How can the issue be reproduced?

Boot the game then wait for title screen to load.

### Log file

[Ryujinx_1.1.201_2022-08-01_17-14-37.log](https://github.com/Ryujinx/Ryujinx/files/9234647/Ryujinx_1.1.201_2022-08-01_17-14-37.log)

### Environment?

- Ryujinx version: 1.1.201</br>
- Game version: 1.1.2</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 2600
  - GPU: Radeon RX 570
  - RAM: 16GB
- Applied Mods : Speed increased (x1.5)

### Additional Context?

I previously reported this on Vulkan PR (when it was exclusive to Vulkan renderer) and decided to move it here since
- The PR has been merged
- The glitch is not exclusive to Vulkan renderer anymore

How the missing grass is supposed to look like
![image](https://user-images.githubusercontent.com/9450683/182168689-026743b4-e5be-47c7-9f99-cc5cf57adcce.png)

**Comment by Monoken** [comment]
Same problem here..

### Environment

- Ryujinx version: 1.1.206
- Game version: 1.1.2

###  System Specs:
> OS: Windows 10

> CPU: Ryzen 5 5900x
> GPU: Radeon 6900XT
> RAM: 64GB
> Applied Mods from Emusak: 

![image](https://user-images.githubusercontent.com/110509296/182736983-b3387460-645b-44f4-b499-672ab8fff2e4.png)


### **Example of grass not showing up**

![image](https://user-images.githubusercontent.com/110509296/182736589-33a9bd1e-e224-421d-b1b9-6331b7264bf8.png)

Log: [Ryujinx_1.1.206_2022-08-03_17-12-26.log](https://github.com/Ryujinx/Ryujinx/files/9255740/Ryujinx_1.1.206_2022-08-03_17-12-26.log)

**Comment by MetrosexualGarbodor** [comment]
Please do not mention piracy software here.

**Comment by Monoken** [comment]
> Please do not mention piracy software here.

uhh which one? I don't know which one.

**Comment by Monoken** [comment]
I

> Please do not mention piracy software here.

I literally spent 30 minutes writing down and editing my post for an issue and you deleted it, what the hell

**Comment by gdkchan** [comment]
You mentioned piracy software on your post in:
`Applied Mods from ***: `
Also, GitHub should have sent a copy of your post to your e-mail.

**Comment by Monoken** [comment]
> You mentioned piracy software on your post in: `Applied Mods from ***: ` Also, GitHub should have sent a copy of your post to your e-mail.

EmuSak is piracy program??? I downloaded it yesterday to put shader cache and mods on my game from youtube guide. I didn't know it was piracy program. Should've just told me and I would've removed it from my post. Thanks for letting me know

**Comment by Monoken** [comment]
All I'm gonna say is fuck you for deleting my shit, I'm not gonna repeat it again, I didn't know it was piracy program as it's not letting you to get stuff you shouldn't just mods/shaders for the game itself. Good job deleting my messages instead of focusing fixing your shitty emulator that doesn't even work properly without having to learn C# or Java. If anyone still here trying to get Xenoblade working I'd recommend trying Yuzu, at least people there won't delete your problems.

**Comment by SomeoneIsWorking** [comment]
Probably should open other issues for these but
Here is the portrait corruption that happens only in native resolution (**contains heavy spoilers**) https://imgur.com/a/tu38UUs
And bush transformation issue (**contains spoilers**) https://www.youtube.com/watch?v=plXrFNfyGZM
There is also slight corruption on time change menu clock
At 1x ![image](https://user-images.githubusercontent.com/9450683/182821217-ff3083ca-2b3c-4805-8632-436c956c3136.png)
At 2x (much less but still there)
![image](https://user-images.githubusercontent.com/9450683/182821350-76b6b440-d9a5-4a65-b400-814c186a378b.png)

**Comment by riperiperi** [comment]
What GPU and backend is this?

**Comment by SomeoneIsWorking** [comment]
Portrait and clock corruption are Vulkan exclusive
Bush transformation is both Vulkan and OpenGL

**Comment by riperiperi** [comment]
You still haven't said what GPU is causing the clock issue.

**Comment by Herpderpus666** [comment]
I have the same issue on Windows 11, using a Radeon RX6800. Game seems to run decently other than that but I haven't tried it extensively on this emulator.

**Comment by gdkchan** [comment]
Fixed by #3832.
