### ISSUE TITLE
Super Mario Odyssey graphical issues on amd/intel after 1.1.200

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#3531]
### What's the issue you encountered?

Super Mario Odyssey graphical issues on amd/intel opengl and vulkan

AMD:

Vulkan:
![image](https://user-images.githubusercontent.com/100526773/182332646-0c1a015a-395f-437a-a23f-71273cff1cb0.png)

OpenGL:
![image](https://user-images.githubusercontent.com/100526773/182332844-3b371496-9f15-43f0-a210-7c750c1a1bb1.png)

Intel:

Vulkan:
N/A didn't test but should be the same

OpenGL:
![image](https://user-images.githubusercontent.com/100526773/182333499-ea65dfb6-e9e9-4d15-8f14-d753ddf6c361.png)

### How can the issue be reproduced?

Reload the game until the issue happens

### Log file

AMD:
1.1.199: [Ryujinx_1.1.199_2022-08-02_09-16-00.log](https://github.com/Ryujinx/Ryujinx/files/9240569/Ryujinx_1.1.199_2022-08-02_09-16-00.log)

1.1.200: [Ryujinx_1.1.200_2022-08-02_09-26-57.log](https://github.com/Ryujinx/Ryujinx/files/9240575/Ryujinx_1.1.200_2022-08-02_09-26-57.log)

Intel:
1.1.200: [Ryujinx_1.1.200_2022-08-02_09-35-35.log](https://github.com/Ryujinx/Ryujinx/files/9240602/Ryujinx_1.1.200_2022-08-02_09-35-35.log) (i forgot i was using flatpak)
 
### Environment?

- Ryujinx version: 1.1.200 and above
- Game version: 1.0.0

- AMD System:
  - OS: Arch Linux
  - CPU: Ryzen 3700X
  - GPU: AMD RX 6600 XT
  - RAM: 80gb
- Applied Mods : Yes
- [Super Mario Odyssey Online](https://github.com/CraftyBoss/SuperMarioOdysseyOnline) (this mod shouldn't affect it i tested without the mod after)

- Intel System:
  - OS: Arch Linux
  - CPU: Intel i5 1135G7
  - GPU: Intel Xe Graphics
  - RAM: 40gb
- Applied Mods : No

### Additional context?

this bug was found by RMED24 more testing was done by me on amd and intel

**Comment by Socke81** [comment]
Since Windows and NVIDIA were not mentioned here. On Vulkan on my 1060 the same. Windows 10. OpenGL is Okay.

![Screenshot 2022-08-03 122003](https://user-images.githubusercontent.com/19229875/182587101-f88ec1c3-7d83-4cc0-8eac-6479657f8452.png)

**Comment by Marsseluo** [comment]
I had the same issue. Try to delete the shader cache, it solves to me

**Comment by piplup55** [comment]
> I had the same issue. Try to delete the shader cache, it solves to me

it's random sometime it's fine and sometimes it isn't shader cache has nothing to with it my intel system had no shaders

**Comment by Socke81** [comment]
Not required. There was an update again. I installed it and Mario looks good again.

**Comment by piplup55** [comment]
this is seems to not happen on opengl anymore, i tried 15 times and didn't trigger it once

**Comment by piplup55** [comment]
forgot to mention in the last comment that this still happens on vulkan, pausing and unpausing fixes this issue or reloading the stage
![image](https://user-images.githubusercontent.com/100526773/184366398-55d279b4-f7ae-4a4f-8543-1bde81d0c357.png)

**Comment by piplup55** [comment]
this doesn't seem to happen on amd anymore, intel should be the same but more testing is needed before closing the issue fully

**Comment by piplup55** [comment]
this doesn't seem to happen on intel anymore, closing this since both reported vendors are now fine
