### ISSUE TITLE
Monster hunter rise doesn't start

### ISSUE THREAD

**Issue by Rochar22** [Ryujinx/Ryujinx#3532]
### What's the issue you encountered?

just downloaded Ryuujinx and installed Monster hunter rise, after starting the game, just a black screen and after a few minutes crashes after a red message in the console

### How can the issue be reproduced?

N\A

### Log file

Ryujinx_1.1.203_2022-08-02_14-17-50.log](https://github.com/Ryujinx/Ryujinx/files/9241779/Ryujinx_1.1.203_2022-08-02_14-17-50.log)

### Environment?

- Ryujinx version: 1.1.203
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 5600
  - GPU: AMD Radeon R7 260x 2GB
  - RAM: 16GB
- Applied Mods :  No

### Additional context?

N/A

**Comment by MutantAura** [comment]
Github issues are not a support forum. Join the discord if you want to troubleshoot: https://discord.gg/ryujinx
