### ISSUE TITLE
AMD RX6700 not found.

### ISSUE THREAD

**Issue by xenesys** [Ryujinx/Ryujinx#3533]
## Game Name
All games I have.
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
1.1.203

#### Graphics Backend : *(e.g. Vulkan or OpenGL)*
vulkan and opengl

*Describe the current game state here.*
No GPU RX6700 in Ryujinx options windows with vulkan or opengl
![bug-rx6700-01](https://user-images.githubusercontent.com/10657107/182409476-72f2f80d-9461-4696-a3fd-3f5487665e4c.jpg)

GPUZ don't find vulkan. 
AMD Drivers installed : amd-software-adrenalin-edition-22.7.1-win10-win11-july26
```

#### Hardware Specs : 

##### CPU: 2700X AMD
##### GPU: Sapphire AMD RX6700
##### RAM: DDR4 2x8GO


#### Screenshots :


#### Log file :
[Ryujinx_1.1.203_2022-08-02_17-14-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9243467/Ryujinx_1.1.203_2022-08-02_17-14-45.log)

**Comment by xenesys** [comment]
Oups sorry for the tag...
I try a thing : remove AMD driver + reboot and tada...
don't know what's wrong. Bug in AMD drive ?
![Sans driver - GPUZ Vulkan](https://user-images.githubusercontent.com/10657107/182420042-4f772a2b-87d4-47ed-807b-0afb67829c2e.png)
![Sans driver ryujinx gpu ok](https://user-images.githubusercontent.com/10657107/182420054-f6f310b4-7ff4-4825-a3db-56d6116d1389.png)
.

**Comment by MutantAura** [comment]
OpenGL does not allow device selection. It just uses the default GPU, only Vulkan has the selector.
Glad you got this fixed.

**Comment by xenesys** [comment]
> OpenGL does not allow device selection. It just uses the default GPU, only Vulkan has the selector. Glad you got this fixed.

I don't knew it. Thanks a lot.

**Comment by gopat** [comment]
I know i'm late to the party, but if (for whatever reason) anyone needs a workaround for a version of Ryujinx with this issue, setting the following variable to `1` "fixed" it temporarily for me:


_Windows_
```cmd
set DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1

```

_Linux_
```shell
export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1
```
(\* Or just prepend it to the binary path in the command itself)

Example in windows, running from cmd:

![image](https://user-images.githubusercontent.com/10393246/182954972-360f41e1-0676-46eb-b014-647c2836695e.png)
![image](https://user-images.githubusercontent.com/10393246/182957276-0b6bcadb-a215-43ca-ab6e-ead9d2d97262.png)
![image](https://user-images.githubusercontent.com/10393246/182957416-94ca966d-a356-491b-8df6-91a61c1b1db0.png)


I may be wrong but It seems to avoid an issue with some AMD-based systems "switchable graphics".

System: Asus TUF Gaming A15 FA506QM

P.D.: As a note, information about v1.1.206 seems to be missing from the Changelog.
