### ISSUE TITLE
Information about Mario Kart 8 Deluxe on AMD

### ISSUE THREAD

**Issue by rgbarros120** [Ryujinx/Ryujinx#3536]
Good night gdkchan. When you are going to focus on fixing the lights bug of mario kart deluxe on vulkan AMD, it will take time to implement this feature of the fix you know. Because on August 4th, wave 2 of mario kart 8 deluxe will be released. For now I had to resort to another emulator in the case of yuzu.

**Comment by AcK77** [comment]
Duplicate of #3512 for nothing
