### ISSUE TITLE
Motion trigger switch

### ISSUE THREAD

**Issue by dharmang1910** [Ryujinx/Ryujinx#3538]
In some games if we eneble motion controls then if we turn left or right with motion then after player turns at proper angle we have to turn controller to normal zero angle but doing so also turn back player to the previous angle also. So for this condition motion trigger switch is very useful so only trigger motion when we press some key or touch the touchpad of DS4 controller etc. Some game have built in trigger keys but some have not so request this feature in input option under motion section.

**Comment by MutantAura** [comment]
Rephrase your issue or feature request into one of the templates we provide or use our discord for support questions: https://discord.gg/ryujinx
