### ISSUE TITLE
DOOM needs opcode 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#354]
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/2290175/Ryujinx.log)

Unhandled Exception: Ryujinx.HLE.OsHle.Exceptions.UndefinedInstructionException: The instruction at 0x0000000011a59208 (opcode 0x4e287821) is undefined!

**Comment by ReaperOfSouls1909** [comment]
Update Pr #365 solves opcode now a new service is needed https://gist.github.com/ReaperOfSouls1909/b5324d75d273b027aa642fddc86f272c 

Unhandled Exception: System.NotImplementedException: ssl ISslService: 0

**Comment by emmauss** [comment]
Closing this as the issue seems to be resolved. Please open a new issue for other issues
