### ISSUE TITLE
Xenoblade Chronicles 3: Models Vanishing During Combat

### ISSUE THREAD

**Issue by RandomGitUser321** [Ryujinx/Ryujinx#3543]
## Bug Report
Interlinked Ouroboros mesh turns invisible after using certain abilities. This happens on both Vulkan and OpenGL, cleared shader/PPTC caches.

### How can the issue be reproduced?
While using the interlink between Eunie and Taion, some of the abilities cause the mesh to turn invisible until you separate or cancel the interlink. I initially thought it was caused by the heat buildup effect on the mesh, where the mesh glows as your time runs out, but it turned out to not be the case. The shadows still show up during the day(my clips were at night because I forgot to change the time of day to show it).

Autoattacking stays visible:
https://i.imgur.com/uKgmG02.mp4

Typhoon Field stays visible:
https://i.imgur.com/gLEcmxz.mp4

Lighting Arrow turns invisible:
https://i.imgur.com/zA0fAql.mp4

Raptor Raid turns invisible:
https://i.imgur.com/sQRPoyB.mp4

### Environment?

- Ryujinx version: 1.1.206</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: *Windows 11 21H2*
  - CPU: *i3-10100*
  - GPU: *NVIDIA GTX 1650 516.59 drivers*
  - RAM: *16GB*
- Applied Mods : *None*

**Comment by tedios** [comment]
Can confirm this on pre and post Vulkan Builds and on 1.1.207 it still happens but a lot less often - so far happened 6-7 times in the span of 10+ hours.

**Comment by tedios** [comment]
Yes, used to happen constantly before 207 for me every single Eunie- Taion interlink, however after the update even after I control them and spam the arts faster doesn't happen every time for since 2-3 builds ago, but I can confirm it's still present as a graphical bug

**Comment by tedios** [comment]
Yes, in my experience it only happens when I cancel them too fast.

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
