### ISSUE TITLE
Mario Kart 8 Deluxe - Texture flickering in "Sky-High Sundae"

### ISSUE THREAD

**Issue by jonker130** [Ryujinx/Ryujinx#3548]
### What's the issue you encountered?

When playing the Sky-High Sundae map you can see heavy texture flickering in the sky.

### How can the issue be reproduced?

Just play the map, issue persists on both Vulkan and OpenGL / with and without ResScale

### Environment?

- Ryujinx version: Ryujinx_1.1.0+b26983b
[Ryujinx_1.1.0+b26983b_2022-08-04_21-54-15.log](https://github.com/Ryujinx/Ryujinx/files/9264852/Ryujinx_1.1.0%2Bb26983b_2022-08-04_21-54-15.log)
- Game version: 2.1.0
- System Specs:
  - OS: Win 11
  - CPU: Ryzen 5 3600
  - GPU: AMD rx5700xt
  - RAM: 16GB
- Applied Mods : No

### Additional context?

https://user-images.githubusercontent.com/88239202/182991058-b507206f-1d62-4678-b770-79f8ba31d038.mp4

(Video by RMED24)
Edit: video doesnt work, so here is a screenshot:
![image](https://user-images.githubusercontent.com/88239202/183002964-2964a5f5-307b-4f25-b105-d25aa04f4fe5.png)
How it's supposed to look: (without the lines)
![image](https://user-images.githubusercontent.com/88239202/183003063-d65fe0e5-d66e-4670-8c7d-dd5b075f49a2.png)

**Comment by gdkchan** [comment]
For future reference, you need to put an empty line separating the video URL from the text if you want it to embed.

**Comment by piplup55** [comment]
here's a video of it happening anyway https://youtu.be/5fmibQJQgrw

**Comment by ActualMandM** [comment]
Can confirm that it happens on the Steam Deck.

https://user-images.githubusercontent.com/15317421/183159098-f40fc4bd-f10a-46d0-ba5f-c973ce54eec4.mp4

[Ryujinx_1.1.208_2022-08-05_13-16-53.log](https://github.com/Ryujinx/Ryujinx/files/9271549/Ryujinx_1.1.208_2022-08-05_13-16-53.log)

**Comment by m0nk210** [comment]
I can also confirm that this is an issue on the Steam deck. Same with yuzu.

**Comment by MetrosexualGarbodor** [comment]
Closing as this was already reported in the game compatibility entry.
