### ISSUE TITLE
[Xenoblade Chronicles 3] Attempt to read or write protected memory

### ISSUE THREAD

**Issue by PhiZero** [Ryujinx/Ryujinx#3550]
### What's the issue you encountered?

Sometimes during normal play, when using the Memory Manager modes "Host unchecked" or "Host", the game crashes with the following error:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.ArmProcessContext`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```

This happens at different parts, but when you encounter it is always consistent. Or seems to be, since 3 people can reproduce it.

### How can the issue be reproduced?

Attached are a set of saves where the issue can be consistently reproduced. (tested between 3 people)
[test_saves.zip](https://github.com/Ryujinx/Ryujinx/files/9269469/test_saves.zip)

### Steps:
1. Select OpenGL backend.
2. Ensure that memory manager mode is set to "Host unchecked"
3. Load game, select Continue
4. Open the main menu and select "Heroes".

On "Host unchecked" or "Host", the game crashes at this point. On "Software" mode, there are no issues.

### Log file

(This crash doesn't show up in normal Ryujinx logs)
[crash_output.txt](https://github.com/Ryujinx/Ryujinx/files/9269543/crash_output.txt)

### Environment?

- Ryujinx version: 1.1.215</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: *Windows 11*
  - CPU: *Ryzen 5900X*
  - GPU: *3080 Ti*
  - RAM: *32GB*
- Applied Mods: None

### Additional context?

Videos displaying the differences between "Host unchecked" and "Software"

https://user-images.githubusercontent.com/7350221/183096927-3127bc01-65b9-4560-abd1-7e80d15f1bcd.mp4

https://user-images.githubusercontent.com/7350221/183096944-e51f8795-b8d3-49b4-a46b-2a7ddc20d296.mp4

**Comment by EmulationFanatic** [comment]
>  (Due to the nature of the crash, this doesn't show up on logs and is hard to catch)

FWIW, opening a command prompt and launching the emulator there via the command line will guarantee capturing the full crash output in that window every time.

Thanks for the report!

**Comment by PhiZero** [comment]
> FWIW, opening a command prompt and launching the emulator there via the command line will guarantee capturing the full crash output in that window every time.

Thanks! Updated the log.

**Comment by jmwangde3** [comment]
still happen on 1.1.213

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.ArmProcessContext`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()

**Comment by ripps818** [comment]
Still happens in 1.1.220.
Don't get me wrong, it happens much less now, but this game still crashes alot.
[Ryujinx_1.1.220_2022-08-17_17-34-04.log](https://github.com/Ryujinx/Ryujinx/files/9366689/Ryujinx_1.1.220_2022-08-17_17-34-04.log)

**Comment by Allexio** [comment]
Hey all, got a(nother?) reproducible crash with this error.
These are my save files (I'm not sure which one is the right one but follow reproduction steps and you should be fine)
[xenoblade3saves.zip](https://github.com/Ryujinx/Ryujinx/files/9389125/xenoblade3saves.zip)

Reproduction steps:

1. Launch game
2. Select Continue
3. Wait for game to load
4. Press X to access game menu
5. Select the "Affinities" sub menu
6. Crash

Interestingly, it seems this crash does **NOT** appear in generated Ryu log files (It does however of course appear in the console after Ryu has crashed)

**Comment by MetrosexualGarbodor** [comment]
Closing this as we're now only tracking game-specific issues on the compatibility list. Thanks.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3960
