### ISSUE TITLE
Weird squares appearing on Ryujinx in Super Kirby Clash [01003fb00c5a8000]

### ISSUE THREAD

**Issue by RocoGreen** [Ryujinx/Ryujinx#3554]
# Bug Report - Super Kirby Clash [01003fb00c5a8000]

## What's the issue you encountered?

I was playing Super Kirby Clash and when I started playing the Waddle Dee mission on the Ruins section, I saw these weird visual glitch squares on screen.

https://user-images.githubusercontent.com/52676010/183225610-6825225a-461a-4447-8413-51da0eda0306.mp4

## How can the issue be reproduced?

1. Go to the game
2. Press A to mission board
3. Select the ruins (third one from the top left) 
4. Select the waddle dee one
5. Launch the mission
6. You see the visual glitches on screen when playing

### Log file
[Ryujinx_1.1.208_2022-08-06_01-39-52.log](https://github.com/Ryujinx/Ryujinx/files/9274022/Ryujinx_1.1.208_2022-08-06_01-39-52.log)

### Environment?

- Ryujinx version: 1.1.208 (Vulkan)</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: *Windows 11 (Build 22000)*
  - CPU: *AMD Ryzen 7 5800h*
  - GPU: *NVIDIA GeForce RTX 3060*
  - RAM: *16GB*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
- Logs are spamming "Invalid texture format 0x7FFFF"

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
