### ISSUE TITLE
When loading Super Smash Brothers Ultimate wiith Vulkan, Ryujinx will crash

### ISSUE THREAD

**Issue by Wfree86** [Ryujinx/Ryujinx#3555]
### What's the issue you encountered?

Starting Super Smash Brothers Ultimate with Vulkan, ryujinx closes while game loads
### How can the issue be reproduced?

- Go to settings and go to Graphics tab
- Change graphics backend to Vulcan
- Make sure that you have chosen "Enable shader cache"
- Apply and Save
- Run Super Smash Brothers Ultimate
- See that the game will crash while loading the title.

### Log file
[Ryujinx_1.1.208_2022-08-05_20-44-30.log](https://github.com/Ryujinx/Ryujinx/files/9274344/Ryujinx_1.1.208_2022-08-05_20-44-30.log)
[Ryujinx_1.1.208_2022-08-05_20-45-10.log](https://github.com/Ryujinx/Ryujinx/files/9274345/Ryujinx_1.1.208_2022-08-05_20-45-10.log)
[Ryujinx_1.1.208_2022-08-05_20-56-01.log](https://github.com/Ryujinx/Ryujinx/files/9274346/Ryujinx_1.1.208_2022-08-05_20-56-01.log)

### Environment?

- Ryujinx version: 1.1.28</br>

- Game version: 13.0.1</br>

- System Specs:
  - OS: Windows 10
  - CPU: i7 4712HQ
  - GPU: GTX 850m
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Graphics Backend Multuthreading on or off doesn't change results.
Repro'd 5/5

!Vulkan

**Comment by Squall-Leonhart** [comment]
I can't reproduce this on a GTX 1060, drivers might be involved.

**Comment by Wfree86** [comment]
> I can't reproduce this on a GTX 1060, drivers might be involved.

Using the newest drivers.

**Comment by Wfree86** [comment]
Ok so I've done a completely clean install and made it portable so its pulling from new folders for all files. It no longer crashes, but it's now just a black screen with no sound.

[Ryujinx_1.1.208_2022-08-07_15-20-17.log](https://github.com/Ryujinx/Ryujinx/files/9277897/Ryujinx_1.1.208_2022-08-07_15-20-17.log)
[Ryujinx_1.1.208_2022-08-07_15-22-32.log](https://github.com/Ryujinx/Ryujinx/files/9277898/Ryujinx_1.1.208_2022-08-07_15-22-32.log)
[Ryujinx_1.1.208_2022-08-07_15-29-06.log](https://github.com/Ryujinx/Ryujinx/files/9277899/Ryujinx_1.1.208_2022-08-07_15-29-06.log)

Default settings.

**Comment by MetrosexualGarbodor** [comment]
Your game does not have a romFS according to the log, redump it properly, and next time please ask for help in Discord, not here.

**Comment by Wfree86** [comment]
@MetrosexualGarbodor that was before the rom was properly loaded and the updates and DLC were reinstalled. Please take the time to actually NMI a bug report before dismissing the issue and closing it.

Here is the new Vulkan log. 
[Ryujinx_1.1.208_2022-08-07_19-54-13.log](https://github.com/Ryujinx/Ryujinx/files/9278339/Ryujinx_1.1.208_2022-08-07_19-54-13.log)

Again, this does work with OpenGL. Here is that log:
[Ryujinx_1.1.208_2022-08-07_21-35-55.log](https://github.com/Ryujinx/Ryujinx/files/9278789/Ryujinx_1.1.208_2022-08-07_21-35-55.log)

**Comment by Squall-Leonhart** [comment]
Vulkan black screens are a common issue where the notebook has an IGP or APU on an older driver model where the DGPU driver model is 2.4 or higher, this issue particularly affects the 800M and 900M products.

There are no intel packages that bring the 4712HQ's IGP above WDDM 2.1, thus the Nvidia driver must be downgraded to that, or the IGP be disabled in the BIOS (often not possible)

The issue has also been noted on Kepler mobile parts when using RTSS 7.2.1 (though nobody should be on a version that old)

Verify that vulkan actually works in GPU Cap Viewers vulkan demos.

**Comment by Wfree86** [comment]
@Squall-Leonhart thank you for this info! I'm not sure which Vulkan test you wanted me to do so I did all of them. I didn't experience any issues with either the Vulkan or Vulkan 2 tests,

**Comment by Squall-Leonhart** [comment]
ok, that just leaves a possible compatibility issue with the GM10x architecture or a driver issue with that chip.

**Comment by Wfree86** [comment]
So basically it's possibly just a sit and wait to see if I get a driver update for my 9 year old igpu or the design of ryujinx changes to allow my set up to work.

**Comment by jduncanator** [comment]
> So basically it's possibly just a sit and wait to see if I get a driver update for my 9 year old igpu or the design of ryujinx changes to allow my set up to work. 

Where possible, it's always the intention of the developers to ensure as maximal compatibility as possible, however it's not always possible to support hardware that predates the Nintendo Switch itself. A pseudo-target is Maxwell-era graphics cards, so a GTX700 or later series card could be considered minimum System requirements.

**Comment by Wfree86** [comment]
Oh well. I'll go back to the other emulator for near perfect Vulkan and hope for updated mod features and dream what could be with ryujinx. 

Continue the good work.

**Comment by Squall-Leonhart** [comment]
> Where possible, it's always the intention of the developers to ensure as maximal compatibility as possible, however it's not always possible to support hardware that predates the Nintendo Switch itself. A pseudo-target is Maxwell-era graphics cards, so a GTX700 or later series card could be considered minimum System requirements.

only the 750 is Maxwell, which is on the same architecture as ops 850m.

**Comment by gdkchan** [comment]
I think this might be caused by the `shaderOutputViewportIndex` capability that this GPU does not support. SSBU uses this, but we don't have it implemented on OpenGL, only Vulkan. We can ignore it on the shader if the feature is not supported to make it work with older GPUs. Anyway, this is just a guess, it's hard to say for sure without having the GPU to test, it would be helpful to know if other games are working on Vulkan.

**Comment by Wfree86** [comment]
@gdkchan if there are particular games you wish me to test let me know. Happy to help.

**Comment by gdkchan** [comment]
Have you tested anything other than SSBU? Most games do not modify ViewportIndex. For example, Super Mario Odyssey or Mario Kart 8 Deluxe would do.

**Comment by Wfree86** [comment]
@gdkchan I have not. I can test both of these and bring back my results today. Does it matter if mk8 has dlc or not?

**Comment by gdkchan** [comment]
> Does it matter if mk8 has dlc or not?

No.

**Comment by Wfree86** [comment]
Ok I think should have both Odyssey and MK8. Played through the prologue of Odyssey and did neo bowser city on 150cc in MK8


[Ryujinx_1.1.215_2022-08-14_15-46-00.log](https://github.com/Ryujinx/Ryujinx/files/9334321/Ryujinx_1.1.215_2022-08-14_15-46-00.log)
[Ryujinx_1.1.215_2022-08-14_16-34-43.log](https://github.com/Ryujinx/Ryujinx/files/9334322/Ryujinx_1.1.215_2022-08-14_16-34-43.log)
[Ryujinx_1.1.215_2022-08-14_16-36-26.log](https://github.com/Ryujinx/Ryujinx/files/9334323/Ryujinx_1.1.215_2022-08-14_16-36-26.log)

**Comment by gdkchan** [comment]
Can you try SSBU on Vulkan with the build at https://github.com/Ryujinx/Ryujinx/pull/3644 and see if it works? Thanks.

**Comment by shovonz** [comment]
Same issue for the Mac. Please provide/release new Mac version with fix

**Comment by TheFunIsInfinite** [comment]
having the same issue tho even if i use opengl it still wont work
