### ISSUE TITLE
Stuck on loading, no games launch

### ISSUE THREAD

**Issue by devlman127** [Ryujinx/Ryujinx#3557]
## Bug Report

Sorry if I have a similar issue to others, It's hard to look through all the issues.

### What's the issue you encountered?

I freshly installed Ryujinx onto my system along with a few homebrew games. when I try to start them, however, none of my games are able to be launched.  For Bernardo's 2048, it even crashes Ryujinx.

### How can the issue be reproduced?

Fresh install.

### Log file

00:00:00.062 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.067 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.067 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.068 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.069 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.070 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.071 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.073 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.081 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.081 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.081 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.081 |I| Configuration LogValueChange: EnablePtc set to: False
00:00:00.081 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.081 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.081 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.082 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.082 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.083 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.083 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.083 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.087 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.208
00:00:00.093 |N| Application Print: Operating System: Microsoft Windows 10.0.17134 (X64)
00:00:00.093 |N| Application Print: CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz ; 6 logical
00:00:00.094 |N| Application Print: RAM: Total 16328 MB ; Available 11057 MB
00:00:00.096 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.097 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.096 |I| Gpu : Backend Threading (Auto): True
00:00:00.574 |N| Application LoadApplication: Using Firmware Version: 14.1.2
00:00:00.574 |I| Application LoadApplication: Loading as Homebrew.
00:00:00.900 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.940 |I| ModLoader LoadCheats: Build ids found for title 0000000000000000:
    48A659340FE4E56FAC02F7FCD2651BEE215C5F88000000000000000000000000
00:00:00.954 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.099 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.149 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (4.6.0 NVIDIA 465.89)
00:00:02.937 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.945 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.949 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.950 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.955 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:02.955 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:03.072 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:03.789 |E| HLE.OsThread.13 SurfaceFlinger DestroyStrayLayer: Failed to destroy stray layer 1 (permission denied)
00:00:03.812 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: True ; unknownFlag3: False}
00:00:03.812 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:03.818 |S| HLE.OsThread.16 ServiceAm Exit: Stubbed. 
00:00:00.004 |I| Gpu : Backend Threading (Auto): True
00:00:00.313 |N| Application LoadApplication: Using Firmware Version: 14.1.2
00:00:00.313 |I| Application LoadApplication: Loading as Homebrew.
00:00:00.387 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.388 |I| ModLoader LoadCheats: Build ids found for title 0000000000000000:
    0000000000000000000000000000000000000000000000000000000000000000
00:00:00.390 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:00.443 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:00.493 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (4.6.0 NVIDIA 465.89)
00:00:01.991 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.996 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.996 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.998 |W| HLE.GuestThread.15 KernelSvc : GetInfo(value: 0x0000000000000000) = InvalidHandle
00:00:01.998 |W| HLE.GuestThread.15 KernelSvc : GetInfo(value: 0x0000000000000000) = InvalidHandle
00:00:01.998 |W| HLE.GuestThread.15 KernelSvc : GetInfo(value: 0x0000000000000000) = InvalidEnumValue
00:00:01.998 |W| HLE.GuestThread.15 KernelSvc : GetInfo(value: 0x0000000000000000) = InvalidHandle
00:00:01.998 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.000 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:02.000 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:02.107 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fatal.IService: 1

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  01 00 00 00 00 00 00 00   SFCI············
00000010   59 25 00 00 00 00 00 00  02 00 00 00 00 00 00 00   Y%··············
00000020   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 219
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261

### Environment?

- Ryujinx version: 1.1.208</br>

- System Specs:
  - OS: Windows 10 Home
  - CPU: Intel(R) Core(TM) i5-9400F CPU 
  - GPU: NVIDIA GeForce GTX 1050 Ti
  - RAM: 16 GB
- Applied Mods : N/A

### Additional context?

Additional info about your environment:</br>
I'm pretty new to this so I don't know what else to do, feel free to ask for more info.

**Comment by MetrosexualGarbodor** [comment]
Please head to [discord](https://discord.gg/ryujinx) for help, GitHub is for global emulator issues.
