### ISSUE TITLE
[ Xenoblade Chronicles 3 ] Char movements and audio broken

### ISSUE THREAD

**Issue by Jeffslash666** [Ryujinx/Ryujinx#3559]
### What's the issue you encountered?

As the title mention the movements of the main caracter are weird and audio is broken (missing), tried change audio backend and nothing changes.
### How can the issue be reproduced?

It happens instantly when i go in game.
### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version:  1.1.208

- System Specs:
  - OS: Windows 10
  - CPU: i5 9600kf (stock)
  - GPU: Nvidia 1060 6gb
  - RAM: 16GB ddr4
- Applied Mods : No

### Additional context?

Sent you a video and the logs.

https://user-images.githubusercontent.com/83434355/183288077-14a91aa5-f273-47cb-bd71-eeaa52f2e398.mp4
[Ryujinx_1.1.208_2022-08-07_07-55-34.log](https://github.com/Ryujinx/Ryujinx/files/9276655/Ryujinx_1.1.208_2022-08-07_07-55-34.log)

**Comment by GamerzHell9137** [comment]
I see nothing wrong with the character movement. Also looks like your F2 button is stuck and its muting and unmuting the emulator, the volume icon is flashing.

**Comment by MutantAura** [comment]
For support please use our discord and not the issue tracker: https://discord.gg/ryujinx
