### ISSUE TITLE
Xbox One elite 2 controller crashes using rumble option

### ISSUE THREAD

**Issue by MNS26** [Ryujinx/Ryujinx#3560]
### What's the issue you encountered?

Xbox One Elite 2 controller crashing when rumble is enabled
</br>

### How can the issue be reproduced?
enabling rumble in settings and then playing a game that uses it (for me `Inner Space`)

moment after rumble activates the controller becomes unresponsive
</br>

### Log file
N/A
</br>

### Environment?

- Ryujinx version: 1.0.0 (git)</br>

- Game version: Inner Space 1.0.2</br>

- System Specs:
  - OS: Arch Linux
  - CPU: I7-8750H (laptop)
  - GPU: NVIDIA RTX2070 Mobile
  - RAM: 16GB
- Applied Mods : No
</br>

### Additional context?

Additional info about your environment: N/A</br>

extra info regarding the issue: 
Ive had this same thing happen with steam games but on proton, after some digging it ended up being that the FF command doesnt have a send cap (speed) and crashes the bluetooth stack of the controller.
A workaround for those games were to limit the speed to 100hz

**Comment by Squall-Leonhart** [comment]
Update the firmware of the controller, this was fixed long ago.

**Comment by MNS26** [comment]
> Update the firmware of the controller, this was fixed long ago.

did that about half a year ago and that didnt help

**Comment by Squall-Leonhart** [comment]
Ah, you must have the OG Elite 2,

Latest fixes the LE (refresh) version, for the OG, you have to go up to latest and then downgrade to 4.8 with a console, or secret windows command.

1: Install Xbox Accessories from the microsoft store.
2: Connect the controller via usb USB.
3: Enter the line "xboxaccessories:\\firmwareupdate?legacyDowngrade=true" into an Explorer path, Browser, or Run.

**Comment by MNS26** [comment]
@Squall-Leonhart im on linux so i cant use the XB app
i got this controller 7 or so months ago, idk if there is a way to check what version of the elite 2 it is

**Comment by Squall-Leonhart** [comment]
The cited cases in the xpadneo repo are not applicable here as that is a HID driver, SDL upstream is responsible for the controllers raw data functions and configuration.

This image indicates some revision history of the Elite2, with the newer one using the Bluetooth LE Xinput compatible input device driver.

![image](https://user-images.githubusercontent.com/1098176/184031461-f0389b1d-2cdc-4950-ba48-8077d57310e0.png)

**Comment by MNS26** [comment]
i do not understand what you mean by this 

> The cited cases in the xpadneo repo are not applicable here as that is a HID driver, SDL upstream is responsible for the controllers raw data functions and configuration.
>
> This image indicates some revision history of the Elite2, with the newer one using the Bluetooth LE Xinput compatible input device driver.

(english isnt my native language)

**Comment by AcK77** [comment]
This doesn't seems to be an issue related to Ryujinx then. I close it, if it's really specific to the projet, we could reopen it.
