### ISSUE TITLE
Posters having a visual glitches in Splatoon 2 : Octo Expansion

### ISSUE THREAD

**Issue by RocoGreen** [Ryujinx/Ryujinx#3562]
# Bug Report - Splatoon 2 (Octo Expansion DLC)

## What's the issue you encountered?

In Splatoon 2 : Octo Expansion DLC, every poster is having visual glitch when you're being far from them. And It applies to every stage that contain a poster. It's doing this on OpenGL and Vulkan.

https://user-images.githubusercontent.com/52676010/183303489-fbda8da0-d360-4e80-8a9f-dea0ae4a6d29.mp4

Especially here :
![image](https://user-images.githubusercontent.com/52676010/183303527-6ba9b619-f61e-47a2-9a8d-38f726cc670e.png)

## How can the issue be reproduced?

To be honest, just play the Octo Expansion especially at the start and you'll see the glitches when being far from the posters.

## Log file

[Ryujinx_1.1.208_2022-08-07_19-13-10.log](https://github.com/Ryujinx/Ryujinx/files/9277214/Ryujinx_1.1.208_2022-08-07_19-13-10.log)

## Environment

- Ryujinx version: 1.1.208</br>
- Game version: 5.5.0</br>
- System Specs:
  - OS: *Windows 11 (Build 22000)*
  - CPU: *AMD Ryzen 7 5800H*
  - GPU: *NVIDIA GeForce RTX 3060 Laptop GPU*
  - RAM: *16GB*

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
