### ISSUE TITLE
Maps in missions on Splatoon 2 : Octo Expansion DLC become greenish, yellowish or even blueish randomly

### ISSUE THREAD

**Issue by RocoGreen** [Ryujinx/Ryujinx#3563]
# Bug Report - Splatoon 2 : Octo Expansion DLC

## What's the issue you encountered?

Sometime when doing a mission, the map get all greenish, yellowish or blueish. I don't know if they can get to another color tho. It's doing this randomly on every mission I think. Sometime it does it, sometime not. 

* ### First one 
On :
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 21 06 40 34](https://user-images.githubusercontent.com/52676010/183307211-a09d2ddb-d7d8-4517-bbc5-dd48ee90988a.png)

When having the bug :
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 20 13 30 89](https://user-images.githubusercontent.com/52676010/183307164-8e4fc50d-3a7f-4689-800e-c499b040df76.png) 
and
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 20 13 10 95](https://user-images.githubusercontent.com/52676010/183307174-69de7f93-970f-414e-99cb-f8c929d7db6a.png)

* ### Second one
On : 
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 21 07 51 90](https://user-images.githubusercontent.com/52676010/183307274-6d20ef46-b4dc-420e-8000-561b26533f76.png)

When having the bug : 
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 20 28 42 56](https://user-images.githubusercontent.com/52676010/183307291-b3216d97-fb7b-4ebf-8a48-6800e7f21383.png)

* ### Third one
On : 
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 21 09 20 48](https://user-images.githubusercontent.com/52676010/183307311-455b8312-fa67-4f55-a152-3e920cada892.png)

When having the bug :
![Ryujinx Nvidia Profile Screenshot 2022 08 07 - 20 57 20 63](https://user-images.githubusercontent.com/52676010/183307319-7920f785-5896-4897-a259-37f8e4caf05f.png)

## How can the issue be reproduced?

Just try to play any mission or any mission I reported until you get the bug. I was on Vulkan

### Log file

[Ryujinx_1.1.208_2022-08-07_19-13-10.log](https://github.com/Ryujinx/Ryujinx/files/9277336/Ryujinx_1.1.208_2022-08-07_19-13-10.log)

### Environment

- Ryujinx version: 1.1.208</br>
- Game version: 5.5.0</br>
- System Specs:
  - OS: *Windows 11 (Build 22000)*
  - CPU: *AMD Ryzen 7 5800H*
  - GPU: *NVIDIA GeForce RTX 3060 Laptop GPU*
  - RAM: *16GB*

### Additional context?

Additional info about your environment:</br>
- I was on the Octo Expansion DLC
- Playing with Vulkan

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
