### ISSUE TITLE
Vulkan + Mii editor = Crash

### ISSUE THREAD

**Issue by mm12** [Ryujinx/Ryujinx#3566]
### What's the issue you encountered?
When Settings/Graphics/Backend is set to "Vulkan" rather than "OpenGL", the "Mii Editor" applet crashes when launched. 

### Log file

[Ryujinx_1.1.208_2022-08-09_21-04-47.log](https://github.com/Ryujinx/Ryujinx/files/9295924/Ryujinx_1.1.208_2022-08-09_21-04-47.log)
### Environment?

- Ryujinx version: 1.1.208</br>
- Game Version: N/A
- System Specs:
  - OS: *SteamOS 3.3*
  - CPU: *8x AMD Valve APU 0405*
  - GPU: *AMD Valve APU 0405*
  - RAM: *14 GiB*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Steam Deck

**Comment by AcK77** [comment]
I think it's *probably* related to AMD, I don't have any issue here. Your log file doesn't contain any error message.

![image](https://user-images.githubusercontent.com/4905390/184162177-17d7aa5f-45ee-41c1-b3ac-30948eaa9733.png)

**Comment by piplup55** [comment]
> I think it's _probably_ related to AMD, I don't have any issue here. Your log file doesn't contain any error message.
> 
> ![image](https://user-images.githubusercontent.com/4905390/184162177-17d7aa5f-45ee-41c1-b3ac-30948eaa9733.png)

i think it might be i just tried on my 6600XT and it crashes with *** stack smashing detected *** but adding `COMPlus_EnableAlternateStackCheck=1` shows no error [Ryujinx_1.1.209_2022-08-11_15-53-22.log](https://github.com/Ryujinx/Ryujinx/files/9309677/Ryujinx_1.1.209_2022-08-11_15-53-22.log)

**Comment by CloneDeath** [comment]
I can not reproduce, but there's a chance #3597 will fix this issue...
@mm12 Can you checkout that branch, and see if it's still happening?

If it is, could you please set "Graphics Backend Log Level" to "Error" in the options, and post an updated log.

![image](https://user-images.githubusercontent.com/2948533/184789534-d1893ac1-e813-434d-90b5-6908031fdf15.png)

**Comment by CloneDeath** [comment]
I just reproduced the issue on my deck. I switched to my branch, and now it works.

Confirmed that #3597 fixes this issue.
