### ISSUE TITLE
Crash when switching to Vulkan in options

### ISSUE THREAD

**Issue by leopold-p** [Ryujinx/Ryujinx#3567]
Ryujinx Version: 1.1.209
GPU: NVIDIA GeForce RTX 3070

When selecting Vulkan as graphics backend option Ryujinx immediately crashes, before i get to apply or save changes.
The error isn't captured in logs file so i attach a screenshot of the log window.
![image](https://user-images.githubusercontent.com/44367440/183881956-236ef7a4-3cf4-473b-b8da-6518ed24cff7.png)

**Comment by Squall-Leonhart** [comment]
Do you have any exotic hid devices installed, such as RGB controllers?

**Comment by leopold-p** [comment]
I don't think so, just a couple of gamepads connected via bluetooth.

**Comment by GamerzHell9137** [comment]
Think this is a user error. Join the Discord for support. https://discord.gg/VkQYXAZ

**Comment by MutantAura** [comment]
See above.

**Comment by MetrosexualGarbodor** [comment]
Last time this was caused by Gshade doing something weird with Vulkan, for anyone who comes here in the future.
