### ISSUE TITLE
Xenoblade Chronicles: Definitive Edition [0100FF500E34A000]:black model

### ISSUE THREAD

**Issue by jmwangde3** [Ryujinx/Ryujinx#3578]
Bug Report

Xenoblade Chronicles: Definitive Edition [0100FF500E34A000]:black model

What's the issue you encountered?

Xenoblade Chronicles: Definitive Edition vulkan mode if I set the  resolution in lib_nx.ini large than 1(even just 1.1) then all model become black,
opengl dose not.
![ryujinx_capture_2022-08-12_21-08-37](https://user-images.githubusercontent.com/99083755/184361702-0561b232-94dc-4fd4-b6c9-52bc268a40ea.png)

How can the issue be reproduced?

here is the default lix_nx.ini,i only change  resolution to 1.1
[lib_nx.ini.log](https://github.com/Ryujinx/Ryujinx/files/9316548/lib_nx.ini.log)

log

[Ryujinx_1.1.213_2022-08-12_21-11-28.log](https://github.com/Ryujinx/Ryujinx/files/9316530/Ryujinx_1.1.213_2022-08-12_21-11-28.log)

Environment?

    Ryujinx version: 1.1.213
    Game version: Xenoblade Chronicles: Definitive Edition [0100FF500E34A000]
    System Specs:
        OS: Windows 10
        CPU: 5800x
        GPU: 1060 6gb
        RAM: 32gb
    Applied Mods : no

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
