### ISSUE TITLE
Unimplemented Trap instruction

### ISSUE THREAD

**Issue by yeboi51** [Ryujinx/Ryujinx#3580]
### What CPU instruction is missing?

Requires the *trap* instruction.</br>

```
Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000c30ed14 (opcode 0xe7ffdefe) is undefined!
```

### Instruction name
```
trap 
```

### Required by: 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/749

**Comment by EmulationFanatic** [comment]
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1340
