### ISSUE TITLE
Unable to load shared library 'libX11'

### ISSUE THREAD

**Issue by cat-master21** [Ryujinx/Ryujinx#3582]
### What's the issue you encountered?

I was unable to start Ryujinx. Despite Ryujinx warning me I have `libX11.so.6` at `/lib64/libX11.so.6` which is in my ld path.

### How can the issue be reproduced?

1. Download [ryujinx-1.1.213-linux_x64.tar.gz](https://github.com/Ryujinx/release-channel-master/releases/download/1.1.213/ryujinx-1.1.213-linux_x64.tar.gz)
2. Make sure to extract this file.
3. run  it through your prefered terminal with something like `./publish/Ryujinx`.
4. Observe the error

### Log file
No log by Ryujinx was created so tty ouput when running:
```
[pumkinking@fedora publish]$ /home/pumkinking/Downloads/ryujinx-1.1.213-linux_x64/publish/Ryujinx
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
   at Ryujinx.Program.XInitThreads()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 104
Aborted (core dumped)
[pumkinking@fedora publish]$ export GDK_BACKEND=x11
[pumkinking@fedora publish]$ /home/pumkinking/Downloads/ryujinx-1.1.213-linux_x64/publish/Ryujinx
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
   at Ryujinx.Program.XInitThreads()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 104
Aborted (core dumped)
[pumkinking@fedora publish]$
```

### Environment?

- Ryujinx version: 1.1.213
- Game version: X.X.X (Was unable to launch fully)
- System Specs:
  - OS: Fedora 36 / GNU Linux
  - CPU: AMD 5700g
  - GPU: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c8)
  - RAM: 16GB
- Applied Mods : No

### Additional context?

I have libx11 fully installed as mentioned before.
If there is a dependency issue maybe ryujinx could be packaged as an appimage or a installer?

**Comment by edisionnano** [comment]
sudo dnf install libX11-devel

**Comment by cat-master21** [comment]
yeah installing `libX11-devel` did the trick. I think Ryujinx could be packaged as an appimage to fix this so I don't have to install it but I'd say this can be closed.
