### ISSUE TITLE
Playing RPG-m MV/trinity on Vulkan heavily visual glitches

### ISSUE THREAD

**Issue by kevincrans** [Ryujinx/Ryujinx#3584]
## Bug Report
sorry I posted too early.
RPG-m MV/trinity Vulkan visual glitches

### What's the issue you encountered?

RPG-m MV gives all tiny coloured squares, a diagonal stripe and sometimes 2 equally sized big squares in left bottom.

### How can the issue be reproduced?

play RPG-MV (nsp) with Nvidia Vulkan, newest firmware/Ryujinx

### Log file

[Ryujinx_1.1.213_2022-08-13_11-26-28.log](https://github.com/Ryujinx/Ryujinx/files/9332982/Ryujinx_1.1.213_2022-08-13_11-26-28.log)

### Environment?

- Ryujinx version: before 1.1.213</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 11
  - CPU: i7-7700K)
  - GPU: NVIDIA GTX 1070
  - RAM: 32GB
- Applied Mods : No (Vulkan)

### Additional context?

Additional info about your environment:</br>
![screen shot](https://user-images.githubusercontent.com/22748357/184529725-52e92294-7642-4684-836e-fc8b8ca1ed83.png)

Sorry for Excel in the bottom.
The video was 4.5GB, so I here's a screenshot where there are appearently 3-4 squares
![image](https://user-images.githubusercontent.com/22748357/184530298-7fad300f-f159-4324-b449-f0d065e5a0c2.png)
I still have to make a screenshot for the in-game editor and event/database editor

**Comment by kevincrans** [comment]
However the game is as far as I know fully functional

**Comment by kevincrans** [comment]
Oh suddenly it's working, I don't know how, I think it updated

**Comment by GamerzHell9137** [comment]
Try enabling texture recompression in settings.

**Comment by kevincrans** [comment]
No, it's still working, don't know what broke it first time

**Comment by Squall-Leonhart** [comment]
This is a known vulkan driver issue when OoM is encountered on Nvidia drivers, once you are around 1.2GB overcommitted (system shared video memory is > 1.2GB) and affects the next vulkan application start.

**Comment by Squall-Leonhart** [comment]
PSA: Under Windows 10 there is a problem that may be nvidia driver caused where after a display driver update (or using Restart64 for CRU), cycling a TV or monitor on/off may cause significant memory leakage of Explorer.exe in  both GPU memory and Working set, and result in the above issue.

using the Avalonia GUI may result in this
![image](https://user-images.githubusercontent.com/1098176/185371889-b47e53ed-6a54-42d1-b5fb-88c8a2d28206.png)

**Comment by MutantAura** [comment]
Closing as appeared to be random and resolved? Game-specific should also be reported to the compatibility page in future.
