### ISSUE TITLE
Xenoblade Chronicles 3 – Unimplented texture formats

### ISSUE THREAD

**Issue by ExE-Boss** [Ryujinx/Ryujinx#3586]
### What's the issue you encountered?

**Xenoblade Chronicles 3** sometimes spams “Invalid texture format” with many different IDs in the logs.

### How can the issue be reproduced?

This issue happens only when the game decides to load a texture in an unsupported format.

One location this occurred at was during **Chapter 4** while halfway‑ish through **Maktha Wildwood**.

### Log file

All the unique texture format IDs I’ve encountered so far since I started playing **Xenoblade Chronicles 3** at the start of the month:
- [Xenoblade 3 – Invalid texture formats.txt](https://github.com/Ryujinx/Ryujinx/files/9333912/Xenoblade.3.Invalid.texture.formats.txt)

### Environment?

- Ryujinx version: 1.1.201 … 1.1.214
- Game version: 1.1.0
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 7 3700X 8-Core Processor
  - GPU: NVIDIA GeForce RTX 2070
  - RAM: 32 GB
- Applied Mods : No

### Additional context?

N/A

## See also:
- <https://github.com/Ryujinx/Ryujinx-Games-List/issues/3960>
- <https://github.com/Ryujinx/Ryujinx/issues/3231>
- <https://github.com/Ryujinx/Ryujinx/pull/3570>
- <https://github.com/Ryujinx/Ryujinx/pull/3631>

**Comment by MetrosexualGarbodor** [comment]
I haven't noticed this issue for a while now. If you have any current logs of it, please [post them in the compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3960), as we're now only tracking game-specific issues on the compatibility list. Thanks.
