### ISSUE TITLE
Constantly re-update to latest version when launching Pokemon Sword online

### ISSUE THREAD

**Issue by MAchtman94** [Ryujinx/Ryujinx#3589]
## Bug Report

N/A

### What's the issue you encountered?

When I update Ryujinx to the latest version and run Pokemon Sword version 1.3.2, I get an error saying that I need to update the software. I have re-updated to Ryujinx to firmware 14.1.2, it works for a second, then the error pops up again. This is a continuous issue. 

### How can the issue be reproduced?

Run the Y-Comm on pokemon sword version 1.3.2

### Log file

Attached as separate file.

### Environment?

- Ryujinx version: 14.1.2</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.3.2</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS:Windows 10
  - CPU: i7-9700
  - GPU: NVIDIA 2070 Super 
  -  64GB
- Applied Mods : Yes, texture mods

### Additional context?

N/A
[Ryujinx_1.0.0-ldn2.4_2022-08-14_20-41-00.log](https://github.com/Ryujinx/Ryujinx/files/9334469/Ryujinx_1.0.0-ldn2.4_2022-08-14_20-41-00.log)
![Capture](https://user-images.githubusercontent.com/44070077/184561561-a7d9e4e0-6625-4364-9185-1a24891ad26d.PNG)

**Comment by MutantAura** [comment]
This error usually just means you do not match the software version of other users. It has nothing to do with firmware version.
Please use discord for further support queries: https://discord.gg/ryujinx
