### ISSUE TITLE
Mario Kart 8 Booster Course Pass can not load properly

### ISSUE THREAD

**Issue by iknightpl** [Ryujinx/Ryujinx#3591]
## Bug Report

I have download Mk8 dlc wave 2 (1 new dlc and 1 new ticket file)
I have update ryujinx to latest(14/8/2022) 
load dlc successful, and load new ticket file successful.
but when I start the game, the version show 2.1.0 but with no star.
In the game, select single, try to choose new course, can not use it. notice me to buy the game pass.

I have try to use yuzu
load the same dlc and ticket, the version show 2.1.0 with star.
then I can play the new course.

**Comment by Squall-Leonhart** [comment]
That whole thing you deleted to replace with what you did write?

Put it back and use it.

**Comment by AcK77** [comment]
You can go on our discord for support. Issues aren’t here for that. Thanks.
