### ISSUE TITLE
Regression: Fate/EXTELLA missing graphics since 1.1.139

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#3592]
### What's the issue you encountered?

[Fate/EXTELLA](https://github.com/Ryujinx/Ryujinx-Games-List/issues/882) no longer renders most graphics. Only the UI and menu items are showing now.
![image](https://user-images.githubusercontent.com/62343878/184726388-d0c1e5c7-daaa-472c-99da-62da25dec7bb.png)

### How can the issue be reproduced?

Launch Fate/EXTELLA on any version of the emulator from 1.1.139 or newer.

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.1.139 --> current build
- Game version: 1.0.0
- System Specs:
  - OS: Windows 11
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA RTX 3080 Ti
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:
Graphics were last working on this game in build 1.1.138

**Comment by ExE-Boss** [comment]
This will be fixed by <https://github.com/Ryujinx/Ryujinx/pull/3596>
