### ISSUE TITLE
Secret VR mode

### ISSUE THREAD

**Issue by Jorerim** [Ryujinx/Ryujinx#360]
Hello everyone, I know it may not be top priority right now, but maybe would be nice to have it implemented. The dolphin emulator has stereoscopic support.
The native VR mode for switch
https://www.fudzilla.com/news/gaming/46977-switch-has-a-secret-vr-mode

**Comment by Dudejoe870** [comment]
There isn't really any point in opening a Issue for this, as none of these are probably documented well enough at all (and probably not for a very long time) to be able to be implemented in any sort of capacity.

**Comment by DrHacknik** [comment]
Another issue that is open for no reason. These really do need to be closed.

**Comment by simonmkwii-dev** [comment]
I love how you're using a "hype" news article as your source...

**Comment by Dudejoe870** [comment]
Yeah, no need for this issue, unless you have, real, actual documentation on how these work, other than that, there'd be no need to implement these.

**Comment by DrHacknik** [comment]
What would even be the objective of opening a Issue with the concept of VR in Ryujinx? That's the most useless feature I could ever see here.

**Comment by AcK77** [comment]
Since it’s not really an issue and a feature who can’t achieved, I guess I can close this one!
