### ISSUE TITLE
Ryujinx Crashing after update

### ISSUE THREAD

**Issue by RinMaru** [Ryujinx/Ryujinx#3611]
I have windows Terminal set as default and Ryu seems to crash upon restarting after an update. Ryu updates successfully but once it restarts windows says its crashed and needs to close.

Windows 11
RX 6700XT
R5 5600

cant seem to locate log

**Comment by MetrosexualGarbodor** [comment]
Please head to [Discord](https://discord.gg/ryujinx) for help. This is not a valid issue.
