### ISSUE TITLE
Crash starting Ryujinx ldn 2.5 on Fedora 36

### ISSUE THREAD

**Issue by raaffaaeell** [Ryujinx/Ryujinx#3612]
### What's the issue you encountered?

Crash starting Ryujinx ldn 2.5 on Fedora 36

### How can the issue be reproduced?
Download the linux build from the LDN guide, start `Ryujinx`

### Log file
[Ryujinx_1.1.0-ldn2.5_2022-08-20_23-38-19.log](https://github.com/Ryujinx/Ryujinx/files/9388375/Ryujinx_1.1.0-ldn2.5_2022-08-20_23-38-19.log)

### Environment?

- Ryujinx version: 1.1.0-ldn2.5

- System Specs:
  - OS: Fedora 36
  - CPU: AMD Ryzen 7 5700X
  - GPU: RX 6600XT
  - RAM: 32GB
- Applied Mods : No

**Comment by MutantAura** [comment]
For support queries join the Discord: https://discord.gg/ryujinx
