### ISSUE TITLE
Splatoon 2 Turf Points are Amplified

### ISSUE THREAD

**Issue by thomadash** [Ryujinx/Ryujinx#3615]
### What's the issue you encountered?

I was using the latest multiplayer build of Ryujinx to play Splatoon 2 with friends. It worked normally at first, but at some point I encountered a glitch that was only on my side. When I splatted the ground, the amount of turf points I got for it was several times larger than what it should usually get, leading to special weapons charging up almost instantly and end result percentages being inaccurate.

### How can the issue be reproduced?

N/A (this happened randomly during gameplay, I'm not sure how to replicate it or fix it)

### Log file

[Ryujinx_1.1.0-ldn2.5_2022-08-21_17-28-35.log](https://github.com/Ryujinx/Ryujinx/files/9389991/Ryujinx_1.1.0-ldn2.5_2022-08-21_17-28-35.log)

### Environment?

- Ryujinx version: 1.1.0-ldn2.5</br>
- Game version: 5.5.0</br>
- System Specs:
  - OS: Windows 10 Pro
  - CPU: Intel Core i5 10600k
  - GPU: AMD Radeon RX 6800
  - RAM: 32GB
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
