### ISSUE TITLE
cant install ryujinx latest build

### ISSUE THREAD

**Issue by stan1234** [Ryujinx/Ryujinx#3619]
When i try to extract the publish folder from the zip file this error comes up

! G:\All stuff\Emulators\Switch\ryujinx-1.1.227-win_x64.zip: Cannot create G:\All stuff\Emulators\Switch\publish\bin\libdatrie-1.dll
  The request failed due to a fatal device hardware error.

**Comment by MutantAura** [comment]
For support queries join the Discord: https://discord.gg/ryujinx
