### ISSUE TITLE
burnout paradise remastered green logo screen

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3623]
### What's the issue you encountered?

the two logo screens when the game starts are green
![Screenshot_2022-08-25_08-20-12](https://user-images.githubusercontent.com/80461138/186614118-2c65d9bc-1ab2-4b2a-9e63-41435fd16c3a.png)

### Log file
[Ryujinx_1.1.228_2022-08-25_08-19-37.log.zip](https://github.com/Ryujinx/Ryujinx/files/9422903/Ryujinx_1.1.228_2022-08-25_08-19-37.log.zip)

### Environment?

- Ryujinx version: 11.228
- Game version: 1.0.0
- System Specs:
  - OS: archlinux (mesa git)
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16gb 
- Applied Mods : no

**Comment by EmulationFanatic** [comment]
Install ffmpeg. If ffmpeg is installed, please either file a single issue regarding the various graphical problems that are occurring on Intel mesa git, or add this information to the game issue on the game compatibility list.
