### ISSUE TITLE
pokken start screen glitched

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3624]
### What's the issue you encountered?

start screen in both opengl and vulkan is glitched

some examples with ogl

![Screenshot_2022-08-25_08-49-51](https://user-images.githubusercontent.com/80461138/186620174-00bdad1c-ebe8-4243-9334-0fd4edbbebc3.png)
![Screenshot_2022-08-25_08-50-07](https://user-images.githubusercontent.com/80461138/186620182-aa7fe452-1d49-4085-ae05-8ad16aa5c7d1.png)

### Environment?

- Ryujinx version: 1.1.228
- Game version: 1.3.3
- System Specs:
  - OS: archlinux (mesa git)
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16gb
- Applied Mods : no

**Comment by A-w-x** [comment]
[Ryujinx_1.1.228_2022-08-25_08-43-21.log](https://github.com/Ryujinx/Ryujinx/files/9423117/Ryujinx_1.1.228_2022-08-25_08-43-21.log)

**Comment by yuwenhua653** [comment]
It seems that playing videos are all broken on the latest mega.git 
this also affects amd

**Comment by A-w-x** [comment]
its the same with mesa stable, and i did not notice issues with other apps
ffmpeg issues in ryu?

**Comment by EmulationFanatic** [comment]
Install ffmpeg. If ffmpeg is installed, please either file a single issue regarding the various graphical problems that are occurring on Intel mesa git, or add this information to the game issue on the game compatibility list.
