### ISSUE TITLE
pokemon sp/dp vertex explosions and glitches

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3625]
### What's the issue you encountered?

https://user-images.githubusercontent.com/80461138/186630704-dad9c13c-5560-422d-bfb7-17222d4521e0.mp4

![Screenshot_2022-08-25_09-26-16](https://user-images.githubusercontent.com/80461138/186631451-3eb0e60d-2222-4aca-9dc1-cd447368d404.png)

### How can the issue be reproduced?

not easy probably, but what i did: start a new game and proceed till explosions appear (should happen before you get the first pokemon)

about the glitched start screen, run the game, play a bit, stop and rerun, screen should be glitched

### Log file
[Ryujinx_1.1.228_2022-08-25_09-25-17.log.zip](https://github.com/Ryujinx/Ryujinx/files/9423501/Ryujinx_1.1.228_2022-08-25_09-25-17.log.zip)

### Environment?

- Ryujinx version: 1.1.228
- Game version: 1.3.0
- System Specs:
  - OS: arch (mesa git)
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16gb
- Applied Mods : no

**Comment by EmulationFanatic** [comment]
Please either file a single issue regarding the various graphical problems that are occurring on Intel mesa git, or add this information to the game issue on the game compatibility list.
