### ISSUE TITLE
mario kart 8 broken previews

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3626]
### What's the issue you encountered?

![Screenshot_2022-08-25_10-07-36](https://user-images.githubusercontent.com/80461138/186637719-c096ecaa-2d05-4e61-bc7b-fdf1deeb763f.png)

both ogl and vulkan

### Log file

[Ryujinx_1.1.228_2022-08-25_10-06-57.log.zip](https://github.com/Ryujinx/Ryujinx/files/9423701/Ryujinx_1.1.228_2022-08-25_10-06-57.log.zip)

### Environment?

- Ryujinx version: 1.1.228
- Game version: 2.1.0
- System Specs:
  - OS: arch (mesa git)
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16
- Applied Mods : no

**Comment by EmulationFanatic** [comment]
Install ffmpeg. If ffmpeg is installed, please either file a single issue regarding the various graphical problems that are occurring on Intel mesa git, or add this information to the game issue on the game compatibility list.
