### ISSUE TITLE
pokemon legend arceus invisible trees

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3627]
### What's the issue you encountered?

![Screenshot_2022-08-25_10-26-22](https://user-images.githubusercontent.com/80461138/186641968-0b7d9c41-e110-4601-8abe-c683bf157fdd.png)

![Screenshot_2022-08-25_10-26-41](https://user-images.githubusercontent.com/80461138/186641978-0655365c-af35-436a-b35c-8f2fd3a14ddd.png)

both ogl and vulkan, this is a regression probably after dithering support pr

### Log file

[Ryujinx_1.1.229_2022-08-25_10-26-56.log](https://github.com/Ryujinx/Ryujinx/files/9423837/Ryujinx_1.1.229_2022-08-25_10-26-56.log)

### Environment?

- Ryujinx version: 1.1.229
- Game version: 1.1.1
- System Specs:
  - OS: arch (mesa git)
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16gb
- Applied Mods : no

**Comment by Squall-Leonhart** [comment]
MESA Xe has known issues, DXVK affected too.

**Comment by EmulationFanatic** [comment]
Please either file a single issue regarding the various graphical problems that are occurring on Intel mesa git, or add this information to the game issue on the game compatibility list.
