### ISSUE TITLE
shader cache freezes ryujinx when switching gfx backend

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3628]
### What's the issue you encountered?

ryujinx will freeze sometime when booting a game with a cache if you switch between ogl and vulkan
the only fix is to delete the shader cache

### How can the issue be reproduced?

set vulkan or ogl, play a bit, stop and set the other backend, play a bit and so on till you can no longer boot the game

### Log file

empty

### Environment?

- Ryujinx version: 1.1.230
- System Specs:
  - OS: arch (mesa git)
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16b
- Applied Mods : no

**Comment by Ackliez** [comment]
I am a bit confused cause stutter when using a backend without cache happens and is generally normal or is the issue you can't boot anymore once shader cache has been built?

**Comment by A-w-x** [comment]
the emulator softlocks when loading the cache when you boot the game if you switch beetween ogl and vulkan a few times and you play for a bit whit both backends
