### ISSUE TITLE
eBASEBALL Powerful Professional Baseball 2022 Customization Bug

### ISSUE THREAD

**Issue by Threule** [Ryujinx/Ryujinx#3637]
### What's the issue you encountered?

When trying to customize the uniforms, the game glitches visually:

![pp2022 bug](https://user-images.githubusercontent.com/5224648/187024026-ad5b940c-568a-4452-8b3c-03f789e137d4.png)

### How can the issue be reproduced?

![pp2022 bug steps](https://user-images.githubusercontent.com/5224648/187024023-13163d3a-f773-4f69-a175-0dd7f5bbd815.png)

### Log file

[Ryujinx_1.1.241_2022-08-27_11-26-22.log](https://github.com/Ryujinx/Ryujinx/files/9437642/Ryujinx_1.1.241_2022-08-27_11-26-22.log)

### Environment?

- Ryujinx version: 1.1.241</br>
- Game version: 1.5.0</br>
- System Specs:
  - OS: W10
  - CPU: i7-7700K
  - GPU: NVIDIA GeForce GTX1080
  - RAM: 16GB
- Applied Mods : No

![settings 1](https://user-images.githubusercontent.com/5224648/187024162-b73ec0b6-7de0-4783-abb5-5bf55a0dcc31.png)
![settings 2](https://user-images.githubusercontent.com/5224648/187024163-6900389d-f0d8-46ae-aecb-f99614aa3dae.png)

### Additional context?

Additional info about your environment:</br>
Playing with Vulkan is a must, otherwise it leads to Issue #3325

**Comment by Threule** [comment]
After playing a bit more, this issue happens with player uniforms names and numbers on the same team.
For example, I had a NPC player that is not called YABE had the YABE name in the uniform, because YABE batted before him.

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions,. Game compatibility information/per-game bugs belong on the game compatibility list.
