### ISSUE TITLE
New Super Mario Bros. U Deluxe: green artifacts by a green pipe on map

### ISSUE THREAD

**Issue by k0lourful** [Ryujinx/Ryujinx#3639]
### What's the issue you encountered?

These green artifacts appear on the map under and by the pipe in Acorn Plains, the first chapter in the game. Occurs on both OpenGL and Vulkan.</br>
Here's how it looks like with x2 scale in docked mode:
![ryujinx_capture_2022-08-28_13-00-24](https://user-images.githubusercontent.com/41012295/187068604-7508b741-8ae4-40ff-ad93-496af2aef5d4.png)
Handheld mode, visibly reduced glitches:
![ryujinx_capture_2022-08-28_13-01-08](https://user-images.githubusercontent.com/41012295/187068610-d119e8c6-88d4-48f6-ab51-5f4674c54e1b.png)
And native resolution, looks to be completely gone:
![ryujinx_capture_2022-08-28_13-01-28](https://user-images.githubusercontent.com/41012295/187068614-3ccb85bb-979f-464d-b431-cadbad680098.png)

### How can the issue be reproduced?

1. Enable resolution scale, x2 is enough
2. Start the game and go to the pipe in Acorn Plains

### Log file

[Ryujinx_1.1.242_2022-08-28_12-26-58.log](https://github.com/Ryujinx/Ryujinx/files/9439440/Ryujinx_1.1.242_2022-08-28_12-26-58.log)

### Environment?

- Ryujinx version: 1.1.242</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10 Pro 21H2 (Build 19044.1889)
  - CPU: Ryzen 5 5600X
  - GPU: NVIDIA GTX 1070 Ti
  - RAM: DDR4 32GB 3200MHz
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game issues, particularly ones that only occur while performing resolution scaling, belong on the game compatibility list.
