### ISSUE TITLE
eBASEBALL Powerful Professional Baseball 2022 with "light" issues

### ISSUE THREAD

**Issue by scju** [Ryujinx/Ryujinx#3640]
## Bug Report

Vulkan fixed the problem in [this post](https://github.com/Ryujinx/Ryujinx/issues/3325#issue-1228643228). That was a huge improvement. But some baseball fields now still seem too "dark". Here is an example:

https://youtu.be/LGHl1tbQsFk

PS - The light should be as bright as it is at 0:46-0:49.

### Log file
Log:
[Ryujinx_1.1.242_2022-08-28_16-20-59.log](https://github.com/Ryujinx/Ryujinx/files/9439361/Ryujinx_1.1.242_2022-08-28_16-20-59.log)

### Environment?

Ryujinx version: 1.1.242
Game version: 1.1.5
System Specs:
OS: Windows 10
CPU: i9-9900k
GPU: NVIDIA RTX 3060ti
RAM: 32GB
Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions,. Game compatibility information/per-game bugs belong on the game compatibility list.
