### ISSUE TITLE
FFMPEG 5.1+ breaks video rendering (green screen)

### ISSUE THREAD

**Issue by yuwenhua653** [Ryujinx/Ryujinx#3645]
## Bug Report
FFMPEG 5.1+ breaks video rendering (green screen) 

### What's the issue you encountered?

After updating FFMPEG5.1, ryujinx can't render video images, only audio. Video works fine after going back to 5.01

### How can the issue be reproduced?

Open the game and run to the video

### screenshot
![ryujinx_capture_2022-08-29_15-20-34](https://user-images.githubusercontent.com/30205483/187333488-4bffeac0-252c-4f32-b939-a8c0086fa6ff.png)
![ryujinx_capture_2022-08-30_10-19-24](https://user-images.githubusercontent.com/30205483/187334025-400b6724-6a6d-4fc1-bebf-6155ccdab576.png)

### Log file
The log does not output an exception
### Environment?

- Ryujinx version: 1.0.243
- Game version: 1.0.0
- System Specs:
  - OS: *arch linux*
  - CPU: *AMD R7 5700U*
  - GPU: *AMD AMD RENOIR (LLVM 14.0.6, DRM 3.47, 5.19.4-zen1-1-zen) (4.6 (Compatibility Profile) Mesa 22.1.7)
  - RAM: *16GB*
- Applied Mods : [ No ]

**Comment by MutantAura** [comment]
This is an ffmpeg bug when using ffmpeg 5.1 or above, not a mesa bug.

**Comment by piplup55** [comment]
if you downgrade to 5.0.1 everything will work fine, avoid 5.1 for the time being
