### ISSUE TITLE
Pikmin 3 broken graphical effects

### ISSUE THREAD

**Issue by LukeGreatwow** [Ryujinx/Ryujinx#3649]
Don't know if this has been reported ever/recently, but all light effects (pikmin whistle, ambient light from ship, etc) don't display in ryujinx, but have in yuzu for years. First picture is hardware, second is ryujinx current version.
![firefox_AxbX47Qfxz](https://user-images.githubusercontent.com/102778122/187576562-177656e4-d835-4094-9af1-ffc7f7cdbe78.jpg)
![Ryujinx_wSvRE7rucp](https://user-images.githubusercontent.com/102778122/187576566-5ffd3847-7e25-46ad-80dd-c74f20065a8f.jpg)

**Comment by EmulationFanatic** [comment]
Please resubmit this issue with the proper format, including all pertinent system information listed in the template, and a save file so we can attempt to reproduce.
