### ISSUE TITLE
Pikmin 3 Deluxe Missing Graphical Effects

### ISSUE THREAD

**Issue by LukeGreatwow** [Ryujinx/Ryujinx#3651]
## Bug Report

Missing graphical effects in Pikmin 3 Deluxe

### What's the issue you encountered?

Several lighting effects, such as whistle radius, ship pod ambient light, and idle pikmin glow do not appear.

Picture of the bug in Ryujinx
![Ryujinx_qP7nh8LWM0](https://user-images.githubusercontent.com/102778122/187591281-0ff613bc-4a71-4605-8211-2a9fb0b8560c.png)

here is how these effects appear on console
![firefox_zXtsTjN7QM](https://user-images.githubusercontent.com/102778122/187593411-41385d74-318e-4c30-b1d9-26af4ba4c3cb.png)
![firefox_w3dOUSQmK5](https://user-images.githubusercontent.com/102778122/187593415-6de8e3d8-b4d9-4fd0-8746-a7d3c8cd7e19.png)

### How can the issue be reproduced?

Enter any level. Can be most quickly observed by going to mission mode and picking any mission.

### Log file

[Ryujinx_1.1.243_2022-08-31_00-00-13.log](https://github.com/Ryujinx/Ryujinx/files/9458301/Ryujinx_1.1.243_2022-08-31_00-00-13.log)

### Environment?

- Ryujinx version: 1.1.243</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 5600X 6-Core
  - GPU: Nvidia RTX 3080
  - RAM: 2x16GB, 3600MHz
- Applied Mods : N/A

### Additional context?

Additional info about your environment: This is unlikely an issue with my PC, as I've had the same issue on 3 different builds, including AMD and Nvidia gpus. Yuzu emulates these effects properly, and has for a while. This issue also happens on both Vulkan and OpenGL.

**Comment by gdkchan** [comment]
Reference pictures should come from hardware, not other emulators.

**Comment by LukeGreatwow** [comment]
here is how these effects appear on console
![firefox_zXtsTjN7QM](https://user-images.githubusercontent.com/102778122/187593411-41385d74-318e-4c30-b1d9-26af4ba4c3cb.png)
![firefox_w3dOUSQmK5](https://user-images.githubusercontent.com/102778122/187593415-6de8e3d8-b4d9-4fd0-8746-a7d3c8cd7e19.png)

**Comment by MutantAura** [comment]
These issues should be filed alongside a full game compatibility report in the compatibility repo. https://github.com/Ryujinx/Ryujinx-Games-List/issues/2822
