### ISSUE TITLE
Pikmin 3 Deluxe Random Crashes

### ISSUE THREAD

**Issue by IrealiTY** [Ryujinx/Ryujinx#3655]
### What's the issue you encountered?

Ryujinx crashes periodically, in a non-reproducible way, when playing Pikmin 3 Deluxe. With a `InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.` 

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[Ryujinx_1.1.244_2022-08-31_23-02-42.log](https://github.com/Ryujinx/Ryujinx/files/9465324/Ryujinx_1.1.244_2022-08-31_23-02-42.log)

### Environment?

- Ryujinx version: 1.1.243</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: *Windows 11s*
  - CPU: *Ryzen 7 5800x*
  - GPU: *NVIDIA RTX 3080*
  - RAM: *16GB*
- Applied Mods : No (Internal Resolution was changed to 3x, does that count?)

### Additional context?

N/A

**Comment by MutantAura** [comment]
Game specific bugs should be reported on the games respective compatibility page if not already mentioned: https://github.com/Ryujinx/Ryujinx-Games-List/issues/2822
