### ISSUE TITLE
Zelda BOTW hangs after 1.1.248 update

### ISSUE THREAD

**Issue by Labaman** [Ryujinx/Ryujinx#3667]
### What's the issue you encountered?

Zelda BOTW hangs after 1.1.248 update</br>

### How can the issue be reproduced?
Just play the game for a while. Try loading a couple of saves. 

### Log file

[Logs_BOTW.zip](https://github.com/Ryujinx/Ryujinx/files/9481247/Logs_BOTW.zip)

### Environment?

- Ryujinx version: 1.1.248</br>
- Game version: 1.6.0</br>
- System Specs:
  - OS: Arch Linux
  - CPU: i7-10750H
  - GPU: NVIDIA RTX 2070 Super
  - RAM: 32 Gb
- Applied Mods : NO

**Comment by MutantAura** [comment]
Breath of the Wild currently exhibits random gpu memory crashes as experienced here. This has always been the case and is not caused by any recent change. For further support queries please use the discord: https://discord.gg/ryujinx
Thanks!
