### ISSUE TITLE
[Feature Request] Allow the Main Window to remember its sizing and position upon closing

### ISSUE THREAD

**Issue by Daisouji** [Ryujinx/Ryujinx#3671]
The title. I think it is a good feature to keep consistent w/ other platform programs.

**Comment by theboy181** [comment]
BUMP!

**Comment by HaizenTrist** [comment]
Hi, I'm new to open-source contribution but I think I can handle this. Can I take the issue?

**Comment by HaizenTrist** [comment]
Made a pull request, though not sure if I did it correctly as this is my first issue.

**Comment by Daisouji** [comment]
addressed in #4657

**Comment by MutantAura** [comment]
We'll close this after it's been merged :)

**Comment by MutantAura** [comment]
Closed by https://github.com/Ryujinx/Ryujinx/pull/4657
