### ISSUE TITLE
Ryujinx closing immediately

### ISSUE THREAD

**Issue by UntitledOutput** [Ryujinx/Ryujinx#3673]
### What's the issue you encountered?

I was playing on Splatoon 2 with LDN, and I kept getting connection errors, so I tried to restart Ryujinx.

No, I didn't make any file changes to Ryujinx.

### How can the issue be reproduced?

N/A

### Log file

[Ryujinx_1.1.0-ldn2.5_2022-09-05_07-47-59.log](https://github.com/Ryujinx/Ryujinx/files/9489475/Ryujinx_1.1.0-ldn2.5_2022-09-05_07-47-59.log)

### Environment?

- Ryujinx version: 1.1.0-ldn2.5X</br>
- Game version: 5.5.0</br>
- System Specs:
  - OS: Windows 11 (X64)
  - CPU: i7-11800H
  - GPU: NVIDIA GeForce RTX 3050
  - RAM: 16GB
- Applied Mods : Yes (Patches)

### Additional context?

This has never happened before.

**Comment by MetrosexualGarbodor** [comment]
This is not a help page, [please join Discord for support](https://discord.gg/ryujinx).
