### ISSUE TITLE
[Feature Request] Use VkDriverID instead of vendor name in the status bar for Vulkan.

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#3682]
#### Overview:

Changing the usual "GPU: 'Vendor Name'" section of the bottom status bar with "GPU: 'Driver name'". In practise this solely affects AMD, Intel and exotic renderers on Linux when using Vulkan.

#### Smaller Details: 

Specification: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceDriverProperties.html
Silk.NET: https://github.com/dotnet/Silk.NET/blob/main/src/Vulkan/Silk.NET.Vulkan/Structs/PhysicalDeviceDriverProperties.gen.cs

#### Nature of Request:  

- Change

### Why would this feature be useful?

The Vulkan API provides a lot of detail on what sort of device is being used for rendering. While It is certainly useful to see what vendor Ryujinx is using it is even more helpful to see what driver is being used. On Windows most users would notice no difference at all as most are using NVIDIA, AMD or Intels own proprietary drivers but on Linux there are a number of driver ID's that Vulkan can distinguish between. 

Vulkan currently has the following discrete driver identifications:
```
VK_DRIVER_ID_AMD_PROPRIETARY
VK_DRIVER_ID_AMD_OPEN_SOURCE
VK_DRIVER_ID_MESA_RADV
VK_DRIVER_ID_NVIDIA_PROPRIETARY
VK_DRIVER_ID_INTEL_PROPRIETARY_WINDOWS
VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA
VK_DRIVER_ID_IMAGINATION_PROPRIETARY
VK_DRIVER_ID_QUALCOMM_PROPRIETARYVK_DRIVER_ID_ARM_PROPRIETARY
VK_DRIVER_ID_GOOGLE_SWIFTSHADER
VK_DRIVER_ID_GGP_PROPRIETARY
VK_DRIVER_ID_BROADCOM_PROPRIETARY
VK_DRIVER_ID_MESA_LLVMPIPE
 VK_DRIVER_ID_MOLTENVK
VK_DRIVER_ID_COREAVI_PROPRIETARY
VK_DRIVER_ID_JUICE_PROPRIETARY
VK_DRIVER_ID_VERISILICON_PROPRIETARY
VK_DRIVER_ID_MESA_TURNIP
VK_DRIVER_ID_MESA_V3DV
VK_DRIVER_ID_MESA_PANVK
VK_DRIVER_ID_SAMSUNG_PROPRIETARY
VK_DRIVER_ID_MESA_VENUS
VK_DRIVER_ID_MESA_DOZEN
```

**Comment by gdkchan** [comment]
Are you suggesting that we use the raw value? Right now we try to get a friendly name from the driver ID as you can see here: https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Graphics.Vulkan/Vendor.cs#L32

**Comment by MutantAura** [comment]
No, I'm suggesting more fine detail in the reporting. Taking AMD on Linux as an example no matter what driver is used (RADV, AMDVLK etc.) the name is just "AMD" where it would likely be much more useful to actually read something like "AMD (RADV)". Vulkan makes the distinction between driver types with driverID. Currently we use vendorID afaik not driverID.

**Comment by gdkchan** [comment]
Ah right, my mistake then.

**Comment by MetrosexualGarbodor** [comment]
Added on #6146
