### ISSUE TITLE
Unimplemented SEV instruction

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#3686]
### What CPU instruction is missing?

```
The instruction at 0x00000000003357f4 (opcode 0xe320f004) is undefined!
```

### Instruction name
```
0x0000000000000000:  04 F0 20 E3    sev 
```

### Required by: 
Hanayaka Nari Waga Ichizoku Modern Nostalgie [01008DE00C022000] [32-bit] (no game issue exists)
Original issue here: https://github.com/Ryujinx/Ryujinx/issues/2717

**Comment by LukeWarnut** [comment]
Ryujinx/Ryujinx-Games-List#2809 also seems to use it according to GamerzHell9137.
