### ISSUE TITLE
RTSS not working with vulkan mode

### ISSUE THREAD

**Issue by ghost** [Ryujinx/Ryujinx#3699]
## Feature Request

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ If you do not have the information needed for a section, replace its contents with "Unknown". ]</br>
[ Lines between [ ] (square brackets) are to be removed before posting. ]</br>

[ Please search for existing [feature requests](https://github.com/Ryujinx/Ryujinx/issues) before you make your own request. ]</br>
[ Duplicate requests will be marked as such and you will be referred to the original request. ]

#### Overview:
- [ Include the basic, high-level concepts for this feature here. ]

#### Smaller Details: 
- [ These may include specific methods of implementation etc. ]

#### Nature of Request:  
[ Remove all that do not apply to your request. ]
- Addition
  - [ Ex: Addition of certain original features or features from other community projects. ]
  - [ If you are suggesting porting features or including features from other projects, include what license they are distributed under and what, if any libraries those project use. ]
- Change
- Removal
  - [Ex: Removal of certain features or implementation due to a specific issue/bug or because of low quality code, etc.]

### Why would this feature be useful?
[ If this is a feature for an end-user, how does it benefit the end-user? ]</br>
[ If this feature is for developers, what does it add to Ryujinx that did not already exist? ]

**Comment by riperiperi** [comment]
Is there any particular reason that there is no other information and the issue title is in all-caps?

**Comment by ShadowLady** [comment]
About this one.... I've noticed if you open Ryujinx on OpenGL mode then switch in the options to Vulkan and save/apply without restarting, then RTSS will work on Vulkan mode (says so in the overlay too) but RTSS won't work after you restart Ryujinx.

**Comment by GamerzHell9137** [comment]
> Is there any particular reason that there is no other information and the issue title is in all-caps?

Other than the terrible report from OP, can confirm what the other person says.

Launch game with OpenGL, stop emulation, swap to Vulkan and launch the game and RTSS will work.

![image](https://user-images.githubusercontent.com/2002038/190172201-4bd7a0af-0f12-42cd-8c17-51acfb06758e.png)

**Comment by Squall-Leonhart** [comment]
install the latest RTSS beta released today, this is already resolved by updating the json files used.

**Comment by Squall-Leonhart** [comment]
this of course only applies to the original GUI, Avalonia has other issues where RTSS is concerned that are yet to be addressed, ie #3674

**Comment by Squall-Leonhart** [comment]
This can be closed, RTSS 7.3.4B5 has no issues with either gui now.

**Comment by gdkchan** [comment]
Closing as the issue has been fixed by #3674.

**Comment by sausje** [comment]
Somehow I can't get it to work on vulkan? Even after updating RTSS to beta 7 now.. v1.1.409 win11 22h2-22621.819 nvidia v527.37 on an 2700x with rtx2080

**Comment by Bjorn29512** [comment]
> 

for RTSS to work open and close the settings menu before launching the game

**Comment by sausje** [comment]
> for RTSS to work open and close the settings menu before launching the game

Thanks but what a hassle... Will this ever be fixed you think? Seeing it's been around for quite some time already.

**Comment by ShadowLady** [comment]
Think you're supposed to just use the Avalonia releases for it, should work fine there. The test-ava ones from release channel.

That would be the proper fix eventually?

**Comment by Squall-Leonhart** [comment]
Neither UI frameworks need anything other than having started RTSS first here.

**Comment by sausje** [comment]
> Neither UI frameworks need anything other than having started RTSS first here.

Yet mine does first need settings opened up before it shows. Afterburner and RTSS are opened from win boot.

**Comment by Squall-Leonhart** [comment]
then you aren't on latest RTSS.

**Comment by sausje** [comment]
> then you aren't on latest RTSS.

I am, as I said a few posts above. Beta 7 of a week ago. https://forums.guru3d.com/threads/msi-ab-rtss-development-news-thread.412822/page-189#post-6075536

I know reading is hard.
