### ISSUE TITLE
Lots of graphical bugs in Pokemon Legends Arceus when using intel gpus

### ISSUE THREAD

**Issue by 1235612356** [Ryujinx/Ryujinx#3704]
### What's the issue you encountered?

There're lots of graphical glitchs in game. </br>
No.</br>

### How can the issue be reproduced?

Open the game normally.

### Log file

Vulkan
[Ryujinx_1.1.264_2022-09-14_20-33-47.log](https://github.com/Ryujinx/Ryujinx/files/9566395/Ryujinx_1.1.264_2022-09-14_20-33-47.log)

https://user-images.githubusercontent.com/109408687/190164666-a8ed48d1-ba10-45d7-87e4-827988921e42.mp4

OpenGL
[Ryujinx_1.1.264_2022-09-14_21-19-28.log](https://github.com/Ryujinx/Ryujinx/files/9566709/Ryujinx_1.1.264_2022-09-14_21-19-28.log)

https://user-images.githubusercontent.com/109408687/190166926-f7ee992f-a216-4921-943a-1027e7e490e7.mp4

### Environment?

- Ryujinx version: 1.1.264</br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 11 Build 22622.598
  - CPU: i5-1155G7
  - GPU: 80eu iris xe
  - RAM: 16GB
- Applied Mods : No.

### Additional context?

Additional info about your environment:</br>
The bugs only affect the intel official windows driver.
Ryujinx works well when using Linux+mesa driver.

**Comment by GamerzHell9137** [comment]
If its not a regression i shouldn't be posted on the Ryujinx github.
Report the issues on the compatibility list.
