### ISSUE TITLE
Map zh_CN and zh_TW to zh-Hans/zh-Hant

### ISSUE THREAD

**Issue by Narugakuruga** [Ryujinx/Ryujinx#3713]
Only "Simplified Chinese" or "Traditional Chinese" will work. Chinese and Taiwanese is just placeholders. Using them will cause crashes or game languages not working
See https://github.com/yuzu-emu/yuzu/issues/6721

Another better way is to just hide Chinese and Taiwanese. Which greatly reduce the confusion of Chinese users

![屏幕截图(5443)](https://user-images.githubusercontent.com/31060534/190946053-6591eb2a-1f8b-4010-997c-ace289f482ed.png)

**Comment by emmauss** [comment]
> 

Post issues you experience with this emulator, and not another. If there is an issue launching game with the indicated languages, post logs and explain what you did and which games, and if the behavior also occurs on real hardware.

**Comment by yuwenhua653** [comment]
This problem does not exist in ryu
