### ISSUE TITLE
Sand graphical glitches in Skyward Sword

### ISSUE THREAD

**Issue by ivooc** [Ryujinx/Ryujinx#3717]
### What's the issue you encountered?

Graphical glitches in Lanayru Mining Facility sand on The Legend of Zelda: Skyward Sword HD. This is the only sand in the game that show these glitches that I encountered of, there was plenty of sand in the game before that did not have this issue. Maybe it's related with the relief of this area (the sand is uneven, not leveled in this part).
![image](https://user-images.githubusercontent.com/44483972/191167246-edd3cf7c-d60e-41c5-8bc0-ceaa5520123a.png)

### How can the issue be reproduced?

Run Skyward Sword HD and reach Lanayru Mining Facility. Go to the room in the provided screenshot, the sand should be glitchy.

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.277</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Microsoft Windows 10.0.19044 (X64)
  - CPU: AMD Ryzen 5 5600G
  - GPU: NVIDIA RTX 2060
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Using Vulkan backend, 2x resolution, docked mode, anisotropic filtering 16x, vsync on. Tried changing to OpenGL, native resolution, handheld mode, anisotropic filtering auto, vsync off.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Comment by cesarpeninck** [comment]
I had the same issue but solved it here by just switching from Vulkan to OpenGL. 
Spcs:
ryzen 5 1600af
gtx 980ti
2x8gb 3000mhz
ryujinx 1.1.468

**Comment by ivooc** [comment]
> I had the same issue but solved it here by just switching from Vulkan to OpenGL. Spcs: ryzen 5 1600af gtx 980ti 2x8gb 3000mhz ryujinx 1.1.468

Hmmm curious. Back then I tried that, it did not work.
