### ISSUE TITLE
Animal Crossing work with LAN mode (with console)

### ISSUE THREAD

**Issue by aldeandersantos** [Ryujinx/Ryujinx#3729]
Hello, I've been playing with the Ryujinx emulator for a few months, it's actually great, but I'd like to play with a person who has the game on the console. I searched around here and saw that animal crossing isn't included in the LAN mode list, even so I tried to connect the games and I was not successful. I want to know if there is any way to make this happen or unfortunately I will have to wait for future updates.

**Comment by EmulationFanatic** [comment]
Animal Crossing doesn't have LAN mode because the game developer did not include. There's nothing that can be done at this time. 
Eventually, if ldn_mitm gets implemented, it will be possible to connect via LDN to hacked Switch consoles. Until then, you're unfortunately out of luck.
