### ISSUE TITLE
IndexOutOfRangeException from Vulkan in Fire Emblem Warriors Three Hopes

### ISSUE THREAD

**Issue by WilliamWsyHK** [Ryujinx/Ryujinx#3734]
### What's the issue you have encountered?

Game ID: 010071F0143EA000
Game Title: Fire Emblem Warriors: Three Hopes
The game just crash after the video of Prologue of Blue House is played / skipped, with IndexOutOfRangeException from Vulkan.

### How can the issue be reproduced?

Normal playthrough the story using with Blue Fraction, and playthrough to Prologue.

### Environment?

- Ryujinx version: 1.1.283
- Game version: 1.0.1
- System Specs:
  - OS: Windows 11
  - CPU: Intel i5-12600K
  - GPU: Nvidia RTX 2070 Super
  - RAM: 32 GB
- Applied Mods: _N/A_

[Ryujinx_1.1.283_2022-10-02_08-05-47.log](https://github.com/Ryujinx/Ryujinx/files/9691434/Ryujinx_1.1.283_2022-10-02_08-05-47.log)

**Comment by gdkchan** [comment]
Can you provide a save and more clear instructions of how to reproduce it? Or can one expect to start a new game and reproduce on the first 5 minutes or so of gameplay?

**Comment by WilliamWsyHK** [comment]
It is easy to reproduce by playthrough, but I can share the save.
I have copied it as Slot 5 in the game.
[SlotData6.zip](https://github.com/Ryujinx/Ryujinx/files/9691472/SlotData6.zip)
