### ISSUE TITLE
Xenoblade Chronicles 3 - Light dots effect disappears

### ISSUE THREAD

**Issue by xtitan0123** [Ryujinx/Ryujinx#3740]
Xenoblade Chronicles 3 - Light dots effect disappears

I don't know if anyone noticed that the light dots symbolizing the dead human soul disappeared from the animation.

This problem has not been fixed from the previous version until now, which greatly affects the experience of the game plot.
I really hope it can be fixed as soon as possible.

![Ryujinx1](https://github.com/xtitan0123/somepics/blob/main/Ryujinx1.png)
![switch1](https://github.com/xtitan0123/somepics/blob/main/switch1.png)
![Ryujinx2](https://github.com/xtitan0123/somepics/blob/main/Ryujinx2.png)
![switch2](https://github.com/xtitan0123/somepics/blob/main/switch2.png)
![Ryujinx3](https://github.com/xtitan0123/somepics/blob/main/Ryujinx3.png)
![switch3](https://github.com/xtitan0123/somepics/blob/main/switch3.png)
![Ryujinx4](https://github.com/xtitan0123/somepics/blob/main/Ryujinx4.png)
![switch4](https://github.com/xtitan0123/somepics/blob/main/switch4.png)

**Comment by MetrosexualGarbodor** [comment]
This issue is already documented on the compatibility list.
