### ISSUE TITLE
Support for sys-botbase or similar ip connection functionality.

### ISSUE THREAD

**Issue by Mandydeth** [Ryujinx/Ryujinx#3753]
## Feature Request

[ Please search for existing [feature requests](https://github.com/Ryujinx/Ryujinx/issues) before you make your own request. ]</br>
[ Duplicate requests will be marked as such and you will be referred to the original request. ]

#### Overview:
-  Support for sys-botbase or a similar method of connecting to Ryujinx via IP connection 

#### Smaller Details: 
- A way to use features such as item injection via NHSE and other tools

### Why would this feature be useful?
Allows for direct item injection in game </br>

**Comment by TSRBerry** [comment]
Superseded by #5997
