### ISSUE TITLE
Use .NET 7 for Aot 

### ISSUE THREAD

**Issue by luc-git** [Ryujinx/Ryujinx#3758]
It can be useful to compile ryujinx in aot compilation in order to have a smaller software size and a faster launch time. Ryujinx is very performant but is a little slow to launch. At this moment .Net 7 is in preview mode and I tried to compile Ryujinx with it in aot mode but a lot of error are thrown when compiling with .Net 7 instead of .Net 6. Maybe we have to wait until .Net 7 is release in stable release.

**Comment by MutantAura** [comment]
The migration to .NET 7 and any use of its feature-set will be started when the stable release is finalized.
