### ISSUE TITLE
 Splatoon 3 crashes with "*** stack smashing detected ***: terminated" 5 seconds after boot.

### ISSUE THREAD

**Issue by autoteelar** [Ryujinx/Ryujinx#3772]
https://github.com/Ryujinx/Ryujinx/issues/2864 seems relevant.

runs just fine for like 5 seconds 

then 

    },
    "game_record_history": {
        "highest_udemae": 0,
        "highest_udemae_update_timestamp": 0
    },
    "vs_win_num_for_amiibo": 0,
    "change_fest_region_timestamp": 0,
    "version": 65536,
    "system_report_tag": 2175206328
}

00:00:26.430 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:00:26.431 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:28.987 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
*** stack smashing detected ***: terminated

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Comment by autoteelar** [comment]
sure i will, but just looking at it do you see anything interesting?

**Comment by autoteelar** [comment]
and well i dont really know if its game-specific or not yet, might be pre assumtious to close it just like that
