### ISSUE TITLE
[Avalonia] Controller Applet not working

### ISSUE THREAD

**Issue by Squall-Leonhart** [Ryujinx/Ryujinx#3773]
When starting a game with a controller mapped but powered off, Avalonia builds start throwing 

```GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'```

into the log window as expected, but the main window's menu's become unclickable as if a child window has been opened that blocks the parent.

![image](https://user-images.githubusercontent.com/1098176/196779463-04d032d5-acae-479d-94f3-114f997b6f03.png)

on the original GUI, these menu's remain clickable and the Controller Applet child window is opened informing the user to configure or attach the requested control. (see below)

![image](https://user-images.githubusercontent.com/1098176/196779058-2e221db0-0808-44e3-803b-c0f314dca17e.png)

**Comment by MetrosexualGarbodor** [comment]
Seems pressing Esc to bring up the "quit emulation?" prompt also makes the controller applet visible. If you don't do this, it stays hidden.
![image](https://user-images.githubusercontent.com/79612681/196821813-1736a24f-462d-423f-aa80-b530dd37a513.png)

Before pressing Esc, it doesn't show up here.
![image](https://user-images.githubusercontent.com/79612681/196822037-c554c8df-75ab-4f18-9a0b-589c55304ec4.png)

**Comment by Squall-Leonhart** [comment]
Can we reopen this, its reoccuring in 1.1.335

**Comment by tilsgee** [comment]
This problem also Appeared to "Pokemon Lets Go series"
GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'Handheld, JoyconLeft, JoyconRight, Pokeball' on 'Player1, Player2, Handheld'

**Comment by MANMAN13000** [comment]
How do we fix this wont stop when playing pokemon lets go
