### ISSUE TITLE
[Bug] Smash Ultimate - Imported replays can't be played and Ryujinx replays can't be played elsewhere

### ISSUE THREAD

**Issue by Xalavar** [Ryujinx/Ryujinx#3780]
Version: 1.1.299
Log: [Ryujinx_1.1.299_2022-10-12_17-06-42.log](https://github.com/Ryujinx/Ryujinx/files/9834921/Ryujinx_1.1.299_2022-10-12_17-06-42.log)

So I've dumped my replays from my Switch onto my PC, but Ryujinx only plays the first few seconds before booting me back to the replay menu with an in-game error (see the screenshot below). Additionally, any replays _saved_ in Ryujinx succumb to the same behavior when playing them on other platforms.

The table below lists the results for every combination of platforms I saved replays from and tried viewing them on. All replays tested were from the final Smash update and no mods were used.
|                  | Playable on Switch | Playable in Ryujinx | Playable in Yuzu |
|------------------|--------------------|---------------------|------------------|
| **Saved on Switch**  | ✔️                | ❌                  | ✔️              |
| **Saved in Ryujinx** | ❌**        | ✔️                 | ❌               |

** Side note: I noticed some substantial FPS spikes while playing the Ryujinx replays on my Switch.

✔️ = No issue. Replay successfully plays from beginning to end.
❌ = The platform only plays the first few seconds of a replay saved from the listed platform row, then stops, and brings me back to the replay menu with this error:

![image](https://user-images.githubusercontent.com/41214918/197089384-51a15476-cb07-4b0f-ae5b-394f8f13ee39.png)

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/136). Thank you.
