### ISSUE TITLE
GPU Vulcan Fix

### ISSUE THREAD

**Issue by TimNoob** [Ryujinx/Ryujinx#3796]
My notebook have *RTX 3060* graphics card width installed last drivers and vulcan runtime but if set preferences to vulcan my video card not found. If i disabled integrated video device this error disappears but game running very very very slow (3/5 fps). But i revert back settings on openGL (my GPU and integrated Ryzen7 not found in "*Preffered GPU*").  Pls fix this error 
Logs fragment:
_Ryujinx.Graphics.Vulkan.VulkanException: Initialization failed, none of the available GPUs meets the minimum requirements. at Ryujinx.Graphics.Vulkan.VulkanInitialization.FindSuitablePhysicalDevice(Vk api, Instance instance, SurfaceKHR surface, String preferredGpuId) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanInitialization.cs:line 225 at Ryujinx.Graphics.Vulkan.VulkanRenderer.Setup..._
 P.S App crashed after Vulcan set. Sry my englis not good. Default mode in OpenGL give 30fps with drawdowns up to 5fps

**Comment by GamerzHell9137** [comment]
Think this is support related. Join the Discord for support.

**Comment by MetrosexualGarbodor** [comment]
Update both the AMD GPU and Nvidia GPU drivers.

**Comment by TimNoob** [comment]
All of the latest drivers I have personally checked, both on the integrated video card and on the built-in. Installed Vulkan Runtime did not help. The application refuses to use video card resources in Vulkan mode. List of video cards when switching to Vulkan mode no, but if you disable at least one, no matter what he appears. For the record I have dota2 running on VulkanAPI and everything is normal, I put Rdr2 and DaysGone with MortalKombat 11 there is nothing wrong, and then one time and the problem with the drivers? Doesn't sound plausible it's an obvious problem!

Translated with www.DeepL.com/Translator (free version)

**Comment by jduncanator** [comment]
Do you have NVIDIA Optimus on your laptop? You will need to go into your NVIDIA settings and set the preferred GPU to your dedicated one, it's possible it's only loading the ICD for your integrated GPU otherwise.

**Comment by TimNoob** [comment]
Nividia optimus not supported on RTX 3060

**Comment by TimNoob** [comment]
I think this problem may be due to the fact that Windows 10 thinks it is a console application because the properties show the console options and the console starts first, not the window.

**Comment by jduncanator** [comment]
We have tens of thousands of users running Ryujinx perfectly fine on laptops/Windows 10. Given that only you are having this issue, it would suggest it's a configuration issue on your end.

Try forcing Ryujinx onto your dedicated GPU in the NVIDIA control panel.

**Comment by Squall-Leonhart** [comment]
the nvidia control panel is not how you force preferred gpu settings anymore, its effectively disabled on windows 10 above 1806.

it is more than than likely the AMD switchable layer issue that requires installing the amd reference drivers, if a vendor hasn't released them yet.

**Comment by TimNoob** [comment]
It's funny that this problem occurs only with your emulator) yuzu, cemu quietly work with vulkan. I think I'll switch to yuzu. Thank you all for your help

**Comment by Squall-Leonhart** [comment]
different ways to enumerate vk devices, all of them are legit and all of them rely on the systems drivers working properly.

yours are not.

**Comment by TimNoob** [comment]
All the same, I decided to install adrenaline drivers on AMD because I liked your emulator better than yuzu. You were right! It works! And by the way the video card in mode with vulkan was active without a driver when running any application that uses a video card by default appears Nvidia 3060 in the list. Issue closed and solved!
