### ISSUE TITLE
Burnout Paradise Remastered: Audio levels are off

### ISSUE THREAD

**Issue by fishcu** [Ryujinx/Ryujinx#3814]
### What's the issue you encountered?

Audio in cutscenes / intro video is too quiet compared to background music.
Audio is very quiet overall even at maximum volume.

### How can the issue be reproduced?

Start a new game. The intro video is way too quiet. Start playing. The audio is still very quiet overall.

### Log file

Nothing special here.

[Ryujinx_1.1.335_2022-10-31_10-46-03.log](https://github.com/Ryujinx/Ryujinx/files/9899948/Ryujinx_1.1.335_2022-10-31_10-46-03.log)

### Environment?

- Ryujinx version: 1.1.335</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 4800H
  - GPU: RTX 2060 mobile
  - RAM: 16 GB
- Applied Mods : No

### Additional context?

N.A.

**Comment by GamerzHell9137** [comment]
Wrong place to post.

https://github.com/Ryujinx/Ryujinx-Games-List/issues/1782

**Comment by EmulationFanatic** [comment]
Game-specific issues should be posted on their respective game issue pages on the compatibility list. Thanks!
