### ISSUE TITLE
Breath of the Wild Ryujinx v1.1.337

### ISSUE THREAD

**Issue by CartesianFish** [Ryujinx/Ryujinx#3821]
I'm having a serious issue with running BOTW since I've updated Ryujinx v1.1.337. The in-game terrain and character will saturate with solid or near solid yellow, green, or white. I have experimented with different settings to try to eliminate user error, but nothing has worked. I'm using Switch FW 15 and updated to 15.01 with no difference.

**Pc info:**
11700k
GTX 1650 (Vulkan v1.3.224, Driver v526.47.0.0)
16GB RAM
Windows 11 Pro

**Images:**
![Screenshot 2022-11-02 223657](https://user-images.githubusercontent.com/81728104/199644617-3fa93de4-f4e9-42eb-b070-3fd77ada4d40.png)
![Screenshot 2022-11-02 224012](https://user-images.githubusercontent.com/81728104/199644632-34582d14-94a3-4242-90d0-fa6f22895ad5.png)
![Screenshot 2022-11-02 225428](https://user-images.githubusercontent.com/81728104/199645098-efb41688-8b3a-4903-ad89-2e865dcb67b6.png)

**Ryujinx log (game is still running):**
00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.044 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.048 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.048 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.049 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.050 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.050 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.051 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1F0A
00:00:00.053 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.058 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.058 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.058 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.058 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.058 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.058 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.058 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.059 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.059 |I| Configuration LogValueChange: AudioVolume set to: 0.73
00:00:00.060 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.060 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.060 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.063 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.337
00:00:00.067 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.067 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz ; 16 logical
00:00:00.068 |N| Application Print: RAM: Total 16193 MB ; Available 11174 MB
00:00:00.070 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.071 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.061 |I| Gpu : Backend Threading (Auto): True
00:00:00.601 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:00.601 |I| Application LoadApplication: Loading as NSP.
00:00:00.637 |I| Application AddAocItem: Found AddOnContent with TitleId 01007EF00011F002
00:00:00.637 |I| Application AddAocItem: Found AddOnContent with TitleId 01007EF00011F001
00:00:00.655 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.658 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001
00:00:00.658 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002
00:00:00.660 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.660 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001
00:00:00.660 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002
00:00:00.667 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.674 |I| Loader LoadExeFs: Loading rtld...
00:00:00.742 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.742 |I| Loader LoadExeFs: Loading main...
00:00:00.970 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Cafe\U-King\trunk\Game\App\Rom\NX64\Product\code\U-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Atk-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-7_3_2-Release
                   SDK MW+Microsoft+Havok_Cloth-2014_2
                   SDK MW+Microsoft+Havok-2014_2
                   SDK MW+Microsoft+Havok_Animation-2014_2
                   SDK MW+Microsoft+Havok_AI-2014_2
                   SDK MW+Microsoft+Havok_Physics2012-2014_2
00:00:00.971 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.998 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-7_3_2-Release
00:00:00.998 |I| Loader LoadExeFs: Loading sdk...
00:00:01.062 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:01.127 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.615 |I| Ptc Load: Loaded Translation Cache (size: 154432314 bytes, translated functions: 77377).
00:00:02.631 |I| Ptc Load: Loaded Profiling Info (size: 267306 bytes, profiled functions: 77377).
00:00:02.781 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.782 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.796 |I| Loader LoadNsos: Loading image 2 at 0x000000000ad6a000...
00:00:02.798 |I| Loader LoadNsos: Loading image 3 at 0x000000000b487000...
00:00:02.810 |I| ModLoader LoadCheats: Build ids found for title 01007EF00011E000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    8E9978D50BDD20B4C8395A106C27FFDE00000000000000000000000000000000
    93FF8252D975ADF07230CB86C83301C53F2804DF000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:02.810 |I| Loader LoadNca: Application Loaded: The Legend of Zelda: Breath of the Wild v1.6.0 [01007ef00011e000] [64-bit]
00:00:03.467 |I| GUI.WindowThread Hid Configure: Configured Controller Handheld to Handheld
00:00:03.467 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:03.483 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:03.820 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1650 (Vulkan v1.3.224, Driver v526.47.0.0)
00:00:03.835 |I| GPU.MainThread Gpu LoadShaders: Loading 3605 shaders from the cache...
00:00:09.311 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:10.204 |I| HLE.GuestThread.15 Ptc LoadTranslations: 77377 translated functions loaded
00:00:10.355 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:10.359 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed.
00:00:10.359 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:10.360 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:10.367 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed.
00:00:11.449 |G| HLE.OsThread.16 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 10s
    Line: 18
    Filename: 'D:/home/Cafe/U-King/trunk/Game/Lib/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'U-King'
    Message: '0000002e'

00:00:11.450 |S| HLE.OsThread.16 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:11.450 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:11.451 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:11.451 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:11.451 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:11.487 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed.
00:00:11.492 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:11.504 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed.
00:00:11.524 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:11.566 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed.
00:00:11.567 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:11.567 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed.
00:00:11.567 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed.
00:00:11.568 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed.
00:00:11.568 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed.
00:00:11.568 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed.
00:00:11.570 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed.
00:00:11.598 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:11.601 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:11.601 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:11.606 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:11.629 |S| HLE.OsThread.16 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72197163296350208}
00:00:11.632 |S| HLE.OsThread.16 ServiceAcc IsUserAccountSwitchLocked: Stubbed.
00:00:11.654 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:11.655 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:11.656 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:11.656 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:12.564 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed.
00:00:12.564 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:14.825 |S| HLE.OsThread.9 ServiceHid ActivateConsoleSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:14.825 |S| HLE.OsThread.9 ServiceHid InitializeSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; counter0: 4096 ; counter1: 520192}
00:00:15.100 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:15.109 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV7
00:00:15.126 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:15.127 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:15.153 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:15.188 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:15.278 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceSystemEvent: Stubbed.
00:00:15.279 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed.
00:00:15.314 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.243 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed.
00:00:16.542 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; _gyroscopeZeroDriftMode: Tight}
00:00:16.542 |S| HLE.OsThread.16 ServiceAm SetGamePlayRecordingState: Stubbed. {_gamePlayRecordingState: True}
00:00:16.546 |S| HLE.OsThread.9 ServiceHid StopSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:27.508 |I| HLE.OsThread.16 ServicePrepo ProcessReport:
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: option
 Report: {
    "BalloonTextOnOff": 1,
    "AutoSaveOnOff": 1,
    "CameraUpDownReverse": 0,
    "CameraRLReverse": 0,
    "TextRubyOnOff": 1,
    "JumpButtonChange": 0,
    "StickSensitivity": 2,
    "GyroOnOff": 0,
    "MiniMapDirection": 1,
    "AmiiboItemOnOff": 0,
    "MainScreenOnOff": 0,
    "DisplaySpecialMode": 0,
    "TextWindowChange": 1,
    "DockInOnOff": 1,
    "ControllerType": 1,
    "AttachExtGrip": 0,
    "CtrlModeHandheldFree": 0,
    "CtrlModeHandheldExt": 0,
    "CtrlModeHandheldFullKey": 0,
    "CtrlModeHandheldHandheld": 0,
    "CtrlModeConsoleFree": 0,
    "CtrlModeConsoleExt": 0,
    "CtrlModeConsoleFull": 78655,
    "PlayTimeHandheld": 0,
    "PlayTimeConsole": 78655,
    "PlayTimeAll": 78655,
    "RomVer": 160,
    "AoCVer": 30,
    "RegionLanguage": 16,
    "AudioMono": 0,
    "AudioStereo": 0,
    "Audio5_1ch": 78655,
    "AudioOther": 0
}

00:00:59.668 |N| .NET ThreadPool Worker Application Screenshot: Screenshot saved to C:\Users\xxxxx\Pictures\Ryujinx\ryujinx_capture_2022-11-02_22-39-49.png
00:01:10.236 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 267317 bytes, profiled functions: 77380).

**Comment by OldManKain** [comment]
Known Issue.

Please come to the [discord](https://discord.gg/ryujinx) for support or check the [games list](url) for known or to report new issues.

**Comment by jduncanator** [comment]
Correct games list link is this one: https://github.com/Ryujinx/Ryujinx-Games-List/issues
