### ISSUE TITLE
Sonic Frontiers: high load GPU

### ISSUE THREAD

**Issue by wounkun** [Ryujinx/Ryujinx#3823]
Hi. I have a problem while playing Sonic Frontiers: when game starts get freezing 2-3fps in 2 minutes; when ups to 30fps get high load rendering on GPU to 90-100%; after playing 10-15 minutes crashing. It has high load on GPU RTX 4090 and shows warning "GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented."

Possibly to fix it?

![image](https://user-images.githubusercontent.com/34368014/199946259-26d7c234-1c18-4931-bf8e-2c997b70a85b.png)

**Comment by MetrosexualGarbodor** [comment]
Do not open issues for unreleased games.
