### ISSUE TITLE
Xenoblade Chronicles 2 crashes on RadeonSL

### ISSUE THREAD

**Issue by ulti214** [Ryujinx/Ryujinx#3831]
The game crashes immediately with the OpenGL graphical backend. Although while it runs somewhat fine with Vulkan, all of the models are broken like the game is corrupted. 
![image](https://user-images.githubusercontent.com/97585083/201241077-a17a4b6d-4c72-40e4-aa00-7f929ecc275c.png)
OS: EndeavourOS
CPU: Ryzen 5900X
GPU: AMD RX 6600XT
RAM: 16 GB

**Comment by MutantAura** [comment]
Game-specific issues should be reported on the game's compatibility page: https://github.com/Ryujinx/Ryujinx-Games-List/issues
