### ISSUE TITLE
OpenAL initialization failure

### ISSUE THREAD

**Issue by devtrickhub** [Ryujinx/Ryujinx#384]
![errorline21](https://user-images.githubusercontent.com/41463022/44586762-1f3de480-a7b1-11e8-84a0-69ac3ec8fbfa.JPG)
 Errro on line 21  and 205
Using Windows Version 1803 (build 17134.228)

**Comment by AcK77** [comment]
You should install OpenAL SDK as it’s said on our Website and in the Readme. Thanks!

**Comment by gdkchan** [comment]
Please use the title as a brief description of your issue. If you want to talk with us, write a normal comment on the issue.

OpenAL needs to be installed for it to work, you can use the installer from the official page. Theres also a checkbox you need to check on the setup for it to work.

**Comment by DrHacknik** [comment]
Why is this issue still open? Is there a need that I am unaware of? 

_To be fair, the Discord server is a better place to ask these things._

**Comment by Dudejoe870** [comment]
He did @DrHacknik no one could help him, that's why he opened a issue here.

**Comment by DrHacknik** [comment]
@Dudejoe870 Yet this issue is still open. As to why I don't have perms to close issues on this repo is funny. Since I have perms elsewhere.

**Comment by Dudejoe870** [comment]
He had said he installed OpenAL though, and it didn't work, that's why he opened a issue.

**Comment by DrHacknik** [comment]
Well it seems that he hasn't responded in over a week. So I am assuming he doesn't care any longer, or fixed it.

**Comment by Dudejoe870** [comment]
Yeah I supposed

**Comment by simonmkwii-dev** [comment]
Try reinstalling this: https://www.openal.org/downloads/oalinst.zip

**Comment by emmauss** [comment]
Closing this issue. No response from op
