### ISSUE TITLE
Pokemon Scarlet crashed 

### ISSUE THREAD

**Issue by tfqmstrmnd** [Ryujinx/Ryujinx#3840]
## Missing Service Call

[ when i start  the game it crashed since very first booting. ]</br>

[ trying to looking for tips on the internet but not working at all. ]</br>
[ thank you. ]</br>

[Ryujinx_1.1.341_2022-11-12_07-59-47.log](https://github.com/Ryujinx/Ryujinx/files/9993791/Ryujinx_1.1.341_2022-11-12_07-59-47.log)
![Ryujinx Console 1 1 341 11_12_2022 8_04_39 AM](https://user-images.githubusercontent.com/74163672/201449198-da2b021c-6b53-4050-9a79-afc79e8298de.png)

**Comment by MutantAura** [comment]
Please do not open issues for unreleased games.
