### ISSUE TITLE
Splatoon 3 Vulkan crash 

### ISSUE THREAD

**Issue by dangerousPoison** [Ryujinx/Ryujinx#3843]
## What's the issue you encountered?

There is a crash when you are trying to play a level. It happens only using Vulkan. Switching to OpenGL the level is loaded without issues.

I'm including a video and my save file to help you. The log file is also included.

## How can the issue be reproduced?

The error happens right after loading the level (check video).

## Environment?

- Ryujinx version: 1.1.341 (also 1.1.338)</br>

- System Specs:
  - OS: Windows 10
  - CPU: i9-10900KF
  - RAM: 32 GB
  - GPU: NVIDIA RTX 3070 Ti
- Applied Mods : No

## Additional context?

Save file:
[GameSave00.zip](https://github.com/Ryujinx/Ryujinx/files/9995498/GameSave00.zip)

Video:

https://user-images.githubusercontent.com/93678306/201486084-38ce31ad-9bcf-4438-9460-4b463b09fc8b.mp4

Log:
[Ryujinx_1.1.341_2022-11-11_21-09-52.log](https://github.com/Ryujinx/Ryujinx/files/9995500/Ryujinx_1.1.341_2022-11-11_21-09-52.log)

**Comment by MetrosexualGarbodor** [comment]
This is not a game issue, you are running out of VRAM due to the 3x resolution scale.
