### ISSUE TITLE
Controller input doesn't work if remote desktop is active

### ISSUE THREAD

**Issue by sirzento** [Ryujinx/Ryujinx#3849]
When accessing the computer via remote desktop, the controller inputs wont work anymore.

**Comment by sirzento** [comment]
But why can I run and play via remote desktop with keyboard as input? Only thing I see is that the controller is not working.

**Comment by EmulationFanatic** [comment]
The takeaway here is that playing via remote desktop is not a supported configuration. Using Parsec or other similar streaming application would be a better option.
