### ISSUE TITLE
.NET 6/7 improvements

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#3858]
#### Overview:
This is a short list of improvements that have been enabled by .NET 6 or .NET 7, with the introduction of new features and APIs.

#### Smaller Details: 
- [x] `Interlocked.And`/`Interlocked.Or` (#3937)

`Ryujinx.Memory/Tracking/ConcurrentBitmap` currently uses a compare and swap look to set and clear bits on the bitmap array. Those news methods can be used to update it atomically in a more efficient way.

- [x] Generic math (#3929)

We have some methods on `Ryujinx.Common/Utilities/BitUtils` with overloads for all the common integer types. With the new generic math feature, we can replace them with a single method that operates on integers. There are other cases that can potentially benefit too like the `Add` methods on `ARMeilleure/IntermediateRepresentation/Operand`.

- [x] System.Half (#4106)

This was actually introduced in .NET 6. We can remove `Ryujinx.Graphics.Shader/Translation/Optimizations/HalfConversion` and replace it uses with a reinterpretation of the ushort value to the Half type followed by a cast to float.

**Comment by turbedi** [comment]
Another one: [P/Invoke source generation](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation)

**Comment by luca-bertero** [comment]
Seal internal types: https://github.com/dotnet/runtime/issues/49944. 
It show really big improvement in the performance

**Comment by gdkchan** [comment]
Another one that I forgot is that C# not has ref fields. I think it can replace some (or all?) usages of the `Ptr<T>` type on the VP9 decoder (`Ryujinx.Graphics.Nvdec.Vp9`). Probably a bit more complicated than the other changes.

**Comment by mageven** [comment]
> - `Interlocked.And`/`Interlocked.Or`

> `Ryujinx.Memory/Tracking/ConcurrentBitmap` currently uses a compare and swap look to set and clear bits on the bitmap array. Those news methods can be used to update it atomically in a more efficient way.

This part was resolved by #3937

**Comment by turbedi** [comment]
Another set of new APIs introduced in .NET 6/7: Throw helper APIs like
[ArgumentNullException.ThrowIfNull](https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-7.0#system-argumentnullexception-throwifnull(system-object-system-string))
[ObjectDisposedException.ThrowIf](https://learn.microsoft.com/en-us/dotnet/api/system.objectdisposedexception.throwif?view=net-7.0#system-objectdisposedexception-throwif(system-boolean-system-object))

**Comment by gdkchan** [comment]
Closing as all the improvements have already been done. We can open separate issues for other potential improvements.
