### ISSUE TITLE
Support for macOS 10 High Sierra

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [Ryujinx/Ryujinx#3903]
#### Overview:

Compilation with support for macOS 10 High Sierra would be great for the group of people using Hackintosh computers that have stayed on macOS 10 for being the last version of macOS that supports Nvidia GPUs. These are computers with hardware perfectly capable of running the emulator being left behind the newly implemented macOS support.

I understand it would depend on the complexity of the emulator, but just about every emulator on macOS except for RPCS3 still compiles with support for High Sierra and above.

**Comment by EmulationFanatic** [comment]
Protip: Boot into Windows or Linux on the PC being used as a Hackintosh and enjoy full support.

**Comment by 2V3EvG4LMJFdRe** [comment]
😕 for reference, RPCS3 can't do it for technical reasons which are at least detailed on the issue https://github.com/RPCS3/rpcs3/issues/11986
