### ISSUE TITLE
[Bug] MacOS - Triangle "stuck" on screen on top of certain effects in Super Mario Odyssey

### ISSUE THREAD

**Issue by dagstuan** [Ryujinx/Ryujinx#3904]
First of all, amazing work making this even run on MacOS!

When I run Super Mario Odyssey I sometimes see a "triangle" stuck on the screen over certain effects such as waterfalls and smoke. Is there some way of making this triangle go away? See screenshots/video

https://user-images.githubusercontent.com/397559/204088845-dca560c8-4c97-41a0-89ae-1e3bc9833c42.mov

<img width="505" alt="Screenshot 2022-11-26 at 12 17 11" src="https://user-images.githubusercontent.com/397559/204088851-1f37eb58-7325-4de6-9ddb-4091fe41a1f9.png">
<img width="982" alt="Screenshot 2022-11-26 at 13 02 42" src="https://user-images.githubusercontent.com/397559/204088853-1e585913-201e-4df6-9227-f2f1e1437744.png">

**Comment by EmulationFanatic** [comment]
Thanks for the report! This issue tracker is for general emulator issues. Please post this info as a reply to the [game's compatibility issue](https://github.com/Ryujinx/Ryujinx-Games-List/issues/93) on the compatibility list.
