### ISSUE TITLE
[Error] Running Pokémon Scarlet & Violet with high resolution scale causes crash.

### ISSUE THREAD

**Issue by Fiocher** [Ryujinx/Ryujinx#3907]
Does this file contain error information? I'm not very familiar with it and can only find this file.
[Ryujinx_1.1.389_2022-11-26_23-15-47.log](https://github.com/Ryujinx/Ryujinx/files/10096502/Ryujinx_1.1.389_2022-11-26_23-15-47.log)

**Comment by EmulationFanatic** [comment]
Please post this on the respective game compatibility list entry. This issue tracker is for general emulator issues.
