### ISSUE TITLE
NBA 2K22 and NBA 2K23 black screen on boot

### ISSUE THREAD

**Issue by timgerstel** [Ryujinx/Ryujinx#3910]
#### Overview:
- NBA 2K22 and 2K23 do not boot

#### Nature of Request:  
[ Remove all that do not apply to your request. ]
- Addition
  - Support for game

### Why would this feature be useful?
Ball is life

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues on the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List). Thank you.
