### ISSUE TITLE
macOS - Random crashes in game

### ISSUE THREAD

**Issue by federicochiesa** [Ryujinx/Ryujinx#3916]
Hi, I'm not specifying the type of issue because I really don't know since when I load a game it loads fine, but at completely random spots in the game Ryujinx just crashes and macOS says it quit unexpectedly without giving me a reason except for EXC_CRASH(SIGABRT).

If I can help in any way to solve this issue please let me know how.

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues on the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List) and add a Ryujinx log file when reporting crashes. Thank you.
