### ISSUE TITLE
macOS - Album photos don't display correctly in BotW

### ISSUE THREAD

**Issue by R-033** [Ryujinx/Ryujinx#3917]
#### Overview:
- Please fix album in BotW on macOS. The camera itself works fine, but saved images in the album look like distorted halfs of story images.

#### Smaller Details: 
![Screenshot 2022-11-28 at 02 32 43](https://user-images.githubusercontent.com/15189406/204148401-65b61b5b-8bcd-4faa-9136-011d7acaca6d.png)

#### Nature of Request:  
- Bug fix

### Why would this feature be useful?
- This would make albums useful in the game.

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues on the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List). Thank you.
