### ISSUE TITLE
Avalonia: Tab key steals input and never gives it back

### ISSUE THREAD

**Issue by andOlga** [Ryujinx/Ryujinx#3919]
### What's the issue you encountered?

Pressing Tab while a game is running on Avalonia seems to focus the menu, which causes arrow keys to start navigating it. The hotkey binding for Tab (which defaults to vsync toggle) also does not trigger. Furthermore, there is no way to return the input handling back to the game itself, so that the keys can be used for input again -- or, at least, I haven't found one: hitting Tab over and over doesn't help, clicking the game doesn't help, clicking the menu bar doesn't help. Restarting Ryujinx helps (but only until you hit Tab again), though this is rather extreme since an accidental button press can essentially force you to end your play session and potentially lose progress.

### How can the issue be reproduced?

https://user-images.githubusercontent.com/462484/204158355-bb6783e7-5e09-4345-a9e2-3b71f9976d91.mp4

### Environment?

- Ryujinx version: 1.1.391</br>
- Game version: (irrelevant)</br>
- System Specs:
  - OS: *Windows 11 22H2*
  - CPU: (irrelevant)
  - GPU: (irrelevant)
  - RAM: (irrelevant)
- Applied Mods : No

**Comment by MetrosexualGarbodor** [comment]
This is not really an issue, it's just how the Avalonia framework functions. Once Avalonia becomes the default, Vsync will be moved to another hotkey by default. Until then, Avalonia lets you change it.

Perhaps it would be better to instead focus the issue on how the keyboard can't send inputs to the game again after pressing it, but I'm not sure if that's an emulator bug either; it might be a bug on their end, it might even be intended.
