### ISSUE TITLE
macOS - Random Crashes Happens in various games

### ISSUE THREAD

**Issue by arkeane** [Ryujinx/Ryujinx#3920]
## Bug Report

The emulator crashes without predictable cause while gaming.

### What's the issue you encountered?

While Playing the Emulator crashes (apparently) randomly without any significant hint (stuck game, glitches ecc...).</br>
No change was made to the configuration</br>

### How can the issue be reproduced?

Just by playing, The Issue was encountered while playing:
Pokémon Brilliant Diamond
Animal Crossing New Horizons

Probably It just happens with every other game

### Log file
[Ryujinx_ 1.1.0-macos1_2022-11-27_22-04-19.log](https://github.com/Ryujinx/Ryujinx/files/10099217/Ryujinx_.1.1.0-macos1_2022-11-27_22-04-19.log)
[MacOSCrashreport_2022-11-27-22-04-19.log](https://github.com/Ryujinx/Ryujinx/files/10099219/MacOSCrashreport_2022-11-27-22-04-19.log)

### Environment?

- Ryujinx version: 1.1.0</br>
- Game version: 1.3.0</br>
- System Specs:
  - OS: *MacOS Ventura*
  - CPU: *Apple M1*
  - GPU: *Apple M1 8-Core*
  - RAM: *8GB*
- Applied Mods : NO

### Additional context?

Additional info about your environment:</br>
Macbook Air M1 With 8-Core GPU

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues on the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List). Thank you.

**Comment by gdkchan** [comment]
For more "generic" issues that affects multiple games, it's better to report them here no? Rather than adding the same information on several games.

**Comment by arkeane** [comment]
It does affect multiple games
