### ISSUE TITLE
macOS - Extreme Audio Lagging

### ISSUE THREAD

**Issue by manuthebyte** [Ryujinx/Ryujinx#3921]
## Bug Report

Audio

### What's the issue you encountered?

In the version 1.1.0-macos1 the two games I tested (MK8 Deluxe and Super Mario 3D World + Bowser) have extreme audio lags.

It just sounds like Distortion.

I tested OpenAL and SDL2 as the audio backend, both of which have the same issue.

### How can the issue be reproduced?

1. Go onto the website and download the macOS-Version.
2. Start it
3. Do the initial setup (keys + firmware installation)
4. Start any game

### Environment?

- Ryujinx version: 1.1.0-macos1
- System Specs:
  - OS: *macOS Ventura*
  - CPU: *M1 Max 32C*
  - RAM: *64GB*

## Additional Information

If I look up the benchmarks of the Ryujinx, it looks like it runs pretty good on the apple silicon Macs. I saw the video today of Andrew Tsai, as an example, where he had stable 60FPS and no audio lag at all.

What's REAAALLY weird: it seems to me that every time I do something (change window, change focus, click on anything) it shortly has good audio but then re-distorts (yeah tested it now a couple of times, my theory is correct somehow)

And I have also tried it with Rosetta and tried to turn off SoundSource, both with no success.

And lastly, it seems not that my bluetooth headphones are the cause, I also tried it with the built-in speakers.

**Comment by 556644O** [comment]
I have met this issue once when I transferred the audio output device from speaker to my airpods.

**Comment by manuthebyte** [comment]
I don't know what I did, but after a restart everything works. Also with SoundSource enabled.
