### ISSUE TITLE
Ryujinx crashing / Pokemon Scarlet & Violet 

### ISSUE THREAD

**Issue by IdiotSandwich00** [Ryujinx/Ryujinx#3927]
### What's the issue you encountered?

[ Whenever I start ryujinx OR specifically try to encounter / catch a pokemon that is when this issue occurs ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ All I've done is simply update ryujinx to the current version (Most Recent as of 11/28/2022) ]

### How can the issue be reproduced?

[ Start Game / Attempt to encounter + catch a pokemon or idly walk / sprint in the game around pokemon ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

00:00:00.073 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.082 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.082 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.083 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.085 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.086 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.087 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2486
00:00:00.090 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.103 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.104 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.104 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.104 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.104 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.106 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.106 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.107 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.107 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.108 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.113 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.394
00:00:00.120 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.121 |N| Application Print: CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
00:00:00.122 |N| Application Print: RAM: Total 16335 MiB ; Available 12073 MiB
00:00:00.127 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.127 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### Environment?

- Ryujinx version: 1.1.394 

- Game version: 1.0.1

- System Specs:
Processor - AMD Ryzen 5 3600 6-Core Processor 3.59 GHz 
Installed RAM	- 16.0 GB 
GPU - NVIDIA GEFORCE 3060 TI

- Applied Mods : [ Yes (Which ones) / No ]

4x candy xp
100% fast capture on 
Tera Orb Recharge After Battle 
Force Shiny on
6 IV On
Infinite Money & LP
Game Speed 1.5x 

### Additional context?

Additional info about your environment:</br>

[ Game was working fine till I clicked the Ignore Evolution mods, first time I tried using it is when this started, now with cheats reset and off it still crashes, please help I'm not smart and i'm most certainly in need of a distraction! ]

![image](https://user-images.githubusercontent.com/115895181/204233981-b6026dbe-c318-4e05-8925-2102801af9cf.png)
![image](https://user-images.githubusercontent.com/115895181/204234016-6c083420-dd8d-459e-bf99-d2f810050f6f.png)
[Ryujinx_1.1.394_2022-11-28_03-40-01.log](https://github.com/Ryujinx/Ryujinx/files/10101997/Ryujinx_1.1.394_2022-11-28_03-40-01.log)
[Ryujinx_1.1.394_2022-11-28_03-31-54.log](https://github.com/Ryujinx/Ryujinx/files/10101998/Ryujinx_1.1.394_2022-11-28_03-31-54.log)

**Comment by IdiotSandwich00** [comment]
**Just to clarify** I either didn't get a crash report or simply don't know where to look, my apologies.

**Comment by OldManKain** [comment]
Infinite money and LP does not work on emulators.  That is what is causing your crash.

**Comment by IdiotSandwich00** [comment]
> Infinite money and LP does not work on emulators, that is what is causing your crash.
> 
> If you need further assistance, please join us in the [Ryujinx Discord](https://discord.com/invite/VkQYXAZ).

I feel like it does because I went the entire playthrough before turning on the evolution ignore mod and the infinite money and LP worked, but I will take your suggestion / fact and turn it off and see. Thank you for the speedy response!
