### ISSUE TITLE
when load games, ryujinx is crashed

### ISSUE THREAD

**Issue by bearfat001** [Ryujinx/Ryujinx#3930]
## Bug Report

when load games, ryujinx is crashed. All games.
I am using a mac M1, bigsur 11.0.1

### Log file

attached in [files]
[attached.txt](https://github.com/Ryujinx/Ryujinx/files/10105738/attached.txt)

### Environment?

- Ryujinx version: 1.1.0-macos1</br>

- Game version: X.X.X</br>
mario odessy 1.0.0

- System Specs:
  - OS: bigsur 11.0.1
  - CPU: mac m1
  - GPU: 
  - RAM: 8G
- Applied Mods : 

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MetrosexualGarbodor** [comment]
Please join [discord](https://discord.gg/ryujinx) for help. Thank you.

**Comment by bearfat001** [comment]
i cannot join the ryujinx server according to the url above. I check the pic of banana once and once again, but the page remain the same

**Comment by bearfat001** [comment]
@MetrosexualGarbodor
