### ISSUE TITLE
Regression: LAN play does not work for Splatoon 3

### ISSUE THREAD

**Issue by CoocooFroggy** [Ryujinx/Ryujinx#3936]
### What's the issue you encountered?

In Splatoon 3, when initiating LAN play as described [in the Wiki](https://github.com/Ryujinx/Ryujinx/wiki/Multiplayer-(LDN-Local-Wireless)-Guide#splatoon-3-lan-mode), the player is kicked out to the plaza from The Shoal. I'm unsure if this is a regression or a Mac specific bug—not sure if anyone has tried LAN play recently for this game. A relevant error appears in the logs.

```
PlayReport log:
 UserId: 33b5a3e98ab94435afd97a4ad90a1b20
 Room: erepo_network_error
 Report: {
    "SectionId": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "SectionType": 0,
    "SectionTime_sec": 79,
    "NetworkType": 2,
    "ServerSessionId": "",
    "P2PSessionId": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "P2PSessionClock_sec": -1,
    "ErrorFrom": "Nifm",
    "ErrorLevel": "NeedSpecialHandling",
    "CommonError": "ReadyNetworkFailed",
    "IsNeedDisplayViewer": False,
    "ApplicationErrorId": 0,
    "system_report_tag": 0
}
```

### How can the issue be reproduced?

Follow the steps for LAN Mode as described by the Wiki:

1. Start Splatoon 3 with "Guest Internet Access/LAN Mode" disabled (otherwise you'll be stuck on the initial screen)
2. Enable "Guest Internet Access/LAN Mode" and enter The Shoal.
3. Perform the button combination to be taken to LAN play
4. After less than a second with the "Preparing LAN play" popup, the scene will transition back to the plaza and the log will print the error above

### Log file

[Ryujinx_ 1.1.0-macos1_2022-11-28_17-27-39.log](https://github.com/Ryujinx/Ryujinx/files/10107988/Ryujinx_.1.1.0-macos1_2022-11-28_17-27-39.log)

### Environment?

- Ryujinx version: 1.1.0-macos1</br>
- Game version: 1.2.1</br>
- System Specs:
  - OS: macOS Monterey — 12.6 (21G115) Darwin 21.6.0
  - CPU: Apple M1
  - GPU: MoltenVK Apple M1 (Vulkan v1.2.231, Driver v0.2.2008)
  - RAM: 8192 MiB
- Applied Mods : No

### Additional context?

N/A</br>

**Comment by CoocooFroggy** [comment]
Confirmed reproducible on Windows as well, as per Dragonu#3831 [on Discord](https://discord.com/channels/410208534861447168/830855276437438485/1046930324237586583):

> processor  Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
RAM installed  16.0 GB (15.8 GB usable)
> Nvidia GTX 1050 4gb
> windows 11 x64

https://user-images.githubusercontent.com/45371102/204421773-a46e9f98-e4fe-4174-9e47-3477a8a287d1.mp4

**Comment by MetrosexualGarbodor** [comment]
Make sure you enable guest internet access while _in_ the Shoal and that nothing's blocking Ryujinx from using the internet, such as a firewall, antivirus or router configuration. 

https://user-images.githubusercontent.com/79612681/204428746-6c0f46b7-4ce6-41be-90c3-ac50329e6e30.mp4

**Comment by CoocooFroggy** [comment]
Enabling guest mode while in the shoal unfortunately results in the same issue.

Mario Kart 8 DX's LAN Play works perfectly as well—it's just Splatoon 3. I've tried both with internet and on an ad-hoc network solely for LAN, and neither worked. I've also tried ethernet, and manually trying en0 and en8 interfaces—none of which worked.

Are you sure internet is required?

**Comment by CoocooFroggy** [comment]
Dragonu was apparently able to solve the issue by downgrading LDN to 2.5, which points towards regression. And to support this, I can't find any reports of this issue before a week ago. This isn't possible on Mac, though, as LDN is bundled.

<img width="529" alt="Screen Shot 2022-11-29 at 7 25 57 AM" src="https://user-images.githubusercontent.com/45371102/204528675-8ab55378-48a3-470f-a28e-c190c02c0629.png">

Although I see that you're on LDN 3.0.1, so I'm not really sure what's happening.
