### ISSUE TITLE
Updater for Ryujinx for MacOS

### ISSUE THREAD

**Issue by KrishWu** [Ryujinx/Ryujinx#3941]
## Feature Request

</br>

#### Overview:
- An updater for MacOS can be added to assist in keeping MacOS users up to date.

#### Smaller Details:
- The most common way to update mac apps is through sparkle.
- https://sparkle-project.org/
- This is an open-source framework that most third-party apps use to help manage updates.

#### Nature of Request:
- Addition
  - This is the license they use.
  - https://github.com/sparkle-project/Sparkle/blob/2.x/LICENSE
- Change

### Why would this feature be useful?
This would benefit the end user in helping them keep up to date, so I just added some info I thought would help the more experienced developers with moving along in the process! 😃

**Comment by marysaka** [comment]
Closed by https://github.com/Ryujinx/Ryujinx/pull/4464
