### ISSUE TITLE
Animal Crossing 01006F8002326000 - random crashes

### ISSUE THREAD

**Issue by mbs0ft** [Ryujinx/Ryujinx#3945]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?
Random crashed after launch, nothing in Ryujinx is changed

### How can the issue be reproduced?
Launch game, after couple minutes got crash

### Log file
[Ryujinx_ 1.1.0-macos1_2022-11-29_12-30-23.log](https://github.com/Ryujinx/Ryujinx/files/10112375/Ryujinx_.1.1.0-macos1_2022-11-29_12-30-23.log)
[Ryujinx_ 1.1.0-macos1_2022-11-29_12-47-58.log](https://github.com/Ryujinx/Ryujinx/files/10112376/Ryujinx_.1.1.0-macos1_2022-11-29_12-47-58.log)

### Environment?

- Ryujinx version: 1.1.0</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *(macOS Ventura 13.0)*
  - CPU: *(M2)*
  - GPU: *(M2)*
  - RAM: *(8GiB)*
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please post game-specific issues on their respective game entry on the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List/issues). Thanks!
