### ISSUE TITLE
A Internet Lobby？or Can create myself Public Server？

### ISSUE THREAD

**Issue by PigeonMuyz** [Ryujinx/Ryujinx#3950]
Ryujinx LDN is really useful.But there is no Internet Lobby？We can't see who online in my RyujinxKey.It's Terrible.I think can Create Server. And I have some ASP.WEB development capabilities, but I not found the Ryujinx LDN API Docs.
I wonder if you can publish some API documents, so that we can also find ways to research our own Ryujinx online server

**Comment by PigeonMuyz** [comment]
Come and Help me！

**Comment by EmulationFanatic** [comment]
Go to https://ldn.ryujinx.org to see who is playing. It's not intended for you to set up your own LDN server, you just use the games' local wireless as the game intends, and it works.
