### ISSUE TITLE
Ryujinx for Mac consistently crashes on "game list" screen

### ISSUE THREAD

**Issue by vesper8** [Ryujinx/Ryujinx#3962]
### What's the issue you encountered?

Ryujinx is crashing while just starting at the game list. I have 32 games. I noticed that the games don't appear automatically when I open Ryujinx. After I hit the little refresh icon, they appear after a few seconds. Then, within ~1 minute it crashes time and time again with the error found below.

### How can the issue be reproduced?

This is following a fresh install of Ryujinx for Mac. I deleted the ~/.config/Ryujinx folder and installed a fresh copy. Installed the 15.0.1 firmware and keys. Then I pointed it to a folder containing .nsp and .xci games, 32 of them.

### Log file

00:18:06.323 |W| .NET ThreadPool Worker Application LoadApplications: Failed to fetch the public games JSON from the API. Player and game count in the game list will be unavailable.
00:18:46.977 |W| .NET ThreadPool Worker Application LoadApplications: Failed to fetch the public games JSON from the API. Player and game count in the game list will be unavailable.
00:18:47.022 |E| .NET ThreadPool Worker Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Ui.Common/App/ApplicationLibrary.cs:line 521
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

### Environment?

- Ryujinx version: 1.1.0</br>
- Game version: n/a</br>
- System Specs:
  - OS: MacOS Ventura 13.0.1
  - CPU: M1 MAX
  - GPU: M1 MAX
  - RAM: 64GiB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
n/a

**Comment by EmulationFanatic** [comment]
This happens when the LDN website goes down (which we are currently experiencing frequently and are actively investigating).

**Comment by vesper8** [comment]
Turning off your wifi entirely prior to launching a game seems to prevent this from happening too.
