### ISSUE TITLE
Games sometimes don't up on MacOs Ryujinx

### ISSUE THREAD

**Issue by lul0910** [Ryujinx/Ryujinx#3963]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
Games sometimes don't show up, even though it showed up before.</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
No</br>
[ If so, make sure to include details relating to what exactly you changed. ]
 "N/A"
### How can the issue be reproduced?
Opening and closing Ryujinx multiple times
[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.1.0</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS:  MacOs Ventura 13.0.1*(e.g. Windows 10)*
  - CPU: M1 Pro*(e.g. i7-6700)*
  - GPU: M1 Pro *(e.g. NVIDIA RTX 2070)*
  - RAM: 16 GB *(e.g. 16GiB)*
- Applied Mods : No [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by Animenosekai** [comment]
Did you wait a bit for them to show up ? Sometimes it takes a little bit of time to load

**Comment by lul0910** [comment]
It seemed to be somewhat inconsistent, sometimes it's a minute but maybe I didn't wait long enough. I think the longest I waited without something showing up was around 5 min.

**Comment by vesper8** [comment]
Try turning off your wifi entirely before launching Ryujinx. Then open it, do all games show up instantly then?

**Comment by AcK77** [comment]
The issue template is bad completed and mostly unreadable.
I suggest you to come on our Discord for support, if a real issue exist, then reopen a new one well completed. Thanks.
