### ISSUE TITLE
Ava UI: Text alignment issues on non Windows platforms [Fixed in V2]

### ISSUE THREAD

**Issue by IsaacMarovitz** [Ryujinx/Ryujinx#3970]
There is a series of issues regarding text alignment issues in FluentAvalonia on non-Windows platforms. FluentAvalonia v2, which should be released soon, contains a fix for this [issue](https://github.com/amwx/FluentAvalonia/pull/210), `TextVerticalAlignmentOverrideBehavior`.

I have done a quick build with the preview version of FluentAvalonia v2 and confirmed that this solves the issue.

I'm making this issue for tracking this problem, as some work will be required to convert to v2 when it releases.

Notably, some controls, like `Search` are not fixed by v2 and will probably need work on our side.

**Comment by AcK77** [comment]
It's not possible to do a temporary fix on our side until the v2 of FluentAvalonia is out?
We can remove the fix later and then keep going on other changes.

**Comment by IsaacMarovitz** [comment]
@AcK77 I tried to make patches but Avalonia ignored my Style selectors even though they showed up in the dev tools.
