### ISSUE TITLE
The latest version cannot load the game on m2, it keeps crashing

### ISSUE THREAD

**Issue by Arks7** [Ryujinx/Ryujinx#3971]
## Bug Report

The latest version cannot load the game on m2, it keeps crashing

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file
 error log：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/82130343/204996103-fa6daeff-1f8d-440f-adad-d12222cb3335.png">

### Environment?

- Ryujinx version: 1.0.X</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *MacOS*
  - CPU: *M2*
  - RAM: *16GiB*
- Applied Mods : No 

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by skabning** [comment]
What is your process for dumping roms? Please be as detailed as possible, as it seems like there's an issue with how they were obtained.
