### ISSUE TITLE
Ryujinx wont boot any game

### ISSUE THREAD

**Issue by player94j** [Ryujinx/Ryujinx#3979]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ryujinx [34644]
Path:                  /Users/USER/Desktop/Ryujinx.app/Contents/MacOS/Ryujinx
Identifier:            org.ryujinx.Ryujinx
Version:               1.1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               752158348

Date/Time:             2022-11-30 15:13:39.2897 -0600
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Anonymous UUID:        75F855DD-13E9-5B93-D8F5-8C6045B83907

Sleep/Wake UUID:       A0275A45-17C4-4A39-8E89-64AE3365ADE3

Time Awake Since Boot: 19000 seconds
Time Since Wake:       747 seconds

System Integrity Protection: enabled

Crashed Thread:        59

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80c1dd97a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80c1ddce8 mach_msg + 56
2   CoreFoundation                	    0x7ff80c2e139d __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff80c2dfa28 __CFRunLoopRun + 1276
4   CoreFoundation                	    0x7ff80c2dee6c CFRunLoopRunSpecific + 562
5   HIToolbox                     	    0x7ff814f8d5e6 RunCurrentEventLoopInMode + 292
6   HIToolbox                     	    0x7ff814f8d34a ReceiveNextEventCommon + 594
7   HIToolbox                     	    0x7ff814f8d0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
8   AppKit                        	    0x7ff80ed18fad _DPSNextEvent + 927
9   AppKit                        	    0x7ff80ed1766a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
10  AppKit                        	    0x7ff80ed09d19 -[NSApplication run] + 586
11  libAvaloniaNative.dylib       	       0x116f15800 PlatformThreadingInterface::RunLoop(IAvnLoopCancellation*) + 128
12  ???                           	       0x128ce8909 ???
13  ???                           	       0x128ce83a9 ???
14  ???                           	       0x128ce7eb9 ???
15  ???                           	       0x128c3d970 ???
16  ???                           	       0x1271c28c7 ???
17  ???                           	       0x1264a3885 ???
18  Ryujinx                       	       0x10d332009 CallDescrWorkerInternal + 124
19  Ryujinx             

it starts to boot a game and then while loading crashes this is on macbook air specks:   
MacBook Air (13-inch, 2017)
1.8 GHz Dual-Core Intel Core i5
8 GB 1600 MHz DDR3
Intel HD Graphics 6000 1536 MB
does anyone have a solution?

**Comment by MetrosexualGarbodor** [comment]
Ryujinx cannot run on an Intel HD Graphics 6000.

**Comment by player94j** [comment]
> Ryujinx cannot run on an Intel HD Graphics 6000.
thanks i forgot to check ill just run it on my other pc
