### ISSUE TITLE
Mac default Fullscreen key must be changed

### ISSUE THREAD

**Issue by M0REKZ** [Ryujinx/Ryujinx#3981]
### What's the issue you encountered?

The F11 Key that Riujinx uses for fullscreen is already used by the mac system for the "show desktop" action, and Riujinx wont be full screen.

### How can the issue be reproduced?

Just press Fn + F11 on Mac

### Environment?

- Ryujinx version: 1.1.0 (mac-1)</br>

- System Specs:
  - OS: *macOS Ventura (13.0.1)*

**Comment by gustaf71** [comment]
On default Mac 'F11' is Show Desktop... but access that a user need to do fn + F11
When we change in System Preferences->Keyboard->Shortcuts->Mission Control-> checkbox to off
Its possible to make Ryujinx to become fullscreen with fn + F11

On Monterey the default fullscreen for application is Global + F in other words (fn + F).
In other words F11 is turn down audio and second option fn + F11 is keyboard shortcuts F11.
If the second option is already used 'Show Desktop' that is why macOS application use Global/fn + F instead.

**Comment by M0REKZ** [comment]
Sorry, with F11 i was saying fn+F11, F11 is for less sound too, ill edit that on the first comment.

> When we change in System Preferences->Keyboard->Shortcuts->Mission Control-> checkbox to off
> Its possible to make Ryujinx to become fullscreen with fn + F11

Oh, good thing to know, however i dont think all people would like to disable this thing, i would suggest to change the key to a different "Fxx", or, maybe is better to change it to something like Ctrl + F (not Fxx) to avoid weird key problems

**Comment by gustaf71** [comment]
In Monterey Global + F or fn + F is the default keyboard shortcuts for fullscreen in macOS application.
Safari has it, Mail has it and so on...
Here is the defaults https://support.apple.com/en-ae/HT201236

Global/fn + F is same as Control-Command-F at least that is how it works for me in 12.6.1

**Comment by M0REKZ** [comment]
> In Monterey Global + F or fn + F is the default keyboard shortcuts for fullscreen in macOS application. Safari has it, Mail has it and so on...

Ryujinx dont have it
