### ISSUE TITLE
Zelda BOTW crash after 1.1.407

### ISSUE THREAD

**Issue by Roromor** [Ryujinx/Ryujinx#3984]
Hello guys,

i've been playing for the last week BOTW, up until 1.1.406 no major problems. Since i updated to 1.1.410 the game keep crashing at the some spot, there's rain (idk if it's useful).

### Log file

00:00:00.035` |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.039 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.039 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.039 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.040 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.041 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.041 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x687F
00:00:00.043 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.043 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.043 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.043 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.043 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.043 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.043 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.043 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.043 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.044 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.044 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.044 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.044 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.044 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.047 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.410
00:00:00.051 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.051 |N| Application Print: CPU: AMD Ryzen 7 3700X 8-Core Processor ; 16 logical
00:00:00.051 |N| Application Print: RAM: Total 16314 MiB ; Available 11729 MiB
00:00:00.053 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.054 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:09.849 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.069 |I| Gpu : Backend Threading (Auto): True
00:00:00.273 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:00.273 |I| Application LoadApplication: Loading as XCI.
00:00:00.322 |I| Application AddAocData: Found AddOnContent with TitleId 01007EF00011F002
00:00:00.322 |W| Application AddAocData: Duplicate AddOnContent detected. TitleId 01007EF00011F002
00:00:00.326 |I| Application AddAocData: Found AddOnContent with TitleId 01007EF00011F001
00:00:00.326 |W| Application AddAocData: Duplicate AddOnContent detected. TitleId 01007EF00011F001
00:00:00.342 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.343 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001
00:00:00.343 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002
00:00:00.344 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.344 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001
00:00:00.344 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002
00:00:00.346 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.351 |I| Loader LoadExeFs: Loading rtld...
00:00:00.398 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.398 |I| Loader LoadExeFs: Loading main...
00:00:00.547 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Cafe\U-King\trunk\Game\App\Rom\NX64\Product\code\U-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Atk-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-7_3_2-Release
                   SDK MW+Microsoft+Havok_Cloth-2014_2
                   SDK MW+Microsoft+Havok-2014_2
                   SDK MW+Microsoft+Havok_Animation-2014_2
                   SDK MW+Microsoft+Havok_AI-2014_2
                   SDK MW+Microsoft+Havok_Physics2012-2014_2
00:00:00.548 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.568 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-7_3_2-Release
00:00:00.568 |I| Loader LoadExeFs: Loading sdk...
00:00:00.610 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:00.649 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.094 |I| Ptc Load: Loaded Translation Cache (size: 146945001 bytes, translated functions: 84744).
00:00:02.114 |I| Ptc Load: Loaded Profiling Info (size: 253125 bytes, profiled functions: 73373).
00:00:02.227 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.228 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.242 |I| Loader LoadNsos: Loading image 2 at 0x000000000ad6a000...
00:00:02.244 |I| Loader LoadNsos: Loading image 3 at 0x000000000b487000...
00:00:02.252 |I| ModLoader LoadCheats: Build ids found for title 01007EF00011E000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    8E9978D50BDD20B4C8395A106C27FFDE00000000000000000000000000000000
    93FF8252D975ADF07230CB86C83301C53F2804DF000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:02.252 |I| Loader LoadNca: Application Loaded: The Legend of Zelda: Breath of the Wild v1.0.0 [01007ef00011e000] [64-bit]
00:00:02.260 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.282 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.536 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD Radeon RX Vega (Vulkan v1.3.206, Driver v2.0.220)
00:00:02.544 |I| GPU.MainThread Gpu LoadShaders: Loading 3114 shaders from the cache...
00:00:06.905 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:07.825 |I| HLE.GuestThread.15 Ptc LoadTranslations: 73373 translated functions loaded
00:00:07.947 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:07.950 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:07.951 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:07.951 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:07.959 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed. 
00:00:08.888 |G| HLE.OsThread.16 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 8s
    Line: 18
    Filename: 'D:/home/Cafe/U-King/trunk/Game/Lib/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'U-King'
    Message: '0000002e'

00:00:08.889 |S| HLE.OsThread.16 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:08.889 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:08.890 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:08.890 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:08.890 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:08.922 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:08.927 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:08.941 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:08.954 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:08.996 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:08.997 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:08.997 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:08.998 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:08.999 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:08.999 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:08.999 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:09.000 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:09.027 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:09.030 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:09.030 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:09.034 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:09.064 |S| HLE.OsThread.16 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72197163296350208}
00:00:09.066 |S| HLE.OsThread.16 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:09.091 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:09.095 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:09.096 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:09.097 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:09.972 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:09.973 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:12.748 |S| HLE.OsThread.9 ServiceHid ActivateConsoleSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:12.748 |S| HLE.OsThread.9 ServiceHid InitializeSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; counter0: 4096 ; counter1: 520192}
00:00:13.087 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:13.089 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV7
00:00:13.105 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:13.106 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:13.122 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:13.157 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:13.265 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceSystemEvent: Stubbed. 
00:00:13.267 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:13.310 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:14.608 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:14.880 |S| HLE.OsThread.16 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:00:14.884 |I| HLE.OsThread.16 ServiceAm .ctor: Applet 'Error' created.
00:00:14.887 |I| HLE.OsThread.16 ServiceAm : ErrorApplet version: 0x00000000
00:00:17.350 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; _gyroscopeZeroDriftMode: Tight}
00:00:17.351 |S| HLE.OsThread.16 ServiceAm SetGamePlayRecordingState: Stubbed. {_gamePlayRecordingState: True}
00:00:17.354 |S| HLE.OsThread.9 ServiceHid StopSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:33.889 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: option
 Report: {
    "BalloonTextOnOff": 1,
    "AutoSaveOnOff": 1,
    "CameraUpDownReverse": 0,
    "CameraRLReverse": 0,
    "TextRubyOnOff": 1,
    "JumpButtonChange": 0,
    "StickSensitivity": 2,
    "GyroOnOff": 0,
    "MiniMapDirection": 0,
    "AmiiboItemOnOff": 0,
    "MainScreenOnOff": 0,
    "DisplaySpecialMode": 0,
    "TextWindowChange": 1,
    "DockInOnOff": 1,
    "ControllerType": 1,
    "AttachExtGrip": 0,
    "CtrlModeHandheldFree": 0,
    "CtrlModeHandheldExt": 0,
    "CtrlModeHandheldFullKey": 0,
    "CtrlModeHandheldHandheld": 0,
    "CtrlModeConsoleFree": 0,
    "CtrlModeConsoleExt": 0,
    "CtrlModeConsoleFull": 56588,
    "PlayTimeHandheld": 0,
    "PlayTimeConsole": 56969,
    "PlayTimeAll": 56969,
    "RomVer": 160,
    "AoCVer": 0,
    "RegionLanguage": 112,
    "AudioMono": 0,
    "AudioStereo": 0,
    "Audio5_1ch": 56969,
    "AudioOther": 0
}

00:01:05.543 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 31392334,
    "PlayTime": 56612,
    "AllPlayTime": 56989
}

00:01:30.176 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -385583197,
    "Position": 31122002,
    "PlayTime": 56637,
    "AllPlayTime": 57014
}

00:01:37.880 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 31113811,
    "PlayTime": 56644,
    "AllPlayTime": 57021
}

00:01:48.957 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 31056462,
    "PlayTime": 56655,
    "AllPlayTime": 57032
}

00:01:59.859 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 30990929,
    "PlayTime": 56666,
    "AllPlayTime": 57043
}

00:02:01.856 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 30999125,
    "PlayTime": 56668,
    "AllPlayTime": 57045
}

00:02:02.080 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 31007318,
    "PlayTime": 56669,
    "AllPlayTime": 57046
}

00:02:07.856 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 253130 bytes, profiled functions: 73374).
00:02:25.879 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -72230835,
    "Position": 31220304,
    "PlayTime": 56692,
    "AllPlayTime": 57069
}

00:02:46.875 |I| HLE.OsThread.16 ServicePrepo ProcessReport: 
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: getitem
 Report: {
    "IsHardMode": 0,
    "DisplaySpecialMode": 0,
    "MapType": 1,
    "Name": -385583197,
    "Position": 31400530,
    "PlayTime": 56713,
    "AllPlayTime": 57090
}

00:02:50.521 |I| HLE.GuestThread.37 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x000000000a07039c	main:0x206c39c	
   0x000000000a09924c	main:0x209524c	
   0x000000000a0a094c	main:0x209c94c	
   0x000000000a09d5e8	main:0x20995e8	
   0x0000000009ed89ac	main:0x1ed49ac	
   0x0000000009ee8e9c	main:0x1ee4e9c	
   0x0000000009ee8dc0	main:0x1ee4dc0	
   0x0000000009ee8d1c	main:0x1ee4d1c	
   0x000000000b7b0e88	sdk:0x329e88	
   0x000000000b7b5294	sdk:0x32e294	
   0x0000000000000000

00:02:50.527 |I| HLE.GuestThread.37 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x00000001ced56040
	X[01]:	0x00000011f021ea00 (SP:-0x0030)
	X[02]:	0x0000000000000014
	X[03]:	0x000000101240da40
	X[04]:	0x0000000000000014
	X[05]:	0x0000000000000150
	X[06]:	0x000000101107f560
	X[07]:	0x000000000000001c
	X[08]:	0xffffffffbf7acdcc
	X[09]:	0x00000000bf7acdcd
	X[10]:	0x000000000a744524
	X[11]:	0x0000000000004000
	X[12]:	0x0000000000008000
	X[13]:	0x00000010abb1e9d0
	X[14]:	0x0000000000000000
	X[15]:	0x00000010117ec0cc
	X[16]:	0x000000000ac82c20
	X[17]:	0x000000000b7aef80 (sdk:0x327f80)	=> nn::os::GetTlsValue(nn::os::TlsSlot)
	X[18]:	0x0000000000000007
	X[19]:	0x00000011f021ed30 (SP:-0x0360)
	X[20]:	0x00000010b8d93610
	X[21]:	0x000000000a61242c
	X[22]:	0x00000001ced56030
	X[23]:	0x00000010123190b0
	X[24]:	0x0000000033333333
	X[25]:	0x0000000000000002
	X[26]:	0x000000000ad3ba10
	X[27]:	0x00000010117e9798
	X[28]:	0x00000010b8d93610
	FP:	0x00000011f021ea50 (SP:-0x0080)
	LR:	0x0000000009ed5724 (main:0x1ed1724)	=> 
	SP:	0x00000011f021e9d0 (SP)
	PC:	0x0000000009ed3640 (main:0x1ecf640)	=> 

00:02:50.527 |E| HLE.GuestThread.37 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000001CED56000.
00:02:50.565 |E| HLE.GuestThread.37 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265

### Environment

- Ryujinx version: 1.1.410</br>

- Game version: 1.6.0</br>

- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 7 3700X
  - GPU: AMD Radeon RX Vega 56
  - RAM: 16GB
- Applied Mods : No

**Comment by Arucied** [comment]
I've been experiencing this as well on the steam deck. For me no matter the configuration it would crash attempting to start a new game or load a file. After wiping all saves/shader cache it would crash on the opening cutscene.

If it helps i noticed it seems to almost be time-based; with vsync off on desktop mode it would get further thanks to when the application isn't focused it seemed to run at a faster/uncapped framerate (thus it would speed through the cutscene faster); but in game mode it would only get up to the "Presents" title bit.

**Comment by Haronee** [comment]
Tested the game with update 1.6.0 on the latest Ryujinx mainline (1.1.415) using Vulkan on an RX570 using the latest AMD optional drivers (22.11.2) on Windows 10
![image](https://user-images.githubusercontent.com/53187465/205405688-ba3a2863-1ba7-4f3b-9803-670145683429.png)

Game works fine, I was able to play for over 10min without a crash.

**Comment by Arucied** [comment]
My test was from yesterday on 1.1.410, trying again today on 1.1.415 yields same results.
I was able to run it previously on system versions 14.1.2 and 15.0.0 and 15.0.1; i even swapped between the 3 with this latest update to try again. I even got the 13.2.1 seen in your screenshot just to be certain.
Memory manager mode buys me a few more seconds on software; but otherwise crashes the same. Other settings seem to have no effect.
Furthest i can get is desktop mode in which it fades to white on the opening cutscene to which it hangs and then fully crashes. All other switch applications for me are running fine; its just this one crashing.
Not sure how its running for the original poster after the last update but for the steam deck it seems to still be broken.

**Comment by gdkchan** [comment]
The Steam Deck issue has been happening for a while, I don't think it's a recent regression.

**Comment by Arucied** [comment]
Not sure, it worked for me a little over a week ago; so don't know when this issue would've started for the deck.

**Comment by Arucied** [comment]
Thought i'd add a bit of an add-on. This runs on the deck if you swap to OpenGL; Vulkan is where all the crashes occur. Unfortunately the OpenGL performance is a little....bad; so its not ideal.
I found this out by accident when reconfiguring/reinstalling things as well as trying a few extra things.

**Comment by genmatrix** [comment]
Vulkan doesn’t crash on start up with BOTW after the fix starting 1.1.469 on the Steam Deck OS. Still runs poorly though.
