### ISSUE TITLE
Ryujin closes on its own when trying to open it, not launching a game, just trying to open it

### ISSUE THREAD

**Issue by shaftbottom** [Ryujinx/Ryujinx#3986]
So my ryujinx was running smoothly and when i opened it a few minutes ago it asked if i wanted to update. I clicked yes and it did its work but now when i try to open ryujinx it just closes before it even displays the window with the emulated games. on the other window with all the text and numbers . This oart was shown in red.

00:00:00.364 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.

 \---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll

   at GLibrary.Load(Library library)

   at Gtk.Application..cctor()

   \--- End of inner exception stack trace ---

   at Gtk.Application.Init()

   at Ryujinx.Program.Main(String\[\] args) in D:\\a\\Ryujinx\\Ryujinx\\Ryujinx\\Program.cs:line 186

Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.

 \---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll

   at GLibrary.Load(Library library)

   at Gtk.Application..cctor()

   \--- End of inner exception stack trace ---

   at Gtk.Application.Init()

   at Ryujinx.Program.Main(String\[\] args) in D:\\a\\Ryujinx\\Ryujinx\\Ryujinx\\Program.cs:line 186

&#x200B;

Any idea on how i can fix this?

**Comment by MelonSpeedruns** [comment]
Redownload Ryujinx from the official website. Sometimes the program fails to update correctly and corrupts files.
