### ISSUE TITLE
[Regression]Super Smash Bros Ultimate crashes RADV

### ISSUE THREAD

**Issue by edisionnano** [Ryujinx/Ryujinx#3993]
I don't know if this is a genuine regression or a side effect but since 1.1.299 this game crashes RADV after joining a match
We have a mesa issue open however this is probably not a mesa issue
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7611

It would be nice if we at least got a hotfix to disable border color on RADV until the issue is investigated

Scarlet/Violet also crash on boot however it could be for another reason

**Comment by gaberilde** [comment]
Pokemon scarlet and smash works fine for me but im probally using different hardware to you so maybe thats why

**Comment by edisionnano** [comment]
> Pokemon scarlet and smash works fine for me but im probally using different hardware to you so maybe thats why

on RADV?

**Comment by gaberilde** [comment]
> > Pokemon scarlet and smash works fine for me but im probally using different hardware to you so maybe thats why
> 
> on RADV?

i dont know what radv is so im probally not using it

**Comment by edisionnano** [comment]
Metroid Dread also crashes when interacting with a network station
Steps to reproduce:
load up the game, start new game, go to the network station (it's directly in your path, can't miss it), and it'll crash as soon as the text box should show up

I don't know if it's border color that broke it

Pokemon Scarlet and Violet will hang the whole system but only on Vega iGPUs

**Comment by TSRBerry** [comment]
Could you fill the template out? Then I could also add the proper labels.

**Comment by kode54** [comment]
I reproduced the network station issue, without any dialog, just entering a network station from a room door. Reverting the border color commit removes the crash.

**Comment by DadSchoorse** [comment]
please test #4116.

**Comment by edisionnano** [comment]
BOTW crashes too...
