### ISSUE TITLE
GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?

### ISSUE THREAD

**Issue by RandomLegend** [Ryujinx/Ryujinx#3998]
## Bug Report

Getting GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?

![image](https://user-images.githubusercontent.com/38812603/205437240-ca2dd295-27e3-4433-ba66-83d074857e02.png)

### Log file
https://pastebin.com/CTJDH0ar

### Environment?

- Ryujinx version: 1.1.415</br>

- Game version: 1.1.0</br>
- 
- System Specs:
  - OS: *Garuda Linux / Kernel: 6.0.10-zen2-1-zen*
  - CPU: *Ryzen 5 2600X*
  - GPU: *NVidia RTX3070*
  - RAM: *6GiB*
- Applied Mods : [ No ]

**Comment by edisionnano** [comment]
Looks like a warning safe to ignore

**Comment by RandomLegend** [comment]
wanted to post it in case it's something with an effect on performance.

**Comment by MetrosexualGarbodor** [comment]
There is barely any information at all on this issue. If this is happening in a given game, please report it in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues). Thank you.
