### ISSUE TITLE
Pokemon Violet naming pokemon crash

### ISSUE THREAD

**Issue by Latias888** [Ryujinx/Ryujinx#4001]
### What's the issue you encountered?

Naming pokemon after catching them causes emulator to crash

Attempted multiple times to name captured pokemon and emulator shuts down upon pressing "ok"

No changes to Ryujinx were made.

### How can the issue be reproduced?

catch a pokemon and give a nickname

- Encounter wild pokemon
- Catch it
- Nickname on ryujinx program keyboard
- Press Ok

### Log file

[Ryujinx_1.1.415_2022-12-03_10-06-21.log](https://github.com/Ryujinx/Ryujinx/files/10146732/Ryujinx_1.1.415_2022-12-03_10-06-21.log)

### Environment?

- Ryujinx version: 1.1.415
- Game version: 1.1.0
- System Specs:
  - OS: Win 10
  - CPU: i9-9900
  - GPU: Nvidia Geforce rtx 2080
  - RAM: 63GiB
- Applied Mods : No

### Additional context?

N/A

**Comment by TSRBerry** [comment]
You can probably fix this issue by using a newer firmware than 1.0.0
