### ISSUE TITLE
GUI not working / buttons cannot be clicked

### ISSUE THREAD

**Issue by animalcrossingfriendo** [Ryujinx/Ryujinx#4014]
### What's the issue you encountered?
Was attempting to start up ryujinx, but the GUI didn't allow me to click on anything</br>
I did try deleting ryujinx and basically reinstalling it, but the GUI still is not responsive

### How can the issue be reproduced?

Not quite sure how to explain the reproducable issue, besides
- open up ryujinx
- find buttons are not working / gui is not responding to interaction
- try to restart it, update it, etc
- still not working

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.423</br>
- Game version: N/A</br>
- System Specs: Windows 10 with an AMD Ryzen 7 1700 Eight-Core processor and 16gb of installed RAM

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by MetrosexualGarbodor** [comment]
This is not an emulator issue, please join discord for help.
