### ISSUE TITLE
CAN´T INSTALL UPDATES

### ISSUE THREAD

**Issue by lapocha5** [Ryujinx/Ryujinx#4015]
### What's the issue you encountered?

Hello, i´m triying to update mario plus rabbids spark of hope and AC NH and the emulator shows this:
"Aplication CreateErrorDialog: The specified files does not contain an update for the selected title!"

### How can the issue be reproduced?

Trying to install the update for those games.

### Environment?

- Ryujinx version: 1.1.423

- Game version: 1.1.20</br>

- System Specs:
  - OS: Windows 11
  - CPU: AMD RYZEN 5 5600G
  - GPU: RADEON XR 6600 8GB
  - RAM: 16GB
- Applied Mods : No.

**Comment by MetrosexualGarbodor** [comment]
This is not an emulator issue, please join discord for help.
