### ISSUE TITLE
An issue with controller

### ISSUE THREAD

**Issue by lennondong** [Ryujinx/Ryujinx#4019]
### What's the issue you encountered?

when run the game <need for speed hot pursuit remastered>, it showed the message followerd.
In fact I have setted the player1 with an  input device but the message still appeared like this.

-----------

Application requests exactly 1 players(s) with:
Types:ProController,Handheld,JoyonPair
PLAYERS:Player1,Player2...
Please open settings and reconfigure input now or press close.

-----------

### How can the issue be reproduced?

1. run the ryujinx for mac with M1 cpu.
2. run the game <need for speed hot pursuit remastered>

### Log file

I didn't find the log file in ryujinx folder.

### Environment?

- Ryujinx version: 1.1.0</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.2</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS:macOS Monterey 12.5.1
  - CPU: Apple M1
  - GPU: none
  - RAM: 16GB
- Applied Mods : [ Yes (Which ones) / No ]
![Snip20221205_1](https://user-images.githubusercontent.com/3203702/205549448-5c6192a2-b398-41ae-9b11-d4a4d0c10517.png)

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MetrosexualGarbodor** [comment]
Do as it asks.

**Comment by lennondong** [comment]
![Snip20221205_2](https://user-images.githubusercontent.com/3203702/205549795-50b55e59-3ef0-424f-93a7-e0ae44286232.png)
