### ISSUE TITLE
[Bug Report] Front Mission broken upscaling

### ISSUE THREAD

**Issue by NineKain** [Ryujinx/Ryujinx#4023]
Game is pretty broken/blurry at above 1x

![image](https://user-images.githubusercontent.com/72826232/205673620-5a3ec35d-0ea7-40dc-b7a8-09b3999754ff.png)

[Ryujinx_1.1.426_2022-12-05_16-17-00.log](https://github.com/Ryujinx/Ryujinx/files/10155412/Ryujinx_1.1.426_2022-12-05_16-17-00.log)

**Comment by MetrosexualGarbodor** [comment]
Please post about this in #1488.
