### ISSUE TITLE
Regression: Xenoblade Chronicles: Definitive Edition - Missing Textures

### ISSUE THREAD

**Issue by Oxidela** [Ryujinx/Ryujinx#4036]
### What's the issue you encountered?

After upgrading to v1.1433 (prior was three versions back):

- Vertical scan lines appear in the save/load menu thumbnails
- Some open world textures are completely black 

### How can the issue be reproduced?

View main menu with saves, or anywhere in the over world.

### Log file

N/A

### Environment?

Settings where not changed between upgrades:

- Game patch version 1.1.2
- VSync on
- PPTC checked
- Multithreading On
- Vulkan
- Enabled Shader Cache
- Enabled Micro HLE

### Additional context?

Issues where not present in yesterday's releases.

![ryujinx_capture_2022-12-05_18-32-21](https://user-images.githubusercontent.com/93446756/205796660-13e050e3-8da9-4fd0-a2b1-8c99d0e7098e.png)

**Comment by MetrosexualGarbodor** [comment]
Can confirm. 1.1.429:
![image](https://user-images.githubusercontent.com/79612681/205800562-abac6a0a-a3ab-4f61-8928-c83aacab1999.png)
![image](https://user-images.githubusercontent.com/79612681/205800676-ec0aa3ae-ed22-406c-ae40-ddd534751985.png)

1.1.430:
![image](https://user-images.githubusercontent.com/79612681/205802040-476591ba-e67e-49e6-9db0-f1258b71066d.png)
![image](https://user-images.githubusercontent.com/79612681/205802783-3b26fbde-57dc-479f-b79a-a3d805915e65.png)
