### ISSUE TITLE
vulcan crash. pokemon violet

### ISSUE THREAD

**Issue by bonypoke** [Ryujinx/Ryujinx#4040]
when i change the grafic setting to vulcan it crash.. anyone help ? 
[Ryujinx_1.1.434_2022-12-06_14-17-30.log](https://github.com/Ryujinx/Ryujinx/files/10163647/Ryujinx_1.1.434_2022-12-06_14-17-30.log)
[Ryujinx_1.1.434_2022-12-06_15-01-52.log](https://github.com/Ryujinx/Ryujinx/files/10163648/Ryujinx_1.1.434_2022-12-06_15-01-52.log)
[Ryujinx_1.1.434_2022-12-06_14-11-11.log](https://github.com/Ryujinx/Ryujinx/files/10163649/Ryujinx_1.1.434_2022-12-06_14-11-11.log)

**Comment by CrusadingNinja** [comment]
Your GPU Drivers are extremely outdated. Update them - both the Nvidia dedicated and the Intel integrated.

Also, github is not for support requests. Come to the [discord server](https://discord.gg/ryujinx) for support.
