### ISSUE TITLE
Separate 720p and 1080p video setting

### ISSUE THREAD

**Issue by cwscws** [Ryujinx/Ryujinx#4046]
To get better performance on M1 it would be nice to have separate 720p and 1080p settings.

And Command+Q does not quit the emulator.

#### Overview:
- [ Include the basic, high-level concepts for this feature here. ]

#### Smaller Details: 
- [ These may include specific methods of implementation etc. ]

#### Nature of Request:  
[ Remove all that do not apply to your request. ]
- Addition
  - [ Ex: Addition of certain original features or features from other community projects. ]
  - [ If you are suggesting porting features or including features from other projects, include what license they are distributed under and what, if any libraries those project use. ]
- Change
- Removal
  - [Ex: Removal of certain features or implementation due to a specific issue/bug or because of low quality code, etc.]

### Why would this feature be useful?
[ If this is a feature for an end-user, how does it benefit the end-user? ]</br>
[ If this feature is for developers, what does it add to Ryujinx that did not already exist? ]

**Comment by TSRBerry** [comment]
Could you please properly fill this template out?

**Comment by LukeWarnut** [comment]
Handheld and docked mode are already 720p and 1080p respectively.

**Comment by TSRBerry** [comment]
I'm closing this as this already exists. If you are talking about something different feel free to properly fill out the template and reopen this issue.
