### ISSUE TITLE
Pokemon Violet, E-nigma exam bug (Mengano Calleja)

### ISSUE THREAD

**Issue by udrux** [Ryujinx/Ryujinx#4055]
When i reach e-nigma's gym exam the game bugs and I can't search for Mengano Calleja (professor), any button of the controller works in order to do it.

**Comment by EmulationFanatic** [comment]
Game-specific issues should be posted on their respective entries on [the compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List/issues). However I'm fairly certain this is a fixable issue; please come to Discord for support.
