### ISSUE TITLE
(Mac M1) No sound in games

### ISSUE THREAD

**Issue by Wolvpak** [Ryujinx/Ryujinx#4061]
### What's the issue you encountered?

Tested on multiple games, always the same issue: no sound or music

### Environment?

- Ryujinx version: 1.1.0</br>

[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *Mac OS Ventura 13.0.1*

**Comment by EmulationFanatic** [comment]
Change the audio backend to SDL2
