### ISSUE TITLE
Xenoblade Crash on Linux

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#4065]
### What's the issue you encountered?

It looks like Xenoblade Chronicle 2 crash after the emulator Starts "AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer". And Xenoblade Chronicle 3 seems to crash after a boot loading screen and can hear some sound from the game. Xenoblade Chronicle 3 crash's around the time its reading the save from the looks of it.

These only consist with Vulkan. when I use Opengl The games boot and go's in-game.

### Log file
Xenoblade Chronicle 2
[Xc2-Vulkan.log](https://github.com/Ryujinx/Ryujinx/files/10180239/Xc2-Vulkan.log)

Xenoblade Chronicle 3
[Xc3-Vulkan.log](https://github.com/Ryujinx/Ryujinx/files/10180553/Xc3-Vulkan.log)

### Environment?

- Hardware: Steam Deck

- Ryujinx version: 1.1.445</br>

Xenoblade Chronicle 2
- Game version: 2.0.2</br>
- System Specs:
  - OS: *SteamOS Holo 3.3.2*
  - CPU: *AMD Zen 2 (4-core, 8-thread @ 2.4GHZ – 3.5Ghz)*
  - GPU: *RDNA 2 (8 compute units @ 1GHz – 1.6GHz)*
  - RAM: *16GB LPDDR5*
- Applied Mods : No

Xenoblade Chronicle 3
- Game version: 1.2.0</br>
- System Specs:
  - OS: *SteamOS Holo 3.3.2*
  - CPU: *AMD Zen 2 (4-core, 8-thread @ 2.4GHZ – 3.5Ghz)*
  - GPU: *RDNA 2 (8 compute units @ 1GHz – 1.6GHz)*
  - RAM: *16GB LPDDR5*
- Applied Mods : No

### Additional context?

I have also had input from a friend that use's a AMD GPU that he encountered a similar issue.
Sadly There really isn't much info to go off of in the logs, I have tried deleting pptc and shader cache but neither of these gave any meaningful result

I do know My Nvidia system does not encounter these issues. So I presume it may have something to do with mesa

**Comment by edisionnano** [comment]
Can you try reverting the border color pr? Does it happen on both flatpak and binary?

**Comment by B3astTech** [comment]
I used Binary but I highly doubt that the packaging gives any meaningful difference in it

**Comment by B3astTech** [comment]
Are you referring to the build 1.1.299 when it's was merged?

**Comment by edisionnano** [comment]
> Are you referring to the build 1.1.299 when it's was merged?

Yeah revert that and build

**Comment by B3astTech** [comment]
Sounds good

**Comment by B3astTech** [comment]
![image](https://user-images.githubusercontent.com/45114656/206531835-61f08e0e-614e-4339-829e-8a2622c6f3c4.png)

it works on the version before the build 1.1.299

**Comment by edisionnano** [comment]
> ![image](https://user-images.githubusercontent.com/45114656/206531835-61f08e0e-614e-4339-829e-8a2622c6f3c4.png)
> 
> it works on the version before the build 1.1.299

No no, build latest master, just revert this commit

**Comment by B3astTech** [comment]
[Ryujinx_1.1.299_2022-12-08_12-22-05.log](https://github.com/Ryujinx/Ryujinx/files/10188423/Ryujinx_1.1.299_2022-12-08_12-22-05.log)

Sorry don't really want to mess with reverting a pr right now. I just booted 1.1.299 and sent the log

**Comment by B3astTech** [comment]
It does infact match the issue with latest mainline build

**Comment by B3astTech** [comment]
[Ryujinx_1.1.298_2022-12-08_12-28-34.log](https://github.com/Ryujinx/Ryujinx/files/10188471/Ryujinx_1.1.298_2022-12-08_12-28-34.log)

XC3 Also gives a better log on ths build and progress's further by a bit

**Comment by edisionnano** [comment]
> [Ryujinx_1.1.299_2022-12-08_12-22-05.log](https://github.com/Ryujinx/Ryujinx/files/10188423/Ryujinx_1.1.299_2022-12-08_12-22-05.log)
> 
> Sorry don't really want to mess with reverting a pr right now. I just booted 1.1.299 and sent the log

The PR in question is an one-liner, just undo the change manually by editing the source file with a text editor

**Comment by B3astTech** [comment]
Since you are insistent on it I did so.

![image](https://user-images.githubusercontent.com/45114656/206825494-17e69b9a-61ac-481a-b2c2-996c28d2bccb.png)

It does in fact work when you remove the line of code from mainline build.

**Comment by MK73DS** [comment]
Any updates on this? I'm still getting a crash when using 1.1.458, right after the loading screen in XC3.

System Specs:
- Operating System: Arch Linux
- Kernel Version: 6.0.12-arch1-1 (64-bit)
- Graphics Platform: X11
- Processors: 16 × AMD Ryzen 7 6800HS Creator Edition
- Memory: 13.3 Gio of RAM
- Graphics Processor: AMD Radeon Graphics 680M

**Comment by edisionnano** [comment]
> Any updates on this? I'm still getting a crash when using 1.1.458, right after the loading screen in XC3.
> 
> System Specs:
> 
>     * Operating System: Arch Linux
> 
>     * Kernel Version: 6.0.12-arch1-1 (64-bit)
> 
>     * Graphics Platform: X11
> 
>     * Processors: 16 × AMD Ryzen 7 6800HS Creator Edition
> 
>     * Memory: 13.3 Gio of RAM
> 
>     * Graphics Processor: AMD Radeon Graphics 680M

A pr was opened to address this like 5 minutes ago

**Comment by MK73DS** [comment]
Sorry, the pr didn't mention this issue so I had no idea. Thank you very much!

**Comment by B3astTech** [comment]
https://github.com/Ryujinx/Ryujinx/pull/4116

Does in fact fix Xenoblade Chronicle 2 and does allow Xenoblade Chronicle 3 to crash.

End of log crash
`
00:01:04.771 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan1 waitSemaphores, ReadOnlySpan1 waitDstStageMask, ReadOnlySpan1 signalSemaphores)
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl()
   at Ryujinx.Graphics.GAL.Multithreading.Commands.SetRenderTargetsCommand.Run(SetRenderTargetsCommand& command, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_74(Span1 memory, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop)
   at Ryujinx.Ui.RendererWidgetBase.Render() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx/Ui/RendererWidgetBase.cs:line 401
   at System.Threading.Thread.StartCallback()
`

Log From This Pull Request

[Ryujinx_1.1.08080b5c_2022-12-13_19-06-14.log](https://github.com/Ryujinx/Ryujinx/files/10223350/Ryujinx_1.1.08080b5c_2022-12-13_19-06-14.log)

It's one Step closer to getting there but its not playable with this pr alone

**Comment by MetrosexualGarbodor** [comment]
Fixed by #4116
