### ISSUE TITLE
Metroid Dread crashes RADV driver on some shaders, massively fails Vulkan validation layers

### ISSUE THREAD

**Issue by kode54** [Ryujinx/Ryujinx#4072]
### What's the issue you encountered?

I experience an issue where certain shaders, such as the one which first gets cached when Samus is submerged in lava without the Gravity Suit acquired. I also took the liberty of running the game at my current save with the Vulkan Validation Layers inserted into the process, and it spewed out a huge log of nonstop validation errors, which I've included in a stdout log from the emulator.

### How can the issue be reproduced?

1. Install Metroid Dread base game
2. Install patch 2.1.0
3. Install the attached save data
4. Run the emulator with `vulkan-validation-layers` installed and `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation` in the environment, logging stdout to a log file
5. Load the save game in the game with a sufficient shader cache
6. Move around assuming it loads

### Log file

Plain run: [ryujinx.log.gz](https://github.com/Ryujinx/Ryujinx/files/10185210/ryujinx.log.gz)
Run which leads to a room which crashes RADV, but doesn't crash AMDGPU Pro: 
[ryujinx.2.log.gz](https://github.com/Ryujinx/Ryujinx/files/10185298/ryujinx.2.log.gz)

### Environment?

- Ryujinx version: 1.1.450-1
- Game version: 2.1.0
- System Specs:
  - OS: Arch Linux, linux-tkg-cfs 6.1.rc8-272
  - CPU: Ryzen R7 2700
  - GPU: Radeon RX 480 8GB
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:
I am running `vulkan-validation-layers` 1.3.231.1-1, and the game only runs past the crashing shaders if I use AMDGPU Pro Vulkan driver, not if I use the open source RADV, regardless of whether I use the default ACO or switch to LLVM.

Attaching save file: 
[metroid_dread_save.tar.gz](https://github.com/Ryujinx/Ryujinx/files/10185306/metroid_dread_save.tar.gz)

Crash from this save occurs by loading, dropping down into the vertical room below the elevator, blasting the wall to the right, navigating downward, and to the left, and entering the previously entered Network Room. Crash on RADV occurs the instant the room transition begins, whereas AMDGPU-Pro loads the room instantly.

**Comment by kode54** [comment]
Reverting #3751 fixes the crash with RADV. May be worth looking into those validation layer errors, though.

**Comment by DadSchoorse** [comment]
Ryujinx doesn't use `VkPhysicalDeviceCustomBorderColorFeaturesEXT` to enable the customBorderColors feature. So radv never allocated the border color buffer object and crashes when creating a sampler with custom border colors.

**Comment by DadSchoorse** [comment]
please test #4116

**Comment by kode54** [comment]
Fixed. No more crash.
