### ISSUE TITLE
[Bug Report] DQ Builders Stutter

### ISSUE THREAD

**Issue by NineKain** [Ryujinx/Ryujinx#4098]
### What's the issue you encountered?

Dragon Quest Builders has horrendous frametimes, the game stutters heavily

### How can the issue be reproduced?

Open the game and play for a while, move around and the camera too

### Log file

[Ryujinx_1.1.461_2022-12-11_16-10-06.log](https://github.com/Ryujinx/Ryujinx/files/10202491/Ryujinx_1.1.461_2022-12-11_16-10-06.log)

### Environment?

- Ryujinx version: 1.1.461</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU: 5600x
  - GPU: 3060ti
  - RAM: 16gb
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MutantAura** [comment]
Please report game-specific issues on the relevant compatibility page: https://github.com/Ryujinx/Ryujinx-Games-List/issues/59
