### ISSUE TITLE
BLACK SCREEN - MARIO PLUS RABBIDS SPARKS OF HOPE 

### ISSUE THREAD

**Issue by lapocha5** [Ryujinx/Ryujinx#4101]
### What's the issue you encountered?
Hello, the screen is all black when i try to play with resolution of x2 (1440p/2160p)
It doesnt happen all the time but 90% is right.

### How can the issue be reproduced?
Start the game with that resolution, press A with the logo and voila.

### Environment?

- Ryujinx version: 1.1.461>
- Game version: 1.1.20</br>
- System Specs:
  - OS: *Windows 11*
  - CPU: *Ryzen 5 5600g*
  - GPU: *Radeon XR 6600*
  - RAM: *16GB*
- Applied Mods : NO

**Comment by GamerzHell9137** [comment]
This is not something to be reported here. Go to the compatibility list github and to the specific game.

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues on the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List). This one in particular has already been reported as well.
