### ISSUE TITLE
Unreal Engine 4 games flickering on AMD GPUs

### ISSUE THREAD

**Issue by dante3732** [Ryujinx/Ryujinx#4104]
### What's the issue you encountered?
Zones flicker on the screen.

### How can the issue be reproduced?
Just start game. It happened in Densha De Go, Shin Megami Tensei V, Crisis Core - FINAL FANTASY VII– REUNION. Same on Opengl and Vulkan.

### Log file
[Ryujinx_1.1.461_2022-12-12_12-02-11.log](https://github.com/Ryujinx/Ryujinx/files/10206368/Ryujinx_1.1.461_2022-12-12_12-02-11.log)

### Environment?
- Ryujinx version: 1.1.461
- Game version: 1.0.0
- System Specs:
  - OS: Windows 11
  - CPU: R5 3600
  - GPU: AMD RX Vega 64
  - RAM: 16GiB
- Applied Mods : No

### Additional context?
https://user-images.githubusercontent.com/66036249/207003330-fc569b1b-adf3-4410-a4ed-23cd720a216d.mp4

**Comment by dante3732** [comment]
Same on Rx 580 https://youtu.be/Mz28A-mcxts?t=67

**Comment by aarno97** [comment]
Having the same issue on MacBook Pro 16" (2019) with AMD Radeon Pro 5300M

**Comment by dante3732** [comment]
By the way, I have checked on Linux for a long time with mesa driver and it was the same there. I don't think anything has changed, but at the moment I don't have the opportunity to check again.

**Comment by animatedgoshawk** [comment]
Same issue on the same platform as aarno97 (MBP 16 with AMD 5300M).

Here's a log with debugging enabled: 

[Ryujinx_ 1.1.0-macos1_2022-12-23_03-19-43.log](https://github.com/Ryujinx/Ryujinx/files/10294387/Ryujinx_.1.1.0-macos1_2022-12-23_03-19-43.log)

**Comment by JRR-33** [comment]
I also have crashes with AMD Radeon PRO 5300 GPU... Games are running bug screen flickers, and games crash when action start (I can see menu screens and introduction videos). So it must be a problem of graphic compatibility with AMD cards... Is there any configuration or update that can fix it ?
