### ISSUE TITLE
[Feature Request] Progress bar for disk shader cache re-packing

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#4105]
#### Overview:

- Loading bar for the shader re-pack to disk stage of recompilation.

#### Smaller Details: 

- After the "Compiling shaders" loading bar a new bar should start with something like "Packaging shaders:". 
- Alternatively make this process part of the same bar as the compilation, this would slow it down but all be within one loading bar.

#### Nature of Request:  

- Addition/Change depending on implementation

### Why would this feature be useful?

Currently it appears that Ryujinx has frozen or hung when a large amount of shaders are being recompiled after a shader cache bump or driver update. It can take up to 15 minutes for titles such as XC3 and SSBU and as such probably needs some sort of indicator to the user that _something_ is still happening.

This screen was visible for over 10 minutes with no indication anything was happening:
![image](https://user-images.githubusercontent.com/44103205/207030999-738e422e-a0c5-46b6-8438-8d52964f6385.png)

Log only reads:
`00:02:27.217 |I| GPU.MainThread Gpu LoadShaders: Rebuilding 15886 shaders...` and is static the whole time.

**Comment by laernumoretz** [comment]
Concur.  

I ended up right on this page wondering the exact same thing thats posted here.   Coincidentally for ssbu

**Comment by Rahul190299** [comment]
So this issue is closed or still open
