### ISSUE TITLE
Legend of Zelda BOTW - Screen Goes White

### ISSUE THREAD

**Issue by jradut** [Ryujinx/Ryujinx#4112]
As soon as I load up the game and move around the screen goes white except for the map and icons. I can open the menu and see it fine. Also sometime the colors go green, yellow then white. 

BOTW 1.60
Ryujinx 1.1.468
Mods - Cheats 
![Screenshot 2022-12-12 171016](https://user-images.githubusercontent.com/24232393/207201538-23cad99e-80f6-4788-8c7c-f20d567ac19c.png)

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/86

**Comment by MetrosexualGarbodor** [comment]
Please post this in the compatibility entry linked above and include a log. Thank you.
