### ISSUE TITLE
Change language doesn't work in Harukana Toki no Naka de 7

### ISSUE THREAD

**Issue by Rosabis** [Ryujinx/Ryujinx#4118]
## Bug Report
[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]
Change language doesn't work in Harukana Toki no Naka de 7
### What's the issue you encountered?
[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]
Change language doesn't work in Harukana Toki no Naka de 7
### How can the issue be reproduced?
[ Include a detailed step by step process for recreating your issue. ]
1.Change system region to Chinese
2.Change system language to Chinese
3. The game still show Japanese,instead of Chinese.
### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]
[Ryujinx_1.1.468_2022-12-14_13-08-07.log](https://github.com/Ryujinx/Ryujinx/files/10224498/Ryujinx_1.1.468_2022-12-14_13-08-07.log)
### Environment?

- Ryujinx version: 1.0.X</br>
[ Replace X's with the Ryujinx version at time of crash. ]
1.1.468
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
1.0.2
- System Specs:
  - OS: *(e.g. Windows 10)*Windows 8.1
  - CPU: *(e.g. i7-6700)*i5-4300u
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GiB)*16iB
- Applied Mods : [ Yes (Which ones) / No ]No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MutantAura** [comment]
Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues
Join the discord for further support queries: https://discord.gg/ryujinx
