### ISSUE TITLE
Ikaruga not properly rendering at gameplay sections

### ISSUE THREAD

**Issue by mdsmendes94** [Ryujinx/Ryujinx#4122]
## Bug Report

![ryujinx_capture_2022-12-14_15-38-37](https://user-images.githubusercontent.com/89781294/207684887-9a4ca7ea-e959-4750-8dbd-6fa171b94f59.png)

### What's the issue you encountered?

Game doesn't properly render at gameplay sections.

### How can the issue be reproduced?

1. load game
2. 1 player mode
3. arcade mode
4. normal difficulty

After that the gameplay sections will start, you can control your ship but can't see enemies and your ship.  You can see the attacks though.
### Log file

[Ryujinx_1.1.468_2022-12-14_15-37-13.log](https://github.com/Ryujinx/Ryujinx/files/10230707/Ryujinx_1.1.468_2022-12-14_15-37-13.log)

### Environment?

- Ryujinx version: Ryujinx_1.1.468
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.2
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: WINDOWS 11 PRO 22H2
  - CPU: RYZEN 3550H
  - GPU: GTX 1650 MOBILE
  - RAM: 16GiB
- Applied Mods : no

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by EmulationFanatic** [comment]
Game-specific issues should be posted on their respective entries on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List/issues). Thank you!

**Comment by EmulationFanatic** [comment]
Also, before you do post on the game compatibility list, did you confirm the issue still occurs on default settings (anisotropic filtering set to Auto)?

**Comment by mdsmendes94** [comment]
> Game-specific issues should be posted on their respective entries on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List/issues). Thank you!
Ok, sorry.

> Also, before you do post on the game compatibility list, did you confirm the issue still occurs on default settings (anisotropic filtering set to Auto)?
Updated Ryujinx to  1.1.470 and tried setting the anisotropic filtering set to Auto, same issue.
Will update there on the game compatibility list.

**Comment by EmulationFanatic** [comment]
https://github.com/Ryujinx/Ryujinx/pull/4123 will fix it anyway.

**Comment by mdsmendes94** [comment]
Thanks for the update!
