### ISSUE TITLE
Super Mario Odyssey crashes on NVIDIA OpenGL Linux

### ISSUE THREAD

**Issue by emeliagit** [Ryujinx/Ryujinx#4126]
## Bug Report

After a couple of seconds, Super Mario Odyssey crashes on NVIDIA GPUs using OpenGL on Linux

### What's the issue you encountered?

After starting a new game, there are few issues for a couple seconds (other than shader compilation stutter, of course), until it crashes, usually about 15-30 seconds after the game loads. 
I did not make any changes to Ryujinx, I used default settings, though on OpenGL.

### How can the issue be reproduced?

1) On NVIDIA GPU on GNU+Linux, open Ryujinx
2) Start Super Mario Odyssey
3) Play for 15-30 seconds, then it should crash

### Log file

[Crashdump.txt](https://github.com/Ryujinx/Ryujinx/files/10237841/Crashdump.txt)

### Environment?

- Ryujinx version: 1.1.470</br>
- Game version: 1.3.0</br>
- System Specs:
  - OS: *(Nobara Linux)*
  - CPU: *(Intel Core i7 10875H)*
  - GPU: *(NVIDIA GeForce RTX 2070 - latest available drivers on Nobara)*
  - RAM: *(16 GiB DDR4 2933 MT/s CL21)*
- Applied Mods : [ No ]

### Additional context?

Happens on multiple peoples' machines, including my own.

**Comment by TSRBerry** [comment]
This is not a Ryujinx log.

**Comment by edisionnano** [comment]
> This is not a Ryujinx log.

Ryujinx's log file doesn't contain any useful info since this is a native crash. The attached file is core dump log.

**Comment by edisionnano** [comment]
Reopen
