### ISSUE TITLE
system.NotImplementedException: Framebuffer configuration couldn't be selected and fallback not implemented

### ISSUE THREAD

**Issue by martinlindhe** [Ryujinx/Ryujinx#4133]
## Bug Report

I am testing Ryujinx on a unusual setup:

- I use the weak and integrated graphics of the i12900K called "Intel UHD 770".
- I run Arch linux and Wayland

### What's the issue you encountered?

Ryujinx crashes directly on game load with the following exception:

```
(Ryujinx:517623): Gdk-CRITICAL **: 14:58:39.006: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
00:00:00.642 |E| Application : Unhandled exception caught: System.NotImplementedException: Framebuffer configuration couldn't be selected and fallback not implemented!
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in /home/m/dev/ryujinx-git/src/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 47
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in /home/m/dev/ryujinx-git/src/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 34
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

[ Did you make any changes related to Ryujinx itself? ]

- Compared to the AUR version in Arch, I compiled the Debug configuration instead to get a better crash.

### How can the issue be reproduced?

On arch:

* install ryujinx-git from AUR   # installs a release build from git head
```
$ gdb Ryujinx

(gdb) r
(gdb) handle SIG34 noprint      # allow and ignore SIG34 
(gdb) c
```

* chose OpenGL
* install firmware, load a game.
* get crash

### Log file

See attached.
[Ryujinx_1.0.0-dirty_2022-12-16_14-58-05.log](https://github.com/Ryujinx/Ryujinx/files/10246330/Ryujinx_1.0.0-dirty_2022-12-16_14-58-05.log)

### Environment?

- Ryujinx version: git master commit 5a085cba0fe15b8f4946ab328887a063afe3a147</br>

- Game version: Super Mario Odyssey 1.0 (no updats installed)</br>

- System Specs:
  - OS: Arch Linux
  - CPU: i9-12900K
  - GPU: Intel UHD 770 (integrated)
  - RAM: 64 GiB
- Applied Mods :  No

**Comment by piplup55** [comment]
you need to start ryujinx with `GDK_BACKEND=x11`

**Comment by martinlindhe** [comment]
> you need to start ryujinx with `GDK_BACKEND=x11`

Indeed. This works!

I got another crash now, but that is a separate issue.
