### ISSUE TITLE
Bug Report : Mario 3D All-Stars (When playing Mario 64, locks up if you press the "-" button to bring up a menu.

### ISSUE THREAD

**Issue by TomTurbine** [Ryujinx/Ryujinx#4139]
### What's the issue you encountered?

If you play "Mario 3D All-Stars and choose to play Mario 64. The game itself seems to run fine but the moment you hit the minus button to bring up the menu the game goes dark and the menu never loads. Ryujinx doesn't crash out until tell it to end emulation, it just stays frozen at that screen where the menu is supposed to come up.

### How can the issue be reproduced?

Start up the game, start Mario 64, and either when the Princess is still talking or anytime afterwards just hit the minus button to cause the lock.

### Environment?

- Ryujinx version: 1.1.476
- Game version: Updated to version 1.1.1

- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 5900X
  - GPU: NVIDIA RTX 2080
  - RAM: 32GB
- Applied Mods : None

### Additional context?

Edit: Just tried it under Yuzu and it behaves in exactly the same way, Was about to post it there as well but it looks like they already have extensive bug reports on this game.

I compressed my log file, it was 54MB uncompressed which was too big, wish my other stuff compressed this well.
[Ryujinx_1.1.476_2022-12-16_23-22-43.zip](https://github.com/Ryujinx/Ryujinx/files/10250897/Ryujinx_1.1.476_2022-12-16_23-22-43.zip)

**Comment by MutantAura** [comment]
Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues
Join the discord for further support queries: https://discord.gg/ryujinx
