### ISSUE TITLE
Apple Intel Silicon crash

### ISSUE THREAD

**Issue by mrisso** [Ryujinx/Ryujinx#4148]
Hello,

I've installed the new version of Ryujinx for MacOS with all the dependencies installed as well. I'm using version 15.0.0 of firmware and keys. Still, when I try to open my game, the app crashes on load screen. I'll post part of the error report below but since it is too long (22k lines) I'll upload the file with the full report as well: [report.txt](https://github.com/Ryujinx/Ryujinx/files/10256852/report.txt)
 
> -------------------------------------
> Translated Report (Full Report Below)
> -------------------------------------
>
> Process:               Ryujinx [15032]
> Path:                  /Applications/Ryujinx.app/Contents/MacOS/Ryujinx
> Identifier:            org.ryujinx.Ryujinx
> Version:               1.1 (1.1.0)
> Code Type:             X86-64 (Native)
> Parent Process:        launchd [1]
> User ID:               501
>
> Date/Time:             2022-12-19 07:18:36.7960 +0000
> OS Version:            macOS 12.6.2 (21G320)
> Report Version:        12
> Anonymous UUID:        96B8469D-0510-3C7E-CDDE-C3C25B169072
>
>
> Time Awake Since Boot: 4400 seconds
>
> System Integrity Protection: enabled
>
> Crashed Thread:        59
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
>
> Application Specific Information:
> abort() called

The end has hardware info:

>Model: MacBookAir7,2, BootROM 476.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 1,6 GHz, 8 GB, SMC 2.27f2
>Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
>Display: Color LCD, 1440 x 900 (Widescreen eXtended Graphics Array Plus), Main, MirrorOff, Online
>Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80CE, 0x4B3445364533303445452D45474345000000
>Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80CE, 0x4B3445364533303445452D45474345000000
>AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
>AirPort: 
>Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
>Network Service: Wi-Fi, AirPort, en0
>Serial ATA Device: APPLE SSD SM0256G, 251 GB
>USB Device: USB30Bus
>USB Device: BRCM20702 Hub
>USB Device: Bluetooth USB Host Controller
>Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

Does anybody know what it could be?

**Comment by MetrosexualGarbodor** [comment]
Please join [discord](https://discord.gg/ryujinx) for help. Thank you.
