### ISSUE TITLE
Dialogue box/bcat save directory creation regression

### ISSUE THREAD

**Issue by B-Crolly** [Ryujinx/Ryujinx#4149]
## Bug Report

Dialogue box/bcat save directory creation regression

If I'm missing anything or formatted improperly please let me know, this is my first bug report, thanks

### What's the issue you encountered?

when attempting to open the bcat directory of a game without one in the latest version of ryujinx, a dialogue box should open that facilitates the creation of that save directory. Instead, this does not occur, and a ResultFsTargetNotFound (2002-1002) error is thrown. This functionality works in older versions (such as LDN 2.4) and can carry over to the latest version. 

### How can the issue be reproduced?

Right click a game without a bcat directory, choose "open bcat directory". Notably, If the user has no games with bcat directories, the first will succeed, though without opening a dialogue. Any other game will throw the error described when trying to create the directory. Any directories created by previous versions of ryujinx will open properly.

Ryujinx 1.1.480:
https://gfycat.com/grandunitedamphiuma

Ryujinx LDN 2.4:
https://gfycat.com/fr/coolfortunatefennecfox

### Log file

1.1480:
[Ryujinx_1.1.480_2022-12-19_13-17-53.log](https://github.com/Ryujinx/Ryujinx/files/10261962/Ryujinx_1.1.480_2022-12-19_13-17-53.log)

### Environment?

- Ryujinx version: 1.1.480</br>
- Game version: N/A</br>

- System Specs:
  - OS: *Windows 10*
  - CPU: *r7 3700x*
  - GPU: *gtx 1660 super 6gb*
  - RAM: *32GB*
- Applied Mods : N/A

### Additional context?

Additional info about your environment:</br>
I believe another dialogue box for missing controllers is no longer working as well but I was not able to show this in LDN 2.4. I may be misremembering on this count, though the log does complain about it.

**Comment by AKettle** [comment]
I've got the same issue, on version 1.1.564
OS: Windows 11 
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz 
GPU: Nvidia RTX 3050 TI
RAM: 16 GB
Log File: [Ryujinx_1.1.564_2023-01-25_06-28-59.log](https://github.com/Ryujinx/Ryujinx/files/10500413/Ryujinx_1.1.564_2023-01-25_06-28-59.log)
I have the firmware, and the ram given for some reason is wrong. If there's any way to manually create a bcat folder, please let me know.

**Comment by AKettle** [comment]
Found a workaround; download another instance of ryujinx, make it portable, and only open that game for which you want the BCAT for. Should work now, and you should be able to put the BCAT files in to the directory.
