### ISSUE TITLE
SSBU with Arcropolis crashing on startup on macOS

### ISSUE THREAD

**Issue by a-plastic-bag** [Ryujinx/Ryujinx#4152]
### What's the issue you encountered?

(I followed [this guide](https://gamebanana.com/tuts/14311))
I placed the Arcropolis romfs folder and Skyline's exefs folder into ~/.config/Ryujinx/sdcard/atmosphere/contents/01006A800016E000

Upon starting Super Smash Bros. Ultimate, Ryujinx crashes.

### How can the issue be reproduced?

1. Download Arcropolis and Skyline, and place them into their respective folders, as outlined above.
2. Attempt to start Super Smash Bros Ultimate

### Log file

[Ryujinx_ 1.1.0-macos1_2022-12-20_17-54-23.log](https://github.com/Ryujinx/Ryujinx/files/10266057/Ryujinx_.1.1.0-macos1_2022-12-20_17-54-23.log)

### Environment?

- Ryujinx version: 1.0.1-macos1</br>
- Game version: 13.0.0</br>
- System Specs:
  - OS: macOS 13.0.1
  - CPU: Apple M1 Pro
  - GPU: Apple M1 Pro
  - RAM: 16GB
- Applied Mods: Arcropolis and Skyline

### Additional context?

N/A

**Comment by MetrosexualGarbodor** [comment]
Update your game

**Comment by a-plastic-bag** [comment]
> Update your game

I updated the game to 13.0.1, but it seems to still be crashing with the same error.
