### ISSUE TITLE
Graphics Freeze, Music Continues 

### ISSUE THREAD

**Issue by Chazz08** [Ryujinx/Ryujinx#4154]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

I am playing along in Pokemon Violet, I don't think it is game specific, and suddenly the game freezes randomly. Music continues, however. It then causes the whole Ryujinx to freeze, and I have to force close.</br>
No changes were made to Ryujinx. </br>

### How can the issue be reproduced?

Simply playing a game. I am currently playing Pokemon Violet, and it freezes randomly during play. No rhyme or reason.

### Log file
[Ryujinx_ 1.1.0-macos1_2022-12-20_06-47-26.log](https://github.com/Ryujinx/Ryujinx/files/10269911/Ryujinx_.1.1.0-macos1_2022-12-20_06-47-26.log)
[Ryujinx_ 1.1.0-macos1_2022-12-20_09-02-33.log](https://github.com/Ryujinx/Ryujinx/files/10269912/Ryujinx_.1.1.0-macos1_2022-12-20_09-02-33.log)
[Ryujinx_ 1.1.0-macos1_2022-12-20_09-21-25.log](https://github.com/Ryujinx/Ryujinx/files/10269913/Ryujinx_.1.1.0-macos1_2022-12-20_09-21-25.log)
</br>

### Environment?

- Ryujinx version: 1.1.0-macos1</br>

- Game version: 1.0.0</br>

- System Specs:
  - OS: macOS Ventura 13.1
  - CPU: Apple M1 Max
  - GPU: M1 Max
  - RAM: 32 GiB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>

**Comment by MutantAura** [comment]
Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues
Join the discord for further support queries: https://discord.gg/ryujinx

**Comment by Chazz08** [comment]
This isn't a game specific issue. Thanks.
