### ISSUE TITLE
Mario kart 8 deluxe crashing

### ISSUE THREAD

**Issue by slowbro63** [Ryujinx/Ryujinx#4160]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[Mario kart crashes when opening grand prix, happens 8/10 times. happens on main and ldn build, other gamemodes work ]</br>
[No]</br>
[N/A]

### How can the issue be reproduced?

[Open ryujinx, choose mariokart, go to singleplayer or multiplayer, choose grand prix. happens every time after having played once, happens randomly on first open]

### Log file
[Ryujinx_1.1.488_2022-12-22_11-21-31.log](https://github.com/Ryujinx/Ryujinx/files/10285681/Ryujinx_1.1.488_2022-12-22_11-21-31.log)
(played one grand prix then crash)

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.1.488</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 2.2.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: windows 10
  - CPU: i7 7700k
  - GPU: NVidia gtx 1060 6gb
  - RAM: 8gb ddr4 3200mhz cl16
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[had a lot of stuttering before, it got better but then this started]

**Comment by TNTblower** [comment]
I get EXACTLY the same error, not even a bit different....

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/244). Thank you.
