### ISSUE TITLE
Rendering issue. Looks transparent in every game. How to fix it ?

### ISSUE THREAD

**Issue by Foreicode** [Ryujinx/Ryujinx#4162]
![Screenshot (3).png](https://user-images.githubusercontent.com/112508107/209211024-ea04688e-449a-4251-88fc-8b3c26bbbcb5.png)

**Comment by MetrosexualGarbodor** [comment]
Disable AMD sharpening, and please don't open issues for help

**Comment by Foreicode** [comment]
> Disable AMD sharpening, and please don't open issues for help

Thanks for help mate. Where can i ask for help in the future ?

**Comment by MetrosexualGarbodor** [comment]
https://discord.gg/ryujinx
