### ISSUE TITLE
Ryujinx Locks Up on macOS

### ISSUE THREAD

**Issue by PodcastGuru74** [Ryujinx/Ryujinx#4171]
## Bug Report
Ryujinx Locks Up on macOS

### What's the issue you encountered?
On macOS, Ryujinx loads forever when trying to start Super Monkey Ball Banana Mania. When I click File > Exit, Ryujinx stops responding to attempts to close the app. The neither the red stoplight button at the top left works nor does Ryujinx > Quit using the system menu bar work. In this state, the only way to quit is to go to Apple Logo > Force Quit, then force quit Ryujinx. No changes have been made to Ryujinx.

### How can the issue be reproduced?
The issue can be reproduced by loading SuperMonkeyBallBananaMania.nsp in Ryujinx using a M1 Mac (specifically the M1 Mac Mini).

### Log file
[Ryujinx_ 1.1.0-macos1_2022-12-23_21-21-53.log](https://github.com/Ryujinx/Ryujinx/files/10298086/Ryujinx_.1.1.0-macos1_2022-12-23_21-21-53.log)
[Ryujinx_ 1.1.0-macos1_2022-12-23_21-37-39.log](https://github.com/Ryujinx/Ryujinx/files/10298087/Ryujinx_.1.1.0-macos1_2022-12-23_21-37-39.log)
[Ryujinx_ 1.1.0-macos1_2022-12-23_21-52-24.log](https://github.com/Ryujinx/Ryujinx/files/10298089/Ryujinx_.1.1.0-macos1_2022-12-23_21-52-24.log)

### Environment?

- Ryujinx version: 1.1.0
- Game version: 1.0.0 (Was attempting to play the base game without any updates applied.)
- System Specs:
  - OS: macOS Ventura (13.1)
  - CPU: Apple M1
  - GPU: Apple M1
  - RAM: 8GB
- Applied Mods: No

### Additional context?
N/A

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, we have [discord](https://discord.gg/ryujinx) for that. Your game dump seems to be incorrect.
