### ISSUE TITLE
Ryujinx/Pokémon Violet launch or stop makes OBS freeze and crash stream

### ISSUE THREAD

**Issue by Erastem** [Ryujinx/Ryujinx#4173]
### What's the issue you encountered?

I'm a streamer and i use OBS Studio. I've never crashed or freezed while i'm streaming but since i'm using Ryujinx to play Pokémon Violet, when i stop or launch the emulator and the game while i'm streaming it's sometimes randomly making OBS freeze and stop the live... All i can do is kill the process and restart OBS. I know it's not OBS fault since i've never had any crash or freeze of some sort and i played a lot of big games. OBS is using the CPU for streaming (x264) in medium and Ryujinx is OpenGL. This problem is so annoying because OBS is using only 3% max of my CPU and it's happening when launching/stopping the game/emulator. Even if the game doesn't crash.

Thanks for your help and sorry for my english, i'm french.

### How can the issue be reproduced?

As i said earlier. Maybe it's a compatibility problem ?

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.488</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: Windows 11
  - CPU: i7-13700k
  - GPU: NVIDIA GTX 1060
  - RAM: 64GiB
- Applied Mods : Non

### Additional context?

N/A

**Comment by Squall-Leonhart** [comment]
issues within the obs software are issues within the obs software.

> I know it's not OBS fault since i've never had any crash or freeze of some sort and i played a lot of big games

it IS obs fault.

**Comment by MetrosexualGarbodor** [comment]
This seems to be an issue on the user end, as we've had no other reports of this happening since the issue was opened. Closing now.
