### ISSUE TITLE
every game crashes I try to boot it up is my mac not good enough?

### ISSUE THREAD

**Issue by farisalike** [Ryujinx/Ryujinx#4175]
I get this message everytime 

Translated Report (Full Report Below)
-------------------------------------

Process:               Ryujinx [33495]
Path:                  /private/var/folders/*/Ryujinx.app/Contents/MacOS/Ryujinx
Identifier:            org.ryujinx.Ryujinx
Version:               1.1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-24 23:15:50.7146 +0300
OS Version:            macOS 12.6.1 (21G217)
Report Version:        12
Anonymous UUID:        C72ED534-3A5C-9FAC-DCCF-3E53AD2E645C

Sleep/Wake UUID:       07F40EB4-9EAD-4B7A-A115-99412BA5AFE0

Time Awake Since Boot: 500000 seconds
Time Since Wake:       4121 seconds

System Integrity Protection: enabled

Crashed Thread:        61

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Model: MacBookAir7,2, BootROM 476.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 1.8 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In

**Comment by MetrosexualGarbodor** [comment]
This GPU can't run Ryujinx, sorry.
