### ISSUE TITLE
Settings tab crashes when using Vulkan

### ISSUE THREAD

**Issue by battista26** [Ryujinx/Ryujinx#4176]
## Bug Report

When I select the "Settings" tab on Ryujinx it suddenly shuts down the program and doesn't appear in logs for some reason.</br>
Although this happens when I select Vulkan, if I select OpenGL it works.

### What's the issue you encountered?

I opened the program, set up keys and firmware. "File", "Options", "Tools" tabs all work, no problems there.</br>
And then Ryujinx asks if I want to use Vulkan or OpenGL. I choose Vulkan then for setting up a controller I select "Setting" tab then boom program shuts down.</br>
I couldn't find anything on the internet but someone was saying something about deleting the Ryujinx folder on %appdata so I deleted it and then when I was setting it up again I selected OpenGL this time and now it works.

### How can the issue be reproduced?
Setup keys and firmware, select Vulkan (not through setting, when program first asks you) open "Options" tab then "Setting" then crash.

### Log file
It looked like this but it said Vulkan im pretty sure.
I didn't delete any logs but this is all I have.</br>
[Ryujinx_1.1.489_2022-12-25_17-01-26.log](https://github.com/Ryujinx/Ryujinx/files/10300097/Ryujinx_1.1.489_2022-12-25_17-01-26.log)
</br>

### Environment?

- Ryujinx version: 1.1.489</br>

[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 5600H
  - GPU: NVIDIA RTX 3050 Laptop GPU
  - RAM: 16 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
It might be because of my new GPU update I don't really know.

**Comment by MetrosexualGarbodor** [comment]
If your device has an AMD iGPU and an NVIDIA dGPU and doesn't work with Vulkan applications then first attempt to update **__both__** GPU drivers from AMD and NVIDIA respectively. 
Latest NVIDIA drivers: <https://www.nvidia.com/download/index.aspx>
Latest AMD Radeon Drivers: <https://www.amd.com/en/support>
If this does not help Vulkan applications then follow these steps: <https://nvidia.custhelp.com/app/answers/detail/a_id/5182/>
