### ISSUE TITLE
Animal Crossing - Character moving by itself

### ISSUE THREAD

**Issue by YeudielG** [Ryujinx/Ryujinx#4179]
### What's the issue you encountered?

Playable character is slowly moving/walking by itself using an Xbox One controller with Pro Controller profile.

### How can the issue be reproduced?

1. Open Ryujinx.
3. Connect Xbox One Controller via USB
2. Open Animal Crossing: New Horizons.
3. Configure the controller mappings, using Pro Controller profile.
4. Get to the first playable part of the game (at the bay).
5. The character will be moving by itself

### Environment?

- Ryujinx version: 1.1.489</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 11*
  - CPU: *AMD Ryzen 5000*
  - GPU: *AMD Radeon*
  - RAM: *8GiB*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
I tested the game on Yuzu before and I didn't have this issue.

**Comment by TSRBerry** [comment]
Increase the deadzone for your controller. Join the discord server for support.

This is not a Ryujinx issue.
