### ISSUE TITLE
Persona 5 Royal (and possibly other games) crashes after a bit of playtime.

### ISSUE THREAD

**Issue by RayRMR** [Ryujinx/Ryujinx#4183]
Whenever I play P5R it will randomly crash without warning, usually without lag and any other signs. It will usually turns my PC to a black screen where i will be able to do nothing unless i restart the whole pc, i recently found out i can circumvent this by switching GPU ports. I'll post again here if you need any other information. For now ill post my most recent log.

System specs: OS Win 10. 
CPU Intel Core i5-7400  
GPU Nvidia 970 
Ram 16GB

[Ryujinx_1.1.492_2022-12-26_20-12-37.log](https://github.com/Ryujinx/Ryujinx/files/10310237/Ryujinx_1.1.492_2022-12-26_20-12-37.log)

**Comment by Dormanil** [comment]
I have literally the same issue, with the same GPU, on Linux. I wonder if switching GPU ports would fix it for me as well, if I had a CPU with graphics output.

**Comment by Squall-Leonhart** [comment]
dying cards be like that,

**Comment by RayRMR** [comment]
definitely not a dying card. It doesn't do this on anything else.

**Comment by Squall-Leonhart** [comment]
said everyone with a dying card ever.

**Comment by Dormanil** [comment]
Could you kindly fuck off? Your insistence on blaming it on a dying card doesn't help anyone here.

**Comment by Squall-Leonhart** [comment]
The black screen is called "Protect mode", on a decayed and dying 900 series card (which all are at this point) it will be accompanied with the fans either stopping entirely on fanstop models or maximum speed on those that don't support fanstop.

Protect mode is triggered when the gpu encounters a triple fault exception that can only be recovered from by fully powercycling the chip, usually as a result of poor current being fed into the chip from the GPU VCIO while performing a task of variable but spikey load.

**Comment by RayRMR** [comment]
I assumed it was something with ryujinx, cause it crashes after it does this. nothing else crashes. I just haven't had problems with anything else since I started this playthrough on ryujinx

**Comment by 666keke** [comment]
Same problem on M1 mac.
I've downloaded the shaderPre-caching from RyuSAK.
[crashReport.md](https://github.com/Ryujinx/Ryujinx/files/10344460/crashReport.md)

**Comment by MetrosexualGarbodor** [comment]
The fact that this does not happen if you switch GPU ports point to it not being an emulator issue. Even so, please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4086). Thank you.
