### ISSUE TITLE
Mario Kart Deluxe 8: Audio Desync when pausing game

### ISSUE THREAD

**Issue by evilsh3ll** [Ryujinx/Ryujinx#4187]
### What's the issue you encountered?
Sometimes when I pause Mario Kart 8 Deluxe and then I resume the game, the audio is not synchronized with video

### How can the issue be reproduced?
1. Play Mario Kart 8 Deluxe (version 2.2.0 + Wave 2 DLC) for 10min
2. pause a race
3. resume the game
4. audio is now not synched

### Log file
N/A

### Environment?

- Ryujinx version: 1.1.489</br>
- Game version: 2.2.0</br>
- System Specs:
  - OS: Arch Linux
  - CPU: *i5-6600k*
  - GPU: *NVIDIA GTX 1070*
  - RAM: *16GiB*
- Applied Mods : No

### Additional context?
N/A

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/244). Thank you.

**Comment by evilsh3ll** [comment]
> Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/244). Thank you.
I edited the issue because the problem happens ont only with mario kart (also in mario odissey, mario 3d world etc..), it seems a Ryujinx problem, not a game related problem. Thanks

**Comment by All-The-Foxes** [comment]
I am having this issue with Super Mario 3D World. I have to pause and resume emulation to fix it.
