### ISSUE TITLE
Pokemon Scarlet Crashes immediately upon launch.

### ISSUE THREAD

**Issue by Ducolamia** [Ryujinx/Ryujinx#4189]
### What's the issue you encountered?

Pokemon Scarlet immediately crashes upon start up in after latest Ryujinx update to 1.1.494. The game starts, but after compiling the shader cache it immediately closes Ryujinx itself. Other games do not have this particular issue. I applied the same exact settings to Pokemon Violet but that still boots perfectly fine. </br>
I have tried turning off V-Sync, turning off Ignore Missing Services, replacing the old Scarlet rom and updates with new clean .xci files, switching Steam Client from Beta to Stable and then back again. I also removed the 60fps mod for Scarlet. I even reverted to an older build in an effort to get it to work "[ryujinx-Release-1.1.0+4d1dec1-linux_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/490594183.zip)" but no dice. </br>

### How can the issue be reproduced?

Ryujinx automatically checks for updates in Steam's Desktop mode (via Emudeck). A prompt will ask to update to the latest Ryujinx version from the previous build. After accepting, Ryujinx will ask to restart. After restarting, Ryujinx opens up normally with all games in the directory, but Pokemon Scarlet will not load.

### Log file

https://github.com/Ducolamia/Logs/blob/main/Ryujinx_Log
I did not get an "official" crash notice, but I do have the log itself.

### Environment?

-Steam Deck
- Ryujinx version: 1.1.494</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: *Steam OS*
  - CPU: *AMD APU - Zen 2 4c/8t, 2.4-3.5GHz*
  - GPU: *8 RDNA 2 CUs, 1.0-1.6GHz*
  - RAM: *16 GB*
- Applied Mods : Yes - 60fps mod for Scarlet Violet. It was removed in an effort to start fresh with clean mods.

### Additional context?

I am using a Steam Deck and installed Ryujinx via Emudeck. Due to another issue with Ryujinx having a black screen upon in opening the games https://github.com/Ryujinx/Ryujinx/issues/3874 I switched to the Avalonia build temporarily for Game Mode. However, the game does not boot there either.

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, we have [discord](https://discord.gg/ryujinx) for that. The log you've posted is empty. Post one containing a crash in the Linux support channel and we'll sort it out.
