### ISSUE TITLE
1.1.500 Crash on Linux

### ISSUE THREAD

**Issue by luisalvarado** [Ryujinx/Ryujinx#4191]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

Was playing Mario Odyssey and the game crashed and closed.
I checked the logs but did not find something that was related to why it happened:

00:00:00.027 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.028 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.028 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.029 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.029 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.029 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.030 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684
00:00:00.031 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.034 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.034 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.034 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.034 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.035 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.035 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.035 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.035 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.035 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.036 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.500
00:00:00.040 |N| Application Print: Operating System: Linux 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 (X64)
00:00:00.040 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i9-13900K ; 32 logical
00:00:00.041 |N| Application Print: RAM: Total 128520 MiB ; Available 124965 MiB
00:00:00.042 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.042 |N| Application PrintSystemInfo: Launch Mode: UserProfile

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.1.500</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.3.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
- 
![image](https://user-images.githubusercontent.com/29236/210006176-4ba6c2b5-6d0b-4a7b-8314-4a45555dde30.png)

- Applied Mods : No

### Additional context?

How can I help to debug or find the reason behind it. Thank you.

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, we have [discord](https://discord.gg/ryujinx) for that. The log you've posted is empty. Post one containing a crash in the Linux support channel and we'll sort it out.
