### ISSUE TITLE
[Linux] Crash upon booting a game with vulkan

### ISSUE THREAD

**Issue by DuIslingr** [Ryujinx/Ryujinx#4200]
### What's the issue you encountered?
Ryujinx crashes when booting any game.

### How can the issue be reproduced?
Boot any game with vulkan backend selected

### Environment?

- Ryujinx version: 1.1.503

- Doesn't matter what game it is or version

- System Specs:
  - OS: Endeavour OS(Arch Linux, Zen Kernel 6.1.1-1)
  - CPU: R9 7950X
  - GPU: RX 6900XT (Mesa 22.3.1 driver)
  - RAM: 32gb
- Applied Mods : Occurs with or without mods.

[Systemlog.txt](https://github.com/Ryujinx/Ryujinx/files/10332872/Systemlog.txt)

**Comment by TSRBerry** [comment]
> ErrorOutOfHostMemory

This doesn't look like a Ryujinx bug. 

Please join the discord and ask in #linux-support for help in case you want further support. If this turns out to be a Ryujinx issue, we'll reopen this.
