### ISSUE TITLE
Ryujinx crash when play Story of Season Friends of Mineral Town

### ISSUE THREAD

**Issue by Zethyx** [Ryujinx/Ryujinx#4201]
### Unplayable Story of Season Friends of Mineral Town

the game just not working at all, ryujinx will exit the program by itself, i have tried change any settings, graphic backend with opengl or vulkan, still not working. no loading screen, the game cant start up

### Log file

- Ryujinx version: 1.1.503
- Game version: 1.0.0.4
- System Specs:
  - OS: Windows 11
  - CPU: AMD Ryzen 5 4600H
  - GPU: NVIDIA GTX 1650Ti
  - RAM: 16GB
- Applied Mods : No

[Ryujinx_1.1.503_2023-01-03_22-21-47.log](https://github.com/Ryujinx/Ryujinx/files/10337788/Ryujinx_1.1.503_2023-01-03_22-21-47.log)

**Comment by MetrosexualGarbodor** [comment]
This is not an emulator issue, join  [discord](https://discord.gg/ryujinx) for help.
