### ISSUE TITLE
Xenoblade Chronicles 2 random crash

### ISSUE THREAD

**Issue by Likesouten** [Ryujinx/Ryujinx#4203]
### What's the issue you encountered?

I was playing Xenoblade Chronicles 2 and then suddenly the game crashes, which happened some days ago until I updated the Vulkan drivers with the lates beta Vulkan drivers which version is 527.86, but I just got another crash even with the update.

### How can the issue be reproduced?

I cannot say for sure how it can be reproduced, it is just a random crash.

### Log file

[Ryujinx_1.1.504_2023-01-03_20-47-26.log](https://github.com/Ryujinx/Ryujinx/files/10341075/Ryujinx_1.1.504_2023-01-03_20-47-26.log)

### Environment?

- Ryujinx version: 1.1.504
- Game version: 2.1.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 5600
  - GPU: NVIDIA GTX 1070
  - RAM: 16GiB
- Applied Mods : Yes, I have a custom lib to improve the graphic quality and an atmosphere mod to change the appearance of the weapons

**Comment by Squall-Leonhart** [comment]
Issue well noted on the compatibility page.

https://github.com/Ryujinx/Ryujinx-Games-List/issues/159

**Comment by AcK77** [comment]
Please report game-specific issues on the relevant compatibility page: https://github.com/Ryujinx/Ryujinx-Games-List/issues/159 if needed. Thanks.

**Comment by Likesouten** [comment]
Thank you very much for the help and sorry for the inconveniences.
