### ISSUE TITLE
Crashing 1.1.505+ on any game on SteamDeck

### ISSUE THREAD

**Issue by BananaAcid** [Ryujinx/Ryujinx#4207]
### What's the issue you encountered?

Just Updated.</br>
No Changes made, worked before recent updates the last few months..</br>

### How can the issue be reproduced?

Use EmuDeck to install, add games, use either Desktop Mode or Gaming Mode to start a game.

### Log file

[ryujinx_crash.log](https://github.com/Ryujinx/Ryujinx/files/10348472/ryujinx_crash.log)

### Environment?

- Ryujinx version: 1.1.509</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: SteamDeck (Jupiter v1), Linux 5.13.0-valve36-1-neptune
  - CPU: AMD Custom APU 0405
  - GPU: AMD Custom GPU 0405 (RadV Vangogh)
  - RAM: 16GiB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Was forwarded to me to post here, can not verify any of the log data.

**Comment by AcK77** [comment]
Fixed in lastest commit, wait the CI for the new build.
