### ISSUE TITLE
Splatoon 2 random early game crash

### ISSUE THREAD

**Issue by yim0000** [Ryujinx/Ryujinx#4217]
### What's the issue you encountered?

The game simply just runs and loads, but it usually crashes during or right after the tutorial, and never made pass it.
I have read the past issues and found sometime about controller issues, but I only have one controller active, and I don't seem to find anything else reading the past issues. The app itself crashes, Quit unexpectedly

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?
- Ryujinx version: 1.0.1macos
- Game version: 5.5.1
- System Specs:
  - OS: Macos ventura
  - CPU: M1
  - RAM: 8GB
- Applied Mods : No

### Additional context?
All the other games including splatoon 3 runs well, do i need a older version? or do I need extra framework? Is it the game or the app problem? What is the issue? here is the unexpected quit details
[error.txt](https://github.com/Ryujinx/Ryujinx/files/10362661/error.txt)

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/703). And please add Ryujinx logs to reports, not macOS logs. Thank you.
