### ISSUE TITLE
~~Super Kirby Clash~~ Multicontent NSP games crash on boot

### ISSUE THREAD

**Issue by hyoretsu** [Ryujinx/Ryujinx#4219]
### What's the issue you encountered?

First, it's Super Kirby Clash. But then I tested with another game and it didn't work. While Kirby and the Forgotten Land, with no updates, worked.

### How can the issue be reproduced?

Get a game and its update, merge them with [SAK](https://github.com/dezem/SAK) and try to play them.

### Log file

[Ryujinx_1.1.512_2023-01-06_19-57-42.log](https://github.com/Ryujinx/Ryujinx/files/10363687/Ryujinx_1.1.512_2023-01-06_19-57-42.log)
[Ryujinx_1.1.512_2023-01-06_19-58-15.log](https://github.com/Ryujinx/Ryujinx/files/10363689/Ryujinx_1.1.512_2023-01-06_19-58-15.log)
[Ryujinx_1.1.512_2023-01-06_20-00-45.log](https://github.com/Ryujinx/Ryujinx/files/10363683/Ryujinx_1.1.512_2023-01-06_20-00-45.log)

### Environment?

- Ryujinx version: 1.1.512</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Windows 11
  - CPU: i5-1135G7
  - GPU: Intel Iris Xe
  - RAM: 16 GB
- Applied Mods : No

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1899). Thank you.
