### ISSUE TITLE
The motion controls doesn't work in  Luigi's Mansion 3 when use vaccum cleaner

### ISSUE THREAD

**Issue by Kyle-Leu** [Ryujinx/Ryujinx#4221]
## Bug Report
I noticed that the motion controls doesn't work when I use the vacuum cleaner to suck the ghosts.I'm sure I open the motion controls in the options because the motion controls work very well for Super Mario Odyssey in Ryujinx.

### How can the issue be reproduced?
Using the Sony dualsense 5 controller to play Luigi's Mansion 3 in Ryujinx ，whether or not you use sdl direct connection or cemuhook with DS4Windows ,we can encounter the issue .

### Environment?

- Ryujinx version: 1.1.515
- Game version: Luigi's Mansion 3 V1.4.0
- System Specs:
  - OS: Windows11
  - CPU: I7-10750H
  - GPU: RTX2060
  - RAM: 16G
- Applied Mods :120FPS

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/207). Thank you.
