### ISSUE TITLE
Unable to update Ryujinx from 1.1.516 to 1.1.518

### ISSUE THREAD

**Issue by Cslizzy** [Ryujinx/Ryujinx#4226]
Unable to update Ryujinx from 1.1.516 to 1.1.518

This is my first time using Ryujinx, so I'm still figuring things out. The update starts up fine, but when it switches to "adding new files", the log crashes and the update blocks. I don't think I did anything to cause crash

How am I able to fix that issue?

Here's the log:
[Ryujinx_1.1.516_2023-01-07_23-15-07.log](https://github.com/Ryujinx/Ryujinx/files/10367153/Ryujinx_1.1.516_2023-01-07_23-15-07.log)

The crash report is too long to be copied

I picked the USA environment

- Ryujinx version: 1.1.516
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i5-6700)*
  - GPU: I'm not sure
  - RAM: *(e.g. 16GiB)*
  - No applied mods
 
Thank you

**Comment by MetrosexualGarbodor** [comment]
This is not an emulator issue. Make sure Ryujinx isn't on a protected folder and that a 3rd party antivirus isn't blocking it from working.

**Comment by Cslizzy** [comment]
It worked! Thank you very much
