### ISSUE TITLE
Game wouldn't launch

### ISSUE THREAD

**Issue by Cslizzy** [Ryujinx/Ryujinx#4233]
I have everything ready, and everything seems to be working fine. I double click the game "pokemon violet" and it loads, after that, it disappears. I tried waiting and trying again but it doesn't seem to be working.

Should I just wait longer or does it close on it's own?

Here's the log:
[Ryujinx_1.1.516_2023-01-08_19-34-28.log](https://github.com/Ryujinx/Ryujinx/files/10368942/Ryujinx_1.1.516_2023-01-08_19-34-28.log)

I picked USA for the eviroment

- Ryujinx version: 1.1.519
- System Specs:
  - OS: *(e.g. Windows 11)*
  - CPU: *(e.g. i5)*
  - GPU: *(Not sure)*
  - RAM: *(e.g. 16GiB)*
  - No applied mods

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, we have [discord](https://discord.gg/ryujinx) for that.
