### ISSUE TITLE
Scale Feature Works fine on Linux but not on Windows

### ISSUE THREAD

**Issue by cassiofb-dev** [Ryujinx/Ryujinx#4241]
### What's the issue you encountered?

1. Scale feature works well on Linux but not on Windows.
2. I didn't make any change on Ryujinx program besides playing portable mode
3. The game was Pokémon Scarlet Version

### How can the issue be reproduced?

1. Boot Windows operate system (must be this OS)
2. Localize and run your Ryujinx
3. Click on ``Options``
4. Click on ``Settings``
5. Click on ``Graphics``
6. Click on ``Resolution Scale``
7. Click on the option ``2x (1440p/2160p)``
8. Click on ``Save`` button
9. Open the game ``Pokémon Scarlet Version``
10. See the error

### Log file

[Ryujinx_1.1.525_2023-01-09_06-14-33.log](https://github.com/Ryujinx/Ryujinx/files/10370884/Ryujinx_1.1.525_2023-01-09_06-14-33.log)

### Environment?

- Ryujinx version: 1.1.525
- Game version: Pokémon Scarlet  V1.1.0
- System Specs:
  - OS: Windows 11 (22H2)
  - CPU: AMD Ryzen 5 3600
  - GPU: AMD RX 6600M
  - RAM: 2x 8GB DDR4 3200 CL14
- Applied Mods : No

### Additional context?

Linux >>> Windows

**Comment by mattzink** [comment]
FYI: I run everything at 3x scale on Windows 11, and don't see that error

**Comment by AcK77** [comment]
The log file doesn't contain an error message... Could you upload another one?

**Comment by gdkchan** [comment]
This is an AMD specific issue. There's something on the depth texture blit operation that causes it to crash.

**Comment by cassiofb-dev** [comment]
@AcK77 , sorry for the delay. I double checked but there's no error in the logs. So I have to get the error from the terminal:

[custom.log](https://github.com/Ryujinx/Ryujinx/files/10451924/custom.log)

The error is:
> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

![image](https://user-images.githubusercontent.com/61878987/213317055-b1c141a6-b29b-459f-98d1-9c476245802f.png)

**Comment by cassiofb-dev** [comment]
The scale problem was solved on version [1.1.601](https://github.com/Ryujinx/Ryujinx/wiki/Changelog#11601---2023-02-05) so I'm closing this issue. Thanks all of you guys for the effort, this version also boosted my FPS so much that even scaled is stable at 30fps!
