### ISSUE TITLE
[Feature Request] Gyro Calibration Settings

### ISSUE THREAD

**Issue by veploxmine123** [Ryujinx/Ryujinx#4246]
#### Overview:
Add Gyro Calibration Settings for Controllers with Gyro Support

#### Smaller Details: 
Sometimes an issue where using Gyro Controls Natively has a drift. Some apps fixes this by having a calibration settings like betterjoy but it would be better to have it natively on Ryujinx.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
It benefits most controllers that uses Gyro Controls that needed a calibration to fix drifting.

**Comment by EmulationFanatic** [comment]
![image](https://user-images.githubusercontent.com/62343878/211366574-a3fb8212-52fc-4168-a28b-3ac73b5ba695.png)
Is the Gyro Deadzone setting not what you're looking for?

**Comment by veploxmine123** [comment]
> ![image](https://user-images.githubusercontent.com/62343878/211366574-a3fb8212-52fc-4168-a28b-3ac73b5ba695.png) Is the Gyro Deadzone setting not what you're looking for?

Deadzone does fix the drift but the gyro deadzone isn't good when you use it. It makes the gyro not smooth and requires more movement when using motions.

**Comment by EmulationFanatic** [comment]
> > ![image](https://user-images.githubusercontent.com/62343878/211366574-a3fb8212-52fc-4168-a28b-3ac73b5ba695.png) Is the Gyro Deadzone setting not what you're looking for?
> 
> Deadzone does fix the drift but the gyro deadzone isn't good when you use it. It makes the gyro not smooth and requires more movement when using motions.

Then what exactly are you expecting for calibration?

**Comment by veploxmine123** [comment]
Calibrate the Gyro Controls to be in a neutral state like what it does on other apps. Its much better than a deadzone

**Comment by AcK77** [comment]
Superseeded by #4917
