### ISSUE TITLE
`MemoryBlock.GetPageSize` should detect the correct page size for the platform

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#4258]
This function was added mainly for Apple Silicon which has 16 KB pages. However right now it just assumes that if it's macOS and Arm64, the page size is 16 KB, otherwise it is 4 KB. We should instead call the appropriate functions per platform and get the correct page size.

This will be required to make the emulator work on Asahi Linux which AFAIK also has 16 KB pages.

**Comment by gnisman** [comment]
#4291
