### ISSUE TITLE
Arm64: Detect CPU capabilities

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#4259]
#4114 added JIT Arm64 support, however right now we can't use some instructions directly because we have no way to detect if the CPU actually supports them. Right now, the only fast path that is disabled due to this is the one for the PMULL instruction, but in the future we will also hit that issue for crypto and hash instructions that are optional.

We should implement a function to get CPU capabilities for each platform, and expose properties on the `ARMeilleure.Optimizations` class that will be used by the instruction implementations to check if a given feature is supported.

**Comment by MutantAura** [comment]
Complete?

**Comment by gdkchan** [comment]
Yes.
