### ISSUE TITLE
MiiEdit applet is not implemented.

### ISSUE THREAD

**Issue by danielkleinert** [Ryujinx/Ryujinx#4267]
### What service call is missing?

AppletAE Unknown: Unknown (MiiEdit applet) is not implemented.</br>

### Required by: 
[Mario Golf: Super Rush - 0100C9C00E25C000](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3633)

Start a Golf Adventure (1.0.0 / 4.0.0) and choose a save Slot. Ryujinx immediately crashes to the desktop.

[Ryujinx_ 1.1.0-macos1_2023-01-11_11-44-43.log](https://github.com/Ryujinx/Ryujinx/files/10392119/Ryujinx_.1.1.0-macos1_2023-01-11_11-44-43.log)

**Comment by MetrosexualGarbodor** [comment]
File > Load Applet > Mii editor

**Comment by EmulationFanatic** [comment]
This is a valid issue, as games that try to call the applet in-game cannot currently do so.

**Comment by AcK77** [comment]
Duplicated of https://github.com/Ryujinx/Ryujinx/issues/3369 ?

**Comment by jablochniyvorishka** [comment]
> File > Load Applet > Mii editor

its helped for me.
Im created an avatar, and than game not crushing.
