### ISSUE TITLE
Avalonia Test Build [Linux] - Black Window When Running on Wayland

### ISSUE THREAD

**Issue by lkcv** [Ryujinx/Ryujinx#4277]
### What's the issue you encountered?
When launching the latest Ryujinx.Ava build for Linux under a Wayland environment, a black window shows instead of the menu, game list, etc.

The specific issue is possibly this - from the log file: "|E| Ui : [Error] [Visual] Exception in render loop: 'System.ArgumentException: Invalid create info - no Canvas provided (Parameter 'createInfo')"

No changes were made to Ryujinx.

### How can the issue be reproduced?
By running Ryujinx.Ava, either directly or via the proviced shell script

### Log file

[Ryujinx_1.1.547_2023-01-12_10-13-04.log](https://github.com/Ryujinx/Ryujinx/files/10403172/Ryujinx_1.1.547_2023-01-12_10-13-04.log)

### Environment?

- Ryujinx version: 1.1.547 (Ava test build)</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: No game was launched</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *Arch Linux*
  - CPU: *AMD Ryzen 3950X*
  - GPU: *NVIDIA GTX 1070*
  - RAM: *32GiB*
- Applied Mods : [ Yes (Which ones) / No ]
N/A
### Additional context?
The same test build runs normally under an X11 environment. The GTK build of Ryujinx runs under both X11 and Wayland.

**Comment by TSRBerry** [comment]
Could you test this again on latest master? I'm unable to reproduce this issue.

**Comment by AcK77** [comment]
Seems related to https://github.com/AvaloniaUI/Avalonia/issues/7262

**Comment by lkcv** [comment]
Oddly, I'm no longer experiencing this -- even on the version I reported as having the issue.

Launching Ryujinx.Ava - version 1.1.703 (the latest one at the time of posting) also doesn't have this issue. All elements in the window are now drawn.

Note: the application is launching automatically via XWayland.

The logs are attached.

[Ryujinx_1.1.703_2023-04-10_22-03-32.log](https://github.com/Ryujinx/Ryujinx/files/11195564/Ryujinx_1.1.703_2023-04-10_22-03-32.log)
