### ISSUE TITLE
[Feature Request] Ability to hide file types in Game List

### ISSUE THREAD

**Issue by Whovian9369** [Ryujinx/Ryujinx#4281]
#### Overview: 
- I'm requesting the ability to hide certain file types (for example, `nca` files) from the Game List.

#### Nature of Request:  

- Addition
  - The Wii/Gamecube emulator Dolphin has a menu option to hide files from the game list (`dol`, `elf`, `wad`, etc), which inspired this request here.

### Why would this feature be useful?
It would remove stray entries from the Game List, especially in cases where one may be datamining in a directory that Ryujinx is normally set to scan.

**Comment by NitroTears** [comment]
Heya, I was the guy talking about this on development channel, happy to complete this if you want to assign me!

**Comment by MetrosexualGarbodor** [comment]
You can simply start work on it, as it doesn't seem like anyone else is on it.
