### ISSUE TITLE
Super Mario Odyssey crashes continuing (and possibly starting a new game) in v1.1.554

### ISSUE THREAD

**Issue by chookhen60** [Ryujinx/Ryujinx#4288]
Updated Ryujinx to the latest version today (v1.1.554)

After updating tried to play Super Mario Odyssey, but after clicking resume on the menu:
![image](https://user-images.githubusercontent.com/27396264/212464851-da90449b-e0bb-491c-bb61-0dda45bf6dc1.png)

The game immediately crashes with an Access Violation:
![image](https://user-images.githubusercontent.com/27396264/212464882-9c1f9ac5-2838-471c-9eaa-4e6e76a98193.png)

I believe I upgraded from an earlier 1.1.5xx version prior, but am not sure about exactly what version it was (however it was working in this version)

I downgraded to 1.1.552 to test and I was able to resume the game with no issues, so it has only broken in one of the last two release builds.

Unfortunately the log file doesn't get a chance to capture the crash (hence the screenshot instead)

**Comment by marysaka** [comment]
Can you attach the full logfile with system and drivers information for completness?

From what you seems to say, this is related to https://github.com/Ryujinx/Ryujinx/commit/070136b3f7a000e092eef46780091be29c0bc0bf.

**Comment by chookhen60** [comment]
@marysaka sure here it is - I have three logs but I assume this one will suffice:
[Ryujinx_1.1.554_2023-01-14_20-05-48.log](https://github.com/Ryujinx/Ryujinx/files/10417049/Ryujinx_1.1.554_2023-01-14_20-05-48.log)

That commit could possibly be the cause of the issue...
