### ISSUE TITLE
Dedicated fullscreen plz

### ISSUE THREAD

**Issue by Dixip52** [Ryujinx/Ryujinx#4290]
vsync with 144hz monitor without dedicated fullscreen is terrible...
it will be cool if you add an option to select fullscreen mod (like yuzu).

**Comment by EmulationFanatic** [comment]
Set the option to use fullscreen in the emulator. Or press alt+enter or F11 during runtime.
![image](https://user-images.githubusercontent.com/62343878/212476766-bceee198-1338-4540-b0ef-b1c3c0948112.png)

**Comment by Dixip52** [comment]
that's for windowed full screen
its not a reel fullscreen :/

**Comment by EmulationFanatic** [comment]
No, it is exclusive Fullscreen.

**Comment by riperiperi** [comment]
Ryujinx frame pacing issues with 144hz won't be solved by a different kind of full screen. Yuzu didn't invent full screen. Can you try making an issue report that doesn't relate to a completely different piece of software?

**Comment by Dixip52** [comment]
but, why is it not so good as the yuzu's exclusive fullscreen?

**Comment by Dixip52** [comment]
it looks laggy on ryujinx

**Comment by riperiperi** [comment]
I don't know, you could look into it if you like.

**Comment by gdkchan** [comment]
When running in full screen mode, it might be possible to change the display refresh rate to 60 hz. I don't think it will work well at 144 hz given that Switch games will target 60 fps at most. Ryujinx is not capable of changing it automatically right now so you will need to do it manually.

**Comment by riperiperi** [comment]
I think this is much more relevant, as even at 60hz there will be issues unless it's dealt with:
https://github.com/Ryujinx/Ryujinx/issues/3906

It would be nice to control the host refresh rate to avoid weird pacing at 144hz as well.
