### ISSUE TITLE
Ryujinx Ava Cant Hide Cursor

### ISSUE THREAD

**Issue by ForbAvalon** [Ryujinx/Ryujinx#4298]
## Bug Report

Whatever how many time I wait, my cursor will display in screen.

### What's the issue you encountered?

Even I set cursor to hide, it will not. The mainline can hide cursor nomally.

### How can the issue be reproduced?

Just play and switch to full screen.

### Log file

Log is no needed.

### Environment?

- Ryujinx version: 1.1.554</br>
- Game version: all games</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-9750H
  - GPU: RTX-2060-Laptop
  - RAM: 16GiB
- Applied Mods : No

### Additional context?

No

**Comment by MetrosexualGarbodor** [comment]
Update the emulator
