### ISSUE TITLE
MacOS Portable mode update for Wiki

### ISSUE THREAD

**Issue by k3lv1n90** [Ryujinx/Ryujinx#4308]
#### Overview:
- There is missing information on how to create a portable mode for MacOS in the Wiki
- It took a bit of time for me to figure it out and I thought it would help people in the future.

#### Smaller Details: 
- Run the app, click on File -> Show Ryujinx folder, then delete the whole folder. Then close the app
- Right click on the Ryujinx file and click on "Show package content"
- Then navigate to 
- Ryujinx(App) -> Contents -> MacOS -> create your portable folder here.
- Turn on Ryujinx and it'll ask you to put in the keys. Follow the guide from there to be able to install firmware/keys
The folder structure is as below

<img width="1057" alt="Screen Shot 2023-01-18 at 2 48 53 pm" src="https://user-images.githubusercontent.com/32763588/213103729-ec1f81fe-6778-4530-9225-c2c0e511a198.png">

#### Nature of Request:  
- Change of Wiki

### Why would this feature be useful?
This is for end-user using mac and they will be able to use portable mode easily.

**Comment by EmulationFanatic** [comment]
I added this command to the setup guide/wiki with a note indicating it's needed for MacOS portable mode:
/Applications/Ryujinx.app/Contents/MacOS/Ryujinx -r /path/to/custom/ryujinx/folder
