### ISSUE TITLE
[Mods] exlaunch mods fail to load 

### ISSUE THREAD

**Issue by Martmists-GH** [Ryujinx/Ryujinx#4316]
### What's the issue you encountered?

Installing a custom-made exefs mod using exlaunch causes `*** stack smashing detected ***: terminated` on Ryujinx, works fine on hardware

### How can the issue be reproduced?

Load up Pokemon Brilliant Diamond v1.3.0 with the following files in exefs:

- [`subsdk9`](https://anonfiles.com/de2dK8S1y9/subsdk9)
- [`main.npdm`](https://anonfiles.com/ec2dK8Sdy6/main_npdm)

### Log file

<details>
<summary>console output</summary>
<pre><code>00:00:00.005 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.094 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.099 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.099 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.100 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.101 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.102 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.103 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.106 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.117 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.117 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.118 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.118 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.118 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.118 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.118 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.118 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.119 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.119 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.120 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.120 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.121 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.125 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.500
00:00:00.136 |N| Application Print: Operating System: Linux 6.1.5-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 12 Jan 2023 22:42:30 +0000 (X64)
00:00:00.136 |N| Application Print: CPU: AMD Ryzen 5 1600 Six-Core Processor ; 12 logical
00:00:00.137 |N| Application Print: RAM: Total 32048 MiB ; Available 8753 MiB
00:00:00.141 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.141 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.117 |I| Gpu : Backend Threading (Auto): True
00:00:00.741 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:00.741 |I| Application LoadApplication: Loading as NSP.
00:00:00.792 |I| ModLoader QueryContentsDir: Searching mods for Title 0100000011D90000
00:00:00.794 |I| ModLoader QueryTitleDir: Found mod 'TestMod' [E]
00:00:00.794 |I| ModLoader QueryContentsDir: Searching mods for Title 0100000011D90000
00:00:00.799 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.811 |I| Loader LoadExeFs: Loading rtld...
00:00:00.822 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.822 |I| Loader LoadExeFs: Loading main...
00:00:01.463 |I| Loader PrintRoSectionInfo: main:
    Module: F:\JenkinsWorkSpace\workspace\_common\project\unity_project\Dpr\SwitchIL2CPPCache\il2cpp_cache\linkresult_0BBB0343F01737732DBDC3F916456FC5\SwitchPlayer.nss
    SDK Libraries: SDK MW+UnityTechnologies+Unity-2019_4_27_f1
                   SDK MW+Nintendo+NintendoSDK_libcurl-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NEX-4_6_13-appdl
                   SDK MW+Nintendo+PIA_UNITY-0.33.2
                   SDK MW+Nintendo+PiaSession-5_37_2
                   SDK MW+Nintendo+PiaTransport-5_37_2
                   SDK MW+Nintendo+NEX_DS-4_6_13
                   SDK MW+Nintendo+NEX_R2-4_6_13
                   SDK MW+Nintendo+NEX_RK-4_6_13
                   SDK MW+Nintendo+NEX_CO-4_6_13
                   SDK MW+Nintendo+NEX_SS-4_6_13
                   SDK MW+Nintendo+NEX_UT-4_6_13
                   SDK MW+Nintendo+PiaCommon-5_37_2
                   SDK MW+Nintendo+Pia-5_37_2_58415
                   SDK MW+Nintendo+PiaFramework-5_37_2
                   SDK MW+Nintendo+PiaLan-5_37_2
                   SDK MW+Nintendo+PiaLocal-5_37_2
                   SDK MW+Nintendo+PiaNex-5_37_2-forNEX-4_6_5
                   SDK MW+Nintendo+PiaReckoning-5_37_2
                   SDK MW+Nintendo+PiaSync-5_37_2
                   SDK MW+Nintendo+NEX_MM-4_6_13
                   SDK MW+Nintendo+PiaClone-5_37_2
00:00:01.464 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.517 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_3-Release
00:00:01.517 |I| Loader LoadExeFs: Loading sdk...
00:00:01.637 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.3
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_3-Release
00:00:01.643 |I| Loader PrintRoSectionInfo: subsdk9:
    Module: TestMod_Diamond
00:00:01.643 |I| ModLoader ApplyExefsMods: NSO 'subsdk9' replaced
00:00:01.643 |I| ModLoader ApplyExefsMods: main.npdm replaced
00:00:01.719 |W| Ptc LoadExeFs: Detected unsupported ExeFs modifications. PPTC disabled.
00:00:01.721 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: False).
00:00:01.922 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.924 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.981 |I| Loader LoadNsos: Loading image 2 at 0x000000000d066000...
00:00:01.986 |I| Loader LoadNsos: Loading image 3 at 0x000000000d70c000...
00:00:02.000 |I| Loader LoadNsos: Loading image 4 at 0x000000000e8ca000...
00:00:02.019 |I| ModLoader LoadCheats: Build ids found for title 0100000011D90000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    94CEAE325C205C4B9D6F7235552F28FD00000000000000000000000000000000
    507F19D1240D09D00992248E8A0FD77EBD784EB4000000000000000000000000
    B9318E0F0AC51DBA2C884A3A1A8FABDDBF9D8534000000000000000000000000
    2D369D9999E3E10E665106F840FFFF9BDAA0BB8E000000000000000000000000
00:00:02.019 |I| Loader LoadNca: Application Loaded: Pokémon Brilliant Diamond v1.3.0 [0100000011d90000] [64-bit]
00:00:02.034 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:02.314 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:02.670 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (4.6.0 NVIDIA 515.49.19)
00:00:02.708 |I| GPU.MainThread Gpu LoadShaders: Loading 2831 shaders from the cache...
00:00:10.993 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:12.219 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:12.378 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:12.404 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:12.424 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:12.559 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed. 
00:00:14.543 |S| HLE.OsThread.16 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:14.553 |S| HLE.OsThread.16 ServiceNifm Submit: Stubbed. 
00:00:14.553 |S| HLE.OsThread.16 ServiceNifm GetRequestState: Stubbed. 
00:00:14.554 |S| HLE.OsThread.16 ServiceNifm GetResult: Stubbed. 
00:00:14.653 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:14.714 |S| HLE.OsThread.16 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:14.715 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:14.716 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:17.423 |S| HLE.OsThread.16 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:18.118 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:18.122 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:18.124 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:18.136 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Handheld,Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8
00:00:18.291 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:18.366 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:18.513 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:18.516 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:18.517 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:18.520 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:18.521 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:18.522 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:18.523 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:18.534 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:18.602 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:18.605 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 2
*** stack smashing detected ***: terminated</code></pre></details>

### Environment?

- Ryujinx version: 1.1.500
- Game version: 1.3.0
- System Specs:
  - OS: Arch Linux x64
  - CPU: Ryzen 5 1600
  - GPU: NVIDIA GTX 1050 Ti
  - RAM: 32GiB
- Applied Mods : Yes, see reproduction step

### Additional context?

- Removing the exefs mod works fine
- Exefs mod works fine on Switch (same firmware)

**Comment by gdkchan** [comment]
The mod is looking for a `sd:/shaders/imgui.bin` file. Since it does not exist, it crashes. Creating an empty file with that name inside a shaders folder on the SD card folder allows it to proceed (although I'm guessing the mod should provide that file?). It doesn't look like an emulator issue.

**Comment by Martmists-GH** [comment]
Hmm, I'm sure I placed the file there, maybe reinstalling deleted it?
