### ISSUE TITLE
Shader Compilation Crash on MacOS M1 chip | Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by WALEX2000** [Ryujinx/Ryujinx#4319]
### What's the issue you encountered?

When Launching shader heavy games Ryujinx often crashes while still compiling the shaders.
I first encountered this issue with Mario Kart 8. Ryujinx was compiling around 2000 shaders and would crash amidst the compilation process. The error was a memory Segfault, so I switched the CPU memory management mode from Host Unchecked to Host (fast), and the issue resolved itself.

Next, I attempted to launch Super Smash Bros. Ultimate with 16k shaders, but this time Ryujinx crashed with SIGABRT.

### How can the issue be reproduced?

1. Launch Super Smash Bros. Ultimate with a high number of shaders on MacOS M1
2. Wait for Shader compilation to complete
3. The App will likely crash before the shader compilation process is complete

### Log file

Crash Report was too large so I've put it in this file:

[Crash_Report.txt](https://github.com/Ryujinx/Ryujinx/files/10462056/Crash_Report.txt)

### Environment?

- Ryujinx version: 1.1.0-macos1
- Game version: 1.0.0
- System Specs:
  - OS: MacOS Venture 13.1
  - CPU: M1 Max SOC
  - GPU: M1 Max SOC
  - RAM: 32GiB
- Applied Mods : No

**Comment by pfranklin0315** [comment]
I am having the same issue, did you ever find a fix?

**Comment by WALEX2000** [comment]
Not really. Just deleted the entire shader cache folder and dealing with shader compilation stutter as it comes.

**Comment by markmaci** [comment]
I'm also having the same issue. It seems to only happen when I use a pre-made shader cache from RyuSAK with ~32000 shaders. When I load a shader cache that I built just by playing naturally (~4000 shaders), they load just fine.

**Comment by MetrosexualGarbodor** [comment]
Closing as this is most likely an issue on the user end and no Ryujinx logs have been provided.

**Comment by markmaci** [comment]
@WALEX2000 provided his crash report in the .txt file and I do not think this is a user-end issue

**Comment by MetrosexualGarbodor** [comment]
Mario Kart 8 Deluxe does not have 33k shaders. Stop downloading broken caches off the internet and you'll be fine.
