### ISSUE TITLE
The Ryujinx folder is placed in the user directory when the `~/.config` folder does not exist on macOS

### ISSUE THREAD

**Issue by Candygoblen123** [Ryujinx/Ryujinx#4330]
### What's the issue you encountered?

On macOS, for users that do not have a `~/.config/` folder, the Ryujinx directory is placed at `~/Ryujinx/`.

### How can the issue be reproduced?

On macOS, move or erase your current `~/.config/` folder 

### Log file

There isn't anything extraordinary in the log, so I've decided to omit it.

### Environment?

- Ryujinx version: 1.1.0-macos1</br>
- Game version: N/A</br>
- System Specs:
  - OS: macOS 13.1
  - CPU: Apple M1
  - GPU: Apple M1
  - RAM: 8GB
- Applied Mods : N/A

### Additional context?

Additional info about your environment:</br>
Would be resolved by #4296.

**Comment by AcK77** [comment]
Fixed in #4296
