### ISSUE TITLE
Pokemon-Brilliant-Diamond stock on the save page...

### ISSUE THREAD

**Issue by BensonChiangTW** [Ryujinx/Ryujinx#4338]
### What's the issue you encountered?

When i tried to save (on later on get the running shoes from mom), it just stock there... but the games seems still working fine, I can still see the screen moving ok.

<img width="1292" alt="Screenshot 2023-01-23 at 15 08 34" src="https://user-images.githubusercontent.com/123390428/214076450-df452549-0644-4d4d-b072-675fc43b34d8.png">

### Log file

[Ryujinx_ 1.1.0-macos1_2023-01-23_15-15-57.log](https://github.com/Ryujinx/Ryujinx/files/10480992/Ryujinx_.1.1.0-macos1_2023-01-23_15-15-57.log)

### Environment?

- Ryujinx version: 1.0.X</br>
1.1.0
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: 12.6 (Mac)
  - CPU: 2.9 GHz Quad-Core Intel Core i7
  - GPU: Radeon Pro 560 4 GB
Intel HD Graphics 630 1536 MB
  - RAM: 16GB
- Applied Mods : No

**Comment by MutantAura** [comment]
Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues
