### ISSUE TITLE
Regression: Vertex explosions in XBDE and XB2 since 1.1.497 when using Vulkan

### ISSUE THREAD

**Issue by mulchingscoop** [Ryujinx/Ryujinx#4341]
### What's the issue you encountered?

Vertex explosions in XBDE and XB2 when using Vulkan in 1.1.497 or higher. Works fine in OpenGL.

### How can the issue be reproduced?

Launch XBDE or XB2 in Vulkan. Not reproducible in 1.1.496 or lower.

1.1.497:

![ryujinx_capture_1 1 497_vulkan_xbde](https://user-images.githubusercontent.com/123562435/214578558-01d8eacf-dbe3-4038-8ea5-702d4746da6e.png)

![ryujinx_capture_1 1 497_vulkan_xb2](https://user-images.githubusercontent.com/123562435/214578723-1369360a-ebb6-4b2b-b326-86afb4845d00.png)

1.1.496:

![ryujinx_capture_1 1 496_vulkan_xbde](https://user-images.githubusercontent.com/123562435/214578856-368629ec-d4aa-4e10-840d-306509711302.png)

![ryujinx_capture_1 1 496_vulkan_xb2](https://user-images.githubusercontent.com/123562435/214578991-7379f9d6-02f2-4031-bfcc-afe4036ac2eb.png)

### Environment?

- Ryujinx version: 1.1.595</br>
- Game version: 1.1.2 (XBDE) / 2.0.2 (XB2)</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *Ryzen 3600*
  - GPU: *NVIDIA GTX 1660 SUPER (Vulkan v1.1.119, Driver v441.8.0.0)*
  - RAM: *16GiB*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
I am essentially stuck on an older driver version because of some other software compatibility issues unrelated to the emulator.

**Comment by Bjorn29512** [comment]
pls update your drivers they are extremely old and test again.

**Comment by Bjorn29512** [comment]
i have not been able to replicate this on my gpu which is the same as yours but on latest drivers. 
![image](https://user-images.githubusercontent.com/110204265/214587923-425f10a3-6caa-4382-9011-c0cb5fe0046b.png)
![image](https://user-images.githubusercontent.com/110204265/214588087-94685321-464f-4915-a912-1890e7a5f701.png)
so its likely the drivers, does it happen as soon as you load in or is it random ?

**Comment by Bjorn29512** [comment]
> Definitely not random. This happens on every launch.
Yeh i dont seem to get it, seems like dated drivers is likely the here.

**Comment by MetrosexualGarbodor** [comment]
> Thought this is worth a shot because there is an open PR about relaxing vulkan requirements.

Have you tried on that PR then?

**Comment by MutantAura** [comment]
Closing as a won't fix then I guess.
