### ISSUE TITLE
Crash when opening settings, games and Mii editor

### ISSUE THREAD

**Issue by MatfenV1** [Ryujinx/Ryujinx#4344]
### What's the issue you encountered?

Last month I never had any problems with Ryujinx, everything worked fine. But now in the latest versions of the past few weeks, Ryujinx crashes always when I try to lauch a game, open settings menu or the Mii editor. I've reinstalled Ryujinx again and the issue still persists in V1.1.595. 

### How can the issue be reproduced?

 1. Launch Ryujinx
 2. Launch a game, open the Mii editor via the 'Load applet' tab or open settings under the 'Option' tab.
 3. Ryujinx closes itselfs and nothings happens

### Log file
I have included 3 log files:
[Ryujinx_1.1.592_2023-01-23_17-52-26 crash open settings.log](https://github.com/Ryujinx/Ryujinx/files/10513205/Ryujinx_1.1.592_2023-01-23_17-52-26.crash.open.settings.log)
[Ryujinx_1.1.592_2023-01-23_17-55-04 crash open mii editor.log](https://github.com/Ryujinx/Ryujinx/files/10513206/Ryujinx_1.1.592_2023-01-23_17-55-04.crash.open.mii.editor.log)
[Ryujinx_1.1.592_2023-01-23_18-01-03 crash open Pokemon Violet.log](https://github.com/Ryujinx/Ryujinx/files/10513207/Ryujinx_1.1.592_2023-01-23_18-01-03.crash.open.Pokemon.Violet.log)

### Environment?

- Ryujinx version: 1.1.592 - 1.1.595</br>
- Game version: 1.0.0?</br>
- System Specs:
  - OS: Windows 11
  - CPU: AMD Ryzen 5 4600H
  - GPU: NVIDIA GTX 1650
  - RAM: 16GiB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
/ No relevant information, ask me if you need extra info about the problem... :)

**Comment by AcK77** [comment]
Your log files doesn’t contains any error. I suggest you to run Ryujinx through the command line to see if it print an error and give us a feedback. Thanks.

**Comment by MatfenV1** [comment]
> Your log files doesn’t contains any error. I suggest you to run Ryujinx through the command line to see if it print an error and give us a feedback. Thanks.

Now it gives an error in the logs:
[Ryujinx_1.1.596_2023-01-27_09-15-22.log](https://github.com/Ryujinx/Ryujinx/files/10516853/Ryujinx_1.1.596_2023-01-27_09-15-22.log)
Everything works now but only when using OpenGL (with lots of lag)

**Comment by MutantAura** [comment]
Update **both GPU drivers** from AMD and NVIDIA respectively. 
Latest NVIDIA drivers: https://www.nvidia.com/download/index.aspx
Latest AMD Radeon Drivers: https://www.amd.com/en/support
If this does not help Vulkan applications then follow these steps: https://nvidia.custhelp.com/app/answers/detail/a_id/5182/ 

Use our discord for further support queries: https://discord.gg/ryujinx
