### ISSUE TITLE
Ryujinx crashes when loading a game with the Vulkan backend

### ISSUE THREAD

**Issue by arichmondphoto** [Ryujinx/Ryujinx#4348]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description of Issue

Ryujinx emulator crashes when loading a game. When the software is set to use an OpenGL backend, the games run fine. Vulkan backend was working fine before I upgraded to mesa 22.3.3-2 and Ryujinx 1.1.596.

To replicate the bug, start the Ryujinx software and start a game. After shaders compile and PPTC caching, the application will hang before exiting on it's own.

There is nothing in the log file to indicate what the problem is. Starting the emulator from the terminal allowed me to catch the following snippet when the app crashed, which was not recorded in the Ryujinx log file:

```
Ryujinx: ../mesa-22.3.3/src/vulkan/runtime/vk_image.c:494: vk_image_view_init: Assertion `driver_internal || !(image_view->usage & ~image_usage)' failed.
^Czsh: IOT instruction (core dumped)  ./Ryujinx
```

Running the app with validation layers enabled as an environment variable gives the following:

```
        [0] 0x7ee248de85d0, type: 6, name: NULL
VUID-VkImageViewCreateInfo-pNext-02662(ERROR / SPEC): msgNum: -55646969 - Validation Error: [ VUID-VkImageViewCreateInfo-pNext-02662 ] Object 0: handle = 0xfd01b30000003f7c, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfcaee507 | vkCreateImageView(): pNext chain includes VkImageViewUsageCreateInfo and image was not created with a VkImageStencilUsageCreateInfo in pNext of vkImageCreateInfo, usage must not include any bits that were not set in VkImageCreateInfo::usage used to create image The Vulkan spec states: If the pNext chain includes a VkImageViewUsageCreateInfo structure, and image was not created with a VkImageStencilUsageCreateInfo structure included in the pNext chain of VkImageCreateInfo, its usage member must not include any bits that were not set in the usage member of the VkImageCreateInfo structure used to create image (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-pNext-02662)
    Objects: 1
        [0] 0xfd01b30000003f7c, type: 10, name: NULL 
```

I opened an issue at the mesa GitLab and they say this seems to be invalid API usage and is therefore not a driver issue.
Link to mesa GitLab ticket: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8174 

### Reproduction Steps

Open Ryujinx and ensure Vulkan backend is selected. Start a game. After shaders compile and PPTC cache is complete, the application will hang before exiting on its own.

### Log File

[Ryujinx_1.1.596_2023-01-28_10-21-57.log](https://github.com/Ryujinx/Ryujinx/files/10527694/Ryujinx_1.1.596_2023-01-28_10-21-57.log)

### OS

Linux 6.1.7-1-MANJARO

### Ryujinx version

1.1.596

### Game version

2.1.0

### Environment?

Intel NUC 8 Hades Canyon NUC8i7HVK
CPU: i7-8809G
GPU: Radeon RX Vega M GH
RAM: 64GB
No Mods

**Comment by arichmondphoto** [comment]
Issue not happening on flatpak build. Unsure of the original cause, but the problem persists on standard builds. Flatpak is working fine for me with no other changes to my system.

**Comment by NotTristanN64** [comment]
idk what to do

**Comment by NotTristanN64** [comment]
im trying to play crash 4 but it kepts crashing when i press continue at language select
