### ISSUE TITLE
Skyline crashes on ARM macOS with Hypervisor or Host memory mode

### ISSUE THREAD

**Issue by tech-ticks** [Ryujinx/Ryujinx#4354]
### Description of Issue

The [Skyline](https://github.com/skyline-dev/skyline) modding framework crashes on ARM macOS when either the Hypervisor or any Memory Manager mode other than Software is used.

### Reproduction Steps

1. Download the latest Skyline beta from https://github.com/skyline-dev/skyline/releases/tag/beta
2. Right-click *Super Smash Bros. Ultimate* in the game list and select *Open Atmosphere Mods Directory*
3. Copy the `exefs` folder in the downloaded .zip to this directory
4. Start the game with the Hypervisor or any Memory Manager mode other than Software

Note that this crash is triggered by the Skyline mod loader itself even with if no other mods like Arcropolis are loaded.

### Log File

Crash with Hypervisor:
[Ryujinx_1.0.0-dirty_2023-01-31_21-13-44.log](https://github.com/Ryujinx/Ryujinx/files/10550542/Ryujinx_1.0.0-dirty_2023-01-31_21-13-44.log)

Crash with Host Memory Manager mode:
[Ryujinx_1.0.0-dirty_2023-01-31_21-14-23.log](https://github.com/Ryujinx/Ryujinx/files/10550560/Ryujinx_1.0.0-dirty_2023-01-31_21-14-23.log)

Crash with Host unchecked Memory Manager mode:
[Ryujinx_1.0.0-dirty_2023-01-31_21-16-41.log](https://github.com/Ryujinx/Ryujinx/files/10550575/Ryujinx_1.0.0-dirty_2023-01-31_21-16-41.log)

### OS

macOS Ventura 13.2

### Ryujinx version

Commit 9044cb38d19194bb29595ac09cad8857364650b2

### Game version

1.0.0

### Environment?

- ##### CPU: Apple M2 Max
- ##### GPU: Apple M2 Max
- ##### RAM: 32 GB
- Applied Mods: Skyline

**Comment by gdkchan** [comment]
I'm not sure if it's possible to make it work on host mapped mode since macOS has 16 KB pages on Arm, and it will try to map the code memory on a address that may not be 16 KB aligned. It should work on the Hypervisor though, will need to take a look to see why it doesn't.

**Comment by tech-ticks** [comment]
I've experimented with host mapped mode a bit, seems like forcing Skyline use a 16 KB-aligned destination address in the `svcMapProcessMemory` call doesn't help either. I guess this doesn't necessarily mean that the physical address on the host has the correct alignment as well? It's possible that I did something wrong though, I'm not really familiar with this part of the Skyline code base.

**Comment by gdkchan** [comment]
I took a look at the hypervisor issue, and it appears to be an issue on skyline side. The invalid access comes from a `DC CVAU` data cache invalidation instruction. Looks like it performs data cache invalidation on unmapped memory. It's not a problem with the JIT because it does not really the data cache maintenance instructions.

The invalidation with unmapped memory seems to come from here:
https://github.com/skyline-dev/skyline/blob/e831ae3899268a54ae7abbb112f40b9022e4a89e/source/skyline/inlinehook/And64InlineHook.cpp#L485
It is unmapped here when the memory is transitioned to writable:
https://github.com/skyline-dev/skyline/blob/e831ae3899268a54ae7abbb112f40b9022e4a89e/source/skyline/nx/kernel/jit.c#L95
So my guess is that the `JitType_CodeMemory` mode is broken.

**Comment by gdkchan** [comment]
> I've experimented with host mapped mode a bit, seems like forcing Skyline use a 16 KB-aligned destination address in the `svcMapProcessMemory` call doesn't help either. I guess this doesn't necessarily mean that the physical address on the host has the correct alignment as well? It's possible that I did something wrong though, I'm not really familiar with this part of the Skyline code base.

The emulator physical memory allocation is also not 16 KB aligned. We should probably enforce physical memory allocations to be 16 KB aligned when using host mapped mode on platforms with 16 KB pages.

**Comment by tech-ticks** [comment]
> I took a look at the hypervisor issue, and it appears to be an issue on skyline side. The invalid access comes from a `DC CVAU` data cache invalidation instruction. Looks like it performs data cache invalidation on unmapped memory. It's not a problem with the JIT because it does not really implement the data cache maintenance instructions.
> 
> The invalidation with unmapped memory seems to come from here: https://github.com/skyline-dev/skyline/blob/e831ae3899268a54ae7abbb112f40b9022e4a89e/source/skyline/inlinehook/And64InlineHook.cpp#L485 It is unmapped here when the memory is transitioned to writable: https://github.com/skyline-dev/skyline/blob/e831ae3899268a54ae7abbb112f40b9022e4a89e/source/skyline/nx/kernel/jit.c#L95 So my guess is that the `JitType_CodeMemory` mode is broken.

Thanks for investigating this, removing the invalidation code seems to fix the issue without any negative side effects at least with my simple mod. This should be safe too since [`svcUnmapCodeMemory` should invalidate the entire instruction cache anyway](https://github.com/Atmosphere-NX/Atmosphere/blob/8176f085f134007b99df79013c6ec76bdea38bf3/libraries/libmesosphere/source/kern_k_page_table_base.cpp#L998). Is this also the case in Ryujinx? Just asking to make sure since this was missing in Yuzu, which caused issues some time ago, and I can't find it in the code at a glance.

**Comment by gdkchan** [comment]
> Is this also the case in Ryujinx?

Not on the hypervisor. On the JIT it always invalidates the unmapped memory ranges on the JIT cache.
There's a `InvalidateCacheRange` method on the CpuContext, but it's currently unused, and it does nothing on the hypervisor https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Cpu/AppleHv/HvCpuContext.cs#L34

**Comment by Ghussy** [comment]
Just to clarify, this is a problem with Skylines data cache invalidation, and not Ryujinx hypervisor?

**Comment by gdkchan** [comment]
I think so yea. Although I think on the Switch it uses the code memory syscalls to map a mirror of the region that it wants to modify as R/W. This requires a kernel patch that is normally disabled on the emulator (except for homebrew), so right now it is using a different code path in the emulator, that's probably why it works on the Switch.

**Comment by gdkchan** [comment]
#5518 might have fixed it on hypervisor. Can someone check?

**Comment by TSRBerry** [comment]
Fixed by #5518
