### ISSUE TITLE
Fire Emblem Engage Mod Useless

### ISSUE THREAD

**Issue by ForbAvalon** [Ryujinx/Ryujinx#4370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

I place some layeredfs mod in mod directory but not reflected in game.
The same mod in usable in Yuzu.
[Mod Directory]\romfs\Data\StreamingAssets\aa\Switch\fe_assets_gamedata

But IPS mod can work well like 60fps mod.
[Mod Directory]\exefs

### Reproduction Steps

Just place mod in the directory - restart ryujinx - launch game - test the effect

### Log File

[https://drive.google.com/file/d/1xjvJ7YUW4oQ_ynWYR0PklFtEl3iKKhJ9/view?usp=sharing](url)

### OS

Windows 10

### Ryujinx version

1.1.599

### Game version

1.1.0

### Environment?

- ##### CPU: I7-9750H
- ##### GPU: RTX 2060
- ##### RAM: 16GiB
- Applied Mods: Yes, a self-made mod that modified some gamedata

**Comment by MetrosexualGarbodor** [comment]
For support and technical issues, please come to our Discord server. https://discord.gg/ryujinx
