### ISSUE TITLE
Contra Rogue Corps crashed on Ryujinx 1.1.0 mac

### ISSUE THREAD

**Issue by anatblsv** [Ryujinx/Ryujinx#4375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Hello! After starting game few seconds black screen and crash it.

Started as native mode, also in rosetta mode.

### Reproduction Steps

Start game, wait few seconds, this time shows black screen and crashed it.

### Log File

Process: Application, PID: 93
   0x000000000b764ec0	sdk:0x175ec0	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   0x000000000b764f84	sdk:0x175f84	
   0x000000000b765020	sdk:0x176020	nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   0x000000000b681c10	sdk:0x92c10	nn::audio::OpenAudioOut(nn::audio::AudioOut*, nn::os::SystemEvent*, char const*, nn::audio::AudioOutParameter const&)
   0x000000000879caa0	main:0x798aa0	
   0x000000000871656c	main:0x71256c	
   0x00000000087162d8	main:0x7122d8	
   0x0000000008717ae8	main:0x713ae8	
   0x0000000008709c1c	main:0x705c1c	
   0x0000000008724564	main:0x720564	
   0x000000000b90c4d8	sdk:0x31d4d8	
   0x000000000b910938	sdk:0x321938	
   0x0000000000000000

00:00:11.616 |I| HLE.GuestThread.33 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000001199c4bc48 (SP:-0x01a8)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000001199c4bc48 (SP:-0x01a8)
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000018
	X[11]:	0x0000000000800000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x000000000b7665c0 (sdk:0x1775c0)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000c192f68
	X[18]:	0x0000000000000000
	X[19]:	0x0000001199c4bc48 (SP:-0x01a8)
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x000000000bf56d76
	X[23]:	0x000000000bf56d76
	X[24]:	0x0000001199c4bc10 (SP:-0x0170)
	X[25]:	0x000000000bf56d76
	X[26]:	0x000000000bf56d76
	X[27]:	0x0000000000050020
	X[28]:	0x00000000000000ff
	FP:	0x0000001199c4baa0 (SP)
	LR:	0x000000000b7665dc (sdk:0x1775dc)	=> nn::diag::detail::Abort(nn::Result const*):0x001c
	SP:	0x0000001199c4baa0 (SP)
	PC:	0x000000000b960044 (sdk:0x371044)	=> 

00:00:11.619 |W| HLE.GuestThread.19 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.619 |W| HLE.GuestThread.18 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.619 |W| HLE.GuestThread.16 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.620 |W| HLE.GuestThread.20 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.620 |W| HLE.GuestThread.26 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.620 |W| HLE.GuestThread.21 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.620 |W| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.621 |W| HLE.GuestThread.30 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.621 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.621 |W| HLE.GuestThread.22 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.621 |W| HLE.GuestThread.32 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.622 |W| HLE.GuestThread.38 KernelSvc : ArbitrateLock() = ThreadTerminating
00:00:11.622 |W| HLE.GuestThread.35 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.34 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.37 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.40 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.39 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.41 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.43 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.623 |W| HLE.GuestThread.42 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:11.748 |E| HLE.GuestThread.33 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/Ryujinx.Horizon.Generators/Ryujinx.Horizon.Generators.Kernel.SyscallGenerator/SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/Ryujinx.Horizon.Generators/Ryujinx.Horizon.Generators.Kernel.SyscallGenerator/SyscallDispatch.g.cs:line 3424
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/ARMeilleure/Instructions/NativeInterface.cs:line 50

### OS

Mac OS 13.1 (Ventura)

### Ryujinx version

1.1.0

### Game version

1.0.0-1.3.0

### Environment?

- ##### CPU: *M1 Max*
- ##### GPU: *M1 Max* (Vulkan)
- ##### RAM: *32GB*
- Applied Mods: [ No ]

**Comment by AcK77** [comment]
The log file is incomplete, try to use SDL2 Audio Backend.

**Comment by anatblsv** [comment]
> The log file is incomplete, try to use SDL2 Audio Backend.

Thanks! I switched audio to SDL2 and it work!!! Thank you very much!
