### ISSUE TITLE
Cappy appears to flicker in Super Mario Odyssey

### ISSUE THREAD

**Issue by ArbestRi** [Ryujinx/Ryujinx#4381]
### Description of Issue

In Super Mario Odyssey, in the Cap Kingdom map Cappy appears to flicker.

### Reproduction Steps

GO into Cap Kingdom and get to the cutscenes
Here is a video of the problem:

https://user-images.githubusercontent.com/86171223/217403995-aa2f4a1d-37e2-42e0-bfff-f43326b0cefc.mp4

### Log File

I don't have one

### OS

Windows 11

### Ryujinx version

1.1.604 (Avilonia)

### Game version

1.2.0?

### Environment?

- ##### CPU: *i7-10700F*
- ##### GPU: *(NVIDIA RTX 2060 SUPER)*
- ##### RAM: *(16GB)*
- Applied Mods: [No ]

**Comment by AcK77** [comment]
Without a log file, it will be hard to track things. What are your specs ?
