### ISSUE TITLE
Matches of ARMS crashes the game

### ISSUE THREAD

**Issue by RukGoodMan** [Ryujinx/Ryujinx#4386]
### Description of Issue

If you try to play a match of ARMS the game crash and it closes.
I don't know if it's my PC, but isn't a bad one, and other games work perfectly.

### Reproduction Steps

Just if you enter a match of Grand Prix, Versus, etc, the game close. You can choose character but not play. In 1.0.0 and 5.4.0

### Log File

[Ryujinx_1.1.608_2023-02-08_21-45-16.log](https://github.com/Ryujinx/Ryujinx/files/10689805/Ryujinx_1.1.608_2023-02-08_21-45-16.log)

### OS

Windows 10

### Ryujinx version

1.1.608

### Game version

1.0.0 and 5.40

### Environment?

- ##### CPU: *i5-9600*
- ##### GPU: *NVIDIA RTX 3060*
- ##### RAM: *16GB*
- Applied Mods: No

### Additional context?

I forgot to say this: the only thing you can play is the tutorial. I don't know if this is important.

**Comment by gdkchan** [comment]
Does it happen with resolution scale set to native?

**Comment by RukGoodMan** [comment]
No! It doesn't happen! Thank you very much!
