### ISSUE TITLE
FE: Engage, experiencing more texture glitches after upgrading from 1.1.604 to 1.1.608

### ISSUE THREAD

**Issue by H-Toine** [Ryujinx/Ryujinx#4388]
### Description of Issue

After upgrading from Ryujinx 1.1.604 to 1.1.608, I've been experiencing many more graphical texture errors.

Below an example of how it looks during battle (chapter 21): 

**Epilepsy warning!**

https://user-images.githubusercontent.com/25739208/217656902-ffc298db-a10b-4d85-8133-47b544ade1cb.mp4

1.1.604 and lower had some graphical errors, but those were once every few hours (About 6x in 48 hours). They also looked different (Haven't had these happen yet in 1.1.608, but that doesn't say much) :
![7de0426dfbeb1f100cceaab891141f25c6f63365](https://user-images.githubusercontent.com/25739208/217657808-4184c3ba-e926-4ee6-be22-a60d3b90d5ef.jpg)

### Reproduction Steps

Not sure what triggers it, but it seems to happen mainly in Somniel, and during battle after some time. Had it happen multiple times within 10 minutes by walking around/teleporting around the Somniel.

### Log File

[Ryujinx_1.1.608_2023-02-08_21-39-38.log](https://github.com/Ryujinx/Ryujinx/files/10690021/Ryujinx_1.1.608_2023-02-08_21-39-38.log)

### OS

Windows 11

### Ryujinx version

1.1.608

### Game version

Fire Emblem Engage 1.1.0 (With Wave 1 DLC)

### Environment?

- ##### CPU: *Ryzen R9 5900X*
- ##### GPU: *NVIDIA GTX 1080*
- ##### RAM: *(e.g. 32GB)*
- Applied Mods: [ No ]

**Comment by gdkchan** [comment]
Does it happen with resolution scale set to native?

**Comment by H-Toine** [comment]
> Does it happen with resolution scale set to native?

Currently running on:
- 3x Resolution Scale (2160p/3240p)
- Anisotropic Filtering on Auto
- [X] Enable Shader Cache
- [  ] Enable Texture Recompression
- [X] Enable Macro HLE

**Comment by Squall-Leonhart** [comment]
That wasn't what you were asked.

**Comment by H-Toine** [comment]
> That wasn't what you were asked.

3x resolution scale is not native, right? Just added some extra info as well.

> And the video driver is old.

That's true. I did miss the last driver update now that you mention it. I'll try it again later today after updating the driver. The issues started happening right after updating Ryujinx.

**Comment by H-Toine** [comment]
I really seemed to be unable to correctly read the native resolution question. Sorry about that!

I have updated drivers and updated to the latest Ryujinx version (1.1.614 as of now), and the same issue hasn't popped up yet.

I did get a crash after running around Somniel for 5 mins and then teleporting to the ring chamber, but I haven't been able create a reproducible set of steps of that yet. 

```
00:04:21.190 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 180
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 66
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, PhysicalDevice physicalDevice, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 148
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 115
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 400
   at System.Threading.Thread.StartCallback()
```

I'll close this issue for now. If I can reproduce the above ErrorOutOfDeviceMemory, then I'll open up a separate issue for that.

**Comment by H-Toine** [comment]
Well, I'm re-opening as it seems I can _kind of_ reproduce it (textures corrupting + out of memory error).

I spawn in on Somniel,
Open a shop (or multiple)
Keep scrolling through the characters in the shop UI, making sure that their model loads before scrolling to the next.  (scrolling top to bottom about 10x)
Teleport to Ring chamber
Repeat a few times if necessary.

Eventually, the textures seem to get corrupted, and by moving around a lot/opening menus/teleporting around Somniel, the game crashes with the above mentioned **Unexpected API error "ErrorOutOfDeviceMemory".**

![Ryujinx_lL419eDEf4](https://user-images.githubusercontent.com/25739208/217902422-5c00b3ab-6601-4b0d-a306-8e6a92f51cfd.jpg)
![Ryujinx_zvdiJ3lFEs](https://user-images.githubusercontent.com/25739208/217902426-a4989743-f78d-49aa-9c3c-08894c38089f.jpg)
![Ryujinx_zxbEenb3Q7](https://user-images.githubusercontent.com/25739208/217902435-cab78afd-922a-4f1a-aca8-be9badbac99f.jpg)

[Ryujinx_1.1.614_2023-02-09_19-05-59.log](https://github.com/Ryujinx/Ryujinx/files/10700338/Ryujinx_1.1.614_2023-02-09_19-05-59.log)


I'll test the same with native resolution.

**Comment by H-Toine** [comment]
Native does resolution seems stable after playing (loading/scrolling through unit lists/running around) for 20+ minutes (which is much longer than with 3x resolution scale). 

I'll keep playing for a while and see if anything memory/texture related occurs in native.

**Comment by GamerzHell9137** [comment]
The reaction is normal tho. 8 GB VRAM is probably not enough for x3 and its leaking over and introducing issues. You can either enable texture recompression or play on OpenGL since it probably won't happen there.

**Comment by Linktothepast** [comment]
1.1.606 Seems to be the commit that causes this issue after some testing.

**Comment by gdkchan** [comment]
This looks like the texture corruption that happens on NVIDIA when you get close to filling all the VRAM. Probably not an emulator issue although it`s possible that some recent change increased VRAM usage a bit and made it more likely to happen.
You can:
- Play at native resolution to reduce VRAM usage.
- Enable texture recompression to further reduce VRAM usage. Maybe with that enabled you can use resolution scaling.
- Use OpenGL that can move textures out of VRAM, so crashes due to lack of memory are less likely.

**Comment by Linktothepast** [comment]
I am already playing at native with texture recompression.  Previous to 1.1.606 seems fine though with the same settings.

**Comment by Squall-Leonhart** [comment]
> This looks like the texture corruption that happens on NVIDIA when you get close to filling all the VRAM. Probably not an emulator issue although it`s possible that some recent change increased VRAM usage a bit and made it more likely to happen.

I do wish nvidia had a Heap type that combined Local+System like their D3D11 and OpenGL UMD's do.

**Comment by GamerzHell9137** [comment]
> I am already playing at native with texture recompression. Previous to 1.1.606 seems fine though with the same settings.

There's no need for texture recompression on native if you're on a 8 GB card.

**Comment by Radinax** [comment]
I'm presenting the same problems, after Ryujinx update yesterday (2/10/2023), it started giving the error:

**Unexpected API error "ErrorOutOfDeviceMemory"**

I played 5 hours straight the day before without a single crash, after the update I play like 20 minutes and it gives this error for Fire Emblem Engage.

**Comment by Bjorn29512** [comment]
> I'm presenting the same problems, after Ryujinx update yesterday (2/10/2023), it started giving the error:
> 
> **Unexpected API error "ErrorOutOfDeviceMemory"**
> 
> I played 5 hours straight the day before without a single crash, after the update I play like 20 minutes and it gives this error for Fire Emblem Engage.

Enable texture recompression

**Comment by H-Toine** [comment]
I can confirm enabling texture recompression, or lowering resolution scaling fixes the issue.

Something did change in (probably) version 1.1.606 that increases VRAM usage, and I'm not sure if this needs to be taken a look at, or of this issue should be closed (as there is a fix/workaround by changing options to lower VRAM usage).

**Comment by Radinax** [comment]
> > I'm presenting the same problems, after Ryujinx update yesterday (2/10/2023), it started giving the error:
> > **Unexpected API error "ErrorOutOfDeviceMemory"**
> > I played 5 hours straight the day before without a single crash, after the update I play like 20 minutes and it gives this error for Fire Emblem Engage.
> 
> Enable texture recompression or reduce scaling to 2x

Oh thanks! Played four hours straight after doing this change and it works now

**Comment by marysaka** [comment]
I think it can be closed.

If this happens to anyone seeing this:
- Enable Texture Recompression 
- Lower resolution
