### ISSUE TITLE
[Black Textures and missing effects] <Metroid Prime Remastered>

### ISSUE THREAD

**Issue by fl1ppyXD** [Ryujinx/Ryujinx#4392]
### Description of Issue

Primarily Samus and some other models have black textures almost always, under specific lighting the normal texture actually pops up but even then it is not "rendered" completely right. Happens on both Vulkan and OpenGL.
![6324643663634664343](https://user-images.githubusercontent.com/32999893/217843078-8826c628-1abc-4a81-9515-63a268ac2d58.png)

In the first level of the game there should be some kind of fog and other effects near the waterfall but none are rendered both on Vulkan and OpenGL.
Correct rendering - 
![7457475745745](https://user-images.githubusercontent.com/32999893/217843140-f5e95d72-e3b0-48c3-81d7-6e1703472000.jpg)

Ryujinx rendering - 
![image](https://user-images.githubusercontent.com/32999893/217843456-7740eea5-b880-47bd-9a32-94d0abc10577.png)

### Reproduction Steps

Just playing the game.

### Log File

[Ryujinx_1.1.614_2023-02-09_14-41-50.log](https://github.com/Ryujinx/Ryujinx/files/10698249/Ryujinx_1.1.614_2023-02-09_14-41-50.log)

### OS

Windows 10

### Ryujinx version

1.1.614

### Game version

1.0 

### CPU

9700K

### GPU

RTX 2060 SUPER

### RAM

16GB

### Applied Mods?

- [ ] Yes

**Comment by GamerzHell9137** [comment]
The github is not used to report a state of the game, only for regressions if they happened.

The compat list github is used for that.

The thread for Metroid Prime: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4411
