### ISSUE TITLE
[Regression] Resolution scaler no longer functions for PMD: Rescue Team DX.

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx#4396]
### Description of Issue

Regression since: #4364 

Likely affects other titles that started to scale with the merge of #2860 

1.1.604 (2x):
![ryujinx_capture_2023-02-09_20-35-38](https://user-images.githubusercontent.com/44103205/217934947-9d3989a0-093f-405d-a540-36ebc627c665.png)

1.1605 (2x):
![ryujinx_capture_2023-02-09_20-43-33](https://user-images.githubusercontent.com/44103205/217934967-edf8f60e-41fd-41d6-9f7e-acd812d4c061.png)

### Reproduction Steps

Most noticeable with the [disable blur mod](https://cdn.discordapp.com/attachments/1020349193421856768/1020349391665627196/PMDRTDX_BlurRemoval_ByDetero.zip) but should be noticeable either way. I own Rescue Team DX which I noticed it in but could affect other games like Rune Factory 5 that started to scale with the merge of #2860.

Can also enter a dungeon in handheld mode (also removes blur) and then scale to easily see.

### Log File

[Ryujinx_1.0.0-dirty_2023-02-09_20-42-59.log](https://github.com/Ryujinx/Ryujinx/files/10701371/Ryujinx_1.0.0-dirty_2023-02-09_20-42-59.log)

### OS

Windows 11

### Ryujinx version

1.1.614

### Game version

1.0.2

### CPU

Ryzen 5 5600X

### GPU

NVIDIA RTX 3070

### RAM

32GB

### List of applied mods

[disable blur](https://cdn.discordapp.com/attachments/1020349193421856768/1020349391665627196/PMDRTDX_BlurRemoval_ByDetero.zip) 

### Additional context?

Pull request that caused regression: #4364 
Pull request that originally allowed scaling: #2860

**Comment by GamerzHell9137** [comment]
Seems like all of the games that had the upscaler fixed on them are broken too, Bubble Bobble and RF5 including.
Weirdly enough Monopoly Madness is fine but it might be that its less impacted than the other named games. On Bubble Bobble its really visible.

![image](https://user-images.githubusercontent.com/2002038/220202576-29c7b0b4-35b1-41f8-87fe-ee41d82555db.png)

Also it added black pixel lines on the right side of the screen.
