### ISSUE TITLE
[Bug] Data loss with crash or incorrect game saving

### ISSUE THREAD

**Issue by asandyguy** [Ryujinx/Ryujinx#4397]
### Description of Issue

There is a problem with saving in a few games, so far only Zelda Breath of the Wild and Star Kirby, sav. can be read immediately, but the data will be lost after exiting game. Not sure if autosave has this problem.

(my god can anyone help me out?  really need a safety insurance against game crash with data loss!)

### Reproduction Steps

1. Select a manual file to read - start game
2. Save the game
3. Ensure Loading and saving interface displayed normally
4. Exit the game or close Ryujinx completely, next play sav. will lost

notes:These pics specifically show how to locate the file,
and the process difference between two data after the game is saved. One of the pictures shows that the files in the \0 directory are not overwritten correctly, it will be restored after crashing or exiting the emu process. though these small problems, add up more, the development cannot be ignored. 

![detail1](https://user-images.githubusercontent.com/124961320/218004287-3d3154fa-a51c-4a78-99d6-8450fb1a7715.png)
![detail2](https://user-images.githubusercontent.com/124961320/218004317-c93fcbbc-1e68-416b-bd76-b4c776994aed.png)
![detail3](https://user-images.githubusercontent.com/124961320/218004361-5d42d5a5-30d0-4da3-bcec-a9a9b9f29406.png)
![detail4](https://user-images.githubusercontent.com/124961320/218004415-e973cffe-a66c-4f05-b269-955e54ae5cfd.png)

### Log File

[Ryujinx_1.1.610_2023-02-10_log1.log](https://github.com/Ryujinx/Ryujinx/files/10703804/Ryujinx_1.1.610_2023-02-10_log1.log)

### OS

Windows 11 home 21h2

### Ryujinx version

1.1.610

### Game version

1.6.0

### CPU

12th Gen Intel (R) i5 -12500h 2.50Ghz

### GPU

Nvidia RTX2050 4GB 45w

### RAM

16GB

### List of applied mods

No mods

### Additional context?

[Zelda BOTW save test.zip](https://github.com/Ryujinx/Ryujinx/files/10711424/Zelda.BOTW.save.test.zip)

**Comment by asandyguy** [comment]
maybe some files in the save directory are not overwritten

**Comment by asandyguy** [comment]
Found something interesting, ryujinx seems to save data in two same directory, one part of the data used for reading, \0 used for storage. If saving incomplete or interrupted, error occur, and save out of sync cause data missing. Sav. not modified during testing, customizing system time have no problem, bug may not occur frequently in short time.

**Comment by mkende** [comment]
I’m facing this same issue with Zelda Breath of the Wild on Ryujinx 1.1.599: well playing Zelda and saving, the savegame correctly appear if I try to load a game. But once I close the game and restart it, the most recent save games where not saved. I updated to 1.1.616 just now and was not yet able to reproduce the issue, but I would guess that it is still here as I don’t see relevant changes in the changelog.

Looking at the data files in the AppData folder under `Ryujinx\bis\user\save\0000000000000001` I see two sub-directory named `0` and `1` and my recent save games are actually in the directory `1`, while the game will open the save games from the directory `0`. My guess is that when writing a save game it’s written first to the directory `1` and then the directories are switched, to avoid data-loss (I’m not sure if it’s a feature of Ryujinx, Zelda or the Switch firmware) but something prevents that directory switch from correctly happening.

If I delete the directory `0` and then start the game, on startup the directory `1` is copied into the directory `0` and my most recent games will appear.

When this bug occurs, nothing is logged in the logs window (and no popup, error message or anything appear either). This is possibly a bug in itself, as warning me of a possible data-loss would be great (I frequently let the emulator run for days without really closing it, so when I do close it and restart I’m potentially loosing days of data).

**Comment by asandyguy** [comment]
'GoodSync' is a performance-sacrificing option, temporarily...

A good idea is to improve ryujinx's log update, ensure the synchronization of user data, add ⚠ warning bar when error occurs, and fix it by modification order.

**Comment by asandyguy** [comment]
invisible issues

**Comment by TheEarthrise** [comment]
I found out that this happens only if you have the used save folder actively opened in Windows Explorer while saving.

Let's assume the following:
- you have opened the following folders in Windows Explorer, while saving BotW:
`..\bis\user\save\<your BotW save folder>\0\2`
`..\bis\user\save\<your BotW save folder>\1\2`

- Your save data is written to `..\2\game_data.sav`

The save data will only be written to `..\1\2\game_data.sav` while `..\0\2\game_data.sav` remains unchanged. If you now stop the emulation and start the game again, the data is read from `..\0\2\game_data.sav` which is outdated.

Do the same again, but have the folders opened as follows:
`..\bis\user\save\<your BotW save folder>\0`
`..\bis\user\save\<your BotW save folder>\1\2`

Now the data is written to both `..2\game_data.sav` files, which you can confirm by comparing the `caption.jpg`.
I have no idea why it behaves like that though, it's weird.

**Comment by asandyguy** [comment]
Sorry this issue is closed, and it's not convenient to reopen...
Can we move to a similar question #4516 , or a similar request #4425  for discussion?

**Comment by asandyguy** [comment]
I found that the save data is lost or outdated frequently after stop emulation, so I open ryujinx\publish\portable\bis\user\save\0000000000000000000X\0 and \1 to find what happened. I sure that there is an error in the \0 directory, sorry that I can't reproduce the situation you mentioned(test on ver.645), but the problem still exists.

**Comment by jinxenyou** [comment]
It's crap! Every time I restart Ryujinx on the steam deck all save data and updates are missing!
