### ISSUE TITLE
[Bug] Strange lines in the game ori and the blind forest

### ISSUE THREAD

**Issue by teddy171** [Ryujinx/Ryujinx#4399]
### Description of Issue

I use ryujinx to run game Ori and the Blind Forest. When I was playing it, there are strange lines under the water. 

https://user-images.githubusercontent.com/77321244/218099702-cc381807-2c32-4c99-858b-acaac6b9063a.mp4

As the video shows, the water doesn't display properly. So it is a bug of Ryujinx or the problem of MoltenVK? Could it been sloved?

### Reproduction Steps

Play ori and the Blind Forest on the ryujinx. (I am not sure whether the problem only happen on macOS or not)

### Log File

[Ryujinx_ 1.1.0-macos1_2023-02-10_20-57-28.log](https://github.com/Ryujinx/Ryujinx/files/10707689/Ryujinx_.1.1.0-macos1_2023-02-10_20-57-28.log)

### OS

Macos

### Ryujinx version

1.1.0-macos 1

### Game version

1.0.0

### CPU

Apple M1 Max

### GPU

Apple M1 Max

### RAM

32GB

### Applied Mods?

- [ ] Yes

**Comment by teddy171** [comment]
![IMG_4231](https://user-images.githubusercontent.com/77321244/218257124-6353975e-15d4-45bc-ad5b-e297308a7ca8.JPG)
This is it really like.

**Comment by MutantAura** [comment]
Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues

**Comment by Squall-Leonhart** [comment]
> Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues

This is a Regression or MoltenVK issue.
