### ISSUE TITLE
[Bug] Unable to install firmware

### ISSUE THREAD

**Issue by Rafraba** [Ryujinx/Ryujinx#4417]
### Description of Issue

I am unable to install the firmware in order to set up the emulator. I know that nothing is wrong with the file am I using because I have set up the emulator with it before recently. When I select "Install firm ware from xci or zip" I am not prompted as usual and instead receive a bug in the ryujinx terminal and the emulator freezes.

### Reproduction Steps

Attempting to install firmware

### Log File

I do not know how to retrieve a log file since the emulator freezes and I then have to close the terminal but a log file is produced upon closing.

### OS

Windows 10

### Ryujinx version

1.1.618

### CPU

i7-8700

### GPU

NVIDIA GTX 1660

### RAM

24GB

**Comment by Rafraba** [comment]
![Ryujinx bug](https://user-images.githubusercontent.com/125316185/218584683-aaf040f8-a58b-49f7-87ca-9a7e9af78afc.PNG)

**Comment by Foul-Tarnished** [comment]
Logs are in the app folder, in "Logs" folder

you need to put your keys in %appdata%/Ryujinx/system/prod.keys first
and then you can install firmware

**Comment by AcK77** [comment]
Without any log file it will be hard to help you.

**Comment by AcK77** [comment]
User don't give much informations anymore. I close it then.
You can join our discord for support and this issue can be reopened if needed.
Thanks
