### ISSUE TITLE
[Feature Request] 5.1 Surround sound support

### ISSUE THREAD

**Issue by Silent-Remux** [Ryujinx/Ryujinx#4422]
### Overview

Currently Ryujinx only seems to output Stereo.

### Smaller details

Yuzu has a option to pick the system sound mode directly, Stereo or Surround.

### Nature of request

Sound.

### Why would this feature be useful?

5.1 support is common place in home setups.

**Comment by turntable97** [comment]
Can't wait for this to be implemented. :)

**Comment by gdkchan** [comment]
I believe this is already supported (it should use 5.1 output as long the audio device being used supports it).

**Comment by Silent-Remux** [comment]
> I believe this is already supported (it should use 5.1 output as long the audio device being used supports it).

This is incorrect. I have Dolby Atmos selected in windows sound settings and I am only get 2.0 channels of sound versus Yuzu's 5.1.

**Comment by gdkchan** [comment]
It should use 5.1 as long the game is outputting 5.1 audio. If the game only has stereo output then it will only have 2 channels.

**Comment by Silent-Remux** [comment]
> 

You can test this with Metroid Prime Remastered main menu music. I assure you there is no output from the surround speakers, only L and R.

**Comment by Ritaku02** [comment]
I seem to have a different problem; I get some sort of surround sound when using OpenAL, but nothing on the center channel, and stuff that are supposed to be coming from behind are coming from directly to the left.

**Comment by jojodunet** [comment]
Why not also adding a feature to test all 5.1 channels in the Ava UI sound menu?

**Comment by jordanvachon** [comment]
yup no direct 5.1

**Comment by ShinKaz** [comment]
same here no 5.1 in BOTW for instance, wish Ryujinx would support this so bad. Thanks for your hard work !

**Comment by samdnz** [comment]
can confirm this is disabled

**Comment by Silent-Remux** [comment]
As of `1.1.783` 5.1 surround sound is still not working. I had hopes as the changelog mentioned changes:
```
AUDIO:
- amadeus: Fix wrong channel mapping check and an old typo.
  - Fixes broken audio in The Legend of Zelda: Tears of the Kingdom.
 ```
 Dolby Atmos is set in Control Panel (7.1 setup, channel upmixer off)
 
 I think Ryu team will need to implement the "Sound Output Mode" option so we can pick `Stereo` or `Surround` Sound.

**Comment by JaleSwiftpaw** [comment]
I don't know for sure, but Voicemeeter is picking up 6 channel audio from Ryujinx, so I believe it already supports it.

![003](https://github.com/Ryujinx/Ryujinx/assets/93559140/88b4d3e7-c964-462d-a2c5-ee2b419df0d5)

**Comment by Glebman95** [comment]
Funny thing is: it used to work on older versions. When the issue with the surround started I used a yuzu sdl2.dll for Ryujinx and it worked. Recently they changed it somehow, so that workaround doesn't work anymore.
