### ISSUE TITLE
[Bug]Use ldn_mitm in any game that supports LDN connection will be crash

### ISSUE THREAD

**Issue by LimonChoms** [Ryujinx/Ryujinx#4426]
### Description of the issue

The game crashes when I try to connect with ldn_mitm.This problem only occurs on my win11(r7 3700x+2080ti),on my mac(m1) it works very well

### Reproduction steps

Use ldn_mitm in any game that supports LDN connection will be crash

### Log file

[Ryujinx_1.1.0-ldn3.1.0_2023-02-15_21-38-40.log](https://github.com/Ryujinx/Ryujinx/files/10744674/Ryujinx_1.1.0-ldn3.1.0_2023-02-15_21-38-40.log)

### OS

Windows 11

### Ryujinx version

3.1

### CPU

r7 3700x

### GPU

rtx 2080ti

### RAM

16g

**Comment by Haceo** [comment]
same issue, only seems to happen with ldn-mitm not ryujinx ldn

**Comment by larryare** [comment]
I also have this issue on Arch Linux.

**Comment by TSRBerry** [comment]
See: https://github.com/Ryujinx/Ryujinx/issues/4437#issuecomment-1433639259

Duplicate of: #4423
