### ISSUE TITLE
[Feature Request] Missing instructions on how to build on macos

### ISSUE THREAD

**Issue by lucicam** [Ryujinx/Ryujinx#4428]
### Overview

There are no instructions on the particularities of building on macos (especially for M1/M2)

### Smaller details

Building with just the command in the readme fails on macos.

### Nature of request

Documentation request

### Why would this feature be useful?

Developers wanting to help with the emulator from a mac

**Comment by gdkchan** [comment]
Related: #4371.

**Comment by lucicam** [comment]
looked more into in in the meantime, seems like it doesn't build if there are spaces in the path where the project is cloned, maybe it could be specified in the documentation. I'll close the issue, thank you.

**Comment by gdkchan** [comment]
It might be better to leave it open to track doing something about this, since it's not the first time we get this question.

**Comment by lucicam** [comment]
Indeed. I made a quick pull request to specify this in the readme https://github.com/Ryujinx/Ryujinx/pull/4434
