### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by samyeung0** [Ryujinx/Ryujinx#4431]
### Description of the issue

![龙神模拟器bug](https://user-images.githubusercontent.com/100855216/219237731-042fabb3-dc14-4ed6-87c6-0e7ae88112b9.png)
你好，这里反应一个问题。这是关于龙神模拟器的所有版本。
在所有版本的模拟器中都会出现一个问题就是在运行所有游戏中开启游戏后都会出现白色的小方框在游戏中如图
只要在options-settings-graphics backend选择了vulkan模式都会出现小白框
但使用OpenGL是正常的

### Reproduction steps

![龙神模拟器bug](https://user-images.githubusercontent.com/100855216/219240419-3d07c00d-4321-432a-b01d-30e7045bb638.png)
你好，这里反应一个问题。这是关于龙神模拟器的所有版本。
在所有版本的模拟器中都会出现一个问题就是在运行所有游戏中开启游戏后都会出现白色的小方框在游戏中如图
只要在options-settings-graphics backend选择了vulkan模式都会出现小白框
但使用OpenGL是正常的

### Log file

没有备份文件

### OS

win10-win11 all

### Ryujinx version

all

### Game version

all

### CPU

i9 12900K

### GPU

rtx 3080ti

### RAM

32GB

### Additional context?

![龙神模拟器bug](https://user-images.githubusercontent.com/100855216/219240064-721406e2-9a49-45be-9f52-082c90467e86.png)

**Comment by MetrosexualGarbodor** [comment]
Please report issues in the [game's compatibility page](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4089). Also, please report issues in English, at least using an online translator, as none of us can read this.
