### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by samyeung0** [Ryujinx/Ryujinx#4432]
### Description of the issue

When using options-settings-graphics backend=vulkan, a small white box will appear, but it is normal to use opengl
![龙神模拟器bug](https://user-images.githubusercontent.com/100855216/219257225-674f50cb-64f9-4da4-a83b-66b3f5bb84dd.png)

### Reproduction steps

When using options-settings-graphics backend=vulkan, a small white box will appear, but it is normal to use opengl
![龙神模拟器bug](https://user-images.githubusercontent.com/100855216/219257286-44d6c810-a717-4442-a14e-85469cc48976.png)

### Log file

No backup log

### OS

win10-win11 all

### Ryujinx version

all

### Game version

all

### CPU

i9 12900K

### GPU

rtx 3080ti

### RAM

32GB

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [game's compatibility page](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4089).
