### ISSUE TITLE
[Bug] Pink hue when inside business buildings ACNH

### ISSUE THREAD

**Issue by purrrcocet** [Ryujinx/Ryujinx#4435]
### Description of the issue

There is an issue with lighting that is causing a pink hue. I saw a post from 2021 about a shader issue with mixed PBK and SSY addresses on the stack. This only happens when entering a business like nooks cranny, able sisters, the airport and the museum. The speech bubbles are normal colors its the lighting inside the buildings that is the issue, 
![2023-02-16 (3)](https://user-images.githubusercontent.com/125542252/219297850-08ce4ed3-ca86-4da1-82e1-b08cd7449761.png)

### Reproduction steps

When starting the game for the first time the issue is immediate. When entering the museum, nooks cranny, the able sisters, and the airport.

### Log file

[Ryujinx_1.1.622_2023-02-16_00-58-02.log](https://github.com/Ryujinx/Ryujinx/files/10753266/Ryujinx_1.1.622_2023-02-16_00-58-02.log)

### OS

windows 10

### Ryujinx version

1.1.622

**Comment by AcK77** [comment]
This should be reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/250, I've already done it. 
It seems to be an Intel specific error.
