### ISSUE TITLE
[Bug]  Ni No Kuni Wrath of the White Witch 

### ISSUE THREAD

**Issue by GoranXXV** [Ryujinx/Ryujinx#4436]
### Description of the issue

Ni No Kuni Wrath of the White Witch loops the title screen without giving me a chance to press any buttons even if buttons are mapped

### Reproduction steps

I launch the game and after loading shader and TPC the titlescreen loops and I can't go on

### Log file

[Ryujinx_1.1.622_2023-02-16_09-46-03.log](https://github.com/Ryujinx/Ryujinx/files/10753891/Ryujinx_1.1.622_2023-02-16_09-46-03.log)

### OS

Windows 11

### Ryujinx version

1.1.622

### Game version

1.0.0/1.0.2

### CPU

i5-8250U

### GPU

NVIDIA MX 130

### RAM

8GB

**Comment by yuwenhua653** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/980
same problem

**Comment by joseramosdarias** [comment]
It works!  with Ryujinx 1.1.1050   (MAC version)

**Comment by joseramosdarias** [comment]
<img width="1859" alt="Captura de pantalla 2023-10-13 a las 19 37 00" src="https://github.com/Ryujinx/Ryujinx/assets/32616105/474af112-ddb0-44a1-a5cc-da0529f0d907">
<img width="1923" alt="Captura de pantalla 2023-10-13 a las 19 36 23" src="https://github.com/Ryujinx/Ryujinx/assets/32616105/97f7bf96-6f15-431a-8937-95e236c5446c">
<img width="1891" alt="Captura de pantalla 2023-10-13 a las 19 31 42" src="https://github.com/Ryujinx/Ryujinx/assets/32616105/6c2e72ed-4a71-4c76-9d52-308b119e9e19">

**Comment by gilmith** [comment]
It doesn't work on Ryujinx 1.1.1069. It's an infinte llop of start screen

**Comment by joseramosdarias** [comment]
> It doesn't work on Ryujinx 1.1.1069. It's an infinte llop of start screen

Try to use  xci instead nsp roms

**Comment by gilmith** [comment]
Hello @joseramosdarias 
It's the same result

**Comment by raffwrwrwrw** [comment]
Ryujunx Version 1.1.1248 - 2024-03-27
Using XCI
Game Update 1.0,2
Same result, infinite loop of title screen.

**Comment by Metasynic** [comment]
Still occurring on the latest flatpak version. As there are many reports of this still happening @MetrosexualGarbodor please can this be re-opened?

**Comment by ekuland** [comment]
> Still occurring on the latest flatpak version. As there are many reports of this still happening @MetrosexualGarbodor please can this be re-opened?

This was closed in favor of the gameslist entry.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/980
