### ISSUE TITLE
[Bug] Splatoon 3 ldn_mitm crash

### ISSUE THREAD

**Issue by AniDeYnEs** [Ryujinx/Ryujinx#4437]
### Description of the issue

Game crashes when I'm trying to use ldn_mitm and LAN Play

### Reproduction steps

Press X to bring up the menu, go to **The Shoal** when ldm_mitm is active

### Log file

[Ryujinx_1.1.0-ldn3.1.0_2023-02-16_20-41-29.log](https://github.com/Ryujinx/Ryujinx/files/10760087/Ryujinx_1.1.0-ldn3.1.0_2023-02-16_20-41-29.log)

### OS

Windows 10

### Ryujinx version

1.1.0-ldn3.1.0

### Game version

2.1.1

### CPU

i3-6100

### GPU

RX 460 4GB

### RAM

16GB

**Comment by TSRBerry** [comment]
ldn_mitm currently doesn't work correctly, we are working on a fix and are already aware of this issue.

For now please use LDN 3.0.2 for ldn_mitm

**Comment by AniDeYnEs** [comment]
> ldn_mitm currently doesn't work correctly, we are working on a fix and are already aware of this issue.
> 
> For now please use LDN 3.0.2 for ldn_mitm

Sorry, where can i get the 3.0.2 version?

**Comment by AniDeYnEs** [comment]
?

**Comment by AniDeYnEs** [comment]
WOW you helped SO much thanks
