### ISSUE TITLE
Metroid Dread 2.1.0 crashes on start. Version 1.0.0 still works [Bug]

### ISSUE THREAD

**Issue by Tasosgemah** [Ryujinx/Ryujinx#4443]
### Description of the issue

When i try to launch version 2.1.0 of the game, it closes the emulator completely. If i disable the update, the game launches.

In Yuzu, the same update works perfectly and i managed to finish the game 100%.

I'm using the 15.01 firmware and keys. I'm using no additional mods or cheats.

### Reproduction steps

I'm just trying to launch the updated game.

### Log file

[Ryujinx_1.1.625_2023-02-18_12-13-50.log](https://github.com/Ryujinx/Ryujinx/files/10773856/Ryujinx_1.1.625_2023-02-18_12-13-50.log)

### OS

Windows 10

### Ryujinx version

1.1.625

### Game version

2.1.0

### CPU

i5 4670

### GPU

NVIDIA GTX 1060 6GB

### RAM

16 GB

**Comment by riperiperi** [comment]
Some part of the dump is incorrect. It works on yuzu because it simply does not validate the hash. You can disable filesystem integrity checks in Ryujinx but it is not correct, you should redump the update to fix the issue.
