### ISSUE TITLE
[Bug] System Time Reset macOS

### ISSUE THREAD

**Issue by Browser1004** [Ryujinx/Ryujinx#4447]
### Description of the issue

The system time resets in macOS when you change it, it just defaults to the current time.

### Reproduction steps

Go into options, settings and system then change the current date and time.
Once you hit apply and save and check back on it, it will remain the current date and time.

### Log file

I don't have one since I'm checking the time out before I start a game. 

### OS

macOS Ventura

### Ryujinx version

1.1.0macos1

### CPU

M2

### GPU

MoltenVK

### RAM

16GB

**Comment by TimeZlicer** [comment]
Changing System Date/Time requires elevated access (admin)

macOS data/time defaults to automatic update, please change it following https://support.apple.com/guide/mac-help/mchlp1124/mac

**Comment by AcK77** [comment]
It should be fixed now.
