### ISSUE TITLE
[Bug] FileChooser is not shown in Flatpak distribution

### ISSUE THREAD

**Issue by git-developer** [Ryujinx/Ryujinx#4450]
### Description of the issue

Whenever I click on an menu item that opens a file chooser, nothing happens.

This makes it impossible to install a firmware from file or to configure updates and DLCs.

### Reproduction steps

1. Boot the retro linux distribution [batocera](https://batocera.org/) v35
2. Install the flatpak image org.ryujinx.Ryujinx
3. Start Ryujinx
4. Click on _File_ / _Load Application from File_

### Log file

Unfortunately, nothing is printed to the log when I click on a menu item that should open a file chooser dialog.

### OS

Batocera 35

### Ryujinx version

1.1.625

### Additional context?

* I found PR #2633 that replaces a GTK dialog with `FileChooserNative`. My assumption is that no `FileChooserNative` is available in my environment (Flatpak on Batocera).
* The directory chooser, e.g. File -> Load Unpacked Game, works.

**Comment by marysaka** [comment]
Appears really weird to me, are you sure any other GTK3 based app works correctly?

This is nothing that is under our control, your DE should be providing some file picker...

**Comment by git-developer** [comment]
I don't know if they're GTK3 based, but Yuzu and Citra are working fine via Flatpak. The [batocera wiki](https://wiki.batocera.org/systems:flatpak) states:

> Common issues: no PS4 controller support, cannot install Flatpaks if using a NAS for your SAVES directory, audio is absent on some configurations, some games think the D-pad is eternally being pressed down on certain controllers, **apps that depend on opening the file browser crash upon doing so**, etc.

Isn't one of flatpak's key features being independent of the operating system? As far as I understand, a Flatpak app bundles everything it requires (even a file chooser). Maybe Ryujinx is missing a dependency? I'm not an Flatpak expert, though.

**Comment by AcK77** [comment]
Batocera seems to be a lightweight linux distro built from scratch, I'm pretty sure it miss a package or something like that. In any case, this is not an issue related to Ryujinx, and our flatpak doesn't have to include anything related to basic functionality.
Thanks.

**Comment by git-developer** [comment]
Possibly related to https://github.com/flatpak/flatpak/issues/5201
