### ISSUE TITLE
[Bug] Gsync Stutter?

### ISSUE THREAD

**Issue by cjhunter2160** [Ryujinx/Ryujinx#4456]
### Description of the issue

Whenever I use Gsync with Ryujinx I get this weird stuttering. This happens in both OpenGL and Vulkan backends.  The only way I can use Ryujinx smoothly is by changing my refresh rate to 60hz but this causes input lag as I am no longer in Gsync range. 

### Reproduction steps

In Nvidia control panel: Gsync on Vsync on.
In Ryujinx vsync on

### Log file

00:00:00.036 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.039 |I| Configuration LogValueChange: ResScaleCustom set to: 0.2
00:00:00.039 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.040 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.040 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.041 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.041 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2489
00:00:00.042 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.048 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.048 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableInternetAccess set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.048 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.049 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.049 |I| Configuration LogValueChange: AudioVolume set to: 0.5
00:00:00.049 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.049 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.049 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.049 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.051 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.626
00:00:00.055 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.055 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz ; 12 logical
00:00:00.055 |N| Application Print: RAM: Total 16265 MiB ; Available 11359 MiB
00:00:00.057 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.057 |N| Application PrintSystemInfo: Launch Mode: Portable

### OS

Windows 11

### Ryujinx version

1.1.626

### Game version

Any game

### CPU

11600k

### GPU

Geforce RTX 3060 ti

### RAM

2x8=16gb

### List of applied mods

None

**Comment by Boodax78** [comment]
I have the same problem,
the only solution I found is to activate in the nvidia control panel "Fast Sync", deactivate in Ryujinx the vsync and block the fps limit with a third party software, so that the game is not in fast forward.

By the way I don't have this problem on yuzu when I disable vsync the game still runs with the real fps limit, it just has tearing for non gsync-vrr displays.

It would be nice to add a similar option.

**Comment by cjhunter2160** [comment]
> I have the same problem, the only solution I found is to activate in the nvidia control panel "Fast Sync", disable in Ryujinx the vsync and block the fps limit with a third party software, so that the game is not in fast forward.
> 
> It would be nice to add a similar option.

This does fix the stuttering however some games (like BOTW for example) have other issues when ryujinx's Vsync is disabled like link having a weird acceleration when he runs.

**Comment by cjhunter2160** [comment]
In case anyone is still wondering about this issue I didnt really find a fix but I decided to change my refresh to 60 disable GSYNC and use nvidia vsync and ryujinx vsync since this allows for the smoothest gameplay for me. There is input delay but being able to emulate a current gen system with input lag is better than not emulating at all.

**Comment by jhorv** [comment]
Interesting, I haven't noticed anything like this in either of my games (BotW or Metroid Prime Remastered). I've had no  stuttering or input lag. Nvidia 3080, latest release driver, Win 10 latest, 144hz, G-SYNC enabled for both windowed and fullscreen apps.

@cjhunter2160 (and anyone else who experiences this):

- What's your monitor's refresh rate?
- Is G-SYNC set to fullscreen only, or both fullscreen and windowed?
- Is Ryujinx fullscreen or windowed?
- Can you describe the stuttering more, like is it occasional full stops, or constant micro-stutters, or just some more description?
- What's the your monitor's exact make/model?
- @cjhunter2160, the report says Windows 11 but the log says Windows 10?

**Comment by cjhunter2160** [comment]
My monitor's max refresh rate is 165hz
I have gsync set to fullscreen only but with the prefer layered on DXGI swapchain setting in the nvidia control panel should make it so that dwm does not composite vulkan and opnegl programs.
Ryujinx is set to fullscreen.
The stuttering is most noticeable when I turn the camera, it just feels jerky and not consistent.
My monitor's model isnt that well known, it is an ASUS VG279QR.
I am running windows 11 but I know some programs that detect windows 11 as 10 (Im guessing since they're so similar?)

**Comment by cjhunter2160** [comment]
I also tried Gsync fullscreen + windowed, issue still persists.

**Comment by OldManKain** [comment]
> My monitor's max refresh rate is 165hz I have gsync set to fullscreen only but with the prefer layered on DXGI swapchain setting in the nvidia control panel should make it so that dwm does not composite vulkan and opnegl programs. Ryujinx is set to fullscreen. The stuttering is most noticeable when I turn the camera, it just feels jerky and not consistent. My monitor's model isnt that well known, it is an ASUS VG279QR. I am running windows 11 but I know some programs that detect windows 11 as 10 (Im guessing since they're so similar?)

Your monitor will not enable G-Sync until you hit 50fps or higher which means any games under that will stutter.
![image](https://user-images.githubusercontent.com/47503099/227796995-c5e87038-f93b-49ca-b641-8084f18a2aad.png)

**Comment by cjhunter2160** [comment]
My monitor is capable of LFC which means that it will use a multiple of my fps as the refresh rate. ( so if I were getting 30fps gsync would  change the refresh rate to 90 to get rid of stuttering, so the range issue with gsync compatible monitors is irrelevant.)
and even if my monitor didnt have lfc the games I play are 60fps anyway.
And also nvidia's description of my monitor is incorrect. my monitor's gsync range is 48-165 as said in the manual and results from testing.

**Comment by OldManKain** [comment]
> My monitor is capable of LFC which means that it will use a multiple of my fps as the refresh rate. ( so if I were getting 30fps gsync would change the refresh rate to 90 to get rid of stuttering, so the range issue with gsync compatible monitors is irrelevant.) and even if my monitor didnt have lfc the games I play are 60fps anyway. And also nvidia's description of my monitor is incorrect. my monitor's gsync range is 48-165 as said in the manual and results from testing.

Are you Using Adaptive Sync (LFC )with MPRT?.  This is for your Monitor ASUS VG279QR.
```Additionally, LFC (Low Framerate Compensation) is supported which will ensure a smooth performance even south of 40 frames per second.```

```Keep in mind that Adaptive-Sync and 1ms MPRT cannot work simultaneously.```

**Comment by cjhunter2160** [comment]
No, my monitor doesnt even let me enable both at once.
Although i need to ask do you have the vsync enabled in ryujinx settings?

**Comment by OldManKain** [comment]
> 

Yes I have VSync enabled in Ryujinx, 

#### Nvida Control Panel
**Prefered Refresh Rate**: Highest Availiable 
**Vullkan/OpenGL Present Method:** Prefer Layered on DXGI swapchain.
G-Sync set to full screen only mode.

#### Windows Settings
**Hardware-Accelerated GPU Scheduling:** On
**Variable Refresh Rate:** On
**Optimizations for Windowed Games:** On

**Comment by cjhunter2160** [comment]
First of all, thank you for going through the trouble to assist me.
Secondly I have all of those things enabled except for hags.

**Comment by OldManKain** [comment]
> First of all, thank you for going through the trouble to assist me. Secondly I have all of those things enabled except for hags.

You are welcome, I would really like to figure out what is causing the G-Sync problems for some users but not others.

**Comment by cjhunter2160** [comment]
Well... Im clueless. The only way for me to make gsync work properly is to disable the emulated console's vsync and then cap fps to whatever the fps of the game is. but like I said earlier this can cause issues in some games. So I guess ill just deal with the input lag. Thanks for your help.

**Comment by Immersion95** [comment]
You can close this issue thanks to https://github.com/Ryujinx/Ryujinx/pull/4744

It's silky smooth with Freesync here :).

**Comment by cjhunter2160** [comment]
Im gonna go ahead and close the issue anyway, but gsync compatible is what im using and gaync compatible is basically freesync so im not sure whats happening.
