### ISSUE TITLE
WarioWare Get it Together - Flickering on certain character/object sprites [Bug]

### ISSUE THREAD

**Issue by MikePrime13** [Ryujinx/Ryujinx#4461]
### Description of the issue

When booting WarioWare Get it Together, the characters' sprites and other objects in the background may either flicker continuously or completely invisible/disappeared. This issue appears to be present with NVIDIA hardware; it was present on machines running Ryujinx on NVIDIA hardware (RTX 2070m, RTX 2070 super, and GTX 1080). The issue does not appear on AMD hardware (Steam Deck).

https://user-images.githubusercontent.com/126015367/220435847-420750a0-e4f2-43d9-8826-2a1ba212bf8e.mp4

### Reproduction steps

Run the game using NVIDIA hardware, latest drivers 528.49.

### Log file

[Ryujinx_1.1.630_2023-02-21_10-58-55.log](https://github.com/Ryujinx/Ryujinx/files/10796731/Ryujinx_1.1.630_2023-02-21_10-58-55.log)

### OS

Windows 11

### Ryujinx version

1.1.630

### Game version

1.0.0

### CPU

Ryzen 5600

### GPU

NVIDIA GTX 1080

### RAM

32GB

### List of applied mods

No mods being applied.

**Comment by GamerzHell9137** [comment]
I've found the thing that regressed it and opened a new issue thread, you can close this one and continue following the issue on the new one. https://github.com/Ryujinx/Ryujinx/issues/4463

**Comment by MikePrime13** [comment]
Thanks for responding -- I've closed the issue.
