### ISSUE TITLE
[Bug]ALT TAB bug in fullscreen

### ISSUE THREAD

**Issue by Keizer120** [Ryujinx/Ryujinx#4465]
### Description of the issue

Whenever I ALT TAB in or out of fullscreen, buttons start randomly not working. Not sure if it's a bug with Pokemon Violet or with any other games. If you would like I can test and check that. 

### Reproduction steps

Enter fullscreen ( pokemon Violet ). Alt tab a few times, and buttons in menu's stop working. Also in battle screens you simply cannot use some buttons or specific attacks. 

### Log file

Literally can't find it.

### OS

windows 10

### Ryujinx version

1.1.632

### CPU

AMD ryzen 7 2700x

### GPU

Radeon RX6600

### RAM

16

### List of applied mods

none

**Comment by MutantAura** [comment]
Doesn't seem like anyone else is able to reproduce this. 
Closing, please use discord for further support.
