### ISSUE TITLE
[Bug] Ni No Kuni Wrath of the White Witch

### ISSUE THREAD

**Issue by GoranXXV** [Ryujinx/Ryujinx#4469]
### Description of the issue

After bypassing EULA Contract and starting a new game, I have a texture bug after the initial cutscenes
![Screenshot_20230223_142727](https://user-images.githubusercontent.com/101893515/220920731-4cdc9c70-2939-4b06-abae-06011c9da457.png)

### Reproduction steps

Starting a new game with 1.0.2 patch causes this bug

### Log file

[Ryujinx_1.1.637_2023-02-23_14-25-18.log](https://github.com/Ryujinx/Ryujinx/files/10813959/Ryujinx_1.1.637_2023-02-23_14-25-18.log)

### OS

Windows 11

### Ryujinx version

1.1.637

### Game version

1.0.2

### CPU

i5-8250U

### GPU

NVIDIA MX 130

### RAM

8GB

### Additional context?

If I start a new game with no patch I don't have any texture bugs 
![Screenshot_20230223_144045](https://user-images.githubusercontent.com/101893515/220923509-4aba0a32-97be-4f41-ad9f-f3dd0876df58.png)

**Comment by MetrosexualGarbodor** [comment]
Please post game-specific issues in the [compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List/issues/980).
