### ISSUE TITLE
[Bug] Error 2318-0006

### ISSUE THREAD

**Issue by lostFloBH** [Ryujinx/Ryujinx#4470]
### Description of the issue

So I was playing Pokémon Scarlet and wanted to have a battle with someone.
Everything was working fine until we get to the Rule select screen.
We were able to connect, but as soon as we were able to select any rules, I got kicked out with an connection error.

Everything I found about this error is, that it is a normal Nintendo Switch error about connection and means that either my internet or the LDN server is offline which wouldn't make sense to me, cause I'm connected to the internet and it's just me getting the error, not my friend so it shouldn't be the LDN server.

Any help would be much appreciated!

### Reproduction steps

The way it works for me:

1. search for an opponent
2. as soon as we find each other we try to connect
3. the connection breaks off at the latest when either one of us is able to select the rules

### Log file

[Ryujinx_1.1.0-ldn3.1.0_2023-02-23_19-02-53.log](https://github.com/Ryujinx/Ryujinx/files/10817338/Ryujinx_1.1.0-ldn3.1.0_2023-02-23_19-02-53.log)

### OS

Windows 10

### Ryujinx version

1.1.0-ldn3.1.0

### Game version

1.1.0

**Comment by MutantAura** [comment]
Support requests are better shared on our discord: https://discord.gg/ryujinx
Thanks.
