### ISSUE TITLE
[Bug] alan wake blinking objects in scene

### ISSUE THREAD

**Issue by nsklaus** [Ryujinx/Ryujinx#4473]
### Description of the issue

the game "alan wake", largely rendering correctly, but most objects and characters in-game are constantly blinking. i tested this on macos, on macbookpro M2 pro. both with the old release and current tree (my own builds).

### Reproduction steps

just start a game. 

### Log file

[Ryujinx_1.1.1+1.1.0_2023-02-24_14-59-29.log](https://github.com/Ryujinx/Ryujinx/files/10824881/Ryujinx_1.1.1%2B1.1.0_2023-02-24_14-59-29.log)

### OS

macos 13.2.1

### Ryujinx version

1+1 (own build, arbitrary version number given at compile time ) 

### Game version

1.0.1

### CPU

m2 rpo

### GPU

m2 pro

### RAM

16gb

**Comment by MutantAura** [comment]
Game-specific issues should be reported on their compatibility page: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4085
Thanks.
