### ISSUE TITLE
[Bug] Octopath Traveler II - Flickering during dialog scenes

### ISSUE THREAD

**Issue by k-schneider** [Ryujinx/Ryujinx#4481]
### Description of the issue

During most dialog scenes the background will flicker.

### Reproduction steps

Play the game and its pretty apparent in most dialog scenes.

### Log file

[Ryujinx_1.1.642_2023-02-25_10-01-43.log](https://github.com/Ryujinx/Ryujinx/files/10831546/Ryujinx_1.1.642_2023-02-25_10-01-43.log)

### OS

Windows 10

### Ryujinx version

1.1.642

### Game version

1.0.0

### CPU

Ryzen 5 7600X

### GPU

NVIDIA RTX 4090

### RAM

64GB

**Comment by MutantAura** [comment]
Game-specific issues should be reported on their compatibility page: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4465 preferably with an accompanying video.
Thanks.
