### ISSUE TITLE
[Feature Request] Hide cursor for touchscreens

### ISSUE THREAD

**Issue by crazygamerdude17** [Ryujinx/Ryujinx#4486]
### Overview

I would really like to have the ability to just tap without seeing a cursor on a touch screen like my steam deck, there is already the option to hide the cursor after a few seconds but why not have the ability to make the cursor invisible so you can play it perfectly without an ugly cursor on a steam deck

### Smaller details

Two ideas of implementing this: 1. Toggle off and on cursor visibility by making the cursor invisible when the feature is toggled 2. Change the time it takes to hide to be like a nanosecond so the player doesn’t see the cursor after they remove their finger

### Nature of request

Not sure what to put for nature of request but I guess it would be a good useful feature for touch screens

### Why would this feature be useful?

It would be useful for playing ryujinx with a touch screen and making it feel more like the real switch

**Comment by jojodunet** [comment]
I think I can refer with the following issue, as the both are complementary.
#4445 [Avalonia Build] HideCursor arguments

**Comment by AcK77** [comment]
Fixed in https://github.com/Ryujinx/Ryujinx/pull/4613
