### ISSUE TITLE
[Bug] SDL2 audio output much lower than OpenAL/Normal or no balancing

### ISSUE THREAD

**Issue by Ryan2603** [Ryujinx/Ryujinx#4492]
### Description of the issue

SDL2 audio output much lower than normal 100%, OpenAL no such problem

### Reproduction steps

you might compare OpenAL output , its like halve ~70%

### Log file

nope

### OS

W11

### Ryujinx version

1.1.645

**Comment by Squall-Leonhart** [comment]
Its actually OpenAL that is too loud, this is a common issue with the openal renderer that even the Doom 3 developers didn't account for, so samples clip far more than they should.

**Comment by Squall-Leonhart** [comment]
Irrelevant comparison, Ryujinx is not Chrome and all you've done is highlighted that Chromes audio renderer has terrible base audio mixing too.

**Comment by Ryan2603** [comment]
> Irrelevant comparison, Ryujinx is not Chrome and all you've done is highlighted that Chromes audio renderer has terrible base audio mixing too.

i would like to quit replying your no sense ( doesnt know who you are represent to), i will suggest you to test your own before answering some excuse.

**Comment by ArkhXI** [comment]
I have the exact same problem with xenoblade 3. Everything is updated, SDL2 audio is WAY too low, did not have this problem in the past

**Comment by Ryan2603** [comment]
![comparison](https://user-images.githubusercontent.com/10262883/227189902-95e8371b-eb8d-4922-a666-6b3595689865.jpg)

follow up the comparison for that SDL2 sound IO output much lower than normal/Yuzu , but seen i cannot upload the project directly, i think this jpg should enough to prove it anyway (let see the wavelength)

**Comment by Ryan2603** [comment]
this problem was gone quietly (tested on 1.1.800 with P5R and XC3), thank you every developer efforts!
