### ISSUE TITLE
[Bug] Updater fails to restart Ryujinx

### ISSUE THREAD

**Issue by Silent-Remux** [Ryujinx/Ryujinx#4494]
### Description of the issue

Pressing yes here only closes Ryujinx and it does not automatically restart.

![Ryujinx_dqGlHLX3hE](https://user-images.githubusercontent.com/16107603/221978131-65e2c62a-9d25-4a8c-83fc-8189dacf4c96.png)

### Reproduction steps

As above.

### Log file

Not required

### OS

Win 11

### Ryujinx version

All

**Comment by MetrosexualGarbodor** [comment]
Windows Command Line needs to be set to Windows Console Host instead of Windows Terminal on W11

**Comment by MutantAura** [comment]
Related for reference: https://github.com/Ryujinx/Ryujinx/issues/3779
