### ISSUE TITLE
[Bug]change tabs in setting GUI causes crash

### ISSUE THREAD

**Issue by a234106261** [Ryujinx/Ryujinx#4496]
### Description of the issue

Switch to some tabs of the setting GUI causes crash
![click UI after input causes crash](https://user-images.githubusercontent.com/16643671/222210853-0da86920-3e9c-4f68-ad76-689af00657bd.png)

### Reproduction steps

When I open options-settings, after click any tabs such as input and click tp switch back to User Interface again, Ryujinx always crash

### Log file

[Ryujinx_1.1.646_2023-03-02_00-57-52.log](https://github.com/Ryujinx/Ryujinx/files/10863664/Ryujinx_1.1.646_2023-03-02_00-57-52.log)

### OS

Windows 10 

### Ryujinx version

1.1.646

### Game version

No

### CPU

12th Gen Intel(R) Core(TM) i5-12600KF | AVX2 | FMA

### GPU

Nvidia 3080/30.0.15.1694

### RAM

31.8GiB 3600MHz

### List of applied mods

No

**Comment by Squall-Leonhart** [comment]
You appear to be missing a system font.

**Comment by a234106261** [comment]
> You appear to be missing a system font or one of its substyles.

Hard to understand this, I can click any tab at the first time
Anyway, even if you notice the real problem, there's still no clue to figure out the missing font
Thanks for any idea if you know

**Comment by AcK77** [comment]
Duplicated of #4589
