### ISSUE TITLE
[Bug] Unable to access specific menus in GRID Autosport

### ISSUE THREAD

**Issue by LeRutY** [Ryujinx/Ryujinx#4502]
### Description of the issue

There are two menus in GRID Autosport which can´t be accessed, "Help" and "Change controls" you just get thrown back to the previous menu when trying to do so. Example video https://streamable.com/5styoy

### Reproduction steps

1. Start the game
2. Create a new profile or load an existing one
3. Scroll to the "Help" tab or "Change controls" (found in "Options & Extras", "Controls")
4. Try to open it

### Log file

[Ryujinx_1.1.647_2023-03-02_19-25-08.log](https://github.com/Ryujinx/Ryujinx/files/10874522/Ryujinx_1.1.647_2023-03-02_19-25-08.log)

### OS

Windows 10

### Ryujinx version

1.1.649

### Game version

1.8.3

### CPU

i7 7700K

### GPU

GTX 1080

### RAM

16 GB

**Comment by gdkchan** [comment]
The menu seems to use web applet. Likely the same issue as Ni no Kuni.

**Comment by AcK77** [comment]
As gdkchan said, it's require LibAppletOff which isn't implemented (see #1004).
I close it because it's a duplicated issue.
Thanks.
