### ISSUE TITLE
Some sprites are missing in Mario Maker 2 on latest branch MacOS [Bug]

### ISSUE THREAD

**Issue by jneen** [Ryujinx/Ryujinx#4506]
### Description of the issue

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/225017/222811049-d2c4e419-b14a-4c49-a93d-3ceef4450e20.png">

It appears that any element from the tiles spritesheet is not displayed. Other sprite sheets seem to display fine, like enemies and items. Note that the starting ground is missing - I've also added ground, several blocks, and a conveyor, but they do not display (or display as entirely transparent).

### Reproduction steps

* Build Ryujinx on current master (tested on ecee34a50cd8e4266cb2ecc9910d8d33d612c84a)
* Run Super Mario Maker 2
* Make a course in any style other than 3DWorld
* Note that the starting ground is missing, but still appears to have physics
* Place any block tile, conveyor, semisolid, bridge, etc and note that they do not render.
* Note that they do not render in play mode either.

### Log file

[ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/10885590/ryujinx.log)

I couldn't find the Logs folder so I tee'd the console output for a session where I loaded mario maker 2, and the bug was present on screen.

### OS

MacOS (M1 Max) Ventura 13.2.1 (22D68)

### Ryujinx version

master (ecee34a50cd8e4266cb2ecc9910d8d33d612c84a)

### Game version

3.0.2

### CPU

Apple M1 Max

### GPU

Apple M1 Max

### RAM

64GB

**Comment by jneen** [comment]
Seems to work fine on non-macos. Also the release macos version I have (1.1.0-macos1) seems to be fine. I'm not sure what branch or commit that's on but I'm happy to bisect it if need be.

[Screenshot from release MacOS]
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/225017/222827604-092be49e-285e-4153-80ea-22628b3ab29a.png">

**Comment by gdkchan** [comment]
This game uses geometry shaders, which MoltenVK (and Metal) does not support. The macos1 release has some code to emulate geometry shaders that was not upstreamed yet. I'm not sure if it's worth upstreaming it since there's some work underway to support geometry shader on MoltenVK by emulating them with mesh shaders. The game should render correctly in theory once the support lands on MoltenVK side or we implement the geometry shader emulation here.

**Comment by jneen** [comment]
Thank you!

**Comment by B0XGaming** [comment]
This may be related to the issue. This occurs on Windows and you can see the grid lines through objects in anything except 3dw.

Most noticeable in SMB, but is present in SMB, SMB3, SMW and New Soup.

CPU: Ryzen 5 5600X
Memory: 32Gb DDR4
GPU: GTX 1080
OS: Windows 11 Pro 64-Bit 22H2
Ryujinx Version: 1.1.650
Game Version: 3.0.2


![bug](https://user-images.githubusercontent.com/127067244/223003671-d8cb94e7-ac4e-437b-9b6a-e18ef7de476c.png)

**Comment by gdkchan** [comment]
This is a resolution scale issue and is not related to this problem at all.

**Comment by B0XGaming** [comment]
> This is a resolution scale issue and is not related to this problem at all.

Alright. Then I'll open a separate bug report. Thank-you.

**Comment by AcK77** [comment]
See https://github.com/Ryujinx/Ryujinx/issues/4062 for more informations.

**Comment by jneen** [comment]
Verified still an issue on latest master - is there somewhere else where this was completed?

<img width="752" alt="image" src="https://user-images.githubusercontent.com/225017/235732719-266938ec-377a-4972-bcb8-503b7515ac2e.png">

**Comment by gdkchan** [comment]
Yea the issue still exists, it should remain open until geometry shaders are supported on macOS.
