### ISSUE TITLE
[Bug] Fire emblem Ryujinx map 19 is Crashing

### ISSUE THREAD

**Issue by nazcanhok** [Ryujinx/Ryujinx#4515]
### Description of the issue

I played it fine from the beginning, but when I played to the end of map 19,it was crashing 

https://www.youtube.com/watch?v=OKkiPDq7Mjc

please help me ==!

### Reproduction steps

I played it fine from the beginning, but when I played to the end of map 19,it was crashing 

https://www.youtube.com/watch?v=OKkiPDq7Mjc

please help me ==!

### Log file

I played it fine from the beginning, but when I played to the end of map 19,it was crashing 

https://www.youtube.com/watch?v=OKkiPDq7Mjc

please help me ==!

### OS

Window 10

### Ryujinx version

13.2.1

### Game version

1.2

### CPU

i7 -6700

### GPU

Nvidia 980ti

### RAM

16gb

**Comment by Foul-Tarnished** [comment]
This is a game that run really poorly for me compared to other games, I hope devs could do some analysis about the game perf

**Comment by Squall-Leonhart** [comment]
Re-dump your game data.
