### ISSUE TITLE
[Bug]Crash when running Octopath Traveler 2

### ISSUE THREAD

**Issue by dtndmd** [Ryujinx/Ryujinx#4517]
### Description of the issue

Suddenly crash when joining a new companion

### Reproduction steps

I was playing fine before, when the new companions (Throné and Agnea) joined, suddenly crashed
In the event that Throné joins the party, it crashes after the fight.
When Agnea joined the party, it crashed after Agnea's first words
When transfer Ryujinx save files to Yuzu, the same event will not report an error

### Log file

[Ryujinx_1.1.650_2023-03-07_00-52-08.log](https://github.com/Ryujinx/Ryujinx/files/10900155/Ryujinx_1.1.650_2023-03-07_00-52-08.log)

### OS

windows 10

### Ryujinx version

1.1.650

### Game version

1.0.2

### CPU

i7-7700

### GPU

NVIDIA GeForce GTX 1070

### RAM

16gb

**Comment by gdkchan** [comment]
The error indicates that the ROM file is corrupted.
