### ISSUE TITLE
[Bug]AMD GPU Vulkan，Pokémon Legends does't show Character model.

### ISSUE THREAD

**Issue by LoveChienJay** [Ryujinx/Ryujinx#4519]
### Description of the issue

GPU：RX480 8G
Model:Vulkan
Driver：Adrenalin 23.2.2 win10
Problem：Pokémon Legends does't show Character model. Older AMD driver runs ok.

### Reproduction steps

Pokémon Legends does't show Character model. Older AMD driver runs ok.

### Log file

no log file

### OS

win10 64bit

### Ryujinx version

650

### Game version

1.1.1

### CPU

R7 1800x

### GPU

RX480 8G

### RAM

16

### List of applied mods

none

**Comment by MetrosexualGarbodor** [comment]
You said it yourself: this is an AMD driver issue, not a Ryujinx issue. However feel free to post about it on the game's compatibility page.
