### ISSUE TITLE
[Bug] build fails on arch linux

### ISSUE THREAD

**Issue by wantija** [Ryujinx/Ryujinx#4520]
### Description of the issue

Building the latest git from source, and it fails

> Ryujinx.Graphics.Nvdec -> /home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Graphics.Nvdec/bin/Release/net7.0/Ryujinx.Graphics.Nvdec.dll
  Ryujinx.Graphics.Vic -> /home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Graphics.Vic/bin/Release/net7.0/Ryujinx.Graphics.Vic.dll
CSC : warning CS9057: The analyzer assembly '/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon.Generators/bin/Release/netstandard2.0/Ryujinx.Horizon.Generators.dll' references version '4.5.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'. [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/LogManager/Ipc/LogService.cs(7,32): error CS0535: 'LogService' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Sm/Ipc/ManagerService.cs(5,36): error CS0535: 'ManagerService' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Sm/Ipc/UserService.cs(8,33): error CS0535: 'UserService' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Sdk/Sf/Cmif/DomainServiceObject.cs(3,68): error CS0535: 'DomainServiceObject' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/LogManager/Ipc/LmLogger.cs(15,30): error CS0535: 'LmLogger' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Sdk/Sf/Hipc/HipcManager.cs(7,33): error CS0535: 'HipcManager' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Prepo/Ipc/PrepoService.cs(16,34): error CS0535: 'PrepoService' does not implement interface member 'IServiceObject.GetCommandHandlers()' [/home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
  Ryujinx.Audio.Backends.OpenAL -> /home/username/.cache/pikaur/build/ryujinx-git/src/Ryujinx/Ryujinx.Audio.Backends.OpenAL/bin/Release/net7.0/Ryujinx.Audio.Backends.OpenAL.dll
==> ERROR: A failure occurred in build().
    Aborting...

### Reproduction steps

attempt to build from source on arch linux

### Log file

n/a

### OS

Arch Linux

### Ryujinx version

git

**Comment by piplup55** [comment]
you need the latest dotnet sdk [arch package](https://archlinux.org/packages/community/x86_64/dotnet-sdk/), [manual install](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.201-linux-x64-binaries)

**Comment by wantija** [comment]
Looks like the arch package is out-of-date possibly(?), using the dotnet-sdk/host/runtime-bin from the AUR fixed this, thanks.

**Comment by YoshiRulz** [comment]
b8556530f introduced the dependency on version 7.0.200 of the SDK. 4f3af839b was the last version that can be built with 7.0.100.
