### ISSUE TITLE
[Bug] Ryujinx crashes when opening an application off an SMB share

### ISSUE THREAD

**Issue by nice-username** [Ryujinx/Ryujinx#4523]
### Description of the issue

I am writing some homebrew for my Nintendo Switch.  
It's easier to test in an emulator so I'm using Ryujinx -- but it keeps crashing.

### Reproduction steps

1) Open a homebrew application from an SMB share

For example, I keep my homebrew applications at 
smb://192.168.1.1/Homebrew

2) Ryujinx crashes

Copying my homebrew application from to the devices local disk results it in running just fine, "Hello world!"

### Log file

[Ryujinx_1.1.1+0_2023-03-06_16-19-23.log](https://github.com/Ryujinx/Ryujinx/files/10922803/Ryujinx_1.1.1%2B0_2023-03-06_16-19-23.log)

### OS

macOS 13.2.1 (22D68)

### Ryujinx version

1.1.1

### CPU

M1 Max

### GPU

M1 Max

### RAM

65

### Additional context?

This post is only regarding homebrew applications.

**Comment by riperiperi** [comment]
The log file doesn't show any error, it just shows the game being closed after a while.

**Comment by Squall-Leonhart** [comment]
probably a file system timeout.

**Comment by AcK77** [comment]
I wonder how this could an homebrew:
```
00:00:00.369 |I| Loader LoadExeFs: Loading rtld...
00:00:00.373 |I| Loader LoadExeFs: Loading main...
00:00:00.713 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.732 |I| Loader LoadExeFs: Loading sdk...
```

In any cases, the "homebrew" seems to load as it should regarding your log file.
