### ISSUE TITLE
[Bug] D-Pad doesn't work with Box Style Controller

### ISSUE THREAD

**Issue by AtomToast** [Ryujinx/Ryujinx#4527]
### Description of the issue

I tried using both the latest master build and Ryujinx 1.1.651 on Arch Linux and I can't use my dpad in the ryujinx settings or in game (smash ultimate). Similar to the problem described in issue https://github.com/Ryujinx/Ryujinx/issues/4400

There are no outputs in the log when trying to use the dpad.

In this video you can see the controller send the same inputs to both ryujinx(on the left) and yuzu(on the right)
https://user-images.githubusercontent.com/27757087/224175526-68ff051d-39e2-420c-ae83-df57ef024d81.mp4
Both do the exact same actions, except when taunting (which is the dpad input) (shown in the middle of the video)

### Reproduction steps

1. Own an OpenFrame1 or similar box style controller that runs Haybox firmware
2. Select it in the Ryujinx settings
3. Observe Dpad inputs are not detected

### Log file

[Ryujinx_1.1.651_2023-03-09_23-25-04.log](https://github.com/Ryujinx/Ryujinx/files/10936620/Ryujinx_1.1.651_2023-03-09_23-25-04.log)

### OS

Arch Linux

### Ryujinx version

1.1.651

### Game version

13.0.1

### CPU

AMD Ryzen 5 5600X

### GPU

NVIDIA GeForce GTX 1060

### RAM

16GB

### List of applied mods

Ultimate Training Modpack, though I also tested it without and it also happens in the Emulator settings, outside of a game

### Additional context?

For context, I am using a smashbox like controller that basically just emulates a controller with [this firmware](https://github.com/JonnyHaystack/HayBox). The dpad works fine in yuzu and other games, only not in Ryujinx. 
The dpad of my 8bitdo Pro2(in x-input mode) works fine in Ryujinx. Using it in Pro Controller Mode also works fine both wired and wireless.
Just my box controller can't use the dpad (in standard x-input mode). It is detected in d-input mode but that mangles some button mappings for me so I'd prefer not having to use it. Also pretty sure x-input is the more modern one anyways.

**Comment by Squall-Leonhart** [comment]
upstream support issue, report it to SDL github.

**Comment by AtomToast** [comment]
Do you have any more details on what the actual SDL issue may be?

**Comment by Squall-Leonhart** [comment]
no embedded mapping in sdl, so its using a generic method that doesn't handle exotic controls.

https://github.com/spurious/SDL-mirror/blob/master/src/joystick/SDL_gamecontrollerdb.h

**Comment by AtomToast** [comment]
While I won't dismiss your take, since you know this project better than I do, I have tested a bit and to me the issue does not seem to be with SDL on it's own.

- The controller is detected as an "X360 Wireless Controller" in Ryujinx, which is listed 4 times in the [SDL_gamepad_db.h](https://github.com/libsdl-org/SDL/blob/f4c12601206dda36f2996a95083e3e0602a9ca42/src/joystick/SDL_gamepad_db.h#L847)
  There it also seems to have dpad directions configured.
  ![image](https://user-images.githubusercontent.com/27757087/224488799-4811a006-5568-4a3a-9b61-b9601e1fd4a1.png)
- The dpad works fine in yuzu, which also appears to be using SDL2.
- Using https://gitlab.com/sdl-jstest/sdl-jstest I was able to test the controller and dpad works both with --test and the --event flag 
  ![image](https://user-images.githubusercontent.com/27757087/224489378-a2379612-14a3-4843-9068-c0618657f35d.png)
  ![image](https://user-images.githubusercontent.com/27757087/224489599-59d77b6f-99a6-4236-8e15-7acdb2bce6b8.png)
  (note, I had to switch to this unmerged pr to get it to compile https://gitlab.com/sdl-jstest/sdl-jstest/-/merge_requests/16)
