### ISSUE TITLE
Fire Emblem Engage instantly crashing after installing 1.2 or 1.3 update [Bug]

### ISSUE THREAD

**Issue by jewxl** [Ryujinx/Ryujinx#4532]
### Description of the issue

My Fire Emblem Engage instantly crashes after I installed the 1.2 or 1.3 updates. The 1.1 update boots up normally but with 1.2 and 1.3 it stays as a black screen until it eventually crashes. 

### Reproduction steps

![FEE Crash 1 3](https://user-images.githubusercontent.com/127580272/224465765-279356a2-e264-4710-b3ae-acfc16b6e8da.png)
![FEE NCrash 1 1](https://user-images.githubusercontent.com/127580272/224465800-da93f181-fd8e-4a20-90cd-40dd71ad6f29.png)

### Log file

[Ryujinx_1.1.651_2023-03-10_23-47-04.log](https://github.com/Ryujinx/Ryujinx/files/10947642/Ryujinx_1.1.651_2023-03-10_23-47-04.log)
[Ryujinx_1.1.651_2023-03-10_23-55-09.log](https://github.com/Ryujinx/Ryujinx/files/10947643/Ryujinx_1.1.651_2023-03-10_23-55-09.log)
[Ryujinx_1.1.651_2023-03-10_23-55-57.log](https://github.com/Ryujinx/Ryujinx/files/10947644/Ryujinx_1.1.651_2023-03-10_23-55-57.log)

### OS

Windows 10 

### Ryujinx version

Ryujinx 1.1.651

### Game version

1.3.0

### List of applied mods

No mods downloaded

### Additional context?

I download update 1.3 from ziperto

**Comment by MetrosexualGarbodor** [comment]
Piracy is not supported.
