### ISSUE TITLE
[Bug]fps drop when leaving a house [pokemon Sowrd/Shield]

### ISSUE THREAD

**Issue by yhusei** [Ryujinx/Ryujinx#4533]
### Description of the issue

at certain moments in the game or leaving certain houses early in the game, the stable fps drops from 30 to 25-27, and only returns to normal by saving and restarting the game.

### Reproduction steps

I tried restoring the default settings, no results.

### Log file

[
[Ryujinx_1.1.651_2023-03-11_11-31-11.log](https://github.com/Ryujinx/Ryujinx/files/10948958/Ryujinx_1.1.651_2023-03-11_11-31-11.log)
](url)

### OS

windows 11

### Ryujinx version

1.1.651

### Game version

all versions 

### CPU

i5 10300H

### GPU

gtx 1650

### RAM

16

### Additional context?

I have tried "another emulator "Y" " and this problem does not occur, it only occurs in riujinx

**Comment by riperiperi** [comment]
This isn’t a bug. When outdoors this game samples a shadow map multiple times which causes GPU stalls that are especially expensive on laptops. Yuzu avoids this issue by not doing that and as a result outdoors lighting is incorrect.
