### ISSUE TITLE
[Bug] mvk-error metroid prime 

### ISSUE THREAD

**Issue by nsklaus** [Ryujinx/Ryujinx#4534]
### Description of the issue

after one or two hours of gameplay, the game crash suddenly when trying to enter the temple on tallon4 surface. it seems to me that the code should check what kind of data it passes to moltenvk before doing it, or implement some try catch in case the data passed over is not of the required type, or not in the required order..things like that. i have no idea what impact such checks would do to performance. it is just a suggestion. maybe it is not even a valid one. you'll judge what need to be done by looking at the provided log chunk.

### Reproduction steps

game systematically crash when trying to enter a specific area.  
as shown in the screenshot below. 

![Screenshot 2023-03-11 at 18 32 59](https://user-images.githubusercontent.com/6810861/224503679-455ff1aa-11e2-4329-b1f0-88e76f2b29a1.png)

![Screenshot 2023-03-11 at 18 35 26](https://user-images.githubusercontent.com/6810861/224503689-e8576344-d72e-4be2-ab9a-7c72f39c35dc.png)

problem is, you need missiles to be able to reach that area, and missile are elsewhere in the game.
you need to play the game normaly, gain missiles, then come back here, try to open the temple door and finally be able to witness the crash.

### Log file

[mvk-error.log](https://github.com/Ryujinx/Ryujinx/files/10949065/mvk-error.log)

full log:
[Ryujinx_1.1.1+1.5_2023-03-11_19-03-42.log](https://github.com/Ryujinx/Ryujinx/files/10949174/Ryujinx_1.1.1%2B1.5_2023-03-11_19-03-42.log)

### OS

macos13.2.1

### Ryujinx version

own build (current tree at the time of filling this bug)

### Game version

1.0.0

### CPU

m2 pro

### GPU

m2 pro

### RAM

16gb

**Comment by gdkchan** [comment]
This issue is supposed to be fixed by #4404.

**Comment by nsklaus** [comment]
> This issue is supposed to be fixed by #4404.

thanks for telling but, i imported this PR into my local tree some time ago. i should already have it:
```
klaus@NsMac Ryujinx % git branch
* master
  pr4368
  pr4404
  pr4406
  pr4408
  pr4471
klaus@NsMac Ryujinx %
```
it shows in my git log too. yet i'm still getting the crash.

**Comment by MetrosexualGarbodor** [comment]
Can you post a save file?

**Comment by nsklaus** [comment]
yes, let me look for it

**Comment by nsklaus** [comment]
for what it's worth, i tried to load my save file from the old macos1 build from november. and the game did not crash upon opening that particular door. so current build does crash there, and old build does not.  (old build quickly crashes elsewhere but that's another story).

**Comment by nsklaus** [comment]
yes, sorry maybe i should have left a closing message. in the last builds the issue appear solved. i'm not crashing anymore at that point.
