### ISSUE TITLE
[Bug]Shader compilation crash on Mac M1 Chip| Mario Kart Deluxe 8

### ISSUE THREAD

**Issue by ducky8888** [Ryujinx/Ryujinx#4541]
### Description of the issue

When Launching shader heavy games Ryujinx often crashes while still compiling the shaders.
I encountered this issue with Mario Kart Deluxe 8. Ryujinx was compiling around 6400 shaders and would crash amidst the compilation process. 
Ryujinx crashed with SIGABRT

### Reproduction steps

Launch Mario Kart Deluxe 8. Ultimate with a high number of shaders on MacOS M1
Wait for Shader compilation to complete
The App will likely crash before the shader compilation process is complete

### Log file

[Untitled.txt](https://github.com/Ryujinx/Ryujinx/files/10951807/Untitled.txt)

### OS

MacOS Monterey 12.5

### Ryujinx version

Ryujinx version: 1.1.0-macos1

### Game version

2.3.0 and 1.0.0

### CPU

Apple M1 SOC

### GPU

Apple M1 SOC

### RAM

16GB LPDDR4

### List of applied mods

No

**Comment by TimeZlicer** [comment]
This is likely already fixed on master, >8000 shaders compiles without problem albeit it takes a few minutes on M1 MBA

Options
- wait for upstream to be completed
- build your own
