### ISSUE TITLE
crash down at the same scene eveytime :system reflection targetinvocation

### ISSUE THREAD

**Issue by Quesera008** [Ryujinx/Ryujinx#4542]
### Description of the issue

![image](https://user-images.githubusercontent.com/44633291/224572806-113dc3a6-7b25-425f-9399-d138aee6d357.png)

### Reproduction steps

open collar x malice
play to this scene
![image](https://user-images.githubusercontent.com/44633291/224572997-103a778a-8ac0-44b3-8215-04b7a336b629.png)

### Log file

[Ryujinx_1.1.662_2023-03-13_04-42-54.log](https://github.com/Ryujinx/Ryujinx/files/10952062/Ryujinx_1.1.662_2023-03-13_04-42-54.log)

### OS

windows 10

### Ryujinx version

1.1.662

### Game version

1.0.0

### CPU

Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.20 GHz

### GPU

NVIDIA GeForce RTX 2060

### RAM

16Gb

**Comment by MutantAura** [comment]
Your game dump is corrupt. Redump it.

**Comment by Quesera008** [comment]
> Your game dump is corrupt. Redump it.

please tell me how to redump!thank you so much!!

**Comment by Quesera008** [comment]
hey, i  removed the old keys and pasted new 15.0.1 keys, then reinstall the 15.0.0 firmware,but it still corrupt. please reply thanks so much
[Ryujinx_1.1.662_2023-03-14_18-39-09.log](https://github.com/Ryujinx/Ryujinx/files/10967352/Ryujinx_1.1.662_2023-03-14_18-39-09.log)
