### ISSUE TITLE
[Bug] Exception Type: EXC_CRASH (SIGABRT) Exception Codes: 0x0000000000000000, 0x0000000000000000

### ISSUE THREAD

**Issue by termaulmaul** [Ryujinx/Ryujinx#4545]
### Description of the issue

Ryujinx quit unexpectedly with error
Crashed Thread:        52
s
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

### Reproduction steps

playing with 5 minutes

### Log file

[log.txt](https://github.com/Ryujinx/Ryujinx/files/10969217/log.txt)

### OS

macOS Ventura

### Ryujinx version

1.1.0

### Game version

Animal Crossing: New Horizons v2.0.6

### CPU

Apple M1

### GPU

Apple M1

### RAM

8

**Comment by marysaka** [comment]
Please provide the actual emulator logs, the version of Ryujinx.

Without any of that we cannot asses what is the reason of this crash.

Please reopen a new issue with all the information.
