### ISSUE TITLE
Characters don't appear on Vulkan and OpenGl appear sideways[Bug] [Vulkan] [Gpu]

### ISSUE THREAD

**Issue by IchibiGnarosaki** [Ryujinx/Ryujinx#4546]
### Description of the issue

When I open Pokemon Legends Arceus or Pokemon Scarlett everything seems to work as normal but when the actual gameplay starts all characters are invisible
My gpu is a Rx66000 I was running on 23.3.1 driver but I made a downgrade trying to solve this problem and wasn't  fixed

and error always appear on the cmd:
.NET ThreadPool Worker Gpu : Background Compilation failed: Unexpected API error "ErrorUnknown".

### Reproduction steps

Configure to vulkan open the game and pass the intruduction

### Log file

[Ryujinx_1.1.0+c12233c_2023-03-14_02-47-06.log](https://github.com/Ryujinx/Ryujinx/files/10969849/Ryujinx_1.1.0%2Bc12233c_2023-03-14_02-47-06.log)

### OS

Windows 11

### Ryujinx version

lastest and I tried on 1.1.0+c12233c

### GPU

Rx6600

**Comment by RayleighPablo** [comment]
Same issue here. Starts all good but when in game, game characters are invisible. See screenshot below. 
![Screenshot 2023-03-15 092639](https://user-images.githubusercontent.com/127910348/225181252-36617b7d-9ed4-4fb3-861b-1d2323e38e34.png)

Here is a copy of my log file: 
[Ryujinx_1.1.665_2023-03-15_09-29-53.log](https://github.com/Ryujinx/Ryujinx/files/10975151/Ryujinx_1.1.665_2023-03-15_09-29-53.log)

Also noticed that when the shaders are being loaded, the total number is significantly lower than before I updated Ryujinx to version 1.1.663

**Comment by IchibiGnarosaki** [comment]
tested in an older version and the error on the cmd changed but no characters 
![image](https://user-images.githubusercontent.com/87989336/226674407-1015aa17-1c18-4602-9a68-16d214c4dcf7.png)

[Ryujinx_1.1.590_2023-03-21_13-13-05.log](https://github.com/Ryujinx/Ryujinx/files/11030984/Ryujinx_1.1.590_2023-03-21_13-13-05.log)

**Comment by Nvidix123** [comment]
I have the same Issue on Windows 10.
My Specs are:
AMD Ryzen 5 5600X
AMD Radeon RX6800
16GB RAM
If I use OpenGL the Models are completely bugged and halfway in the Ground.
Here are my Vulkan Logs + a Screenshot:
[Ryujinx_1.1.709_2023-04-15_11-50-33.log](https://github.com/Ryujinx/Ryujinx/files/11239145/Ryujinx_1.1.709_2023-04-15_11-50-33.log)

![Screenshot_1](https://user-images.githubusercontent.com/130836035/232209145-e118d12f-200f-4c28-8883-bdb48fdc24e0.png)

Here are my OpenGL Logs + a Screenshot:


![OpenGl](https://user-images.githubusercontent.com/130836035/232209162-39dc3ab4-87dc-4dbf-8606-dd7b0876f8d4.png)
[OpenGL Log](https://github.com/Ryujinx/Ryujinx/files/11239151/Ryujinx_1.1.709_2023-04-15_12-01-04.log)
