### ISSUE TITLE
[Regression] Icons in Dragon Quest Builders are random/broken

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#4550]
### Description of the issue

After #3754 the icons in Dragon Quest Builders either show as broken or exchanged with other icons from the game

1.1.566

![image](https://user-images.githubusercontent.com/2002038/225606385-2ab17688-45da-4345-a748-0c6ba3557c8b.png)

1.1.565

![image](https://user-images.githubusercontent.com/2002038/225606426-e792efad-37b6-413e-9d87-791d841e907b.png)

### Reproduction steps

Just booting the game

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.665

### Game version

1.0.0

### CPU

Ryzen 3600

### GPU

NVIDIA RTX 3060 Ti

### RAM

16 GB

**Comment by H3roDude** [comment]
Still happening on 1.1.724

OS
Windows 10

Ryujinx version
1.1.665

Game version
1.0.0

CPU
I7 12700k

GPU
NVIDIA RTX 3060 Ti

RAM
32 GB

List of applied mods
No response

Additional context?
No response
