### ISSUE TITLE
[Bug] Newest commits causes jittering in some games & low performance in BDSP (plus mods crashing)

### ISSUE THREAD

**Issue by MarioMastr** [Ryujinx/Ryujinx#4551]
### Description of the issue

Compared to the mac version on the website, the compiled version has some jittering with some games (BDSP showcased, but it also happens with the opening cutscene in Sonic Origins), and BDSP is also lower performance with the compiled version than the website version. Mods also crash games in this version when they do not in the website version. 

### Reproduction steps

1. Build the github version
2. open bdsp (or sonic origins for the first time so you can see the opening cutscene)
3. watch the jitteriness

Mods:
1. use a mod (pretty sure its any mod)

### Log file

for the mods crashing:
[Ryujinx_1.1.0-macos+da073fc_2023-03-16_15-39-49.log](https://github.com/Ryujinx/Ryujinx/files/10992713/Ryujinx_1.1.0-macos%2Bda073fc_2023-03-16_15-39-49.log)

for the jittering and slower performance:
[Ryujinx_1.1.0-macos+da073fc_2023-03-16_15-41-29.log](https://github.com/Ryujinx/Ryujinx/files/10992740/Ryujinx_1.1.0-macos%2Bda073fc_2023-03-16_15-41-29.log)

### OS

macOS 13.3 beta 4 (not sure if the beta matters)

### Ryujinx version

1.1.0-macos vs compiled version

### CPU

M1

### GPU

M1

### RAM

8GB

### List of applied mods

None

**Comment by TSRBerry** [comment]
Could you please add the current Ryujinx version at the time you were compiling your own build to your description?

**Comment by Veemyu** [comment]
I can confirm. This behavior has been present ever since we got the ability to compile Ryujinx on our own.
Mod loading not working is harsh, but dropping from 240+ FPS in BDSP down to 20 FPS is a big thing.

**Comment by MutantAura** [comment]
Major components of the macos1 release (on the webpage) are not upstreamed. Lots of those are performance related.
Until this process is completed please do not expect parity with macos1.
