### ISSUE TITLE
[Bug] "Manage Cheats" window doesn't show any cheats, console does.

### ISSUE THREAD

**Issue by Dorhana** [Ryujinx/Ryujinx#4552]
### Description of the issue

The "Manage Cheats" window doesn't show any cheats and instead displays "No cheats found", the background console on the other hand finds the exact cheat that is installed. This occurs not matter what game or what cheat. The cheats are confirmed to work by other people.

### Reproduction steps

1. Install mod
2. Open Ryujinx
3. Rightclick game and select "Manage Cheats"
4. "No cheats found"

This issue persists after restarting both Ryujinx and my entire PC multiple times, renaming mods to their BID and inserting the mod directly into the mods folder instead of their own folder.

### Log file

[Ryujinx_1.1.665_2023-03-17_11-09-04.log](https://github.com/Ryujinx/Ryujinx/files/11000216/Ryujinx_1.1.665_2023-03-17_11-09-04.log)

### OS

Windows 10

### Ryujinx version

1.1.665

### CPU

AMD Ryzen 7 5800H

### GPU

NVIDIA RTX 3070 Laptop

### RAM

32GB

**Comment by MutantAura** [comment]
Are you sure these are cheats? Mods and cheats are not the same and the cheat manager will not display romfs or exefs mods.

**Comment by Dorhana** [comment]
> 
God. Now that you mentioned this, I took a look at it again... its not even a normal mod, its an atmosphere mod. I just missed it. Sorry for wasting your time. Works fine now. I'll just delete this post if possible.

**Comment by MutantAura** [comment]
No worries. A mod manager should be coming sometime in the future: https://github.com/Ryujinx/Ryujinx/pull/4390
