### ISSUE TITLE
FIFA 23 - missing active player overlay/indicator [Bug]

### ISSUE THREAD

**Issue by DerGitRob** [Ryujinx/Ryujinx#4553]
### Description of the issue

Normally there is a red arrow on the active player like this:
![image](https://user-images.githubusercontent.com/127032030/225980573-77c71691-5c33-4c24-9728-bf10ce0bdf81.png)

On Ryujinx, the active player sign is missing, so it is really hard to play because you don't know which player you are control:
![image](https://user-images.githubusercontent.com/127032030/225980325-c38ec9af-6325-4e88-8449-ee26c3b85328.png)

### Reproduction steps

Start FIFA 23 and play a match

### Log file

[Ryujinx_1.1.668_2023-03-17_18-35-40.log](https://github.com/Ryujinx/Ryujinx/files/11004216/Ryujinx_1.1.668_2023-03-17_18-35-40.log)

### OS

Linux Debian Kernel 6.1.3 with KDE 5.26.4

### Ryujinx version

1.1.668

### Game version

01001C8016B4E000

### CPU

Ryzen 5 5600

### GPU

NVIDIA GeForce RTX 3060

### RAM

32 GB

**Comment by MutantAura** [comment]
This has already been reported on the game's compatibility page: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4381 
Further issues should go there.

**Comment by DerGitRob** [comment]
Possible errors:

`00:00:45.527 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 45s
    ProgramName: fifazf
    Thread: SportsUtil::AsyncCallback
    Message: ParticlesXmlParser::VerifyAttributes: Attribute 'version' not recognised in XML ''.`

Possible stubbed things:
`00:00:15.720 |S| HLE.OsThread.20 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:15.720 |S| HLE.OsThread.20 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:15.720 |S| HLE.OsThread.20 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:15.721 |S| HLE.OsThread.20 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:15.721 |S| HLE.OsThread.20 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:15.887 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:15.894 |I| HLE.OsThread.20 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:15.896 |I| HLE.OsThread.20 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:15.912 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:15.927 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:15.962 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:15.963 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:15.963 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:15.964 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:15.964 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:15.965 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:15.965 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:15.966 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:18.619 |S| HLE.OsThread.20 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:18.621 |S| HLE.OsThread.20 ServiceNifm Submit: Stubbed. 
00:00:18.621 |S| HLE.OsThread.20 ServiceNifm GetRequestState: Stubbed. 
00:00:18.621 |S| HLE.OsThread.20 ServiceNifm GetResult: Stubbed. 
00:00:18.621 |S| HLE.OsThread.20 ServiceNifm GetAppletInfo: Stubbed.`

Possible Infos:
`00:14:41.983 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 881s
    ProgramName: fifazf
    Thread: FEThread
    Message: overlayService::SetOverlaySet 9->7

00:14:41.989 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 881s
    ProgramName: fifazf
    Thread: RenderThread
    Message: ***Preloader::ConfirmStadiumAndFreeWrongAssets(420,1, 1) - we had (420,1, 1)

00:14:41.928 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 881s
    ProgramName: fifazf
    Thread: FEThread
    Message: Using players passed in.  Hope you know what you're doing...`

**Comment by armoman92** [comment]
Same issue for me on macOS Ryujinx.

Same issue happens ins FIFA 19 as well.

**Comment by ageorgios** [comment]
same issue

**Comment by AppleSiliconM7** [comment]
How to fix issue "Missing player indicators" ? I have downloaded the latest version of Ryujinx....the problem remains the same

**Comment by ZAIDIYI** [comment]
I have yuzu is there any Solution for Android users ?
