### ISSUE TITLE
[Bug] Pinball FX3 Medievel Madness table crashes out the emulator before it loads the table

### ISSUE THREAD

**Issue by benderscruffy** [Ryujinx/Ryujinx#4557]
### Description of the issue

Medievel Madness table crashes out the emulator before it loads the table
all the other williams table load except for this one 

### Reproduction steps

just choose the Medievel Madness table and it will crash out

### Log file

[Ryujinx_1.1.668_2023-03-18_13-24-21.log](https://github.com/Ryujinx/Ryujinx/files/11007576/Ryujinx_1.1.668_2023-03-18_13-24-21.log)

### OS

Windows 10

### Ryujinx version

1.1.668

### Game version

1.0.11.0

### CPU

Ryzen 7 5700X

### GPU

NVIDIA RTX 3060

### RAM

32GB

**Comment by AcK77** [comment]
It crashes because you have enabled "Ignore Missing Service", since the missing service is faked an returns empty data, it crashes.
The missing service is already reported here: #1575
In that case, I close this issue. Thanks.

**Comment by benderscruffy** [comment]
if i untick  "Ignore Missing Service" it crashes out on the same spot now
doesnt even go ingame
![Screenshot 2023-05-03 143708](https://user-images.githubusercontent.com/2696404/235846784-dae1733f-12e1-4431-a554-792c2acdef42.png)
please reopen

**Comment by benderscruffy** [comment]
still happens in 1.1.861
