### ISSUE TITLE
Ryujinx hangs within frames of loading a save file in Super Mario Odyssey [Bug]

### ISSUE THREAD

**Issue by DorAntCr** [Ryujinx/Ryujinx#4562]
### Description of the issue

Game hangs after loading the world in Super Mario Odyssey. This bug appears in most of the kingdoms ("maps"). The game loads for a few frames, then suddenly stops, music continues playing. See attached picture. 
![ryujinx hangs](https://user-images.githubusercontent.com/71099338/226116580-0b449617-5a2a-4b6f-b73d-7c936c6fb301.png)
The bug started happening after creating a new save file. 

### Reproduction steps

Open Ryujinx normally
Run Super Mario Odyssey normally
Load a save file
Game hangs

### Log file

[Ryujinx_1.1.668_2023-03-18_16-50-02.log](https://github.com/Ryujinx/Ryujinx/files/11008937/Ryujinx_1.1.668_2023-03-18_16-50-02.log)

### OS

Windows 10

### Ryujinx version

1.1.668

### Game version

1.3.0

### CPU

AMD Ryzen 5 5600H

### GPU

NVIDIA GeForce GTX 1650

### RAM

16GB

### Additional context?

The bug was also present on 1.1.650, updating hasn't helped. On the same version previously, I was able to make a new save file without problems. 
Rendering engine used is OpenGL.

**Comment by gdkchan** [comment]
Should be fixed by #4560 I believe?

**Comment by DorAntCr** [comment]
Fixed, thanks!
