### ISSUE TITLE
[Bug] Freeze in Zelda Link's Awakening after beating Spider Boss (Dungeon 5)

### ISSUE THREAD

**Issue by RobMcGee** [Ryujinx/Ryujinx#4570]
### Description of the issue

Hey, seems like the boss' death animation is freezing the emulator. Using Vulkan backend. Reproduced twice on my system.
Not seeing any stacktrace in the console logs unfortunately so it doesn't look like a proper crash.
The game window remains open and just freezes when it happens.
[bug.txt](https://github.com/Ryujinx/Ryujinx/files/11012651/bug.txt)

Edit: Works fine when using OpenGL.

### Reproduction steps

1. Beat spider boss in Catfish's Maw (the second of the 2 spiders)
2. ???
3. Cry

### Log file

[Ryujinx_1.1.672_2023-03-19_16-55-07.log](https://github.com/Ryujinx/Ryujinx/files/11012660/Ryujinx_1.1.672_2023-03-19_16-55-07.log)
[Ryujinx_1.1.672_2023-03-19_17-02-26.log](https://github.com/Ryujinx/Ryujinx/files/11012661/Ryujinx_1.1.672_2023-03-19_17-02-26.log)
[Ryujinx_1.1.672_2023-03-19_16-53-27.log](https://github.com/Ryujinx/Ryujinx/files/11012662/Ryujinx_1.1.672_2023-03-19_16-53-27.log)

### OS

W10

### Ryujinx version

1.1.672

### Game version

1.0.0

### CPU

Can be found in bug.txt

### List of applied mods

None

### Additional context?

Thanks for the emulator!

**Comment by GamerzHell9137** [comment]
Would be nice if you wrote what CPU GPU RAM you have instead of leaving it with the logs. There's a reason why its asked to be written.

**Comment by RobMcGee** [comment]
Lol if it's a required field, *make* it required.

**Comment by piplup55** [comment]
> Lol if it's a required field, *make* it required.
there a reason it's not marked as required because some issues don't need it, if your going to report a game bug the info is required

**Comment by MetrosexualGarbodor** [comment]
The Link's Awakening log ends with your controller getting disconnected. You likely didn't see the controller applet and assumed the game was frozen. Closing now as it's not a Ryujinx issue.

**Comment by RobMcGee** [comment]
That's quite a theory, but wrong I'm afraid.
Since I took the time to create this bug report, over ten minutes had
passed and my controller had gone idle so shut itself off so that didn't
cause the problem I saw.

The boss explodes when you beat it so it seemed like that was triggering
the hang.
Like I reported, I was able to reproduce it. Switching to OpenGL allowed me
to get past the boss and now I've switched back to Vulkan to continue my
playthrough.

I've added my specs to the report. I'd advise reopening it.

**Comment by RobMcGee** [comment]
I'll add my save asap

**Comment by Bjorn29512** [comment]
> I'll add my save asap

would really appreciate the save file, helps debug the issue if it actually exists.

**Comment by RobMcGee** [comment]
I'm slightly annoyed to say that my game autosaved past the dungeon where I could repro the issue.
I found out the game has a custom dungeon creator where you can retry bosses so I tried that but I didn't see the freeze in there. Although it's not an exact match of the story dungeon, I think it's close enough to close the issue.
I purged my game's shader cache and tried again but it works fine with Vulkan now. 
Maybe somebody else will run into it someday. Or maybe it was cosmic rays. Definitely wasn't my controller disconnecting though.

**Comment by GamerzHell9137** [comment]
Can you give us the save anytime soon?

**Comment by RobMcGee** [comment]
Ok I've run into the the same issue on _another_ boss. But now I can't reproduce that one either... 
You can have my save file this time though but I'm not sure what the difference is between my first and subsequent runs..
I completely wiped my game's cache folder to try again but it didn't help.. 
I have a recording from after the error happened the first time (MP4) and another with the steps I took to try reproducing it. The only difference was maybe fighting a few extra enemies and more exploring on the way the first time around. 
In the second video, the boss fight starts around 1:30min but the rest of the video has the path to get to him since you load in at the back of the dungeon. 

Edit: The second video is bigger than github will allow me to upload (~40MB). 
Any preferred method for me to upload it?

Save files: [0000000000000007.zip](https://github.com/Ryujinx/Ryujinx/files/11036246/0000000000000007.zip)

https://user-images.githubusercontent.com/9448154/226801842-b384663b-f4c7-4591-9571-f3ec64d14f8f.mp4

**Comment by RobMcGee** [comment]
The purple explosion in part5 is where the issue happened the first time on both bosses.
The rest of the videos have the path to get to the boss since you load in at the back of the dungeon.
https://user-images.githubusercontent.com/9448154/226804576-74ae3dbf-6b41-4ad0-b22c-196c1e56790f.mp4
https://user-images.githubusercontent.com/9448154/226804590-e6bb678d-3d2c-498c-89ee-2202105251da.mp4
https://user-images.githubusercontent.com/9448154/226804594-aaefd3f7-ad26-435a-b4b0-8150afdf1aa1.mp4
https://user-images.githubusercontent.com/9448154/226804606-529070e6-ad0b-4621-abe2-baa43c43fe50.mp4
https://user-images.githubusercontent.com/9448154/226804615-d45401ef-448c-43c1-ac7e-d6fb1ed460eb.mp4

**Comment by Bjorn29512** [comment]
> The purple explosion in part5 is where the issue happened the first time on both bosses. The rest of the videos have the path to get to the boss since you load in at the back of the dungeon. https://user-images.githubusercontent.com/9448154/226804576-74ae3dbf-6b41-4ad0-b22c-196c1e56790f.mp4 https://user-images.githubusercontent.com/9448154/226804590-e6bb678d-3d2c-498c-89ee-2202105251da.mp4 https://user-images.githubusercontent.com/9448154/226804594-aaefd3f7-ad26-435a-b4b0-8150afdf1aa1.mp4 https://user-images.githubusercontent.com/9448154/226804606-529070e6-ad0b-4621-abe2-baa43c43fe50.mp4 https://user-images.githubusercontent.com/9448154/226804615-d45401ef-448c-43c1-ac7e-d6fb1ed460eb.mp4

Leave one line of space between each video for embed

**Comment by RobMcGee** [comment]
Ah well, thanks for trying. I'm at the end anyway so won't affect me for much longer.
