### ISSUE TITLE
[Bug] Super Mario Odyssey experiences visual artifacts when scaling

### ISSUE THREAD

**Issue by Bjorn29512** [Ryujinx/Ryujinx#4580]
### Description of the issue

Super Mario Odyssey experiences flickering with visual artifacts when scaling, there is a chance of it happening on native but since the issue is random in nature me not getting it could be a coincidence, I also noticed specific behavior that is common to each of the following shots

- The issue always had a perfect oval in the center/or sometimes off center but its always there, along with a 16:9 ratio rectangle in the top left area of the screen.

![image](https://user-images.githubusercontent.com/110204265/226871885-1a365a65-bd59-4a38-85bc-e63841cb6cbe.png)

![image](https://user-images.githubusercontent.com/110204265/226871915-dbb5321e-7d16-4635-ac69-399a08750266.png)

![image](https://user-images.githubusercontent.com/110204265/226871940-90dbfe9e-7e23-48d8-8d2c-e5b83c6dcac6.png)

### Reproduction steps

- Enable scaling and try to play in the very first cap kingdom level.
- Recommended to use a lot of camera motion and try in different areas within the same level

Since the issue is random in nature it could take variable amt of time to reproduce.

### Log file

[Ryujinx_1.1.675_2023-03-22_15-29-07.log](https://github.com/Ryujinx/Ryujinx/files/11038827/Ryujinx_1.1.675_2023-03-22_15-29-07.log)

### OS

Windows 11

### Ryujinx version

1.1.675

### Game version

1.3.0

### CPU

i5-12400f

### GPU

GTX 1660 Super (driver 531.29)

### RAM

32 GB

### List of applied mods

None

**Comment by gdkchan** [comment]
Assuming fixed by #6493, please re-open if the issue still persists.
