### ISSUE TITLE
[Bug] Crash when exiting full screen if emulation is not stopped first

### ISSUE THREAD

**Issue by ajab561** [Ryujinx/Ryujinx#4588]
### Description of the issue

Ryujinx is crashing on macOS when switching between full screen and windowed mode if the emulation is running.

### Reproduction steps

1. Run game emulation in macOS fullscreen.
2. Exit fullscreen mode without stopping the emulation.
3. Ryujinx hangs then crashes.

### Log file

[Ryujinx_ 1.1.0-macos1_2023-03-22_22-04-52.log](https://github.com/Ryujinx/Ryujinx/files/11046329/Ryujinx_.1.1.0-macos1_2023-03-22_22-04-52.log)

[Ryujinx-2023-03-22-222535.txt](https://github.com/Ryujinx/Ryujinx/files/11046360/Ryujinx-2023-03-22-222535.txt)

### OS

macOS 13.2.1 (22D68)

### Ryujinx version

1.1.0-macos1

### CPU

M2 Max

### GPU

M2 Max

### RAM

32GB

**Comment by TSRBerry** [comment]
I'm unable to reproduce this. I also used Mario Kart 8 Deluxe as a test, but was able to go to windowed mode without any issues.

Are you able to reproduce this constantly? If so, could you share your config file?

**Comment by AcK77** [comment]
Closed as inactive.
