### ISSUE TITLE
Vertex Explosion in Pokemon Scarlet/Violet[Bug]

### ISSUE THREAD

**Issue by Mafilux** [Ryujinx/Ryujinx#4590]
### Description of the issue

Haven't seen this before but occasionally textures will start going wild on certain models. Bisharp in particular but it may affect others, definitely a seizure warning kind of thing. I had been playing a couple hours (in one session) as well so I don't know if this is a game thing or an emulator thing, but thought I'd report it anyway.
![bisharp](https://user-images.githubusercontent.com/46135592/227374725-7e614699-7b4d-4e9b-9cbc-a0d70985d5e0.jpg)

Textures stretch and start fluctuating wildly, seemingly only on certain parts. I played a little more and it started happening on Vaporeon too. This event happened in the bamboo forest woods in-game, I'm sorry I can't remember the exact name.

### Reproduction steps

Use Pokemon in the bamboo forest of Violet (or conversely, Scarlet). Some models would stretch and freak out!

### Log file

N/A

### OS

Win10

### Ryujinx version

Latest

### Game version

1.1.0

### CPU

Intel I5-4460 @ 3.20 ghz

### GPU

Nvidia 1060 6GB

### RAM

8GB

### List of applied mods

N/A

**Comment by gdkchan** [comment]
This is usually called vertex explosion, it doesn't really have anything to do with textures, it's the vertex data that is incorrect.

**Comment by Mafilux** [comment]
Is there a way to correct it on the emulator? I'm not particularly tech savvy.

**Comment by Mafilux** [comment]
Restarting everything fixed the issue. Sorry if it was a false alarm
