### ISSUE TITLE
[Regression] Link's Awakening bomb texture glitch introduced in 1.1.664

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Ryujinx/Ryujinx#4598]
### Description of the issue

API: Vulkan
Resolution Scale: 2x
Post Processing Effect: SMAA Ultra
Upscale: FSR 80.0
All other settings: Default

Visual bug with bomb texture in Link's Awakening. This bug is oddly specific. It's only happened when the miniboss Master Stalfos in Catfish's Maw is present on screen. It has not happened anywhere in the game prior to this. It can happen in all four rooms you fight him in, as well as custom dungeons you create with him in it. It stops happening as soon as he is no longer present.

UPDATE: This is a regression that started with build 1.1.664, discovered by [Bjorn29512](https://github.com/Bjorn29512). Tested on 1.1.663, and there is no issue there.

Image showing the bug is below.
![bomb](https://user-images.githubusercontent.com/60951301/227704079-51d4d7a5-48a3-4636-a5a1-02ea9bb00619.png)

### Reproduction steps

- Load the save file provided in the comment section
- Speak to Dampe
- Choose to Adventure into a dungeon
- Go to the Free tab and enter the only dungeon there
- Enter the room to the right as soon as you spawn
- Place a bunch of bombs once battle starts

### Log file

[Ryujinx_1.1.681_2023-03-25_03-06-42.log](https://github.com/Ryujinx/Ryujinx/files/11068320/Ryujinx_1.1.681_2023-03-25_03-06-42.log)

### OS

Windows 10

### Ryujinx version

1.1.681

### Game version

1.0.1

### CPU

Ryzen 5 5600X

### GPU

Nvidia RTX 3060Ti

### RAM

16Gb.

**Comment by Bjorn29512** [comment]
can you upload a save ?

**Comment by JENOVAAbsolute** [comment]
> can you upload a save ?

Oh Lord. I should have. I completed the dungeon already. I apologize for that.

**Comment by JENOVAAbsolute** [comment]
Thankfully I was able to recreated a dungeon with the miniboss, and the bug happens there too. Save file is attached. You will start in Dampe's shack. The custom dungeon is in the Free tab, and the miniboss will be in the room to the right of the entrance.

[[SAVE].zip](https://github.com/Ryujinx/Ryujinx/files/11069827/SAVE.zip)

**Comment by Bjorn29512** [comment]
> Thankfully I was able to recreate a dungeon with the miniboss, and the bug happens there too. Save file is attached. You will start in Dampe's shack. The custom dungeon is in the Free tab, and the miniboss will be in the room to the right of the entrance.
> 
> [[SAVE].zip](https://github.com/Ryujinx/Ryujinx/files/11069827/SAVE.zip)

I tested this on my end and found it out to be a regression that started with 1.1.664 PR #4442 , try downloading 1.1.663 and verifying on your end, if it checks out then i recommend changing the issue label to regression and adding appropriate information in the description.

**Comment by OpaqueReptile** [comment]
I was able to replicate this on latest master, but the issue seems to disappear when building Ryujinx.Graphics.Gpu as Debug instead of Release.
