### ISSUE TITLE
[Bug] OpenGL crashes everytime on Avalonia under Linux

### ISSUE THREAD

**Issue by CoolFrenchPerson** [Ryujinx/Ryujinx#4600]
### Description of the issue

There is a regression with 1.1.563 with OpenGL that makes it crash everytime on Avalonia. I have currently only tested with Mario Kart 8 Deluxe and Super Mario Odyssey, this might happen with other games too but they are the only ones i currently have dumped..

### Reproduction steps

Set graphics backend to OpenGL and launch game

### Log file

[Ryujinx_1.1.563_2023-03-25_08-34-43.log](https://github.com/Ryujinx/Ryujinx/files/11068306/Ryujinx_1.1.563_2023-03-25_08-34-43.log)

### OS

Linux Ubuntu

### Ryujinx version

1.1.563

### CPU

Intel® Core™ i5-7300HQ 

### GPU

GeForce GTX 1060 Mobile

### RAM

8GB

**Comment by Squall-Leonhart** [comment]
current nightly is 1.1.681, your issue has already been resolved between then and now.

**Comment by CoolFrenchPerson** [comment]
Just tested, no it has not been resolved.

**Comment by rmvdesign** [comment]
seconding this issue, still a thing on the newest version

**Comment by CoolFrenchPerson** [comment]
I also remember Berry saying this is an nvidia only issue
Not sure if we have a tag for that but if we do, it would be nice to add it to this issue
