### ISSUE TITLE
[Bug]Cannot scan Amiibo

### ISSUE THREAD

**Issue by boreslayer** [Ryujinx/Ryujinx#4614]
### Description of the issue

Cannot use the Scan an Amiibo emulation on Ryujinx

### Reproduction steps

Amiibo emulation not loading for my switch games.  Tried this is Fire Emblem: Engage, Three Houses and Mario Kart.  It just showed 
![image](https://user-images.githubusercontent.com/17951976/228229736-4ce7540f-301a-4c23-b62a-feec2c4334e1.png)
even after clicking show all amiibo.  I tried this on my desktop and on a laptop with a FRESH INSTALL of Windows 10 and Ryujinx.  

On the laptop, when I tried to scan an amiibo for the first time, I was able to load the amiibo and scan it but the Ryujinx crashed after the amiibo was registered  For the 2nd try onwards, it took longer and longer for the amiibo to load until no amiibo loaded.  

Someone seems to have a similar issue with me
https://www.reddit.com/r/Ryujinx/comments/1070o6i/is_it_possible_for_a_persons_internet_connection/

### Log file

No logs files were stored in the logs folder by Ryujinx.  

Let me know what other information I can provide or need.  

### OS

Windows 10

### Ryujinx version

1.1.686

### Game version

1.3.0

### CPU

AMD Ryzen 7 5800x

### GPU

NVIDIA RTX 3080

### RAM

32GB

### List of applied mods

None

**Comment by fernandodosanjosxmarts** [comment]
😢
I get a message in ryujinx 
Unable to connect to Amiibo API server. The service may be down or you may need to verify your internet connection is online.

**Comment by TSRBerry** [comment]
Could you ping me on the Ryujinx discord server? I'd like to figure this out if possible.

**Comment by fairplayer916** [comment]
yeah i can use the scan an amiibo once in BOTW, then when i go to scan it again, the list doesnt populate like the picture above

**Comment by cesarsb83** [comment]
> 😢 Recibo un mensaje en ryujinx No se puede conectar al servidor API de Amiibo. Es posible que el servicio esté inactivo o que deba verificar que su conexión a Internet esté en línea.

si les pasa eso es la ip de su pc por lo que tienen que usar una vpn eso arreglara el problema.

**Comment by cesarsb83** [comment]
If that happens to you, it's the IP of your PC, so you have to use a VPN, that will fix the problem.
