### ISSUE TITLE
[Bug] Cruisin' Blast - Emulator Crash During Gameplay

### ISSUE THREAD

**Issue by Skates1616** [Ryujinx/Ryujinx#4620]
### Description of the issue

During game play, after finishing a Circuit, Ryujinx crashed completely with the following message:

![image](https://user-images.githubusercontent.com/23196661/228879952-0c26e4e2-27b3-43eb-8313-c0d1b8c0a815.png)

The log attached is from the crash in Multiplayer mode (2 controllers).

### Reproduction steps

Play the game and between circuits the game will start to slow, until it ultimately crashes the emulator between the next few circuit completions.

### Log file

[Ryujinx_1.1.687_2023-03-29_19-47-05.log](https://github.com/Ryujinx/Ryujinx/files/11113066/Ryujinx_1.1.687_2023-03-29_19-47-05.log)

### OS

Windows 11 Version 22H2 (Build 22624.1391)

### Ryujinx version

1.1.687

### Game version

1.07

### CPU

12th Gen Intel(R) Core(TM) i7-12700K | AVX2 | FMA

### GPU

NVIDIA GeForce RTX 3060 Ti / NVIDIA 531.18.0.0

### RAM

32GB

### List of applied mods

None

**Comment by AcK77** [comment]
Your log say: `VulkanException: Unexpected API error "ErrorOutOfDeviceMemory"`
Try to enabled Texture Recompression to see if it fixes something.
We can reopen this issue if it's not fixed. Thanks.
