### ISSUE TITLE
Bayonetta 3 launch issue

### ISSUE THREAD

**Issue by TrollAndHack** [Ryujinx/Ryujinx#4627]
### Description of the issue

Bayonetta 3 crashing when opening 

### Reproduction steps

Get the Bayonetta 3 nsp and launch it in Ryujinx

### Log file

[Ryujinx_1.1.692_2023-04-01_07-01-00.log](https://github.com/Ryujinx/Ryujinx/files/11129706/Ryujinx_1.1.692_2023-04-01_07-01-00.log)

### OS

Windows 11

### Ryujinx version

1.1.692

### Game version

1.1.0

### CPU

AMD Ryzen 5 5600X 6-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 TI

### RAM

15.9GB

### List of applied mods

No mods

**Comment by OldManKain** [comment]
```LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!```
Bad dump, re-dump your game.
Please join us in discord in the future for troubleshooting problems https://discord.gg/ryujinx
