### ISSUE TITLE
Game crashing Lock exit stubbed (Fire Emblem Engage)

### ISSUE THREAD

**Issue by NoNomaer23** [Ryujinx/Ryujinx#4637]
### Description of the issue

Fire Emblem Engage randomly crashes

### Reproduction steps

the game randomly crashes anytime anywhere in the game

### Log file

[Ryujinx_1.1.694_2023-04-04_09-25-02.log](https://github.com/Ryujinx/Ryujinx/files/11143976/Ryujinx_1.1.694_2023-04-04_09-25-02.log)

### OS

Windows 10 

### Ryujinx version

1.1.694

### Game version

1.2.0

### CPU

Ryzen 5 3400g

### GPU

NVIDIA GTX 1650

### RAM

16GB DDR4

### List of applied mods

no mods

**Comment by OldManKain** [comment]
I do not see a crash in your log. 

Anyway, for troubleshooting please join us in our [discord](https://discord.gg/ryujinx
 ) and head on over to the windows support channel.
