### ISSUE TITLE
Option to Synchronize saved games through the cloud between several PC's Steam Cloud style

### ISSUE THREAD

**Issue by Predatux** [Ryujinx/Ryujinx#4638]
### Overview

Many times you start playing on a computer, and then you would like to continue on a laptop.

### Smaller details

Implementation of an option to upload saved games to the cloud, just like Steam does

### Nature of request

It would be great to be able to do it.

### Why would this feature be useful?

At the same time that you can play the game on several computers, it serves as a backup copy of them.

**Comment by gr3ger** [comment]
It would require a backend server that someone has to pay for. 
A tip would be to have your save data folder synced with google drive / dropbox etc.

**Comment by Squall-Leonhart** [comment]
yeah, no, don't do this with any drive service, there are too many cases of incomplete synchronisations and reversions.

**Comment by Flyingbacen** [comment]
I'm unsure if you could do something similar in Windows, but in Linux, you should be able to create a systemd file, and make it so that it automatically moves your files when you close Ryujinx using an application that puts your drive into a custom folder (I forgot what it's called)

**Comment by subworx** [comment]
This problem could be mitigated by Ryujinx not caring about "how Nintendo does it" and instead renaming the save directories from `0000000x` depending on the order in which you first launch the games, to the actual Title ID like any normal person would do.

This would allow us to use `SyncThing` or similar tools. No cloud but at least something to sync between e.g. Steam Deck and PC, as I cannot be bothered to start the emu on PC and Deck and launch every new game on each just so the numbered directories stay in sync - let alone restarting from scratch on both devices just so the numbers align and I can use my sync tool.

Maybe I am not the only one who thinks this is a make-or-break feature, making me use Yuzu over Ryujinx for as many games as possible except the ones Yuzu does not recognize for whatever reasons.

**Comment by AcK77** [comment]
It could be useful but the emulator doesn't have to take care about files syncing.
You have to do it using any external tool.
We could consider cloud syncing one day, but provide this kind of service have a cost we can't support for now.
Thanks.

**Comment by subworx** [comment]
The problem is, you do not enable people to use an external tool, by randomly naming the save game directories depending on game launch order instead of game ID.

**Comment by MetrosexualGarbodor** [comment]
This is not "random", this is how the Switch itself does it. We did not engineer that, this is an emulator, not Nintendo HQ. Redirect your complaints to them for designing it this way.

**Comment by gdkchan** [comment]
FWIW saves and all the guest file system functionality are managed by Libhac (which is an external library), so if this was changed, it would need to be changed on Libhac side AFAIK. Personally I would not be against changing that since there are already other things that we do that the Switch doesn't for convenience, for example, we don't require installing application or their updates/DLCs.
