### ISSUE TITLE
[Bug] Fire Emblem Engage Ryujinx closing for no reason

### ISSUE THREAD

**Issue by NoNomaer23** [Ryujinx/Ryujinx#4644]
### Description of the issue

The emulator closes suddenly midgame. I have 2 recordings if you want proof.

### Reproduction steps

Emulator closes even during midgame or while idle, it just suddenly closes. Mid combat animations, idling in somniel, idling in map, pretty much everywhere in the game, this was not present during previous versions of Ryujix.

### Log file

[Ryujinx_1.1.697_2023-04-05_17-51-52.log](https://github.com/Ryujinx/Ryujinx/files/11158228/Ryujinx_1.1.697_2023-04-05_17-51-52.log)
[Ryujinx_1.1.697_2023-04-05_18-49-46.log](https://github.com/Ryujinx/Ryujinx/files/11158229/Ryujinx_1.1.697_2023-04-05_18-49-46.log)

### OS

Windows 10 

### Ryujinx version

1.1.697

### Game version

1.3.0

### CPU

Ryzen 5 3400g

### GPU

NVIDIA GTX 1650

### RAM

16GB DDR4

### List of applied mods

N/A

### Additional context?

None

**Comment by Bjorn29512** [comment]
use discord for support, switch to vulkan and enable texture recompression.

**Comment by NoNomaer23** [comment]
Noted. Thanks for the fast response.
