### ISSUE TITLE
[Bug] Scott Pilgrim vs The World The Game – Complete Edition crashes Ryujinx upon loading

### ISSUE THREAD

**Issue by mdsmendes94** [Ryujinx/Ryujinx#4650]
### Description of the issue

It crashes Ryujinx upon loading and closes itself

### Reproduction steps

Step 1. Try to run the game
Step 2. Watch Ryujinx crash

### Log file

[Ryujinx_1.1.699_2023-04-06_10-46-09.log](https://github.com/Ryujinx/Ryujinx/files/11171213/Ryujinx_1.1.699_2023-04-06_10-46-09.log)

### OS

Windows 11 Pro 22H2 22621.1344

### Ryujinx version

1.1.699

### Game version

1.0

### CPU

Ryzen 5 3550h

### GPU

GTX 1650 Mobile

### RAM

16GB

### List of applied mods

None

### Additional context?

NVIDIA DRIVER 531.41

**Comment by joe564338** [comment]
Create a mii with the mii applet and then select ignore missing services on system settings. For whatever reason it works.

**Comment by BigTinz** [comment]
This issue is still occurring in the current version of Ryujinx. 

I've created a Mii via the applet, and ticked "ignore missing services", and SPvTW crashes the emulator on boot every time.
