### ISSUE TITLE
[Bug] LDN wireless room not working - MK8D

### ISSUE THREAD

**Issue by sjskdkd** [Ryujinx/Ryujinx#4651]
### Description of the issue

I am unable to join other's rooms within Mario Kart 8 Deluxe. Trying to do so would result in an a error from the game, but none from the client. In some cases the game would just crash with no error message.

### Reproduction steps

Open Ryujinx LDN
Open Mario Kart 8 Deluxe with the latest DLC and updates.
Have a friend create a room or join one from a random player.
The error would pop up when you're trying to choose a driver, kart, wheels and glider, kicking you out the room and back to the main menu. 
In some cases, the creation of a new room by another player while I'm in the wireless play screen can cause the game to crash for me.

### Log file

[Ryujinx_1.1.0-ldn3.0.2_2023-04-06_19-54-23.log](https://github.com/Ryujinx/Ryujinx/files/11175260/Ryujinx_1.1.0-ldn3.0.2_2023-04-06_19-54-23.log)
[Ryujinx_1.1.0-ldn3.0.2_2023-04-06_20-31-46.log](https://github.com/Ryujinx/Ryujinx/files/11175261/Ryujinx_1.1.0-ldn3.0.2_2023-04-06_20-31-46.log)
[Ryujinx_1.1.0-ldn3.0.2_2023-04-06_20-33-10.log](https://github.com/Ryujinx/Ryujinx/files/11175262/Ryujinx_1.1.0-ldn3.0.2_2023-04-06_20-33-10.log)

### OS

Win. 10

### Ryujinx version

1.1.0-Idn3.0.2

### Game version

2.3.0

### CPU

i7-9700K

### GPU

NVIDIA RTX 2060

### RAM

64Gb

### List of applied mods

n/a

### Additional context?

I have a custom mii. It causes the game to crash on start-up but I think that's a known issue.

**Comment by OldManKain** [comment]
Hello, you should be using our newest LDN build https://www.patreon.com/posts/74910544 there were some issues with 3.0.2 and connectivity which have been addressed in the newest build.   Also, for troubleshooting support please join us in our [Discord](https://discord.gg/ryujinxl) in the appropriate support channel.

**Comment by sjskdkd** [comment]
oh my god i was trying so hard to find an update 😭 ty!
