### ISSUE TITLE
[Bug] Monster hunter rise sunbreak doesn't open

### ISSUE THREAD

**Issue by Saryong0102** [Ryujinx/Ryujinx#4669]
### Description of the issue

when I click MH, just stop end close ldn.

### Reproduction steps

just click MH

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2023-04-11_02-53-21.log](https://github.com/Ryujinx/Ryujinx/files/11195054/Ryujinx_1.1.0-ldn3.1.3_2023-04-11_02-53-21.log)

### OS

windows 11

### Ryujinx version

1.1.0.ldn3.1.3

### Game version

13.0.0

### CPU

i7-1165G7

### GPU

Intel Xe Graphic

### RAM

16GB

**Comment by OldManKain** [comment]
Monster Hunter Rise Sunbreak only works on Master and LDN 3.0, you can grab it from our [Discord](https://discord.gg/ryujinx) in the ldn-monster-hunter channel.

**Comment by tbergeron** [comment]
@OldManKain I just compiled my own version on Mac M1 and it still crash. I read somewhere that the Mac build doesn't contain all the latest fixes. Any idea/suggestion? I don't think LDN 3.0 is available for Mac yet?

**Comment by GamerzHell9137** [comment]
> @OldManKain I just compiled my own version on Mac M1 and it still crash. I read somewhere that the Mac build doesn't contain all the latest fixes. Any idea/suggestion? I don't think LDN 3.0 is available for Mac yet?

#3425 is necessary for MHR with the latest update to work. Older versions of the game should work fine (Windows at least)
