### ISSUE TITLE
[Bug] Link's awakening random crashes when killing enemies

### ISSUE THREAD

**Issue by dyharlan** [Ryujinx/Ryujinx#4674]
### Description of the issue

Link's awakening crashes randomly when hitting enemies. There doesn't seem to be a pattern on when it happens.

### Reproduction steps

Play the game, try killing an enemy or a boss and the game freezes.

### Log file

[Ryujinx_1.1.703_2023-04-13_13-11-15.log](https://github.com/Ryujinx/Ryujinx/files/11218380/Ryujinx_1.1.703_2023-04-13_13-11-15.log)

### OS

Windows 11

### Ryujinx version

1.1.703

### Game version

1.0.1

### CPU

i5-9400

### GPU

NVIDIA GT-1030

### RAM

16GB DDR4 2666

**Comment by OldManKain** [comment]
There is no crash in your log, please join us in our discord https://discord.gg/ryujinx)for troubleshooting issues.
