### ISSUE TITLE
[Bug]with prod.key

### ISSUE THREAD

**Issue by Citrus1609** [Ryujinx/Ryujinx#4680]
### Description of the issue

the file prod.key is not installing even after lauching the app and it says over and over key is missing 

### Reproduction steps

so i luch the thing he open my cmd and then the key is missing so i click ok and then go on the files but there is not prod.key

### Log file

[Ryujinx_1.1.709_2023-04-15_18-14-04.log](https://github.com/Ryujinx/Ryujinx/files/11239983/Ryujinx_1.1.709_2023-04-15_18-14-04.log)
[Ryujinx_1.1.709_2023-04-15_17-52-37.log](https://github.com/Ryujinx/Ryujinx/files/11239984/Ryujinx_1.1.709_2023-04-15_17-52-37.log)
[Ryujinx_1.1.709_2023-04-15_18-11-42.log](https://github.com/Ryujinx/Ryujinx/files/11239985/Ryujinx_1.1.709_2023-04-15_18-11-42.log)

### OS

Widows 10

### Ryujinx version

1.0.470

**Comment by CoolFrenchPerson** [comment]
Prod keys are not included. Also please re-download ryujinx from the release you are using a version that is almost one year old

**Comment by OldManKain** [comment]
Keys come from your hackable Switch https://github.com/Ryujinx/Ryujinx/wiki/Keys
