### ISSUE TITLE
[Bug] Cannot Set Preferred GPU

### ISSUE THREAD

**Issue by GumbyXGames** [Ryujinx/Ryujinx#4689]
### Description of the issue

You cannot set a Preferred GPU under Settings->Graphics in Ryujinx built from source #4688. When trying to launch a game, Ryujix crashes to desktop.

### Reproduction steps

1.  Setup Ryujinx by manually installing latest firmware (16.0.1) and adding prod.key to **/Users/_<user_folder>_/Library/Application Support/Ryujinx/system**
2. Set Games Directory in Settings->User Interface->Game Directories
3. Switch to Settings->Graphics

Tested with fresh build from source (deleting application, **/Users/_<user_folder>_/Library/Application Support/Ryujinx/**,and **/Users/_<user_folder>_/.config/Ryujinx**).

Screenshot:
![No_GPU_Screenshot](https://user-images.githubusercontent.com/82996624/232348088-ff75648a-435b-40d3-951e-4f82c0f08edb.png)

### Log file

00:00:00.038 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.040 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.040 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.040 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.040 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.041 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.041 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.041 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.042 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.042 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.043 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.047 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.047 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.047 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.047 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.047 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.047 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.047 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.047 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.047 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.047 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.048 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.048 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.048 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.048 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.050 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.0-4688+0
00:00:00.053 |N| Application Print: Operating System: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 (Arm64)
00:00:00.053 |N| Application Print: CPU: Apple M1 Pro ; 10 logical
00:00:00.053 |N| Application Print: RAM: Total 16384 MiB ; Available 5963 MiB
00:00:00.055 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.055 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.104 |I| Gpu : Backend Threading (Auto): True
00:00:00.473 |N| Application LoadGuestApplication: Using Firmware Version: 16.0.1
00:00:00.473 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.486 |I| ModLoader QueryContentsDir: Searching mods for Title 0100097016B04000
00:00:00.487 |I| ModLoader QueryContentsDir: Searching mods for Title 0100097016B04000
00:00:00.488 |I| Loader Load: Loading rtld...
00:00:00.492 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.492 |I| Loader Load: Loading main...
00:00:00.536 |I| Loader PrintRoSectionInfo: main:
    Module: C:\Users\work\vg2\vg2_2ndMaster\vg2_pg\Project\Build\vg2\NX64_Release\vg2.nss
    SDK Libraries: SDK MW+Nintendo+NEX_MM-4_6_6
                   SDK MW+Nintendo+NEX_VS-4_6_6
                   SDK MW+Nintendo+NEX-4_6_6-
                   SDK MW+Nintendo+NEX_RK-4_6_6
                   SDK MW+Nintendo+NintendoSDK_libcurl-13_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Atk-13_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_libz-13_3_2-Release
00:00:00.536 |I| Loader Load: Loading sdk...
00:00:00.588 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 13.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_2-Release
00:00:00.608 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.608 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:00.614 |I| Loader LoadNsos: Loading image 2 at 0x000000000beda000...
00:00:00.617 |I| ModLoader LoadCheats: Build ids found for title 0100097016B04000:
    567CDD4C5251494C5CD70822E3CCC740C190C2B2000000000000000000000000
    5CF54F40F5886330EC73527D04643AAD8EC3C78A000000000000000000000000
    357EFC198E728CB5D55265AFF304F03CFC9CC0E3000000000000000000000000
00:00:00.619 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.652 |I| Loader Start: Application Loaded: CARDFIGHT!! Vanguard Dear Days v1.0.0 [0100097016b04000] [64-bit]
00:00:00.675 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:00.684 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:00.711 |S| HLE.OsThread.20 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:00.713 |E| GUI.RenderThread Application : Unhandled exception caught: System.IO.FileNotFoundException: Could not load from any of the possible library names! Please make sure that the library is installed and in the right place!
   at Silk.NET.Vulkan.Vk.CreateDefaultContext(String[] n)
   at Silk.NET.Vulkan.Vk.GetApi()
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in /Users/gumbyx84/Downloads/Projects/Ryujinx_Mac/Ryujinx/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 341
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in /Users/gumbyx84/Downloads/Projects/Ryujinx_Mac/Ryujinx/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 668
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in /Users/gumbyx84/Downloads/Projects/Ryujinx_Mac/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 373
   at Ryujinx.Ava.AppHost.RenderLoop() in /Users/gumbyx84/Downloads/Projects/Ryujinx_Mac/Ryujinx/Ryujinx.Ava/AppHost.cs:line 858
   at System.Threading.Thread.StartCallback()

### OS

MacOS 13.3

### Ryujinx version

4688

### Additional context?

Build using latest .NET SDK (dotnet-sdk-7.0.203-osx-arm64)

Build Command: ./distribution/macos/create_macos_release.sh ./ ./distribution/macos/temp ./distribution/macos/output ./distribution/macos/entitlements.xml 1.1.0-4688 0

**Comment by gdkchan** [comment]
That error sounds like it can't find MoltenVK, although I'm not sure why since it should be included when you build it.

**Comment by gdkchan** [comment]
This is a regression from #4686, the newer version of Silk.NET can't find MoltenVK anymore.

**Comment by GumbyXGames** [comment]
Noted and thank you. I did notice something odd: The new Config.json had `preferred_gpu` set to _null_.

**Comment by Ryan2603** [comment]
i have this issue before, but on windows, solved by reinstall the driver

**Comment by GumbyXGames** [comment]
> i have this issue before, but on windows, solved by reinstall the driver

You can't reinstall GPU drivers on a Apple silicon Mac
