### ISSUE TITLE
[Bug] Ryujinx 100% reproducible crash on startup

### ISSUE THREAD

**Issue by Metroid-Prime** [Ryujinx/Ryujinx#4691]
### Description of the issue

Crash on startup for all versions of Ryujinx (including latest 1.1.721) when Ryujinx is configured to read ROMS that are stored on locally mapped NETWORK DRIVE 
W:\ below is the said network drive. 

Crashes on startup every time.

[quote]
00:00:00.032 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.035 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.035 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.036 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.037 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.037 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.037 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73DF
00:00:00.038 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.038 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.038 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.040 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.041 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.041 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.041 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.041 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.041 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.041 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.042 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.042 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.042 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.042 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.046 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.721
00:00:00.050 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.050 |N| Application Print: CPU: AMD Ryzen 7 5700X 8-Core Processor ; 16 logical
00:00:00.050 |N| Application Print: RAM: Total 65462 MiB ; Available 59514 MiB
00:00:00.052 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.053 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.872 |E| GUI.ApplicationLibraryThread Application : Unhandled exception caught: System.IO.IOException: Invalid Signature. : 'W:\Ron's ROMS\Nintendo Switch\Monster Hunter Rise'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 125
   at Ryujinx.Ui.MainWindow.<UpdateGameTable>b__94_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 665
   at System.Threading.Thread.StartCallback()
[/quote]

### Reproduction steps

Launch any version of Ryujinx  (including including latest 1.1.721) with NSP files on network drive w/ mapped drive

### Log file

00:00:00.032 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.036 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.036 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.036 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.037 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.038 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.038 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73DF
00:00:00.039 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.039 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.039 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.041 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.041 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.042 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.042 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.042 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.042 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.042 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.042 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.043 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.043 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.043 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.043 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.047 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.721
00:00:00.050 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.050 |N| Application Print: CPU: AMD Ryzen 7 5700X 8-Core Processor ; 16 logical
00:00:00.051 |N| Application Print: RAM: Total 65462 MiB ; Available 58530 MiB
00:00:00.053 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.054 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.873 |E| GUI.ApplicationLibraryThread Application : Unhandled exception caught: System.IO.IOException: Invalid Signature. : 'W:\Ron's ROMS\Nintendo Switch\Monster Hunter Rise'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 125
   at Ryujinx.Ui.MainWindow.<UpdateGameTable>b__94_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 665
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.721

### Game version

N/A

### CPU

AMD 5700X

### GPU

XFX AMD 6700 XT

### RAM

64GB

### List of applied mods

N/A

### Additional context?

Crash on startup for all versions of Ryujinx (including latest 1.1.721) when ROMS are on locally mapped network drive.
When files are moved to local drives, Ryujinx does not crash.  Back to network drive (W:\) it crashes on startup & produces the error in log.

**Comment by AcK77** [comment]
This seems to be related to your network drive settings and not the emulator or the network drive speed.
Could you give us more information related to it?

**Comment by Metroid-Prime** [comment]
1) It works with Yuzu
2) The host computer is on a gigabit network
3) The host SSD is one of the top 3 fastest hard drives (SK Hynix P41 Platinum)

**Comment by AcK77** [comment]
I suggest you to try https://support.microsoft.com/en-us/kb/2686098 which seems to be a server settings issue as I said.

**Comment by jgoyvaerts** [comment]
@Metroid-Prime can you provide information about the Host computer? Operating system version, etc.

**Comment by AcK77** [comment]
Closed due to lack of informations.

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime can you provide information about the Host computer? Operating system version, etc.

Apologies. Github has not been notifying me about replies here until the ticket was closed, ugh.

The host computer that has the extracted ROMs is a Mac MIni M2 running ventura (latest as of 5/28/23) through an  SMB share. The games were hosted on a fast SSD connected via TB4. 

I've since moved them locally to my PC and the crashes have stopped.

**Comment by Metroid-Prime** [comment]
> I suggest you to try https://support.microsoft.com/en-us/kb/2686098 which seems to be a server settings issue as I said.

Try what specifically?  The host server is a Mac. These instructions seem like they're not meant for Windows 10 as the computer playing the games.

**Comment by patrick-hovsepian** [comment]
What user account is ryujinx running as? Does that user have read access to your smb share?

**Comment by fullpwemium** [comment]
@NikoMuffin did you ever fix this? Exact same issue here
