### ISSUE TITLE
[Bug] I can't set system time in Mac M1

### ISSUE THREAD

**Issue by soliditydev30** [Ryujinx/Ryujinx#4696]
### Description of the issue

I am using Macbook Pro M1.
I tried to set system time in setting.
But it's not working correctly.
I checked Config.json file and change system_time_offset value manually.
I think that emulator doesn't change this variable correctly when user change system time.

### Reproduction steps

Please open setting->System and change System Time.
It's not working correctly.
system_time_offset variable changed with wrong value in Config.json.

### Log file

There is not log file.

### OS

macos 13.3.1 (22E261)

### Ryujinx version

1.1.0

**Comment by TimeZlicer** [comment]
Good day

There is a workaround, when you click on the field, instead of typing anything, swipe to scroll

From there, a list of timezones should appear and you can pick yours

**Comment by FolkSong** [comment]
It's the same on Windows I think, timezone is stuck at UTC. I tried scrolling with the mouse wheel and arrows but it doesn't change. 

You can manage to get the correct time in-game by setting "System Time" to the appropriate offset (Eg. I'm at UTC-6 so I set the time 6 hours earlier than the actual time) but this is a workaround.

**Comment by MutantAura** [comment]
This issue is fixed in master.
