### ISSUE TITLE
[Regression] Xenoblade Chronicles 3 : Screen goes white on initiating the boss fight from build 1.1.664 onwards

### ISSUE THREAD

**Issue by Bjorn29512** [Ryujinx/Ryujinx#4698]
### Description of the issue

Build 1.1.664 #4442  introduced a regression in XB 3 where the screen would go white after initiating a boss battle in Keves Castle region.

### Reproduction steps

- MAKE SURE ALL MODS ARE DISABLED 
- Select load game and open the save in slot no 3/ second save in order : Keves Castle region.
- Once you enter the game approach the checkpoint in front and skip the cut scene. 
[0.zip](https://github.com/Ryujinx/Ryujinx/files/11276731/0.zip)

### Log file

[Ryujinx_1.1.663_2023-04-20_00-44-12.log](https://github.com/Ryujinx/Ryujinx/files/11276807/Ryujinx_1.1.663_2023-04-20_00-44-12.log)
[Ryujinx_1.1.664_2023-04-20_00-32-14.log](https://github.com/Ryujinx/Ryujinx/files/11276808/Ryujinx_1.1.664_2023-04-20_00-32-14.log)

### OS

Windows 11

### Ryujinx version

1.1.723

### Game version

1.3.0

### CPU

i5-12400f

### GPU

GTX 1660 Super (driver 531.41)

### RAM

32 GB

### List of applied mods

NONE

### Additional context?

Attachments showcasing the issue : 

1.1.663
![image](https://user-images.githubusercontent.com/110204265/233177600-8a3bbcec-639c-4b69-8823-54c5b6ec0b37.png)

1.1.664
![image](https://user-images.githubusercontent.com/110204265/233176988-fc9ad79f-349a-459c-848b-af4b9123a249.png)

**Comment by SPWizard01** [comment]
i thought i was the only one having this issue, in my case clearing shader cache helped, it is as if the more shaders you have the more often this can occur.
