### ISSUE TITLE
[Bug] Rune Factory 4 Special Crash in game

### ISSUE THREAD

**Issue by jsgATsbu** [Ryujinx/Ryujinx#4699]
### Description of the issue

The game runs well in normal mode
but in newlywed mode, when talking to NPC it crashes immediately.
The difference between the two mode is that they use Emote on the character arts in newlywed mode, not sure if this is the cause.
I will attach the log here.

### Reproduction steps

1. Open Ryujinx
2. Load Rune Factory 4 Special 1.02 version with DLC
3. Start with Newlywed mode and talk with NPC
4. Game crashes with following log

### Log file

[Ryujinx_1.1.723_2023-04-19_20-16-27.log](https://github.com/Ryujinx/Ryujinx/files/11278798/Ryujinx_1.1.723_2023-04-19_20-16-27.log)

### OS

Windows 11

### Ryujinx version

1.1.723

### Game version

1.0.2

### CPU

AMD Ryzen 5 5600X 6-Core Processor   3.70 GHz

### GPU

NVIDIA GeForce RTX 3060 Ti

### RAM

16.0 GB

### List of applied mods

No Mod

**Comment by GamerzHell9137** [comment]
If its not a regression, game related issues should be reported in the corresponding thread on the compatibility list.

https://github.com/Ryujinx/Ryujinx-Games-List/issues/243

**Comment by OldManKain** [comment]
Known Issue.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/243
