### ISSUE TITLE
XCI with updates not working

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#470]
Oky Xci Failed Loading RyujiNX Master Build PR #467 
![anotacao 16](https://user-images.githubusercontent.com/37957125/47270539-9be80780-d543-11e8-94a9-ed3a9da3b270.png)

**Comment by Thog** [comment]
This only happens on XCI containing updates.
To fix this we will need the latest changes on libhac to be stable and released on nugget.

**Comment by EmulationChannel** [comment]
@Thog https://github.com/Thealexbarney/LibHac/releases

**Comment by EmulationChannel** [comment]
Fixed XCI Files PR https://github.com/Ryujinx/Ryujinx/pull/476
