### ISSUE TITLE
Tearing ryujinx

### ISSUE THREAD

**Issue by Alessandroomv** [Ryujinx/Ryujinx#4700]
### Description of the issue

I downloaded ryujinx a few weeks ago and I hadn't had any problems, until I updated my mac to macos ventura 13.3.1 and now all the games I play suffer from tearing, I don't know if this has something to do with the mac os update, but now all my games suffer from this, any solution?

### Reproduction steps

1.- You enter any game
2.- you move the right joystick and start to see the tear

### Log file

.

### OS

MaOs Ventura 13.3.1

### Ryujinx version

1.1.0

### Game version

1.0.0 (Example, Mario 3d world)

### CPU

Apple M1

### GPU

7 or 8 cores

### RAM

8 GB

### List of applied mods

none

### Additional context?

.

**Comment by TimeZlicer** [comment]
https://github.com/Ryujinx/Ryujinx/pull/4744 might already fixed this

**Comment by siegmund-heiss-ich** [comment]
I tried the current master version. I can confirm it is fixed.
