### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Bilbockay** [Ryujinx/Ryujinx#4713]
### Description of the issue

The game Pokemon BDSP crashes every 15 minutes.

### Reproduction steps

Every time I run the game, about 15 minutes later, the game crash.

### Log file

[Ryujinx_1.1.0-macos1_2023-04-23_22-59-51.log](https://github.com/Ryujinx/Ryujinx/files/11305057/Ryujinx_1.1.0-macos1_2023-04-23_22-59-51.log)

### OS

macOS Monterey 12.5

### Ryujinx version

1.1.0

### Game version

1.1.0

### GPU

M1

### RAM

8 Gb

**Comment by OldManKain** [comment]
Disable expand Dram to 6GB (Developer Option) and please use our Discord https://discord.gg/ryujinx for troubleshooting issues.
