### ISSUE TITLE
[Bug]Ryujinx Can't Load SaveGame.

### ISSUE THREAD

**Issue by RockingSisyphus** [Ryujinx/Ryujinx#4715]
### Description of the issue

Ryujinx Load Saves in C:\Users\aketo\AppData\Roaming\Ryujinx\bis\user\save\0000000000000002\0 Folder but Save Saves in C:\Users\aketo\AppData\Roaming\Ryujinx\bis\user\save\0000000000000002\1 Folder,That make Game Never be Saved.
that bug happens ever time when I play Zeldar

### Reproduction steps

Open Game,Save,Exit Game,Reload Game,Save,And It happen

### Log file

[Ryujinx_1.1.726_2023-04-24_00-02-35.log](https://github.com/Ryujinx/Ryujinx/files/11305128/Ryujinx_1.1.726_2023-04-24_00-02-35.log)
[Ryujinx_1.1.726_2023-04-24_00-06-52.log](https://github.com/Ryujinx/Ryujinx/files/11305129/Ryujinx_1.1.726_2023-04-24_00-06-52.log)
[Ryujinx_1.1.726_2023-04-24_06-45-11.log](https://github.com/Ryujinx/Ryujinx/files/11305130/Ryujinx_1.1.726_2023-04-24_06-45-11.log)

### OS

Windows11

### Ryujinx version

1.1.726

### Game version

1.6.0

### CPU

i9 12900kf

### GPU

rtx 1080ti

### RAM

32gb

**Comment by OldManKain** [comment]
From what I'm seeing in your log something has the saves folders in use.  Try restarting your computer, make sure the Ryujinx folder is not on the Desktop, also if you have a 3rd party Anti-Virus make sure Ryujinx has an exception.

For further assistance please join us in our Discord https://discord.gg/ryujinx for troubleshooting issues.

**Comment by RockingSisyphus** [comment]
> From what I'm seeing in your log something has the saves folders in use. Try restarting your computer, make sure the Ryujinx folder is not on the Desktop, also if you have a 3rd party Anti-Virus make sure Ryujinx folder has an exception.
> 
> For further assistance please join us in our Discord https://discord.gg/ryujinx for troubleshooting issues.

yes,but as i say,Save file in Ryujinx\bis\user\save\0000000000000002\1 Folder but Ryujinx only Load Save which in Ryujinx\bis\user\save\0000000000000002\0 Folder

**Comment by OldManKain** [comment]
And I told you what is causing the Issue please try what I have told you to resolve it.
