### ISSUE TITLE
Fire Emblem Engage crashing only in battle no. 2 of Fell Xenologue

### ISSUE THREAD

**Issue by pvtblaubaer** [Ryujinx/Ryujinx#4718]
[save files.zip](https://github.com/Ryujinx/Ryujinx/files/11310456/save.files.zip)
### Description of the issue

FE Engage worked like a charm with and without mods for the whole campaign + first map of fell xenologue but battle no. 2 where a certain woman joins you for the first time, it always crashes once i try to start the fight. i can prepare as long as i want but as soon as i hit the start battle button ryujinx crashes. 

im playing on 2x resolution with smaa turned on and v sync turned off (nvidia control panel limits to 48 frames).
i tried two different update files from different sources and lowered graphics settings (like lower res and enabling v sync).
i also tried different save files and turning off every mod. still got the same error log.

### Reproduction steps

hitting the start battle button on battle no. 2 of fell xenologue dlc. 

preparing and swapping team members etc. or looking at enemies doesnt crash the game, only once i hit the start battle button the game crashes instantly.

### Log file

00:01:33.337 |I| HLE.GuestThread.19 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Fire Emblem Engage, PID: 96
   0x000000000b20b2f8	main:0x32072f8	
   0x000000000b206a9c	main:0x3202a9c	
   0x000000000a2869a4	main:0x22829a4	
   0x0000000009e73d5c	main:0x1e6fd5c	
   0x000000000a367618	main:0x2363618	
   0x000000000a8213bc	main:0x281d3bc	
   0x000000000a8211ac	main:0x281d1ac	
   0x000000000a81e190	main:0x281a190	
   0x000000000a81e030	main:0x281a030	
   0x000000000a61ffb0	main:0x261bfb0	
   0x00000000081009d4	main:0xfc9d4	
   0x00000000084478a8	main:0x4438a8	
   0x00000000085a90b0	main:0x5a50b0	
   0x0000000008595918	main:0x591918	
   0x000000000858b540	main:0x587540	
   0x00000000088e8a1c	main:0x8e4a1c	
   0x000000000873ece4	main:0x73ace4	
   0x000000000873ed34	main:0x73ad34	
   0x000000000873f06c	main:0x73b06c	
   0x00000000084b358c	main:0x4af58c	nnMain:0x061c
   0x000000000eff57f4	sdk:0x2a87f4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	

00:01:33.339 |I| HLE.GuestThread.19 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000001
	X[01]:	0x00000016719c6a74
	X[02]:	0x0000000000000004
	X[03]:	0x000000000001b97a
	X[04]:	0x0000000000000004
	X[05]:	0x0000000000000000
	X[06]:	0x000000000bc77200 (main:0x3c73200)	=> 
	X[07]:	0x0000000000000000
	X[08]:	0x000000000001b97e
	X[09]:	0x0000000000000004
	X[10]:	0x0000000000200000
	X[11]:	0x00000016719c6a74
	X[12]:	0x0000000000000018
	X[13]:	0xfffffffffffff000
	X[14]:	0x0000000000000005
	X[15]:	0x0000000000000000
	X[16]:	0x000000000e2844e8
	X[17]:	0x000000000f2895f0 (sdk:0x53c5f0)	=> memcpy
	X[18]:	0x00000016719c6000
	X[19]:	0x0000001678da5150
	X[20]:	0x0000000000000000
	X[21]:	0x000000000e173038
	X[22]:	0x000000000e173040
	X[23]:	0x000000000e16d528
	X[24]:	0x000000000e16d540
	X[25]:	0x000000000e1570e8
	X[26]:	0x000000000e17f298
	X[27]:	0x000000000e17f2b8
	X[28]:	0x0000000000000000
	FP:	0x00000049f21080e0 (SP:-0x0030)
	LR:	0x000000000ab53f90 (main:0x2b4ff90)	=> 
	SP:	0x00000049f21080b0 (SP)
	PC:	0x000000000f289778 (sdk:0x53c778)	=> memcpy:0x0188

00:01:33.339 |E| HLE.GuestThread.19 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:33.377 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270

### OS

Windows 11

### Ryujinx version

1.1.730

### Game version

2.0.0

### CPU

11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz   2.50 GHz

### GPU

NVIDIA RTX 3070

### RAM

32 GB

### List of applied mods

'FEE_DoubleSP'

'Improved Art Damage Calculation & Inheritable skill cost halved + Extra Skills (STR or MAGE) + (SPD divided by 2)'
'Battle Outfits and More Outfits 2.0.1'

### Additional context?

had to cut the log because the body was too long to post

**Comment by pvtblaubaer** [comment]
> provide a save file pls

uploaded the auto save + a normal save, both experience the same crash (i already unequipped every emblem ring etc for trouble shooting but didnt help)

**Comment by solarmystic** [comment]
Could be a corrupted save on your end or the usage of unsupported mods, I've  managed to start and complete Fell Xenologue 2 with no issues, and i've never used any mods on my save whatsoever, 

At Fell Xenologue 3 on the world map now 

![image](https://user-images.githubusercontent.com/4345150/234194015-daae235a-fc50-49b1-8fb5-29591badf75f.png)

Tested with the latest ryujinx mainline 1.1.731.

**Comment by Bjorn29512** [comment]
the value changing mods likely corrupt the save files for good causing the invalid mem region crash then, this issue can be closed since its not an emu issue and likely caused by mods which corrupt saves.

**Comment by pvtblaubaer** [comment]
thank you all for testing!

is there anyway to "save" this save file? 

i did test it on yuzu now and it works fine there
