### ISSUE TITLE
Problem whit DLL not found 

### ISSUE THREAD

**Issue by champii8029** [Ryujinx/Ryujinx#4719]
### Description of the issue

when entering the app it stays cycled and gives the following error
image is attached

### Reproduction steps

a

### Log file

![Screenshot_4](https://user-images.githubusercontent.com/58783472/234162063-e5443282-cce3-4c2e-a137-cd2d95426060.png)

### OS

windows

### Ryujinx version

1.1.726

### CPU

ryzen 5

### GPU

nvidi 1650

### RAM

8

**Comment by OldManKain** [comment]
You seem to be missing some files, Re-download the emulator and extract it somewhere that is not on the desktop or in a protected folder.

It could also be due to a 3rd party Anti-Virus.

For further assistance please join us in our Discord https://discord.gg/ryujinx for further troubleshooting.
