### ISSUE TITLE
[Feature Request] DLSS Implementation

### ISSUE THREAD

**Issue by HDPacks** [Ryujinx/Ryujinx#4727]
### Overview

With NVIDIA providing both a DLSS SDK and a streamline kit, both with Vulkan support, I think it should be completely possible to implement DLSS. I figure this probably wouldn't be easy, with having to provide motion vectors for every frame, but hopefully the devs could figure this out?

### Smaller details

On each evaluate call (i.e. each frame), provide:
-The raw color buffer for the frame (in HDR or LDR/SDR space).
-Screen space motion vectors that are: accurate and calculated at 16 or 32 bits per-pixel; and updated each frame.
-The depth buffer for the frame.
-The exposure value (if processing in HDR space).

### Nature of request

DLSS implementation for Ryujinx.

### Why would this feature be useful?

This would be a huge improvement for game performance. It would also help people with mid-tier cards to play games at higher resolution.

**Comment by riperiperi** [comment]
> Screen space motion vectors that are: accurate and calculated at 16 or 32 bits per-pixel; and updated each frame.

This is not available. The others are very hard to discover as games may go though any number of post processing stages and tend to draw the UI on top, which would very negatively impact DLSS.

It’s much easier to increase internal scaling on emulated games, as they are designed to run on really weak GPUs anyways.

**Comment by MutantAura** [comment]
In addition to the above points, any GPU that supports DLSS is likely going to be capable of at least 2x scaling in all titles. Even if it were possible, the only GPU I can see having any benefit is the RTX 3050. 

Closing for the above technical challenges. The same is also true for any future requester for FSR2 and XeSS.
