### ISSUE TITLE
[Bug] Ryujinx crashes upon loading Mario Party Superstars with mods

### ISSUE THREAD

**Issue by Noah-HalfSquid** [Ryujinx/Ryujinx#4732]
### Description of the issue

I put all the mods in the correct mod directory, but when I start playing I get a black screen before a crash. The log file shows an error at the bottom but I have no clue what it means. Any help is appreciated.

### Reproduction steps

Download some character, text, and minigame mods, and then boot up the game.

### Log file

[Ryujinx_1.1.0-ldn3.0.1_2023-04-26_14-36-38.log](https://github.com/Ryujinx/Ryujinx/files/11337579/Ryujinx_1.1.0-ldn3.0.1_2023-04-26_14-36-38.log)

### OS

Windows 10

### Ryujinx version

ldn3.0.1 (or 1.1.0)

### Game version

1.1.1

### List of applied mods

Peter Griffin over Birdo
Mayro over Mario
Wallace over Luigi
Morgana over Yoshi
Samus over Daisy
Shrek over DK
Mr. Krabs over Wario
Jonesy over Waluigi (includes an emote.nx.bea file)
Pot of Greed over Thwomp
Luigi's Mansion King Boo over King Boo
Alternative Text
Aggressive Stickers

### Additional context?

no audio or hud pictures were changed, only things found in romfs

**Comment by OldManKain** [comment]
Does it work without the mods?

**Comment by Noah-HalfSquid** [comment]
> [OldManKain](https://github.com/OldManKain) commented [4 minutes ago](https://github.com/Ryujinx/Ryujinx/issues/4732#issuecomment-1524144547)
Does it work without the mods?

Yes, it does, and it runs smoothly as well

**Comment by OldManKain** [comment]
Okay so this is one of three issues.
1. The mods aren't made for the version of the game you are running.
2. The mods are installed wrong.
3. The mods are broken entirely.

**Comment by Noah-HalfSquid** [comment]
Understood, I'll have to test them one by one
