### ISSUE TITLE
[Bug] can't build current master on Linux

### ISSUE THREAD

**Issue by notpentadactyl** [Ryujinx/Ryujinx#4740]
### Description of the issue

building current master shows this error:

```
MSBuild version 17.5.0+6f08c67f3 for .NET
MSBUILD : error MSB1009: Project file does not exist.
``` 

### Reproduction steps

clone master and try building it on (Arch) Linux.

### Log file

-

### OS

Arch Linux

### Ryujinx version

master

**Comment by TSRBerry** [comment]
Tested it here, works without issues. CI also works, so you probably did something wrong.

If you want help or need any other assistance feel free to join the Ryujinx discord server.
