### ISSUE TITLE
[Bug] motion delay in switch pro controller mode

### ISSUE THREAD

**Issue by RuafuMan-Obs** [Ryujinx/Ryujinx#4756]
### Description of the issue

Crosshair doesnt point to the direction accurately when turning controller fastly,instead it turns slowly to the right angle when controller is stable. This doesnt happen when using andorid phone cemuhook motion control

### Reproduction steps

every game using motion to move sight/aim

### Log file

[Ryujinx_1.1.742_2023-05-02_09-21-01.log](https://github.com/Ryujinx/Ryujinx/files/11369069/Ryujinx_1.1.742_2023-05-02_09-21-01.log)

### OS

windows 10

### Ryujinx version

1.1.472

### CPU

i9-9900k

### GPU

Nvidia RTX 2080Ti

### RAM

8G*2 4266Mhz

**Comment by AcK77** [comment]
Pirated games aren't supported. Thanks.
