### ISSUE TITLE
[Bug] Crashes during any race loading screen of mario kart 8

### ISSUE THREAD

**Issue by ariesardonyx** [Ryujinx/Ryujinx#4762]
### Description of the issue

always crashes to desktop when game proceed to race loading screen， version 1.1.742 works fine

### Reproduction steps

always crashes during loading screen after selecting race，character，kart type etc

### Log file

[Ryujinx_1.1.743_2023-05-02_16-40-13.log](https://github.com/Ryujinx/Ryujinx/files/11371426/Ryujinx_1.1.743_2023-05-02_16-40-13.log)

### OS

windows 10

### Ryujinx version

1.1.743

### Game version

2.3.0

### CPU

i7-10875H

### GPU

NVIDIA Geforce RTX 2070 Super

### RAM

32GB

**Comment by riperiperi** [comment]
Can you be more specific as to what you are doing in the menu? I cannot replicate this issue on a 1070.
![image](https://user-images.githubusercontent.com/6294155/235631299-732482e2-a124-46e0-8779-b738051fc424.png)

**Comment by riperiperi** [comment]
One possibility is that the older GPU drivers are not handling host imported memory very well. If it keeps crashing, could you try update the driver and see if it still does?

**Comment by ariesardonyx** [comment]
> One possibility is that the older GPU drivers are not handling host imported memory very well. If it keeps crashing, could you try update the driver and see if it still does?

after updating nvidia driver no crashes appeared, the problem seems solved. just wonder why 1.1.742 works fine and 1.1.743 cause crash, but nvm, thanks for help

**Comment by riperiperi** [comment]
We're using an extension to speed up texture readbacks, but `v512.78.0.0` and earlier seem to have a bug. I think we'll have to end up forcing it off on older versions of the driver.
