### ISSUE TITLE
[Bug] Game wont open after sudden crash

### ISSUE THREAD

**Issue by SiegeTheStars** [Ryujinx/Ryujinx#4769]
### Description of the issue

I was playing Breath of the Wild when my game suddenly crashed, after that I tried to open Ryujinx and the emulator could not even open again.

### Reproduction steps

Launch Breath of The Wild, play for 20 minutes, crashes, and the emulator doesn't open anymore.

### Log file

[Ryujinx_1.1.743_2023-05-02_11-17-14.log](https://github.com/Ryujinx/Ryujinx/files/11374295/Ryujinx_1.1.743_2023-05-02_11-17-14.log)
[Ryujinx_1.1.743_2023-05-02_11-18-52.log](https://github.com/Ryujinx/Ryujinx/files/11374297/Ryujinx_1.1.743_2023-05-02_11-18-52.log)
[Ryujinx_1.1.743_2023-05-02_11-26-05.log](https://github.com/Ryujinx/Ryujinx/files/11374299/Ryujinx_1.1.743_2023-05-02_11-26-05.log)

### OS

Windows 10

### Ryujinx version

1.1.743

### CPU

Ryzen 5600

### GPU

GALAX RTX 360

### RAM

16GB

### List of applied mods

No mods where applied 

### Additional context?

Nothing special i was just in the Great Plateau.

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, read the FAQ or ask on discord. 
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-cant-open-ryujinx-e-application--unhandled-exception-caught-systemtypeinitializationexception-the-type-initializer-for-gtkapplication-threw-an-exception-----systemdllnotfoundexception-gtk-libgtk-3-0dll-libgtk-3so0-libgtk-30dylib-gtk-3dll
