### ISSUE TITLE
Game crashes on start (BOTW)

### ISSUE THREAD

**Issue by Raiznb** [Ryujinx/Ryujinx#4770]
### Description of the issue

After 15 sec game just freeze. After clearing cache, emulator crashes 

### Reproduction steps

Start the game

### Log file

[Ryujinx_ 1.1.0-macos1_2023-05-02_17-35-39.log](https://github.com/Ryujinx/Ryujinx/files/11374352/Ryujinx_.1.1.0-macos1_2023-05-02_17-35-39.log)

### OS

MacOS 13.2

### Ryujinx version

1.1.0

### CPU

M1 Pro

### RAM

16

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, read the FAQ or ask on discord.
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#the-legend-of-zelda-breath-of-the-wild
