### ISSUE TITLE
[Regression] Performance loss on all games on some Intel GPUs from build 1.1.683 onwards

### ISSUE THREAD

**Issue by Void-Time** [Ryujinx/Ryujinx#4771]
### Description of the issue

Build 1.1.683 #4607 has introduced a Regression to some Intel GPUs, where all games I have tested so far have suffered a large performance loss which has caused games to experience framerates from 3 to 13 on menus where they had previously experienced 30fps on previous builds. 

### Reproduction steps

- Launch any game

### Log file

[Ryujinx_1.1.682_2023-05-02_20-11-58.log](https://github.com/Ryujinx/Ryujinx/files/11374609/Ryujinx_1.1.682_2023-05-02_20-11-58.log)
[Ryujinx_1.1.743_2023-05-02_20-19-34.log](https://github.com/Ryujinx/Ryujinx/files/11374665/Ryujinx_1.1.743_2023-05-02_20-19-34.log)

### OS

Windows 11

### Ryujinx version

1.1.743

### Game version

1.0.0

### CPU

i5-1135G7

### GPU

Intel(R) Iris(R) Xe 

### RAM

16GB

### Additional context?

1.1.682

https://user-images.githubusercontent.com/84456308/235708769-fda72bb6-a4bc-4816-b595-9aad4568355c.mp4

1.1.743

https://user-images.githubusercontent.com/84456308/235710323-a16a028a-cf01-499e-b963-4e6cdfbb6686.mp4

**Comment by riperiperi** [comment]
Note that this doesn’t affect all Intel GPUs. The ones I have tested are unaffected.

**Comment by Squall-Leonhart** [comment]
has this iris Xe got the classic [DCH](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) driver installed, or the one specifically designated for[ Arc / Iris Xe](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)?

The former does work on the Iris Xe for some reason, but the latter has a better performing UMD.

**Comment by Void-Time** [comment]
> has this Iris Xe got the classic [DCH](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) driver installed, or the one specifically designated for[ Arc / Iris Xe](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)?
> 
> The former does work on the Iris Xe for some reason, but the latter has a better performing UMD.
> 
> hrm, the log doesn't output a valid intel driver version, should be in the format XX.X.XXX.XXXX, such as v31.0.101.4314

I was using [intel's driver and support assistant](https://www.intel.com/content/www/us/en/support/detect.html) to update my drivers which are Arc/Iris Xe drivers, but when checked which version my drivers were it stated I was on drivers that I was using a 5-month-old driver, which probably explains why the log didn't consider it a valid version or such.

Now that I have manually updated the drivers to the latest arc/iris xe drivers, it seems that I am suffering from the same issue as previously stated.
