### ISSUE TITLE
[Bug] Certain cheats no longer working in game as of Ryujinx version 1.1.744

### ISSUE THREAD

**Issue by Ashuraman666** [Ryujinx/Ryujinx#4780]
### Description of the issue

As it says in the title, cheats are no longer working for any game, even games where the cheats worked perfectly before such as Breath Of The Wild.

### Reproduction steps

I used Breath Of The Wild as an example because I know the cheats for that work. Load game, turn on any cheat, none of them work.

### Log file

[Ryujinx_1.1.744_2023-05-03_03-55-19.log](https://github.com/Ryujinx/Ryujinx/files/11379025/Ryujinx_1.1.744_2023-05-03_03-55-19.log)

### OS

Windows 10

### Ryujinx version

1.1.744

### Game version

All

### CPU

Intel Core i7 @ 3.00GHz

### GPU

NVIDIA GeForce GTX 1650 

### RAM

8GB

**Comment by OldManKain** [comment]
Can confirm no cheats working on 1.1.744.

**Comment by DuckyThePilot** [comment]
Confirmed as well.

**Comment by piplup55** [comment]
linux seems unaffected
![image](https://user-images.githubusercontent.com/100526773/235826750-9826869b-0a81-4f8e-a007-bb4f5d926d5e.png)
![image](https://user-images.githubusercontent.com/100526773/235826768-57987274-ff3f-4c76-afdb-bd275fc72b72.png)

**Comment by StanTheRebel** [comment]
Confirmed as well

**Comment by epl609** [comment]
confirmed happening with Zelda

**Comment by AcK77** [comment]
This is currently fixed since the original PR (#4720) was reverted.
