### ISSUE TITLE
[Feature Request] Choose a profile from command line

### ISSUE THREAD

**Issue by jamesst20** [Ryujinx/Ryujinx#4784]
### Overview

I would like to be able to pin twice a game in Steam Big Picture using Steam ROM Manager and choose a specific profile for the save game depending on who is playing.

Right now

```
ryujinx.exe path/to/xci
```

Launches the game. I would like to be able to do something like

```
ryujinx.exe path/to/xci --profile "Profile Name"
```

Also, I could not find any documentation about existing options.

### Smaller details

```
ryujinx.exe path/to/xci --profile "Profile Name"
```

### Bonus

Something that would be even better is being asked directly by Ryujinx what profile we want to use and have controller compatibility there. I requested command line arguments because it's likely easier to implement.

### Why would this feature be useful?

Using a PC as a gaming console in the living room is always better without a mouse and keyboard

**Comment by TSRBerry** [comment]
This already exists.

**Comment by jamesst20** [comment]
@TSRBerry 

I am very sorry about that. Would you mind linking to me the documentation? Or is it just working exactly as I described?

**Comment by TSRBerry** [comment]
No worries, it's not really well documented. You can find the existing options here: https://github.com/Ryujinx/Ryujinx/blob/250fc51374d39b4ea08d45b12d9674dd8b3451eb/src/Ryujinx.Ui.Common/Helper/CommandLineState.cs#L26-L82

Although it does work exactly like you described.
