### ISSUE TITLE
[Blog Post Request] Why C#, how is it so fast?!

### ISSUE THREAD

**Issue by gamedevsam** [Ryujinx/Ryujinx#4789]
### Overview

I'm a software engineer and I know C# is a high level garbage collected language, unlike C++ which is a lower level language without any garbage collection. Building an emulator demands maximum performance, so building one in C# is quite an unusual decision.

I'd love to read an article, blog post, or even reddit post / markdown file on why C# is / was a good decision for emulation. On one hand it makes it a lot easier to build / contribute, but on the other hand you need to deal with the garbage collection and you do leave some perf on the table.

What amazes me is that for most games the performance difference between Ryujinx and Yuzu is not really noticeable. You'd think the C++ implementation would be faster, but in this case it doesn't seem to matter much.

What sort of black magic was employed here to make Ryujinx not suffer from any meaningful / noticeable performance differences compared to its non-garbage collected variants?

### Smaller details

N/A

### Nature of request

Sorry if this is inappropriate to post here, feel free to close this issue if you don't think it's worthwhile.

### Why would this feature be useful?

Many software engineers have an assumption that lower level languages with manual memory management are always faster than higher level languages with garbage collection. Ryujinx stands out as an example that is not necessarily the case.

How is this possible?!

Please help me understand, many thanks in advance!

**Comment by TSRBerry** [comment]
Does this article answer your question?

https://boilingsteam.com/an-interview-with-gdkchan-creator-of-ryujinx/

**Comment by amayra** [comment]
I love C# and trying to make a Vita emulator with C# based ARMeilleure

**Comment by gamedevsam** [comment]
@TSRBerry yes it does thank you!

If @gdkchan or anyone else has some extra insight here feel free to comment on this issue, otherwise I'm closing it to keep the repo tidy.
