### ISSUE TITLE
[Bug] Several Games are crashing before lauching it

### ISSUE THREAD

**Issue by adriengonz** [Ryujinx/Ryujinx#4802]
### Description of the issue

Hello,
I just updated to 1.1.750, and I tried to launch animal crossing and splatoon afterwards, and the games don't want to launch. The shaders seem to load, but the game does not launch, Ryujinx crash...

you will find the logs below

### Reproduction steps

Launch the game

### Log file

00:00:00.090 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.099 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.099 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.100 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.101 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.102 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.103 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1004
00:00:00.104 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.105 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.105 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.110 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.123 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.124 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.124 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.124 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.124 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.124 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.124 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.124 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.125 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.126 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.126 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.127 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.127 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.127 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.133 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.750
00:00:00.140 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.140 |N| Application Print: CPU: Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz ; 4 logical
00:00:00.141 |N| Application Print: RAM: Total 12205 MiB ; Available 7997 MiB
00:00:00.146 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.146 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.087 |I| Gpu : Backend Threading (Auto): True
00:00:00.549 |N| Application LoadApplication: Using Firmware Version: 15.0.0
00:00:00.549 |I| Application LoadApplication: Loading as XCI.
00:00:00.609 |I| ModLoader QueryContentsDir: Searching mods for Title 01006F8002326000
00:00:00.611 |I| ModLoader QueryContentsDir: Searching mods for Title 01006F8002326000
00:00:00.621 |I| Loader Load: Loading rtld...
00:00:00.632 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.632 |I| Loader Load: Loading main...
00:00:01.375 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\Park\App\Rom\NX64\Product\code\Park.nss
    SDK Libraries: SDK MW+OmronSoftware+iWnn-1_9_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-9_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_libz-9_3_1-Release
                   SDK MW+Nintendo+NEX-4_6_3-
                   SDK MW+Nintendo+PiaClone-5_24_0
                   SDK MW+Nintendo+PiaCommon-5_24_0
                   SDK MW+Nintendo+Pia-5_24_0
                   SDK MW+Nintendo+PiaLan-5_24_0
                   SDK MW+Nintendo+PiaLocal-5_24_0
                   SDK MW+Nintendo+PiaSession-5_24_0
                   SDK MW+Nintendo+PiaTransport-5_24_0
                   SDK MW+Nintendo+PiaNex-5_24_0-forNEX-4_6_3
                   SDK MW+Nintendo+NEX_MM-4_6_3
                   SDK MW+Nintendo+NintendoWare_Vfx2-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Atk-9_3_1-Release
                   SDK MW+Nintendo+NEX_CO-4_6_3
                   SDK MW+Microsoft+Havok_Cloth-2019_1
                   SDK MW+Microsoft+Havok_Animation-2019_1
00:00:01.376 |I| Loader Load: Loading subsdk0...
00:00:01.466 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-9_3_1-Release
00:00:01.466 |I| Loader Load: Loading sdk...
00:00:01.714 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 9.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-9_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-9_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-9_3_1-Release
00:00:02.077 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:03.143 |I| Ptc Load: Loaded Translation Cache (size: 53931432 bytes, translated functions: 49502).
00:00:03.174 |I| Ptc Load: Loaded Profiling Info (size: 156249 bytes, profiled functions: 49502).
00:00:03.197 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:03.201 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:03.234 |I| Loader LoadNsos: Loading image 2 at 0x000000000babb000...
00:00:03.238 |I| Loader LoadNsos: Loading image 3 at 0x000000000c1c8000...
00:00:03.254 |I| ModLoader LoadCheats: Build ids found for title 01006F8002326000:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    7FC1BAFF976AECA414520CB89F4616CB00000000000000000000000000000000
    5A7ADA8DD7447C10AA244944F64D0AFF17C50539000000000000000000000000
    AD3FDFBD62A5F4B082D385FFE420D4400ABB831D000000000000000000000000
00:00:03.262 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:03.453 |I| Loader Start: Application Loaded: Animal Crossing: New Horizons v1.0.0 [01006f8002326000] [64-bit]
00:00:03.467 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:03.492 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:04.082 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 780 (Vulkan v1.2.175, Driver v474.30.0.0)
00:00:04.098 |I| GPU.MainThread Gpu LoadShaders: Loading 195 shaders from the cache...
00:00:04.691 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:06.540 |I| HLE.GuestThread.21 Ptc LoadTranslations: 49502 translated functions loaded
00:00:06.731 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:06.751 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:06.751 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.752 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.767 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:08.507 |W| HLE.GuestThread.21 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:08.626 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:08.634 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:08.664 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:08.701 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:08.775 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:08.776 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:08.776 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:08.777 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:08.778 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:08.779 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:08.779 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:08.781 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:08.833 |S| HLE.OsThread.9 ServiceHid ActivateDebugPad: Stubbed. {appletResourceUserId: 1}
00:00:08.834 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:08.841 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:08.841 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:08.843 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:08.846 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:08.848 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:08.854 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:08.855 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:08.855 |S| HLE.OsThread.22 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:08.855 |S| HLE.OsThread.22 ServiceAm LockExit: Stubbed. 
00:00:08.870 |S| HLE.OsThread.22 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72180189621280768}
00:00:08.873 |S| HLE.OsThread.22 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:09.176 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:09.176 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:09.468 |S| HLE.OsThread.22 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:09.468 |S| HLE.OsThread.22 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:09.468 |S| HLE.OsThread.22 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:09.706 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:09.710 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV8
00:00:09.748 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:09.749 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:09.751 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:09.805 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:09.807 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:09.829 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:11.377 |E| HLE.OsThread.17 Application : Unhandled exception caught: System.NotImplementedException: BcatService command ID: 0 is not implemented
   at Ryujinx.Horizon.Sdk.Sf.Cmif.ServiceDispatchTableBase.ProcessMessageImpl(ServiceDispatchContext& context, ReadOnlySpan`1 inRawData, IReadOnlyDictionary`2 entries, String objectName) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Cmif\ServiceDispatchTableBase.cs:line 55
   at Ryujinx.Horizon.Sdk.Sf.Cmif.ServiceDispatchTable.ProcessMessage(ServiceDispatchContext& context, ReadOnlySpan`1 inRawData) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Cmif\ServiceDispatchTable.cs:line 20
   at Ryujinx.Horizon.Sdk.Sf.Cmif.ServiceObjectHolder.ProcessMessage(ServiceDispatchContext& context, ReadOnlySpan`1 inRawData) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Cmif\ServiceObjectHolder.cs:line 31
   at Ryujinx.Horizon.Sdk.Sf.Cmif.DomainServiceObjectDispatchTable.ProcessMessageImpl(ServiceDispatchContext& context, ServerDomainBase domain, ReadOnlySpan`1 inRawData) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Cmif\DomainServiceObjectDispatchTable.cs:line 64
   at Ryujinx.Horizon.Sdk.Sf.Cmif.DomainServiceObjectDispatchTable.ProcessMessage(ServiceDispatchContext& context, ReadOnlySpan`1 inRawData) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Cmif\DomainServiceObjectDispatchTable.cs:line 12
   at Ryujinx.Horizon.Sdk.Sf.Cmif.ServiceObjectHolder.ProcessMessage(ServiceDispatchContext& context, ReadOnlySpan`1 inRawData) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Cmif\ServiceObjectHolder.cs:line 31
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerSessionManager.DispatchRequest(ServiceObjectHolder objectHolder, ServerSession session, Span`1 inMessage, Span`1 outMessage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerSessionManager.cs:line 315
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerSessionManager.ProcessRequestImpl(ServerSession session, Span`1 inMessage, Span`1 outMessage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerSessionManager.cs:line 199
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerSessionManager.ProcessRequest(ServerSession session, Span`1 message) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerSessionManager.cs:line 166
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.ProcessForSession(MultiWaitHolder holder) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 297
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.Process(MultiWaitHolder holder) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 213
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.WaitAndProcessRequestsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 135
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.ServiceRequests() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 116
   at Ryujinx.Horizon.Bcat.BcatIpcServer.ServiceRequests() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Bcat\BcatIpcServer.cs:line 40
   at Ryujinx.Horizon.Bcat.BcatMain.Main(ServiceTable serviceTable) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\Bcat\BcatMain.cs:line 20
   at Ryujinx.Horizon.ServiceEntry.Start(ISyscallApi syscallApi, IVirtualMemoryManager addressSpace, IThreadContext threadContext) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Horizon\ServiceEntry.cs:line 24
   at Ryujinx.HLE.HOS.Horizon.<>c__DisplayClass181_0.<StartNewServices>b__0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Horizon.cs:line 357
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1258
   at System.Threading.Thread.StartCallback()

### OS

Windows 10 v22H2

### Ryujinx version

1.1.750

### Game version

1.0.0

### CPU

i5-3550

### GPU

NVIDIA GTX 780

### RAM

12

### List of applied mods

Nothing

**Comment by MetrosexualGarbodor** [comment]
Fixed in 1.1.751

**Comment by adriengonz** [comment]
it's works, thanks !
