### ISSUE TITLE
[Bug] [macOS Master] Depth issue in Dark Souls

### ISSUE THREAD

**Issue by shinra-electric** [Ryujinx/Ryujinx#4813]
### Description of the issue

After going in-game, distant objects and effects are presented on top of where they should be. 

<img width="1392" alt="Screenshot 2023-05-05 at 15 05 47" src="https://user-images.githubusercontent.com/50119606/236466981-c7e09169-1b46-49f9-ab86-e9c2c736aaba.png">

### Reproduction steps

Go in-game.

### Log file

[Ryujinx_1.1.1+0_2023-05-05_15-03-53.log](https://github.com/Ryujinx/Ryujinx/files/11406511/Ryujinx_1.1.1%2B0_2023-05-05_15-03-53.log)

### OS

macOS 13.3.1

### Ryujinx version

1.1.1-0 (Master)

### Game version

1.0.3

### CPU

M1 Pro

### GPU

M1 Pro

### RAM

16GB

### List of applied mods

N/A

### Additional context?

This is using a local build of Ryujinx from the master branch, not the official macOS release.

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues with locally built versions. macOS still has several graphical fixes pending to be upstreamed; until this process is complete, it won't be much help to document graphical issues.

**Comment by gdkchan** [comment]
Dark Souls actually renders much worse than this on macos1 (or rather, doesn't render). I think that issue might not be macOS specific, you might want to check https://github.com/Ryujinx/Ryujinx-Games-List/issues/72

**Comment by shinra-electric** [comment]
I know this issue was closed, but it has been fixed recently: 

<img width="1624" alt="Screenshot 2024-04-09 at 21 46 28" src="https://github.com/Ryujinx/Ryujinx/assets/50119606/b8a09902-8eaa-49b9-83f8-9ca62da4878b">
