### ISSUE TITLE
[Feature Request] Changelog Button in Updater

### ISSUE THREAD

**Issue by flopityflips** [Ryujinx/Ryujinx#4814]
### Overview

I'd really like a button that links to the changelog just for convience sake. I get since it's updated near daily- sometimes multiple times a day- it'd be a bit cumbersome to add what's been changed in the updater itself so a quick button press to get to the changelog page from the updater would be appreciated.

### Smaller details

honestly i'd just like a button in the updater and/or somewhere in the emulator. don't think i can get more detailed than that

### Nature of request

i dont know what to put for the nature. i just want a button that can open a link so i don't have to manually go to the github page every update lol. here's a mockup i drew in paint.
![worlds worst mockup](https://user-images.githubusercontent.com/108518610/236487251-a4ec61ba-94eb-4563-818a-2af5c7e526ab.png)

### Why would this feature be useful?

it'd just be convenient. not uber necessary but i imagine it'd be relatively easy to implement and would make it faster and easier to see what improvements and optimizations are made with each update and/or if any bugs or issues per game or with the emulator have been addressed.

**Comment by AcK77** [comment]
Duplicated of #3262
