### ISSUE TITLE
[Bug] Computer not going to sleep with no game running

### ISSUE THREAD

**Issue by d3xMachina** [Ryujinx/Ryujinx#4828]
### Description of the issue

Ryujinx prevents the computer from sleeping when no game is launched or when a game execution is suspended. It should only prevent sleep when a game is running.

#1850 is the PR that added the functionality to prevent sleep.

On windows you can check that Ryujinx is preventing the computer from going to sleep by opening a terminal with admin rights and the command : 
> powercfg /requests

The result : 
> DISPLAY :
> [PROCESS] \Device\HarddiskVolume9\Emulators\Ryujinx\bin\Ryujinx.exe
> 
> SYSTEM :
> None.
> 
> AWAYMODE :
> None.
> 
> EXECUTION :
> None.
> 
> PERFBOOST :
> None.
> 
> ACTIVELOCKSCREEN :
> None.

### Reproduction steps

- Start Ryujinx with no other program preventing sleep
- Wait enough time without touching the keyboard or mouse so the computer can go to sleep
- The computer does not go to sleep

### OS

Windows 11

### Ryujinx version

1.1.762

**Comment by Squall-Leonhart** [comment]
Literally working as intended, and every game that has been implemented correctly makes certain to keep the system awake.

**Comment by d3xMachina** [comment]
How is it working as intended ? If I start Ryujinx without starting a game it prevents my computer from going to sleep. I don't see how it's the intended behavior.

**Comment by OldManKain** [comment]
It was put into Ryujinx to keep the display from going to sleep while playing a game.

You could always make a Feature Request to have it toggleable.

**Comment by d3xMachina** [comment]
> It was put into Ryujinx to keep the display from going to sleep while playing a game.
I was not playing a game. Ryujinx was opened but no game was started.

**Comment by d3xMachina** [comment]
I can't reopen the issue. Should I create a new one ?

**Comment by piplup55** [comment]
> I can't reopen the issue. Should I create a new one ?

no, as oldman said this is not a bug this is intended behavior

**Comment by d3xMachina** [comment]
I really don't understand, the intended behavior is to prevent sleep only when playing a game as stated in the linked PR. If I have no game running as I said it should really not prevent the computer from going to sleep as nothing is happening. I'm really confused here...

**Comment by piplup55** [comment]
> I really don't understand, the intended behavior is to prevent sleep only when playing a game as stated in the linked PR. If I have no game running as I said it should really not prevent the computer from going to sleep as nothing is happening. I'm really confused here...

that pr prevents the main window from triggering a sleep event, the main window being the same one used when playing a game, You could always make a Feature Request to have it toggleable.
