### ISSUE TITLE
[Feature Request] Command line close app and pop-up

### ISSUE THREAD

**Issue by phibryzo** [Ryujinx/Ryujinx#4829]
### Overview

Hello,

CASE 1 :
When I use command line for launch app, the game launch correctly.
So, when I want quit by "Escape" button, a "pop-up" appear ("unsaved progress...")
I valid and I return in Ryujinx interface.

CASE 2 :
When I use command line for launch app, I've sometimes this "pop-up" because XBOX 360 controller is "off" :
![image](https://user-images.githubusercontent.com/14242172/236611578-cfb4a787-495d-4866-8d68-8f77fa6280de.png)

Good Job. Thank you !

### Smaller details

Any solution for remove "pop-up" interface with --option command line ?
It's possible to close app with a simple "ESC" action with  --option command line ?

### Nature of request

Command line implement

### Why would this feature be useful?

Command line must have standalone fonctionnality. thread process must not to be blocked by any interface.

Thank you

**Comment by yohann84L** [comment]
Hi @phibryzo , I have the same issue. Did you find a solution ?

**Comment by phibryzo** [comment]
Hello,
Sorry, but no solution for this issue. I waiting.

**Comment by TSRBerry** [comment]
Please use the headless release if you want to control everything via the command line.
