### ISSUE TITLE
Wrong game version display[Bug]

### ISSUE THREAD

**Issue by phibryzo** [Ryujinx/Ryujinx#4830]
### Description of the issue

Hello,

With gui interface, I see the wrong version of xci files :

![image](https://user-images.githubusercontent.com/14242172/236617079-7482487f-9685-4fbe-a703-2e6b1cd9adc7.png)

This is the 2.30 version.
With right click, property, no update and no dlc.

On Yuzu (sorry for comparaison) :
![image](https://user-images.githubusercontent.com/14242172/236617341-8b3cea19-f874-4906-9ab7-c98830f4836b.png)

Any idea ?

### Reproduction steps

Boot app with MK 2.30 xci version and show interface

### Log file

It's not issue in game

### OS

win10

### Ryujinx version

1.1.762

### Game version

2.30

### List of applied mods

not apply

**Comment by Squall-Leonhart** [comment]
Not reproducible, you likely haven't selected the update in the update/dlc managers.

![image](https://user-images.githubusercontent.com/1098176/236617586-1ab39760-aae7-4be2-82f1-3cacde7eb664.png)

**Comment by phibryzo** [comment]
Yes, it's merged data. superxci. at title screen (in game), version 1.00 appear.

So, I do to have 2 files and not a super xci ?

**Comment by OldManKain** [comment]
I can not reproduce this issue, anyway it's best to keep your files separate after you dump them so bugs like this do not happen.

**Comment by phibryzo** [comment]
It's OK with splitted files. Thank you !
