### ISSUE TITLE
[Bug]All versions after 1.1.73 cannot load Zelda

### ISSUE THREAD

**Issue by taoyuancun123** [Ryujinx/Ryujinx#4833]
### Description of the issue

I hadn't used the emulator for several days before the bug occurred. Today, after updating to 1.1.763, the game couldn't load properly. (Breath of the Wild)
The specific bug reproduction process is: load the game, which can be successful, and then enter the main interface. But after selecting a save file, loading the game will go wrong.
I tried 1.1763 and 1.1.751, but neither of them worked.
Not until I re-downloaded 1.1.739, then the game could load normally.  

### Reproduction steps

load game
then select save file in main UI
it will 100% occurre.

### Log file

00:00:00.037 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.041 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.041 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.041 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.042 |I| Configuration LogValueChange: BackendThreading set to: Off
00:00:00.043 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.043 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x249D
00:00:00.044 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.044 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.044 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.045 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.051 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.051 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.051 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.051 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.052 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.052 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.053 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.053 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.053 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.053 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.055 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.763
00:00:00.058 |N| Application Print: Operating System: Microsoft Windows 10.0.22000 (X64)
00:00:00.058 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i5-12400 ; 12 logical
00:00:00.059 |N| Application Print: RAM: Total 16088 MiB ; Available 11388 MiB
00:00:00.061 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.061 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.041 |I| Gpu : Backend Threading (Off): False
00:00:00.349 |N| Application LoadApplication: Using Firmware Version: 16.0.0
00:00:00.350 |I| Application LoadApplication: Loading as NSP.
00:00:00.371 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.372 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.375 |I| Loader Load: Loading rtld...
00:00:00.384 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.384 |I| Loader Load: Loading main...
00:00:00.535 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Cafe\U-King\trunk\Game\App\Rom\NX64\Product\code\U-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_G3d-0_12_14-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-0_12_13-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-0_12_14-Release
                   SDK MW+Nintendo+NintendoWare_Font-0_12_14-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-0_12_14-Release
                   SDK MW+Nintendo+NintendoWare_Atk-0_12_14-Release
                   SDK MW+Havok+hcl_2014_1
                   SDK MW+Havok+hkp_2014_2
                   SDK MW+Havok+hkai_2014_2
                   SDK MW+Havok+hka_2014_2
00:00:00.536 |I| Loader Load: Loading subsdk0...
00:00:00.545 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: nvn
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_NVN-0_12_14-Release
00:00:00.545 |I| Loader Load: Loading subsdk1...
00:00:00.546 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: nnDisplay
00:00:00.546 |I| Loader Load: Loading subsdk2...
00:00:00.547 |I| Loader PrintRoSectionInfo: subsdk2:
    Module: libcurl
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-0_12_14-Release
00:00:00.548 |I| Loader Load: Loading subsdk3...
00:00:00.568 |I| Loader PrintRoSectionInfo: subsdk3:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-0_12_14-Release
00:00:00.568 |I| Loader Load: Loading sdk...
00:00:00.594 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 0.17.14
    SDK Libraries: SDK MW+Nintendo+NintendoSdk_nnSdk-0_12_14-Release
00:00:00.698 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.599 |I| Ptc Load: Loaded Translation Cache (size: 87106693 bytes, translated functions: 101482).
00:00:01.618 |I| Ptc Load: Loaded Profiling Info (size: 295099 bytes, profiled functions: 82887).
00:00:01.625 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.627 |I| Loader LoadNsos: Loading image 1 at 0x0000000008006000...
00:00:01.637 |I| Loader LoadNsos: Loading image 2 at 0x000000000a388000...
00:00:01.638 |I| Loader LoadNsos: Loading image 3 at 0x000000000a57c000...
00:00:01.638 |I| Loader LoadNsos: Loading image 4 at 0x000000000a5a6000...
00:00:01.638 |I| Loader LoadNsos: Loading image 5 at 0x000000000a5eb000...
00:00:01.640 |I| Loader LoadNsos: Loading image 6 at 0x000000000ac61000...
00:00:01.645 |I| ModLoader LoadCheats: Build ids found for title 01007EF00011E000:
    DB4B66DBF275A8261E2D51375F20C47D9A729537000000000000000000000000
    2094F152836683A3632C6153FD84AB8000000000000000000000000000000000
    9F7E69A5C5E8AA0E61199AC33DD0D2D13717C190000000000000000000000000
    FC3D9AAE8B6769E2D69961C005E239F536805F19000000000000000000000000
    2BA5FCC00BA28CDDA26C792E934949CBB5CBC513000000000000000000000000
    AA72F973A902C24747AF4522EE67EA9A7994C3FB000000000000000000000000
    99D55FB2A2CE9E14BD5D56428EC0397BE46E48EB000000000000000000000000
00:00:01.648 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.707 |I| Loader Start: Application Loaded: The Legend of Zelda: Breath of the Wild v1.0.0 [01007ef00011e000] [64-bit]
00:00:01.711 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.730 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:03.290 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3070 Laptop GPU (Vulkan v1.3.194, Driver v511.81.0.0)
00:00:03.296 |I| GUI.RenderLoop Gpu LoadShaders: Loading 3832 shaders from the cache...
00:00:33.003 |I| GUI.RenderLoop Gpu LoadShaders: Rebuilding 3832 shaders...
00:01:34.366 |I| GUI.RenderLoop Gpu LoadShaders: Rebuilt 3832 shaders successfully.
00:01:34.367 |I| GUI.RenderLoop Gpu LoadShaders: Shader cache loaded.
00:01:35.339 |I| HLE.GuestThread.19 Ptc LoadTranslations: 82887 translated functions loaded
00:01:35.450 |S| HLE.OsThread.20 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:01:35.453 |S| HLE.OsThread.20 ServiceAm AcquireForegroundRights: Stubbed. 
00:01:35.453 |S| HLE.OsThread.20 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:01:36.492 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Thread: MainThread
    Filename: D:/home/Cafe/U-King/trunk/Game/Lib/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp
    Line: 18
    Function: PrintStringImpl
    Message: 00000010

00:01:36.493 |S| HLE.OsThread.20 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:01:36.494 |S| HLE.OsThread.20 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:01:36.494 |S| HLE.OsThread.20 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:01:36.532 |I| HLE.OsThread.20 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:01:36.546 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:01:36.563 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:01:36.607 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:01:36.607 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:01:36.608 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:01:36.609 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:01:36.610 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:01:36.610 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:01:36.611 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:01:36.630 |S| HLE.OsThread.9 ServiceHid ActivateDebugPad: Stubbed. {appletResourceUserId: 1}
00:01:36.631 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 0}
00:01:36.633 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:01:36.634 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 96 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:01:36.639 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:01:36.639 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:01:36.642 |I| HLE.OsThread.20 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:01:36.644 |I| HLE.OsThread.20 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:01:36.675 |S| HLE.OsThread.20 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72197163296350208}
00:01:39.096 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:01:39.098 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV1
00:01:39.112 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:01:39.113 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:01:39.128 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:01:39.226 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:01:39.319 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceSystemEvent: Stubbed. 
00:01:39.320 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:01:39.354 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 96 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:01:40.206 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:01:40.476 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5 ; _gyroscopeZeroDriftMode: Tight}
00:01:40.476 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541 ; _gyroscopeZeroDriftMode: Tight}
00:01:58.809 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 96
 UserId: 00000000000000010000000000000000
 Room: option 
 Report: {
    "BalloonTextOnOff": 1,
    "AutoSaveOnOff": 1,
    "CameraUpDownReverse": 0,
    "CameraRLReverse": 0,
    "TextRubyOnOff": 1,
    "JumpButtonChange": 0,
    "StickSensitivity": 2,
    "GyroOnOff": 0,
    "MiniMapDirection": 1,
    "AmiiboItemOnOff": 0,
    "MainScreenOnOff": 0,
    "TextWindowChange": 1,
    "DockInOnOff": 1,
    "ControllerType": 1,
    "AttachExtGrip": 0,
    "CtrlModeHandheldFree": 0,
    "CtrlModeHandheldExt": 0,
    "CtrlModeHandheldFullKey": 0,
    "CtrlModeHandheldHandheld": 0,
    "CtrlModeConsoleFree": 0,
    "CtrlModeConsoleExt": 0,
    "CtrlModeConsoleFull": 101194,
    "PlayTimeHandheld": 0,
    "PlayTimeConsole": 166669,
    "PlayTimeAll": 166669
}

00:01:59.484 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:59.635 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 315
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 219
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id, Boolean strict) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 72
   at Ryujinx.Graphics.Gpu.GpuContext.CreateHostSyncIfNeeded(HostSyncFlags flags)
   at Ryujinx.Graphics.Gpu.Image.Texture.SignalModifying(Boolean bound) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1426
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateRenderTargetState(RenderTargetUpdateFlags updateFlags, Int32 singleUse) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 424
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount, Int32 drawFirstVertex, Int32 drawVertexCount) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 107
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__78_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 471
   at Ryujinx.Graphics.GAL.IRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\IRenderer.cs:line 57
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 447
   at System.Threading.Thread.StartCallback()

### OS

windows 11 

### Ryujinx version

above 1.1.73

### Game version

1.0.0

**Comment by MarkLanders777** [comment]
It works fine here
![1](https://user-images.githubusercontent.com/82430579/236638987-e82d527f-94a8-45c6-b332-bcd2bc8555b6.png)

**Comment by riperiperi** [comment]
If you continue to get issues, you should update your graphics driver. I think the older one has issues with a recently added feature.

**Comment by taoyuancun123** [comment]
cpu:12th intel core i5-12400
GPU:nvidia geforce rtx 3070 laptop gpu

There is a problem after 1.1.739, and it will be normal after downgrading to 1.1.739

**Comment by riperiperi** [comment]
Or you could update your drivers...

**Comment by taoyuancun123** [comment]
Sent to you by mail?

**Comment by taoyuancun123** [comment]
oh，i get you，your mean update my drivers on my computer, I will try

**Comment by taoyuancun123** [comment]
I thought you said you wanted me to upload the driver so that you can locate the bug.

**Comment by taoyuancun123** [comment]
Thank you, after updating the driver, the problem is solved.
