### ISSUE TITLE
[Feature Request] Automatic builds for macOS

### ISSUE THREAD

**Issue by karwa** [Ryujinx/Ryujinx#4836]
### Overview

Currently, the bot which generates binaries appears to only do so for Windows and Linux ([example](https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.763)):

![image](https://user-images.githubusercontent.com/5254025/236650530-a38e0b1a-6ef2-4262-8b41-e3387b9fd443.png)

It would be nice to provide builds for macOS users, too.

### Smaller details

N/A

### Nature of request

Infrastructure

### Why would this feature be useful?

So macOS users can try the latest builds without needing to download the .Net SDK and build the project manually.

**Comment by TSRBerry** [comment]
We could do this if Github Actions supported `Arm64`, but they don't.

See these issues for more context:
- https://github.com/actions/runner-images/issues/2187
- https://github.com/actions/runner-images/issues/5631

**Comment by gdkchan** [comment]
Is it not possible to cross-compile from x86 to arm64?

**Comment by TSRBerry** [comment]
If we are able to use `codesign` on Linux or Windows it should be [possible](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run#cross-platformarchitecture-restrictions), although the build times will probably increase a lot and they are already huge.

**Comment by gdkchan** [comment]
We already have Github Action building for macOS on the other repo iirc, so it's totally possible. The only limitation is that we can't run the tests without a mac arm64 machine.

**Comment by TSRBerry** [comment]
I thought this was running on an arm64 self-hosted runner from @marysaka, but it doesn't look like that's the case.
If you have no objections because of the missing tests, I could add the pieces for that to our CI here.

**Comment by marysaka** [comment]
> I thought this was running on an arm64 self-hosted runner from @marysaka, but it doesn't look like that's the case. If you have no objections because of the missing tests, I could add the pieces for that to our CI here.

We would need a runner somwhere for that still

**Comment by TSRBerry** [comment]
I think we should probably wait for Github to add arm64 runners to run the tests for that as well.

**Comment by gdkchan** [comment]
> I think we should probably wait for Github to add arm64 runners to run the tests for that as well.

We don't know when that will happen and sooner or later we will need those builds. So I don't think we should wait for that. Most of the tests are CPU tests that wouldn't work on macOS anyway right now, since Unicorn doesn't play nicely with .NET on arm64 Mac due to the JIT memory restrictions.

**Comment by TSRBerry** [comment]
I may have worded that badly, I just meant we should not add our own runner here to run arm64 tests right now and instead wait for Github to add support for arm64 runners.

**Comment by TSRBerry** [comment]
Apple M1 runners are planned for Q4 2023: https://github.com/orgs/github/projects/4247?pane=issue&itemId=5944419

(Thanks @Candygoblen123 for letting me know!)

**Comment by ingangi** [comment]
Hi @TSRBerry @gdkchan 
If I compile the latest code on M1 macbook pro, can I get the same features as the windows/linux version, or does mac have an independent branch, and I need to wait for your merge code?

**Comment by TSRBerry** [comment]
https://github.com/Ryujinx/Ryujinx/issues/4062

You get the same features as Windows/Linux, but that won't be enough to make everything work as on the release build. You can see the upstreaming progress in the issue above.
