### ISSUE TITLE
[Bug] Ryujinx 1.1.763 (Master, Ava, Flatpak) crashes/freezes when launching SMT V (1.0.0, 1.0.2, with or without DLC)

### ISSUE THREAD

**Issue by sw0leymammoth** [Ryujinx/Ryujinx#4839]
### Description of the issue

Ryujinx refuses to launch SMT V (010063b012dc6000) on Fedora 38 KDE, regardless of version of Ryujinx. This occurs using either Vulkan or OpenGL. The same cartridge dump works fine on Ryujinx 1.1.763 in Windows 11 and on my Steam Deck, and also launches fine in Yuzu. Logs usually don't indicate an error before Ryujinx either closes or freezes, but there were two messages I haven't been able to replicate ('Segmentation fault (core dumped)' and 'Fatal error. The RW block to unmap was not found'). Usually Ryujinx will  close and won't have any indication as to why in its logs. Running the program extracted from the tar.gz will close, the Flatpak version will hit about 5.3gb of ram usage and needs to be force closed or will sit frozen indefinitely.

### Reproduction steps

Fresh install of Ryujinx, use Vulkan, place keys, install firmware, load game directory, try to launch SMT V 1.0.0, program will freeze or close. Result is the same when adding 1.0.2 update, user saves, etc.

### Log file

[Ryujinx_1.1.763_2023-05-07_00-08-08.log](https://github.com/Ryujinx/Ryujinx/files/11414052/Ryujinx_1.1.763_2023-05-07_00-08-08.log)
[Ryujinx_1.1.763_2023-05-06_23-46-26.log](https://github.com/Ryujinx/Ryujinx/files/11414053/Ryujinx_1.1.763_2023-05-06_23-46-26.log)
[Ryujinx_1.1.763_2023-05-06_23-47-52.log](https://github.com/Ryujinx/Ryujinx/files/11414054/Ryujinx_1.1.763_2023-05-06_23-47-52.log)
[Ryujinx_1.1.763_2023-05-07_00-04-58.log](https://github.com/Ryujinx/Ryujinx/files/11414055/Ryujinx_1.1.763_2023-05-07_00-04-58.log)
[Ryujinx_1.1.763_2023-05-06_22-59-49.log](https://github.com/Ryujinx/Ryujinx/files/11414056/Ryujinx_1.1.763_2023-05-06_22-59-49.log)
[Ryujinx_1.1.763_2023-05-06_23-02-08.log](https://github.com/Ryujinx/Ryujinx/files/11414057/Ryujinx_1.1.763_2023-05-06_23-02-08.log)
[Ryujinx_1.1.763_2023-05-07_00-06-50.log](https://github.com/Ryujinx/Ryujinx/files/11414058/Ryujinx_1.1.763_2023-05-07_00-06-50.log)

### OS

Fedora Linux 38 (KDE)

### Ryujinx version

1.1.763 (Master, Ava, Flatpak)

### Game version

1.0.2

### CPU

AMD Ryzen 5 5600x

### GPU

AMD Radeon 6800xt

### RAM

16gb

### List of applied mods

Occurs with and without mods. Was able to successfully launch SMT V with the 1080p60 LOD mod with Ryujinx on Windows, however.

**Comment by gdkchan** [comment]
Duplicate of #3372?

**Comment by sw0leymammoth** [comment]
@gdkchan yep, seems like. It seems like it will open on software, and it seems like my system's default memory is 65530, so this is a duplicate.
