### ISSUE TITLE
[Feature Request]Auto restart on crash

### ISSUE THREAD

**Issue by goosecrash** [Ryujinx/Ryujinx#4841]
### Overview

Auto restart on crash, some games need multiple attempts to start, so I suggest that there should be an auto restart feature

### Smaller details

Easy to configure, easy to use

### Nature of request

Im not sure what this means

### Why would this feature be useful?

so that people don't have to deal with manually restarting the app

**Comment by MutantAura** [comment]
Could you provide some examples of games that need multiple boot attempts alongside a log?

**Comment by gdkchan** [comment]
I don't think implementing features to work around bugs is a very good thing in general.

**Comment by MutantAura** [comment]
Closing as won't fix.
