### ISSUE TITLE
[Bug] Breath of the wild crash

### ISSUE THREAD

**Issue by tommy-sorce** [Ryujinx/Ryujinx#4851]
### Description of the issue

The legend of Zelda breath of the wild crashes after about an hour of gameplay.

### Reproduction steps

Play botw for at least an hour 

### Log file

[Ryujinx_1.1.766_2023-05-07_23-36-29.log.txt](https://github.com/Ryujinx/Ryujinx/files/11416220/Ryujinx_1.1.766_2023-05-07_23-36-29.log.txt)

### OS

Windows 10 Pro N for workstations 

### Ryujinx version

1.1.767

### Game version

1.6

### CPU

I5 4670k

### GPU

Gigabyte Radeon RX 260x OC 1gb gddr5 

### RAM

8 GB DDR3 2400Mhz 

### List of applied mods

30 fps 
Disabled dynamic resolution

### Additional context?

Tested with and without mods.
Tested with 12 GB ram
Tested with Linux 
Tested with newest modded and amdgpu drivers for AMD 
Tested with CPU/GPU OC 

But issue is still present 😢

CPU is utilized at 75-80%
GPU is utilized at 55-60%
Game is stable with constant 30fps so i don't think it's an w3ak hardware issue.

**Comment by MutantAura** [comment]
Your GPU has 2GB of VRAM and is deprecated by AMD and out of driver support. 
The error is a VRAM exhaustion crash.
