### ISSUE TITLE
[Bug] Ryujinx on Mac can't read my controller

### ISSUE THREAD

**Issue by 2O48** [Ryujinx/Ryujinx#4875]
### Description of the issue

I use a Xbox series x controller on Mac and Windows at the same time. But since I switched the controller to Windows, ryujinx on my Mac can't read the controller any more even it appears in the controller list, I tried re-pairing the controller but it didn't work but Ryujinx on Windows can still read my controller successfully
<img width="1282" alt="SCR-20230510-taku" src="https://github.com/Ryujinx/Ryujinx/assets/21039418/91d94948-1959-49f0-b430-54831ebd6c2f">
<img width="1212" alt="SCR-20230510-tkan" src="https://github.com/Ryujinx/Ryujinx/assets/21039418/ca2fc267-5c31-440c-a4a2-34e6736d0562">

### Reproduction steps

Connect the controller to Mac
Launch Ryujinx and launch a game

### Log file

[Ryujinx_ 1.1.0-macos1_2023-05-10_22-34-13.log](https://github.com/Ryujinx/Ryujinx/files/11443065/Ryujinx_.1.1.0-macos1_2023-05-10_22-34-13.log)

### OS

macOS 13.3.1

### Ryujinx version

1.1.0

**Comment by CoolFrenchPerson** [comment]
![image](https://github.com/Ryujinx/Ryujinx/assets/123309403/85bd3515-4684-4678-8056-ccaf3b5c37f3)
i dont think this is a log file
anyways please use our discord for these kinds of issues: https://discord.gg/ryujinx

**Comment by 2O48** [comment]
I deleted my config.json in ~/.config/Ryujinx then it works again

**Comment by 2O48** [comment]
I deleted my config.json in ~/.config/Ryujinx then it works again
