### ISSUE TITLE
[Bug] Motion Control not Working (Extremely Buggy) for Switch Pro Controller in Zelda TotK

### ISSUE THREAD

**Issue by Light-Blue-Yoshi** [Ryujinx/Ryujinx#4878]
### Description of the issue

I have x2 top tier 3rd party controllers both capable of running in Nintendo Switch Pro Controller mode and with motion control (gyroscope) function that works in Yuzu for motion control aim assist but doesn't work 99% of the time in Ryujinx. The game tested on is The Legend of Zelda - Tears of the Kingdom. The controllers tested are the GuliKit KingKong 2 Pro Controller and the GuiliKit KingKong 2 Controller. Both controllers have the function (selected by pressing mode button on controller) to to connect via Bluetooth in either of these 4 modes:

Nintendo Switch Pro Controller Mode
Windows PC XINPUT Mode
Android & iOS Mode
Windows (Older) PC DINPUT Mode

Using Windows 11, I have tried Bluetooth pairing these 2 controllers in "Nintendo Switch Pro Controller Mode" and also tried in "Windows PC XINPUT Mode". Both controllers work with in these modes for most functions except I find that so far the only way I can get motion control to work is with both controllers connected in "Nintendo Switch Pro Controller Mode" and then only reliably with motion control using Yuzu. When I use the controllers in either Switch Pro Controller Mode or Windows PC XINPUT Mode there is not motion control in Ryujinx.

So here is the really weird buggy thing is if I connect the controllers in "Nintendo Switch Pro Controller Mode" and then run Zelda - TotK on Yuzu (where motion control aiming assis works fine), close Yuzu and then open the game in Ruyjinx then all of a sudden the motion control aiming works sometimes, just the very first time I press the right stick button (to open the Zelda zoom camera) where motion control aiming should work. Then when I press same right stick button button to close the Zelda zoom camera and press it again to reopen usually there is no longer any motion control aiming.

I'm using the latest Ryujinx and Yuzu Mainline version. Please note that since these top tier 3rd party GuliKit Controllers are made to connect directly to a Nintendo Switch as a Pro Controller and also show up in Ryujinx as "NinTendo Swtich Pro Controller" I would assume that the genuine 1st party Nintendo Swtich Pro Controllers will most likley have exactly the same issue of no motion control aim assist in Zelda TotK (or most likley other games) in Ryujinx.

I would be most grateful if you could please fix this as Ruyjinx IMHO is a far better emulator to run Zelda - TotK and most games on as Yuzu has significant lags even on my brand $4500 water cooled gaming laptop from 2023 with the latest spec intel i9 24-core CPU, nVidia RTX 4070, 32GB 5600 DDR4 RAM & 2TB Kingston Fury M.2 NVMe SSD (7GB/s) running latest vers Win11 & all recent drivers.

### Reproduction steps

All steps to reproduce are already clearly described in the section above describing the issue.

### Log file

[Ryujinx_1.1.762_2023-05-06_11-57-31.log](https://github.com/Ryujinx/Ryujinx/files/11446552/Ryujinx_1.1.762_2023-05-06_11-57-31.log)

### OS

Windows 11

### Ryujinx version

1.1.762

### Game version

1.10

### CPU

i9-13900HX

### GPU

NVIDIA RTX 4070

### RAM

32GB DDR4 5600

**Comment by gdkchan** [comment]
Please do not post issues about leaked games. Any problems with this game should be reported on the official release date (May 12th) or later.
