### ISSUE TITLE
[Bug] Donkey Kong Country: Tropical Freeze crashes immediately on MacOS (M1 Max) after the first cutscene 

### ISSUE THREAD

**Issue by bensaratikian** [Ryujinx/Ryujinx#4889]
### Description of the issue

The game crashes immediately on MacOS (M1 Max) after the first cutscene

### Reproduction steps

Just try a mentioned version of the game it crashes immediately after first cutscene

### Log file

None

### OS

MacOS

### Ryujinx version

1.0.0 & 1.1.0+

### Game version

1.0.2

### CPU

M1 MAX

### GPU

M1 MAX

### RAM

32GB

### List of applied mods

None

### Additional context?

None

**Comment by leitewill** [comment]
im having the same issue

**Comment by gdkchan** [comment]
This game uses transform feedback, it should be fixed by #5080.

**Comment by Black-Hill852** [comment]
same issue on the newest nightly build. I use Macbook Pro M1 Pro. 16 GB Ram
