### ISSUE TITLE
[Bug] TOTK Áudio

### ISSUE THREAD

**Issue by DanielSvoboda** [Ryujinx/Ryujinx#4891]
### Description of the issue

I was told that TOTK has the sound slightly to the right and with some noise...
I'm not sure about that, but I believe there is a problem with the 'SubMix' count, perhaps in this code below:
https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.Audio/Renderer/Server/CommandGenerator.cs

I don't have the TOTK game, but I was informed that there are these audio configurations in the game:
```
    IsCreateSpatialCalcuratorOnInit: true
    IsPoolSpeakerBalanceUnifier: true
    IsRequestLoadOnInitialize: true
    MaxEmitterCount: !l 360
    MemoryMgrSmallRate: 0,15800
    OpusChannelCount: !l 12
    OutputVolumStereoJack: 1,00000
    OutputVolumeBuildInSpeaker: 1,00000
    OutputVolumeTV: 1,00000
    ResourceHeapSize: 50,00000
    StreamCacheBlockCountRate: 0,80000
    StreamChannelCountMax: !u 80
    StreamReadCacheSize: !l 256
    SubMixCount: !l 11
    SubResourceHeapSize: 4,50000
    UseOpus: true
```

And when changing 'SubMixCount' to 7 or a smaller number, the audio is not noisy and cracked, however, you cannot hear some audio tracks, (you can hear the music and menu sounds, but you cannot hear the steps or attack sounds).
Maybe it's a good time to implement: mono/stereo /5.1 /7.1 options?  :D

### Reproduction steps

Switch-Toolbox edit .bgyml

### Log file

nome

### OS

Windows 10

### Ryujinx version

1.1.781

### Game version

1.1.0

**Comment by MutantAura** [comment]
This was resolved in https://github.com/Ryujinx/Ryujinx/pull/4888.
