### ISSUE TITLE
[Feature Request] Move game directory option

### ISSUE THREAD

**Issue by cootshk** [Ryujinx/Ryujinx#4895]
### Overview

Be able to choose where to store games (like in dolphin and yuzu)

### Smaller details

have an option inside the settings menu

### Nature of request

what does nature of request mean

### Why would this feature be useful?

for people also using yuzu and dont have much drive space left

**Comment by gdkchan** [comment]
Can you clarify what you mean? The emulator already allows the game directory to be selected. You just need to Options > Settings, and add a game directory on the `Game Directories` list.

**Comment by OldManKain** [comment]
You can already add the game directory.
![addgames](https://github.com/Ryujinx/Ryujinx/assets/47503099/629de157-c451-4363-984a-f18fa0d8d4ba)

**Comment by cootshk** [comment]
Sorry I didn't see that button
