### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by esteban142536** [Ryujinx/Ryujinx#4897]
### Description of the issue

In TOTK, there are some errors, here is a full list of the errors that I have found:

1. The game fun in 60 FPS with VSync and no frame limit, but the game is not made to run at this speed, I have found that 25 FPS is the decent playable speed, but in some shrine this can drop and feel the game slower, the FPS are set by using Nvidia control panel
2. The game can crash during one of the auto save events, sometimes in mid-game, teleporting when complete a shrine, or after you die
3. The audio from cutscenes are out of sync, being faster that the actual cutscene
4. There are some visual effects like squares when a NPS is in form of the sun in cutscenes, or, when a text box appear, there's a bigger square in the same one, one example is fighting a boss and the text box that show his name, retail an image of the background, being static
5. For some reason, you cannot show photos to characters, in one of the quest that require to show a photo to a NPC, It's impossible to show it, resulting in a softlock of the quest
6. The game fail to get the time of the console, being the time of all the saves "1/1/1970" even if the time in the emulator is correct, this result in only 2 save files, the auto save and the manual save, because the game don't allow you to choose between overwrite or create a new save, this can result in softlock or bad experience to the user
7. There are some moments, in between the transition of the sky and the land, the game doesn't fully load, resulting in NPC or enemies appearing spontaneously, along site with details or animals

### Reproduction steps

Play TLOZ Tears of the Kingdom for about 10 minutes to 1 hour, using a controller with DS4Windows

### Log file

[Ryujinx_1.1.743_2023-05-01_20-36-36.log](https://github.com/Ryujinx/Ryujinx/files/11457015/Ryujinx_1.1.743_2023-05-01_20-36-36.log)
[Ryujinx_1.1.743_2023-05-01_20-37-33.log](https://github.com/Ryujinx/Ryujinx/files/11457016/Ryujinx_1.1.743_2023-05-01_20-37-33.log)
[Ryujinx_1.1.743_2023-05-01_20-42-19.log](https://github.com/Ryujinx/Ryujinx/files/11457017/Ryujinx_1.1.743_2023-05-01_20-42-19.log)

### OS

Windows 10

### Ryujinx version

1.1.788

### Game version

1.0.0

### CPU

ADM Ryzen 7 5700X

### GPU

NVIDIA GeForce RTX 3050

### RAM

32 Gb

### Additional context?

The controller is by using a PS4 controller as a Pro controller without motion controls

**Comment by RedPana** [comment]
Comment this on the game page https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598

**Comment by MetrosexualGarbodor** [comment]
Please read the compatibility list and only point out the issues you don't see from your list in there.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598
