### ISSUE TITLE
[Bug] Settings Error

### ISSUE THREAD

**Issue by teej532** [Ryujinx/Ryujinx#4907]
### Description of the issue

Went to go change settings on ryujinx, crashed the software and created an error message 

(Ryujinx:11196): Gtk-WARNING **: 13:41:06.213: gtk_widget_size_allocate(): attempt to allocate widget with width -4 and height 27
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

### Reproduction steps

idk

### Log file

.

### OS

Windows 10

### Ryujinx version

1.1.792

### CPU

i7

### GPU

1070ti

### RAM

16gb

### List of applied mods

none

**Comment by marysaka** [comment]
Issue template is wrong, please provide full log details.

**Comment by AcK77** [comment]
You can use our Avalonia UI too. Since there isn't a full log I close this issue. You can go to our Discord for support. Thanks.
