### ISSUE TITLE
[Bug] No audio on Zelda TotK with latest macOS nightlies.

### ISSUE THREAD

**Issue by onesun43** [Ryujinx/Ryujinx#4912]
### Description of the issue

No audio output on Zelda TotK with latest macOS nightlies.

### Reproduction steps

No audio output with either OpenAL or SDL2 options. Works with mainstream 1.1.0-macos1 release

### Log file

[Ryujinx_1.1.793_2023-05-12_13-21-18.log](https://github.com/Ryujinx/Ryujinx/files/11466906/Ryujinx_1.1.793_2023-05-12_13-21-18.log)

### OS

MacOS Ventura 13.3.1

### Ryujinx version

1.1.793

### CPU

m1

**Comment by f6mon** [comment]
did you found a solution ?

**Comment by GamerzHell9137** [comment]
> did you found a solution ?

Github is just for tracking issues. Someday someone will look at it.

**Comment by callum4411** [comment]
I got the audio to work on 1.1.811. I did this by installing it and an older version where the audio works.(1.1.792). I then went to both the aplications in the aplications folder and option clicked them so i could select show package contents for both. Then i replaced the libSDL2.dylib file in the framework folder that was in the new application with the same file but in the older version.

**Comment by robyrobyr** [comment]
just tried it and it doesn't work, there are no other steps to this?

**Comment by callum4411** [comment]
> just tried it and it doesn't work, there are no other steps to this?

Are you using sdl2 in the audio settings after. If that does not work then make sure you switched the right files and replaced the old one

**Comment by robyrobyr** [comment]
Yes I'm pretty sure I did things correctly, which firmware you using?

**Comment by callum4411** [comment]
I am using firmware 16.0.3 . What Mac are you using because I am using an m1 MacBook Pro

**Comment by robyrobyr** [comment]
Ok I was using 15.x, just changed to 16.0.3 and it now works :)

**Comment by tranquillum** [comment]
I tried with 16.0.2, does not work. With 16.0.3 works perfectly. @callum4411 Thank you!
