### ISSUE TITLE
[Bug] build script for mac os does not work

### ISSUE THREAD

**Issue by arno4000** [Ryujinx/Ryujinx#4913]
### Description of the issue

The build script `create_macos_build.sh` does not work (see error details further below). The script [create_macos_release.sh](https://github.com/Ryujinx/Ryujinx/blob/ba71141bdcb4742ee8707b9c354365d9ea142ca9/distribution/macos/create_macos_release.sh) worked. 

### Reproduction steps

I used the following commands for the two scripts:
* `./distribution/macos/create_macos_release.sh ./ ./distribution/macos/temp ./distribution/macos/output ./distribution/macos/entitlements.xml 1.1.1 0`
* `./distribution/macos/create_macos_build.sh ./ ./distribution/macos/temp ./distribution/macos/output  ./distribution/macos/entitlements.xml 1.1.1 0 "" ""`

The script `create_macos_build.sh` gave the following error:

```
/private/tmp/Ryujinx/Ryujinx.sln.metaproj : error MSB4126: The specified solution configuration "src/Ryujinx.Ava|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [/private/tmp/Ryujinx/Ryujinx.sln]

Build FAILED.

/private/tmp/Ryujinx/Ryujinx.sln.metaproj : error MSB4126: The specified solution configuration "src/Ryujinx.Ava|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [/private/tmp/Ryujinx/Ryujinx.sln]
    0 Warning(s)
    1 Error(s)
```

OS: macOS 13.3.1 22E261 arm64
Host: MacBookPro18,2
Dotnet: 7.0.203

### Log file

see reproduction steps

### OS

macOS 13.3.1 22E261 arm64

### Ryujinx version

git commit 7271f1b

**Comment by TSRBerry** [comment]
```
./distribution/macos/create_macos_build.sh ./ ./distribution/macos/temp ./distribution/macos/output  ./distribution/macos/entitlements.xml 1.1.1 0 "Release" ""
```
If you supply the configuration argument correctly the script works fine, don't leave it empty specify either "Debug" or "Release".
