### ISSUE TITLE
the settings tab does not open [Bug]

### ISSUE THREAD

**Issue by hmjunior13** [Ryujinx/Ryujinx#4914]
### Description of the issue

I installed riyujinx recently, I did all the settings and it didn't give any errors.

That said, after this process I tried to open the configuration tab but it doesn't work. I click and nothing happens.

### Reproduction steps

the setting button doesn't work, i click and nothing happens

### Log file

dont have one

### OS

10

### Ryujinx version

16.0.3

**Comment by marysaka** [comment]
Issue template is empty, closing.

WIthout all informations we cannot profile assistance.
