### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ThisCharimgMan** [Ryujinx/Ryujinx#4925]
### Description of the issue

I can't open The Legend of Zelda Tears of the Kingdom. It attempts to boot but it runs into the same error every time changing graphics back end to OpenGL gives a black screen for a moment but the log files are the same. I've tried changing as many settings as I could find and did my best to look for other issues like mine.

### Reproduction steps

I lunch Tears of the Kingdom it freezes a moment and then crashes.

### Log file

[Ryujinx_1.1.796_2023-05-12_22-12-40.log](https://github.com/Ryujinx/Ryujinx/files/11468846/Ryujinx_1.1.796_2023-05-12_22-12-40.log)

### OS

Windows 10

### Ryujinx version

1.1.796

### Game version

1.1.0

### CPU

AMD Ryzen 7 3700X

### GPU

NVIDIA GeForce RTX 2070 SUPER

### RAM

16 gigabytes 3600MHz

### Additional context?

I hope I didn't cause a duplicate bug report and thank you for your time :)

**Comment by gdkchan** [comment]
The emulator save data seems to be corrupted. If you don't have a save from any other game that you want to keep, you could just delete all save data and try again.

**Comment by AcK77** [comment]
EnableFsIntegrityChecks is disabled, it could be a bad dump of a game/update, try that before deleting the save file!

**Comment by ThisCharimgMan** [comment]
Thank you for your feedback I'll try fresh installs of everything I more of just wanted to bring it to your attention in case it could help support the game.
