### ISSUE TITLE
[Feature Request] Auto-Close after exiting content.

### ISSUE THREAD

**Issue by Skullfurious** [Ryujinx/Ryujinx#4929]
### Overview

* Currently when accessing Ryujinx from a frontend the main application remains after exiting the content via Esc.
* It would be beneficial if there was a toggle to auto-close Ryujinx after launching / closing content.

### Smaller details

* A possible toggle in the Settings menu would be very useful.

### Nature of request

Toggleable Option in Settings

### Why would this feature be useful?

Specifically in my case when accessing Ryujinx from a frontend like Big Box the main Ryujinx application lingers after closing content and doesn't allow the computer to refocus on the frontend automatically.

Another issue is that the application becomes unresponsive to ESC input after content has been closed. It would be nice if Esc also was used to close the application as well, this would provide parity with basically all other emulators such as RA, Dolphin, PCSX2, etc.

**Comment by AcK77** [comment]
I don't get it, you want to exit the emulator after the launched game is exited? Then why you don't use our Headless build instead of the UI one as everyone does when they use a frontend?

**Comment by CoolBeansStudioOfficial** [comment]
I'll give it a go!

**Comment by IsaacMarovitz** [comment]
BigBox/LaunchBox should be using the headless build, not one of the builds with a UI.
