### ISSUE TITLE
[Feature Request] UX improvement: warn users to delete shader caches after changing graphics backend

### ISSUE THREAD

**Issue by ldorigo** [Ryujinx/Ryujinx#4932]
### Overview

I learned today that it's essential to re-build shader caches after changing graphics backend between OpenGL and Vulkan. This is not expressed clearly (or at all) in the settings and I only thought about it after a bunch of googling and crashes. 

There should be something notifying the users that the caches need to be emptied when changing backend.

### Smaller details

The easy way would be to just add a small message after the setting name ("Graphics Backend (requires re-building shader caches)"). Better UX would be to automatically purge caches after changing the setting and letting the user know. Even better, probably, would be to keep separate caches for Vulkan and OpenGL shaders?

### Nature of request

UX improvement

### Why would this feature be useful?

Save newbies time and pain

**Comment by MutantAura** [comment]
Why would this be preferable? The whole point of the current system is that you can build a cache in say Vulkan, and then perhaps play in OpenGL if the performance or graphical issues are better. It is explicitly designed to be able to cross convert.

**Comment by ldorigo** [comment]
Aren't shaders backend-specific? I was told by multiple people today that it's necessary to erase shaders after switching graphics backend. If not, then obviously the issue is moot.

**Comment by MetrosexualGarbodor** [comment]
Closing as users don't actually need to clear their caches when switching backends.
