### ISSUE TITLE
[Bug] ToTK : 1080p cheat (mod) crash while booting the game

### ISSUE THREAD

**Issue by Foul-Tarnished** [Ryujinx/Ryujinx#4933]
### Description of the issue

When I try to use the 1080p cheat, Ryujinx just crash while booting the game.
I cannot get to the game main menu, but the game somewhat boots, as the fps counter shows ~30fps for a few seconds, with a black screen.

### Reproduction steps

Install the cheat on ToTK 1.1.0
Enable it in the GUI
Boot the game

### Log file

[Ryujinx_1.1.0+ef81e79_2023-05-13_15-10-55.log](https://github.com/Ryujinx/Ryujinx/files/11469739/Ryujinx_1.1.0%2Bef81e79_2023-05-13_15-10-55.log)
[...]
Guest stack trace : [...]
```
00:00:31.330 |E| HLE.GuestThread.68 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:31.361 |E| HLE.GuestThread.68 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId)
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```

### OS

Windows 11 - 22H2

### Ryujinx version

1.1.798

### Game version

1.1.0

### CPU

R7 3770x

### GPU

GTX 1060 6GB

### RAM

16GB

### List of applied mods

- 1080p cheat for game ver 1.1.0

[D5AD6AC71EF53E3E.txt](https://github.com/Ryujinx/Ryujinx/files/11469744/D5AD6AC71EF53E3E.txt)
(put in game-mod-dir\mod-name\cheats\D5AD6AC71EF53E3E.txt)

```
[1080p docked (1x)]
580F0000 04719670
580F1000 00000090
780F0000 000000F0
680F01D0 00000510 00000900
```

(for BuildID D5AD6AC71EF53E3E)

### Additional context?

Apparently the cheat is unstable on real hardware too, but you can at least get ingame, for a few minutes. (source : gbatemp)
Taken from github repo : bad1dea/NXCheats
(check commits, one was removing the 1080p cheats because "unstable")

**Comment by 2peik** [comment]
Im having excatly the same error. So then why is the way to fix it? im a bit new on this

**Comment by Foul-Tarnished** [comment]
If I create an issue, it means there are no known fixes for now.

Hopefully the logs can help the devs, but as I said, the mod is hnstable on
real hardware anyway.

**Comment by 2peik** [comment]
oh okay ty

**Comment by AcK77** [comment]
Issues are for Ryujinx and not mods/cheats bugs, so you should ask the mods/cheats creator instead since we do not know what's changed.
I suggest you to clear PTC and Shader cache before using/removing a mod btw.
You can go to our Discord in `#modding-cheats` for trying to find a solution.
Thanks

**Comment by Foul-Tarnished** [comment]
If a mod/cheat works on hw but not on ryu, this means it's an emulator
issue :)

I did completely remove both pptc and shaders cache before trying it too
