### ISSUE TITLE
[Bug] GPU.MainThread: System.NullReferenceException

### ISSUE THREAD

**Issue by Qjawko** [Ryujinx/Ryujinx#4934]
### Description of the issue

Emulator unexpectedly closes when I was playing Tears of the Kingdom.

### Reproduction steps

I just fell into the shelter of the sentinel fort and there was a crash.

### Log file

[Ryujinx_1.1.798_2023-05-13_19-20-31.log](https://github.com/Ryujinx/Ryujinx/files/11469797/Ryujinx_1.1.798_2023-05-13_19-20-31.log)

### OS

Windows 11

### Ryujinx version

1.1.798

### Game version

1.1.0

### CPU

AMD 5900X 

### GPU

Nvidia RTX 4090

### RAM

32GB

### List of applied mods

[VisualFixes](https://gamebanana.com/mods/443105) only

**Comment by MetrosexualGarbodor** [comment]
This is caused by some broken mods going around.

**Comment by Qjawko** [comment]
> This is caused by some broken mods going around.

thanks, will try without any mods.
