### ISSUE TITLE
Ryujinx Crashes During TotK Gameplay

### ISSUE THREAD

**Issue by PodcastGuru74** [Ryujinx/Ryujinx#4941]
### Description of the issue

Ryujinx crashes seemingly randomly during TotK. This did not happen at all during the initial sky islands gameplay.

Info about the first crash (1/2)
It only started after I dropped to the ground and started exploring. The first time it crashed when I was going to meet Hoz during the "Crisis at Hyrule Castle" mission. I was attempting to climb on the wall shown in the pictures when the game crashed.
![image](https://github.com/Ryujinx/Ryujinx/assets/108306240/2bd2fcee-157d-4efe-88b9-67b137b93cb4)
![image](https://github.com/Ryujinx/Ryujinx/assets/108306240/9479b93b-3bd7-481d-a13a-3dc869c311fd)

Info about the second crash (2/2)
The second crash occurred after I talked to Hoz. I fast traveled to Kyononis Shrine after talking to Hoz and was walking back to talk to Purah for the second time when it crashed.

Note about logs: I pasted all three of the three log files in the Ryujinx logs folder. I think only the first two should be useful (Ryujinx_1.1.799_2023-05-14_00-06-01.log  and  Ryujinx_1.1.799_2023-05-14_00-20-45.log) but I added all three just in case.

### Reproduction steps

The crashes do not seem reproducible because I reloaded my save after both crashes and tried not to change what I did in order to see if the crashes would happen again and they did not.

### Log file

[Ryujinx_1.1.799_2023-05-14_00-06-01.log](https://github.com/Ryujinx/Ryujinx/files/11471412/Ryujinx_1.1.799_2023-05-14_00-06-01.log)
[Ryujinx_1.1.799_2023-05-14_00-20-45.log](https://github.com/Ryujinx/Ryujinx/files/11471413/Ryujinx_1.1.799_2023-05-14_00-20-45.log)
[Ryujinx_1.1.799_2023-05-14_00-54-57.log](https://github.com/Ryujinx/Ryujinx/files/11471421/Ryujinx_1.1.799_2023-05-14_00-54-57.log)

### OS

Fedora 38 Linux

### Ryujinx version

1.1.799

### Game version

1.0.0

### CPU

AMD Ryzen 7 3700X (16) @ 3.600GHz

### GPU

AMD Radeon RX 5600 XT

### RAM

32GB

**Comment by MutantAura** [comment]
None of the above logs have any crashes present. Do you have any other examples which might have more info?

**Comment by AcK77** [comment]
All logs contains:
```
ATTENTION: default value of option mesa_glthread overridden by environment.
```
Maybe the crash is related to that. There is probably something missing on your system.

**Comment by ethanqm** [comment]
> All logs contains:
> 
> ```
> ATTENTION: default value of option mesa_glthread overridden by environment.
> ```

Can we rule out Firefox? According to [Bugzilla 1744389](https://bugzilla.mozilla.org/show_bug.cgi?id=1744389) Firefox unconditionally overrides this env var, so I'm familiar with this warning

**Comment by d9j** [comment]
Just suggestion: can you guys allow tagging platform in issues? It's easier to navigate like  it's windows / mac(apple silicon)/ linux

**Comment by AcK77** [comment]
> Just suggestion: can you guys allow tagging platform in issues? It's easier to navigate like it's windows / mac(apple silicon)/ linux

Yes we can, but how we could be sure the issue occurs only on Linux ?

Related to the subject, `mesa_glthread overridden by environment` seems to be a warning. I can't help further for now.

**Comment by stefsot** [comment]
could this be related to #4923? A similar crash with no error logs, but Vulkan seems to mitigate that issue somehow but here Vulkan is used

**Comment by RypoFalem** [comment]
I've had an issue with segfaults when loading things in totk (loading screens, hitting ore, walking to a new area, etc) in linux mint and it was solved by increasing vm.max_map_count as detailed here #3372 `sysctl -w vm.max_map_count=262144`

**Comment by BlastBolt5** [comment]
> I've had an issue with segfaults when loading things in totk (loading screens, hitting ore, walking to a new area, etc) in linux mint and it was solved by increasing vm.max_map_count as detailed here #3372 `sysctl -w vm.max_map_count=262144`
> 
> Segfaults won't show up in the logs but you can see it when you crash if you launch the game through the terminal

This was suggested to me in the discord on launch day when i was crashing a lot and haven't had but like 1 or 2 small crashes in the 60ish hours since.

**Comment by TathagataDM** [comment]
Been getting random crashes/freezes occasionally as well. Here's a log from the most recent time:

Log file

file:///home/tatha/Emulators/Ryujinx/Mainline/Logs/Ryujinx_1.1.819_2023-05-24_18-44-44.log

EndeavourOS Linux 6.3.3-zen1-1-zen

Ryujinx version
1.1.819

Game version
1.1.1

CPU
AMD Ryzen 9 7950x

GPU
AMD Radeon RX 7900 XTX

RAM
64GB DDR5-6000

List of applied mods
1080p_Disable_FSR_FXAA_v1.1.1
Improved LOD v1.1.1
Remove DOF v1.1.1

Additional context?
Seems to be entirely random as far as I can tell.
