### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ISuuuu** [Ryujinx/Ryujinx#4945]
### Description of the issue

火神兽 经常闪退
![image](https://github.com/Ryujinx/Ryujinx/assets/16700132/974882d1-cf66-4799-8cbf-d6fba1953101)

### Reproduction steps

火之神殿 走路 或者发射阿沅

### Log file

。。

### OS

win11 

### Ryujinx version

1.1.799

### CPU

amd 3700

### GPU

1065

### RAM

24

### Additional context?

..

**Comment by MutantAura** [comment]
Please use Discord for support queries: https://discord.gg/ryujinx
