### ISSUE TITLE
[Bug] TotK crash at Chasm with Vulkan

### ISSUE THREAD

**Issue by krst221** [Ryujinx/Ryujinx#4946]
### Description of the issue

Every time i enter the Chasm from outside, try to warp out or there are many things loading the game crashes. Doesn't happen with OpenGL but the gloom looks really bad

### Reproduction steps

Enter the chasm from a well or a big hole, warp away from a lightroot or close to (specially in places with a lot of gloom)

### Log file

00:00:00.042 |I| Configuration LogValueChange: ResScale set to: -1
00:00:00.045 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.045 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.046 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.046 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.047 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.047 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1C02
00:00:00.048 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.049 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.049 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.051 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.051 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.051 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.051 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.052 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.052 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.052 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.052 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.052 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.053 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.053 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.053 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.053 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.056 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.800
00:00:00.060 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.060 |N| Application Print: CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
00:00:00.061 |N| Application Print: RAM: Total 16309 MiB ; Available 13191 MiB
00:00:00.064 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.064 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.091 |I| Gpu : Backend Threading (Auto): True
00:00:00.309 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:00.309 |I| Application LoadApplication: Loading as XCI.
00:00:00.335 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.337 |I| ModLoader AddModsFromDirectory: Found mod '<0100F2C0115B6000 ExeFs>' [E]
00:00:00.337 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.340 |I| Loader Load: Loading rtld...
00:00:00.348 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.348 |I| Loader Load: Loading main...
00:00:00.638 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:00.638 |I| Loader Load: Loading subsdk0...
00:00:00.661 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:00.661 |I| Loader Load: Loading sdk...
00:00:00.714 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:00.722 |I| ModLoader ApplyProgramPatches: Matching IPSwitch patch '1.1.0.pchtxt' in '<0100F2C0115B6000 ExeFs>' bid=D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3
00:00:00.724 |I| ModLoader Parse: IPSwitch:    print_values 0x90eac4 <= 41008052
00:00:00.725 |I| ModLoader Parse: IPSwitch:    print_values 0xebd258 <= 41008052
00:00:00.725 |I| ModLoader Parse: IPSwitch:    print_values 0x90ea90 <= 55008052
00:00:00.725 |I| ModLoader Parse: IPSwitch:    print_values 0x90eb38 <= 55008052
00:00:00.725 |I| ModLoader Parse: IPSwitch:    print_values 0x90eba8 <= 48008052
00:00:00.726 |I| ModLoader Parse: IPSwitch:    print_values 0x90eb40 <= 4C008052
00:00:00.726 |I| ModLoader Parse: IPSwitch:    print_values 0x90ea8c <= EB031F2A
00:00:00.726 |I| ModLoader Parse: IPSwitch:    print_values 0x19bf204 <= 1F2003D5
00:00:00.726 |I| ModLoader Parse: IPSwitch:    print_values 0x19ca768 <= 1F2003D5
00:00:00.731 |I| ModLoader Patch: Patching address offset 90e98c <= EB 03 1F 2A len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 90e990 <= 55 00 80 52 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 90e9c4 <= 41 00 80 52 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 90ea38 <= 55 00 80 52 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 90ea40 <= 4C 00 80 52 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 90eaa8 <= 48 00 80 52 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset ebd158 <= 41 00 80 52 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 19bf104 <= 1F 20 03 D5 len=4
00:00:00.731 |I| ModLoader Patch: Patching address offset 19ca668 <= 1F 20 03 D5 len=4
00:00:00.837 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:03.486 |I| Ptc Load: Loaded Translation Cache (size: 246111533 bytes, translated functions: 195387).
00:00:03.529 |I| Ptc Load: Loaded Profiling Info (size: 590786 bytes, profiled functions: 170735).
00:00:03.539 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:03.540 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:03.564 |I| Loader LoadNsos: Loading image 2 at 0x000000000c731000...
00:00:03.567 |I| Loader LoadNsos: Loading image 3 at 0x000000000cdda000...
00:00:03.574 |I| ModLoader LoadCheats: Build ids found for title 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:03.577 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:03.645 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.1.0 [0100f2c0115b6000] [64-bit]
00:00:03.658 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:03.675 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:03.946 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1060 3GB (Vulkan v1.3.236, Driver v531.79.0.0)
00:00:03.955 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:03.962 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:06.519 |I| HLE.GuestThread.21 Ptc LoadTranslations: 170735 translated functions loaded
00:00:06.656 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:06.667 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:06.667 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.667 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.680 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:07.363 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:07.364 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:07.364 |S| HLE.OsThread.22 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:07.364 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:07.365 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:07.485 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:07.490 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:07.492 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:07.509 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:07.524 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.573 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:07.573 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:07.574 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:07.575 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:07.576 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:07.576 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:07.576 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:07.578 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:07.602 |S| HLE.OsThread.22 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:07.604 |S| HLE.OsThread.22 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:07.605 |S| HLE.OsThread.22 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:07.620 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:07.623 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:07.624 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:08.489 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:08.489 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:10.803 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:10.805 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:10.989 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:10.991 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV11
00:00:11.013 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:11.014 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:11.015 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:11.050 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:11.051 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:11.087 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:11.516 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:11.517 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:11.848 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:11.848 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:11.848 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:11.848 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:12.458 |S| HLE.OsThread.22 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:12.459 |S| HLE.OsThread.22 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:12.459 |S| HLE.OsThread.22 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:13.099 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:00:13.099 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:00:13.113 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:13.242 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: bootup_time 
 Report: {
    "BootupTimeUs": 13340,
    "system_report_tag": 2175206328
}

00:00:13.244 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: erepo_region 
 Report: {
    "Region": 1,
    "Language": 1,
    "StandardTimeName": "UTC",
    "UtcOffsetSeconds": 0,
    "system_report_tag": 2759414308
}

00:00:13.244 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: erepo_time 
 Report: {
    "ActiveTime": 6,
    "UpdatedTime": 0,
    "system_report_tag": 2759414308
}

00:00:13.245 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: erepo_playstyle 
 Report: {
    "system_report_tag": 2759414308
}

00:00:13.245 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: erepo_network_status 
 Report: {
    "NetworkInterface": {
        "TypeCode": 64,
        "Value": "0x00000000000000000000000000000000"
    },
    "LinkLevel": {
        "TypeCode": 65,
        "Value": "0x00"
    },
    "FrequencyBand": {
        "TypeCode": 66,
        "Value": "0x00000000000000000000"
    },
    "system_report_tag": 2759414308
}

00:00:13.362 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:13.468 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: erepo_active_beacon 
 Report: {
    "IntervalTime": 0,
    "UpdatedTime": 0,
    "system_report_tag": 0
}

00:00:16.028 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.030 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player2}
00:00:16.030 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player3}
00:00:16.030 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player4}
00:00:23.428 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:25.165 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1332,
    "PlayDataUniqueID": 1835047512,
    "EventInfo": "Dm_OP_0037",
    "PlayerPosX": 3,406024E-11,
    "PlayerPosY": -0,15038963,
    "PlayerPosZ": 3,406211E-11,
    "system_report_tag": 2175206328
}

00:00:25.246 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1332,
    "PlayDataUniqueID": 1835047512,
    "EventInfo": "Dm_OP_0038",
    "PlayerPosX": 3,406024E-11,
    "PlayerPosY": -0,15038963,
    "PlayerPosZ": 3,406211E-11,
    "system_report_tag": 2175206328
}

00:00:25.390 |S| HLE.OsThread.22 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:00:50.741 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: option_data 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1332,
    "PlayDataUniqueID": 1835047512,
    "BoolOptions": 1037,
    "CameraRotateSpeed": 4,
    "DisplayMode": 0,
    "MessageWindowTransparency": 0,
    "VoiceLanguage": 0,
    "Action": 1,
    "Cancel": 2,
    "Jump": 3,
    "Attack": 4,
    "SpecialPower": 5,
    "Attention": 6,
    "Throw": 7,
    "Bow": 8,
    "PlusMenu": 9,
    "MinusMenu": 10,
    "SpecialPowerShortcut": 11,
    "CompanionShortcut": 13,
    "PouchShortcut": 14,
    "Whistle": 12,
    "Crouch": 25,
    "Scope": 33,
    "PresetType": 0,
    "system_report_tag": 2175206328
}

00:00:50.767 |S| HLE.OsThread.22 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:00:58.502 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:04.706 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:05.707 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 4519 took more than 1000ms, resuming execution...
00:01:06.169 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 35812,
    "ReleaseVersion": 1332,
    "PlayDataUniqueID": 2066793723,
    "EventInfo": "DefaultBootEvent",
    "PlayerPosX": -180,97044,
    "PlayerPosY": -367,6875,
    "PlayerPosZ": -431,12994,
    "system_report_tag": 2175206328
}

00:01:06.447 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:21.976 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: erepo_active_beacon 
 Report: {
    "IntervalTime": 60,
    "UpdatedTime": 60,
    "system_report_tag": 0
}

00:02:38.567 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 35887,
    "ReleaseVersion": 1332,
    "PlayDataUniqueID": 2066793723,
    "EventInfo": "DmF_SY_WarpIn",
    "PlayerPosX": -184,6704,
    "PlayerPosY": -367,683,
    "PlayerPosZ": -432,01468,
    "system_report_tag": 2175206328
}

00:02:39.210 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 182
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 58
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 149
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 116
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 447

### OS

Windows 11

### Ryujinx version

1.1.800

### Game version

1.1.0

### CPU

Ryzen 5 3600

### GPU

NVIDIA GTX 1060 3GB

### RAM

16 GB

### List of applied mods

30 fps fix

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, check the FAQ or ask on discord.
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-game-crashes-with-e-guirenderthread-application--unhandled-exception-caught-ryujinxgraphicsvulkanvulkanexception-unexpected-api-error-erroroutofdevicememory
