### ISSUE TITLE
[Bug] Configs reset after every update

### ISSUE THREAD

**Issue by juliocoliveira** [Ryujinx/Ryujinx#4947]
### Description of the issue

The configs file is deleted every time I do an update.
So i need or rename the Config.json.ryunold to Config.json before the restart so I keep my settings, or let the restart delete Config.json and reset all my controllers and all other settings.
So please fix this, is very annoying to reset all my settings on each update 

### Reproduction steps

Do an update

### Log file

00:00:00.057 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.063 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.063 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.064 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.065 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.066 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.066 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2489
00:00:00.067 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.068 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.068 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.070 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.087 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.087 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.087 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.088 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.088 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.088 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.088 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.089 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.089 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.089 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.089 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.089 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.089 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.093 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.800
00:00:00.096 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.096 |N| Application Print: CPU: AMD Ryzen 7 5800X 8-Core Processor ; 16 logical
00:00:00.097 |N| Application Print: RAM: Total 32674 MiB ; Available 21539 MiB
00:00:00.099 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.099 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.884 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.894 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.902 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.909 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)

### OS

Windows 11

### Ryujinx version

1.1.800

### Game version

1.1.0

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA RTX 3060 TI

### RAM

32 GB

**Comment by AcK77** [comment]
What? The Config.json file is stored at `%appdata%\Ryujinx` and not in the Ryujinx folder.
So it's not possible to get `Config.json.ryuold` or I miss something!

**Comment by juliocoliveira** [comment]
Ahm, So thats MY problem, I created a link on the %appdata%\Ryujinx to my Ryunjinx folder to store my settings, So every time i format I don't loose all the settings. So I'll need to do other workaround to that be fixed. Thanks anyway.
