### ISSUE TITLE
[Bug] Vertex explosions and bright white texture artifacts in ToTK macOS

### ISSUE THREAD

**Issue by cobbycobbycobcob** [Ryujinx/Ryujinx#4949]
### Description of the issue

Certain colours (dark grey) appear glowing white, and textures (specifically Link in the 'pause screen', Link's shadow, the chu-chu enemies) are distorted.
<img width="1249" alt="Screen Shot 2023-05-13 at 12 57 36 PM" src="https://github.com/Ryujinx/Ryujinx/assets/88045608/15816d16-5b7c-4a0e-965b-0affbf5347ea">
- Dark grey as glowing white

<img width="1274" alt="Screenshot 2023-05-14 at 10 34 18 AM" src="https://github.com/Ryujinx/Ryujinx/assets/88045608/b1f93158-934a-4445-8bab-8f0f16aa5f84">
- Distorted Link

<img width="1250" alt="Screenshot 2023-05-14 at 10 33 17 AM" src="https://github.com/Ryujinx/Ryujinx/assets/88045608/fa02480e-5238-4875-98b2-456591bdadff">
- Distorted shadow

### Reproduction steps

- Load base .xci
- Load v 1.1.0 .nsp
- Compile + package shaders (n = 13494)
- Play the game, notice the glitches

### Log file

[Ryujinx_1.1.799_2023-05-14_00-34-01.log](https://github.com/Ryujinx/Ryujinx/files/11472430/Ryujinx_1.1.799_2023-05-14_00-34-01.log)

### OS

Mac OS Ventura 13.3.1

### Ryujinx version

1.1.799

### Game version

1.1.0

### CPU

Apple M2

### GPU

Apple M2 (Vulkan)

### RAM

16 GB

**Comment by d9j** [comment]
And certain enemies glitching out like Chuchu for example.. they look totally messed up

**Comment by xiongpahao** [comment]
Same problems on my 14‘’ M1 Pro MacBook Pro.

**Comment by Foul-Tarnished** [comment]
`Download and try various shaders (n = 13494)`
Sharing shaders is illegal, as they contain copyrighted material.

Also, they are compiled and optimized for each gpu, so not really a good idea to even just copy them between your *own* computers either way.

**Comment by Pbird99** [comment]
Same problems here. It seems the bug with Link's hair in the menu and the shadow for it doesn't occur when wearing armour.

**Comment by IsaacMarovitz** [comment]
This is already mentioned in my Mac compatibility report here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598#issuecomment-1544022273

**Comment by vesper8** [comment]
When building yourself using this PR https://github.com/Ryujinx/Ryujinx/pull/4899 the inventory screen crazy hair is fixed! The crazy shadows are not fixed (yet) however.

**Comment by IsaacMarovitz** [comment]
> When building yourself using this PR #4899 the inventory screen crazy hair is fixed! The crazy shadows are not fixed (yet) however.

It doesn't. Vertex explosions are inconsistent, they only happen when wearing certain clothes/doing certain animations.

**Comment by iRonJ** [comment]
Seeing this as well. Noticed an error about a shader compilation in the console messages— probably related?

**Comment by Pbird99** [comment]
Loading a save from outside of Lookout Landing next to Mondi gives this log. As @iRonJ mentioned, the log has two main errors: `VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL` and `VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline`

[Ryujinx_1.1.808_2023-05-20_09-19-34.log](https://github.com/Ryujinx/Ryujinx/files/11521136/Ryujinx_1.1.808_2023-05-20_09-19-34.log)

**Comment by iRonJ** [comment]
> Loading a save from outside of Lookout Landing next to Mondi gives this log. As @iRonJ mentioned, the log has two main errors: `VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL: MSL conversion error: Subgroup builtins are not available in this type of function` and `VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline`
> 
> [Ryujinx_1.1.808_2023-05-20_09-19-34.log](https://github.com/Ryujinx/Ryujinx/files/11521136/Ryujinx_1.1.808_2023-05-20_09-19-34.log)

I can see the shader that fails here, but not sure what to do about it... seems to be a fairly small shader program
<img width="659" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/6108031/e41a78df-8c20-44a4-becf-b11b591b7603">

**Comment by Pbird99** [comment]
I don't think that code is the problem, it seems to just load up the precompiled shader that doesn't work properly to the shader cache.

**Comment by noahgg12** [comment]
Is there any fixes yet? This really ruins the experience for me.

**Comment by GANNI-GANNI** [comment]
same issues here on 14 inch m1 macbook pro

**Comment by iRonJ** [comment]
> I don't think that code is the problem, it seems to just load up the precompiled shader that doesn't work properly to the shader cache.

I'm pretty sure it's passing it off to the moltenvk backend which is trying to transpile it to MSL and the transpiler can't convert it. The ultimate solution is either for the MVK transpiler to be updated to handle the issue, or Ryujinx intercepts the shader and replaces it with an equivalent one.

**Comment by gdkchan** [comment]
> Loading a save from outside of Lookout Landing next to Mondi gives this log. As @iRonJ mentioned, the log has two main errors: `VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL: MSL conversion error: Subgroup builtins are not available in this type of function`, `VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline` and `VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 9): Invalid Resource (00000009:kIOGPUCommandBufferCallbackErrorInvalidResource)`
> 
> [Ryujinx_1.1.808_2023-05-20_09-19-34.log](https://github.com/Ryujinx/Ryujinx/files/11521136/Ryujinx_1.1.808_2023-05-20_09-19-34.log)

The first error is probably because a shader is using subgroup operations in a vertex shader. AFAIK Apple Silicon GPU does not support this (and if it does, then MoltenVK doesn't support it). The only way around this would be converting the vertex shader to a compute shader which is very complicated to do. Also I don't know if that error is what is causing the issue(s) reported here.

**Comment by iRonJ** [comment]
I don't think the shader error is related to the geometry glitches regardless (probably the cause of the glowing white hair textures though?).
Geometry issues and the shadow issues are related though, seems the shadow is of the glitched geometry, but the geometry doesn't always show as glitched... weird...
<img width="1292" alt="Screenshot 2023-05-21 at 3 58 36 PM" src="https://github.com/Ryujinx/Ryujinx/assets/6108031/eff1aafd-19e0-4d99-9cb0-0c0b868ae63d">

**Comment by Pbird99** [comment]
> The first error is probably because a shader is using subgroup operations in a vertex shader. AFAIK Apple Silicon GPU does not support this (and if it does, then MoltenVK doesn't support it). The only way around this would be converting the vertex shader to a compute shader which is very complicated to do. Also I don't know if that error is what is causing the issue(s) reported here.

I tried manually updating the libMoltenVK.dylib file in the app's contents to see what happens and it changes the error message `VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL: MSL conversion error: Subgroup builtins are not available in this type of function` to this `VK_ERROR_INVALID_SHADER_NV: Shader module does not contain an entry point named 'main0'`. Not sure if this error message helps or if it's basically the same thing.

**Comment by Pbird99** [comment]
Also, I enabled trace logs to see what's going on and here's a snippet of the log (the original log was too big at 500MB): 
[Ryujinx_1.1.1+0 Trace Log Snippet.txt](https://github.com/Ryujinx/Ryujinx/files/11526833/Ryujinx_1.1.1%2B0.Trace.Log.Snippet.txt)

**Comment by MR-UNI** [comment]
same on my base m2 Mini

**Comment by donut** [comment]
Same on Mac Studio, M1 Max, 64 GB RAM, macOS Ventura 13.3, and Ryujinx 1.1.819.

**Comment by noahgg12** [comment]
When are we going to get fixes. We have been waiting for a week, and I really haven't seen much work to fix this from the devs.

**Comment by MutantAura** [comment]
> When are we going to get fixes. We have been waiting for a week, and I really haven't seen much work to fix this from the devs.

The project is open-source under the MIT license. If you want to take a look and propose some fixes then you are fully within your freedom to do so.

**Comment by noahgg12** [comment]
> > When are we going to get fixes. We have been waiting for a week, and I really haven't seen much work to fix this from the devs.
> 
> The project is open-source under the MIT license. If you want to take a look and propose some fixes then you are fully within your freedom to do so.

Sorry, It must be hard, I don't know how to code, and I am not doing anything, so I am out of my boundaries. I was just upset at the experience I was having; that was so perfect, except for these issues. Good luck Dev team, and hope you can find the problem and fix it soon.

**Comment by d9j** [comment]
@noahgg12  check how many issues are  currently open basis on this do expectation

**Comment by sulapse** [comment]
Is there any info on if this is even being looked into?

**Comment by MR-UNI** [comment]
> Vertex explosions should have already been fixed with https://github.com/Ryujinx/Ryujinx/commit/2c9715acf6cb9ae8bceabec5e81602c7d64c7192 and shiny textures are fixed with most recent PR. 

Wait fr?

**Comment by sulapse** [comment]
> Vertex explosions should have already been fixed with [2c9715a](https://github.com/Ryujinx/Ryujinx/commit/2c9715acf6cb9ae8bceabec5e81602c7d64c7192) and shiny textures are fixed with most recent PR.

Are vertex explosions also causing the bright glowing textures?
