### ISSUE TITLE
[Bug] crashing ZTOTK Hebra mountains

### ISSUE THREAD

**Issue by itachisen** [Ryujinx/Ryujinx#4957]
### Description of the issue

 the game crash wherever place you move in that direction, travel to other places  near or far from the area doesnt crash the game 

### Reproduction steps

once you complete the hebra  mountain mission and the player must go  at the top of the mountains the game crash wherever place you move in that direction, travel to other places  near or far from the area doesnt crash the game 

### Log file

[Ryujinx_1.1.799_2023-05-15_02-10-00.log](https://github.com/Ryujinx/Ryujinx/files/11475824/Ryujinx_1.1.799_2023-05-15_02-10-00.log)

### OS

windows 11

### Ryujinx version

1.1.799

### Game version

1.1

### CPU

AMD RYZEN 7 5800U

### GPU

AMD RADEON TM

### RAM

16

### List of applied mods

N/a

**Comment by Foul-Tarnished** [comment]
Probably an issue with your rom file. Try to redump.

I had no issues to do this mission.
I even start "climbing" the mountain with Ryu being running since a few hours.

**Comment by morceaudebois** [comment]
Working fine on M1 Mac as well!

**Comment by MutantAura** [comment]
GitHub is not for support queries, please join the discord: https://discord.gg/ryujinx
Thanks.
