### ISSUE TITLE
[Bug] Cursor stays visible in full screen (macOS)

### ISSUE THREAD

**Issue by morceaudebois** [Ryujinx/Ryujinx#4958]
### Description of the issue

When playing a game in full screen, the cursor stays visible at all time. It should disappear after a few seconds and then reappear when using the mouse.

### Reproduction steps

1. Open game
2. Enable full screen

### OS

macOS 12

### Ryujinx version

 1.1.799

**Comment by MutantAura** [comment]
Does this still occur in 1.1.800?

**Comment by morceaudebois** [comment]
It does

**Comment by OldManKain** [comment]
> ### Description of the issue
> When playing a game in full screen, the cursor stays visible at all time. It should disappear after a few seconds and then reappear when using the mouse.
> 
> ### Reproduction steps
> 1. Open game
> 2. Enable full screen
> 
> ### OS
> macOS 12
> 
> ### Ryujinx version
> 1.1.799

Do you have hide cursor on Idle enabled?
![image](https://github.com/Ryujinx/Ryujinx/assets/47503099/4ef7d2b5-dc79-4d40-a768-66e49071a6e0)

**Comment by Pbird99** [comment]
This issue doesn't occur for me on 1.1.800 using macOS 13.3.1.

**Comment by morceaudebois** [comment]
Oh I'm sorry, I had completely missed the option in the settings! Thank you 😊
