### ISSUE TITLE
[Bug] Ryujinx 100% crashes on the startup app

### ISSUE THREAD

**Issue by burivuh26** [Ryujinx/Ryujinx#4969]
### Description of the issue

I'm trying start Ryujinx.app in macos and it crashes with report. 
I tried delete and reinstall app but it doesn't helped me.

### Reproduction steps

I'm trying start Ryujinx.app in macos and it crashes with report. 
I tried delete and reinstall app but it doesn't helped me.

### Log file

[error report.txt](https://github.com/Ryujinx/Ryujinx/files/11479559/error.report.txt)

### OS

MacOS 13.3.1

### Ryujinx version

1.1.800

### Additional context?

no firmware or games installed.

**Comment by MutantAura** [comment]
GitHub is not for support queries, please join the discord: https://discord.gg/ryujinx
Thanks.
