### ISSUE TITLE
[Feature Request] Official support for 8 GiB memory layout

### ISSUE THREAD

**Issue by SilentStorm-1986** [Ryujinx/Ryujinx#4971]
### Overview

Since the kernel for Switch supports up to 8 GiB of extended memory, it makes sense to utilize the full amount of RAM available. As you (the devs) might be aware, the default memory allocation for the application in 8 GiB mode is the same as 6 GiB, and the rest is allocated to the applet memory. However, this can be changed to any number up to 8000 MiB with reducing the applet memory accordingly. Yuzu now sets the application memory to 6547 MiB if I recall correctly. While only a few mods may use the extra memory, it certainly would make sense to have the extra memory available if there's any need to activate extended memory at all.

### Smaller details

The memory class is found in HLE/HOS/Kernel/Common/KSystemControl.cs
MemoryConfiguration in MainWindow.cs would have to be changed to 8GiB.

### Nature of request

Would be great to see Ryujinx implement this in official builds.

### Why would this feature be useful?

This would be useful for any mods that require a large amount of memory, both present and future.

**Comment by Foul-Tarnished** [comment]
Some games like BOTW/ToTK can trigger a "blood moon" when the game is low on memory, or there's too much fragmentation, idrk.

Would those games use the extra memory by themselves ?

And making it harder to get those annoying blood moon
Also preventing weird stuff like link loosing his hair when duplicating hundreds of bows (one famous glitch on botw)

**Comment by SilentStorm-1986** [comment]
With a pchtxt it definitely can reduce memory issues.

**Comment by SilentStorm-1986** [comment]
Not in every scenario. Texture packs are rare for Switch, as are pchtxts that modify memory to use extended memory. Some games however have auto sized memory heaps, which might reduce crashes with certain kinds of mods such as draw distance and LOD.

Since the option is available in the Switch kernel, why not?

**Comment by gdkchan** [comment]
I don't mind exposing the 8GB configuration, but I don't think we would want to invent sizes used for application memory.

**Comment by SilentStorm-1986** [comment]
A logical compromise seems to be setting the application memory to 8GiB minus the standard applet memory (if 448MiB is enough for the planned applet support).
