### ISSUE TITLE
[Bug] Latest flatpak build unable to launch on Linux

### ISSUE THREAD

**Issue by MarkGhanz** [Ryujinx/Ryujinx#4974]
### Description of the issue

The latest flatpak build at the time (1.1.800) seems unable to launch on GNOME (both X and Wayland).

### Reproduction steps

1. Enter GNOME 44.1 wayland. 
2. `flatpak run org.ryujinx.Ryujinx` in a terminal emulator.

### Log file

[Ryujinx_1.1.800_2023-05-15_15-00-07.log](https://github.com/Ryujinx/Ryujinx/files/11481520/Ryujinx_1.1.800_2023-05-15_15-00-07.log)

### OS

Arch Linux (6.3.2-zen1-1-zen)

### Ryujinx version

1.1.800

### CPU

i5-1135G7

### GPU

Intel Iris Xe TGL GT2 (Mesa)

### RAM

16GB

### Additional context?

Tried with fractional scaling enabled on Wayland and no fractional scaling on X.

**Comment by MarkGhanz** [comment]
Oh I forgot I have `SDL_VIDEODRIVER=wayland` environment variable. I will disable it.

**Comment by iMonZ** [comment]
> Oh I forgot I have `SDL_VIDEODRIVER=wayland` environment variable. I will disable it.

Hopefully, this should be fixed soon.
https://github.com/AvaloniaUI/Avalonia/pull/11546
:)
