### ISSUE TITLE
Command Line Switches [Feature Request]

### ISSUE THREAD

**Issue by wwwizzarrdry** [Ryujinx/Ryujinx#4981]
### Overview

Add a command line switch for specifying a user profile when launching Ryujinx.

Eg.
"C:\Ryujinx\Ryujinx.exe" --fullscreen --profile-directory=Profile1  "C:\Ryujinx\Games\MyFavoriteGame.xci"

### Smaller details

Use an implementation similar to how web browsers do it.
"C:\Ryujinx\Ryujinx.exe" --fullscreen --profile-id=GYY12ZHZETGYIR8387BF06RD  "C:\Ryujinx\Games\MyFavoriteGame.xci"

### Nature of request

User experience and gain of function.

### Why would this feature be useful?

Especially useful for launching a game directly under a specified profile.

Eg. Multiple users in a household can create shortcuts to launch games with their chosen profile ID rather than bothering with the extra steps of opening the Profile Manager before every game.

**Comment by wwwizzarrdry** [comment]
It's undocumented but supported:
`"C:\Ryujinx\Ryujinx.exe" --fullscreen --profile "RyuPlayer" "C:\somegame.xci"`

**Comment by DocMAX** [comment]
All of the sudden ryujinx "/path/to/game/game.xci" doesnt start the xci anymore. I get into the game menu.
