### ISSUE TITLE
[Bug] Settings reset after changing settings in ldn build and opening base build

### ISSUE THREAD

**Issue by TBV305** [Ryujinx/Ryujinx#4996]
### Description of the issue

After opening ldn build and changing some settings they reset after opening and closing base build and opening ldn build 

### Reproduction steps

Open ldn build 
Change any settings, save and close
![image](https://github.com/Ryujinx/Ryujinx/assets/72977924/3eb8b61b-dcf1-4efe-92cd-ae00260af69c)
![image](https://github.com/Ryujinx/Ryujinx/assets/72977924/0d2ee13d-6e87-4d81-9d10-cc762a4df5f8)
Open and close base build
![image](https://github.com/Ryujinx/Ryujinx/assets/72977924/883bc9c1-281a-4401-8651-75f7b227afe4)
Open ldn build
All settings are reset
![image](https://github.com/Ryujinx/Ryujinx/assets/72977924/4f8364b4-c23d-44d8-9a9e-f4bf238a953f)
![image](https://github.com/Ryujinx/Ryujinx/assets/72977924/08ca9b00-1eeb-4352-ad20-280cd21e75ea)
![image](https://github.com/Ryujinx/Ryujinx/assets/72977924/46f4f6e8-dc69-4c6e-a504-746188363cbf)

### Log file

empty

### OS

Windows 11

### Ryujinx version

1.1.800

**Comment by AcK77** [comment]
There is currently an issue in our Avalonia UI build for LDN where the config used isn't `LDNConfig.json` as GTK UI.
You can use the Avalonia UI in a portable mode, or use the GTK UI for LDN.
The issue will be fixed in any future LDN release. Thanks.

**Comment by thu2468** [comment]
the setting is still a issue they are both sharing the same config file
