### ISSUE TITLE
[Bug] Crash on startup of TOTK on MacOS

### ISSUE THREAD

**Issue by dexilimes** [Ryujinx/Ryujinx#4997]
### Description of the issue

Ryujinx crashes every time I try and start Tears of the kingdom. It plays breath of the wild and other games. 

### Reproduction steps

Once I start TOTK it goes to the game icon and the loading bar, and then crashes

### Log file

[Ryujinx_1.1.800_2023-05-17_23-09-12.log](https://github.com/Ryujinx/Ryujinx/files/11498483/Ryujinx_1.1.800_2023-05-17_23-09-12.log)
[Ryujinx_1.1.800_2023-05-17_23-09-27.log](https://github.com/Ryujinx/Ryujinx/files/11498485/Ryujinx_1.1.800_2023-05-17_23-09-27.log)

### OS

MacOS 12.6.2 Monterey

### Ryujinx version

1.1.800

### Game version

1.1.0

### CPU

Apple M1

### GPU

Apple M1

### RAM

16GB

**Comment by gdkchan** [comment]
Enable hypervisor in the settings.

**Comment by MutantAura** [comment]
As above.
These issue pages are not for support queries. Please join our discord: https://discord.gg/ryujinx
