### ISSUE TITLE
[Bug]The Legend of Zelda: Breath of the Wild Archive directory has multiple duplicate files

### ISSUE THREAD

**Issue by love768952693** [Ryujinx/Ryujinx#5004]
### Description of the issue

Archive path, there are multiple parent directories, such as:
\publish\portable\bis\user\save\0000000000000002\1\1

The correct one should be
\publish\portable\bis\user\save\0000000000000002\1

The archive path exists multiple nested folders, the correct path and rules should be, game ID\archive file

### Reproduction steps

Run and save the game normally to reproduce it.

### Log file

/

### OS

win10

### Ryujinx version

1.1.804

### Game version

1.6.0

### CPU

I7-8700K

### GPU

3070

### RAM

32G

**Comment by OldManKain** [comment]
No this is actually how it is done on real hardware and is working as intended.
