### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DeltaQ-dze** [Ryujinx/Ryujinx#5011]
### Description of the issue

No audio after selecting save file to load in The Legend of Zelda: Tears of the Kingdom. Enabling Vsync fixes the issue.

### Reproduction steps

Configuration as it's listed in the log file. ensure Vsync is disabled. Launch the game and select a save to load and load into the game.

### Log file

[Ryujinx_1.1.804_2023-05-18_05-24-56.log](https://github.com/Ryujinx/Ryujinx/files/11508999/Ryujinx_1.1.804_2023-05-18_05-24-56.log)

### OS

Windows 11

### Ryujinx version

1.1.804

### Game version

1.10

### CPU

Ryzen 9 5900X

### GPU

Nvidia RTX 2060

### RAM

32GB

### List of applied mods

60fps_totk
60fpsBlackscreenFix
60fpsCutscenes (2GB re-encoded cutscenes)
DynamicFPSv1.41
Locked 1080p

### Additional context?

Running the same mods and settings on Yuzu with Vsync disabled does not produce the issue. (Don't worry I'm not changing to Yuzu anytime soon :)

**Comment by Pbird99** [comment]
It's probably due to your mods, the 60fps mod is unstable right now. Try removing them and test if that fixes things.

**Comment by OldManKain** [comment]
Please join us in our Discord https://discord.gg/ryujinx for troubleshooting issues.
