### ISSUE TITLE
[Feature Request] Local Wireless Offline (No internet or proxy)

### ISSUE THREAD

**Issue by lucas-xk** [Ryujinx/Ryujinx#5019]
### Overview

Multiplayer mode to emulate Local Wireless (ADHOC) but with offline option. It'd be nice to play with local network level instead to be connected to the internet.

### Smaller details

Option to play local multiplayer without internet connection.

### Nature of request

Network / multiplay

### Why would this feature be useful?

It's useful to play in a local network with low latency. And sometimes I want to play with friends using VPN, but the Ryujinx connects to its proxy server, and I want use just my VPN.

**Comment by gdkchan** [comment]
Why was this closed?

**Comment by lucas-xk** [comment]
> Why was this closed?

I realized that the option already exists (ldn_mitm). I couldn't make work with two instances of ryujinx in the same PC but with two different PCs in differents networks using a VPN worked. I'll try in the same network without VPN when I have access to two PCs at home.
