### ISSUE TITLE
glitches in totk [Bug]

### ISSUE THREAD

**Issue by Mohitrai123** [Ryujinx/Ryujinx#5020]
### Description of the issue

graphical glitches occur in tears of the  kingdom
rainbow textures

### Reproduction steps

i cant say for sure i have amd card and vulcan rest is on default

### Log file

eee

### OS

windows 11

### Ryujinx version

1.1.806

### Game version

1.10

### CPU

r5 3600

### GPU

rx 470

### RAM

8gb

### List of applied mods

30 fps

### Additional context?

e

**Comment by gdkchan** [comment]
Where's the log file? Also screenshots would be nice to actually show the issue.

**Comment by Mohitrai123** [comment]
so will it be fixed

**Comment by Mohitrai123** [comment]
anything i can do to fix it

**Comment by MetrosexualGarbodor** [comment]
[Already posted here](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598#issuecomment-1548754682).
