### ISSUE TITLE
[Feature Request] Allow the use of relative paths

### ISSUE THREAD

**Issue by RandomDude560** [Ryujinx/Ryujinx#5029]
### Overview

Files are always referenced by their full paths with can be a problem in portable mode if drive letters change for example.

### Smaller details

One easy way to change this would be to use the game directory as provided by the user e.g. "./games" and not resolve it to an absolute path in updates.json, dlc.json, and any other place it may be used.

### Nature of request

Portable mode improvement

### Why would this feature be useful?

Won't break paths if drive letters change in portable mode.

**Comment by AcK77** [comment]
> Won't break paths if drive letters change in portable mode.

In case the path of the portable install won't change, relative paths can do the job.
If the Ryujinx folder is moved, the issue stays the same. That's why we used fullpath, we "manage" the executable and not the used content so if a disk have their letter changed, the user have to set the letter permanently.

**Comment by gdkchan** [comment]
> > Won't break paths if drive letters change in portable mode.
> 
> In case the path of the portable install won't change, relative paths can do the job. If the Ryujinx folder is moved, the issue stays the same. That's why we used fullpath, we "manage" the executable and not the used content so if a disk have their letter changed, the user have to set the letter permanently.

I'm not sure what you're trying to say here, but moving the emulator directory wouldn't be a problem with relative paths.

**Comment by RandomDude560** [comment]
Manually editing updates.json and dlc.json to use relative paths seems to work just fine, it's just that even if the game directory is a relative path e.g. "./games" it gets expanded to an absolute path in updates.json and dlc.json.
Having changing paths should be expected in portable mode that's what makes it portable after all.

All I'm asking is to use the literal game directory as provided by the user instead of just expanding to absolute paths all the time, this way users can add relative paths as game directories and things just work even with changing paths.

Bonus would be if a game directory is within the root directory of Ryujinx the directory could be converted to a relative path instead to allow for this to just work.

**Comment by buggii** [comment]
> Manually editing updates.json and dlc.json to use relative paths seems to work just fine, it's just that even if the game directory is a relative path e.g. "./games" it gets expanded to an absolute path in updates.json and dlc.json. Having changing paths should be expected in portable mode that's what makes it portable after all.
> 
> All I'm asking is to use the literal game directory as provided by the user instead of just expanding to absolute paths all the time, this way users can add relative paths as game directories and things just work even with changing paths.
> 
> Bonus would be if a game directory is within the root directory of Ryujinx the directory could be converted to a relative path instead to allow for this to just work.

Hi RandomDude560, can you tell me how to manually edit the updates.json to use relative paths ? I have my games under:

X:\roms\switch\gamename.nsp 
and
X:\roms\switch\gameupdate.nsp 

and the ryujinx .exe is inside X:\emulators\ryujinx

I tried with:
\.gameupdate.nsp
and
..\..\roms\switch\gameupdate.nsp
but without success.

Thank you in advance !

**Comment by gelas78** [comment]
> ryujinx
For each back directory, you have to put ..\\
Assuming the emulator is on this path:   X:\emulators\ryujinx

"game_dirs": [
    "..\\..\\roms\\switch"
  ],
