### ISSUE TITLE
[Bug] TOTK, segmentation fault on loading

### ISSUE THREAD

**Issue by shionn** [Ryujinx/Ryujinx#5034]
### Description of the issue

Hello, 

Sometime, when game load new zone, or just after teleporting, game crash, with no log just have "Segmentation Fault" in my terminal where i launch ryujinx. 

I try different settings like : 
- Memory Manager Mode : Host or Host Unchecked
- Graphics Backend Multithreading On or Off
- Resolution scale Native or 2x

### Reproduction steps

In game, move long time for loading new aera, then teleport to new arera, if not crash, re-teleport again and again. 

### Log file

00:00:00.368 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.371 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.371 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.371 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.372 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.373 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.373 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73FF
00:00:00.374 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.374 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.374 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.386 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.808
00:00:00.395 |N| Application Print: Operating System: Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) (X64)
00:00:00.395 |N| Application Print: CPU: AMD Ryzen 7 5800X3D 8-Core Processor ; 16 logical
00:00:00.395 |N| Application Print: RAM: Total 31988 MiB ; Available 26721 MiB
00:00:00.398 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error, Guest
00:00:00.398 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.271 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:01.006 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD Radeon RX 6600 XT (RADV NAVI23) (Vulkan v1.3.230, Driver v22.3.6)
00:00:39.170 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:55.756 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:56.681 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:23.392 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:11:57.595 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:11:57.600 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:11:57.604 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:11:57.613 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:12:02.288 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:12:02.293 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:12:02.298 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:12:24.259 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:21:20.196 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:21:20.200 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:21:20.206 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:37:42.530 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

### OS

Debian, linux 6.1.0-9-AMD64

### Ryujinx version

1.1.808

### Game version

1.1.0

### CPU

R7 5800 X3D

### GPU

RX 6600 XT (RADV 22.3.6)

### RAM

32 GB

### List of applied mods

Different cases tested : 
- 30 FPS_Static (from FAQ)
- Ultrawide 21:9 or 32:1
- none, shader cache cleared, PPTC cleared

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
Thanks.
