### ISSUE TITLE
[Bug] Ryujinx crash at startup due to missing folder (?)

### ISSUE THREAD

**Issue by quentinhermiteau** [Ryujinx/Ryujinx#5037]
### Description of the issue

Hello Mac M1 user here.
2 days ago I was using Ryujinx with no issue at all. Uninstalled it with the Clean My Mac app
Today I tried to reinstall Ryujinx and it crashed every time I tried to launch regardless of the version
Fixed the issue by creating the `Ryujinx` folder into `/Users/xxx/Library/Application Support`
Figured you would like to know to fix this

### Reproduction steps

-

### Log file

-

### OS

MacOS Ventura 13.3.1 (a)

### Ryujinx version

1.1.810

### CPU

M1

**Comment by xiongpahao** [comment]
I met that, too. This is caused by the remained alias of Ryujinx folder in /Users/xiongpa/.config after deleting /Users/xiongpa/Library/Application Support/Ryujinx folder during uninstalling. So just delete the alias manually after third-party app's uninstalling, the crash would be solved.

**Comment by xiongpahao** [comment]
Of course, create a Ryujinx folder manually in /Users/xiongpa/Library/Application Support can be an alternative solution.
xiongpa is my username.

**Comment by livni** [comment]
I would update Ryujinx to inspect existence and integrity both of `/Users/user_name/Library/Application Support/Ryujinx` and of  the alias at `/Users/user_name/.config` and fix/recreate rather than failing, i.e. use defensive coding when having dependencies.

**Comment by AcK77** [comment]
> I tried to reinstall Ryujinx and it crashed every time I tried to launch regardless of the version

It will be hard to help you or point out the issue without a full log file or any error message. Can you provide one please?

**Comment by quentinhermiteau** [comment]
> It will be hard to help you or point out the issue without a full log file or any error message. Can you provide one please?

Well the rest of the issue + comments below should be self-explanatory, what kind of logs do you want? As the app crashes at launch I can't extract any logs from Ryujinx. Do you want the crash report from MacOS?

**Comment by AcK77** [comment]
Run Ryujinx from a terminal should show an error message.

**Comment by quentinhermiteau** [comment]
<img width="338" alt="CleanShot 2023-05-22 at 15 41 44@2x" src="https://github.com/Ryujinx/Ryujinx/assets/26874020/fb5f987a-5c16-47af-8fa8-28fb1c0490d9">
Aside of the MacOS popup to ask me if I want to generate a report, no error message appears in the terminal

**Comment by xiongpahao** [comment]
> I met that, too. This is caused by the remained alias of Ryujinx folder in /Users/xiongpa/.config after deleting /Users/xiongpa/Library/Application Support/Ryujinx folder during uninstalling. So just delete the alias manually after third-party app's uninstalling, the crash would be solved.

No need for log.

**Comment by AcK77** [comment]
Then the issue is solved.

**Comment by quentinhermiteau** [comment]
I'm trying to help improve the project here...
Please explain how I can provide you the logs you need

**Comment by legolas119** [comment]
Hi, i think that i have this issue as Axiom verge 2 contonue to crash at start up. But i haven't understood how to fix it... i have a portable installation of Ryujinx:
![Cattura2](https://github.com/Ryujinx/Ryujinx/assets/48774386/1b49318a-4ae5-48b3-b124-4dc2ed380404)

How i can find the Library/Application Support/Ryujinx folder?
thanks
