### ISSUE TITLE
[Bug] Ryujinx doesn't load defensively if Application Support folder was tampered

### ISSUE THREAD

**Issue by livni** [Ryujinx/Ryujinx#5039]
### Description of the issue

As I was trying to workaround bug #5038 on my macbook, I thought perhaps it would be best if Ryujinx completely resets its settings.
I made the following unforgivable change - I changed `Library/Application Support/Ryujinx` to `Library/Application Support/Ryujinx1` - note the `1` at the end and re-ran Ryujinx. When that failed I trashed Ryujinx from Applications and placed a new one there. That failed too, but that also deleted `Library/Application Support/Ryujinx1` folder so now I can't even change it back to the original name.

So yeah, I messed up big time, and now I can't seem to be able to run Ryujinx at all no matter what I do.
I'm opening a bug because I think Ryujinx could load more defensively, handling situations where the files/folders are not in the right place. Perhaps this is a feature request - your call. I also hope you might be able to tell me what I need to do to un-stuck myself - pretty please...

### Reproduction steps

1. While Ryujinx is not running, be a dumbass and rename `Library/Application Support/Ryujinx` to something else
2. Be a dumbass a second time and trash Applications / Ryujinx
3. cry

### Log file

No logs

### OS

macOS Ventura 13.3.1 (a)

### Ryujinx version

1.1.808

### CPU

Apple M1 Pro

**Comment by xiongpahao** [comment]
See my answer in #5037
