### ISSUE TITLE
[Bug] Glitched Visuals when using vulkan on nvidia gpu

### ISSUE THREAD

**Issue by IGame4FUN** [Ryujinx/Ryujinx#5040]
### Description of the issue

This is what I get when I start botw:
![image](https://github.com/Ryujinx/Ryujinx/assets/91326524/9b57e9df-780f-4a8b-a5f2-baf818ac1be5)

### Reproduction steps

Starting any game in Ryujinx using vulkan.

### Log file

[Ryujinx_1.1.811_2023-05-21_01-45-37.log](https://github.com/Ryujinx/Ryujinx/files/11523378/Ryujinx_1.1.811_2023-05-21_01-45-37.log)

### OS

Windows 10

### Ryujinx version

1.1.811

### CPU

i7-6700K

### GPU

gtx 970 4GB

### RAM

16GB DDR4

**Comment by IGame4FUN** [comment]
fixed by rolling back drivers to 516.94 (gtx 970 4GB)

**Comment by GamerzHell9137** [comment]
Don't use custom resolution scaling. Have it on native and if you wanna lower the resolution either use mods or handheld mode.
