### ISSUE TITLE
[Bug] TotK crash when near Dominizuin shrine

### ISSUE THREAD

**Issue by romulof** [Ryujinx/Ryujinx#5062]
### Description of the issue

Ryujinx completely crashes when getting close to the aforementioned shrine.

### Reproduction steps

- Get close to Dominizuin shrine
- Emulator crashes

Sometime I manage to get near enough to activate it, creating an autosave, but then when I load that save it crashes at the end of the loading screen.

### Log file

[Ryujinx_1.1.818_2023-05-22_23-15-41.log](https://github.com/Ryujinx/Ryujinx/files/11537186/Ryujinx_1.1.818_2023-05-22_23-15-41.log)

### OS

macOS Ventura 13.4 (22F66)

### Ryujinx version

1.1.818

### Game version

1.1.1

### CPU

M1 Pro

### GPU

M1 Pro

### RAM

16GB

### List of applied mods

Happens without mods, but also with these:
- Anisotropic Fix
- Disable FSR
- Disable FXAA
- Disable Quality Reduction
- Force 1008p Resolution
- fps++ 30
- Improve Shadow Resolution

### Additional context?

It seems to be a shader compilation error. Tried wiping the cache and using a shared shader cache, both without success.

**Comment by MetrosexualGarbodor** [comment]
Can you please post a save file and a log without any mods?

**Comment by romulof** [comment]
Other shrines work (already did 3 since I skipped the problematic one mentioned before), but it also happens in [Morok Shrine](https://www.ign.com/wikis/the-legend-of-zelda-tears-of-the-kingdom/Morok_Shrine).

**Comment by Foul-Tarnished** [comment]
BTW, don't use the "anisotropic fix" for ToTK on Ryu, does nothing good, quite the contrary.
Same for the 1008p mod ; just use the 1080p one instead. No AO issues with it on Ryujinx 😎
1080p for 1.1.1 is `00CECC0C 15000014`

**Comment by romulof** [comment]
Also happening in Spring of Wisdom, Mount Lanayru.

- [Log](https://github.com/Ryujinx/Ryujinx/files/11555883/Ryujinx_1.1.819_2023-05-24_16-37-55.log)
- [Save](https://github.com/Ryujinx/Ryujinx/files/11555888/Save.zip) - Load slot 1, walk forward, towards the Godess statue..

**Comment by romulof** [comment]
Never mind. It was one of the mods 🤦 

I was "disabling" by appending some characters in mod folder, but apparently that was not enough. Moving to a different locations solved it.

Apparently I was using the wrong version of the Disable FXAA mod that was not compatible with patch 1.1.1
