### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Szinrak** [Ryujinx/Ryujinx#5065]
### Description of the issue

Zelda TotK no focus on ZL

### Reproduction steps

The camera does not recenter behind the character in focus mode when I press ZL. Instead, the camera remains in the same position.
![Capture](https://github.com/Ryujinx/Ryujinx/assets/134343978/b185cb39-c28d-4a6c-862e-4027f01933ff)

### Log file

[Ryujinx_1.1.818_2023-05-23_02-22-56.log](https://github.com/Ryujinx/Ryujinx/files/11538025/Ryujinx_1.1.818_2023-05-23_02-22-56.log)

### OS

Win 10 x64

### Ryujinx version

1.1.818

### Game version

1.1.1 and 1.1.0

**Comment by MelonSpeedruns** [comment]
It seems to be a deadzone issue, try adding 0.2 of deadzone to both joysticks and try again.

**Comment by Szinrak** [comment]
it works, thank you very much you saved my life :D
