### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by haip4k** [Ryujinx/Ryujinx#5070]
### Description of the issue

When I start Luigi's Mansion 3 on version 1.0.0 or 1.4.0 with the local shader, it always crashes on the spot with the 119-121 (or so) shader 

### Reproduction steps

When I start the game with the local shader from RyuSAK v1.6.2, the game crashed. I've also tried to delete the local shader, but that doesn't help. In the place of Luigi falls through the shaft and the ghost dog (no idea what it's called) wakes up to him, it crashed at the spot. I don't know what I can do. Can someone help me? Thank you))

https://github.com/Ryujinx/Ryujinx/assets/133811195/c6be5c03-8a68-4a70-b51f-fd9efc70366e

https://github.com/Ryujinx/Ryujinx/assets/133811195/390f8f51-e056-44b8-a42a-536871b1d2d7

### Log file

[Ryujinx_1.1.811_2023-05-21_16-24-25.log](https://github.com/Ryujinx/Ryujinx/files/11542555/Ryujinx_1.1.811_2023-05-21_16-24-25.log)
[Ryujinx_1.1.811_2023-05-21_16-27-04.log](https://github.com/Ryujinx/Ryujinx/files/11542557/Ryujinx_1.1.811_2023-05-21_16-27-04.log)
[Ryujinx_1.1.811_2023-05-21_16-34-00.log](https://github.com/Ryujinx/Ryujinx/files/11542563/Ryujinx_1.1.811_2023-05-21_16-34-00.log)

### OS

macOS Ventura Version 13.1.1 (a)

### Ryujinx version

1.1.811

### Game version

1.0.0 or 1.4.0

### CPU

Apple Silicon M1

### GPU

M1

### RAM

8GB

### List of applied mods

I don't have any

### Additional context?

nope

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, especially with piracy tools.
