### ISSUE TITLE
[Bug] totk Fire temple entrance cutscene crashes

### ISSUE THREAD

**Issue by AThrowawayJoke** [Ryujinx/Ryujinx#5075]
### Description of the issue

Entering fire temple, cutscene right before you can use the hand thing for the temple. repeated crash right after the rocks slam onto the ceiling. The first time it crashed in the middle of the rocks going up.

### Reproduction steps

walk into fire temple

### Log file

[Ryujinx_1.1.819_2023-05-23_11-10-07.log](https://github.com/Ryujinx/Ryujinx/files/11545847/Ryujinx_1.1.819_2023-05-23_11-10-07.log)
[Ryujinx_1.1.819_2023-05-23_11-16-50.log](https://github.com/Ryujinx/Ryujinx/files/11545850/Ryujinx_1.1.819_2023-05-23_11-16-50.log)
[Ryujinx_1.1.819_2023-05-23_07-25-29.log](https://github.com/Ryujinx/Ryujinx/files/11545854/Ryujinx_1.1.819_2023-05-23_07-25-29.log)

### OS

Windows 10

### Ryujinx version

1.1.819

### Game version

1.1.1

### CPU

i5-12400F

### GPU

NVIDIA RTX 3070

### RAM

16GB

### List of applied mods

None

**Comment by riperiperi** [comment]
Do you have a save before this cutscene? It appears the GPU is running out of VRAM, but it’s not obvious why.

**Comment by AThrowawayJoke** [comment]
multiple cutscenes in fire temple appear to have the issue. I have saves but I don't know where to find them in my system files. how should I send them?

**Comment by SirSiscu** [comment]
I had the same problem getting into the boss fight (I solved it skipping the scene very quickly), but now when I beat the boss it crashes again even if I try to skip.

**Comment by riperiperi** [comment]
Try running the game at native resolution.

**Comment by AThrowawayJoke** [comment]
running at native resolution helps get through the cutscene without issue, but the game fails to save during the bossfight. Audio is also not playing music or half the other sounds, and the d-pad menu's struggle to load.

**Comment by Flax4** [comment]
I just had this very same issue today, for some reason that cutscene makes GPU & VRAM usage skyrocket and crashes the game.

**Comment by AThrowawayJoke** [comment]
UPDATE: This is indeed a VRAM issue. It has been noted in the FAQ & Troubleshooting guide found [here](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-game-crashes-with-e-guirenderthread-application--unhandled-exception-caught-ryujinxgraphicsvulkanvulkanexception-unexpected-api-error-erroroutofdevicememory)
enabling texture recompression and rebuilding the shader and pptc caches should fix it, but I encountered an issue where the game continued to be unable to save. The only thing I can guess as to what is causing it is some sort of memory leak, because rebooting my computer has solved that persistent issue.

So when you encounter this issue: Enable Texture recompression, run at native resolution, clear caches, then restart your computer.

Seeing as this caused a strange error with saving, I'm going to wait for someone with more experience to close this issue and/or open a new one. After going through the cutscene for the opening boss fight, the game tried to autosave, and the icon never disappeared. Manually trying to save softlocked the game; attempting to load did the same. it just got stuck trying to finish the save in the menu.

**Comment by gdkchan** [comment]
The save issue sounds like #5024.

**Comment by SirSiscu** [comment]
It worked! It was still laggy, but the cutscene could end without the game imploding. Thanks!
