### ISSUE TITLE
[Bug] crash when finished loading shaders for TOTK

### ISSUE THREAD

**Issue by OR-Apocrypha** [Ryujinx/Ryujinx#5081]
### Description of the issue

Whilst loading up TOTK and it finishes loading the shader cache it crashes completely, only started since recent update, also round that my Aspect Resolution was set to 31:9 for some reason even though I'm 16:9.

### Reproduction steps

1. Launch TOTK (tried from file and from list on home page)
2. Wait for shader cache to load.
3. Crash.

### Log file

[Ryujinx_1.1.819_2023-05-24_02-20-59.log](https://github.com/Ryujinx/Ryujinx/files/11549585/Ryujinx_1.1.819_2023-05-24_02-20-59.log)

### OS

Windows 10 Pro

### Ryujinx version

1.1.819

### Game version

1.1.0

### CPU

i7-9700K @ 3.60GHz

### GPU

NVIDIA GeForce RTX 2060

### RAM

32GB

### List of applied mods

- 60 FPS
- BeedleStock
- DynamicFPSv1.41
- Guaranteed Amiibo Fabrics
- NoLootBoxes
- Visual Improvements

### Additional context?

went from version 1.1.818 to 1.1.819

**Comment by MetrosexualGarbodor** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
Thanks.
