### ISSUE TITLE
Hide the mouse [Bug]

### ISSUE THREAD

**Issue by altiereslima** [Ryujinx/Ryujinx#5082]
### Description of the issue

The Ryujinx Ava doesn't hide the mouse in fullscreen mode.

### Reproduction steps

-Enable "Hide Cursor"
-Launch the game in fullscreen mode.

### Log file

?

### OS

Windows 10

### Ryujinx version

1.1.819

### CPU

I7 6700K

### GPU

RTX 2060 Super

### RAM

16GB

**Comment by TSRBerry** [comment]
Closing in favor of #5136
