### ISSUE TITLE
[Bug]Ryujinx used to run at 50-60 fps, now consistently runs at 20-40

### ISSUE THREAD

**Issue by hackakat** [Ryujinx/Ryujinx#5097]
### Description of the issue

I've been using Ryujinx for a couple months now to play Super Mario Maker 2, and have never had any problems except for a bit of frame drops every now and then. A week ago I opened it up and while playing it would consistently stay at around 20-40 fps, as well as having these texture bugs.

![hj](https://github.com/Ryujinx/Ryujinx/assets/134601205/f2c9856a-a303-4f20-bfb5-ff2e92b3bf05)

I didn't change any settings or mess with anything, just one day it was fine and the next it wasn't. I've switched between OpenGL and Vulkan, I've purged my shader cache, I've uninstalled and reinstalled Ryujinx, all with no success.

Any help is appreciated <3

### Reproduction steps

n/a

### Log file

[Ryujinx_1.1.819_2023-05-25_04-52-38.log](https://github.com/Ryujinx/Ryujinx/files/11563466/Ryujinx_1.1.819_2023-05-25_04-52-38.log)
[Ryujinx_1.1.819_2023-05-25_03-36-30.log](https://github.com/Ryujinx/Ryujinx/files/11563467/Ryujinx_1.1.819_2023-05-25_03-36-30.log)
[Ryujinx_1.1.819_2023-05-25_03-22-14.log](https://github.com/Ryujinx/Ryujinx/files/11563468/Ryujinx_1.1.819_2023-05-25_03-22-14.log)

### OS

Windows 11

### Ryujinx version

15.0.1

### Game version

3.0.2

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz

### GPU

NVIDIA GeForce GTX 1650

### RAM

8GB

### Additional context?

While playing SMM2 Ryujinx uses 40% of my CPU, 672 MB of my memory, and 95% of my GPU. Don't know if this is normal or matters at all.

**Comment by B0XGaming** [comment]
I'm also experiencing this (and have been for months.)

Machine specs:
Ryzen 5 5600X
32Gb Ran
GTX 1080
Applied mod: open course world

I'm using the same Ryujinx version and OS as hakakat.

**Comment by riperiperi** [comment]
You have set res scale to 4x, which will be running games at 8k resolution. Super Mario Maker scales tilesets incorrectly so should be played at 1x scale.

**Comment by B0XGaming** [comment]
> You have set res scale to 4x, which will be running games at 8k resolution. Super Mario Maker scales tilesets incorrectly so should be played at 1x scale.

This just fixed mine. Heck. Thank-you dude!
