### ISSUE TITLE
RyujiNX Master Build 1.0.2042 Crash GAMES XCI,NSP

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#510]
RyujiNX Master Build 1.0.2042 crash boot all games XCI,NSP  #438 #509 

![anotacao 2018-11-19 072908](https://user-images.githubusercontent.com/37957125/48697869-d7223880-ebcc-11e8-9055-cbc4e01017f9.jpg)

**Comment by emmauss** [comment]
do you have a file with that same name there?

**Comment by simontime** [comment]
I don't think you're doing it right

**Comment by simontime** [comment]
Are you sure there isn't a file in that directory called "system"?

**Comment by EmulationChannel** [comment]
yes yes there is no local pasta system

**Comment by EmulationChannel** [comment]
OK Thanks for the help it worked out right now after creating another pasta system here Thanks

**Comment by emmauss** [comment]
okay, closing this then

**Comment by EmulationChannel** [comment]
OK Thanks for the help
