### ISSUE TITLE
[Bug]MacOS Crash in specific area

### ISSUE THREAD

**Issue by wms-0520** [Ryujinx/Ryujinx#5106]
### Description of the issue

When I move character to a specific area, the game crashed. 
<img width="1440" alt="截屏2023-05-26 18 06 32" src="https://github.com/Ryujinx/Ryujinx/assets/134120606/0e213c2b-df46-4061-a6a2-3871b05034c8">
<img width="1440" alt="截屏2023-05-26 18 06 59" src="https://github.com/Ryujinx/Ryujinx/assets/134120606/f778f889-0ff1-4110-9203-cb06571f406e">

### Reproduction steps

move character to this area, along the road on the map.

### Log file

[Ryujinx_1.1.824_2023-05-26_17-44-27.log](https://github.com/Ryujinx/Ryujinx/files/11574139/Ryujinx_1.1.824_2023-05-26_17-44-27.log)
[Ryujinx_1.1.824_2023-05-26_18-00-37.log](https://github.com/Ryujinx/Ryujinx/files/11574140/Ryujinx_1.1.824_2023-05-26_18-00-37.log)
[Ryujinx_1.1.824_2023-05-26_18-04-45.log](https://github.com/Ryujinx/Ryujinx/files/11574141/Ryujinx_1.1.824_2023-05-26_18-04-45.log)

### OS

macOS 13.3.1 (a) 

### Ryujinx version

1.1.824

### Game version

1.1.2

### CPU

M1

### GPU

M1

### RAM

8 GB

### Additional context?

This issue also occurs elsewhere in the game, it's not an isolated case.

**Comment by AcK77** [comment]
`LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

This more looks like a bad dump (game or update one) than a Ryujinx issue.

**Comment by wms-0520** [comment]
> `LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`
> 
> This more looks like a bad dump (game or update one) than a Ryujinx issue.

I asked my friends who use the Mac version simulator, but they haven't encountered this problem. Perhaps it's because my memory is only 8GB?

**Comment by AcK77** [comment]
It’s because your game/update dump are bad. As I told you above.

**Comment by wms-0520** [comment]
> It’s because your game/update dump are bad. As I told you above.

So the possible solution is to reinstall the game/update?

**Comment by wms-0520** [comment]
Replaced a dump and now runs perfectly.thx
