### ISSUE TITLE
[Bug] auto-update deletes executables, doesn't replace them

### ISSUE THREAD

**Issue by speedwaystar** [Ryujinx/Ryujinx#5115]
### Description of the issue

the last two times Ryujinx has autoupdated, the result has been an install folder with no Ryujinx.exe, necessitating a full reinstall from the website download page.

the install location isn't  protected windows folder, so i'm not sure what's going on.

### Reproduction steps

accept Ryujinx's request to install an update when it pops up.

### Log file

[Ryujinx_1.1.826_2023-05-27_17-17-53.log](https://github.com/Ryujinx/Ryujinx/files/11581418/Ryujinx_1.1.826_2023-05-27_17-17-53.log)

### OS

11

### Ryujinx version

1.1.826

**Comment by OldManKain** [comment]
Don't put Ryujinx on the Desktop or try to run a game during updating.

**Comment by speedwaystar** [comment]
There was no game running

**Comment by OldManKain** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-updated-ryujinx-and-now-the-executableall-my-files-are-gonenamed-ryuold

**Comment by speedwaystar** [comment]
Thanks!
