### ISSUE TITLE
[Bug] Amiibo on macOS

### ISSUE THREAD

**Issue by iMonZ** [Ryujinx/Ryujinx#5117]
### Description of the issue

The Amiibo Function is greyed out on the macOS Version

### Reproduction steps

Starting Ryujinx, Opening TOTK  game, and pressing inside the game on the "Action" tab. The Amiibo Function is greyed out.

### Log file

[Ryujinx_1.1.825_2023-05-26_22-16-48.log](https://github.com/Ryujinx/Ryujinx/files/11581967/Ryujinx_1.1.825_2023-05-26_22-16-48.log)
[Ryujinx_1.1.825_2023-05-27_01-27-25.log](https://github.com/Ryujinx/Ryujinx/files/11581968/Ryujinx_1.1.825_2023-05-27_01-27-25.log)
[Ryujinx_1.1.826_2023-05-27_01-28-51.log](https://github.com/Ryujinx/Ryujinx/files/11581969/Ryujinx_1.1.826_2023-05-27_01-28-51.log)

### OS

macOS 13.4 (22F66)

### Ryujinx version

1.1.825

### Game version

1.1.1

### List of applied mods

<img width="1007" alt="Screenshot 2023-05-26 at 00 54 34" src="https://github.com/Ryujinx/Ryujinx/assets/11319871/e8f92edc-410a-4777-a9d2-a71c9e51c111">

**Comment by MutantAura** [comment]
You need to reach a stage where the game requests an amiibo, in ToTK this function needs to be activated in the settings menu and you then need to activate the amiibo slate power. Once this power is active, the amiibo button will be ungreyed. 

In future please use discord for support queries.

**Comment by iMonZ** [comment]
> You need to reach a stage where the game requests an amiibo, in ToTK this function needs to be activated in the settings menu and you then need to activate the amiibo slate power. Once this power is active, the amiibo button will be ungreyed.
> 
> In future please use discord for support queries.

Okay I did that. But the list of Amiibos is empty.
