### ISSUE TITLE
[Bug] Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries

### ISSUE THREAD

**Issue by Colin6618** [Ryujinx/Ryujinx#5120]
### Description of the issue

The screen is black after opening the game. Pictures flickering.
Pic attached.

![SCR-20230527-in4](https://github.com/Ryujinx/Ryujinx/assets/3047309/456aff26-3b74-451d-8030-dd9a7558e124)

### Reproduction steps

1. Initial installation. Import keys and firmware, load game and patches. 
2. Load TOTK. Load success.  Nintendo text appears. Screen is balck and screen flickers. 
3. Try another game, having the same issue.
4. Ryujinx Crashed after around 1 min. 

### Log file

[Ryujinx_1.1.826_2023-05-27_13-00-28.log](https://github.com/Ryujinx/Ryujinx/files/11583071/Ryujinx_1.1.826_2023-05-27_13-00-28.log)
[Ryujinx_1.1.826_2023-05-27_14-05-15.log](https://github.com/Ryujinx/Ryujinx/files/11583072/Ryujinx_1.1.826_2023-05-27_14-05-15.log)
[Ryujinx_1.1.826_2023-05-27_14-49-21.log](https://github.com/Ryujinx/Ryujinx/files/11583073/Ryujinx_1.1.826_2023-05-27_14-49-21.log)

### OS

macOS 13.3.1 (a) 

### Ryujinx version

1.1.826

### Game version

1.1.1

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5300M 4G

### RAM

16G

### List of applied mods

None

### Additional context?

<details open></summary> app crash report</summary>

[Crash full report](https://github.com/Ryujinx/Ryujinx/files/11583174/crash.full.report.log)

</details>

**Comment by Pbird99** [comment]
For Intel macs, you should probably run Ryujinx on Windows via Bootcamp instead as there should be less bugs.

**Comment by JRR-33** [comment]
HI,
I've read many comments as this for Intel Mac issues (which is my case too)

Can you please explain the problem with Intel Mac on Ryujinx ? 
Intel I7 and radeon and GPU 5300 PRO are not supposed to be too leak to run Ryujinx ? But as I understand, it's a problem of GPU driver or something like this ? 
I really don't understand how my Mac up to date is not able to have the last version avec Radeon card driver ??? And how using bootcamp on windows or linux can make the same system being OK to run Ryujinx without crash...
But if it really works then I will try it on bootcamp !
Thx

JR

**Comment by gleng** [comment]
The black screen and flickering image should be fixed by https://github.com/Ryujinx/Ryujinx/pull/5446.

**Comment by Colin6618** [comment]
I can't confirm if this is still an issue, but I would choose to close this Issue.
