### ISSUE TITLE
Unable to  launch TOTK with Vulkan

### ISSUE THREAD

**Issue by DubiousDolphin** [Ryujinx/Ryujinx#5134]
### Description of the issue

Launching with Vulkan causes my Ryujinx to instantly crash. I have a Asus laptop with a GTX 1660 TI and a Ryzen 7 4800H. I'm using default settings on Ryujinx. The game runs fine on OpenGL but I've been told it runs much better with Vulkan so I was hoping there was some sort of solution. My graphics drivers are up to date. Tears of the Kingdom does not even load, Ryujinx just instantly crashes whenever I double click the game.

### Reproduction steps

I'm not sure how to reproduce this issue.

### Log file

[Ryujinx_1.1.829_2023-05-28_12-59-13.log](https://github.com/Ryujinx/Ryujinx/files/11585571/Ryujinx_1.1.829_2023-05-28_12-59-13.log)

### OS

Windows 11

### Ryujinx version

1.1.829

### Game version

1.1.2

### CPU

Ryzen 7 4800H

### GPU

Nvidia GTX 1660 TI

### RAM

16GB

### List of applied mods

NA

**Comment by AcK77** [comment]
Can you try to backup/delete the Config.json file in your Ryujinx folder?
It's more looks like an issue for Ryujinx to find your GPU using Vulkan.

**Comment by SirJoe71** [comment]
Vulkan requries updated nvida drivers installed, I have solved installing the latest.

**Comment by DubiousDolphin** [comment]
> Vulkan requries updated nvida drivers installed, I have solved installing the latest.

I have the latest version installed

**Comment by DubiousDolphin** [comment]
> Can you try to backup/delete the Config.json file in your Ryujinx folder? It's more looks like an issue for Ryujinx to find your GPU using Vulkan.

I don't see this file in my Ryujinx folder

**Comment by djsmax** [comment]
Hey, were you able to use Vulkan in the end? I have the same laptop and exact same error as you, wonder what's up with that.

**Comment by DubiousDolphin** [comment]
> Hey, were you able to use Vulkan in the end? I have the same laptop and exact same error as you, wonder what's up with that.

Yeah, you need to update the drivers on both your gpu and your integrated graphics card. My gpu drivers were up to date but my igpu had 2 year old drivers. You can download the drivers from the amd site, and that should allow you to use vulkan and pick your gpu.

**Comment by djsmax** [comment]
> > Hey, were you able to use Vulkan in the end? I have the same laptop and exact same error as you, wonder what's up with that.
> 
> Yeah, you need to update the drivers on both your gpu and your integrated graphics card. My gpu drivers were up to date but my igpu had 2 year old drivers. You can download the drivers from the amd site, and that should allow you to use vulkan and pick your gpu.

Oh, thank you! One reinstall later, GPU shows up in the settings, and Vulkan works. Can't believe it was an AMD driver that was holding me back. Vulkan is SO much better for frame pacing.
