### ISSUE TITLE
Hide cursor option is still broken

### ISSUE THREAD

**Issue by TSRBerry** [Ryujinx/Ryujinx#5136]
@TSRBerry Unfortunately, the argument is still broken. 

The cursor disappears during the loading screen, but it reappears when the game is loaded.

Ava UI version 1.1.800

I am using the following command:

Ruyjinx.Ava.exe -f --hide-cursor Always Game.nsp

I need to move the cursor outside the window to avoid seeing it.

_Originally posted by @jojodunet in https://github.com/Ryujinx/Ryujinx/issues/4927#issuecomment-1552031910_

**Comment by Exhigh** [comment]
> Ruyjinx.Ava.exe -f -hide-cursor Always Game.nsp

in the command it should be --hide-cursor instead of -hide-cursor

**Comment by gdkchan** [comment]
Fixed by #6725.
