### ISSUE TITLE
[Bug] TOTK LOD or Texture issue?

### ISSUE THREAD

**Issue by systox** [Ryujinx/Ryujinx#5138]
### Description of the issue

Looking at the island and lake in the distance is all jacked up like this:

https://github.com/Ryujinx/Ryujinx/assets/50300640/130d6ba4-3814-41a2-a082-37a8e51ce4a0

### Reproduction steps

Look at the Rist Peninsula from anywhere in the distance. Its margins are all in flux and look wrong.

No mods, Vsync on, Vulkan API.

### Log file

[Ryujinx_1.1.819_2023-05-28_18-59-01.log](https://github.com/Ryujinx/Ryujinx/files/11586074/Ryujinx_1.1.819_2023-05-28_18-59-01.log)

### OS

Windows 11

### Ryujinx version

1.1.819

### Game version

1.1.2

### CPU

5800x3d

### GPU

RTX 4090

### RAM

32GB

### List of applied mods

None.

### Additional context?

Please let me know if there's additional information I can provide.

**Comment by systox** [comment]
[slot_00.zip](https://github.com/Ryujinx/Ryujinx/files/11586094/slot_00.zip)


My save if its helpful.

**Comment by Pbird99** [comment]
Try updating Ryujinx to the latest version as this issue should be reduced by PR #5027.

**Comment by systox** [comment]
Updated to Ryujinx 1.1.841, unfortunately issue persists. Video attached. I purged shaders just in case, no change.

https://github.com/Ryujinx/Ryujinx/assets/50300640/5a847911-d727-4e78-9e65-e5e6f9c5b7af

**Comment by systox** [comment]
Just tried with OpenGL, same problem. Thanks for looking into it.

**Comment by Pbird99** [comment]
You could also try using the WIP PR #5012 as that specifically fixes z-fighting for water; however, it hasn't been rebased so the other fixes for TOTK aren't included.

**Comment by systox** [comment]
Thank you everyone, it looks like this is a known bug that folks may be working on.

**Comment by cobbycobbycobcob** [comment]
#5073 ?

**Comment by systox** [comment]
dunno if its related but wanted to point out there are also horizontal scanlines in low standing water: 
![image](https://github.com/Ryujinx/Ryujinx/assets/50300640/4fd4f147-03f3-4911-aac8-1ce7b444b87b)

**Comment by HomAfromPTZ** [comment]
Have the same issue.
Ryujinx v.1.1.850, Vulkan (all default settings except 2x resolution. Setting in back to native has no effect - the bug persists)
Ryzen 6800H + RTX 3060 Laptop
https://github.com/Ryujinx/Ryujinx/assets/9579310/7fa1b0f3-2448-49de-a7a7-6e025cb3939e

**Comment by systox** [comment]
Likely relates to: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598#issue-1705759855
