### ISSUE TITLE
Not able to update on mac [Bug]

### ISSUE THREAD

**Issue by noahgg12** [Ryujinx/Ryujinx#5146]
### Description of the issue

Not able to update on Mac while in ryujinx app

### Reproduction steps

Idk, I just try to update on mac then it says updater error. An error occurred during ryujinx update ( Updater.sh:50)

### Log file

An error occurred during Ryujinx update (updater.sh:50)

### OS

MAC OS

### Ryujinx version

1.1.840

### Game version

1.10

### CPU

M2 Pro 

[Ryujinx-2023-05-25-104839.ips.zip](https://github.com/Ryujinx/Ryujinx/files/11592954/Ryujinx-2023-05-25-104839.ips.zip)

**Comment by noahgg12** [comment]
Log file in additional context

**Comment by siegmund-heiss-ich** [comment]
Thx for the Logfile
It happens because there are spaces in your path of the app.
I will try to fix this.

**Comment by siegmund-heiss-ich** [comment]
I can't reproduce this issue..
I tried an external path with spaces (your setup) and it works fine for me.
Do you have write permissions on your external drive?
If you use an external drive with ntfs it also wouldn't work, unless you installed specific tools for that.
Did the updater work before?
I would try to place `Ryujinx.app` in the Applications folder on your mac, and try updating it from this location.

**Comment by noahgg12** [comment]
I have had the same problems in the updater for forever. I will try placing it into the application folder. Will let you know if that works

**Comment by noahgg12** [comment]
It works when you put it into applications folder thanks for the help

**Comment by siegmund-heiss-ich** [comment]
You are welcome!
It seems there is something wrong with write permissions on your external drive.
Not a problem of Ryujinx itself.
