### ISSUE TITLE
[Bug] ToTK textures aren't loading, unless an effect is used on them

### ISSUE THREAD

**Issue by Danke-Boi** [Ryujinx/Ryujinx#5150]
### Description of the issue

Everything is black, except for the fog, and all effects that have self luminance. This effect is negated (at least for link) if you obstruct the camera's view with link, forcing a transparency effect. This allows Link's textures to load.

### Reproduction steps

Load the game, the title screen shouldn't show anything but menu items and the swirly green bits.

### Log file

[Ryujinx_1.1.841_2023-05-29_14-25-14.log](https://github.com/Ryujinx/Ryujinx/files/11594338/Ryujinx_1.1.841_2023-05-29_14-25-14.log)

### OS

Windows 10

### Ryujinx version

1.1.841

### Game version

1.0.0

### CPU

i5-10400f

### GPU

Nvidia GTX 1070ti

### RAM

16GB

### List of applied mods

none

**Comment by Danke-Boi** [comment]
https://youtu.be/Jr-OAgw_Vs4

**Comment by phoenixpereira** [comment]
Try setting the graphics backend to Vulkan. Also, the log says the MaxAnisotropy is set to -1, which doesn't seem right, so try setting the Anisotropic Filtering to 16x.

**Comment by Danke-Boi** [comment]
> Try setting the graphics backend to Vulkan. Also, the log says the MaxAnisotropy is set to -1, which doesn't seem right, so try setting the Anisotropic Filtering to 16x.

It's on Vulkan already, did the log file say otherwise? Also, I have anistropic filtering set to 4x, I'll try 16x

**Comment by phoenixpereira** [comment]
The log file that you provided said it was on OpenGL.

**Comment by Danke-Boi** [comment]
> The log file that you provided said it was on OpenGL.

No change, I tried setting it to OpenGL and back again in case that would fix it showing up as OpenGL

**Comment by Danke-Boi** [comment]
[Ryujinx_1.1.841_2023-05-29_16-52-57.log](https://github.com/Ryujinx/Ryujinx/files/11594581/Ryujinx_1.1.841_2023-05-29_16-52-57.log)

**Comment by Foul-Tarnished** [comment]
> Try setting the graphics backend to Vulkan. Also, the log says the MaxAnisotropy is set to -1, which doesn't seem right, so try setting the Anisotropic Filtering to 16x.

-1 just means auto

**Comment by MutantAura** [comment]
Purge your shader cache and fresh install GPU drivers with a tool such as DDU. This seems like a system specific issue.
In future please use our discord for support queries: https://discord.gg/ryujinx
