### ISSUE TITLE
[Bug] TOTK Extreme Stuttering

### ISSUE THREAD

**Issue by KokoDraws** [Ryujinx/Ryujinx#5152]
### Description of the issue

I've been using version 1.1.805 for weeks because every update since then stutters unplayably bad in every location. From the moment the game starts. It'd be running smoothly if not for the constant stopping.

### Reproduction steps

Run Tears of the Kingdom

### Log file

[Ryujinx_1.1.841_2023-05-29_15-36-47.log](https://github.com/Ryujinx/Ryujinx/files/11594433/Ryujinx_1.1.841_2023-05-29_15-36-47.log)

### OS

Windows 10

### Ryujinx version

1.1.841

### Game version

1.0.0

### CPU

Ryzen 7 5700G 8 Core

### GPU

Nvidia RTX 3090

### RAM

32GB

### List of applied mods

I had no mods until yesterday. I don't know if they show up in the logs but this issue's been present long before then.

**Comment by phoenixpereira** [comment]
Enabling the shader cache should fix most of the stutters after you played for a bit. If that doesn't work, try setting the graphics backend to Vulkan.

**Comment by AcK77** [comment]
As suggested above, use Vulkan graphic backend and enable shader cache. Thanks.
