### ISSUE TITLE
[Bug] Taiko no Tatsujin Rhythm Festival

### ISSUE THREAD

**Issue by dantezero0403** [Ryujinx/Ryujinx#5157]
### Description of the issue

exit with error

### Reproduction steps

After booting and pressing the button a few times

### Log file

[Ryujinx_1.1.842_2023-05-30_10-08-07.log](https://github.com/Ryujinx/Ryujinx/files/11594856/Ryujinx_1.1.842_2023-05-30_10-08-07.log)

### OS

Win11

### Ryujinx version

1.1.842

### Game version

1.0.0

### CPU

AMD Ryzen™ 9 6900HX

### GPU

AMD Radeon™ 680M

### RAM

24312

**Comment by MetrosexualGarbodor** [comment]
You need to accept the first User License agreement and **not** accept the second Data Analysis Policy to launch the game.
Please use discord for support queries next time: https://discord.gg/ryujinx
Thanks.
