### ISSUE TITLE
[Bug] Ryujinx crashing when playing ToTK macOS (Ryujinx 1.1.842)

### ISSUE THREAD

**Issue by josh-the-tech** [Ryujinx/Ryujinx#5166]
### Description of the issue

When playing ToTK on macOS 13.4 MacBook Pro M1 Max, the game can crash the emulator whilst performing any action. It is random and when trying to reproduce the exact steps that caused the crash, it then won't crash, but will at another action.

E.g. in a shrine it crashed when opening the chest at the end. When reloading the autosave, and re-completing the shrine, the crash did not occur.

I suspect it could be an intermittent crash potentially related to auto save.

Sometimes I can play for an hour or longer with no issue, sometimes it can be a matter of minutes.

I have attached the log with the error.

### Reproduction steps

This issue does not appear to be easily reproducible and is intermittent. I suspect it may occur when an autosave is happening. This doesn't always result in a crash.

### Log file

[Ryujinx_1.1.842_2023-05-30_20-50-07.log](https://github.com/Ryujinx/Ryujinx/files/11604354/Ryujinx_1.1.842_2023-05-30_20-50-07.log)

### OS

macOS 13.4

### Ryujinx version

1.1.842

### Game version

1.1.1

### CPU

M1 Max

### GPU

M1 Max

### RAM

64GB

### List of applied mods

fps++30_totk
VisualFixes_1008P_FXAA_Off_FSR_Off_totk
VisualFixes_AnisotropicFix_totk
VisualFixes_ShadowResolution_totk

**Comment by systox** [comment]
If you enable vsync, can you reproduce the crash?

**Comment by josh-the-tech** [comment]
I’ll test tomorrow evening and update. If it happens again with vsync on, I’ll attach the updated log
  
  

  
  
>

**Comment by phoenixpereira** [comment]
Also try playing it without the mods.

**Comment by AcK77** [comment]
> Also try playing it without the mods.

Yeah does the crash still happens if you play without mods ?

**Comment by josh-the-tech** [comment]
I haven't removed the mods but playing for a little while today with no crashes on the latest build, with VSync on. Closing this for now.
