### ISSUE TITLE
[Regression] Hyrule Warriors Age of Calamity broken water shader

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#5170]
### Description of the issue

After https://github.com/Ryujinx/Ryujinx/pull/4401 was merged the water shader in AOC got broken.

It was tested on native with no mods and its still happening. Its happening in all maps but its easiest visible on Cryonis Mastering map.

Before:
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/2e010f25-4ebc-49aa-a4e4-b38dc75b4226)

After:
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/c100d962-27af-4b0b-9f5b-379a73d7b82f)

Location of the map:

![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/91f0f5b3-eec4-4330-b4cb-22d679d56752)

### Reproduction steps

Just start the mission

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.842

### Game version

1.3.0

### CPU

Ryzen 3600

### GPU

RTX 3060 Ti

### RAM

16 GB

**Comment by Foul-Tarnished** [comment]
Can you upload a save ?
