### ISSUE TITLE
[Bug] TOTK crashes every time when starting.

### ISSUE THREAD

**Issue by ha7rock** [Ryujinx/Ryujinx#5174]
### Description of the issue

When playing totk with my MBP (M1 max), its crashes every time after starting.

### Reproduction steps

1. firmware = 16.0.2
2. totk.xci with 1.1.0 patched.
3. just double click to start game

### Log file

[Ryujinx_1.1.844_2023-05-31_18-33-02.log](https://github.com/Ryujinx/Ryujinx/files/11611902/Ryujinx_1.1.844_2023-05-31_18-33-02.log)

### OS

MAC OS 13.3.1

### Ryujinx version

1.1.844

### Game version

1.1.0

### CPU

M1 MAX

### GPU

M1 MAX

### RAM

32GB

**Comment by arloan** [comment]
I also encountered the crash while loading ToTK, in the status bar, the FIFO suddenly increased as 100%, and after a couple of seconds, it changed a bit like 99.x%, 75.x%, and then Ryujinx crashed.

### Reproduction steps
1. firmware = 16.0.2
2. totk.xci 1.0.0 non patched.
3. just double click to start game

### Log File
[errorlog-totk-ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/11623286/errorlog-totk-ryujinx.log)

### OS
MAC OS 12.2.1

### Ryujinx version
1.1.0-macos1

### Game version
1.0.0

### CPU
Intel i7-10710U

### GPU
Intel Integrated GPU

### RAM
16GB

**Comment by arloan** [comment]
Oh, the log file above is generated by macOS itself, I'll attach the log file generated by Ryujinx here.

[Ryujinx_ 1.1.0-macos1_2023-06-01_17-08-20.log](https://github.com/Ryujinx/Ryujinx/files/11623434/Ryujinx_.1.1.0-macos1_2023-06-01_17-08-20.log)

**Comment by AcK77** [comment]
@ha7rock Your log file doesn't include any error, could you try again and send the most recent log file here please.

@arloan To play totk you can use macos universal build from : https://github.com/Ryujinx/release-channel-master/releases (I suggest you to come to our discord for support for any further questions)

**Comment by ha7rock** [comment]
> > ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
> 
> Your game dump seems to be corrupted, I suggest you to redump your game following our guide on the Wiki, and try again. You can come to our discord server if you need support. Thanks.

finally got start game after changing the game image. 
Thank you very much！

**Comment by arloan** [comment]
> @ha7rock Your log file doesn't include any error, could you try again and send the most recent log file here please.
> 
> @arloan To play totk you can use macos universal build from : https://github.com/Ryujinx/release-channel-master/releases (I suggest you to come to our discord for support for any further questions)

Also crashed for 1.1.855, I checked the logfile, seems it complained that GPU is too slow, maybe I should use a machine with a better standalone GPU?

[Ryujinx_1.1.855_2023-06-02_09-10-58.log](https://github.com/Ryujinx/Ryujinx/files/11630972/Ryujinx_1.1.855_2023-06-02_09-10-58.log)

**Comment by AcK77** [comment]
How is that related to the OP?
You can come to our discord server if you need support. Thanks.
