### ISSUE TITLE
[Bug] Ryujinx Crashes When Switching to Another Ability in TotK

### ISSUE THREAD

**Issue by Sponge-bink** [Ryujinx/Ryujinx#5175]
### Description of the issue

When playing The Legend of Zelda: Tears of the Kingdom, switching to another ability from the Right-hand Ability menu sometimes crashes Ryujinx. 

Also, the background for this menu, and other menus like switching between bows, weapons and items, should look like this normally:

![ryujinx_capture_2023-05-31_19-54-48](https://github.com/Ryujinx/Ryujinx/assets/33798984/485fea82-de8e-4658-b9d2-e62892a32ca1)
![ryujinx_capture_2023-05-31_19-43-17](https://github.com/Ryujinx/Ryujinx/assets/33798984/5d855024-b481-4037-b60a-b70351d9d473)

But instead, after the first switch, it sometimes becomes like this: 

![ryujinx_capture_2023-05-31_19-54-39](https://github.com/Ryujinx/Ryujinx/assets/33798984/263c55c7-c2b5-4478-a2bd-b3554569649a)
![ryujinx_capture_2023-05-31_19-51-27](https://github.com/Ryujinx/Ryujinx/assets/33798984/a38e25e9-87c4-48c0-8a08-446a62edfeb0)

### Reproduction steps

Wherever you are in the game, switch to another ability (for crash) or weapon (for black background).

### Log file

[Ryujinx_1.1.840_2023-05-31_19-02-14.log](https://github.com/Ryujinx/Ryujinx/files/11612746/Ryujinx_1.1.840_2023-05-31_19-02-14.log)

### OS

macOS 12.6.6

### Ryujinx version

1.1.840

### Game version

1.1.1

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16 GB

### List of applied mods

DynamicFPS_totk

**Comment by riperiperi** [comment]
The black background happens because of the dynamic fps mod. I'm not sure what could cause the crash, though it could be related.

**Comment by systox** [comment]
yeah, on pc at least, the dfps mods are causing crashes if a conservative frame limit or vsync are enabled. Issue not present on yuzu apparently.

**Comment by riperiperi** [comment]
Yuzu ignores invalid memory access for some reason. That will crash on console, so it's likely up to the mod maker to fix it.
