### ISSUE TITLE
[Bug] i'm unable to manually increase the memory mapping

### ISSUE THREAD

**Issue by Radical4ever** [Ryujinx/Ryujinx#5182]
### Description of the issue

hi, im unable to install pkexec on the os i use, nor i know how to manually increase the memory mapping
![Captura desde 2023-05-30 19-50-03](https://github.com/Ryujinx/Ryujinx/assets/83252104/4383a2ab-87b8-4b20-933c-f9c7eac6583e)

### Reproduction steps

-open ryujinx
-messaje just drops

### Log file

[Ryujinx_1.1.844_2023-05-31_14-57-00.log](https://github.com/Ryujinx/Ryujinx/files/11617512/Ryujinx_1.1.844_2023-05-31_14-57-00.log)

### OS

Fedora 38

### Ryujinx version

1.1.844 (Flathub)

### CPU

intel i5-10500H

### GPU

Nvidia GTX 1050 (Max-Q Design)

### RAM

8gb

### Additional context?

is it something related to flatpak or something i should mod on the application folder of ryujinx?

**Comment by Radical4ever** [comment]
already fixed it myself using the next command ` sudo sysctl -w vm.max_map_count=53000` (or the value in the message)

**Comment by B0pol** [comment]
> already fixed it myself using the next command ` sudo sysctl -w vm.max_map_count=53000` (or the value in the message)

This will only last until you reboot. To make it permanent, you have to edit `/etc/sysctl.conf`, put `vm.max_map_count=524288` and run `sudo sysctl -p`
