### ISSUE TITLE
[Bug] Colors are all wrong in persona 4 golden 

### ISSUE THREAD

**Issue by Dexsueko** [Ryujinx/Ryujinx#5193]
### Description of the issue

The game looks like it has a colorblind filter on 
<img width="1440" alt="Screenshot 2023-06-01 at 3 28 15 PM" src="https://github.com/Ryujinx/Ryujinx/assets/121522695/b8633ace-2b3c-4d83-bf0e-8de8904d72e4">

### Reproduction steps

Just launching the game is enough

### Log file

[Ryujinx_1.1.855_2023-06-01_15-20-06.log](https://github.com/Ryujinx/Ryujinx/files/11629332/Ryujinx_1.1.855_2023-06-01_15-20-06.log)

### OS

Mac os ventura 13.4

### Ryujinx version

1.1.855

### CPU

m2

### GPU

m2

### RAM

8

### List of applied mods

N/A

**Comment by gdkchan** [comment]
<img width="1392" alt="Captura de Tela 2023-06-02 às 15 40 33" src="https://github.com/Ryujinx/Ryujinx/assets/5624669/ba2a6308-33f7-4f30-9326-96f412e40503">
Can't reproduce on m1 macbook air with default settings. I will try with your settings.

**Comment by gdkchan** [comment]
The issue is caused by the FXAA (or SMAA) filter and is not macOS specific. Investigating...
