### ISSUE TITLE
[Bug]The header key is incorrect or missing and therefore the NCA header content type check has failed

### ISSUE THREAD

**Issue by JudinScutin** [Ryujinx/Ryujinx#5196]
### Description of the issue

I´m having a hard time with the ryujinx trying to recognize my game list, first got this issue with zelda awakening, ryujinx couldn´t read it anymore and won´t be able to start the game, now it´s turning into other games, they just get the "unknown" status

### Reproduction steps

simply start ryujinx and it´s there

### Log file

[Ryujinx_1.1.855_2023-06-01_22-09-43.log](https://github.com/Ryujinx/Ryujinx/files/11630991/Ryujinx_1.1.855_2023-06-01_22-09-43.log)

### OS

Windows 10

### Ryujinx version

1.1.855

### Game version

any version

### CPU

Ryzen 3 2200G

### GPU

NVIDIA GTX 1060 6gb

### RAM

16

**Comment by AcK77** [comment]
Dump latest keys and redump your game from your switch. Everything should work as expected after that.
You can come to our discord server if you need support. Thanks.

**Comment by JudinScutin** [comment]
Do you mean just renew the Keys in the ryujinx system folder??

***@***.***

De: ***@***.***>
Enviado:quinta-feira, 1 de junho de 2023 22:32
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [Ryujinx/Ryujinx] [Bug]The header key is incorrect or missing and therefore the NCA header content type check has failed (Issue #5196)


Dump latest keys and redump your game from your switch. Everything should work as expected after that.
You can come to our discord server if you need support. Thanks.

**Comment by AcK77** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/Keys
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-how-can-i-dump-my-firmwaregameskeys
https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#initial-setup---placement-of-prodkeys
