### ISSUE TITLE
[Bug] Ryujinx 1.1.861 & 1.1.862 Fire Emblem: Three Houses

### ISSUE THREAD

**Issue by Drangueforde** [Ryujinx/Ryujinx#5217]
### Description of the issue

I've encountered an issue after the most recent update released that cause the textures in the background to strobe from normal to darkened repeatedly. The character sprite on screen and to UI menu is unaffected. The textures flicker in a strobing manner and the issue appears to persist even while exploring the monastery. They also occur on the battle maps, but limited to certain areas only like cloud shadows, special tiles, and some areas in the background. This issue was not present in 1.1.860, so I grabbed that version to test and I could confirm the issue was completely absent when running the game in that version of Ryujinx.

![Ryujinx_1mTQCIKFMR](https://github.com/Ryujinx/Ryujinx/assets/135484457/8e4811f5-28e9-4898-ace9-2a20355b8e89)

### Reproduction steps

I turned on Ryujinx and noticed an update was available, updated it. Restarted Ryujinx. Started it back up, resumed my save file from earlier and immediately noticed the issue. No settings were changed from how they were in 1.1.860.

### Log file

[Ryujinx_1.1.861_2023-06-03_22-43-24.log](https://github.com/Ryujinx/Ryujinx/files/11644649/Ryujinx_1.1.861_2023-06-03_22-43-24.log)
[Ryujinx_1.1.861_2023-06-03_22-24-04.log](https://github.com/Ryujinx/Ryujinx/files/11644650/Ryujinx_1.1.861_2023-06-03_22-24-04.log)
[Ryujinx_1.1.861_2023-06-03_22-37-15.log](https://github.com/Ryujinx/Ryujinx/files/11644651/Ryujinx_1.1.861_2023-06-03_22-37-15.log)

### OS

Windows 11

### Ryujinx version

1.1.861

### Game version

1.2.0

### CPU

AMD Ryzen 9 7950X

### GPU

Intel Arc A770

### RAM

32GB

### List of applied mods

[Same-Sex_v1.2.0.zip](https://github.com/Ryujinx/Ryujinx/files/11644657/Same-Sex_v1.2.0.zip)
[FireEmblemThreeHouses-60FPS-1.2.0.zip](https://github.com/Ryujinx/Ryujinx/files/11644658/FireEmblemThreeHouses-60FPS-1.2.0.zip)

### Additional context?

Issue is still present in 1.1.865, last stable version is 1.1.860.

**Comment by Drangueforde** [comment]
Sorry, 32 GB of RAM, not 16; got mixed up and thought you were asking about the GPU but realized that was redundant since the type of GPU would tell you that.

**Comment by Drangueforde** [comment]
I closed this by accident, my apologies.

**Comment by Foul-Tarnished** [comment]
I hope #5223 will get merged soon 🙏
