### ISSUE TITLE
[Bug] Hypervisor not working with BotW on MacBook Pro

### ISSUE THREAD

**Issue by blackxfiied** [Ryujinx/Ryujinx#5219]
### Description of the issue

Can only use JIT with BotW, no hypervisor for some reason

### Reproduction steps

Run Zelda with Hypervisor enabled

### Log file

[Ryujinx_1.1.862_2023-06-04_22-47-48.log](https://github.com/Ryujinx/Ryujinx/files/11645945/Ryujinx_1.1.862_2023-06-04_22-47-48.log)

### OS

macOS

### Ryujinx version

1.1.862, 1.1.0-macos1

### Game version

1.6.0

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

**Comment by kevincrans** [comment]
That is already under known issues here: https://blog.ryujinx.org/the-impossible-port-macos/
But good that it has a place here too now.
Other games that do not work are 32-bit titles, I don't think this is one, but please tell me if it is.

**Comment by gdkchan** [comment]
32-bit games should work fine with the JIT. If you found a 32-bit game that doesn't work, you should file an issue here or report on the game compat entry for the game.

**Comment by livni** [comment]
I can confirm this still doesn't work with 1.1.891 - see #5309
