### ISSUE TITLE
[Feature Request] Shader recompilation

### ISSUE THREAD

**Issue by paulober** [Ryujinx/Ryujinx#5221]
### Overview

Currently Ryujinx compiles the shaders on the fly during gameplay as it needs them and then stores them in a cache. The compilation causes stutters which do not happen on the Switch because the games contain pre-compiled shaders included.
Would it be possible to have a tool in Ryujinx which does all the shader compilation for the currently platform it would normally do during the gameplay, all at once?

### Smaller details

...

### Nature of request

So I would run the pre/re-compilation for some hours before I launch the game but then it can use a custom precompiled shader cache for the current platform.

### Why would this feature be useful?

No stutters while playing caused by shader compilation.

**Comment by MutantAura** [comment]
It is impossible to know where and in what format games will store the relevant information for shader compilation. Not to mention the relevant pipeline state. All of this info is only available at runtime.

**Comment by paulober** [comment]
@MutantAura Ok, so even I want to do it my self for only one game like Zelda Botw or Totk it would be very very hard to do?

**Comment by CrusadingNinja** [comment]
> @MutantAura Ok, so even I want to do it my self for only one game like Zelda Botw or Totk it would be very very hard to do?

I don't think you understand. There is no concept of any "pre-compiled shader cache" on the switch. The game will send the switch GPU commands in the low level maxwell shader binary which the GPU can directly understand and execute upon based on what the game requires at the time. The only way to intercept these shader binary commands so Ryujinx can translate them is at runtime like MutantAura explained.

**Comment by gdkchan** [comment]
You could do it for a specific game, if you can extract the shaders on said game. It would still be missing the pipeline state though, which Vulkan requires to create pipelines. One way around that would be using the new Vulkan extension that allow shaders to be created and bound without needing pipelines, but even then there's still some specialization state that we need to generate shader variants, and that's only know at runtime. In any case, something that requires work on a per-game basis is not really suitable for implementing on a emulator.
