### ISSUE TITLE
[Bug] Alphabet keyboard applet not working as intended 

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#5233]
### Description of the issue

alphabet mode on the keyboard applet doesn't accept number or spaces, this is most noticeable on pokemon

ryujinx:
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/56649bb5-199d-4577-9356-6539c1c30a2f)
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/d933ec61-ecc8-4c15-b1f0-fa0c0318535d)

Switch:
![2023060504070000-50E2A11CE4BDDC72EF99DF78315D4938](https://github.com/Ryujinx/Ryujinx/assets/100526773/9ce8d8d8-240f-48b6-b422-9b1f356fa777)

### Reproduction steps

try to nickname a pokemon

pokemon sword save: 
[000000000000004a.zip](https://github.com/Ryujinx/Ryujinx/files/11653012/000000000000004a.zip)

### Log file

N/A

### OS

Arch Liinux

### Ryujinx version

1.1.866

### Game version

1.3.1

### CPU

AMD Ryzen 7900X3D

### GPU

AMD RX 6600 XT

### RAM

64GB

**Comment by IsaacMarovitz** [comment]
Is this how it's meant to work in every switch game or just Pokemon? Also does the game actually let you Press Ok with numbers in the string? What about symbol like # + etc since I see them on the Switch's UI.

**Comment by piplup55** [comment]
> Is this how it's meant to work in every switch game or just Pokemon? Also does the game actually let you Press Ok with numbers in the string? What about symbol like # + etc since I see them on the Switch's UI.

![2023060516460500-B6CE40797459B0890BF7CEF68A4CE587](https://github.com/Ryujinx/Ryujinx/assets/100526773/783bf322-a00f-43e6-9004-804ef0bec6a0)
![2023060516435900-B6CE40797459B0890BF7CEF68A4CE587](https://github.com/Ryujinx/Ryujinx/assets/100526773/00348d23-a8c8-4331-96df-34806796b1a4)
![2023060516390100-B6CE40797459B0890BF7CEF68A4CE587](https://github.com/Ryujinx/Ryujinx/assets/100526773/42d55cde-0134-4c03-8585-d7922518786b)
