### ISSUE TITLE
[Bug] Graphical regression in Splatoon 3 on version 1.1.741 and onwards

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [Ryujinx/Ryujinx#5239]
### Description of the issue

Lighting in some scenes has been broken since version 1.1.741 of Ryujinx and onwards.
1.1.740 works, all versions after have the issue.
![image](https://github.com/Ryujinx/Ryujinx/assets/33284629/53226fab-a917-4020-83c6-6b90863ea7b7)

### Reproduction steps

Enter customization menu or view match EOR sequence.

### Log file

[Ryujinx_1.1.869_2023-06-05_18-04-34.log](https://github.com/Ryujinx/Ryujinx/files/11654973/Ryujinx_1.1.869_2023-06-05_18-04-34.log)

### OS

Windows 10

### Ryujinx version

1.1.869

### Game version

4.0.1

### CPU

AMD Ryzen 9 5900X

### GPU

NVIDIA RTX 3080

### RAM

32GB

**Comment by CosmicDreamsOfCode** [comment]
I looked a bit into this with RenderDoc and the culprit seems to be one of the constant buffers for the fragment shaders 
![image](https://github.com/Ryujinx/Ryujinx/assets/33284629/6b86d75a-ebf1-410b-b3d1-7fecf26eb1f3)
on 1.1.741 and afterwards some values are just 0s that were actually set to things before
![image](https://github.com/Ryujinx/Ryujinx/assets/33284629/42d21666-c942-4879-8f7b-f52a7f4c329f)

**Comment by gdkchan** [comment]
Just for reference, that versions corresponds to PR #4711.

**Comment by CosmicDreamsOfCode** [comment]
Unsure if this is related to the nature of the PR or if a newer ryujinx version changed something but all the values from before were populated with something different when i was checking something just now, resulting in something quite a bit worse than i initially observed 
![image](https://github.com/Ryujinx/Ryujinx/assets/33284629/9e936429-fdef-4dcc-acbe-e391052ce42c)

**Comment by CosmicDreamsOfCode** [comment]
This seems to possibly be fixed by either game version 8.0.0 or latest Ryujinx updates, not sure.

**Comment by gdkchan** [comment]
It was fixed by #6794.

**Comment by CosmicDreamsOfCode** [comment]
Gotcha.
