### ISSUE TITLE
SD Cache Files

### ISSUE THREAD

**Issue by Mramor0Italian** [Ryujinx/Ryujinx#5240]
### Description of the issue

I need to put in the game SD Cache Files. In these folders are maps for Just Dance 2023

### Reproduction steps

-

### Log file

-

### OS

Windows 11

### Ryujinx version

1.1.869

### Game version

1.0.0

### CPU

i3 12100f

### GPU

NVIDIA RTX 2060 Super

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
Thanks.
