### ISSUE TITLE
[Bug] TOTK Vertex Explosion on Link's Character Model

### ISSUE THREAD

**Issue by Luke44565** [Ryujinx/Ryujinx#5246]
### Description of the issue

The Legend of Zelda: Tears of the Kingdom
Any time Link is on the screen his model is significantly messed up. One of his legs is out of position and there are multiple vertex explosions.
<img width="1280" alt="Screenshot 2023-06-05 at 9 38 15 PM" src="https://github.com/Ryujinx/Ryujinx/assets/44324377/0edf02d1-9ac9-45c0-8ed0-f4de084e4ebe">

### Reproduction steps

Get to any point where Link is on the screen

### Log file

[Ryujinx_ 1.1.0-macos1_2023-06-05_21-43-44.log](https://github.com/Ryujinx/Ryujinx/files/11659058/Ryujinx_.1.1.0-macos1_2023-06-05_21-43-44.log)

### OS

MacOS 13.3.1 (Ventura)

### Ryujinx version

1.1.0-macos1

### Game version

1.1.2

### CPU

i7-9750H

### GPU

Radeon Pro 555X (4GB VRAM)

### RAM

16GB

### List of applied mods

none

### Additional context?

Please let me know if there is any additional testing I should do, or if I can help contribute to the solution. I have some C/C++ coding experience and am wiling to help.

**Comment by AcK77** [comment]
You can use `macos_universal` build from https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.869 that’s should fix the vertex explosion issue. Thanks.
