### ISSUE TITLE
[Bug] Etrian Odyssey 3 HD mouse click out of position

### ISSUE THREAD

**Issue by dantezero0403** [Ryujinx/Ryujinx#5254]
### Description of the issue

When trying to draw a map by clicking the screen with the mouse, the drawing position shifts

https://github.com/Ryujinx/Ryujinx/assets/133920073/2101ff5d-c94b-4948-b219-fa020f27891c

### Reproduction steps

The position is shifted when drawing the map in the dungeon

### Log file

[Ryujinx_1.1.869_2023-06-07_07-08-45.log](https://github.com/Ryujinx/Ryujinx/files/11669656/Ryujinx_1.1.869_2023-06-07_07-08-45.log)

### OS

Win11

### Ryujinx version

1.1.869

### Game version

1.0.2

### CPU

AMD Ryzen™ 9 6900HX

### GPU

AMD Radeon™ 680M

### RAM

24312

### List of applied mods

no

**Comment by gdkchan** [comment]
You should not use touch in docked mode since that's impossible on an actual Switch, some games assume handheld resolution and touch doesn't work properly if they are not in handheld mode. This is probably not an emulator issue.

**Comment by dantezero0403** [comment]
Joycon Pair but it's the same
![image](https://github.com/Ryujinx/Ryujinx/assets/133920073/48e669c1-64b4-4718-a5f1-3b443acdce48)

**Comment by GamerzHell9137** [comment]
> Joycon Pair but it's the same ![image](https://user-images.githubusercontent.com/133920073/244009958-48e669c1-64b4-4718-a5f1-3b443acdce48.png)

What they meant with the thing they said is that you should disable docked mode if you wanna play with the mouse. 
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/11347476-5b45-45fd-b788-c9d5aaf9b7f1)

**Comment by dantezero0403** [comment]
got it！thank you
