### ISSUE TITLE
[Bug]Can´t get thru intro sequence The DioField Chronicle

### ISSUE THREAD

**Issue by JudinScutin** [Ryujinx/Ryujinx#5260]
### Description of the issue

The game starts like every other, get to introduction cutscene and when it´s about to start the game (main screen) ryujinx just shuts down, useless trying to get after this point, always end up the same way

### Reproduction steps

start game, wait till the cutscene near ending and get shut down

### Log file

[Ryujinx_1.1.869_2023-06-07_16-10-53.log](https://github.com/Ryujinx/Ryujinx/files/11681213/Ryujinx_1.1.869_2023-06-07_16-10-53.log)

### OS

Windows 10

### Ryujinx version

1.1.856

### Game version

1.1.0

### CPU

Ryzen 3 2200G

### GPU

NVIDIA GTX 1060 6gb

### RAM

16

**Comment by OldManKain** [comment]
Bad Dump Re-Dump your game.
```ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!```
