### ISSUE TITLE
[Bug]Animal Crossing autosave lag

### ISSUE THREAD

**Issue by fnsmake** [Ryujinx/Ryujinx#5263]
### Description of the issue

<img width="1798" alt="截屏2023-06-07 18 36 57" src="https://github.com/Ryujinx/Ryujinx/assets/82305994/345cf531-7894-45ac-8134-7b041e37fc36">

### Reproduction steps

just play

### Log file

not have

### OS

macos 13.3

### Ryujinx version

1.1.869

### Game version

2.0.6

### CPU

m1 pro

**Comment by AcK77** [comment]
`not have` it will be hard to help you without more informations.

**Comment by fnsmake** [comment]
> `not have`如果没有更多信息，将很难为您提供帮助。

[Ryujinx_1.1.881_2023-06-10_13-54-09.log](https://github.com/Ryujinx/Ryujinx/files/11711709/Ryujinx_1.1.881_2023-06-10_13-54-09.log)
[Ryujinx_1.1.881_2023-06-10_14-04-45.log](https://github.com/Ryujinx/Ryujinx/files/11711710/Ryujinx_1.1.881_2023-06-10_14-04-45.log)
[Ryujinx_1.1.881_2023-06-10_14-12-35.log](https://github.com/Ryujinx/Ryujinx/files/11711711/Ryujinx_1.1.881_2023-06-10_14-12-35.log)
i add log file. please check
