### ISSUE TITLE
[Bug] Improper filename check?

### ISSUE THREAD

**Issue by pubct** [Ryujinx/Ryujinx#5273]
### Description of the issue

In `/Roaming/Ryujinx/sdcard/atmosphere/contents`, let me use an imaginary `ApplicationId`, say `001a0011`.

When,
`01a0011` (remove beginning),
`001a001` (remove end),
`e001a0011` (add beginning),
the mod doesn't load. Which are correctly what happened, as they don't match..

When `001a0011e` (add end) however, the mod loads. Which I think **shouldn't** happen.

### Reproduction steps

1. Right click game
2. Select `Open Atmosphere Mod Directory`
3. Throw in any mods
4. Go back one folder level
5. Change the folder name
6. Launch game

### Log file

 Not needed I believe

### OS

Windows 10

### Ryujinx version

1.1.881

**Comment by AcK77** [comment]
Well, the folder you put in `content` should be the `ApplicationId` (and only that) which is unique by game, so it make sense if the mods isn’t detected  by Ryujinx as you have changed it by add/remove a char at the beginning or the end of the folder name.
Or I have misunderstood what you explained, in that case, add some examples please.

**Comment by pubct** [comment]
I'm not at my PC at the moment. So, let me use an imaginary `ApplicationId`. Say `001a0011`.

When,
`01a0011` (remove beginning),
`001a001` (remove end),
`e001a0011` (add beginning),
the mod doesn't load. Which is correctly what should happen, as they don't match..

When `001a0011e` (add end) however, the mod loads. Which I think **shouldn't** happen.

**Comment by TSRBerry** [comment]
This would have been nice to include in the initial description as I wasn't sure what you meant until you added that.

**Comment by pubct** [comment]
Yeah. My bad. Will remember this for next time.
