### ISSUE TITLE
[Regression] Audio peaking and crakling with SDL2

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#5275]
### Description of the issue

After https://github.com/Ryujinx/Ryujinx/pull/4908 audio in a lot of games (with SDL2 set as the audio backend) crackles.
Really noticable on SMT V with certain attacks. Can't remember any other right now but i've seen it in 4-5 games so far.

!!! AUDIO WARNING, LOWER THE VOLUME !!!

1.1.797

https://github.com/Ryujinx/Ryujinx/assets/2002038/1e31b510-6365-406a-b52e-1e9faad66ba3

Everything before 797

https://github.com/Ryujinx/Ryujinx/assets/2002038/232ad57d-230d-4394-b72d-a54938af1f2e

### Reproduction steps

Just do special attacks in SMT V

### Log file

None

### OS

Windows 10

### Ryujinx version

1.1.797

### Game version

1.3.0

### CPU

Ryzen 3600

### GPU

RTX 3060 Ti

### RAM

16 GB

**Comment by AcK77** [comment]
A log and more informations about your sound setup could be nice too. Thanks.

**Comment by GamerzHell9137** [comment]
> A log and more informations about your sound setup could be nice too. Thanks.

There's nothing really in the logs that shows anything about the issue. As for the sound setup, its just the motherboard audio jack that's being used. Its an Realtek ALC1220 set at 2channel, 16 bit, 48000 Hz.

**Comment by GamerzHell9137** [comment]
Here's how Jackbox 6 sounds like

https://github.com/Ryujinx/Ryujinx/assets/2002038/29d8e4e5-65ae-4d6d-9dc6-a417961e2da4

[Ryujinx_1.1.1020_2023-09-21_10-47-35.log](https://github.com/Ryujinx/Ryujinx/files/12682516/Ryujinx_1.1.1020_2023-09-21_10-47-35.log)

Other audio backends are fine.
