### ISSUE TITLE
[Bug] BoTW keeps crashing on vulkan backend

### ISSUE THREAD

**Issue by Macavitycode** [Ryujinx/Ryujinx#5286]
### Description of the issue

After setting up, I tried running BoTW with OpenGL and it ran at 30 FPS (memory manager mode: Host Unchecked initially, then changed it to Host). This worked but was slow.

![image](https://github.com/Ryujinx/Ryujinx/assets/50370816/304f99d2-7028-4d83-95a4-8a5e510b2e58)

I tried getting it to work with Vulkan after that, installed it and set the options as default and tried launching it, got "ErrorDeviceLost". I tried searching online, found a suggestion to change configuration of Vulkan to "Layers fully configured by application". Did that, with the following settings

![image](https://github.com/Ryujinx/Ryujinx/assets/50370816/6596e48b-d76c-45f1-97a3-ea1f56b88ce5)

Each time it gets to the menu, allows me to select a save and then crashes out. I'm really not sure where the problem is, because Vulkan's test application (cube) runs fine. I'm pretty lost and very new to this emulator, please let me know what I can try.
 
I've broken the log file into two because it was too large.

### Reproduction steps

- Installed Ryujinx, set up keys and firmware 16.0.3
- Got BoTW NSP and set it up in folder
- got vulkan from [[here](https://vulkan.lunarg.com/)](https://vulkan.lunarg.com/)
- Installed vulkan
- Setup input profiles
- launched BoTW

### Log file

[log1.log](https://github.com/Ryujinx/Ryujinx/files/11714698/log1.log)

[log2.log](https://github.com/Ryujinx/Ryujinx/files/11714697/log2.log)

### OS

Windows 10

### Ryujinx version

16.0.3

### Game version

1.0.0

### CPU

AMD Ryzen 7 5800HS with Radeon Graphics

### GPU

NVIDIA RTX 3060

### RAM

16GB

### List of applied mods

None

### Additional context?

None

**Comment by piplup55** [comment]
update your game and update both your amd and nvidia drivers
future support requests should be done though the [discord](https://discord.gg/ryujinx)
