### ISSUE TITLE
[Feature Request] allow simultaneous kb/m+gamepad input

### ISSUE THREAD

**Issue by soredake** [Ryujinx/Ryujinx#5287]
### Overview

It would be nice if i can do simultaneous kb/m+gamepad input in ryujinx.

### Smaller details

There are games where it would be useful to use keyboard and gamepad in rotation.

### Nature of request

Nice to have.

### Why would this feature be useful?

For playing visual novels for example, i start game and load save with gamepad and then will use keyboard as i need only few buttons.

**Comment by MutantAura** [comment]
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1986
