### ISSUE TITLE
Unable to install newer firmware

### ISSUE THREAD

**Issue by vampiregoat699** [Ryujinx/Ryujinx#5296]
### Description of the issue

I downloaded the firmware 16.0.3 and click install from zip, upon clicking on the firmware zip I always get the error 
Ryujinx was unable to parse the provided firmware due to outdated keys even though I also have the newest keys. Seems no matter what firmware or keys I try it throws same error over and over and is very annoying.

### Reproduction steps

See above trying to install firmware and keys

### Log file

[Ryujinx_1.1.886_2023-06-12_08-04-08.log](https://github.com/Ryujinx/Ryujinx/files/11725108/Ryujinx_1.1.886_2023-06-12_08-04-08.log)
[Ryujinx_1.1.886_2023-06-12_08-05-43.log](https://github.com/Ryujinx/Ryujinx/files/11725110/Ryujinx_1.1.886_2023-06-12_08-05-43.log)
[Ryujinx_1.1.886_2023-06-12_08-10-36.log](https://github.com/Ryujinx/Ryujinx/files/11725111/Ryujinx_1.1.886_2023-06-12_08-10-36.log)

### OS

Win 10

### Ryujinx version

1.1.886

### CPU

I7-9600

### GPU

Nvidia RTX 3070

### RAM

32 gig

**Comment by AcK77** [comment]
Keys are outdated. You have to dump them from the same Firmware on your switch to be able to install the firmware.
Next time please come to our discord server for support instead of opening an issue here. Thanks.
