### ISSUE TITLE
[Bug] Pokemon Scarlet/Violet/Sword/Shield shader cache slowly increasing

### ISSUE THREAD

**Issue by FireGeneral** [Ryujinx/Ryujinx#5301]
### Description of the issue

I think this is a bug, basically, the more you play the game, the bigger the shader cache becomes, however, it's not in a natural way.
For example, suppose a save inside "computer A" which has say 100 hours worth of gameplay, whenever the game starts, Ryujinx loads around 10000 shaders.
If you take that save file and put it inside "computer B" which has never start the game before, Ryujinx only needs to load around 7000 shaders.
Both save files are the same, everything is the exact same in-game, can confirm nothing has changed inside both computers.
I also noticed everytime I close the game, there's a chance of increasing shader cache with around 10-30 shaders, presumably the reason behind this phenomenon.
Still, I think this is weird and not intented.

### Reproduction steps

Simply continue playing the game normally, saving and quitting.

### Log file

00:00:00.031 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.035 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.035 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.035 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.036 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.036 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.036 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x25A2
00:00:00.037 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.037 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.037 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.039 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.044 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.044 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.044 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.044 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.045 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.045 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.045 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.045 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.045 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.045 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.045 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.045 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.046 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.046 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.048 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.885
00:00:00.051 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.051 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700H ; 20 logical
00:00:00.052 |N| Application Print: RAM: Total 16088 MiB ; Available 9897 MiB
00:00:00.054 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.054 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.090 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)

### OS

Windows10/11

### Ryujinx version

1.1.885

### Game version

SS v1.3.2 / SV v1.3.0

### GPU

NVIDIA RTX3050/3050Ti

### RAM

16GB

### List of applied mods

None

**Comment by Foul-Tarnished** [comment]
Moving the camera slightly differently in the open world can make the game render more stuff and cache more shaders

**Comment by FireGeneral** [comment]
> Moving the camera slightly differently in the open world can make the game render more stuff and cache more shaders
> 
> But I guess if you just run the game until in the overworld and close it, shader cache should be the same. Well, unless there's some randomness in the pokemon spawns, and not the same ones spawns near you and get shader cached, idk

I checked multiple times, same thing can happen even in-doors.
Take pokemon sword for example, after you finish a dynamax adventure, shader cache has a chance to increase despite you're completely in-doors.
Furthermore, your explanation doesn't explain why the cache number only goes up and never goes down.
One of the reason I reported this as a bug is because for some reason, the Ryujinx is building more and more cache without ever releasing it. (amount eventually becomes 2+ times more than the original amount)

**Comment by FireGeneral** [comment]
> The emulator adds shaders to the disk cache so that they don’t have to compile the next time the game runs. It is not possible to know when to “release” it, the whole point of the cache is guessing that when a game uses a shader once, it will use it in the future. The number of shaders should never decrease.

But that ultimately leads to long startup time, does it not?
Also, does that mean even 2 to 3 times more than the original amount is normal?

**Comment by FireGeneral** [comment]
> Longer startup is still faster than converting the shader each time, at runtime. And you would have stutter while playing, so way worse experience.
> 
> You can just disable the shader cache in the settings if you really want to huh
> 
> **Your second pc having a smaller shader cache is normal ; shader gets cached when they are used, so using an end-game savefile won't make Ryu generate the same big shader cache.** The only way is to replay the entirety of the game. Loading every zones, loading every pokemon, loading every animation, effects, etc.

To be honest, I do not know whether the shader is getting duplicated, is there a way for me to check?

**Comment by Foul-Tarnished** [comment]
Not really, and it should never happen anyway.
Only scenario it could happen is if a game update modified shaders, you would get old and new ones in the cache.

There's really no issue here, as I said the shader cache size being different between your pc is normal, as you just took the savefile and loaded ingame, not replayed the game.

you should close this
