### ISSUE TITLE
[Bug] Various Games will not run on the M2 Ultra Mac Studio

### ISSUE THREAD

**Issue by cciedc80** [Ryujinx/Ryujinx#5310]
### Description of the issue

Will not run on the M2 Ultra Mac studio

### Reproduction steps

Launch on M2 Ultra Mac studio

### Log file

00:00:00.045 |I| Configuration LogValueChange: ResScale set to: 3
00:00:00.046 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.046 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.047 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.047 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.047 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.048 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xD0303EF
00:00:00.048 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.048 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.048 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.049 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.053 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.053 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.053 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.053 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.053 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.054 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.054 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.054 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.054 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.054 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.054 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.057 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.893
00:00:00.060 |N| Application Print: Operating System: Darwin 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:41:21 PDT 2023; root:xnu-8796.121.2~3/RELEASE_ARM64_T6020 (Arm64)
00:00:00.060 |N| Application Print: CPU: Apple M2 Ultra� ; 24 logical
00:00:00.061 |N| Application Print: RAM: Total 196608 MiB ; Available 173914 MiB
00:00:00.062 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.062 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:05.565 |E| .NET ThreadPool Worker [mvk-info] MoltenVK version 1.2.0, supporting Vulkan version 1.2.231.
00:00:05.566 |E| .NET ThreadPool Worker 	The following 83 Vulkan extensions are supported:
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_16bit_storage v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_8bit_storage v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_bind_memory2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_buffer_device_address v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_create_renderpass2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_dedicated_allocation v3
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_depth_stencil_resolve v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_descriptor_update_template v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_device_group v4
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_device_group_creation v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_driver_properties v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_dynamic_rendering v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_external_fence v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_external_fence_capabilities v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_external_memory v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_external_memory_capabilities v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_external_semaphore v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_external_semaphore_capabilities v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_fragment_shader_barycentric v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_get_memory_requirements2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_get_physical_device_properties2 v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_get_surface_capabilities2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_imageless_framebuffer v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_image_format_list v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_maintenance1 v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_maintenance2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_maintenance3 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_multiview v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_portability_subset v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_push_descriptor v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_relaxed_block_layout v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_sampler_mirror_clamp_to_edge v3
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_sampler_ycbcr_conversion v14
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_separate_depth_stencil_layouts v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_shader_draw_parameters v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_shader_float_controls v4
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_shader_float16_int8 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_shader_subgroup_extended_types v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_spirv_1_4 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_storage_buffer_storage_class v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_surface v25
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_swapchain v70
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_swapchain_mutable_format v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_timeline_semaphore v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_uniform_buffer_standard_layout v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_KHR_variable_pointers v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_buffer_device_address v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_debug_marker v4
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_debug_report v10
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_debug_utils v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_descriptor_indexing v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_fragment_shader_interlock v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_hdr_metadata v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_host_query_reset v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_image_robustness v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_inline_uniform_block v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_memory_budget v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_metal_objects v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_metal_surface v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_post_depth_coverage v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_private_data v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_robustness2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_sample_locations v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_scalar_block_layout v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_separate_stencil_usage v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_shader_stencil_export v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_shader_viewport_index_layer v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_subgroup_size_control v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_swapchain_colorspace v4
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_texel_buffer_alignment v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_texture_compression_astc_hdr v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_EXT_vertex_attribute_divisor v3
00:00:05.566 |E| .NET ThreadPool Worker 		VK_AMD_gpu_shader_half_float v2
00:00:05.566 |E| .NET ThreadPool Worker 		VK_AMD_negative_viewport_height v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_AMD_shader_image_load_store_lod v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_AMD_shader_trinary_minmax v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_IMG_format_pvrtc v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_INTEL_shader_integer_functions2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_GOOGLE_display_timing v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_MVK_macos_surface v3
00:00:05.566 |E| .NET ThreadPool Worker 		VK_MVK_moltenvk v36
00:00:05.566 |E| .NET ThreadPool Worker 		VK_NV_fragment_shader_barycentric v1
00:00:05.566 |E| .NET ThreadPool Worker 		VK_NV_glsl_shader v1
00:00:05.566 |E| .NET ThreadPool Worker [mvk-info] GPU device:
00:00:05.566 |E| .NET ThreadPool Worker 		model: Apple M2 Ultra
00:00:05.566 |E| .NET ThreadPool Worker 		type: Integrated
00:00:05.566 |E| .NET ThreadPool Worker 		vendorID: 0x106b
00:00:05.566 |E| .NET ThreadPool Worker 		deviceID: 0xd0303ef
00:00:05.566 |E| .NET ThreadPool Worker 		pipelineCacheUUID: 260BAD42-0D03-03EF-0000-000000000000
00:00:05.566 |E| .NET ThreadPool Worker 	supports the following Metal Versions, GPU's and Feature Sets:
00:00:05.566 |E| .NET ThreadPool Worker 		Metal Shading Language 2.4
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 7
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 6
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 5
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 4
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 3
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 2
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Apple 1
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Mac 2
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Mac 1
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Common 3
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Common 2
00:00:05.566 |E| .NET ThreadPool Worker 		GPU Family Common 1
00:00:05.566 |E| .NET ThreadPool Worker 		macOS GPU Family 2 v1
00:00:05.566 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v4
00:00:05.566 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v3
00:00:05.566 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v2
00:00:05.566 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v1
00:00:05.566 |E| .NET ThreadPool Worker [mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 0 Vulkan extensions enabled:

### OS

MacOS 13.4

### Ryujinx version

1.1.893

### Game version

1.1.2

### RAM

192GB

### List of applied mods

None

**Comment by AcK77** [comment]
The provided log doesn’t have any error message, could you explain the issue a bit? Or reproduce the bug and then send the log file here (by drag and drop it on the textarea).
Thanks.

**Comment by cciedc80** [comment]
That is the issue when I run TOTK, my system becomes totally unresponsive. Sometimes Ryujinx crashes and the system becomes responsive other times I have to hard reboot. This is not consistent across games though as I just tried Link's Awakening and it works fine.

**Comment by MetrosexualGarbodor** [comment]
Does it happen if you set resolution scaling to native?

**Comment by cciedc80** [comment]
I see this a lot in the Apple Crash report but dunno if it matters:

87  Ryujinx                       	       0x1041fb8a8 DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 272

**Comment by cciedc80** [comment]
Anyone else see this issue? I am seeing it on some games but not all

**Comment by cciedc80** [comment]
[Ryujinx_1.1.900_2023-06-22_16-55-59.log](https://github.com/Ryujinx/Ryujinx/files/11840462/Ryujinx_1.1.900_2023-06-22_16-55-59.log)
[Ryujinx_1.1.900_2023-06-22_17-00-36.log](https://github.com/Ryujinx/Ryujinx/files/11840463/Ryujinx_1.1.900_2023-06-22_17-00-36.log)
 

Here are what I think are better logs.

**Comment by kevincrans** [comment]
> I see this a lot in the Apple Crash report but dunno if it matters:
> 
> 87 Ryujinx 0x1041fb8a8 DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 272

I had this too in my Ryujinx M2 crash logs, so it might be typically the issue or typically not the issue.

**Comment by cciedc80** [comment]
Apple must have really changed something between the M1 Ultra and M2 Ultra

**Comment by MutantAura** [comment]
Both of your logs have some unstable mods applied, namely the "visualfixes" mods. Can you remove them and try again.

**Comment by cciedc80** [comment]
Both mods folders are empty.

**Comment by cciedc80** [comment]
[Ryujinx_1.1.909_2023-06-24_22-06-22.log](https://github.com/Ryujinx/Ryujinx/files/11858572/Ryujinx_1.1.909_2023-06-24_22-06-22.log)

**Comment by AcK77** [comment]
UI logs isn’t really useful here, have you tried to purge shader and PTC cache?

**Comment by cciedc80** [comment]
Purged both. Still the same. Some games work and some don’t

**Comment by AcK77** [comment]
> Purged both. Still the same. Some games work and some don’t

Isn't an issue about Totk ?

**Comment by shinra-electric** [comment]
This may or may not be relevant, but there are performance bugs with games in general on the M2 Ultra. 

You can see some examples in [Andy Tizer’s video](https://youtu.be/ecl_Y6W4ins) on YouTube.

**Comment by gdkchan** [comment]
This video does show TOTK working on M2 Ultra though, while that issue says it doesn't work, which is a bit puzzling.

**Comment by cciedc80** [comment]
I just blew away the whole Ryujinx folder under Application Support. This seems to have resolved my issue.
