### ISSUE TITLE
[Bug] CPU utilization. Ryujinx use half of available cores.

### ISSUE THREAD

**Issue by alessandro893** [Ryujinx/Ryujinx#5324]
### Description of the issue

Ryujinx can't fully utilize my CPU, it loads my CPU at 20-30%, GPU at 20%. It can't utilize all CPU cores, just half, and even used half of cores not loaded at 100%. 

I also tried compiling with different pull requests:
4899 (Vulkan: Buffer Mirrors for MacOS performance)
5291 (Add an alternative backend parallel compilation queue for macOS)

I have Mac Pro 5.1, CPU - dual X5680 (12 cores, 24 threads), RAM 96gb triple channel (1333mhz), GPU - Vega64.

CPU Usage:
<img width="1920" alt="1" src="https://github.com/Ryujinx/Ryujinx/assets/4077478/e8d06ee8-22b9-48a8-8094-7669eaf002a7">

CPU Load with Geekbench (example of good CPU utilization):
<img width="1920" alt="2" src="https://github.com/Ryujinx/Ryujinx/assets/4077478/1c7e0f91-d1ec-4104-9230-46aca7ab6284">

GPU Benchmarks:
<img width="1920" alt="3" src="https://github.com/Ryujinx/Ryujinx/assets/4077478/c6bc5884-82a2-4e7e-bc16-8ab2a3b8a840">

### Reproduction steps

Start Ryujinx on Mac Pro, no matter which versions.

### Log file

[Ryujinx_1.1+889_2023-06-17_15-56-01.log](https://github.com/Ryujinx/Ryujinx/files/11778965/Ryujinx_1.1%2B889_2023-06-17_15-56-01.log)

[Ryujinx_1.1+889_2023-06-17_18-32-17.log](https://github.com/Ryujinx/Ryujinx/files/11778966/Ryujinx_1.1%2B889_2023-06-17_18-32-17.log)

### OS

MacOS Monterey 12.4

### Ryujinx version

1.1.889

### Game version

1.1.0

### CPU

Dual Xeon X5680

### GPU

Radeon Vega 64

### RAM

96GB

### List of applied mods

ChuckPatch_FSRDisable+QualityReduceFix+Shadow1024+1080p+DOF 
(tried with/without mods, no difference)

**Comment by riperiperi** [comment]
This isn’t unusual, emulation in general is very single core heavy. Workloads can’t be parellelized if they’re meant to run in sequence, for example guest CPU threads or draw calls. Not that we don’t try with the backend multithreading.

Since you’re using an x86 mac, you might have more luck using Bootcamp and running the emulator through Windows. That way, you won’t run into performance issues introduced by MoltenVK.

**Comment by MutantAura** [comment]
Closing as won't fix.
