### ISSUE TITLE
TOTK Depths is unplayable because of visual glitches. walls appear that arent there... constant visual bug [Bug]

### ISSUE THREAD

**Issue by DennisMahieu** [Ryujinx/Ryujinx#5326]
### Description of the issue

I had some shadow glitches in the game but nothing that made it unplayable. untill i reached the depths. In some of the caves i had minor visual glitches and walls that appear that arent there. But in the depths its so chaotic that the game is unplayable there. 

### Reproduction steps

It happens every time i go in the depths. Its also a glitch that is violently flashing and changing. I took a few screenshots. All at the same location (temple in the depths). I did not move or look around, you can see the game is broken there. 
I took all these screenshots within 1 minute
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 57 1" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/e83cd927-30a4-4224-a5d6-9a7c74d958cd">
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 58" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/33a540a9-18bd-4137-a4d0-e993cc44eec0">
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 29 00" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/6814c517-d7ee-47c7-9e88-1e058abfeb25">

<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 54" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/5cf3b65f-c98d-41a3-9b3f-d0d385633268">
.
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 55" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/f07635b1-7d47-43dc-b0e4-a5103cd9aaad">
 
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 56" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/6170648c-af47-4654-af75-8ddf482b82fe">
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 57" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/a84df49a-dcd3-4f1d-b699-14c9aaa6339e">

<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 14" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/d77e3dd8-e0e4-4080-9627-93f1490a31bc">
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 16" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/6fda816e-d8ad-430e-83cf-364e9982b34a">
<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 18" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/ea81981d-9fae-4c53-8ad5-42272d03e2cb">

<img width="1440" alt="Scherm­afbeelding 2023-06-17 om 23 28 13" src="https://github.com/Ryujinx/Ryujinx/assets/136632901/c50e1a39-e9ae-4e01-a68b-caa4b46e0dda">

### Log file

[Ryujinx_ 1.1.0-macos1_2023-06-17_23-23-07.log](https://github.com/Ryujinx/Ryujinx/files/11780098/Ryujinx_.1.1.0-macos1_2023-06-17_23-23-07.log)

### OS

MAC Ventura 13.4

### Ryujinx version

Ryujinx 1.1.0 macos1

### Game version

1.1.2

### CPU

M1

### GPU

M1

### RAM

16GB

### List of applied mods

1.1.2.pchtxt
main-1.1.0.pchtxt
main-1.1.1.pchtxt
main-1.1.2.pchtxt
main.npdm
subsdk9

**Comment by gdkchan** [comment]
You should use the build on https://github.com/Ryujinx/Ryujinx/pull/4899#issuecomment-1545007093 to play Tears of the Kingdom on macOS for now.
Click on "Experimental GUI (Avalonia)" and download the one that ends with "macos_universal".

**Comment by MutantAura** [comment]
As above, already fixed on latest releases.

**Comment by DennisMahieu** [comment]
Wow ok, didnt find it when I was looking around for a fix, this works, thanks a lot
