### ISSUE TITLE
[Bug]touch screen no reaction

### ISSUE THREAD

**Issue by hanasakufreu** [Ryujinx/Ryujinx#5330]
### Description of the issue

Touch the screen,nothing happened.

### Reproduction steps

I run ryujinx in my ayaneo air plus,I can input by abxy but I can't touch screen,seems my touch input didn't work……I try handheld and docked mode,nether two of this worked.I use mouse,and it didn't work either…

### Log file

00:00:00.056 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.063 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.063 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.064 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.065 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.066 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.067 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x1681
00:00:00.068 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.069 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.069 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.072 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.083 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.083 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.083 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.084 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.084 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.084 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.084 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.084 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.085 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.085 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.086 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.086 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.086 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.086 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.091 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.896
00:00:00.097 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.097 |N| Application Print: CPU: AMD Ryzen 7 6800U with Radeon Graphics ; 16 logical
00:00:00.098 |N| Application Print: RAM: Total 26383 MiB ; Available 22758 MiB
00:00:00.102 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.102 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

windows 11

### Ryujinx version

1.1.896

### CPU

AMD Ryzen 6800U

### GPU

AMD Radeon（TM） Graphics

### RAM

32gb

**Comment by MutantAura** [comment]
You will need to provide more info. Most games do not make use of the touch screen even while in handheld.

**Comment by hanasakufreu** [comment]
> You will need to provide more info. Most games do not make use of the touch screen even while in handheld.

DAIROKU：AYAKASHIMORI、君は雪間に希う、paradigm paradox.I test this three games.

**Comment by hanasakufreu** [comment]
sorry I closed it by accident,I don't use this website very often…

**Comment by MutantAura** [comment]
And you're sure that these games support touch inputs? I would check on a Switch that they do, I can't find much information about them online.

**Comment by hanasakufreu** [comment]
> And you're sure that these games support touch inputs? I would check on a Switch that they do, I can't find much information about them online.

yes I'm sure…I once played these on my switch.I just test another game in my laptop,it can touch screen (through it's need to double touch) I don't know why ayaneo can't…

**Comment by hanasakufreu** [comment]
So I tried ラディアンテイル,it can touch screen but need double click…I don't know why.(those three game actually have touch screen but somehow they didn't work in ryujinx.(maybe it's game's problem?)
