### ISSUE TITLE
[Bug]Jikkyou Powerful Pro Yakyuu (0100e9c00bf28000)

### ISSUE THREAD

**Issue by s0386** [Ryujinx/Ryujinx#5340]
### Description of the issue

Crashes after starting the game

### Reproduction steps

https://github.com/Ryujinx/Ryujinx/assets/137259483/6a9728cc-4e41-4c97-bf45-0b53cfa1e069

### Log file

00:00:00.043 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.043 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.044 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2187
00:00:00.044 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.045 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.045 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.047 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.054 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.054 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.054 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.054 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.055 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.055 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.055 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.055 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.056 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.056 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.059 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.898
00:00:00.063 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.063 |N| Application Print: CPU: Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz ; 16 logical
00:00:00.063 |N| Application Print: RAM: Total 16298 MiB ; Available 5132 MiB
00:00:00.066 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.066 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:03.747 |W| GUI.ApplicationLibraryThread Application LoadApplications: The "game_dirs" section in "Config.json" contains an invalid directory: "E:\Switch\新增資料夾\download\Sengoku Musou 5 [010089A0117D4000][v0][JP](Dumped).xci"
00:00:03.815 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.822 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.824 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.827 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.829 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.834 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.838 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.843 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.853 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.855 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.869 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.872 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.875 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.877 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.879 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.883 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.886 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.891 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.893 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.894 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.897 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.899 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.904 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:03.907 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:00.088 |I| Gpu : Backend Threading (Auto): True
00:00:00.309 |N| Application LoadApplication: Using Firmware Version: 16.0.3
00:00:00.309 |I| Application LoadApplication: Loading as XCI.
00:00:00.334 |I| ModLoader QueryContentsDir: Searching mods for Title 0100E9C00BF28000
00:00:00.335 |I| ModLoader QueryContentsDir: Searching mods for Title 0100E9C00BF28000
00:00:00.338 |I| Loader Load: Loading rtld...
00:00:00.346 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.346 |I| Loader Load: Loading main...
00:00:00.772 |I| Loader PrintRoSectionInfo: main:
    Module: D:\work\enif_full\obj\enif_nx\Release\NX64\enif_nx.nss
    SDK Libraries: SDK MW+Nintendo+NEX_MM-4_6_2
                   SDK MW+Nintendo+NEX-4_6_2-
                   SDK MW+Nintendo+NEX_RK-4_6_2
                   SDK MW+Nintendo+NEX_SS-4_6_2
                   SDK MW+Nintendo+PiaCommon-5_12_1
                   SDK MW+Nintendo+Pia-5_12_1
                   SDK MW+Nintendo+PiaLocal-5_12_1
                   SDK MW+Nintendo+PiaTransport-5_12_1
                   SDK MW+Nintendo+PiaNex-5_12_1
                   SDK MW+Nintendo+PiaSession-5_12_1
                   SDK MW+Nintendo+PiaTransport-5_12_1
                   SDK MW+Nintendo+NintendoSDK_libz-6_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_libcurl-6_4_1-Release
00:00:00.772 |I| Loader Load: Loading subsdk0...
00:00:00.830 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-6_4_1-Release
00:00:00.830 |I| Loader Load: Loading sdk...
00:00:00.927 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 6.4.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-6_4_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-6_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-6_4_1-Release
00:00:01.043 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.072 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.074 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.666 |I| Loader LoadNsos: Loading image 2 at 0x000000006e773000...
00:00:01.669 |I| Loader LoadNsos: Loading image 3 at 0x000000006ee93000...
00:00:01.676 |I| ModLoader LoadCheats: Build ids found for title 0100E9C00BF28000:
    09AA0F157B8CF44DF373510612A0452A4803B2AB000000000000000000000000
    859A3A3D296D44E86C70F2DE2BE2A8CE00000000000000000000000000000000
    E5E40DD9061CD55929FD0B970C981FEA5BCF1BE8000000000000000000000000
    EE5DCA3CEA1E21925A3A13D3CE4A3C671B18DBA5000000000000000000000000
00:00:01.679 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.729 |I| Loader Start: Application Loaded: 実況パワフルプロ野球 v1.0.4 [0100e9c00bf28000] [64-bit]
00:00:01.736 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.751 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:02.059 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1650 SUPER (Vulkan v1.3.242, Driver v536.23.0.0)
00:00:02.068 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:02.074 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.952 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.977 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.978 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.980 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:03.001 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:04.801 |E| HLE.OsThread.9 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Hid.IHidServer: 134

Guest Stack Trace:
Process: Service, PID: 86

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  86 00 00 00 00 00 00 00   SFCI···········
00000010   01 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000020   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 435
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 278
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windowns 10

### Ryujinx version

16.0.3

### Game version

1.0.4

### CPU

i7-10700F

### GPU

NVIDIA GTX 1650S

### RAM

16GB

### Additional context?

Thank you

**Comment by AcK77** [comment]
duplicated of https://github.com/Ryujinx/Ryujinx/issues/1891
