### ISSUE TITLE
[Bug] TOTK 1.0/1.1.2  crashes the Ryujinx emulator

### ISSUE THREAD

**Issue by vasile-coste** [Ryujinx/Ryujinx#5342]
### Description of the issue

Trying to run TOTK 1.0 and 1.1.2, but results in emulator completely crashes. The version 1.0 is playable with random crashes while the version 1.1.2 crashes the emulator if i try to emulate it

### Reproduction steps

Steps to reproduce first crash
- Download TOTK 
- apply update to 1.1.2
- start the game

For the v1.0 it happens randomly 

### Log file

Log for v1.1.2
![Screenshot 2023-06-22 191620](https://github.com/Ryujinx/Ryujinx/assets/17108452/a5fd764e-656d-4cb6-93b8-5e2800d55a97)

Log for v1.0
![Screenshot 2023-06-22 191134](https://github.com/Ryujinx/Ryujinx/assets/17108452/9a3986a1-662e-4c2b-ab16-1958b6e8fe6c)

### OS

Windows 11

### Ryujinx version

1.1.898

### Game version

1.1.2

### CPU

i7-9750H CPU @ 2.60GHz

### GPU

GTX 1660 Ti

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
Though it's impossible to know for certain since all your logging is disabled, your update file is likely corrupted. Dump it again from your Switch.
Next time please use discord for support queries: https://discord.gg/ryujinx
Thanks.
