### ISSUE TITLE
[Bug] Controller 2 not working.

### ISSUE THREAD

**Issue by ducky3333** [Ryujinx/Ryujinx#5348]
### Description of the issue

hi. i m using two controller.
one is Xbox controller to player 1 and i have set number two is 8bitdo.
anyway, if i connect only player2 controller , Ryujinx cannot find controller .

### Reproduction steps

connect no.1 controller.

### Log file

00:00:00.022 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.025 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.025 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.026 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.026 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.026 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.027 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2208
00:00:00.027 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.027 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.027 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.028 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.033 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.033 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.033 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.033 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.033 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.033 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.033 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.034 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.034 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.034 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.035 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.904
00:00:00.038 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.038 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i7-13700K ; 24 logical
00:00:00.038 |N| Application Print: RAM: Total 32509 MiB ; Available 21923 MiB
00:00:00.040 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.040 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.393 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.401 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.423 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:02:07.767 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:02:07.772 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:02:07.787 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:00.047 |I| Gpu : Backend Threading (Auto): True
00:00:00.248 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:00.248 |I| Application LoadApplication: Loading as NSP.
00:00:00.254 |I| Application AddAocItem: Found AddOnContent with TitleId 01006F800232712C
00:00:00.254 |I| Application AddAocItem: Found AddOnContent with TitleId 01006F800232712D
00:00:00.254 |I| Application AddAocItem: Found AddOnContent with TitleId 01006F80023273E8
00:00:00.296 |I| ModLoader QueryContentsDir: Searching mods for Title 01006F8002326000
00:00:00.296 |I| ModLoader QueryContentsDir: Searching mods for DLC 01006F800232712C
00:00:00.296 |I| ModLoader QueryContentsDir: Searching mods for DLC 01006F800232712D
00:00:00.296 |I| ModLoader QueryContentsDir: Searching mods for DLC 01006F80023273E8
00:00:00.297 |I| ModLoader QueryContentsDir: Searching mods for Title 01006F8002326000
00:00:00.297 |I| ModLoader QueryContentsDir: Searching mods for DLC 01006F800232712C
00:00:00.297 |I| ModLoader QueryContentsDir: Searching mods for DLC 01006F800232712D
00:00:00.297 |I| ModLoader QueryContentsDir: Searching mods for DLC 01006F80023273E8
00:00:00.298 |I| Loader Load: Loading rtld...
00:00:00.302 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.302 |I| Loader Load: Loading main...
00:00:00.490 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\Park\App\Rom\NX64\Product\code\Park.nss
    SDK Libraries: SDK MW+OmronSoftware+iWnn-1_9_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-10_9_8-Release
                   SDK MW+Nintendo+NintendoSDK_libz-10_9_8-Release
                   SDK MW+Nintendo+NEX-4_6_4-
                   SDK MW+Nintendo+PiaClone-5_31_0
                   SDK MW+Nintendo+52322
                   SDK MW+Nintendo+PiaCommon-5_31_0
                   SDK MW+Nintendo+Pia-5_31_0
                   SDK MW+Nintendo+PiaLan-5_31_0
                   SDK MW+Nintendo+PiaLocal-5_31_0
                   SDK MW+Nintendo+PiaSession-5_31_0
                   SDK MW+Nintendo+PiaTransport-5_31_0
                   SDK MW+Nintendo+PiaNex-5_31_0-forNEX-4_6_4
                   SDK MW+Nintendo+NEX_MM-4_6_4
                   SDK MW+Nintendo+NintendoWare_Vfx2-10_9_8-Release
                   SDK MW+Nintendo+NintendoWare_Font-10_9_8-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-10_9_8-Release
                   SDK MW+Nintendo+NintendoWare_G3d-10_9_8-Release
                   SDK MW+Nintendo+NintendoWare_Atk-9_3_1-Release
                   SDK MW+Nintendo+NEX_CO-4_6_4
                   SDK MW+Microsoft+Havok_Cloth-2019_1
                   SDK MW+Microsoft+Havok_Animation-2019_1
00:00:00.490 |I| Loader Load: Loading subsdk0...
00:00:00.505 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-10_9_8-Release
00:00:00.505 |I| Loader Load: Loading sdk...
00:00:00.541 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 10.9.8
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-10_9_8-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-10_9_8-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-10_9_8-Release
00:00:00.612 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.619 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.620 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:00.639 |I| Loader LoadNsos: Loading image 2 at 0x000000000d12e000...
00:00:00.641 |I| Loader LoadNsos: Loading image 3 at 0x000000000d7df000...
00:00:00.646 |I| ModLoader LoadCheats: Build ids found for title 01006F8002326000:
    620D55F95C8AC34DF89484DB4797E8F724814DBF000000000000000000000000
    15765149DF53BA4105C75A3A1A5102FC00000000000000000000000000000000
    A8D85220646799ADF9FEC8069202EF485A8A50B7000000000000000000000000
    3EBF13FD7A682BFCB9C812E1EF48B06CB2051985000000000000000000000000
00:00:00.647 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.743 |I| Loader Start: Application Loaded: 모여봐요 동물의 숲 v2.0.6 [01006f8002326000] [64-bit]
00:00:00.752 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:00.976 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3080 Ti (Vulkan v1.3.242, Driver v536.23.0.0)
00:00:00.981 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:00.986 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:01.320 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.378 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.380 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.382 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:01.413 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:02.753 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:04.660 |I| Hid Configure: Configured Controller ProController to Player2
00:00:04.667 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player2
00:00:09.349 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:09.371 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:09.372 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:09.448 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:09.483 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:09.522 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:09.523 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:09.524 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:09.524 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:09.526 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:09.526 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:09.527 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:09.531 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:09.664 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:09.667 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:09.668 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:09.669 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:09.671 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:09.676 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:09.691 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:09.692 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:09.694 |S| HLE.OsThread.22 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:09.694 |S| HLE.OsThread.22 ServiceAm LockExit: Stubbed. 
00:00:09.791 |S| HLE.OsThread.22 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72180189621280768}
00:00:09.796 |S| HLE.OsThread.22 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:09.802 |S| HLE.OsThread.22 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:09.809 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1000}
00:00:09.812 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F80023273E8
00:00:09.814 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1000}
00:00:09.815 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F80023273E8
00:00:10.081 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:10.081 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:10.448 |S| HLE.OsThread.22 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:10.448 |S| HLE.OsThread.22 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:10.449 |S| HLE.OsThread.22 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:10.473 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:10.475 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV8
00:00:10.495 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:10.496 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:10.503 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:10.585 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:10.619 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:10.621 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:17.761 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 300}
00:00:17.761 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712C
00:00:17.793 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 300}
00:00:17.793 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712C
00:00:17.798 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 301}
00:00:17.799 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712D
00:00:17.800 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 301}
00:00:17.800 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712D
00:00:17.800 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1000}
00:00:17.801 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F80023273E8
00:00:17.801 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1000}
00:00:17.801 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F80023273E8
00:00:17.809 |S| HLE.OsThread.22 ServiceAm GetIdleTimeDetectionExtension: Stubbed. {_idleTimeDetectionExtension: 0}
00:00:18.615 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:18.616 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:18.987 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131331}
00:00:19.326 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:20.032 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 300}
00:00:20.032 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712C
00:00:20.032 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 300}
00:00:20.032 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712C
00:00:20.033 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 301}
00:00:20.033 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712D
00:00:20.033 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 301}
00:00:20.034 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01006F800232712D
00:00:20.057 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:20.057 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:20.059 |I| GUI.WindowThread Hid SetupNpad: Disconnected Controller ProController from Player2
00:00:20.059 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:20.181 |S| HLE.OsThread.9 ServiceHid GetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 1 ; SupportedStyleSets: ProController, Handheld, JoyconPair}
00:00:20.184 |S| HLE.OsThread.22 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:00:20.189 |I| HLE.OsThread.22 ServiceAm .ctor: Applet 'Controller' created.
00:00:20.203 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerApplet ArgPriv 20 1072 ShowControllerSupport HoldType:Horizontal StyleSets:ProController, Handheld, JoyconPair
00:00:20.203 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerSupportArg Version 7 EnableExplainText=True
00:00:20.203 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerApplet Arg 1 1 1 1
00:00:22.060 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:24.061 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:26.063 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:28.064 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:30.065 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:30.227 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerApplet ReturnResult 0 16
00:00:30.998 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 126791 bytes, profiled functions: 41749).
00:00:31.989 |S| HLE.OsThread.22 ServiceOlsc Initialize: Stubbed. 
00:00:31.990 |S| HLE.OsThread.22 ServiceOlsc GetSaveDataBackupSetting: Stubbed. {userId: 00000000000000010000000000000000}
00:00:32.066 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:34.068 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:36.070 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:36.649 |S| HLE.OsThread.22 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:36.652 |S| HLE.OsThread.22 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:36.654 |S| HLE.OsThread.22 ServiceNifm Submit: Stubbed. 
00:00:36.654 |S| HLE.OsThread.22 ServiceNifm GetRequestState: Stubbed. 
00:00:36.655 |S| HLE.OsThread.22 ServiceNifm GetResult: Stubbed. 
00:00:38.072 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:40.074 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:42.075 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:43.102 |S| HLE.OsThread.22 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:44.076 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:46.079 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:48.080 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:50.081 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:52.083 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:54.016 |S| HLE.OsThread.9 ServiceHid GetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 1 ; SupportedStyleSets: ProController, Handheld, JoyconPair}
00:00:54.017 |I| HLE.OsThread.22 ServiceAm .ctor: Applet 'Controller' created.
00:00:54.022 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerApplet ArgPriv 20 1072 ShowControllerSupport HoldType:Horizontal StyleSets:ProController, Handheld, JoyconPair
00:00:54.022 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerSupportArg Version 7 EnableExplainText=True
00:00:54.022 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerApplet Arg 1 1 1 1
00:00:54.084 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:56.085 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:58.086 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:01:00.087 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:01:00.997 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 183567 bytes, profiled functions: 58537).
00:01:02.088 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:01:03.599 |S| HLE.OsThread.22 ServiceHid Start: Stubbed. ControllerApplet ReturnResult 0 16
00:01:04.090 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:01:06.092 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'

### OS

windows 11

### Ryujinx version

lastest

### CPU

13700k

**Comment by AcK77** [comment]
As the popup message should tell you:

> No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'

So change your controllers settings to met the game requirements.

Could you please stop to open issues for wrong settings! Thanks.

**Comment by ducky3333** [comment]
When the error message appeared, two controllers were already connected to the computer.
