### ISSUE TITLE
[Feature Request] some function reqesting

### ISSUE THREAD

**Issue by ducky3333** [Ryujinx/Ryujinx#5351]
hi Ryujinx team.
thanks for great application.
anyway, im gonna request some funcion.
1.supporting multimonitor(Fixed display output)
i m using almost 48CX (sub,TV) so, everytime i m dropping windows to rightside monitor.
2.Fixed Audio output
this is relate of upper requst. if i selected TV , i have to change audio output to TV everytimes.
3. Changing title when in playing game.
mose of users having some titles. if i want change title when i playing game , i have to exit and re-start app. I hope there is a function that runs other games quickly
thanks in advance !

### Smaller details

up

### Nature of request

up

### Why would this feature be useful?

more comfortable application.

**Comment by MutantAura** [comment]
Can you please re-write this request. It is unclear of what you are asking.
If you are not a native English speaker then please use a tool such as [DeepL](https://www.deepl.com/en/translator) to translate. Thanks.

**Comment by ducky3333** [comment]
> Can you please re-write this request. It is unclear of what you are asking. If you are not a native English speaker then please use a tool such as [DeepL](https://www.deepl.com/en/translator) to translate. Thanks.

 hi. i m relly sorry for my English . 
i have fixed grammer.

**Comment by AcK77** [comment]
Sorry but it’s really hard to understand what you want here:
1 - Multi-Monitor is something handled by Windows, we don’t have to do anything to support it.
2 - Changing your audio output is still something handled by windows. If you output devices change while Ryujinx is running it’s up to the user to select the one they want.
3 - The title already change each time a game is launched through the emulator.

If you needs support, you can go to our discord server. As the other team member suggested you above, you should use DeepL. Thanks.
