### ISSUE TITLE
[Bug] ToTK crashing PC

### ISSUE THREAD

**Issue by tvoracek** [Ryujinx/Ryujinx#5396]
### Description of the issue

This is the only game causing issues on my PC. By completely crashing it. It is not BSOD (nothing worth mentioning in EventLog), PC just stops working and I need to turn it off on PSU and on again to start it up.

Sometimes game will crash even before loading main screen. Most of time it will run but crash after some period (10-15mins).

### Reproduction steps

Settings:
00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.044 |I| Configuration LogValueChange: ResScale set to: 3
00:00:00.048 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.048 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.048 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.049 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.050 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.050 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2489
00:00:00.050 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.051 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.051 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.057 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.907
00:00:00.060 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.060 |N| Application Print: CPU: AMD Ryzen 7 5700X 8-Core Processor ; 16 logical
00:00:00.061 |N| Application Print: RAM: Total 32682 MiB ; Available 29059 MiB
00:00:00.063 |N| Application PrintSystemInfo: Logs Enabled: Debug, Error
00:00:00.063 |N| Application PrintSystemInfo: Launch Mode: UserProfile

Just start Zelda: Tears of the Kingdom.

### Log file

[Ryujinx_1.1.907_2023-06-24_23-47-53.log.zip](https://github.com/Ryujinx/Ryujinx/files/11858287/Ryujinx_1.1.907_2023-06-24_23-47-53.log.zip)

### OS

Windows 10

### Ryujinx version

1.1.907

### Game version

1.1.2

### CPU

5700x

### GPU

RTX 3060Ti

### RAM

32GB

### List of applied mods

Crashed with no mods or with mods. No difference.

### Additional context?

PC games are fine, other emulators (pcsx2, rpcs3 etc) no issues. BoTW, MK8 etc also run ok. Just ToTK causing big issues.

**Comment by MutantAura** [comment]
This log is heavily truncated and has no crash. Can you upload a full log file that contains the crash.

**Comment by tvoracek** [comment]
That's the only thing in there, full file, really. There are some binary characters at the end, not sure what that is. I guess it crashes and it doesn't even have the chance to write anything about it and close the file properly. When ToTK loads PC just shuts off suddenly. There is no EventLog record about any error, no memory dump, nothing.

**Comment by tvoracek** [comment]
Hmm, seems it crashes when backend is set to Vulkan.

**Comment by AcK77** [comment]
First you should disable debug Logs since it's not needed in your case, and then if you are able to reproduce the issue, send a full log file here, not the beginning of it, not a truncated one. Thanks.

(Additionaly to that, you should try to purge all caches, without mods and no Resolution Scaler.)

**Comment by tvoracek** [comment]
Seems that since I re-seated my GPU the problem is not happening again. I changed some components few months ago and also moved my GPU so maybe it was not 100% in position and it was causing these problems. Don't know.
