### ISSUE TITLE
TOTK crashes after talking to Harth[Bug]

### ISSUE THREAD

**Issue by gampagampa** [Ryujinx/Ryujinx#5402]
### Description of the issue

Everytime when I talk to Harth in the Tulin of Rito Quest, my game crashes.
I Tried to purge my cash and the PPCT directory, but did not help.

### Reproduction steps

Everytime I talk to Harth in the Tulin of Rito Quest, my game crashes after a couple of seconds. 

### Log file

00:00:00.042 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.048 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.049 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.050 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.051 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.052 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.052 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1E89
00:00:00.053 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.054 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.054 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.057 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.066 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.067 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.067 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.067 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.067 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.068 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.068 |I| Configuration LogValueChange: AudioVolume set to: 0,32
00:00:00.069 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.069 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.069 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.069 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.073 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.924
00:00:00.077 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.077 |N| Application Print: CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
00:00:00.078 |N| Application Print: RAM: Total 32694 MiB ; Available 28380 MiB
00:00:00.081 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.081 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.420 |W| GUI.ApplicationLibraryThread Application LoadApplications: The "game_dirs" section in "Config.json" contains an invalid directory: "E:\game"
00:00:00.104 |I| Gpu : Backend Threading (On): True
00:00:00.349 |N| Application LoadApplication: Using Firmware Version: 16.0.1
00:00:00.350 |I| Application LoadApplication: Loading as XCI.
00:00:00.376 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.378 |I| ModLoader AddModsFromDirectory: Found mod '60 FPS Hack' [E]
00:00:00.379 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.382 |I| Loader Load: Loading rtld...
00:00:00.391 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.391 |I| Loader Load: Loading main...
00:00:00.840 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:00.840 |I| Loader Load: Loading subsdk0...
00:00:00.868 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:00.868 |I| Loader Load: Loading sdk...
00:00:00.947 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:01.098 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.762 |I| Ptc Load: Loaded Translation Cache (size: 154734413 bytes, translated functions: 110131).
00:00:02.791 |I| Ptc Load: Loaded Profiling Info (size: 423034 bytes, profiled functions: 123892).
00:00:02.801 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.803 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.826 |I| Loader LoadNsos: Loading image 2 at 0x000000000c66a000...
00:00:02.828 |I| Loader LoadNsos: Loading image 3 at 0x000000000cd13000...
00:00:02.836 |I| ModLoader LoadCheats: Build ids found for title 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    082CE09B06E33A123CB1E2770F5F9147709033DB000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:02.839 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.908 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.0.0 [0100f2c0115b6000] [64-bit]
00:00:02.928 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.969 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:03.322 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2060 (Vulkan v1.3.205, Driver v516.94.0.0)
00:00:03.331 |I| GPU.MainThread Gpu LoadShaders: Loading 1552 shaders from the cache...
00:00:06.295 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:07.627 |I| HLE.GuestThread.21 Ptc LoadTranslations: 103350 translated functions loaded
00:00:07.655 |I| HLE.GuestThread.21 Ptc MakeAndSaveTranslations: 0 of 20542 functions translated | Thread count: 11
00:00:13.443 |I| HLE.GuestThread.21 Ptc MakeAndSaveTranslations: 20542 of 20542 functions translated | Thread count: 11 in 5,7871358 s
00:00:13.534 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:13.545 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:13.546 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:13.546 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:13.557 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:14.204 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:14.204 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:14.205 |S| HLE.OsThread.22 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:14.205 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:14.205 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:14.335 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:14.341 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:14.342 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:14.359 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:14.372 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:14.414 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:14.414 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:14.415 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:14.416 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:14.416 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:14.416 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:14.416 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:14.418 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:14.438 |S| HLE.OsThread.22 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:14.440 |S| HLE.OsThread.22 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:14.441 |S| HLE.OsThread.22 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:14.456 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:14.459 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:14.462 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:15.192 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:15.192 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:18.849 |I| Ptc Save: Saved Translation Cache (size: 175343296 bytes, translated functions: 130673).
00:00:19.946 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:19.948 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:20.124 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:20.127 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV11
00:00:20.151 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:20.152 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:20.153 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:20.187 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:20.188 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:20.208 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:20.669 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:20.669 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:21.035 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:21.035 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:21.035 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:21.035 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:22.452 |S| HLE.OsThread.22 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:22.452 |S| HLE.OsThread.22 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:22.452 |S| HLE.OsThread.22 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:22.576 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:22.594 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:22.693 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 98
 UserId: 6370087c17884babbd6ba639e6cbedc9
 Room: bootup_time

### OS

Windows 10

### Ryujinx version

1.1.924

### Game version

 v1.1.0

### CPU

AMD Ryzen 5 3600

### GPU

Nvidia RTX 2060

### RAM

32 GB

### List of applied mods

60 FPS mod, but it happens aswell without the mod.

**Comment by gampagampa** [comment]
00:30:10.665 |E| HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 44
   at InvokeStub_IStorage.Read(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 435
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 278
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

**Comment by AcK77** [comment]
Your game/update dump is bad. Redump them from your hacked switch and this will be fixed. Next time, come to our discord for support before posting an issue. Thanks.

**Comment by gampagampa** [comment]
Ok, sorry for the inconvenience. Next time I will come to the discord channel.
Can you maybe just shortly explain what it means to redump the game/update?
