### ISSUE TITLE
[Bug] Ryuinx crashes when playing TOTK

### ISSUE THREAD

**Issue by H3nshin** [Ryujinx/Ryujinx#5405]
### Description of the issue

Hello, I'm fairly new to emulating so sorry if this is a common mistake, but I'm trying to emulate TOTK and the game just crashes after a few seconds. I don't know if my PC is just not strong enough to run it or if I'm doing something wrong. If anyone knows what to do it would be a great help. Thanks a lot.
![Sin título](https://github.com/Ryujinx/Ryujinx/assets/137819943/8e68d321-7120-4426-8244-1e14d57cbc0b)

### Reproduction steps

I just installed the emulator and the game file and used the common stapes to make it run. I'm using OpenGL with standard settings bcs Vulcan crashes.

### Log file

00:00:00.111 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.119 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.119 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.120 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.122 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.123 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.123 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.124 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.125 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.125 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.129 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.142 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.142 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.143 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.143 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.143 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.143 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.143 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.143 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.145 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.145 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.146 |I| Configuration LogValueChange: MemoryManagerMode set to: SoftwarePageTable
00:00:00.146 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.146 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.146 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.153 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.924
00:00:00.160 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.160 |N| Application Print: CPU: AMD FX(tm)-4300 Quad-Core Processor ; 4 logical
00:00:00.161 |N| Application Print: RAM: Total 8150 MiB ; Available 4705 MiB
00:00:00.165 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.166 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

Windows 10

### Ryujinx version

ryujinx-1.1.924-win_x64

### Game version

1.0.0

### CPU

AMD Fx(tm)-4300 Quad-Core Processor

### GPU

Radeon(TM) RX 460 Graphics

### RAM

8GB

### List of applied mods

No mods

**Comment by AcK77** [comment]
Your GPU seems too old and your driver can’t compile the OpenGL shaders. Try to update them. If you can’t, then there is nothing we can do.
But don’t expect a playable game since your specs are too low.
