### ISSUE TITLE
[Bug] there is detecing bug on some titles

### ISSUE THREAD

**Issue by ducky3333** [Ryujinx/Ryujinx#5413]
### Description of the issue

especially, Super mario party & party Superstars .
when i enter to title screen, my two controllers connection has disconnected.
also, NSW sport having same issue.
all titles has updated to lastet verion.

would you check please? 

thanks in advance.

### Reproduction steps

there is no solutuon. 

### Log file

[Ryujinx_1.1.942_2023-06-29_19-44-46.log](https://github.com/Ryujinx/Ryujinx/files/11904863/Ryujinx_1.1.942_2023-06-29_19-44-46.log)

### OS

windows 11

### Ryujinx version

1.1.942

### Game version

1.1.0

**Comment by AcK77** [comment]
As the popup message should tell you:

> No matching controllers found. Application requests 'JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'

So change your controllers settings to met the game requirements.
