### ISSUE TITLE
cheats don't work on ryujinx

### ISSUE THREAD

**Issue by valelisa88** [Ryujinx/Ryujinx#5416]
### Description of the issue

hello these days I'm playing with Ryujinx emulator because my switch is broken it doesn't work I was playing with Ryujinx at my time at portia version 1.0.7 but some codes don't work only the infinite money one works but the others nothing doesn't work

### Reproduction steps

no

### Log file

no

### OS

windows 11

### Ryujinx version

ryujinx version 1.1.9.4.2.0

### Game version

my time at portia  1.0.7

### CPU

intel core

### GPU

no

### RAM

16gb

### List of applied mods

no

### Additional context?

no

**Comment by piplup55** [comment]
You haven't proved us we enough info to see if it's even related to ryujinx, you also haven't filled out the template opting for `no` in most **required** fields
