### ISSUE TITLE
cheats don't work on ryujinx

### ISSUE THREAD

**Issue by valelisa88** [Ryujinx/Ryujinx#5417]
### Description of the issue

hi the codes don't work on ryujinx especially on my time at portia version 1.0.7 i'm using the latest version of ryujinx attached screenshots 

### Reproduction steps

[url=https://ibb.co/1JShgGm][img]https://i.ibb.co/sJBkf9V/IMG-20230629-211110-397.jpg[/img][/url]

[url=https://ibb.co/MScQ3gw][img]https://i.ibb.co/6wHLfy9/IMG-20230629-211053-440.jpg[/img][/url]

### Log file

no

### OS

windows 11

### Ryujinx version

ryujinx version 1.1.942

### Game version

my time at portia  1.0.7

### CPU

no

### GPU

no

### RAM

16gb

### List of applied mods

no

### Additional context?

no

**Comment by piplup55** [comment]
this doesn't look like a ryujinx issue you can join the [discord](https://discord.gg/ryujinx) if you need help applying cheats or goto the faq [cheat page](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-how-do-i-install-cheats-for-a-game), you also haven't filled out the template opting for `no` in most **required** fields.

**Comment by AcK77** [comment]
You don’t give enough informations here, looks more like an issue at your side than a Ryujinx bug. Be sure you use the right cheat code version corresponding to the game version.
You can come to our discord server for support. Thanks.
