### ISSUE TITLE
[Bug] ryujinx wont let me save my controller layout

### ISSUE THREAD

**Issue by Marblesinmayhem** [Ryujinx/Ryujinx#5423]
### Description of the issue

Ryujinx won’t let me save controller layout at all

### Reproduction steps

Download ryujinx, load it up, set it up, open controller layout and try to set up Xbox controller. Software then refuses to let me click save after inputting each control

### Log file

There was no log. Nothing crashed, but nothing worked.

### OS

Windows 10

### Ryujinx version

1.1.947

### Additional context?

Ran it through steam, still didn’t work. Tried the automatic controller setup thing and still did not work. I’m so confused

**Comment by AcK77** [comment]
It was a regression of #5395 which is now fixed by #5424.
