### ISSUE TITLE
[Bug] Blinking textures (squares) all over the place in Master Detective Archives: RAIN CODE

### ISSUE THREAD

**Issue by TANTRUM01** [Ryujinx/Ryujinx#5428]
### Description of the issue

On every level, on walls, on objects, on the floor etc. there are textures that are moving/teleporting and blinking constantly, like in the pic below

### Reproduction steps

Start the game

### Log file

[Ryujinx_1.1.952_2023-07-03_23-09-17.log](https://github.com/Ryujinx/Ryujinx/files/11940728/Ryujinx_1.1.952_2023-07-03_23-09-17.log)

### OS

Microsoft Windows 10.0.19044 (X64)

### Ryujinx version

1.1.952

### Game version

1.3.0

### CPU

Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 

### GPU

AMD Radeon RX 580 Series (Vulkan v1.3.246, Driver v2.0.262)

### RAM

16318 MiB

### Additional context?

![tG0CEaXvtlk](https://github.com/Ryujinx/Ryujinx/assets/138499811/e3e046cd-801b-4335-9193-0c5e0c36a584)

**Comment by Kohega** [comment]
Confirming this issue too. 
Latest Ryujinx, Vulkan.

**Comment by othmanead** [comment]
this issue is due to amd not supporting shader interlock: this one: https://github.com/Ryujinx/Ryujinx/pull/2768
so the issue is not present on nvidia gpus

**Comment by DespairFate** [comment]
> Hi
I have the same problem. But then the question is why there are no such problems on another emulator ???

**Comment by DuIslingr** [comment]
This bug has not been fully fixed. During some cutscenes this effect occurs around character models sometimes. It’s not consistent though. https://www.youtube.com/live/JX4dIu59lgU?feature=share 

58:56 timestamp to see it occur briefly when the camera shifts to behind the protag.

playing at 2x
gpu: RX 7900XTX (23.7.2 drivers)
