### ISSUE TITLE
[Bug] Pokémon Legends Arceus, Game like automatic input even disabling all control (only on docked mode)

### ISSUE THREAD

**Issue by Ryan2603** [Ryujinx/Ryujinx#5431]
### Description of the issue

Pokémon Legends Arceus ID. 01001F5010DFA000

when the game loaded, its automatic moving, switching and cancelling, its not a game crash but its input jamming somewhat.

whlie i switched to handheld mode, its stopped jamming.

### Reproduction steps

just load up game in docked mode

### Log file

no any error logging retrieved

### OS

W11 22621.1848

### Ryujinx version

latest

### Game version

latest 1.1.1

### CPU

AMD 5700X

### GPU

3060 TI

### RAM

64GB

**Comment by OldManKain** [comment]
This is either do to having steam open or having handheld controls enabled in input settings.   Please join us in our discord https://discord.gg/ryujinx for trouble shooting.

**Comment by Ryan2603** [comment]
> This is either due to having steam open or having handheld controls enabled in input settings. Please join us in our discord https://discord.gg/ryujinx for trouble shooting.

thanks for the tips, but i cannot using discord to further questions. 
i haven't any steam open or handheld controls enabled in input settings, im just testing for new PR in dozen of game, none got this bug but Pokémon Legends Arceus ID. 01001F5010DFA000

did you really thought this is not an issue at all?

**Comment by OldManKain** [comment]
It is a Known Issue, and has been known for a while now, this is not an issue with Ryujinx itself, it is due to not having the input setup right.

**Comment by Ryan2603** [comment]
damn it, im sorry i double check again, yes my handheld setting is On to keyboard, sorry bro!
