### ISSUE TITLE
[Bug] Shader Z-index in Legend of Zelda: Link's Awakening

### ISSUE THREAD

**Issue by DistractionRectangle** [Ryujinx/Ryujinx#5443]
### Description of the issue

Shadow from the tower for Level 7 (upper right corner of the map) clips when you approach it. Clipping is present before and after it is unlocked. 

[Expected Behavior](https://www.youtube.com/watch?v=fUEk683QNO0&t=680s)

[Actual Behavior](https://github.com/Ryujinx/Ryujinx/assets/48034372/3c2f0e62-1550-41a4-9f93-19ec4f747b3c)

### Reproduction steps

See video - simply walk into/out of the shadow.

### Log file

[Ryujinx_1.1.956_2023-07-08_11-46-31.log](https://github.com/Ryujinx/Ryujinx/files/11992259/Ryujinx_1.1.956_2023-07-08_11-46-31.log)

### OS

Windows 11 Pro Build 22621

### Ryujinx version

1.1.956

### Game version

1.0.1

### CPU

AMD 5700G

### GPU

NVIDIA RTX 3080 (10G)

### RAM

32GB

### List of applied mods

N/A

### Additional context?

Vulkan backend using the 3080. This is the only graphical bug I've noticed in the game.

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/208
Since it's a game specific issue, I close.
Thanks
