### ISSUE TITLE
Screen Tearing On M1 Mac

### ISSUE THREAD

**Issue by Hoplite1111** [Ryujinx/Ryujinx#5445]
### Description of the issue

Horrible screen tearing on Omori, I haven't tested with anything else. Here I have included a screenshot of my graphics settings as well as a video showing the issue. I am running the latest MacOS version from the website.
<img width="1440" alt="Screenshot 2023-07-08 at 6 31 09 PM" src="https://github.com/Ryujinx/Ryujinx/assets/136226630/7e6e7c0e-9d47-4c34-93ab-7689cf6e3f6f">

https://github.com/Ryujinx/Ryujinx/assets/136226630/80ac3900-6e13-4f97-95be-08cd6beda192

### Reproduction steps

Simply play Omori.

### Log file

[Ryujinx_ 1.1.0-macos1_2023-07-08_18-41-32.log](https://github.com/Ryujinx/Ryujinx/files/11994164/Ryujinx_.1.1.0-macos1_2023-07-08_18-41-32.log)

### OS

MacOS Ventura 13.4

### Ryujinx version

1.1.0 macos

### Game version

1.0.2

### CPU

M1

### GPU

M1

### RAM

8Gb

**Comment by gdkchan** [comment]
Screen tearing on mac should be fixed on latest version.

**Comment by Hoplite1111** [comment]
Am I not on the most current version? I downloaded it today from the downloads page.

**Comment by liejuntao001** [comment]
It's not. Scroll down to the bottem and use the "Manual Download" button.

**Comment by Hoplite1111** [comment]
Thank you so much dude now I can enjoy one of my favorite games!
