### ISSUE TITLE
[Bug] Fire Emblem Engage crashed after battle of chapter 16

### ISSUE THREAD

**Issue by sigal1113** [Ryujinx/Ryujinx#5447]
### Description of the issue

Upon battle of chapter 16 ended, the message "chapter 16 is ended" pop-up, then screen gets dark, and then Ryujinx crashed.
Ryujinx version is 1.1.956, fire emblem engage's version is 2.0.0, installed several mods and cheats from the beginning of game and never crashed until ends of battle of chapter 16.

### Reproduction steps

Kill the second boss of the two bosses, message shows MVP is XXX and chapter 16 ends, screen gets dark and then Ryujinx crashed. Tried removing all mods and cheats but still same issue. 
Switched graphic's backend between both Vulkan and OpenGL, both crashed still.

### Log file

[](url)
[Ryujinx_1.1.956_2023-07-09_22-10-25.log](https://github.com/Ryujinx/Ryujinx/files/11995359/Ryujinx_1.1.956_2023-07-09_22-10-25.log)

### OS

Windows 10

### Ryujinx version

1.1.956

### Game version

2.0.0

### CPU

AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz

### GPU

NVIDIA RTX 3070 Ti

### RAM

32GB

### List of applied mods

aAmiiboSomnielPack
aaSimpleCameraTweak
aCharEditPack
Battle Outfits and More Outfits 2.0.1
Class_Amiibo_2.1.0
Nude_Mod_Classes
Playable Bosses
skyline
ThirdPlaythroughMod
Cobalt

**Comment by MetrosexualGarbodor** [comment]
The error in your log suggests a mod issue.
