### ISSUE TITLE
PPTC is taking an abnormally long time to build and games need to have PPTC requeued for every time I load them.

### ISSUE THREAD

**Issue by JoeBrisado** [Ryujinx/Ryujinx#5448]
### Description of the issue

Games only load once after taking a very long time to load the PPTC and after closing and reopening the emu, they don't load anymore, they still start but nothing is displayed on the screen. No error message is displayed on the console, which goes on a forever stand by...

The only way to load the games again is requeueing the PPTC which is taking abnormally long times to load it. After closing and reopening the emu, they won't load anymore, rinse and repeat... By the way, I've always used PPTC enabled on the settings and building it has always been super fast. If i try to disable it and play, it has the same effect of trying to play it without rebuilding it, the game doesn't load and the console doesn't display any error message.

I had been playing on Ryujinx almost every day until last month, this issue started after a big wave of updates that happened recently.

### Reproduction steps

I believe the issue itself already describes how to be reproduced.

### Log file

[Ryujinx_1.1.960_2023-07-11_19-20-28.log](https://github.com/Ryujinx/Ryujinx/files/12021901/Ryujinx_1.1.960_2023-07-11_19-20-28.log)
[Ryujinx_1.1.960_2023-07-11_18-56-57.log](https://github.com/Ryujinx/Ryujinx/files/12021902/Ryujinx_1.1.960_2023-07-11_18-56-57.log)
[Ryujinx_1.1.960_2023-07-11_18-49-23.log](https://github.com/Ryujinx/Ryujinx/files/12021903/Ryujinx_1.1.960_2023-07-11_18-49-23.log)

### OS

Windows 10

### Ryujinx version

1.1.960

### Game version

Every single game on my folder

### CPU

i7-4790

### GPU

Nvidia Geforce 1660 TI

### RAM

32GB

**Comment by Linktothepast** [comment]
Same issue here the emulator has practically become unplayable.

**Comment by hightechman6819** [comment]
I have the same problem, after the windows update 

![image](https://github.com/Ryujinx/Ryujinx/assets/139459478/ab97d49b-3466-4d29-8654-85f9f363b191)

**Comment by hightechman6819** [comment]
thanks everyone yes it was the AV
