### ISSUE TITLE
[Bug] Audio pitch shift issue

### ISSUE THREAD

**Issue by THRESHER1998** [Ryujinx/Ryujinx#5449]
### Description of the issue

There seems to be an issue with the audio when playing Super Mario Odyssey and Super Mario 3d all stars where the audio will shift in pitch. It only seems to happen when there's a change in the frame rate though. I'm up to date with the latest version of Ryujinx but I don't see an option to change the emulation speed as was shown on an earlier post. 

this post: https://github.com/Ryujinx/Ryujinx/pull/4778 

How do I upgrade to this version? Or how do I install this mod/hack for the emulator?

### Reproduction steps

Happens on start up and issue persists in game play.

### Log file

[Ryujinx_1.1.958_2023-07-12_00-46-50.log](https://github.com/Ryujinx/Ryujinx/files/12024298/Ryujinx_1.1.958_2023-07-12_00-46-50.log)
[Ryujinx_1.1.958_2023-07-12_00-59-35.log](https://github.com/Ryujinx/Ryujinx/files/12024300/Ryujinx_1.1.958_2023-07-12_00-59-35.log)

### OS

Windows 11

### Ryujinx version

1.1.958

### Game version

1.1.1

### CPU

Intel i7-11800H

### GPU

Nivida GTX 1660Ti 8 GB

### RAM

16GB

**Comment by AcK77** [comment]
You can report the state of the game at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/93
Or your can come to our discord server for support.
Thanks
