### ISSUE TITLE
[Bug] TOTK Crash at fire temple intro cutscene

### ISSUE THREAD

**Issue by hutiwephy** [Ryujinx/Ryujinx#5455]
### Description of the issue

every time yunobo points at the cage and the animation starts it just crashes due to "ErrorOutOfDeviceMemory"

### Reproduction steps

walk into the fire temple with yunobo

### Log file

[Ryujinx_1.1.961_2023-07-15_23-05-14.log](https://github.com/Ryujinx/Ryujinx/files/12062905/Ryujinx_1.1.961_2023-07-15_23-05-14.log)

### OS

Windows 10

### Ryujinx version

1.1.961

### Game version

1.1.2

### CPU

i7-11370H @ 3.30GHz

### GPU

NVIDIA RTX 3060 (laptop)

### RAM

16GB

### List of applied mods

DynamicFPS_totk
Loaded_Zonaite_Deposit_10-20_v110
VisualFixes_1008P_FXAA_Off_FSR_Off_totk
VisualFixes_DisableQualityReduction_totk
VisualFixes_DisableTargetingDOF_totk
Xbox UI v2

### Additional context?

I've already tried all memory management modes possible

**Comment by OldManKain** [comment]
Known issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598

**Comment by hutiwephy** [comment]
Thanks
