### ISSUE TITLE
[GPU] nvidia geforce rtx 3060 intel i7-127000kf [CPU] 16GB ram 

### ISSUE THREAD

**Issue by xCBMKilo0x** [Ryujinx/Ryujinx#5460]
### Shader instruction

|W| GPU.AsyncTranslationThread.7 Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.

reapeating and shader compilation is very slow 
[Ryujinx_1.1.964_2023-07-17_13-46-57.log](https://github.com/Ryujinx/Ryujinx/files/12073900/Ryujinx_1.1.964_2023-07-17_13-46-57.log) 
the game will crash as soon as it goes to launch forcing ryujjinx to close as well

### Required by

im not sure what im supposed to put here

**Comment by RedPana** [comment]
Votevtg is already reported [here](https://github.com/Ryujinx/Ryujinx/issues/2794).

Set your backend to Vulkan instead of OpenGL for faster shader compilation. Come to the discord if you need more help.
