### ISSUE TITLE
[Bug] Monster Hunter Stories 2 Graphics Glitching

### ISSUE THREAD

**Issue by theKnightsOfRohan** [Ryujinx/Ryujinx#5461]
### Description of the issue

- Player, monster, and object models switch between two different positions and/or actions. There is also stretching. This issue occurs while in the middle of a battle, but not anywhere else that I could tell.
- Even though this glitch begins in battles, it persists to the overworld as well, probably due to them being rendered the same way.
- The glitch does not persist if the game emulation is stopped and reopened from the Ryujinx menu screen.

### Reproduction steps

I don't know exactly how to reproduce it, besides enter the game with 8gb ram on Mac and see what happens. There's no specific time it occurs. The glitch seems to be triggered when the GPU/CPU is under high stress, as I am playing on an M1 Macbook Air, and the issue occurs regularly and occurs while the laptop has heated up while playing. I have been able to delay the glitch by switching to handheld mode instead of docked and pausing the game periodically whenever the heat gets too high. The glitching does not stop when I pause the game and let my Mac cool down without restarting the game, however.

### Log file

Here is a log file of two different times when this glitch occurred, with me restarting the game in between. 
[Ryujinx_ 1.1.0-macos1_2023-07-17_11-52-24.log](https://github.com/Ryujinx/Ryujinx/files/12074169/Ryujinx_.1.1.0-macos1_2023-07-17_11-52-24.log)

### OS

Mac OS Monterey 12.6.2

### Ryujinx version

1.1.0

### Game version

1.5.2

### CPU

Apple M1

### GPU

Apple M1

### RAM

8GB

### List of applied mods

N/A

### Additional context?

I have the first 31 DLC installed.

**Comment by MetrosexualGarbodor** [comment]
does this happen on the latest build?

**Comment by theKnightsOfRohan** [comment]
> does this happen on the latest build?

Isn't 1.1.0 the only version available for Mac OS currently?

**Comment by AcK77** [comment]
You can use our `macos_universal` build from https://github.com/Ryujinx/release-channel-master/releases

Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3672
Since it's a game specific issue, I close.
Thanks
