### ISSUE TITLE
[Bug] Macbook Pro 14" M2 Max crashes after a few minutes of gameplay of Touhou Luna Nights

### ISSUE THREAD

**Issue by PaulShiLi** [Ryujinx/Ryujinx#5462]
### Description of the issue

Game freezes followed by the entire Mac freezing and unable to access anything. Forced touch trackpad became disabled as well as a result of this freeze/crash by Ryujinx. Only solution was to hard reboot. Same thing happened with Legend of Zelda TOTK after some gameplay.

### Reproduction steps

For me, it happens with every game where I would game for around 5-10 minutes until Ryujinx would randomly decide to freeze which causes my mac to crash -_- 

Vsync is enabled as well for all games.

### Log file

[Ryujinx_1.1.964_2023-07-17_17-19-50.log](https://github.com/Ryujinx/Ryujinx/files/12075240/Ryujinx_1.1.964_2023-07-17_17-19-50.log)
[Ryujinx_1.1.964_2023-07-17_19-18-27.log](https://github.com/Ryujinx/Ryujinx/files/12075242/Ryujinx_1.1.964_2023-07-17_19-18-27.log)

### OS

MacOS Sonoma 14.0

### Ryujinx version

1.1.964

### CPU

M2 Max

### GPU

M2 Max

### RAM

64 GB

### List of applied mods

None

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/new?assignees=&labels=&projects=&template=game_compatibility.yml
(Don't forget to use our latest build now since macos1 is outdated)
Since it's a game specific issue, I close.
Thanks
