### ISSUE TITLE
[Feature Request] Add game notes or rename

### ISSUE THREAD

**Issue by itxxq** [Ryujinx/Ryujinx#5473]
### Overview

At present, it is difficult to remember the automatically recognized game name. I hope to add a renaming function and change the name according to personal preferences.

### Smaller details

rename

### Nature of request

rename

### Why would this feature be useful?

At present, it is difficult to remember the automatically recognized game name. I hope to add a renaming function and change the name according to personal preferences.

**Comment by AcK77** [comment]
IMO I don't see in what way that could be useful. Names are set by games creators and they are already fully readable.

**Comment by AcK77** [comment]
You can still use the favorite option in the UI to put your games on the top of the list using the right sorting filter.
Since there isn't more input about that, I close the issue.
If something really revelant is say, we could reconsider opening it back.
Thanks

**Comment by gdkchan** [comment]
This sounds somewhat similar to #5655.

**Comment by AcK77** [comment]
You mean #5584 ?

**Comment by mitch03** [comment]
this would be awesome, even if its made so we can use file names instead, similar to how other emulators do it
