### ISSUE TITLE
 HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish In code rain

### ISSUE THREAD

**Issue by Kittonaito** [Ryujinx/Ryujinx#5474]
### Description of the issue

i have a problem that message appears me in the console when i open the code rain game i download the game in spanish, when i try other emulator with the game and i don´t have problems but with ryujinx the game still in inglish :C

### Reproduction steps

when i open the game

### Log file

00:00:11.753 |I| HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:00:11.758 |I| HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:00:11.771 |I| HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish

### OS

windows 10

### Ryujinx version

1.1.966

### CPU

AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz

### GPU

NVIDIA GTX 1650

### RAM

16,0 GB

**Comment by CoolFrenchPerson** [comment]
This is normal behavior, since Master Detective : Rain Code (and maybe other games) may use other types of English. You can ignore this error since it will use the type of English that the game requests.

**Comment by Kittonaito** [comment]
but i want the game in spanish and don´t appear in spanish

**Comment by Kittonaito** [comment]
> ### Description of the issue
> i have a problem that message appears me in the console when i open the code rain game i download the game in spanish, when i try other emulator with the game and i don´t have problems but with ryujinx the game still in inglish :C
> 
> ### Reproduction steps
> when i open the game
> 
> ### Log file
> 00:00:11.753 |I| HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish 00:00:11.758 |I| HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish 00:00:11.771 |I| HLE.OsThread.22 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
> 
> ### OS
> windows 10
> 
> ### Ryujinx version
> 1.1.966
> 
> ### Game version
> _No response_
> 
> ### CPU
> AMD Ryzen 5 2600 Six-Core Processor 3.40 GHz
> 
> ### GPU
> NVIDIA GTX 1650
> 
> ### RAM
> 16,0 GB
> 
> ### List of applied mods
> _No response_
> 
> ### Additional context?
> _No response_



> but i want the game in spanish and don´t appear in spanish

how i supposed to change it to spanish then?

**Comment by CoolFrenchPerson** [comment]
Then you haven't changed the settings for it to appear in spanish, Options -> Settings -> System -> System Language ( change it to spanish there )

**Comment by Kittonaito** [comment]
Thank you very much, seriously, I spent the entire first case doing it in English, which is not impossible for me but it is still complicated for me, because I didn't know what to do, it turns out that I had it in Latin American Spanish and not in Spanish from Spain, that's how I solved it, thank you very much!
