### ISSUE TITLE
[Bug] Pikmin 4 won't run

### ISSUE THREAD

**Issue by lirazly** [Ryujinx/Ryujinx#5475]
### Description of the issue

I tried to play Pikmin 4, but it wouldn't launch. What would happen is it'd start to boot, showing the bar that displays the framerate, vsync, ect, but the fps would go to 00.00 (infinity ms) then after a moment kill the program. There would be nothing shown on the screen too.

### Reproduction steps

This happens everytime I try to play Pikmin 4, I'm unsure on what conditions cause this to happen.

### Log file

[Ryujinx_1.1.966_2023-07-21_00-22-24.log](https://github.com/Ryujinx/Ryujinx/files/12116315/Ryujinx_1.1.966_2023-07-21_00-22-24.log)
[Ryujinx_1.1.966_2023-07-21_00-22-59.log](https://github.com/Ryujinx/Ryujinx/files/12116316/Ryujinx_1.1.966_2023-07-21_00-22-59.log)
[Ryujinx_1.1.966_2023-07-21_00-28-45.log](https://github.com/Ryujinx/Ryujinx/files/12116317/Ryujinx_1.1.966_2023-07-21_00-28-45.log)

### OS

Pop!_OS

### Ryujinx version

1.1.966

### Game version

1.0.1

### CPU

Intel® Core™ i5-9400 CPU @ 2.90GHz × 6 

### GPU

Geforce rtx 3040

### RAM

16GB

### List of applied mods

N/A

### Additional context?

I've tried both xci roms and nsp roms of pikmin 4, but both would have the same issue. Something strange is that I'm still able to play the demo without any problems. I'm unclear on what's special about the demo vs the full game.

**Comment by CoolFrenchPerson** [comment]
Set Audio backend to SDL2 and Memory Mode Manager to Host Unchecked. Also use our discord for future support : https://discord.gg/N2FmfVc

**Comment by lirazly** [comment]
sadly your solution didn't work, but thank you still. I'll get on the discord for more help, thank you once again.
