### ISSUE TITLE
[Bug] Ryujinx won't run.Pl tell me the solution.

### ISSUE THREAD

**Issue by suzuki-udo** [Ryujinx/Ryujinx#5477]
### Description of the issue

I can't get Ryujinx started.
Ryujinx crashes with me starting the games.
Pl tell me the solution.
the crash report is written below.

Process:               Ryujinx [652]
Path:                  /Volumes/VOLUME/*/Ryujinx 3.app/Contents/MacOS/Ryujinx
Identifier:            org.ryujinx.Ryujinx
Version:               1.1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Ryujinx [652]
User ID:               501

Date/Time:             2023-07-21 21:49:23.286 +0900
OS Version:            macOS 11.7.8 (20G1351)
Report Version:        12
Anonymous UUID:        63DDA028-A9B4-C63F-9CF6-A421F87A2B80

Time Awake Since Boot: 360 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        59

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0:: Dispatch queue: com.apple.main-thread

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=845.8M resident=0K(0%) swapped_out_or_unallocated=845.8M(100%)
Writable regions: Total=8.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8.6G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 1440K        6 
CG image                            24K        3 
CoreAnimation                       48K        8 
CoreGraphics                         4K        1 
CoreUI image data                  380K        7 
Foundation                          16K        1 
IOKit                             7940K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           195.4M      235 
MALLOC guard page                   32K        8 
MALLOC_LARGE (reserved)            160K        1         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        384K        5 
STACK GUARD                       56.2M       61 
Stack                            107.2M       61 
VM_ALLOCATE                        1.0T    14185 
VM_ALLOCATE (reserved)            1508K        2         reserved VM address space (unallocated)
__DATA                            16.0M      370 
__DATA_CONST                      23.8M      215 
__DATA_DIRTY                       702K      125 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       571.6M       19 
__OBJC_RO                         70.2M        1 
__OBJC_RW                         2496K        2 
__TEXT                           274.3M      369 
__UNICODE                          588K        1 
dylib                               24K        2 
dylib (reserved)                    36K        3         reserved VM address space (unallocated)
mapped file                      290.4M       59 
shared memory                      7.6G       27 
===========                     =======  ======= 
TOTAL                              1.0T    15785 
TOTAL, minus reserved VM space     1.0T    15785 

Model: iMac14,2, BootROM 433.140.2.0.0, 4 processors, Quad-Core Intel Core i5, 3.2 GHz, 16 GB, SMC 2.15f7
Graphics: kHW_NVidiaGeForceGT755MItem, NVIDIA GeForce GT 755M, spdisplays_pcie_device, 1 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE SSD SD0128F, 121.33 GB
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Controller
USB Device: Portable HDD CH94
USB Device: MF-MSU2B
Thunderbolt Bus: iMac, Apple Inc., 23.10

### Reproduction steps

I installed prodkey ver-16.03 and firmware ver-16.0.3.
And I downloaded MetoroidDred ROM ver-1.0.0.

### Log file

[Ryujinx_1.1.965_2023-07-19_15-17-54.log](https://github.com/Ryujinx/Ryujinx/files/12124989/Ryujinx_1.1.965_2023-07-19_15-17-54.log)

### OS

mac os 11.7.8

### Ryujinx version

1.1.967

### Game version

1.0.0

### CPU

3.2 GHz Quadcore Intel Core i5

### GPU

NVIDIA GeForce GT 755M 1 GB

### RAM

16gb

**Comment by mrtnptrs** [comment]
An educated guess would be that your GPU is is sadly far too weak with its extremely limited amount of VRAM, clockspeed etc. Likely when starting a game through Ryujinx, it immediatly hits your VRAM limit and crashes.

**Comment by AcK77** [comment]
Your mac specs are a bit too low to run Ryujinx.
You can try bootcamp but that will not doing magical things.
