### ISSUE TITLE
Super Mario Odyssey  -  Game crashes during of after Hariet battle in Sand Kingdom

### ISSUE THREAD

**Issue by Gurjinho** [Ryujinx/Ryujinx#5478]
### Description of the issue

Game has crashed several times, always during or after the fight 

### Reproduction steps

Crashes randomly, sometimes when I hit a bomb or right after the fight

### Log file

[Ryujinx_1.1.967_2023-07-21_15-35-36.log](https://github.com/Ryujinx/Ryujinx/files/12129353/Ryujinx_1.1.967_2023-07-21_15-35-36.log)

### OS

Windows 11

### Ryujinx version

1.1.967

### Game version

1.3.0

### CPU

AMD Ryzen 5 5600X

### GPU

AMD Radeon 6500 XT

### RAM

16GB

**Comment by AcK77** [comment]
No more answer from OP.
You can report the state of the game at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/93
Or your can come to our discord server for support.
Thanks
