### ISSUE TITLE
[Bug] Random Pikmin 4 Crashes

### ISSUE THREAD

**Issue by PodcastGuru74** [Ryujinx/Ryujinx#5479]
### Description of the issue

Pikmin 4 crashes randomly. If I had to pinpoint the crashes I would say they happen during or just after loading screens.

### Reproduction steps

I could not find a way to reproduce the crash. Just playing Pikmin 4 for a while seems to trigger the crash.

### Log file

[Ryujinx_1.1.968_2023-07-22_00-12-58.log](https://github.com/Ryujinx/Ryujinx/files/12136030/Ryujinx_1.1.968_2023-07-22_00-12-58.log)
[Ryujinx_1.1.968_2023-07-22_01-49-36.log](https://github.com/Ryujinx/Ryujinx/files/12136033/Ryujinx_1.1.968_2023-07-22_01-49-36.log)

### OS

Fedora Linux 38

### Ryujinx version

1.1.968

### Game version

1.0.1

### CPU

AMD Ryzen 7 3700X 8-Core Processor

### GPU

AMD Radeon RX 5600 XT

### RAM

32 GiB

### List of applied mods

None.

**Comment by lirazly** [comment]
I'm experiencing a similar issue, except the entire game won't run. It crashes while loading everything. How did you get it to run in the first place? Like, what settings and such? I'm sorry the game doesn't run properly for you too </3

**Comment by PodcastGuru74** [comment]
I didn't do anything in particular to get it running; I just loaded it up like normal with no modifications or changed settings and it worked.

**Comment by lirazly** [comment]
Yeah it could be a difference in hardware, I'm also running Pop_os so that might be part of the problem, different distros and all.

**Comment by AcK77** [comment]
Based on your log file:

> .NET ThreadPool Worker ioctl (GFEATURE): Input/output error
> .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.

This issue looks more like an OS issue.

**Comment by PodcastGuru74** [comment]
> Based on your log file:
> 
> > .NET ThreadPool Worker ioctl (GFEATURE): Input/output error
> > .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
> 
> This issue looks more like an OS issue.

Do you have any idea of how I could fix this issue?

I had another issue related to `vm.max_map_count` that would crash Tears of the Kingdom. The solution in that case was to temporarily change the value while using Ryujinx, then change it back after Ryujinx was closed ([https://github.com/Ryujinx/Ryujinx/pull/4702](url) - [https://github.com/Ryujinx/Ryujinx/issues/4941](url)).

Could this be a similar situation of having to change a systemd value temporarially for Ryujinx to prevent crashes?

**Comment by TSRBerry** [comment]
> .NET ThreadPool Worker ioctl (GFEATURE): Input/output error

Are you using a preview version of dotnet?

> .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.

You are using environment variables which are changing the behavior here, but I don't think this is related to your issues.

> I had another issue related to vm.max_map_count that would crash Tears of the Kingdom. The solution in that case was to temporarily change the value while using Ryujinx, then change it back after Ryujinx was closed

Ryujinx does that for you already. 

Your logs are completely empty. Are you running Ryujinx using `Ryujinx.sh`?

**Comment by PodcastGuru74** [comment]
I'm not knowingly using a beta version of dotnet. I'll check for sure when I'm close to my computer again.

I downloaded Ryujinx from the Releases section of GitHub and have it stored in my home directory. I'm not using Ryujinx.sh.

**Comment by TSRBerry** [comment]
Does the problem also occur if you use `Ryujinx.sh`?

**Comment by AcK77** [comment]
No more answer from OP.
You can report the state of the game at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4693
Or your can come to our discord server for support.
Thanks
