### ISSUE TITLE
[Feature Request] Add SAO Alicization Lycoris to LDN

### ISSUE THREAD

**Issue by ChaeZee** [Ryujinx/Ryujinx#5482]
### Overview

Having an online access will create an opportunity to connect  SAO Alicization Lycoris to the internet, whether it is WiFi or Ethernet. This will also help the players access the CUBE and SAO Shop online.

### Smaller details

Have an online access in order to connect and play with multiple players.

### Nature of request

Have an online access in order to connect and play with multiple players.

### Why would this feature be useful?

Having this feature allows the players to play SAO Alicization Lycoris online. This may also help the emulator have more access online and improve even better.

**Comment by ekuland** [comment]
The game itself does not support local play. LDN emulates local connections.
