### ISSUE TITLE
[Bug]Sword Art Online Alicization Lycoris could not connect to server

### ISSUE THREAD

**Issue by ChaeZee** [Ryujinx/Ryujinx#5487]
### Description of the issue

Every time I open the game, it always pop-up that it couldn't connect to server even I set up the emulator to connect to WiFi. I want to access the CUBE in the game but it doesn't have internet access.

### Reproduction steps

When I open the game it always pop-up in the middle of intro that it couldn't connect to server. Even when accessing the CUBE in game it says "A network error has occurred. 0011".

### Log file

[Ryujinx_1.1.969_2023-07-25_11-04-29.log](https://github.com/Ryujinx/Ryujinx/files/12156775/Ryujinx_1.1.969_2023-07-25_11-04-29.log)

### OS

Windows 10

### Ryujinx version

1.1.969

**Comment by MetrosexualGarbodor** [comment]
Ryujinx does not support connecting to Nintendo servers, and there's currently no plans to do so.
