### ISSUE TITLE
[Bug] Pikmin 1 Doesn't work. Stuck on start screen M1 Mac

### ISSUE THREAD

**Issue by imransilvake** [Ryujinx/Ryujinx#5488]
### Description of the issue

I started Pikmin 1 on M1 Macbook Air and it always get stuck on Start screen. It shows 0FPS.

### Reproduction steps

1. Start Pikmin 1 (NSP or XCI)
2. Press A
3. Game gets stuck

### Log file

-

### OS

13.4.1 (22F82)

### Ryujinx version

1.1.0

### Game version

1.0

### CPU

Apple M1

### GPU

Apple M1

### RAM

8GB

**Comment by spudpiggy** [comment]
why are you emulating the switch version of pikmin 1, just emulate the wii version

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4653
(Without a log file it will be hard to know the issue aswell)
Since it's a game specific issue, I close.
Thanks
