### ISSUE TITLE
[Bug] Console alway ON

### ISSUE THREAD

**Issue by Ryan2603** [Ryujinx/Ryujinx#5489]
### Description of the issue

![Clipboard01](https://github.com/Ryujinx/Ryujinx/assets/10262883/a27921e8-2ef7-4155-a7f0-b9cf894ad1b6)

unable to close, once you turn it off, Ryujinx also off.
Switched off in Ryujinx, but its still ON.

its won't started before ryujinx 1.1, but i maybe wrong.

### Reproduction steps

uncheck the show log console

### Log file

none

### OS

W11

### Ryujinx version

1.1

### CPU

AMD

### GPU

Nvidia

### RAM

64GB

**Comment by Foul-Tarnished** [comment]
Pretty sure you have to close and reopen Ryujinx for this setting to take effect...

Anyway it would just get hidden at startup

**Comment by Ryan2603** [comment]
> Pretty sure you have to close and reopen Ryujinx for this setting to take effect...
> 
> Anyway it would just get hidden at startup

nope, its just started up as a non-active application window only, its alive safe and sound.
i would't not call it a hidden..

**Comment by GamerzHell9137** [comment]
iirc this is a W11 issue. There's an option that needs to enabled or disabled on windows to make it hide it.

**Comment by Foul-Tarnished** [comment]
On Win11 last time I tried, the console would still open but would get hidden/close after a fraction of a second
So yeah the main window would be non-active

**Comment by CoolFrenchPerson** [comment]
> the console would still open but would get hidden/close after a fraction of a second

I can confirm this also happens to me on W11 but you can still click on the console in the taskbar which will make it reappear,
I think they're trying to say you can just do that (?)

**Comment by MutantAura** [comment]
Caused by windows terminal. 
See https://github.com/Ryujinx/Ryujinx/issues/3779
