### ISSUE TITLE
App icon proposal

### ISSUE THREAD

**Issue by Zabriskije** [Ryujinx/Ryujinx#5490]
Hi folks, since Discussions aren't enabled, I'm posting this here.

I would like to propose a new app icon for Ryujinx. I've made two versions: one matching the original Switch layout (element spacing has been corrected to be more pleasing) and another a bit more minimal/polished. I'm posting both just in case you find the minimal too minimal, but I'm cheering for that one since smaller elements are indistinguishable when seen in such a small size, imho. You can click on the images to see them in real size (1024x1024):

<img width="128" src="https://github.com/Ryujinx/Ryujinx/assets/101254295/a2aca61f-d9f4-4834-947e-c183f56ad20c"> <img width="128" src="https://github.com/Ryujinx/Ryujinx/assets/101254295/78a13da5-3ab0-4f01-bec5-9beeea32b839">

In case you're already happy with those, [here's a zip](https://github.com/Ryujinx/Ryujinx/files/12169851/Ryujinx-icon.zip) with PNG + ICNS + Iconset.

**Comment by AcK77** [comment]
Hi,
Thanks for your contribution, but I don't think this should take place in an issue.
We can speak about that on our discord (https://discord.com/invite/VkQYXAZ) at #interface-development channel.
In that way, I close it.
