### ISSUE TITLE
[Bug] GUI.RenderLoop error occurs infinitely while playing Fire Emblem Three Houses

### ISSUE THREAD

**Issue by elrod829** [Ryujinx/Ryujinx#5495]
### Description of the issue

The console gets a repeating error that reads:
`00:42:49.785 |E| GUI.RenderLoop Gpu UserCallback: Validation Error: [ VUID-vkCmdPipelineBarrier-pDependencies-02285 ] Object 0: handle = 0xd44b9c00004bce18, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x3936bc0c | vkCmdPipelineBarrier(): pImageMemoryBarriers[0].srcAccessMask (0x20) is not a subset of VkSubpassDependency srcAccessMask of subpass 0 of VkRenderPass 0xd44b9c00004bce18[]. Candidate VkSubpassDependency are pDependencies entries [0]. The Vulkan spec states: If fname:vkCmdPipelineBarrier is called within a render pass instance using a VkRenderPass object, the render pass must have been created with at least one subpass dependency that expresses a dependency from the current subpass to itself, does not include VK_DEPENDENCY_BY_REGION_BIT if this command does not, and has synchronization scopes and access scopes that are all supersets of the scopes defined in this command (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-pDependencies-02285)`

Log is about 1.6 GB, so I had to upload to Google Drive.

### Reproduction steps

Loading into Fire Emblem Three Houses version 1.2.0 with all 6 DLC installed. Running Vulkan (version 1.3.250.1) with Bilinear Upscale.

Loading Chapter 1: Three Houses' map.

### Log file

Due to Log size, [here is the Google Drive Link](https://drive.google.com/file/d/1dkqheG7qq7TOXDvGT2CU19GXJbhhGv3G/view?usp=sharing)

### OS

Windows 11

### Ryujinx version

1.1.968

### Game version

1.2.0

### CPU

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### GPU

Intel(R) Iris(R) Xe Graphics

### RAM

16GB

### List of applied mods

Alterations to 4 files containing character, class, growth, and item parameters.

**Comment by elrod829** [comment]
Google Drive upload has about 5 minutes ETA as of writing this.

**Comment by gdkchan** [comment]
I think those barrier errors appear on pretty much any game if you have validation layers enabled.

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/230
Since it's a game specific issue, I close.
Thanks
