### ISSUE TITLE
[Bug] Pikmin 4 showing up as "Unknown"

### ISSUE THREAD

**Issue by Noah-HalfSquid** [Ryujinx/Ryujinx#5496]
### Description of the issue

When I try to play Pikmin 4 it just shows up as an unknown rom, attempting to launch it crashes the software.

### Reproduction steps

All I did was put the rom in the games directory I have. then start up Ryujinx.

### Log file

[Ryujinx_1.1.0-ldn3.0.1_2023-07-27_17-28-23.log](https://github.com/Ryujinx/Ryujinx/files/12188854/Ryujinx_1.1.0-ldn3.0.1_2023-07-27_17-28-23.log)

### OS

Windows 10

### Ryujinx version

ldn3.0.1 (or 1.1.0)

### Game version

1.0

### Additional context?

I've also tested on the latest version, the same issue arises.

**Comment by OldManKain** [comment]
Key's are outdated,  Redump your keys.

```00:00:00.523 |E| Application : Unhandled exception caught: System.AggregateException: One or more errors occurred. (Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f)
 ---> LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f```
