### ISSUE TITLE
[Bug] Exception Codes:       0x0000000000000000, 0x0000000000000000

### ISSUE THREAD

**Issue by remember-5** [Ryujinx/Ryujinx#5497]
### Description of the issue

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ryujinx [12075]
Path:                  /Applications/Ryujinx.app/Contents/MacOS/Ryujinx
Identifier:            org.ryujinx.Ryujinx
Version:               1.1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-28 15:16:32.2094 +0800
OS Version:            macOS 13.4 (22F66)
Report Version:        12
Anonymous UUID:        A6F94E88-3366-1B5E-7C7C-4DA0A37A3F8E

Time Awake Since Boot: 3900 seconds

System Integrity Protection: enabled

Crashed Thread:        53

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80bb875b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80bb9572d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff80bb8e5e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff80bb8789a mach_msg + 19
4   CoreFoundation                	    0x7ff80bca206f __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff80bca0af0 __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff80bc9ff31 CFRunLoopRunSpecific + 560
7   HIToolbox                     	    0x7ff81571bdad RunCurrentEventLoopInMode + 292
8   HIToolbox                     	    0x7ff81571bbbe ReceiveNextEventCommon + 657
9   HIToolbox                     	    0x7ff81571b918 _BlockUntilNextEventMatchingListInModeWithFilter + 64
10  AppKit                        	    0x7ff80ed345d0 _DPSNextEvent + 858
11  AppKit                        	    0x7ff80ed3347a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
12  AppKit                        	    0x7ff80ed25ae8 -[NSApplication run] + 586
13  libAvaloniaNative.dylib       	       0x115b66a70 PlatformThreadingInterface::RunLoop(IAvnLoopCancellation*) + 118
14  ???                           	       0x11a0a41a9 ???
15  ???                           	       0x11a0a3129 ???
16  ???                           	       0x11a0a23e9 ???
17  ???                           	       0x119880090 ???
18  ???                           	       0x117e127e7 ???
19  ???                           	       0x117153861 ???
20  Ryujinx                       	       0x10dfdf839 CallDescrWorkerInternal + 124

...

Model: iMac19,1, BootROM 1916.40.6.0.0, 8 processors, 8-Core Intel Core i7, 2.9 GHz, 64 GB, SMC 2.46f12
Graphics: AMD Radeon RX 5500 XT, AMD Radeon RX 5500 XT, PCIe, 8 GB
Display: DELL U2720QM, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: BANK 1/ChannelA-DIMM1, 32 GB, DDR4, 2667 MHz, 0B15, JAD2666U1932
Memory Module: BANK 3/ChannelB-DIMM1, 32 GB, DDR4, 2667 MHz, 0B15, JAD2666U1932
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1771)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
PCI Card: AMD Radeon RX 5500 XT, gpu-controller, Slot-1@0,1,0/0,0/0,0/0,0
PCI Card: Navi 14 HDMI Audio, Audio Device, Slot-1@0,1,0/0,0/0,0/0,1
Serial ATA Device: ST4000VX015-3CU104, 4 TB
USB Device: USB30Bus
USB Device: USB2.0 Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: composite_device
USB Device: G502 HERO Gaming Mouse
USB Device: USB Keyboard
Thunderbolt Bus: 

### Reproduction steps

nothing

### Log file

[Ryujinx_1.1.969_2023-07-28_15-15-33.log](https://github.com/Ryujinx/Ryujinx/files/12191187/Ryujinx_1.1.969_2023-07-28_15-15-33.log)

### OS

MacOS

### Ryujinx version

1.1.969

### Game version

1.0.0

### CPU

i7-10700

### GPU

AMD Radeon RX 5500 XT

### RAM

64GB

**Comment by AcK77** [comment]
AMD GPU with macOS isn't currently supported. You can try to use bootcamp to run it.
Thanks
