### ISSUE TITLE
[Bug] Pikmin 4 crashes whenever loading second area.

### ISSUE THREAD

**Issue by kleokely** [Ryujinx/Ryujinx#5498]
### Description of the issue

Whenever I load into the second level, Blossoming Arcadia, the loading screen seems to work fine until the pikmin in the bottom right hand corner stops walking and the game closes with no error. After this happens the first time, the game creates a save loading into this area so the only thing I can load into is this crash. 

### Reproduction steps

This happened to my original save after 100% the first area. I created a second save and played until I was able to access the second area again and the same exact thing is happening with this new save. 

### Log file

[Ryujinx_1.1.969_2023-07-28_16-08-38.log](https://github.com/Ryujinx/Ryujinx/files/12197945/Ryujinx_1.1.969_2023-07-28_16-08-38.log)

### OS

Windows 10

### Ryujinx version

1.1.969

### Game version

1.0.1

### CPU

Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)

### GPU

NVIDIA GeForce GTX 1080

### RAM

32GB

**Comment by AcK77** [comment]
Based on the log file:
> ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!

I don't know if it's related to the savedata or the game dump. (Or about code which handle savedatas)

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4693
(Don't forget to use our latest build now since macos1 is outdated)
Since it's a game specific issue, I close.
Thanks
