### ISSUE TITLE
[Bug] Pikmin 4 crashing at random

### ISSUE THREAD

**Issue by CrystalCookie73** [Ryujinx/Ryujinx#5500]
### Description of the issue

Sometimes whenever loading in or out of an area, Ryujinx spontaneously exits

### Reproduction steps

Play the game and enter loading zones, eventually the emulator closes. Also seems to be easily reproducible by attempting to play Olimar's Shipwreck Tale

### Log file

[Ryujinx_1.1.969_2023-07-29_15-58-26.log](https://github.com/Ryujinx/Ryujinx/files/12207899/Ryujinx_1.1.969_2023-07-29_15-58-26.log)

### OS

Windows 10

### Ryujinx version

1.1.969

### Game version

1.1.0

### CPU

11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz, 2496 Mhz, 8 Core(s), 16 Logical Processor(s)

### GPU

NVIDIA GeForce RTX 2060

### RAM

32GB

**Comment by OldManKain** [comment]
Known Issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/4693
