### ISSUE TITLE
[Bug] KLONOA Phantasy Reverie Series - Crash when loading either game

### ISSUE THREAD

**Issue by Ritaku02** [Ryujinx/Ryujinx#5501]
### Description of the issue

The game boots fine, but when it tries to load either game, Ryujinx crashes.

### Reproduction steps

Simply boot up the game and attempt to load either Klonoa 1 or 2.

### Log file

[Ryujinx_1.1.970_2023-07-29_17-47-30.log](https://github.com/Ryujinx/Ryujinx/files/12208309/Ryujinx_1.1.970_2023-07-29_17-47-30.log)

### OS

Windows 10

### Ryujinx version

1505

### Game version

1.0

### CPU

Ryzen 7 5800X3S

### GPU

RTX 2070

### RAM

32GB

### List of applied mods

None

**Comment by Eli0t77** [comment]
Maybe a regression, I remember playing the demo on Ryu 1.1.109 (opengl) and it ran without problems. I got the full game on pc in the end

**Comment by AcK77** [comment]
The crash seems related to corrupted savedata, delete it and try again.

**Comment by Ritaku02** [comment]
Deleting the save data didn't work, and when I first reported the crash I had ran the game for the first time on Ryujinx with no prior save data.

**Comment by AcK77** [comment]
First crash is because the game require an internet connection, what if you disable it in Ryujinx settings?

**Comment by AcK77** [comment]
Could you please report that in our Game Compatibility List: https://github.com/Ryujinx/Ryujinx-Games-List/issues/new/choose
Thanks.
