### ISSUE TITLE
[Bug + Solution] Story of Season Pioneers of the Olive Town (010082E012A84000) Stuck Loading Black Screen during Spring 14 to Spring 15

### ISSUE THREAD

**Issue by Legarad** [Ryujinx/Ryujinx#5505]
### Description of the issue

The bug is due to 3 DLCs that seem to have anti-backup measures which are Twillight Isle Expansion Pack (010082E012A85001), Windslept Falls Expansion Pack (010082E012A85002) and Terracotta Oasis Expansion Pack (010082E012A85003) . By deactivating those three DLCs the game works correctly also another solution is to downgrade the game to 1.0.8. This Bug also happens on Nintendo Switch with CFW that has the mentioned DLC installed as backup.

### Reproduction steps

See the previous message. The registry that I will add will be both working and not working the game.

### Log file

[Ryujinx_1.1.970_2023-07-30_16-08-45.log](https://github.com/Ryujinx/Ryujinx/files/12210138/Ryujinx_1.1.970_2023-07-30_16-08-45.log)

### OS

Windows 11

### Ryujinx version

1.1.970

### Game version

1.1.0

### Additional context?

https://gbatemp.net/threads/sos-pioneers-of-olive-town-infinite-loading-screen-before-egg-hunt.609068/
https://gbatemp.net/threads/story-of-seasons-pioneers-of-olive-town-freezin-on-egg-hunt.608457/

**Comment by Legarad** [comment]
More like game optimization problems on Nintendo Switch, I found a news where the Japanese complained about the loading time of this version before the DLC, the developer official blog says that the "some" loading screen were fixed  in the Japanese update 1.0.3.

**Comment by AcK77** [comment]
So I state that as a game issue.
