### ISSUE TITLE
[Bug]Pokémon Brilliant Diamond The game scene has shadow error

### ISSUE THREAD

**Issue by macOSWk** [Ryujinx/Ryujinx#5506]
### Description of the issue

 Pokémon: Let's Go, Eevee! and Pokémon Brilliant Diamond The game scene has shadow error

and Occasional software flashbacks

<img width="1440" alt="截屏2023-07-31 17 45 16" src="https://github.com/Ryujinx/Ryujinx/assets/86730293/34e93c1f-b4be-40ed-9d63-d1817fa8b943">

### Reproduction steps

as mentioned above

### Log file

[Ryujinx_ 1.1.0-macos1_2023-07-31_17-31-52.log](https://github.com/Ryujinx/Ryujinx/files/12213951/Ryujinx_.1.1.0-macos1_2023-07-31_17-31-52.log)

### OS

macos Ventura 13.4.1 (c)

### Ryujinx version

Ryujinx 1.1.0-macos1

### Game version

Pokémon Brilliant Diamond  1.3.0 and  Pokémon: Let's Go, Eevee! 1.0.2

### CPU

2.3 GHz quad-core Intel Core i5

### GPU

Intel Iris Plus Graphics 655 1536 MB

### RAM

16GB

### List of applied mods

none

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3776
(Don't forget to use our latest build now since `macos1` is outdated)
Since it's a game specific issue, I close.
Thanks
