### ISSUE TITLE
New Pokemon Snap random crashing at picture slection or grading [Bug]

### ISSUE THREAD

**Issue by tbezaire** [Ryujinx/Ryujinx#5510]
### Description of the issue

happens randomly but always while in picture selection, or while photos are being graded. 
changed around graphics settings and it always seems to happen eventually.
sometimes itll happen on the first excursion, and sometimes itll happen after 3 or 4 excursions. it might be happening more often during nighttime runs, but i cant be sure. 

### Reproduction steps

happens randomly during playing, always at either photo selection or photo grading.

### Log file

[Ryujinx_1.1.972_2023-07-31_14-51-34.log](https://github.com/Ryujinx/Ryujinx/files/12222227/Ryujinx_1.1.972_2023-07-31_14-51-34.log)

### OS

windows 11

### Ryujinx version

1.1.972

### Game version

2.0.1

### CPU

AMD ryzen 9 7900X

### GPU

AMD Radeon 6950 XT

### RAM

32GB

### Additional context?

![Ryujinx_settings_screenshot_system](https://github.com/Ryujinx/Ryujinx/assets/124899626/74c8400f-3306-4a7d-bc53-a99e39914e43)
![Ryujinx_settings_screenshot_graphics](https://github.com/Ryujinx/Ryujinx/assets/124899626/8585912f-56a9-488e-b876-21badc840c7d)

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3669
Since it's a game specific issue, I close.
Thanks
