### ISSUE TITLE
[Bug] Zelda BotW Camera Glitch

### ISSUE THREAD

**Issue by xespi** [Ryujinx/Ryujinx#5511]
### Description of the issue

The game runs ok, but there is a glitch only on the game, we playing, I use the Zelda Camera function to take pictures, in the preview the picture are ok, and looks ok, but if I go to de gallery all the pictures I've taken are glitched. One particular detail about the glitch is all the glitches show partial images of the Zelda already loaded pictures (those are not taken by the player, it comes with the game)  

Game saving runs ok. 
I take a look at the User Saved folder, and the glitched images are there. so I discard the idea of lack on write permissions to the game

Here, some captures of the game: 

![Screen Shot 2023-07-31 at 21 38 35](https://github.com/Ryujinx/Ryujinx/assets/10585314/0b36a059-89f0-4852-b7fd-968cf1fc814c)
![Screen Shot 2023-07-31 at 21 39 26](https://github.com/Ryujinx/Ryujinx/assets/10585314/b6f29d6b-79ad-4b4c-820d-379f5569e4f7)

Here a saved file: 
![pict_008](https://github.com/Ryujinx/Ryujinx/assets/10585314/7f317ad3-b924-40cb-924e-6e6665a4a40f)

Thank you all, 

### Reproduction steps

Going ahead on the game, after getting done a few taks, you can get the feature "Camera" on the Zelda's device "SheiKa Tablet"

In the moment you get this feature, you are asked to take a picture, following the steps I get the picture, as I said the preview looks fine, but the saved files are all corrupted. 

### Log file

[Ryujinx_ 1.1.0-macos1_2023-07-31_21-48-21.log](https://github.com/Ryujinx/Ryujinx/files/12223397/Ryujinx_.1.1.0-macos1_2023-07-31_21-48-21.log)

### OS

MacOS Monterrey 12.6.1

### Ryujinx version

1.1.0-Macos1

### Game version

Zelda BotW 1.6.0

### CPU

M1

### RAM

8GB

### List of applied mods

v1.6.0

[60 FPS]
04000000 01614954 52800008
04000000 01614D84 5287F008
04000000 01614DB0 52800020
04000000 01614DA4 12000021

[Default 30 FPS]
04000000 01614954 39497E68
04000000 01614D84 1E380008
04000000 01614DB0 B9423800
04000000 01614DA4 12001C21

### Additional context?

It is my first game on Ryujinx, and currently the only game I've installed

**Comment by xespi** [comment]
Thank you so much for your time, 

I've recently tested the latest MacOS universal release, but unfortunately, the camera bug still persists. 
Would it be helpful if I shared the log file or any other information?

**Comment by AcK77** [comment]
The wrong "in game captures" are stored in the savedata, so even if the issue is fixed, they will stay like that forever.
It's probably due to your applied mods or something.
Is anyone under macOS can reproduce it ?

**Comment by joroldan** [comment]
> The wrong "in game captures" are stored in the savedata, so even if the issue is fixed, they will stay like that forever. It's probably due to your applied mods or something. Is anyone under macOS can reproduce it ?

No mods and same issue at least with the build from 15 days ago (it is when I played). MacBook Pro 14 M2 - macOS Ventura. Indeed it was reported last November in issue #3917.

**Comment by xespi** [comment]
Thank you both for taking time to reply to this

> The wrong "in game captures" are stored in the savedata, so even if the issue is fixed, they will stay like that forever.
Thank you Ack77, yes, I understand that already saved pictures are stored glitched. I've found the files on my HDD, so I take new pictures on each test to try if this was fixed.

**Comment by AcK77** [comment]
It's already reported at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/86
Since it's a game specific issue, I close.
Thanks
