### ISSUE TITLE
[Bug]Press 'check for update' or 'about' with no responsed 

### ISSUE THREAD

**Issue by dzrforever** [Ryujinx/Ryujinx#5513]
### Description of the issue

Everytime I Press 'check for update' or 'about' with no responsed. And the console said '|W| Ui ShowAsync: Content dialog overlay failed to populate. Default value has been returned.'

### Reproduction steps

 Press 'check for update' or 'about' 

### Log file

[Ryujinx_1.1.967_2023-08-01_15-04-07.log](https://github.com/Ryujinx/Ryujinx/files/12225617/Ryujinx_1.1.967_2023-08-01_15-04-07.log)

### OS

Windows 11

### Ryujinx version

1.1.967

### CPU

 AMD Ryzen 7 3700X 8-Core Processor ; 16 logical

### GPU

NV 2070super

### RAM

32GB

**Comment by OldManKain** [comment]
This issue was fixed in 1.1.968. 
You can get it here https://ryujinx.org/download.
