### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by RaijinXBlade** [Ryujinx/Ryujinx#5523]
### Overview

Yuzu has a feature called 'Multicore CPU Emulation'. I'm simply requesting something like that.

### Smaller details

I am not sure what the specifics are. It implies it uses multiple cores with it enabled, but I'm not sure why it's labeled as 'emulation'. Whatever the case, it could be implemented as a toggle setting.

### Nature of request

I got curious, and tested the Paldea Crater area in Pokemon Scarlet, where my frame rate there gets down to around 10fps at the worst, and never above 18fps at best, in Ryujinx.
In Yuzu, with the Multicore option disabled, I get around the same performance, if slightly better. Around 15fps at worst, and around 22fps at best. With that option enabled however, the game runs perfectly. I figure Ryujinx simply doesn't have an equivalent to that yet.

### Why would this feature be useful?

Significant performance increases. It would be especially great to see before the next LDN build as well.

**Comment by MetrosexualGarbodor** [comment]
[Added in 2018](https://github.com/Ryujinx/Ryujinx/pull/393#issuecomment-420114033)

**Comment by RaijinXBlade** [comment]
> [Added in 2018](https://github.com/Ryujinx/Ryujinx/pull/393#issuecomment-420114033)

Sorry, then I'm not sure what the setting does in Yuzu then. Clearly it's something different if it increases performance so dramatically though.

**Comment by gdkchan** [comment]
Are you asking for a option to disable multi-core emulation then? Because the emulator already has it and its always enabled. There's no option to disable it since there's no point in doing that (other than maybe fixing a few games that have multithreading related issues).

**Comment by RaijinXBlade** [comment]
If Ryujinx has that already, then what I'm saying is, my OP is wrong and I have no clue what Yuzu's equivalent option does, if it's even doing the same thing in the first place.

**Comment by GamerzHell9137** [comment]
> If Ryujinx has that already, then what I'm saying is, my OP is wrong and I have no clue what Yuzu's equivalent option does, if it's even doing the same thing in the first place.

It is

**Comment by RaijinXBlade** [comment]
> > If Ryujinx has that already, then what I'm saying is, my OP is wrong and I have no clue what Yuzu's equivalent option does, if it's even doing the same thing in the first place.
> 
> It is

Understood, and sorry for the confusion on my part then. I suppose in that case, this should have been a request for *insert whatever Yuzu is doing to have such significant performance increases* option, whatever that even is :\

**Comment by riperiperi** [comment]
“Make emulator faster” isn’t a valid feature request.

**Comment by RaijinXBlade** [comment]
> “Make emulator faster” isn’t a valid feature request.

Haha, yes. I was simply saying "well, in that case, I guess I don't know what I should have requested".
