### ISSUE TITLE
Zelda TOTK save file corrupted [Bug]

### ISSUE THREAD

**Issue by Andmon** [Ryujinx/Ryujinx#5533]
### Description of the issue

During a game the power has gone out and my PC obviously turned off. 
On reboot, all saves files are corrupted. 
I tried to physically go to the save folder and I find the following structure: 
0000000000000000 > 0 > slot_00 (and later) and 
00000000000000000 > 1 > slot_00 (and later). 
In all these folders the progress file is 2245KB size but opening it with a text editor consists only of spaces. 
Is it possible to somehow recover my 180 hours of gameplay?

### Reproduction steps

During a game the power has gone out and my PC obviously turned off.
The game wasn't in a save point, I was in external exploration.

### Log file

There are no log files present.

### OS

Windows 11

### Ryujinx version

1.1.966

### Game version

1.1.0

### CPU

AMD Ryzen 7 5800 X

### GPU

nVidia GeForce RTX 3080

### RAM

32 Gb

**Comment by OldManKain** [comment]
No there is not the only thing I can recommend to do is to keep backups of your saves in a safe place on your PC.
