### ISSUE TITLE
Cant Progress past this part of rain code [Eu version] due to freeze no matter what I do 

### ISSUE THREAD

**Issue by ThatGuyRai** [Ryujinx/Ryujinx#5534]
### Description of the issue

I get to this one section in the mystery labrynth in Ch0 and it crashes right after I select red herring key, the text freezes and game crashes so fast i cant react. I checked open gl and vulkan too, no luck and im on a 6800xt latest drivers. So in turn I tried yuzu and boom! same thing at the same spot EXCEPT it full on freezes there, like only music plays with a still screen. I dont get why this is happening and i cant progress cuz of it (pictured below)
![image](https://github.com/Ryujinx/Ryujinx/assets/71162577/626c0890-12db-4e08-8e97-c924a281fdc4)

### Reproduction steps

Go up to the mystery door in ch0 when youre pointing out zilchs death being a red herring then select, the next dialogue will crash (on ryu) and or freeze the game to an unplayable/uninteractable state yet will still play music (on yuzu).

### Log file

[Ryujinx_1.1.974_2023-08-05_11-37-03.log](https://github.com/Ryujinx/Ryujinx/files/12267614/Ryujinx_1.1.974_2023-08-05_11-37-03.log)

### OS

Windows 10

### Ryujinx version

1.1.974

### Game version

1.0.0 (same bug happens in 1.3.0/1.3.1)

### CPU

5800x ryzen 7

### GPU

6800xt - on driver update 23.7.2

### RAM

 32 Gb DDR4 3200Mhz

### List of applied mods

1440p mod, and 60 fps mod

### Additional context?

I am supposed to be able to advance the dialogue as normal during this part but the game full on crashes

**Comment by gdkchan** [comment]
Have you tried without mods and cheats?

**Comment by ThatGuyRai** [comment]
> Have you tried without mods and cheats?

just tried no mods and switched to US version of the game and it seems to have fixed, imma add the mods again and see if the eu version was the issue

**Comment by ThatGuyRai** [comment]
Nope! it was the 1440p mod! a particle effect happens after that text, I presume the 1440p mod broke it causing a crash, Ill disable the 1440p mod for now and if the game crashes like that again ill know to disbale it for a save point!

**Comment by gdkchan** [comment]
I guess because the resolution is higher, the game is using more memory and running out of it. It might work with the "Use alternative memory layout" aka "Expand DRAM size to 6GB" option which increases emulated memory size, but I would recommend playing with that option disabled.

**Comment by ThatGuyRai** [comment]
That explains why the game Ram leaks to 100% usage on the crash
