### ISSUE TITLE
[Bug] Cheats not working for Fire Emblem Three Houses

### ISSUE THREAD

**Issue by MilarvozM** [Ryujinx/Ryujinx#5535]
### Description of the issue

Have obtained cheats from various sources but none worked. Maximum gold/renown, all +1 when level up were the main cheats I wanted to use and found not working.
I have tried turning off then on before launch, mid-game and all sorts of that. Maybe I am just missing something incredibly obvious.
![image](https://github.com/Ryujinx/Ryujinx/assets/34495348/d9371510-8baf-4c02-b724-2d7209142c63)

### Reproduction steps

Load the mods and load the save files. Can test the maximum gold/renown at the point I think.
[save.zip](https://github.com/Ryujinx/Ryujinx/files/12268165/save.zip)

### Log file

[Ryujinx_1.1.974_2023-08-05_13-50-33.log](https://github.com/Ryujinx/Ryujinx/files/12268161/Ryujinx_1.1.974_2023-08-05_13-50-33.log)

### OS

Windows 11 Education

### Ryujinx version

1.1.974

### Game version

1.2.0

### CPU

i7-13700HX

### GPU

Nvidia RTX 4070

### RAM

32 GB

### List of applied mods

https://gbatemp.net/threads/fire-emblem-three-houses-general-hacking.544144/
[010055D009F78000.zip](https://github.com/Ryujinx/Ryujinx/files/12268175/010055D009F78000.zip)

**Comment by MetrosexualGarbodor** [comment]
Please use our [Discord](https://discord.gg/ryujinx) for general support queries.
Thanks.
