### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Guri1Surka** [Ryujinx/Ryujinx#5536]
### Description of the issue

I don't know if this is really a bug or if anyone will help me here. But I can't find any where else to go for help. So for whatever reason my emulator doesn't launch when I double click a game. I have sat and waited for 30 minutes nothing comes up. It used work good. One time it did launch the game I selected but it took over an hour and it was super slow like really really slow. But after that no good. I see it loading up the files at the button right but that's about it. I had already updated the emulator I also updated the game to current version. I tried discord but there isn't anything on there. I have close the log widows in order to shut down the emulator because the mouse disappears like it would normally do when a game launches. None of my games go through. Also there has been at least 3 or 4 updates since this problem has happened.

### Reproduction steps

I click onto the ryujinx app and it launches with no problem. I doubled click a game and at the bottom right I see the shaders being loaded and the mouse disappears and normally the game goes. Then nothing happens after that. I close the app by closing the log windows because the emulator won't close if I just click the X button. It will ask if I want to close it and I click yes but nothing happens. It will only close if I close the log window. I relaunch emulator again try a different game and I get the same results. 

### Log file

[Ryujinx_1.1.974_2023-08-05_07-51-07.log](https://github.com/Ryujinx/Ryujinx/files/12268598/Ryujinx_1.1.974_2023-08-05_07-51-07.log)

### OS

Windows 11 Home

### Ryujinx version

1.1.974

### CPU

11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz   3.50 GHz

### GPU

Nvidia Rtx 3070

### RAM

32 gb

**Comment by MetrosexualGarbodor** [comment]
Uninstall third party antivirus software. In the future, please use our [Discord](https://discord.gg/ryujinx) for general support queries.
Thanks.
