### ISSUE TITLE
[Feature Request] Add direct joystick reaction to the UI of input configuration dialog

### ISSUE THREAD

**Issue by dragonation** [Ryujinx/Ryujinx#5539]
### Overview

Make UI realtime reaction in input configuration dialogs, while joystick state changed.

### Smaller details

If users pressing buttons in the joysticks, the UI will make button red, or some colors to indicate what will really take effects while playing games?
If users moving sticks in the joysticks, the UI will make stick drawing moved, or some colors to indicate what will really take effects while playing games?
If users pushing triggers in the joysticks, the UI will make trigger force updated, or some colors to indicate what will really take effects while playing games?

### Nature of request

The JoySitck configuration is complex to basic user, sometimes not obviously if config is correct.
Is it possible to show the button states or stick states in the settings dialog of input section?
So users can clearly knows what did they configured for input mappings, and whether the configs is correct.
Especially for the stick rotations, and joycon side configs.
And what's more, multiple joysticks will be confused if they share the same name, only with index different. if realtime reaction will be shown in the dialogs, users does not need to tested correct mappings in game.

### Why would this feature be useful?

Complex stick mapping is generally confusing, if the joystick is advanced with macros and hardware remapping.
Users sometimes confused with the multiple player and joystick mapping. which joystick is player 1, or player 2?

**Comment by AcK77** [comment]
Duplicated of #2586
