### ISSUE TITLE
[Bug] macOS incorrect resource disposal on exit

### ISSUE THREAD

**Issue by siegmund-heiss-ich** [Ryujinx/Ryujinx#5542]
### Description of the issue

CMD+Q (for quitting the current active software) works as intended if you are in Ryujinx startup menu.
But when you trigger it while you are running a game, Ryujinx gets stuck.
Surely there is a deadlock somewhere that I can't resolve due to skill issues.

(Thanks to our disposal expert, who will fix it in a future coffee break 🤝)

### Reproduction steps

Open Ryujinx.Ava, start any Game and try to quit Ryujinx with Cmd+q.

### Log file

Because the application doesn't crash, there is no helpful information in the logfile.

### OS

MacOS Ventura 13.4.1 

### Ryujinx version

1.1.975

### CPU

M1 Pro

### GPU

M1 Pro

### RAM

16 GB

**Comment by AcK77** [comment]
Closed in favor of #5689

**Comment by siegmund-heiss-ich** [comment]
I don't see the reason why this issue would be related to #5689. 
This is a different story as you can see in the descriptions.
But someone will fix it anyways..
