### ISSUE TITLE
[Bug] Cannot open controller configuration

### ISSUE THREAD

**Issue by Polymaker** [Ryujinx/Ryujinx#5543]
### Description of the issue

I encountered the problem after updating Ryujinx today. 

Upon clicking the "Configure" button in the "Input" tab, the "Controller Settings" window appears completely white, causing Ryujinx to freeze. Consequently, my PC experiences significant lag, and I am forced to terminate the Ryujinx process.

I don't remember which version I had before updating so I first attempted downgrading to version 1.1.965 but I still had the problem. I downgraded to version 1.1.950 and now the input configuration works as expected.

Nothing is printed in the console window and the log does not contains anything after the initial startup.

### Reproduction steps

1. Open Ryujinx
2. Go to Options > Settings
3. Click the Inputs tab then click the Configure button for Player 1

### Log file

The log file does not contain anything related to the problem.

### OS

Windows 10

### Ryujinx version

1.1.975

### CPU

i7-7700K

### GPU

RTX 4070

### RAM

16GB

**Comment by Mewzapchu** [comment]
same here, it written this

(Ryujinx:18488): Pango-WARNING **: 11:34:02.286: couldn't load font ""Helvetica-Bold" Not-Rotated 32", falling back to "Sans Not-Rotated 32", expect ugly output.

and then my computer gets supper slow, i have good cpu and nvidia rtx 4060 ti

**Comment by Polymaker** [comment]
First of all the issue kind of disappeared on it's own, but back when it was happening I tested the Avalonia build and I had the same result.
I honestly don't know what fixed the problem. I can't speak for @Mewzapchu but for me the issue is resolved and I could close the issue.

**Comment by Mewzapchu** [comment]
i tried yuzu and the issue was completely gone
