### ISSUE TITLE
The text is all weird on Persona 5 Royal[Bug]

### ISSUE THREAD

**Issue by Maxxed-0ut** [Ryujinx/Ryujinx#5544]
### Description of the issue

The dialog boxes show text covered in small images and/or changes to special characters when going through the dialog or anything else text related
![ryujinx_capture_2023-08-05_13-35-35](https://github.com/Ryujinx/Ryujinx/assets/141483483/d38d1a1c-44e7-4b8f-8444-b44debb7771a)
The game was normal two weeks ago before I had updated Ryujinx to its current version.

### Reproduction steps

Literally talk to any character in the game. It starts with normal text at first then it gets progressively worse and worse with each new dialog box.

### Log file

[Ryujinx_1.1.977_2023-08-08_14-36-14.log](https://github.com/Ryujinx/Ryujinx/files/12289504/Ryujinx_1.1.977_2023-08-08_14-36-14.log)

### OS

Windows 11

### Ryujinx version

1.1.9777

### CPU

i5-11300H

### GPU

NVIDIA GeForce RTX 3050

### RAM

8GB

**Comment by gdkchan** [comment]
It looks fine here
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/67f775c5-68b9-4089-9ae4-cf3d829a2bd2)

**Comment by GamerzHell9137** [comment]
Whenever reporting issues always:

1. Use the latest version of Ryujinx
2. Update game if possible
3. Update your GPU drivers
4. Use default Ryujinx settings
5. Dont use upscale and emulate at native resolution
6. Do not use any mods

If its fine on native but not one upscaled then its a upscaling issue, but if you're doing any of the above wrong then something in the setup is causing the issue.

I've tried the game too and i couldn't make it trigger the issue you're having.

**Comment by AcK77** [comment]
Additionally to the comment above, your log file is empty so we can't provide you more help.
I suggest your to come to our discord for support.
I can reopen this issue if anyone succeed to reproduce it.
