### ISSUE TITLE
[Bug] UI translation should update

### ISSUE THREAD

**Issue by doyenho** [Ryujinx/Ryujinx#5550]
### Description of the issue

I have updated the crowdin Chinese translation, when does the crowdin.yml do?
「嘛好」should be 「確定」，and others...

### Reproduction steps

Avalonia UI

### Log file

None

### OS

Windows 10, 64 bit

### Ryujinx version

1.1.979 Avalonia

**Comment by Schaefers** [comment]
https://github.com/Ryujinx/Ryujinx/pull/4758
