### ISSUE TITLE
Hew Draw Remix not loading after updating from Ryujinx 1.1.976 to 1.1.979

### ISSUE THREAD

**Issue by heyha1400** [Ryujinx/Ryujinx#5552]
### Game Name

Super Smash Bros. Ultimate*

### Game Update Version

13.0.1

### Emulator Build Version

1.1.979

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *i7 12700K*
- ##### GPU: *Intel Arc A770*
- ##### RAM: *32GB*

### Game State

It just loads base smash ultimate instead of Hew Draw Remix on the newer Ryujinx version.
After downloading 1.1.976 again it works correctly.

**Comment by OldManKain** [comment]
Save [THIS FILE](https://cdn.discordapp.com/attachments/410208534861447170/1139219391611949096/legacy_discovery) to <your ryujinx directory>/sdcard/ultimate/arcropolis/config/some numbers/some numbers/
![image](https://github.com/Ryujinx/Ryujinx/assets/47503099/5fbd5f96-7312-4aac-b606-f7b8b7e041d8)

**Comment by heyha1400** [comment]
If I place the file here, the emulator crashes to desktop even with both HDR and Ryujinx clean installed on 1.1.980 and 1.1.981.

These are the only folders there.
![image](https://github.com/Ryujinx/Ryujinx/assets/105302028/5a493443-27f6-4771-8e94-0789244d7bde)

**Comment by OldManKain** [comment]
Look at my screenshot you put it in the wrong place there should be at least 20 numbers in the directories you put it in.

**Comment by heyha1400** [comment]
I know what you mean, and forgot to add this to my earlier post (sorry)... there are no other folders there, apart from the 1 with the 0 folder. 
If I make folders named like yours in the screenshot, the emulator seems to ignore it, boot base Smash Ultimate and makes the '1'and '0' folders again.
![image](https://github.com/Ryujinx/Ryujinx/assets/105302028/2597b5fd-21f5-4dda-b1cc-a74d4edee3cf)

**Comment by Raytwo** [comment]
> Look at my screenshot you put it in the wrong place there should be at least 20 numbers in the directories you put it in.

These are UID values, which Ryujinx replaces with single digit numbers, so it is actually correct.

**Comment by OldManKain** [comment]
Seems you have to remove sdcard/atmosphere/contents/0100000000000013 for HDR to work, something to do with Sysmodule. Anyway this is a support issue and should be discussed in our [Discord](https://discord.gg/ryujinx.)
