### ISSUE TITLE
[Feature Request] Game name in screenshot file name

### ISSUE THREAD

**Issue by redactedscribe** [Ryujinx/Ryujinx#5553]
### Overview

Currently screenshots are automatically named `ryujinx_capture_<date>.png`. It would be ideal if the game's name would be included in the screenshot's file name.

### Smaller details

-

### Nature of request

-

### Why would this feature be useful?

-

**Comment by AcK77** [comment]
It could be nice to get a more descriptive request.
IMO, you can just look the thumbnails to know which game is it, it's a bit useless to get the game name in the screenshot file name.

**Comment by Kfollen93** [comment]
I will take on this one.

Should have a PR shortly. I have the code implemented, but reviewing the process as this is my first contribution to this project.
