### ISSUE TITLE
Ryujinx crashing when I try to play a game

### ISSUE THREAD

**Issue by poopdadoo** [Ryujinx/Ryujinx#5565]
### Description of the issue

Whenever I try to open a game (Celeste and Game Builder Garage), Ryujinx crashes. I've seen things like this happening on Reddit(There are ways to fix this bug there), whenever I do what it says to it still doesn't work and I don't know why.

### Reproduction steps

Just Open a game and it crashes.

### Log file

[Ryujinx_ 1.1.0-macos1_2023-08-13_08-29-17.log](https://github.com/Ryujinx/Ryujinx/files/12329536/Ryujinx_.1.1.0-macos1_2023-08-13_08-29-17.log)
[Ryujinx_ 1.1.0-macos1_2023-08-13_08-35-30.log](https://github.com/Ryujinx/Ryujinx/files/12329537/Ryujinx_.1.1.0-macos1_2023-08-13_08-35-30.log)
[Ryujinx_ 1.1.0-macos1_2023-08-13_08-48-38.log](https://github.com/Ryujinx/Ryujinx/files/12329538/Ryujinx_.1.1.0-macos1_2023-08-13_08-48-38.log)

### OS

MacOs Big Sur 11.7.8

### Ryujinx version

1.1.0-macos1

### Game version

both are 1.0.0(latest version)

### CPU

2.8 GHz Dual-Core Intel Core i7

### GPU

Intel Iris 1536 MB

### RAM

8GB

**Comment by MetrosexualGarbodor** [comment]
Your system does not meet the minimum requirements to run Switch games.
