### ISSUE TITLE
[Bug] Controller profile are available for only one controller

### ISSUE THREAD

**Issue by 721560273** [Ryujinx/Ryujinx#5571]
### Description of the issue

When using a third-party controller to play a game that requires joycon single controller, "sr" and "sl" cannot save the key changes when there are more than 2 controllers

### Reproduction steps
In the Crazy Rabbit Adventure Party, the third-party controller needs to be simulated as a joycon single controller to play the game. 1 player can save the changes of the sr sl button, and restore the default unbound after changing the srsl in the case of multiple controllers

### Log file

00:00:00.055 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.060 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.060 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.061 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.062 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.063 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.064 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x13C2
00:00:00.064 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.065 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.065 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.068 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.077 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.078 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.078 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.078 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.078 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.078 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.078 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.078 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.079 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.079 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.080 |I| Configuration LogValueChange: MemoryManagerMode

### OS

win10

### Ryujinx version

3.1.3

**Comment by AcK77** [comment]
This report an issue from LDN 3.1.3 build related to input.
Please use the master build since it's more up-to-date and try to reproduce this issue, if it still exists, reopen an issue.
Thanks.
