### ISSUE TITLE
[Bug] Bayonetta 3 some texture become dark.

### ISSUE THREAD

**Issue by zhm86** [Ryujinx/Ryujinx#5592]
### Description of the issue

Some textures become dark, but not completely black.
Texture of face of bayonetta, walls and storefront.
I tried both texture recompression on and off.
![switch](https://github.com/Ryujinx/Ryujinx/assets/16450203/3f26de1b-fd03-4912-a34a-838a0855dc7c)
![ryujinx-1 1 997](https://github.com/Ryujinx/Ryujinx/assets/16450203/4d72c4fe-be4d-42b2-91c3-56f9ad0d2ca4)

### Reproduction steps

Enter Chapter 11 - A Familiar Dance

### Log file

[Ryujinx_1.1.997_2023-08-18_22-25-52.log](https://github.com/Ryujinx/Ryujinx/files/12380372/Ryujinx_1.1.997_2023-08-18_22-25-52.log)

### OS

Windows 10

### Ryujinx version

1.1.997

### Game version

1.2.0

### CPU

e3-1231 v3

### GPU

nvidia GTX 1650 4GB VRAM

### RAM

10GB RAM

### List of applied mods

None

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4129
Since it's a game specific issue, I close.
Thanks
