### ISSUE TITLE
[Bug] Ryujinx replaces the downloaded ryuSAK shaders when opening a game.

### ISSUE THREAD

**Issue by Zard-Studios** [Ryujinx/Ryujinx#5593]
### Description of the issue

Hi, I'm facing an issue with Ryujinx. I'm attempting to play Super Mario 3D World with a friend locally, but every time we try, we encounter a problem where 2/3 of the frames are dropped, leading to a communication error. To address this, I downloaded RyuSAK to acquire precompiled shaders for the entire game. However, after downloading all the game's shaders and launching Super Mario, Ryujinx seems to delete and recompile my custom shaders from scratch.

### Reproduction steps

I open RyuSAK, select the game (imported by Ryujinx), and click the download all shaders button for the game. Then I start Ryujinx and start SM3DW. Shaders load unusually fast, which raises suspicions. I pause the emulation, go to the folder where the shaders are stored and notice that the file dates appear very recent and the file sizes are surprisingly small.

### Log file

[Ryujinx_ 1.1.0-macos1_2023-08-18_15-45-16.log](https://github.com/Ryujinx/Ryujinx/files/12380405/Ryujinx_.1.1.0-macos1_2023-08-18_15-45-16.log)

### OS

MacOS 13.4 Ventura

### Ryujinx version

1.1.0 Avalonia 0.10

### Game version

1.1.0

### CPU

M1 Pro

### RAM

16 GB

**Comment by Zard-Studios** [comment]
why

**Comment by JustinSUF** [comment]
downloading shaders are considered piracy, they aren't going to help you.
