### ISSUE TITLE
Red Dead Redemption flickering issues on AMD gpu's[Bug]

### ISSUE THREAD

**Issue by illlas** [Ryujinx/Ryujinx#5596]
### Description of the issue

There's a weird flickering issue when playing on vulkan with an AMD gpu. usually happens with npc's, horses, cutscenes, and in places like Macfarlane's Ranch and Armadillo. 

https://github.com/Ryujinx/Ryujinx/assets/142617316/3e6989a7-e48e-415d-b799-2778eaab9fc7

### Reproduction steps

play with an AMD gpu with Vulkan on. I cannot reproduce it everytime but it happens often with horses, npc's, and in Macfarlane's Ranch.

### Log file

[Ryujinx_1.1.997_2023-08-19_17-50-20.log](https://github.com/Ryujinx/Ryujinx/files/12385756/Ryujinx_1.1.997_2023-08-19_17-50-20.log)

### OS

Windows 10

### Ryujinx version

1.1.997

### CPU

Ryzen 5 5600

### GPU

RX 6600XT

### RAM

16gb DDR4 3200mhz

### List of applied mods

none

**Comment by superproxy420** [comment]
I have the same issue on my RX570 4gb. Did you already fix the problem?

**Comment by illlas** [comment]
> I have the same issue on my RX570 4gb. Did you already fix the problem?

not yet. i have no idea for a solution to it unfortunately.

**Comment by realriccio** [comment]
I think yuzu solved this with this pr: https://github.com/yuzu-emu/yuzu/pull/11320

**Comment by realriccio** [comment]
Why was my comment deleted? I provided information which can help the developers fix the issue.
I guess there are projects which can't be talked about in this github... Lemme try again without mentioning them: i believe this issue has something to do with "Supporting masked depthstencil clears".

**Comment by gdkchan** [comment]
The change that you mentioned is likely the same as https://github.com/Ryujinx/Ryujinx/pull/5589 which is not related to this AMD issue.

**Comment by realriccio** [comment]
Oh ok sorry, it must be something else then. I thought it was that because on another software i had the same issue mentioned here on my amd hardware and it went away with a recent software update. Feel free to remove my comments.

**Comment by gdkchan** [comment]
Maybe it's the same issue as #5276.

**Comment by k1savage** [comment]
Version 1.1.1003 
RX 580 4G Ryzen 3600 16gb ram
Still the same issue game is unplayable npcs and horses flickering everywhere

**Comment by KyoShio** [comment]
> [也许这与#5276](https://github.com/Ryujinx/Ryujinx/issues/5276)是同一问题。

MacBook Pro 16-inch,2019
OS: MacOS 13.2.1 (22D68)
Ryujinx Version: 1.1.1019
Game Version: 1.0.1
Renderer: Vulkan
Memory:16 GB 2667 MHz DDR4
GPU: AMD Radeon Pro 5500M 4 GB
CPU:2.6 GHz  Six -core Intel Core i7

[Ryujinx_1.1.1019_2023-09-20_17-12-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12671337/Ryujinx_1.1.1019_2023-09-20_17-12-00.log)
Crashed when I loaded the game

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4721
Since it's a game specific issue, I close.
Thanks
