### ISSUE TITLE
[Bug] Controls don't work in DOOM 2016

### ISSUE THREAD

**Issue by supinrus** [Ryujinx/Ryujinx#5597]
### Description of the issue

Controls don't work in DOOM 2016, but it works in other games.

### Reproduction steps

This bug reproduced always.
https://fastpic.org/view/122/2023/0819/_55098a2683abc01d33b858c183265d5e.jpeg.html

### Log file

00:00:00.031 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.033 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.033 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.033 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.033 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.034 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.034 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xD0503EF
00:00:00.034 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.034 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.034 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.035 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.039 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.039 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.039 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.039 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.039 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.039 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.040 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.040 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.040 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.040 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.041 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.997
00:00:00.044 |N| Application Print: Operating System: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 (Arm64)
00:00:00.044 |N| Application Print: CPU: Apple M2 ; 8 logical
00:00:00.044 |N| Application Print: RAM: Total 8192 MiB ; Available 3556 MiB
00:00:00.046 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.046 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

macOS 13.5.1

### Ryujinx version

1.1.997

### Game version

1.2 and 1.0

### CPU

M2

### GPU

M2

### RAM

8GB

**Comment by gdkchan** [comment]
Does it work on macos1? I remember testing it in the past, but for me it stopped working everywhere, even on builds where it did work before, so I'm not sure what happened.

**Comment by supinrus** [comment]
DOOM launched in emulator in macos, but controls don't work.
But, controls works fine in Quake 2 and Mario Odysey in emulator in macos, for example.

**Comment by supinrus** [comment]
I can't confirm license agreement. Background music plays in emulator.

**Comment by AcK77** [comment]
This is already reported at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/499

**Comment by PrisedRabbit** [comment]
Why it's closed if it's still not working?

**Comment by ekuland** [comment]
> Why it's closed if it's still not working?

Feel free to read the comment right before yours...

**Comment by PrisedRabbit** [comment]
> > Why it's closed if it's still not working?
> 
> Feel free to read the comment right before yours...

I see. This is already reported. Thanks.
