### ISSUE TITLE
.NET Thread Worker Gpu : Error querying Vulkan devices: Could not find or load the native library: vulkan-1.dll Attempted "vulkan-1.dll", "D:\test-ava-ryunjinx-1.1.997-win_x64\publish\vulkan-1.dll"

### ISSUE THREAD

**Issue by arisuchigatana** [Ryujinx/Ryujinx#5602]
### Description of the issue

When downloading Ryujinx from the website there's no vulkan-1.dll file, which makes impossible to effectively change the 'Graphics Backend' option to Vulkan, doing so returns the following error message:

![Screenshot 2023-08-19 142751](https://github.com/Ryujinx/Ryujinx/assets/75755347/0852df88-82ba-4a72-a838-bdd8933da472)

Also, this is the emulator after extracting the .zip folder:
![Screenshot 2023-08-19 130355](https://github.com/Ryujinx/Ryujinx/assets/75755347/fa8ca978-e892-4f3b-a45e-f692e20d5d7b)

### Reproduction steps

1. Access the Ryujinx website
2. Download the latest available build
3. Extract the downloaded folder
4. Execute the application
5. Go in Options -> Settings -> Graphics
6. Change the 'Backend Graphics' option to 'Vulkan'
7. Access the console or log
8. Notice the 'Could not find or load vulkan-1.dll' error message

### Log file

00:00:00.034 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.038 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.039 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.040 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.041 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.042 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.042 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2188
00:00:00.043 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.043 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.044 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.046 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.053 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.054 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.054 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.054 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.054 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.054 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.054 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.055 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.055 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.055 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.055 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.063 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.997
00:00:00.068 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.068 |N| Application Print: CPU: AMD Ryzen 3 4100 4-Core Processor ; 8 logical
00:00:00.069 |N| Application Print: RAM: Total 16177 MiB ; Available 9760 MiB
00:00:00.071 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.072 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:05.430 |E| .NET ThreadPool Worker Gpu : Error querying Vulkan devices: Could not find or load the native library: vulkan-1.dll Attempted: "vulkan-1.dll", "D:\test-ava-ryujinx-1.1.997-win_x64\publish\vulkan-1.dll"
00:00:18.847 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:20.383 |I| Configuration LogValueChange: PreferredGpu set to: 

### OS

Windows 11

### Ryujinx version

1.1.997

### Game version

Red Dead Redemption 1.0.1

### CPU

Ryzen 3 4100

### GPU

NVIDIA GTX 1650

### RAM

16GB

### List of applied mods

No mods were applied.

### Additional context?

Unknown to me if this is a byproduct of the bug, but when selecting the Vulkan option on the 'Graphics Backend' you cannot select the 'Preferred GPU'.

**Comment by AcK77** [comment]
Is your GPU driver updated? Have you got an Antivirus installed?

**Comment by arisuchigatana** [comment]
At the time it was, and now that I updated again it's working as intended... I don't have a antivirus besides what comes with windows so it couldn't be that. So the issue it's fixed and sorry for wasting your time.

But regardless thanks for commenting, this made me recheck everything and it worked.
