### ISSUE TITLE
[Bug] No proper Mii Fighters rendering in Smash Ultimate?

### ISSUE THREAD

**Issue by Arkezuli** [Ryujinx/Ryujinx#5604]
### Description of the issue

![image](https://github.com/Ryujinx/Ryujinx/assets/97872002/7af984ce-4952-41e7-8f43-952c1e64bb39)

### Reproduction steps

Run Smash Ultimate
Create and save a custom Mii

### Log file

[Ryujinx_1.1.997_2023-08-20_05-59-16.log](https://github.com/Ryujinx/Ryujinx/files/12388169/Ryujinx_1.1.997_2023-08-20_05-59-16.log)

### OS

Windows 10

### Ryujinx version

1.1.997

### Game version

13.0.1

### CPU

i3-10105F

### GPU

NVIDIA GTX 1050 Ti

### RAM

32G

### List of applied mods

No mods

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/136
Since it's a game specific issue, I close.
