### ISSUE TITLE
[Bug] Graphical glitches on Animal Crossing: New Horizons on Intel Graphics 

### ISSUE THREAD

**Issue by 2Tsk2** [Ryujinx/Ryujinx#5605]
### Description of the issue

![image](https://github.com/Ryujinx/Ryujinx/assets/96981837/9177fe64-5aa9-4289-adfd-2060080a64bb)
![image](https://github.com/Ryujinx/Ryujinx/assets/96981837/79a74380-8d23-4acd-91d1-339b8ec5cc4e)

### Reproduction steps

just run the game on a system with intel graphics.

### Log file

[Ryujinx_1.1.999_2023-08-20_23-55-15.log](https://github.com/Ryujinx/Ryujinx/files/12388592/Ryujinx_1.1.999_2023-08-20_23-55-15.log)

### OS

Windows 11

### Ryujinx version

1.1.999

### Game version

1.0.0

### CPU

i5-8365u

### GPU

Intel UHD 620

### RAM

16gb

### List of applied mods

none

### Additional context?

Unsure if it affects newer Integrated graphics or GPU's in general

**Comment by AcK77** [comment]
Already reported at https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
