### ISSUE TITLE
[Bug]Super Mario Odyssey - Flickering Shadows And Lights

### ISSUE THREAD

**Issue by redsun1983cy** [Ryujinx/Ryujinx#5607]
### Description of the issue

Super Mario Odyssey - Flickering Shadows And Lights
A strange flickering ocurres from time to time in Super Mario Odyssey.

### Reproduction steps

just playing around wood kingdom
also cappy flickers on the very first level

### Log file

No logs 

### OS

MacOS 

### Ryujinx version

1.1.999

### Game version

1.30

### CPU

Apple M1

### GPU

Apple M1

### RAM

16G

**Comment by OldManKain** [comment]
Known Issue on the games list https://github.com/Ryujinx/Ryujinx-Games-List/issues/93#issuecomment-1333790286.

**Comment by redsun1983cy** [comment]
> Known Issue on the games list [Ryujinx/Ryujinx-Games-List#93 (comment)](https://github.com/Ryujinx/Ryujinx-Games-List/issues/93#issuecomment-1333790286).

Is this issue fixed?
Or what should I do to fix it?
