### ISSUE TITLE
[Bug]The screen of Mario + Rabbids Sparks of Hope will flicker when using hypervisor on Mac

### ISSUE THREAD

**Issue by Shihta** [Ryujinx/Ryujinx#5611]
### Description of the issue

the screen will flicker, as:
[sample1](https://youtu.be/ct1oSmgh1EM)
[sample2](https://youtu.be/2_y-WkkORqU)

### Reproduction steps

enable the hypervisor then play the game. not every scene will flicker, please refer to the scenes illustrated by the two videos

this issue will not happen if the hypervisor is disabled

### Log file

[Ryujinx_1.1.1+0_2023-08-23_22-10-30.log](https://github.com/Ryujinx/Ryujinx/files/12420288/Ryujinx_1.1.1%2B0_2023-08-23_22-10-30.log)

### OS

macOS 13.4.1

### Ryujinx version

1.1.999

### Game version

1.5.2205169

### CPU

Apple M2

### GPU

Apple M2

### RAM

24G

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4089
Since it's a game specific issue, I close.
Thanks
