### ISSUE TITLE
Regression on Cave Story+ due to the Scissor test implementation

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#562]
PR https://github.com/Ryujinx/Ryujinx/pull/556 caused a regression on Cave Story+. On my intel iGPU, it caused the game to flicker to a black screen. Seems to cause a black screen (all the time, not just flickering) on AMD? Needs further testing.

fyi @BaronKiko

**Comment by jduncanator** [comment]
For me it renders completely black. (AMD HD5450)

**Comment by gdkchan** [comment]
This is how it looks like here after the scissor PR (epillepsy warning?):
https://gfycat.com/HandmadePaltryCero

**Comment by BaronKiko** [comment]
Looks like the same cause as the bottom part has a negative viewport x coordinate which is undefined so AMD cards probably handle it differently. Will try see what's up.

**Comment by BaronKiko** [comment]
Can be closed, Fix has been merged.
