### ISSUE TITLE
[Feature Request] Add some kind of indicator for controller mappings when controller is pressed

### ISSUE THREAD

**Issue by Y0ngg4n** [Ryujinx/Ryujinx#5630]
### Overview

So i am playing on Steamdeck. So you normally connect your ps4 controllers for 4 players to play mario kart for example. Now you always have to select the controller from the list and assign it to the player. But the controller have kind of random numbers. So you always set the controller, exit the menu check if all controllers are working and reconfigure it. It would be nice if there would be some kind of indicator (can just be a red or green box that is lightened up when getting any input) when something on the controller is pressed (More advanced would be something like yuzu does) so you can check if you have selected the correct controller from the list. 

### Smaller details

Cool would be something like yuzu does in the controller mappings, but i would be totally fine with just something simple, that indicates that i seleted the correct controller

### Nature of request

Settings Feature

### Why would this feature be useful?

This would be extremely usefull for the steamdeck and multi controller setups.

**Comment by AcK77** [comment]
Duplicated of #2586
