### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by arminolat** [Ryujinx/Ryujinx#5633]
### Description of the issue

Running Ryujinx in Fullscreen reverts the monitor's refresh rate to the highest one possible, regardless of what was set before running Ryujinx in Fullscreen.

For example, I set my monitor's refresh rate to 60 in Windows Display Settings since playing games feels the smoothest in 60Hz - anything more than that and the games are not smooth and feel stuttery (frame pacing issues on high refresh rates?).

The problem is, if I run the game fullscreen, it just forces my monitor back to 144Hz, which is the max for my monitor. I also tested on a few other high refresh rate monitors and the same issue happens.

### Reproduction steps

1. Set refresh rate in Windows to 60Hz
2. Start any game in Ryujinx
3. Go fullscreen

### Log file

[Ryujinx_1.1.1003_2023-08-31_22-50-49.log](https://github.com/Ryujinx/Ryujinx/files/12490513/Ryujinx_1.1.1003_2023-08-31_22-50-49.log)

### OS

Windows 11

### Ryujinx version

1.1.1003

### CPU

Ryzen 7 3700X

### GPU

AMD RX 6600

### RAM

16GB

**Comment by Foul-Tarnished** [comment]
Not the first person complaining about higher refresh rates cause stutter or latency.

I think Ryujinx need quite a lot of work in that regard, but it looks like it's a complex problem, for sure

**Comment by riperiperi** [comment]
60hz does not fit into 144hz. Frames will be displayed for 2 and 3 frames alternating. That's just math.

**Comment by Foul-Tarnished** [comment]
144 bad 😎
