### ISSUE TITLE
[Feature Request] image downscale

### ISSUE THREAD

**Issue by boludoz** [Ryujinx/Ryujinx#5634]
### Overview

Downscaling can be used to improve performance by reducing the amount of data that needs to be rendered by the GPU.

### Smaller details

Percentages could be established, for example 0.50% and 0.75% of the original image.

### Nature of request

Render

### Why would this feature be useful?

 This can be useful for users who have a low-end PC or who are experiencing performance issues with a particular game.

**Comment by gdkchan** [comment]
This is already supported, you just need to set the resolution scale to custom and type the value that you want. for example, for 50% it would be 0.5, for 75% it would be 0.75 etc.
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/eeb01264-73b1-426b-81bf-21af369290c7)

**Comment by GamerzHell9137** [comment]
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/351047e5-455d-44a1-b76e-8d74496ff00b)

**Comment by boludoz** [comment]
I think I tried it but it didn't work, maybe I should have used a comma, the minimum value is one, you can't break that gap?, it would have many benefits

**Comment by boludoz** [comment]
> This is already supported, you just need to set the resolution scale to custom and type the value that you want. for example, for 50% it would be 0.5, for 75% it would be 0.75 etc. ![image](https://user-images.githubusercontent.com/5624669/264850800-eeb01264-73b1-426b-81bf-21af369290c7.png)

![image](https://github.com/Ryujinx/Ryujinx/assets/11653030/1b1e442e-8e4c-471e-9c12-53ccad5242b5)

**Comment by gdkchan** [comment]
If your OS region uses comma as decimal separator, then yes, you need to use comma.

**Comment by boludoz** [comment]
> If your OS region uses comma as decimal separator, then yes, you need to use comma.
Thank you, this emulator is a work of art in its construction, it really is very, very reliable, I tried this way because I know that the emulator was not designed for this and it works with zero glitches. I would really like to see this emulator progress, I know it will be the best, it just needs some optimizations.

**Comment by boludoz** [comment]
Thank you, this emulator is a work of art in its construction, it really is very, very reliable, I tried this way because I know that the emulator was not designed for this and it works with zero glitches. I would really like to see this emulator progress, I know it will be the best, it just needs some optimizations. I really love and appreciate your work very much.
