### ISSUE TITLE
[Bug] Pokémon Mystery Dungeon Rescue Team DX randomly fails to boot on macOS

### ISSUE THREAD

**Issue by tech-ticks** [Ryujinx/Ryujinx#5636]
### Description of the issue

There's a ~50% chance that *Pokémon Mystery Dungeon Rescue Team DX* gets stuck booting on macOS, so multiple attempts are often required to get in-game. If the hypervisor is enabled, it shows a black screen forever after the Ryujinx loading screen with the name and icon is finished. Without the hypervisor, it gets stuck on the loading screen instead.

### Reproduction steps

Launch *Pokémon Mystery Dungeon Rescue Team DX*.

### Log file

[Ryujinx_1.1.1003_2023-09-01_15-42-37.log](https://github.com/Ryujinx/Ryujinx/files/12498573/Ryujinx_1.1.1003_2023-09-01_15-42-37.log)

### OS

macOS Ventura 13.5

### Ryujinx version

1.1.1003 (the older "macos1" build has the same issue)

### Game version

1.0.2

### CPU

Apple M2 Max

### GPU

Apple M2 Max

### RAM

32 GB

### List of applied mods

None

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/245
Since it's a game specific issue, I close.
Thanks

**Comment by tech-ticks** [comment]
@AcK77 I've added a comment there, but I thought that this issue tracker was the appropriate place since the issue is both specific to an architecture (ARM; the game boots consistently on Intel) and operating system (macOS), and whether this game is considered "playable" there would now vary based on which platform it's played on. I'm also worried about whether this bug will ever be looked at if it's buried in a comment on a games list issue with the "status-playable" label.

**Comment by gdkchan** [comment]
Game is working on my m1 macbook air with hypervisor enabled. Have you tried it on the latest version of the emulator?

<img width="1392" alt="Captura de Tela 2023-09-28 às 14 31 33" src="https://github.com/Ryujinx/Ryujinx/assets/5624669/c02bd803-da20-485d-99c0-c86977c42e94">

**Comment by gdkchan** [comment]
Yes, I tried loading it about 8 times. It did get stuck once but the other times it worked.

**Comment by tech-ticks** [comment]
I see, yeah it roughly feels like a 50% chance to boot on my machine, with it often starting several times in a row without issue and other times, I have to keep restarting five times until it boots. The inconsistency is extremely annoying for developing mods especially, when I have to restart several times until it finally works.

**Comment by gdkchan** [comment]
It used to do that on x86 too. supposedly it was fixed with some changes to memory barriers on the JIT. Something like this should not affect the hypervisor of course, since it's just running the Arm code directly.
