### ISSUE TITLE
[Bug] It Takes two flickering screen, unstable frame rate 

### ISSUE THREAD

**Issue by moon-xt** [Ryujinx/Ryujinx#5637]
### Description of the issue

It Takes two The game freezes and cannot be played

### Reproduction steps

1、 open It Takes two 
2、boss level

### Log file

[Ryujinx_1.1.1003_2023-09-01_21-55-15.log](https://github.com/Ryujinx/Ryujinx/files/12498657/Ryujinx_1.1.1003_2023-09-01_21-55-15.log)

### OS

macOS 13.2

### Ryujinx version

1.1.1003

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

**Comment by moon-xt** [comment]
https://github.com/Ryujinx/Ryujinx/assets/47058891/188af999-3968-4325-b35c-ad5ce1e24fa6

**Comment by AcK77** [comment]
Could you please open a well formatted issue at https://github.com/Ryujinx/Ryujinx-Games-List/issues/new?assignees=&labels=&projects=&template=game_compatibility.yml (You can find explainations at https://github.com/Ryujinx/Ryujinx-Games-List)
Since it's a game specific issue, I close.
Thanks

**Comment by pierre-emmanuelJ** [comment]
Same here! Screen flickering a lot and flashing, if I have time, maybe I can provide a proper issue later.

Thanks a lot for this huge project ❤️
