### ISSUE TITLE
[Bug] Game crashes when clicking on a cheat name

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#5643]
### Description of the issue

the game will crash if you click on a cheat name while a game is running

### Reproduction steps

1. Open a game with cheats
2. Click the cheat name

### Log file

[Ryujinx_1.1.1004_2023-09-03_19-00-39.log](https://github.com/Ryujinx/Ryujinx/files/12506738/Ryujinx_1.1.1004_2023-09-03_19-00-39.log)

### OS

Arch Linux

### Ryujinx version

1.1.1004/1.1.1005

### CPU

AMD Ryzen 9 7900X3D

### GPU

AMD RX 6600 XT

### RAM

64GB

### List of applied mods

N/A

**Comment by Kurochi51** [comment]
Caused by https://github.com/Ryujinx/Ryujinx/pull/4362
