### ISSUE TITLE
[Bug] Ryujinx.ShaderTools unexpected instruction type 0 for fragment shaders

### ISSUE THREAD

**Issue by ScanMountGoat** [Ryujinx/Ryujinx#5644]
### Description of the issue

I'm getting a debug assert about an invalid alpha type of 0. If I attempt to continue, the code throws `System.InvalidOperationException: 'Unexpected instruction type "0"'`. Ignoring the exception results in Ryujinx.ShaderTools emitting an extra discard statement. The first bad commit after running a git bisect is b423197619dd8d9dda1c255a76105bf30e255dae.

### Reproduction steps

This happens for all the fragment shader binary files I've tested so far for Xenoblade 3. This only applies to Ryujinx.ShaderTools. Emulating the game still works as expected.
1. Extract the sample file from [nvsd0_FS0.zip](https://github.com/Ryujinx/Ryujinx/files/12507021/nvsd0_FS0.zip)
2. Run `Ryujinx.ShaderTools.exe nvsd0_FS0.bin`.

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.1005

**Comment by gdkchan** [comment]
The default `QueryGraphicsState` implementation on `IGpuAccessor` should return a `GpuGraphicsState` with the alpha test set to "always".
