### ISSUE TITLE
[Bug] Random crashes when running a number of games

### ISSUE THREAD

**Issue by hyeung001** [Ryujinx/Ryujinx#5648]
### Description of the issue

Seems to be getting the same invalid memory access error on multiple games after updating to the latest build.
The games that I've experienced crashes includes:
MARIO & SONIC AT THE OLYMPIC GAMES TOKYO 2020
Plants vs. Zombies: Battle for Neighborville™
Mario Golf: Super Rush

### Reproduction steps

Games will just crash randomly.

### Log file

00:00:00.008 |I| Gpu : Backend Threading (Auto): True
00:00:00.178 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:00.178 |I| Application LoadApplication: Loading as XCI.
00:00:00.245 |I| ModLoader QueryContentsDir: Searching mods for Title 0100C56010FD8000
00:00:00.245 |I| ModLoader QueryContentsDir: Searching mods for Title 0100C56010FD8000
00:00:00.257 |I| Loader Load: Loading rtld...
00:00:00.257 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.257 |I| Loader Load: Loading main...
00:00:01.456 |I| Loader PrintRoSectionInfo: main:
    Module: E:\p4\TnT\Local\Bin\GW3\NX\retail\GW3.Main_NX_retail.nss
00:00:01.456 |I| Loader Load: Loading sdk...
00:00:01.540 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 10.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-10_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-10_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-10_4_0-Release
00:00:01.541 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.543 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.543 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.593 |I| Loader LoadNsos: Loading image 2 at 0x0000000013e74000...
00:00:01.597 |I| ModLoader LoadCheats: Build ids found for title 0100C56010FD8000:
    C1ED34FD7D1962277A4555D9EC7146571218ED5D000000000000000000000000
    D89E062DA1D854AC9D98E2D664DA43D400000000000000000000000000000000
    204EAEF83FE5E5617D0787C8EF01A080000BCD9A000000000000000000000000
00:00:01.597 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.653 |I| Loader Start: Application Loaded: Plants vs. Zombies: Battle for Neighborville™ v1.0.0 [0100c56010fd8000] [64-bit]
00:00:01.654 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.654 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.738 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3080 (Vulkan v1.3.236, Driver v531.41.0.0)
00:00:01.739 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.744 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:01.763 |S| HLE.OsThread.24 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.784 |S| HLE.OsThread.24 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.785 |S| HLE.OsThread.24 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.785 |S| HLE.OsThread.24 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:01.799 |S| HLE.OsThread.24 ServicePctl Initialize: Stubbed. 
00:00:08.794 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:08.795 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:08.809 |S| HLE.OsThread.24 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:08.813 |S| HLE.OsThread.24 ServiceNifm Submit: Stubbed. 
00:00:08.813 |S| HLE.OsThread.24 ServiceNifm GetRequestState: Stubbed. 
00:00:08.813 |S| HLE.OsThread.24 ServiceNifm GetResult: Stubbed. 
00:00:08.814 |S| HLE.OsThread.24 ServiceNifm Submit: Stubbed. 
00:00:08.814 |S| HLE.OsThread.24 ServiceNifm GetRequestState: Stubbed. 
00:00:08.814 |S| HLE.OsThread.24 ServiceNifm GetResult: Stubbed. 
00:00:08.824 |S| HLE.OsThread.24 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: True ; unknownFlag3: False}
00:00:08.824 |S| HLE.OsThread.24 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:08.824 |S| HLE.OsThread.24 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:11.569 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:11.639 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:11.667 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:11.669 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:11.669 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:11.716 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:11.717 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:11.717 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:11.717 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:11.719 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:11.719 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:11.720 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:11.724 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:11.822 |I| HLE.OsThread.24 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:11.822 |I| HLE.OsThread.24 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:11.969 |S| HLE.OsThread.24 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72274610430509056}
00:00:11.973 |S| HLE.OsThread.24 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:11.981 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:11.982 |S| HLE.OsThread.9 ServiceHid GetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 1 ; SupportedStyleSets: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:11.983 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Handheld,Player1,Player2,Player3,Player4
00:00:12.061 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 100 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:12.062 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Handheld,Player1,Player2,Player3,Player4
00:00:12.064 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:12.081 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:12.239 |S| HLE.OsThread.24 ServiceNifm Submit: Stubbed. 
00:00:12.239 |S| HLE.OsThread.24 ServiceNifm GetRequestState: Stubbed. 
00:00:12.239 |S| HLE.OsThread.24 ServiceNifm GetResult: Stubbed. 
00:00:13.274 |S| HLE.OsThread.24 ServiceAm LockExit: Stubbed. 
00:00:13.572 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:13.572 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV8
00:00:13.575 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:13.575 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:13.633 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:13.747 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:26.342 |I| HLE.GuestThread.44 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Plants vs. Zombies: Battle for Neighborville™, PID: 100
   0x0000000013ec1a10	sdk:0x4da10	nn::audio::RequestUpdateAudioRenderer(nn::audio::AudioRendererHandle, nn::audio::AudioRendererConfig const*):0x00e0
   0x0000000008bcb9e8	main:0x6c79e8	fb::AudioDspOutputNX::Impl::dspThreadFunc(void*):0x0398
   0x000000000a500848	main:0x1ffc848	EA::Debug::ExceptionHandler::RunTrapped(long (*)(void*), void*):0x0038
   0x0000000008943048	main:0x43f048	
   0x00000000143cf6c0	sdk:0x55b6c0	
   0x00000000141b2698	sdk:0x33e698	
   0x00000000141b6e64	sdk:0x342e64	
   0x0000000000000000

00:00:26.343 |I| HLE.GuestThread.44 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x000000110193f050
	X[01]:	0x0000001101949bb0
	X[02]:	0x00000010312dfe00 (SP:-0x0080)
	X[03]:	0x00000010312dfe08 (SP:-0x0088)
	X[04]:	0x0000000000000001
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000001
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000004
	X[12]:	0x00000000c2996966
	X[13]:	0x0000000000000000
	X[14]:	0x00000000ffffff00
	X[15]:	0x000000001ee00000
	X[16]:	0x0000000014ada998
	X[17]:	0x00000000141b8410 (sdk:0x344410)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Enter()
	X[18]:	0x0000000000ffffff
	X[19]:	0x00000010312dfe00 (SP:-0x0080)
	X[20]:	0x000000110193f050
	X[21]:	0x000000110193f000
	X[22]:	0x0000001101949bb0
	X[23]:	0x00000010312dfe08 (SP:-0x0088)
	X[24]:	0x00000000000008dd
	X[25]:	0x00000011018d38b0
	X[26]:	0x00000011018d1b80
	X[27]:	0x00000011018d1ed8
	X[28]:	0x00000000000008df
	FP:	0x00000010312dfdc0 (SP:-0x0040)
	LR:	0x0000000013ebc8d4 (sdk:0x488d4)	=> nn::audio::VoiceInfoManager::UpdateVoiceRelatedParameters(void*, unsigned long*, unsigned long*):0x0034
	SP:	0x00000010312dfd80 (SP)
	PC:	0x00000000141b8410 (sdk:0x344410)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Enter()

00:00:26.343 |E| HLE.GuestThread.44 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:26.369 |E| HLE.GuestThread.44 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 106
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1251

### OS

Windows 11

### Ryujinx version

1.1.1005

### Game version

1.0.0

### CPU

i9-12900K

### GPU

RTX3080

### RAM

64GB

**Comment by gdkchan** [comment]
Crashes on MARIO & SONIC AT THE OLYMPIC GAMES TOKYO 2020 and Plants vs. Zombies: Battle for Neighborville are not new, they have always been broken.

**Comment by KushaalL** [comment]
When I updated to this version I am getting random crashes when playing Pokemon Legends Arceus

**Comment by gdkchan** [comment]
Post the log when it crashes, otherwise we can't really do anything.

**Comment by AcK77** [comment]
Report issues in the game compatibility issues (https://github.com/Ryujinx/Ryujinx-Games-List/issues) instead of reporting various issues without context, log files or anything else. Thanks.
