### ISSUE TITLE
[Feature Request] Auto-hide mouse

### ISSUE THREAD

**Issue by SirTenzin** [Ryujinx/Ryujinx#5654]
### Overview

Automatically hide the mouse after inactivity.

### Smaller details

If a game is being played and there has been no mouse input for a minute, it should automatically hide the mouse to allow for immersion into the game, simple QOL feature.

### Nature of request

Quality of Life

### Why would this feature be useful?

Small QOL features like this add up over time, making the gameplay more immersive. Its just one of those "nice to have" comfy features.

**Comment by MutantAura** [comment]
There is already an option for this in settings.
