### ISSUE TITLE
[Bug] Triangular waterfall texture artifact in SM Odyssey

### ISSUE THREAD

**Issue by benjaminmordaunt** [Ryujinx/Ryujinx#5657]
### Description of the issue

Triangle artifact seen in top-right of screen. Likely related to waterfall texture. See one of its points starting just below and to the right of the compass widget.

![image](https://github.com/Ryujinx/Ryujinx/assets/17656637/19fd2425-be61-4189-89b9-8c4648df8ea3)

### Reproduction steps

Travel to Cascade Kingdom and stand on the fallen bridge.

### Log file

None

### OS

macOS 13.5.1

### Ryujinx version

1.1.1009

### Game version

1.3.0

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

**Comment by benjaminmordaunt** [comment]
EDIT: So this seems to appear in most scenes in the game it seems - may be completely unrelated to waterfall.

**Comment by gdkchan** [comment]
It will appear on any scene with fog/smoke. MoltenVK does not support extended dynamic state, so there's no way to pass the vertex buffer size. Those games does draws that fetch outside the vertex buffer if the correct size is not specified. The correct behaviour is reading values outside the vertex buffer range as zero.

BTW I believe Captain Toad has the same issue.

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/93
Since it's a game specific issue, I close.
Thanks
