### ISSUE TITLE
[Bug] Mii Fighter rendering gltich in Smash Bros. Ultimate

### ISSUE THREAD

**Issue by Bladewolf3301** [Ryujinx/Ryujinx#5659]
### Description of the issue

After creating a Mii Fighter in Smash Ultimate, the fighter icon looks extremely glitchy.

![Screenshot (237)](https://github.com/Ryujinx/Ryujinx/assets/68881807/f4d02bff-6736-4a5e-9151-78c244df5288)

### Reproduction steps

Open SSBU on Ryujinx
Go to Games & More
Select Mii Fighter.
Pick one and customize.
Save your customization.

### Log file

[Ryujinx_1.1.1009_2023-09-07_07-17-53.log](https://github.com/Ryujinx/Ryujinx/files/12543841/Ryujinx_1.1.1009_2023-09-07_07-17-53.log)

### OS

Windows 11

### Ryujinx version

1.1.1009

### Game version

13.0.0

### CPU

Ryzen 7 6800H

### GPU

NVIDIA RTX 3050

### RAM

16GB

### List of applied mods

No mods applied.

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/136
Since it's a game specific issue, I close.
