### ISSUE TITLE
[Bug]Octo Traveler 2 crashed after the save was loaded

### ISSUE THREAD

**Issue by yourlin** [Ryujinx/Ryujinx#5660]
### Description of the issue

**[Normal]** Intro 
**[Normal]** Menu
**[Crashed]** Game Started

### Reproduction steps

1. Load the game
2. Select "Continue"
3. Crashed

### Log file

[Ryujinx_1.1.1009_2023-09-07_14-15-16.log](https://github.com/Ryujinx/Ryujinx/files/12545317/Ryujinx_1.1.1009_2023-09-07_14-15-16.log)

### OS

macOS 13.5 (22G74)

### Ryujinx version

1.1.1009-macos1

### Game version

1.0.2

### CPU

2.6 GHz Intel Core i7

### GPU

AMD Radeon Pro 5300M

### RAM

16 GB 2667 MHz DDR4

**Comment by OldManKain** [comment]
This is a TDR due to your PC, you should probably try Linux or Bootcamp since this isn't Apple Silicon.
