### ISSUE TITLE
[Bug] Pokemon Violet crashes on start up after 1.1.1002

### ISSUE THREAD

**Issue by Lynius0001** [Ryujinx/Ryujinx#5662]
### Description of the issue

Since update 1.1.1002 Pokemon Violet crashes on start up. Any version after is the same, just an instant crash. The log gives some kinda vulkan error. There are two logs attached: from 1001 and from 1002.
  
 Also, clearing the shader folder results in the emulator getting forever stuck on this part.
![image](https://github.com/Ryujinx/Ryujinx/assets/144349421/1a752523-4d11-42b3-bf92-2bbb804642b2)

### Reproduction steps

Just trying to open the game on any version after 1.1.1001

### Log file

[Ryujinx_1.1.1001_2023-09-07_19-34-15.log](https://github.com/Ryujinx/Ryujinx/files/12549293/Ryujinx_1.1.1001_2023-09-07_19-34-15.log)
[Ryujinx_1.1.1002_2023-09-07_19-38-24.log](https://github.com/Ryujinx/Ryujinx/files/12549298/Ryujinx_1.1.1002_2023-09-07_19-38-24.log)

### OS

Windows 10

### Ryujinx version

1.1.1002

### Game version

1.3.2

### CPU

i5-4460

### GPU

AMD Radeon R7 370

### RAM

16 GB

### List of applied mods

None

**Comment by AcK77** [comment]
Since you seems the only one to report regression I suggest you to delete the whole shaders folder and update your driver.
1001 was a code update related to macOS and 1002 was an UI code update...

**Comment by Lynius0001** [comment]
>Deleted shaders multiple times, always gets stuck on the console error. My drivers are as good as my hardware gets, so that very well could be the issue.

**Comment by AcK77** [comment]
You purged caches or deleted the whole folder?

**Comment by Nayru7** [comment]
I'm experiencing the very same issue on an old pc, but with Pokemon Scarlet.
The GPU is an AMD HD7950 updated to the latest drivers 22.6.1 released on 02/08/2022.
OS Win10 64bit.
The game version is 2.0.1 + Teal Mask DLC.
Firmware 16.1.0 and Prodkeys 16.0.3
Graphics backend: Vulkan
I've tried first by purging and later deleting the shader folder.
The game runs normally up to Ryujinx version 1.1.1001

I have then tried the same setup on a newer pc with a Nvidia RTX2070 graphics card and the game runs perfectly both on Ryujinx version 1.1.1002 and on the current 1.1.1012

I hope this will help with the troubleshooting.

**Comment by MetrosexualGarbodor** [comment]
Can you please update to **1.1.1014** and check if it's fixed?

**Comment by Nayru7** [comment]
Thank you for the quick response.
After updating the emulator Pokemon Scarlet crashes on startup with the following error message:

00:00:04.502 |E| GUI.RenderLoop Application : Unhandled exception caught: System.AggregateException: One or more errors occurred. (Unexpected API error "ErrorInitializationFailed".)
 ---> Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorInitializationFailed".

I'm attaching the full log file for completeness.
[Ryujinx_1.1.1014_2023-09-14_20-30-00.log](https://github.com/Ryujinx/Ryujinx/files/12612233/Ryujinx_1.1.1014_2023-09-14_20-30-00.log)

**Comment by gdkchan** [comment]
If you want to help figuring out that issue, install the Vulkan SDK from https://vulkan.lunarg.com/, go to Options > Settings > Logging, and set Graphics Backend Log Level to error, then launch the game and upload the log here when it crashes.

**Comment by Nayru7** [comment]
I have tried deleting the shader folder once more, and I'm now getting the initial error message again:

00:00:14.072 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:14.820 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:15.821 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 4 took more than 1000ms, resuming execution...

[Ryujinx_1.1.1014_2023-09-14_20-46-34.log](https://github.com/Ryujinx/Ryujinx/files/12612339/Ryujinx_1.1.1014_2023-09-14_20-46-34.log)

**Comment by Nayru7** [comment]
I have installed Vulkan SDK version 1.3.261.1 and enabled the Backend Log Level like you explained.
This is the new log file I get once Ryujinx is stuck on "Wait on syncpoint 1 for threshold 4 took more than 1000ms, resuming execution..."
[Ryujinx_1.1.1014_2023-09-14_21-04-40.log](https://github.com/Ryujinx/Ryujinx/files/12612574/Ryujinx_1.1.1014_2023-09-14_21-04-40.log)

Thank you again for the support.

**Comment by gdkchan** [comment]
Can you check if the build on #5683 fixes the issue?

**Comment by Nayru7** [comment]
I confirm that with the build [ryujinx-Release-1.1.0+5bf1f30-win_x64] the game starts properly.
I'm also including a one minute log of the emulator running the game with Graphics Backend Log Level set to "error".
[Ryujinx_1.1.0+5bf1f30_2023-09-14_22-36-18.log](https://github.com/Ryujinx/Ryujinx/files/12613271/Ryujinx_1.1.0%2B5bf1f30_2023-09-14_22-36-18.log)

I remain available for any further testing and I'll update the thread in case of any issue.
Thanks for the amazing job, as always.

**Comment by gdkchan** [comment]
Thanks for testing. You can disable the graphics backend logging by putting it back to None (keeping it enabled impacts performance). You can also uninstall the Vulkan SDK if you don't plan to use it anymore (though there is no harm in keeping it installed).

**Comment by Lynius0001** [comment]
Both, same result.

**Comment by Lynius0001** [comment]
Worked for me as well, thank you so much!
