### ISSUE TITLE
[Bug] Games crash mostly Fire Emblem 3H

### ISSUE THREAD

**Issue by Maounobu92** [Ryujinx/Ryujinx#5669]
### Description of the issue

I launched, FE3H as usual, and Ryujinx automatically closes not even 3 sec after the game launched
 I wanted to try another game, and it’s the same result knowing that last night, I was playing it and I had no problem to launch the game and play it. I even made the most recent update and I had no issues so far.

### Reproduction steps

Trying to launch the game

### Log file

Ryujinx_1.1.1010_2023-09-10_17-00-52
Ryujinx_1.1.1010_2023-09-10_17-10-21
Ryujinx_1.1.1010_2023-09-10_17-26-29

### OS

Windows 11

### Ryujinx version

1.1.1010

### Game version

1.2.0

### GPU

Nvidia RTX 3050

### RAM

16 Gb

**Comment by MetrosexualGarbodor** [comment]
You didn't upload any logs, and this is probably not a Ryujinx issue. Please join Discord for help.
