### ISSUE TITLE
[Bug]macOS run any games crash

### ISSUE THREAD

**Issue by fuhuan416** [Ryujinx/Ryujinx#5674]
### Description of the issue

Run game emulator crash.

### Reproduction steps

No matter use Open-> Load Application from File to pick a game file in menu bar or
into the settings add a folder then double-click icon to launch game.
two both methods will make emulator crash.

### Log file

[Log.txt](https://github.com/Ryujinx/Ryujinx/files/12582115/Log.txt)

### OS

macOS 13.0.1

### Ryujinx version

Ryujinx-1.1.0-macos1-macos_universal.app.tar

### Game version

Origin version without any patches

### CPU

M1 Pro

### GPU

M1 Pro

### RAM

16GB

### List of applied mods

Without any mods.

**Comment by OldManKain** [comment]
Please download the newest MacOS release from our website https://ryujinx.org/download and join us in [discord](https://discord.gg/ryujinx) for general trouble shooting issues.

**Comment by fuhuan416** [comment]
> Please download the newest MacOS release from our website https://ryujinx.org/download and join us in [discord](https://discord.gg/ryujinx) for general troubleshooting issues.

Yes i had downloaded newest version, but still crash, perhaps the log info is diferrence, i'll upload that log.txt later.
