### ISSUE TITLE
sfdnsres: 13 (GetNameInfoRequestWithOptions) is not implemented

### ISSUE THREAD

**Issue by Lucky-Strike1695** [Ryujinx/Ryujinx#5675]
### Service call

sfdnsres: 13 (GetNameInfoRequestWithOptions)

### Service description

[Switchbrew: sfdnsres](https://switchbrew.org/wiki/Sockets_services#sfdnsres)

No information about GetNameInfoRequestWithOptions

### Required by

Fae Farm - We currently don't have a compat report issue for this game at https://github.com/Ryujinx/Ryujinx-Games-List

---

_Original description:_

### Description of the issue

When playing Fae Farm and trying to connect from Ryujinx to a CFW switch, Ryujinx crashes and closes, as soon as clicking on "join".

### Reproduction steps

Launch the game, go to "join world", local play, click "join".

### Log file

<details>
<summary>Ryujinx LDN Log</summary>

```
00:00:43.368 |I| HLE.OsThread.15 ServiceLdn : Initializing with multiplayer mode: LdnMitm
00:00:43.384 |I| HLE.OsThread.15 ServiceLdn : Initialize LanDiscovery using IP: 192.168.1.82
00:00:43.387 |I| HLE.OsThread.15 ServiceLdn : Connecting to host: 192.168.1.171
00:00:43.475 |I| .NET ThreadPool Worker ServiceLdn : LdnProxyTCPClient connected!
00:00:43.535 |E| HLE.OsThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 13

Guest Stack Trace:
Process: Service, PID: 98

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000000000000000 Size: 0x0000000000000000
	SendBuff:
	Position: 0x0000001780000008 Size: 0x0000000000000010 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	ReceiveBuff:
	Position: 0x0000001a4000002c Size: 0x0000000000000401 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0D 00 00 00 00 00 00 00   SFCI············
00000010   02 00 00 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262

```
</details> 

### OS

Windows 11

### Ryujinx version

1.1.0-ldn3.1.3

### Game version

1.3.1

### CPU

AMD Ryzen 5600X

### GPU

AMD Radeon 5700XT

### RAM

32GB

### List of applied mods

None

**Comment by TSRBerry** [comment]
This issue should have been created with the `missing service call` template.

**Comment by AcK77** [comment]
Duplicated of #1819

**Comment by SuperQuoc** [comment]
So if I understand the problem's still running and there's no solution planned ?

**Comment by GamerzHell9137** [comment]
> So if I understand the problem's still running and there's no solution planned ?

No, there's just another thread opened about the issue which is in the correctly formatted, there's no need for two threads about it especially when this one is not created with the correct template. Try enabling missing services or play on the master build if you wanna play Fae Farm.
