### ISSUE TITLE
[Bug] Persona 5 Royal lightning issues

### ISSUE THREAD

**Issue by Ragnar-es** [Ryujinx/Ryujinx#5676]
### Description of the issue

When entering a new map, (not all) lightning starts broken, opening the menu repeatedly seems to fix it after a few tries.

### Reproduction steps

- Take the subway to Shibuya
- Select the Central Street
- Once the map is loaded you'll see it very dark.
- Open the menu repeatedly until the lightning comes back

### Log file

[Ryujinx_1.1.1011_2023-09-12_17-44-20.log](https://github.com/Ryujinx/Ryujinx/files/12588404/Ryujinx_1.1.1011_2023-09-12_17-44-20.log)

### OS

Windows 10

### Ryujinx version

1.1.1011

### Game version

1.0.0

### CPU

Intel i7-8700

### GPU

NVIDIA GTX 1080

### RAM

16GB

### List of applied mods

PS4 Button Mod
Remove Cinematic Black Bars
60FPS Mod

(Even with the mods removed it still happens)

### Additional context?

https://github.com/Ryujinx/Ryujinx/assets/73453057/b30e527c-d24a-4359-bace-cd01bf106118

**Comment by OldManKain** [comment]
Known Issue, https://github.com/Ryujinx/Ryujinx-Games-List/issues/4086
Please report specific game issues on the Games-List.
