### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Chris2004m** [Ryujinx/Ryujinx#5677]
### Description of the issue

![image](https://github.com/Ryujinx/Ryujinx/assets/123336687/cfd54bae-9a4b-4f02-b41e-ef3135b92f1c)

![image](https://github.com/Ryujinx/Ryujinx/assets/123336687/9b2a6562-069c-4597-83ce-00a96da0eac8)

Hi I'm getting this error every time I try playing multiplayer with my friend. I followed the usual guide for LDN and local wireless setup, but it still does not work.
Both me and my friend are getting this error. We both can create a lobby, however neither of us can join the other's lobby. Every time each one of us tries to join, we get this connection related error

### Reproduction steps

1. Get onto Mario Kart 8 deluxe
2. On home menu, select "wireless play" with 1p option
3. If I am creating a room, then I click create room button
4. My friend gets to this wireless play menu and selects my lobby from the lobbies available. Upon selecting this, the above connection error message pops up. We can both create rooms but cannot join each others. This issue not only exists when we play

### Log file

[Ryujinx_ 1.1.0-macos1_2023-09-12_14-30-02.log](https://github.com/Ryujinx/Ryujinx/files/12590686/Ryujinx_.1.1.0-macos1_2023-09-12_14-30-02.log)

[Ryujinx_ 1.1.0-macos1_2023-09-12_15-20-06.log](https://github.com/Ryujinx/Ryujinx/files/12590690/Ryujinx_.1.1.0-macos1_2023-09-12_15-20-06.log)

[Ryujinx_ 1.1.0-macos1_2023-09-12_15-34-57.log](https://github.com/Ryujinx/Ryujinx/files/12590691/Ryujinx_.1.1.0-macos1_2023-09-12_15-34-57.log)

### OS

macOS 13.5

### Ryujinx version

1.1.0 (ldn version with avalonia 0.10)

### Game version

2.4.0 (Mario Kart 8 Deluxe)
1.1.0 (Super Mario 3D World + Bowser's Fury)

### CPU

Apple M1 Pro

### GPU

MoltenVK Apple M1 Pro (Vulkan v1.2.231, Driver v0.2.2008)

### RAM

16GB

### List of applied mods

None

### Additional context?

N/A

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, especially after being denied support for engaging in piracy.
