### ISSUE TITLE
[Bug] Mortal Kombat 1 not rendering correctly many effects, poor performance

### ISSUE THREAD

**Issue by appvitor** [Ryujinx/Ryujinx#5687]
### Description of the issue

Trying to play Mortal Kombat 1 is currently not possible.
Many effects are slow or rendered completely wrong.
Exploding and disappearing pixels all over.

### Reproduction steps

Install and play Mortal Kombat 1 with its latest version and DLCs

### Log file

[Ryujinx_1.1.1014_2023-09-15_11-03-52.log](https://github.com/Ryujinx/Ryujinx/files/12621896/Ryujinx_1.1.1014_2023-09-15_11-03-52.log)
[Ryujinx_1.1.1014_2023-09-15_11-10-00.log](https://github.com/Ryujinx/Ryujinx/files/12621898/Ryujinx_1.1.1014_2023-09-15_11-10-00.log)
[Ryujinx_1.1.1014_2023-09-15_13-18-08.log](https://github.com/Ryujinx/Ryujinx/files/12621899/Ryujinx_1.1.1014_2023-09-15_13-18-08.log)

### OS

Mac OS 14 RC

### Ryujinx version

1.1.1014

### Game version

1.3 or 1.0.3

### CPU

M1

### GPU

M1

### RAM

8GB

### List of applied mods

No mods applied

**Comment by Edenia3** [comment]
Serious memory leak with Mk1. Every next battle VRAM consumption increases +2Gb and after reaching GPU VRAM limit emulator crashes.

**Comment by iMonZ** [comment]
on macOS the Game is Crashing. Any Fix in View?

**Comment by AcK77** [comment]
Performance are a bit improved since Ryujinx 1.1.1032.
You can report the current macOS state on the compatibility list: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4744
Since it's a game specific issue, I close.

Note: https://www.ign.com/videos/mortal-kombat-1-switch-funniest-bugs-and-glitches
