### ISSUE TITLE
[Bug] Super Mario Maker 2 3.0.2 update crash

### ISSUE THREAD

**Issue by gmcguedes** [Ryujinx/Ryujinx#5690]
### Description of the issue

Hi everyone! Been using Ryujinx for quite a while and everything works amazing on my M1 Pro MacBook Pro. Except for SMM2. I don't know why but the game loads fine except when I start playing a level. After 20-30sec my Ryujinx app crash.

It doesn't matter if it's loaded levels or history. Even try with hypervisor turned off. And in this case the app crashes on game load.

Need help, please. I uploaded my 2 latest logs. Thanks.

### Reproduction steps

When loading a level inside the game.

### Log file

[Ryujinx_1.1.1014_2023-09-16_13-47-47.log](https://github.com/Ryujinx/Ryujinx/files/12640731/Ryujinx_1.1.1014_2023-09-16_13-47-47.log)
[Ryujinx_1.1.1014_2023-09-16_13-48-59.log](https://github.com/Ryujinx/Ryujinx/files/12640732/Ryujinx_1.1.1014_2023-09-16_13-48-59.log)

### OS

MacOS Sonoma

### Ryujinx version

1.1.1014

### Game version

3.0.2

### CPU

M1 Pro

### GPU

M1 Pro

### RAM

16GB

**Comment by anzbert** [comment]
Same here. If i run the game without the update, so just version 1.0.0, it works fine. I am also using a M1 macbook running Sonoma since it was released yesterday.

**Comment by AcK77** [comment]
Could you please send report in the compatibility issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues/180
Since it's a game specific issue, I close.
Thanks.
