### ISSUE TITLE
[Bug]  Trine 5 A Clockwork Can't recognize game

### ISSUE THREAD

**Issue by gitcfly** [Ryujinx/Ryujinx#5691]
### Description of the issue

The game cannot be recognized： Trine 5 A Clockwork

### Reproduction steps

Firmware 16.1.0, key 16.1.0

### Log file

00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: False
00:00:00.006 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.010 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.010 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.011 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.012 |I| Configuration LogValueChange: BackendThreading set to: Off
00:00:00.012 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.013 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x28E0
00:00:00.013 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.013 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.013 |I| Configuration LogValueChange: ScalingFilterLevel set to: 81
00:00:00.023 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1015
00:00:00.026 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.026 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i7-13700H ; 20 logical
00:00:00.027 |N| Application Print: RAM: Total 16108 MiB ; Available 8483 MiB
00:00:00.028 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error, Guest
00:00:00.029 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.090 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'D:\MyGames\switch\三位一体5[1.0.1][16.0.3].xci' Error: System.ArgumentException: An item with the same key has already been added. Key: 0100e2701a8888000000000000000010.tik
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey, TValue, InsertionBehavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[], Func`2, Func`2, IEqualityComparer`1)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1, Func`2, Func`2, IEqualityComparer`1 )
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1, Func`2, Func`2)
   at LibHac.FsSystem.PartitionFileSystem..ctor(IStorage storage)
   at LibHac.Tools.Fs.XciPartition..ctor(IStorage storage)
   at LibHac.Tools.Fs.Xci.OpenPartition(XciPartitionType type)
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 185
00:00:01.102 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.112 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.115 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.130 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)

### OS

Windows 11

### Ryujinx version

1.1.1015

### Game version

1.0.3

### CPU

i7-13700H

### GPU

RTX4060

**Comment by AcK77** [comment]
Have you tried to dump your game again?

**Comment by AcK77** [comment]
Proper dumps can't contains the ticket twice, the issue can be fixed by dumping it again.

(Even if an issue exists in LibHac, it will be fixed when a new version will be released)
