### ISSUE TITLE
wolfenstein youngblood black screen[Bug]

### ISSUE THREAD

**Issue by iAmSuperMan12** [Ryujinx/Ryujinx#5693]
### Description of the issue

At first everything is fine, video screensavers from the game publishers are shown and at the moment when the main menu should appear, there is a black screen but there is sound

### Reproduction steps

At first everything is fine, video screensavers from the game publishers are shown and at the moment when the main menu should appear, there is a black screen but there is sound
<img width="1204" alt=" 1" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/af9fddc8-8197-4687-a3f1-ffd7ab25ce32">

### Log file

[Ryujinx_1.1.1015_2023-09-18_14-44-34.log](https://github.com/Ryujinx/Ryujinx/files/12646503/Ryujinx_1.1.1015_2023-09-18_14-44-34.log)

### OS

Mac OS 12.6.2

### Ryujinx version

1.1.1015

### Game version

1.5

### CPU

apple m1

### GPU

apple gpu

### RAM

16

### List of applied mods

DLC

**Comment by AcK77** [comment]
This is the same on every platform: https://github.com/Ryujinx/Ryujinx-Games-List/issues/2557
