### ISSUE TITLE
[Bug] Graphic glitches - Zelda TOTK - macOS

### ISSUE THREAD

**Issue by reklic** [Ryujinx/Ryujinx#5694]
### Description of the issue

Hello! I have faced flickering graphic glitches. Tried different scenarios (with/out mods, graphic settings, reset shaders). No glitch found in 1.1.1013. would appreciate you help, thank you.

### Reproduction steps

Appears on such type of environment details (scratches, signs, stones, mud and so on).

<img width="779" alt="1" src="https://github.com/Ryujinx/Ryujinx/assets/14798675/7f844b40-ec51-4c24-9835-8dda875e3614">

### Log file

don't know :(

### OS

MacOS Ventura

### Ryujinx version

1.1.1017

### Game version

1.2.1

### CPU

M1 Pro

### GPU

Apple 16-core GPU

### RAM

16GB

**Comment by IsaacMarovitz** [comment]
Regressed from https://github.com/Ryujinx/Ryujinx/pull/5683

**Comment by IsaacMarovitz** [comment]
Same issue as https://github.com/Ryujinx/Ryujinx/issues/5685 it seems

**Comment by AcK77** [comment]
Is this still happen?

**Comment by reklic** [comment]
> Is this still happen?

No, Thank you all!
