### ISSUE TITLE
[Bug] Animal Crossing New Horizon crashes on macOS

### ISSUE THREAD

**Issue by 3ndyxZ** [Ryujinx/Ryujinx#5695]
### Description of the issue

As soon as I start the game, the game starts normally without lag but after a few minutes it goes into crush ryujinx, I tried to change the game version, play without dlc and change the graphics and CPU settings but nothing. I also have other games that start and work normally, this is the only game that gives me this problem.

P.S Sorry for my bad English.

### Reproduction steps

I started the game via Ryujinx with my Mac, I play with a Dualsense for ps5 but every time I play after a few minutes the game goes into crush. the other games don't have this problem, only its.

### Log file

[Ryujinx_1.1.1017_2023-09-19_15-16-27.log](https://github.com/Ryujinx/Ryujinx/files/12660686/Ryujinx_1.1.1017_2023-09-19_15-16-27.log)

### OS

macOS Ventura

### Ryujinx version

1.1.1017

### Game version

1.0 & 2.0.6

### CPU

Apple M2

### GPU

Apple M2

### RAM

8GB 

### Additional context?

DLC - Happy Home Paradise
DLC - Special Order Ticket Pocket Camp tie-in campaign
DLC - Nook Inc Silk Rug

**Comment by AcK77** [comment]
This issue is already reported at https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
You can send another report there if you want to.
Since it's a game specific issue, I close.
