### ISSUE TITLE
[Feature Request] - GUI accessibility with screen readers

### ISSUE THREAD

**Issue by shadow2560** [Ryujinx/Ryujinx#5696]
### Overview

I've tried on Windows 11 with the screen reader NVDA, nothing is announced by the screen reader so it's impossible to use or configure the program.

### Smaller details

I don't know how to to this but maybe look at Yusu witch is accessible by default or Retroarch witch have a param to enable accessibility features could give some clues. Or maybe have a specific interface if an accessibility setting is enabled could also be a solution but could be difficult to maintain a give too mutch work.

### Nature of request

GUI accessibility

### Why would this feature be useful?

Because everyone could use the program, it's not because I don't see what is written on the screen that I can't play any game.

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #4352
