### ISSUE TITLE
[Bug]Smash Brothers Ultimate crashes on startup 

### ISSUE THREAD

**Issue by Talkingtom442** [Ryujinx/Ryujinx#5699]
### Description of the issue

Whenever I try to open supers smash brothers ultimate it is a black screen for a while then Ryujinx crashes.
This is a video of what happened 
https://drive.google.com/file/d/1X76u7BifWUR7Emw1sC0sjZgKdbkvFl4L/view?usp=sharing

It doesn’t show it, but it crashes right when the video ends.

### Reproduction steps

I downloaded Ryujinx, put in the keys, and I installed the switch firmware. I added Smash Brother’s game directory, but when I clicked on it, it crashed after glitching a lot.

### Log file

https://docs.google.com/document/d/176qirW5vvVULJfri6zCX1tQ2z4C_OPWZSwy0yAjunWA/edit

### OS

Windows 10

### Ryujinx version

1.1.1019

### Game version

13.0.1

### RAM

8GB

### Additional context?

The game file I am using worked on another device

**Comment by MetrosexualGarbodor** [comment]
Your system does not meet minimum requirements.
