### ISSUE TITLE
Game Crashes a few minutes after arriving in Hyrule Fields[Bug]

### ISSUE THREAD

**Issue by VernamonR** [Ryujinx/Ryujinx#5701]
### Description of the issue

Game Crashes a few minutes after arriving in Hyrule Fields and killing the Bokoblin near a tree. After killing the Bokoblin and walking towards a sign nearby game crashes completely even after saving after killing the Bokoblin. FPS has been a steady below 20. Menus run at 30fps. Mods make the game run even worse. Game crashed even on the update before the latest Ryujinx update.

### Reproduction steps

Game version: 1.2.1 Firmware: 16.1.0; 

All Settings on default no apps open in the background.

Enter Hyrule fields upon the very handing Zelda the broken Master sword. 

Walk north towards yellow waypoint. 

Kill Bokoblin and head towards the sign near the water.

Game should crash every time. 

### Log file

00:00:00.055 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.062 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.062 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.063 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.064 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.064 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.065 |I| Configuration LogValueChange: PreferredGpu set to: 0x8086_0x9A49
00:00:00.066 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.067 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.067 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.070 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.071 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.071 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.071 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.071 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.071 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.071 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.071 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.072 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.072 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.072 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.072 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.073 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.073 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.073 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.074 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.078 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1019
00:00:00.086 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.086 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz ; 8 logical
00:00:00.088 |N| Application Print: RAM: Total 12067 MiB ; Available 8792 MiB
00:00:00.092 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.092 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.071 |I| Gpu : Backend Threading (Auto): True
00:00:00.827 |N| Application LoadApplication: Using Firmware Version: 16.1.0
00:00:00.827 |I| Application LoadApplication: Loading as XCI.
00:00:00.860 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.861 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.867 |I| Loader Load: Loading rtld...
00:00:00.876 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.876 |I| Loader Load: Loading main...
00:00:01.259 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:01.260 |I| Loader Load: Loading subsdk0...
00:00:01.290 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:01.290 |I| Loader Load: Loading sdk...
00:00:01.372 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:01.497 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:03.903 |I| Ptc Load: Loaded Translation Cache (size: 195439975 bytes, translated functions: 142119).
00:00:03.937 |I| Ptc Load: Loaded Profiling Info (size: 484508 bytes, profiled functions: 141015).
00:00:03.947 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:03.949 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:03.973 |I| Loader LoadNsos: Loading image 2 at 0x000000000cc2f000...
00:00:03.976 |I| Loader LoadNsos: Loading image 3 at 0x000000000d2d8000...
00:00:03.984 |I| ModLoader LoadCheats: Build ids found for title 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    9B4E43650501A4D4489B4BBFDB740F26AF3CF850000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:03.987 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:04.060 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.2.1 [0100f2c0115b6000] [64-bit]
00:00:04.072 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:04.091 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:05.340 |N| GUI.RenderLoop Gpu PrintGpuInformation: Intel Intel(R) Iris(R) Xe Graphics (Vulkan v1.2.204, Driver v0.404.1404)
00:00:05.349 |I| GPU.MainThread Gpu LoadShaders: Loading 8057 shaders from the cache...
00:00:16.725 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:20.027 |I| HLE.GuestThread.25 Ptc LoadTranslations: 140952 translated functions loaded
00:00:20.078 |I| HLE.GuestThread.25 Ptc MakeAndSaveTranslations: 0 of 63 functions translated | Thread count: 7
00:00:20.325 |I| HLE.GuestThread.25 Ptc MakeAndSaveTranslations: 63 of 63 functions translated | Thread count: 7 in 0.2450429 s
00:00:20.477 |S| HLE.OsThread.26 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:20.491 |S| HLE.OsThread.26 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:20.491 |S| HLE.OsThread.26 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:20.492 |S| HLE.OsThread.26 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:20.505 |S| HLE.OsThread.26 ServicePctl Initialize: Stubbed. 
00:00:24.744 |S| HLE.OsThread.26 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:24.745 |S| HLE.OsThread.26 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:24.745 |S| HLE.OsThread.26 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:24.746 |S| HLE.OsThread.26 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:24.746 |S| HLE.OsThread.26 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:24.950 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:24.958 |I| HLE.OsThread.26 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:24.960 |I| HLE.OsThread.26 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:24.983 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:25.006 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:25.072 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:25.073 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:25.075 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:25.077 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:25.077 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:25.077 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:25.077 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:25.080 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:25.112 |S| HLE.OsThread.26 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:25.115 |S| HLE.OsThread.26 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:25.115 |S| HLE.OsThread.26 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:25.133 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:25.135 |I| GUI.WindowThread Hid SetupNpad: Disconnected Controller JoyconPair from Player1
00:00:25.138 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:25.139 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:25.140 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 102 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:25.142 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:26.841 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:26.841 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:30.282 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:30.286 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:30.638 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:30.643 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV11
00:00:30.681 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:30.682 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:30.685 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:30.752 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:30.754 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:31.250 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:31.890 |S| HLE.OsThread.26 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:31.891 |S| HLE.OsThread.26 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:32.551 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:32.552 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:32.552 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:32.552 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:34.096 |S| HLE.OsThread.26 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:34.097 |S| HLE.OsThread.26 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:34.097 |S| HLE.OsThread.26 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:34.623 |I| Ptc Save: Saved Translation Cache (size: 195485794 bytes, translated functions: 142182).
00:00:34.688 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:00:34.688 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:00:34.704 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:34.907 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: bootup_time 
 Report: {
    "BootupTimeUs": 17635,
    "system_report_tag": 2175206328
}

00:00:34.911 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: erepo_region 
 Report: {
    "Region": 1,
    "Language": 1,
    "StandardTimeName": "UTC",
    "UtcOffsetSeconds": 0,
    "system_report_tag": 2759414308
}

00:00:34.911 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: erepo_time 
 Report: {
    "ActiveTime": 14,
    "UpdatedTime": 0,
    "system_report_tag": 2759414308
}

00:00:34.912 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: erepo_playstyle 
 Report: {
    "system_report_tag": 2759414308
}

00:00:34.914 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: erepo_network_status 
 Report: {
    "NetworkInterface": {
        "TypeCode": 64,
        "Value": "0x00000000000000000000000000000000"
    },
    "LinkLevel": {
        "TypeCode": 65,
        "Value": "0x00"
    },
    "FrequencyBand": {
        "TypeCode": 66,
        "Value": "0x00000000000000000000"
    },
    "system_report_tag": 2759414308
}

00:00:34.961 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:35.026 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: erepo_active_beacon 
 Report: {
    "IntervalTime": 0,
    "UpdatedTime": 0,
    "system_report_tag": 0
}

00:00:38.656 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 102 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:38.661 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player2}
00:00:38.662 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player3}
00:00:38.662 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player4}
00:00:47.080 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:48.625 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 4,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 2087851477,
    "EventInfo": "Dm_OP_0037",
    "PlayerPosX": 3.4059776E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406162E-11,
    "system_report_tag": 2175206328
}

00:00:48.799 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 4,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 2087851477,
    "EventInfo": "Dm_OP_0038",
    "PlayerPosX": 3.4059776E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406162E-11,
    "system_report_tag": 2175206328
}

00:00:49.373 |S| HLE.OsThread.26 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:00:50.395 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 484518 bytes, profiled functions: 141017).
00:00:58.653 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: option_data 
 Report: {
    "PlayTime": 4,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 2087851477,
    "BoolOptions": 1033,
    "CameraRotateSpeed": 2,
    "DisplayMode": 0,
    "MessageWindowTransparency": 0,
    "VoiceLanguage": 0,
    "Action": 1,
    "Cancel": 2,
    "Jump": 3,
    "Attack": 4,
    "SpecialPower": 5,
    "Attention": 6,
    "Throw": 7,
    "Bow": 8,
    "PlusMenu": 9,
    "MinusMenu": 10,
    "SpecialPowerShortcut": 11,
    "CompanionShortcut": 13,
    "PouchShortcut": 14,
    "Whistle": 12,
    "Crouch": 25,
    "Scope": 33,
    "PresetType": 0,
    "system_report_tag": 2175206328
}

00:00:58.686 |S| HLE.OsThread.26 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:01:20.363 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 484520 bytes, profiled functions: 141018).
00:01:21.548 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:21.713 |I| HLE.OsThread.19 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 102
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 11629,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 739319794,
    "EventInfo": "DefaultBootEvent",
    "PlayerPosX": 323.27383,
    "PlayerPosY": 124.558304,
    "PlayerPosZ": 534.86206,
    "system_report_tag": 2175206328
}

00:01:22.262 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:34.604 |E| HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 41
   at InvokeStub_IStorage.Read(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 445
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 285
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1019

### Game version

1.2.1

### CPU

11th Gen Intel(R) Core(TM) i5-1135G7 

### GPU

Intel Iris xe

### RAM

12

### List of applied mods

none

### Additional context?

All Settings on default no apps open in the background.

Game crashed even on the update before the latest Ryujinx update using the same exact steps.

Using an Acer Aspire 315-58 laptop.

Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	12.0 GB (11.8 GB usable)
Product ID	00342-22111-55109-AAOEM
System type	64-bit operating system, x64-based processor

Laptop plays Saints Row 2022 low graphics with minimal lag.
Also plays Assassin's Creed Valhalla low graphics with some lag.(may or may not be relevant however it gives context to what the intel iris xe card with 12gb of ram is capable of.)

Tears of the Kingdom was laggy but playable with less than 20fps before reaching Hyrule officially when first playing the game.

**Comment by MetrosexualGarbodor** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error
