### ISSUE TITLE
[Bug] Graphics artifact LIS Before the storm

### ISSUE THREAD

**Issue by iAmSuperMan12** [Ryujinx/Ryujinx#5702]
### Description of the issue

Starting from the main menu and throughout the game there are artifacts from overlay objects and sprites. This may disappear if you switch VSYNC.
The playback speed is also unstable and there are drops of up to 16 fps in native resolution and standalone mode
<img width="1552" alt="Снимок экрана 2023-09-19 в 22 57 19" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/5075ab23-efb3-46f1-8720-09f885b7916f">
<img width="1552" alt="Снимок экрана 2023-09-19 в 23 05 02" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/e330ebc8-b1ef-4f06-970e-0056ab2f0f62">
<img width="1552" alt="Снимок экрана 2023-09-19 в 23 05 24" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/7cd5cdd2-685d-4981-9006-a6e7d39a87b8">
<img width="1552" alt="Снимок экрана 2023-09-19 в 23 32 42" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/d418dcdc-f979-4f28-a7ef-728ae5c84afc">

### Reproduction steps

throughout the game

### Log file

[Ryujinx_1.1.1019_2023-09-19_23-00-21.log](https://github.com/Ryujinx/Ryujinx/files/12671206/Ryujinx_1.1.1019_2023-09-19_23-00-21.log)

### OS

Mac OS 1

### Ryujinx version

1.1.1019

### Game version

1.0

### CPU

apple m1

### GPU

apple gpu

### RAM

16

**Comment by AcK77** [comment]
Are you able to reproduce using build here: https://github.com/Ryujinx/Ryujinx/pull/5700#issuecomment-1726685346

**Comment by iAmSuperMan12** [comment]
> Are you able to reproduce using build here: [#5700 (comment)](https://github.com/Ryujinx/Ryujinx/pull/5700#issuecomment-1726685346)

The nature of the glitch has changed a little, but the essence of the problem remains the same.
I noticed that the translucent artifacts disappeared, but the large ones remained

<img width="1552" alt="Снимок экрана 2023-09-20 в 22 19 23" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/32fb88e7-67ca-4acb-83e1-00bb167610f8">
<img width="1552" alt="Снимок экрана 2023-09-20 в 22 23 03" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/fb53fd60-bcd7-4d26-a08e-c5eac9206075">

**Comment by AcK77** [comment]
Since it's a game specific issue, could you please report it at https://github.com/Ryujinx/Ryujinx-Games-List/issues/4050 ?
Thanks!
