### ISSUE TITLE
TOTK Crash (and mild graphics issues) 1.1 + 8e1ae70 [Bug]

### ISSUE THREAD

**Issue by cobbycobbycobcob** [Ryujinx/Ryujinx#5706]
### Description of the issue

TOTK crashes while gliding at high altitudes

Also mild graphical 'flickering', primarily in distant objects.

### Reproduction steps

Install 1.1 + 8e1ae70; run TOTK 1.2.1; launch high into the air and glide

### Log file

[Ryujinx_1.1.0+8e1ae70_2023-09-20_12-26-36.log](https://github.com/Ryujinx/Ryujinx/files/12675953/Ryujinx_1.1.0%2B8e1ae70_2023-09-20_12-26-36.log)
[Ryujinx_1.1.0+8e1ae70_2023-09-20_13-27-24.log](https://github.com/Ryujinx/Ryujinx/files/12675955/Ryujinx_1.1.0%2B8e1ae70_2023-09-20_13-27-24.log)

### OS

OS 13.3.1

### Ryujinx version

1.1.0 + 8e1ae70 

### Game version

1.2.1

### CPU

M2

### GPU

M2

### RAM

16GB

### Additional context?

+ 8e1ae70 resolves much of the flickering; up until the crash, I was smiling while thinking 'damn, they've done it ...'

Thank you for your work!

**Comment by MetrosexualGarbodor** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error
