### ISSUE TITLE
[Bug] Avatar LA - Quest for Balance glitches and poor performance

### ISSUE THREAD

**Issue by appvitor** [Ryujinx/Ryujinx#5707]
### Description of the issue

Avatar The Last Airbender Quest for Balance goes in game and runs, but the performance is not the best, around 15 FPS.
Cinematics are flawless, but in-game glitches happens a lot, specially when world effects are on screen.

### Reproduction steps

Add the game
Run the game
Glitches start to happen already on main menu

### Log file

[Ryujinx_1.1.1013_2023-09-18_23-58-24.log](https://github.com/Ryujinx/Ryujinx/files/12677120/Ryujinx_1.1.1013_2023-09-18_23-58-24.log)
[Ryujinx_1.1.1013_2023-09-20_16-41-21.log](https://github.com/Ryujinx/Ryujinx/files/12677121/Ryujinx_1.1.1013_2023-09-20_16-41-21.log)
[Ryujinx_1.1.1013_2023-09-20_17-01-32.log](https://github.com/Ryujinx/Ryujinx/files/12677122/Ryuj

### OS

Mac OS 14

### Ryujinx version

1.1.1013

### Game version

0.3.0.29423

### CPU

M1

### GPU

M1

### RAM

8GB

### List of applied mods

No mods applied

### Additional context?

Not using newer builds of Ryujinx due to serious glitches that have been introduced in version 1.1.1014 and hasn't been fixed yet.
<img width="1680" alt="Screenshot 2023-09-20 at 4 56 50 PM" src="https://github.com/Ryujinx/Ryujinx/assets/21270922/d90a0d0b-886e-4def-b425-18c0754dca2f">

**Comment by appvitor** [comment]
Re-added log file that was corrupted
Besides, that, any idea what is that "RyuPlayer"on the corner of the screen?
[Ryujinx_1.1.1013_2023-09-20_17-01-32.log](https://github.com/Ryujinx/Ryujinx/files/12677180/Ryujinx_1.1.1013_2023-09-20_17-01-32.log)

**Comment by AcK77** [comment]
"RyuPlayer" is the default player name. You can change it by editing your user profile in Ryujinx.

I see this issue more like a compatibility report, could you please open a formatted issue at https://github.com/Ryujinx/Ryujinx-Games-List/issues 

Thanks.
