### ISSUE TITLE
Controller disconnect reconnect 

### ISSUE THREAD

**Issue by 007mesen** [Ryujinx/Ryujinx#5709]
### Description of the issue

When a controller disconnects due to time out or dead batteries emulator needs to be exited and restarted. Or if a controller that was powered off powers on to join in again must be restarted. Is it possible to add some kind of refresh method?

### Reproduction steps

Windows 10 64bit
Disconnect reconnect a controller after emulator launched

### Log file

Na

### OS

Windows 10

### Ryujinx version

1.1.1017

### CPU

I5-9400

### GPU

Nvidia gt1030 ddr5

### RAM

32gb

### List of applied mods

None

**Comment by AcK77** [comment]
Duplicated of #5470
