### ISSUE TITLE
[Bug] TOTK not rendering anything but UI correctly

### ISSUE THREAD

**Issue by LoneWolf155** [Ryujinx/Ryujinx#5712]
### Description of the issue

Using the current release of Ryujinx (1.1.1020) I am having issues where Zelda Tears of the Kingzom is not rendering anything correctly except the UI elements within the game. This happens immediately within the main menu and persists after loading a save making the game unplayable. It appears as though it is stretching the colors of rendered elements across the screen.

![ryujinx_capture_2023-09-21_09-28-37](https://github.com/Ryujinx/Ryujinx/assets/22579074/342dcdd7-e73c-45ae-991d-844b852314d7)

### Reproduction steps

Simply using Vulkan as the graphics backend makes this occur, all other settings seem to be irrelevant.

### Log file

[Ryujinx_1.1.1020_2023-09-21_09-12-18.log](https://github.com/Ryujinx/Ryujinx/files/12685209/Ryujinx_1.1.1020_2023-09-21_09-12-18.log)

### OS

Windows 10

### Ryujinx version

1.1.1020

### Game version

1.1.0

### CPU

AMD Ryzen 7 3700X

### GPU

AMD Radeon RX 6800

### RAM

32 GB

### List of applied mods

None

### Additional context?

Here is some additional information on my installed drivers and system
![Capture](https://github.com/Ryujinx/Ryujinx/assets/22579074/c8c7e434-58df-4ded-b438-7052e11225e0)

**Comment by Ogloppi** [comment]
I have this same issue.
After installing [Adrenalin Edition 23.9.2](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-9-2) drivers, graphics looked the same as with @LoneWolf155.
After downgrading drivers back to [Adrenalin Edition 23.9.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-9-1), my issue disappeared.

- OS: Windows 10
- CPU: AMD Ryzen 7 3700X
- GPU: AMD Radeon RX 6600 XT
- RAM: 16 GB
- Ryujinx version: 1.1.1021
- Ryujinx graphics backend: Vulkan
- Game version: 1.2.1
- No mods

**Comment by AcK77** [comment]
Iirc, 23.9.3 was released 2 days ago, is this issue fixed?

**Comment by Ceremony64** [comment]
> Iirc, 23.9.3 was released 2 days ago, is this issue fixed?

nope, issue persists (on a 5700 XT)

**Comment by Ogloppi** [comment]
I was about to write the same thing.
On 23.9.3 the issue persists, and downgrading to 23.9.1 fixes the issue.

Here is a logfile (on 23.9.3 driver) while booting the game to start screen:
[Ryujinx_1.1.1037_2023-09-30_18-47-13.log](https://github.com/Ryujinx/Ryujinx/files/12775172/Ryujinx_1.1.1037_2023-09-30_18-47-13.log)

**Comment by 2ez4kyd** [comment]
I updated to [Adrenalin Edition Preview Driver for AMD Fluid Motion Frames](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-30-afmf-tech-preview) and this fixes my issue on this. (6600 xt)

**Comment by gdkchan** [comment]
Closing as I believe this is fixed by #5757, can be re-opened if the issue still exists on latest version.
