### ISSUE TITLE
Make Support For Android

### ISSUE THREAD

**Issue by Ishan0981** [Ryujinx/Ryujinx#5715]
### Overview

Make Support For Android Devices And You Know The Yuzu Already Came To Android Devices. If You Provide Better Performance Than Yuzu Then You Will Get Huge Support From Mobile Cumunity And Also You Can Release A Early Access For Paid Then Also You Can Earn From The Your App.

### Smaller details

Make Support For Android Devices

### Nature of request

Make Support For Android Devices

### Why would this feature be useful?

Make Support For Android Devices And You Know The Yuzu Already Came To Android Devices. If You Provide Better Performance Than Yuzu Then You Will Get Huge Support From Mobile Cumunity And Also You Can Release A Early Access For Paid Then Also You Can Earn From The Your App.

**Comment by Foul-Tarnished** [comment]
Man, stop using uppercase letter for every word seriously

If you want an highly optimized switch emulator for Android, then support Strato :)
