### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by COringning** [Ryujinx/Ryujinx#5718]
### Description of the issue

[1.1.1021] Mac m2 pro,without any sounds

### Reproduction steps

anytime I open

### Log file

none

### OS

Mac os 13.2.1

### Ryujinx version

1.1.1021

### Game version

1.2

### CPU

m2 pro

### GPU

-

### RAM

16

**Comment by MetrosexualGarbodor** [comment]
Without a log or any information whatsoever it's impossible to know what's wrong. Also, do not open issues for help, ask on Discord instead.
