### ISSUE TITLE
[Bug] macOS – Vulkan Collapse

### ISSUE THREAD

**Issue by aaabbbaaa** [Ryujinx/Ryujinx#5722]
### Description of the issue

runs New Super Mario Bros. U Deluxe and Super Mario Odyssey games and it will crash

### Reproduction steps

game begin play

### Log file

[Ryujinx_1.1.1004_2023-09-17_18-25-03.log](https://github.com/Ryujinx/Ryujinx/files/12708504/Ryujinx_1.1.1004_2023-09-17_18-25-03.log)
[Ryujinx_1.1.1014_2023-09-16_23-07-30.log](https://github.com/Ryujinx/Ryujinx/files/12708505/Ryujinx_1.1.1014_2023-09-16_23-07-30.log)
[Ryujinx_1.1.1014_2023-09-24_20-37-37.log](https://github.com/Ryujinx/Ryujinx/files/12708506/Ryujinx_1.1.1014_2023-09-24_20-37-37.log)

### OS

macOS Ventura 13.4.1

### Ryujinx version

1.0.1014

**Comment by AcK77** [comment]
macOS with AMD GPU is barely supported, I suggest you to use bootcamp and use the emulator with Windows.
