### ISSUE TITLE
[Bug] Random texture flicker and glitches Master Detective Archives: Rain Code

### ISSUE THREAD

**Issue by zany130** [Ryujinx/Ryujinx#5725]
### Description of the issue

similar to https://github.com/Ryujinx/Ryujinx/issues/5428 I get flicking textures but on top of that sometimes colors look weird or corrupted 

### Reproduction steps

Happens randomly while playing, but happens often

### Log file

[Ryujinx_1.0.0-dirty_2023-09-24_21-13-31.log](https://github.com/Ryujinx/Ryujinx/files/12710298/Ryujinx_1.0.0-dirty_2023-09-24_21-13-31.log)

### OS

Garuda Linux

### Ryujinx version

latest git as of Sat 23 Sep 2023 09:21:34 PM EDT

### Game version

1.3.2

### CPU

5600x

### GPU

6700 XT

### RAM

32

### Additional context?
This is an extreme case I got by viewing the first gab with Halara
![image](https://github.com/Ryujinx/Ryujinx/assets/25832539/f3e53202-aa7b-4064-802a-5d07d382695f)

**Comment by piplup55** [comment]
if you are going to report a bug, please make sure you are using the latest version of [master](https://github.com/Ryujinx/release-channel-master/releases/latest), we don't accept bugs for "custom builds" as we can't verify if the code has been altered in anyway

**Comment by AcK77** [comment]
Yeah please, update the current issue with the state of the build our CI provide. Thanks.

**Comment by zany130** [comment]
I got it from https://aur.archlinux.org/packages/ryujinx-git, so isn't that the same as if I built from master manually?

**Comment by TSRBerry** [comment]
It is, I wasn't aware it doesn't set the version information during the build.
I asked the maintainer to add the missing steps, so it won't be flagged as a custom build anymore.

**Comment by zany130** [comment]
haven't been able to reproduce this for a while now... closing for now
