### ISSUE TITLE
[Bug] Master Detective Archives:Rain Code Crash CH.2 mystery dungeon 

### ISSUE THREAD

**Issue by zany130** [Ryujinx/Ryujinx#5733]
### Description of the issue

Game crashes after clearing all three routes

### Reproduction steps

1.load provided save file
2. progress through text until Yuma mentions looking at the case from a new prespective
3. game freezes

### Log file

[Ryujinx_1.1.1032_2023-09-26_21-24-58.log](https://github.com/Ryujinx/Ryujinx/files/12733181/Ryujinx_1.1.1032_2023-09-26_21-24-58.log)

### OS

Garuda Linux

### Ryujinx version

1.1.1032 also tested on the latest git, but due to using the aur package it doesn't report the version 

### Game version

1.3.2

### CPU

5600x

### GPU

6700 XT

### RAM

32

### List of applied mods

https://github.com/StevensND/switch-port-mods/tree/main/Master%20Detective%20Archives:%20RAIN%20CODE

### Additional context?

[saves.zip](https://github.com/Ryujinx/Ryujinx/files/12733217/saves.zip)

**Comment by gdkchan** [comment]
Are you using any resolution mods? Those mods make the game use more memory than the Switch has in some cases and crash. You can try to enable the "Use alternative memory layout" in the Settings > System tab, You can also try disabling the mod.

**Comment by zany130** [comment]
my bad jumped the gun and thought it was a ryujinx bug. Either disabling the mod or enabling use alternative memory layout fixes the issue
