### ISSUE TITLE
[Bug] ryujinx wont open

### ISSUE THREAD

**Issue by SayianRonin1996** [Ryujinx/Ryujinx#5736]
### Description of the issue

when I open ryujinx the diagnostics box with computer code opens up and minimised and then closed and ryujinx wont open anymore.

### Reproduction steps

not sure how to repeat as it happens every time i try opening ryujinx

### Log file

00:00:00.042 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.047 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.047 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.048 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.048 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.049 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.050 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1F99
00:00:00.050 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.051 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.051 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.068 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1015
00:00:00.073 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.073 |N| Application Print: CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz ; 8 logical
00:00:00.074 |N| Application Print: RAM: Total 8023 MiB ; Available 1505 MiB
00:00:00.077 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.077 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.580 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 254

### OS

windows 11

### Ryujinx version

latest version of ryujinx as of this report being submitted

**Comment by AcK77** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-cant-open-ryujinx-e-application--unhandled-exception-caught-systemtypeinitializationexception-the-type-initializer-for-gtkapplication-threw-an-exception-----systemdllnotfoundexception-gtk-libgtk-3-0dll-libgtk-3so0-libgtk-30dylib-gtk-3dll

You can come to our discord for support aswell.
