### ISSUE TITLE
[Feature Request] Webapp Support

### ISSUE THREAD

**Issue by SuperSmashPastel** [Ryujinx/Ryujinx#5737]
### Overview

Any Support for Web Applets does not work on here. but needs an update for Ryujinx to feature Webapp support like for mods for SSBU like HDR for example. because loading Custom Smash in the menu crashes the game because no webapp support. I really wish you could make webapp support for Ryujinx. to work like a regular switch 

### Smaller details

Coding Webapplet support by using lots of code, testing HTML pages in the Switch Emulator.

### Nature of request

It would work very well for games like Smash. for Modding and stuff

### Why would this feature be useful?

Useful? because I hope this would happen on a new version where it supports webapp like let's say HDR for Ultimate has webapp support. this needs to happen because we don't want to find HDR crashing when opening Mii Fighter or Custom Smash. and one more thing, this also has to work on the Avalonia build of Ryujinx

**Comment by AcK77** [comment]
Duplicated of #1004
