### ISSUE TITLE
[Bug] Ys X: Nordics has no audio

### ISSUE THREAD

**Issue by To-Kondo** [Ryujinx/Ryujinx#5740]
### Description of the issue

The bootup screen has sound, but the menu and onwards doesn't, I believe it's a FFmpeg audio compression issue.

### Reproduction steps

Boot up the game, sound will play but instantly stop at the main menu

### Log file

00:00:00.043 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.047 |I| Configuration LogValueChange: ResScaleCustom set to: 1.5
00:00:00.047 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.048 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.048 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.049 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.049 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73EF
00:00:00.050 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.050 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.050 |I| Configuration LogValueChange: ScalingFilterLevel set to: 10
00:00:00.066 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1035
00:00:00.071 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.071 |N| Application Print: CPU: AMD Ryzen 7 3700X 8-Core Processor ; 16 logical
00:00:00.071 |N| Application Print: RAM: Total 32678 MiB ; Available 20422 MiB
00:00:00.074 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.074 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.835 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.
00:00:00.405 |N| Application LoadGuestApplication: Using Firmware Version: 16.0.0
00:00:01.460 |N| GUI.RenderThread Gpu PrintGpuInformation: ATI Technologies Inc. AMD Radeon RX 6650 XT (4.6.0 Compatibility Profile Context 23.9.1.230911)
00:00:18.186 |E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 00000299040835c0] illegal short term buffer state detected
00:00:18.284 |E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 00000299040835c0] illegal short term buffer state detected
00:00:18.616 |E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 00000299040835c0] illegal short term buffer state detected
00:00:18.883 |E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 00000299040835c0] illegal short term buffer state detected
00:00:19.116 |E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 00000299040835c0] illegal short term buffer state detected

### OS

Windows 11

### Ryujinx version

1.1.1035

### Game version

1.02

### CPU

Ryzen 7 3700X

### GPU

AMD RX 6650 XT

### RAM

32GB

**Comment by Markin-Wang** [comment]
Yes, I have the same issue with mac os, no audio.
