### ISSUE TITLE
[Feature Request] Implement FSR3 Frame Generation

### ISSUE THREAD

**Issue by TibRib** [Ryujinx/Ryujinx#5749]
### Overview

Adding FSR3 Optical Flow frame generation, once the AMD repository is open, will be a game changer for games that depend on 30FPS, allowing to interpolate frames between the game frames and suit to 60 or 120hz monitors.

### Smaller details

The repository will be available soon on https://github.com/GPUOpen-Effects. The open source repository (MIT licensed) will allow us to upgrade from FSR to FSR3 as well as eventually benefit from frame generation.

### Nature of request

Update FSR implementation with FSR3 & frame generation.

### Why would this feature be useful?

Will allow games that depend on 30fps as a fixed delta to appear smoother for end users.

**Comment by MetrosexualGarbodor** [comment]
Frame generation requires information from the game engine that Ryujinx does not have access to. Also, since every game is different, it would be up to modders to implement this for individual games, although that's unrealistic as well.

**Comment by MutantAura** [comment]
It may be possible to use the generic AFMF whenever AMD decide to support Vulkan applications instead of just DX11/12. But that is a driver setting and not something programs need to implement.
