### ISSUE TITLE
[Feature Request] save editor

### ISSUE THREAD

**Issue by Fujin33** [Ryujinx/Ryujinx#5758]
### Overview

save editor for Fae farm switch

### Smaller details

save editor for fae farm on switch

### Nature of request

Bonjour, mon épuisette à insecte n'a pas évoluer quand je l'ai acheter. impossible de revenir en arrière ni de le corriger.
existe t'il un éditeur de sauvegarde? merci

Hello, my insect net did not evolve when I bought it. It’s impossible to go back or correct it.
is there a backup editor? THANKS

### Why would this feature be useful?

Toute personne avec un bug pourrait le résoudre.
un matériaux manquant,  un peu comme l'éditeur de sauvegarde Animal Crossing ou Xenoblade Chronicles 3.

Anyone with a bug could fix it.
a missing material, a bit like the animal crossing save editor or xenoblade chronicles 3.

**Comment by GamerzHell9137** [comment]
> ### Overview
> 
> save editor for Fae farm switch
> ### Smaller details
> 
> save editor for fae farm on switch
> ### Nature of request
> 
> Bonjour, mon épuisette à insecte n'a pas évoluer quand je l'ai acheter. impossible de revenir en arrière ni de le corriger. existe t'il un éditeur de sauvegarde? merci
> 
> Hello, my insect net did not evolve when I bought it. It’s impossible to go back or correct it. is there a backup editor? THANKS
> ### Why would this feature be useful?
> 
> Toute personne avec un bug pourrait le résoudre. un matériaux manquant, un peu comme l'éditeur de sauvegarde Animal Crossing ou Xenoblade Chronicles 3.
> 
> Anyone with a bug could fix it. a missing material, a bit like the animal crossing save editor or xenoblade chronicles 3.

Lorsque vous rapportez quelque chose sur github, cela doit être écrit en anglais. Ce message a été écrit en utilisant DeepL, vous devriez donc l'utiliser également si vous postez la prochaine fois sur github ici.

Pour ce qui est de votre problème, les jeux spécifiques ont besoin d'éditeurs spécifiques, vous devrez donc trouver un éditeur de fae farm en ligne. Si vous parlez de sauvegardes, je pense qu'il est trop tard pour cela. Il y a un PR ouvert en ce moment qui ajoute l'option de sauvegarder vos sauvegardes mais pour l'instant il n'y a rien que vous puissiez faire à ce sujet.

**Comment by MetrosexualGarbodor** [comment]
It's not up to emulator developers to create save editors.
