### ISSUE TITLE
[Bug]emudeck on steamdeck cannot boot roms after update

### ISSUE THREAD

**Issue by Tntrance** [Ryujinx/Ryujinx#5763]
### Description of the issue

running ryujinx on a steamdeck using emudeck. was able to play nsp games fine untul an update today. 1.1.1401 or something. now the nsps wont load. how do k change back to the previous update or fix this thx

### Reproduction steps

open ryujinx
double clicking nsp game to play
system freezes

### Log file

00:00:00.137 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.144 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.145 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.146 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.148 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.149 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.150 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x163F
00:00:00.152 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.153 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.153 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.157 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.181 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.181 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.181 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.181 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.181 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.182 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.182 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.182 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.182 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.183 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.183 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.184 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.184 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.185 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.185 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.190 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1041
00:00:00.208 |N| Application Print: Operating System: Linux 5.13.0-valve37-1-neptune #1 SMP PREEMPT Thu, 17 Aug 2023 23:47:04 +0000 (X64)
00:00:00.208 |N| Application Print: CPU: AMD Custom APU 0405   AmdCcxVhFf3PeiInit Entry ; 8 logical
00:00:00.210 |N| Application Print: RAM: Total 14818 MiB ; Available 12753 MiB
00:00:00.214 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.215 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:39.104 |E| .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:40.373 |E| .NET ThreadPool Worker Gtk-Message: 17:04:02.052: Failed to load module "canberra-gtk-module"
00:00:41.578 |E| .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:41.579 |E| .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:41.678 |E| .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:41.680 |E| .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:46.680 |E| .NET ThreadPool Worker ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:46.898 |E| .NET ThreadPool Worker Gtk-Message: 17:04:08.576: Failed to load module "canberra-gtk-module"

### OS

steamdeck linux

### Ryujinx version

1.1.1041

### List of applied mods

none

**Comment by gdkchan** [comment]
Is it still broken on version 1.1.1042?

**Comment by Tntrance** [comment]
It is working after the new update that came 1 hour later! Thanks for the response!
