### ISSUE TITLE
[Bug] freezing problem in Pokemon Sword and Shield

### ISSUE THREAD

**Issue by Lucas-Zxc** [Ryujinx/Ryujinx#5774]
### Description of the issue

in the latest versions, a new bug in Pokemon Sword and probably Shield is occurring, where in it, the game simply freezes after playing it for some time, but that doesn't take long

### Reproduction steps

it's simple, just play in the latest versions of the emulator that the game will freeze at some point

### Log file

[Ryujinx_1.1.1037_2023-09-29_12-49-43.log](https://github.com/Ryujinx/Ryujinx/files/12838024/Ryujinx_1.1.1037_2023-09-29_12-49-43.log)

### OS

Windows 11

### Ryujinx version

1.1.1037, now 1.1.1047

### Game version

1.3.2

### CPU

Intel I5 12400f

### GPU

Nvidia Rtx 3060 12gb

### RAM

16 GB Ram Dual Channel

**Comment by gdkchan** [comment]
Let's track it on #5778 that is more detailed (has the specific version where the problem started happening).
