### ISSUE TITLE
[Bug] Regression in Pokemon Sword/Shield

### ISSUE THREAD

**Issue by Littl3Guy** [Ryujinx/Ryujinx#5778]
### Description of the issue

Pokemon SW/SH freeze after about 20 minutes of gameplay.

### Reproduction steps

Start the game and wait 20 minutes.

### Log file

[Ryujinx_1.1.1026_2023-10-07_18-07-52.log](https://github.com/Ryujinx/Ryujinx/files/12839384/Ryujinx_1.1.1026_2023-10-07_18-07-52.log)

### OS

Windows 11

### Ryujinx version

1.1.1026

### Game version

1.3.2

### CPU

R7 3800x

### GPU

RX 6700xt

### RAM

16GB

### List of applied mods

None

**Comment by gdkchan** [comment]
Do you know when this started happening? I have only seen this being mentioned recently, so I guess it's a recent regression? Or maybe it was just a coincidence.

**Comment by Littl3Guy** [comment]
> Do you know when this started happening? I have only seen this being mentioned today, so I guess it's a recent regression? Or maybe it was just a coincidence.

It started in 1.1.1026, I guess I should have mentioned that.

**Comment by gdkchan** [comment]
So it was broken by #5652 I guess? Seems plausible since this game calls BSD sockets service non-stop.

**Comment by TSRBerry** [comment]
Investigated this today and found a solution! I'm going to PR it tomorrow though, since I'm pretty tired already.
I gotta say, only being able to test if your change worked every 20 minutes is pretty tiring. :sweat_smile:

**Comment by kergepeter** [comment]
> Investigated this today and found a solution! I'm going to PR it tomorrow though, since I'm pretty tired already. I gotta say, only being able to test if your change worked every 20 minutes is pretty tiring. 😅

I just wanted to thank you for this. My 7 yo son just started playing this game and for us it froze every 10 minutes. I just have tested it now for 30 min and it looks like this issue is fixed. I am really grateful!!
