### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PokenFan** [Ryujinx/Ryujinx#5789]
### Description of the issue

O emulador ryujinx fecha ao abrir o pokemon violet 

### Reproduction steps

quando eu tento abrir o o jogo violet no emulador ryujinx ele fecha sozinho e não abre mas nos jogos shild e sword ele abre normalmente.

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2023-10-09_14-12-23.log](https://github.com/Ryujinx/Ryujinx/files/12848907/Ryujinx_1.1.0-ldn3.1.3_2023-10-09_14-12-23.log)
[Ryujinx_1.1.0-ldn3.1.3_2023-10-09_14-26-39.log](https://github.com/Ryujinx/Ryujinx/files/12848908/Ryujinx_1.1.0-ldn3.1.3_2023-10-09_14-26-39.log)
[Ryujinx_1.1.0-ldn3.1.3_2023-10-09_14-30-46.log](https://github.com/Ryujinx/Ryujinx/files/12848909/Ryujinx_1.1.0-ldn3.1.3_2023-10-09_14-30-46.log)

### OS

windows 10

### Ryujinx version

1.1.0-Ind3.1.3

### Game version

2.0.1

### CPU

i5-10300h

### GPU

NVIDIA GTX1650

### RAM

8 GB

### List of applied mods

nenhum

### Additional context?

Pokémon escudo e sapada roldão normalmente

**Comment by MetrosexualGarbodor** [comment]
Your issue is likely caused by the mods you're using.

**Comment by PokenFan** [comment]
strange because I'm not using any mod on it
