### ISSUE TITLE
Fire Emblem: Three Houses  Using 'Divine Pulse' ability cause 100% crash on MacOS Sonoma(14.0) M1 Max 64GB.

### ISSUE THREAD

**Issue by hakcumx** [Ryujinx/Ryujinx#5790]
Using 'Divine Pulse' ability cause 100% crash on MacOS Sonoma(14.0) M1 Max 64GB.
Including ryujinx version 1.1.1036~1.1.1049.
When crash happend no ryujinx logs were dumped, only got MacOS error log.

Thread 60 Crashed:
0 libsystem_kernel.dylib       0x1843cb11c __pthread_kill + 8
1   libsystem_pthread.dylib   0x184402cc0 pthread_kill + 288
2   libsystem_c.dylib              0x184312a50 abort + 180
3   Ryujinx                       	       0x103500000 PROCAbort + 64
4   Ryujinx                       	       0x1034fff10 PROCEndProcess(void*, unsigned int, int) + 388
5   Ryujinx                       	       0x103143d94 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 876
6   Ryujinx                       	       0x103143e78 DispatchManagedException(PAL_SEHException&, bool) + 68
7   Ryujinx                       	       0x1030a6e9c IL_Throw(Object*) + 536
8   ???                           	       0x10b5fa914 ???
9   ???                           	       0x10c5ca518 ???
10  ???                           	       0x10c5c9148 ???
11  ???                           	       0x10c804a78 ???
12  ???                           	       0x10c804888 ???
13  ???                           	       0x10c5759b8 ???
14  ???                           	       0x10b434180 ???
15  ???                           	       0x10ab24030 ???
16  ???                           	       0x1074bc4bc ???
17  ???                           	       0x1074bc3a8 ???
18  ???                           	       0x1074bc1a0 ???
19  Ryujinx                       	       0x1031cdff4 CallDescrWorkerInternal + 132
20  Ryujinx                       	       0x1030438a0 DispatchCallSimple(unsigned long*, unsigned int, unsigned long,unsigned int) + 272
21  Ryujinx                       	       0x103057fbc ThreadNative::KickOffThread_Worker(void*) + 148
22  Ryujinx                       	       0x103011cdc ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 260
23  Ryujinx                       	       0x103012248 ManagedThreadBase::KickOff(void (*)(void*), void*) + 32
24  Ryujinx                       	       0x103058094 ThreadNative::KickOffThread(void*) + 172
25  Ryujinx                       	       0x1035045ec CorUnix::CPalThread::ThreadEntry(void*) + 380
26  libsystem_pthread.dylib       	       0x184403034 _pthread_start + 136
27  libsystem_pthread.dylib       	       0x1843fde3c thread_start + 8

[crash_log.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/12837566/crash_log.txt)
[Ryujinx_1.1.1049_2023-10-08_17-37-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12840320/Ryujinx_1.1.1049_2023-10-08_17-37-01.log)

_Originally posted by @hakcumx in https://github.com/Ryujinx/Ryujinx-Games-List/issues/230#issuecomment-1751683452_

**Comment by gdkchan** [comment]
Can you attach a save to allow the issue to be reproduced easily?

**Comment by hakcumx** [comment]
> Can you attach a save to allow the issue to be reproduced easily?
You can choose any combat scene to reproduce this problem.
[0000000000000007.zip](https://github.com/Ryujinx/Ryujinx/files/12853407/0000000000000007.zip)
