### ISSUE TITLE
Resolution scale changes automatically even though I have it set to custom

### ISSUE THREAD

**Issue by abrahamhobandooo** [Ryujinx/Ryujinx#5794]
### Description of the issue

I have an issue where the resolution scale changes automatically even though I have it set to custom. Honestly, I think all games run perfectly fine at 1x on my Mac with M1. The problem is that during a game, it increases to 2x or even 4x, making it unplayable. I have to exit the game, go into settings, and change it back again. Is this normal? Is there a setting to keep it at 1x permanently for all games? It's very inconvenient, and that's why I haven't been able to play. I obviously click "apply" when I set the manual scale, but I have no idea why this keeps happening. Please help.

### Reproduction steps

I open the app, go to options on the menu bar, then settings, then graphics, and there I select the custom resolution scale option to 1x. I click "apply" at the bottom, then I open a game, and after a few minutes, in the bottom left corner, it says it changes to 4x

### Log file

no found

### OS

Mac OS 14

### Ryujinx version

1.1.10.50

### CPU

m1

### RAM

8

**Comment by gdkchan** [comment]
I think there is a hotkey to increase and decrease resolution scale, maybe you're accidentaly pressing it during gameplay.

**Comment by abrahamhobandooo** [comment]
> I think there is a hotkey to increase and decrease resolution scale, maybe you're accidentaly pressing it during gameplay.

I've already tested it, and I think that was what was happening. Thank you very much
