### ISSUE TITLE
[Bug] Ryujinx 1.1.1052 Crashing when launching a game on MacOS 12.6.6

### ISSUE THREAD

**Issue by bmatos15** [Ryujinx/Ryujinx#5812]
### Description of the issue

Hello, Im trying to play the game Pokémon Brilliant Diamond 1.3.0 with Ryujinx 1.1.1052 on my MacBook Air 2017  but the software keeps crashing. Checking the logs, it seems there's an exception with vulkan "VK_ERROR_FEATURE_NOT_PRESENT" but I'm new to this stuff, can someone please help me?

Vulkan Exception showing on log file:

00:00:03.014 |E| .NET ThreadPool Worker [mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: vkCreateDevice(): Requested feature is not available on this device.
00:00:03.021 |E| .NET ThreadPool Worker [mvk-info] Created VkDevice to run on GPU Intel(R) Iris(TM) Graphics 6000 with the following 7 Vulkan extensions enabled:
00:00:03.021 |E| .NET ThreadPool Worker 		VK_KHR_portability_subset v1
00:00:03.021 |E| .NET ThreadPool Worker 		VK_KHR_push_descriptor v2
00:00:03.021 |E| .NET ThreadPool Worker 		VK_KHR_shader_float16_int8 v1
00:00:03.021 |E| .NET ThreadPool Worker 		VK_KHR_swapchain v70
00:00:03.021 |E| .NET ThreadPool Worker 		VK_EXT_descriptor_indexing v2
00:00:03.021 |E| .NET ThreadPool Worker 		VK_EXT_fragment_shader_interlock v1
00:00:03.021 |E| .NET ThreadPool Worker 		VK_EXT_robustness2 v1
00:00:03.241 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorFeatureNotPresent".
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.CreateDevice(Vk api, VulkanPhysicalDevice physicalDevice, UInt32 queueFamilyIndex, UInt32 queueCount) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs:line 555
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 382
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 731
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 391
   at Ryujinx.Ava.AppHost.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 898
   at System.Threading.Thread.StartCallback()

### Reproduction steps

Installed Ryujinx 1.1.1052 from official website;
Added files prod.keys and title.keys v16.1.0 to the system folder inside Ryujinx folder;
Installed Firmware 16.1.0;
Settings: GPU is selected as Vulkan and "Ignore Missing Services" is toggled on (Settings-System-Hacks);
Added the update .nsp file to the .xci game file on Ryujinx
Click the game to launch

### Log file

[Ryujinx_1.1.1052_2023-10-17_00-17-34.log](https://github.com/Ryujinx/Ryujinx/files/12923987/Ryujinx_1.1.1052_2023-10-17_00-17-34.log)
[Ryujinx_1.1.1052_2023-10-17_00-26-22.log](https://github.com/Ryujinx/Ryujinx/files/12923988/Ryujinx_1.1.1052_2023-10-17_00-26-22.log)
[Ryujinx_1.1.1052_2023-10-17_00-27-16.log](https://github.com/Ryujinx/Ryujinx/files/12923989/Ryujinx_1.1.1052_2023-10-17_00-27-16.log)

### OS

MacOS 12.6.6 Monterey

### Ryujinx version

1.1.1052

### Game version

Pokémon Brilliant Diamond 1.3.0

### CPU

1,8 GHz Intel Core i5 Dual-Core

### GPU

Intel HD Graphics 6000 1536 MB

### RAM

8 GB 1600 MHz DDR3

**Comment by MetrosexualGarbodor** [comment]
You can't run Ryujinx on this hardware

**Comment by bmatos15** [comment]
> You can't run Ryujinx on this hardware
@MetrosexualGarbodor Thanks for the information. Can you tell me which part of the hardware is not enough for Ryujinx? I tried checking the system requirements on Ryujinx website but it wasn’t really clear about the minimal specifications needed for Mac devices.

**Comment by jcm93** [comment]
Your GPU (the Intel Graphics 6000) doesn't support features that the Vulkan renderer needs in order to initialize. It's not clear from the log exactly what features it's failing on, but it's a GPU/GPU driver issue.

Realistically, all Intel Macs are very limited in their ability to run Ryujinx due to graphics driver issues. You might have some success booting into Windows with your machine, but even if that passes initialization, I wouldn't expect things to work very well apart from perhaps simpler 2D titles.

**Comment by bmatos15** [comment]
> Your GPU (the Intel Graphics 6000) doesn't support features that the Vulkan renderer needs in order to initialize. It's not clear (to me) from the log exactly what features it's failing on, but it's a GPU/GPU driver issue.
> 
> Realistically, all Intel Macs are very limited in their ability to run Ryujinx due to graphics driver issues. You might have some success booting into Windows with your machine, but even if that passes initialization, I wouldn't expect things to work very well apart from perhaps simpler 2D titles.

@jcm93 Oh thank you so much for the explanation!
