### ISSUE TITLE
Joy-Con/Motion Control Support 

### ISSUE THREAD

**Issue by BetterWaifus** [Ryujinx/Ryujinx#582]
Currently there is no way to use Nintendo Switch Controllers or motion controls.

**Comment by Dudejoe870** [comment]
Joy-Con and motion control support are quite very different issues, perhaps it'd be best to split them up?

**Comment by BetterWaifus** [comment]
@Dudejoe870 Good Idea

**Comment by B3astTech** [comment]
Renaming the Issue to Motion Control Would be best since there are already other applications handling Joy-Con support like vjoy

**Comment by B3astTech** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/400

**Comment by EmulationFanatic** [comment]
This was closed with https://github.com/Ryujinx/Ryujinx/issues/1332
