### ISSUE TITLE
[Bug] Constant Crashes While Playing SMT3 Nocturne HD

### ISSUE THREAD

**Issue by gg-mariotti** [Ryujinx/Ryujinx#5824]
### Description of the issue

The emulator crashes constantly, more or less every 1 hour of gameplay. It's been having this issue for the last few versions (at least 3 or 4).

### Reproduction steps

There are no specific requirements to reproduce this issue other than playing for some time. Around 1 to 3 hours should be enough to see the crash.

### Log file

[Ryujinx_1.1.1057_2023-10-21_11-56-19.log](https://github.com/Ryujinx/Ryujinx/files/13060533/Ryujinx_1.1.1057_2023-10-21_11-56-19.log)

### OS

Windows 10 64bits

### Ryujinx version

1.1.1057

### Game version

1.0.3

### CPU

i9-7900X CPU @ 3.30GHz

### GPU

NVIDIA GeForce GTX 1080 Ti

### RAM

64GB

### Additional context?

I suspect that this crash is not specific to this game in particular.

**Comment by gg-mariotti** [comment]
Since at least version 1.1.1061 I don't see the frequent crashes anymore, so this problem seems to be solved.

**Comment by gdkchan** [comment]
I'm going to close this then, please re-open if the problem starts happening again. The log posted doesn't have any indication of the game crashing, it just appears that the emulator was stopped normally after 14 minutes from the log, so there is no clue about what caused the crash with the information provided so far.
