### ISSUE TITLE
[Bug] macOS - Application shortcut broken

### ISSUE THREAD

**Issue by nickoanastassiu** [Ryujinx/Ryujinx#5827]
### Description of the issue

The application shortcut that is generated is not working because the binary specified in the script is `Ryujinx.Ava` but the binary is actually called `Ryujinx`. Fixing this manually solves the issue.

A quick suggestion would also be to put the shortcuts in the Applications folder rather than on the Desktop.

### Reproduction steps

1. Create application shortcut
2. Try to open -> "crashes" on launch as the script cannot execute
3. Go to `Shortcut.app/Contents/MacOS/runner.sh` and fix binary name
4. Works as expected

### Log file

No logs necessary

### OS

macOS Sonoma 14.1 RC

### Ryujinx version

1.0.1059

**Comment by Bentheminernz** [comment]
I have found a fix!!! In the runner.sh file which is located in the macos folder of the application, it has a path for `/Applications/Ryujinx.app/Contents/MacOS/Ryujinx.ava`. When I set it to `/Applications/Ryujinx.app/Contents/MacOS/Ryujinx` it fixes itself.

**Comment by nickoanastassiu** [comment]
Yeah, that's exactly what I said.

> ... the binary specified in the script is `Ryujinx.Ava` but the binary is actually called `Ryujinx`. Fixing this manually solves the issue.

**Comment by Bentheminernz** [comment]
Oops, also it runs so much quicker if you copy and paste the runner.sh code into an automaton application for some reason

**Comment by NitroTears** [comment]
Alright, I'll work on this soon. I don't have a mac to test this on straight away, so I might need a hand in that later

**Comment by nickoanastassiu** [comment]
Feel free to DM me anytime.

**Comment by miche-egg564** [comment]
where do i edit the shortcut from

**Comment by nickoanastassiu** [comment]
Locate the shortcut on your desktop. Right click and choose `Show package contents`. Go to `Contents/MacOS/runner.sh` and open it with TextEdit. Locate `Ryujinx.Ava` in the file and remove the `.Ava`

**Comment by miche-egg564** [comment]
thanks
