### ISSUE TITLE
Ryujinx macOS cannot auto update

### ISSUE THREAD

**Issue by Therapist1911** [Ryujinx/Ryujinx#5829]
### Description of the issue

Everytime Ryujinx tries to download the update an error message will appear. The message will say to download the update manually and the currently installed Ryujinx app will not be able to be opened as it is corrupt.

### Reproduction steps

-click OK to auto update
-error message will occur
-app now corrupt 

### Log file

[Ryujinx_1.1.1057_2023-10-21_11-19-17.log](https://github.com/Ryujinx/Ryujinx/files/13061108/Ryujinx_1.1.1057_2023-10-21_11-19-17.log)

### OS

macOS ventura 13.5.2

### Ryujinx version

1.1.1057

### CPU

M1

### GPU

M1

### RAM

32G

### List of applied mods

none

### Additional context?

-

**Comment by MutantAura** [comment]
You must place the application into the macOS `Applications` folder.

**Comment by Therapist1911** [comment]
The application IS in the applications folder

**Comment by Therapist1911** [comment]
> You must place the application into the macOS `Applications` folder.

Very amatuerish to close this issue so fast. Like I wrote, Ryujinx is in the applications folder. It probably has to do with updating Ryujinx as a standard user maybe.
