### ISSUE TITLE
[Bug] "Create application shortcut" feature creates partially broken shortcuts on Windows

### ISSUE THREAD

**Issue by RobMcGee** [Ryujinx/Ryujinx#5839]
### Description of the issue

This feature creates a shortcut target command where the ryujinx binary filepath is duplicated, eg:
```
E:\Emulators\Ryujinx\Ryujinx.exe E:\Emulators\Ryujinx\Ryujinx.exe "E:\Emulators\Ryujinx\Games\CHRONO CROSS THE RADICAL DREAMERS EDITION.nsp"
```
[These surprisingly do work](https://miro.medium.com/v2/resize:fit:1274/1*ON_d7DWgW8g8uu3EBntfNw.png) when run from the desktop but don't work when parsed by other applications such as Nvidia Game Experience, which I use to play these games remotely on my TV via Moonlight.
Here's an example of a shortcut I created myself, which does work:
```
E:\Emulators\Ryujinx\Ryujinx.exe --fullscreen "E:\Emulators\Ryujinx\Games\CHRONO CROSS THE RADICAL DREAMERS EDITION.nsp"
```

Obviously the fullscreen option is an addition of my own but I'd argue that if someone wants to create a shortcut for a game, they probably want it to go right into fullscreen too, so that'd be a nice addition, but now we're bordering on feature request [so I'll leave that up to you...](https://media.tenor.com/xijGlpXoHYIAAAAC/winkwinknudgenudge-wink.gif)

Thanks for the emu, works great otherwise!

### Reproduction steps

This is fairly self-explanatory. Right-click on a game in the UI and create a game shortcut then view the target of the .lnk file.

### Log file

N/A.

### OS

W10

### Ryujinx version

v1.1.1061

### Game version

ALL

### CPU

N/A

### GPU

N/A

### RAM

N/A

### List of applied mods

None

**Comment by gdkchan** [comment]
@NitroTears Can you take a look at this issue?

**Comment by NitroTears** [comment]
Yeah sure, can have a look at this after work. For the `--fullscreen` addition. I will add that in, and then someone can yell at me if that's a no no.

**Comment by gdkchan** [comment]
Can you look at #5827 as well while you're at it?

**Comment by NitroTears** [comment]
I'll put this and #5827 in the same PR I think. Had stuff come up tonight so I'll just get to this when I can.

**Comment by RobMcGee** [comment]
Hey guys, I actually found another issue with these shortcuts but I don't know if you'll care..
Look like long filepaths for games don't get captured properly and caps out at 260 characters ([MAX_PATH](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)). 
I _can_ set the full path manually so it's fine, just FYI. 
Your initial fix to remove the dupe will partly help with this but not solve it completely.
