### ISSUE TITLE
[Bug] Crashing after calculating shader

### ISSUE THREAD

**Issue by YuryRegis** [Ryujinx/Ryujinx#5841]
### Description of the issue

After calculating shaders of the game "Hyrule Warriors: Age of Calamity [v1.3.0]", Ryujinx crashes.
The game worked normally in a previous version of Ryujinx.

This is the last screen before crash:
<div align="center">
<img width="1392" alt="Captura de Tela 2023-10-23 às 12 36 07" src="https://github.com/Ryujinx/Ryujinx/assets/29512626/7e19831f-34c0-4091-967f-54641ec73150">
</div>

### Reproduction steps

- Open Ryujinx v1.1.1061
- Select the game "Hyrule Warriors: Age of Calamity v1.3.0"
- Wait shaders compiling
- Wait for the game to start until the exact point shown in the issue description

### Log file

[Ryujinx_1.1.1061_2023-10-23_12-35-23.log](https://github.com/Ryujinx/Ryujinx/files/13073159/Ryujinx_1.1.1061_2023-10-23_12-35-23.log)

[log.txt](https://github.com/Ryujinx/Ryujinx/files/13073162/log.txt)

### OS

Sonoma 14.0 (23A344)

### Ryujinx version

v1.1.1061

### Game version

1.3.0

### CPU

Apple M1 Max

### GPU

Apple M1 Max (32 cores)

### RAM

32GB

### Additional context?

Working fine on Ryujinx version v1.1.1060

**Comment by TylerJaacks** [comment]
Do u have DLC installed?

**Comment by YuryRegis** [comment]
> Do u have DLC installed?

I believe the game update version 1.3.0 brings the "Guardian of Remembrance" DLC

**Comment by gdkchan** [comment]
Should be fixed on emulator version 1.1.1062. Please re-open if the issue still persists.
