### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by Simerjeetkaur8440** [Ryujinx/Ryujinx#5845]
[Ryujinx_1.1.1062_2023-10-24_15-16-12.log](https://github.com/Ryujinx/Ryujinx/files/13113360/Ryujinx_1.1.1062_2023-10-24_15-16-12.log)
### Description of the issue

Its showing "Error device lost" when playing most of the games

### Reproduction steps

No

### Log file

[Ryujinx_ 1.1.0-macos1_2023-10-24_14-06-45.log](https://github.com/Ryujinx/Ryujinx/files/13112634/Ryujinx_.1.1.0-macos1_2023-10-24_14-06-45.log)

Mac OS

Mac OS Sonoma

Ldn Ryujinx version

Ldn Latest Mac OS

### Game version

1.0.0

### CPU

Apple m2

### GPU

Integrated Moltenvk

### RAM

8gb

**Comment by AcK77** [comment]
Use our latest build instead of `macos1` one. Thanks.
