### ISSUE TITLE
[Bug]Shutdown issue with Super Mario Wonder

### ISSUE THREAD

**Issue by JudinScutin** [Ryujinx/Ryujinx#5847]
### Description of the issue

Unhandled exception caught

### Reproduction steps

start mario wonder rom and got shutdown before game starts

### Log file

[Ryujinx_1.1.965_2023-10-24_19-49-28.log](https://github.com/Ryujinx/Ryujinx/files/13128920/Ryujinx_1.1.965_2023-10-24_19-49-28.log)

### OS

Windows 10

### Ryujinx version

1.1.856

### Game version

1.0

**Comment by MetrosexualGarbodor** [comment]
The first thing you should do before asking for help or opening an issue is update the software you're using.

**Comment by AcK77** [comment]
Update Ryujinx to use our latest version.
