### ISSUE TITLE
Scissor Test breaks games that use multiple viewports

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#586]
The scissor testing introduced in 0cd5ba03fe4cccd232cdb6aa7e8648b4a08a0ab1 causes some games to display blank, or partially blank. It's believed this is due to issues with multiple viewports.

Sparkle 2 is known to be affected on Intel iGPU’s:

Without scissor test:
![Without Scissor Test](https://user-images.githubusercontent.com/1518948/52894552-6efce600-31ff-11e9-8ee7-53e1b25e74fe.png)

With scissor test:
![With Scissor Test](https://user-images.githubusercontent.com/1518948/52894551-6c01f580-31ff-11e9-87ca-701fbcc98caf.png)

Fixed by #595 

cc: @BaronKiko @gdkchan

**Comment by BaronKiko** [comment]
This can be closed
