### ISSUE TITLE
[Bug] Ryujinx starts with an error 0xc0000142

### ISSUE THREAD

**Issue by prallo** [Ryujinx/Ryujinx#5871]
### Description of the issue

App cannot start because error pops up.
Fresh install.

### Reproduction steps

Start app and doesn´t open, only produces an error.
I added an empty log file because there is no log file in the program folder.
Without log file I cannot post.

### Log file

No log and no log folder !

[log.txt](https://github.com/Ryujinx/Ryujinx/files/13223522/log.txt)

### OS

Windows 11

### Ryujinx version

1.1.1067 and 1.1.1068

### CPU

i9-13900KF

### GPU

NVIDIA 4080 RTX

### RAM

32 GB

### Additional context?

![Screenshot 2023-11-01 112840](https://github.com/Ryujinx/Ryujinx/assets/20041525/62d17dfc-9944-4b90-b1b7-b430688056d3)

**Comment by OldManKain** [comment]
Not enough information, also please join us in our [Discord](https://discord.gg/ryujinx) for general trouble shooting issues.
