### ISSUE TITLE
[Bug] Street of Rage | Does not start the second time

### ISSUE THREAD

**Issue by willianholtz** [Ryujinx/Ryujinx#5876]
### Description of the issue

When we start the game for the first time, the game runs 100%. However, if you close the game (by pressing ESC) and when trying to start again, the game tries to load and crashes, closing the emulator.

### Reproduction steps

Start the game normally, close it. Then try starting again!

### Log file

[StreetOfRages.txt](https://github.com/Ryujinx/Ryujinx/files/13231643/StreetOfRages.txt)

### OS

Arch Linux

### Ryujinx version

ryujinx-git r3084.841dd56f4-1

### CPU

Ryzen 7 5700x

### GPU

Nvidia RTX 2060

### RAM

64

**Comment by gdkchan** [comment]
Sounds like the same issue as #5874 which was just fixed. Can you try on latest version (if you are not building yourself you might need to wait a few minutes as the build is still in progress).

**Comment by willianholtz** [comment]
Tested with the latest build (#5875) and it's normal now!
