### ISSUE TITLE
[Bug] Some games disappearing after update 1.1.1060

### ISSUE THREAD

**Issue by gxyf106** [Ryujinx/Ryujinx#5880]
### Description of the issue

After updating, Mario kart disappears from UI. Error message from log is attached below. have played the missing game in the past without any issues for many hours.

### Reproduction steps

Update Ryujinx

### Log file

00:00:01.465 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: '/Users/xxx/Mario Kart 8 Deluxe [NSZ]/Mario Kart 8 Deluxe [0100152000022000][v0] (6.77 GB).nsp' Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.App.Common.ApplicationLibrary.ReadControlData(IFileSystem controlFs, Span`1 outProperty) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs:line 81
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs:line 87
00:00:01.595 |E| .NET ThreadPool Worker 2023-11-02 14:53:32.787 Ryujinx[12577:1153267] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### OS

MacOS 14.1

### Ryujinx version

1.1.1061

### CPU

M1 Pro

### GPU

M1 Pro

### RAM

16GB

### Additional context?

<img width="1512" alt="1 1 1065" src="https://github.com/Ryujinx/Ryujinx/assets/5485810/632e3436-b22b-4837-a73c-083ad5c28791">
<img width="1512" alt="1 1 1060" src="https://github.com/Ryujinx/Ryujinx/assets/5485810/947314ee-1f44-4df8-b32f-b9a28ca1cb9b">

**Comment by blza** [comment]
Same here Mario Kart is missing since some update, + Ultra Street Fighter II The Final Challengers [01007330027EE000][v0] is missing also

**Comment by glebmiller** [comment]
had to downgrade to 1.1.1059 to try Mario Kart, didn't see it in the library on 1.1.1070

**Comment by blza** [comment]
How to make the bug more prominent to the developers? It's been there from 1.1.1060 and now it's 1.1.1085.

**Comment by gxyf106** [comment]
Can you post it once again on the discord channel? i had already posted it there

**Comment by piplup55** [comment]
have you tried redumping the game?, you seem to be the only one with this issue

**Comment by blza** [comment]
> have you tried redumping the game?, you seem to be the only one with this issue

That fixes the problem, thanks!

**Comment by Shahil-Ayato** [comment]
Resolved. User issue.

**Comment by Shahil-Ayato** [comment]
Closed. User issue
