### ISSUE TITLE
[Bug]Super Mario 3D World + Bowser's Fury

### ISSUE THREAD

**Issue by Mario9699** [Ryujinx/Ryujinx#5881]
### Description of the issue

This game have flash back.

### Reproduction steps

![未命名](https://github.com/Ryujinx/Ryujinx/assets/103609670/cb35c366-896c-43b5-a943-09149e1c2245)

### Log file

[Ryujinx_1.1.1069_2023-11-04_23-10-55.log](https://github.com/Ryujinx/Ryujinx/files/13256995/Ryujinx_1.1.1069_2023-11-04_23-10-55.log)

### OS

Windows 10

### Ryujinx version

1.1.1069

### Game version

1.1.0

### CPU

i5-8400

### GPU

NVIDIA GeForce GTX 1050

### RAM

16GB

**Comment by DevilGeek** [comment]
I have the same crash. 

**Ryujinx version**
1.1.1069

**Game version**
1.1.0

**CPU**
i7-13700k

**GPU**
NVIDIA GeForce RTX 2070s

**RAM**
32GB

**Comment by MutantAura** [comment]
The above crash indicates running out of VRAM. 
Closing due to low report quality.
