### ISSUE TITLE
[Bug] Games wont run if I use LDN 3.1.3's exe.

### ISSUE THREAD

**Issue by wsoulless** [Ryujinx/Ryujinx#5886]
### Description of the issue

I've unpack the LDN 3.1.3 on top of the stable Ryujinx publish folder (overwriting files when ask).
The problem is that now if I run Ryujinx.exe and run any games I get this error and the program shut down right after (see attahced screenshot).
I also try to redo the standard folder and apply the Avalonia UI alternative (from here: https://github.com/Ryujinx/Ryujinx/wiki/Multiplayer-(LDN-Local-Wireless)-Guide) but it still trigger the same problem.

By the way, if I run Ryujinx.exe with no additional LDN on top, all games run smoothly.

Any help?

![Cattura](https://github.com/Ryujinx/Ryujinx/assets/65297299/7fa0448f-c27b-4ba5-a3d3-5be64f940c9e)
![Immagine 2023-11-02 180953](https://github.com/Ryujinx/Ryujinx/assets/65297299/193f7d66-7413-42e2-8956-4e7daa79ae73)

### Reproduction steps

Simply run any of the LDN exe's and run a game, the emulator crash during the loading of the game.

### Log file

00:00:00.044 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.049 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.049 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.050 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.051 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.052 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.053 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1B80
00:00:00.053 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.054 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.054 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.057 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.065 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.065 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.065 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.065 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.065 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.065 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.065 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.065 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.066 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.066 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.066 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.066 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.066 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.066 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.069 |I| Configuration LogValueChange: MultiplayerMode set to: LdnRyu
00:00:00.069 |I| Configuration LogValueChange: DisableP2p set to: False
00:00:00.074 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.0-ldn3.1.3
00:00:00.078 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.078 |N| Application Print: CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz ; 8 logical
00:00:00.079 |N| Application Print: RAM: Total 16317 MiB ; Available 9321 MiB
00:00:00.081 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.081 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.146 |I| Gpu : Backend Threading (Auto): True
00:00:00.516 |N| Application LoadGuestApplication: Using Firmware Version: 16.1.0
00:00:00.516 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.553 |I| ModLoader QueryContentsDir: Searching mods for Title 010090100E334000
00:00:00.554 |I| ModLoader QueryContentsDir: Searching mods for Title 010090100E334000
00:00:00.557 |I| Loader LoadExeFs: Loading rtld...
00:00:00.564 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.564 |I| Loader LoadExeFs: Loading main...
00:00:00.637 |I| Loader PrintRoSectionInfo: main:
    Module: C:\home\build\workspace\DST_Console_Package_Switch\bin\dontstarve.nss
    SDK Libraries: SDK MW+Nintendo+PiaCommon-5_45_0
                   SDK MW+Nintendo+Pia-5_45_0_69407
                   SDK MW+Nintendo+PiaLan-5_45_0
                   SDK MW+Nintendo+PiaSession-5_45_0
                   SDK MW+Nintendo+PiaTransport-5_45_0
                   SDK MW+Nintendo+PiaLocal-5_45_0
                   SDK MW+Nintendo+PiaFramework-5_45_0
                   SDK MW+Nintendo+PiaClone-5_45_0
                   SDK MW+Nintendo+PiaSync-5_45_0
                   SDK MW+Nintendo+PiaNex-5_45_0-forNEX-4_6_7
                   SDK MW+Nintendo+PiaReckoning-5_45_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-16_2_0-Release
                   SDK MW+Nintendo+NEX_MM-4_6_7
                   SDK MW+Nintendo+NEX-4_6_7-
                   SDK MW+Nintendo+NEX_VS-4_6_7
00:00:00.637 |I| Loader LoadExeFs: Loading sdk...
00:00:00.764 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 16.2.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-16_2_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-16_2_0-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-16_2_0-Release
00:00:00.998 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.065 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.067 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.317 |I| Loader LoadNsos: Loading image 2 at 0x00000000cbbac000...
00:00:02.328 |I| ModLoader LoadCheats: Build ids found for title 010090100E334000:
    2F1967113A281280A48CE3FC6DC23049327BF924000000000000000000000000
    3EB59F26B1D4B36A41DFEA3E29A524C692364B4E000000000000000000000000
    3053B22935E32DDF15EF81997603E5C267534A90000000000000000000000000
00:00:02.330 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.361 |I| Loader LoadNca: Application Loaded: Don't Starve Together v1.9.0 [010090100e334000] [64-bit]
00:00:02.413 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:02.834 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1080 (Vulkan v1.3.242, Driver v537.42.0.0)
00:00:02.842 |I| GPU.MainThread Gpu LoadShaders: Loading 12 shaders from the cache...
00:00:02.855 |W| GPU.MainThread Gpu LoadShaders: Error loading the shader cache. Length check failed, the cache file is corrupted.
00:00:02.860 |I| GPU.MainThread Gpu LoadShaders: Shader cache deleted due to corruption.
00:00:02.860 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:04.415 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:04.685 |S| HLE.OsThread.21 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:04.737 |S| HLE.OsThread.21 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:04.739 |S| HLE.OsThread.21 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:04.741 |S| HLE.OsThread.21 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:04.776 |S| HLE.OsThread.21 ServicePctl Initialize: Stubbed. 
00:00:05.053 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:05.054 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:05.070 |S| HLE.OsThread.21 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72215992670044160}
00:00:05.085 |S| HLE.OsThread.21 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:05.185 |S| HLE.OsThread.21 ServiceAm LockExit: Stubbed. 
00:00:05.231 |S| HLE.OsThread.21 ServiceNim CreateServerInterface: Stubbed. 
00:00:05.283 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:05.285 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 97 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconLeft, JoyconRight}
00:00:05.290 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 3 Players: Handheld,Player1,Player2
00:00:05.342 |S| HLE.OsThread.21 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:05.342 |S| HLE.OsThread.21 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:05.343 |S| HLE.OsThread.21 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:05.344 |S| HLE.OsThread.21 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.345 |S| HLE.OsThread.21 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: True}
00:00:05.346 |S| HLE.OsThread.21 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:05.897 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:05.958 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:06.039 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:06.064 |I| HLE.OsThread.21 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:06.066 |I| HLE.OsThread.21 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:06.182 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:06.227 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:06.367 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.368 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.369 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.371 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.371 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:06.372 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:06.373 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:06.378 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:06.416 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconLeft, JoyconRight' on 'Player1, Player2, Handheld'
00:00:06.843 |S| HLE.OsThread.21 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:06.894 |E| HLE.OsThread.4 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: ngc:u
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 112
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetServiceTipc(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 53
   at InvokeStub_IUserInterface.GetServiceTipc(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallTipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 176
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 301
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()

### OS

Win10

### Ryujinx version

ryujinx-1.1.1069-win_x64

### Game version

1.0.0

### CPU

i7-7700k

### GPU

NVIDIA RTX 1080

### RAM

16gb

### List of applied mods

None

**Comment by MetrosexualGarbodor** [comment]
Super Mario Bros. Wonder does **not** have LDN. It has single system multiplayer and some services that require Nintendo Switch Online. As we do not connect to NSO in any way, these cannot be used.
The game does not work on the LDN build as it is too old. Use [master.](https://ryujinx.org/download)
If you want to play this game on multiplayer, we suggest using Parsec.
