### ISSUE TITLE
[Bug] Fashion Dreamer

### ISSUE THREAD

**Issue by ptonino1** [Ryujinx/Ryujinx#5889]
### Description of the issue

Three issues found:
1. When inside Item Creator mode, groups of outfits show the same texture, but they should show what the item really looks like.  Tried many different combo of settings, same result.

2. When starting a new game, after walking around a bit you will see some models face show some wireframe, or whiteness, darkness, some clothes also become low resolution.

3. Low resolution clothes when walking around (may take 10-30 mins to present itself).

Thanks in advance.  Keep up the good work guys!

### Reproduction steps
Issue1:
1. Go in-game.
2. Progress until you unlock item creator (takes about 10 mins maybe)
4. Go to options - Item Creator (where you craft stuff)
5. View the icons in large or normal mode (any mode) the preview shows wrong clothing item preview, none should look identical.

Issue2:
1. Go in-game.
2. Walk around to some NPCs, after a few mins you should see some with weird faces.

Issue3:
1. Go in-game.
2. Walk around a lot and keep changing outfits, primarily printed dresses.

### Log file

[Ryujinx_1.1.1069_2023-11-03_13-13-15.log](https://github.com/Ryujinx/Ryujinx/files/13246202/Ryujinx_1.1.1069_2023-11-03_13-13-15.log)

### OS

Windows 11

### Ryujinx version

1.1.1069

### Game version

1.1.0

### CPU

Ryzen 5 3600

### GPU

Nvidia GTX 3070

### RAM

64GB

### List of applied mods

None

### Additional context?

(Issue1) Item Creator Mode - Example, Clothing items should all look different.  When you enter them to craft, it shows the right item, but when you go back to this screen it always show wrong items.
![image](https://github.com/Ryujinx/Ryujinx/assets/92829751/fd0554d6-7d8a-4a2b-80ac-20eb87a55362)

(Issue2) Walking around - weird faces sometimes.
![image](https://github.com/Ryujinx/Ryujinx/assets/92829751/6ee22674-1a56-4064-a0e5-9d55691effde)
![image](https://github.com/Ryujinx/Ryujinx/assets/92829751/92441232-7e6b-404b-9073-4934ca914383)

Expected (from issue2): Changing scenes, it refreshes to be good.
![image](https://github.com/Ryujinx/Ryujinx/assets/92829751/709fbe4a-8071-4afc-8471-9f358f257a0c)

(Issue3) Textures on clothes can go low-res sometimes.
![image](https://github.com/Ryujinx/Ryujinx/assets/92829751/d379d219-f4ac-455a-bda1-649ae702e08e)

**Comment by M1CR0H4CK3R** [comment]
This sounds related to my issue, #5908, as I get wireframing faces as well sometimes, and the face graphics look very similar to the ones in that game, possibly using the same modeling process and everything.

**Comment by gdkchan** [comment]
Can you check if #5927 fixes the issue?

**Comment by ptonino1** [comment]
Confirmed fixed, thanks.
