### ISSUE TITLE
Enter the game and flash back

### ISSUE THREAD

**Issue by pipiqi** [Ryujinx/Ryujinx#5897]
### Description of the issue

Enter the game and flash back: 13600kf+7900xt+win11 new computer, totk and other games choose to save to enter, and then get stuck, and then simulator flash back, unable to play the game.

### Reproduction steps

totk and other games choose to save to enter, and then get stuck, and then simulator flash back, unable to play the game.

### Log file

[Ryujinx_1.1.1070_2023-11-06_16-23-52.log](https://github.com/Ryujinx/Ryujinx/files/13264342/Ryujinx_1.1.1070_2023-11-06_16-23-52.log)

### OS

win11

### Ryujinx version

1.1.1070_

### Game version

1.2

### CPU

13600kf

### GPU

7900xt

### RAM

32gb

**Comment by pipiqi** [comment]
yuzu and other PC 3a games work fine on my computer.

**Comment by pipiqi** [comment]
已经解决：原因是我的存档文件来自老电脑的yuzu，yuzu的存档似乎和龙神有一点不兼容。Fixed: The reason is that my archive file is from yuzu on an old computer, and yuzu's archive seems to be a little incompatible with RYUJINX.

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx

**Comment by pipiqi** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！
