### ISSUE TITLE
[Bug] Detective Pikachu Returns - Reflection effects missing from reflective surfaces

### ISSUE THREAD

**Issue by RupeeClock** [Ryujinx/Ryujinx#5901]
### Description
In [Detective Pikachu Returns (010007500F27C000)](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4758), reflective surfaces such as glass windows, and a spherical ceiling lamp are lacking a reflective appearance.
When rendered correctly, the reflection effect is noticeable whilst moving around a scene.

### Configuration
Issue has been reproduced with combinations of the following configuration changes:

- Graphical backend: OpenGL, Vulkan
- Enable VSync: true
- Resolution Scale: Natives (720p/1080p), 3x (2160p/3240p)
- Memory Manager Mode: Host Unchecked
- Hack - Use alternative memory layout: false

### Video recordings
Original Switch hardware:
https://github.com/Ryujinx/Ryujinx/assets/24753760/63ad96ea-fbf3-4905-a09c-eb301b092f8b

Ryujinx 1.1.1071 (Vulkan):
https://github.com/Ryujinx/Ryujinx/assets/24753760/10f4b8f3-e6aa-4788-88f0-ea8f7892c0b5

### Reproduction steps

- Load from this provided save file: [Detective Pikachu Returns save file.zip](https://github.com/Ryujinx/Ryujinx/files/13273818/Detective.Pikachu.Returns.save.file.zip)
    - Alternatively, start a new game, and skip through dialogue until you gain control
 - Move around, and observe a lack of reflection in surfaces that should appear reflective

### Log file

[Ryujinx_1.1.1071_2023-11-06_23-31-15.log](https://github.com/Ryujinx/Ryujinx/files/13273826/Ryujinx_1.1.1071_2023-11-06_23-31-15.log)

### OS

Windows 10 Pro version 22H2 build 19045.3570

### Ryujinx version

1.1.1071

### Game version

1.0.0

### CPU

12th Gen Intel(R) Core(TM) i7-12700K 3.60 GHz

### GPU

NVIDIA RTX 3070

### RAM

32GB DDR5 (2x16gb)

### List of applied mods

n/a

### Additional context?

Issue was previously logged in some additional detail in a comment added to the Ryujinx Game Compatibility List entry, see https://github.com/Ryujinx/Ryujinx-Games-List/issues/4758#issuecomment-1751675280

**Comment by M1CR0H4CK3R** [comment]
I also had this issue when I played; it wasn't game-breaking, but it did slightly impact the immersion.
