### ISSUE TITLE
Snap

### ISSUE THREAD

**Issue by Master811129** [Ryujinx/Ryujinx#5902]
### Overview

Please Make a snap package for ryujinx, available in a snap store.

### Smaller details

```bash
mkdir snap
touch snap/snapcraft.yaml
vim snap/snapcraft.yaml
snapcraft --debug
```
:)

### Nature of request

Availability on Snap Store.

### Why would this feature be useful?

the app runs inside a container with all dependencies and isolated from the base distro. This will make the app more stable and easier to ship for multiple distributions. 

Plus It can be easier for people that already have snapd to install it this way.

Regards.

**Comment by marysaka** [comment]
Marking as invalid, see https://github.com/Ryujinx/Ryujinx/issues/2492#issuecomment-1445047053.

**Comment by Master811129** [comment]
Thanks for the reply. I really don't think it's about advantages or disadvantages but rather the **availability** of the software. 

Ubuntu and its flavors have a large portion of Linux users. By default Ubuntu ships snapd. Making the software available to these users can be useful.

Other than that, There are reasons that people might actually prefer snaps over flatpaks. for these users installing flatpak, and then install its runtimes and this software is not a pleasant and the most resource-efficient experience. 

It would be great if you support snaps as well. 


Thanks in advance
