### ISSUE TITLE
[Bug] Latest update causes some games to not function

### ISSUE THREAD

**Issue by Sephodious** [Ryujinx/Ryujinx#5916]
### Description of the issue

Most current update 1.1.1079 causes some games to not display in the emulator application window.

![image](https://github.com/Ryujinx/Ryujinx/assets/44609387/8bde90be-cc05-4c9b-a890-918db571bcdc)

Also causes games to not launch.

![image](https://github.com/Ryujinx/Ryujinx/assets/44609387/cabef149-ad32-4134-8d15-2d44b65f72a4)

I see no similarities between these games as some XCI seem to work while others don't. Updates, mods, or DLC don't seem to make a difference. 

### Reproduction steps

Add Games folder with a single subfolder for each game.
Launch game through Load Application from File.

### Log file

[Ryujinx_1.1.1079_2023-11-12_09-36-22.log](https://github.com/Ryujinx/Ryujinx/files/13328322/Ryujinx_1.1.1079_2023-11-12_09-36-22.log)

### OS

Windows 11

### Ryujinx version

1.1.1079

### Game version

196608

### CPU

AMD Ryzen 7 5800x

### GPU

Nvidia RTX 4070 Ti

### RAM

32GB

### List of applied mods

N/A

### Additional context?

Games load in the application window fine in 1.1.1078 and have tested to verify they all work on that version as well.

**Comment by gdkchan** [comment]
The root cause of those issues is #5638 (version 1.1.1076), version 1.1.1079 is just reverting that change.
