### ISSUE TITLE
MacBook Pro Os BigSur instantly crashing when running any game ( see crashlog )

### ISSUE THREAD

**Issue by clemensphilipps** [Ryujinx/Ryujinx#5918]
### Description of the issue

When i run a game i see for a second the loading bar and game image, then the app crashes. MacBook Pro, i7, Vulkan with Intel Iris Graphics

Model: MacBookPro11,2, BootROM 478.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,2 GHz, 16 GB, SMC 2.18f15
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 19 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

Thread 81 Crashed:
0   libsystem_kernel.dylib        	0x00007fff2065790e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff206865bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff205db406 abort + 125
3   org.ryujinx.Ryujinx           	0x000000010f83d8a2 PROCAbort + 50
4   org.ryujinx.Ryujinx           	0x000000010f83d7d0 PROCEndProcess(void*, unsigned int, int) + 320
5   org.ryujinx.Ryujinx           	0x000000010f3ed637 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 1127
6   org.ryujinx.Ryujinx           	0x000000010f3ed683 DispatchManagedException(PAL_SEHException&, bool) + 67
7   org.ryujinx.Ryujinx           	0x000000010f34a60b IL_Throw(Object*) + 555
8   ???                           	0x000000012c033d02 0 + 5033377026
9   ???                           	0x000000012c00b209 0 + 5033210377
10  ???                           	0x000000012c0099ee 0 + 5033204206
11  ???                           	0x000000012c00994c 0 + 5033204044
12  ???                           	0x000000012c008407 0 + 5033198599
13  ???                           	0x000000012867c9f7 0 + 4972857847
14  ???                           	0x000000012867c86d 0 + 4972857453
15  ???                           	0x000000012867c716 0 + 4972857110
16  org.ryujinx.Ryujinx           	0x000000010f48f809 CallDescrWorkerInternal + 124
17  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
18  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
19  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
20  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
21  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
22  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
23  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
24  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
25  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
511 org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223

Thread 81 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000700012e86000  rcx: 0x0000700012e833b8  rdx: 0x0000000000000000
  rdi: 0x000000000002a503  rsi: 0x0000000000000006  rbp: 0x0000700012e833e0  rsp: 0x0000700012e833b8
   r8: 0x000000000000f8a0   r9: 0xffffffff00000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x000000000002a503  r13: 0x0000700012e83aa0  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff2065790e  rfl: 0x0000000000000246  cr2: 0x0000700009c49ee0
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Thread 81 instruction stream not available.

Thread 81 last branch register state not available.

### Reproduction steps

When i run a game i see for a second the loading bar and game image, then the app crashes. MacBook Pro, i7, Vulkan with Intel Iris Graphics

### Log file

Model: MacBookPro11,2, BootROM 478.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,2 GHz, 16 GB, SMC 2.18f15
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 19 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

Thread 81 Crashed:
0   libsystem_kernel.dylib        	0x00007fff2065790e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff206865bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff205db406 abort + 125
3   org.ryujinx.Ryujinx           	0x000000010f83d8a2 PROCAbort + 50
4   org.ryujinx.Ryujinx           	0x000000010f83d7d0 PROCEndProcess(void*, unsigned int, int) + 320
5   org.ryujinx.Ryujinx           	0x000000010f3ed637 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 1127
6   org.ryujinx.Ryujinx           	0x000000010f3ed683 DispatchManagedException(PAL_SEHException&, bool) + 67
7   org.ryujinx.Ryujinx           	0x000000010f34a60b IL_Throw(Object*) + 555
8   ???                           	0x000000012c033d02 0 + 5033377026
9   ???                           	0x000000012c00b209 0 + 5033210377
10  ???                           	0x000000012c0099ee 0 + 5033204206
11  ???                           	0x000000012c00994c 0 + 5033204044
12  ???                           	0x000000012c008407 0 + 5033198599
13  ???                           	0x000000012867c9f7 0 + 4972857847
14  ???                           	0x000000012867c86d 0 + 4972857453
15  ???                           	0x000000012867c716 0 + 4972857110
16  org.ryujinx.Ryujinx           	0x000000010f48f809 CallDescrWorkerInternal + 124
17  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
18  org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223
511 org.ryujinx.Ryujinx           	0x000000010f2e09ff DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 223

Thread 81 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000700012e86000  rcx: 0x0000700012e833b8  rdx: 0x0000000000000000
  rdi: 0x000000000002a503  rsi: 0x0000000000000006  rbp: 0x0000700012e833e0  rsp: 0x0000700012e833b8
   r8: 0x000000000000f8a0   r9: 0xffffffff00000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x000000000002a503  r13: 0x0000700012e83aa0  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff2065790e  rfl: 0x0000000000000246  cr2: 0x0000700009c49ee0
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Thread 81 instruction stream not available.

Thread 81 last branch register state not available.

### OS

BigSur 11.7.10

### Ryujinx version

latest

### CPU

I7

### GPU

Intel Iris

### RAM

16GB

### List of applied mods

no mods

### Additional context?

nothing special really

**Comment by CribonGarge** [comment]
i have a similar issue. i hope they fix this. (if they can)

**Comment by ekuland** [comment]
Big Sur is not a supported OS

**Comment by gdkchan** [comment]
> Big Sur is not a supported OS

The website should be updated then, since it says "macOS 11 and later".

**Comment by shinra-electric** [comment]
Ryujinx should probably do a supported OS check at launch, giving a pop up window saying it’s unsupported with just a Quit button if it is definitely not going to work.

Just crashing is going to lead to people assume that it’s a bug, and they will open issues here.

**Comment by MutantAura** [comment]
App manifest and website are being updated to make this clearer. 
Please update to macOS 12 or beyond if possible.
