### ISSUE TITLE
[Bug] Games crashing on launch MacOS

### ISSUE THREAD

**Issue by CribonGarge** [Ryujinx/Ryujinx#5923]
### Description of the issue

Whenever i try to run a game on my mac it seems to crash every time, no matter what i do. (ive tried changing a few different settings) I am running a late 2014 Mac mini. Im worried my mac doesn't support Ryujinx, and my only other device is on Macos 10.13, which doesn't support Ryujinx to my knowledge. Other emulators such as dolphin and citra run fine for me, they use vulkan as well so i don't think it doesn't support my mac. Sorry for my bad english.

### Reproduction steps

I run the game on my mac.
Starts loading for a second.
Crashes. "Ryujinx Quit Unexpectedly"

### Log file

[Ryujinx_1.1.1072_2023-11-13_17-16-02.log](https://github.com/Ryujinx/Ryujinx/files/13343359/Ryujinx_1.1.1072_2023-11-13_17-16-02.log)
[Ryujinx_1.1.1072_2023-11-13_17-16-33.log](https://github.com/Ryujinx/Ryujinx/files/13343360/Ryujinx_1.1.1072_2023-11-13_17-16-33.log)
[Ryujinx_1.1.1072_2023-11-13_17-18-59.log](https://github.com/Ryujinx/Ryujinx/files/13343361/Ryujinx_1.1.1072_2023-11-13_17-18-59.log)

### OS

MacOS Monterey 12.6.1

### Ryujinx version

1.1.1072

### Game version

Not sure, happens on all games i have installed.

### CPU

2.6 GHz Dual-Core Intel Core i5

### GPU

Intel Iris 1536 MB

### RAM

8GB

**Comment by MetrosexualGarbodor** [comment]
Your system does not meet minimum requirements.
