### ISSUE TITLE
[Bug] Not able to update from Mac

### ISSUE THREAD

**Issue by m3kwong** [Ryujinx/Ryujinx#5934]
### Description of the issue

Auto update does not work on mac.  Error Message:

An error occurred during Ryujinx update (updater.sh:50)

Please download the update manually from our website if the problem persists.

### Reproduction steps

launch
tap yes to update
error pops up after download:
An error occurred during Ryujinx update (updater.sh:50)

Please download the update manually from our website if the problem persists.

### Log file

E| .NET ThreadPool Worker xattr: /var/folders/gn/n7w377550nzd9k82gg_pcnmc0000gn/T/Ryujinx/update/update.bin: No such xattr: com.apple.quarantine

### OS

Mac 14

### Ryujinx version

1.1.1081

**Comment by jcm93** [comment]
For Ryujinx to autoupdate properly, you need to move it after downloading, preferably to the Applications folder.

**Comment by m3kwong** [comment]
This auto update has never worked from the even first mac version.

**Comment by m3kwong** [comment]
Yes this works now after moving to Application folder. Thanks.
