### ISSUE TITLE
[Bug]No Sves

### ISSUE THREAD

**Issue by jinxenyou** [Ryujinx/Ryujinx#5944]
### Description of the issue

Why is RYUjinx not holding saves or updates? after I turn it off, restart all DLC updates, and save files are gone! This happens on PC and Steamdeck?????

### Reproduction steps

SAVE TURN OFF TURN OF GONE!

### Log file

no logs as this problem is all over redit

### OS

WIN DOWS 11 and Steam deck

### Ryujinx version

111089

### Game version

100 to 206 acnh

### CPU

i5 and steam deck

### GPU

nviea 4600

### RAM

30

### List of applied mods

0

### Additional context?

0

**Comment by glebmiller** [comment]
happened to me on Mac, lost my 100 hours on hades. problem was, application data was loaded to iCloud, I ran the game, I guess it created new saves and they overwritten mine or smth like that.

**Comment by jinxenyou** [comment]
INEXCUSABLE

**Comment by glebmiller** [comment]
still happens to me, start new hades save, do smth, quit, reopen - no save. no save in save folder also

**Comment by Shahil-Ayato** [comment]
Closing this, as there is absolutely nothing worthwhile here. 

All of the information requested has been either nonexistent or too vague to even begin to diagnose said issue. Either fill out these forums properly or don’t make one at all. We streamlined these issue forums to make it as easy as possible to help both the users and us to diagnose issues and fix them.

**Comment by Shahil-Ayato** [comment]
Issue closed.
