### ISSUE TITLE
Ryujinx Crashes When Switching Pokémon In Scarlet/Violet

### ISSUE THREAD

**Issue by RuinousPrincess** [Ryujinx/Ryujinx#5945]
### Description of the issue

For some reason since I updated Ryujinx to the latest version, it's crashing every time I try to switch Pokémon in battle and I can't figure out if it's the cheat codes or some weird error I saw in the log about some json file I don't see nor can find.

### Reproduction steps

Simply get into battle and try switching Pokémon, it'll instantly crash.

### Log file

[Ryujinx_1.1.1089_2023-11-17_02-42-51.log](https://github.com/Ryujinx/Ryujinx/files/13388957/Ryujinx_1.1.1089_2023-11-17_02-42-51.log)
[Ryujinx_1.1.1089_2023-11-17_02-46-11.log](https://github.com/Ryujinx/Ryujinx/files/13388958/Ryujinx_1.1.1089_2023-11-17_02-46-11.log)
[Ryujinx_1.1.1089_2023-11-17_02-55-32.log](https://github.com/Ryujinx/Ryujinx/files/13388959/Ryujinx_1.1.1089_2023-11-17_02-55-32.log)

### OS

Windows 10

### Ryujinx version

1.1.1089

### Game version

2.0.2

### CPU

i5-8400

### GPU

NVIDIA GeForce GTX 1060 6GB

### RAM

16GB

### List of applied mods

[C0D85FF5B8C86436.txt](https://github.com/Ryujinx/Ryujinx/files/13388999/C0D85FF5B8C86436.txt)

Assume Cheats are considered as mods.

**Comment by MetrosexualGarbodor** [comment]
All 3 of the logs you posted are empty. This sounds like either a mod issue or a bad game dump. Please join Discord for help instead of opening issues.
