### ISSUE TITLE
[Bug] Super Mario RPG: Incorrect lighting on some character and environment geometry

### ISSUE THREAD

**Issue by RupeeClock** [Ryujinx/Ryujinx#5946]
### Description of the issue

When playing [Super Mario RPG](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4811), some geometry appears improperly illuminated giving a dimmed and flat appearance.
This particularly affects player and NPC character models, and are highly noticeable on specific plants and bushes and MarioHouse on the Mario's Pad map.

These display issues occur regardless of graphical backend (OpenGL or Vulkan), and graphical enhancements such as resolution scale increases or enabling Macro HLE.

### Reproduction steps

Play through the game as normal, progressing through Bowser's Keep at the start of the game until you reach Mario's Pad where the issues become most notable. It is also noticeable on the Save screen and Map screen.
Lighting issues appear to vary from scene to scene and are not as noticeable during Bowser's Keep.

Switch hardware screenshots:
![2023111618342300-DD36EAD444102ED69B0AF6882696E2E7](https://github.com/Ryujinx/Ryujinx/assets/24753760/c4c89664-a673-48ab-9d98-18929264cf74)
![2023111618344300-DD36EAD444102ED69B0AF6882696E2E7](https://github.com/Ryujinx/Ryujinx/assets/24753760/d8125a65-ce0b-4e91-87c7-b81a7ca88ae3)
![2023111618351000-DD36EAD444102ED69B0AF6882696E2E7](https://github.com/Ryujinx/Ryujinx/assets/24753760/ee47398f-4758-49e5-81ab-98722c9617e2)
![2023111618353100-DD36EAD444102ED69B0AF6882696E2E7](https://github.com/Ryujinx/Ryujinx/assets/24753760/1b22d111-8da4-4235-9807-72edd362fc9f)
![2023111609544200-DD36EAD444102ED69B0AF6882696E2E7](https://github.com/Ryujinx/Ryujinx/assets/24753760/77963e12-a3e0-476f-ad95-6f99157ba70c)
![2023111609545000-DD36EAD444102ED69B0AF6882696E2E7](https://github.com/Ryujinx/Ryujinx/assets/24753760/1771a7ee-f7be-441b-808e-01059fec0bfd)

Ryujinx v1.1.1087 screenshots:
![Screenshot (82)](https://github.com/Ryujinx/Ryujinx/assets/24753760/9b07e6b7-4978-449c-8b52-66b55b1a483d)
![Screenshot (84)](https://github.com/Ryujinx/Ryujinx/assets/24753760/62f159dc-5a83-4e00-a85d-ec2964381caf)
![Screenshot (83)](https://github.com/Ryujinx/Ryujinx/assets/24753760/ace12c22-05ae-4d39-b696-d59d0f696271)
![Screenshot (85)](https://github.com/Ryujinx/Ryujinx/assets/24753760/ca5b3798-eb28-4c94-8293-b8c64bdbad71)
![Screenshot (74)](https://github.com/Ryujinx/Ryujinx/assets/24753760/c52cfd07-8355-4ecd-af4b-1da658181a32)
![Screenshot (75)](https://github.com/Ryujinx/Ryujinx/assets/24753760/3099dacd-45d2-4ef1-b057-5d5100075f82)

This provided save file will skip past the intro, starting at Mario's Pad: 
[SMRPG Save.zip](https://github.com/Ryujinx/Ryujinx/files/13390302/SMRPG.Save.zip)

### Log file

[Ryujinx_1.1.1087_2023-11-16_18-21-31.log](https://github.com/Ryujinx/Ryujinx/files/13390304/Ryujinx_1.1.1087_2023-11-16_18-21-31.log)

### OS

Windows 10 Pro version 22H2 build 19045.3570

### Ryujinx version

1.1.1087

### Game version

1.0.0

### CPU

12th Gen Intel(R) Core(TM) i7-12700K 3.60 GHz

### GPU

NVIDIA RTX 3070

### RAM

32GB DDR5 (2x16gb)

### List of applied mods

n/a

### Additional context?

For transparency, screenshots and logs were captured on 16/11/2023 a day ahead of the official release date.
These were captured using a personal dump of a physical UK copy that was delivered a day early.

**Comment by mikahjc** [comment]
Don't want to turn this into a "me too" issue, but I am also seeing this lighting issue, most prominently against the hills in Bandit's Way as shown.

Switch hardware screenshot:
![2023111721072100_c](https://github.com/Ryujinx/Ryujinx/assets/1157067/392d6dc1-deda-47e0-bae9-da225a3d75fa)

Ryujinx screenshot:
![ryujinx_capture_2023-11-17_21-15-49](https://github.com/Ryujinx/Ryujinx/assets/1157067/5e6c3eb6-ecc5-4ae3-9785-21d7470dd850)

Game save:
[SMRPG_Bandit's Way.zip](https://github.com/Ryujinx/Ryujinx/files/13398821/SMRPG_Bandit.s.Way.zip)

### Log File
[Ryujinx_1.1.1089_2023-11-17_21-05-52.log](https://github.com/Ryujinx/Ryujinx/files/13398810/Ryujinx_1.1.1089_2023-11-17_21-05-52.log)

### OS
Windows 11 Pro for Workstations 22H2 build 22621.2428

### Ryujinx version
1.1.1089

### Game version
1.0.0

### CPU
AMD Ryzen 9 5900X 12-Core Processor, 3.7 GHz

### GPU
AMD Radeon RX 7800 XT

### RAM
32GB DDR4

### List of applied mods
n/a

**Comment by RupeeClock** [comment]
This rendering issue with Bandit's Way is consistent with my machine.
![bandit's way](https://github.com/Ryujinx/Ryujinx/assets/24753760/02b109c7-0566-47e5-b5ba-52c1154f1700)

This rules out that the issue is not specific to the version of Windows used (10 or 11), and not specific to any CPU or GPU vendor (Intel or AMD, Nvidia or AMD)

**Comment by Romsstar** [comment]
Tested with #3001 and it seems to fix the lighting issues for me on a RTX 4070.

**Comment by GamerzHell9137** [comment]
> Tested with #3001 and it seems to fix the lighting issues for me on a RTX 4070.

Screenshot? Because it doesn't look like for me.
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/a2c30e6c-eabb-4783-ae48-3328e3746a05)

**Comment by Romsstar** [comment]
> > Tested with #3001 and it seems to fix the lighting issues for me on a RTX 4070.
> 
> Screenshot? Because it doesn't look like for me. ![image](https://user-images.githubusercontent.com/2002038/283999010-a2c30e6c-eabb-4783-ae48-3328e3746a05.png)

I seem to have been mistaken. I was sure it fixed things but apparently I was wrong. Sorry :/
