### ISSUE TITLE
[Bug] The King Of Fighters XIII: Global Match

### ISSUE THREAD

**Issue by antoniodesousa** [Ryujinx/Ryujinx#5953]
### Description of the issue

The game crashes immediately after the dialog "Creating new Save Data" appears onscreen.

### Reproduction steps

Just start the game and the dialog will appear right away.

### Log file

[Ryujinx_1.1.1089_2023-11-18_20-15-26.log](https://github.com/Ryujinx/Ryujinx/files/13401313/Ryujinx_1.1.1089_2023-11-18_20-15-26.log)

### OS

Windows 11 23H2

### Ryujinx version

1.1.1089

### Game version

1.0.1

### CPU

Ryzen 9 6900HX

### GPU

Radeon RX 6600M

### RAM

64GB

### List of applied mods

None

**Comment by gdkchan** [comment]
Can't reproduce it here.
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/2b80f647-d060-4568-85e8-38ddbbd69016)
I would try clearing PPTC and shader caches, and deleting any existing save data for this game.

**Comment by antoniodesousa** [comment]
I tried deleting the PPTC and shaders caches (no save data was created) but it didn't fix the problem. I did noticed something very strange, the issue only happens on my 2 external SSD. When I move the Ryujinx installation to my internal 980 PRO PCle 4.0 NVMe M.2 SSD, it creates the save data without issues. I'm clueless about why it crashes on my 2 external SSD. This is the only game that this happens. 🤷

**Comment by antoniodesousa** [comment]
The game still crashes shortly after booting up on the latest release as of today 1.1.1141
Only happens when I run Ryujinx from my external SSD (any external storage actually). Running it from C: works fine
[Ryujinx_1.1.1141_2024-01-28_17-42-59.log](https://github.com/Ryujinx/Ryujinx/files/14076919/Ryujinx_1.1.1141_2024-01-28_17-42-59.log)
