### ISSUE TITLE
[Bug] PERSONA 5 Tactica Bug that crashes every certain time

### ISSUE THREAD

**Issue by rkdrlgh22** [Ryujinx/Ryujinx#5956]
### Description of the issue

Bug that crashes every certain time

List of files used

GAME FILE
Persona 5 Tactica [010090901941E000][v0][US].nsp

UPDATE
Persona 5 Tactica[010090901941E800][1.0.2][131072][17.0.0].nsp

DLC LIST
Persona 5 Tactica[010090901941F001][0][1.0.0][DLC].nsp
Persona 5 Tactica[010090901941F002][0][1.0.0][DLC].nsp
Persona 5 Tactica[010090901941F003][0][1.0.0][DLC].nsp
Persona 5 Tactica[010090901941F005][0][1.0.0][DLC].nsp

### Reproduction steps

[Ryujinx_1.1.1090_2023-11-19_06-51-22.log](https://github.com/Ryujinx/Ryujinx/files/13401595/Ryujinx_1.1.1090_2023-11-19_06-51-22.log)
[Ryujinx_1.1.1090_2023-11-19_07-13-19.log](https://github.com/Ryujinx/Ryujinx/files/13401596/Ryujinx_1.1.1090_2023-11-19_07-13-19.log)
[Ryujinx_1.1.1090_2023-11-19_06-34-11.log](https://github.com/Ryujinx/Ryujinx/files/13401597/Ryujinx_1.1.1090_2023-11-19_06-34-11.log)

1. If you play in Marier's Boss for a long time, the game stops and you don't save the log.
2. Besides, if you play for a long time, the game stops and you don't save the log.

### Log file

[Ryujinx_1.1.1090_2023-11-19_06-34-11.log](https://github.com/Ryujinx/Ryujinx/files/13401581/Ryujinx_1.1.1090_2023-11-19_06-34-11.log)
[Ryujinx_1.1.1090_2023-11-19_06-51-22.log](https://github.com/Ryujinx/Ryujinx/files/13401582/Ryujinx_1.1.1090_2023-11-19_06-51-22.log)
[Ryujinx_1.1.1090_2023-11-19_06-51-22.log](https://github.com/Ryujinx/Ryujinx/files/13401583/Ryujinx_1.1.1090_2023-11-19_06-51-22.log)

### OS

windows11 22H2 pro insider preview

### Ryujinx version

1.1.1090

### Game version

1.0.2

### CPU

AMD RYZEN 5 3600 6-core processor

### GPU

NVDIA GEFORCE RTX 2060

### RAM

16GB

### List of applied mods

NP

### Additional context?

Please fix it as soon as possible.

**Comment by pubct** [comment]
Sounds like the same as #5520 that I previously reported.

The newest log if dev is interested.
[Ryujinx_1.1.1090_2023-11-19_22-36-13.zip](https://github.com/Ryujinx/Ryujinx/files/13404295/Ryujinx_1.1.1090_2023-11-19_22-36-13.zip)

**Comment by StevensND** [comment]
I have also had this issue.

**Comment by Neputin** [comment]
Yeah I have the same issue

**Comment by SzymonJaroslawski** [comment]
(Windows 11 23H2, Ryzen 7 2700X, GTX 1650, Vulkan)

`00:00:02.848 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1650 (Vulkan v1.3.260, Driver v546.17.0.0)`

```
00:24:25.100 |E| Ryujinx.NvdecProcessor Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000100
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 139
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 347
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 206
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 112
   at Ryujinx.Graphics.Nvdec.Image.SurfaceReader.Read(MemoryManager gmm, ISurface surface, UInt32 lumaOffset, UInt32 chromaOffset) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Image\SurfaceReader.cs:line 28
   at Ryujinx.Graphics.Nvdec.Image.SurfaceCache.Get(IDecoder decoder, UInt32 lumaOffset, UInt32 chromaOffset, Int32 width, Int32 height) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Image\SurfaceCache.cs:line 80
   at Ryujinx.Graphics.Nvdec.Vp9Decoder.Decode(ResourceManager rm, NvdecRegisters& state) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Vp9Decoder.cs:line 31
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(ApplicationId applicationId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\NvdecDevice.cs:line 75
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\AsyncWorkQueue.cs:line 39
```

**Comment by B1akeIT** [comment]
I have the same issue: since I started playing the game, ~30 minutes after starting Ryujinx, it crashes. Now that I'm playing a fairly long mission, I can't finish it in time.

Version: 1.1.1100
Windows 11 pro 22H2, Intel i7 8th gen, RTX 2060, 24 GB 3200mhz RAM (command prompt, when I launched Ryujinx, displayed ~15.2 GiB available).

I've tried both Vulkan and OpenGL, docked and handheld, shader cache enabled and disabled, texture compression enabled and disabled, VSync enabled and disabled, but still nothing.
Let me know if I can help running some tests, but I'm currently kind of stuck here.

**Comment by Veriamo** [comment]
It also crashes for me every time without fail. Once this problem happens, the game stutters, and then immediately crashes. The time at which it happens seems to be random. I've played as much as 43 minutes without crashing and closed the emulator manually, but right now it crashed at 14 minutes mark. Usually it's around 25-30 minutes, though.

Version: 1.1.1102
Windows 10 Pro, Intel Core i5-3570K (3rd gen), GTX 1050 ti, 8 GB RAM

The game usually runs fine, with only minor slowdowns, and I can get past the places where it crashed by simply replaying the level. The bug doesn't happen even if I do the exact same sequence of moves, but the game crashes anyway later on.

> 00:14:14.043 |E| Ryujinx.NvdecProcessor Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000100

[Ryujinx_1.1.1102_2023-12-30_22-37-06.log](https://github.com/Ryujinx/Ryujinx/files/13799354/Ryujinx_1.1.1102_2023-12-30_22-37-06.log)
[Ryujinx_1.1.1102_2023-12-31_01-08-29.log](https://github.com/Ryujinx/Ryujinx/files/13799347/Ryujinx_1.1.1102_2023-12-31_01-08-29.log)

**Comment by Ishidad** [comment]
I keep having the same issue, sometimes randomly, at the moment is always at the same spot (reaching turn 4 in the same mission) might be time bases

Version: 1.1.102
Windows 11 os build 22621.2861, AMD Ryzen 7 5800X3D, 7800XT, 16GB Ram

[Ryujinx_1.1.1102_2023-12-31_10-43-25.log](https://github.com/Ryujinx/Ryujinx/files/13800913/Ryujinx_1.1.1102_2023-12-31_10-43-25.log)

**Comment by deeandra** [comment]
No fix yet? Im having the same issue....

**Comment by Kageliencharles** [comment]
Version: 1.1.112
Processor	AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
Installed RAM	16.0 GB (15.8 GB usable)

PERSONA 5 Tactica crashes in 30 mins of doing a mission but not a cutscenes or menu i experience 

Here My Error Log

00:19:12.974 |D| HLE.TamperMachine TamperMachine Set: R_00: 0
00:19:12.974 |D| HLE.TamperMachine TamperMachine Set: 0x000000000C22E940@4: 5284E1E8
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 513 (bound to GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 575 (bound to GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.001 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
00:19:13.002 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
00:19:13.005 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
00:19:13.007 |E| Ryujinx.NvdecProcessor Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000100
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 474
   at Ryujinx.Cpu.Jit.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 293
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 213
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 119
   at Ryujinx.Graphics.Nvdec.Image.SurfaceReader.Read(MemoryManager gmm, ISurface surface, UInt32 lumaOffset, UInt32 chromaOffset) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Image\SurfaceReader.cs:line 28
   at Ryujinx.Graphics.Nvdec.Image.SurfaceCache.Get(IDecoder decoder, UInt32 lumaOffset, UInt32 chromaOffset, Int32 width, Int32 height) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Image\SurfaceCache.cs:line 103
   at Ryujinx.Graphics.Nvdec.Vp9Decoder.Decode(ResourceManager rm, NvdecRegisters& state) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Vp9Decoder.cs:line 31
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(ApplicationId applicationId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\NvdecDevice.cs:line 75
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\AsyncWorkQueue.cs:line 39
00:19:13.034 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
00:19:13.034 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
00:19:13.034 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 529 (bound to GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.034 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 529 (bound to GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.036 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 575 (bound to GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.036 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.036 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityNotification: Buffer detailed info: Buffer object 421 (bound to GL_UNIFORM_BUFFER (8), and GL_COPY_READ_BUFFER_BINDING_EXT, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations.
00:19:13.036 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
00:19:13.036 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
00:19:13.037 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
00:19:13.041 |D| GUI.RenderLoop Gpu GLDEBUG: DebugTypeOther DebugSeverityLow: Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but there is no stencil buffer. Operation will have no effect.
