### ISSUE TITLE
[Bug] Hyrule Warriors: Age of Calamity; Game crashes when using version 1.3, works fine with 1.0.1

### ISSUE THREAD

**Issue by UnendingMoo** [Ryujinx/Ryujinx#5961]
### Description of the issue

I'm trying to play Hyrule Warriors: Age of Calamity:
Playing version 1.0.1 works just fine, even with all 3 DLC's available enabled, but if I try to update to version 1.3 it crashes Ryujinx, and either crashes Yuzu, or gets stuck in an infinite load. I have tried several different downloads of the update on all versions with the same result (with or without dlc's).
Using newest keys (17.0.0), and the version before that.
Tried on Ryujinx 1.1.1090, Yuzu 1451 (Regular, and EA) .
Couldn't find anyone with a solution on Reddit, Github, or anywhere else google took me

### Reproduction steps

Boot Hyrule Warriors: AoC version 1.3

### Log file

[Ryujinx_1.1.1090_2023-11-19_12-55-33.log](https://github.com/Ryujinx/Ryujinx/files/13404599/Ryujinx_1.1.1090_2023-11-19_12-55-33.log)

### OS

WIN 11 

### Ryujinx version

1.1.1090

### Game version

1.3

### CPU

Intel  i7-13700k

### GPU

NVIDIA GTX 4090

### RAM

32GB DDR5

### Additional context?

Log attached is me starting the game (with all 3 DLC activated) on version 1.0.1, stopping emulation after successful load, and then applying the update to version 1.3 and trying to start the game again leading to a crash

**Comment by gdkchan** [comment]
The log indicates that the ROM file is corrupted (I guess it is likely the update, since you said that an older version works without issue).

**Comment by UnendingMoo** [comment]
> The log indicates that the ROM file is corrupted (I guess it is likely the update, since you said that an older version works without issue).

[Update File 1.log](https://github.com/Ryujinx/Ryujinx/files/13404633/Update.File.1.log)
[Update File 2.log](https://github.com/Ryujinx/Ryujinx/files/13404634/Update.File.2.log)
[Update File 3.log](https://github.com/Ryujinx/Ryujinx/files/13404635/Update.File.3.log)
I tried 3 different update files from 2 different sources, and these are the results (always crashed
