### ISSUE TITLE
Super Mario RPG crashes

### ISSUE THREAD

**Issue by CorpseSlayer** [Ryujinx/Ryujinx#5971]
### Description of the issue

Super Mario RPG is crashing on the part where you follow GENO into the forest , Ryujinx starts acting up with music slowing down and it crashes, is right in this moment when crash happens.
![image_2023-11-21_175744398](https://github.com/Ryujinx/Ryujinx/assets/126618918/f070cba5-7950-4680-a7aa-750d5b3fc72f)

### Reproduction steps

just follow Geno throw the forest  at the point mention above Ryujinx will crash.
![image_2023-11-21_180339923](https://github.com/Ryujinx/Ryujinx/assets/126618918/20bdd744-c1ec-42a0-a829-7c37d56b21ee)

Save:
[SMRPGS.zip](https://github.com/Ryujinx/Ryujinx/files/13431420/SMRPGS.zip)

### Log file

[Ryujinx_1.1.1092_2023-11-21_17-52-12.log](https://github.com/Ryujinx/Ryujinx/files/13431440/Ryujinx_1.1.1092_2023-11-21_17-52-12.log)
[Ryujinx_1.1.1092_2023-11-21_17-53-34.log](https://github.com/Ryujinx/Ryujinx/files/13431441/Ryujinx_1.1.1092_2023-11-21_17-53-34.log)
[Ryujinx_1.1.1092_2023-11-21_18-00-21.log](https://github.com/Ryujinx/Ryujinx/files/13431442/Ryujinx_1.1.1092_2023-11-21_18-00-21.log)

### OS

Windows 11

### Ryujinx version

Ryujinx 1.1.1092

### Game version

V 1.0.0

### CPU

I7 9700K

### GPU

Mvidia RTX 2060

### RAM

16gb

### List of applied mods

None

**Comment by OldManKain** [comment]
Bad game dump, Re-dump your game.
```LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!```

**Comment by CorpseSlayer** [comment]
> Bad game dump, Re-dump your game. `LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

I did re-dump like you said and this time i had to restart the game from the very beginning but still Ryujinx crash in the main intro.

**Comment by CorpseSlayer** [comment]
> Bad game dump, Re-dump your game. `LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

you need to re-check!
