### ISSUE TITLE
Ryujinx crashes when playing Link's Awakening

### ISSUE THREAD

**Issue by Chapadin** [Ryujinx/Ryujinx#5972]
### Description of the issue

The game suddenly crashes after a while of playing, these crashes occur completely randomly and close the emulator together. (Even causing a bug on my graphics PC, but this is resolved when I restart).

### Reproduction steps

As previously stated, the bug occurs randomly during gameplay, it has nothing to do with the areas or the game. Because I can run it with an acceptable framerate for my PC (30 - 50 fps, regardless of vsync being on or off)

### Log file

[Ryujinx_1.1.1092_2023-11-21_13-56-31.log](https://github.com/Ryujinx/Ryujinx/files/13432516/Ryujinx_1.1.1092_2023-11-21_13-56-31.log)
(These are the most recent files)

### OS

Windows 11

### Ryujinx version

1.1.1092

### Game version

1.0.0

### CPU

Intel Core i3 1115G4

### GPU

Intel UHD Graphics for 11th Gen Intel Processors

### RAM

8GBs

### List of applied mods

Just a translation mod for my language

**Comment by OldManKain** [comment]
This is a TDR due to you running out of (RAM)/VRAM since you are using an iGPU the ram is shared between the CPU and GPU.
Also you only had 1 GiB of Ram available when you started the game.  
The recommend requirements having 8 GB of ram available on launch.

```00:00:00.160 |N| Application Print: RAM: Total 7.7 GiB ; Available 1 GiB```

```00:22:47.056 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".```
