### ISSUE TITLE
[Bug] Citizens of Space and Citizens Unite Earth x Space only show half a screen

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#5974]
### Description of the issue

during gameplay only half a screen is shown 

### Reproduction steps

start the game 

### Log file

![ryujinx_capture_2023-11-22_16-05-39](https://github.com/Ryujinx/Ryujinx/assets/139027919/96a590fd-9b69-43ef-9d5b-762e58686a68)
![ryujinx_capture_2023-11-22_16-07-27](https://github.com/Ryujinx/Ryujinx/assets/139027919/2640af13-4e4f-492c-80fd-cd2ae55b160c)

### OS

Windows 10

### Ryujinx version

1.11092

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by ScottNash042** [comment]
still an issue in 1.1.1098

**Comment by ScottNash042** [comment]
@gdkchan 
would a RenderDoc help ??

**Comment by RabidLabMonkey** [comment]
As of 1.1.1102 Citizens of Earth is drawing properly but the issue still remains on Citizens of Space.

Citizens of Earth
![NewCanvas25](https://github.com/Ryujinx/Ryujinx/assets/77931508/778576d0-cd7f-4cf6-99f9-1278fdbbe0be)

Citizens of Space
![NewCanvas26](https://github.com/Ryujinx/Ryujinx/assets/77931508/0a6e9d1a-4694-427d-b8f1-6e5f256b1e0c)

**Comment by ScottNash042** [comment]
fixed
can be closed
