### ISSUE TITLE
[Bug]Super Mario RPG

### ISSUE THREAD

**Issue by Mario9699** [Ryujinx/Ryujinx#5975]
### Description of the issue

This game sound have distortion

### Reproduction steps

This game sound have distortion

### Log file

[Ryujinx_1.1.1092_2023-11-22_20-09-31.log](https://github.com/Ryujinx/Ryujinx/files/13439189/Ryujinx_1.1.1092_2023-11-22_20-09-31.log)

### OS

Windows 10

### Ryujinx version

1.1.1092

### Game version

1.0.0

### CPU

i5-8400

### GPU

NVIDIA GeForce GTX 1050

### RAM

16GB

**Comment by OldManKain** [comment]
Known issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/4811#issuecomment-1820014868
Please report game specific bugs on the games list.
