### ISSUE TITLE
Link's Awakening crashes and closes the emulator when I pick up the fishing hook.

### ISSUE THREAD

**Issue by Chapadin** [Ryujinx/Ryujinx#5981]
### Description of the issue

Upon reaching a certain percentage in the game, Link can interact with an NPC in the animal village. Interacting, Link exchanges a broom for a fishing hook. In this part, the emulator crashes and closes.

### Reproduction steps

In the part where I go to the animal village and talk to the NPC who exchanges the broom for the fishing hook, the game simply freezes suddenly.
![ryujinx_capture_2023-11-25_09-26-08](https://github.com/Ryujinx/Ryujinx/assets/147850373/59b53881-df27-4672-9153-7027d53f0f45)

### Log file

[Ryujinx_1.1.1093_2023-11-25_09-24-45.log](https://github.com/Ryujinx/Ryujinx/files/13464142/Ryujinx_1.1.1093_2023-11-25_09-24-45.log)

### OS

Windows 11

### Ryujinx version

1.1.1093

### Game version

1.0.0

### CPU

Intel Core i3 1115G4

### GPU

Intel UHD Graphics for 11th Gen Intel Processors

### RAM

8GBs

**Comment by MutantAura** [comment]
Does it happen without the mods.
In future, fill out this form correctly by stating mods are being used the `List of applied mods` section. It would save us all a lot of time.

**Comment by Chapadin** [comment]
Thanks man. The problem was being caused by the mod. Although I ended up not caring too much since it's a translation mod.
