### ISSUE TITLE
Ryujinx crashing TOTK [Bug]

### ISSUE THREAD

**Issue by remainders3** [Ryujinx/Ryujinx#5983]
### Description of the issue

Whenever I get close to the first shrine on the main island in the start of TOTK my game just crashes and I can't figure out why so I'm coming to more people for help. Any Ideas?

### Reproduction steps

- Get within a small distance of the first shrine
- Ryujinx just closes

### Log file

[Ryujinx_1.1.1093_2023-11-25_14-22-08.log](https://github.com/Ryujinx/Ryujinx/files/13465170/Ryujinx_1.1.1093_2023-11-25_14-22-08.log)

### OS

Windows 10

### Ryujinx version

1.1.1093

### Game version

1.2.1

### CPU

i7-12700KF

### GPU

NVIDIA RTX 3080

### RAM

16GB

### List of applied mods

None

**Comment by MetrosexualGarbodor** [comment]
The log you posted is empty, but it sounds like a bad game dump, so try dumping it again from your Switch. In the future, please join Discord for help instead of opening an issue.

**Comment by remainders3** [comment]
I'm sorry

**Comment by Amariithynar** [comment]
> I'm sorry. What's the discord?

https://discord.com/invite/VkQYXAZ
