### ISSUE TITLE
[Bug] NSO Nintendo 64 Crash to Desktop - E| Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped:

### ISSUE THREAD

**Issue by Deathwishx64** [Ryujinx/Ryujinx#5993]
### Description of the issue

Double click on the Nintendo Switch Online Nintendo 64 and the game launches into the interface to pick the game. I choose any of the games in the list and the application crashes to desktop. I am on Firmware Version 17.0.0

### Reproduction steps

1.Double click on NSO N64 NSP
2.Wait until the game list appears
3.Pick any games in the list.
Ryujinx crashes.

### Log file

00:00:00.041 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.048 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.048 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.049 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.050 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.051 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.051 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2206
00:00:00.052 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.052 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.053 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.054 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.060 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.060 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.060 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.060 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.060 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.060 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.060 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.060 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.060 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.061 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.061 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.062 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.062 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.062 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.062 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.065 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.065 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1094
00:00:00.069 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.069 |N| Application Print: CPU: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz ; 20 logical
00:00:00.071 |N| Application Print: RAM: Total 31.8 GiB ; Available 26.6 GiB
00:00:00.073 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.073 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.078 |I| Gpu : Backend Threading (Auto): True
00:00:00.424 |N| Application LoadApplication: Using Firmware Version: 17.0.0
00:00:00.424 |I| Application LoadApplication: Loading as NSP.
00:00:00.448 |I| ModLoader QueryContentsDir: Searching mods for Title 0100C9A00ECE6000
00:00:00.448 |I| ModLoader QueryContentsDir: Searching mods for Title 0100C9A00ECE6000
00:00:00.451 |I| Loader Load: Loading rtld...
00:00:00.458 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.458 |I| Loader Load: Loading main...
00:00:00.517 |I| Loader PrintRoSectionInfo: main:
    Module: l-classics
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_11-Release
                   SDK MW+Nintendo+NintendoSDK_libcurl-13_3_11-Release
                   SDK MW+Nintendo+NEX-4_6_6-
                   SDK MW+Nintendo+PiaCommon-5_38_0
                   SDK MW+Nintendo+Pia-5_38_0_59024
                   SDK MW+Nintendo+PiaNex-5_38_0-forNEX-4_6_6
                   SDK MW+Nintendo+NEX_MM-4_6_6
                   SDK MW+Nintendo+PiaSession-5_38_0
                   SDK MW+Nintendo+PiaTransport-5_38_0
                   SDK MW+Nintendo+NEX_CO-4_6_6
00:00:00.518 |I| Loader Load: Loading subsdk0...
00:00:00.522 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: vulkan
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_Vulkan-13_3_11-Release
00:00:00.522 |I| Loader Load: Loading subsdk1...
00:00:00.723 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: opengl
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_OpenGL-13_3_11-Release
00:00:00.723 |I| Loader Load: Loading sdk...
00:00:00.824 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 13.3.11
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_11-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_11-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_11-Release
00:00:00.917 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.232 |I| Ptc Load: Loaded Translation Cache (size: 29909943 bytes, translated functions: 21992).
00:00:01.241 |I| Ptc Load: Loaded Profiling Info (size: 72448 bytes, profiled functions: 21992).
00:00:01.254 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.255 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.429 |I| Loader LoadNsos: Loading image 2 at 0x000000002b8ae000...
00:00:01.429 |I| Loader LoadNsos: Loading image 3 at 0x000000002b92a000...
00:00:01.437 |I| Loader LoadNsos: Loading image 4 at 0x000000002d31a000...
00:00:01.444 |I| ModLoader LoadCheats: Build ids found for title 0100C9A00ECE6000:
    C1C80268F07394EA0ECA8BD0B1E3F0D44A763131000000000000000000000000
    35CED735890629B4DBF56C391BF32B2B65018282000000000000000000000000
    4B765CAA5C803D23D425BA4AFE2DC7962A52EDBD000000000000000000000000
    24A4AACDD9E8C619ECAEF6BF4E35ED0243E52F07000000000000000000000000
    857A7C8B3C7EB87E397529475ABB392C0AAD3B74000000000000000000000000
00:00:01.446 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.499 |I| Loader Start: Application Loaded: Nintendo 64 - Nintendo Switch Online v2.13.0 [0100c9a00ece6000] [64-bit]
00:00:01.506 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.516 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.993 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3080 (Vulkan v1.3.260, Driver v546.17.0.0)
00:00:02.000 |I| GPU.MainThread Gpu LoadShaders: Loading 8 shaders from the cache...
00:00:02.054 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.481 |I| HLE.GuestThread.42 Ptc LoadTranslations: 21992 translated functions loaded
00:00:02.763 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.770 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.771 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.771 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.777 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:03.636 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:03.637 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: 1055}
00:00:03.641 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Handheld,Player1,Player2,Player3,Player4
00:00:03.643 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:03.643 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:03.644 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:03.644 |S| HLE.OsThread.43 ServiceAm GetDefaultDisplayResolutionChangeEvent: Stubbed. 
00:00:03.647 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72279283318284288}
00:00:03.649 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:03.649 |S| HLE.OsThread.43 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:03.650 |S| HLE.OsThread.43 ServiceAm LockExit: Stubbed. 
00:00:03.654 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:03.656 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV10
00:00:03.668 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:03.669 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:03.684 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:03.697 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:03.715 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:03.769 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:03.769 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:03.770 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:03.770 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:03.770 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:03.770 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:03.807 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:03.822 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:03.822 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:03.822 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:03.822 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:03.822 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:03.822 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:03.828 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:03.839 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:03.839 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:03.839 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:03.839 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:03.839 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:03.840 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:03.841 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:03.845 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:03.855 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:03.855 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:03.855 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:03.855 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:03.855 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:03.855 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:03.860 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:03.880 |S| HLE.OsThread.43 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:03.886 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:03.886 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:03.889 |S| HLE.OsThread.43 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:03.890 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 7 Players: Handheld,Player1,Player2,Player3,Player4,Player5,Player6
00:00:03.890 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player2}
00:00:03.891 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player3}
00:00:03.891 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player4}
00:00:03.891 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player5}
00:00:03.891 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player6}
00:00:03.985 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:03.987 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:04.019 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: True ; unknownFlag3: False}
00:00:04.019 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:04.023 |S| HLE.OsThread.43 ServiceFriend GetFriendList: Stubbed. {UserId: 00000000000000010000000000000000 ; offset: 0 ; PresenceStatus: None ; IsFavoriteOnly: False ; IsSameAppPresenceOnly: False ; IsSameAppPlayedOnly: False ; IsArbitraryAppPlayedOnly: False ; PresenceGroupId: 0}
00:00:04.050 |S| HLE.OsThread.43 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:06.145 |S| HLE.OsThread.43 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:06.146 |S| HLE.OsThread.43 ServiceNifm Submit: Stubbed. 
00:00:06.146 |S| HLE.OsThread.43 ServiceNifm GetRequestState: Stubbed. 
00:00:06.146 |S| HLE.OsThread.43 ServiceNifm GetResult: Stubbed. 
00:00:06.147 |S| HLE.OsThread.43 ServiceAcc CheckAvailability: Stubbed. 
00:00:06.147 |S| HLE.OsThread.43 ServiceAcc GetNintendoAccountUserResourceCacheForApplication: Stubbed. {NetworkServiceAccountId: 51966}
00:00:10.415 |S| HLE.OsThread.43 ServiceFriend UpdateUserPresence: Stubbed. {UserId: 00000000000000010000000000000000 ; userPresenceInputArray: UserPresence { UserId: 00000000000000010000000000000000, LastTimeOnlineTimestamp: 0, Status: Offline }}
00:00:10.466 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: menu 
 Report: {
    "controller1_state": 5,
    "controller2_state": 0,
    "controller3_state": 0,
    "controller4_state": 0,
    "controller_number": 1,
    "display_version": "2.13.0",
    "finger_clicked_number": 0,
    "finger_displayed_time": 0,
    "guide_mode": 1,
    "is_coral": 1,
    "is_online": 1,
    "is_room_locked": 0,
    "language": 2,
    "launch_title_id": "n_4631_e",
    "new_title_number": 0,
    "pal_mode": 2,
    "save_use_amount": 886016,
    "screen_mode": 1,
    "sort_mode": 1,
    "startup_count": 19,
    "staying_time": 0,
    "switch_mode": 2,
    "vibration_mode": 1
}

00:00:10.499 |S| HLE.OsThread.43 ServiceMnpp Initialize: Stubbed. {pid: 119}
00:00:10.499 |S| HLE.OsThread.43 ServiceMnpp SendRawTelemetryData: Stubbed. {userId: 00000000000000010000000000000000 ; titleId: {"title_id":"N-4631_e"}}
00:00:10.782 |I| HLE.OsThread.43 ModLoader QueryContentsDir: Searching mods for Title 010000000000003B
00:00:10.782 |I| HLE.OsThread.43 ModLoader QueryContentsDir: Searching mods for Title 010000000000003B
00:00:10.782 |I| HLE.OsThread.43 Loader Load: Loading main...
00:00:10.789 |I| HLE.OsThread.43 Loader PrintRoSectionInfo: main:
    Module: jit
00:00:10.790 |I| HLE.OsThread.43 Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:10.790 |I| HLE.OsThread.43 Ptc Load: Loaded Profiling Info (size: 1541 bytes, profiled functions: 484).
00:00:10.791 |I| HLE.OsThread.43 Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:10.791 |I| HLE.OsThread.43 ModLoader LoadCheats: Build ids found for title 010000000000003B:
    60CA63F355716B10FBE9140515336405C7726AC2000000000000000000000000
00:00:10.792 |W| HLE.OsThread.43 Loader Load: No RomFS found in NCA
00:00:10.820 |I| HLE.GuestThread.60 Ptc MakeAndSaveTranslations: 0 of 484 functions translated | Thread count: 19
00:00:10.852 |E| Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000008632410.
00:00:10.852 |E| Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000008632030.
00:00:10.852 |E| Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000000086323F0.
00:00:10.871 |I| HLE.OsThread.43 Loader Start: Application Loaded:  v17.0.0 [010000000000003b] [64-bit]
00:00:10.900 |E| Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x0000000008632030, size=0x0000000000000004
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 139
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.Read[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 202
   at ARMeilleure.Decoders.Decoder.DecodeOpCode(IMemoryManager memory, UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 354
   at ARMeilleure.Decoders.Decoder.FillBlock(IMemoryManager memory, ExecutionMode mode, Block block, UInt64 limitAddress) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 217
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, DecoderMode dMode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 107
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleStep) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 267
   at ARMeilleure.Translation.PTC.Ptc.<>c__DisplayClass75_0.<MakeAndSaveTranslations>g__TranslateFuncs|0() in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\PTC\Ptc.cs:line 829
00:00:10.900 |E| Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x0000000008632410, size=0x0000000000000004
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 139
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.Read[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 202
   at ARMeilleure.Decoders.Decoder.DecodeOpCode(IMemoryManager memory, UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 354
   at ARMeilleure.Decoders.Decoder.FillBlock(IMemoryManager memory, ExecutionMode mode, Block block, UInt64 limitAddress) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 217
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, DecoderMode dMode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 107
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleStep) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 267
   at ARMeilleure.Translation.PTC.Ptc.<>c__DisplayClass75_0.<MakeAndSaveTranslations>g__TranslateFuncs|0() in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\PTC\Ptc.cs:line 829
00:00:10.900 |E| Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x00000000086323F0, size=0x0000000000000004
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 139
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.Read[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 202
   at ARMeilleure.Decoders.Decoder.DecodeOpCode(IMemoryManager memory, UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 354
   at ARMeilleure.Decoders.Decoder.FillBlock(IMemoryManager memory, ExecutionMode mode, Block block, UInt64 limitAddress) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 217
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, DecoderMode dMode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Decoders\Decoder.cs:line 107
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleStep) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 267
   at ARMeilleure.Translation.PTC.Ptc.<>c__DisplayClass75_0.<MakeAndSaveTranslations>g__TranslateFuncs|0() in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\PTC\Ptc.cs:line 829

### OS

Windows 10

### Ryujinx version

1.1.1094

### Game version

2.13.0

### CPU

i9-10850k

### GPU

Nvidia 3080

### RAM

32GB

### List of applied mods

No mods

### Additional context?

I tried uninstalling the NSO Nintendo 64 2.13.0 update to 1.0.0 and tested. Same error happens.
This error only happens on Firmware Version 17.0.0.
If I downgrade to 16.1.0 it will not crash.
I tried with Yuzu on firmware 17.0.0 also and it doesn't crash.

**Comment by gmetals** [comment]
I'm having the exact same issue but with M1 MacBook Air. Exactly the same steps and crashes.

**Comment by gmetals** [comment]
It's working now!!! Awesome Job
