### ISSUE TITLE
[Bug] Apps Built with NX.JS attempt to access an invalid memory region.

### ISSUE THREAD

**Issue by Fancy2209** [Ryujinx/Ryujinx#5994]
### Description of the issue

Any homebrew app built with NX.JS (https://github.com/TooTallNate/nx.js) will crash Ryujinx
Example:
https://github.com/TooTallNate/nx.js/releases/download/v0.0.23/nxjs.nro

### Reproduction steps

1. Load a NRO built using nx.js

### Log file

[Ryujinx_1.1.1094_2023-11-30_21-16-51.log](https://github.com/Ryujinx/Ryujinx/files/13518386/Ryujinx_1.1.1094_2023-11-30_21-16-51.log)

### OS

Windows 11

### Ryujinx version

1.1.1094

### Game version

v0.0.23

### CPU

AMD Ryzen 7 5700U with Radeon Graphics 

### GPU

AMD AMD Radeon(TM) Graphics

### RAM

16 GB

**Comment by TooTallNate** [comment]
nx.js works well with Ryujinx since a few months ago. Below is a screenshot of 2048 running. This issue can probably be closed.

<img width="1392" alt="Screenshot 2024-03-29 at 01 11 39" src="https://github.com/Ryujinx/Ryujinx/assets/71256/24008003-32de-4c9a-b6c2-d48f57b1357a">
