### ISSUE TITLE
astral chain randomly crash latest build

### ISSUE THREAD

**Issue by amarantsnipersnake** [Ryujinx/Ryujinx#5998]
### Description of the issue

gameplay is smooth but its just randomly crash whenever a play this game

### Reproduction steps

intro gameplay crash at first then after retry again. no crash... first battle crash again. restarting the emulator crash gone. i dont know just randomly crash

### Log file

00:00:00.081 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.098 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.098 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.100 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.101 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.103 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.104 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1F91
00:00:00.105 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.107 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.107 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.110 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.122 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.122 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.123 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.123 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.123 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.123 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.123 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.125 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.125 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.128 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.128 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.128 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.128 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.138 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.144 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1094
00:00:00.155 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.155 |N| Application Print: CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz ; 8 logical
00:00:00.159 |N| Application Print: RAM: Total 15.9 GiB ; Available 11.3 GiB
00:00:00.164 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.165 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:02.400 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.
00:00:00.255 |I| Gpu : Backend Threading (On): True
00:00:00.960 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.0
00:00:00.961 |I| Application LoadGuestApplication: Loading as NSP.
00:00:01.040 |I| ModLoader QueryContentsDir: Searching mods for Title 01007300020FA000
00:00:01.041 |I| ModLoader QueryContentsDir: Searching mods for Title 01007300020FA000
00:00:01.060 |I| Loader Load: Loading rtld...
00:00:01.070 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.070 |I| Loader Load: Loading main...
00:00:01.439 |I| Loader PrintRoSectionInfo: main:
    Module: D:\project\PRJ_036\p1_RomMake_Release\common\project\build\exe\NX64\ReleasePack\PRJ_036.nss
00:00:01.440 |I| Loader Load: Loading sdk...
00:00:01.690 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 6.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-6_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-6_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-6_4_0-Release
00:00:01.877 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.469 |I| Ptc Load: Loaded Translation Cache (size: 25819184 bytes, translated functions: 19973).
00:00:02.499 |I| Ptc Load: Loaded Profiling Info (size: 81405 bytes, profiled functions: 24630).
00:00:02.518 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:02.520 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:02.626 |I| Loader LoadNsos: Loading image 2 at 0x00000000151d0000...
00:00:02.634 |I| ModLoader LoadCheats: Build ids found for title 01007300020FA000:
    9621263BF431F8D07AC1057DCC8247CD480C9C0E000000000000000000000000
    ED2026B20685971F8B332095A7FF80FF00000000000000000000000000000000
    E29BE8AD6778527AA248310D0C71A8A51C4643A3000000000000000000000000
00:00:02.639 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.726 |I| Loader Start: Application Loaded: ASTRAL CHAIN v1.0.0 [01007300020fa000] [64-bit]
00:00:02.790 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.824 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:04.696 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1650 (Vulkan v1.3.260, Driver v546.17.0.0)
00:00:04.716 |I| GPU.MainThread Gpu LoadShaders: Loading 249 shaders from the cache...
00:00:06.261 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:06.992 |I| HLE.GuestThread.42 Ptc LoadTranslations: 19520 translated functions loaded
00:00:07.011 |I| HLE.GuestThread.42 Ptc MakeAndSaveTranslations: 0 of 5110 functions translated | Thread count: 7
00:00:13.159 |I| HLE.GuestThread.42 Ptc MakeAndSaveTranslations: 5110 of 5110 functions translated | Thread count: 7 in 6.1458111 s
00:00:13.458 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:13.468 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:13.469 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:13.470 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:13.487 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:13.502 |G| HLE.OsThread.20 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 12s
    ProgramName: PRJ_036
    Thread: MainThread
    Filename: D:/project/PRJ_036/p1_RomMake_Release/framework/src/Hw/Mem/Device/Platforms/Nx/HwSystemAllocateFunc.cpp
    Line: 29
    Function: nninitStartup
    Message: ---- nninitStartup Begin ----

00:00:15.455 |I| Ptc Save: Saved Translation Cache (size: 31024816 bytes, translated functions: 25083).
00:00:15.791 |G| HLE.OsThread.20 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 15s
    ProgramName: PRJ_036
    Thread: MainThread
    Filename: D:/project/PRJ_036/p1_RomMake_Release/framework/src/Hw/Mem/Device/Platforms/Nx/HwSystemAllocateFunc.cpp
    Line: 107
    Function: nninitStartup
    Message: ---- nninitStartup End ----

00:00:15.864 |G| HLE.OsThread.20 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 15s
    ProgramName: PRJ_036
    Thread: MainThread
    Filename: D:/project/PRJ_036/p1_RomMake_Release/framework/src/Hw/Os/Device/Platforms/Nx/HwOsSystemDeviceImpl.cpp
    Line: 90
    Function: entryApplication
    Message: ---- entryPoint Begin ----

00:00:15.875 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:15.875 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: True}
00:00:15.876 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:15.876 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:15.877 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:15.905 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:15.912 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:15.913 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:15.913 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:15.914 |S| HLE.OsThread.9 ServiceHid GetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 1 ; SupportedStyleSets: ProController, Handheld, JoyconPair}
00:00:15.919 |S| HLE.OsThread.43 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:00:15.926 |I| HLE.OsThread.43 ServiceAm .ctor: Applet 'Controller' created.
00:00:15.943 |S| HLE.OsThread.43 ServiceHid Start: Stubbed. ControllerApplet ArgPriv 20 540 ShowControllerSupport HoldType:Vertical StyleSets:ProController, Handheld, JoyconPair
00:00:15.944 |S| HLE.OsThread.43 ServiceHid Start: Stubbed. ControllerSupportArg Version Pre-7 EnableExplainText=False
00:00:15.944 |S| HLE.OsThread.43 ServiceHid Start: Stubbed. ControllerApplet Arg 1 1 1 1
00:00:15.945 |S| HLE.OsThread.43 ServiceHid Start: Stubbed. ControllerApplet ReturnResult 1 0
00:00:15.958 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:15.958 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:15.962 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:15.962 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:17.263 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:17.277 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:17.308 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:17.337 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:17.339 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:17.339 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:17.339 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:17.339 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:17.435 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:17.436 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:17.437 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:17.437 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:17.439 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:17.439 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:17.439 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:17.441 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:18.125 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:18.913 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:19.244 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:19.279 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72184037909700608}
00:00:19.282 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:25.007 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: system_play_mode 
 Report: {
    "mode": "handheld"
}

00:01:13.171 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81428 bytes, profiled functions: 24635).
00:01:20.774 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:21.775 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 8885 took more than 1000ms, resuming execution...
00:01:43.172 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81510 bytes, profiled functions: 24659).
00:02:02.808 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: system_event_skip 
 Report: {
    "event_id": "1150",
    "is_skip": False,
    "type": "phase",
    "geme_clear": False,
    "all_cnt": 8
}

00:02:13.172 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81511 bytes, profiled functions: 24659).
00:02:14.799 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: system_event_skip 
 Report: {
    "event_id": "1151",
    "is_skip": False,
    "type": "phase",
    "geme_clear": False,
    "all_cnt": 9
}

00:02:43.172 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81534 bytes, profiled functions: 24665).
00:02:49.301 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:03:08.162 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:03:13.170 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81575 bytes, profiled functions: 24676).
00:03:27.828 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:03:31.965 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:03:31.990 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:03:39.966 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:03:43.169 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81677 bytes, profiled functions: 24707).
00:04:08.589 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:04:08.622 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:04:08.744 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:04:13.169 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81689 bytes, profiled functions: 24711).
00:04:28.304 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:04:43.168 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81719 bytes, profiled functions: 24720).
00:05:13.173 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81752 bytes, profiled functions: 24730).
00:05:43.170 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81752 bytes, profiled functions: 24730).
00:06:05.590 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: system_event_skip 
 Report: {
    "event_id": "0020",
    "is_skip": False,
    "type": "normal",
    "geme_clear": False,
    "all_cnt": 10
}

00:06:09.729 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:06:13.170 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81834 bytes, profiled functions: 24754).
00:06:17.524 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: game_write_savedata 
 Report: {
    "file_no": 1,
    "playstyle": "super_casual",
    "geme_clear": False,
    "play_time": "000:17:33",
    "file_select": False,
    "money": 0,
    "gene_code": 88,
    "rest_num": 99,
    "rest_max_num": 99
}

00:06:30.294 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:06:30.301 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:06:43.172 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 81865 bytes, profiled functions: 24762).
00:07:10.064 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: system_event_skip 
 Report: {
    "event_id": "0025",
    "is_skip": False,
    "type": "normal",
    "geme_clear": False,
    "all_cnt": 11
}

00:07:10.294 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:10.319 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:11.103 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:11.304 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:11.609 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:11.729 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:11.769 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:13.171 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 82612 bytes, profiled functions: 24975).
00:07:19.903 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:07:21.720 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:26.239 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:26.243 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:31.445 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:07:43.173 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 83231 bytes, profiled functions: 25153).
00:08:13.171 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 83569 bytes, profiled functions: 25255).
00:08:43.170 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 83705 bytes, profiled functions: 25292).
00:09:08.172 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:09:13.170 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 83808 bytes, profiled functions: 25320).
00:09:16.026 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:09:16.037 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:09:19.158 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 223
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 55
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 120
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\AppHost.cs:line 918
   at System.Threading.Thread.StartCallback()

### OS

windows 10

### Ryujinx version

1.1.1094

**Comment by gdkchan** [comment]
You can try enabling texture recompression, this game uses a lot of ASTC textures.
