### ISSUE TITLE
[CPU] Wheel of fortune undefined instruction - opcode 0xe7ffdefe (trap)

### ISSUE THREAD

**Issue by TrevorSlobodnick** [Ryujinx/Ryujinx#6000]
### CPU instruction

The instruction at 0x0000000009a15658 (opcode 0xe7ffdefe) is undefined!

### Instruction name

trap

### Required by

https://github.com/Ryujinx/Ryujinx-Games-List/issues/3756

**Comment by OldManKain** [comment]
Duplicate of #1340.
