### ISSUE TITLE
[Bug] Ryujinx does nothing when I try to load a game

### ISSUE THREAD

**Issue by ballo** [Ryujinx/Ryujinx#6008]
### Description of the issue

Ryujinx does nothing when I try to load a game. If I try to load another it will complain "A game has already been loaded". If I try to quit it will freeze and a force quit is necessary. 

### Reproduction steps

• Download Ryujinx
• Install keys and firmware
• Attempt to load game

### Log file

00:00:00.039 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.043 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.043 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.044 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.044 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.045 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.045 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.045 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.046 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.046 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.046 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.051 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.051 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.051 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.051 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.051 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.051 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.051 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.052 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.052 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.052 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.052 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.054 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.054 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1098
00:00:00.056 |N| Application Print: Operating System: macOS 13.5.1 (22G90) (Arm64)
00:00:00.057 |N| Application Print: CPU: Apple M1 ; 8 logical
00:00:00.058 |N| Application Print: RAM: Total 16 GiB ; Available 5 GiB
00:00:00.059 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.059 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:19.929 |E| .NET TP Worker 2023-12-05 12:46:37.710 Ryujinx[43853:7657129] +[CATransaction synchronize] called within transaction
00:00:20.224 |E| .NET TP Worker 2023-12-05 12:46:38.007 Ryujinx[43853:7657129] +[CATransaction synchronize] called within transaction
00:00:00.096 |I| Gpu : Backend Threading (Auto): True
00:00:00.433 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.0
00:00:00.433 |I| Application LoadGuestApplication: Loading as cart WITHOUT RomFS.
00:00:00.434 |W| Loader GetNpdm: NPDM file not found, using default values!
00:00:00.437 |I| ModLoader QueryContentsDir: Searching mods for DLC 010000000000100D
00:00:00.437 |I| ModLoader QueryContentsDir: Searching mods for DLC 010000000000100D
00:00:00.437 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.438 |W| Application EnsureSaveData: No control file was found for this game. Using a dummy one instead. This may cause inaccuracies in some games.
00:00:00.458 |E| Loader LoadNsos: Process initialization returned error "InvalidMemoryRegion".

### OS

MacOS Ventura 

### Ryujinx version

1.1.1098

### Game version

any

### CPU

M1 8 core

### GPU

M1 8 core

### RAM

16GB

### Additional context?

Is there a version of the app that works?

**Comment by ekuland** [comment]
Whatever you're loading is not a game.
