### ISSUE TITLE
[Bug] Impossible to change Splatoon 2 US version (title ID: 01003BC0000A0000) language 

### ISSUE THREAD

**Issue by uniclo988** [Ryujinx/Ryujinx#6012]
[Ryujinx_1.1.1098_2023-12-06_18-13-10.log](https://github.com/Ryujinx/Ryujinx/files/13589188/Ryujinx_1.1.1098_2023-12-06_18-13-10.log)
### Description of the issue

The US version of Splatoon 2 (title ID: 01003BC0000A0000 vanilla and with 5.5.1 patch) is compatible with English, French, Spanish, Japanese, German, Italian, Dutch, Russian languages. Regardless of the language and region chosen in the Ryujinx settings, the game remains in English. The logfil show "Application doesn't support configured language. Using AmericanEnglish" but on this same game version the language can be changed on the real hardware on with another emulator. 

### Reproduction steps

1) Launch Ruyjinx
2) Choose Option  > Settings > System
3) Choose any parameters apart from English in System language
4) Press “apply” then “save”
5) Launch the game Splatoon 2 US version (title ID: 01003BC0000A0000): you will notice that the game is still in English.

### Log file

N/A

### OS

Windows 11

### Ryujinx version

1.1.1098

### Game version

5.5.1

### CPU

Intel Core I5-8500

### GPU

Nvidia GTX 1660 Super

### RAM

32GB

**Comment by ekuland** [comment]
You have not supplied a log, but I assume the game does not support the language you selected, which would be logged.

**Comment by uniclo988** [comment]
> You have not supplied a log, but I assume the game does not support the language you selected, which would be logged.

Hi,n thanks you for your answer. I confirm that this game version support the language in selected (French & Spannish) because with the same game version this problem doesn't occur on real hardware on an another emulator

**Comment by gdkchan** [comment]
There are two options for french (French and Canadian French) and two options for spanish (Spanish and Latin American Spanish), make sure you're selecting the correct one.

**Comment by uniclo988** [comment]
Thank you for your answer. I retry with "Canadian French" and it works. On the other hand, on Yuzu there are just "French" with no other choice and it works.

This means that it is not a bug but that Ryujinx is more precise than Yuzu in the choice of language. I'm impressed that the Ryujinx developers went into this level of detail, it's a really good emulator !

I'm closing the bug (and I don't know if it's possible to leave the thread to help other people who are wondering)
