### ISSUE TITLE
[Bug] White lights and red flashes on macos totk

### ISSUE THREAD

**Issue by noahgg2** [Ryujinx/Ryujinx#6013]
### Description of the issue

[Bug] White lights and red flashes on macos totk
![Screenshot 2023-12-05 at 9 17 47 PM](https://github.com/Ryujinx/Ryujinx/assets/142541090/1fe94d1c-f962-496f-be02-d22555dd99ed)

### Reproduction steps

just play the game

### Log file

None

### OS

mac 

### Ryujinx version

newest one

### Game version

1.20

### CPU

mac pro 2

### List of applied mods

None

### Additional context?

nope

**Comment by AcK77** [comment]
With just a screenshot it will be hard to debug something.
Try to purge your shader cache, or at least delete the folder completely, be sure you didn’t use any mods before too.
If the issue still occurs after that, you can report it in our game compatibility repository.
Thanks.
