### ISSUE TITLE
enable_file_log config entry should be disabled by default

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#602]
With things like stub function calls being written to the log all the time, the file can get big pretty quickly, and use a considerable amount of hard drive space, after some time with the emulator running, it's likely that the user will run out of space due to that. So, by default, imo it should be disabled.

**Comment by jduncanator** [comment]
I already have a fix for this in development, but happy for input.

I plan to make the log file rotate, rather than append - so each new run will create a new log file, and remove an old one (keeping the max log files on disk at, say, 3).

I don’t like the idea of turning off the file log by default, because it’s extremely handy for users who may not be technically inclined to provide us with a log file after the console has already closed.

**Comment by gdkchan** [comment]
The problem is the size of each log file, not the number of them. As it is now, the file will keep growing forever, which is not a good thing.

**Comment by jduncanator** [comment]
The reason it keeps growing is because the log file appends to the same file each run. By rotating the log file, you’ll only ever have, say, 3 runs worth of logs max.

**Comment by gdkchan** [comment]
What I'm trying to say is that if I leave the emulator running for, say, 10 hours, it will spend all that time writing to the log file, and using a lot of disk spaces, as on some games, stuff is written to the log *all the time*, due to things like stub function calls being logged, like I said before.

**Comment by BaronKiko** [comment]
I think you only need to keep 1 log file. Much simpler to implement as you just open the file with a different mode and the user doesn't have to work out which log is relevant.
Regarding the size, I think we could have a logging enable entry for both console and the log file so we can hide things like stubbed from the file but not console.
Saying that we may want to add a category of useless stubbed stuff like vibrate where it's just constant. Some stubbed things are important.
Finally you could add a limit to the size of the file. And cycle back around to reuse that space. The limit can be set in config

**Comment by jduncanator** [comment]
@BaronKiko The idea behind rotating the logs is to ensure that, at a minimum, the last run's log file stays on disk. This lets me close and open Ryujinx again, without worrying about losing the log entries for the previous run. I can also see this being a fairly common behaviour amongst users (i.e. a user encounters a crash, then tries to run the emulator again, only to give up and report an issue. The second run will have overwritten the original exception they got).

I don't know how we can solve @gdkchan's issue without compressing the log files on disk, or truncating past a specific file size. Truncating might be a solution, but only if the sole goal of the file based log is to catch exceptions for users to report.

**Comment by BaronKiko** [comment]
Ok, I can see the benefit of keeping a few runs worth.
I think limiting the size of the logs, keeping the latest part, and reducing unneeded logs like stubs is probably the best solution. You can make the limit something like 200mb by default to keep a good amount.

**Comment by AcK77** [comment]
Fixed in #724
