### ISSUE TITLE
[Bug]Master Detective Archives colors look weird

### ISSUE THREAD

**Issue by setsuna1126** [Ryujinx/Ryujinx#6026]
### Description of the issue

sometimes colors look weird

### Reproduction steps

Happens randomly while playing, but happens often

### Log file

[Ryujinx_1.1.1098_2023-12-10_05-12-49.log](https://github.com/Ryujinx/Ryujinx/files/13625710/Ryujinx_1.1.1098_2023-12-10_05-12-49.log)

### OS

Windows 10 22H2

### Ryujinx version

Ryujinx_1.1.1098

### Game version

1.4.0

### CPU

 i7-12700

### GPU

RTX 3080

### RAM

32 GB

### List of applied mods

no

### Additional context?

![ryujinx_capture_2023-12-10_05-26-20](https://github.com/Ryujinx/Ryujinx/assets/116227791/67d9abe4-4fdc-4547-8189-6e4c1d662813)

**Comment by OldManKain** [comment]
Please report game specific bugs on our gameslist https://github.com/Ryujinx/Ryujinx-Games-List/issues/4668
