### ISSUE TITLE
Crash Team Racing Crackling Sound[Bug]

### ISSUE THREAD

**Issue by matiashuarta** [Ryujinx/Ryujinx#6027]
### Description of the issue

Crackling sound throughout the game

### Reproduction steps

Just run the game

### Log file

[Ryujinx_1.1.1098_2023-12-11_03-13-00.log](https://github.com/Ryujinx/Ryujinx/files/13637560/Ryujinx_1.1.1098_2023-12-11_03-13-00.log)

### OS

Windows 11

### Ryujinx version

1.1.1098

### Game version

1.0.0

### CPU

i5 9400 F

### GPU

RTX 4060Ti

### RAM

32GB

**Comment by OldManKain** [comment]
Known issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/178 Please report game specific bugs on our [Games List](https://github.com/Ryujinx/Ryujinx-Games-List)
