### ISSUE TITLE
[Bug] Ryujinx crashes when on initial loading screen in Super Mario RPG

### ISSUE THREAD

**Issue by Occuvite1** [Ryujinx/Ryujinx#6031]
### Description of the issue

Whenever I open Super Mario RPG it shows the loading blocks in the bottom right hand corner, but then freezes and crashes Ryujinx.  

### Reproduction steps

Open Ryujinx and run Super Mario RPG

### Log file

[Ryujinx_1.1.1100_2023-12-11_21-45-16.log](https://github.com/Ryujinx/Ryujinx/files/13643839/Ryujinx_1.1.1100_2023-12-11_21-45-16.log)

### OS

Windows 11

### Ryujinx version

1.1.1100

### Game version

1.0.0

### CPU

Ryzen 9 5900x

### GPU

Nvidia RTX 3080 Ti

### RAM

32GB

### List of applied mods

N/A

### Additional context?

I've tested this on multiple computers all with the same issue.  I've also tested Yuzu and it works just fine there.  I do have some of my folders syncing to other machines using Syncthing, so I'm guessing it's an issue that relates to my config or some other setting that is syncing.  I've never been able to launch the game and play it using Ryujinx.  

I also was getting an error that I didn't have my controller connected, which is was over wireless.  I had to plug it in to get that popup to go away, but it still crashes in the same spot regardless.

**Comment by OldManKain** [comment]
Something is stopping Ryujinx from accessing your file system.
Make sure you aren't using a third-party anti virus.
Make sure Ryujinx is not on the desktop or in a protected folder.
If you need more help please join us in our [Discord](https://discord.gg/ryujinxl) for general troubleshooting.

**Comment by Occuvite1** [comment]
I’m using windows Anti-Virus, nothing more.
Ryujinx is on a secondary drive, not in a protected folder, I only had a shortcut on the desktop.  I tried running the app directly from the folder and I get the same result.  Do I need to do anything with the appdata Ryujinx folders?

**Comment by Occuvite1** [comment]
I was able to fix this by clearing out the Ryujinx System Save files.  It seemed like my file save location was not working.
