### ISSUE TITLE
[Bug] DwmEnableBlurBehindWindow Failed

### ISSUE THREAD

**Issue by KduSiqueira** [Ryujinx/Ryujinx#6038]
### Description of the issue

This crash occurs randomly several times during the game since previous versions. A white or black screen appears (It doesn't matter, like when we update the VGA driver) it crashes. Is it a known issue?
![Ryujinx_Crash](https://github.com/Ryujinx/Ryujinx/assets/151872591/6aaf7417-856a-46b0-977c-dd7f464796d6)

### Reproduction steps

It happens at any time

### Log file

![Ryujinx_Crash](https://github.com/Ryujinx/Ryujinx/assets/151872591/1ed28393-73b3-43f7-bcad-6d2bd85bb468)

### OS

Windows 10

### Ryujinx version

1.1.1100

### Game version

1.3.0

### CPU

i5-10400

### GPU

AMD RX 5600 XT

### RAM

16GB

### List of applied mods

None

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
