### ISSUE TITLE
decrypt NCA header.

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#604]
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: LibHac.MissingKeyException: Unable to decrypt NCA header.
#571 
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/2897840/Ryujinx.log)
![sharedscreenshot19](https://user-images.githubusercontent.com/37957125/53298671-0372d400-3810-11e9-97a9-c6171bbdd2a3.jpg)
![sharedscreenshot20](https://user-images.githubusercontent.com/37957125/53298672-0372d400-3810-11e9-9299-8bf66a8991d7.jpg)

**Comment by BaronKiko** [comment]
Error in user config. Please close.
