### ISSUE TITLE
[Bug] Can't load The Legend of Zelda: Tears of the Kingdom on v1.2.1 on Firmware 16.1.0

### ISSUE THREAD

**Issue by juliocoliveira** [Ryujinx/Ryujinx#6048]
### Description of the issue

Crash on loading Tears of the Kingdrom on v1.2.1.
It runs fine with v1.2.0.
But if I update it to the latest version it crashing on load.

### Reproduction steps

1 - Download Tears of the Kingdom v1.2.1,
2 - Load it
3 - Crash

### Log file

00:00:00.038 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.045 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.045 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.046 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.047 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.047 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.048 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2489
00:00:00.048 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.049 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.049 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.050 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.055 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.056 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.056 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.056 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.056 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.056 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.056 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.056 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.056 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.056 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.057 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.058 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.058 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.058 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.058 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.062 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.062 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1100
00:00:00.066 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.066 |N| Application Print: CPU: AMD Ryzen 7 5800X 8-Core Processor ; 16 logical
00:00:00.067 |N| Application Print: RAM: Total 31.9 GiB ; Available 19.5 GiB
00:00:00.069 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.070 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.066 |I| Gpu : Backend Threading (Auto): True
00:00:00.316 |N| Application LoadApplication: Using Firmware Version: 16.1.0
00:00:00.316 |I| Application LoadApplication: Loading as NSP.
00:00:00.336 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.337 |I| ModLoader AddModsFromDirectory: Found mod 'Max DFPS++' [E]
00:00:00.337 |I| ModLoader AddModsFromDirectory: Found mod 'Max DFPS++' [R]
00:00:00.338 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.339 |I| Loader Load: Loading rtld...
00:00:00.344 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.344 |I| Loader Load: Loading main...
00:00:00.591 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:00.591 |I| Loader Load: Loading subsdk0...
00:00:00.611 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:00.611 |I| Loader Load: Loading sdk...
00:00:00.654 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:00.656 |I| Loader PrintRoSectionInfo: subsdk9:
    Module: TOTK-DFPS
00:00:00.656 |I| ModLoader ApplyExefsMods: NSO 'subsdk9' replaced
00:00:00.657 |I| ModLoader ApplyExefsMods: main.npdm replaced
00:00:00.662 |W| Ptc Load: Detected unsupported ExeFs modifications. PTC disabled.
00:00:00.744 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: False).
00:00:00.752 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.753 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.776 |I| Loader LoadNsos: Loading image 2 at 0x000000000cc2f000...
00:00:00.778 |I| Loader LoadNsos: Loading image 3 at 0x000000000d2d8000...
00:00:00.778 |I| Loader LoadNsos: Loading image 4 at 0x000000000d305000...
00:00:00.785 |I| ModLoader LoadCheats: Build ids found for title 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    9B4E43650501A4D4489B4BBFDB740F26AF3CF850000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    F2ACBD073B607405EAB6325E2E415C0B7CD47C1C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:00.787 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Title 0100F2C0115B6000
00:00:00.791 |I| ModLoader ApplyRomFsMods: Replaced 1 file(s) over 1 mod(s). Processing base storage...
00:00:09.270 |I| ModLoader ApplyRomFsMods: Building new RomFS...
00:00:09.345 |I| ModLoader ApplyRomFsMods: Using modded RomFS
00:00:09.346 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:09.442 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.2.1 [0100f2c0115b6000] [64-bit]
00:00:09.450 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:09.465 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:09.811 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3060 Ti (Vulkan v1.3.260, Driver v546.33.0.0)
00:00:09.818 |I| GPU.MainThread Gpu LoadShaders: Loading 8846 shaders from the cache...
00:00:26.593 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:27.198 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:27.318 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:27.323 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:27.327 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:27.419 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:30.560 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:30.561 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:30.562 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:30.562 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:30.563 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:30.727 |I| HLE.OsThread.43 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:00:30.728 |I| HLE.OsThread.43 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:00:30.759 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:30.780 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:30.781 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:30.871 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:30.906 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:30.953 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:30.955 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:30.955 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:30.956 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:30.957 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:30.957 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:30.958 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:30.962 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:31.050 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:31.054 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:31.056 |S| HLE.OsThread.43 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:31.094 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:31.098 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:31.099 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:32.574 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:32.574 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:34.235 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:34.237 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:35.079 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:35.081 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV11
00:00:35.095 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:35.095 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:35.102 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:35.155 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:35.192 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:35.193 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:36.231 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:36.231 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:36.859 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:36.859 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:36.860 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:36.860 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:37.788 |S| HLE.OsThread.43 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:37.791 |S| HLE.OsThread.43 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:37.792 |S| HLE.OsThread.43 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:38.640 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:39.244 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:39.761 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: bootup_time 
 Report: {
    "BootupTimeUs": 9630,
    "system_report_tag": 2175206328
}

00:00:39.766 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: erepo_region 
 Report: {
    "Region": 1,
    "Language": 1,
    "StandardTimeName": "-03",
    "UtcOffsetSeconds": -10800,
    "system_report_tag": 2759414308
}

00:00:39.767 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: erepo_time 
 Report: {
    "ActiveTime": 12,
    "UpdatedTime": 0,
    "system_report_tag": 2759414308
}

00:00:39.767 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: erepo_playstyle 
 Report: {
    "system_report_tag": 2759414308
}

00:00:39.767 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: erepo_network_status 
 Report: {
    "NetworkInterface": {
        "TypeCode": 64,
        "Value": "0x00000000000000000000000000000000"
    },
    "LinkLevel": {
        "TypeCode": 65,
        "Value": "0x00"
    },
    "FrequencyBand": {
        "TypeCode": 66,
        "Value": "0x00000000000000000000"
    },
    "system_report_tag": 2759414308
}

00:00:39.768 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: erepo_active_beacon 
 Report: {
    "IntervalTime": 0,
    "UpdatedTime": 0,
    "system_report_tag": 0
}

00:00:42.582 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:42.594 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player2}
00:00:42.594 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player3}
00:00:42.594 |S| HLE.OsThread.9 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player4}
00:00:48.915 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:49.916 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 899 took more than 1000ms, resuming execution...
00:00:52.720 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1193981078,
    "EventInfo": "Dm_OP_0037",
    "PlayerPosX": 3.406024E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406211E-11,
    "system_report_tag": 2175206328
}

00:00:52.918 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1193981078,
    "EventInfo": "Dm_OP_0039",
    "PlayerPosX": 3.406024E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406211E-11,
    "system_report_tag": 2175206328
}

00:00:53.007 |S| HLE.OsThread.43 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:00:59.722 |I| HLE.OsThread.24 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: option_data 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1193981078,
    "BoolOptions": 1035,
    "CameraRotateSpeed": 2,
    "DisplayMode": 0,
    "MessageWindowTransparency": 0,
    "VoiceLanguage": 1,
    "Action": 1,
    "Cancel": 2,
    "Jump": 3,
    "Attack": 4,
    "SpecialPower": 5,
    "Attention": 6,
    "Throw": 7,
    "Bow": 8,
    "PlusMenu": 9,
    "MinusMenu": 10,
    "SpecialPowerShortcut": 11,
    "CompanionShortcut": 13,
    "PouchShortcut": 14,
    "Whistle": 12,
    "Crouch": 25,
    "Scope": 33,
    "PresetType": 0,
    "system_report_tag": 2175206328
}

00:00:59.775 |S| HLE.OsThread.43 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:01:08.282 |E| HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.RomFs.RomFsFile.DoRead(Int64& bytesRead, Int64 offset, Span`1 destination, ReadOption& option)
   at LibHac.Fs.FileStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.ConcatenationStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 358
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1100

### Game version

1.2.1

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA RTX 3060 TI

### RAM

32GB

### List of applied mods

Max DFPS++

**Comment by OldManKain** [comment]
Bad dump, Re-dump your game.
```LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!```

**Comment by juliocoliveira** [comment]
Indeed, Thanks!, I got it again and it runs great. Strange it got corrupted somehow.
