### ISSUE TITLE
[Bug] Frequent GPU Errors in Shin Megami Tensei V (SMTV)

### ISSUE THREAD

**Issue by Valance23322** [Ryujinx/Ryujinx#6056]
### Description of the issue

Video output will frequently freeze for a few seconds in both cutscenes and gameplay (audio continues uninterrupted) with the terminal / logs reporting:
```Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.```

### Reproduction steps

Issue is present in the game's opening cutscene, just need to start a new game to try to reproduce it.

### Log file

[Ryujinx_1.1.1100_2023-12-24_00-20-25.log](https://github.com/Ryujinx/Ryujinx/files/13761065/Ryujinx_1.1.1100_2023-12-24_00-20-25.log)

### OS

Windows 11

### Ryujinx version

1.1.1100

### Game version

1.0.2

### CPU

AMD 7700X

### GPU

AMD 7900 XTX

### RAM

32 GB

### Additional context?

Issue seems to be less severe, though still present, if the same cutscene is viewed multiple times.  After going through the intro cutscene ~6 times it only freezes a handful of times, whereas the first couple times I tried it it was freezing every handful of seconds.

**Comment by TopRascal** [comment]
Having the same issue. I used to be able to play just fine on my previous PC which also had an AMD GPU, wondering if it has something to do with our GPU in particular.

Current PC
OS: Windows 10 LTSC
GPU: AMD 7900XTX
CPU: AMD 7800X3D
RAM: 32GB 6000mhz

Old PC
OS: Windows 10 Home
GPU: AMD 5700
CPU: Intel i7-9700k
RAM: 64GB 3600mhz

Running on game version 1.01
Ryujinx version 1.1.1104 with no mods

Seems to happen more often when VSync is disabled, but still occurs regardless.

Log file:
[Ryujinx_1.1.1104_2024-01-09_12-33-43.log](https://github.com/Ryujinx/Ryujinx/files/13878925/Ryujinx_1.1.1104_2024-01-09_12-33-43.log)

**Comment by Valance23322** [comment]
@TopRascal I found a potential workaround, though it might cause some instability, if you clone the repo and edit the `MaxQueryRetries` in the BufferedQuery class down from 5000 to ~50 that makes the hitches barely noticeable.  This is more of a bandaid than an actual fix to the underlying issue however.

**Comment by kaminaridark** [comment]
@Valance23322 How can i do this? i'm desperate i don't know what the do with the freezes.. Can you help me? tyvm

**Comment by Valance23322** [comment]
Easiest way is to download one of the builds linked in the [PR](https://github.com/Ryujinx/Ryujinx/pull/6351) and use that instead of the normal release.

**Comment by Valance23322** [comment]
That was a workaround that would require you to edit the code and rebuild the emulator.  The issue is actually fixed via the change that is implemented in the PR.  Any of the builds linked to in that PR thread by the github actions bot will work, just depends on which platform you're running on (or if you want the experimental GUI version or etc.).

**Comment by kaminaridark** [comment]
i just download any version and i can play without freezes?

**Comment by Valance23322** [comment]
You'll need to download the version that was build for your platform (Windows, Linux, etc.).  The builds linked in the PR all include the fix

**Comment by kaminaridark** [comment]
Ohh thank you!! i'm gonna try the windows experimental build! you're the best tyvm
