### ISSUE TITLE
[Bug] crashed with M2 + 8G  Mac mini

### ISSUE THREAD

**Issue by leisurehuang** [Ryujinx/Ryujinx#6059]
### Description of the issue

crashed with M2+8G mac mini

### Reproduction steps

every time when open a game

### Log file

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ryujinx [2395]
Path:                  /Applications/Ryujinx.app/Contents/MacOS/Ryujinx
Identifier:            org.ryujinx.Ryujinx
Version:               1.1 (1.1.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-25 22:21:36.0295 +0800
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        196BE3E6-3D30-7E24-07AB-3E9066D42C00

Time Awake Since Boot: 1300 seconds

System Integrity Protection: enabled

Crashed Thread:        102

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Ryujinx [2395]

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x189345874 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x189357cf0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18934e4b0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x189345bf8 mach_msg + 24
4   CoreFoundation                	       0x189463bf4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1894624bc __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1894619ac CFRunLoopRunSpecific + 608
7   HIToolbox                     	       0x193a10448 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x193a10284 ReceiveNextEventCommon + 648
9   HIToolbox                     	       0x193a0ffdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x18cc3e8a4 _DPSNextEvent + 660
11  AppKit                        	       0x18d418980 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
12  AppKit                        	       0x18cc31d50 -[NSApplication run] + 476
13  libAvaloniaNative.dylib       	       0x1234fecd0 PlatformThreadingInterface::RunLoop(IAvnLoopCancellation*) + 484
14  ???                           	       0x10afb37b8 ???
15  ???                           	       0x10afb2f94 ???
16  ???                           	       0x10afb27d4 ???
17  ???                           	       0x10afb1cd4 ???
18  ???                           	       0x10afb10dc ???
19  ???                           	       0x10a655dd8 ???
20  ???                           	       0x1097102c0 ???
21  ???                           	       0x108677348 ???
22  Ryujinx                       	       0x1044bb104 CallDescrWorkerInternal + 132
23  Ryujinx                       	       0x104336408 MethodDescCallSite::CallTargetWorker(unsigned long long const*, unsigned long long*, int) + 856
24  Ryujinx                       	       0x104239410 RunMain(MethodDesc*, short, int*, PtrArray**) + 632
25  Ryujinx                       	       0x10423975c Assembly::ExecuteMainMethod(PtrArray**, int) + 260
26  Ryujinx                       	       0x104261c14 CorHost2::ExecuteAssembly(unsigned int, char16_t const*, int, char16_t const**, unsigned int*) + 616
27  Ryujinx                       	       0x1047910d4 coreclr_execute_assembly + 204
28  Ryujinx                       	       0x10420cd28 run_app_for_context(hostpolicy_context_t const&, int, char const**) + 1052
29  Ryujinx                       	       0x10420db24 corehost_main + 320
30  Ryujinx                       	       0x1041e3768 fx_muxer_t::handle_exec_host_command(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, host_startup_info_t const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::unordered_map<known_options, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>, known_options_hash, std::__1::equal_to<known_options>, std::__1::allocator<std::__1::pair<known_options const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>>> const&, int, char const**, int, host_mode_t, bool, char*, int, int*) + 1172
31  Ryujinx                       	       0x1041e29e8 fx_muxer_t::execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int, char const**, host_startup_info_t const&, char*, int, int*) + 860
32  Ryujinx                       	       0x1041df3bc hostfxr_main_bundle_startupinfo + 172
33  Ryujinx                       	       0x1042268bc exe_start(int, char const**) + 1080
34  Ryujinx                       	       0x104226bb8 main + 184
35  dyld                          	       0x1890050e0 start + 2360

Thread 102 Crashed:
0   libsystem_kernel.dylib        	       0x18934e0dc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x189385cc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x189291a40 abort + 180
3   Ryujinx                       	       0x10484ff68 PROCAbort + 68
4   Ryujinx                       	       0x10484fe30 PROCEndProcess(void*, unsigned int, int) + 352
5   Ryujinx                       	       0x10442abf8 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 900
6   Ryujinx                       	       0x10442acdc DispatchManagedException(PAL_SEHException&, bool) + 68
7   Ryujinx                       	       0x1043942f0 IL_Throw(Object*) + 516
8   ???                           	       0x10d615d04 ???
9   ???                           	       0x10d615ae8 ???
10  ???                           	       0x10d615424 ???
11  ???                           	       0x10d618ee0 ???
12  ???                           	       0x10cafec64 ???
13  ???                           	       0x10d67c798 ???
14  ???                           	       0x10d5b6a8c ???
15  ???                           	       0x10c9e34b4 ???
16  ???                           	       0x10c9667e0 ???
17  ???                           	       0x10c2a2da8 ???
18  ???                           	       0x10c2a2cd4 ???
19  ???                           	       0x10c2a2bc8 ???
20  Ryujinx                       	       0x1044bb104 CallDescrWorkerInternal + 132
21  Ryujinx                       	       0x10433604c DispatchCallSimple(unsigned long*, unsigned int, unsigned long long, unsigned int) + 268
22  Ryujinx                       	       0x1043493ac ThreadNative::KickOffThread_Worker(void*) + 148
23  Ryujinx                       	       0x1043085c0 ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 256
24  Ryujinx                       	       0x104308b18 ManagedThreadBase::KickOff(void (*)(void*), void*) + 32
25  Ryujinx                       	       0x104349484 ThreadNative::KickOffThread(void*) + 172
26  Ryujinx                       	       0x1048541d0 CorUnix::CPalThread::ThreadEntry(void*) + 380
27  libsystem_pthread.dylib       	       0x189386034 _pthread_start + 136
28  libsystem_pthread.dylib       	       0x189380e3c thread_start + 8

Thread 117:: .NET TP Worker
0   libsystem_kernel.dylib        	       0x18934906c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1893865fc _pthread_cond_wait + 1228
2   Ryujinx                       	       0x104848f78 CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) + 236
3   Ryujinx                       	       0x104848c3c CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) + 376
4   Ryujinx                       	       0x10484d38c CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int, int) + 1716
5   Ryujinx                       	       0x10484d508 PAL_WaitForSingleObjectPrioritized + 76
6   Ryujinx                       	       0x1043530c8 WaitHandle_CorWaitOnePrioritizedNative + 56
7   ???                           	       0x10b904e04 ???
8   ???                           	       0x10b905b48 ???
9   ???                           	       0x10b904cf4 ???
10  ???                           	       0x108693418 ???
11  ???                           	       0x10d148a28 ???
12  Ryujinx                       	       0x1044bb104 CallDescrWorkerInternal + 132
13  Ryujinx                       	       0x10433604c DispatchCallSimple(unsigned long*, unsigned int, unsigned long long, unsigned int) + 268
14  Ryujinx                       	       0x1043493ac ThreadNative::KickOffThread_Worker(void*) + 148
15  Ryujinx                       	       0x1043085c0 ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 256
16  Ryujinx                       	       0x104308b18 ManagedThreadBase::KickOff(void (*)(void*), void*) + 32
17  Ryujinx                       	       0x104349484 ThreadNative::KickOffThread(void*) + 172
18  Ryujinx                       	       0x1048541d0 CorUnix::CPalThread::ThreadEntry(void*) + 380
19  libsystem_pthread.dylib       	       0x189386034 _pthread_start + 136
20  libsystem_pthread.dylib       	       0x189380e3c thread_start + 8

Thread 102 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x00000000000000a0   x6: 0x0000000000000001   x7: 0x000000003b9ac618
    x8: 0xa7888cd8452cd262   x9: 0xa7888cdbf75d6262  x10: 0x0000000000000000  x11: 0x0000000104a09980
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x00000001e8bd7340  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x00000003b271b000  x21: 0x0000000000023303  x22: 0x00000003b271b0e0  x23: 0x00000003b2719948
   x24: 0x00000001048b037f  x25: 0x00000003b271aff0  x26: 0x00000003b271aff0  x27: 0x0000000000000000
   x28: 0x000000018938e620   fp: 0x00000003b2719800   lr: 0x0000000189385cc0
    sp: 0x00000003b27197e0   pc: 0x000000018934e0dc cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x3bac1c000 -        0x3bad9ffff libavcodec.59.dylib (*) <e171d5d3-a773-373c-b138-ad61a3982ddc> /Applications/Ryujinx.app/Contents/Frameworks/libavcodec.59.dylib
       0x1378cc000 -        0x13793bfff libavutil.57.dylib (*) <b6049b82-9325-3f3a-91d3-3591921e2e85> /Applications/Ryujinx.app/Contents/Frameworks/libavutil.57.dylib
       0x166e04000 -        0x1677d3fff com.apple.audio.AudioDSPComponents (1.0) <36aff29d-1856-3e05-b2ae-7d3e3f99a2f4> /System/Library/Components/AudioDSP.component/Contents/MacOS/AudioDSP
       0x136cbc000 -        0x136df3fff com.apple.audio.units.Components (1.14) <06275638-4d71-370d-bf96-b30a567270e1> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x136f90000 -        0x137427fff libMoltenVK.dylib (*) <f1369f0d-55ad-364f-b319-844700008581> /Applications/Ryujinx.app/Contents/Frameworks/libMoltenVK.dylib
       0x13233c000 -        0x132353fff com.apple.iokit.IOHIDLib (2.0.0) <64b640d0-a69c-3ce1-aecd-f5d4c6e861ee> /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib
       0x132854000 -        0x13299bfff libSDL2.dylib (*) <39bfaba5-6014-32a1-8502-be3df68f40b9> /Applications/Ryujinx.app/Contents/Frameworks/libSDL2.dylib
       0x13238c000 -        0x1324bbfff libHarfBuzzSharp.dylib (*) <8559335c-a6cd-3998-b6e9-dff2d2e9faf5> /Applications/Ryujinx.app/Contents/Frameworks/libHarfBuzzSharp.dylib
       0x1262cc000 -        0x1262d7fff libobjc-trampolines.dylib (*) <7778e0d7-361a-378d-9438-3b2bb48c2154> /usr/lib/libobjc-trampolines.dylib
       0x1262e4000 -        0x12634ffff com.apple.AppleMetalOpenGLRenderer (1.0) <41cb4d99-6a07-366a-9e97-d047ce10daa2> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
       0x1234f8000 -        0x123527fff libAvaloniaNative.dylib (*) <ada4af5c-bc67-38b2-b580-b86f046668c1> /Applications/Ryujinx.app/Contents/Frameworks/libAvaloniaNative.dylib
       0x1266d4000 -        0x126d47fff libSkiaSharp.dylib (*) <577c6de8-dc1c-39b7-b1e8-03b37fe68e07> /Applications/Ryujinx.app/Contents/Frameworks/libSkiaSharp.dylib
       0x1041d4000 -        0x1049a7fff org.ryujinx.Ryujinx (1.1) <05691984-73f4-3596-964d-b519a4ec82eb> /Applications/Ryujinx.app/Contents/MacOS/Ryujinx
       0x189344000 -        0x18937efff libsystem_kernel.dylib (*) <ca94fc21-bc40-3b43-b65d-b87ece9e1d48> /usr/lib/system/libsystem_kernel.dylib
       0x1893e6000 -        0x1898bdfff com.apple.CoreFoundation (6.9) <47e4ec09-8f6e-30a8-99d0-34024d4f8122> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1939e0000 -        0x193c9ffff com.apple.HIToolbox (2.1.1) <e2187dfe-1fb4-3b47-874e-a0a6291e51b2> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x18cc05000 -        0x18df1ffff com.apple.AppKit (6.9) <f3527312-e426-3f7c-b77b-2bf49d1b7c04> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x188fff000 -        0x189093347 dyld (*) <324e4ad9-e01f-3183-b09f-3e20b326643a> /usr/lib/dyld
       0x18937f000 -        0x18938bff3 libsystem_pthread.dylib (*) <a7d94c96-7b1f-3229-9bea-048d037c3292> /usr/lib/system/libsystem_pthread.dylib
       0x18938c000 -        0x1893b1ff3 libdyld.dylib (*) <33108ef5-2dc1-3e6d-b3be-c55520e1594f> /usr/lib/system/libdyld.dylib
       0x19370a000 -        0x193733fff com.apple.audio.caulk (1.0) <25e50b84-b506-3db7-9a91-3824b9b8b880> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x18921b000 -        0x189299ffb libsystem_c.dylib (*) <ab8a0a0b-9a1e-3284-9243-5a0334468ae5> /usr/lib/system/libsystem_c.dylib
       0x197f7d000 -        0x197fb5fff libAudioToolboxUtility.dylib (*) <47c30d1e-7fd4-383c-90cf-cb028c0c07c5> /usr/lib/libAudioToolboxUtility.dylib
       0x199263000 -        0x1993e1fff com.apple.audio.toolbox.AudioToolbox (1.14) <45b33e8c-5c24-398e-a4fb-595b24a1b886> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
       0x18b9bc000 -        0x18c0aefff com.apple.audio.CoreAudio (5.0) <2c54c60c-a5af-39f4-8286-0cb88fa43367> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)
Writable regions: Total=6.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=6.1G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
Audio                             10.0M        1 
CG image                            96K        6 
ColorSync                          176K        7 
CoreAnimation                      272K       15 
CoreGraphics                        32K        2 
CoreServices                        64K        1 
CoreUI image data                  480K        7 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.6G       63 
MALLOC guard page                  384K       24 
Memory Tag 28                      672K       42 
OpenGL GLSL                        384K        4 
STACK GUARD                       57.8M      118 
Stack                            218.4M      118 
VM_ALLOCATE                      972.9M     1588 
VM_ALLOCATE (reserved)              64K        1         reserved VM address space (unallocated)
__AUTH                            1048K      233 
__AUTH_CONST                      17.6M      409 
__CTF                               824        1 
__DATA                            5950K      408 
__DATA_CONST                      21.2M      421 
__DATA_DIRTY                      1044K      133 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5174K        1 
__LINKEDIT                       943.5M       14 
__OBJC_RO                         71.1M        1 
__OBJC_RW                         2168K        1 
__TEXT                           399.7M      440 
dyld private memory                272K        2 
mapped file                      291.7M      127 
shared memory                      4.0G       49 
===========                     =======  ======= 
TOTAL                              8.6G     4242 
TOTAL, minus reserved VM space     8.6G     4242 

### OS

Mac  OSX 14.2.1

### Ryujinx version

1.1.1101

### Game version

switch OS 17.0

### CPU

M2

### GPU

M2

### RAM

8G

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx

**Comment by EyadHashwa** [comment]
The Same exact error happened in my macbook air 2023 Game: Super mario all-stars(SunShine)"Galaxy and 64 Runs Good"
How to let it not crash

**Comment by EyadHashwa** [comment]
Do Any one Know?
