### ISSUE TITLE
[Bug]Can't make it run on Imac 27 late 2013

### ISSUE THREAD

**Issue by arnold-bg** [Ryujinx/Ryujinx#6060]
### Description of the issue

I tried to run the Ryujinx on my iMac with Monterey (Late 2013 27 Inch ), but still crashes right after the rom should load. From the logs I read I assume it has something to do with Vulcan drivers... ±Tried to install some files from home-brew, lunar exchange and etc. but still did not work...

### Reproduction steps

every time I try to load any game

### Log file

00:00:00.093 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.102 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.103 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.104 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.105 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.106 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.107 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x119D
00:00:00.108 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.109 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.109 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.111 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.112 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.112 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.112 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.112 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.112 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.112 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.112 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.112 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.113 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.114 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.114 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.115 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.115 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.116 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.116 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.120 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.121 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1101
00:00:00.134 |N| Application Print: Operating System: macOS 12.7.2 (21G1974) (X64)
00:00:00.134 |N| Application Print: CPU: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz ; 4 logical
00:00:00.136 |N| Application Print: RAM: Total 24 GiB ; Available 15.8 GiB
00:00:00.140 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.140 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.202 |I| Gpu : Backend Threading (Auto): True
00:00:00.581 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.0
00:00:00.581 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.722 |I| ModLoader QueryContentsDir: Searching mods for Title 010012101468C000
00:00:00.723 |I| ModLoader QueryContentsDir: Searching mods for Title 010012101468C000
00:00:00.738 |I| Loader Load: Loading rtld...
00:00:00.746 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.746 |I| Loader Load: Loading main...
00:00:01.064 |I| Loader PrintRoSectionInfo: main:
    Module: D:\teamcityagent\work\acc29de9bfddf8f1\bin\NX64\Lotcheck\GameFramework.nss
00:00:01.064 |I| Loader Load: Loading subsdk0...
00:00:01.128 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-12_3_1-Release
00:00:01.129 |I| Loader Load: Loading sdk...
00:00:01.239 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 12.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-12_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-12_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-12_3_1-Release
00:00:01.378 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.386 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.388 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.419 |I| Loader LoadNsos: Loading image 2 at 0x000000000d042000...
00:00:01.422 |I| Loader LoadNsos: Loading image 3 at 0x000000000d6dc000...
00:00:01.429 |I| ModLoader LoadCheats: Build ids found for title 010012101468C000:
    D3A0B917333AE58CD90645D51C4D27D51B44419C000000000000000000000000
    67C9CA1428222752F951021464A7B3597EB98FEC000000000000000000000000
    1506DE55E5A3906EE3C63E66395D2F0C80BB1F4A000000000000000000000000
    2217A4A3C1F3C883278DE72F8B008224AD252A24000000000000000000000000
00:00:01.433 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.534 |I| Loader Start: Application Loaded: Metroid Prime Remastered v1.0.0 [010012101468c000] [64-bit]
00:00:01.564 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.579 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:01.597 |E| .NET TP Worker [mvk-info] MoltenVK version 1.2.0, supporting Vulkan version 1.2.231.
00:00:01.597 |E| .NET TP Worker 	The following 83 Vulkan extensions are supported:
00:00:01.597 |E| .NET TP Worker 		VK_KHR_16bit_storage v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_8bit_storage v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_bind_memory2 v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_buffer_device_address v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_create_renderpass2 v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_dedicated_allocation v3
00:00:01.597 |E| .NET TP Worker 		VK_KHR_depth_stencil_resolve v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_descriptor_update_template v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_device_group v4
00:00:01.597 |E| .NET TP Worker 		VK_KHR_device_group_creation v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_driver_properties v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_dynamic_rendering v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_external_fence v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_external_fence_capabilities v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_external_memory v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_external_memory_capabilities v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_external_semaphore v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_external_semaphore_capabilities v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_fragment_shader_barycentric v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_get_memory_requirements2 v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_get_physical_device_properties2 v2
00:00:01.597 |E| .NET TP Worker 		VK_KHR_get_surface_capabilities2 v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_imageless_framebuffer v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_image_format_list v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_maintenance1 v2
00:00:01.597 |E| .NET TP Worker 		VK_KHR_maintenance2 v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_maintenance3 v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_multiview v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_portability_subset v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_push_descriptor v2
00:00:01.597 |E| .NET TP Worker 		VK_KHR_relaxed_block_layout v1
00:00:01.597 |E| .NET TP Worker 		VK_KHR_sampler_mirror_clamp_to_edge v3
00:00:01.598 |E| .NET TP Worker 		VK_KHR_sampler_ycbcr_conversion v14
00:00:01.598 |E| .NET TP Worker 		VK_KHR_separate_depth_stencil_layouts v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_shader_draw_parameters v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_shader_float_controls v4
00:00:01.598 |E| .NET TP Worker 		VK_KHR_shader_float16_int8 v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_shader_subgroup_extended_types v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_spirv_1_4 v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_storage_buffer_storage_class v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_surface v25
00:00:01.598 |E| .NET TP Worker 		VK_KHR_swapchain v70
00:00:01.598 |E| .NET TP Worker 		VK_KHR_swapchain_mutable_format v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_timeline_semaphore v2
00:00:01.598 |E| .NET TP Worker 		VK_KHR_uniform_buffer_standard_layout v1
00:00:01.598 |E| .NET TP Worker 		VK_KHR_variable_pointers v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_buffer_device_address v2
00:00:01.598 |E| .NET TP Worker 		VK_EXT_debug_marker v4
00:00:01.598 |E| .NET TP Worker 		VK_EXT_debug_report v10
00:00:01.598 |E| .NET TP Worker 		VK_EXT_debug_utils v2
00:00:01.598 |E| .NET TP Worker 		VK_EXT_descriptor_indexing v2
00:00:01.598 |E| .NET TP Worker 		VK_EXT_fragment_shader_interlock v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_hdr_metadata v2
00:00:01.598 |E| .NET TP Worker 		VK_EXT_host_query_reset v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_image_robustness v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_inline_uniform_block v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_memory_budget v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_metal_objects v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_metal_surface v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_post_depth_coverage v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_private_data v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_robustness2 v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_sample_locations v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_scalar_block_layout v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_separate_stencil_usage v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_shader_stencil_export v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_shader_viewport_index_layer v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_subgroup_size_control v2
00:00:01.598 |E| .NET TP Worker 		VK_EXT_swapchain_colorspace v4
00:00:01.598 |E| .NET TP Worker 		VK_EXT_texel_buffer_alignment v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_texture_compression_astc_hdr v1
00:00:01.598 |E| .NET TP Worker 		VK_EXT_vertex_attribute_divisor v3
00:00:01.598 |E| .NET TP Worker 		VK_AMD_gpu_shader_half_float v2
00:00:01.598 |E| .NET TP Worker 		VK_AMD_negative_viewport_height v1
00:00:01.598 |E| .NET TP Worker 		VK_AMD_shader_image_load_store_lod v1
00:00:01.598 |E| .NET TP Worker 		VK_AMD_shader_trinary_minmax v1
00:00:01.598 |E| .NET TP Worker 		VK_IMG_format_pvrtc v1
00:00:01.598 |E| .NET TP Worker 		VK_INTEL_shader_integer_functions2 v1
00:00:01.598 |E| .NET TP Worker 		VK_GOOGLE_display_timing v1
00:00:01.598 |E| .NET TP Worker 		VK_MVK_macos_surface v3
00:00:01.598 |E| .NET TP Worker 		VK_MVK_moltenvk v36
00:00:01.598 |E| .NET TP Worker 		VK_NV_fragment_shader_barycentric v1
00:00:01.598 |E| .NET TP Worker 		VK_NV_glsl_shader v1
00:00:01.598 |E| .NET TP Worker [mvk-info] GPU device:
00:00:01.598 |E| .NET TP Worker 		model: NVIDIA GeForce GTX 775M
00:00:01.598 |E| .NET TP Worker 		type: Discrete
00:00:01.598 |E| .NET TP Worker 		vendorID: 0x10de
00:00:01.598 |E| .NET TP Worker 		deviceID: 0x119d
00:00:01.598 |E| .NET TP Worker 		pipelineCacheUUID: 260BAD42-0C07-07D1-0000-000000000000
00:00:01.598 |E| .NET TP Worker 	supports the following Metal Versions, GPU's and Feature Sets:
00:00:01.598 |E| .NET TP Worker 		Metal Shading Language 2.4
00:00:01.598 |E| .NET TP Worker 		GPU Family Mac 1
00:00:01.598 |E| .NET TP Worker 		GPU Family Common 2
00:00:01.598 |E| .NET TP Worker 		GPU Family Common 1
00:00:01.598 |E| .NET TP Worker 		macOS GPU Family 1 v4
00:00:01.598 |E| .NET TP Worker 		macOS GPU Family 1 v3
00:00:01.598 |E| .NET TP Worker 		macOS GPU Family 1 v2
00:00:01.598 |E| .NET TP Worker 		macOS GPU Family 1 v1
00:00:01.598 |E| .NET TP Worker [mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 3 Vulkan extensions enabled:
00:00:01.598 |E| .NET TP Worker 		VK_KHR_surface v25
00:00:01.598 |E| .NET TP Worker 		VK_EXT_debug_utils v2
00:00:01.598 |E| .NET TP Worker 		VK_EXT_metal_surface v1
00:00:01.634 |E| .NET TP Worker [mvk-info] Vulkan semaphores using Metal implicit guarantees within a single queue.
00:00:01.634 |E| .NET TP Worker [mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: vkCreateDevice(): Requested feature is not available on this device.
00:00:01.637 |E| .NET TP Worker [mvk-info] Created VkDevice to run on GPU NVIDIA GeForce GTX 775M with the following 6 Vulkan extensions enabled:
00:00:01.637 |E| .NET TP Worker 		VK_KHR_portability_subset v1
00:00:01.637 |E| .NET TP Worker 		VK_KHR_push_descriptor v2
00:00:01.638 |E| .NET TP Worker 		VK_KHR_shader_float16_int8 v1
00:00:01.638 |E| .NET TP Worker 		VK_KHR_swapchain v70
00:00:01.638 |E| .NET TP Worker 		VK_EXT_descriptor_indexing v2
00:00:01.638 |E| .NET TP Worker 		VK_EXT_robustness2 v1
00:00:01.699 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorFeatureNotPresent".
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.CreateDevice(Vk api, VulkanPhysicalDevice physicalDevice, UInt32 queueFamilyIndex, UInt32 queueCount) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs:line 555
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 382
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 741
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 400
   at Ryujinx.Ava.AppHost.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 901
   at System.Threading.Thread.StartCallback()

### OS

Mac OS Monterey

### Ryujinx version

1.1.1101

### GPU

Nvidia GTX 775M 2GB

### RAM

24

**Comment by MetrosexualGarbodor** [comment]
Your system does not meet minimum requirements.

**Comment by arnold-bg** [comment]
what are the minimum requirements for macOS?
