### ISSUE TITLE
[Bug] Ryujinx crashing when opening demon slayer (was working fine earlier)

### ISSUE THREAD

**Issue by 0navyu0** [Ryujinx/Ryujinx#6065]
### Description of the issue

Encountering this error when trying to load Demon slayer 

### Reproduction steps

Just by opening the game.

### Log file

[Ryujinx_1.1.1101_2023-12-28_00-56-17.log](https://github.com/Ryujinx/Ryujinx/files/13780785/Ryujinx_1.1.1101_2023-12-28_00-56-17.log)

### OS

windows 10

### Ryujinx version

1.1.1101

### Game version

1.53

### CPU

Intel i7-11800h

### GPU

Nvidia rtx 3050ti

### RAM

16 gb

### List of applied mods

No mods applied

### Additional context?

Earlier it used to work perfect ,,but recently i tried to open it ,,its throwing this error again and again ,, i downloaded the game file again if there was an error in it just in case but it still didnt worked i reinstalled ryujinx but still no effect but other games are working fine. Kindly help

**Comment by AcK77** [comment]
The issue seems related to DLC files, more investigation is needed to know if it’s a Ryujinx issue btw

**Comment by 0navyu0** [comment]
> The issue seems related to DLC files, more investigation is needed to know if it’s a Ryujinx issue btw
mmmmmm...... thanks for ur insight ,, i will try to check the file again ,, the thing i cant get is earlier it used to work perfectly and i just tried to run it today its throwing this exception ,, i just cant find what happened in the gap of 2 days
