### ISSUE TITLE
[Bug] Ryujinx keeps disconnecting controllers, macOS

### ISSUE THREAD

**Issue by pleasejustgo** [Ryujinx/Ryujinx#6066]
### Description of the issue

Im using a Nintendo Pro switch controller and it's a crap shoot if it'll work on startup, or more than 5 minutes. When it does work for more than 5 minutes, it'll disconnect if you change spaces. Controller support is a joke and utterly ridiculous. Not only that, there is a 200+MB log file in the logs folder. duuhh. I wont' be posting that one obviously.

### Reproduction steps

Plug in controller, watch as sh*t hits the fan.

### Log file

[Ryujinx_1.1.1100_2023-12-27_00-47-27.log](https://github.com/Ryujinx/Ryujinx/files/13781934/Ryujinx_1.1.1100_2023-12-27_00-47-27.log)

### OS

macOS ventura 13.5.2

### Ryujinx version

1.1.1100

### Game version

latest version

### CPU

M1 Max

### GPU

M1 Max

### RAM

32

### List of applied mods

none

**Comment by MutantAura** [comment]
It is very possible to report issues without being rude and hostile. If you wish to perhaps rephrase your description with a little more detail, and a little less angst, that would be helpful.
