### ISSUE TITLE
[错误]ryujinx starts full screen handle action

### ISSUE THREAD

**Issue by LushanCloud** [Ryujinx/Ryujinx#6069]
### Description of the issue

When using the switchpro controller to open the ryujinx full-screen game, the controller will lose connection. It will only work if you restart the game.

### Reproduction steps

Use pro controller to start full screen games

### Log file

[Uploading Ryujinx_1.1.1101_2023-12-28_09-49-12.log…]()

### OS

macOS

### Ryujinx version

1.1.1101

### Game version

1.0.1

### CPU

m2

### GPU

m2

### RAM

8g

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
