### ISSUE TITLE
[Feature Request] Autoscan/Apply Updates/DLC

### ISSUE THREAD

**Issue by Androxilogin** [Ryujinx/Ryujinx#6074]
### Overview

An option to autoscan designated folders for DLC/Title updates for all titles.

### Smaller details

Something in the options or via context menu, perhaps. Rather than on a game-by-game basis, an overall auto-picker with the game-by-game basis still intact for those who'd like to stay on previous updates or disable DLC.

### Nature of request

It'd be nice!

### Why would this feature be useful?

Time saver.

**Comment by Androxilogin** [comment]
Looks to be.

**Comment by sakuka47** [comment]
I think it's a bad idea, as the current maj selection (especially with Avalonia) is just fine as it is.

**Comment by Androxilogin** [comment]
I don't understand how more options could be a bad thing, but alright. Not sure what maj selection or Avalonia is.

**Comment by MutantAura** [comment]
Duplicate of #4776
