### ISSUE TITLE
[Bug] [Linux] [Regression] Gunvein crash at the beginning 

### ISSUE THREAD

**Issue by ghost** [Ryujinx/Ryujinx#6075]
### Description of the issue

Gunvein crash at the beginning, then Ryujinx closes
The strange thing is that sometimes it starts (1 time out of ten) without changing anything in the settings

### Reproduction steps

You hear the sound at the beginning then Ryujinx closes

### Log file

00:00:00.045 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.050 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.050 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.051 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.051 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.052 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.052 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1F82
00:00:00.053 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.053 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.053 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.054 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.055 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.055 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.055 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.055 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.055 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.055 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.055 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.055 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.055 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.055 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.055 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.056 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.056 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.056 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.056 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.058 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.058 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1102
00:00:00.067 |N| Application Print: Operating System: Ubuntu 22.04.3 LTS (X64)
00:00:00.067 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i5-12400F ; 12 logical
00:00:00.069 |N| Application Print: RAM: Total 15.5 GiB ; Available 14 GiB
00:00:00.071 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.071 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.068 |I| Gpu : Backend Threading (Auto): True
00:00:00.179 |N| Application LoadApplication: Using Firmware Version: 17.0.1
00:00:00.179 |I| Application LoadApplication: Loading as NSP.
00:00:00.194 |I| ModLoader QueryContentsDir: Searching mods for Title 0100D0501A954000
00:00:00.195 |I| ModLoader QueryContentsDir: Searching mods for Title 0100D0501A954000
00:00:00.197 |I| Loader Load: Loading rtld...
00:00:00.205 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.205 |I| Loader Load: Loading main...
00:00:00.313 |I| Loader PrintRoSectionInfo: main:
    Module: C:\Users\pulst\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\gunvein_887512F\gunvein\Default\Scripts\llvm-switch\Switchsolution\NX64\Release\gunvein.nss
    SDK Libraries: SDK MW+YoYoGames+GameMaker_Studio_2-2023.1.1.81-Release
                   SDK MW+Nintendo+NintendoSDK_libcurl-14_3_0-Release
                   SDK MW+Nintendo+NintendoSDK_OpenSSL_For_NintendoSDK-14_3_0-Release
00:00:00.313 |I| Loader Load: Loading subsdk0...
00:00:00.424 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: opengl
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_OpenGL-14_3_0-Release
00:00:00.424 |I| Loader Load: Loading subsdk1...
00:00:00.450 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-14_3_0-Release
00:00:00.450 |I| Loader Load: Loading sdk...
00:00:00.505 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 14.3.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-14_3_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-14_3_0-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-14_3_0-Release
00:00:00.573 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.928 |I| Ptc Load: Loaded Translation Cache (size: 29604370 bytes, translated functions: 19199).
00:00:00.936 |I| Ptc Load: Loaded Profiling Info (size: 64608 bytes, profiled functions: 19199).
00:00:00.939 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.940 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.951 |I| Loader LoadNsos: Loading image 2 at 0x000000000a164000...
00:00:00.960 |I| Loader LoadNsos: Loading image 3 at 0x000000000bb3a000...
00:00:00.962 |I| Loader LoadNsos: Loading image 4 at 0x000000000c1d4000...
00:00:00.969 |I| ModLoader LoadCheats: Build ids found for title 0100D0501A954000:
    8E405C8A464734D8F71C2C1BE2DAC518010E86FB000000000000000000000000
    1993CE76E091494D93C7D43347297C092F4C1375000000000000000000000000
    EC3B393C492C68E1015C38ADAE238378F92F526E000000000000000000000000
    C781DD63DAF0DDCDB9975DA50A198F932A485719000000000000000000000000
    2AEF2CFFB104EE7C9E212FD2F4C731E9D1E5F2C4000000000000000000000000
00:00:00.971 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.991 |I| Loader Start: Application Loaded: Gunvein v1.0.0 [0100d0501a954000] [64-bit]
00:00:00.996 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.038 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.227 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1650 (Vulkan v1.3.242, Driver v535.129.3.0)
00:00:01.234 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.238 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:01.567 |I| HLE.GuestThread.42 Ptc LoadTranslations: 19199 translated functions loaded
00:00:01.642 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.648 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.649 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.649 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:01.655 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:02.796 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:02.801 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:02.803 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:02.824 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:02.899 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:02.899 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:02.900 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:02.900 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:02.900 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:02.901 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:02.933 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:02.939 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:02.939 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72286636499877888}
00:00:02.941 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:02.946 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:02.946 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:02.946 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:02.947 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.947 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.951 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:02.952 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:02.954 |I| HLE.OsThread.43 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish
00:00:02.959 |S| HLE.OsThread.43 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:05.334 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:05.336 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Handheld,Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8
00:00:05.337 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:05.339 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:05.340 |S| HLE.OsThread.43 ServiceIrs ActivateIrsensorWithFunctionLevel: Stubbed. {appletResourceUserId: 3 ; packedFunctionLevel: 1}
00:00:06.194 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:06.198 |I| HLE.OsThread.7 AudioRenderer ReleaseSessionId: Unregistered output (0)
00:00:06.198 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:06.202 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 800
00:00:06.307 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:06.308 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:06.310 |S| HLE.OsThread.10 ServiceNv DumpGraphicsMemoryInfo: Stubbed. 
00:00:06.311 |S| HLE.OsThread.10 ServiceNv GetStatus: Stubbed. 
00:00:06.320 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:06.320 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:06.320 |S| HLE.OsThread.43 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:06.873 |I| HLE.GuestThread.42 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Gunvein, PID: 119
   0x000000000ad13174	subsdk0:0xbaf174	
   0x000000000acee76c	subsdk0:0xb8a76c	
   0x000000000ad76330	subsdk0:0xc12330	
   0x000000000ad76504	subsdk0:0xc12504	
   0x000000000ad76bd8	subsdk0:0xc12bd8	
   0x000000000ac96f10	subsdk0:0xb32f10	
   0x000000000ac975f0	subsdk0:0xb335f0	
   0x000000000aca94c0	subsdk0:0xb454c0	
   0x000000000aca91a4	subsdk0:0xb451a4	
   0x000000000ad3b180	subsdk0:0xbd7180	
   0x000000000ad46d78	subsdk0:0xbe2d78	
   0x000000000a97910c	subsdk0:0x81510c	
   0x000000000aa97ed4	subsdk0:0x933ed4	
   0x000000000aa79c6c	subsdk0:0x915c6c	
   0x000000000aa7ca58	subsdk0:0x918a58	
   0x000000000aa7c4dc	subsdk0:0x9184dc	
   0x0000000008e6d3d8	main:0x9693d8	
   0x0000000008e6d74c	main:0x96974c	
   0x0000000008e6c500	main:0x968500	
   0x0000000008e69184	main:0x965184	
   0x0000000008e692a8	main:0x9652a8	
   0x0000000008f2d784	main:0xa29784	
   0x0000000008b5a634	main:0x656634	
   0x0000000008e80c08	main:0x97cc08	
   0x0000000008e80c3c	main:0x97cc3c	
   0x0000000008ebe440	main:0x9ba440	
   0x0000000008ebdf48	main:0x9b9f48	
   0x0000000008ebe17c	main:0x9ba17c	
   0x0000000008f9a764	main:0xa96764	
   0x0000000008f9e1d0	main:0xa9a1d0	
   0x0000000008f9e384	main:0xa9a384	
   0x0000000008f9f2e8	main:0xa9b2e8	
   0x0000000008fd4b24	main:0xad0b24	
   0x0000000008fd4cf4	main:0xad0cf4	
   0x0000000008fd51c4	main:0xad11c4	
   0x0000000009138228	main:0xc34228	nnMain:0x0258
   0x000000000c2ce414	sdk:0xfa414	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000085000d4	rtld:0x00d4	

00:00:06.875 |I| HLE.GuestThread.42 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x000000655c5d8020
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000001
	X[03]:	0x00000001003fcba0
	X[04]:	0x0000000000000018
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x000000000adf4d00 (subsdk0:0xc90d00)	=> 
	X[09]:	0x0000000000000040
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000004
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000001
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000000bafdbc8
	X[17]:	0x000000000c75d790 (sdk:0x589790)	=> memset
	X[18]:	0x00000066121fd718
	X[19]:	0x000000655c5d8020
	X[20]:	0x000000655f5c5070
	X[21]:	0x000000655c5fe340
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000003
	X[25]:	0x0000000000000000
	X[26]:	0x00000000000000e8
	X[27]:	0x0000000000000003
	X[28]:	0x00000049ef5067a0 (SP:-0x0030)
	FP:	0x00000049ef506fc0 (SP:-0x0850)
	LR:	0x000000000ad4ff2c (subsdk0:0xbebf2c)	=> 
	SP:	0x00000049ef506770 (SP)
	PC:	0x000000000adf4d00 (subsdk0:0xc90d00)	=> 

00:00:06.875 |E| HLE.GuestThread.42 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x000000684A49B000.
00:00:06.900 |E| HLE.GuestThread.42 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212

### OS

Ubuntu 22.04.3 LTS (X64)

### Ryujinx version

1.1.1102

### Game version

1.0.0

### CPU

12th Gen Intel(R) Core(TM) i5-12400F

### GPU

NVIDIA GeForce GTX 1650

### RAM

16 GB

**Comment by Predaisonline** [comment]
After a bit of testing, I found that the game runs on Ryujinx version 1.1.1086 and earlier. From 1.1.1087 to the latest 1.1.1115 the problem described above persists. Hope it can be of help in resolving.

**Comment by Predaisonline** [comment]
After the last update (1.1.1164) at the first boot I noticed that I had disabled the joypad configuration. By pure chance I found that with the joypad configuration disabled Gunvein always starts. If I launch the game with the joypad enabled, I still encounter the problem described above.

**Comment by Predaisonline** [comment]
After the latest update 1.1.1213, the trick of disabling the joypad to launch the game no longer works. Now the game doesn't start at all.

**Comment by prd-ryu** [comment]
They have fixed with this update: https://github.com/Ryujinx/Ryujinx/pull/6687 
now works
