### ISSUE TITLE
[Bug] Games freeze for seconds at a time every few seconds after driver updates

### ISSUE THREAD

**Issue by Cole478** [Ryujinx/Ryujinx#6080]
### Description of the issue

I am playing Pikmin 4 and the game has started freezing for seconds at a time every few seconds after a driver update.

Whenever a freeze happens, this message occurs in the console:
|E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.

### Reproduction steps

The issue will usually happen within 30 seconds of loading a save game, though can occur on the title screen. I am currently playing through area 4. Usually occurs during my character's movement or camera movement.

### Log file

[Ryujinx_1.1.1102_2024-01-02_12-00-44.log](https://github.com/Ryujinx/Ryujinx/files/13812916/Ryujinx_1.1.1102_2024-01-02_12-00-44.log)

### OS

Windows 10

### Ryujinx version

1.1.1102

### Game version

1.01

### CPU

Ryzen 7 7800X3D

### GPU

RX 7900 XTX

### RAM

32 GB

**Comment by TSRBerry** [comment]
It sounds like you are rebuilding your shader cache, since the old one was invalidated after the driver update.
