### ISSUE TITLE
[Bug] Controller does not connect/ get picked up by Ryujinx

### ISSUE THREAD

**Issue by von2oppy** [Ryujinx/Ryujinx#6084]
### Description of the issue

My Xbox Series Controller does not get picked up by Ryujinx most of the time, so I have to reload the emulator and hope it works again. I apply inut settings and it still does not get picked up by Ryujinx. My Mac recognizes the controller, however Ryujinx does not. 

### Reproduction steps

Connect Controller, Input Mappings, Apply and Save. 

### Log file

[Ryujinx_1.1.1102_2024-01-02_19-30-37.log](https://github.com/Ryujinx/Ryujinx/files/13815848/Ryujinx_1.1.1102_2024-01-02_19-30-37.log)
[Ryujinx_1.1.1102_2024-01-02_22-45-28.log](https://github.com/Ryujinx/Ryujinx/files/13815849/Ryujinx_1.1.1102_2024-01-02_22-45-28.log)
[Ryujinx_1.1.1102_2024-01-02_23-17-06.log](https://github.com/Ryujinx/Ryujinx/files/13815850/Ryujinx_1.1.1102_2024-01-02_23-17-06.log)

### OS

Mac OS Sonoma 14.2.1

### Ryujinx version

1.1.1102

### Game version

N/A

### CPU

M2

### GPU

M2

### RAM

8GB

**Comment by ahrib** [comment]
I experience this after updating to the latest version also.

In my case I have 1 x xbox series controller and 1 x Xbox Elite Wireless Controller Series 2. Only one controller is recognised in the latest version. No issues with previous version

v 1.1.1104 broken
v 1.1.1100 no problems, all OK

**Comment by von2oppy** [comment]
> I experience this after updating to the latest version also.
> 
> 
> 
> In my case I have 1 x xbox series controller and 1 x Xbox Elite Wireless Controller Series 2. Only one controller is recognised in the latest version. No issues with previous version
> 
> 
> 
> v 1.1.1104 broken
> 
> v 1.1.1100 no problems, all OK

I have a Xbox One X controller and an Xbox Series Controller and I believe I had this problem with 1.1.1100 as well. I wonder if an older version would solve this issue.

**Comment by siegmund-heiss-ich** [comment]
Did you try restarting ur mac?
It solved the issue everytime for me!

**Comment by von2oppy** [comment]
> Did you try restarting ur mac?
> 
> It solved the issue everytime for me!

Going to do it now

**Comment by von2oppy** [comment]
> Did you try restarting ur mac?
> 
> It solved the issue everytime for me!

It worked the first time but after it happened again and restarting doesn't seem to work

**Comment by ahrib** [comment]
Restarting Mac did not fix it for me. Using an older version did

**Comment by von2oppy** [comment]
> Restarting Mac did not fix it for me. Using an older version did

Which version did you use?

**Comment by siegmund-heiss-ich** [comment]
> > Restarting Mac did not fix it for me. Using an older version did
> 
> Which version did you use?

i am on the latest one

**Comment by von2oppy** [comment]
> > > Restarting Mac did not fix it for me. Using an older version did
> > 
> > Which version did you use?
> 
> i am on the latest one

I was referring to @ahrib

**Comment by ahrib** [comment]
> > Restarting Mac did not fix it for me. Using an older version did
> 
> Which version did you use?

v 1.1.1104 broken

v 1.1.1100 no problems, all OK

**Comment by Shahil-Ayato** [comment]
This should be posted on our discord as a support inquiry, this is an issue with your system and/or Ryujinx configuration, it is not an issue with the emulator itself.
