### ISSUE TITLE
[Bug] Ryujinx 1.1.1102 quit unexpectedly

### ISSUE THREAD

**Issue by maryzoon** [Ryujinx/Ryujinx#6085]
### Description of the issue

Ryujinx quit unexpectedly and random, It's only been a few minutes since I last opened the game then ryujinx suddenly crashed

### Reproduction steps

just open the game and wait for a few minutes the ryujinx got crashed

### Log file

[Ryujinx_1.1.1102_2024-01-03_13-45-22.log](https://github.com/Ryujinx/Ryujinx/files/13816424/Ryujinx_1.1.1102_2024-01-03_13-45-22.log)

### OS

macOS 14.2.1

### Ryujinx version

1.1.1102

### Game version

1.0

### CPU

8

### RAM

8

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
