### ISSUE TITLE
[Bug] LoveR Kiss - 5 FPS

### ISSUE THREAD

**Issue by bobhob314** [Ryujinx/Ryujinx#6086]
### Description of the issue

Is anyone else also getting really slow speeds for LoveR Kiss? Since I can even play Persona 5 on RyuJinx at 30FPS, I find this strange.

### Reproduction steps

Run LoverR Kiss.
I tried both Vulkan and OpenGL. It's at 720p right now.

### Log file

00:00:00.157 |I| Configuration LogValueChange: ResScale set to: 3
00:00:00.175 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.175 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.177 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.179 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.180 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.182 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.183 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.185 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.185 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.188 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.204 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.204 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.204 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.204 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.204 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.204 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.204 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.204 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.204 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.206 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.206 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.209 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.209 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.209 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.209 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.254 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.255 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1098
00:00:00.263 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.263 |N| Application Print: CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz ; 8 logical
00:00:00.267 |N| Application Print: RAM: Total 23.8 GiB ; Available 7.7 GiB
00:00:00.272 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.273 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:03.762 |I| Application FixExtraDataInSpaceId: Fixed extra data for save data 0x3 in the User save data space
00:00:00.061 |I| Gpu : Backend Threading (Auto): True
00:00:00.502 |N| Application LoadApplication: Using Firmware Version: 16.0.3
00:00:00.502 |I| Application LoadApplication: Loading as NSP.
00:00:00.522 |I| Application AddAocItem: Found AddOnContent with TitleId 01007250089F9033
00:00:00.523 |I| Application AddAocItem: Found AddOnContent with TitleId 01007250089F9073
00:00:00.523 |I| Application AddAocItem: Found AddOnContent with TitleId 01007250089F9072
00:00:00.523 |I| Application AddAocItem: Found AddOnContent with TitleId 01007250089F9075
00:00:00.524 |I| Application AddAocItem: Found AddOnContent with TitleId 01007250089F9076
00:00:00.555 |I| ModLoader QueryContentsDir: Searching mods for Title 01007250089F8000
00:00:00.556 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9033
00:00:00.556 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9072
00:00:00.556 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9073
00:00:00.556 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9075
00:00:00.556 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9076
00:00:00.558 |I| ModLoader QueryContentsDir: Searching mods for Title 01007250089F8000
00:00:00.558 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9033
00:00:00.558 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9072
00:00:00.558 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9073
00:00:00.558 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9075
00:00:00.558 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007250089F9076
00:00:00.563 |I| Loader Load: Loading rtld...
00:00:00.573 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.573 |I| Loader Load: Loading main...
00:00:00.678 |I| Loader PrintRoSectionInfo: main:
    Module: C:\lover_kiss\program\elf\lover_nx_rom.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_gfx-8_2_1-Release
00:00:00.678 |I| Loader Load: Loading subsdk0...
00:00:00.803 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: glslc
00:00:00.803 |I| Loader Load: Loading sdk...
00:00:00.968 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 8.2.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-8_2_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-8_2_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-8_2_1-Release
00:00:01.109 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.124 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.126 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.136 |I| Loader LoadNsos: Loading image 2 at 0x0000000009b52000...
00:00:01.141 |I| Loader LoadNsos: Loading image 3 at 0x000000000a496000...
00:00:01.151 |I| ModLoader LoadCheats: Build ids found for title 01007250089F8000:
    285183CAC95179371CC22CEC3723F882E1589659000000000000000000000000
    8529F6BD4D1AC6882D5693DA2CE578A8212EF07C000000000000000000000000
    C8A3CC0B1D1858330A881C0C2FC879409C4ECDAE000000000000000000000000
    5FD4F531C1195E9E5510C9E73F22CD39612839F8000000000000000000000000
00:00:01.154 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.406 |I| Loader Start: Application Loaded: LoveR Kiss v1.0.3 [01007250089f8000] [64-bit]
00:00:01.419 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.554 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.690 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2 (4.6.0 NVIDIA 461.09)
00:00:01.715 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.731 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.468 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.591 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.597 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.602 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.666 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:05.110 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:05.344 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.871 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:06.091 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:06.202 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.212 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.213 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.215 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:06.225 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.227 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:06.233 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:06.258 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:08.443 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72183282105548800}
00:00:08.464 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:08.502 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:13.300 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:13.307 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Handheld,Player1
00:00:13.349 |S| HLE.OsThread.43 ServiceAm LockExit: Stubbed. 
00:00:13.351 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:13.352 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:13.399 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:13.407 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:13.436 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:13.998 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:13.999 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:14.001 |S| HLE.OsThread.9 ServiceHid EnableSixAxisSensorFusion: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 0 ; _sixAxisSensorFusionEnabled: True}
00:00:14.008 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:14.023 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:14.343 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:14.344 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:14.344 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:14.352 |S| HLE.OsThread.43 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 114}
00:00:14.363 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007250089F9072
00:00:14.369 |S| HLE.OsThread.43 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 114}
00:00:14.376 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007250089F9072
00:00:14.647 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:14.677 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:14.677 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:14.677 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:14.889 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:15.237 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:15.237 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:15.238 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:15.450 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:15.586 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:15.586 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:15.586 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:15.744 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:15.744 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:15.744 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.053 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.053 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:16.053 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.346 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.346 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:16.346 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.621 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.621 |S| HLE.OsThread.43 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 115}
00:00:16.621 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:16.621 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.622 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007250089F9073
00:00:16.630 |S| HLE.OsThread.43 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 115}
00:00:16.631 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007250089F9073
00:00:16.885 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.885 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController}
00:00:16.885 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; 

### OS

Windows 10

### Ryujinx version

1.1.1098

### Game version

1.0.3

### GPU

1080

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
