### ISSUE TITLE
[Bug] AMIIBO API - amiibo.json not being created. 1.1.1102+

### ISSUE THREAD

**Issue by hakushiii** [Ryujinx/Ryujinx#6094]
### Description of the issue

From the amiibo reports I think there was a mishap on 1.1.1101 to 1.1.1102. I tried it too and 1.1.1102+ does not generate the amiibo.json file but 1.1.1101- does generate the file. I think the bug went unseen as most of us have the json file cached already, but is causing to newcomers.

![Screenshot 2024-01-06 at 19 59 00](https://github.com/Ryujinx/Ryujinx/assets/58656012/4b2eaec9-276a-4b8a-9792-7aa8cc15f1d0)

![Screenshot 2024-01-06 at 20 02 01](https://github.com/Ryujinx/Ryujinx/assets/58656012/abaa0dfc-7eae-41e5-9991-11c27526ed8f)

### Reproduction steps

1. Run a game that has a feature than scans an amiibo
2. Scan Amiibo
- 1.1.1101 -> will proceed normally
- 11.1102 -> will throw an error that connection is not found

### Log file

Not logged but here:

[Ryujinx_1.1.1101_2024-01-06_20-00-13.log](https://github.com/Ryujinx/Ryujinx/files/13849626/Ryujinx_1.1.1101_2024-01-06_20-00-13.log)
[Ryujinx_1.1.1102_2024-01-06_19-56-40.log](https://github.com/Ryujinx/Ryujinx/files/13849627/Ryujinx_1.1.1102_2024-01-06_19-56-40.log)

### OS

MacOS 14.2.1

### Ryujinx version

1.1.1101 -> 1.1.1102

**Comment by Houndoom96** [comment]
I am on version 1.1.1104 for Windows and get the same error. I downloaded the json file from[https://amiibo.ryujinx.org/]( https://amiibo.ryujinx.org/) and placed it in the amiibo folder, it worked. But it seems like ryujinx cannot downloaded

**Comment by gdkchan** [comment]
Can you take a look @AxesP @AcK77 ?

**Comment by LazerDickMcCheese** [comment]
This bug still occurs, v1.1.1297. Manually installing the json works as intended, easy fix
