### ISSUE TITLE
[Bug] Emulator crashing when starting Pokemon Scarlet

### ISSUE THREAD

**Issue by ZimSan** [Ryujinx/Ryujinx#6096]
### Description of the issue

Anytime I try running Pokemon Scarlet on Ryujinx it crashes the emulator before the title screen comes up. It doesn't matter which version, if it's with or without DLC it crashes. It functions on other emulator but not on Ryujinx for me.

### Reproduction steps

1. Get Pokemon Scarlet Iso
2. Start the game on Ryujinx

### Log file

00:00:00.038 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.045 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.045 |I| Configuration LogValueChange: MaxAnisotropy set to: 8
00:00:00.046 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.047 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.048 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.048 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684
00:00:00.049 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.050 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.050 |I| Configuration LogValueChange: ScalingFilterLevel set to: 98
00:00:00.051 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.057 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.057 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.057 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.057 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.057 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.057 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.057 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.057 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.057 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.058 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.058 |I| Configuration LogValueChange: AudioVolume set to: 0,15
00:00:00.060 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.060 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.060 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.060 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.062 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.062 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1104
00:00:00.066 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.066 |N| Application Print: CPU: AMD Ryzen 9 5900X 12-Core Processor ; 24 logical
00:00:00.068 |N| Application Print: RAM: Total 63.9 GiB ; Available 48.2 GiB
00:00:00.069 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.070 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.062 |I| Gpu : Backend Threading (On): True
00:00:00.272 |N| Application LoadApplication: Using Firmware Version: 17.0.1
00:00:00.273 |I| Application LoadApplication: Loading as NSP.
00:00:00.281 |I| Application AddAocItem: Found AddOnContent with TitleId 0100A3D008C5D001
00:00:00.288 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A3D008C5C000
00:00:00.292 |I| ModLoader AddModsFromDirectory: Found mod '' [C]
00:00:00.292 |I| ModLoader AddModsFromDirectory: Found mod '' [C]
00:00:00.292 |I| ModLoader AddModsFromDirectory: Found mod '' [C]
00:00:00.292 |I| ModLoader AddModsFromDirectory: Found mod 'Pokemovement+' [R]
00:00:00.293 |I| ModLoader AddModsFromDirectory: Found mod 'remove_sheeran' [R]
00:00:00.293 |I| ModLoader AddModsFromDirectory: Found mod '' [C]
00:00:00.293 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100A3D008C5D001
00:00:00.293 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A3D008C5C000
00:00:00.293 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100A3D008C5D001
00:00:00.295 |I| Loader Load: Loading rtld...
00:00:00.301 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.301 |I| Loader Load: Loading main...
00:00:00.523 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\titan\v_1_0_0\rom_build\programs\prog\app\msvc\main_app\NX64\Release\main_app.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-13_3_5-Release
                   SDK MW+Nintendo+NintendoSDK_gRPC_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_OpenSSL_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_NPLN-1_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_Google_APIs_For_NPLN-1_4_1-Release
                   SDK MW+Nintendo+PiaCommon-6_20_1
                   SDK MW+Nintendo+Pia-6_20_1
                   SDK MW+Nintendo+PiaLocal-6_20_1
                   SDK MW+Nintendo+PiaLan-6_20_1
                   SDK MW+Nintendo+PiaReckoning-6_20_1
                   SDK MW+Nintendo+PiaSession-6_20_1
                   SDK MW+Nintendo+PiaTransport-6_20_1
                   SDK MW+Nintendo+PiaNpln-6_20_1
                   SDK MW+NINTENDO+nlib_LZ4-22_0201
                   SDK MW+Nintendo+NintendoWare_Font-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_G3d-13_3_5-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-13_3_5-Release
                   SDK MW+Microsoft+Havok_AI-2021_1
00:00:00.523 |I| Loader Load: Loading subsdk0...
00:00:00.542 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-13_3_5-Release
00:00:00.542 |I| Loader Load: Loading sdk...
00:00:00.584 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 13.3.5
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_5-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_5-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_5-Release
00:00:00.679 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.687 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.688 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.714 |I| Loader LoadNsos: Loading image 2 at 0x000000000c8f9000...
00:00:00.716 |I| Loader LoadNsos: Loading image 3 at 0x000000000cf93000...
00:00:00.724 |I| ModLoader LoadCheats: Build ids found for title 0100A3D008C5C000:
    567CDD4C5251494C5CD70822E3CCC740C190C2B2000000000000000000000000
    CA44E7DD62E61A2A4E8889B3319AE173375770FD000000000000000000000000
    D0F13015E5BADF2243D60A2BC9B978DDDBA80608000000000000000000000000
    3644A6760469451CABC99F00C540ACC2A64AEE41000000000000000000000000
00:00:00.726 |W| ModLoader LoadCheats: Skipping cheat '<60FPS EMU v3.0.0 Cheat>' because no executable matches its BuildId C01884F294C053C4 (check if the game title and version are correct)
00:00:00.726 |W| ModLoader LoadCheats: Skipping cheat '<60FPS v3.0.0 Cheat>' because no executable matches its BuildId C01884F294C053C4 (check if the game title and version are correct)
00:00:00.726 |W| ModLoader LoadCheats: Skipping cheat '<Improved-Camera v3.0.0 Cheat>' because no executable matches its BuildId C01884F294C053C4 (check if the game title and version are correct)
00:00:00.726 |W| ModLoader LoadCheats: Skipping cheat '<Restore code Cheat>' because no executable matches its BuildId C01884F294C053C4 (check if the game title and version are correct)
00:00:00.729 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Title 0100A3D008C5C000
00:00:00.734 |I| ModLoader ApplyRomFsMods: Replaced 3 file(s) over 2 mod(s). Processing base storage...
00:00:00.736 |I| ModLoader ApplyRomFsMods: Building new RomFS...
00:00:00.738 |I| ModLoader ApplyRomFsMods: Using modded RomFS
00:00:00.739 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.782 |I| Loader Start: Application Loaded: Pokémon Karmesin v1.0.0 [0100a3d008c5c000] [64-bit]
00:00:00.789 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:00.798 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.168 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 4090 (Vulkan v1.3.260, Driver v546.33.0.0)
00:00:01.176 |I| GPU.MainThread Gpu LoadShaders: Loading 502 shaders from the cache...
00:00:02.265 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.789 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.891 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.895 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.902 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.990 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:04.800 |W| HLE.GuestThread.42 KernelSvc : MapPhysicalMemory() = LimitReached
00:00:04.979 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:04.993 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:05.000 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:05.002 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:05.418 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.419 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:05.478 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:05.604 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:05.651 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.657 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.657 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.901 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:05.902 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:05.903 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:05.904 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:05.905 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:05.905 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:05.913 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:08.145 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:08.146 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV10
00:00:08.158 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:08.159 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:08.186 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:08.208 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:08.978 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:09.290 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:09.706 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:09.706 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:09.709 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:09.710 |S| HLE.OsThread.9 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -4285739507224936448}
00:00:09.710 |S| HLE.OsThread.9 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -4285739301066506240}
00:00:10.384 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72237707933630464}
00:00:10.389 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:10.390 |S| HLE.OsThread.43 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:10.713 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:13.944 |I| HLE.GuestThread.51 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Pokémon Karmesin, PID: 119
   0x0000000008f1c0d8
   0x0000000008f1be9c
   0x00000000091afb58
   0x00000000096b8dd4
   0x000000000d30ae08
   0x000000000d311424
   0x0000000000000000

00:00:13.946 |I| HLE.GuestThread.51 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000049dbf91c90 (SP:-0xffffffffffffff80)
	X[02]:	0x0000000000000008
	X[03]:	0x00000015c1b1f420
	X[04]:	0x0000000000000000
	X[05]:	0x8e00486804182808
	X[06]:	0x0000040600010200
	X[07]:	0x0000000000000000
	X[08]:	0x00000015c552b240
	X[09]:	0x000000000000ffff
	X[10]:	0x0000000000000015
	X[11]:	0x0000000000000000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x00000000000000b0
	X[16]:	0x000000000c7ffd20
	X[17]:	0x000000000d3050d0
	X[18]:	0x0000000000000580
	X[19]:	0x00000049dbf91da0 (SP:-0x0090)
	X[20]:	0x00000015c552b240
	X[21]:	0x00000015c4b4d1a0
	X[22]:	0x00000015c4b4d1a0
	X[23]:	0x000000000c85c910
	X[24]:	0x000000000c85c908
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x00000049dbf91d70 (SP:-0x0060)
	LR:	0x0000000008f1d550
	SP:	0x00000049dbf91d10 (SP)
	PC:	0x000000000ac74ff0

00:00:13.946 |E| HLE.GuestThread.51 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:13.987 |E| HLE.GuestThread.51 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1104

### Game version

3.0.0

### CPU

AMD Ryzen 9 5900X 12-Core

### GPU

NVidia Geforce 4090

### RAM

64

**Comment by MetrosexualGarbodor** [comment]
This is likely a mod issue. In the future, refer to Discord or the FAQ for support.
