### ISSUE TITLE
[Bug] Pokemon Scarlet crashes the whole emulator when attempting to go down the Other Items menu

### ISSUE THREAD

**Issue by Aishterus** [Ryujinx/Ryujinx#6097]
### Description of the issue

**Context**:
Hello. I've played this game for a sizable amount of time and even used cheat mods without any real issues, until I started the DLC and caught a few Pokemon. I only really used the 100% fast capture cheat on, and it even worked fine on the DLC for the first half hour. The other mods I left on were 4x shiny chance (didn't seem to function as I had yet to encounter one) and a 30 FPS + speed mod that seemed to have just made my game slower in hindsight. 

**Issue:**
However, the first crash happened when I tried to access the special item to evolve my Applin.
This crash seems to have reset the entire game where I noticed my 100% capture mod doesn't work at all anymore, and the game seems to run at its original framerate since I didn't have the FPS mod on. Resetting these mods and restarting the game still renders the mods useless, so I can't use them anymore. That's fine and doesn't hinder playability.

But the repeated crashes on the Other Items menu does. I can't seem to figure out the problem.

### Reproduction steps

This is only specifically after accessing the Other Items menu, the other tabs in Bag seem towork fine. My guess is the new apple items in DLC might cause some issue.

### Log file

[Ryujinx_1.1.1104_2024-01-08_23-40-46.log](https://github.com/Ryujinx/Ryujinx/files/13863787/Ryujinx_1.1.1104_2024-01-08_23-40-46.log)
[Ryujinx_1.1.1104_2024-01-08_23-56-40.log](https://github.com/Ryujinx/Ryujinx/files/13863788/Ryujinx_1.1.1104_2024-01-08_23-56-40.log)

### OS

Windows 11

### Ryujinx version

17.0.1

### Game version

3.0.0

### CPU

i7-6700HQ

### GPU

Intel(R) HD Graphics 530

### RAM

16GB

### List of applied mods

[C01884F294C053C4.txt](https://github.com/Ryujinx/Ryujinx/files/13863856/C01884F294C053C4.txt)
[enabled.txt](https://github.com/Ryujinx/Ryujinx/files/13863857/enabled.txt)

Left on at the time of the first crash were: 
Restore code
100% Fast capture on(v3.0.0)
4x Shiny Chance
30 FPS (V3.0.0)
Game Speed (L3 + ^/v Speed Up/Down)

### Additional context?

No other crashes were encountered before this. I did have Vsync off and undocked since that's the only thing that made my game playable.

**Comment by MetrosexualGarbodor** [comment]
This is likely a mod issue. In the future, refer to Discord or the FAQ for support.
