### ISSUE TITLE
[Bug] Metroid Prime Remastered crashes when running off a SMB share

### ISSUE THREAD

**Issue by Mav3r1ckHL** [Ryujinx/Ryujinx#6099]
### Description of the issue

Moved most of my backups to a NAS to run my games and provided SMB shares to my Windows boxes.  I noticed that Metroid Prime Remastered crashes after pressing A at the intro movie screen which would lead to the menu to load the game.  This works fine when ran locally.

### Reproduction steps

Assumptions:
- You have the game
- Ryuujinx was configured with the proper SMB path to the backup

1. Run the emulator
2. Double click on Metroid Prime Remastered
3. Press A during the Intro movie screen

What happens: Emulator crashes completely
Expected: Emulator not to crash and the game runs

### Log file

[Ryujinx_1.1.1104_2024-01-08_17-37-14.log](https://github.com/Ryujinx/Ryujinx/files/13866870/Ryujinx_1.1.1104_2024-01-08_17-37-14.log)

### OS

Windows 10

### Ryujinx version

1.1.1104

### Game version

1.0

### CPU

Ryzen 5900x

### GPU

RTX 4090

### RAM

32GB

**Comment by MetrosexualGarbodor** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error
