### ISSUE TITLE
Yo-kai Watch 1 Glitched Lens

### ISSUE THREAD

**Issue by 8-Pit** [Ryujinx/Ryujinx#6102]
### Description of the issue

This is an old issue, and I found a thread seemingly addressing this issue https://github.com/Ryujinx/Ryujinx/issues/3004 but the glitch still persists and the old issue was marked as completed. What's the status of this bug?
![ryujinx_capture_2024-01-09_20-08-29](https://github.com/Ryujinx/Ryujinx/assets/122547509/215870db-7130-41cd-93ba-8681106b9d72)
![ryujinx_capture_2024-01-09_20-07-19](https://github.com/Ryujinx/Ryujinx/assets/122547509/bea7cfd4-68d2-4f2b-88bc-28c9696f4790)

### Reproduction steps

Go to any tree or spot on the overwold where you can search for a Yo-kai, and if you see the Yo-kai through the lens it will be glitched.

### Log file

[Ryujinx_1.1.1104_2024-01-09_20-09-15.log](https://github.com/Ryujinx/Ryujinx/files/13877996/Ryujinx_1.1.1104_2024-01-09_20-09-15.log)
[Ryujinx_1.1.1104_2024-01-09_19-55-42.log](https://github.com/Ryujinx/Ryujinx/files/13877997/Ryujinx_1.1.1104_2024-01-09_19-55-42.log)
[Ryujinx_1.1.1104_2024-01-09_20-03-53.log](https://github.com/Ryujinx/Ryujinx/files/13877998/Ryujinx_1.1.1104_2024-01-09_20-03-53.log)

### OS

Win 11

### Ryujinx version

1.1.1104

### Game version

1.0.2/1.2.0 (Info on Ryu and in game conflicts)

### CPU

i7-9700K

### GPU

ASUS RTX 4070

### RAM

16GB DDR4

### List of applied mods

German Fan Translation (Bug persists without this mod)

**Comment by NineKain** [comment]
This is still an issue, can confirm

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/3398 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.
