### ISSUE TITLE
(Pokemon Legends Arceus) Things Appear not to load in. [Bug]

### ISSUE THREAD

**Issue by von2oppy** [Ryujinx/Ryujinx#6103]
### Description of the issue

As you progress pretty early into the game things start getting all strange. [https://drive.google.com/drive/folders/19Z0CN6O24TuN-AF4b8tMOe0itvtGRtxd?usp=sharing](url)

Let me know if I am supposed to label this as a different type of issue

### Reproduction steps

Just progress into the game pretty early. 

### Log file

Ryujinx_1.1.1104_2024-01-09_18-31-40.log
Ryujinx_1.1.1104_2024-01-09_18-35-34.log
Ryujinx_1.1.1104_2024-01-09_22-25-16.log

### OS

Mac OS Sonoma 14.2.1

### Ryujinx version

1.1.1104

### Game version

1.1.1

### CPU

M2

### GPU

M2

### RAM

8GB

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
