### ISSUE TITLE
[Bug] Sea of Solitude The Directos Cut [0100AFE012BA2000] missing or invisible water

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6112]
### Description of the issue

during the game the water is missing or invisible
![Screenshot 2024-01-13 164411](https://github.com/Ryujinx/Ryujinx/assets/139027919/b8505904-5efe-41ff-9427-f095bf2ba553)
@gdkchan 
would a renderdoc be of any help to you

### Reproduction steps

play the game

### Log file

[Ryujinx_1.1.1106_2024-01-13_16-42-57.log](https://github.com/Ryujinx/Ryujinx/files/13927456/Ryujinx_1.1.1106_2024-01-13_16-42-57.log)

### OS

Windows 10

### Ryujinx version

1.11106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

### List of applied mods

none

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/3426 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games

**Comment by Djipi71** [comment]
Test on 1.1.1202
Same problem no water ingame ...
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/35375131/2cec3908-b9a4-4d65-a44d-ad10e4295e35)
