### ISSUE TITLE
[Bug]V-Rally 4 all cars are black (no details) and clouds are black aswell

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6123]
### Description of the issue

all the cars you choose are black (no detail) and from different angles from the car the clouds are black aswell
here are a few renderdocs to look at 
https://mega.nz/file/ozJFCSjL#SIOhcTcr9mC-Qo4bRtx3hgcUiP5fscjeV7DcLJeiWRw
https://mega.nz/file/RuARxCZK#Jy6CLkVa3S1VSIE69RBZNhls-A6sTal9Tnjr6MFlcXQ
https://mega.nz/file/x2JAmLIb#_k-N-TMjl-8xPNvc-OziEwT2IZybq-f4gyjFnMNpS5E
https://mega.nz/file/1rwQAQ4I#8HcdWXLRm7yR_j1uvPCKNbGwV65nSCfB72tAN35V9cc

### Reproduction steps

play the game

### Log file

[Ryujinx_1.1.1109_2024-01-14_15-20-50.log](https://github.com/Ryujinx/Ryujinx/files/13930705/Ryujinx_1.1.1109_2024-01-14_15-20-50.log)

### OS

Windows 10

### Ryujinx version

1.1.1106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1061 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
