### ISSUE TITLE
[Bug]Trials Rising [01003E800A102000] flashing shadows and lighting is wrong 

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6125]
### Description of the issue

throughout the game shadows are flashing constantly which makes the lighting incorrect aswell
here is a few renderdocs to look at
https://mega.nz/file/1iAEVY4B#aYA9BrTJ1d-fiPnBaBWReNZDVup8A4Qsfkg3IH9-TOU
https://mega.nz/file/Aj4H1J7b#af4VSYbjA00tw9NYMB2qILIhbFpy0Nzb_nblli0g_-o
https://mega.nz/file/I2okVZ7A#9nZVgCRFhd07yq6KbKHjuCEZauisU2K0mf1QnQr5g3c

### Reproduction steps

play any track

### Log file

[Ryujinx_1.1.1109_2024-01-14_15-53-26.log](https://github.com/Ryujinx/Ryujinx/files/13930779/Ryujinx_1.1.1109_2024-01-14_15-53-26.log)

### OS

Windows 10

### Ryujinx version

1.1.1106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
Now reported in the game list: https://github.com/Ryujinx/Ryujinx-Games-List/issues/633

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
