### ISSUE TITLE
Pokemon Sword 1.3.2 Crash [Bug]

### ISSUE THREAD

**Issue by barsoumr** [Ryujinx/Ryujinx#6126]
### Description of the issue

Leaving the house for the first time in the game crashes ryujinx 1.1.1110. 

### Reproduction steps

Walking out of the house for the first time, while the game is loading on the map screen. 

### Log file

[LOG.txt](https://github.com/Ryujinx/Ryujinx/files/13931123/LOG.txt)

### OS

Mac OS 14.2.1

### Ryujinx version

1.1.1110

### Game version

1.3.2

### CPU

M2 Pro

### GPU

M2 Pro/Vulkan

### RAM

16

### List of applied mods

Retexture
Remove outlines

**Comment by MetrosexualGarbodor** [comment]
The log file you posted isn't a Ryujinx log. Please refer to the FAQ or the discord server for troubleshooting.
