### ISSUE TITLE
[Bug]The Flame In The Flood Complete Edition [0100c38004dcc000] characters shadow is a big black square

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6127]
### Description of the issue

your characters shadow is a big black square
here is a few renderdocs to look at
https://mega.nz/file/wn4BzZRL#fVUzTU1UPXh8cuRwgIjsQzE17z_O0c3dpEZvL-oZXNI
https://mega.nz/file/p24g2ICZ#xQhELVLnYdDzCiMHwnx37F-qX_5RaB94CCeA61dT2Jk

### Reproduction steps

play the game

### Log file

[Ryujinx_1.1.1110_2024-01-14_18-24-00.log](https://github.com/Ryujinx/Ryujinx/files/13931243/Ryujinx_1.1.1110_2024-01-14_18-24-00.log)

### OS

Windows 10

### Ryujinx version

1.1.1106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1555 since a long time.
Someone suggested a workaround too.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
