### ISSUE TITLE
[Bug] Graphics Problems for Densha de Go!! Hashirou Yamanote Line on Ryujinx 1.1.1110 macOS 

### ISSUE THREAD

**Issue by wings1207** [Ryujinx/Ryujinx#6130]
### Description of the issue

Graphics problems as shown in the video on https://drive.google.com/file/d/1c0hwUFfJqXD7c_7WWuZ-QWdB25E7awWt/view?usp=share_link

### Reproduction steps

A video of the graphics problems is shown on the above google link.

### Log file

[Ryujinx_1.1.1110_2024-01-15_02-09-29.log](https://github.com/Ryujinx/Ryujinx/files/13932633/Ryujinx_1.1.1110_2024-01-15_02-09-29.log)

### OS

macOS 14.2.1

### Ryujinx version

1.1.1110

### Game version

1.1.1

### CPU

Apple M1

### GPU

Apple M1

### RAM

8GB

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/3627.
Thanks for your report in any case.
