### ISSUE TITLE
[Bug]Solo Islands of the Heart [010008600d1ac000] incorrect water textures

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6133]
### Description of the issue

the water throughout the game is incorrect
here is a few renderdocs
https://mega.nz/file/5jZUVDQR#SXb-sT3MKiGZgz4eG47AXMbdquV6pP1Kx-0xmVBbPUw
https://mega.nz/file/JroDyTaT#qRFDAYbfu_iUOO59_NwmFScYtEeREQICYT5kPfKmmlE
this is what the water is supposed to look like
https://www.youtube.com/watch?v=VvFzxGVn8CY

### Reproduction steps

play the game

### Log file

[Ryujinx_1.1.1110_2024-01-15_17-34-36.log](https://github.com/Ryujinx/Ryujinx/files/13937293/Ryujinx_1.1.1110_2024-01-15_17-34-36.log)

### OS

Windows 10

### Ryujinx version

1.1.1106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1659 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
