### ISSUE TITLE
[Bug]NBA 2K18 [0100760002048000] players and crowd black (missing textures or the lighting problem )

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6134]
### Description of the issue

players and crowd black (missing textures or the lighting problem )
here are a few renderdocs 
https://mega.nz/file/RrQRXZiC#PLs9tnOgb0wRKr_FdC-oc0OpOXW62LWF4023GXv1yZA
https://mega.nz/file/VqIkSLLL#kWzPgqA2_HUDyFcDeteeCOLJRV9bo0up9vOmc2-7A9g

### Reproduction steps

play the game

### Log file

[Ryujinx_1.1.1110_2024-01-15_20-16-24.log](https://github.com/Ryujinx/Ryujinx/files/13938809/Ryujinx_1.1.1110_2024-01-15_20-16-24.log)

### OS

Windows 10

### Ryujinx version

1.1.1106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1496 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
