### ISSUE TITLE
[Bug] NieR:Automata The End of YoRHa Edition visual flashes at the start

### ISSUE THREAD

**Issue by JJ-Singh** [Ryujinx/Ryujinx#6140]
### Description of the issue

NieR:Automata The End of YoRHa Edition faces visual flashes in the beginning mission.

### Reproduction steps

Start and play the game for a while, when entering the base you'll notice visual flashes.

### Log file

[Ryujinx_1.1.1111_2024-01-16_10-47-25.log](https://github.com/Ryujinx/Ryujinx/files/13952819/Ryujinx_1.1.1111_2024-01-16_10-47-25.log)

### OS

MacOS 14.2

### Ryujinx version

1.1.1111

### Game version

1.0.2

### CPU

M1 Max

### GPU

M1 Max 32 core

### RAM

32

### Additional context?

The game runs smoothly(30 fps) till that point at least.

**Comment by AcK77** [comment]
Updated state moved on the game specific issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3462
Thanks for the report!
