### ISSUE TITLE
[Bug]Charge Kid [0100F52013A66000] only shows half a screen

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6141]
### Description of the issue

the bottom half of the screen is black and  flashing
the top half is supposed to be the bottom half of the screen
![Screenshot 2024-01-17 153520](https://github.com/Ryujinx/Ryujinx/assets/139027919/6d41fae5-00dd-43d9-9472-5fca7a88ca95)
![Screenshot 2024-01-17 153454](https://github.com/Ryujinx/Ryujinx/assets/139027919/9ebfe509-285f-41e7-ae49-9a1a02797ff5)

### Reproduction steps

play the game

### Log file

[Ryujinx_1.1.1111_2024-01-17_15-34-32.log](https://github.com/Ryujinx/Ryujinx/files/13960005/Ryujinx_1.1.1111_2024-01-17_15-34-32.log)

### OS

Windows 10

### Ryujinx version

1.1.1111

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
Updated state moved on the game specific issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3462
Thanks for the report!

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
