### ISSUE TITLE
Add install guide of the prod.keys for flatpak version

### ISSUE THREAD

**Issue by K0-RR** [Ryujinx/Ryujinx#6149]
### Overview

I was struggling for 20 minutes to find the directory where I need to copy the keys. The guide should mention that if you are using the flatpak version then the folder for the keys is `~/.var/app/org.ryujinx.Ryujinx/config/Ryujinx/system/`

### Smaller details

I only succeeded in doing this thanks to this guide https://deckcentral.net/posts/run_switch_games_on_steam_deck_with_ryujinx/

### Nature of request

The button from the menu to open the folder doesn't work for me. Same for all other buttons for opening folders like "Open Mods Directory" or "Open User Save Directory"

### Why would this feature be useful?

It makes using the flatpak version possible

**Comment by AcK77** [comment]
I added the information to the guide at https://github.com/Ryujinx/Ryujinx/wiki/Keys.
On the issue about buttons for opening folder, could you open another issue here with more detailed informations, like log files, OS, etc...
Thanks.
