### ISSUE TITLE
[Bug]  a few  .xci game(base, update,dlc, all in one) don't recognize Title update.

### ISSUE THREAD

**Issue by hy9902** [Ryujinx/Ryujinx#6158]
### Description of the issue

don't recognize Title update
<img width="820" alt="屏幕截图 2024-01-21 160545" src="https://github.com/Ryujinx/Ryujinx/assets/8055358/0d1afc38-9fa2-4752-9a78-1e8fc6bba3d1">

### Reproduction steps

Xenoblade2 [0100F3400332C000] [v917504] (1G+1U+6D) 
NSCBx1.0.1b rebuild
[Uploading Xenoblade2 [0100F3400332C000] [v917504] (1G+1U+6D)-fwinfo.txt…]()

### Log file

none

### OS

win10

### Ryujinx version

1.1.1117

### Game version

v2.0.2 (v917504)

### CPU

R9 7900X

### RAM

32GB

**Comment by TSRBerry** [comment]
It should be listed under the "Manage updates" option. If there is an issue with that, reopen this issue please.

**Comment by TSRBerry** [comment]
Nvm, https://github.com/Ryujinx/Ryujinx/pull/5914 was reverted.

**Comment by Arturbc** [comment]
Me too. My games Crash Team Racing Nitro-Fueled and The Legend of Zelda Breath of the Wild has dumped with all of my DLCs and lastest updates of moment built-in on XCI files, but Ryujinx not recognezes these.

![image](https://github.com/Ryujinx/Ryujinx/assets/19739238/838d3f7a-b423-4f68-a2c7-eae2649de5d9)
![image](https://github.com/Ryujinx/Ryujinx/assets/19739238/47f62b39-92f9-4d21-87f3-b31a66e16113)

Thanks.

**Comment by piplup55** [comment]
> Me too. My games Crash Team Racing Nitro-Fueled and The Legend of Zelda Breath of the Wild has dumped with all of my DLCs and lastest updates of moment built-in on XCI files, but Ryujinx not recognizes these.

this should be fixed by https://github.com/Ryujinx/Ryujinx/pull/6515

**Comment by RupeeClock** [comment]
I observed that Ryujinx's title manager can be buggy, and it may explain why some users report that they've been unable to add updates to titles.
It appears to occur whenever an update version string contains letters, and previous updates are only numeric rather than alphanumeric.
https://github.com/Ryujinx/Ryujinx/issues/7021
