### ISSUE TITLE
[Bug] bayonetta 3 bug gameplay 

### ISSUE THREAD

**Issue by zxal20** [Ryujinx/Ryujinx#6163]
### Description of the issue

In game bayonetta 3 in chapter 9 Where we need to summon the flying monster and the wind blows when the door is opened, the monster is summoned, but the wind does not blow with the buttons, what should I do?

### Reproduction steps

I don't know 

### Log file

[Ryujinx_1.1.1117_2024-01-21_12-22-11.log](https://github.com/Ryujinx/Ryujinx/files/14003178/Ryujinx_1.1.1117_2024-01-21_12-22-11.log)

### OS

Windows 10

### Ryujinx version

1.1.1117

### Game version

1.1.0

### CPU

I5 4460

### GPU

Amd rx 580

### RAM

8gb

**Comment by AcK77** [comment]
Could you report this game specific issue in the games list instead of here please : https://github.com/Ryujinx/Ryujinx-Games-List/issues/4129.
Thanks.
