### ISSUE TITLE
E5B9G9R9_SHAREDEXP texture format not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#617]
`E5B9G9R9_SHAREDEXP` (`0x20`) texture format is not implemented

![image](https://user-images.githubusercontent.com/4905390/64083268-2b8e4300-cd1d-11e9-995a-ab9775924438.png)

`GL_RGB9_E5`

## Required by:

- https://github.com/Ryujinx/Ryujinx-Games-List/issues/156

**Comment by jgoyvaerts** [comment]
Is this issue still relevant? I tried reproducing it with the game mentioned but the game boots and runs fine.

**Comment by gdkchan** [comment]
Already implemented.
