### ISSUE TITLE
[Bug] Crash during game loading

### ISSUE THREAD

**Issue by Kavuti** [Ryujinx/Ryujinx#6170]
### Description of the issue

While playing The Legend Of Zelda: Breath Of The Wild, after the update from version 1.1.1122 to 1.1.1125 Ryujinx crashes a few seconds after the game starts loading the chosen save file.

### Reproduction steps

Just updated and restarted the emulator, started the game and selected my last save to be loaded.

### Log file

00:00:00.067 |I| Configuration LogValueChange: ResScale set to: 4
00:00:00.079 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.079 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.080 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.081 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.082 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.082 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1D11
00:00:00.084 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.085 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.085 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.087 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.088 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.088 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.088 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.088 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.089 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.089 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.091 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.091 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.091 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.091 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.096 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.096 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1125
00:00:00.103 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.103 |N| Application Print: CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz ; 8 logical
00:00:00.106 |N| Application Print: RAM: Total 15.8 GiB ; Available 11.8 GiB
00:00:00.109 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.110 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.116 |I| Gpu : Backend Threading (Auto): True
00:00:00.367 |N| Application LoadApplication: Using Firmware Version: 17.0.1
00:00:00.367 |I| Application LoadApplication: Loading as NSP.
00:00:00.374 |W| Loader GetNpdm: NPDM file not found, using default values!
00:00:00.524 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.538 |E| Loader LoadNsos: Process initialization returned error "InvalidMemoryRegion".
00:00:00.539 |E| Loader TryLoad: Unable to load: Could not find Main NCA
00:00:00.023 |I| Gpu : Backend Threading (Auto): True
00:00:00.158 |N| Application LoadApplication: Using Firmware Version: 17.0.1
00:00:00.158 |I| Application LoadApplication: Loading as NSP.
00:00:00.174 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.181 |I| ModLoader AddModsFromDirectory: Found mod '' [CC]
00:00:00.181 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.183 |I| Loader Load: Loading rtld...
00:00:00.192 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.192 |I| Loader Load: Loading main...
00:00:00.631 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Cafe\U-King\trunk\Game\App\Rom\NX64\Product\code\U-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Atk-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-7_3_2-Release
                   SDK MW+Microsoft+Havok_Cloth-2014_2
                   SDK MW+Microsoft+Havok-2014_2
                   SDK MW+Microsoft+Havok_Animation-2014_2
                   SDK MW+Microsoft+Havok_AI-2014_2
                   SDK MW+Microsoft+Havok_Physics2012-2014_2
00:00:00.632 |I| Loader Load: Loading subsdk0...
00:00:00.695 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-7_3_2-Release
00:00:00.695 |I| Loader Load: Loading sdk...
00:00:00.810 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:00.817 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.688 |I| Ptc Load: Loaded Translation Cache (size: 159630252 bytes, translated functions: 81128).
00:00:02.712 |I| Ptc Load: Loaded Profiling Info (size: 280294 bytes, profiled functions: 81133).
00:00:02.720 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:02.721 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:02.737 |I| Loader LoadNsos: Loading image 2 at 0x000000000b26a000...
00:00:02.741 |I| Loader LoadNsos: Loading image 3 at 0x000000000b987000...
00:00:02.748 |I| ModLoader LoadCheats: Build ids found for title 01007EF00011E000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    8E9978D50BDD20B4C8395A106C27FFDE00000000000000000000000000000000
    93FF8252D975ADF07230CB86C83301C53F2804DF000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:02.751 |W| ModLoader LoadCheats: Skipping cheat '<Max - Infinite Health Cheat>' because no executable matches its BuildId 16A91992BBA71201 (check if the game title and version are correct)
00:00:02.751 |W| ModLoader LoadCheats: Skipping cheat '<Max - Infinite Stamina Cheat>' because no executable matches its BuildId 16A91992BBA71201 (check if the game title and version are correct)
00:00:02.751 |W| ModLoader LoadCheats: Skipping cheat '<Infinite Rupies Cheat>' because no executable matches its BuildId 16A91992BBA71201 (check if the game title and version are correct)
00:00:02.751 |W| ModLoader LoadCheats: Skipping cheat '<Infinite Special Powers Cheat>' because no executable matches its BuildId 16A91992BBA71201 (check if the game title and version are correct)
00:00:02.751 |W| ModLoader LoadCheats: Skipping cheat '<Arrows x999 Cheat>' because no executable matches its BuildId 16A91992BBA71201 (check if the game title and version are correct)
00:00:02.751 |I| ModLoader LoadCheats: Installing cheat '<Infinite Health Cheat>'
00:00:02.761 |I| ModLoader LoadCheats: Installing cheat '<Max Hearts Cheat>'
00:00:02.761 |I| HLE.TamperMachine TamperMachine TamperRunner: TamperMachine thread running
00:00:02.761 |I| ModLoader LoadCheats: Installing cheat '<Infinite Stamina Cheat>'
00:00:02.762 |I| ModLoader LoadCheats: Installing cheat '<Infinite Powers Cheat>'
00:00:02.801 |E| TamperMachine Compile: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.HLE.HOS.Tamper.InstructionHelper.GetImmediate(Byte[] instruction, Int32 index, Int32 nybbleCount) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Tamper\InstructionHelper.cs:line 62
   at Ryujinx.HLE.HOS.Tamper.CodeEmitters.StoreConstantToMemory.Emit(Byte[] instruction, CompilationContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Tamper\CodeEmitters\StoreConstantToMemory.cs:line 34
   at Ryujinx.HLE.HOS.Tamper.AtmosphereCompiler.CompileImpl(String name, IEnumerable`1 rawInstructions) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Tamper\AtmosphereCompiler.cs:line 92
   at Ryujinx.HLE.HOS.Tamper.AtmosphereCompiler.Compile(String name, IEnumerable`1 rawInstructions) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Tamper\AtmosphereCompiler.cs:line 40
00:00:02.801 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:02.801 |I| ModLoader LoadCheats: Installing cheat '<Current Arrow 999 Enter Equipment Menu to Refill Cheat>'
00:00:02.801 |I| ModLoader LoadCheats: Installing cheat '<999999 Rupees Cheat>'
00:00:02.801 |I| ModLoader LoadCheats: Installing cheat '<R+L+A To Recharge Master Sword Cheat>'
00:00:02.802 |I| ModLoader LoadCheats: Installing cheat '<Moonjump R+B Cheat>'
00:00:02.802 |I| ModLoader LoadCheats: Installing cheat '<Speed x4 Cheat>'
00:00:02.802 |I| ModLoader LoadCheats: Installing cheat '<Speed x1 Activate to reset Speed x4 Cheat>'
00:00:02.802 |I| ModLoader LoadCheats: Installing cheat '<BEST Moonjump Hold X No need to reactivate Cheat>'
00:00:02.802 |I| ModLoader LoadCheats: Installing cheat '<Moonjump ZL+X Cheat>'
00:00:02.806 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.860 |I| Loader Start: Application Loaded: The Legend of Zelda: Breath of the Wild v1.6.0 [01007ef00011e000] [64-bit]
00:00:02.870 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.886 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:03.708 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce MX230 (Vulkan v1.3.205, Driver v516.40.0.0)
00:00:03.717 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:03.726 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:05.205 |I| HLE.GuestThread.42 Ptc LoadTranslations: 81127 translated functions loaded
00:00:05.231 |I| HLE.GuestThread.42 Ptc MakeAndSaveTranslations: 0 of 6 functions translated | Thread count: 7
00:00:05.376 |I| HLE.GuestThread.42 Ptc MakeAndSaveTranslations: 6 of 6 functions translated | Thread count: 7 in 0,142045 s
00:00:05.523 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:05.529 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:05.530 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.530 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:05.540 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed. 
00:00:07.064 |G| HLE.OsThread.21 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 6s
    ProgramName: U-King
    Thread: MainThread
    Filename: D:/home/Cafe/U-King/trunk/Game/Lib/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp
    Line: 18
    Function: PrintStringImpl
    Message: 0000002e

00:00:07.066 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:07.066 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:07.067 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:07.067 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:07.067 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:07.142 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:07.151 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:07.178 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:07.202 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.285 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:07.285 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:07.286 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:07.287 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:07.288 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:07.289 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:07.289 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:07.291 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:07.342 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:07.347 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:07.348 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:07.359 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:07.398 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72197163296350208}
00:00:07.401 |S| HLE.OsThread.43 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:09.811 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:09.812 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:11.895 |I| Ptc Save: Saved Translation Cache (size: 159614465 bytes, translated functions: 81134).
00:00:14.387 |S| HLE.OsThread.9 ServiceHid ActivateConsoleSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:14.387 |S| HLE.OsThread.9 ServiceHid InitializeSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; counter0: 4096 ; counter1: 520192}
00:00:14.855 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:14.858 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV7
00:00:14.876 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:14.877 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:14.902 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:14.943 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:15.082 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceSystemEvent: Stubbed. 
00:00:15.083 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:15.140 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:16.883 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:17.290 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; _gyroscopeZeroDriftMode: Tight}
00:00:17.291 |S| HLE.OsThread.43 ServiceAm SetGamePlayRecordingState: Stubbed. {_gamePlayRecordingState: True}
00:00:17.294 |S| HLE.OsThread.9 ServiceHid StopSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:17.502 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:17.806 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:35.334 |I| HLE.OsThread.27 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 119
 UserId: 00000000000000010000000000000000
 Room: option 
 Report: {
    "BalloonTextOnOff": 1,
    "AutoSaveOnOff": 1,
    "CameraUpDownReverse": 0,
    "CameraRLReverse": 0,
    "TextRubyOnOff": 1,
    "JumpButtonChange": 0,
    "StickSensitivity": 2,
    "GyroOnOff": 0,
    "MiniMapDirection": 0,
    "AmiiboItemOnOff": 0,
    "MainScreenOnOff": 0,
    "DisplaySpecialMode": 0,
    "TextWindowChange": 1,
    "DockInOnOff": 1,
    "ControllerType": 1,
    "AttachExtGrip": 0,
    "CtrlModeHandheldFree": 0,
    "CtrlModeHandheldExt": 0,
    "CtrlModeHandheldFullKey": 5,
    "CtrlModeHandheldHandheld": 0,
    "CtrlModeConsoleFree": 0,
    "CtrlModeConsoleExt": 0,
    "CtrlModeConsoleFull": 183631,
    "PlayTimeHandheld": 5,
    "PlayTimeConsole": 183636,
    "PlayTimeAll": 183641,
    "RomVer": 160,
    "AoCVer": 0,
    "RegionLanguage": 144,
    "AudioMono": 0,
    "AudioStereo": 177925,
    "Audio5_1ch": 0,
    "AudioOther": 0
}

00:00:36.039 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:36.678 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:37.679 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 1320 took more than 1000ms, resuming execution...
00:00:58.177 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:58.497 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 223
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 55
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 120
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 448

### OS

Windows 11

### Ryujinx version

1.1.1125

### Game version

1.6.0

### CPU

i7-10510U

### GPU

NVIDIA GeForce MX230

### RAM

16GB

### List of applied mods

No mod applied

**Comment by AcK77** [comment]
You set the scaling factor to 4, you should sets it lower since the error is `ErrorOutOfDeviceMemory` and it should be good.
