### ISSUE TITLE
Prince of Persia: The Lost Crown crash in  Main Quest "Neutralize Vahram and Save Ghassan"

### ISSUE THREAD

**Issue by DanishCh29** [Ryujinx/Ryujinx#6172]
### Description of the issue

https://github.com/Ryujinx/Ryujinx/assets/157707497/2fee6593-030b-4045-822d-5d07c7b97629

1. This is Main Quest "Neutralize Vahram and Save Ghassan"
2. We are Supposed to go to Constellation room and Go to past to fight Vahram.
3. After losing the fight, I decided to close the game and continue it later.
4. But Now whenever I tried to go to past, the game freezes, shows white blank screen and then closes.
5. I desperately need help because I can't afford to lose this much game progress.

### Reproduction steps

https://github.com/Ryujinx/Ryujinx/assets/157707497/3e8a4c7b-9f03-4491-b8fe-8ca25459d88c

1.  Follow the path shown in my issues video.
2.It supposed to start a cutscene and then went to fight.

### Log file

[Ryujinx_1.1.1125_2024-01-25_18-02-43.log](https://github.com/Ryujinx/Ryujinx/files/14052543/Ryujinx_1.1.1125_2024-01-25_18-02-43.log)
[Ryujinx_1.1.1125_2024-01-25_18-14-13.log](https://github.com/Ryujinx/Ryujinx/files/14052544/Ryujinx_1.1.1125_2024-01-25_18-14-13.log)

### OS

Windows 11 but for some reason Ryujinx thinks it as Windows 10

### Ryujinx version

1.1.1125

### Game version

1.0.2

### CPU

Ryzen 7

### GPU

NVIDIA RTX 3060 Laptop

### RAM

16GB

### List of applied mods

when it first happened I was using Infinite Dash Cheat.
But after I disabled it, and The result was same.

**Comment by Eli0t77** [comment]
if you could upload your save it would help a lot for anyone trying to reproduce this

**Comment by DanishCh29** [comment]
> if you could upload your save it would help a lot for anyone trying to reproduce this

oh sorry I thought I uploaded it. Here's it:

[000000000000000a.zip](https://github.com/Ryujinx/Ryujinx/files/14062120/000000000000000a.zip)

**Comment by GamerzHell9137** [comment]
Disable all mods and cheats and try again.

**Comment by DanishCh29** [comment]
> Disable and delete all mods and cheats and try again. Tried it and it works fine on my end.

I don't think cheats are the issue here. Like I said I tried without cheats too, it still wasn't working.

Although, I tried messing around with game and emulator today and find the solution:
1. For some reason, if I disable DLCs from going to Manage DLCs - Disable every disable. I'm able to skip the cutscene and continue the game.
2. I checked again by enabling DLCs content and I was stuck in the same issue again.
3. I tried 1st step with cheats enables too, and it was working. Hence, my conclusion that cheats might not be an issue.

Also this is my first time with bug reports, so now my problem is solved should I delete this thread or there's a way to close it?

**Comment by nthitz** [comment]
this also happens to me on a real switch so maybe the emulator is working properly

**Comment by Digital79** [comment]
Had the same exact issue but on Yuzu, so it doesn´t seem to matter where you play. Issue got created exactly the same. I was fighting Vahram a few times and getting my as handed to me so I rage quit. Coming back to try the fight later on it kept freezing when entering the Constellation room. For me removing only the DLCs didn´t help but removing every Mod + DLC did help and I could enter the cutseen and fight Vahram once agin. So I disabled DLCs, game update, mods for 4k and fps. After the fight was over and saved I reenabled everything again.

**Comment by DanishCh29** [comment]
> Had the same exact issue but on Yuzu, so it doesn´t seem to matter where you play. Issue got created exactly the same. I was fighting Vahram a few times and getting my as handed to me so I rage quit. Coming back to try the fight later on it kept freezing when entering the Constellation room. For me removing only the DLCs didn´t help but removing every Mod + DLC did help and I could enter the cutseen and fight Vahram once again. So I disabled DLCs, game update, mods for 4k and fps. After the fight was over and saved I reenabled everything again.

I'm happy my solution worked for you. Do you think I should reopen this? it seems like other having same issue too.

**Comment by DanishCh29** [comment]
> this also happens to me on a real switch so maybe the emulator is working properly

That's unfortunate. Do you find any solution? Because it might help other with switch console too.

**Comment by nthitz** [comment]
> > this also happens to me on a real switch so maybe the emulator is working properly
> 
> That's unfortunate. Do you find any solution? Because it might help other with switch console too.

Sorta, I eventually just reequipped the less good amulets I had when I originally went to the boss fight and it worked.
