### ISSUE TITLE
[Bug] Ace Attorney Apollo Justice Trilogy 3D models flickering

### ISSUE THREAD

**Issue by adrien-krebet** [Ryujinx/Ryujinx#6181]
### Description of the issue

In Apollo Justice Trilogy when a 3D model is on screen and in the middle of an animation it flickers in and out (as in disappearing). This happens during Dual Destinies gameplay, Spirit of Justice gameplay and in the 'animation studio' feature. It seems to alternate frames that it flashes out. I think it also happens with other switch emulators.

My log file is large so i isolated it to when the model was onscreen.

### Reproduction steps

1. Open up Apollo Justice Trilogy and select "Game Selection and Museum"
2. Choose either Dual Destinies (DD), Spirit of Justice (SOJ) or the Museum
3. If either of the former two either load up a new game, load an episode or view the costumes (the third is the fastest, the rotation animation flickers)
4. If in the museum, choose the animation studio option and view any of the 3D characters in DD or SOJ. 

### Log file

[Ryujinx_ 1.1.0-macos1_2024-01-27_02-59-45.txt](https://github.com/Ryujinx/Ryujinx/files/14066982/Ryujinx_.1.1.0-macos1_2024-01-27_02-59-45.txt)

### OS

Macos Monterey version  12.6

### Ryujinx version

1.1.0-macos1 (System ver 16.1.0)

### Game version

1.0.0

### CPU

Mac M1 (2020) cpu

### GPU

Mac M1 (2020) gpu

### RAM

16GB

### List of applied mods

None

### Additional context?

Drive link to my screen recording of it happening

https://drive.google.com/file/d/1ZEFIdy0y8YXg0DpN88wgWwaXJiyEFEgB/view?usp=sharing

**Comment by MetrosexualGarbodor** [comment]
Does it happen on [master](https://ryujinx.org/download/)? Macos1 is really old at this point and should only be used for LDN.

**Comment by adrien-krebet** [comment]
Tried that and also with two different firmwares (17.0.0 and 16.10.0), the flickering is still present

**Comment by adrien-krebet** [comment]
![Screen Shot 2024-01-27 at 03 49 50](https://github.com/Ryujinx/Ryujinx/assets/122225640/27397ef5-ecc3-4690-b319-f154ea5f1e6b)
Screenshot of master build with 17.0.0's log as it has a flickering 3D model on screen

**Comment by gdkchan** [comment]
The issue appears to be macOS specific. I can reproduce it on my m1 macbook air, but not on my Windows PC with either NVIDIA or AMD.

**Comment by adrien-krebet** [comment]
Yeah there's that yuzu issue I mentioned, it being on a steam deck is kinda interesting though? I wonder if it can also be replicated on switch hardware. Tried different resolutions/scaling and still present so yeah nothing within ryujinx from what I can see that can fix or even change it slightly

**Comment by adrien-krebet** [comment]
Downloaded the build from the pull request above.
So the models within the costume selector no longer flash, however new issue when opening up a chapter in one of the 3d games and animation studio, issue is with with black flashing and background issues I took video below I'll also get the log soon to support. 
Should I make this as a separate bug report in this github?

Below is a link to a drive folder with two screencaps of the issue
https://drive.google.com/drive/folders/1yUR1XROZIO8_ZM1kKsbqSvESLfUXdWUj?usp=sharing

**Comment by adrien-krebet** [comment]
This is the log, same with both videos
![Screen Shot 2024-01-28 at 23 41 25](https://github.com/Ryujinx/Ryujinx/assets/122225640/cc7e998e-faae-4b60-969c-3de3331d6e1a)

**Comment by gdkchan** [comment]
`InvalidResource` errors have generally been fixed on macOS Sonoma. I'm not sure if its the case here, but it could be fixable with a system update.

**Comment by adrien-krebet** [comment]
Yep I did a system update to Sonoma and now fully working, thanks a lot for your work! I just avoid mac updates on instinct since most programs are so stingy with them :, ]
