### ISSUE TITLE
[Bug] I can't change the time zone setting

### ISSUE THREAD

**Issue by NereeScarlet** [Ryujinx/Ryujinx#6183]
### Description of the issue

My time zone is UTC+8.
But the default time zone is UTC
When I try to change this setting, I can't find the drop down menu and can only enter it manually.
When I choose to save and reopen the settings screen, the timezone setting changes to UTC again!
This makes my in-game time perpetually eight hours earlier compared to real time, which is really aggravating.

![image](https://github.com/Ryujinx/Ryujinx/assets/61875283/821899b8-e53e-42d9-b9da-85807d1fc069)
![image](https://github.com/Ryujinx/Ryujinx/assets/61875283/5b322ec6-fc13-4ac6-bc5a-cbcdd5af9015)

### Reproduction steps

Go to Settings-System
Change time zone settings
Then save
Re-enter Settings-System
Change the time zone setting back to UTC again

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2024-01-27_03-39-14.log](https://github.com/Ryujinx/Ryujinx/files/14068777/Ryujinx_1.1.0-ldn3.1.3_2024-01-27_03-39-14.log)

### OS

win10

### Ryujinx version

ava-ryujinx-1.1.0-ldn3.1.3-win_x64

**Comment by MutantAura** [comment]
This is already fixed upstream. Whenever LDN is updated, this will also be fixed.

**Comment by NereeScarlet** [comment]
> 这已经在上游修复了。每当 LDN 更新时，这个问题也将得到修复。

May I ask what time that will be updated?
I want to be able to enjoy the game as much as possible while on my upcoming vacation!
Finally, thank you for your work!
