### ISSUE TITLE
[BUG] Red dead redemption screen goes black after trying to save

### ISSUE THREAD

**Issue by Askdaf** [Ryujinx/Ryujinx#6186]
### Description of the issue

I barely started playing the game, whenever i try to use the bed to save the screen just goes black with sound playing, i cant seem to do anything else, im suing the reality redemption mod with only the texture changes

### Reproduction steps

Go to the bed, try to save and choose a slot

### Log file

![Rdr error](https://github.com/Ryujinx/Ryujinx/assets/154361425/111d0713-c4c5-4cf3-a1d0-1671595ed156)

### OS

Windows 10

### Ryujinx version

1.1.1139

### Game version

1.0.1

### CPU

I5 12th gen

### GPU

Nvidia 1060 gtx

### RAM

16gb

### List of applied mods

Reality redemption (only textures)

**Comment by AcK77** [comment]
Log file is incomplete. It will be hard to find a solution without one.
Additionally to that, you can report your state on the game specific issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4721
Thanks.
