### ISSUE TITLE
[Bug][Pokemon Sw/Sh] Daily events + Pokejobs broken

### ISSUE THREAD

**Issue by NereeScarlet** [Ryujinx/Ryujinx#6188]
### Description of the issue

I'm having the same problem as in #2430.
RTC doesn't run ingame. This affects majority of time based events, berry picking, den resets and pokejobs.
Changing clock in Ryu settings doesn't fix it. Although weirdly, Weather changes happen.
In the meantime I tried using https://github.com/Ryujinx/Ryujinx/issues/2430#issuecomment-1543348123
The method mentioned changes the value to 0 using PKHeX
Unfortunately, this didn't improve the problem, and the two values still change back to their original values after entering the game and re-saving.
![image](https://github.com/Ryujinx/Ryujinx/assets/61875283/b1d6e87f-c7f4-4c6c-ac5a-4c3c784bd717)
![image](https://github.com/Ryujinx/Ryujinx/assets/61875283/6222635a-0fb8-4339-a318-be5ed37ba25b)

### Reproduction steps

Register for a pokejob in pokemon centre and Close the game wait a few hours. Check back on the job and it will still state 24 hours remaining.

### Log file

No log files given as it isn't crash related.

### OS

win10

### Ryujinx version

ava-ryujinx-1.1.0-ldn3.1.3-win_x64

### Game version

Pokemon Sw1.3.2/switch Firmware 17.0.0

### CPU

i7-7700

### GPU

1050ti

### RAM

8gib

**Comment by MutantAura** [comment]
This is already fixed upstream. Whenever LDN is updated, this will also be fixed.

**Comment by NereeScarlet** [comment]
Should I try to downgrade the firmware version? Like #4822 mentioned 15.0.0？
