### ISSUE TITLE
irs IIrSensorServer: 319 (ActivateIrsensorWithFunctionLevel) not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#619]
IIrSensorServer ActivateIrsensorWithFunctionLevel is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/HID_services#irs) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::irsensor::IIrSensorServer(319))

Unknown.

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/89
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/114
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/154

**Comment by AcK77** [comment]
Symbol is `ActivateIrsensorWithFunctionLevel(nn::applet::AppletResourceUserId, nn::irsensor::PackedFunctionLevel)`
