### ISSUE TITLE
[Bug] The application “Ryujinx.app” can’t be opened.

### ISSUE THREAD

**Issue by farhang103** [Ryujinx/Ryujinx#6191]
### Description of the issue

I have M1 Pro is v4.2.1 (23C71), I can't open the app, what should I do?

### Reproduction steps

I tried also with ctrl + click to open it and I still get this error

### Log file

I didn't find it in Macos

### OS

Macos

### Ryujinx version

1.1.1141

**Comment by AcK77** [comment]
You can find an installation guide here : https://blog.ryujinx.org/the-impossible-port-macos/
If you needs support you can go to our discord server.
Thanks.
