### ISSUE TITLE
[Bug]test-ava-ryujinx-1.1.1141-win_x64 Execute exe file progress card on cmd command line

### ISSUE THREAD

**Issue by LeeYouRan** [Ryujinx/Ryujinx#6192]
### Description of the issue

Execute exe file progress card on cmd command line
![屏幕截图 2024-01-28 151511](https://github.com/Ryujinx/Ryujinx/assets/29844685/a2a313bc-1c05-443e-9030-3cd299d3d269)

### Reproduction steps

Download test ava ryujinx-1.1.1141-win from GitHub_ After decompressing the x64.zip file on the local computer, execute Ryujinx in the public directory Ava. exe pops up a cmd command window, and the command is executed to the following content (00:00:00.003 | I | Configuration LogValue Change: Enabling FileLog set to: True)

00:00:00.071 | I | Configuration LogValue Change: BackendThreading set to: Auto

00:00:00.073 | I | Configuration LogValue Change: ResScale set to: 1

00:00:00.083 | I | Configuration LogValue Change: ResScaleCustom set to: 1

00:00:00.084 | I | Configuration LogValue Change: MaxAnisotropy set to: -1

00:00:00.085 | I | Configuration LogValue Change: AspectRatio set to: Fixed16x9) Will not continue, progress is stuck

### Log file

[Ryujinx_1.1.1141_2024-01-28_15-09-18.log](https://github.com/Ryujinx/Ryujinx/files/14075258/Ryujinx_1.1.1141_2024-01-28_15-09-18.log)
[Ryujinx_1.1.1141_2024-01-28_15-10-24.log](https://github.com/Ryujinx/Ryujinx/files/14075259/Ryujinx_1.1.1141_2024-01-28_15-10-24.log)
[Ryujinx_1.1.1141_2024-01-28_15-10-41.log](https://github.com/Ryujinx/Ryujinx/files/14075260/Ryujinx_1.1.1141_2024-01-28_15-10-41.log)

### OS

windows11 23H2 22631.3085

### Ryujinx version

test-ava-ryujinx-1.1.1141-win_x64

### CPU

AMD Ryzen 5 2600X Six-Core Processor

### GPU

GTX 1060 6G

### RAM

16G

**Comment by AcK77** [comment]
That's not an issue, the command line stay opened while the GUI is opened when you execute Ryujinx.
I close it. Can be reopened if I don't understand the issue correctly.

**Comment by LeeYouRan** [comment]
I mean that the progress is stuck at this stage. It will not continue, and the software graphical interface will not be opened.

**Comment by AcK77** [comment]
If you use an antivirus be sure to add an exception for Ryujinx, additionnally to that checks if you use latest GPU driver.
You can go to our discord for support if you needs to.
