### ISSUE TITLE
[Bug] Dr Kawashima’s Brain Training for Nintendo Switch (JAP) fails to boot

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6194]
### Description of the issue

fails to boot the game
![Screenshot 2024-01-27 182556](https://github.com/Ryujinx/Ryujinx/assets/139027919/22ae86cb-7de2-4d50-8e90-3fd0ab85f7ca)

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1141_2024-01-28_17-04-47.log](https://github.com/Ryujinx/Ryujinx/files/14075463/Ryujinx_1.1.1141_2024-01-28_17-04-47.log)

### OS

Windows 10

### Ryujinx version

1.1.1141

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
You can report game specific issue in https://github.com/Ryujinx/Ryujinx-Games-List/issues/281 instead of here.
Thanks.
The JAP version have the same ApplicationId than other regions.
It could be a regression that needs more testing from other users.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games

**Comment by ScottNash042** [comment]
will add to games list
