### ISSUE TITLE
MoltenVK used instead of Apple GPU.  

### ISSUE THREAD

**Issue by m3kwong** [Ryujinx/Ryujinx#6195]
### Description of the issue

Loading 1141 will give me moltenVK as the GPU vs 1125 which gives me Apple GPU

Also it seem to have messed settings in particular FSR, the graphics look really bad(low res even at 2x).   Even after going back to 1125, the graphics are all low res even if it says Apple GPU is used.

### Reproduction steps

Use 1.1.1141 on Apple M Macs

### Log file

no logs

### OS

Sonoma 14.3

### Ryujinx version

1.1.1141

### Game version

All games

### CPU

M2

### RAM

32

### List of applied mods

Mods applied

### Additional context?

No context

**Comment by ekuland** [comment]
1.1.1135: Use driver name instead of vendor name in the status bar for Vulkan.

Macs have always used MoltenVK for display. This is a simple rename, no functional change.

**Comment by gdkchan** [comment]
I do think it should be changed back to Apple. This will be bad for Intel macs where GPU could be AMD or Intel but it will also always show "MoltenVK".

**Comment by m3kwong** [comment]
Deleting config.json and restarting it fixes the graphics issue.
