### ISSUE TITLE
[Bug] Fails to Launch on macOS with Version 1.1.1084 and Later Without SIP Enabled

### ISSUE THREAD

**Issue by HouseYeung** [Ryujinx/Ryujinx#6197]
### Description of the issue

If you are using version 1.1.1084 or later on a Mac, please ensure that System Integrity Protection (SIP) is enabled. Otherwise, the application fails to launch.

I'm experiencing an issue with my MacBook Pro 14.2.1 M3 Max. After installing the latest version of the software and granting it launch permissions, clicking on the application icon results in an immediate crash without even displaying the application window. The application opens when using Rosetta. Suspecting a version compatibility issue, I tested around 20 different versions and discovered that the last version that works properly is 1.1.1083. Versions starting from 1.1.1084 onwards fail to launch completely. 

Later, I considered that the issue might be related to SIP. After restarting my computer and enabling SIP, all versions started to launch correctly without the need for Rosetta. 

It's bit dumb but it might help for people who always turn off the SIP

### Reproduction steps

disable SIP and launch Ryujinx after 1.1.1083

### Log file

dont have

### OS

macOS

### Ryujinx version

1.1.1084 and higher

**Comment by jcm93** [comment]
Can you attach a crash log?

**Comment by HouseYeung** [comment]
> Can you attach a crash log?
I couldn't find any logs, as the application fails to launch completely and therefore doesn't generate any logs.

**Comment by HouseYeung** [comment]
> Can you attach a crash log?

I couldn't find any logs, as the application fails to launch completely and therefore doesn't generate any logs.
