### ISSUE TITLE
[Bug]Slow Frame rate on must games for Apple M1 since 1.1.1141 update.

### ISSUE THREAD

**Issue by xel-arjona** [Ryujinx/Ryujinx#6198]
### Description of the issue

Apparently something's going on since last update, suddenly all my games slowed down Frame Rate at gameplay (not in openings or maps in the case of Mario  in my Macbook Air M1.

### Reproduction steps

Updating to 1.1.1141 slowed down all games.

### Log file

[Ryujinx_1.1.1141_2024-01-28_13-24-37.log](https://github.com/Ryujinx/Ryujinx/files/14077525/Ryujinx_1.1.1141_2024-01-28_13-24-37.log)

### OS

Sonoma 14.3

### Ryujinx version

1.1.1141

### CPU

Apple M1

### GPU

Apple M1

### RAM

8 GB

### Additional context?

No apps opened at the OS, only Ryujinx., controllers used both in Bluetooth mode and USB connected.

**Comment by AcK77** [comment]
Have you tried a fresh installation?
Have you tried to purge your shaders cache?

Since this issue isn't reported by anyone else than you, I suggest the issue is at your side.
You can come to our discord for support, this issue can be reopened if it's an emulator issue.
Thanks.
