### ISSUE TITLE
[Bug] Macos Breath of the wild crash

### ISSUE THREAD

**Issue by Redhawk18** [Ryujinx/Ryujinx#6199]
### Description of the issue

Crashes after the game loads, can happen at any time.

### Reproduction steps

It seems to be anytime related to being in the overworld

### Log file

[Ryujinx_1.1.1141_2024-01-28_15-37-28.log](https://github.com/Ryujinx/Ryujinx/files/14077687/Ryujinx_1.1.1141_2024-01-28_15-37-28.log)
[Ryujinx_1.1.1141_2024-01-28_15-42-23.log](https://github.com/Ryujinx/Ryujinx/files/14077688/Ryujinx_1.1.1141_2024-01-28_15-42-23.log)

### OS

macos 14.2.7

### Ryujinx version

1.1.1141

### Game version

1.0.0

### CPU

m1

### GPU

m1

### RAM

8gb

**Comment by gdkchan** [comment]
Only works with hypervisor disabled.

**Comment by AcK77** [comment]
As the previous comment said, the game is only playable with the hypervisor disabled.
You can report this state at https://github.com/Ryujinx/Ryujinx-Games-List/issues/86 if you want.
Thanks.
