### ISSUE TITLE
irs IIrSensorServer: 304 (GetIrsensorSharedMemoryHandle) not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#620]
IIrSensorServer GetIrsensorSharedMemoryHandle is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/HID_services#GetIrsensorSharedMemoryHandle) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::irsensor::IIrSensorServer(304))

> Takes a PID-descriptor and an AppletResourceUserId. Returns a SharedMemory handle.
>
> The SharedMemory is mapped with permissions=read-only and size=0x8000.

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/114
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/154
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/89

**Comment by HorrorTroll** [comment]
irs 304: GetIrsensorSharedMemoryHandle

```
Takes a PID-descriptor and an AppletResourceUserId. Returns a SharedMemory handle.

The SharedMemory is mapped with permissions=read-only and size=0x8000.```

CheckFirmwareVersion is irs 314
