### ISSUE TITLE
[Bug] TotK crashing in same spot near Hyrule fields

### ISSUE THREAD

**Issue by Legalflowers** [Ryujinx/Ryujinx#6200]
### Description of the issue

Has anyone encountered this issue? My game predictably crashes in Hyrule fields, just past where you meet Hoz to help the monster hunters fight. I’m running an Nvidia 4070 with 32gb ram. It’s been running perfectly so far, even when I go into the depths.

Log:

00:01:53.655 |E| HLE.OsThread.& Application : Unhandled exception caught: System. Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> LibHac. Common. HorizonResultException: Result sNonRealDataVerificationFailed (2002-4604) : Hash error! at LibHac. Common. ThrowHelper. ThrowResult (Result result, String message) at LibHac. Tools.FsSystem. IntegrityVerificationStorage. ReadImp1(Int64 offset, Span 1 destination, IntegrityCheckLevel integrityCheckLevel) at LibHac. Tools.FsSystem. CachedStorage. ReadBlock(CacheBlock block, Int64 index) at LibHac.Tools.FsSystem. CachedStorage.GetBlock(Int64 blockIndex) at LibHac. Tools. FsSystem. CachedStorage. Read (Int64 offset, Span' 1 destination) at LibHac. Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count) at System. IO. Stream. Read (Span 1) at LibHac. Tools. FsSystem.StreamStorage.Read(Int64 offset, Span' 1 destination) at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtxcontext)inD:la \Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\F\FileSystemProxy\IStorage.cs:line35 at Invokestub_IStorage. Read(Object, Span 1) at system. Reflection.MethodBaseInvoker, InvokewithoneArg(object, BindingFlags, Binder, Object[], CultureInfo)|

### Reproduction steps

From the goblin settlement where you fight with Hoz, simply walk toward the ruins in the direction of the sky tower and the game crashes. 

### Log file

[Ryujinx_1.1.1141_2024-01-28_16-26-01.log](https://github.com/Ryujinx/Ryujinx/files/14079362/Ryujinx_1.1.1141_2024-01-28_16-26-01.log)

### OS

Windows 10

### Ryujinx version

1.1.1141

### CPU

Intel i9 

### GPU

Nvidia 4070

### RAM

32gb

### List of applied mods

None

**Comment by MetrosexualGarbodor** [comment]
Your game file is corrupted, dump it again from your Switch. 
In the future, please use discord for help.

**Comment by aylumbre** [comment]
Hey man did you ever fix this problem because i'm having the same exact issue you described...
