### ISSUE TITLE
[Bug] Purging Shader Cache allows the game to load faster

### ISSUE THREAD

**Issue by m3kwong** [Ryujinx/Ryujinx#6201]
### Description of the issue

Usually when a game is launched it will need to Compile Shaders.  If i purge Shader Cache, the game does not need to and loads without doing it.  As i play the game more and more everytime i start it compiles more and more shaders(numerical wise).  

When i purge shader again, the Compile Shader is skipped and game loads way faster. This is for any game.
### Reproduction steps

purge shader, run game, compile shader step isn't run and game loads faster. 

After playing game a few times, if you don't purge shader, it will start compiling shaders again.
d
### Log file

none

### OS

mac sonoma

### Ryujinx version

1.1.1141

### CPU

M2

### RAM

32

### List of applied mods

none

**Comment by MutantAura** [comment]
Intended behaviour.

**Comment by m3kwong** [comment]
Why not set it to purge on every load so games load faster without needing to compile shader?

**Comment by gdkchan** [comment]
> Why not set it to purge on every load so games load faster without needing to compile shader?

You can just disable `Enable Shader Cache` in the settings (graphics tab) if you want that behaviour.

**Comment by MutantAura** [comment]
The shader cache moves runtime stutters into a slightly longer boot time. If you prefer the fast boot but stuttery gameplay then do as gdkchan said above.

If you want minimal stuttering then you deal with a longer boot.

**Comment by m3kwong** [comment]
Just curious, why does it rebulid the shaders every time I restart?

**Comment by AcK77** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-what-are-shaders-and-why-do-i-need-them
