### ISSUE TITLE
[Bug]Titan Glory [0100FE801185E000] stuck on loading screen

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6202]
### Description of the issue

comes up with one developers screen then stuck on the loading screen

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1141_2024-01-29_16-55-32.log](https://github.com/Ryujinx/Ryujinx/files/14082017/Ryujinx_1.1.1141_2024-01-29_16-55-32.log)

### OS

Windows 10

### Ryujinx version

1.1.1141

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/2586 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
