### ISSUE TITLE
[Bug]Worms WMD [01001AE005166000] all the worms are invisible during gameplay

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6204]
### Description of the issue

all the worms are invisible during gameplay

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1141_2024-01-29_17-25-46.log](https://github.com/Ryujinx/Ryujinx/files/14082237/Ryujinx_1.1.1141_2024-01-29_17-25-46.log)

### OS

Windows 10

### Ryujinx version

1.1.1141

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/358 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
