### ISSUE TITLE
[Bug] Prince of Persia: The Lost Crown v1.0.2 [0100210019428000] [64-bit] -- incorrect color of some elements on MacOS version

### ISSUE THREAD

**Issue by mtaras0** [Ryujinx/Ryujinx#6212]
### Description of the issue

Some elements have color overlayed on them, but it's rendered incorrectly -- full bright green instead of just "regular" green. Here's how vines in one of the locations should look like vs how they look now. There are also smaller amounts of smaller elements that have the same problem with green (I thought it's how supposed to be so no screenshots). For a few moments of just fading something in or out those elements look how they should, but only briefly
<img width="1664" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/106077126/87c73ea9-6243-41b7-bf1e-383d4db3b0aa">
![ryujinx_capture_2024-01-30_00-27-25](https://github.com/Ryujinx/Ryujinx/assets/106077126/5aa333bd-640a-4d9c-a8a9-419a627ee502)

### Reproduction steps

1. Default settings, Metal renderer
2. Get to those elements, they are always like this

### Log file

[Ryujinx_1.1.1143_2024-01-30_00-25-55.log](https://github.com/Ryujinx/Ryujinx/files/14088208/Ryujinx_1.1.1143_2024-01-30_00-25-55.log)

### OS

MacOS Sonoma 14.3

### Ryujinx version

1.1.1143

### Game version

1.0.3

### CPU

M1

### GPU

M1

### RAM

8GB

### List of applied mods

None

**Comment by showme032** [comment]
It gets pretty much unplayable in the shipyard part, as it's not only vines, but the platforms/surrounding itself. Latest ryujinx 1.1.1144 on M1 Pro:
<img width="1728" alt="Screenshot 2024-01-29 at 20 34 31" src="https://github.com/Ryujinx/Ryujinx/assets/8236625/2e523b69-901e-447f-bcc5-8cc0a5c90cbd">
<img width="1728" alt="Screenshot 2024-01-29 at 20 29 09" src="https://github.com/Ryujinx/Ryujinx/assets/8236625/f925e549-0dc0-4cf2-bf42-aaebd00e742e">

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4859.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.
