### ISSUE TITLE
[Bug]  Crashes on Windows 11. 

### ISSUE THREAD

**Issue by JamesNorword2nd** [Ryujinx/Ryujinx#6216]
### Description of the issue

The issue is after the latest github version the emulator crashes when starting ToTk.  I'll show you in the log files.  after version 1.1.1144 it almost completely loads the game but is missing some shaders for some reason.   Then, it will load the game and then crash after or right before the title screen. Never gets into gameplay.

### Reproduction steps

Try to play the game in Windows and watch it crash.

### Log file

[Ryujinx_1.1.1144_2024-01-29_20-53-53.log](https://github.com/Ryujinx/Ryujinx/files/14089520/Ryujinx_1.1.1144_2024-01-29_20-53-53.log)
[Ryujinx_1.1.1144_2024-01-29_20-35-54.log](https://github.com/Ryujinx/Ryujinx/files/14089521/Ryujinx_1.1.1144_2024-01-29_20-35-54.log)
[Ryujinx_1.1.1144_2024-01-29_20-35-08.log](https://github.com/Ryujinx/Ryujinx/files/14089522/Ryujinx_1.1.1144_2024-01-29_20-35-08.log)

### OS

Windows 10

### Ryujinx version

1.1.1144

### Game version

1.2.0

### CPU

Intel© Core™ i7-10870H CPU @ 2.20GHz × 8

### GPU

NVIDA RTX 270 

### RAM

16GB

**Comment by JamesNorword2nd** [comment]
Also, the actual game saves between linux and windows get corrupted when moving them.  If I leave the one on linux alone it isn't corrupted.  But, if I try copying the files to windows it will get corrupted.

**Comment by gdkchan** [comment]
There is something preventing the emulator from accessing the save data on Windows, might be some antivirus software.

**Comment by JamesNorword2nd** [comment]
Ah, yes, thank you for replying.  I think that what happened was fixed you see.  I was tinkering around and found that I copied the entire user/save directory including the numbered files where I think they differed on windows.  For whatever reason saving the individual games worked out just fine.  It doesn't crash so I will close this pesky issue for you.
