### ISSUE TITLE
[Bug] Zelda TOTK crash in several minuets after launching the game

### ISSUE THREAD

**Issue by ShawnWoooo** [Ryujinx/Ryujinx#6224]
### Description of the issue

On my 2019 16 inches Intel based MacBook Pro. the game runs super unstable and it crash in 1 minuet after the title menu. I tried it on with my 5500M GPU that came with my 16 Inches MacBook Pro, and egpu AMD 6800XT as well, and end with the same result. heard about that RyujinX does not support AMD card, just wondering any plan on fixing this?

Mac OS Sonoma 14.3
2.3 GHz 8-Core Intel i9
RAM: 64GB
AMD 5500M
Egpu: 6800XT

### Reproduction steps

tried V-Sync On and off, different. GPU setting, CPU setting, none of them work well

### Log file

[Ryujinx_1.1.1139_2024-01-27_04-11-35.log](https://github.com/Ryujinx/Ryujinx/files/14094021/Ryujinx_1.1.1139_2024-01-27_04-11-35.log)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ryujinx [10217]
Path:                  /Applications/Ryujinx.app/Contents/MacOS/Ryujinx
Identifier:            org.ryujinx.Ryujinx
Version:               1.1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-30 15:09:32.2143 +0800
OS Version:            macOS 14.3 (23D56)
Report Version:        12
Bridge OS Version:     8.3 (21P3049)
Anonymous UUID:        F33F4B0F-9121-0A5C-9197-9D76B2B7B328

Sleep/Wake UUID:       6A9BEB51-58C6-4852-8E73-C0A68EBFA91F

Time Awake Since Boot: 97000 seconds
Time Since Wake:       1964 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Ryujinx [10217]

ID   Vend/Dev
0cb8 731f1002
2ed9 73bf1002
Seconds Ago   ID   Type
   150000.0   0cb8 Attach
   150000.0   0cb8 Detach
    84000.0   2ed9 Attach
    25000.0   2ed9 Detach
     1900.0   2ed9 Attach

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff812ac57a2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff812afdf30 pthread_kill + 262
2   libsystem_c.dylib             	    0x7ff812a1ca49 abort + 126
3   Ryujinx                       	       0x110283577 PROCAbort + 55
4   Ryujinx                       	       0x11028344d PROCEndProcess(void*, unsigned int, int) + 301
5   Ryujinx                       	       0x10fdc26f3 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 1107
6   Ryujinx                       	       0x10fdc273d DispatchManagedException(PAL_SEHException&, bool) + 61
7   Ryujinx                       	       0x10fd2b429 IL_Throw(Object*) + 521
8   ???                           	       0x11eac118a ???
9   ???                           	       0x11b375958 ???
10  ???                           	       0x11b373b92 ???
11  ???                           	       0x11b37356b ???
12  ???                           	       0x11b3721e3 ???
13  ???                           	       0x11a938315 ???
14  ???                           	       0x119f3bd52 ???
15  ???                           	       0x118ff62d1 ???
16  Ryujinx                       	       0x10fe6f931 CallDescrWorkerInternal + 124
17  Ryujinx                       	       0x10fcc9ec2 MethodDescCallSite::CallTargetWorker(unsigned long long const*, unsigned long long*, int) + 1666
18  Ryujinx                       	       0x10fbc00a9 RunMain(MethodDesc*, short, int*, PtrArray**) + 713
19  Ryujinx                       	       0x10fbc04a2 Assembly::ExecuteMainMethod(PtrArray**, int) + 434
20  Ryujinx                       	       0x10fbeaefd CorHost2::ExecuteAssembly(unsigned int, char16_t const*, int, char16_t const**, unsigned int*) + 733
21  Ryujinx                       	       0x1101a6dd4 coreclr_execute_assembly + 196
22  Ryujinx                       	       0x10fb924bb run_app_for_context(hostpolicy_context_t const&, int, char const**) + 1275
23  Ryujinx                       	       0x10fb932ca corehost_main + 266
24  Ryujinx                       	       0x10fb620e0 fx_muxer_t::handle_exec_host_command(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, host_startup_info_t const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::unordered_map<known_options, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>, known_options_hash, std::__1::equal_to<known_options>, std::__1::allocator<std::__1::pair<known_options const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>>> const&, int, char const**, int, host_mode_t, bool, char*, int, int*) + 1360
25  Ryujinx                       	       0x10fb6111d fx_muxer_t::execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int, char const**, host_startup_info_t const&, char*, int, int*) + 621
26  Ryujinx                       	       0x10fb5d44a hostfxr_main_bundle_startupinfo + 250
27  Ryujinx                       	       0x10fbac8a1 exe_start(int, char const**) + 1105
28  Ryujinx                       	       0x10fbacbd0 main + 176
29  dyld                          	    0x7ff812773386 start + 1942

### OS

Sonoma 14.3

### Ryujinx version

every version

### Game version

tested on 1.0.0 and 1.2.1

### CPU

2.3 GHz 8-Core Intel i9

### GPU

AMD 5500M, AMD 6800XT, 

### RAM

64G

### List of applied mods

none

**Comment by piplup55** [comment]
the mac os amd drivers aren't the greatest, we only really recommand the mac builds for m series mac's, on intel mac's it's better to use windows or linux as they have better drivers for amd cards

**Comment by AcK77** [comment]
As the previous comment said, macOS AMD drivers is not the best way to get games playable... We can't do much more here sadly, in that way I close this issue. You can report the status here : https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598 if you want.
Thanks.
