### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by marleyc02** [Ryujinx/Ryujinx#6225]
### Description of the issue

cannot open on Mac, on os 13 and it is giving me the 'apple cannot check security' error.

### Reproduction steps

unsure

### Log file

N/A

### OS

Mac OS 13.0.0

### Ryujinx version

N/A

### Game version

N/A

### List of applied mods

N/A

**Comment by felixfrey** [comment]
Not a bug. See: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

You can also grant an exception for a blocked app by clicking the Open Anyway button in Privacy & Security settings. This button is available for about an hour after you try to open the app.

To change these settings on your Mac, choose Apple menu  > System Settings, then click Privacy & Security  in the sidebar. (You may need to scroll down.)
