### ISSUE TITLE
[Bug]Spelunker Party 010021F004270000 doesnt detect the controllers properly 

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6231]
### Description of the issue

load the game
at the title screen the game doesn't detect the controllers properly 

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1152_2024-01-31_16-36-41.log](https://github.com/Ryujinx/Ryujinx/files/14109254/Ryujinx_1.1.1152_2024-01-31_16-36-41.log)

### OS

Windows 10

### Ryujinx version

1.1.1151

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/692 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
