### ISSUE TITLE
[Bug]Mythology Waifus Mahjong [0100C7101A5BE000] crashes out at developers screen

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6233]
### Description of the issue

at the first developers screen it crashes out
00:00:20.598 |W| HLE.GuestThread.48 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.49 KernelSvc : SendSyncRequest() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.61 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.60 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.58 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.57 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.56 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.55 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.53 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.598 |W| HLE.GuestThread.51 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.682 |W| HLE.GuestThread.46 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:20.682 |W| HLE.GuestThread.63 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.682 |W| HLE.GuestThread.64 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.683 |W| HLE.GuestThread.65 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.683 |W| HLE.GuestThread.66 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.683 |W| HLE.GuestThread.67 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.683 |W| HLE.GuestThread.69 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.683 |W| HLE.GuestThread.70 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:20.683 |W| HLE.GuestThread.71 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1152_2024-01-31_17-31-28.log](https://github.com/Ryujinx/Ryujinx/files/14109754/Ryujinx_1.1.1152_2024-01-31_17-31-28.log)

### OS

Windows 10

### Ryujinx version

1.1.1151

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4499 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
