### ISSUE TITLE
[Bug] Cheat manager not working on Mac M1

### ISSUE THREAD

**Issue by svnv-svsv-jm** [Ryujinx/Ryujinx#6239]
### Description of the issue

I updated the app to latest version, and now Ryujinx won't see the cheats in the Cheat Manager.

### Reproduction steps

I pasted to `contents\0100a3d008c5c000\cheat_name\cheats\C01884F294C053C4.txt` but I still can't see any cheat in the Cheat Manager.

I also tried pasting to `contents\0100a3d008c5c000\cheats\C01884F294C053C4.txt`, same result.

### Log file

No log.

### OS

Mac M1

### Ryujinx version

1.1.1154

### List of applied mods

No mod.

**Comment by AcK77** [comment]
Could you provide a log file please?
Are your sure the buildid is the same as the game your trying to run since Pokémon Scarlet have a bunch of updates?

**Comment by AcK77** [comment]
No answer. I close the issue seems it’s probably a wrong game’s build ID as no one reported the same issue.
You can goes to our discord for support if needed.
Thanks.
