### ISSUE TITLE
[Bug] monster hunter gen u

### ISSUE THREAD

**Issue by Solar21345** [Ryujinx/Ryujinx#6249]
### Description of the issue

the lighting on the maps gets completely fucked up and on some maps is just unplayable.
![Ryujinx 1 1 0-ldn3 1 3 - MONSTER HUNTER GENERATIONS ULTIMATE v1 4 0 (0100770008DD8000) (32-bit) 2_2_2024 9_44_27 PM](https://github.com/Ryujinx/Ryujinx/assets/158675809/bc2f8f9a-b695-4709-941b-a6bb5cf56622)
![Ryujinx 1 1 0-ldn3 1 3 - MONSTER HUNTER GENERATIONS ULTIMATE v1 4 0 (0100770008DD8000) (32-bit) 2_2_2024 9_54_12 PM](https://github.com/Ryujinx/Ryujinx/assets/158675809/bc76b8a5-0bdb-47bd-97c4-65c92e2e56f1)
![20240202_215703](https://github.com/Ryujinx/Ryujinx/assets/158675809/649275e6-c08b-4145-87cb-909497f3c630)

### Reproduction steps

I have no clue, i just assume this is a bug as when i first started nothing like this happened and only just recently happened.

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2024-02-02_21-46-19.log](https://github.com/Ryujinx/Ryujinx/files/14149657/Ryujinx_1.1.0-ldn3.1.3_2024-02-02_21-46-19.log)

### OS

windows 10

### Ryujinx version

14.1.1

### Game version

1.4.0 

### CPU

i5-9400F

### RAM

8 GB

### List of applied mods

60 fps mod

**Comment by AcK77** [comment]
You use an outdated version of the emulator, please try again with the latest version.
If an issue still occurs, you can report it here : https://github.com/Ryujinx/Ryujinx-Games-List/issues/511
Thanks.
