### ISSUE TITLE
[Feature Request] Time Played

### ISSUE THREAD

**Issue by rcv11x** [Ryujinx/Ryujinx#6256]
### Overview

The user can see in the column of the interface the time played in each game.

### Smaller details

I'm not sure but I think it could be stored in a json configuration file.

### Nature of request

I'm not quite sure what to put here

### Why would this feature be useful?

It would be useful to be able to show the time played per game, I think it is an interesting feature.

**Comment by TSRBerry** [comment]
This feature already exists.

Avalonia:
![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/6885b0f2-1562-43ad-a9ff-fc5790d80f41)
GTK:
![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/d5d9d12b-675d-49c0-8656-45119dacd0ce)
