### ISSUE TITLE
[Bug] The Legend of Zelda: Tears of the Kingdom v1.2.1

### ISSUE THREAD

**Issue by gugaucb** [Ryujinx/Ryujinx#6257]
### Description of the issue

When I tried use the Gamesir T4 Cyclone Pro, I received this message: **Your current configuration is invalid. Open settings and reconfigure your inputs. Docker mode set. Handheld control should be disabled.** in loop.

When I configure the controller type to Joycon left or right, the message disappear.

<img width="1724" alt="Screenshot 2024-02-05 at 15 12 24" src="https://github.com/Ryujinx/Ryujinx/assets/1793649/89c791c9-4f34-446c-b2f3-7f6dde30f1d6">
<img width="1098" alt="Screenshot 2024-02-05 at 15 13 40" src="https://github.com/Ryujinx/Ryujinx/assets/1793649/ad8b1523-fe2f-4253-83d7-789e04c3c4e1">

### Reproduction steps

Execute the game
Configure the input device to Nintendo Switch Pro Controller
Set Controller Type to Pro Controller
Apply settings
Press any button

### Log file

The software didn`t produce log.

### OS

macOS Sonoma 14.3

### Ryujinx version

1.1.1160

### Game version

1.2.1

### CPU

Apple M1 Max

### GPU

Apple M1 Max

### RAM

32GB

### List of applied mods

I don't use.

**Comment by ekuland** [comment]
_**Exactly**_ 1 controller. You have controllers setup for players other than 1. Remove them. Join the discord for further support.

**Comment by DASOSA777** [comment]
U figured out how to fix that?
