### ISSUE TITLE
[Bug] An error occurred during Ryujinx update (updater.sh:50)

### ISSUE THREAD

**Issue by 1075dn** [Ryujinx/Ryujinx#6258]
### Description of the issue

An error occurred during Ryujinx update (updater.sh:50)

### Reproduction steps

This issue is persisting. What other information do you need?

### Log file

N/A

### OS

Mac 14

### Ryujinx version

1.1.1159 ==>1.1.1160

### CPU

M2

### GPU

M2

### RAM

8GB

**Comment by AcK77** [comment]
The line is:
```
rm -rf "$INSTALL_DIRECTORY"
```

Check if you have enough perms to delete the installation folder.
It's probably more an issue at your side than an issue at the script side.
I close this issue for now, can be reopened if there is something wrong in our script.
Thanks.

**Comment by randallbruder** [comment]
@1075dn I was having the same problem: macOS doesn't allow an app to update/modify itself if you're running it from the same folder you unzipped it into (I'd assume it's an anti-malware protection?) If you're still having the updating issue, just move the Ryujinx.app to another folder on your Mac.
