### ISSUE TITLE
[Feature Request] Add the old "Open mods directory" buttons again

### ISSUE THREAD

**Issue by Fafner1000** [Ryujinx/Ryujinx#6262]
### Overview

Please add the option to open the mods directory. This was already implemented but was removed recently.

Cheats and mods break with every update so it is quite often. Having to get the game ID and the manually navigate to app folder and look for a specific ID in a folder full of numbers that are pretty similar takes a while and you can easily make a mistake. This was already implemented and it took 1 click and 1 sec to get there automatically. 
There is no benefit for the user or the devs to remove this. And yes, I know that after you add mods the first there is a little folder icon in the mods manager that does this but it only appears after you add any mod and it doesnt work with cheats folder. So please bring the option back, thanks.

### Smaller details

Was already implemented but removed, just add it back please.

### Nature of request

Makes life easier to users.

### Why would this feature be useful?

Saves A LOT of time for people that uses cheats and likes to mess around with mods.

**Comment by Mashrien** [comment]
As well as opening the mods directory, it can be difficult to find the correct folder in which to drop a cheats file; to add to the dropdown, just below cheats, might be to open the cheats folder that the emulator is expecting - and create said folder if it doesn't exist.
(Can prompt for creation permission upon clicking said listViewMenuItem)

**Comment by Mashrien** [comment]
As well as opening the mods directory, it can be difficult to find the correct folder in which to drop a cheats file; to add to the dropdown, just below cheats, might be to open the cheats folder that the emulator is expecting - and create said folder if it doesn't exist.
(Can prompt for creation permission upon clicking said toolStripMenuItem)

**Comment by TSRBerry** [comment]
Potentially closed by #6237.

**Comment by Fafner1000** [comment]
Great, pretty close to what I was asking. Thanks.

**Comment by IsaacMarovitz** [comment]
Mods should be managed in the new Mod Manager, cheats have no way of being managed in the UI yet which is why I'm re-adding the button.

**Comment by AcK77** [comment]
Fixed in https://github.com/Ryujinx/Ryujinx/pull/6237
