### ISSUE TITLE
[Bug]Factorio [01004200189f4000] freezes up on the menu

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6287]
### Description of the issue

freezes up on the menu

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1173_2024-02-10_16-20-56.log](https://github.com/Ryujinx/Ryujinx/files/14228615/Ryujinx_1.1.1173_2024-02-10_16-20-56.log)

### OS

Windows 10

### Ryujinx version

1.1.1173

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by benderscruffy** [comment]
Doodle Derby [0100F2C00F060000] has the same problem with
GPU.MainThread Gpu UpdateVertexAttribState: Invalid attribute format 0x25E00000.

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4303 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.
