### ISSUE TITLE
[Bug] Updates destroy user data in portable mode on macOS

### ISSUE THREAD

**Issue by moutella** [Ryujinx/Ryujinx#6299]
### Description of the issue

When using portable mode putting the portable folder inside the package content, as taught in this issue #4308, whenever Ryujinx updates, every configuration file is lost, along with save data, and anything else that is found within the portable folder.

### Reproduction steps

1. Download any non-latest version of Ryujinx
2. Open it, do not update, configure it in portable mode, add your keys etc
3. Close it and re-open it
4. When prompted if you want to update, accept it.
5. Open updated Ryujinx. It will ask you to configure your keys again.

### Log file

Does not apply

### OS

macOS

### Ryujinx version

1.1.1164

### Additional context?

Am willing to try and solve this myself, just putting the issue here if anyone else has similar problems

**Comment by jcm93** [comment]
You are not supposed to put things inside the application bundle on macOS. When Ryujinx updates, the entire app bundle is replaced. Even if Ryujinx didn't destroy the entire app bundle, it would still be a bad idea.

I haven't looked into portable mode very closely, but I know that it goes against the way macOS is designed for applications to run, at least as currently implemented. On top of that, there are other issues currently that make Ryujinx not have a valid code signature, so any attempt at referencing a directory outside the app bundle and the application support folder could just fail outright.

I'd recommend at a minimum waiting for #6238 before attempting portable mode, and when you do, don't put things inside the .app bundle.

**Comment by moutella** [comment]
While I do agree with you that it seems like a bad idea, it does work and it seems reasonably easy to fix, so I guess it wouldn't hurt to actually support it this way?

Looking at [this file](https://github.com/Ryujinx/Ryujinx/blob/16fa98370472f843ebdae5addbb00e26899ebe55/distribution/macos/updater.sh), I believe all that needs to be done is to add something like this, before replacing the old bundle with the new bundle

```sh
# Transfer portable mode data if it exists
if [ -d "$INSTALL_DIRECTORY/Contents/MacOS/portable" ]; then
    cp -r "$INSTALL_DIRECTORY/Contents/MacOS/portable" "$NEW_APP_DIRECTORY/Contents/MacOS/portable"
fi
```

I also created a few scripts to help me do this by myself, since it's easier that way
`pre_update.sh`
```sh
INSTALL_DIRECTORY='Ryujinx.app'

if [ -d "$INSTALL_DIRECTORY/Contents/MacOS/portable" ]; then
    cp -r "$INSTALL_DIRECTORY/Contents/MacOS/portable" "./portable"
fi
```
`post_update.sh`
```sh
INSTALL_DIRECTORY='Ryujinx.app'

if ! [ -d "$INSTALL_DIRECTORY/Contents/MacOS/portable" ]; then
    cp -r "./portable" "$INSTALL_DIRECTORY/Contents/MacOS/portable" 
    rm -rf "./portable"
fi
```

However, while testing these scripts, I realized that if you just put the portable folder at the same folder that the bundle is, Ryujinx also recognizes it. So I guess this issue is unecessary, since there is an easy way to use portable mode without having to mess with the bundle.

After these tests, I decided to start using the portable folder out of the bundle, but I believe that some people would find it "neat" to have everything inside the bundle, so I hope this helps anyone who wishes to use it that way
