### ISSUE TITLE
[Bug] Can someone please help me out?

### ISSUE THREAD

**Issue by DreadwyrmBahamut** [Ryujinx/Ryujinx#6307]
### Description of the issue

 This is the crash report. As soon as i launch ryujinx it just crashes immediately, does it with YuZu too, this is very bizarre in the past I just used system restore to an earlier point and it was working. I am suspecting this has something to do with OneDrive as its been driving me absolutely INSANE. I have uninstalled OneDrive from my computer (100% all traces with revo uninstaller), and completely removed Ryujinx from my computer, everything, and tried fresh install.. still not working. Someone please help me

Version=1

EventType=APPCRASH

EventTime=133522518979957538

ReportType=2

Consent=1

UploadTime=133522518986716418

ReportStatus=268435456

ReportIdentifier=ed0f61ad-2de0-45f0-8ced-d860cf690684

IntegratorReportIdentifier=0bfaa580-6f76-4cf0-ad2f-e668942708d8

Wow64Host=34404

NsAppName=Ryujinx.exe

OriginalFilename=Ryujinx.dll

AppSessionGuid=00004b7c-0001-0084-e8ac-6608065eda01

TargetAppId=W:0006a6432f01ae397cf6572b02af4e7ce8e900000000!00009d13145edeee9cf42d7ed35108d56be49ae9e238!Ryujinx.exe

TargetAppVer=2023//11//30:08:27:44!0!Ryujinx.exe

BootId=4294967295

TargetAsId=712

IsFatal=1

Response.BucketId=5493c8c7ba0dd29a8291ff5e0ab59081

Response.BucketTable=4

Response.LegacyBucketId=1338131343677427841

Response.type=4

Sig[0].Name=Application Name

Sig[0].Value=Ryujinx.exe

Sig[1].Name=Application Version

Sig[1].Value=1.1.1192.0

Sig[2].Name=Application Timestamp

Sig[2].Value=65684780

Sig[3].Name=Fault Module Name

Sig[3].Value=Ryujinx.exe

Sig[4].Name=Fault Module Version

Sig[4].Value=1.1.1192.0

Sig[5].Name=Fault Module Timestamp

Sig[5].Value=65684780

Sig[6].Name=Exception Code

Sig[6].Value=c0000005

Sig[7].Name=Exception Offset

Sig[7].Value=00000000002270db

DynamicSig[1].Name=OS Version

DynamicSig[1].Value=10.0.22631.2.0.0.768.101

DynamicSig[2].Name=Locale ID

DynamicSig[2].Value=1033

DynamicSig[22].Name=Additional Information 1

DynamicSig[22].Value=86a1

DynamicSig[23].Name=Additional Information 2

DynamicSig[23].Value=86a150c169ead3bd11f7078c438cc07e

DynamicSig[24].Name=Additional Information 3

DynamicSig[24].Value=2874

DynamicSig[25].Name=Additional Information 4

DynamicSig[25].Value=2874465e7e7ff3d65af1cf4378ec0913

UI[2]=C:\Users\KingO\OneDrive\Desktop\publish\Ryujinx.exe

LoadedModule[0]=C:\Users\KingO\OneDrive\Desktop\publish\Ryujinx.exe

LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll

LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL

LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll

LoadedModule[4]=C:\Windows\System32\ADVAPI32.dll

LoadedModule[5]=C:\Windows\System32\msvcrt.dll

LoadedModule[6]=C:\Windows\System32\sechost.dll

LoadedModule[7]=C:\Windows\System32\bcrypt.dll

LoadedModule[8]=C:\Windows\System32\RPCRT4.dll

LoadedModule[9]=C:\Windows\System32\ole32.dll

LoadedModule[10]=C:\Windows\System32\msvcp_win.dll

LoadedModule[11]=C:\Windows\System32\ucrtbase.dll

LoadedModule[12]=C:\Windows\System32\GDI32.dll

LoadedModule[13]=C:\Windows\System32\win32u.dll

LoadedModule[14]=C:\Windows\System32\gdi32full.dll

LoadedModule[15]=C:\Windows\System32\USER32.dll

LoadedModule[16]=C:\Windows\System32\combase.dll

LoadedModule[17]=C:\Windows\System32\OLEAUT32.dll

LoadedModule[18]=C:\Windows\System32\SHELL32.dll

LoadedModule[19]=C:\Windows\System32\IMM32.DLL

LoadedModule[20]=C:\Windows\System32\bcryptPrimitives.dll

LoadedModule[21]=C:\Windows\SYSTEM32\kernel.appcore.dll

LoadedModule[22]=C:\Windows\SYSTEM32\icu.dll

LoadedModule[23]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22621.3085_none_57ff6980ce140777\gdiplus.dll

LoadedModule[24]=C:\Windows\system32\uxtheme.dll

LoadedModule[25]=C:\Windows\System32\MSCTF.dll

LoadedModule[26]=C:\Windows\SYSTEM32\windows.storage.dll

LoadedModule[27]=C:\Windows\SYSTEM32\wintypes.dll

LoadedModule[28]=C:\Windows\System32\SHCORE.dll

LoadedModule[29]=C:\Windows\System32\shlwapi.dll

LoadedModule[30]=C:\Windows\SYSTEM32\profapi.dll

LoadedModule[31]=C:\Windows\SYSTEM32\vulkan-1.dll

LoadedModule[32]=C:\Windows\SYSTEM32\CFGMGR32.dll

LoadedModule[33]=C:\Windows\system32\dxgi.dll

LoadedModule[34]=C:\Windows\SYSTEM32\dxcore.dll

LoadedModule[35]=C:\Windows\SYSTEM32\windows.staterepositorycore.dll

LoadedModule[36]=C:\Windows\SYSTEM32\directxdatabasehelper.dll

LoadedModule[37]=C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2401.3.0_x64__8wekyb3d8bbwe\x64\vulkan_dzn.dll

LoadedModule[38]=C:\Windows\SYSTEM32\VERSION.dll

LoadedModule[39]=C:\Windows\System32\DriverStore\FileRepository\u0398667.inf_amd64_f7fcccf565a8b59e\B398200\amdvlk64.dll

LoadedModule[40]=C:\Windows\System32\SETUPAPI.dll

LoadedModule[41]=C:\Windows\SYSTEM32\WINMM.dll

LoadedModule[42]=C:\Windows\SYSTEM32\amdihk64.dll

LoadedModule[43]=C:\ProgramData\obs-studio-hook\graphics-hook64.dll

LoadedModule[44]=C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2401.3.0_x64__8wekyb3d8bbwe\x64\DXIL.dll

LoadedModule[45]=C:\Windows\SYSTEM32\d3d12.dll

LoadedModule[46]=C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2401.3.0_x64__8wekyb3d8bbwe\x64\D3D12Core.dll

LoadedModule[47]=C:\Windows\SYSTEM32\dwmapi.dll

LoadedModule[48]=C:\Windows\SYSTEM32\DEVOBJ.dll

LoadedModule[49]=C:\Windows\System32\WINTRUST.dll

LoadedModule[50]=C:\Windows\System32\CRYPT32.dll

LoadedModule[51]=C:\Windows\SYSTEM32\MSASN1.dll

LoadedModule[52]=C:\Windows\System32\DriverStore\FileRepository\u0398667.inf_amd64_f7fcccf565a8b59e\B398200\amdxc64.dll

LoadedModule[53]=C:\Windows\SYSTEM32\D3DSCache.dll

LoadedModule[54]=C:\Windows\SYSTEM32\USERENV.dll

LoadedModule[55]=C:\Windows\SYSTEM32\twinapi.appcore.dll

State[0].Key=Transport.DoneStage1

State[0].Value=1

OsInfo[0].Key=vermaj

OsInfo[0].Value=10

OsInfo[1].Key=vermin

OsInfo[1].Value=0

OsInfo[2].Key=verbld

OsInfo[2].Value=22631

OsInfo[3].Key=ubr

OsInfo[3].Value=3085

OsInfo[4].Key=versp

OsInfo[4].Value=0

OsInfo[5].Key=arch

OsInfo[5].Value=9

OsInfo[6].Key=lcid

OsInfo[6].Value=1033

OsInfo[7].Key=geoid

OsInfo[7].Value=244

OsInfo[8].Key=sku

OsInfo[8].Value=101

OsInfo[9].Key=domain

OsInfo[9].Value=0

OsInfo[10].Key=prodsuite

OsInfo[10].Value=768

OsInfo[11].Key=ntprodtype

OsInfo[11].Value=1

OsInfo[12].Key=platid

OsInfo[12].Value=10

OsInfo[13].Key=sr

OsInfo[13].Value=0

OsInfo[14].Key=tmsi

OsInfo[14].Value=222534687

OsInfo[15].Key=osinsty

OsInfo[15].Value=1

OsInfo[16].Key=iever

OsInfo[16].Value=11.1.22621.0-11.0.1000

OsInfo[17].Key=portos

OsInfo[17].Value=0

OsInfo[18].Key=ram

OsInfo[18].Value=7889

OsInfo[19].Key=svolsz

OsInfo[19].Value=1906

OsInfo[20].Key=wimbt

OsInfo[20].Value=0

OsInfo[21].Key=blddt

OsInfo[21].Value=220506

OsInfo[22].Key=bldtm

OsInfo[22].Value=1250

OsInfo[23].Key=bldbrch

OsInfo[23].Value=ni_release

OsInfo[24].Key=bldchk

OsInfo[24].Value=0

OsInfo[25].Key=wpvermaj

OsInfo[25].Value=0

OsInfo[26].Key=wpvermin

OsInfo[26].Value=0

OsInfo[27].Key=wpbuildmaj

OsInfo[27].Value=0

OsInfo[28].Key=wpbuildmin

OsInfo[28].Value=0

OsInfo[29].Key=osver

OsInfo[29].Value=10.0.22621.3085.amd64fre.ni_release.220506-1250

OsInfo[30].Key=buildflightid

OsInfo[31].Key=edition

OsInfo[31].Value=Core

OsInfo[32].Key=ring

OsInfo[32].Value=Retail

OsInfo[33].Key=expid

OsInfo[33].Value=RS:1A75C,MD:283BAEF,ME:28279A6,FX:12C80CE4,MD:2A69053,MD:255521A

OsInfo[34].Key=fconid

OsInfo[34].Value=15546617,0,2,0;18299130,0,2,0;19193777,0,2,0;19194204,0,2,0;19195493,0,2,0;19195502,0,2,0;19638787,0,2,0;23531064,2,2,0;23562335,2,2,0;23563673,2,2,0;32862274,0,2,1;32862275,0,2,0;35681102,0,1,0;36803287,0,2,1;36803295,0,2,0;36803303,0,2,1;38277973,0,1,0;38859191,0,2,1;39145991,0,2,0;39146010,0,1,0;39263329,1,2,0;39281392,0,2,0;40025975,0,1,0;40616880,0,1,1;40733296,0,2,0;40883769,0,1,0;40981503,0,1,0;41135193,0,1,1;41137130,0,1,0;41249924,0,2,1;41313221,0,2,0;41342175,0,1,0;41557840,0,2,0;41655236,0,2,1;41744267,0,2,1;41772259,0,2,1;41799415,0,2,1;42052423,0,2,0;42092123,0,2,0;42105254,0,2,1;42235377,0,2,0;42921948,0,2,1;42922989,0,2,1;42963857,0,2,1;43133808,1,2,1;43169616,0,1,1;43203978,0,2,1;43572857,0,2,1;43695740,0,2,0;43698028,0,2,0;43772553,0,1,0;43844371,0,1,1;43866633,0,0,0;43978769,0,1,1;43995105,0,2,0;43995122,0,2,0;43998261,0,2,1;44325080,0,1,1;44470355,0,1,0;44521793,0,1,0;44552141,0,1,0;44774051,0,2,0;44776738,0,2,1;44860385,0,2,1;45113694,0,2,1;45185354,0,2,0;45187531,0,2,0;45232725,0,2,0;45732051,0,2,0;45786062,0,2,1;45796396,0,2,0;45949789,0,0,0;45951844,0,2,0;45952583,0,0,0;45952594,0,2,0;45952795,0,2,0;45952819,0,2,0;45952823,0,2,0;45952872,0,2,0;45991456,0,1,1;45994554,0,2,0;45999439,0,0,0;46009617,0,0,0;46094352,0,0,1;46111200,0,2,1;46251949,0,2,0;46541070,0,2,0;46551074,0,1,0;46551941,0,0,1;46557400,0,1,1;46559584,1,2,0;46591190,0,2,1;46604216,0,2,1;46619189,0,2,1;46717502,0,2,0;46752087,0,2,0;46969703,0,1,0;46982417,0,2,1;47205155,0,2,0;47526873,1,2,1;47557358,0,0,1;47991031,0,2,1;48057519,0,2,1

OsInfo[35].Key=containerid

OsInfo[36].Key=containertype

OsInfo[37].Key=edu

OsInfo[37].Value=0

OsInfo[38].Key=servicinginprogress

OsInfo[38].Value=0

OsInfo[39].Key=featureupdatependingreboot

OsInfo[39].Value=0

FriendlyEventName=Stopped working

ConsentKey=APPCRASH

AppName=Ryujinx

AppPath=C:\Users\KingO\OneDrive\Desktop\publish\Ryujinx.exe

NsPartner=windows

NsGroup=windows8

ApplicationIdentity=AAB4B797DBE11DC81AC6E18B88AD3C72

MetadataHash=1106609642

### Reproduction steps

I have no idea, maybe download the disgusting OneDrive? I'm not sure what the cause is.

### Log file

Version=1

EventType=APPCRASH

EventTime=133522518979957538

ReportType=2

Consent=1

UploadTime=133522518986716418

ReportStatus=268435456

ReportIdentifier=ed0f61ad-2de0-45f0-8ced-d860cf690684

IntegratorReportIdentifier=0bfaa580-6f76-4cf0-ad2f-e668942708d8

Wow64Host=34404

NsAppName=Ryujinx.exe

OriginalFilename=Ryujinx.dll

AppSessionGuid=00004b7c-0001-0084-e8ac-6608065eda01

TargetAppId=W:0006a6432f01ae397cf6572b02af4e7ce8e900000000!00009d13145edeee9cf42d7ed35108d56be49ae9e238!Ryujinx.exe

TargetAppVer=2023//11//30:08:27:44!0!Ryujinx.exe

BootId=4294967295

TargetAsId=712

IsFatal=1

Response.BucketId=5493c8c7ba0dd29a8291ff5e0ab59081

Response.BucketTable=4

Response.LegacyBucketId=1338131343677427841

Response.type=4

Sig[0].Name=Application Name

Sig[0].Value=Ryujinx.exe

Sig[1].Name=Application Version

Sig[1].Value=1.1.1192.0

Sig[2].Name=Application Timestamp

Sig[2].Value=65684780

Sig[3].Name=Fault Module Name

Sig[3].Value=Ryujinx.exe

Sig[4].Name=Fault Module Version

Sig[4].Value=1.1.1192.0

Sig[5].Name=Fault Module Timestamp

Sig[5].Value=65684780

Sig[6].Name=Exception Code

Sig[6].Value=c0000005

Sig[7].Name=Exception Offset

Sig[7].Value=00000000002270db

DynamicSig[1].Name=OS Version

DynamicSig[1].Value=10.0.22631.2.0.0.768.101

DynamicSig[2].Name=Locale ID

DynamicSig[2].Value=1033

DynamicSig[22].Name=Additional Information 1

DynamicSig[22].Value=86a1

DynamicSig[23].Name=Additional Information 2

DynamicSig[23].Value=86a150c169ead3bd11f7078c438cc07e

DynamicSig[24].Name=Additional Information 3

DynamicSig[24].Value=2874

DynamicSig[25].Name=Additional Information 4

DynamicSig[25].Value=2874465e7e7ff3d65af1cf4378ec0913

UI[2]=C:\Users\KingO\OneDrive\Desktop\publish\Ryujinx.exe

LoadedModule[0]=C:\Users\KingO\OneDrive\Desktop\publish\Ryujinx.exe

LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll

LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL

LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll

LoadedModule[4]=C:\Windows\System32\ADVAPI32.dll

LoadedModule[5]=C:\Windows\System32\msvcrt.dll

LoadedModule[6]=C:\Windows\System32\sechost.dll

LoadedModule[7]=C:\Windows\System32\bcrypt.dll

LoadedModule[8]=C:\Windows\System32\RPCRT4.dll

LoadedModule[9]=C:\Windows\System32\ole32.dll

LoadedModule[10]=C:\Windows\System32\msvcp_win.dll

LoadedModule[11]=C:\Windows\System32\ucrtbase.dll

LoadedModule[12]=C:\Windows\System32\GDI32.dll

LoadedModule[13]=C:\Windows\System32\win32u.dll

LoadedModule[14]=C:\Windows\System32\gdi32full.dll

LoadedModule[15]=C:\Windows\System32\USER32.dll

LoadedModule[16]=C:\Windows\System32\combase.dll

LoadedModule[17]=C:\Windows\System32\OLEAUT32.dll

LoadedModule[18]=C:\Windows\System32\SHELL32.dll

LoadedModule[19]=C:\Windows\System32\IMM32.DLL

LoadedModule[20]=C:\Windows\System32\bcryptPrimitives.dll

LoadedModule[21]=C:\Windows\SYSTEM32\kernel.appcore.dll

LoadedModule[22]=C:\Windows\SYSTEM32\icu.dll

LoadedModule[23]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22621.3085_none_57ff6980ce140777\gdiplus.dll

LoadedModule[24]=C:\Windows\system32\uxtheme.dll

LoadedModule[25]=C:\Windows\System32\MSCTF.dll

LoadedModule[26]=C:\Windows\SYSTEM32\windows.storage.dll

LoadedModule[27]=C:\Windows\SYSTEM32\wintypes.dll

LoadedModule[28]=C:\Windows\System32\SHCORE.dll

LoadedModule[29]=C:\Windows\System32\shlwapi.dll

LoadedModule[30]=C:\Windows\SYSTEM32\profapi.dll

LoadedModule[31]=C:\Windows\SYSTEM32\vulkan-1.dll

LoadedModule[32]=C:\Windows\SYSTEM32\CFGMGR32.dll

LoadedModule[33]=C:\Windows\system32\dxgi.dll

LoadedModule[34]=C:\Windows\SYSTEM32\dxcore.dll

LoadedModule[35]=C:\Windows\SYSTEM32\windows.staterepositorycore.dll

LoadedModule[36]=C:\Windows\SYSTEM32\directxdatabasehelper.dll

LoadedModule[37]=C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2401.3.0_x64__8wekyb3d8bbwe\x64\vulkan_dzn.dll

LoadedModule[38]=C:\Windows\SYSTEM32\VERSION.dll

LoadedModule[39]=C:\Windows\System32\DriverStore\FileRepository\u0398667.inf_amd64_f7fcccf565a8b59e\B398200\amdvlk64.dll

LoadedModule[40]=C:\Windows\System32\SETUPAPI.dll

LoadedModule[41]=C:\Windows\SYSTEM32\WINMM.dll

LoadedModule[42]=C:\Windows\SYSTEM32\amdihk64.dll

LoadedModule[43]=C:\ProgramData\obs-studio-hook\graphics-hook64.dll

LoadedModule[44]=C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2401.3.0_x64__8wekyb3d8bbwe\x64\DXIL.dll

LoadedModule[45]=C:\Windows\SYSTEM32\d3d12.dll

LoadedModule[46]=C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2401.3.0_x64__8wekyb3d8bbwe\x64\D3D12Core.dll

LoadedModule[47]=C:\Windows\SYSTEM32\dwmapi.dll

LoadedModule[48]=C:\Windows\SYSTEM32\DEVOBJ.dll

LoadedModule[49]=C:\Windows\System32\WINTRUST.dll

LoadedModule[50]=C:\Windows\System32\CRYPT32.dll

LoadedModule[51]=C:\Windows\SYSTEM32\MSASN1.dll

LoadedModule[52]=C:\Windows\System32\DriverStore\FileRepository\u0398667.inf_amd64_f7fcccf565a8b59e\B398200\amdxc64.dll

LoadedModule[53]=C:\Windows\SYSTEM32\D3DSCache.dll

LoadedModule[54]=C:\Windows\SYSTEM32\USERENV.dll

LoadedModule[55]=C:\Windows\SYSTEM32\twinapi.appcore.dll

State[0].Key=Transport.DoneStage1

State[0].Value=1

OsInfo[0].Key=vermaj

OsInfo[0].Value=10

OsInfo[1].Key=vermin

OsInfo[1].Value=0

OsInfo[2].Key=verbld

OsInfo[2].Value=22631

OsInfo[3].Key=ubr

OsInfo[3].Value=3085

OsInfo[4].Key=versp

OsInfo[4].Value=0

OsInfo[5].Key=arch

OsInfo[5].Value=9

OsInfo[6].Key=lcid

OsInfo[6].Value=1033

OsInfo[7].Key=geoid

OsInfo[7].Value=244

OsInfo[8].Key=sku

OsInfo[8].Value=101

OsInfo[9].Key=domain

OsInfo[9].Value=0

OsInfo[10].Key=prodsuite

OsInfo[10].Value=768

OsInfo[11].Key=ntprodtype

OsInfo[11].Value=1

OsInfo[12].Key=platid

OsInfo[12].Value=10

OsInfo[13].Key=sr

OsInfo[13].Value=0

OsInfo[14].Key=tmsi

OsInfo[14].Value=222534687

OsInfo[15].Key=osinsty

OsInfo[15].Value=1

OsInfo[16].Key=iever

OsInfo[16].Value=11.1.22621.0-11.0.1000

OsInfo[17].Key=portos

OsInfo[17].Value=0

OsInfo[18].Key=ram

OsInfo[18].Value=7889

OsInfo[19].Key=svolsz

OsInfo[19].Value=1906

OsInfo[20].Key=wimbt

OsInfo[20].Value=0

OsInfo[21].Key=blddt

OsInfo[21].Value=220506

OsInfo[22].Key=bldtm

OsInfo[22].Value=1250

OsInfo[23].Key=bldbrch

OsInfo[23].Value=ni_release

OsInfo[24].Key=bldchk

OsInfo[24].Value=0

OsInfo[25].Key=wpvermaj

OsInfo[25].Value=0

OsInfo[26].Key=wpvermin

OsInfo[26].Value=0

OsInfo[27].Key=wpbuildmaj

OsInfo[27].Value=0

OsInfo[28].Key=wpbuildmin

OsInfo[28].Value=0

OsInfo[29].Key=osver

OsInfo[29].Value=10.0.22621.3085.amd64fre.ni_release.220506-1250

OsInfo[30].Key=buildflightid

OsInfo[31].Key=edition

OsInfo[31].Value=Core

OsInfo[32].Key=ring

OsInfo[32].Value=Retail

OsInfo[33].Key=expid

OsInfo[33].Value=RS:1A75C,MD:283BAEF,ME:28279A6,FX:12C80CE4,MD:2A69053,MD:255521A

OsInfo[34].Key=fconid

OsInfo[34].Value=15546617,0,2,0;18299130,0,2,0;19193777,0,2,0;19194204,0,2,0;19195493,0,2,0;19195502,0,2,0;19638787,0,2,0;23531064,2,2,0;23562335,2,2,0;23563673,2,2,0;32862274,0,2,1;32862275,0,2,0;35681102,0,1,0;36803287,0,2,1;36803295,0,2,0;36803303,0,2,1;38277973,0,1,0;38859191,0,2,1;39145991,0,2,0;39146010,0,1,0;39263329,1,2,0;39281392,0,2,0;40025975,0,1,0;40616880,0,1,1;40733296,0,2,0;40883769,0,1,0;40981503,0,1,0;41135193,0,1,1;41137130,0,1,0;41249924,0,2,1;41313221,0,2,0;41342175,0,1,0;41557840,0,2,0;41655236,0,2,1;41744267,0,2,1;41772259,0,2,1;41799415,0,2,1;42052423,0,2,0;42092123,0,2,0;42105254,0,2,1;42235377,0,2,0;42921948,0,2,1;42922989,0,2,1;42963857,0,2,1;43133808,1,2,1;43169616,0,1,1;43203978,0,2,1;43572857,0,2,1;43695740,0,2,0;43698028,0,2,0;43772553,0,1,0;43844371,0,1,1;43866633,0,0,0;43978769,0,1,1;43995105,0,2,0;43995122,0,2,0;43998261,0,2,1;44325080,0,1,1;44470355,0,1,0;44521793,0,1,0;44552141,0,1,0;44774051,0,2,0;44776738,0,2,1;44860385,0,2,1;45113694,0,2,1;45185354,0,2,0;45187531,0,2,0;45232725,0,2,0;45732051,0,2,0;45786062,0,2,1;45796396,0,2,0;45949789,0,0,0;45951844,0,2,0;45952583,0,0,0;45952594,0,2,0;45952795,0,2,0;45952819,0,2,0;45952823,0,2,0;45952872,0,2,0;45991456,0,1,1;45994554,0,2,0;45999439,0,0,0;46009617,0,0,0;46094352,0,0,1;46111200,0,2,1;46251949,0,2,0;46541070,0,2,0;46551074,0,1,0;46551941,0,0,1;46557400,0,1,1;46559584,1,2,0;46591190,0,2,1;46604216,0,2,1;46619189,0,2,1;46717502,0,2,0;46752087,0,2,0;46969703,0,1,0;46982417,0,2,1;47205155,0,2,0;47526873,1,2,1;47557358,0,0,1;47991031,0,2,1;48057519,0,2,1

OsInfo[35].Key=containerid

OsInfo[36].Key=containertype

OsInfo[37].Key=edu

OsInfo[37].Value=0

OsInfo[38].Key=servicinginprogress

OsInfo[38].Value=0

OsInfo[39].Key=featureupdatependingreboot

OsInfo[39].Value=0

FriendlyEventName=Stopped working

ConsentKey=APPCRASH

AppName=Ryujinx

AppPath=C:\Users\KingO\OneDrive\Desktop\publish\Ryujinx.exe

NsPartner=windows

NsGroup=windows8

ApplicationIdentity=AAB4B797DBE11DC81AC6E18B88AD3C72

MetadataHash=1106609642

### OS

WIN 11

### Ryujinx version

1.1.1192

### Additional context?

This is on my Asus Rog Ally

**Comment by piplup55** [comment]
try uninstalling dozen, next time don't open an issue for support use the [discord](https://discord.gg/ryujinx)
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/d2018b6c-0c56-4b21-996a-3b43a6cf65d5)
