### ISSUE TITLE
NvHost Ioctl command 40080021 not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#632]
```
Unhandled Exception: System.NotImplementedException: 40080021
   at Ryujinx.HLE.HOS.Services.Nv.NvHostCtrl.NvHostCtrlIoctl.ProcessIoctl(ServiceCtx Context, Int32 Cmd)
   in Ryujinx.HLE\HOS\Services\Nv\NvHostCtrl\NvHostCtrlIoctl.cs:line 41
```

```
NVHOST_IOCTL_CTRL_EVENT_KILL
```

#### Required By:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/128
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/82
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/49
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/53
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/124

**Comment by Thog** [comment]
Implemented in #980
