### ISSUE TITLE
Hid.IHidServer SetTouchScreenResolution Unimplemented - Crashing when running Tomb Raider I-III Remastered

### ISSUE THREAD

**Issue by worriorbg** [Ryujinx/Ryujinx#6321]
### Info

**AppVersion**: Ryujinx 1.1.1197
**OS**: MacOS Sonoma 14.3.7
**Hardware**: MacBook Pro M1 Max

### Service call

Ryujinx.HLE.HOS.Services.Hid.IHidServer

[Ryujinx_1.1.1197_2024-02-16_00-14-54.log](https://github.com/Ryujinx/Ryujinx/files/14302993/Ryujinx_1.1.1197_2024-02-16_00-14-54.log)

### Service description

https://reswitched.github.io/SwIPC/ifaces.html#nn::hid::IHidServer

### Required by

Tomb Raider I-III Remastered 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4869

**Comment by worriorbg** [comment]
Game works with ignore missing services enabled in the settings

**Comment by d9j** [comment]
the game starts but the game gamma too dark and no way to adjust it

**Comment by d9j** [comment]
<img width="1725" alt="截屏2024-02-16 下午10 14 36" src="https://github.com/Ryujinx/Ryujinx/assets/2436637/7a9f1372-ff13-4339-91fe-6964032626c0">

**Comment by worriorbg** [comment]
I agree but this is better handled and explained here:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4869

This ticket is about the unimplemented service
