### ISSUE TITLE
hid IHidServer: 525 (SetPalmaBoostMode) not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#633]
IHidServer SetPalmaBoostMode is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/HID_services#hid) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::hid::IHidServer(525))

```SetPalmaBoostMode(bool)```

Unknown.

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/115

**Comment by jduncanator** [comment]
Resolved in #761

**Comment by AcK77** [comment]
Implemented in #756.
