### ISSUE TITLE
[Bug][Regression] Pokken Tournament DX - Textures missing/mono-colored

### ISSUE THREAD

**Issue by Tosh94** [Ryujinx/Ryujinx#6331]
### Description of the issue

Since update 1.1.1198, using the Vulkan backend specifically, entering any battle in Pokken Tournament DX seems to be lacking most textures, drawing objects mono-colored instead (see images below). The OpenGL backend works normally, but is significantly slower.

Before 1.1.1198 (taken in 1.1.1197):
![ryujinx_1 1 97_pokken_before](https://github.com/Ryujinx/Ryujinx/assets/893279/b52f5059-cd27-4f54-9bd4-25242e730f20)

After 1.1.1198 (taken in 1.1.1198):
![ryujinx_1 1 98_pokken_after](https://github.com/Ryujinx/Ryujinx/assets/893279/b7567e16-c8aa-43b0-a439-cd4713dc4f7f)

This occurs independently of stage, chosen characters or assists. The only difference is the mono-color rendered, which seems to change depending on stage and/or actions taken in the battle.

The game otherwise controls fine, but this makes it almost impossible to play.

### Reproduction steps

After launching the game, enter any battle with any character on any stage.

### Log file

None, there was no difference in the logs before and after the update.

### OS

Windows 10

### Ryujinx version

1.1.1198 (and following)

### Game version

1.3.3

### CPU

i7-13700KF

### GPU

NVIDIA GTX1080

### RAM

64GB

**Comment by GamerzHell9137** [comment]
Driver version?

**Comment by gdkchan** [comment]
Can't reproduce here.
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/da5e9fd9-115e-4159-85a3-56a0f77afebb)
Might be specific to pre-Turing NVIDIA cards or outdated drivers.

**Comment by Tosh94** [comment]
Occured on driver version 537.xx (don't remember) and 551.52 (latest).
Also happens at my friends PC (identical except an even older graphics card, a 970).

Additionally, no Ryujinx settings except graphics backend had any effect.

**Comment by Tosh94** [comment]
After updating, can confirm the game works again. Thanks a lot for the fix!
