### ISSUE TITLE
TOTK randomly crashing when going to certain zones

### ISSUE THREAD

**Issue by Yuri-Matsuki** [Ryujinx/Ryujinx#6333]
### Description of the issue

This bug is very simple, the game simply stutters for a few seconds before crashing, for no apparent reason. I tried disabling mods and changing my settings, but nothings seems to work

### Reproduction steps

This bug can be reproduced only by walking on random spots in the map, here's a clip showing it

https://github.com/Ryujinx/Ryujinx/assets/151469377/f95dc656-c9eb-4ed0-bc74-eb1115e90a55

### Log file

[Ryujinx_1.1.1204_2024-02-20_10-51-35.log](https://github.com/Ryujinx/Ryujinx/files/14346950/Ryujinx_1.1.1204_2024-02-20_10-51-35.log)

### OS

Windows 11

### Ryujinx version

1.1.1204

### Game version

All versions

### CPU

AMD ryzen 5 5600g

### GPU

AMD radeon graphics

### RAM

24 GB

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.

**Comment by rafaelqueiroz88** [comment]
> [Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.
> 
> In the future, please use discord for help.

How to dump them? I think I have the same problem. Sorry asking here
