### ISSUE TITLE
[Bug] Pokemon violet crashes on startup

### ISSUE THREAD

**Issue by FireGeneral** [Ryujinx/Ryujinx#6343]
### Description of the issue

Ryujinx crashes whenever trying to start the game.

### Reproduction steps

Update to version 1.1.1206.

### Log file

[Ryujinx_1.1.1206_2024-02-22_13-09-23.log](https://github.com/Ryujinx/Ryujinx/files/14368911/Ryujinx_1.1.1206_2024-02-22_13-09-23.log)

### OS

Windows 11

### Ryujinx version

1.1.1206

### Game version

SV v3.0.1

### CPU

i7-12700H

### GPU

NVIDIA RTX3050 Laptop

### RAM

16GB

### List of applied mods

None

### Additional context?

Downgrading to v1.1.1110 fixes the issue.

**Comment by Tosh94** [comment]
I have this issue, too, with Pokemon Scarlet v3.0.0. Seems to have been introduced with 1.1.1205 as 1.1.1204 still works.
System info: Win 10, i7-13700KF, NVIDIA GTX 1080 (latest driver), 64GB RAM.

**Comment by MKL78** [comment]
Same problem in TOTK v1.2.1 after updating to 1.1.1206 whenever I press start to access the menu (sometimes also when loading a save): "Offset and length were out of bounds..."

Solved by going back to 1.1.1190 (but havent tested with other versions between 1190 and 1206)

[Ryujinx_1.1.1206_2024-02-22_14-10-42.log](https://github.com/Ryujinx/Ryujinx/files/14369888/Ryujinx_1.1.1206_2024-02-22_14-10-42.log)

**Comment by DMaster2** [comment]
Same issue with Xenoblade Chronicles Definitive edition. Was running perfectly up until 1204. What the heck did they do in this update???

**Comment by Shahil-Ayato** [comment]
Fixed by #6345

**Comment by Havocsouls** [comment]
Been trying to fix this issue myself past day or 2 with different builds both regular and ldn, keys, firmware, different settings, just came back to Ryujinx day before yesterday and the 2 games with the 3.0 update keeps crashing the system before I can get it to launch so is there a specific build that's working or something, I appreciate the assistance if I can be guided towards the solution
