### ISSUE TITLE
[Bug] Xenoblade Chronicles Definitive Edition crash on startup after update to ryujinx

### ISSUE THREAD

**Issue by DMaster2** [Ryujinx/Ryujinx#6344]
### Description of the issue

Ryujinx crashes whenever trying to start the game after updating to 1206. Was running perfectly up until update 1204.

### Reproduction steps

Update to version 1.1.1206.

### Log file

[Ryujinx_1.1.1206_2024-02-22_10-14-36.log](https://github.com/Ryujinx/Ryujinx/files/14371862/Ryujinx_1.1.1206_2024-02-22_10-14-36.log)

### OS

Windows 10

### Ryujinx version

1.1.1206

### Game version

1.1.2

### CPU

Intel I5 10400F

### GPU

NVIDIA RTX 3060Ti

### RAM

16GB

### List of applied mods

No mods applied

**Comment by Shahil-Ayato** [comment]
Fixed by #6345
