### ISSUE TITLE
nvdrv INvDrvServices: 6 (GetStatus) not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#635]
INvDrvServices GetStatus is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/NV_services#nvdrv.2C_nvdrv:a.2C_nvdrv:s.2C_nvdrv:t) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nns::nvdrv::INvDrvServices(6))

> Takes no input. Returns 0x10-bytes and an output u32 (error_code).

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/114
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/168
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/187

**Comment by HorrorTroll** [comment]
Closed, have been fixed by #800

**Comment by Thog** [comment]
No it's still not implemented

**Comment by B3astTech** [comment]
https://github.com/Ryujinx/Ryujinx/issues/635
