### ISSUE TITLE
[Crash at starting Tears of kingdom]

### ISSUE THREAD

**Issue by shoaibsaikat** [Ryujinx/Ryujinx#6353]
### Description of the issue

Can't play the game crashes at opening saved file loading.

### Reproduction steps

Open Tears of the kingdom, continue, then select a game saved file, then crashes at loading screen.

### Log file

00:00:00.002 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.055 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.062 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.063 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.063 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.064 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.065 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.065 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x1638
00:00:00.066 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.067 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.067 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.068 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.075 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.075 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.075 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.075 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.075 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.075 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.075 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.075 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.075 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.076 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.076 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.077 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.077 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.077 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.077 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.080 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.080 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1211
00:00:00.084 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.084 |N| Application Print: CPU: AMD Ryzen 7 5700G with Radeon Graphics ; 16 logical
00:00:00.086 |N| Application Print: RAM: Total 15.4 GiB ; Available 12.7 GiB
00:00:00.088 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.088 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.088 |I| Gpu : Backend Threading (Auto): True
00:00:00.380 |N| Application LoadApplication: Using Firmware Version: 17.0.1
00:00:00.380 |I| Application LoadApplication: Loading as XCI.
00:00:00.421 |I| ModLoader QueryContentsDir: Searching mods for Application 0100F2C0115B6000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.422 |I| ModLoader QueryContentsDir: Searching mods for Application 0100F2C0115B6000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.425 |I| Loader Load: Loading rtld...
00:00:00.433 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.433 |I| Loader Load: Loading main...
00:00:00.808 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:00.809 |I| Loader Load: Loading subsdk0...
00:00:00.833 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:00.833 |I| Loader Load: Loading sdk...
00:00:00.887 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:00.989 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.905 |I| Ptc Load: Loaded Translation Cache (size: 86126654 bytes, translated functions: 71661).
00:00:01.933 |I| Ptc Load: Loaded Profiling Info (size: 278330 bytes, profiled functions: 84886).
00:00:01.941 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.942 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.981 |I| Loader LoadNsos: Loading image 2 at 0x000000000cc2f000...
00:00:01.984 |I| Loader LoadNsos: Loading image 3 at 0x000000000d2d8000...
00:00:01.992 |I| ModLoader LoadCheats: Build ids found for application 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    9B4E43650501A4D4489B4BBFDB740F26AF3CF850000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:01.995 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.052 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.2.1 [0100f2c0115b6000] [64-bit]
00:00:02.060 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:02.070 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:02.364 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD Radeon(TM) Graphics (Vulkan v1.3.260, Driver v2.0.279)
00:00:02.373 |I| GPU.MainThread Gpu LoadShaders: Loading 191 shaders from the cache...
00:00:02.560 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:03.597 |I| HLE.GuestThread.48 Ptc LoadTranslations: 70395 translated functions loaded
00:00:03.617 |I| HLE.GuestThread.48 Ptc MakeAndSaveTranslations: 0 of 14491 functions translated | Thread count: 15
00:00:08.575 |I| HLE.GuestThread.48 Ptc MakeAndSaveTranslations: 14491 of 14491 functions translated | Thread count: 15 in 4.9571623 s
00:00:08.662 |S| HLE.OsThread.49 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:08.672 |S| HLE.OsThread.49 ServiceAm AcquireForegroundRights: Stubbed.
00:00:08.673 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:08.673 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:08.682 |S| HLE.OsThread.49 ServicePctl Initialize: Stubbed.
00:00:09.445 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:09.445 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:09.445 |S| HLE.OsThread.49 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:09.445 |S| HLE.OsThread.49 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:09.446 |S| HLE.OsThread.49 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:09.770 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed.
00:00:09.775 |I| HLE.OsThread.49 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:09.777 |I| HLE.OsThread.49 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:09.791 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed.
00:00:09.804 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed.
00:00:09.843 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed.
00:00:09.844 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:09.844 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed.
00:00:09.845 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed.
00:00:09.845 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed.
00:00:09.845 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed.
00:00:09.845 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed.
00:00:09.847 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed.
00:00:09.866 |S| HLE.OsThread.49 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:09.868 |S| HLE.OsThread.49 ServiceAcc IsUserAccountSwitchLocked: Stubbed.
00:00:09.868 |S| HLE.OsThread.49 ServiceNs CheckAddOnContentMountStatus: Stubbed.
00:00:09.883 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:09.886 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:09.886 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:10.830 |S| HLE.OsThread.8 ServiceNv ZbcSetTable: Stubbed.
00:00:10.831 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed.
00:00:11.366 |I| Ptc Save: Saved Translation Cache (size: 102505325 bytes, translated functions: 86152).
00:00:12.231 |S| HLE.OsThread.7 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:12.233 |S| HLE.OsThread.7 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:13.113 |I| HLE.OsThread.15 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:13.115 |I| HLE.OsThread.15 AudioRenderer Initialize: Initializing with REV11
00:00:13.131 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:13.131 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:13.133 |I| HLE.OsThread.15 AudioRenderer Start: Starting renderer id 0
00:00:13.190 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:18.860 |S| HLE.OsThread.49 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:18.861 |S| HLE.OsThread.49 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:19.649 |S| HLE.OsThread.8 ServiceNv ZbcSetTable: Stubbed.
00:00:19.649 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed.
00:00:19.650 |S| HLE.OsThread.8 ServiceNv ZbcSetTable: Stubbed.
00:00:19.650 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed.
00:00:22.128 |S| HLE.OsThread.49 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed.
00:00:22.128 |S| HLE.OsThread.49 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed.
00:00:22.128 |S| HLE.OsThread.49 ServiceAm SetExpectedMasterVolume: Stubbed.
00:00:24.966 |S| HLE.OsThread.7 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:00:24.966 |S| HLE.OsThread.7 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:00:25.068 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: bootup_time
 Report: {
    "BootupTimeUs": 85713,
    "system_report_tag": 2175206328
}

00:00:25.070 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_region
 Report: {
    "Region": 1,
    "Language": 1,
    "StandardTimeName": "UTC",
    "UtcOffsetSeconds": 0,
    "system_report_tag": 2759414308
}

00:00:25.070 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_time
 Report: {
    "ActiveTime": 16,
    "UpdatedTime": 0,
    "system_report_tag": 2759414308
}

00:00:25.070 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_playstyle
 Report: {
    "system_report_tag": 2759414308
}

00:00:25.071 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_network_status
 Report: {
    "NetworkInterface": {
        "TypeCode": 64,
        "Value": "0x00000000000000000000000000000000"
    },
    "LinkLevel": {
        "TypeCode": 65,
        "Value": "0x00"
    },
    "FrequencyBand": {
        "TypeCode": 66,
        "Value": "0x00000000000000000000"
    },
    "system_report_tag": 2759414308
}

00:00:25.102 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_active_beacon
 Report: {
    "IntervalTime": 0,
    "UpdatedTime": 0,
    "system_report_tag": 0
}

00:00:28.289 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:28.290 |S| HLE.OsThread.7 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player2}
00:00:28.290 |S| HLE.OsThread.7 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player3}
00:00:28.290 |S| HLE.OsThread.7 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player4}
00:00:35.166 |W| HLE.OsThread.8 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:35.933 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start
 Report: {
    "PlayTime": 3,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 970317109,
    "EventInfo": "Dm_OP_0037",
    "PlayerPosX": 3.406024E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406211E-11,
    "system_report_tag": 2175206328
}

00:00:36.016 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start
 Report: {
    "PlayTime": 3,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 970317109,
    "EventInfo": "Dm_OP_0039",
    "PlayerPosX": 3.406024E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406211E-11,
    "system_report_tag": 2175206328
}

00:00:36.271 |S| HLE.OsThread.49 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:00:38.593 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 278386 bytes, profiled functions: 84903).
00:00:41.044 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: option_data
 Report: {
    "PlayTime": 3,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 970317109,
    "BoolOptions": 523,
    "CameraRotateSpeed": 2,
    "DisplayMode": 0,
    "MessageWindowTransparency": 0,
    "VoiceLanguage": 1,
    "Action": 1,
    "Cancel": 2,
    "Jump": 3,
    "Attack": 4,
    "SpecialPower": 5,
    "Attention": 6,
    "Throw": 7,
    "Bow": 8,
    "PlusMenu": 9,
    "MinusMenu": 10,
    "SpecialPowerShortcut": 11,
    "CompanionShortcut": 13,
    "PouchShortcut": 14,
    "Whistle": 12,
    "Crouch": 25,
    "Scope": 33,
    "PresetType": 0,
    "system_report_tag": 2175206328
}

00:00:41.077 |S| HLE.OsThread.49 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:00:52.321 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

ryujinx-1.1.1211-win_x64

### Game version

1.2.1

### CPU

Ryzen 7 5700G

### GPU

Vega 8

### RAM

16 GB

### List of applied mods

No mod applied

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
