### ISSUE TITLE
[Bug] Possible Drop-down menu regression on Linux Avalonia UI 1.1.1203

### ISSUE THREAD

**Issue by Rigerhit047** [Ryujinx/Ryujinx#6354]
### Description of the issue

After version 1.1.1203, the drop-down menu at the top of Ryujinx stopped to work correctly, now the menu only appears about 1 of 15 clicks, when it should appear (and disappear) at each click, now it has turned very unconsistent. Other menus like the context menus when right clicking in games seem to work fine, but even the hotkey to Stop Emulation turned inconsistent (disappears as soon as it appears). This does not happen on GTK builds.

I did try older builds after finding out that the change was after 1.1.1203, I attached a log of 1.1.1202 at the bottom. Both logs are running with a clean Ryujinx data folder and in both I attempt to spam clicking in the "Options" menu.

### Reproduction steps

1. Download a test-ava build of 1.1.1203 or higher
2. Try to access to any of the drop-down menus in the top bar (eg: File, Option, Tools, Help)

### Log file

[Ryujinx_1.1.1203_2024-02-23_07-55-21.log](https://github.com/Ryujinx/Ryujinx/files/14384963/Ryujinx_1.1.1203_2024-02-23_07-55-21.log)

### OS

Fedora Linux 39 (Workstation Edition)

### Ryujinx version

1.1.1203+

### CPU

i5-4690K

### GPU

AMD Radeon™ RX 570 Series (radvk)

### RAM

16GB

### Additional context?

So I have been using Ryujinx on Linux since the start of the year, and although this message of "Error when destroying context" appeared frequently in the logs, it wasn't a problem for me (although I suspect that it makes the emulator crash sometimes when going fullscreen through the context menu), I forgot to mention it in the server, and let it be until I were less busy, I didn't have any other problems until today, where it suddenly was very difficult to get the menus to work, so I spend a little of time and figured it was after 1.1.1203 after a direct comparison.

Here's the log from 1.1.1202:

[Ryujinx_1.1.1202_2024-02-23_07-54-27.log](https://github.com/Ryujinx/Ryujinx/files/14384965/Ryujinx_1.1.1202_2024-02-23_07-54-27.log)

**Comment by marysaka** [comment]
@Rigerhit047 are you using the flathub version?

**Comment by Rigerhit047** [comment]
@marysaka No, I'm using Ryujinx with the tarball binary, and I tested the older versions with those too. I actually do forget that there's a flatpak...

**Comment by piplup55** [comment]
i have never seen this on my system, if you could post a video that would help

**Comment by Rigerhit047** [comment]
@piplup55 Here you go
[Screencast from 2024-02-24 21-16-29.webm](https://github.com/Ryujinx/Ryujinx/assets/87140051/f96d56ea-19f3-4fd7-908d-09c0177ecb19)

**Comment by Rigerhit047** [comment]
Update: I noticed that if I unfocus the Ryujinx window, then click on a menu, it will work correctly 100% of the time, but only if I do that again and again (Unfocus window>Click on a menu). This doesn't even print any error on the logs (normal usage even when working correctly threw "Error when destroying context" errors.

**Comment by marysaka** [comment]
> @marysaka No, I'm using Ryujinx with the tarball binary, and I tested the older versions with those too. I actually do forget that there's a flatpak...

Okay so considering that the error I was hinting on your log file show up when clicking it seems your installation might have some issues.

However, If you have this issue it means it could arise again to someone so I will change it so it only enable gamescope workaround when ran under gamescope on SteamOS.

**Comment by Rigerhit047** [comment]
I can say it's solved, thanks!

However, I need to ask, with "installation issues" do you mean Ryujinx, or the OS? If it's Ryujinx, it was a freshly extracted tarball running how it should with no userdata whatsoever. If it's OS... No idea how I would tackle that specially since I reinstalled it like 3 times and in two of them those messages in the log where still there, but I'll prob try to research it whenever I can.

I want to say that I did try the flatpak, but since there was no Avalonia GUI flatpak... then there was no issue, but well, it works in latest flatpak too, although the fix came before Avalonia was merged, I couldn't really tell if the flatpak version would not have this issue before, but I'll say probably yes since the "Error when destroying context" spam is present in it, too.

**Comment by marysaka** [comment]
> I can say it's solved, thanks!
> 
> However, I need to ask, with "installation issues" do you mean Ryujinx, or the OS? If it's Ryujinx, it was a freshly extracted tarball running how it should with no userdata whatsoever. If it's OS... No idea how I would tackle that specially since I reinstalled it like 3 times and in two of them those messages in the log where still there, but I'll prob try to research it whenever I can.
> 
> I want to say that I did try the flatpak, but since there was no Avalonia GUI flatpak... then there was no issue, but well, it works in latest flatpak too, although the fix came before Avalonia was merged, I couldn't really tell if the flatpak version would not have this issue before, but I'll say probably yes since the "Error when destroying context" spam is present in it, too.

I was thinking about an OS installation issue because you have very weird DBus errors each time you try to open the menu:

```
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/IBus/InputContext_523”
```

So to me it sounded that something might be missing but I couldn't reproduce that on a fresh Fedora Workstation version. (KDE or even GNOME)

But again, that fix for gamescope isn't really needed on everything else so it's safer to disable it in case this is an issue more spread that I anticipated.
