### ISSUE TITLE
[Feature Request] Configure input button for mac (FOR MOTION CONTROLS)

### ISSUE THREAD

**Issue by CodingForAddicts** [Ryujinx/Ryujinx#6357]
### Overview

Currently we have this on mac : 
<img width="348" alt="Screenshot 2024-02-24 at 12 53 11 AM" src="https://github.com/Ryujinx/Ryujinx/assets/95184556/45e9e5fc-ee64-44b0-a72f-5613a27bef5d">
BUT

Windows user have this : ![86279008-8d664600-bb96-11ea-9ed3-32034ad9f53a](https://github.com/Ryujinx/Ryujinx/assets/95184556/34d891d8-1c35-42c7-a5ef-a142e17279fd)

### Smaller details

no details need to be added.

### Nature of request

The goal with this is to offer the possibility of using your phone as motion control like on windows......

### Why would this feature be useful?

Useful for many games like just dance for example

**Comment by MutantAura** [comment]
Im not sure how these images are relevant to your query. 
You can already configure a cemuhook motion source for any controller in the motion configuration section.
<img width="1212" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/44103205/98454ca4-24df-4d3b-a3db-37dbe09fd29b">
