### ISSUE TITLE
[Bug] THE LAST FAITH [0100C69018E4A000][V0][US].NSP

### ISSUE THREAD

**Issue by kalt9** [Ryujinx/Ryujinx#6369]
### Description of the issue

Red text, game won't load

### Reproduction steps

Everytime I try to load game.

### Log file

[Ryujinx_1.1.1214_2024-02-28_18-26-08.log](https://github.com/Ryujinx/Ryujinx/files/14442177/Ryujinx_1.1.1214_2024-02-28_18-26-08.log)

### OS

Windows 10

### Ryujinx version

1.1.1214

### Game version

THE LAST FAITH [0100C69018E4A000][V0][US].NSP

### CPU

i5-7600K

### GPU

NVIDIA GTX 1060

### RAM

16GB

### List of applied mods

None

**Comment by piplup55** [comment]
your game is corrupted, redump it from your switch, join the [discord](https://discord.gg/ryujinx) for support next time

**Comment by kalt9** [comment]
The game requires the update. The base game does not contain all of the files necessary to run the game. Get the update, right click the game in Ryujinx > Manage Title Updates > Add > Navigate to and Select the Game Update File > Save. Then the game will work. (RedColoredStars)
