### ISSUE TITLE
[Bug] Legend of Zelda BOTW regression

### ISSUE THREAD

**Issue by rishabruh** [Ryujinx/Ryujinx#6372]
### Description of the issue

With recent update, BOTW seems to no longer work with Hypervisor enabled. After disabling hypervisor there seems to be a performance hit, with game frequently dipping into low 20's. Previously it was a stable locked 30.

### Reproduction steps

Launch game with default Ryujinx settings and hypervisor enabled on Ryujinx 1.1.1214

### Log file

[Ryujinx_1.1.1214_2024-03-02_00-40-32.log](https://github.com/Ryujinx/Ryujinx/files/14465108/Ryujinx_1.1.1214_2024-03-02_00-40-32.log)

### OS

MacOS Sonoma (14.3)

### Ryujinx version

1.1.1214

### Game version

1.6.0

### CPU

Apple M2

### GPU

Apple M2

### RAM

16GB

**Comment by piplup55** [comment]
This is not a regression the change was reverted in 1.1.1109 (#6068) because it caused other games to freeze on mac os
