### ISSUE TITLE
[Bug] Legend of Zelda BOTW: Album does not display images

### ISSUE THREAD

**Issue by rishabruh** [Ryujinx/Ryujinx#6373]
### Description of the issue

In the in-game Sheikah slate, going to the album does not display the images you captured and instead shows a bugged out collage of all the preloaded slate images.
![Screenshot 2024-03-02 at 02 17 57](https://github.com/Ryujinx/Ryujinx/assets/91521594/b1135b10-db2f-4f42-8e84-e2476364003e)

### Reproduction steps

Unlock album capability from hateno village and take a picture. Then view picture in the album.

### Log file

[Ryujinx_1.1.1214_2024-03-02_01-06-14.log](https://github.com/Ryujinx/Ryujinx/files/14465902/Ryujinx_1.1.1214_2024-03-02_01-06-14.log)

### OS

MacOS Sonoma 14.3

### Ryujinx version

1.1.1214

### Game version

1.6.0

### CPU

Apple M2

### GPU

Apple M2

### RAM

16GB

**Comment by gdkchan** [comment]
Fixed by #6356.
