### ISSUE TITLE
Latest Ryujinx forces disconnect on fullscreen while streaming through Moonlight

### ISSUE THREAD

**Issue by Vertreal** [Ryujinx/Ryujinx#6383]
### Description of the issue

After Avalonia update for Windows, entering fullscreen mode in Ryujinx crashes the active Moonlight streaming session. Never encountered this problem on earlier versions or with other fullscreen applications. Ryujinx keeps running in the background. Crossposting here but I don't think it's a Moonlight issue.

### Reproduction steps

Enter fullscreen while having an active Moonlight stream. Wait about 10-15 seconds for the streaming session to be forcefully ended.

### Log file

[Ryujinx_1.1.1217_2024-03-02_20-53-29.log](https://github.com/Ryujinx/Ryujinx/files/14470636/Ryujinx_1.1.1217_2024-03-02_20-53-29.log)

### OS

Windows 10

### Ryujinx version

1.1.1217

**Comment by QuirkyKirkHax** [comment]
I am also experiencing this issue myself.

**Comment by QuirkyKirkHax** [comment]
Took a look inside event viewer, and this was the event viewer log of the crash:

Faulting application name: Sunshine.exe, version: 0.22.0.0, time stamp: 0x65e5b22f
Faulting module name: ntdll.dll, version: 10.0.19041.3996, time stamp: 0x39215800
Exception code: 0xc0000374
Fault offset: 0x00000000000ff349
Faulting process id: 0x4124
Faulting application start time: 0x01da6f0df7268e5f
Faulting application path: C:\Program Files\Sunshine\Sunshine.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 4422a667-5c72-4567-92e0-d13515516448
Faulting package full name:
Faulting package-relative application ID:

That exception code seems to imply a heap corruption error based on what I can find.

**Comment by Rahzadan** [comment]
I can confirm this. It has also been raised on the Sunshine Github. See my comments here:

https://github.com/LizardByte/Sunshine/issues/2219

**Comment by Rahzadan** [comment]
This has been fixed on Sunshine, will be in the next release. See https://github.com/LizardByte/Sunshine/issues/2219

**Comment by MutantAura** [comment]
Fixed in latest Sunshine releases.
