### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Akira2103** [Ryujinx/Ryujinx#6384]
### Description of the issue

Every game crashes when trying to start

### Reproduction steps

i just updated and none of my games work now. everything worked fine till i updated.

### Log file

00:00:00.057 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.065 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.065 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.066 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.067 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.068 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.068 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73EF
00:00:00.069 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.070 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.070 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.071 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.077 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.077 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.077 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.077 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.077 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.077 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.077 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.077 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.077 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.078 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.078 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.080 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.080 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.080 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.080 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.083 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.086 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1217
00:00:00.091 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.091 |N| Application Print: CPU: AMD Ryzen 5 5600X 6-Core Processor ; 12 logical
00:00:00.093 |N| Application Print: RAM: Total 63.9 GiB ; Available 51.9 GiB
00:00:00.096 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.097 |N| Application PrintSystemInfo: Launch Mode: Portable

### OS

windows 11 home

### Ryujinx version

1.1.1217

### Game version

3.0.0

### CPU

Ryzen 5600x

### GPU

NVIDIA 3060

### RAM

64gb

### List of applied mods

none

**Comment by piplup55** [comment]
Github is not the place to ask for support, join the [discord](https://discord.gg/ryujinx) if you want support
