### ISSUE TITLE
fsp-srv IFileSystemProxy: 22 (CreateSaveDataFileSystem) not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#639]
IFileSystemProxy CreateSaveDataFileSystem is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Filesystem_services#CreateSaveDataFileSystem) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::fssrv::sf::IFileSystemProxy(22))

```
CreateSaveDataFileSystem(nn::fssrv::sf::SaveStruct saveStruct, nn::fssrv::sf::SaveCreateStruct saveCreate, u128 input)
```

> Takes a 0x40-byte Save-struct entry, a 0x40-byte SaveCreate-struct entry, and a 0x10-byte input struct.
> 
> Only the first 0x5-bytes in the 0x10-byte struct are initialized: all-zero when automatically creating savedata during savecommon mount by official user-processes. In the dedicated save-creation code in official user-processes: +0 u32 = 0x40060, +4 u8 = 1.
> 
> Creates regular savedata.

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/78

**Comment by AcK77** [comment]
Fixed in #801
