### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PxGT09** [Ryujinx/Ryujinx#6390]
### Description of the issue

I'm trying to run mlb the show 23 on Vulkan but I get an error
![erroCapturar](https://github.com/Ryujinx/Ryujinx/assets/162047390/eca32555-e449-4239-aa98-f0d32d822adb)

### Reproduction steps

When I start any mode the game closes by itself

### Log file

[Ryujinx_1.1.1217_2024-03-03_14-43-52.log](https://github.com/Ryujinx/Ryujinx/files/14473959/Ryujinx_1.1.1217_2024-03-03_14-43-52.log)

### OS

Windows 10

### Ryujinx version

1.1.1217

### Game version

1.0.10

**Comment by piplup55** [comment]
Github is not the place for support join the [discord](https://discord.gg/ryujinx), also empty log and didn't follow the template
