### ISSUE TITLE
Touch Screen Calibration[Feature Request]

### ISSUE THREAD

**Issue by mame-rr-player001** [Ryujinx/Ryujinx#6392]
### Overview

It seems that Touch Screen Calibration of Ryujinx is wrong.

### Smaller details

In Game (I play The House Of The Dead Remake), shoot position is different from Windows Mouse Position.
What should I do?

### Nature of request

Normal

### Why would this feature be useful?

Please Fix It.

**Comment by gdkchan** [comment]
On some games, touch screen only has correct coordinates in handheld mode, since on a physical Switch console, you can only use the touch screen in handheld. This might be the case here.

**Comment by Coolsium** [comment]
I was testing ryujinx and on an old version the touchscreen feature worked fine with my mouse, now in the latest update the touch is registering very off and inaccurate, even in handheld mode, any solutions?

**Comment by gamegod333** [comment]
This is a bug.
You can temporarily adjust the Windows font scaling to 100% to solve it.

**Comment by gdkchan** [comment]
Does the issue still happen on latest version? There was a change to how mosue events are handled on Windows.

**Comment by gamegod333** [comment]
v1.1.1224 - 2024-03-11 already fixed!

**Comment by gdkchan** [comment]
Fixed by #6450.
