### ISSUE TITLE
[Feature Request] Emulation Accuracy Settings

### ISSUE THREAD

**Issue by Axis4s** [Ryujinx/Ryujinx#6399]
### Overview

Image found on Ryujinx's Discord Server.
![image](https://github.com/Ryujinx/Ryujinx/assets/97393974/0bb98df2-523d-4639-b772-43e30a3d8a14)

### Smaller details

Accurate (slower) - Basically how the emulator is runs right now.
Fast (Unsafe)
Fastest (Unstable) 

### Nature of request

Giving users the option to trade accuracy for performance.

### Why would this feature be useful?

Having settings for how accurate you want the emulator to be would be very helpful. It could give some users better performance on certain hardware configurations.

To be honest, I thought this was a feature from the beginning, as some other emulators also include options to make the emulation run less accurately but provide more performance.

**Comment by Shahil-Ayato** [comment]
We have made it clear before that we are not interested in “accuracy settings” we want Ryujinx to be as accurate as possible.

**Comment by Axis4s** [comment]
> We have made it clear before that we are not interested in “accuracy settings” we want Ryujinx to be as accurate as possible.

:<
