### ISSUE TITLE
[Feature Request]Remove the " please follow these steps" guide under the“ keys ”section to ensure Nintendo won't sue ryujinx.

### ISSUE THREAD

**Issue by stc2001** [Ryujinx/Ryujinx#6404]
### Overview

Remove the " please follow these steps" guide under the“ keys ”section to ensure Nintendo won't sure ryujinx.
from https://github.com/Ryujinx/Ryujinx/wiki/Keys

### Smaller details

Delete the following guide  to avoid being perceived by Nintendo as indulging in cracking

To dump your prod.keys and title.keys please follow these steps.

    First off [learn how to boot into RCM mode and inject payloads](https://nh-server.github.io/switch-guide/) if you haven't already.
    Make sure you have an SD card with the latest release of [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases) inserted into your Nintendo Switch.
    Download the latest release of Picklock_RCM/Lockpick_RCM.
    Boot into RCM mode.
    Inject the Picklock_RCM/Lockpick_RCM.bin that you have downloaded at Step 3. using your preferred payload injector. We recommend [TegraRCMGUI](https://github.com/eliboa/TegraRcmGUI/releases) as it is easy to use and has a decent feature set.
    Using the Vol+/- buttons to navigate and the Power button to select, select Dump from SysNAND | Key generation: X ("X" depends on your Nintendo Switch's firmware version).
    The dumping process may take a while depending on how many titles you have installed.
    After its completion, press any button to return to the main menu of Picklock_RCM/Lockpick_RCM.
    Navigate to and select Power off if you have an SD card reader. Or you could Navigate and select Reboot (RCM) if you want to mount your SD card using TegraRCMGUI > Tools > Memloader V3 > MMC - SD Card.
    You can find your keys in sd:/switch/prod.keys and sd:/switch/title.keys respectively.
    Copy these files and paste them in your Ryujinx system folder. And you're done!

### Nature of request

ensure leaglity

### Why would this feature be useful?

ensure leaglity

**Comment by MetrosexualGarbodor** [comment]
No 👍 
Removing guides will only annoy users and do nothing for the project
