### ISSUE TITLE
[Feature Request]Remove the " firmware dumping guide " section to ensure Nintendo won't sure ryujinx.

### ISSUE THREAD

**Issue by stc2001** [Ryujinx/Ryujinx#6405]
### Overview

Remove the " firmware dumping guide " section to ensure Nintendo won't sure ryujinx.
from https://github.com/Ryujinx/Ryujinx/wiki/Firmware-Dumping-Guide

### Smaller details

Remove the " firmware dumping guide " section to ensure Nintendo won't sure ryujinx.
from https://github.com/Ryujinx/Ryujinx/wiki/Firmware-Dumping-Guide

### Nature of request

ensure leaglity

### Why would this feature be useful?

ensure legality

**Comment by MetrosexualGarbodor** [comment]
No 👍 
Removing guides will only annoy users and do nothing for the project
