### ISSUE TITLE
Linking "illegal" guides to dump Switch stuff: what if it ends up in court?

### ISSUE THREAD

**Issue by ezkha** [Ryujinx/Ryujinx#6409]
No 👍 
        Removing guides will only annoy users and do nothing for the project

_Originally posted by @MetrosexualGarbodor in https://github.com/Ryujinx/Ryujinx/issues/6404#issuecomment-1977921462_
            
I'm not sure about that.

Yuzu got killed and is dead, and having guides to "100% illegally obtain production keys/etc..." directly embedded into their wikis sure as hell gave a good bonus to Nintendo legal team. Quote is approximately from Nintendo vs. Yuzu lawsuit document.

Consider unlinking or removing them and people will just be forced to search online.

Oh, and, having a Patreon up might also kill the project, but whatever at this point.

**Comment by piplup55** [comment]
No 👍
