### ISSUE TITLE
[Feature Request] Update wiki to remove dead links

### ISSUE THREAD

**Issue by BDMCGaming** [Ryujinx/Ryujinx#6413]
### Overview

Should be fairly obvious. The Yuzu website is dead, which means it's mod database is dead

### Smaller details

<img width="919" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/48656222/7129d359-31b3-473f-be69-422903d03925">

### Nature of request

?

### Why would this feature be useful?

Stops people from being confused

**Comment by AcK77** [comment]
Already fixed
