### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by furax124** [Ryujinx/Ryujinx#6415]
### Description of the issue

Ryujinx crash when i start a game (especially Zelda TOTK)

### Reproduction steps

Download Zelda TOTK,download mod of 60 fps and start it

### Log file

[Ryujinx_1.1.1217_2024-03-06_00-18-13.log](https://github.com/Ryujinx/Ryujinx/files/14502574/Ryujinx_1.1.1217_2024-03-06_00-18-13.log)

### OS

Windows 11

### Ryujinx version

1.1.1217

### Game version

1.2.1

### CPU

i7-11700k

### GPU

Nvidia Rtx 2080 Asus Rog

### RAM

32 Go

### List of applied mods

60 fps mod

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
