### ISSUE TITLE
sfdnsres IResolver: 10 (GetHostByNameRequestWithOptions) not implemented

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#642]
IResolver (GetHostByNameRequestWithOptions) is not implemented.

## Service description:

Unknown.

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/47

**Comment by TuxSH** [comment]
This is GetHostByNameRequestWithOptions (5.0+)
