### ISSUE TITLE
[Feature Request] Remove "legally-problematic" terms (eg. dumping, CFW, etc.) from the wiki.

### ISSUE THREAD

**Issue by TDuffinNTU** [Ryujinx/Ryujinx#6422]
### Overview

Following the Yuzu news, one of the stated reasons that Nintendo launched its legal attack on Yuzu was because it "encouraged" the use of proprietary Nintendo binary data (eg firmwares, keys, etc).

While the Wiki has a flat-out "Do not pirate" statement, evening mentioning the vague process of dumping, custom firmware, and other legally-grey terms might not help the project avoid Nintendo's watchful eye. It would be good to drop them entirely and let unassociated individuals bear the responsibility of maintaining documentation for those particular features.

### Smaller details

Removing sections from the wiki such as [What does \[legally problematic term\] mean?](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-what-does-dumping-mean), instead warnings users that the project cannot be associated with any activity to procure NX firmware, even if it's through "legal" methods, such as using your personal device -- Nintendo does not differentiate between "legal" and "illegal" methods of extracting binary blobs from its hardware, and in some jurisdictions it may claim that regardless of the method, the binary blobs are property *of* Nintendo itself.

It may seem like a particularly "over the top" response to the Yuzu news but its these oft-overlooked wikis and documentation that can sometimes be the thing that become blood in the proverbial water for corporate lawyers. It may even be that Ryujinx isn't a target because of other factors, but I would argue that now is the best opportunity to become more scrupulous with compliance, even at the cost of user experience (poorer documentation) and heavier contributor burden (supporting and moderating users with said poorer documentation)

### Nature of request

Legal.

### Why would this feature be useful?

Protecting the Ryujinx project and contributors from legal threats, even if this is just "security through obscurity". It would make sense community members more heavily moderate any directly-associated discord/community forums but that is outside of my domain.

**Comment by Shahil-Ayato** [comment]
Hello!
We humbly appreciate everyone’s concern on this topic, but right now we ask all of our users to not make posts about this and topics surrounding this. We are well aware of the situation that’s happened and right now there is 0 indiction of anything that’ll happen to this project. We will update things we think need to be changed accordingly but as of right now, Users seem to be more concerned then all of us on the team and again we appreciate the concern but issues like these only start creating fear mongering. Any further inquires about this topic can be asked and answered in our discord. Thanks.

**Comment by LokeYourC3PH** [comment]
> Hello! We humbly appreciate everyone’s concern on this topic, but right now we ask all of our users to not make posts about this and topics surrounding this. We are well aware of the situation that’s happened and right now there is 0 indiction of anything that’ll happen to this project. We will update things we think need to be changed accordingly but as of right now, Users seem to be more concerned then all of us on the team and again we appreciate the concern but issues like these only start creating fear mongering. Any further inquires about this topic can be asked and answered in our discord. Thanks.

Mad respect to you guys, too many run scared, you guys shrug your shoulders 😂. I salute you🫡
