### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ZongMan** [Ryujinx/Ryujinx#6429]
### Description of the issue

Loading Ryujinx presents screen flickering

### Reproduction steps

Load Ryujinx

### Log file

00:00:00.054 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.061 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.061 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.062 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.063 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.064 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.064 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2204
00:00:00.065 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.066 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.066 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.067 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.067 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.067 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.068 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.068 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.068 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.068 |I| Configuration LogValueChange: AudioVolume set to: 0.56
00:00:00.070 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.070 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.070 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.070 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.073 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.075 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1217
00:00:00.080 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.080 |N| Application Print: CPU: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz ; 36 logical
00:00:00.082 |N| Application Print: RAM: Total 31.7 GiB ; Available 26.7 GiB
00:00:00.084 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.084 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.054 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.

### OS

Win 10

### Ryujinx version

1.1.1217

### CPU

Intel 10980XE

### GPU

NVIDIA RTX 3090

### RAM

32gb

### List of applied mods

NONE

### Additional context?

Nvidia driver 537.42, 4k panel screen at 144hz full resolution,

**Comment by MutantAura** [comment]
Please use the discord for general support: https://discord.gg/ryujinx
