### ISSUE TITLE
[Feature Request] Change save directory structure to use titleID

### ISSUE THREAD

**Issue by GlazedBelmont** [Ryujinx/Ryujinx#6437]
### Overview

So, we all know of the current events so it makes sense that plenty of users would migrate to Ryujinx, these users might be confused about Ryujinx's odd save folder structure 
![image](https://github.com/Ryujinx/Ryujinx/assets/48196637/c5f9cb7e-05d7-4c82-b492-3c34265c1e00)

My request is to just use titleIDs, it's not like Ryujinx isn't using them, it does for per-game settings and such.
![image](https://github.com/Ryujinx/Ryujinx/assets/48196637/d70c9f2d-5698-4e10-a3f5-d82f21bac097)

### Smaller details

Auto-migration for existing setups because otherwise this request will break everyone's saves, due to them using the incremental structure.

### Nature of request

mainly consistency and quality of life, I've been migrating my install and just baffled at how it's structured, while my library is small, others may have a considerably bigger one which won't be easily migrate-able.

### Why would this feature be useful?

Consistency and easier migrating and syncing saves across devices (which game is which folder may change per-install), once again I do understand how this is a breaking change so some sort of auto-migration would need to be done, as previously mentioned.

**Comment by MetrosexualGarbodor** [comment]
See https://github.com/Ryujinx/Ryujinx/issues/3975#issuecomment-1535335321

The "odd save folder structure" Ryujinx uses is that of the Switch itself. If anything it's odd to do it differently.

**There are currently no plans to change the file system structure.**

If you want to migrate from an actually odd save structure, you will have to individually right click every game on your library and `open user save directory`, then paste the corresponding save files in each.

If you want to sync your Ryujinx save files with another system also running Ryujinx, the minimum folders/files you have to sync (theoretically, since every time we ask someone to test they never confirm) are:

[Ryujinx Dir]/system/profiles.json
[Ryujinx Dir]/bis/user/save
[Ryujinx Dir]/bis/user/savemeta
[Ryujinx Dir]/bis/system/save/8000000000000000

Related pull request: https://github.com/Ryujinx/Ryujinx/pull/6196

**Comment by GlazedBelmont** [comment]
I actually did not know it was the same structure as the switch. Thanks for the memo!

**Comment by titoudoc** [comment]
> See [#3975 (comment)](https://github.com/Ryujinx/Ryujinx/issues/3975#issuecomment-1535335321)
> 
> The "odd save folder structure" Ryujinx uses is that of the Switch itself. If anything it's odd to do it differently.
> 
> **There are currently no plans to change the file system structure.**
> 
> If you want to migrate from an actually odd save structure, you will have to individually right click every game on your library and `open user save directory`, then paste the corresponding save files in each.
> 
> If you want to sync your Ryujinx save files with another system also running Ryujinx, the minimum folders/files you have to sync (theoretically, since every time we ask someone to test they never confirm) are:
> 
> [Ryujinx Dir]/system/profiles.json [Ryujinx Dir]/bis/user/save [Ryujinx Dir]/bis/user/savemeta [Ryujinx Dir]/bis/system/save/8000000000000000
> 
> Related pull request: #6196

Will try it and let you know 🙂

**Comment by titoudoc** [comment]
> > See [#3975 (comment)](https://github.com/Ryujinx/Ryujinx/issues/3975#issuecomment-1535335321)
> > The "odd save folder structure" Ryujinx uses is that of the Switch itself. If anything it's odd to do it differently.
> > **There are currently no plans to change the file system structure.**
> > If you want to migrate from an actually odd save structure, you will have to individually right click every game on your library and `open user save directory`, then paste the corresponding save files in each.
> > If you want to sync your Ryujinx save files with another system also running Ryujinx, the minimum folders/files you have to sync (theoretically, since every time we ask someone to test they never confirm) are:
> > [Ryujinx Dir]/system/profiles.json [Ryujinx Dir]/bis/user/save [Ryujinx Dir]/bis/user/savemeta [Ryujinx Dir]/bis/system/save/8000000000000000
> > Related pull request: #6196
> 
> Will try it and let you know 🙂

So far so good !
Shared the designer folders with onedrike (mklink) and everything works perfect !

**Comment by Redhawk18** [comment]
> See [#3975 (comment)](https://github.com/Ryujinx/Ryujinx/issues/3975#issuecomment-1535335321)
> 
> The "odd save folder structure" Ryujinx uses is that of the Switch itself. If anything it's odd to do it differently.
> 
> **There are currently no plans to change the file system structure.**
> 
> If you want to migrate from an actually odd save structure, you will have to individually right click every game on your library and `open user save directory`, then paste the corresponding save files in each.
> 
> If you want to sync your Ryujinx save files with another system also running Ryujinx, the minimum folders/files you have to sync (theoretically, since every time we ask someone to test they never confirm) are:
> 
> [Ryujinx Dir]/system/profiles.json [Ryujinx Dir]/bis/user/save [Ryujinx Dir]/bis/user/savemeta [Ryujinx Dir]/bis/system/save/8000000000000000
> 
> Related pull request: #6196

Thank you for this list, I've been trying to track this down for a while. I understand it's your guys project I'm just thinking to get my syncthing tools to work.
