### ISSUE TITLE
Ryujinx crash on startup

### ISSUE THREAD

**Issue by JKL2021** [Ryujinx/Ryujinx#6438]
### Description of the issue

I can't start the program, as I get the console in loop writing red errors.

### Reproduction steps

n/a

### Log file

[Ryujinx_1.1.1217_2024-03-07_19-36-05.log](https://github.com/Ryujinx/Ryujinx/files/14529499/Ryujinx_1.1.1217_2024-03-07_19-36-05.log)

### OS

Win10 1803

### Ryujinx version

1.1.1217

### Game version

n/a

### CPU

i7-8700k

### GPU

NVIDIA GTX 1080

### RAM

16GB

**Comment by RR9487** [comment]
I had same issue... is there any solution for this error?

**Comment by RR9487** [comment]
oh I fixed it.... just get the latest Windows updates and it works.

**Comment by JKL2021** [comment]
Same here, but It should run from 1803-> so maybe requirents need to be updated?

**Comment by Anthonyc833** [comment]
> oh I fixed it.... just get the latest Windows updates and it works.

what build of windows did you use to double check?

**Comment by RR9487** [comment]
> > oh I fixed it.... just get the latest Windows updates and it works.
> 
> what build of windows did you use to double check?

win 10 1803->22H2

I found the error code (0x88980800) might from DirectWrite and the DirectX use Windows Update.

**Comment by Anthonyc833** [comment]
are the requirements known to be outdated?

**Comment by JKL2021** [comment]
> are the requirements known to be outdated?
> 
> edit: just did abit of looking around code im beginning to think think of two things
> 
> #1 it got outdated and code got changed so that build 1803 wont work with ryujinx
> 
> #2 directx has incompatibility to windows build 1803

I think so, if the requirements list win10 1803 as compatible but it isn't

**Comment by Anthonyc833** [comment]
why is it advertised for needing Windows 10 RS4 (Redstone 4, version 1803) or newer instead of just saying that you need to have the latest windows 10 build installed?

**Comment by AcK77** [comment]
As it said right now `You are running an outdated version of Windows. Ryujinx supports Windows 10 version 1803 and newer.`
