### ISSUE TITLE
[Feature Request] Updates list sorting

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx#6448]
### Overview

Not sure, whether to call it a bug or a feature request, but let it be a feature request: a proper sorting for the update versions. Right now a list of game updates looks unsorted.
![versions](https://github.com/Ryujinx/Ryujinx/assets/39680140/217ca5d0-df17-4a0b-9cdd-dc8fe6ed3c92)

### Smaller details

The picture above should have the listed versions sorted either as "No Update" => "Version 1.0.2" => "Version 1.0.3" or, maybe, "Version 1.0.3" => "Version 1.0.2" => "No Update" (suggesting to use the more recent version by putting it on top).

### Nature of request

Common sense.

### Why would this feature be useful?

Because unsorted lists are inconvenient to use.

**Comment by piplup55** [comment]
it's not unsorted, it goes no update, then highest to lowest update same happens on gtk if you add the updates backwards
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/f336e64a-3f51-4136-9876-b0b42e711529)

**Comment by F1ReB4LL** [comment]
Maybe to put "No Update" to the bottom? Also, "No Update" also has its own version, why not to display it as "Version 1.0.0 (No Update)"?

**Comment by piplup55** [comment]
> Maybe to put "No Update" to the bottom? Also, "No Update" also has its own version, why not to display it as "Version 1.0.0 (No Update)"?

not all games base update is 1.0.0

**Comment by F1ReB4LL** [comment]
> also has its own version

Yes, that's why I've said "also has its own version", 1.0.0 was just an example for your case.

**Comment by IsaacMarovitz** [comment]
This is working as intended IMO. The versions people are most likely to want are the latest and no update, which are the ones at the top of the list.
