### ISSUE TITLE
[Bug] Joyxoff bindings no longer working in fullscreen mode

### ISSUE THREAD

**Issue by Zobby31** [Ryujinx/Ryujinx#6451]
### Description of the issue

I am launching Ryujinx over Playnite (over Sunshine/Moonlight in order to stream the games from my PC to the couch).
Since Playnite does not provide a feature to close an emulator, the only way to achieve this is to use some third party app like JoyXoff, or reWASD in order to provide Ryujinx a command (like Alt+F4) through hotkey-like bindings.

I noticed that if Ryujinx is not toggled in fullscreen, the commands (Alt+F4 using the gamepad + JoyXoff bindings) are properly dealt with and that I am able to close the emulator but when in fullscreen nothing seems to be working.

### Reproduction steps

1) Install JoyXoff on the PC and configure a profile for Ryujinx such as :

- Primary : "Select" button : "Use secondary bindings" 
- Secondary : any other button : keyboard combination : Alt + F4

2) Launch Ryujinx over playnite (over sunshine (PC) + moonlight (Nvidia Shield or smartphone))
3) Toggle fullscreen mode
4) Try the above-mentioned binding
--> Not working

### Log file

[Ryujinx_1.1.1221_2024-03-09_23-56-42.log](https://github.com/Ryujinx/Ryujinx/files/14548099/Ryujinx_1.1.1221_2024-03-09_23-56-42.log)
[Ryujinx_1.1.1221_2024-03-10_00-06-44.log](https://github.com/Ryujinx/Ryujinx/files/14548100/Ryujinx_1.1.1221_2024-03-10_00-06-44.log)
[Ryujinx_1.1.1221_2024-03-10_00-08-25.log](https://github.com/Ryujinx/Ryujinx/files/14548101/Ryujinx_1.1.1221_2024-03-10_00-08-25.log)

### OS

Windows 11

### Ryujinx version

1.1.1221

**Comment by Iiviin** [comment]
I just came across this, did you find a fix?

**Comment by Zobby31** [comment]
I did indeed.

In fact, in Joyxoff, for each profile, it is possible to edit the "rules" for primary and secondary bindings.

I set them to "Do not disable on fullscreen mode".

Hope that helps

**Comment by Iiviin** [comment]
Thanks so much for taking the time to share that! I’ll give it a go!

**Comment by AllTheFranklins** [comment]
> I did indeed.
> 
> In fact, in Joyxoff, for each profile, it is possible to edit the "rules" for primary and secondary bindings.
> 
> I set them to "Do not disable on fullscreen mode".
> 
> Hope that helps

Works perfectly.  Thanks for the response.  How did you stumble on the solution?

**Comment by Zobby31** [comment]
By investigating.
Some research on Google and Reddit plus a pinch of perseverance.
