### ISSUE TITLE
Ryujinx crashes after launching

### ISSUE THREAD

**Issue by angmodurian** [Ryujinx/Ryujinx#6458]
### Description of the issue

Hi there I am a first time user of ryujinx. The app runs after the second try but once I tried to open an xci file, the system prompt me to update firmware after which ryujinx crashes upon launching app.

I am running the emulator through rog ally btw with Z1 extreme chip

### Reproduction steps

Just launching the app will immediately crashes it. 

### Log file

[Ryujinx_1.1.1223_2024-03-11_10-53-05.log](https://github.com/Ryujinx/Ryujinx/files/14553408/Ryujinx_1.1.1223_2024-03-11_10-53-05.log)

### OS

windows 11

### Ryujinx version

1.1.1223

### CPU

AMD Z1 extreme

### GPU

Radeon 780m

### RAM

16gb

**Comment by piplup55** [comment]
You are missing files redownload the [emulator](https://ryujinx.org/download)

**Comment by angmodurian** [comment]
Thanks for replying, I resolved it.
