### ISSUE TITLE
Unable to recognize Nvidia graphics card under Vulkan simulation[Bug]

### ISSUE THREAD

**Issue by water107** [Ryujinx/Ryujinx#6459]
### Description of the issue

![Snipaste_2024-03-11_14-12-16](https://github.com/Ryujinx/Ryujinx/assets/125546308/f60b0592-b317-475a-ab47-a4f2a69a2a0b)

### Reproduction steps

none

### Log file

none

### OS

Win 11

### Ryujinx version

Ryujinx Version: 1.1.1221

### CPU

i9-13000h

### GPU

RTX 4060

### RAM

16BG

**Comment by piplup55** [comment]
Update your drivers for both IGPU and DGPU
Latest NVIDIA drivers: https://www.nvidia.com/download/index.aspx
Latest Intel Drivers: https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html
If this does not help Vulkan applications then follow these steps: https://nvidia.custhelp.com/app/answers/detail/a_id/5182/

**Comment by zzeking** [comment]
尝试删掉游戏加加，另外用everything看看游戏加加有多少残留，我这边出现过游戏加加把vulkan环境搞得乱七八糟的情况

**Comment by l1z1cheng** [comment]
> 尝试删掉游戏加加，另外用everything看看游戏加加有多少残留，我这边出现过游戏加加把vulkan环境搞得乱七八糟的情况

感谢，真是这个原因
