### ISSUE TITLE
[Bug] Metroid out of memory error

### ISSUE THREAD

**Issue by Anthonyc833** [Ryujinx/Ryujinx#6464]
### Description of the issue

I was attempting to look at another bug relating to Metroid remastered. when attempting to get through its first door the emulator crashes descripting a out of memory error.

### Reproduction steps

.1 play till you open the first door

.2 open the ryujinx log tab to get the following error below

00:03:51.478 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".

### Log file

[Ryujinx_1.1.1224_2024-03-12_21-47-19.log](https://github.com/Ryujinx/Ryujinx/files/14574023/Ryujinx_1.1.1224_2024-03-12_21-47-19.log)

### OS

Windows 10

### Ryujinx version

1.1.1224

### Game version

1.00

### CPU

Intel(R) Core i3-10105F CPU

### GPU

NVDIA GeForce GTX 1050

### RAM

24.0 GB

### List of applied mods

N/A

### Additional context?

none

**Comment by MutantAura** [comment]
Your GPU is running out of VRAM. There is not much to be done for a card with 2GB total.
