### ISSUE TITLE
[Bug] Ryujinx Crashes on Intel Arc a770m + Vulkan

### ISSUE THREAD

**Issue by Remailleu** [Ryujinx/Ryujinx#6474]
### Description of the issue

Hi There!
On my setup, Ryujinx crashes right after the launch of a game or a few seconds when i'm lucky (usually after the boot screen) when i use my Intel Arc A770m GPU with Vulkan, but:
-It works with Open GL (with a few graphical glitches) on the same GPU
-It works perfectly with my Intel Iris Xe Integrated GPU (but i can't push this GPU more than 1x resolution) with Vulkan

Tried to tweak a few options, but nothing helped. 
Tried to uninstall with DDU and reinstall the drivers, same result.
Same with Ryujinx reinstallation.

My a770m works fine with Vulkan on other emulators for various consoles, and i haven't found any other topic with intel arc issues that helped solved my problem so far... Mostly driver updates reccommendations but i'm already on the last driver version (31.0.101.5353). This is the mobile a770m version of the GPU, not the desktop a770 usual one.

### Reproduction steps

I just need to switch to Vulkan and Arc a770m GPU to get the issue back

### Log file

[Ryujinx_1.1.1224_2024-03-12_23-33-34.log](https://github.com/Ryujinx/Ryujinx/files/14579589/Ryujinx_1.1.1224_2024-03-12_23-33-34.log)
[Ryujinx_1.1.1224_2024-03-12_23-42-11.log](https://github.com/Ryujinx/Ryujinx/files/14579590/Ryujinx_1.1.1224_2024-03-12_23-42-11.log)

### OS

Windows 11

### Ryujinx version

1.1.1218 to 1224

### Game version

All games/Versions

### CPU

i7-12700h

### GPU

Intel Arc a770m

### RAM

32GB

### List of applied mods

None

### Additional context?

Computer is Intel NUC 12 Enthusiast, for all the detailed specs...

**Comment by Maeoh** [comment]
I've been locked out of using Ryujinx for awhile as well. Looks to be the same issue. 
Same system details, though I'm on a desktop Arc a770.

[Ryujinx_1.1.1239_2024-03-19_21-10-10.log](https://github.com/Ryujinx/Ryujinx/files/14662101/Ryujinx_1.1.1239_2024-03-19_21-10-10.log)

**Comment by MutantAura** [comment]
Closing in favour of #6512
