### ISSUE TITLE
[Bug] low frame rate when window is in focus, full speed if fullscreen or window out of focus.

### ISSUE THREAD

**Issue by GumballBunny** [Ryujinx/Ryujinx#6477]
### Description of the issue

As the title states. On every game I have if i have the emulator actively in focus the frame rate tanks to almost half speed. If the click off the emulator like on the desktop but keep the window up it jumps to full speed. Going fullscreen also runs full speed. 

https://github.com/Ryujinx/Ryujinx/assets/98939069/8fc3be2f-5e38-4195-a13d-565f86dd6933

### Reproduction steps

click on window, click off window.

### Log file

00:00:00.059 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.068 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.068 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.069 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.069 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.070 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.071 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1E81
00:00:00.071 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.072 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.072 |I| Configuration LogValueChange: ScalingFilterLevel set to: 100
00:00:00.074 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.080 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.080 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.080 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.080 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.081 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.081 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.083 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.083 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.083 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.083 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.086 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.092 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1224
00:00:00.097 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.097 |N| Application Print: CPU: AMD Ryzen 7 3800X 8-Core Processor ; 16 logical
00:00:00.099 |N| Application Print: RAM: Total 31.9 GiB ; Available 20.8 GiB
00:00:00.101 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.102 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.131 |I| Gpu : Backend Threading (On): True
00:00:00.443 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.1
00:00:00.443 |I| Application LoadGuestApplication: Loading as XCI.
00:00:00.457 |I| Application AddAocItem: Found AddOnContent with TitleId 0100152000023001
00:00:00.472 |I| ModLoader QueryContentsDir: Searching mods for Application 0100152000022000 in "E:\Nintendo Switch\Ryujinx\portable\mods\contents"
00:00:00.479 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100152000023001 in "E:\Nintendo Switch\Ryujinx\portable\mods\contents"
00:00:00.480 |I| ModLoader QueryContentsDir: Searching mods for Application 0100152000022000 in "E:\Nintendo Switch\Ryujinx\portable\sdcard\atmosphere\contents"
00:00:00.481 |I| ModLoader AddModsFromDirectory: Found mod 'Gamecube Wario Colosseum' [R]
00:00:00.481 |I| ModLoader AddModsFromDirectory: Found mod 'Mario Sports Mix Pack' [R]
00:00:00.481 |I| ModLoader AddModsFromDirectory: Found mod 'Mini BGM.bars' [R]
00:00:00.481 |I| ModLoader AddModsFromDirectory: Found mod 'Sonic And Amy' [R]
00:00:00.481 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100152000023001 in "E:\Nintendo Switch\Ryujinx\portable\sdcard\atmosphere\contents"
00:00:00.483 |I| Loader Load: Loading rtld...
00:00:00.489 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.489 |I| Loader Load: Loading main...
00:00:00.567 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\TurboS_chg6\App\Rom\NX32\Product\TurboS.nss
    SDK Libraries: SDK MW+Nintendo+PiaCommon-5_6_4
                   SDK MW+Nintendo+Pia-5_6_4
                   SDK MW+Nintendo+NEX-4_3_3-apptrbs
                   SDK MW+Nintendo+NintendoSDK_gfx-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_G3d-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Atk-4_4_0-Release
                   SDK MW+Nintendo+NEX_CO-4_3_3
                   SDK MW+Nintendo+PiaInet-5_6_4
                   SDK MW+Nintendo+PiaNat-5_6_4
                   SDK MW+Nintendo+PiaLan-5_6_4
                   SDK MW+Nintendo+PiaSession-5_6_4
                   SDK MW+Nintendo+PiaTransport-5_6_4
                   SDK MW+Nintendo+PiaLocal-5_6_4
                   SDK MW+Nintendo+NintendoSDK_libcurl-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Font-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-4_4_0-Release
                   SDK MW+Nintendo+NEX_MM-4_3_3
                   SDK MW+Nintendo+NEX_DS-4_3_3
                   SDK MW+Nintendo+NEX_RK-4_3_3
                   SDK MW+Nintendo+NEX_UT-4_3_3
                   SDK MW+Nintendo+NintendoSDK_libz-4_4_0-Release
00:00:00.567 |I| Loader Load: Loading subsdk0...
00:00:00.588 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-4_4_0-Release
00:00:00.588 |I| Loader Load: Loading sdk...
00:00:00.620 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 4.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-4_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-4_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-4_4_0-Release
00:00:00.730 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.287 |I| Ptc Load: Loaded Translation Cache (size: 45225857 bytes, translated functions: 60162).
00:00:01.305 |I| Ptc Load: Loaded Profiling Info (size: 177597 bytes, profiled functions: 59281).
00:00:01.312 |I| Loader LoadNsos: Loading image 0 at 0x0000000000700000...
00:00:01.313 |I| Loader LoadNsos: Loading image 1 at 0x0000000000704000...
00:00:01.318 |I| Loader LoadNsos: Loading image 2 at 0x0000000001660000...
00:00:01.320 |I| Loader LoadNsos: Loading image 3 at 0x0000000001c2e000...
00:00:01.325 |I| ModLoader LoadCheats: Build ids found for application 0100152000022000:
    392D5F620063DCF173BD5C4EA2DE7D46733A7184000000000000000000000000
    9EF5CAA2D5B933C772358C5AA6FABA1500000000000000000000000000000000
    EA3F2A9B705EEF46ED08414F88C49ECF2559B4FB000000000000000000000000
    F0D9307B48E4E8F147A40E44A9CBC555D4C6148F000000000000000000000000
00:00:01.328 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Application 0100152000022000
00:00:01.328 |I| ModLoader ApplyRomFsMods: No files found. Using base RomFS
00:00:01.329 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.402 |I| Loader Start: Application Loaded: Mario Kart 8 Deluxe v3.0.1 [0100152000022000] [32-bit]
00:00:01.456 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.468 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.920 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2080 SUPER (Vulkan v1.3.277, Driver v551.76.0.0)
00:00:01.926 |I| GPU.MainThread Gpu LoadShaders: Loading 880 shaders from the cache...
00:00:04.586 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:05.284 |I| HLE.GuestThread.48 Ptc LoadTranslations: 59281 translated functions loaded
00:00:05.365 |S| HLE.OsThread.49 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:05.368 |S| HLE.OsThread.49 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:05.369 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.369 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:05.375 |S| HLE.OsThread.49 ServicePctl Initialize: Stubbed. 
00:00:06.070 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed. 
00:00:06.076 |I| HLE.OsThread.49 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:06.096 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed. 
00:00:06.107 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:06.146 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.146 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.147 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.147 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:06.148 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.148 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:06.148 |S| HLE.OsThread.8 ServiceNv SetPriority: Stubbed. 
00:00:06.149 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:06.180 |S| HLE.OsThread.7 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:06.181 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 0}
00:00:06.184 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:06.185 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:06.185 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Player1,Player2,Player3,Player4,Handheld
00:00:06.321 |S| HLE.OsThread.49 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72080821221203968}
00:00:06.459 |S| HLE.OsThread.7 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:06.470 |S| HLE.OsThread.49 ServiceAcc CheckAvailability: Stubbed. 
00:00:06.470 |S| HLE.OsThread.49 ServiceAcc GetNintendoAccountUserResourceCacheForApplication: Stubbed. {NetworkServiceAccountId: 51966}
00:00:06.471 |S| HLE.OsThread.49 ServiceAm LockExit: Stubbed. 
00:00:06.479 |S| HLE.OsThread.49 ServiceAm UnlockExit: Stubbed. 
00:00:06.483 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.483 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.483 |S| HLE.OsThread.49 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.483 |S| HLE.OsThread.49 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.484 |S| HLE.OsThread.49 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:07.309 |I| HLE.OsThread.15 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:07.312 |I| HLE.OsThread.15 AudioRenderer Initialize: Initializing with REV4
00:00:07.324 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:07.325 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:07.343 |I| HLE.OsThread.15 AudioRenderer Start: Starting renderer id 0
00:00:07.376 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:11.178 |S| HLE.OsThread.7 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:11.185 |S| HLE.OsThread.49 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:11.186 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100152000023001
00:00:11.187 |S| HLE.OsThread.49 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:11.188 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100152000023001
00:00:11.247 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: dlc 
 Report: {
    "CheckedTime": 20240313051255,
    "DlcState": 3,
    "DlcVersion": 10002
}

00:00:11.301 |S| HLE.OsThread.49 ServiceAm LockExit: Stubbed. 
00:00:11.327 |S| HLE.OsThread.49 ServiceAm UnlockExit: Stubbed. 
00:00:11.333 |I| HLE.OsThread.26 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 125
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: user_data 
 Report: {
    "Version": "3.0.1",
    "StartupCount": 11,
    "GrandPrixTrophy": "000000000000000000000000000000000000000000000000000000000000",
    "GrandPrixTrophyCnsw": "000000000000000000000000000000000000000000000000000000000000",
    "TotalRaceNum": 1,
    "TotalBalloonBattleNum": 0,
    "TotalKeidoroBattleNum": 0,
    "TotalBombBattleNum": 0,
    "TotalCoinBattleNum": 0,
    "TotalShineBattleNum": 0,
    "TotalMileageMeter": 4965,
    "TotalRunTimeFrame": 15376,
    "TotalDrift": 60,
    "TotalMiniTurbo1": 30,
    "TotalMiniTurbo2": 3,
    "TotalMiniTurbo3": 1,
    "TotalJumpAction": 13,
    "TotalJugemRescue": 2,
    "TotalGyroTimeFrame": 0,
    "TotalAssistTimeFrame": 0,
    "TotalAutoAccelTimeFrame": 0,
    "TotalShowMapTimeFrame": 15376,
    "TotalFlyTimeFrame": 566,
    "TotalSwimTimeFrame": 2186,
    "TotalCoin": 10,
    "TotalDisconnectCount": 0,
    "TotalWin": 0,
    "TotalLose": 0,
    "RaceRate": 1000,
    "BattleRate": 1000,
    "OpenGoldMario": 0,
    "OpenBodyFlags": {
        "TypeCode": 0,
        "Value": "0x0000014A0080C829"
    },
    "OpenTireFlags": {
        "TypeCode": 0,
        "Value": "0x000000000000C829"
    },
    "OpenWingFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000004829"
    },
    "Win150ccStaffGhostFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Win150ccStaffGhostCount": 0,
    "Try150ccTimeAttackFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Try150ccTimeAttackCount": 0,
    "Win150ccStaffGhostFlagsCnsw": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Win150ccStaffGhostCountCnsw": 0,
    "Try150ccTimeAttackFlagsCnsw": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Try150ccTimeAttackCountCnsw": 0,
    "Win200ccStaffGhostFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Win200ccStaffGhostCount": 0,
    "Try200ccTimeAttackFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Try200ccTimeAttackCount": 0,
    "Win200ccStaffGhostFlagsCnsw": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Win200ccStaffGhostCountCnsw": 0,
    "Try200ccTimeAttackFlagsCnsw": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "Try200ccTimeAttackCountCnsw": 0,
    "WatchEndingFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "OpenMiiSuitsFlags": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "DlcState": 3
}

00:00:35.453 |W| HLE.GuestThread.55 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.48 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.56 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.51 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.67 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.57 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.73 KernelSvc : WaitForAddress() = TerminationRequested
00:00:35.453 |W| HLE.GuestThread.58 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.65 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.86 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.59 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.66 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.60 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.87 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.61 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.62 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.75 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.76 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.63 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.64 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.68 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.77 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.74 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.78 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.82 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.83 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.79 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.84 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.81 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.91 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.92 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.93 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.94 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.95 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.454 |W| HLE.GuestThread.96 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:35.460 |I| HLE.OsThread.15 AudioRenderer Stop: Stopping renderer id 0
00:00:35.460 |I| HLE.OsThread.15 AudioRenderer Stop: Stopped renderer id 0
00:00:35.460 |I| HLE.OsThread.15 AudioRenderer ReleaseSessionId: Unregistered renderer (0)
00:00:35.463 |I| AudioProcessor.Worker AudioRenderer Work: Stopping audio processor
00:00:35.490 |I| HLE.OsThread.15 AudioRenderer StopLocked: Stopped audio renderer
00:00:35.506 |W| GUI.WindowThread ServiceNv Close: Closing channel

### OS

Windows 11

### Ryujinx version

1.1.1224

### Game version

3.0.1

### CPU

Ryzen 7 3800x

### GPU

RTX 2080 Super

### RAM

32

**Comment by GumballBunny** [comment]
it stopped doing it after the latest update so I'm assuming it was fixed.

**Comment by goodra64** [comment]
I'm having this exact problem currently. 

I tested older builds and I found that it doesn't happen on 1.1215 and the few I tested below that (both test.ava and normal builds). 
It does happen on build 1.1.1216 and the few I tested above that (including the latest as of writing this, 1.1.1321).

CPU: Ryzen 5 3600
GPU: GTX 1050 Ti
Ram: 16gb
OS: Windows 11

[Ryujinx_1.1.1215_2024-05-24_00-40-46.log](https://github.com/Ryujinx/Ryujinx/files/15427911/Ryujinx_1.1.1215_2024-05-24_00-40-46.log)

[Ryujinx_1.1.1216_2024-05-24_01-08-28.log](https://github.com/Ryujinx/Ryujinx/files/15427905/Ryujinx_1.1.1216_2024-05-24_01-08-28.log)

**Comment by Mario-119** [comment]
Was having the same issue, I can confirm that disabling freesync worked for me as well (I have an LG 38GL950G).

Specs are below as reference 
CPU: Ryzen 5 7600X
GPU: RX 6750 XT
RAM: 32GB DDR5 @ 6400MHz
OS: Windows 11 26120.670

**Comment by GumballBunny** [comment]
As long as I lay fullscreen its not an issue. Just annoying it does it when in windowed.

**Comment by GamerzHell9137** [comment]
> As long as I play fullscreen its not an issue. Just annoying it does it when in windowed.

Try settings this in Nvidia settings.
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/83bf71c2-f83a-4cc6-9e23-33f79b843fb4)
