### ISSUE TITLE
Frame Skip Option[Feature Request]

### ISSUE THREAD

**Issue by Garou312** [Ryujinx/Ryujinx#6479]
### Overview

A Frame Skip Option is a feature which skip frames when games will run in less frame rate than intended in order to prevent slow motion. And it's not necessary for it to do good for low end gamers but gamers with decent pc play games with mods like 60 fps but if the fps drops for say 50 then it will run in slow mo. That's why this feature is necessary.

### Smaller details

A Frame Skip Option is a feature which skip frames when games will run in less frame rate than intended in order to prevent slow motion.

### Nature of request

Frame Skip, prevents slow motion

### Why would this feature be useful?

It will be useful for preventing sow motion in games. And it's not necessary for it to do good for low end gamers but gamers with decent pc play games with mods like 60 fps but if the fps drops for say 50 then it will run in slow mo. That's why this feature is necessary.

**Comment by MutantAura** [comment]
This is not possible to implement.
Closing as not planned.
