### ISSUE TITLE
STUCK.

### ISSUE THREAD

**Issue by HELPME23333333** [Ryujinx/Ryujinx#6494]
### Description of the issue

When loading Splatoon 3 (NSP) file it gets stuck on "loading as NSP file"

### Reproduction steps

everytime i try to load it

### Log file

00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.160 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.180 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.180 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.182 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.184 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.186 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.186 |I| Configuration LogValueChange: PreferredGpu set to: 0x8086_0x8A56
00:00:00.187 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.189 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.189 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.191 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.202 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.202 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.202 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.203 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.203 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.203 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.203 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.203 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.203 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.204 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.205 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.207 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.207 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.207 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.207 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.212 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.220 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1231
00:00:00.234 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.234 |N| Application Print: CPU: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz ; 4 logical
00:00:00.245 |N| Application Print: RAM: Total 3.8 GiB ; Available 0.7 GiB
00:00:00.252 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.253 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.197 |I| Gpu : Backend Threading (Auto): True
00:00:00.851 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.0
00:00:00.851 |I| Application LoadGuestApplication: Loading as NSP.

### OS

Windows 10

### Ryujinx version

1.1.1231

### Game version

v65536

### GPU

intel intregrated

### RAM

4gb

### List of applied mods

N/A

### Additional context?

N/A

**Comment by Shahil-Ayato** [comment]
This is a not an error with the emulator, please visit our discord for support

**Comment by gdkchan** [comment]
Double check the updates and DLCs for the game, make sure the files have not been moved, and make sure you're trying to load the base game file, not one of the update or DLC files.

**Comment by HELPME23333333** [comment]
> Double check the updates and DLCs for the game, make sure the files have not been moved, and make sure you're trying to load the base game file, not one of the update or DLC files.

I checked,its base im gonna try load it in XCI now
