### ISSUE TITLE
[Bug] Ryujinx crashes after loading the game and entering my name in Pokemon Sword 

### ISSUE THREAD

**Issue by ZFDR12** [Ryujinx/Ryujinx#6501]
### Description of the issue

Hello! 

I have the latest update of Ryujinx (1.1.1231) and as soon as I load up the game and select name name, it crashes immediately. It reproduces 100%. I have tried change from Vulkan to OpenGL, disabling VSync, chaning the resolution scale, deleting the cache and a lot of other stuff recommended from youtube, but nothing worked.  It crashes after this screen :
![Screenshot 2024-03-15 115510](https://github.com/Ryujinx/Ryujinx/assets/163520985/821d93d4-960d-414e-a598-12813d7dd2b3)

And the error I'm getting: 
![Screenshot 2024-03-15 120116](https://github.com/Ryujinx/Ryujinx/assets/163520985/5f1185f9-632d-4f24-a1cf-ffefdf039af4)

If anyone knows how to fix this, that'd be greatly appreciated. Thank you!

### Reproduction steps

Open Ryujinx
Open the game
Select English
Enter a random username
Press OK
-crash-

### Log file

00:00:00.059 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.067 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.067 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.068 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.069 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.070 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.070 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1B82
00:00:00.071 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.072 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.072 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.074 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.080 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.080 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.080 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.080 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.081 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.081 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.081 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.083 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.083 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.083 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.083 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.086 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.090 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1231
00:00:00.094 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.094 |N| Application Print: CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz ; 6 logical
00:00:00.096 |N| Application Print: RAM: Total 31.9 GiB ; Available 23.7 GiB
00:00:00.098 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.099 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.118 |I| Gpu : Backend Threading (Auto): True
00:00:00.423 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.0
00:00:00.423 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.463 |I| ModLoader QueryContentsDir: Searching mods for Application 0100ABF008968000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.464 |I| ModLoader QueryContentsDir: Searching mods for Application 0100ABF008968000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.467 |I| Loader Load: Loading rtld...
00:00:00.474 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.474 |I| Loader Load: Loading main...
00:00:00.864 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\rigel\rom\RomBuild\program\output\NX64\Release\main.nss
    SDK Libraries: SDK MW+NVIDIA+PhysX-3_4_2-release
                   SDK MW+Nintendo+NEX_DS-4_6_8
                   SDK MW+Nintendo+NEX_MM-4_6_8
                   SDK MW+Nintendo+NEX-4_6_8-appor
                   SDK MW+Nintendo+NEX_UT-4_6_8
                   SDK MW+Nintendo+PiaCommon-5_18_98
                   SDK MW+Nintendo+Pia-5_18_98
                   SDK MW+Nintendo+PiaLan-5_18_98
                   SDK MW+Nintendo+PiaLocal-5_18_98
                   SDK MW+Nintendo+PiaNex-5_18_98-forNEX-4_6_2
                   SDK MW+Nintendo+PiaSession-5_18_98
                   SDK MW+Nintendo+PiaTransport-5_18_98
                   SDK MW+NINTENDO+nlib_LZ4-19_0226
                   SDK MW+Nintendo+NintendoSDK_libcurl-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-7_3_2-Release
00:00:00.864 |I| Loader Load: Loading subsdk0...
00:00:00.922 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-7_3_2-Release
00:00:00.922 |I| Loader Load: Loading subsdk1...
00:00:00.999 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: glslc
00:00:00.999 |I| Loader Load: Loading sdk...
00:00:01.108 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:01.212 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.418 |I| Ptc Load: Loaded Translation Cache (size: 14675425 bytes, translated functions: 14455).
00:00:01.427 |I| Ptc Load: Loaded Profiling Info (size: 47699 bytes, profiled functions: 15124).
00:00:01.436 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.438 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.453 |I| Loader LoadNsos: Loading image 2 at 0x000000000ae89000...
00:00:01.456 |I| Loader LoadNsos: Loading image 3 at 0x000000000b5a6000...
00:00:01.459 |I| Loader LoadNsos: Loading image 4 at 0x000000000be18000...
00:00:01.465 |I| ModLoader LoadCheats: Build ids found for application 0100ABF008968000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    A3B75BCD3311385AEED67FBEEB79CBB7BF02F471000000000000000000000000
    93FF8252D975ADF07230CB86C83301C53F2804DF000000000000000000000000
    A36DAC0E0A5ED3B41482B6BB85625C73EECD0023000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:01.469 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.525 |I| Loader Start: Application Loaded: Pokémon Sword v1.3.2 [0100abf008968000] [64-bit]
00:00:01.768 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.779 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:01.808 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2 (4.6.0 NVIDIA 551.76)
00:00:01.833 |I| GPU.MainThread Gpu LoadShaders: Loading 26 shaders from the cache...
00:00:01.924 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.301 |I| HLE.GuestThread.48 Ptc LoadTranslations: 14362 translated functions loaded
00:00:02.309 |I| HLE.GuestThread.48 Ptc MakeAndSaveTranslations: 0 of 762 functions translated | Thread count: 5
00:00:03.242 |I| HLE.GuestThread.48 Ptc MakeAndSaveTranslations: 762 of 762 functions translated | Thread count: 5 in 0.9321069 s
00:00:03.356 |S| HLE.OsThread.49 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:03.360 |S| HLE.OsThread.49 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:03.360 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:03.361 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:03.367 |S| HLE.OsThread.49 ServicePctl Initialize: Stubbed. 
00:00:03.705 |I| Ptc Save: Saved Translation Cache (size: 15591595 bytes, translated functions: 15217).
00:00:04.757 |S| HLE.OsThread.49 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:04.808 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed. 
00:00:04.820 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed. 
00:00:04.833 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:04.890 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:04.891 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:04.891 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:04.892 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:04.892 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:04.893 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:04.893 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:04.894 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:04.901 |I| HLE.OsThread.49 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:06.109 |W| HLE.GuestThread.48 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:06.315 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.315 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.316 |S| HLE.OsThread.49 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.319 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:06.325 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:06.328 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:06.332 |S| HLE.OsThread.7 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:06.333 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -2815385353546891264}
00:00:06.333 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -2815385147388461056}
00:00:06.357 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.357 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.357 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.357 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:06.357 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.357 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:06.358 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:06.358 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:06.363 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.364 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.364 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.364 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:06.364 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.364 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:06.364 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:06.365 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:08.625 |S| HLE.OsThread.49 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72246641462509568}
00:00:08.627 |S| HLE.OsThread.49 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:08.642 |S| HLE.OsThread.17 ServiceFriend GetFriendList: Stubbed. {userId: 00000000000000010000000000000000 ; offset: 0 ; filter: { PresenceStatus: None, IsFavoriteOnly: False, IsSameAppPresenceOnly: False, IsSameAppPlayedOnly: False, IsArbitraryAppPlayedOnly: False, PresenceGroupId: 0 } ; pidPlaceholder: 0 ; pid: 125}
00:00:08.694 |S| HLE.OsThread.49 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:08.695 |S| HLE.OsThread.49 ServiceAcc CheckAvailability: Stubbed. 
00:00:08.695 |S| HLE.OsThread.49 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:08.763 |S| HLE.OsThread.49 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:08.773 |S| HLE.OsThread.7 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:00:08.774 |S| HLE.OsThread.7 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:00:08.774 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:08.774 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:08.774 |S| HLE.OsThread.7 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:08.774 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -2555301787871477760}
00:00:08.775 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -2555301581713047552}
00:00:09.475 |I| HLE.OsThread.15 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:09.507 |I| HLE.OsThread.15 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:01:03.247 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 47735 bytes, profiled functions: 15135).
00:01:06.622 |S| HLE.OsThread.49 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:01:06.626 |I| HLE.OsThread.49 ServiceAm .ctor: Applet 'SoftwareKeyboard' created.
00:01:19.311 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.1231

### Game version

1.3.2

### CPU

i5-8500k

### GPU

1070ti

### RAM

32gb

**Comment by valxantr** [comment]
I can MAYBE add to this error, but Pokemon Shield, after the initial cutscene when picking up the bag.

[Ryujinx_1.1.880_2024-03-15_12-09-00.log](https://github.com/Ryujinx/Ryujinx/files/14614760/Ryujinx_1.1.880_2024-03-15_12-09-00.log)
[Ryujinx_1.1.1231_2024-03-15_11-52-25.log](https://github.com/Ryujinx/Ryujinx/files/14614761/Ryujinx_1.1.1231_2024-03-15_11-52-25.log)
[Ryujinx_1.1.1231_2024-03-15_11-54-59.log](https://github.com/Ryujinx/Ryujinx/files/14614762/Ryujinx_1.1.1231_2024-03-15_11-54-59.log)

Tried on two different ryujinx versions as I just updated today but the issue remains. 

I think the issue is the following from the end of the log(s)

00:00:42.358 |E| HLE.GuestThread.24 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:42.403 |E| HLE.GuestThread.24 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266

**Comment by Anthonyc833** [comment]
what region is your game and what region is your keys?

**Comment by ZFDR12** [comment]
> what region is your game and what region is your keys?

The game is Europe region. Not so sure about the keys, don't know how to find out.

**Comment by piplup55** [comment]
Bad dump, Re-dump your game.
`LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

**Comment by ZFDR12** [comment]
I'm sorry, but what  does "Bad dump, Re-dump your game." mean? From what I found on google, basically it means to re-download the files? Sorry, I'm new to this:)
