### ISSUE TITLE
[Bug][MLB 24 The Show] ServiceNotImplementedException for IShopServiceAccessServerInterface while launching

### ISSUE THREAD

**Issue by mrashed-dev** [Ryujinx/Ryujinx#6504]
### Description of the issue

Launching MLB 24 The Show it crashes within 2 seconds. Settings set to OpenGL or Vulkan makes no difference. For reference, MLB 23 The Show worked fine on OpenGL. Firmware is on 17.0.1 which is the minimum specified FW version for this game.

### Reproduction steps

1. Load the game into Ryujinx
2. Install the v1.0.1 update and the DLC
3. Launch the game

### Log file

[Ryujinx_1.1.1231_2024-03-15_12-14-13.log](https://github.com/Ryujinx/Ryujinx/files/14618103/Ryujinx_1.1.1231_2024-03-15_12-14-13.log)

### OS

Windows 11

### Ryujinx version

1.1.1231

### Game version

1.0.1

### CPU

AMD Ryzen 5 3600

### GPU

NVIDIA RTX 2070 Super

### RAM

16 GB

**Comment by GamerzHell9137** [comment]
Wrong place to post this.
Make a compatibility report here https://github.com/Ryujinx/Ryujinx-Games-List/issues
