### ISSUE TITLE
[Bug] Ryujinx crashes on Intel Arc A770 and Vulkan

### ISSUE THREAD

**Issue by kirusyaga** [Ryujinx/Ryujinx#6512]
### Description of the issue

We return where are we started at times of release of TotK. Vulkan exception "ErrorDeviceLost" on startup of any game.

### Reproduction steps

1. Launch Ryujinx
2. Start any game (e.g. Animal Crossing New Horizons, Legend of Zelda: Tears of the Kingdom)

### Log file

[Ryujinx_1.1.1231_2024-03-16_19-31-21.log](https://github.com/Ryujinx/Ryujinx/files/14624584/Ryujinx_1.1.1231_2024-03-16_19-31-21.log)
[Ryujinx_1.1.1231_2024-03-16_19-42-05.log](https://github.com/Ryujinx/Ryujinx/files/14624586/Ryujinx_1.1.1231_2024-03-16_19-42-05.log)

### OS

Windows 10 22H2 19045.3930

### Ryujinx version

1.1.1231

### Game version

ACNH 2.0.6, TOTK 1.1.2

### CPU

i9-7940X

### GPU

Intel ARC A770 16GB

### RAM

128 GB

### List of applied mods

-

**Comment by Remailleu** [comment]
It won't help, but you're not alone... 😋

https://github.com/Ryujinx/Ryujinx/issues/6474

**Comment by kirusyaga** [comment]
It was 1.1.1141.

**Comment by lijia80622** [comment]
1196 still work，1199 crash

**Comment by nico-abram** [comment]
If I'm reading the commit log correctly, it seems these 3 pull requests are the only difference between those 2 versions:
https://github.com/Ryujinx/Ryujinx/pull/6315
https://github.com/Ryujinx/Ryujinx/pull/6154
https://github.com/Ryujinx/Ryujinx/pull/6240

**Comment by gdkchan** [comment]
If we know the specific version/PR where the problem started, we can try to disable it for Intel. Unfortunately, I can't test it right now as I don't have an Intel Arc GPU.

**Comment by Remailleu** [comment]
Just retested on my a770m, and it's between 1197 and 1198... 1197 runs fine, and 1198 crashes at the launch of any game...

**Comment by Remailleu** [comment]
> If we know the specific version/PR where the problem started, we can try to disable it for Intel. Unfortunately, I can't test it right now as I don't have an Intel Arc GPU.

Just retested on my a770m, and it's between 1197 and 1198... 1197 runs fine, and 1198 crashes at the launch of any game...

**Comment by gdkchan** [comment]
Can someone check if the build here fixes the issue? https://github.com/Ryujinx/Ryujinx/pull/6551#issuecomment-2016331302

**Comment by Remailleu** [comment]
The issue seems to be fixed for me with this build yes!

**Comment by aoyegudu** [comment]
> Can someone check if the build here fixes the issue? [#6551 (comment)](https://github.com/Ryujinx/Ryujinx/pull/6551#issuecomment-2016331302)

Great!!! Thank you very much, my a770 can play the game normally, thank you very much.
