### ISSUE TITLE
[Bug] Avalonia not respecting scaling

### ISSUE THREAD

**Issue by rowbawts** [Ryujinx/Ryujinx#6529]
### Description of the issue

I use 200% scaling as I have a 4K monitor and with the new default to Avalonia on Linux my window has become tiny, before it worked as expected.

Steam window for reference.
![image](https://github.com/Ryujinx/Ryujinx/assets/13012832/0008046b-53cb-4622-b341-38d30a4d3ce5)

### Reproduction steps

Just open Ryujinx with a non 100% scaling set.

### Log file

N/A

### OS

Fedora 39

### Ryujinx version

1.1.1239

### CPU

Ryzen 9 5950X

### GPU

AMD RX 6950XT

### RAM

64GB

**Comment by MutantAura** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/9390 for the current limitations with X11/Avalonia scaling.
Can be worked around via environment variables: https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

**Comment by rowbawts** [comment]
That sucks, the env variables don't seem to work as a workaround for me I don't have XRANDR in my system or any of that as the only X implementation I have is through Xwayland.

**Comment by TathagataDM** [comment]
@rowbawts 

> That sucks, the env variables don't seem to work as a workaround for me I don't have XRANDR in my system or any of that as the only X implementation I have is through Xwayland.

This reddit post was helpful for me, to find wayland alternatives to xrandr: https://www.reddit.com/r/wayland/comments/kuiqcl/xrandr_equivalent_on_wayland/
