### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by juicer1337** [Ryujinx/Ryujinx#6534]
### Description of the issue

Ryujinx Crashing

### Reproduction steps

Launch PKMN Sword 
Let it load
Crash

### Log file

00:00:00.054 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.061 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.062 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.063 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.064 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.065 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.065 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2204
00:00:00.066 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.066 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.067 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.068 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.074 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.074 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.074 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.074 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.074 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.074 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.074 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.074 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.074 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.075 |I| Configuration LogValueChange: AudioBackend set to: Dummy
00:00:00.075 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.076 |I| Configuration LogValueChange: MemoryManagerMode set to: SoftwarePageTable
00:00:00.076 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.076 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.076 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.080 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.083 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1239
00:00:00.087 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.087 |N| Application Print: CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz ; 16 logical
00:00:00.089 |N| Application Print: RAM: Total 31.9 GiB ; Available 22.3 GiB
00:00:00.091 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.092 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.094 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.
00:00:00.139 |I| Gpu : Backend Threading (On): True
00:00:00.357 |N| Application LoadGuestApplication: Using Firmware Version: 12.0.0
00:00:00.357 |I| Application LoadGuestApplication: Loading as XCI.
00:00:00.389 |I| Application AddAocItem: Found AddOnContent with TitleId 0100ABF008969002
00:00:00.389 |I| Application AddAocItem: Found AddOnContent with TitleId 0100ABF008969001
00:00:00.408 |I| ModLoader QueryContentsDir: Searching mods for Application 0100ABF008968000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.409 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100ABF008969001 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.409 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100ABF008969002 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.410 |I| ModLoader QueryContentsDir: Searching mods for Application 0100ABF008968000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.410 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100ABF008969001 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.410 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100ABF008969002 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.413 |I| Loader Load: Loading rtld...
00:00:00.419 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.419 |I| Loader Load: Loading main...
00:00:00.782 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\rigel\rom\RomBuild\program\output\NX64\Release\main.nss
    SDK Libraries: SDK MW+NVIDIA+PhysX-3_4_2-release
                   SDK MW+Nintendo+NEX_DS-4_6_8
                   SDK MW+Nintendo+NEX_MM-4_6_8
                   SDK MW+Nintendo+NEX-4_6_8-appor
                   SDK MW+Nintendo+NEX_UT-4_6_8
                   SDK MW+Nintendo+PiaCommon-5_18_98
                   SDK MW+Nintendo+Pia-5_18_98
                   SDK MW+Nintendo+PiaLan-5_18_98
                   SDK MW+Nintendo+PiaLocal-5_18_98
                   SDK MW+Nintendo+PiaNex-5_18_98-forNEX-4_6_2
                   SDK MW+Nintendo+PiaSession-5_18_98
                   SDK MW+Nintendo+PiaTransport-5_18_98
                   SDK MW+NINTENDO+nlib_LZ4-19_0226
                   SDK MW+Nintendo+NintendoSDK_libcurl-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-7_3_2-Release
00:00:00.782 |I| Loader Load: Loading subsdk0...
00:00:00.839 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-7_3_2-Release
00:00:00.839 |I| Loader Load: Loading subsdk1...
00:00:00.912 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: glslc
00:00:00.913 |I| Loader Load: Loading sdk...
00:00:01.014 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:01.087 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.094 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.095 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.108 |I| Loader LoadNsos: Loading image 2 at 0x000000000ae89000...
00:00:01.110 |I| Loader LoadNsos: Loading image 3 at 0x000000000b5a6000...
00:00:01.113 |I| Loader LoadNsos: Loading image 4 at 0x000000000be18000...
00:00:01.118 |I| ModLoader LoadCheats: Build ids found for application 0100ABF008968000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    A3B75BCD3311385AEED67FBEEB79CBB7BF02F471000000000000000000000000
    93FF8252D975ADF07230CB86C83301C53F2804DF000000000000000000000000
    A36DAC0E0A5ED3B41482B6BB85625C73EECD0023000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:01.122 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.186 |I| Loader Start: Application Loaded: Pokémon Sword v1.3.2 [0100abf008968000] [64-bit]
00:00:01.242 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:01.607 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3090 (Vulkan v1.3.277, Driver v551.76.0.0)
00:00:01.617 |I| GPU.MainThread Gpu LoadShaders: Loading 11 shaders from the cache...
00:00:01.688 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.577 |S| HLE.OsThread.49 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.666 |S| HLE.OsThread.49 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.673 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.679 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.755 |S| HLE.OsThread.49 ServicePctl Initialize: Stubbed. 
00:00:03.243 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:05.244 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:06.699 |S| HLE.OsThread.49 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.882 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed. 
00:00:07.000 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed. 
00:00:07.056 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.203 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:07.204 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:07.204 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:07.205 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:07.208 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:07.208 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:07.210 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:07.219 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:07.245 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:07.332 |I| HLE.OsThread.49 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:08.732 |W| HLE.GuestThread.48 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:09.245 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:09.296 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:09.297 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:09.297 |S| HLE.OsThread.49 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:09.327 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:09.377 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:09.383 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:09.386 |S| HLE.OsThread.7 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:09.389 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -2815386727936425984}
00:00:09.389 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -2815386521777995776}
00:00:10.029 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:10.030 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:10.030 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:10.030 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:10.030 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:10.030 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:10.030 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:10.031 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:10.035 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:10.035 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:10.036 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:10.036 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:10.036 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:10.036 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:10.036 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:10.036 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:11.248 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:12.375 |S| HLE.OsThread.49 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:12.381 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100ABF008969001
00:00:12.383 |S| HLE.OsThread.49 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:12.385 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100ABF008969001
00:00:12.388 |S| HLE.OsThread.49 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 2}
00:00:12.389 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100ABF008969002
00:00:12.391 |S| HLE.OsThread.49 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 2}
00:00:12.391 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100ABF008969002
00:00:13.249 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:15.250 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:16.623 |S| HLE.OsThread.49 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72246641462509568}
00:00:16.633 |S| HLE.OsThread.49 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:16.666 |S| HLE.OsThread.17 ServiceFriend GetFriendList: Stubbed. {userId: 00000000000000010000000000000000 ; offset: 0 ; filter: { PresenceStatus: None, IsFavoriteOnly: False, IsSameAppPresenceOnly: False, IsSameAppPlayedOnly: False, IsArbitraryAppPlayedOnly: False, PresenceGroupId: 0 } ; pidPlaceholder: 0 ; pid: 125}
00:00:17.105 |S| HLE.OsThread.49 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:17.106 |S| HLE.OsThread.49 ServiceAcc CheckAvailability: Stubbed. 
00:00:17.107 |S| HLE.OsThread.49 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:17.251 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:17.295 |S| HLE.OsThread.49 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:17.455 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:17.455 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:17.456 |S| HLE.OsThread.7 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:17.456 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -2555301787871477760}
00:00:17.456 |S| HLE.OsThread.7 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -2555301581713047552}
00:00:19.253 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:19.465 |I| HLE.OsThread.15 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:20.420 |I| HLE.OsThread.15 AudioRenderer ReleaseSessionId: Unregistered output (0)
00:00:21.147 |I| HLE.OsThread.15 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:21.158 |I| HLE.OsThread.49 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)).
00:00:21.254 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Handheld'
00:00:21.301 |I| HLE.GuestThread.60 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Pokémon Sword, PID: 125
   0x000000000bf96d3c	sdk:0x17ed3c	
   0x000000000bf96e08	sdk:0x17ee08	
   0x000000000bf96eb0	sdk:0x17eeb0	nn::diag::detail::AbortImpl(nn::diag::MetaLogContext const&, nn::Result const*, char const*, ...)
   0x000000000beaf77c	sdk:0x9777c	
   0x00000000088aa0d0	main:0x3a60d0	
   0x000000000887fc3c	main:0x37bc3c	
   0x000000000887f9d8	main:0x37b9d8	
   0x00000000088811b8	main:0x37d1b8	
   0x000000000883a60c	main:0x33660c	
   0x0000000008838b44	main:0x334b44	
   0x000000000c141e88	sdk:0x329e88	
   0x000000000c146294	sdk:0x32e294	
   0x0000000000000000

00:00:21.303 |I| HLE.GuestThread.60 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000001079205c68 (SP:-0x01c8)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x000000000032802f
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000018
	X[11]:	0x0080000000000000
	X[12]:	0x0000000000000000
	X[13]:	0x000000000000000e
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000000bf981d0 (sdk:0x1801d0)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000ca1e0d0
	X[18]:	0x0000000000000000
	X[19]:	0x0000001079205c68 (SP:-0x01c8)
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x000000000c7e1f6d
	X[23]:	0x000000000c7e1f6d
	X[24]:	0x000000000c7e1f6d
	X[25]:	0x000000000c7e1f6d
	X[26]:	0x0000001079205c30 (SP:-0x0190)
	X[27]:	0x00000000000000ff
	X[28]:	0x000000000ab3ceb0
	FP:	0x0000001079205aa0 (SP)
	LR:	0x000000000bf981e8 (sdk:0x1801e8)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x0000001079205aa0 (SP)
	PC:	0x000000000c196ba4 (sdk:0x37eba4)	=> 

00:00:21.303 |W| HLE.GuestThread.48 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.51 KernelSvc : ArbitrateLock() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.53 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.55 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.56 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.57 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.303 |W| HLE.GuestThread.59 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.304 |I| HLE.OsThread.15 AudioRenderer ReleaseSessionId: Unregistered output (0)
00:00:21.343 |E| HLE.GuestThread.60 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264

### OS

11

### Ryujinx version

1.1.1239

### Game version

1.32

### CPU

13900k

### GPU

3090

### RAM

32gb

### List of applied mods

n/a

**Comment by MutantAura** [comment]
Please use the discord for general support: https://discord.gg/ryujinx
