### ISSUE TITLE
[Bug] Not working properly when a mod its activated

### ISSUE THREAD

**Issue by EmmanueldelaCruz** [Ryujinx/Ryujinx#6537]
### Description of the issue

I’m playing Xenoblade Chronicles 2. It freeze when a certain speed mod it’s activated. But, without it, the game turns really slow.

### Reproduction steps

The thing it’s that during a chain attack and in the main manu, it freezes. In the second case, the bug appears when switching to other parts of the menu. It freezes in the middle of the transition, but, the background music keeps as normal. When this happens, there is no other way to solve it than restarting the game.

### Log file

00:00:00.004 |I| Configuration LogValueChange: EnableFileLog set to: False
00:00:00.020 |I| Configuration LogValueChange: ResScale set to: -1
00:00:00.034 |I| Configuration LogValueChange: ResScaleCustom set to: 0.7
00:00:00.034 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.035 |I| Configuration LogValueChange: AspectRatio set to: Stretched
00:00:00.036 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.037 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.038 |I| Configuration LogValueChange: PreferredGpu set to: 0x8086_0x5917
00:00:00.039 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.040 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.041 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.055 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1239
00:00:00.064 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.064 |N| Application Print: CPU: Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz ; 4 logical
00:00:00.066 |N| Application Print: RAM: Total 3.9 GiB ; Available 0.6 GiB
00:00:00.067 |N| Application PrintSystemInfo: Logs Enabled: <None>
00:00:00.068 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.149 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.1
00:00:03.400 |N| GUI.RenderThread Gpu PrintGpuInformation: Intel Intel(R) UHD Graphics 620 (Vulkan v1.2.151, Driver v0.402.661)

### OS

Windows 11

### Ryujinx version

1.1.1239

### List of applied mods

Dynamically FPS for Xenoblade Chronicles 2.

**Comment by MutantAura** [comment]
Please use the discord for general support: https://discord.gg/ryujinx
