### ISSUE TITLE
[Bug] keyborad input text prompt doesn't work

### ISSUE THREAD

**Issue by DieGuiXvg** [Ryujinx/Ryujinx#6542]
### Description of the issue

when i try to name a character in a few games, the input text prompt don't move the cursor forward when i press a key on the keyborad.

### Reproduction steps

I record a video so you can see more easily

https://github.com/Ryujinx/Ryujinx/assets/147178387/aaf5384d-3488-4738-9677-14dbaf78173d

I try other games like diablo III and astral chain, but those games bring up another window to write the text there.

### Log file

[Ryujinx_1.1.1240_2024-03-20_21-37-40.log](https://github.com/Ryujinx/Ryujinx/files/14676279/Ryujinx_1.1.1240_2024-03-20_21-37-40.log)

### OS

Windows 10

### Ryujinx version

1.1.1240

### Game version

2.5.1

### CPU

Ryzen 7 5700g

### GPU

Radeon RX 6700 XT

### RAM

32 Ram

**Comment by KarenNscmnto** [comment]
Same issue with Monster Hunter Generations.

**Comment by Ukyolino** [comment]
Can confirm the same issue in Monster Hunter Generations (0100770008dd8000) ver. 1.4.0, Both in Vulcan and OpenGL mode.

Specs.
AMD Ryzen 5 5600x
GPU Nvidia RTX3060Ti

I went through them and the latest Ryujinx version where the issue doesn't appear is 1.1.1215

**Comment by MisterIgorGarcia** [comment]
Same here on monster hunter generations ultimate

**Comment by ccde177** [comment]
I encountered the same issue and found that after multiple presses of the <TAB> key, the type of selection changes, and the next input is appended at the beginning of the text.

https://github.com/user-attachments/assets/be8abbd0-0cec-4398-bdb1-44fc1f5128ad

**Comment by longfruit** [comment]
Seems like an issue with how Avalonia handles TextInput events, because Ryujinx with Gtk3 works fine.

![image](https://github.com/user-attachments/assets/0adf272b-0bdf-4895-adf0-429bc5fb2a09)

To anyone looking for a quick fix: Follow Ryujinx's build instructions then use `Ryujinx.Gtk3.exe`.

**Comment by MetrosexualGarbodor** [comment]
Fixed by #7030
