### ISSUE TITLE
[Bug] TotK seems to crash at random times during gameplay

### ISSUE THREAD

**Issue by Kuipo** [Ryujinx/Ryujinx#6543]
### Description of the issue

I've seen it crash now at random times (10mins of gameplay or up to over an hour of play before it crashes).  It doesn't seen to be triggered by anything specific that I can notice.

I was not getting logs that seemed to show the reason for the crash when using Vulkan. The app simply froze for 5 seconds or so and then closed.  I switched to OpenGL and it happened much sooner (within the first 5 mins of gameplay) while I was moving a fan with the hand ability.  I was moving it and walking with it and then same thing, 5 seconds or so of frozen screen then desktop.  The logs at least gave me an error in OpenGL though.  I will attach both, the later timestamp is the OpenGL one (ending in 45-15.log).

### Reproduction steps

Play TotK for a while? I don't have a good repro yet, I will try to keep an eye out if I find more info.

### Log file

[Ryujinx_1.1.1240_2024-03-20_18-56-12.log](https://github.com/Ryujinx/Ryujinx/files/14685305/Ryujinx_1.1.1240_2024-03-20_18-56-12.log)
[Ryujinx_1.1.1240_2024-03-20_20-45-01.log](https://github.com/Ryujinx/Ryujinx/files/14685316/Ryujinx_1.1.1240_2024-03-20_20-45-01.log)
[Ryujinx_1.1.1240_2024-03-20_21-45-15.log](https://github.com/Ryujinx/Ryujinx/files/14685318/Ryujinx_1.1.1240_2024-03-20_21-45-15.log)

### OS

Window 11 Pro 

### Ryujinx version

1.1.1240

### Game version

1.2.1

### CPU

Intel Core i9-9900K @3.60GHz

### GPU

NVIDIA 4070 Super driver version 551.86

### RAM

32GB

### List of applied mods

!!!TOTK Optimizer
00_MERGED_RESTBL
2x durability - no shield surf damage - v2
Aspect Ratio 21-9
dialogue_fixes_6
Linkle_TotK

**NOTE:** I had this issue as well when I was only using `TOTK Optimizer` and `Aspect Ratio 21-9`. The others are listed only because it's what I currently have loaded.

**Comment by Virtua64** [comment]
probably not a valid issue if you're using mods like Optimizer.  Sounds like an issue with that and not the emulator itself...

**Comment by Kuipo** [comment]
Not sure I agree with that statement. It’s not like optimizer is a an unknown mod and mods are supported by the emulator. There’s an error in the OpenGL log, it’s at least worth looking at. I’ll try again with no mods since OpenGL only lasted 10 mins anyway and I suspect it will still fail in short order.

**Comment by Kuipo** [comment]
If nothing else, it made a much faster repro disabling the mods.  

Repro Steps:
1. Launched Ryujinx and ensured all mods were turned off
2. Launched game (set to vulkan)
3. Waited for the main menu to load in TotK
4. Stopped emulation and it crashed when stopping the emulation with a very similar error
```
00:01:40.593 |E| GUI.WindowThread Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Dispose() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 932
```

[Ryujinx_1.1.1240_2024-03-20_22-50-59.log](https://github.com/Ryujinx/Ryujinx/files/14686564/Ryujinx_1.1.1240_2024-03-20_22-50-59.log)

It doesn't seem to be every time unfortunately.  I'll dig some more

**Comment by Kuipo** [comment]
Maybe @Virtua64 was correct, after completely removing TOTK Optimizer, changing the settings back to normal, clearing the shader cache and the PPTC I'm no longer seeing it after about an hour of play.  I'll try and narrow it down more if I do see it pop up and report it to TOTK Optimizer instead maybe.  Thanks, I'll close this issue.
