### ISSUE TITLE
[Regression] Ava UI huge FPS drops when playing in windows/fullscreen mode

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#6545]
### Description of the issue

On Avalonia on certain games the FPS tanks, happening on native and upscaled resolutions and makes games unplayable.
Entering fullscreen modes fixes the performance but changing to a 2nd monitor or pressing the windows key maxes the GPU and lowers the FPS in game. Windowed mode has bad FPS too.
Doesn't happen on GTK UI.

![image-6](https://github.com/Ryujinx/Ryujinx/assets/2002038/0c8bc31c-900b-42e9-b94d-6a7f455df85f)
![image-6](https://github.com/Ryujinx/Ryujinx/assets/2002038/52d23b76-93bf-4117-abdf-d52fb502686a)
![image-6](https://github.com/Ryujinx/Ryujinx/assets/2002038/9a50ad99-0825-4ec9-9c39-2df888f89f61)

### Reproduction steps

1. Launch game
2. Enter/leave fullscreen mode

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.1240

### Game version

v1.1.1

### CPU

Ryzen 3600

### GPU

NVIDIA RTX 3060 Ti

### RAM

16 GB

**Comment by MutantAura** [comment]
Unable to reproduce.

**Comment by GamerzHell9137** [comment]
Seems like its related to how the clocks of the GPU are operating.

With ``Power managment mode`` set to ``Normal`` and the ``Vulkan/OpenGL present method`` set to ``Auto`` or ``Prefer native`` the GPU is clocking at around 700 Mhz on Ryu.
These are the default Nvidia settings.

Setting the ``Power managment mode`` to ``Prefer maximum performance`` fixes the issue.

Another way to fix it is to have the ``Power managment mode`` to ``Normal`` but change the ``Vulkan/OpenGL present method`` to ``Prefer layered on DXGI Swapchain``
