### ISSUE TITLE
[Bug] Crash TOTK while playing

### ISSUE THREAD

**Issue by Steelfri** [Ryujinx/Ryujinx#6547]
### Description of the issue

Ryujinx crashe randomly when playing TOTK, I just started playing the game, Zelda was explaining something and the game just randomly crashed.  I relaunched the game finished the firsts cinematics and then I was about to leave the first island after jumping in the water and it crashed again.

### Reproduction steps

It's very random, it doesn't have a scheme.

### Log file

[Ryujinx_1.1.1231_2024-03-22_13-20-02.log](https://github.com/Ryujinx/Ryujinx/files/14726788/Ryujinx_1.1.1231_2024-03-22_13-20-02.log)
[Ryujinx_1.1.1231_2024-03-22_13-34-42.log](https://github.com/Ryujinx/Ryujinx/files/14726789/Ryujinx_1.1.1231_2024-03-22_13-34-42.log)

### OS

Windows 10.0.19045 (X64)

### Ryujinx version

1.1.1231

### Game version

1.2.1

### CPU

i5-12600KF

### GPU

RTX 3070 8gb

### RAM

32gb

### List of applied mods

60 fps mods

**Comment by ekuland** [comment]
"ErrorOutOfDeviceMemory"

3x scaling on a game with ASTC textures vs an 8GB vram card. You ran out and it crashed. Lower your resolution scaling.

**Comment by Steelfri** [comment]
Alright thanks
