### ISSUE TITLE
[Bug]Pokemon sword freezes when it starts boss fight

### ISSUE THREAD

**Issue by ZeeRef99** [Ryujinx/Ryujinx#6548]
### Description of the issue

as soon as the dialogue with the head coach ends and the pokemon come out of the pokeballs the game freezes crashing and closes, checking the save data I noticed that they are in an unknown language

### Reproduction steps

![image](https://github.com/Ryujinx/Ryujinx/assets/164574338/3b6a0380-4954-49a7-aa72-1bfd255f2f55)

### Log file

[Ryujinx_1.1.1192_2024-03-22_23-10-55.log](https://github.com/Ryujinx/Ryujinx/files/14729012/Ryujinx_1.1.1192_2024-03-22_23-10-55.log)
[Ryujinx_1.1.1242_2024-03-22_23-11-47.log](https://github.com/Ryujinx/Ryujinx/files/14729013/Ryujinx_1.1.1242_2024-03-22_23-11-47.log)
[Ryujinx_1.1.1242_2024-03-22_23-34-18.log](https://github.com/Ryujinx/Ryujinx/files/14729014/Ryujinx_1.1.1242_2024-03-22_23-34-18.log)

### OS

windows 11

### Ryujinx version

1.1.1242

### RAM

8 GB

**Comment by ekuland** [comment]
`ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`
Your game dump is bad. Redump it. [Join the discord](https://discord.gg/ryujinx) for further support.
