### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by alnioj** [Ryujinx/Ryujinx#6553]
### Description of the issue

Everytime I open tinfoil on ryujinx it crashes 

### Reproduction steps

Opening tinfoil

### Log file

00:00:00.116 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.125 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.127 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.128 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.129 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.130 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.131 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xE0303EF
00:00:00.132 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.133 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.133 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.136 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.146 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.147 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.147 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.148 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.148 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.148 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.149 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.149 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.150 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.152 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.152 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.154 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.154 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.154 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.154 |I| Configuration LogValueChange: UseHypervisor set to: False
00:00:00.161 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.163 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1242
00:00:00.173 |N| Application Print: Operating System: macOS 14.3.1 (23D60) (Arm64)
00:00:00.173 |N| Application Print: CPU: VirtualApple @ 2.50GHz ; 8 logical
00:00:00.176 |N| Application Print: RAM: Total 16 GiB ; Available 8.4 GiB
00:00:00.182 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.183 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:03.088 |E| .NET TP Worker 2024-03-23 13:29:05.888 Ryujinx[1573:20465] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
00:00:00.183 |I| Gpu : Backend Threading (Auto): True
00:00:00.590 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.1
00:00:00.590 |I| Application LoadGuestApplication: Loading as homebrew.
00:00:00.599 |W| Loader GetNpdm: NPDM file not found, using default values!
00:00:00.841 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: False).
00:00:00.846 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.851 |I| ModLoader LoadCheats: Build ids found for application 0000000000000000:
    ADEC7590B96F9A00492805805F33436E4405644F30290E6CF2BEE47C47591FC3
00:00:00.924 |I| Loader Start: Application Loaded: Tinfoil Installer v17.0.1 [010000000000100d] [64-bit]
00:00:00.979 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.009 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:01.042 |E| .NET TP Worker [mvk-info] MoltenVK version 1.2.0, supporting Vulkan version 1.2.231.
00:00:01.043 |E| .NET TP Worker 	The following 83 Vulkan extensions are supported:
00:00:01.043 |E| .NET TP Worker 		VK_KHR_16bit_storage v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_8bit_storage v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_bind_memory2 v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_buffer_device_address v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_create_renderpass2 v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_dedicated_allocation v3
00:00:01.043 |E| .NET TP Worker 		VK_KHR_depth_stencil_resolve v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_descriptor_update_template v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_device_group v4
00:00:01.043 |E| .NET TP Worker 		VK_KHR_device_group_creation v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_driver_properties v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_dynamic_rendering v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_external_fence v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_external_fence_capabilities v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_external_memory v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_external_memory_capabilities v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_external_semaphore v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_external_semaphore_capabilities v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_fragment_shader_barycentric v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_get_memory_requirements2 v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_get_physical_device_properties2 v2
00:00:01.043 |E| .NET TP Worker 		VK_KHR_get_surface_capabilities2 v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_imageless_framebuffer v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_image_format_list v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_maintenance1 v2
00:00:01.043 |E| .NET TP Worker 		VK_KHR_maintenance2 v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_maintenance3 v1
00:00:01.043 |E| .NET TP Worker 		VK_KHR_multiview v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_portability_subset v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_push_descriptor v2
00:00:01.045 |E| .NET TP Worker 		VK_KHR_relaxed_block_layout v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_sampler_mirror_clamp_to_edge v3
00:00:01.045 |E| .NET TP Worker 		VK_KHR_sampler_ycbcr_conversion v14
00:00:01.045 |E| .NET TP Worker 		VK_KHR_separate_depth_stencil_layouts v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_shader_draw_parameters v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_shader_float_controls v4
00:00:01.045 |E| .NET TP Worker 		VK_KHR_shader_float16_int8 v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_shader_subgroup_extended_types v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_spirv_1_4 v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_storage_buffer_storage_class v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_surface v25
00:00:01.045 |E| .NET TP Worker 		VK_KHR_swapchain v70
00:00:01.045 |E| .NET TP Worker 		VK_KHR_swapchain_mutable_format v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_timeline_semaphore v2
00:00:01.045 |E| .NET TP Worker 		VK_KHR_uniform_buffer_standard_layout v1
00:00:01.045 |E| .NET TP Worker 		VK_KHR_variable_pointers v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_buffer_device_address v2
00:00:01.045 |E| .NET TP Worker 		VK_EXT_debug_marker v4
00:00:01.045 |E| .NET TP Worker 		VK_EXT_debug_report v10
00:00:01.045 |E| .NET TP Worker 		VK_EXT_debug_utils v2
00:00:01.045 |E| .NET TP Worker 		VK_EXT_descriptor_indexing v2
00:00:01.045 |E| .NET TP Worker 		VK_EXT_fragment_shader_interlock v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_hdr_metadata v2
00:00:01.045 |E| .NET TP Worker 		VK_EXT_host_query_reset v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_image_robustness v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_inline_uniform_block v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_memory_budget v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_metal_objects v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_metal_surface v1
00:00:01.045 |E| .NET TP Worker 		VK_EXT_post_depth_coverage v1
00:00:01.046 |E| .NET TP Worker 		VK_EXT_private_data v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_robustness2 v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_sample_locations v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_scalar_block_layout v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_separate_stencil_usage v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_shader_stencil_export v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_shader_viewport_index_layer v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_subgroup_size_control v2
00:00:01.047 |E| .NET TP Worker 		VK_EXT_swapchain_colorspace v4
00:00:01.047 |E| .NET TP Worker 		VK_EXT_texel_buffer_alignment v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_texture_compression_astc_hdr v1
00:00:01.047 |E| .NET TP Worker 		VK_EXT_vertex_attribute_divisor v3
00:00:01.047 |E| .NET TP Worker 		VK_AMD_gpu_shader_half_float v2
00:00:01.047 |E| .NET TP Worker 		VK_AMD_negative_viewport_height v1
00:00:01.047 |E| .NET TP Worker 		VK_AMD_shader_image_load_store_lod v1
00:00:01.047 |E| .NET TP Worker 		VK_AMD_shader_trinary_minmax v1
00:00:01.047 |E| .NET TP Worker 		VK_IMG_format_pvrtc v1
00:00:01.047 |E| .NET TP Worker 		VK_INTEL_shader_integer_functions2 v1
00:00:01.047 |E| .NET TP Worker 		VK_GOOGLE_display_timing v1
00:00:01.047 |E| .NET TP Worker 		VK_MVK_macos_surface v3
00:00:01.047 |E| .NET TP Worker 		VK_MVK_moltenvk v36
00:00:01.047 |E| .NET TP Worker 		VK_NV_fragment_shader_barycentric v1
00:00:01.047 |E| .NET TP Worker 		VK_NV_glsl_shader v1
00:00:01.047 |E| .NET TP Worker [mvk-info] GPU device:
00:00:01.047 |E| .NET TP Worker 		model: Apple M2
00:00:01.047 |E| .NET TP Worker 		type: Integrated
00:00:01.047 |E| .NET TP Worker 		vendorID: 0x106b
00:00:01.047 |E| .NET TP Worker 		deviceID: 0xe0303ef
00:00:01.047 |E| .NET TP Worker 		pipelineCacheUUID: 260BAD42-0E03-03EF-0000-000100000000
00:00:01.047 |E| .NET TP Worker 	supports the following Metal Versions, GPU's and Feature Sets:
00:00:01.047 |E| .NET TP Worker 		Metal Shading Language 2.4
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 7
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 6
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 5
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 4
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 3
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 2
00:00:01.047 |E| .NET TP Worker 		GPU Family Apple 1
00:00:01.047 |E| .NET TP Worker 		GPU Family Mac 2
00:00:01.047 |E| .NET TP Worker 		GPU Family Mac 1
00:00:01.047 |E| .NET TP Worker 		GPU Family Common 3
00:00:01.047 |E| .NET TP Worker 		GPU Family Common 2
00:00:01.047 |E| .NET TP Worker 		GPU Family Common 1
00:00:01.047 |E| .NET TP Worker 		macOS GPU Family 2 v1
00:00:01.047 |E| .NET TP Worker 		macOS GPU Family 1 v4
00:00:01.047 |E| .NET TP Worker 		macOS GPU Family 1 v3
00:00:01.047 |E| .NET TP Worker 		macOS GPU Family 1 v2
00:00:01.047 |E| .NET TP Worker 		macOS GPU Family 1 v1
00:00:01.047 |E| .NET TP Worker [mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 3 Vulkan extensions enabled:
00:00:01.047 |E| .NET TP Worker 		VK_KHR_surface v25
00:00:01.047 |E| .NET TP Worker 		VK_EXT_debug_utils v2
00:00:01.047 |E| .NET TP Worker 		VK_EXT_metal_surface v1
00:00:01.091 |E| .NET TP Worker [mvk-info] Vulkan semaphores using Metal implicit guarantees within a single queue.
00:00:01.092 |E| .NET TP Worker [mvk-info] Created VkDevice to run on GPU Apple M2 with the following 8 Vulkan extensions enabled:
00:00:01.092 |E| .NET TP Worker 		VK_KHR_portability_subset v1
00:00:01.092 |E| .NET TP Worker 		VK_KHR_push_descriptor v2
00:00:01.092 |E| .NET TP Worker 		VK_KHR_shader_float16_int8 v1
00:00:01.092 |E| .NET TP Worker 		VK_KHR_swapchain v70
00:00:01.092 |E| .NET TP Worker 		VK_EXT_descriptor_indexing v2
00:00:01.092 |E| .NET TP Worker 		VK_EXT_fragment_shader_interlock v1
00:00:01.092 |E| .NET TP Worker 		VK_EXT_robustness2 v1
00:00:01.092 |E| .NET TP Worker 		VK_EXT_shader_stencil_export v1
00:00:01.202 |E| .NET TP Worker [mvk-info] Created 3 swapchain images with initial size (2560, 1380) and contents scale 2.0 for screen Built-in Retina Display.
00:00:01.205 |N| GUI.RenderThread Gpu PrintGpuInformation: Apple Apple M2 (Vulkan v1.2.231, Driver v0.2.2008)
00:00:02.360 |S| HLE.OsThread.49 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.381 |S| HLE.OsThread.49 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.385 |S| HLE.OsThread.49 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.387 |S| HLE.OsThread.49 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.398 |S| HLE.OsThread.49 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:02.399 |S| HLE.OsThread.49 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:03.963 |E| HLE.OsThread.6 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IDeviceOperator: 100

Guest Stack Trace:
Process: Service, PID: 83

Buffer Information:
	ReceiveBuff:
	Position: 0x00000020c0000c40 Size: 0x0000000000000010 Flags: 0

Raw Request Data:
00000000   01 00 18 00 05 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  64 00 00 00 00 00 00 00   SFCI····d·······
00000020   10 00 00 00 00 00 00 00  34 00 00 00               ········4···    

   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/IpcService.cs:line 159
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Mac m2

### Ryujinx version

1.1.1242

### RAM

16

**Comment by hajosattila** [comment]
current version:

[alucard@desktop ~]$ Ryujinx
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle

The previous version worked perfectly

[alucard@desktop ~]$ inxi -Fz
System:
  Kernel: 6.8.1-AMD-znver3 arch: x86_64 bits: 64
  Desktop: Sway v: 1.9 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: ASRock model: X300M-STX serial: <superuser required>
    UEFI: American Megatrends LLC. v: P1.80F date: 05/09/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 5700G with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 4 MiB
  Speed (MHz): avg: 886 min/max: 400/4673 cores: 1: 400 2: 400 3: 400 4: 400
    5: 400 6: 400 7: 400 8: 2994 9: 400 10: 400 11: 400 12: 400 13: 2993 14: 400
    15: 400 16: 2993
Graphics:
  Device-1: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Display: wayland server: Xwayland v: 23.2.4 compositor: Sway v: 1.9
    driver: gpu: amdgpu resolution: 2560x1440~60Hz
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel
  Device-2: XMOS iFi (by AMR) HD USB Audio driver: snd-usb-audio type: USB
  API: ALSA v: k6.8.1-AMD-znver3 status: kernel-api
  Server-1: PipeWire v: 1.0.4 status: active
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp1s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth Radio driver: btusb type: USB
  Report: btmgmt ID: hci0 state: up address: <filter> bt-v: 5.1
Drives:
  Local Storage: total: 465.76 GiB used: 63.9 GiB (13.7%)
  ID-1: /dev/sda vendor: Samsung model: SSD 870 EVO 500GB size: 465.76 GiB
Partition:
  ID-1: / size: 456.89 GiB used: 63.77 GiB (14.0%) fs: ext4 dev: /dev/sda2
  ID-2: /boot size: 511 MiB used: 135.2 MiB (26.5%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: zram size: 4 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 35.5 C mobo: N/A gpu: amdgpu temp: 29.0 C
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 16 GiB note: est. available: 13.54 GiB used: 3.84 GiB (28.4%)
  Processes: 299 Uptime: 1h 56m Shell: Zsh inxi: 3.3.33

**Comment by MutantAura** [comment]
No support will be provided for homebrew that facilitates piracy.
