### ISSUE TITLE
[Bug] Crash on Arch

### ISSUE THREAD

**Issue by hajosattila** [Ryujinx/Ryujinx#6555]
### Description of the issue

https://aur.archlinux.org/packages/ryujinx-bin

[alucard@desktop ~]$ Ryujinx
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle

The previous version worked perfectly

- Arch Linux
- 6.8.1-AMD-znver3
- Sway 1.9
- Mesa 24.0.3
- dotnet-runtime 8.0.3.sdk103

### Reproduction steps

[alucard@desktop ~]$ Ryujinx

### Log file

Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle

### OS

Arch Linux

### Ryujinx version

1.1.1242-1

### CPU

Ryzen 5700G

### RAM

16GB DDR4

**Comment by ilbuonmarcio** [comment]
Are you using the AUR package 'ryujinx-git'?

If so, I'm trying to work on it and provide a solution (I'm the initial publisher for this AUR package)

**Comment by hajosattila** [comment]
> Are you using the AUR package 'ryujinx-git'?
> 
> If so, I'm trying to work on it and provide a solution (I'm the initial publisher for this AUR package)

https://aur.archlinux.org/packages/ryujinx-bin

**Comment by TSRBerry** [comment]
I already informed the maintainer of ryujinx-git on how to fix this issue.

**Comment by ilbuonmarcio** [comment]
> I already informed the maintainer of ryujinx-git on how to fix this issue.

Can you provide me with the message, I'm not finding it

**Comment by TSRBerry** [comment]
This was a message on Discord to dnmodder: https://discord.com/channels/410208534861447168/1045857724338028594/1220903171040215161

> could you add the `!debug` option to the ryujinx-git package? Some people seem to run into issues when this option is enabled in their `makepkg.conf`
I'm replying to the message which contains the error message I'm talking about, but you can also read from there if you are interested in the troubleshooting that we did.

He already replied and said he'd handle it today.

**Comment by ilbuonmarcio** [comment]
Then I'll let him patch it directly, no help needed here from me if that's the case 👍🏼

**Comment by ilbuonmarcio** [comment]
On `ryujinx-git` side is now working and published with this additional option, let's wait for the -bin version

**Comment by willianholtz** [comment]
I'm also having the same problem, I've already tried some modifications to the file (aur) and nothing.. I even posted something on the aur about the subject. I know that the Maintainer is trying to fix it, but here just to give notice of the breakage!

**Comment by hajosattila** [comment]
The only version that doesn't work for me is 1.1.1242. The latest 1.1.1243 and 1.1.1244 run perfectly.

**Comment by TSRBerry** [comment]
The issue here as already been solved, we are just waiting for the maintainers of the AUR package for ryujinx-bin to add the fix as well.

**Comment by TSRBerry** [comment]
Since we aren't maintaining `ryujinx-bin` someone probably needs to contact the maintainers and link them to this issue.
It probably doesn't really make sense to keep this issue open (and it probably shouldn't have been opened here).
