### ISSUE TITLE
Ryujinx crashes on launching The Legend of Zelda: TOTK [Bug]

### ISSUE THREAD

**Issue by AmeyAvhad** [Ryujinx/Ryujinx#6559]
### Description of the issue

So, I downloaded the latest version of ryujinx emulater added the firmware version. 16.1.0 and added the keys for same.
Then I have the game XCI file, whenever I start the game The Legend of Zelda : TOTK the emulator just crashes.
The emulator seems to be working for other games like Pokemon Violet,etc.

I have updated both my graphics drivers to latest version.

### Reproduction steps

Launching the game crashes the emulator.

### Log file

[Ryujinx_1.1.1244_2024-03-25_01-30-20.log](https://github.com/Ryujinx/Ryujinx/files/14736649/Ryujinx_1.1.1244_2024-03-25_01-30-20.log)

### OS

Windows 10

### Ryujinx version

1.1.1244

### Game version

1.21

### CPU

Ryzen 5 - 4600H

### GPU

NVIDIA GTX 1060Ti

### RAM

8GB

**Comment by ekuland** [comment]
`ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`
Your game and/or file is corrupted. Redump it. Please join [the discord](https://discord.gg/ryujinx) for support.

**Comment by AmeyAvhad** [comment]
The game file is not corrupted as it is running on another emulator perfectly.

**Comment by ekuland** [comment]
That error can _**only**_ mean corrupted file. Join the discord for any future support.
