### ISSUE TITLE
[Bug] Crashes while playing TotK

### ISSUE THREAD

**Issue by Helium745** [Ryujinx/Ryujinx#6580]
### Description of the issue

As the title says. It takes place near the first shrine(Ukouh Shrine).
This is a screenshot at the time of the crash.
![image](https://github.com/Ryujinx/Ryujinx/assets/42940650/19e9515d-7d14-4131-8c8f-ab336e085650)

### Reproduction steps

Play normally until near the Ukouh Shrine.

### Log file

[Ryujinx_1.1.1248_2024-03-30_16-50-56.log](https://github.com/Ryujinx/Ryujinx/files/14811134/Ryujinx_1.1.1248_2024-03-30_16-50-56.log)

### OS

Windows 11

### Ryujinx version

1.1.1248

### Game version

Ver.1.2.1

### CPU

Intel Core i5-12400F

### GPU

Nvidia GeForce GTX 1650 Super

### RAM

16GB

### List of applied mods

[TOTK Optimizer 2.0.5](https://github.com/MaxLastBreath/TOTK-mods)

### Additional context?

I disabled the optimizer mod, but it didn't fix it.
Removing the update 1.2.1 fixed it.

**Comment by piplup55** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
