### ISSUE TITLE
[Bug] Balatro crashing on load

### ISSUE THREAD

**Issue by Decscots** [Ryujinx/Ryujinx#6582]
### Description of the issue

Invalid memory access at virtual address 0x0000000000000000 when trying to open balatro on 1.0.0 and on 1.0.3, dont know if another version works.

### Reproduction steps

Just attempt to load balatro

### Log file

[Ryujinx_1.1.1248_2024-03-30_22-51-20.log](https://github.com/Ryujinx/Ryujinx/files/14813791/Ryujinx_1.1.1248_2024-03-30_22-51-20.log)

### OS

Windows 11 22631

### Ryujinx version

1.1.1248

### Game version

1.0.0

### CPU

i7-13700KF

### GPU

NVIDIA RTX 3070

### RAM

32GB

**Comment by Luke44565** [comment]
this seems to be a regression.
Balatro works fine on version 1.1.1086 (cdc8fed64fc8e51fe626b0a369902932db0ec49c)
but stops working on version 1.1.1087 (dcf10561b996cdba111c5a3c3fe128781ab44021)

for now I would recommend downloading the last working version if you want to play: https://github.com/Ryujinx/Ryujinx/releases/tag/1.1.1086
