### ISSUE TITLE
"Easy come Easy golf" unplayable after 1.1.637

### ISSUE THREAD

**Issue by Funkyspectrum** [Ryujinx/Ryujinx#6587]
### Description of the issue

Hello, there's an issue with Easy Come Easy Golf after emulator version 1.1.637, in that it's not playable once the game starts and you're about to take a shot. For some reason, it now places the player and spectators in the ground so that it's never possible to take a shot/start a game (a warning is displayed saying "it's impossible to take a shot from here" or words to that effect). 

Strangely this issue is NOT present in 1.1.637 and before, so something must have happened to upset the applecart in the interim. However, somewhat obviously, that's quite an old build so it'd be great to get it working on the latest build/s from here on, as they run smoother and there are more graphical options. 

Aside from that, the game runs well on the old emulator, in that it seems to be 100% playable BUT it'd be much preferable to be able to run it on the latest builds, as stated. Hopefully this can be resolved, thanks for all your hard work!

EDIT: NON WORKING in 1.1.1248

![image](https://github.com/Ryujinx/Ryujinx/assets/165818596/91525ba3-5992-4c74-9546-07a1e8814dac)

![golfwrong](https://github.com/Ryujinx/Ryujinx/assets/165818596/aa5f8a61-5b89-4585-9fb1-2432943bad8a)

### Reproduction steps

The issue can be produced by simply starting any game on the latest version of the emulator. Any mode that puts you on the course will have this issue. Occasionally you can see the top of a head sticking out of the ground but usually there's just nothing and no visible audience/player. The error message appears as soon as you're about to take a shot, and cannot be removed as the player character isn't lined up to take the shot. 

### Log file

[Ryujinx_1.1.1248_2024-04-02_18-11-56.log](https://github.com/Ryujinx/Ryujinx/files/14840261/Ryujinx_1.1.1248_2024-04-02_18-11-56.log)

### OS

Windows 10

### Ryujinx version

1.1.1248

### Game version

1.8.0 (same issue on all versions, though)

### CPU

i7 12700

### GPU

nvidia 3080

### RAM

64gb

### List of applied mods

none

### Additional context?

I thought I had dumped the rom somehow incorrectly, but on searching the internet I found others talking about the issue, which led me to go back and use the older emulator version - where it does work 100%. It works fine on my Switch and I'd never seen this error before, so that made me check online after I'd dumped it a second time and it still wasn't working. Again, thanks in advance for taking the time to check this out.

**Comment by GamerzHell9137** [comment]
With the information that it ran on an older build doesnt help anyone. Find the version that's causing the issue.

**Comment by Funkyspectrum** [comment]
> With the information that it ran on an older build doesnt help anyone. Find the version that's causing the issue.

I've clearly stated that it doesn't work on subsequent builds after 1.1.637, as stated, and that it doesn't work on the current build (1.1.1248) as stated.

**Comment by GamerzHell9137** [comment]
> > With the information that it ran on an older build doesnt help anyone. Find the version that's causing the issue.
> 
> I've clearly stated that it doesn't work on subsequent builds after 1.1.637, as stated, and that it doesn't work on the current build (1.1.1248) as stated.

So why is it fine on 1.1.1000 then? 
![image](https://github.com/Ryujinx/Ryujinx/assets/2002038/0f36d797-c278-42c6-bccc-99935f7eeae7)

**Comment by GamerzHell9137** [comment]
1024 is what's breaking it

https://github.com/Ryujinx/Ryujinx/pull/5719
