### ISSUE TITLE
[Bug] MacOS build instructions out of date (or missing)

### ISSUE THREAD

**Issue by prakity** [Ryujinx/Ryujinx#6594]
### Description of the issue

create_macos_release.sh  does not exist

Then type ./distribution/macos/create_macos_release.sh ./ ./distribution/macos/temp ./distribution/macos/output ./distribution/macos/entitlements.xml 1.1.1 0

### Reproduction steps

could not find instructions except on web
https://www.reddit.com/r/macgaming/comments/116fewn/guide_how_to_build_the_latest_version_of_ryujinx/?rdt=41930

### Log file

no log available

### OS

Macos Sonoma

### Ryujinx version

3.2.10

### Game version

n/a

### CPU

Mac m2 (Mac Studio)

### GPU

Mac m2 (Apple)

### RAM

64 GB

### List of applied mods

none

### Additional context?

n/a

**Comment by gdkchan** [comment]
`create_macos_release` was renamed to `create_macos_build` on #4837, then it was renamed to `create_macos_build_ava` on #5272. There is an additional argument where you need to pass `Release`, and another for extra args that I think you can leave empty. So for example `./distribution/macos/create_macos_build_ava.sh ./ ./distribution/macos/temp ./distribution/macos/output ./distribution/macos/entitlements.xml 1.1.1 0 Release` should work in theory.

**Comment by prakity** [comment]
Better 

Needed to 0 0 at the end.

Could someone please add to the documentation the complete instructions including dependent software that is needed.

Many Thanks

Philip

**Comment by IsaacMarovitz** [comment]
`create_macos_build` is only necessary if you want to create a complete `.app`. If you want to just build an executable, `dotnet build` works fine.

**Comment by prakity** [comment]
Works !IPaw PoweredOn 5 Apr 2024, at 16:35, Isaac Marovitz ***@***.***> wrote:﻿
create_macos_build is only necessary if you want to create a complete .app. If you want to just build an executable, dotnet build works fine.

**Comment by prakity** [comment]
Sorry. You’re missing the documentation for others to build. IPaw PoweredOn 5 Apr 2024, at 17:12, Isaac Marovitz ***@***.***> wrote:﻿
Closed #6594 as completed.
