### ISSUE TITLE
Most games crash right when I open them

### ISSUE THREAD

**Issue by camolad** [Ryujinx/Ryujinx#6595]
### Description of the issue

Hello, I installed Ryujinx the other day and I tried to play Mario Kart, which worked. I installed Legend of Zelda games, and those crash instantly when I try to open them. 

### Reproduction steps

I don't know how to be honest

### Log file

[Ryujinx_1.1.1250_2024-04-04_16-00-22.log](https://github.com/Ryujinx/Ryujinx/files/14876678/Ryujinx_1.1.1250_2024-04-04_16-00-22.log)
[Ryujinx_1.1.1250_2024-04-04_15-59-13.log](https://github.com/Ryujinx/Ryujinx/files/14876679/Ryujinx_1.1.1250_2024-04-04_15-59-13.log)
[Ryujinx_1.1.1250_2024-04-04_15-17-02.log](https://github.com/Ryujinx/Ryujinx/files/14876680/Ryujinx_1.1.1250_2024-04-04_15-17-02.log)

### OS

Windows 11

### Ryujinx version

1.1.1250

### Game version

1.2.1 and 1.0.0

### CPU

i5-12400

### GPU

GTX 980 Ti

### RAM

32GB DDR4, 3200 MHZ

### List of applied mods

None

### Additional context?

Just installed the games and it wouldn't even let me launch :(

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
