### ISSUE TITLE
[Bug/Compatibility help] Wolfenstein Young Blood Doesn't boot.

### ISSUE THREAD

**Issue by ShadenXa** [Ryujinx/Ryujinx#6596]
### Description of the issue

I just wanted to try and help the overall compatibility of the emulator to boot more games overall in the future. This game doesnt boot at all. If you try ryujinx will just crash.

### Reproduction steps

Try to boot the game

### Log file

[Ryujinx_1.1.1250_2024-04-04_15-30-42.log](https://github.com/Ryujinx/Ryujinx/files/14877823/Ryujinx_1.1.1250_2024-04-04_15-30-42.log)

### OS

Windows 10

### Ryujinx version

1.1.1.250

### Game version

No updates.

### CPU

CPU Intel(R) Xeon(R) CPU E5-1650 0 

### GPU

RTX  GeForce 2060

### RAM

32

**Comment by gdkchan** [comment]
Compatibility reports should go on https://github.com/Ryujinx/Ryujinx-Games-List/ (https://github.com/Ryujinx/Ryujinx-Games-List/issues/2557 for this game in specific).

**Comment by ShadenXa** [comment]
Alright my bad
