### ISSUE TITLE
I cant Add any more games for some reason

### ISSUE THREAD

**Issue by buddy34792** [Ryujinx/Ryujinx#6597]
### Description of the issue

every time i try to add  a new game it always pops up with this error.
![Screenshot 2024-04-04 184318](https://github.com/Ryujinx/Ryujinx/assets/118638954/7ae9f516-481f-417e-a4de-1ca6d21c7585)
![Screenshot 2024-04-04 184350](https://github.com/Ryujinx/Ryujinx/assets/118638954/80b3e1bd-a3e1-4fc6-820e-1eece5894401)

### Reproduction steps

i download game 
i extract game
i drag game into file directory
it dosnt work/load

### Log file

00:00:00.038 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.044 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.044 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.045 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.046 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.046 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.047 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x731F
00:00:00.048 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.048 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.049 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.051 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.062 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.062 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.062 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.062 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.063 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.063 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.064 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.064 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.064 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.064 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.068 |I| Configuration LogValueChange: MultiplayerMode set to: LdnRyu
00:00:00.068 |I| Configuration LogValueChange: DisableP2p set to: False
00:00:00.069 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.0-ldn3.1.3
00:00:00.074 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.074 |N| Application Print: CPU: AMD Ryzen 5 5500 ; 12 logical
00:00:00.075 |N| Application Print: RAM: Total 16233 MiB ; Available 6490 MiB
00:00:00.078 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.079 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.760 |W| .NET ThreadPool Worker Application LoadApplications: The header key is incorrect or missing and therefore the NCA header content type check has failed. Errored File: F:\Switch games\Super Mario RPG [0100BC0018138000][v0][US](nsw2u.com).xci

### OS

windows 11 pro

### Ryujinx version

17.0.0

**Comment by MetrosexualGarbodor** [comment]
We do not support piracy.
