### ISSUE TITLE
[Bug] No supported Vulkan surface found!

### ISSUE THREAD

**Issue by Grant12311** [Ryujinx/Ryujinx#6599]
### Description of the issue

When I try to launch a game, Ryujinx crashes. The terminal shows "No supported Vulkan surface found!" among other errors.

### Reproduction steps

Launch a game. It Ryujinx crashes.

### Log file

[Ryujinx_1.1.1250_2024-04-05_03-19-53.log](https://github.com/Ryujinx/Ryujinx/files/14881483/Ryujinx_1.1.1250_2024-04-05_03-19-53.log)

### OS

Ubuntu 23.10

### Ryujinx version

1.1.1250 from Flathub

### CPU

AMD Ryzen 7 5700U

### GPU

iGPU

### RAM

16GB

**Comment by MutantAura** [comment]
This usually indicates a driver problem. 
Fully reinstall your GPU drivers and use our discord for further support: https://discord.gg/ryujinx
