### ISSUE TITLE
MacBook links Joycons but prompts configuration issues when entering the game

### ISSUE THREAD

**Issue by Realybig** [Ryujinx/Ryujinx#6606]
### Description of the issue

MacBook links Joycons but prompts configuration issues when entering the game，What to do with it

<img width="515" alt="001" src="https://github.com/Ryujinx/Ryujinx/assets/10878451/e91b5102-24c4-41fb-b0b1-d83260bc1989">
<img width="1100" alt="002" src="https://github.com/Ryujinx/Ryujinx/assets/10878451/147d1b14-e19b-4b81-a076-dc6312f0c1d9">
<img width="715" alt="003" src="https://github.com/Ryujinx/Ryujinx/assets/10878451/04b69edd-8c18-49c3-a835-402ff6c25fc6">

### Reproduction steps

Just for normal use

### Log file

no file

### OS

MacOS

### Ryujinx version

1.1.1251

### CPU

M2pro

### RAM

16

**Comment by MutantAura** [comment]
The valid controllers are the _Joycon Pair_ or the _Pro Controller_. 
Your screenshot shows your configured controller is just the left joycon.

Please use our discord for future use queries: https://discord.gg/ryujinx
