### ISSUE TITLE
[Bug] Joystick not working in the dashboard menu.

### ISSUE THREAD

**Issue by IHsojib71** [Ryujinx/Ryujinx#6614]
### Description of the issue

I dont know its intentionally done or not joystick not working on dashboard where all my game titles are available for playing. Problem is joystick is working perfectly also the gyro working but in the dashboard I have to use mouse to open a game. 

### Reproduction steps

1. Connect joystick/gamepad 
2. Open Ryuzinx
3. Try to open any game from joystick

### Log file

[Ryujinx_1.1.1262_2024-04-07_12-59-59.log](https://github.com/Ryujinx/Ryujinx/files/14896062/Ryujinx_1.1.1262_2024-04-07_12-59-59.log)

### OS

Windows 11

### Ryujinx version

1.1.1262

**Comment by piplup55** [comment]
this is not a bug, we don't support navigating the ui with controllers
