### ISSUE TITLE
[Bug] SMB Wonder Crash

### ISSUE THREAD

**Issue by krocodyle** [Ryujinx/Ryujinx#6616]
### Description of the issue

The game crashes upon the arrival of Prince Florian

### Reproduction steps

Walking past the very first cutscene and waiting for the arrival of Prince Florian

https://github.com/Ryujinx/Ryujinx/assets/166301419/f6feafe3-314c-46e7-a57e-f026d9dd762b

### Log file

[Ryujinx_1.1.1262_2024-04-07_14-57-18.log](https://github.com/Ryujinx/Ryujinx/files/14897125/Ryujinx_1.1.1262_2024-04-07_14-57-18.log)

### OS

Windows 10

### Ryujinx version

1.1.1262

### Game version

1.0.0

### CPU

i7-6800K

### GPU

ASUS ARES3

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
AMD GPU users on Windows should always be using Vulkan, not OpenGL. In the future, please use Discord for support.
