### ISSUE TITLE
[Feature Request] Trim the Ava file from the release files

### ISSUE THREAD

**Issue by wzsx150** [Ryujinx/Ryujinx#6625]
### Overview

The compiled release version contains duplicate identical files, and it is recommended to streamline by deleting these duplicates. 

For instance, within the file ryujinx-1.1.1268-win_x64.zip, Ryujinx.exe and Ryujinx.Ava.exe are the same. Additionally, test-ava-ryujinx-1.1.1268-win_x64.zip and ryujinx-1.1.1268-win_x64.zip are also identical. 

This issue has been present for a while; it is suggested to consolidate and streamline. 
Thank you.

### Smaller details

Content as above.

### Nature of request

Streamline the released files.

### Why would this feature be useful?

Reduce resource consumption, save storage space, and conserve download bandwidth.

**Comment by IsaacMarovitz** [comment]
This is intentional, not an issue. It is necessary to make sure users on older versions of Ava can still update without issues. They will be consolidated in a few months.
