### ISSUE TITLE
Repeated crashes since updating to 1.1.1268

### ISSUE THREAD

**Issue by JonAugusto** [Ryujinx/Ryujinx#6628]
### Description of the issue

Playing BOTW.. Game crashes about 4-5 minutes after loading save.

### Reproduction steps

Save file load, start to walk around,  kill a couple of enemies and then hard crash. 

### Log file

[Ryujinx_1.1.1268_2024-04-08_10-25-50.log](https://github.com/Ryujinx/Ryujinx/files/14908871/Ryujinx_1.1.1268_2024-04-08_10-25-50.log)
[Ryujinx_1.1.1268_2024-04-08_12-44-42.log](https://github.com/Ryujinx/Ryujinx/files/14908872/Ryujinx_1.1.1268_2024-04-08_12-44-42.log)
[Ryujinx_1.1.1268_2024-04-08_13-16-43.log](https://github.com/Ryujinx/Ryujinx/files/14908873/Ryujinx_1.1.1268_2024-04-08_13-16-43.log)

### OS

MacOS Sonoma 14.5

### Ryujinx version

1.1.1268

### Game version

BOTW 1.5.0

### CPU

M1 Max

### GPU

M1 Max

### RAM

64 GB

### List of applied mods

None,  just DLC

**Comment by gdkchan** [comment]
@jhorv Can this be related to the audio change? There is an error in the log that I don't remember ever seeing before.
```
AudioRenderer CheckConsumedSize: Consumed output size mismatch (got 8416 expected 1984)
```

**Comment by V380-Ori** [comment]
Having the exact same issue on macOS 14.4.1, after PR #6604 merge while playing BOTW, crash happens at random times, can happen after 1 minute, or an hour.

**Comment by jhorv** [comment]
> Having the exact same issue on macOS 14.4.1, after PR #6604 merge while playing BOTW, crash happens at random times, can happen after 1 minute, or an hour.

@V380-Ori what CPU in your machine?

**Comment by V380-Ori** [comment]
> > Having the exact same issue on macOS 14.4.1, after PR #6604 merge while playing BOTW, crash happens at random times, can happen after 1 minute, or an hour.
> 
> @V380-Ori what CPU in your machine?

M1 (8 CPU & 7 GPU cores) with 8 GiB of RAM. If you need more information please let me know.

**Comment by fanitriastowo** [comment]
I also experience this bug. M1 (8CPU & 8 GPU) with 8 GB RAM
