### ISSUE TITLE
[Bug]resident evil 1 crash after cinematic or opening a door

### ISSUE THREAD

**Issue by Batuace** [Ryujinx/Ryujinx#6639]
### Description of the issue

resident evil 1 crash after a cinematic, or crossing a door, tried different settings, always the same. ryujinx closes.
latest version, resident evil nsp version 1.0 no mods.

### Reproduction steps

run the game
start a new game
cinematic ends CTD
------
using a save:
run game
load the save (game runs fine)
activate door
door animation ends CTD

### Log file

[
[Ryujinx_1.1.1272_2024-04-09_21-05-13.log](https://github.com/Ryujinx/Ryujinx/files/14925758/Ryujinx_1.1.1272_2024-04-09_21-05-13.log)
](url)

### OS

windows 10

### Ryujinx version

1.1.1272

### Game version

1.0.0

### CPU

ryzen 5 1600x

### GPU

nvidia rtx 2060

### RAM

16 gb

### List of applied mods

none

### Additional context?

yuzu ran the game fine, so i ussed a save made in that to pass the fist cinematic
it seems to have something to do with audio, one time after enabling graphics backend multitreading i got pass the door animation but after that i got no audio... but that worked just that one time... i know my cpu is not the best but i can run lots more demanding games and this is the only one that crashes for me, before passing a door game runs fine.
tried different settings but the result is always the same.

**Comment by gdkchan** [comment]
That might be a regression, you could try version 1.1.1264 to confirm that.

**Comment by Batuace** [comment]
yep, 1264 worked fine.
still gave red messages but can pass cinematics and doors:
00:02:13.731 |E| HLE.OsThread.15 AudioRenderer Update: Unmap of memory pool (address: 0x20a8af1000, size 0x5a000) failed!
00:02:13.737 |S| HLE.OsThread.23 ServiceMm SetAndWait: Stubbed. {requestId: 2 ; clockRateMin: 0 ; clockRateMax: -1}
00:02:13.737 |S| HLE.OsThread.23 ServiceMm Finalize: Stubbed. {requestId: 2}
00:02:22.006 |E| HLE.OsThread.15 AudioRenderer Update: Unmap of memory pool (address: 0x20a8af1000, size 0x5a000) failed!
00:02:22.006 |E| HLE.OsThread.15 AudioRenderer Update: Unmap of memory pool (address: 0x20a8bb1000, size 0x5a000) failed!
00:02:24.903 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 50602 bytes, profiled functions: 15354).
00:02:34.345 |E| HLE.OsThread.15 AudioRenderer Update: Unmap of memory pool (address: 0x20a8eb1000, size 0x5a000) failed!
00:02:37.571 |E| HLE.OsThread.15 AudioRenderer Update: Unmap of memory pool (address: 0x20a8df1000, size 0x5a000) failed!
00:02:54.903 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 50615 bytes, profiled functions: 15358).
