### ISSUE TITLE
[Bug] Crash when changing controller config

### ISSUE THREAD

**Issue by Luke44565** [Ryujinx/Ryujinx#6647]
### Description of the issue

When switching from an input device without motion (ie a keyboard) to one with motion while a game is running causes a crash because of a null reference exception. This happens on both Ava and Gtk.

### Reproduction steps

1. Open a game
2. Make sure a controller is set to something that doesn't support motion (i.e. a keyboard)
3. Switch that controller to a device that supports motion (for Gtk, "Enable Motion Controls" must be set)

### Log file

[Ryujinx_1.1.1276_2024-04-10_18-51-01.log](https://github.com/Ryujinx/Ryujinx/files/14938972/Ryujinx_1.1.1276_2024-04-10_18-51-01.log)

### OS

Linux (Arch) and Windows 11

### Ryujinx version

1.1.1276

### Additional context?

[Discussion Here](https://github.com/Ryujinx/Ryujinx/pull/6644)

**Comment by gdkchan** [comment]
Fixed by #6654.
