### ISSUE TITLE
Zelda TOTK destroyed by ryujinx version 1.1.1276

### ISSUE THREAD

**Issue by shackpool** [Ryujinx/Ryujinx#6648]
### Description of the issue

after updating ryujinx to the latest version from 1.1.1276, totk was destroyed, 0 rupees, 0 arrows, 0 meals, sword and shields not present inventory, couldnt move link at all, game completely unplayable, version 1.1.1275 was perfectly fine and had none of these new bugs now shown below: 
![Screenshot (41)](https://github.com/Ryujinx/Ryujinx/assets/166669268/4875c62f-e5d5-4618-8fdd-6e70e2ae691d)
![Screenshot (42)](https://github.com/Ryujinx/Ryujinx/assets/166669268/a09cdb0a-97f8-407c-a4f8-a8dfd29fb9ee)
![Screenshot (44)](https://github.com/Ryujinx/Ryujinx/assets/166669268/39718fcb-7c86-4b33-92f9-60eb488c14d2)
![Screenshot (45)](https://github.com/Ryujinx/Ryujinx/assets/166669268/e8e8b15a-f584-4553-83d3-c0b50526cf52)
![Screenshot (47)](https://github.com/Ryujinx/Ryujinx/assets/166669268/4f57a1b3-889c-48a1-b63f-699370c634b5)
![Screenshot (48)](https://github.com/Ryujinx/Ryujinx/assets/166669268/f8342788-c0a7-49a6-b60d-d5001a307312)
![Screenshot (43)](https://github.com/Ryujinx/Ryujinx/assets/166669268/d961f308-e220-4854-9453-d10198e7d1e6)
![Screenshot (46)](https://github.com/Ryujinx/Ryujinx/assets/166669268/9cc13d1e-7984-4c8f-8052-cb0306835c30)

the stranger thing is that the ryujinx console acts as if nothing is wrong

### Reproduction steps

well im no coding expect, but if i were to guess, look at what was changed in 1.1.1276 compared to 1.1.1275 and see if anything added may be bad for the game

### Log file

[Ryujinx_1.1.1276_2024-04-11_01-07-17.log](https://github.com/Ryujinx/Ryujinx/files/14939128/Ryujinx_1.1.1276_2024-04-11_01-07-17.log)

### OS

Windows 11

### Ryujinx version

1.1.1276

### Game version

1.2.1

### CPU

i7-13700F

### GPU

NVIDIA Geforce RTX 4060 Ti

### RAM

16GB

### List of applied mods

TOTK Optimizer
PlayStation UI

### Additional context?

before asking, yes, i disabled my mods, yet the issue remained present

**Comment by gdkchan** [comment]
Your log shows a lot of cheats being enabled. The only change on version 1.1.1276 is related to cheats.

**Comment by shackpool** [comment]
why have they patched the cheats? there wasnt even anything wrong with them before

**Comment by gdkchan** [comment]
There was a cheat failing to load silently, this change fixes that.

**Comment by shackpool** [comment]
strange, fixing that cheat broke loads of others

**Comment by shackpool** [comment]
just done a little bit of testing, this update may have broken more cheats then expected, i tried using only 3 of them, the game broke with even just 1 of them on

**Comment by gdkchan** [comment]
Yea, I found that the change is actually wrong, it was just a misguided attempt to try fixing an invalid cheat. I will revert it, thanks for reporting.
