### ISSUE TITLE
[Bug]I can not found GPU

### ISSUE THREAD

**Issue by KevinYangKai** [Ryujinx/Ryujinx#6656]
### Description of the issue

why can i not found gpu
<img width="821" alt="微信图片_20240413022204" src="https://github.com/Ryujinx/Ryujinx/assets/38915548/46748978-e1a0-4c61-8a41-456d9ce35ee0">

### Reproduction steps

I have do nothing.Just open the Ryujinx application

### Log file

<img width="863" alt="微信图片_20240413022411" src="https://github.com/Ryujinx/Ryujinx/assets/38915548/c15fdc42-19d4-426e-be69-e934e98e17c6">

### OS

Windows 11

### Ryujinx version

1.1.1279

### Game version

none

### CPU

i9-14900

### GPU

NVIDIA RTX 4090

### RAM

64GB

**Comment by RedPana** [comment]
Join the [Discord](https://discord.com/invite/ryujinx) for help

**Comment by piplup55** [comment]
your driver is likely broken, please use [ddu](https://www.guru3d.com/download/display-driver-uninstaller-download/) and reinstall it in future join the [discord](https://discord.gg/ryujinx) for support
