### ISSUE TITLE
[Bug] Ryujinx fails to build on linux

### ISSUE THREAD

**Issue by Shoegzer** [Ryujinx/Ryujinx#6658]
### Description of the issue

Ryujinx fails to build.  From the build log, this seems to be due to the following:

`CSC : warning CS9057: The analyzer assembly '/home/testing/Desktop/Ryujinx/build/Ryujinx.Horizon.Generators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/testing/Desktop/Ryujinx/src/Ryujinx.Horizon/Ryujinx.Horizon.csproj]
`

However, the installed version of dotnet (which is presumed to include the aforementioned compiler) meets the 8.0.100 version requirements as noted in [global.json](https://github.com/Ryujinx/Ryujinx/blob/master/global.json):
```
$ dotnet --version
8.0.103
```

### Reproduction steps

Follow the build instructions as listed in [README.md](https://github.com/Ryujinx/Ryujinx/blob/master/README.md)

### Log file

[build.log](https://github.com/Ryujinx/Ryujinx/files/14964699/build.log)

### OS

Linux Mint 21.3 / kernel 6.5

### Ryujinx version

e916662b0f17b93d8987d481784cd45073335990

### Game version

N/A

### CPU

Intel i7-10870H

### GPU

Nvidia GTX 3070

### RAM

32GB

**Comment by gdkchan** [comment]
You need a newer version of .NET SDK.

**Comment by Shoegzer** [comment]
Thanks, I guess that means global.json is outdated. What is the minimum SDK version now?

**Comment by gdkchan** [comment]
I believe it's 8.0.203.

**Comment by Shoegzer** [comment]
Thanks again, I updated to 8.0.204 and that worked, so I'll close this.
