### ISSUE TITLE
I can't play fashion dreamer online [Bug]

### ISSUE THREAD

**Issue by valelisa36** [Ryujinx/Ryujinx#6661]
### Description of the issue

I can't arrive with my wind3 connection wifi  to play Fashion Dreamer online with ryujinx what can I do thanks in advance

### Reproduction steps

no

### Log file

no

### OS

Windows 11

### Ryujinx version

1.1.1.2.7.9

### Game version

Fashion Dreamer  version 140

### CPU

Vulkan 

### GPU

Intel(R)

### RAM

500GB

**Comment by ekuland** [comment]
The game only has single system functions and those that would require Nintendo Switch Online. The emulator does not and will not connect to NSO for any reason. Those functions will not be available.

![image](https://github.com/Ryujinx/Ryujinx/assets/4542300/d16f6ba1-6db6-45bd-a449-83cca377c7d6)

**Comment by Maverynthia** [comment]
Fashion Dreamer DOES NOT require NSO. That's one of it's selling points.

**Comment by ekuland** [comment]
I do not believe there's a difference in whether it requires a subscription or not. It still would connect to through NSO.
