### ISSUE TITLE
ARCropolis Panicked [Bug]

### ISSUE THREAD

**Issue by Rockyfan75000** [Ryujinx/Ryujinx#6663]
### Description of the issue

I was starting this game called "Super Smash Bros. Ultimate" with a lot of mods and somehow ARCropolis panicked. could it be the stage itself? 
![Error Number_ 69 (Details) 4_13_2024 7_07_57 PM](https://github.com/Ryujinx/Ryujinx/assets/153872220/826e40d0-101b-48c0-a242-a24837b16d5c)

### Reproduction steps

Somehow, just like the game "Among Us". you must somehow find the mod that causes this error.

### Log file

ARCropolis has panicked at 'assertion failed: self.is_char_boundary(n)', L:\.cargo\skyline\toolchain\skyline\lib\rustlib\src\rust\libary\alloc\src\string.rs:1916:29

### OS

Windows 11

### Ryujinx version

1.1.1279

### Game version

13.0.2

### CPU

i7-10750H

### GPU

Intel(R) Core(TM)

### RAM

32GB

### List of applied mods

Toon Link Emoji Pack

### Additional context?

Can you guys get any tips on how in the world is this thing happening?

**Comment by TSRBerry** [comment]
If you use these mods on the switch do they work fine?

**Comment by Rockyfan75000** [comment]
> If you use these mods on the switch do they work fine?

While any mods work without a hitch, some mods display an error. for example: the Toon Link Emoji Pack can display the error on it.

**Comment by TSRBerry** [comment]
So the same error appears on the switch?

**Comment by Rockyfan75000** [comment]
Yes, I can't give the tutorial of it there, but some is very useful. you might wanna find it.

**Comment by TSRBerry** [comment]
Well then this is not a Ryujinx issue. You should create an issue at the repository of the mod, so they can work on it.

**Comment by Rockyfan75000** [comment]
I also wanted to test that on the real switch, but I'm too lazy to do that though. :(
