### ISSUE TITLE
[Bug][Linux] Controller detected only when connected via USB+Bluetooth

### ISSUE THREAD

**Issue by voidanix** [Ryujinx/Ryujinx#6666]
# Description of the issue

Ryujinx does not display the Xbox Series X controller connected via USB or Bluetooth in `Settings -> Input -> Input Device`. The only way to render it visible is by connecting it via USB and Bluetooth at the same time.

The controller works just fine on the citrus fruit emulator when using either connection method.

The issue is reproducible on Flatpak, the distributed binary and the emulator built from source.

The Series X controller uses xpadneo when on Bluetooth. When via USB, there is a simple USB-A <-> USB-C cable connected to the laptop (cannot recall what driver is being called, but it is on mainline).

The machine is running GNOME 46 (Wayland) on Fedora Rawhide. This behaviour is also observed under X11.

# Reproduction steps

Connect an Xbox Series X on Linux either via USB or Bluetooth. To connect both of them at the same time, do the following:

* Connect the controller via Bluetooth so it can be autoconnected the next time.
* Turn off Bluetooth on the computer.
* Connect the controller via USB and, immediately after, enable Bluetooth on the computer such that the controller also connects through it (otherwise, the controller's BT will be turned off).
* Notice only one entry in the Input tab and that the controller works how it is supposed to.

# OS

Fedora Rawhide

# Ryujinx version

1.1.1279

P.S. Are the issue templates broken? They do not show up when using GH CLI.

**Comment by TSRBerry** [comment]
This appears to be a system specific problem.
I can't reproduce this on my machine and can play fine using either Bluetooth or USB.

You could try other SDL2 programs and if you aren't able to reproduce this issue there then come back and reopen this issue. I'd take a more in depth look in that case.

**Comment by voidanix** [comment]
Could you give me more details about your configuration (and controller)? As mentioned, it works just fine on the citrus emulator (and other programs as well).

I also tried https://github.com/mikyll/SDL2-Controller-Tester and it works just fine there. Ryujinx is the only program behaving this way.

**Comment by voidanix** [comment]
Looks like I cannot reopen the issue. OTOH, I am extremely confident this is a Ryujinx issue and is unrelated to my system.

**Comment by TSRBerry** [comment]
Not sure what details you are looking for but I am using xone and xpadneo dkms for bluetooth and usb support.

Do you have them both installed?
I'm really sure this is related to your system configuration, since I can play just fine here and other Linux users also haven't reported any issues with Xbox controllers specifically.

**Comment by piplup55** [comment]
after testing this myself using a elite series 2 controller i can confirm both usb and bluetooth works, one thing to note is that over bluetooth the controller will show as a `xbox 360 controller` and you may or may not have a dupe entry but everything works how it should
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/17ed391a-e61f-4ae0-ba4a-db6c95ff279b)

**Comment by voidanix** [comment]
> Not sure what details you are looking for

DE, kernel version and controller (but I assume it to be the Series X/S controller).

Knowing the kernel version would have been important. There was an upstream bug in 6.8.0 (which my machine was running) that is fixed on the recent stable kernel. Everything works fine now, but it was not a configuration error from my side.

> Do you have them both installed?

As mentioned before, xpadneo worked just fine for Bluetooth and USB also worked just fine, even without xone. Installing xone did not change Ryujinx's behavior.

> I'm really sure this is related to your system configuration, since I can play just fine here and other Linux users also haven't reported any issues with Xbox controllers specifically.

See above. This was a kernel issue upstream (I can bisect this too if you want me to).

> after testing this myself using a elite series 2 controller i can confirm both usb and bluetooth works

I am fairly confident you were not running 6.8.0 or some -rc kernel: would that be correct?
