### ISSUE TITLE
[Bug] Ryujinx stuttering on Linux with Nvidia.

### ISSUE THREAD

**Issue by PixelGames987** [Ryujinx/Ryujinx#6678]
### Description of the issue

Hello.
Recently I've installed Ryujinx on Fedora Linux. I dumped my games to the emulator, but I noticed that the game was stuttering a lot. I know Nvidia drivers work bad on Linux, but I don't have issues like that when playing games from steam or wine. The screen just goes back a few frames from time to time. I'm using Ryujinx with Vulcan, because OpenGL crashes on Linux with Nvidia. It works fine on Windows 11.

(Xenoblade Chronicles 1, 2 and 3)

### Reproduction steps

1. Open Ryujinx on my PC
2. Start XC 1, 2 or 3
3. Get all the stuttering

### Log file

[log.txt](https://github.com/Ryujinx/Ryujinx/files/15026872/log.txt)

### OS

Fedora Linux 39

### Ryujinx version

I believe it was this: 1.1.1280

### Game version

Doesn't matter

### CPU

Intel Core i5-9400F

### GPU

Nvidia GTX 1660Ti

### RAM

16Gb

**Comment by TSRBerry** [comment]
I can't reproduce this issue on my device.

**Comment by prd-ryu** [comment]
with Linux 6.5.0-28-generic x86_64 kernel and proprietary drivers NVIDIA 545   fixed the stuttering issue on some games.

**Comment by PixelGames987** [comment]
I'm stupid, turning off VSync resolved the issue. 😅
