### ISSUE TITLE
[Bug] mk8dx, opening controller connection applet on char. select scrren will keep on getting message

### ISSUE THREAD

**Issue by CatMow** [Ryujinx/Ryujinx#6688]
### Description of the issue

mk8dx. on character select screen, pressing plus/minus will bring ryujinx popup "game request exactly x player...". pressing ok will open the popup again. cant get rid, the game is frozen.
Only tested on 1 player

### Reproduction steps

open mk8dx
go 1 player (may have bug on multi, idk)
on char. select screen, press plus/minus
gg, game is bricked until restart

### Log file

too lazy to upload.
in the console, it just says "created applet controller" or smth.
after pressing ok on the dialouge, nothing happens in console, just another popup

### OS

win10 x64

### Ryujinx version

latest

### Game version

3.0.1

### CPU

not need

### GPU

not need

### RAM

not need

### List of applied mods

not need

**Comment by piplup55** [comment]
this isn't a bug, you have no controllers setup or to many setup
