### ISSUE TITLE
[Bug] Ryujinx 1.1.1289 quit unexpectedly.

### ISSUE THREAD

**Issue by C0DDER** [Ryujinx/Ryujinx#6696]
### Description of the issue

Ryujinx crashing after shader compolation

### Reproduction steps

install Ryujinx 1.1.1289 and try to run The Legend of Zelda: Breath of the Wild or any other game

### Log file

[Ryujinx_1.1.1289_2024-04-21_19-45-17.log](https://github.com/Ryujinx/Ryujinx/files/15052779/Ryujinx_1.1.1289_2024-04-21_19-45-17.log)
[Ryujinx_1.1.1289_2024-04-21_19-50-47.log](https://github.com/Ryujinx/Ryujinx/files/15052780/Ryujinx_1.1.1289_2024-04-21_19-50-47.log)
[Ryujinx_1.1.1289_2024-04-21_19-54-55.log](https://github.com/Ryujinx/Ryujinx/files/15052781/Ryujinx_1.1.1289_2024-04-21_19-54-55.log)

### OS

Sonoma 14.4.1 (23E224)

### Ryujinx version

1.1.1289

### Game version

1.1.1289

### CPU

M1 max

### RAM

32 GB

**Comment by jhorv** [comment]
should be fixed by #6695
