### ISSUE TITLE
Implementation of a graphics API

### ISSUE THREAD

**Issue by Amul2004** [Ryujinx/Ryujinx#670]
In the Ryujinx emulator, **OpenAL** has been implemented which results in good FPS and good audio. But I think if we add an Graphics API (like Direct3D) will lead to good graphics too.
Right now, Ryujinx experiences graphics crashes but sound and FPS are good still.....
Just like the **Yuzu emulator**(which uses opengl 4.5) can run some 3D games; you can also implement a graphics API which will prevent **crashing of graphics**...
It's a just a suggestion....

**Comment by emmauss** [comment]
Thanks for the suggestion. We are still working on the 3D graphic engine, and as it is still incomplete, adding another rendering backend won't help much. It will make it more difficult to maintain, test, and it is going to restrict compatibility to only Windows systems, Opengl 3.3 ( the minimum we target) is good enough for 3D rendering, though it has some issues, but that can be easily resolved by using Opengl versions, or making fallbacks.

**Comment by Amul2004** [comment]
Well thanks for informing me....
You can also use Vulkan 1.0 for rendering 3D graphics!
I think OpenGL 3.3 will not be enough because the real Nintendo Switch uses some OpenGL 4.5 extensions....
And why will it be restricted only to windows???
You should extend the support to Linux also; Linux is a lot faster than Windows....you might be knowing this!!

**Comment by jduncanator** [comment]
@Amul2004 The emulator is fully cross platform and already runs very well under Linux. Have you tried the emulator? Take a look at the README as well, it may answer some of your questions.

**Comment by zephyren25** [comment]
> You can also use Vulkan 1.0 for rendering 3D graphics!

What's wrong with OpenGL

> I think OpenGL 3.3 will not be enough-

Like emmaus said, we can always use workarounds / upgrade OpenGL

> And why will it be restricted only to windows???

DirectX is only supported by windows

> You should extend the support to Linux also

Linux is already supported

**Comment by gdkchan** [comment]
Technically it requires OpenGL 4.2. But it works with 4.0 too as long your GPU/driver supports the required extensions (iirc ARB_separate_shader_objects and ARB_shading_language_packing for games using half float on the shader).

About adding support for another graphics API, first Direct3D has the problem that it would only work on Windows, and Vulkan is not going to be compatible with older GPUs/drivers, so I think OpenGL is still the most compatible choice. I don't disagree that supporting a more modern graphics API like Vulkan would be interesting, but I'm afraid we currently don't have anyone with interest and time to work on that.

**Comment by Amul2004** [comment]
@gdkchan I myself use a low-end laptop(7 years old) with a intel gpu (graphics hd 4000)...
It supports Vulkan 1.0 only on linux....
That's  why I was saying that  implementing vulkan will be a grewt step towards accurae graphics emulation

**Comment by emmauss** [comment]
can you move to the discord, this is not a good place to discuss this
