### ISSUE TITLE
[Bug] game crash before game even opens

### ISSUE THREAD

**Issue by PinkLizard3559** [Ryujinx/Ryujinx#6701]
### Description of the issue

I've been trying to play pokemon legends arceus on my PC but when I try to run it it gives me an error code

### Reproduction steps

trying to load from file

### Log file

[Ryujinx_1.1.1290_2024-04-21_18-09-40.log](https://github.com/Ryujinx/Ryujinx/files/15055230/Ryujinx_1.1.1290_2024-04-21_18-09-40.log)

### OS

windows 10

### Ryujinx version

1.1.1290

### Game version

1.1.0

### CPU

i5-6500

### GPU

NVIDIA GeForce GTX 1660 SUPER

### RAM

32GB

**Comment by piplup55** [comment]
your game file is corrupted redump it from your switch, in future use the [discord](https://discord.gg/ryujinx) for support
