### ISSUE TITLE
[Bug] Input Profile can't be loaded or saved on Mac M3

### ISSUE THREAD

**Issue by lazywhite** [Ryujinx/Ryujinx#6702]
### Description of the issue

<img width="449" alt="SCR-20240422-pgbr" src="https://github.com/Ryujinx/Ryujinx/assets/17612898/7413084f-fbe3-4e1c-9bef-8fb336541991">  

none these three buttons worked. can't create multiple keyboard mapping profile for different games

### Reproduction steps

no

### Log file

[Ryujinx_1.1.1289_2024-04-22_17-25-00.log](https://github.com/Ryujinx/Ryujinx/files/15060632/Ryujinx_1.1.1289_2024-04-22_17-25-00.log)

### OS

mac 14.4.1 

### Ryujinx version

1.1.1289

**Comment by RomainAn** [comment]
Hello I don't think it's a bug
Just you can't override the default profile.
Change the name of the profile to something else and press the button save.

![image](https://github.com/Ryujinx/Ryujinx/assets/7524521/ada03694-dd0a-4402-9092-238a0c9aab0a)

Working fine on Mac M2

**Comment by lazywhite** [comment]
> Hello
> 
> I don't think it's a bug Just you can't override the default profile. Change the name of the profile to something else and press the button save.
> 
> ![image](https://private-user-images.githubusercontent.com/7524521/324772324-ada03694-dd0a-4402-9092-238a0c9aab0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjQ1MDcsIm5iZiI6MTcxMzg2NDIwNywicGF0aCI6Ii83NTI0NTIxLzMyNDc3MjMyNC1hZGEwMzY5NC1kZDBhLTQ0MDItOTA5Mi0yMzhhMGM5YWFiMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMDkyMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgzODU2M2E0NWQ0MTg5YzdkODdkMmFjOTA3Y2QxMDI2NzYxMWU1ZmM4OGMwNzNhMjEzYWViNzQ1MDI3ODk3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NHyj7rQtRJQ3tFk1q3PqZwG04f5YNW7yRqRuyVhNLdU)
> 
> Working fine on Mac M2

wow, profile name could be clicked to edit, I got it.
