### ISSUE TITLE
Ryujinx crashes while trying to boot Tears of the Kingdom

### ISSUE THREAD

**Issue by ShoutForPi** [Ryujinx/Ryujinx#6710]
### Description of the issue

The application crashes while booting Tears of the Kingdom. Every other game works fine.

### Reproduction steps

Run Tears of the Kingdom

### Log file

00:00:00.100 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.111 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.112 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.113 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.114 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.115 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.116 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.117 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.119 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.119 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.121 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.130 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.130 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.130 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.130 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.132 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.133 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.134 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.134 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.134 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.135 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.139 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.186 |N| Application Load: Configuration file updated to version 50
00:00:00.192 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1291
00:00:00.198 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.198 |N| Application Print: CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz ; 8 logical
00:00:00.201 |N| Application Print: RAM: Total 31.9 GiB ; Available 22.6 GiB
00:00:00.205 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.206 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:38.754 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x13FA
00:00:38.869 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'C:\Users\[redacted]\Documents\Nathan\Games\Kirby and the Forgotten Land [01004D300C5AE000][v0].nsp' Error: LibHac.Common.HorizonResultException: ResultFsOutOfRange (2002-3005)
   at LibHac.Common.ThrowHelper.ThrowResult(Result result)
   at LibHac.Tools.FsSystem.NcaUtils.NcaHeader.DecryptHeader(KeySet keySet, IStorage storage)
   at LibHac.Tools.FsSystem.NcaUtils.Nca..ctor(KeySet keySet, IStorage storage)
   at Ryujinx.UI.App.Common.ApplicationLibrary.GetGameData(VirtualFileSystem fileSystem, IFileSystem pfs, Int32 programIndex) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 829
   at Ryujinx.UI.App.Common.ApplicationLibrary.GetControlFsAndTitleId(IFileSystem pfs, IFileSystem& controlFs, String& titleId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 513
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 255
00:00:00.123 |I| Gpu : Backend Threading (Auto): True
00:00:00.550 |N| Application LoadGuestApplication: Using Firmware Version: 18.0.0
00:00:00.550 |I| Application LoadGuestApplication: Loading as XCI.
00:00:00.588 |I| ModLoader QueryContentsDir: Searching mods for Application 0100F2C0115B6000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.590 |I| ModLoader QueryContentsDir: Searching mods for Application 0100F2C0115B6000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.595 |I| Loader Load: Loading rtld...
00:00:00.604 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.604 |I| Loader Load: Loading main...
00:00:01.540 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:01.540 |I| Loader Load: Loading subsdk0...
00:00:01.620 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:01.620 |I| Loader Load: Loading sdk...
00:00:01.786 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:01.926 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.941 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.943 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.991 |I| Loader LoadNsos: Loading image 2 at 0x000000000cc2f000...
00:00:01.996 |I| Loader LoadNsos: Loading image 3 at 0x000000000d2d8000...
00:00:02.007 |I| ModLoader LoadCheats: Build ids found for application 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    9B4E43650501A4D4489B4BBFDB740F26AF3CF850000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:02.012 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.092 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.2.1 [0100f2c0115b6000] [64-bit]
00:00:02.571 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:02.589 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:02.840 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA Corporation Quadro M3000M/PCIe/SSE2 (4.6.0 NVIDIA 516.69)
00:00:02.889 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:02.901 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:04.133 |S| HLE.OsThread.51 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:04.417 |S| HLE.OsThread.51 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:04.432 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:04.443 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:04.643 |S| HLE.OsThread.51 ServicePctl Initialize: Stubbed. 
00:00:12.304 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:12.306 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:12.309 |S| HLE.OsThread.51 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:12.310 |S| HLE.OsThread.51 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:12.311 |S| HLE.OsThread.51 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:13.110 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed. 
00:00:13.170 |I| HLE.OsThread.51 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:13.174 |I| HLE.OsThread.51 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:13.428 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed. 
00:00:13.527 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:13.655 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:13.659 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:13.660 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:13.668 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:13.671 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:13.673 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:13.676 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:13.690 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:13.962 |S| HLE.OsThread.51 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:13.986 |S| HLE.OsThread.51 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:13.989 |S| HLE.OsThread.51 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:14.088 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:14.098 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:14.101 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:19.111 |S| HLE.OsThread.8 ServiceNv ZbcSetTable: Stubbed. 
00:00:19.111 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:20.161 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windows 10 Pro

### Ryujinx version

1.1.1291

### Game version

1.2.1

### CPU

Core i7 vPro

### GPU

NVIDIA Quadro M3000M

### RAM

32.0 GB

### List of applied mods

None

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
