### ISSUE TITLE
[Feature Request] Prevent Ryujinx window on Linux to sleep after inactivity

### ISSUE THREAD

**Issue by mdsmendes94** [Ryujinx/Ryujinx#6722]
### Overview

Prevent Ryujinx window on Linux to sleep after inactivity

### Smaller details

Prevent Ryujinx window on Linux to sleep after inactivity

### Nature of request

Prevent Ryujinx window on Linux to sleep after inactivity

### Why would this feature be useful?

The user can play with his game pad in peace

**Comment by piplup55** [comment]
this should already happen when using gamemode and the `ryujinx.sh` file
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/b11a37fa-7192-498b-a437-c7035a23f5f5)

**Comment by TSRBerry** [comment]
Execute Ryujinx using `Ryujinx.sh` and gamemode will stop your system from entering sleep mode.

**Comment by mdsmendes94** [comment]
> Execute Ryujinx using `Ryujinx.sh` and gamemode will stop your system from entering sleep mode.

It would be a good idea to make gamemode a dependency or something like that because it's not mentioned anywhere else that using Ryujinx on Linux without gamemode doesn't count as activity in the system thus making the go into sleep mode even if someone is using a gamepad
