### ISSUE TITLE
[Bug] Mouse Cursor dismissed immediately by not holding click / clicking

### ISSUE THREAD

**Issue by Ryan2603** [Ryujinx/Ryujinx#6723]
### Description of the issue

as title, i think it should stay mapping as a connected pointer

### Reproduction steps

https://github.com/Ryujinx/Ryujinx/assets/10262883/ef3d608d-0819-4f1d-a637-a346c168eee8

### Log file

nope

### OS

Win11

### Ryujinx version

1.1.1291

**Comment by Exhigh** [comment]
Have you tried using direct mouse input ?

**Comment by Ryan2603** [comment]
> > By the way, Mario Galaxy being unplayable by a webapplet created in millsecond cause FIFO 100%.
> 
> does it stay at 100% forever, if not that's fine.

In-game does 99.50% ~99.99 forever (stage/homeland), hope some one investigate.

**Comment by Exhigh** [comment]
I would suggest opening another issue, for this issue particularly then.

**Comment by Ryan2603** [comment]
nevermind, in this situation, its isn't a bug thing occur at all, i will closing this report for now.
