### ISSUE TITLE
[Bug] Crashing when loading Super Mario Odyssey

### ISSUE THREAD

**Issue by MInecrafterPictures** [Ryujinx/Ryujinx#6724]
### Description of the issue

I tried running Super Mario Odyssey after a fresh update and it crashes on both Vulkan and OpenGL. And What's interesting is that, for some reason, Snipperclips works just fine. The logs are from when I tested Mario Odyssey.

### Reproduction steps

Run Super Mario Odyssey rom

### Log file

[Ryujinx_1.1.1291_2024-04-26_17-30-19.log](https://github.com/Ryujinx/Ryujinx/files/15132205/Ryujinx_1.1.1291_2024-04-26_17-30-19.log)

### OS

Windows 10

### Ryujinx version

1.1.1291

### Game version

1.3.0

### CPU

12th Gen Intel Core i5-12400F

### GPU

ASUS Radeon RX 4600

### RAM

16GB

### Additional context?

Until the most recent update, the game worked fine

**Comment by ekuland** [comment]
> 00:28:07.820 |E| HLE.GuestThread.50 Application : Unhandled exception caught: System.SystemException: The paging file is too small for this operation to complete.

> 00:00:00.089 |N| Application Print: RAM: Total 15.8 GiB ; Available 4.9 GiB

This is an error on your system probably due to running out of ram. Please join the discord for any further support.

**Comment by MInecrafterPictures** [comment]
Apparently, Unity games work no problem. So Snipperclips and Nickelodeon All-Star Brawl Ultimate Edition boot just fine.
