### ISSUE TITLE
[Bug] Crash on launching Hyrule Warriors: Age of Calamity

### ISSUE THREAD

**Issue by AkazaRenn** [Ryujinx/Ryujinx#6735]
### Description of the issue

Can see the loading screen of Ryujinx (Loading [Game Name]), if no controller is connected it was able to complain about that, but afterwards Ryujinx just closes itself.

### Reproduction steps

Launch the game, should be able to observe that instantly 

### Log file

[File_Apr 27, 2024 18_49_59_.txt](https://github.com/Ryujinx/Ryujinx/files/15140224/File_Apr.27.2024.18_49_59_.txt)

### OS

Windows 11 IoT Enterprise LTSC 24H2 26100.268

### Ryujinx version

1.1.1291 Ava

### Game version

1.0.0

### CPU

AMD Ryzen 7 7800X3D

### GPU

NVIDIA RTX 3080

### RAM

32 GB

### List of applied mods

None

### Additional context?

NS Firmware ver 18.0.0

**Comment by AcK77** [comment]
Your save data seems to be corrupted, or Ryujinx does not have enought right to access to the save folder.
You can come to our discord server for more support. Thanks.
