### ISSUE TITLE
Yoshi's Crafted World crashes just before opening splash screen

### ISSUE THREAD

**Issue by mxradio** [Ryujinx/Ryujinx#6737]
Yoshi's Crafted World crashing now too. 

[Ryujinx_1.1.0+f6879b1_2024-04-27_15-52-42.log](https://github.com/Ryujinx/Ryujinx/files/15140228/Ryujinx_1.1.0%2Bf6879b1_2024-04-27_15-52-42.log)
[Ryujinx_1.1.0+f6879b1_2024-04-27_15-49-45.log](https://github.com/Ryujinx/Ryujinx/files/15140229/Ryujinx_1.1.0%2Bf6879b1_2024-04-27_15-49-45.log)

_Originally posted by @mxradio in https://github.com/Ryujinx/Ryujinx/issues/6697#issuecomment-2081223909_

**Comment by gdkchan** [comment]
Can't reproduce, game is working fine here.
<img width="1392" alt="Captura de Tela 2024-04-27 às 23 45 10" src="https://github.com/Ryujinx/Ryujinx/assets/5624669/b0d507ab-1aa7-4a4a-b0a9-9f82aaa5592f">
<img width="1392" alt="Captura de Tela 2024-04-27 às 23 47 10" src="https://github.com/Ryujinx/Ryujinx/assets/5624669/6483f17b-1683-49ac-85b3-29fa1717b384">

**Comment by mxradio** [comment]
Didn't help, crashing even faster now before splash screen. 

[Ryujinx_1.1.0+f6879b1_2024-04-28_10-10-23.log](https://github.com/Ryujinx/Ryujinx/files/15142948/Ryujinx_1.1.0%2Bf6879b1_2024-04-28_10-10-23.log)
[Ryujinx_1.1.0+f6879b1_2024-04-28_10-08-09.log](https://github.com/Ryujinx/Ryujinx/files/15142949/Ryujinx_1.1.0%2Bf6879b1_2024-04-28_10-08-09.log)

**Comment by AcK77** [comment]
Your save data seems to be corrupted, or Ryujinx does not have enought right to access to the save folder.
That's why gdkchan can't reproduce it. Btw, use our master build instead of a commit one.
You can come to our discord server for more support. Thanks.
