### ISSUE TITLE
Zelda ToTK crash when approaching Mayachin Shrine

### ISSUE THREAD

**Issue by AimanAY** [Ryujinx/Ryujinx#6739]
### Description of the issue

Ryujinx crashes when getting close to the shrine
I tried approaching from different directions, including the sky and it crashes every time

### Reproduction steps

get close to Mayachin Shrine

### Log file

[Ryujinx_1.1.1291_2024-04-28_17-25-38.log](https://github.com/Ryujinx/Ryujinx/files/15142491/Ryujinx_1.1.1291_2024-04-28_17-25-38.log)

### OS

MacOS

### Ryujinx version

1.1.1291

### Game version

1.2.1

### CPU

M2 Pro

### GPU

M2 Pro

### RAM

16GB

### List of applied mods

no mods

### Additional context?

[slot_00.zip](https://github.com/Ryujinx/Ryujinx/files/15142497/slot_00.zip)
in the save file attached, jump towards the red pin (north)

**Comment by MetrosexualGarbodor** [comment]
There is no crash on your log. Please join Discord and post a log containing a crash in the macOS support channel.
