### ISSUE TITLE
[Bug]Dual Card Games only show 1 game in Ryujinx

### ISSUE THREAD

**Issue by Waifu4Life** [Ryujinx/Ryujinx#6740]
### Description of the issue

I have 3 game cards which I dump using the latest nightly build of NXDumpTool: Pikmin 1 + 2, Sonic Forces + Super Monkey Ball: Banana Blitz HD, No More Heroes 1 + 2 (Korean Version). When I dumped these games, they make a single XCI file so in Ryujinx, only 1 game shows up.

### Reproduction steps

1- Dump your dual card game using the latest nightly build of NXDumpTool
2- Place your XCI file in your Ryujinx game directory
3- Look in your Ryujinx game list

### Log file

[Ryujinx_1.1.1291_2024-04-28_12-51-33.log](https://github.com/Ryujinx/Ryujinx/files/15142940/Ryujinx_1.1.1291_2024-04-28_12-51-33.log)

### OS

Windows 10

### Ryujinx version

1.1.1293

**Comment by ekuland** [comment]
This is the point of https://github.com/Ryujinx/Ryujinx/pull/6515
