### ISSUE TITLE
[Feature Request] Set default window size to multiples of internal resolution

### ISSUE THREAD

**Issue by floppyD** [Ryujinx/Ryujinx#6745]
### Overview

Just an option to set default window size to multiples of internal resolution. Like 1x, 2x, 3x and so on.

### Smaller details

The only way to get proper 720p in windowed mode (without painfully resizing the window manually) is by editing Config.json and using

``"window_size_width": 1280,
"window_size_height": 777``
<details>
777 as height because Ryujinx doesn't take only the content in account

![new](https://github.com/Ryujinx/Ryujinx/assets/29208110/93be8a93-4cfd-4726-acbd-22ee0e3ad5b9)

</details>

### Nature of request

Emulators often have options to set scaling in windowed mode, and the default behavior is often setting the window size to 1x internal res.

Ex:
![image](https://github.com/Ryujinx/Ryujinx/assets/29208110/0510f54c-dd3c-455d-9139-6179c27c26df)

### Why would this feature be useful?

Switch's screen is 720p in handheld mode, so having proper scaling for 720p would be nice.

**Comment by TSRBerry** [comment]
Reopen this if you feel like your feature request wasn't fully implemented.

**Comment by floppyD** [comment]
720p/1080p is fine too
