### ISSUE TITLE
[Bug] Start crashing for some games

### ISSUE THREAD

**Issue by superawdi** [Ryujinx/Ryujinx#6749]
### Description of the issue

Recently, I've been experiencing crashes with Ryujinx, which is unusual since most of my games ran smoothly without any issues before. However, now around 15% of the games on my list are crashing. The latest error I encountered was an unhandled exception: "LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed."run

### Reproduction steps

Let's say I am playing ZAU: Tales of kenzera , once I open the game the app just crashes.

### Log file

[Ryujinx_1.1.1295_2024-04-29_13-28-24.log](https://github.com/Ryujinx/Ryujinx/files/15152755/Ryujinx_1.1.1295_2024-04-29_13-28-24.log)

### OS

Window 11

### Ryujinx version

1.1.1295

### Game version

1.0.2

### CPU

i7-10700F

### GPU

NVIDIA RTX 1660 SUPER

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
