### ISSUE TITLE
fsp-srv IFileSystemProxy: 62 (OpenSaveDataInfoReaderOnlyCacheStorage) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#675]
fsp-srv IFileSystemProxy: 62 (OpenCacheStorageList) is not implemented.

## Service description:
[Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::fssrv::sf::IFileSystemProxy(62))
```
OpenCacheStorageList(unknown) -> unknown
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/165

**Comment by Thealexbarney** [comment]
#1449 should fix this. If anyone with the game could test it, that would be great.
