### ISSUE TITLE
[Feature Request] Force custom LOD BIAS on games

### ISSUE THREAD

**Issue by Foul-Tarnished** [Ryujinx/Ryujinx#6751]
### Overview

Most games switch to low res LOD textures/models pretty quickly, and it's even more visible with the resolution scaler on ryu.
if we could have a way to force any game to a negative LOD bias, it could help a lot.

### Smaller details

I think you can do this with nvidia profile inspector, but only for OGL/DX9-11
values are usually negative for better quality (-1, -2, -3, ...)

### Nature of request

Improve graphics (level of details) without needing game-specific mods

### Why would this feature be useful?

less pop-in, better render distance, sharper textures.

**Comment by IsaacMarovitz** [comment]
It is impossible to accomplish this consistently in every game. Every game and engine has different LOD systems, and this isn't necessarily done at the GPU API level.
