### ISSUE TITLE
ZR No Longer Works For Pokémon Scarlet After Auto-Battling

### ISSUE THREAD

**Issue by RuinousPrincess** [Ryujinx/Ryujinx#6753]
### Description of the issue

Ever since the recent updates for Ryujinx I can no longer use ZR to throw out my Pokémon to trigger a battle or recall my Pokémon back into it's Pokéball, and I can't really find any info online if anyone else is having this issue or if it's possibly a issue with the games itself. I've only encountered it a few times in past Ryujinx updates, but this time it's so bad that restarting the game only fixes the bug briefly until it happens again. It makes the game unplayable for me. Also, got like 3 log files, so I am not sure if any of them have any info about the issue, so I'll upload all three. I can try to get more if those don't have any information.

### Reproduction steps

The bug usually happens a lot if I use R to auto-battle then trying to use ZR to recall my Pokémon, and somehow ZR just stops working altogether for me that only restarting the game fixes ZR, allowing it to be used again. Trying picnics or warping doesn't fix it, so auto-battles to using ZR seems to really cause some bad issues. No idea what causes ZR to just stop like that.

### Log file

[Ryujinx_1.1.1294_2024-04-29_23-17-57.log](https://github.com/Ryujinx/Ryujinx/files/15158514/Ryujinx_1.1.1294_2024-04-29_23-17-57.log)
[Ryujinx_1.1.1294_2024-04-30_00-30-32.log](https://github.com/Ryujinx/Ryujinx/files/15158515/Ryujinx_1.1.1294_2024-04-30_00-30-32.log)
[Ryujinx_1.1.1295_2024-04-30_00-31-32.log](https://github.com/Ryujinx/Ryujinx/files/15158516/Ryujinx_1.1.1295_2024-04-30_00-31-32.log)

### OS

Windows 10

### Ryujinx version

1.1.1295

### Game version

3.0.0

### CPU

Intel(R) Core(TM) i5-4800

### GPU

NVIDIA Geforce GTX 1060

### RAM

16GB

**Comment by piplup55** [comment]
for support you should join the [discord](https://discord.gg/ryujinx-410208534861447168)

**Comment by RuinousPrincess** [comment]
I tried to before, but was unable to access their server and I'm a noob at
Discord stuff like that.

Also think it might be game-related when I tried another Switch emulator
and ZR still broke, so maybe it's just the games being buggy as hell like
usual. From Reddit forums, it could be a game bug when using picnics. I
doubt there is a fix unless Nintendo releases a patch.
