### ISSUE TITLE
[Bug] a XCI game was not recognized in 1.1.1295

### ISSUE THREAD

**Issue by Web13234** [Ryujinx/Ryujinx#6755]
### Description of the issue

One XCI game file was not recognized after my Ryujinx update. When I use LDN version 3.0, it loads as usual, and the game file passes the hash and signature check with NSGManager.
(Tried changing the firmware and secret key version, but the problem is not solved)
The screenshot is below:
![image](https://github.com/Ryujinx/Ryujinx/assets/52309229/00954651-2e5c-4d5c-982a-3e44c52c76b1)
![image](https://github.com/Ryujinx/Ryujinx/assets/52309229/e4533b1e-fe05-4b1a-80e6-61acca299d79)

And the console warnings are as follows: 
 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'S:\NSGames\TearsOfTheKingdom\TheLegendOfZeldaTearsOfTheKingdom0100F2C0115B6000APPv0v1.0.0.xci' Error: LibHac.Common.HorizonResultException: ResultFsSha256PartitionHashVerificationFailed (2002-4643)
   at LibHac.Common.ThrowHelper.ThrowResult(Result result)
   at LibHac.Result.ThrowIfFailure()
   at LibHac.Tools.Fs.XciPartition..ctor(IStorage storage)
   at LibHac.Tools.Fs.Xci.OpenPartition(XciPartitionType type)
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 193

### Reproduction steps

XCI file : TheLegendOfZeldaTearsOfTheKingdom0100F2C0115B6000APPv0v1.0.0.xci

### Log file

[Ryujinx_1.1.1295_2024-04-30_22-24-47.log](https://github.com/Ryujinx/Ryujinx/files/15168498/Ryujinx_1.1.1295_2024-04-30_22-24-47.log)

### OS

Windows11

### Ryujinx version

1.1.1295

### Game version

1.0.0

### CPU

i7-9750

### GPU

NVDIA 1660-MQ

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
Dump your game file again.
