### ISSUE TITLE
[Bug] Crash when opening Super Mario 64 in Super Mario 3D All Stars (010049900F546000)

### ISSUE THREAD

**Issue by memoryhash** [Ryujinx/Ryujinx#6758]
### Description of the issue

Ryujinx crashes after trying to load Super Mario 64 from Super Mario 3D All Stars.

### Reproduction steps

Load game, press A to get to main menu, press A to run Super Mario 64, wait, crash.

### Log file

[Ryujinx_1.1.1295_2024-04-30_21-00-38.log](https://github.com/Ryujinx/Ryujinx/files/15170482/Ryujinx_1.1.1295_2024-04-30_21-00-38.log)

### OS

Windows 11 (22621.3447)

### Ryujinx version

1.1.1295

### Game version

1.1.0

### CPU

AMD Ryzen 7950X3D

### GPU

NVIDIA RTX 4090

### RAM

64GB

### List of applied mods

N/A

### Additional context?

I am using an official Nintendo Switch Pro Controller connected via USB-C.

**Comment by gdkchan** [comment]
Works here, though I'm still on version 1.0.0 of the game.
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/b4bea0b5-ba46-4feb-b22a-7e6bbf66c1b1)

**Comment by gdkchan** [comment]
I also did not test firmware 18.0.0 which is somewhat recent.

**Comment by piplup55** [comment]
checked nintendo 64 nso and allstars, it loads on 17.0.1 and crashes on 18.0.0 and 18.0.1
[Ryujinx_1.1.1295_2024-04-30_23-41-45.log](https://github.com/Ryujinx/Ryujinx/files/15171990/Ryujinx_1.1.1295_2024-04-30_23-41-45.log)

**Comment by piplup55** [comment]
fixed by #7075
