### ISSUE TITLE
There is no sound of dialogues

### ISSUE THREAD

**Issue by Mifkill** [Ryujinx/Ryujinx#6760]
### Description of the issue

the sound of the game is there, but the dialogues are not voiced, can this be fixed

### Reproduction steps

Games

### Log file

[Ryujinx_1.1.1295_2024-05-01_19-10-14.log](https://github.com/Ryujinx/Ryujinx/files/15177775/Ryujinx_1.1.1295_2024-05-01_19-10-14.log)

### OS

Windows 10

### Ryujinx version

1.1.1295

### GPU

nvidia 3050 laptop

### RAM

24 gb

**Comment by piplup55** [comment]
for support you should join the [discord](https://discord.gg/ryujinx) and ask in a support channel
