### ISSUE TITLE
Double Dragon Collection Showing only 1 game instead of 6[Bug]

### ISSUE THREAD

**Issue by Deathwishx64** [Ryujinx/Ryujinx#6761]
### Description of the issue

Hello,

When i open Double Dragon Collections with Ryujinx I can only see and run the Double Dragon Advanced. On the other Emulator that start with a Y (I don't want to say the name) I can see all 6 of them. I am running the latest keys and firmware (8.0.0 keys and 8.0.1. firmware)

![Ryujinx](https://github.com/Ryujinx/Ryujinx/assets/152556270/eadd6247-818a-4cd7-ab59-2ee94aeeb87f)
![Yuz](https://github.com/Ryujinx/Ryujinx/assets/152556270/fa3a32e2-a6f0-4ea2-ad06-1849eb1172f9)

### Reproduction steps

Load the game Double Dragon Collection [0100DD900E498000+01001AD00E49A000+010001B005E5C000+01009930191EC000+01003CF0191EE000][v0][US](nsw2u.com).xci
in game dir and run Ryujinx

### Log file

[Ryujinx_1.1.1295_2024-05-01_10-12-38.log](https://github.com/Ryujinx/Ryujinx/files/15177845/Ryujinx_1.1.1295_2024-05-01_10-12-38.log)

### OS

Windows 10

### Ryujinx version

1.1.1295

### Game version

1.0.1

### CPU

i9-10850k

### GPU

Nvidia RTX 3080

### RAM

32GB

**Comment by ekuland** [comment]
This is the point of https://github.com/Ryujinx/Ryujinx/pull/6515

**Comment by TSRBerry** [comment]
We'll just close it automatically, when the PR gets merged. That way you also get a notification when the feature is available.
