### ISSUE TITLE
[Bug] 0 FPS in TOTK

### ISSUE THREAD

**Issue by alba4k** [Ryujinx/Ryujinx#6764]
### Description of the issue

I don't really know why, but the performance in Ryujinx is terrible (I was getting 30-60 fps on yuzu). It's perfectly fine in the start menu and in the loading screen, but the last frames of the loading screen and the actual game run at what I would estimate to be 0.5 - 0.2 FPS.

### Reproduction steps

Open TOTK

### Log file

[Ryujinx_1.1.1296+e1a995dbe09f6abb99a0f258280f110404f637d4_2024-05-01_22-13-31.log](https://github.com/Ryujinx/Ryujinx/files/15181017/Ryujinx_1.1.1296%2Be1a995dbe09f6abb99a0f258280f110404f637d4_2024-05-01_22-13-31.log)

### OS

Arch Linux

### Ryujinx version

1.1.1296

### Game version

1.2.1

### CPU

i7-1260P

### GPU

Alder Lake P intel iris Xe

### RAM

16GB (16GB swap)

### List of applied mods

Unrelated, The issues appears without any

* Black Screen Fix
* TOTK Optimizer

### Additional context?

Running Ryujinx under Hyprland, via xwayland, and using gamemode.

While running at basically 0 FPS, the sound plays perfectly fine and the CPU usage is normal

Please don't mint telling me about anything that might be useful to help debugging this :)

**Comment by ekuland** [comment]
We do not support custom builds. You also have many logs off. Use an [official emulator release](https://ryujinx.org/download) and join [the discord](https://discord.gg/ryujinx) for general support.

**Comment by alba4k** [comment]
@ekuland no difference but thanks for the link do the discord, I will most certainly try that
