### ISSUE TITLE
[Bug] BoTW crashing on start

### ISSUE THREAD

**Issue by asianmaster64** [Ryujinx/Ryujinx#6765]
### Description of the issue

I'm trying to play BoTW but every time I click on the game shows the loading bar but when the bar is full Ryujinx crashes. Other games don't crash for me but the other games I have are Cyberpoly RPG - Dark City and World of Horror.

### Reproduction steps

I click on the game it crashes every time

### Log file

Don't know how to lmao

### OS

Sonoma 14.2.1 (23C71)

### Ryujinx version

1.1.1296

### Game version

1.0.0

### CPU

M2 Pro

### GPU

N/A

### RAM

16GB

### List of applied mods

No mods

### Additional context?

It's the base game with no mods, updates, and DLC

**Comment by gdkchan** [comment]
Duplicate of #6727.

**Comment by asianmaster64** [comment]
I turned of Hyper vision and it still crashed
