### ISSUE TITLE
[Bug] crashes while lunching Yo-kai_Watch_4

### ISSUE THREAD

**Issue by Kik07L** [Ryujinx/Ryujinx#6770]
### Description of the issue

So when i lunch classic games like mk8 or others ryujinx work well just when i try tu lunch Yo-kai_Watch_4 the game is not loading and it crashes, i tried differents rom formats and setting but Always the same error on the cmd and it's crashing again and again

### Reproduction steps

lunch ryujinx load a rom of Yo-kai_Watch_4 start the game and ryujinx close

### Log file

00:00:00.078 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.089 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.089 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.090 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.092 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.093 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.094 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1F08
00:00:00.095 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.096 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.096 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.098 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.107 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.107 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.107 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.107 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.107 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.107 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.108 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.108 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.108 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.109 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.109 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.111 |I| Configuration LogValueChange: MemoryManagerMode set to: SoftwarePageTable
00:00:00.111 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.111 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.111 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.116 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.121 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1297
00:00:00.127 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.127 |N| Application Print: CPU: AMD Ryzen 5 2600 Six-Core Processor ; 12 logical
00:00:00.129 |N| Application Print: RAM: Total 23.9 GiB ; Available 11 GiB
00:00:00.133 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.134 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:23.782 |I| Configuration LogValueChange: EnablePtc set to: False
00:00:23.782 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:29.480 |I| Configuration LogValueChange: EnableShaderCache set to: False
00:00:29.480 |I| Configuration LogValueChange: EnableMacroHLE set to: False
00:00:00.152 |I| Gpu : Backend Threading (Auto): True
00:00:00.500 |N| Application LoadGuestApplication: Using Firmware Version: 15.0.1
00:00:00.500 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.524 |I| ModLoader QueryContentsDir: Searching mods for Application 010086C00AF7C000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.525 |I| ModLoader QueryContentsDir: Searching mods for Application 010086C00AF7C000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.527 |I| ModLoader AddModsFromDirectory: Found enabled mod '010086c00af7c000' [R]
00:00:00.527 |I| ModLoader QueryPatchDirs: Found NSO patch 'YKW4pp-NoFullwidth-By-RSM'
00:00:00.530 |I| Loader Load: Loading rtld...
00:00:00.537 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.537 |I| Loader Load: Loading main...
00:00:00.706 |I| Loader PrintRoSectionInfo: main:
    Module: G:\yw4\program\main\program\Release\NX64_Rom\yw_nx.nss
    SDK Libraries: SDK MW+Nintendo+NEX_MM-4_6_2
                   SDK MW+Nintendo+NEX-4_6_2-
                   SDK MW+Nintendo+PiaCommon-5_17_0
                   SDK MW+Nintendo+Pia-5_17_0
                   SDK MW+Nintendo+PiaLocal-5_17_0
                   SDK MW+Nintendo+PiaNex-5_17_0-forNEX-4_6_2
                   SDK MW+Nintendo+PiaSession-5_17_0
                   SDK MW+Nintendo+PiaTransport-5_17_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+NVIDIA+PhysX-3_4_0-release
00:00:00.706 |I| Loader Load: Loading sdk...
00:00:00.802 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:00.812 |W| Ptc Load: Detected unsupported ExeFs modifications. PTC disabled.
00:00:00.941 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: False).
00:00:00.952 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.953 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.973 |I| Loader LoadNsos: Loading image 2 at 0x000000000adce000...
00:00:00.981 |I| ModLoader LoadCheats: Build ids found for application 010086C00AF7C000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    E2630E9B825910485CC2899EBCBA254DAA6A6366000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:00.986 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Application 010086C00AF7C000
00:00:01.019 |I| ModLoader ApplyRomFsMods: Replaced 8 file(s) over 1 mod(s). Processing base storage...
00:00:01.123 |I| ModLoader ApplyRomFsMods: Building new RomFS...
00:00:01.132 |I| ModLoader ApplyRomFsMods: Using modded RomFS
00:00:01.134 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.219 |I| Loader Start: Application Loaded: 妖怪ウォッチ4 ぼくらは同じ空を見上げている v1.0.0 [010086c00af7c000] [64-bit]
00:00:01.248 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.263 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.664 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2060 (Vulkan v1.3.277, Driver v551.76.0.0)
00:00:02.403 |S| HLE.OsThread.51 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.465 |S| HLE.OsThread.51 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.472 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.477 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.543 |S| HLE.OsThread.51 ServicePctl Initialize: Stubbed. 
00:00:02.661 |G| HLE.OsThread.22 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 2s
    ProgramName: yw_nx
    Thread: MainThread
    Filename: G:/yw4/program/lives/program/10_lib_platform/src/nx/device/device_nx.cpp
    Line: 301
    Function: Startup
    Message: Remain Memory Size 258MiB (270532608byte)

00:00:06.191 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed. 
00:00:06.317 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed. 
00:00:06.379 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:06.381 |S| HLE.OsThread.8 ServiceNv ZbcSetTable: Stubbed. 
00:00:06.381 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:06.524 |S| HLE.OsThread.51 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.525 |S| HLE.OsThread.51 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:06.526 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.526 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.530 |S| HLE.OsThread.51 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72205753413779456}
00:00:06.542 |S| HLE.OsThread.51 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:06.610 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.611 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.611 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.612 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:06.616 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.616 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:06.617 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:06.627 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:06.686 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.686 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.686 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.686 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:06.687 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:06.687 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:06.687 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:06.765 |I| HLE.OsThread.51 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:07.021 |W| HLE.GuestThread.50 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:07.027 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:07.029 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:07.037 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:07.380 |I| HLE.GuestThread.50 Cpu PrintGuestStackTrace: Guest stack trace:
Process: 妖怪ウォッチ4 ぼくらは同じ空を見上げている, PID: 127
   0x0000000008d23a70	main:0x81fa70	nnMain:0x1d60
   0x000000000b064c9c	sdk:0x296c9c	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()):0x004c
   0x00000000085000c0	rtld:0x00c0	

00:00:07.382 |I| HLE.GuestThread.50 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x00000000099a9430
	X[01]:	0x0000000000000000
	X[02]:	0x000000100bd03e00 (SP:-0xffffffffffffffb0)
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000000
	X[09]:	0x0000000000000001
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000000
	X[12]:	0x0000000000000001
	X[13]:	0x00000000000000b0
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x00000000098a07f8
	X[17]:	0x000000000b0f5ca0 (sdk:0x327ca0)	=> nn::os::GetCurrentThread()
	X[18]:	0x0000000000000000
	X[19]:	0x00000000099a9430
	X[20]:	0x0000000009b67000
	X[21]:	0x0000000008504000 (main:0x0000)	=> 
	X[22]:	0x000000000999b000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x000000100bd03eb0 (SP:-0x0060)
	LR:	0x0000000008a28728 (main:0x524728)	=> 
	SP:	0x000000100bd03e50 (SP)
	PC:	0x0000000008d3d0f0 (main:0x8390f0)	=> 

00:00:07.382 |E| HLE.GuestThread.50 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.

### OS

Windows 11

### Ryujinx version

15.0.1

### Game version

1.0.0

### CPU

Ryzen 52600

### GPU

Nvidia geforce RTX 2060

### RAM

24gb ddr4

**Comment by MetrosexualGarbodor** [comment]
The mod you're running is not for your version of the game. In the future, please don't open issues for help and use Discord instead.
