### ISSUE TITLE
Persona 5 royal slowing down severely and crashing

### ISSUE THREAD

**Issue by Alioman15** [Ryujinx/Ryujinx#6776]
### Description of the issue

I have played p5r on Ryujinx for a long time, but after updating to the latest version, it has been going through an error where it sometimes slows down and experiences rendering errors (character faces separating from bodies, etc), It also crashes sometimes, especially during scene changes.

### Reproduction steps

1-open game with these settings: 
![image](https://github.com/Ryujinx/Ryujinx/assets/169000410/45aa6a7f-e284-42ff-90af-23fc7e9e4991), vsync on
2-enter crowded area/ change of environment

### Log file

[Ryujinx_1.1.1297_2024-05-06_01-10-31.log](https://github.com/Ryujinx/Ryujinx/files/15214795/Ryujinx_1.1.1297_2024-05-06_01-10-31.log)

### OS

windows 11 enterprise

### Ryujinx version

1.1.1295

### Game version

1.0

### CPU

i7-10070

### GPU

NVIDIA GTX 1650

### RAM

16GB

### List of applied mods

60fps cheat, problem occurs even when turned off

**Comment by MetrosexualGarbodor** [comment]
You ran out of VRAM. Given that you're on a GTX 1650, your resolution scaling is probably too high. Lower it.

In the future, please use Discord for help.
