### ISSUE TITLE
[Bug]DRAGON BALL Z: KAKAROT freezes the entire mac

### ISSUE THREAD

**Issue by lwlbeng** [Ryujinx/Ryujinx#6790]
### Description of the issue

DRAGON BALL Z: KAKAROT freezes the entire mac

### Reproduction steps

If you just open it, it'll get stuck

### Log file

[Ryujinx_1.1.1298_2024-05-09_12-56-48.log](https://github.com/Ryujinx/Ryujinx/files/15259180/Ryujinx_1.1.1298_2024-05-09_12-56-48.log)

### OS

macOS 13.3.1

### Ryujinx version

1.1.1298

### Game version

1.50

### CPU

i7 8809G

### GPU

RX Vega M GH

### RAM

32GB

### Additional context?

NUC8i7HVK hackmac

**Comment by AcK77** [comment]
Could you please report game status on the dedicated repository: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3986
Thanks.
