### ISSUE TITLE
kirby return to dreamland deluxe issue

### ISSUE THREAD

**Issue by Acci-denti** [Ryujinx/Ryujinx#6797]
### Description of the issue

Hi guys I need help with ryujinx;

I've been trying to play Kirby Return to Dreamland Deluxe for days. the game seems to work correctly at first, but after a while the graphic starts to glitch and then the game crashes. I've looked on github how to fix the problem but nothing seems to work.
Other games i played work fine.

Firmware version: 18.0.0

here some pictures:

![Desktop Screenshot 2024 05 12 - 21 53 25 04](https://github.com/Ryujinx/Ryujinx/assets/169615086/55dc388a-1a83-40a0-898d-e9cdcb68dd8e)
![Desktop Screenshot 2024 05 12 - 21 53 48 01](https://github.com/Ryujinx/Ryujinx/assets/169615086/a6982bfe-74f9-4479-b09c-d920c1dee843)
![Desktop Screenshot 2024 05 12 - 21 54 42 87](https://github.com/Ryujinx/Ryujinx/assets/169615086/baab1b3a-334d-4c41-9015-486396926367)

### Reproduction steps

.

### Log file

[Ryujinx_1.1.1298_2024-05-12_21-46-34.log](https://github.com/Ryujinx/Ryujinx/files/15287575/Ryujinx_1.1.1298_2024-05-12_21-46-34.log)

### OS

windows 10

### Ryujinx version

1.1.1298

### Game version

1.0.0

### CPU

Intel Core i5-8400

### GPU

Nvidia gtx 1050

### RAM

16 GB

**Comment by gdkchan** [comment]
You're running out of VRAM. You can try enabling texture recompression, which might help if the game uses ASTC textures.

**Comment by GamerzHell9137** [comment]
Also you can try with OpenGL too.

**Comment by Acci-denti** [comment]
I solved the problem. Thank you
