### ISSUE TITLE
BOTW crash caused by read from nullpointer [Bug]

### ISSUE THREAD

**Issue by buildmine10** [Ryujinx/Ryujinx#6814]
### Description of the issue

When loading the game, the menu loads, then some error occurs and it crashes. But for some reason this doesn't happen if I enable the relics of the past mod. I have tested with the mod not in the mods folder (so not available in any way to ryujinx) on all cpu modes, with both extended and normal ram, with both OpenGL and Vulkan, with PPTC enabled and disabled, with and without a fresh shader cache. It crashes with the same error in all those circumstances.

This was not an issue before I started modding the game. I tested the same game files on Yuzu to see if somehow it was corrupted and the mod was fixing it. The game ran unmodded on Yuzu. This is why I believe it to be some kind of bug with Ryujinx.

Using the safer CPU modes make it take longer for this error to occur. ie. It gets deeper into the game before crashing.
For Host Unchecked the nintendo logo appears then it crashes.
For Host the nintendo logo appears and sometimes the light, then it crashes.
For Software it gets to the light, then it crashes.

If previous save data exists, Host Unchecked and Host both crash before the main menu loads, and Software lets me navigate the menu and even start to load the save before crashing. It seems to always crash after the same amount of time.

### Reproduction steps

This is performed with no save files.

To get the error. I only need to start botw without relics of the past.
To not get the error. I only need to start with relics of the past.

I can also run the game if Waikuteru's randomizer is active as the only mod.

The prescence of either Waikuteru's randomizer or Relics of the Past are the only way I have made BOTW not crash.
This issue is not happening for other games.

I believe I have done something that I am unaware of to cause this issue.

### Log file

00:00:00.184 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.190 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.190 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.191 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.191 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.192 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.192 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2783
00:00:00.193 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.193 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.193 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.194 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.199 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.199 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.199 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.199 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.199 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.199 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.199 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.199 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.199 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.200 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.200 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.201 |I| Configuration LogValueChange: MemoryManagerMode set to: SoftwarePageTable
00:00:00.201 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.201 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.201 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.203 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.205 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1312
00:00:00.208 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.208 |N| Application Print: CPU: AMD Ryzen 7 7800X3D 8-Core Processor ; 16 logical
00:00:00.209 |N| Application Print: RAM: Total 31.7 GiB ; Available 20.6 GiB
00:00:00.211 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.211 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.076 |I| Gpu : Backend Threading (Auto): True
00:00:00.334 |N| Application LoadGuestApplication: Using Firmware Version: 15.0.1
00:00:00.334 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.354 |I| Application AddAocItem: Found AddOnContent with TitleId 01007EF00011F002
00:00:00.356 |I| Application AddAocItem: Found AddOnContent with TitleId 01007EF00011F001
00:00:00.370 |I| ModLoader QueryContentsDir: Searching mods for Application 01007EF00011E000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.375 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.376 |I| ModLoader AddModsFromDirectory: Found enabled mod 'Randomizer' [R]
00:00:00.376 |I| ModLoader AddModsFromDirectory: Found enabled mod 'Relics of the Past' [R]
00:00:00.376 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.376 |I| ModLoader QueryContentsDir: Searching mods for Application 01007EF00011E000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.377 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.377 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.379 |I| Loader Load: Loading rtld...
00:00:00.382 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.382 |I| Loader Load: Loading main...
00:00:00.528 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Cafe\U-King\trunk\Game\App\Rom\NX64\Product\code\U-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Atk-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-7_3_2-Release
                   SDK MW+Microsoft+Havok_Cloth-2014_2
                   SDK MW+Microsoft+Havok-2014_2
                   SDK MW+Microsoft+Havok_Animation-2014_2
                   SDK MW+Microsoft+Havok_AI-2014_2
                   SDK MW+Microsoft+Havok_Physics2012-2014_2
00:00:00.528 |I| Loader Load: Loading subsdk0...
00:00:00.547 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-7_3_2-Release
00:00:00.547 |I| Loader Load: Loading sdk...
00:00:00.582 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:00.645 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.083 |I| Ptc Load: Loaded Translation Cache (size: 190868639 bytes, translated functions: 49840).
00:00:02.095 |I| Ptc Load: Loaded Profiling Info (size: 170247 bytes, profiled functions: 49831).
00:00:02.098 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:02.099 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:02.109 |I| Loader LoadNsos: Loading image 2 at 0x000000000b26a000...
00:00:02.111 |I| Loader LoadNsos: Loading image 3 at 0x000000000b987000...
00:00:02.115 |I| ModLoader LoadCheats: Build ids found for application 01007EF00011E000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    8E9978D50BDD20B4C8395A106C27FFDE00000000000000000000000000000000
    93FF8252D975ADF07230CB86C83301C53F2804DF000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:02.117 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.174 |I| Loader Start: Application Loaded: The Legend of Zelda: Breath of the Wild v1.6.0 [01007ef00011e000] [64-bit]
00:00:02.503 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.511 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.711 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 4070 SUPER (Vulkan v1.3.277, Driver v552.44.0.0)
00:00:02.718 |I| GPU.MainThread Gpu LoadShaders: Loading 698 shaders from the cache...
00:00:03.493 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:04.503 |I| HLE.GuestThread.50 Ptc LoadTranslations: 49831 translated functions loaded
00:00:04.623 |S| HLE.OsThread.51 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:04.626 |S| HLE.OsThread.51 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:04.626 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:04.627 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:04.632 |S| HLE.OsThread.51 ServicePctl Initialize: Stubbed. 
00:00:05.327 |G| HLE.OsThread.22 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: U-King
    Thread: MainThread
    Filename: D:/home/Cafe/U-King/trunk/Game/Lib/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp
    Line: 18
    Function: PrintStringImpl
    Message: 0000002e

00:00:05.328 |S| HLE.OsThread.51 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:05.328 |S| HLE.OsThread.51 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:05.329 |S| HLE.OsThread.51 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:05.329 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.329 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:05.352 |S| HLE.OsThread.8 ServiceNv FinishInitialize: Stubbed. 
00:00:05.356 |I| HLE.OsThread.51 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.367 |S| HLE.OsThread.8 ServiceNv InitializeEx: Stubbed. 
00:00:05.375 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.401 |S| HLE.OsThread.8 ServiceNv SetNvMapFd: Stubbed. 
00:00:05.401 |S| HLE.OsThread.8 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:05.402 |S| HLE.OsThread.8 ServiceNv AllocObjCtx: Stubbed. 
00:00:05.402 |S| HLE.OsThread.8 ServiceNv SetTimeout: Stubbed. 
00:00:05.402 |S| HLE.OsThread.8 ServiceNv SetErrorNotifier: Stubbed. 
00:00:05.403 |S| HLE.OsThread.8 ServiceNv SetUserData: Stubbed. 
00:00:05.403 |S| HLE.OsThread.8 ServiceNv SetTimeslice: Stubbed. 
00:00:05.404 |S| HLE.OsThread.8 ServiceNv ZcullBind: Stubbed. 
00:00:05.424 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:05.426 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:05.427 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:05.433 |S| HLE.OsThread.7 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:05.456 |S| HLE.OsThread.51 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72197163296350208}
00:00:05.458 |S| HLE.OsThread.51 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:05.483 |S| HLE.OsThread.51 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:05.484 |I| HLE.OsThread.6 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:05.484 |I| HLE.OsThread.6 ModLoader ApplyRomFsMods: Applying RomFS mods for Application 01007EF00011F001
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/A-1/A-1_Dynamic.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/A-1/A-1_Static.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/A-2/A-2_Dynamic.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/A-2/A-2_Static.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/B-1/B-1_Dynamic.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/B-1/B-1_Static.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/B-2/B-2_Dynamic.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/B-2/B-2_Static.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/B-5/B-5_Dynamic.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/B-5/B-5_Static.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/F-5/F-5_Dynamic.smubin' from 'Relics of the Past'
00:00:05.547 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/AocField/F-5/F-5_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-1/A-1_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-1/A-1_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-2/A-2_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-2/A-2_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-3/A-3_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-3/A-3_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-4/A-4_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-4/A-4_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-5/A-5_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-5/A-5_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-6/A-6_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-6/A-6_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-7/A-7_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-7/A-7_Static.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-8/A-8_Dynamic.smubin' from 'Relics of the Past'
00:00:05.548 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/A-8/A-8_Static.smubin' from 'Relics of the Past'
//Many lines have been deleted because this log was too long. (I'm not sure how its finding Relics of the Past. It was not listed under manage mods for this attempt)
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-3/J-3_Dynamic.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-3/J-3_Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-4/J-4_Dynamic.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-4/J-4_Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-5/J-5_Dynamic.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-5/J-5_Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-6/J-6_Dynamic.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-6/J-6_Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-7/J-7_Dynamic.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-7/J-7_Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-8/J-8_Dynamic.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/J-8/J-8_Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainField/Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Map/MainFieldDungeon/Static.smubin' from 'Relics of the Past'
00:00:05.644 |W| HLE.OsThread.6 ModLoader ApplyRomFsMods:     Skipped duplicate file '/Pack/AocMainField.pack' from 'Relics of the Past'
00:00:05.644 |I| HLE.OsThread.6 ModLoader ApplyRomFsMods: Replaced 338 file(s) over 2 mod(s). Processing base storage...
00:00:05.690 |I| HLE.OsThread.6 ModLoader ApplyRomFsMods: Building new RomFS...
00:00:05.692 |I| HLE.OsThread.6 ModLoader ApplyRomFsMods: Using modded RomFS
00:00:06.134 |S| HLE.OsThread.8 ServiceNv ZbcSetTable: Stubbed. 
00:00:06.134 |S| HLE.OsThread.8 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:08.483 |S| HLE.OsThread.7 ServiceHid ActivateConsoleSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:08.483 |S| HLE.OsThread.7 ServiceHid InitializeSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; counter0: 4096 ; counter1: 520192}
00:00:08.773 |I| HLE.OsThread.15 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:08.775 |I| HLE.OsThread.15 AudioRenderer Initialize: Initializing with REV7
00:00:08.784 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:08.784 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:08.798 |I| HLE.OsThread.15 AudioRenderer Start: Starting renderer id 0
00:00:08.813 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:08.951 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:10.311 |S| HLE.OsThread.7 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; _gyroscopeZeroDriftMode: Tight}
00:00:10.312 |S| HLE.OsThread.51 ServiceAm SetGamePlayRecordingState: Stubbed. {_gamePlayRecordingState: True}
00:00:10.314 |S| HLE.OsThread.7 ServiceHid StopSevenSixAxisSensor: Stubbed. {appletResourceUserId: 1}
00:00:18.598 |I| HLE.GuestThread.86 Cpu PrintGuestStackTrace: Guest stack trace:
Process: The Legend of Zelda: Breath of the Wild, PID: 127
   0x0000000009a64618	main:0x1560618	
   0x0000000009a5f008	main:0x155b008	
   0x0000000009c7b658	main:0x1777658	
   0x000000000931a138	main:0xe16138	
   0x000000000934b9fc	main:0xe479fc	
   0x000000000a1508c8	main:0x1c4c8c8	
   0x000000000a14eed8	main:0x1c4aed8	
   0x0000000009771b78	main:0x126db78	
   0x0000000009770f74	main:0x126cf74	
   0x000000000bcb0e88	sdk:0x329e88	
   0x000000000bcb5294	sdk:0x32e294	
   0x0000000000000000

00:00:18.599 |I| HLE.GuestThread.86 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000001
	X[01]:	0x00000020b46ae752
	X[02]:	0x000000000abb0153
	X[03]:	0x00000000c3050f7d
	X[04]:	0x000000212fa65388
	X[05]:	0x0000002130573230
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000000
	X[09]:	0x0000001069b5ab40 (SP:-0xffffffffffffffc0)
	X[10]:	0x00000000000002c1
	X[11]:	0x000000000b1c37a4
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000463170
	X[14]:	0x000000000002fa93
	X[15]:	0x000000212fa65480
	X[16]:	0x000000000b182cd8
	X[17]:	0x000000000be3fd80 (sdk:0x4b8d80)	=> 
	X[18]:	0x00000000ffffffff
	X[19]:	0x00000000c3050f7d
	X[20]:	0x0000000000000035
	X[21]:	0x00000021309ca5a8
	X[22]:	0x000000000abc7d80
	X[23]:	0x0000000000000000
	X[24]:	0x000000000aba1238
	X[25]:	0x000000000af726c0
	X[26]:	0x0000000000000001
	X[27]:	0x000000000b1c8000
	X[28]:	0x00000000ffffffff
	FP:	0x0000001069b5ac30 (SP:-0x00b0)
	LR:	0x0000000009a7f540 (main:0x157b540)	=> 
	SP:	0x0000001069b5ab80 (SP)
	PC:	0x000000000be3fd80 (sdk:0x4b8d80)	=> 

00:00:18.599 |E| HLE.GuestThread.86 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000018.
00:00:18.599 |I| HLE.GuestThread.86 Cpu PrintGuestStackTrace: Guest stack trace:
Process: The Legend of Zelda: Breath of the Wild, PID: 127
   0x0000000009a64618	main:0x1560618	
   0x0000000009a5f008	main:0x155b008	
   0x0000000009c7b658	main:0x1777658	
   0x000000000931a138	main:0xe16138	
   0x000000000934b9fc	main:0xe479fc	
   0x000000000a1508c8	main:0x1c4c8c8	
   0x000000000a14eed8	main:0x1c4aed8	
   0x0000000009771b78	main:0x126db78	
   0x0000000009770f74	main:0x126cf74	
   0x000000000bcb0e88	sdk:0x329e88	
   0x000000000bcb5294	sdk:0x32e294	
   0x0000000000000000

00:00:18.599 |I| HLE.GuestThread.86 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000001
	X[01]:	0x00000020b46ae752
	X[02]:	0x000000000abb0153
	X[03]:	0x00000000c3050f7d
	X[04]:	0x000000212fa65388
	X[05]:	0x0000002130573230
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000000
	X[09]:	0x0000001069b5ab40 (SP:-0xffffffffffffffc0)
	X[10]:	0x00000000000002c1
	X[11]:	0x000000000b1c37a4
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000463170
	X[14]:	0x000000000002fa93
	X[15]:	0x000000212fa65480
	X[16]:	0x000000000b182cd8
	X[17]:	0x000000000be3fd80 (sdk:0x4b8d80)	=> 
	X[18]:	0x00000000ffffffff
	X[19]:	0x00000000c3050f7d
	X[20]:	0x0000000000000035
	X[21]:	0x00000021309ca5a8
	X[22]:	0x000000000abc7d80
	X[23]:	0x0000000000000000
	X[24]:	0x000000000aba1238
	X[25]:	0x000000000af726c0
	X[26]:	0x0000000000000001
	X[27]:	0x000000000b1c8000
	X[28]:	0x00000000ffffffff
	FP:	0x0000001069b5ac30 (SP:-0x00b0)
	LR:	0x0000000009a7f540 (main:0x157b540)	=> 
	SP:	0x0000001069b5ab80 (SP)
	PC:	0x000000000be3fd80 (sdk:0x4b8d80)	=> 

00:00:18.599 |E| HLE.GuestThread.86 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000018.
00:00:18.621 |E| HLE.GuestThread.86 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\MemoryBlock.cs:line 440
   at Ryujinx.Cpu.Jit.MemoryManager.GetPhysicalAddressSpan(UIntPtr pa, Int32 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 504
   at Ryujinx.Memory.VirtualMemoryManagerBase.Read(UInt64 va, Span`1 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\VirtualMemoryManagerBase.cs:line 170
   at Ryujinx.Cpu.Jit.MemoryManager.Read(UInt64 va, Span`1 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 168
   at Ryujinx.Memory.VirtualMemoryManagerBase.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\VirtualMemoryManagerBase.cs:line 107
   at Ryujinx.Memory.VirtualMemoryManagerBase.Read[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\VirtualMemoryManagerBase.cs:line 150
   at Ryujinx.Cpu.Jit.MemoryManager.ReadGuest[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 150
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264

### OS

Windows 10

### Ryujinx version

1.1.1312

### Game version

1.6.0

### CPU

AM Ryzen 7 7800X3D

### GPU

NVIDIA GeForce RTX 4070 SUPER (dGPU)

### RAM

16 GB

### List of applied mods

Only applied on their own.
Relics of the Past
Waikuteru's BOTW Randomizer

### Additional context?

I was setting up multiple user profiles for using different save files with different mods. That was working. When I moved the existing save data from the original profile to the dedicated modded profile, I then deleted the save data from the original profile. When I then tried to disable the mods and load a fresh game this error occured.

This is my first time using Ryujinx. I downloaded it today.

**Comment by piplup55** [comment]
Does this happen without the mod
