### ISSUE TITLE
Unable to recognize AMD graphics card under Vulkan simulation[Bug]

### ISSUE THREAD

**Issue by yemaowuxin** [Ryujinx/Ryujinx#6815]
### Description of the issue

![image](https://github.com/Ryujinx/Ryujinx/assets/48284264/b86c47e0-0f1c-4cac-b5c3-050bac20e731)

### Reproduction steps

none

### Log file

none

### OS

window 11

### Ryujinx version

1.1.1312

### CPU

10900K

### GPU

AMD Radeon RX 6900 XT

### RAM

32GB

**Comment by piplup55** [comment]
Without a log file, there no real way for us to tell what the issue is here, make sure your drivers are up to date in future use the [discord](https://discord.gg/ryujinx) for support

**Comment by yemaowuxin** [comment]
> Without a log file, there no real way for us to tell what the issue is here, make sure your drivers are up to date in future use the [discord](https://discord.gg/ryujinx) for support

已添加日志文件。

**Comment by yemaowuxin** [comment]
> Without a log file, there no real way for us to tell what the issue is here, make sure your drivers are up to date in future use the [discord](https://discord.gg/ryujinx) for support

Log file added.
