### ISSUE TITLE
[Feature Request] Enable ability to stop emulation just by controller

### ISSUE THREAD

**Issue by ns6000** [Ryujinx/Ryujinx#6819]
### Overview

If possible, ability to stop emulation (or exit the emulator completely when running with command line parameter `--fullscreen`) just by using controller.

This could be done in many ways, in the maximalist way by creating possibility to define controller shortcuts Steam-style. But basic implementation would just entail hardcoded controller shortcut just for stopping emulation / exiting Ryujinx.

### Smaller details

Ideally controller shortcuts would use Guide button (PlayStation logo on DualShock 4, Xbox logo on Xbox controller and, i presume, Home button on Switch Pro controller) with some other button. Preferably there could be some predefined actions in the future to expand on this, like taking screenshots and such, but the ability to exit is the most important.

### Nature of request

Better support for Steam Big Picture gaming on TV when Ryujinx is added as non-Steam game with command line parameters for full screen and game.

### Why would this feature be useful?

Now, when you want to exit Ryujinx instance started as non-Steam game instance from steam Big Picture, you have no other way of exiting than using Steam overlay and essentially killing the process of Ryujinx. The ability to kill the process is basically only reason to have Steam overlay turned on for Ryujinx in the first place.

**Comment by gdkchan** [comment]
Sounds like this is a duplicate/subset of #3423.

**Comment by ns6000** [comment]
> Sounds like this is a duplicate/subset of #3423.

Damn, i tried to search for similar issue but didn't find this one, my bad.

**Comment by rollercoaster** [comment]
This would be excellent feature !
