### ISSUE TITLE
[Bug] Ryujinx and Cemu

### ISSUE THREAD

**Issue by RandomUser35** [Ryujinx/Ryujinx#6833]
### Description of the issue

Ryujinx and  Cemu won't open up on the first setup, I installed the vc file and the.NET files required and my drivers.

### Reproduction steps

I dunno

### Log file

I dont have the log files..

### OS

Windows 11 24H2

### Ryujinx version

The latest version

### Game version

1316

### CPU

i5-I5-14400

### GPU

Intel Graphics Card

### RAM

8GB

### List of applied mods

None

### Additional context?

Nope

**Comment by piplup55** [comment]
use the ryujinx [discord](https://discord.gg/ryujinx) for support
for cemu support goto the cemu discord

**Comment by RandomUser35** [comment]
Bruh I can't use discord
