### ISSUE TITLE
[Bug]Graphics card not recognized

### ISSUE THREAD

**Issue by tiancaiqx** [Ryujinx/Ryujinx#6840]
### Description of the issue

Unable to render when running Bayonetta 3, white screen
![Snipaste_2024-05-21_21-50-44](https://github.com/Ryujinx/Ryujinx/assets/95039251/18be6c46-aecc-4294-93de-a26211f87ad7)
![Snipaste_2024-05-21_21-51-06](https://github.com/Ryujinx/Ryujinx/assets/95039251/9b11736f-832e-4cea-8745-da6e50c41d7e)

### Reproduction steps

Unable to render when running Bayonetta 3, white screen
![Snipaste_2024-05-21_21-50-44](https://github.com/Ryujinx/Ryujinx/assets/95039251/18be6c46-aecc-4294-93de-a26211f87ad7)
![Snipaste_2024-05-21_21-51-06](https://github.com/Ryujinx/Ryujinx/assets/95039251/9b11736f-832e-4cea-8745-da6e50c41d7e)

### Log file

[Ryujinx_1.1.1318_2024-05-21_21-48-58.log](https://github.com/Ryujinx/Ryujinx/files/15390799/Ryujinx_1.1.1318_2024-05-21_21-48-58.log)

### OS

WIN 11

### Ryujinx version

1.1.1318

### Game version

1.2.0

### CPU

i5-12600KF

### GPU

AMD Radeon RX 6750 GRE 12GB

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
Bayonetta 3 doesn't work currently with OpenGL, use Vulkan. In the future please refer to Discord for support.

**Comment by tiancaiqx** [comment]
I tried to set up Vulkan mode, but I couldn't recognize my graphics card and saved the settings.

從我的iPhone傳送

> MetrosexualGarbodor ***@***.***>於2024年5月21日 22:00寫道：
> 
> Bayonetta 3 doesn't work currently with OpenGL, use Vulkan. In the future please refer to Discord for support.
>
