### ISSUE TITLE
[Bug]GeForce Game Ready ver.552.44

### ISSUE THREAD

**Issue by Mario9699** [Ryujinx/Ryujinx#6850]
### Description of the issue

GeForce Game Ready ver.552.44 have problem

### Reproduction steps

In GeForce Game Ready ver.552.44,The game have slow

### Log file

[Ryujinx_1.1.1319_2024-05-23_06-39-24.log](https://github.com/Ryujinx/Ryujinx/files/15409797/Ryujinx_1.1.1319_2024-05-23_06-39-24.log)

### OS

Windows 10

### Ryujinx version

1.11319

### CPU

i5-8400

### GPU

NVIDIA GeForce GTX 1050

### RAM

16GB

### List of applied mods

[Ryujinx_1.1.1319_2024-05-23_06-39-24.log](https://github.com/Ryujinx/Ryujinx/files/15409797/Ryujinx_1.1.1319_2024-05-23_06-39-24.log)

**Comment by MetrosexualGarbodor** [comment]
My game not have slow. Cannot reproduce.
