### ISSUE TITLE
[Bug] Paper Mario: The Thousand-Year Door - Save Block completely black

### ISSUE THREAD

**Issue by tonyhoro** [Ryujinx/Ryujinx#6857]
### Description of the issue

All save blocks in the game are lacking its rainbow-colored animation, being all black with only the "S" being visible
![mario](https://github.com/Ryujinx/Ryujinx/assets/30053020/d4399324-ac6e-4974-a7fa-09b6d9c4436f)

### Reproduction steps

Just boot the game and go through the prologue until you reach Rogueport Town. The first save block is on the first area to the left of Mario.

### Log file

00:00:00.264 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.271 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.271 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.272 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.273 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.274 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.275 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2504
00:00:00.275 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.276 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.276 |I| Configuration LogValueChange: ScalingFilterLevel set to: 100
00:00:00.278 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.284 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.284 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.284 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.284 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.284 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.284 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.284 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.284 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.285 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.286 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.286 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.287 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.287 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.287 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.287 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.290 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.295 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1319
00:00:00.299 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.299 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz ; 12 logical
00:00:00.301 |N| Application Print: RAM: Total 15.9 GiB ; Available 7 GiB
00:00:00.303 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.304 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

Windows 11

### Ryujinx version

1.1.1320

### Game version

13

### CPU

i5-11400

### GPU

NVIDIA RTX 3060

### RAM

16GB

### List of applied mods

No mod applied.

### Additional context?

Seems to run fine on the final release of Yuzu.

**Comment by piplup55** [comment]
fixed by #6853

**Comment by mrhdog13** [comment]
Save block and Crystal shards are still black for me and I am on the latest release 1.1.1321 I use vulkan Nivdia gpu pls fix
