### ISSUE TITLE
[Bug][regression] amd logic op workaround crashes ryujinx with latest mesa

### ISSUE THREAD

**Issue by qqlow** [Ryujinx/Ryujinx#6861]
### Description of the issue

ryujinx crashes due to the amd workaround (#6852) with latest mesa, no crash in 1.1.1319

### Reproduction steps

run paper mario, ryu will crash on boot

### Log file

[Ryujinx_1.1.1320_2024-05-23_17-57-00.log](https://github.com/Ryujinx/Ryujinx/files/15419466/Ryujinx_1.1.1320_2024-05-23_17-57-00.log)

### OS

archlinux

### Ryujinx version

1.1.1320

### Game version

1.0

### CPU

6800u

### GPU

680m

### RAM

32

### Additional context?

mesa git as of now

**Comment by gdkchan** [comment]
AFAIK @piplup55 tested it on radv and it was fine?

**Comment by gdkchan** [comment]
I don't think this crash has anything to do with this change, if its crashing on boot, that is just something that happens randomly, although from my experience it stops happening after PPTC has been built.

**Comment by piplup55** [comment]
> AFAIK @piplup55 tested it on radv and it was fine?

i didn't test git

**Comment by piplup55** [comment]
please enable logs and post another log, the log you provided has logging disabled
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/2a6e68e5-7d28-4a08-a7fe-8cbb141e736a)

**Comment by piplup55** [comment]
can't confirm the issue on my end after building git, likely the random crash gdk mentioned i will wait for a log before closing the issue
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/ca0155f1-477f-431a-b849-f587d3cc3038)

**Comment by piplup55** [comment]
yeah this is just a random crash, it's not a regression

**Comment by GamerzHell9137** [comment]
> i get this with a 100% rate in 1320, dunno

If it was 1320 it would be related to 1320. You're getting random crashes. Also change to Host Unchecked in CPU settings.
