### ISSUE TITLE
[Bug] Octopath Traveler II — Crash after selecting character in new game

### ISSUE THREAD

**Issue by skyzyx** [Ryujinx/Ryujinx#6862]
### Description of the issue

When starting a new game of Octopath Traveler II (v1.0.2), you select your character, and then Ryujinx crashes as the game loads.

### Reproduction steps

https://github.com/Ryujinx/Ryujinx/assets/39447/4ef227d5-6a39-4723-bc53-11607632aaf1

### Log file

[Ryujinx_1.1.1320_2024-05-23_17-50-35.log](https://github.com/Ryujinx/Ryujinx/files/15425170/Ryujinx_1.1.1320_2024-05-23_17-50-35.log)

[ryujinx-crash.log](https://github.com/Ryujinx/Ryujinx/files/15425172/ryujinx-crash.log)

### OS

macOS 14.5.0

### Ryujinx version

1.1.1320

### Game version

1.0.2

### CPU

Apple M1 Max

### GPU

Apple M1 Max

### RAM

64 GB

### List of applied mods

None

**Comment by AcK77** [comment]
Log file show:
`ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

It could be a bad dump or a corrupted save data. Do a proper game dump, try to remove all old save data and start a new game. You can go to our discord if support needed. Thanks.
