### ISSUE TITLE
[Bug]The Switch Pro controller does not support scanning physical amiibo, but the Joy-Con controllers do. 

### ISSUE THREAD

**Issue by wzsx150** [Ryujinx/Ryujinx#6866]
### Description of the issue

The Switch Pro controller does not support scanning physical amiibo, but the Joy-Con controllers do. 
Please fix this issue and enable the Switch Pro controller to support scanning physical amiibo.

### Reproduction steps

1. Launch any game that supports Amiibo, such as The Legend of Zelda: Breath of the Wild, Super Mario Odyssey, etc.
2. In the game, activate the amiibo feature. When using the Switch Pro controller, it fails to scan physical amiibo.
3. However, if you perform the same operation with the Joy-Con, it can successfully scan physical amiibo.

### Log file

[Ryujinx_1.1.1321_2024-05-24_12-54-24.log](https://github.com/Ryujinx/Ryujinx/files/15427739/Ryujinx_1.1.1321_2024-05-24_12-54-24.log)

### OS

Win11

### Ryujinx version

new UI up to 1.1.1321

### Game version

x

### CPU

i5-12600KF

### GPU

RTX3070Ti

### RAM

32GB

**Comment by wzsx150** [comment]
When using the Switch Pro controller to scan physical amiibo, there is no response or prompt in the game, as if the amiibo was not touched at all.

**Comment by AcK77** [comment]
Scanning a real Amiibo isn’t supported at all, you can only use virtual amiibo.

I updated the amiibo issue #2122 to reflect that. This issue can be closed to avoid duplicated report.
