### ISSUE TITLE
[Bug] Paper Mario TTYD Closes Ryujinx on Launch

### ISSUE THREAD

**Issue by biolyeon** [Ryujinx/Ryujinx#6871]
### Description of the issue

While testing Ryujinx and Yuzu for TTYD, I've been unable to launch TTYD properly on my PC and steam deck. Yuzu has had no issues as of now, but clicking TTYD on Ryujinx will launch the black screen to start loading the game, and then immediately crash the emulator.

I have the log file available to send (attached below)
[Ryujinx_1.1.1321_2024-05-24_22-45-07.log](https://github.com/Ryujinx/Ryujinx/files/15441298/Ryujinx_1.1.1321_2024-05-24_22-45-07.log)

I am on FW 18.0.0 with latest prod_keys for 18.0 as well. All other games that I have are working as intended so it's currently just TTYD.

### Reproduction steps

This can be recreated everytime I try to launch the game, with or without mods. I have the 60FPS and text advanced mods and they don't impact the status of this error. Changing between Vulkan/OpenGL, changing audio settings, disabling FS Integrity Check all haven't changed this.

### Log file

[Ryujinx_1.1.1321_2024-05-24_22-45-07.log](https://github.com/Ryujinx/Ryujinx/files/15441300/Ryujinx_1.1.1321_2024-05-24_22-45-07.log)

### OS

Windows 10

### Ryujinx version

1.1.1321

### Game version

1.0.0

### CPU

Ryzen 7 3700X

### GPU

NVIDIA RTX 4080 SUPER

### RAM

64GB

### List of applied mods

60FPS Mod
Text Speed Mod
4K GFX Mod

**Comment by gdkchan** [comment]
The log indicates an error loading one of the cheats you have.

**Comment by biolyeon** [comment]
You are right. I thought I tested it while it was disabled but it was specifically the 60fps mod (other 2 mods are working with no issues).
