### ISSUE TITLE
Unable to launch any games since updating

### ISSUE THREAD

**Issue by Bobiscus** [Ryujinx/Ryujinx#6875]
### Description of the issue

I have not used ryujinx in a few months, but after launching it and updating, all of my games crash ryujinx when I attempt to launch them.

### Reproduction steps

Attempting to load a game through either the library GUI or the "load application from file" option cause a crash.

### Log file

[Ryujinx_1.1.1322_2024-05-25_21-31-56.log](https://github.com/Ryujinx/Ryujinx/files/15445728/Ryujinx_1.1.1322_2024-05-25_21-31-56.log)

### OS

Windows 11

### Ryujinx version

1.1.1322

### CPU

Ryzen 9 5900X

### GPU

NVIDIA RTX 3070TI

### RAM

32GB

**Comment by piplup55** [comment]
```
File Open Ryujinx Folder
--\bis
---\system
----\Contents
-----\registered
```
Delete all the contents of the directory.
Open Ryujinx and re-install the Firmware.

**Comment by Bobiscus** [comment]
Thank you. It works now.
