### ISSUE TITLE
[Bug] Paper Mario TTYD Creepy Steeple Crash on Steam Deck

### ISSUE THREAD

**Issue by jcr-vie** [Ryujinx/Ryujinx#6876]
### Description of the issue

On Chapter 4 at Creepy Steeple, a crash occurs in an area that is required for story progression, effectively locking me out of my current save file. This error occurred using the recent patch that fixed save box and reflective textures like coins and crystal stars from appearing black and textureless. I am using a Steam Deck.

### Reproduction steps

On Chapter 4 at Creepy Steeple, once you open the box in the basement sub-area that holds 200 boos in it, you are required to enter a dialogue in the main area with a boo. The only way to progress through the area and advance the game is to answer "No" when asked by the npc if you're going to hurt it. Upon answering no, the game spawns hundreds of boo npcs that then circle the area in a clockwise fashion. Before the boos can begin spinning around the area, the frame rate grinds to a halt and then proceeds to crash ryujinx. Picture provided is from a YouTube video of the sequence for reference.
![ksnip_20240525-225610](https://github.com/Ryujinx/Ryujinx/assets/170842762/eab8d9ed-3ce8-4083-a2e9-126a83e29b98)
__

### Log file

[Ryujinx_1.1.0+1f40537_2024-05-25_22-33-06.log](https://github.com/Ryujinx/Ryujinx/files/15445938/Ryujinx_1.1.0%2B1f40537_2024-05-25_22-33-06.log)

### OS

Arch Linux (Steam OS)

### Ryujinx version

1.1.0+1f40537-linux_x64

### Game version

1.0.0

### CPU

AMD Zen 2

### GPU

8 RDNA 2 CUs

### RAM

16 GB LPDDR5 

### List of applied mods

N/A

**Comment by piplup55** [comment]
you are running out of vram, you can try and enable texture recompression and you shouldn't be opening issues using a PR build
