### ISSUE TITLE
[Bug] Paper Mario: The Thousand Year Door - All Crystal Stars appear completely black.

### ISSUE THREAD

**Issue by AZthemute** [Ryujinx/Ryujinx#6878]
### Description of the issue

Whenever a Crystal Star shows in the overworld or battle, it appears completely black instead of having any colour.

### Reproduction steps

1. Find a crystal star in the overworld or in a battle, it will appear completely black. So far, this has happened for every single instance of a crystal star appearing.

https://github.com/Ryujinx/Ryujinx/assets/104761702/3818eeca-5349-4157-986b-c1bd230b41b5

Apologies for the lack of audio; I muted it due to background noise.

I am not sure if this is related, but save blocks also appear completely black.
![image](https://github.com/Ryujinx/Ryujinx/assets/104761702/7ecfc3a6-2000-40dd-823e-5c984e5478d2)

### Log file

[Ryujinx_1.1.1322_2024-05-26_10-45-03.log](https://github.com/Ryujinx/Ryujinx/files/15447192/Ryujinx_1.1.1322_2024-05-26_10-45-03.log)
This session ended due to an emulator crash when loading a new room. I'm not going to report this officially as it is inconsistent and seemingly not possible to reproduce, and it could very well just be weak hardware, but if it's a known issue then please let me know the solution.

### OS

Windows 10

### Ryujinx version

1.1.1321 - 1.1.1322

### Game version

1.0.0

### CPU

i5-9400F

### GPU

Geforce GTX 1660 SUPER

### RAM

16 GB

### List of applied mods

None.

**Comment by ParronnaProjects** [comment]
look at that : [#6853](https://github.com/Ryujinx/Ryujinx/pull/6853)
