### ISSUE TITLE
[Bug]MLB The Show 24 crash when Vulkan 

### ISSUE THREAD

**Issue by tw94015** [Ryujinx/Ryujinx#6884]
### Description of the issue

MLB The Show 24 runs smoothly using OpenGL, but player eyes cannot be rendered. I also tried running it with Vulkan, but it crashes every time I enter a game. This is a shame and I hope Vulkan support for MLB The Show will be fixed as soon as possible. 

### Reproduction steps

MLB The Show 24 runs smoothly using OpenGL, but player eyes cannot be rendered. I also tried running it with Vulkan, but it crashes every time I enter a game. This is a shame and I hope Vulkan support for MLB The Show will be fixed as soon as possible. 

### Log file

[Ryujinx_1.1.1325_2024-05-27_13-26-30.log](https://github.com/Ryujinx/Ryujinx/files/15451283/Ryujinx_1.1.1325_2024-05-27_13-26-30.log)

### OS

Windows10

### Ryujinx version

1.1.1325

### Game version

1.0.8

### CPU

R5-7500F

### GPU

NVIDIA RTX 4060 Ti

### RAM

32GB

**Comment by MutantAura** [comment]
File game compatibility reports at their respective page here: https://github.com/Ryujinx/Ryujinx-Games-List/issues
