### ISSUE TITLE
[Bug] TTYD-Remake Crash after going to the Harbor

### ISSUE THREAD

**Issue by CaioGS06** [Ryujinx/Ryujinx#6891]
### Description of the issue

After loading the game on the latest version of Ryujinx (1.1.1325) on the Saveblock of the Rogueport main part (the one with the gallows), and then going to the harbor, the game just crashes. Note that in the previous version, the one where the Saveblocks and coins graphics are still not fixed, this error crash does not occur, so since there's no crash in this version I'm currently not going to play on the newer version.

### Reproduction steps

After going from the plaza to the harbor, when the game tries to load it, it crashes, issuing an exception at Ryujinx.Graphics.Vulkan.VulkanException: "ErrorOutOfDeviceMemory".

### Log file

[Ryujinx_1.1.1325_2024-05-27_01-21-04.log](https://github.com/Ryujinx/Ryujinx/files/15464168/Ryujinx_1.1.1325_2024-05-27_01-21-04.log)

### OS

Windows 10

### Ryujinx version

1.1.1325

### Game version

1.0.0

### CPU

Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz

### GPU

NVIDIA GeForce GT 1030 

### RAM

8GB

**Comment by GamerzHell9137** [comment]
Your GPU has 2 GB VRAM, its not enough to emulate the game. Most Switch games ask for at least 4 GB VRAM.
You got couple of options:
1. Get a new GPU
2. Change to OpenGL and play on that
3. Enable and see if it works with Texture Recompression on Vulkan, if not go back to option 2

**Comment by MutantAura** [comment]
Closing as a won't fix. 2GB of VRAM is not viable.
