### ISSUE TITLE
[Bug] Zelda BOTW - Game crashes when entering cut scene at temple of time to receive paraglider from old man

### ISSUE THREAD

**Issue by alexballvideos** [Ryujinx/Ryujinx#6892]
### Description of the issue

Load a game save at temple of time to see old man on the rooftop of the temple of time, after completing all goals to get the Paraglider. When cut scene begins Ryujinx crashes.

Log file detail (I think)
Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### Reproduction steps

Load a game save at temple of time to see old man on the roof of the temple of time, after completing all goals to get the Paraglider. When cut scene begins Ryujinx crashes.

### Log file

[Ryujinx_1.1.1325_2024-05-28_16-32-32.log](https://github.com/Ryujinx/Ryujinx/files/15465063/Ryujinx_1.1.1325_2024-05-28_16-32-32.log)

### OS

OS X Sonoma 14.5

### Ryujinx version

1.1.1325

### Game version

1.6.0

### CPU

M3 12 core

### GPU

M3 MAX 30 core GPU

### RAM

36GB

### List of applied mods

None

### Additional context?

Game has played fine from the beginning until this point, receiving paraglider from old man and cannot proceed past it. Has happen for multiple versions of Ryujinx in the past month since starting a play-through on Mac. Firmware Version 18.0

**Comment by MutantAura** [comment]
Your ROM is corrupt. Redump it from your Switch.
