### ISSUE TITLE
[Bug] Every game crashes when I open it.

### ISSUE THREAD

**Issue by GoldenGlitch22** [Ryujinx/Ryujinx#6894]
### Description of the issue

i open a game and the emulator crashes just after loading shaders.

### Reproduction steps

Open the emulator
Open any game

### Log file

[Ryujinx_1.1.1325_2024-05-28_21-03-01.log](https://github.com/Ryujinx/Ryujinx/files/15475549/Ryujinx_1.1.1325_2024-05-28_21-03-01.log)
[Ryujinx_1.1.1325_2024-05-28_20-59-16.log](https://github.com/Ryujinx/Ryujinx/files/15475553/Ryujinx_1.1.1325_2024-05-28_20-59-16.log)

### OS

Windows 11

### Ryujinx version

1.1.1325

### Game version

1.3.2, 1.0.0

### CPU

i5-10300H

### GPU

NVIDIA RTX 2060

### RAM

16GB

### Additional context?

This started happening as soon as I loaded 1.3.2 Pokemon Shield

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use Discord for help.
