### ISSUE TITLE
Keeps crashing mid game

### ISSUE THREAD

**Issue by Chowderrrr** [Ryujinx/Ryujinx#6902]
### Description of the issue

My game keeps crashing 10-15 minutes after launching it

### Reproduction steps

Start up animal crossing and play it for about 10-20 minutes

### Log file

[Ryujinx_1.1.1325_2024-06-01_05-13-43.log](https://github.com/user-attachments/files/15521233/Ryujinx_1.1.1325_2024-06-01_05-13-43.log)

### OS

Mac OSsonoma

### Ryujinx version

18.0.0

### Game version

1.0.0

### CPU

Apple M1 Pro

### RAM

16GB

### List of applied mods

None

**Comment by piplup55** [comment]
The crash is because the hypervisor is unstable in Animal Crossing. Disable it to play that game. in future join the [discord](https://discord.gg/ryujinx) for support
