### ISSUE TITLE
[Bug] Pokemon Scarlet and Violet instantly crashing when opening with mod

### ISSUE THREAD

**Issue by luhfaris** [Ryujinx/Ryujinx#6917]
### Description of the issue

Pretty much the title, I made a randomiser for Pokemon Scarlet and Violet and everytime I use the mod, it crashes before even opening. 

### Reproduction steps

I booted up Ryujinx 1.1.1330, 
Added my mod which consisted of only the RomFS folder into the mod directory for the game
Loaded my .NSP file of Pokemon Scarlet which works WITHOUT the mod
Crashes upon opening

### Log file

00:00:00.262 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.269 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.270 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.270 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.271 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.272 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.273 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1F06
00:00:00.273 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.274 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.274 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.276 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.281 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.281 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.281 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.281 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.281 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.281 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.281 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.281 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.281 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.282 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.282 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.283 |I| Configuration LogValueChange: MemoryManagerMode set to: SoftwarePageTable
00:00:00.283 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.283 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.283 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.286 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.290 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1330
00:00:00.294 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.294 |N| Application Print: CPU: AMD Ryzen 7 3700X 8-Core Processor ; 16 logical
00:00:00.296 |N| Application Print: RAM: Total 15.9 GiB ; Available 8.7 GiB
00:00:00.298 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.299 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.134 |I| Gpu : Backend Threading (Auto): True
00:00:00.466 |N| Application LoadGuestApplication: Using Firmware Version: 8.0.1
00:00:00.466 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.494 |I| ModLoader QueryContentsDir: Searching mods for Application 0100A3D008C5C000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.501 |I| ModLoader AddModsFromDirectory: Found enabled mod '0100a3d008c5c000' [R]
00:00:00.502 |I| ModLoader QueryContentsDir: Searching mods for Application 0100A3D008C5C000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.502 |I| ModLoader AddModsFromDirectory: Found disabled mod '0100a3d008c5c000' [R]
00:00:00.505 |I| Loader Load: Loading rtld...
00:00:00.510 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.510 |I| Loader Load: Loading main...
00:00:00.798 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\titan\v_1_0_0\rom_build\programs\prog\app\msvc\main_app\NX64\Release\main_app.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-13_3_5-Release
                   SDK MW+Nintendo+NintendoSDK_gRPC_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_OpenSSL_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_NPLN-1_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_Google_APIs_For_NPLN-1_4_1-Release
                   SDK MW+Nintendo+PiaCommon-6_20_1
                   SDK MW+Nintendo+Pia-6_20_1
                   SDK MW+Nintendo+PiaLocal-6_20_1
                   SDK MW+Nintendo+PiaLan-6_20_1
                   SDK MW+Nintendo+PiaReckoning-6_20_1
                   SDK MW+Nintendo+PiaSession-6_20_1
                   SDK MW+Nintendo+PiaTransport-6_20_1
                   SDK MW+Nintendo+PiaNpln-6_20_1
                   SDK MW+NINTENDO+nlib_LZ4-22_0201
                   SDK MW+Nintendo+NintendoWare_Font-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_G3d-13_3_5-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-13_3_5-Release
                   SDK MW+Microsoft+Havok_AI-2021_1
00:00:00.798 |I| Loader Load: Loading subsdk0...
00:00:00.820 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-13_3_5-Release
00:00:00.820 |I| Loader Load: Loading sdk...
00:00:00.870 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 13.3.5
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_5-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_5-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_5-Release
00:00:00.954 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.986 |I| Ptc Load: Loaded Profiling Info (size: 124926 bytes, profiled functions: 40398).
00:00:00.990 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.991 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.014 |I| Loader LoadNsos: Loading image 2 at 0x000000000c8f9000...
00:00:01.016 |I| Loader LoadNsos: Loading image 3 at 0x000000000cf93000...
00:00:01.024 |I| ModLoader LoadCheats: Build ids found for application 0100A3D008C5C000:
    567CDD4C5251494C5CD70822E3CCC740C190C2B2000000000000000000000000
    CA44E7DD62E61A2A4E8889B3319AE173375770FD000000000000000000000000
    D0F13015E5BADF2243D60A2BC9B978DDDBA80608000000000000000000000000
    3644A6760469451CABC99F00C540ACC2A64AEE41000000000000000000000000
00:00:01.027 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Application 0100A3D008C5C000
00:00:01.067 |I| ModLoader ApplyRomFsMods: Replaced 40 file(s) over 1 mod(s). Processing base storage...
00:00:01.071 |I| ModLoader ApplyRomFsMods: Building new RomFS...
00:00:01.073 |I| ModLoader ApplyRomFsMods: Using modded RomFS
00:00:01.074 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.130 |I| Loader Start: Application Loaded: Pokémon Scarlet v1.0.0 [0100a3d008c5c000] [64-bit]
00:00:01.154 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.166 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:01.493 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2060 SUPER (Vulkan v1.3.242, Driver v537.42.0.0)
00:00:01.501 |I| GPU.MainThread Gpu LoadShaders: Loading 83 shaders from the cache...
00:00:01.669 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:01.682 |I| HLE.GuestThread.46 Ptc MakeAndSaveTranslations: 0 of 40398 functions translated | Thread count: 15
00:00:30.719 |I| HLE.GuestThread.46 Ptc MakeAndSaveTranslations: 40398 of 40398 functions translated | Thread count: 15 in 29.0360884 s
00:00:30.873 |S| HLE.OsThread.47 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:30.885 |S| HLE.OsThread.47 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:30.886 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:30.886 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:30.898 |S| HLE.OsThread.47 ServicePctl Initialize: Stubbed. 
00:00:31.013 |W| HLE.GuestThread.46 KernelSvc : MapPhysicalMemory() = LimitReached
00:00:31.024 |S| HLE.OsThread.47 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:31.026 |S| HLE.OsThread.3 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:31.031 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:31.031 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:31.145 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:31.147 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:31.162 |S| HLE.OsThread.4 ServiceNv FinishInitialize: Stubbed. 
00:00:31.174 |S| HLE.OsThread.4 ServiceNv InitializeEx: Stubbed. 
00:00:31.188 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:31.193 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:31.193 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:31.200 |W| HLE.GuestThread.46 KernelSvc : MapPhysicalMemory() = OutOfMemory
00:00:31.201 |W| HLE.GuestThread.46 KernelSvc : MapPhysicalMemory() = OutOfMemory
00:00:31.232 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 30s
    ProgramName: main_app
    Thread: MainThread
    Message: Pure virtual function called!

00:00:31.240 |I| HLE.OsThread.47 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)).
00:00:31.437 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Pokémon Scarlet, PID: 127
   0x000000000d0fe8e8	sdk:0x16b8e8	
   0x000000000d0fea14	sdk:0x16ba14	
   0x000000000d0ff8f4	sdk:0x16c8f4	
   0x000000000d543dfc	sdk:0x5b0dfc	
   0x000000000d4fc704	sdk:0x569704	
   0x000000000d4eb408	sdk:0x558408	
   0x000000000d4eaec4	sdk:0x557ec4	
   0x000000000d44aca8	sdk:0x4b7ca8	
   0x000000000951e5a4	main:0x101a5a4	
   0x000000000951d918	main:0x1019918	
   0x000000000951d76c	main:0x101976c	
   0x000000000951d62c	main:0x101962c	
   0x00000000098fdce8	main:0x13f9ce8	
   0x00000000098fd880	main:0x13f9880	
   0x00000000098f83bc	main:0x13f43bc	
   0x00000000098f8308	main:0x13f4308	
   0x0000000009009a80	main:0xb05a80	
   0x00000000090027cc	main:0xafe7cc	
   0x0000000008fa56b8	main:0xaa16b8	
   0x000000000993fe54	main:0x143be54	
   0x000000000993dfec	main:0x1439fec	nnMain:0x00ac
   0x000000000d26efe4	sdk:0x2dbfe4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000085000d4	rtld:0x00d4	

00:00:31.438 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000049f0308208 (SP:-0x01a8)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000000cf93000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000cd8910
	X[11]:	0x0000000000008000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000002
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000000d100120 (sdk:0x16d120)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000dc6b910
	X[18]:	0x0000000000000000
	X[19]:	0x00000049f0308208 (SP:-0x01a8)
	X[20]:	0x0000000000000000
	X[21]:	0x000000000da13ab1
	X[22]:	0x000000000da13ab1
	X[23]:	0x0000000000000000
	X[24]:	0x000000000da13ab1
	X[25]:	0x00000049f03081e8 (SP:-0x0188)
	X[26]:	0x000000000d0fea14 (sdk:0x16ba14)	=> 
	X[27]:	0x000000000da13ab1
	X[28]:	0x00000015c1b126e0
	FP:	0x00000049f0308060 (SP)
	LR:	0x000000000d100138 (sdk:0x16d138)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x00000049f0308060 (SP)
	PC:	0x000000000d360350 (sdk:0x3cd350)	=> 

00:00:31.439 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.48 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.51 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.49 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.53 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.55 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.57 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.56 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.439 |W| HLE.GuestThread.58 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:31.483 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\obj\Release\net8.0\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\obj\Release\net8.0\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1330

### Game version

3.01

### CPU

AMD Ryzen 7 3700X

### GPU

NVIDIA GeForce RTX 2060 SUPER

### RAM

16GB

### List of applied mods

Scarlet-and-Violet-Randomizer-Main

**Comment by MaxMadcc** [comment]
00:00:31.240 |I| HLE.OsThread.47 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)). 
It is key reason.
Try to Disable the memory expansion/developer hack. It's in Options > Settings > System > Hacks.

**Comment by Chaplu** [comment]
> 00:00:31.240 |I| HLE.OsThread.47 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)). It is key reason.
> 
> Look like **ExpandRam** is True. Try to Disable the memory expansion/developer hack. It's in Options > Settings > System > Hacks.

I have the same problem and I don't have the alternative memory hack enabled

**Comment by MetrosexualGarbodor** [comment]
@luhfaris your game is crashing because you're trying to run a romfs mod that is most likely not for version 1.0 of the game.

@Chaplu if you had the same problem, it wouldn't have a different cause. Join Discord for general support.
