### ISSUE TITLE
[Bug] IndexOutOfRangeException when running Vulkan with dGPU on Fedora 40

### ISSUE THREAD

**Issue by WizardMike08** [Ryujinx/Ryujinx#6919]
### Description of the issue

Running Ryujinx with Vulkan and dGPU cause it to crash immediately after trying to launch the game. However OpenGL or Vulkan with iGPU runs normally. I have also tried running Ryujinx with Vulkan dGPU on Windows 11 and it works without any issues.

### Reproduction steps

Launch any game with Vulkan backend and dedicated GPU selected

### Log file

[Ryujinx_1.1.1330_2024-06-06_21-31-19.log](https://github.com/user-attachments/files/15629583/Ryujinx_1.1.1330_2024-06-06_21-31-19.log)
[Ryujinx_1.1.1330_2024-06-06_22-12-54.log](https://github.com/user-attachments/files/15649728/Ryujinx_1.1.1330_2024-06-06_22-12-54.log)

### OS

Fedora KDE Plasma 40

### Ryujinx version

1.1.1330

### CPU

i7-13700HX

### GPU

NVIDIA RTX 4070 Laptop GPU

### RAM

24GB

### Additional context?

Device model is Lenovo Legion Pro 5, dual booted with Windows 11 and Fedora KDE 40. I suspected it has something to do with NVIDIA drivers, currently using version 550.78 as of writing this.

**Comment by WizardMike08** [comment]
Update:
I have concluded the issue is related to the Flatpak version of Ryujinx. After redownloading through the official website, it seems to be working fine for now. Will close this soon after trying a few more sessions.

**Comment by WizardMike08** [comment]
So far no crashes reoccurring, closing this issue

**Comment by playday3008** [comment]
Same happened, was working tho (even same version), until now.

- Ryujinx 1.1.1340 (Flatpak)
- Fedora 40
- dGPU: NVIDIA RTX 3050Ti (works on iGPU)

Temporarely using .tar.gz build from a site

[Ryujinx_1.1.1340_2024-06-28_02-03-57.log](https://github.com/user-attachments/files/16022420/Ryujinx_1.1.1340_2024-06-28_02-03-57.log)

**Comment by playday3008** [comment]
Clean reinstall helped, but still wondering what happened
