### ISSUE TITLE
[Bug] Unable To Choose Files/Directories on Linux

### ISSUE THREAD

**Issue by Duder963** [Ryujinx/Ryujinx#6922]
### Description of the issue

On attempting to select any option which would lead to choosing a file or directory, nothing happens

### Reproduction steps

1) Download Ryujinx
2) Select Tools > Install Firmware > Install a firmware from XCI or ZIP
3) Nothing happens

### Log file

00:00:00.241 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.248 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.248 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.249 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.250 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.251 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.251 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.252 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.252 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.253 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.254 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.260 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.260 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.260 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.260 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.260 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.260 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.260 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.260 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.260 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.261 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.261 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.262 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.262 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.262 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.262 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.265 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.271 |W| Application GetActualScaleFactor: Couldn't determine monitor DPI: Wayland not yet supported
00:00:00.271 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1330
00:00:00.281 |N| Application Print: Operating System: Arch Linux (X64)
00:00:00.281 |N| Application Print: CPU: AMD Ryzen 5 5600 6-Core Processor ; 12 logical
00:00:00.283 |N| Application Print: RAM: Total 15.5 GiB ; Available 7.1 GiB
00:00:00.285 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.285 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

Arch Linux

### Ryujinx version

1.1.1330

### CPU

AMD Ryzen 5 5600

### GPU

NVIDIA GeForce GTX 1080 Ti

### RAM

16GB

**Comment by TSRBerry** [comment]
Make sure you have a desktop portal installed: https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Comment by Duder963** [comment]
I have a desktop portal installed and everything works fine on other programs, but not Ryujinx

**Comment by Duder963** [comment]
Resolved. Did some more fiddling around and it turns out even though I had a desktop portal installed it wasn't quite working right
