### ISSUE TITLE
Ryujinx crashes on MacBook 15" (2013) running macOS Sonoma

### ISSUE THREAD

**Issue by Joeyblaa** [Ryujinx/Ryujinx#6923]
### Description of the issue

Hello Ryujinx Team,

I am unable to get Ryujinx to run on my MacBook 15" from 2013. My MacBook is running macOS Sonoma thanks to the OpenCore Legacy Patcher. It should support Metal 2. Typically, Ryujinx crashes immediately when I try to start a game. However, after tweaking some settings in MoltenVK, I can at least hear the game's audio, but the screen remains completely black.

Here are the configurations I activated to prevent the immediate crash:

export MVK_CONFIG_PRELOAD_METAL_RUNTIME=1
export MVK_CONFIG_LOG_LEVEL=3
export MVK_CONFIG_PERFORMANCE_LOGGING=0
export MVK_CONFIG_RESUME_LOST_DEVICE=1
export MVK_CONFIG_SHADER_CONVERSION_FLUSH_RATE=1
export MVK_CONFIG_SHADER_CONVERSION_FLUSH_ON_QUEUE_SUBMIT=0
export MVK_CONFIG_SEMAPHORE_USE_MIN_SPEC=1
export MVK_CONFIG_FENCE_WAIT_THRESHOLD=1000
export MVK_CONFIG_USE_HOMOGENEOUS_DEPTH=1
export MVK_CONFIG_FULL_SCREEN_LAYER=1
export MVK_CONFIG_SURFACE_PRESENT_MODE=2
export MVK_CONFIG_DEBUG_LAYER_VALIDATION=1
export MVK_CONFIG_USE_GUARDED_IMAGE_TRANSACTIONS=1
export MVK_CONFIG_PREFILL_TEXTURES=1
export MVK_CONFIG_ENABLE_INSTANCING=1
export MVK_CONFIG_USE_PRIVATE_MEM_POOLS=1
export MVK_CONFIG_PREFER_UNIFIED_MEMORY=1
export MVK_CONFIG_MTL_BUFFER_STORAGE_MODE=2
export MVK_CONFIG_USE_CALCULATED_EXTENTS=1
export MVK_CONFIG_GPU_TIMEOUT=1000000
export MVK_CONFIG_PREEMPTION_ENABLE=1
export MVK_CONFIG_SUPPORT_INDIRECT_DRAW_BUFFER=1
export MVK_CONFIG_SUPPORT_MULTIVIEWPORT=1
export MVK_CONFIG_SUPPORT_CONFIGURABLE_COMPUTE_QUEUES=1
export MVK_CONFIG_SUPPORT_CONFIGURABLE_TRANSFER_QUEUES=1
export MVK_CONFIG_SUPPORT_BLIT_ENCODER=1
export MVK_CONFIG_SUPPORT_METAL_HIGH_POWER=1
export MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE=1
export MVK_ALLOW_METAL_FENCES=1
export MVK_ALLOW_METAL_COMMAND_BUFFERS=1
export MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1
export MVK_CONFIG_USE_COMMAND_BUFFER_PRECISE_PIPELINE_BARRIERS=1
export MVK_CONFIG_PREFILL_METADATA=1
export MVK_CONFIG_FAST_MATH_ENABLED=1
export MVK_CONFIG_CHECK_FOR_MOLTENVK_UPDATES=0
export MVK_CONFIG_DEACTIVATE_COMPILETIME_OBFUSCATION=1
export MVK_CONFIG_DEBUG_SHADER_VALIDATION=1
export MVK_CONFIG_SHADER_CONVERSION_DEBUG_INFO=1

ulimit -n 65535
ulimit -u 4096

I would be thrilled if I could play Switch games on my Mac. Even if it doesn't work out, I want to thank you for your amazing work. I'm a big fan!

### Reproduction steps

Every time I try to start the game

### Log file

00:00:08.925 |S| HLE.OsThread.4 ServiceNv SetErrorNotifier: Stubbed.
00:00:22.792 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkDeviceWaitIdle CommandBuffer on Queue 0-0" execution failed (code 9): Invalid Resource (00000009:kIOAccelCommandBufferCallbackErrorInvalidResource)
00:00:23.045 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 1): Internal Error (00000001:Internal Error)
00:01:46.089 |E| .NET TP Worker [mvk-trace] vkMapMemory() [139523/84556/]
00:01:46.089 |E| .NET TP Worker [mvk-trace] vkBindBufferMemory() [139523/84556/]
00:01:46.089 |E| .NET TP Worker [mvk-trace] vkCmdPipelineBarrier() [139523/84556/]
00:01:46.089 |E| .NET TP Worker [mvk-trace] vkCmdCopyBuffer() [139523/84556/]
00:01:46.089 |E| .NET TP Worker [mvk-trace] vkCmdPipelineBarrier() [139523/84556/]
00:01:46.303 |E| .NET TP Worker [mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
00:01:46.303 |E| .NET TP Worker program_source:151:151: error: cannot assign resource locations to 'spvDescriptorSet2'
00:01:46.303 |E| .NET TP Worker vertex main0_out main0(main0_in in [[stage_in]], constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]], constant spvDescriptorSetBuffer2& spvDescriptorSet2 [[buffer(2)]], constant uint* spvSwizzleConstants [[buffer(14)]])
00:01:46.303 |E| .NET TP Worker                                                                                                                                                       ^
00:01:46.303 |E| .NET TP Worker program_source:109:22: note: attribute 'id' set location to 0, but minimum is 1
00:01:46.303 |E| .NET TP Worker     texture2d<float> vp_t_tcb_18 [[id(0)]];
00:01:46.303 |E| .NET TP Worker                      ^             ~~~~~
00:01:46.303 |E| .NET TP Worker .
00:01:46.303 |E| .NET TP Worker [mvk-error] VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline. See previous logged error.
00:01:46.303 |E| .NET TP Worker Gpu : Background Compilation failed: Unexpected API error "ErrorInvalidShaderNV".
00:01:46.481 |E| .NET TP Worker [mvk-trace] vkCmdPipelineBarrier() [139523/84556/]
00:01:46.481 |E| .NET TP Worker [mvk-trace] vkCreateBuffer() [139523/84556/]
00:01:46.481 |E| .NET TP Worker [mvk-trace] vkGetBufferMemoryRequirements() [139523/84556/]
00:01:46.481 |E| .NET TP Worker [mvk-trace] vkAllocateMemory() [139523/84556/]
00:01:46.481 |E| .NET TP Worker [mvk-trace] vkMapMemory() [139523/84556/]
00:01:46.481 |E| .NET TP Worker [mvk-trace] vkBindBufferMemory() [139523/84556/]
00:01:46.507 |E| .NET TP Worker [mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
00:01:46.507 |E| .NET TP Worker Unhandled constant.
00:01:46.508 |E| .NET TP Worker Gpu : Background Compilation failed: Unexpected API error "ErrorInitializationFailed".
00:01:46.508 |E| .NET TP Worker [mvk-trace] vkCreateImage() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkCmdDrawIndexed() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkCmdBindIndexBuffer() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkCmdBindVertexBuffers() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkUpdateDescriptorSetWithTemplate() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkCmdBindDescriptorSets() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkUpdateDescriptorSetWithTemplate() [139523/84556/]
00:01:47.234 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 1): Internal Error (00000001:Internal Error)
00:01:47.234 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 1): Internal Error (00000001:Internal Error)
00:01:47.234 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 1): Internal Error (00000001:Internal Error)
00:01:47.234 |E| .NET TP Worker [mvk-trace] vkCmdBindDescriptorSets() [139523/84556/]

### OS

macOS Sonoma 14.4.1

### Ryujinx version

1.1.1330

### Game version

1.0

### CPU

Quad-Core Intel Core i7 2,4 GHz

### GPU

Nvidia GT650m

### RAM

16 GB 1600mhz

### List of applied mods

no mods

**Comment by MetrosexualGarbodor** [comment]
There are no plans to support Intel Macs, the Apple drivers for these GPUs are severely outdated, and it's simply not realistic to develop for hardware several years older and weaker than the console being emulated. Therefore, we suggest installing Linux or Windows.
