### ISSUE TITLE
Known Issues in Ryujinx 1.1.1330 [Bug]

### ISSUE THREAD

**Issue by KrowofAgony** [Ryujinx/Ryujinx#6929]
### Description of the issue

**These are the known issues in Ryujinx 1.1.1330:**

### The Legend of Zelda: Link's Awakening

_* Constantly crashes at certain parts: (Mysterious Forest, South of Mabe Village, etc.)
* Owl sometimes causes it to crash
* Treasure Chests sometime cause it to crash
* Runs on Vulkan ONLY_

### Sonic Origins:

* Constantly crashes at loading
* Sometimes crashes before Special Stage
* Special Stage often crashes playing Sonic 1
* Other games are uncertain in this collection
* Found to run best on Vulkan (can run on OpenGL, but island may not appear correctly)

### Sonic Colors Ultimate:

_* Slow startup
* Flashing different colors during load time (if this is normal, then it is a no-issue)_
* ![Ryujinx Sonic Colors Ultimate](https://github.com/Ryujinx/Ryujinx/assets/7153059/3479ed78-3980-4929-bb86-ce97e361bdea)

_* Sometimes crashes during certain levels
* Can either run on Vulkan or OpenGL_

### Turrican Anthology Vol 1 - 2:

_* Game crashes at startup
* Sometimes white loading screen before loading game_

### Controller:

_* Sometimes does not detect my controller
* Have to set my settings every time I load the emulator_
* ![Ryujinx Controller](https://github.com/Ryujinx/Ryujinx/assets/7153059/cd6c2079-3e9c-44ca-b4e6-084f52baafb8)

### Graphics:

_* Have to input with Vulkan Backend to get certain games to work (i.e., Sonic Colors Ultimate, Link's Awakening, Sonic Origins, etc.)
* OpenGL causes a black screen to input on Intel Graphics HD 500 - 520_
* ![Ryujinx Graphics](https://github.com/Ryujinx/Ryujinx/assets/7153059/781b2aaa-e922-4f42-bb9b-cea5980317bf)

There are others that may have encountered similar issues.

### Reproduction steps

I would either go to the following:

* Mess with the Graphics tab
* Mess with the Input tab
* At least set the backend to either OpenGL or Vulkan
* Attempt to load any game by double-clicking

### Log file

[Ryujinx_1.1.1330_2024-06-10_20-59-37.log](https://github.com/user-attachments/files/15780820/Ryujinx_1.1.1330_2024-06-10_20-59-37.log)
[Ryujinx_1.1.1330_2024-06-10_21-01-45.log](https://github.com/user-attachments/files/15780821/Ryujinx_1.1.1330_2024-06-10_21-01-45.log)
[Ryujinx_1.1.1330_2024-06-10_21-02-08 02.log](https://github.com/user-attachments/files/15781267/Ryujinx_1.1.1330_2024-06-10_21-02-08.02.log)
[Ryujinx_1.1.1330_2024-06-10_21-02-08 03.log](https://github.com/user-attachments/files/15781268/Ryujinx_1.1.1330_2024-06-10_21-02-08.03.log)
[Ryujinx_1.1.1330_2024-06-10_21-02-08.log](https://github.com/user-attachments/files/15781269/Ryujinx_1.1.1330_2024-06-10_21-02-08.log)

### OS

Windows 10

### Ryujinx version

1.1.1330

### CPU

Intel Core i5-6200U @ 2.30GHz

### GPU

Intel HD Graphics 500 - 520

### RAM

32 GB SO-DIMM

### List of applied mods

The applied mod is _Agumon's Awakening_ by **Hallow**. [https://gamebanana.com/mods/250085](url)

### Additional context?

My environment is summarized in these images:

![MSInfo Display](https://github.com/Ryujinx/Ryujinx/assets/7153059/84782d42-eaf1-4b4f-bfa7-ebc008693566)
![MSInfo Memory](https://github.com/Ryujinx/Ryujinx/assets/7153059/6cb5a34d-1df9-4cfe-b87c-4c928612102d)

**Comment by MutantAura** [comment]
This sort of report is not helpful. Search for individual issues and open them if needed.

Some of this can likely be solved via our support channels on discord.
