### ISSUE TITLE
[功能请求] Handheld mode cannot be displayed on a vertical screen.

### ISSUE THREAD

**Issue by JiangYuf** [Ryujinx/Ryujinx#6933]
### Overview

Handheld mode cannot be displayed on a vertical screen.
![Uploading IMG_1045.jpeg…]()

### Smaller details

Handheld mode cannot be displayed on a vertical screen.

### Nature of request

Handheld mode cannot be displayed on a vertical screen.

### Why would this feature be useful?

Handheld mode cannot be displayed on a vertical screen.

**Comment by MutantAura** [comment]
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1104
