### ISSUE TITLE
[Bug]Unhandled Exception: GuestBrokeExecutionException During Fire Emblem Engage Execution

### ISSUE THREAD

**Issue by maxwell142857** [Ryujinx/Ryujinx#6941]
### Description of the issue

While playing Fire Emblem Engage, Ryujinx crashes unexpectedly after about 1-2 hours of gameplay. The macOS error dialog pops up with the message: "Ryujinx quit unexpectedly." This issue has occurred twice so far. The logs indicate the error as "Unhandled Exception: GuestBrokeExecutionException During Game Execution."

### Reproduction steps

1 Launch Fire Emblem Engage on Ryujinx.
2 Play the game for 1-2 hours.
3 Wait for the crash to occur.

### Log file

[Ryujinx_1.1.1330_2024-06-13_15-38-35.log](https://github.com/user-attachments/files/15830197/Ryujinx_1.1.1330_2024-06-13_15-38-35.log)

### OS

macOS Sonoma 14.1.2

### Ryujinx version

1.1.1330

### Game version

2.0.0

### CPU

Apple M2

### GPU

Apple M2

### RAM

8GB

### List of applied mods

No mods were used, only DLCs.

**Comment by ekuland** [comment]
`SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001))`

This error is the game itself crashing

**Comment by maxwell142857** [comment]
Got it! Thank you!
