### ISSUE TITLE
[Feature Request]a simple android support for ryujinx

### ISSUE THREAD

**Issue by gitker** [Ryujinx/Ryujinx#6944]
### Overview

ryjujinx support linux ,termux can simulate a linux enviroment in android ,this two can combine

### Smaller details

we can install .net framework in termux,and for ryjujinx it would see it run in a normal linux

### Nature of request

graphics would run in x11 window ,and 3d accel by vulkan api

### Why would this feature be useful?

android support will be a terrific feature,because so many people use the system

**Comment by piplup55** [comment]
duplicate of #6148
