### ISSUE TITLE
totk not launching, insta crash ryujinx[Bug]

### ISSUE THREAD

**Issue by FroofyFroof** [Ryujinx/Ryujinx#6946]
### Description of the issue

STOP CLOSING THE POST I DONT USE DISCORD
never used this emulator before, used yuzu and it worked fine. when i try to launch totk it doesnt launch, just instantly freezes and crashes ryujinx. it also doesnt create any log files even though they are enabled in the settings

### Reproduction steps

start totk and it freezes

### Log file

00:00:00.235 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.241 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.241 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.242 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.243 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.244 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.244 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x249C
00:00:00.245 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.246 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.246 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.247 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.253 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.253 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.253 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.253 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.253 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.253 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.253 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.253 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.253 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.254 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.254 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.255 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.256 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.256 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.256 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.258 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.266 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1332
00:00:00.271 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.271 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz ; 16 logical
00:00:00.272 |N| Application Print: RAM: Total 31.7 GiB ; Available 17.3 GiB
00:00:00.274 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.275 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.104 |I| Gpu : Backend Threading (Auto): True

### OS

Windows 11

### Ryujinx version

1.1.1332

### Game version

1.0.0/1.2.1

### CPU

i9

### GPU

rtx 3080

### RAM

32 gb

**Comment by riperiperi** [comment]
Your log doesn't contain any useful information, so it's impossible for us to help. You should see if the mii applet is able to launch (via File/Open Applet menu) to see if there's just some fatal error preventing the emulation from starting at all.
