### ISSUE TITLE
[Bug] Crash when starting Shin Megami Tensei III Nocturne HD Remaster

### ISSUE THREAD

**Issue by Endertainer** [Ryujinx/Ryujinx#6962]
### Description of the issue

The emulator crashes when trying to run the game. There's no error or anything, the emulator just suddenly closes.

### Reproduction steps

Just run the game.

### Log file

[Ryujinx_1.1.1336_2024-06-20_18-11-50.log](https://github.com/user-attachments/files/15912814/Ryujinx_1.1.1336_2024-06-20_18-11-50.log)

### OS

Windows 11

### Ryujinx version

1.1.1336

### Game version

1.0.1 (Updated to 1.0.3)

### CPU

i7-13700H

### GPU

Nvidia RTX 4060 Laptop

### RAM

16 GB

### List of applied mods

No mods have been installed

### Additional context?

The game was also installed with its 4 DLC

- Maniax Pack
- Merciful Difficulty
- Mercy and Expectation Map Pack
- Shin Megami Tensei BGM Pack

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use Discord for help.
