### ISSUE TITLE
Games wont launch on Raspberry pi

### ISSUE THREAD

**Issue by corped12** [Ryujinx/Ryujinx#6969]
### Description of the issue

I'm trying to launch games on my Raspberry pi but its not working

### Reproduction steps

I CD to my USB drive then I CD the folder then I run Ryujinx.sh the I click on Super Mario Maker 2

### Log file

[Ryujinx_1.1.1336_2024-06-22_11-45-22.log](https://github.com/user-attachments/files/15937503/Ryujinx_1.1.1336_2024-06-22_11-45-22.log)

### OS

Debian 12 (will only run debian 11 programs)

### Ryujinx version

1.1.1336

### Game version

1.0.0

### CPU

Raspberry PI 4B CPU

### GPU

Raspberry PI 4B GPU

### RAM

8GB

**Comment by MutantAura** [comment]
These devices do not meet minimum requirements.

**Comment by corped12** [comment]
Switching from OpenGL to Vulken I got a loading screen for a second before crashing

**Comment by gdkchan** [comment]
You should use Vulkan, not OpenGL.

**Comment by corped12** [comment]
> You should use Vulkan, not OpenGL.

do you know any Vulkan packages for ARM64 that work I could only find 1 and that had issues because the ARM64 and armhf packages are at different versions

**Comment by gdkchan** [comment]
You need the v3dv driver to use Vulkan on the Raspberry Pi 4. I think it should come pre-installed with the image at this point. When I tried it, I had to build and install the driver myself, but it was long ago.
