### ISSUE TITLE
[Bug] Pokemon Sword crashes on loading screen

### ISSUE THREAD

**Issue by Ocelotko123** [Ryujinx/Ryujinx#6970]
### Description of the issue

Once I enter my name and it goes into the loading screen, the emulator crashes.

### Reproduction steps

Everytime I enter the game and enter a name, the loading screen shows up and a few seconds later during the loading, the game crashes.

### Log file

[Ryujinx_1.1.1336_2024-06-22_22-52-28.log](https://github.com/user-attachments/files/15938298/Ryujinx_1.1.1336_2024-06-22_22-52-28.log)

### OS

Windows 11

### Ryujinx version

1.1.1336

### Game version

1.3.2

### GPU

Nvidia GTX 1650

**Comment by ekuland** [comment]
`ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`
Bad dump. Redump the game from your switch.
