### ISSUE TITLE
[Bug] Shin Megami Tensei V: Vengeance crashing on loading screen

### ISSUE THREAD

**Issue by italoghost** [Ryujinx/Ryujinx#6971]
### Description of the issue

The game crashes on the first loading screen. The loading symbols are fully completed once and then the game crashes on the second symbol. 

On Yuzu (and derivatives, like Suyu and Sudachi) it loads - and play! - just fine.

The logs are from the `ryujinx-git`, but I tried with the official build as well and have the same error. 

I couldn't use the official log, as it wouldn't register the error (it seems that the error occurs when Ryujinx thinks it is running just fine), so I runned Ryujinx on the terminal and copied the logs.

### Reproduction steps

Just launch the game and try to pass the first loading screen.

### Log file

[SMTVV.log](https://github.com/user-attachments/files/15941978/SMTVV.log)

### OS

Arch Linux, GNOME 46, Wayland

### Ryujinx version

1.1.1336+0afa8f2c14f046b46ac5ba14c96f3a5ce523ba16

### Game version

1.0.0

### CPU

AMD Ryzen™ 7 5700X3D × 16

### GPU

AMD Radeon™ RX 6700 XT

### RAM

16 GB

### List of applied mods

1080p60_ShX4
DistanceX3

**Comment by gdkchan** [comment]
Log indicates a file system related error. You can try to create and use a new user profile on the emulator, to have fresh save data. Other than that, I'm not sure what could be causing such error.

**Comment by italoghost** [comment]
It worked! I will reset my config directory! Thanks!
