### ISSUE TITLE
[Feature Request] Adding a game controller with the ability to set shortcut keys/hotkey

### ISSUE THREAD

**Issue by Macrored** [Ryujinx/Ryujinx#6976]
### Overview

In the configuration page of "Settings - Shortcuts", there are only keyboard shortcuts. Why not add game controller shortcuts? This way, it will be more convenient to use.

### Smaller details

Hotkey settings similar to yuzu
![image](https://github.com/Ryujinx/Ryujinx/assets/52482853/dae8d41f-e390-485f-9969-001ab7df8d03)

### Nature of request

None

### Why would this feature be useful?

You can completely control Ryujinx without using a keyboard or mouse, using only a game controller, similar to basic functions such as selecting games, starting games, full screen, vertical synchronization on/off, and exiting.

**Comment by reloxx13** [comment]
Overall more Headless would be nice (no KB/Mouse, only Monitor and controller).

**Comment by MutantAura** [comment]
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3423
