### ISSUE TITLE
[Bug] "Yu-Gi-Oh! RUSH DUEL: Saikyo Battle Royale!! Let's Go! Go Rush!!"

### ISSUE THREAD

**Issue by KallinikZed** [Ryujinx/Ryujinx#6981]
### Description of the issue

The emulator crashes immediately when I try to open the game.

### Reproduction steps

Double click the game to open it and it crashes.

### Log file

[Ryujinx_1.1.1337_2024-06-26_02-28-21.log](https://github.com/user-attachments/files/15980366/Ryujinx_1.1.1337_2024-06-26_02-28-21.log)

### OS

Windows 10

### Ryujinx version

1.1.1337

**Comment by gdkchan** [comment]
Regression from #6581?

**Comment by TSRBerry** [comment]
This is related to how long the string is vs how many bytes are needed to represent it.
I don't think it is a regression, although the game name from the log is exactly 128 bytes long for me. So it should have worked before that PR was merged, which makes this a regression in a weird way?
