### ISSUE TITLE
[Feature Request] Option to just load in Favorites for faster Launch of Ryujinx

### ISSUE THREAD

**Issue by thingsiplay** [Ryujinx/Ryujinx#6986]
### Overview

Loading in all games when starting Ryujinx becomes slower the more games there are, especially on slower drives. Therefore I suggest to give the user a way to load in Favorites only to speedup the initial start phase of Ryujinx. Then there could be an icon or menu option to load in the rest when needed.

### Smaller details

In Settings could be a toggle to `[ ] Load Favorites only on Launch` . To load the rest of the games on demand, either a menu entry in the right mouse menu could be added. Or just use the left bottom icon to reload all games, which in this case could be used to load in everything.

### Nature of request

Optimization for start phase, when only a handful of games are needed regularly. 

### Why would this feature be useful?

In example when I play Zelda for a few weeks, I am not interested into loading in the other games. Especially on a HDD. This also might even save some RAM.

**Comment by Pixxel123** [comment]
This seems like a massive UX downgrade for the edge case users who have potato storage from the 2000s that is complicating things for no reason. If you're just playing one game anyway, just wait instead of staring at a stopwatch.

**Comment by thingsiplay** [comment]
This is not a massive UX downgrade. Nothing changes in the UX, not sure what you imagine there. It's just a single option to prevent loading everything. And this is not about potato storage from 2000s. Games are stored in a normal regular hard drive, just like millions of people have it.

**Comment by thingsiplay** [comment]
What are you talking? It's not a UX downgrade, it's not a potato storage from 2000s, its not for no reason, I'm not staring at stopwatch. Not only are you wrong in so many fronts, you are also very toxic. If you have nothing constructive to say, sometimes its better to say nothing.

**Comment by GamerzHell9137** [comment]
Its a niche feature to request tbh. If you dont want your games to load just move them to a folder under your main folder and exclude it from loading. Make a favorite games folder and put the favorites in there.
