### ISSUE TITLE
[Bug] Luigi's Mansion 2 HD: Slow climbing stairs

### ISSUE THREAD

**Issue by LiderKonmils** [Ryujinx/Ryujinx#6991]
### Description of the issue

In Luigi's Mansion 2 HD, Luigi climb the stairs but really slow.

### Reproduction steps

1.Go to a stairs
2.Try to climb it

### Log file

[Ryujinx_1.1.1340_2024-06-29_15-46-42.log](https://github.com/user-attachments/files/16042069/Ryujinx_1.1.1340_2024-06-29_15-46-42.log)

### OS

Windows 10

### Ryujinx version

1.1.1340

### Game version

1.0.0

### CPU

AMD Ryzen 7 7800X3D

### GPU

XFX Speedster QICK319 Radeon RX 6750XT

### RAM

32Go

### List of applied mods

None

### Additional context?

https://github.com/Ryujinx/Ryujinx/assets/1256145/077fbca5-5530-46ea-9487-2a7d0c337949

Strangly, it seems to do it more with short stairs than long ones

https://github.com/Ryujinx/Ryujinx/assets/1256145/26c29b0b-c2fa-4f07-aad1-0d0f736e9bd4

**Comment by MetrosexualGarbodor** [comment]
enable vsync
