### ISSUE TITLE
[Bug] Animal Crossing: New Horizons (ACNH) | All text is missing on the SteamDeck

### ISSUE THREAD

**Issue by matt1432** [Ryujinx/Ryujinx#6993]
### Description of the issue

No matter what save I'm on in Animal Crossing, the game will always have blank text bubbles, missing button prompts and time, etc.

These reddit posts from other people also show the same problem:
https://www.reddit.com/r/Ryujinx/comments/1dnk2rx/no_text_on_animal_crossing_new_horizon_any_help/
https://www.reddit.com/r/Ryujinx/comments/1dr712p/animal_crossing_new_horizons_seemingly_not_having/

### Reproduction steps

Be on a SteamDeck, using OpenGL backend and launch Animal Crossing.

This issue persists no matter the save or the OS. I tried it on SteamOS, on NixOS, with and without flatpak, etc.

### Log file

No logs

### OS

SteamOS and NixOS

### Ryujinx version

1.1.1336

### Game version

2.0.5

### CPU

Zen 2 4c/8t, 2.4-3.5GHz (up to 448 GFlops FP32)

### GPU

8 RDNA 2 CUs, 1.6GHz (1.6 TFlops FP32)

### RAM

16GB

**Comment by lordmyron** [comment]
the last working version for me that doesn't have this font bug is version 1.1.806. I am on linux using opengl with an rdna3 card. The same issue is happening in totk too.

**Comment by riperiperi** [comment]
![image](https://github.com/Ryujinx/Ryujinx/assets/6294155/b61b3068-4b6c-4b13-8938-cf8bd3b04baa)
This appears to be an issue with Mesa, OpenGL on NVIDIA still works fine. I'm not sure what build would cause this to happen, so it's probably worth testing whether this regressed on a specific Ryujinx build by doing something the Mesa driver was never happy about, or if it regressed in a specific Mesa driver version.

**Comment by piplup55** [comment]
Mesa git (git-0ce2e6594d) fixes this issue
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/915eec32-eacb-4900-84b2-e5958c55b86e)

Mesa 24.1.3 built from gitlab (git-8361a3dfb9)
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/c4cad395-6dd0-4e74-a217-812932ec31a5)

Mesa 24.1.3 from the arch repo
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/911fb5e1-bbab-4c52-914f-9ba057adaec2)

**Comment by ptrsr** [comment]
This is not just on the steam deck. This happens using the latest version of mesa `24.1.3-1` and Ryujinx `1.1.1345`.

**Comment by ptrsr** [comment]
I have tried using mesa `Mesa 24.1.4-2` and it's still broken.

**Comment by krazyguy97** [comment]
> Anyone able to confirm whether this is still an issue with Mesa 24.1.5?

still is an issue aswell
for a workaround i suggest setting up the proprietary amd driver or trying out amdvlk

**Comment by lordmyron** [comment]
The issue still exist in 24.1.6-1, i don't know if the update that was on Mesa git (git-0ce2e6594d) was ever pushed to stable or if it still exist on the git branch.

**Comment by Naxdy** [comment]
@lordmyron The commit in question is included in the 24.2 branch only. See: https://gitlab.freedesktop.org/mesa/mesa/-/commit/0ce2e6594d

**Comment by piplup55** [comment]
this issue seems to be fixed as of Mesa 24.2 being released, if this issue still exists after updating tag me and i will reopen it
![image](https://github.com/user-attachments/assets/6ef93dec-75a0-479e-82b2-d29ed4db81f8)
