### ISSUE TITLE
[Bug] [Crash] playing Zelda TOTK

### ISSUE THREAD

**Issue by tffernandes** [Ryujinx/Ryujinx#6994]
### Description of the issue

The application crash an exit.

### Reproduction steps

walk on the mabe village the aplication crash

### Log file

[Ryujinx_1.1.1340_2024-07-01_17-44-55 - Copia.log](https://github.com/user-attachments/files/16059132/Ryujinx_1.1.1340_2024-07-01_17-44-55.-.Copia.log)
[Ryujinx_1.1.1340_2024-07-01_17-48-50 - Copia.log](https://github.com/user-attachments/files/16059133/Ryujinx_1.1.1340_2024-07-01_17-48-50.-.Copia.log)

### OS

Windows 10

### Ryujinx version

1.1.1340

### Game version

1.2

### CPU

AMD Ryzen 5 3600X

### GPU

RTX 2070 Super

### RAM

16 gb

**Comment by ekuland** [comment]
`LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

Your game dump is bad. Redump it from your switch. Join the discord for further support.
