### ISSUE TITLE
[Bug] Yoshi's Crafted World: Game runs too fast with an uncapped FPS (Vulkan)

### ISSUE THREAD

**Issue by mrjo118** [Ryujinx/Ryujinx#6997]
### Description of the issue

When playing Yoshi's Crafted world, the frame rate is noticeably higher than 60 FPS starting from the title screen through to playing levels, ranging from 90-120 FPS. It can be run at a normal speed if using a third party FPS limiting tool at 60 FPS

### Reproduction steps

With the Vulkan graphics backend set, open Yoshi's Crafted World and observe a high frame rate beginning from the title screen and continuing into the gameplay

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.1340

### Game version

1.0.0

### CPU

i7-6700

### GPU

NVIDIA GeForce  GT 1030

### RAM

12GB

### List of applied mods

None

**Comment by GamerzHell9137** [comment]
Enable Vsync in Ryujinx.

**Comment by ekuland** [comment]
Having vsync off will uncap framerates past what the game is expecting. Most switch games have clocks timed to framerate. This is normal function.
