### ISSUE TITLE
[Feature Request] Add the option to launch a game without compiling shaders first

### ISSUE THREAD

**Issue by epic-bruh-moment** [Ryujinx/Ryujinx#7015]
### Overview

Simply add an option to launch a game without compiling its shaders if it has a cache.

### Smaller details

Add it as a right click option

### Nature of request

Quality of Life

### Why would this feature be useful?

Quickly opening games to test out whether or not mods crash it

**Comment by ekuland** [comment]
Just... disable the shader cache in settings.
