### ISSUE TITLE
[Bug] Ryujinx crashing when walking in an area of the TOTK map

### ISSUE THREAD

**Issue by mrp1no** [Ryujinx/Ryujinx#7023]
### Description of the issue

When I walk in a specific area of the map in Zelda Tears of the Kingdom Ryujinx crashes

### Reproduction steps

Walk north from here (coordinates on bottom right)
<img width="970" alt="image" src="https://github.com/user-attachments/assets/e01a1cb1-3ffd-4f7f-a507-87095129c0e3">

### Log file

00:00:00.222 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.227 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.227 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.228 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.229 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.230 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.230 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2487
00:00:00.231 |I| Configuration LogValueChange: AntiAliasing set to: SmaaMedium
00:00:00.231 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.231 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.232 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.237 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.237 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.237 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.237 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.237 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.237 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.237 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.237 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.238 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.238 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.238 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.239 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.239 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.239 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.239 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.242 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.244 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1345
00:00:00.248 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.248 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz ; 16 logical
00:00:00.249 |N| Application Print: RAM: Total 31.8 GiB ; Available 24.4 GiB
00:00:00.251 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.252 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.107 |I| Gpu : Backend Threading (Auto): True
00:00:00.369 |N| Application LoadGuestApplication: Using Firmware Version: 18.0.0
00:00:00.369 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.392 |I| ModLoader QueryContentsDir: Searching mods for Application 0100F2C0115B6000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.399 |I| ModLoader AddModsFromDirectory: Found enabled mod '!!!TOTK Optimizer' [E]
00:00:00.399 |I| ModLoader AddModsFromDirectory: Found enabled mod '!!!TOTK Optimizer' [R]
00:00:00.399 |I| ModLoader QueryContentsDir: Searching mods for Application 0100F2C0115B6000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.401 |I| Loader Load: Loading rtld...
00:00:00.406 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.406 |I| Loader Load: Loading main...
00:00:00.699 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:00.700 |I| Loader Load: Loading subsdk0...
00:00:00.719 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:00.719 |I| Loader Load: Loading sdk...
00:00:00.761 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:00.770 |I| Loader PrintRoSectionInfo: subsdk3:
    Module: SRC
00:00:00.770 |I| ModLoader ApplyExefsMods: NSO 'subsdk3' replaced
00:00:00.771 |I| ModLoader ApplyExefsMods: main.npdm replaced
00:00:00.776 |W| Ptc Load: Detected unsupported ExeFs modifications. PTC disabled.
00:00:00.852 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: False).
00:00:00.859 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.860 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.880 |I| Loader LoadNsos: Loading image 2 at 0x000000000cc2f000...
00:00:00.882 |I| Loader LoadNsos: Loading image 3 at 0x000000000d2d8000...
00:00:00.882 |I| Loader LoadNsos: Loading image 4 at 0x000000000d347000...
00:00:00.886 |I| ModLoader LoadCheats: Build ids found for application 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    9B4E43650501A4D4489B4BBFDB740F26AF3CF850000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    833A91087CEA527CBFAF4B1C62EA9B8A242784AF000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:00.889 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Application 0100F2C0115B6000
00:00:00.908 |I| ModLoader ApplyRomFsMods: Replaced 1 file(s) over 1 mod(s). Processing base storage...
00:00:18.619 |I| ModLoader ApplyRomFsMods: Building new RomFS...
00:00:18.705 |I| ModLoader ApplyRomFsMods: Using modded RomFS
00:00:18.707 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:18.766 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.2.1 [0100f2c0115b6000] [64-bit]
00:00:18.901 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:18.912 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:19.228 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3060 (Vulkan v1.3.277, Driver v551.86.0.0)
00:00:19.234 |I| GPU.MainThread Gpu LoadShaders: Loading 3635 shaders from the cache...
00:00:26.057 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:26.547 |S| HLE.OsThread.47 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:26.650 |S| HLE.OsThread.47 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:26.658 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:26.663 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:26.743 |S| HLE.OsThread.47 ServicePctl Initialize: Stubbed. 
00:00:28.197 |S| HLE.OsThread.3 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:28.199 |S| HLE.OsThread.3 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:30.316 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:30.316 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:30.317 |S| HLE.OsThread.47 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:30.317 |S| HLE.OsThread.47 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:30.318 |S| HLE.OsThread.47 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:30.473 |S| HLE.OsThread.4 ServiceNv FinishInitialize: Stubbed. 
00:00:30.495 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:30.496 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:30.587 |S| HLE.OsThread.4 ServiceNv InitializeEx: Stubbed. 
00:00:30.621 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:30.668 |S| HLE.OsThread.4 ServiceNv SetNvMapFd: Stubbed. 
00:00:30.669 |S| HLE.OsThread.4 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:30.669 |S| HLE.OsThread.4 ServiceNv AllocObjCtx: Stubbed. 
00:00:30.671 |S| HLE.OsThread.4 ServiceNv SetErrorNotifier: Stubbed. 
00:00:30.671 |S| HLE.OsThread.4 ServiceNv SetUserData: Stubbed. 
00:00:30.671 |S| HLE.OsThread.4 ServiceNv SetTimeout: Stubbed. 
00:00:30.672 |S| HLE.OsThread.4 ServiceNv SetTimeslice: Stubbed. 
00:00:30.677 |S| HLE.OsThread.4 ServiceNv ZcullBind: Stubbed. 
00:00:30.773 |S| HLE.OsThread.47 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:30.778 |S| HLE.OsThread.47 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:30.779 |S| HLE.OsThread.47 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:30.811 |S| HLE.OsThread.3 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:30.813 |I| GUI.WindowThread Hid SetupNpad: Disconnected Controller ProController from Player1
00:00:30.814 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:30.815 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:30.815 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:30.816 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:32.547 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:32.547 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:35.218 |I| HLE.OsThread.11 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:35.220 |I| HLE.OsThread.11 AudioRenderer Initialize: Initializing with REV11
00:00:35.235 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:35.236 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:35.244 |I| HLE.OsThread.11 AudioRenderer Start: Starting renderer id 0
00:00:35.321 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:36.409 |S| HLE.OsThread.47 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:36.412 |S| HLE.OsThread.47 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:36.882 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:36.883 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:36.883 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:36.883 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:38.116 |S| HLE.OsThread.47 ServiceAm GetMainAppletExpectedMasterVolume: Stubbed. 
00:00:38.116 |S| HLE.OsThread.47 ServiceAm GetLibraryAppletExpectedMasterVolume: Stubbed. 
00:00:38.119 |S| HLE.OsThread.47 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:00:39.027 |S| HLE.OsThread.3 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:40.243 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: bootup_time 
 Report: {
    "BootupTimeUs": 11208,
    "system_report_tag": 2175206328
}

00:00:40.247 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_region 
 Report: {
    "Region": 2,
    "Language": 5,
    "StandardTimeName": "UTC",
    "UtcOffsetSeconds": 0,
    "system_report_tag": 2759414308
}

00:00:40.249 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_time 
 Report: {
    "ActiveTime": 13,
    "UpdatedTime": 0,
    "system_report_tag": 2759414308
}

00:00:40.249 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_playstyle 
 Report: {
    "system_report_tag": 2759414308
}

00:00:40.250 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_network_status 
 Report: {
    "NetworkInterface": {
        "TypeCode": 64,
        "Value": "0x00000000000000000000000000000000"
    },
    "LinkLevel": {
        "TypeCode": 65,
        "Value": "0x00"
    },
    "FrequencyBand": {
        "TypeCode": 66,
        "Value": "0x00000000000000000000"
    },
    "system_report_tag": 2759414308
}

00:00:40.434 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: erepo_active_beacon 
 Report: {
    "IntervalTime": 0,
    "UpdatedTime": 0,
    "system_report_tag": 0
}

00:00:43.487 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:43.504 |S| HLE.OsThread.3 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player2}
00:00:43.504 |S| HLE.OsThread.3 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player3}
00:00:43.505 |S| HLE.OsThread.3 ServiceHid DisconnectNpad: Stubbed. {appletResourceUserId: 4294967296 ; npadIdType: Player4}
00:00:50.187 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:51.188 |E| HLE.OsThread.4 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 1086 took more than 1000ms, resuming execution...
00:00:55.399 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1893212732,
    "EventInfo": "Dm_OP_0037",
    "PlayerPosX": 3.406024E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406211E-11,
    "system_report_tag": 2175206328
}

00:00:55.632 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1893212732,
    "EventInfo": "Dm_OP_0038",
    "PlayerPosX": 3.406024E-11,
    "PlayerPosY": -0.15038963,
    "PlayerPosZ": 3.406211E-11,
    "system_report_tag": 2175206328
}

00:00:55.726 |S| HLE.OsThread.47 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:01:24.101 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: option_data 
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1893212732,
    "BoolOptions": 523,
    "CameraRotateSpeed": 2,
    "DisplayMode": 0,
    "MessageWindowTransparency": 0,
    "VoiceLanguage": 7,
    "Action": 1,
    "Cancel": 2,
    "Jump": 3,
    "Attack": 4,
    "SpecialPower": 5,
    "Attention": 6,
    "Throw": 7,
    "Bow": 8,
    "PlusMenu": 9,
    "MinusMenu": 10,
    "SpecialPowerShortcut": 11,
    "CompanionShortcut": 13,
    "PouchShortcut": 14,
    "Whistle": 12,
    "Crouch": 25,
    "Scope": 33,
    "PresetType": 0,
    "system_report_tag": 2175206328
}

00:01:24.157 |S| HLE.OsThread.47 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:01:39.666 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:42.791 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start 
 Report: {
    "PlayTime": 4334,
    "ReleaseVersion": 1369,
    "PlayDataUniqueID": 1439420357,
    "EventInfo": "DefaultBootEvent",
    "PlayerPosX": 65.81858,
    "PlayerPosY": 128.60939,
    "PlayerPosZ": 160.3574,
    "system_report_tag": 2175206328
}

00:01:43.737 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:53.640 |E| HLE.OsThread.2 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.RomFs.RomFsFile.DoRead(Int64& bytesRead, Int64 offset, Span`1 destination, ReadOption& option)
   at LibHac.Fs.FileStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.ConcatenationStorage.Read(Int64 offset, Span`1 destination)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1255
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1345

### Game version

1.2.1

### CPU

i7-8700k

### GPU

NVIDIA RTX 3060

### RAM

32GB

### List of applied mods

TOTK Optimizer 2.0 (crashing with all mods disabled too)

**Comment by MutantAura** [comment]
Your game dump is corrupt.

**Comment by mrp1no** [comment]
> Your game dump is corrupt.

Oh okay, from what can you tell it's corrupt? And what should I do?

**Comment by MutantAura** [comment]
```
 LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
 ```
 This indicates a corrupt dump. To fix it, re-dump the game.
