### ISSUE TITLE
Tears of the Kingdom crashes when initially loading save

### ISSUE THREAD

**Issue by DaLizard64** [Ryujinx/Ryujinx#7029]
### Description of the issue

When selecting a save file from the title screen, the game will crash after 1-2 seconds of loading. The game had been randomly crashing during gameplay, but when trying to reopen it, it would not load.

### Reproduction steps

Launch game, select save file, wait for a few seconds

### Log file

[Ryujinx_1.1.1346_2024-07-14_21-19-16.log](https://github.com/user-attachments/files/16229387/Ryujinx_1.1.1346_2024-07-14_21-19-16.log)

### OS

Windows 10

### Ryujinx version

1.1.1346

### Game version

1.0.0

### CPU

AMD Ryzen 5 5600 6-Core

### GPU

AMD Radeon RX 6650 XT

### RAM

36GB

### List of applied mods

n/a

### Additional context?

Game had been crashing, never had this issue though

**Comment by GamerzHell9137** [comment]
Bad dump.
Redump your game.
