### ISSUE TITLE
[Bug] pokemon scarlet items

### ISSUE THREAD

**Issue by Malabar16** [Ryujinx/Ryujinx#7038]
### Description of the issue

As i updated the game today all my items in Pokémon scarlet is gone. I have literally nothing.

### Reproduction steps

i updated ryujinx when it said it need an update and now my stuf is gone.

### Log file

[Ryujinx_1.1.1350_2024-07-16_16-39-45.log](https://github.com/user-attachments/files/16257555/Ryujinx_1.1.1350_2024-07-16_16-39-45.log)

### OS

windows 10

### Ryujinx version

1.1.1350

### List of applied mods

none

**Comment by ekuland** [comment]
Empty log, incomplete format, [join the discord for support](https://discord.gg/ryujinx).
