### ISSUE TITLE
[Bug] Ryujinx Crashing in TotK

### ISSUE THREAD

**Issue by NeptunianMC** [Ryujinx/Ryujinx#7042]
### Description of the issue

Whenever i get too far away from the landing point after Great Sky Island, it just freezes, then crashes. No idea what's going on.
I've also tried custom save after lookout landing, but crashes when i try to load.

### Reproduction steps

Crashes after Great Sky Island, idk how to replicate

### Log file

[Ryujinx_1.1.1350_2024-07-17_12-08-59.log](https://github.com/user-attachments/files/16271206/Ryujinx_1.1.1350_2024-07-17_12-08-59.log)

### OS

Windows 11

### Ryujinx version

1.1.1350

### Game version

1.1.1

### CPU

i9-13900k

### GPU

NVIDIA RTX 4060 Ti

### RAM

32GB

### List of applied mods

none

**Comment by GamerzHell9137** [comment]
Bad dump.
Redump your game.

**Comment by NeptunianMC** [comment]
> Bad dump. Redump your game.

Got it from a website, didn't dump
