### ISSUE TITLE
[Regression] Mario 3D All Stars not applying updates when launching games after 1.1.1350

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#7044]
### Description of the issue

Super mario 3D all stars no longer applies updates to the sub games

### Reproduction steps

apply an update and load sunshine

### Log file

1.1.1349: [Ryujinx_1.1.1349_2024-07-17_17-52-32.log](https://github.com/user-attachments/files/16273174/Ryujinx_1.1.1349_2024-07-17_17-52-32.log)
1.1350: [Ryujinx_1.1.1350_2024-07-17_17-42-09.tar.gz](https://github.com/user-attachments/files/16273183/Ryujinx_1.1.1350_2024-07-17_17-42-09.tar.gz)

### OS

EndeavourOS

### Ryujinx version

1.1.1350

### Game version

1.0.0/1.1.0

### CPU

AMD Ryzen 9 7900X3D

### GPU

AMD RX 6600 XT/NVIDIA 3060

### RAM

64gb

### Additional context?

the build ids are the same on 1350 but are different on 1349 meaning the update isn't applied correctly
<details close>
<summary>1.1.1350</summary>
<br>

1.1.0:
```00:00:00.387 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    ED0D7ACE84EEC7807225034AD8A30CFD313E422D000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
```
1.0.0
```00:00:00.233 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    ED0D7ACE84EEC7807225034AD8A30CFD313E422D000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
``` 

</details>

<details close>
<summary>1.1.1349</summary>
<br>

1.1.0:
```00:00:00.357 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    B21E3733E11D6FCF1A8D57CE51BEF4A5001CCF66000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
```    
1.0.0:
```00:00:00.207 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    ED0D7ACE84EEC7807225034AD8A30CFD313E422D000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
```

</details>

**Comment by Littl3Guy** [comment]
Same issue here
1.1.1349
[Ryujinx_1.1.1349_2024-07-18_14-07-05.zip](https://github.com/user-attachments/files/16287275/Ryujinx_1.1.1349_2024-07-18_14-07-05.zip)

1.1.1352
[Ryujinx_1.1.1352_2024-07-18_13-52-09.zip](https://github.com/user-attachments/files/16287279/Ryujinx_1.1.1352_2024-07-18_13-52-09.zip)

**Comment by TSRBerry** [comment]
The build ids in these logs are matching. The update seems to be applied correctly.
What makes you think there is something wrong? Does the GUI show something else?

**Comment by Sapelain** [comment]
Thank you for not detecting the updates or DLCs inside XCI. Let's try.

**Comment by Sapelain** [comment]
Well, the ryujinx-Release-1.1.0+2a5d147-win_x64 version doesn't solve anything but they are solving the problem

[Ryujinx_1.1.0+2a5d147_2024-07-18_22-36-03.log](https://github.com/user-attachments/files/16289019/Ryujinx_1.1.0%2B2a5d147_2024-07-18_22-36-03.log)

**Comment by TSRBerry** [comment]
You seem to be talking about a different issue. If my PR doesn't address it could you please open another issue for your problem?

**Comment by Sapelain** [comment]
It's the same problem, it all started with 1.1.1350 and it happens to all games that have updates and dlcs

**Comment by TSRBerry** [comment]
> Well, the ryujinx-Release-1.1.0+2a5d147-win_x64 version doesn't solve anything but they are solving the problem
> 
> [Ryujinx_1.1.0+2a5d147_2024-07-18_22-36-03.log](https://github.com/user-attachments/files/16289019/Ryujinx_1.1.0%2B2a5d147_2024-07-18_22-36-03.log)

Could you try to rephrase this then? I'm not sure what problem it doesn't solve.

**Comment by Sapelain** [comment]
Con la ultima actualización sigue sin detectar ni Actualizacion ni dlc en los archivos xci. Cuando siempre perfecto.

Example with the latest version:
![1](https://github.com/user-attachments/assets/cfb1f508-eccd-4ade-b1b9-cc4395f16c1c)

Ryujinx_1.1.1349, everything worked perfectly:
![2](https://github.com/user-attachments/assets/ec7390da-6d8d-40af-960d-348cac0487cd)

**Comment by TSRBerry** [comment]
Ah, yep that issue gets fixed with #7055.

**Comment by Sapelain** [comment]
I correct one thing I said, the dlcs already read them. But the Updates are not in version 1.1.1354

**Comment by Rahzadan** [comment]
All of my games (50+) are .NSP with Title updates integrated in (one big NSP for each game which includes DLC and TU's)

Prior to 1.1.1350 (1.1.1349 and earlier) this was not a problem.

With 1.1.1350 and later, All games show as 1.0.0.

**Comment by TSRBerry** [comment]
That's a different issue.
