### ISSUE TITLE
[Bug] Consistent Crashing Near Lookout Landing TOTK

### ISSUE THREAD

**Issue by AmyL4** [Ryujinx/Ryujinx#7047]
### Description of the issue

My game has been working fine for many months. But now it keeps crashing if I approach or warp to Lookout Landing, regardless of update or game file, or if I have mods on or not. 

### Reproduction steps

Warp or approach Lookout Landing above ground or from the hidden passage

### Log file

00:04:02.989 |E| HLE.GuestThread.69 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:04:03.031 |E| HLE.GuestThread.69 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263

### OS

Windows 10

### Ryujinx version

15.0.1

### Game version

1.1.1 and above

### CPU

AMD Ryzen 9 5900HX with Radeon Graphics

### GPU

NVIDIA GeForce RTX 3060 Laptop GPU 

### RAM

16GB

### List of applied mods

TOTK Optimizer
zelda-loading-screen_v2-0_110-112 (Ryujinx updates also seem to either fix or break the changed corner ''Loading...'' text of this mod, but that is a separate issue)
various armor/texture replacer mods
warm-embrace-comfort_v1(changes home bed sleep script to give extra hearts)
2k_v12
Better Master Sword Light-60 v1.0
DynamicFPS++ 
LOD Improvement
Optimized Sort + Arrowhead + QOL Sorting
Playstation UI Mod v11.5 - Normal - White
Shadows - 1024x - highest stable

I'm not sure if my mod list is to blame however, because it was working perfectly fine before and the crashes persist even without any mods applied at all or all the mods disabled.

**Comment by TamotoBoi** [comment]
Did you find a fix to this issue

**Comment by Nix0rd** [comment]
I tought i was the only one with this problem but did you find a fix cause it's been like 3 month i've had this crash

**Comment by AmyL4** [comment]
> I tought i was the only one with this problem but did you find a fix cause it's been like 3 month i've had this crash

No, I didn't find a fix. I just figured my save might have been corrupted in a specific way from uninstalling and installing mods as I thought I was the only one with the issue. But if others are experiencing it then it must be something else.

**Comment by Nix0rd** [comment]
> > I tought i was the only one with this problem but did you find a fix cause it's been like 3 month i've had this crash
> 
> No, I didn't find a fix. I just figured my save might have been corrupted in a specific way from uninstalling and installing mods as I thought I was the only one with the issue. But if others are experiencing it then it must be something else.

Too bad, i tried everything and even downloaded like 7 different rom but nothing changed.
It seems like we will never be able to continue the story.

**Comment by AmyL4** [comment]
> > > I tought i was the only one with this problem but did you find a fix cause it's been like 3 month i've had this crash
> > 
> > 
> > No, I didn't find a fix. I just figured my save might have been corrupted in a specific way from uninstalling and installing mods as I thought I was the only one with the issue. But if others are experiencing it then it must be something else.
> 
> Too bad, i tried everything and even downloaded like 7 different rom but nothing changed. It seems like we will never be able to continue the story.

Just to confirm, completely fresh game installs and new saves make no difference? I haven't had time to fully test that. 

Sadly, it seems overwriting the files in publish to a previous release of ryujinx, from before the issue began, doesn't help either. At least not for me. I'm a bit at my wits end trying to find the cause.

It is a real shame.

**Comment by Nix0rd** [comment]
> > > > I tought i was the only one with this problem but did you find a fix cause it's been like 3 month i've had this crash
> > > 
> > > 
> > > No, I didn't find a fix. I just figured my save might have been corrupted in a specific way from uninstalling and installing mods as I thought I was the only one with the issue. But if others are experiencing it then it must be something else.
> > 
> > 
> > Too bad, i tried everything and even downloaded like 7 different rom but nothing changed. It seems like we will never be able to continue the story.
> 
> Just to confirm, completely fresh game installs and new saves make no difference? I haven't had time to fully test that.
> 
> Sadly, it seems overwriting the files in publish to a previous release of ryujinx, from before the issue began, doesn't help either. At least not for me. I'm a bit at my wits end trying to find the cause.
> 
> It is a real shame.

Yeah it change nothing, and it keeps happening on yuzu ryujinx et suyu.
