### ISSUE TITLE
[Feature Request] Support for individual configurations and 8GBRAM

### ISSUE THREAD

**Issue by carlosgamer23** [Ryujinx/Ryujinx#7059]
### Overview

As you know some games support 6gb ram and others only 4g, it would be nice if each game could have its individual configuration. For example, when I want to play Pokémon Legends Arceus, I need to disable the 6gb ram hack and several other settings that I left in the emulator for it to work in other games. Could you also add the 8gb ram hack you have in Sudachi no Ryujinx?

With their own settings, the games would suffer less from bugs, in addition to being possible to adjust the graphics individually in each of them.

### Smaller details

.

### Nature of request

+

### Why would this feature be useful?

.-

**Comment by piplup55** [comment]
stop opening duplicate issues
