### ISSUE TITLE
[Bug] Tears of the kingdom crash

### ISSUE THREAD

**Issue by jacksheehy143** [Ryujinx/Ryujinx#7063]
### Description of the issue

Tears of the kingdom keeps crashing as I approach the lookout landing area. I can go everywhere else just no there haven't tried the depths yet as I cannot progress the story.

### Reproduction steps

Finish tutorial and head for the first crator to the depths you find and try to walk to lookout landing from there

### Log file

[Ryujinx_1.1.1353_2024-07-19_12-35-37.log](https://github.com/user-attachments/files/16311415/Ryujinx_1.1.1353_2024-07-19_12-35-37.log)
[Ryujinx_1.1.1353_2024-07-19_11-47-27.log](https://github.com/user-attachments/files/16311416/Ryujinx_1.1.1353_2024-07-19_11-47-27.log)
[Ryujinx_1.1.1353_2024-07-19_11-56-27.log](https://github.com/user-attachments/files/16311417/Ryujinx_1.1.1353_2024-07-19_11-56-27.log)

### OS

Windows 11

### Ryujinx version

1.1.1353

### Game version

1.2.0

### CPU

Intel® Core™ i5-14600K Desktop Processor 14 cores 

### GPU

NVIDIA Geforce RTX 4060 ti

### RAM

32gb

### List of applied mods

No mods applied

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use Discord for help.
