### ISSUE TITLE
[Bug] Screenshots are saved as blank on Intel

### ISSUE THREAD

**Issue by Rulumi** [Ryujinx/Ryujinx#7068]
### Description of the issue

Saving screenshots with either the Vulkan backend or the OpenGL backend from Ryujinx "Take Screnshoot" option results in a fully blank screenshot saved on an Intel GPU, at least on Windows.
Tested on Intel® Graphics Driver 32.0.101.5762 for Intel® Arc™ & Iris® Xe.

Example screenshot
![ルイージマンション２ HD_2024-07-20_](https://github.com/user-attachments/assets/e712d97d-2b4b-4711-b47b-de70b3fd7529)

### Reproduction steps

Open a game using a modern Intel GPU and take an screenshot from Ryujinx built in option.

### Log file

[Ryujinx_1.1.1354.log](https://github.com/user-attachments/files/16318945/Ryujinx_1.1.1354.log)

### OS

Windows 10 (10.0.19045.4651)

### Ryujinx version

1.1.1354

### CPU

Intel® Core™ i5-1135G7 Processor

### GPU

Intel® Iris® Xe Graphics (80 Execution Units)

### RAM

16,0 GB

### Additional context?

Screenshots save correctly on 1.1.1330, but are already broken on 1.1.1350. The problem started happening in one of the releases between that two versions.

**Comment by dajwong23** [comment]
I think I have the same problem. I back to 1.1.1345 it save correctly and at 1.1.1346 it's not. But I'm using a Nvidia GPU and this bug doesn't happen on all games.
