### ISSUE TITLE
SM3DAS Crash opengl launch SMG [Bug]

### ISSUE THREAD

**Issue by FredericVincent0** [Ryujinx/Ryujinx#7071]
### Description of the issue

SM3DAS Crash opengl when i launch SMG

### Reproduction steps

launch SMG with opengl

### Log file

[Ryujinx_1.1.1354_2024-07-20_08-21-40.log](https://github.com/user-attachments/files/16321111/Ryujinx_1.1.1354_2024-07-20_08-21-40.log)

### OS

Windows 11

### Ryujinx version

1.1.1354

### Game version

1.1.1

### CPU

Ryzenx 5

### GPU

NVIDIA RTX GEFORCE 2060

### RAM

16GB

### List of applied mods

N/A

**Comment by ekuland** [comment]
There is no game crash here, just you closing the game.

**Comment by FredericVincent0** [comment]
I tink i upload the wrong log

Le sam. 20 juill. 2024, 09 h 32, ekuland ***@***.***> a
écrit :

**Comment by FredericVincent0** [comment]
ok it's weird I took a 100% backup and the games on opengl no longer crash

**Comment by FredericVincent0** [comment]
and the fifo and low fps problem is solved it seems
