### ISSUE TITLE
[Bug] TOTK Crashes after Ryujinx Update

### ISSUE THREAD

**Issue by jar25** [Ryujinx/Ryujinx#7076]
### Description of the issue

Updated Ryujinx yesterday with all the updates from over the week and now TOTK is regularly crashing. Prior to updates was working fine

### Reproduction steps

Issues arises simply from regular TOTK play but is not consistent. Usually while take a few minutes to crash, but starting game from save and doing same action will not always cause issue.

### Log file

[Ryujinx_1.1.1357_2024-07-20_14-55-25.log](https://github.com/user-attachments/files/16322169/Ryujinx_1.1.1357_2024-07-20_14-55-25.log)

### OS

Windows 10

### Ryujinx version

1.1.1359

**Comment by liftedplane** [comment]
having a similar issue, was running fine, then updated to 1.1.1358 sometimes it crashes when loading, sometimes it randomly crashes

Here's my two most recent logs before I downgrade.

**Log file**
[Ryujinx_1.1.1358_2024-07-21_15-44-48.log](https://github.com/user-attachments/files/16326478/Ryujinx_1.1.1358_2024-07-21_15-44-48.log)

[Ryujinx_1.1.1358_2024-07-21_17-04-01.log](https://github.com/user-attachments/files/16326479/Ryujinx_1.1.1358_2024-07-21_17-04-01.log)

OS
Windows 11

Ryujinx version
1.1.1358

Game version
1.0

CPU
i9-13900ks

GPU
EVGA RTX 3090

RAM
32GB DDR5 6400

List of applied mods
None

Additional context?
It's random, I cannot seem to get it to occur on command, just randomly crashing when it wasn't on 1.1.1352

**Comment by Paperzlel** [comment]
I've had this issue multiple times this week, and for me it's logged as being an `ErrorDeviceLost`. It's entirely random for me, sometimes happening within minutes, sometimes hours, and all without any real consistency. I've attached two logs, one I had today and one I had a few days ago, to see if anything can be made of this.

### Log file
[Ryujinx_1.1.1359_2024-07-24_08-59-54.log](https://github.com/user-attachments/files/16362075/Ryujinx_1.1.1359_2024-07-24_08-59-54.log)
[Ryujinx_1.1.1354_2024-07-20_13-48-38.log](https://github.com/user-attachments/files/16362080/Ryujinx_1.1.1354_2024-07-20_13-48-38.log)

### OS

Windows 10
### Ryujinx version

1.1.1359
### Game version

v1.0.0

### CPU

AMD Ryzen 5 5600G with Radeon Graphics
### GPU

NVIDIA GeForce GTX 1660
### RAM

16GB
### List of applied mods

None
### Additional context?

Again, it's entriely random to when the `ErrorDeviceLost` is logged, and sometimes it doesn't even get logged.

**Comment by Paperzlel** [comment]
I can confirm that this crash happens on version 1.1.1316, which is one that apparently fixed the issue for others, so this seems to be a separate issue.

### Log file
[Ryujinx_1.1.1316_2024-07-24_17-28-42.log](https://github.com/user-attachments/files/16366653/Ryujinx_1.1.1316_2024-07-24_17-28-42.log)

### Ryujinx Version 
1.1.1316

**Comment by jar25** [comment]
I am unsure as to what has changed if anything, but as of update 1.1.1361 the issue no longer exists.

**Comment by Paperzlel** [comment]
I've tested with 1.1.1361 and still have my issue, although looking at your log it seems they are two separate issues. It may be worth keeping this issue open if anyone else has a similar problem.

**Comment by Therises** [comment]
Same issue. Latest Ryujinx (1.1.1364), latest nvidia game ready drivers (560.70).
Decided to play through TotK again, and encountering this issue (`ErrorDeviceLost`). Played it couple of months ago and it worked fine, but now it crashes for some reason.

CPU: Ryzen 5800X3D
GPU: RTX 4090
RAM: 64GB

[Ryujinx_1.1.1364_2024-08-02_14-05-17.log](https://github.com/user-attachments/files/16469791/Ryujinx_1.1.1364_2024-08-02_14-05-17.log)
[Ryujinx_1.1.1364_2024-08-02_13-34-21.log](https://github.com/user-attachments/files/16469792/Ryujinx_1.1.1364_2024-08-02_13-34-21.log)

**Comment by riperiperi** [comment]
This issue appears to be related to NVIDIA GPUs later than pascal. I'm still on a 1070 so I can't reproduce the issue, and "ErrorDeviceLost" is about as unhelpful as it can get. I doubt anyone wants to play with validation layers enabled for over an hour (they slow things down a lot and fill up your hdd with logs), so it'll probably need a wild guess to fix.

**Comment by Paperzlel** [comment]
Unfortunately I wasn't able to get a crash with error logging enabled, so I'm going to assume that it's something to do with these constant validation errors (if they're not, that's fine, I'm not familiar with Vulkan errors). Since the log is too large (about 16GB) I'll paste the common validation errors below:

Version: 1.1.1368

```
This would be printed for the first few seconds whilst on the title screen
00:00:05.257 |E| .NET TP Worker Gpu UserCallback: Validation Error: [ VUID-VkSubpassDependency-srcSubpass-06809 ] | MessageID = 0xa6d0b68f | vkCreateRenderPass(): pDependencies[0] specifies a self-dependency from stage(s) that access framebuffer space VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT|VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT to stage(s) that access non-framebuffer space VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT|VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT. The Vulkan spec states: If srcSubpass is equal to dstSubpass and srcStageMask includes a framebuffer-space stage, dstStageMask must only contain framebuffer-space stages (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-VkSubpassDependency-srcSubpass-06809)

These would appear during general gameplay in shrines/overworld
00:14:08.858 |E| GUI.RenderThread Gpu UserCallback: Validation Error: [ VUID-vkCmdDrawIndexed-None-09000 ] Object 0: handle = 0xcd6199000000c215, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xd86163000000c71e, type = VK_OBJECT_TYPE_IMAGE_VIEW; Object 2: handle = 0x8f31b4000000c917, type = VK_OBJECT_TYPE_FRAMEBUFFER; Object 3: handle = 0x85f582000000c71f, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xe1a0fc9a | vkCmdDrawIndexed():  the descriptor (VkDescriptorSet 0xcd6199000000c215[], binding 133, index 0) has VkImageView 0xd86163000000c71e[] which will be overlap written to as VkImageView 0x85f582000000c71f[] in VkFramebuffer 0x8f31b4000000c917[] attachment 2. The Vulkan spec states: If a color attachment is written by any prior command in this subpass or by the load, store, or resolve operations for this subpass, it is not in the VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT image layout, and either: the VK_PIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT is set on the currently bound pipeline or the last call to vkCmdSetAttachmentFeedbackLoopEnableEXT included VK_IMAGE_ASPECT_COLOR_BIT and there is no currently bound graphics pipeline or the currently bound graphics pipeline was created with VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT it must not be accessed in any way other than as an attachment by this command (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-09000)
00:14:08.860 |E| GUI.RenderThread Gpu UserCallback: Validation Error: [ VUID-vkCmdPipelineBarrier-None-07889 ] Object 0: handle = 0xeddc6d000000c916, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xdb3e75ca | vkCmdPipelineBarrier(): pMemoryBarriers[0].srcAccessMask (VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT) and dstAccessMask (VK_ACCESS_2_SHADER_READ_BIT) is not a subset of subpass dependency's srcAccessMask and dstAccessMask of subpass 0 of VkRenderPass 0xeddc6d000000c916[]. The Vulkan spec states: If vkCmdPipelineBarrier is called within a render pass instance using a VkRenderPass object, the render pass must have been created with at least one subpass dependency that expresses a dependency from the current subpass to itself, does not include VK_DEPENDENCY_BY_REGION_BIT if this command does not, does not include VK_DEPENDENCY_VIEW_LOCAL_BIT if this command does not, and has synchronization scopes and access scopes that are all supersets of the scopes defined in this command (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-None-07889)
```

Again, these are probably normal validation errors and nothing to worry about, if you want a zip from the log I can see about compressing one

**Comment by Paperzlel** [comment]
Tested with the latest NVIDIA drivers (2 sessions of ~5hrs) and the issue seems to no longer be present, so I think as it is this issue is closed for now
