### ISSUE TITLE
[Bug] Launching .xci game through command line not working when a game folder containing the game is defined

### ISSUE THREAD

**Issue by Tartifless** [Ryujinx/Ryujinx#7077]
### Description of the issue

When a game is launched through command line, ryujinx brings up the gamelist menu without actually running the game.

If i remove the game folder from the configured folder, all works fine (or if there are multiple games in the folder and the one launched is not the first one (alphabetically))

Started with version 1.1.1350.

### Reproduction steps

1) Download ryujinx and extract in c:\emulators\ryujinx
2) add a "portable" folder in ryujinx folder
3) Try and run a game through command line "ryujinx.exe "c:\games\switch_dumps\mario kart 8.xci"
4) Game loads fine
5) Open ryujinx and go to settings
6) Add the c:\games\switch_dumps folder to the game folders
7) close ryujinx
8) Repeat step 3
9) Ryujinx does not launch the game but goes to game list

### Log file

Working log:
[working.txt](https://github.com/user-attachments/files/16322245/working.txt)

Not working:
[not working.txt](https://github.com/user-attachments/files/16322246/not.working.txt)

### OS

Windows 11

### Ryujinx version

1.1.1354

### Game version

1.0.0.0

### List of applied mods

N/A

### Additional context?

Here are the 2 config.json files:

working:
[Config_working.json](https://github.com/user-attachments/files/16322259/Config_working.json)

Not working:
[Config_not working.json](https://github.com/user-attachments/files/16322257/Config_not.working.json)

It looks like the LoadAndSaveMetaData method is called twice, file is opened to write the information of the game launched through CLI, and while loading the MainWindow, the metadata is also loaded, but it's already locked.

**Comment by ekuland** [comment]
This is not a truly accurate reasoning. I have multiple games that _do_ boot despite being in my game directory, but a game right next to them will not.

My examples are BOTW will boot fine, Disgaea 6 will not.
These are both v0 xci dumps that work fine. Both are in the same library folder.

Tested via cmd. "path\to\ryujinx" "path\to\game"

**Comment by Tartifless** [comment]
Try to put BOTW in its own folder and set only this folder in ryujinx.

The issue might be linked with looping in the metadata.json files, the bigger the library, the more possible the file is released.

**Comment by filipppp** [comment]
Having the same issue when starting through playnite..

**Comment by frafes** [comment]
Same issue here with both xci and nsp files.

- If there is only one game in that folder: it fails to launch via command line or shortcut.

- If there are multiple games in that folder:  the first game in that folder (in alphabetical order) fails to launch via command line or shortcut. All other games launch fine.

Some time ago I reported this issue when testing this [PR](https://github.com/Ryujinx/Ryujinx/pull/6515#issuecomment-2084422200), it seems that it still remains.

**Comment by Tartifless** [comment]
Yes exactly that issue, they should be able to fix it, it seems that it does not release the metadata file.

I'll stay with 1.1.349 while waiting for a fix

**Comment by Tartifless** [comment]
Anybody has succeded in testing if latest builds have fixed this ?
I still have the issue and am getting some information from other users that it's affecting all OSes

**Comment by piplup55** [comment]
> Anybody has succeded in testing if latest builds have fixed this ?
 
if the issue was fixed the issue would be closed

**Comment by DocMAX** [comment]
Same here. What a stupid error. Worked long time.
