### ISSUE TITLE
"Docked mode set. Handheld control should be disabled." when using Backbone One Controller

### ISSUE THREAD

**Issue by stonerl** [Ryujinx/Ryujinx#7086]
### Description of the issue

When starting BOTW shortly after loading, I get the following error message: `Docked mode set. Handheld control should be disabled.` Even switching to another controller does not make the window go away.

The only way to resolve this is to unplug the controller (Backbone One). This only happens when this very controller is plugged in and only with BOTW. In other games, this issue does not appear.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/e58a9870-c016-4267-b8dc-9bac1444d7cb">

### Reproduction steps

1. Plug in the Backbone One controller.
2. Start BOTW
3. The error appears.

### Log file

[Ryujinx_1.1.1358_2024-07-22_10-39-44.log](https://github.com/user-attachments/files/16330410/Ryujinx_1.1.1358_2024-07-22_10-39-44.log)

### OS

macOS 14.6

### Ryujinx version

1.1.1358

### Game version

1.6

### CPU

M2 Pro

### GPU

M2 Pro

### RAM

32GB

### Additional context?

This happens only with one specific controller. [Backbone One — Playstation Edition](https://playbackbone.com/products/backbone-one-playstation/)

**Comment by ekuland** [comment]
> 00:00:00.903 |I| GUI.WindowThread Hid Configure: Configured Controller Handheld to Handheld
> 00:00:00.911 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
> 00:00:00.911 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player2

You have 2 players and handheld setup of the ONE that is allowed. Go to handheld, set the controller it's connected to as 'Disabled', apply, and do it for Player 2 as well.

**Comment by stonerl** [comment]
🤦 

thx
