### ISSUE TITLE
[Bug] Visual Glitches with water on Splatoon 3 Vulkan

### ISSUE THREAD

**Issue by nvnprogram** [Ryujinx/Ryujinx#7087]
### Description of the issue

On Splatoon 3 v8.1.0 on latest ryujinx (built from latest source), Vulkan, Laptop Nvidia RTX 3060 6GB ram, 16GB Ram, water flickering effects can be observed. This does not happen on OpenGL. (could have something to do with multithreading?) 
![image](https://github.com/user-attachments/assets/6e435ac3-53b4-469a-81b0-1afb684d5276)
![image](https://github.com/user-attachments/assets/b0a47948-af85-449c-8587-8a70016724e7)
![image](https://github.com/user-attachments/assets/db3a3cbc-fa21-4ab2-9462-09c0791fc8e3)
![image](https://github.com/user-attachments/assets/5c1abf6e-5fc5-460c-a85b-308244f71804)

### Reproduction steps

On Splatoon 3, go to any map that has water (Vss_Ruins03/Bluefin Depot has this bug the most visible)

### Log file

[Ryujinx_1.0.0-dirty_2024-07-22_10-16-25.log](https://github.com/user-attachments/files/16331205/Ryujinx_1.0.0-dirty_2024-07-22_10-16-25.log)

### OS

Windows 11

### Ryujinx version

1.1.1358

### Game version

8.1.0

### CPU

12th Gen Intel(R) Core(TM) i7-12700H

### GPU

NVIDIA GeForce RTX 3060 Laptop GPU (6GB)

### RAM

16GB

### List of applied mods

Flexlion

### Additional context?

This does not happen on OpenGL.
I believe this is the shader (ignore the visual effects in this image, this is a utility for finding shaders at runtime that I made)
![image](https://github.com/user-attachments/assets/9da9251f-d7b1-4fbf-9339-95e3429d935b)
[shader.zip](https://github.com/user-attachments/files/16331166/shader.zip)

**Comment by CosmicDreamsOfCode** [comment]
![image](https://github.com/user-attachments/assets/1a640554-2b65-4a75-8b7b-05480f48fd6e)
Another example of this, curious what change might have caused it.

**Comment by CosmicDreamsOfCode** [comment]
I think zfighting is also worse than usual now, But I'm not sure if thats related or not.

**Comment by gdkchan** [comment]
Fixed by #7226.
