### ISSUE TITLE
[Regression] BOTW water renders white using amdvlk/windows driver after 1.1.1352

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#7089]
### Description of the issue

breath of the wild water renders white after 1.1.1352
![image](https://github.com/user-attachments/assets/0d7bd0b6-fd3b-4563-8a56-e7b7911557ac)
![image](https://github.com/user-attachments/assets/9390d081-2fee-41d7-a601-ae79432f4c63)

### Reproduction steps

load the game near zora's domain (any water should work i used zora's domain because it was the closest to my save location)

### Log file

[Ryujinx_1.1.1352_2024-07-22_14-40-52.log](https://github.com/user-attachments/files/16334509/Ryujinx_1.1.1352_2024-07-22_14-40-52.log)

### OS

EndeavourOS

### Ryujinx version

1.1.1352+

### Game version

1.6.0

### CPU

AMD Ryzen 9 7900X3D

### GPU

RX 6600 XT / RTX 3060

### RAM

64gb

**Comment by GamerzHell9137** [comment]
Fixed by https://github.com/Ryujinx/Ryujinx/pull/7092
