### ISSUE TITLE
[Bug] Unable to launch TotK

### ISSUE THREAD

**Issue by oblivisheee** [Ryujinx/Ryujinx#7112]
### Description of the issue

I cannot launch Zelda: TotK on my steam deck.

### Reproduction steps

Launch TotK
Ryujinx crash

### Log file

[Ryujinx_1.1.1361_2024-07-26_00-04-06.log](https://github.com/user-attachments/files/16390829/Ryujinx_1.1.1361_2024-07-26_00-04-06.log)

### OS

Last version of Steam OS

### Ryujinx version

Last version

### Game version

1.0.0

### CPU

Steam Deck Oled CPU

### GPU

Steam Deck Oled GPU

### RAM

16 GB

### List of applied mods

TOTK Optimizer

**Comment by piplup55** [comment]
github is not the place for support, please join the [discord](https://discord.gg/ryujinx) for support

**Comment by oblivisheee** [comment]
> github is not the place for support, please join the [discord](https://discord.gg/ryujinx) for support
which channel exactly? I have written to `linux-support` but have been ignored

**Comment by MetrosexualGarbodor** [comment]
The logs you posted in both places are both empty, that's why you didn't receive any replies.
