### ISSUE TITLE
[Bug] Zeldas don't use all the CPU and GPU

### ISSUE THREAD

**Issue by SikinoGaming** [Ryujinx/Ryujinx#7113]
### Description of the issue

When playing Breath of the Wild or Tears of the Kingdom with 60fps mods or with VSync off, we can see that the game is arround 45-50 fps and the gpu and cpu are not fully used.

### Reproduction steps

Launch BotW or TotK with a 60fps mod or VSync off.

### Log file

00:02:06.127 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:07.252 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1368,
    "PlayDataUniqueID": 338211282,
    "EventInfo": "Dm_OP_0037",
    "PlayerPosX": 3,406024E-11,
    "PlayerPosY": -0,15038963,
    "PlayerPosZ": 3,406211E-11,
    "system_report_tag": 2175206328
}

00:02:07.350 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1368,
    "PlayDataUniqueID": 338211282,
    "EventInfo": "Dm_OP_0038",
    "PlayerPosX": 3,406024E-11,
    "PlayerPosY": -0,15038963,
    "PlayerPosZ": 3,406211E-11,
    "system_report_tag": 2175206328
}

00:02:07.450 |S| HLE.OsThread.47 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:02:23.414 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: option_data
 Report: {
    "PlayTime": 2,
    "ReleaseVersion": 1368,
    "PlayDataUniqueID": 338211282,
    "BoolOptions": 1035,
    "CameraRotateSpeed": 2,
    "DisplayMode": 0,
    "MessageWindowTransparency": 0,
    "VoiceLanguage": 2,
    "Action": 1,
    "Cancel": 2,
    "Jump": 3,
    "Attack": 4,
    "SpecialPower": 5,
    "Attention": 6,
    "Throw": 7,
    "Bow": 8,
    "PlusMenu": 9,
    "MinusMenu": 10,
    "SpecialPowerShortcut": 11,
    "CompanionShortcut": 13,
    "PouchShortcut": 14,
    "Whistle": 12,
    "Crouch": 25,
    "Scope": 33,
    "PresetType": 0,
    "system_report_tag": 2175206328
}

00:02:23.448 |S| HLE.OsThread.47 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:02:32.829 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:35.183 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 362086 bytes, profiled functions: 107721).
00:02:35.616 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:36.176 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: event_player_start
 Report: {
    "PlayTime": 23988,
    "ReleaseVersion": 1368,
    "PlayDataUniqueID": 759805569,
    "EventInfo": "DefaultBootEvent",
    "PlayerPosX": -3294,586,
    "PlayerPosY": 1453,4154,
    "PlayerPosZ": -3430,5122,
    "system_report_tag": 2175206328
}

00:02:38.257 |I| HLE.OsThread.22 ServicePrepo ProcessPlayReport:
PlayReport log:
 Kind: Normal
 Pid: 127
 ApplicationVersion: 0
 UserId: 00000000000000010000000000000000
 Room: is_location_visit
 Report: {
    "PlayTime": 23988,
    "ReleaseVersion": 1368,
    "PlayDataUniqueID": 759805569,
    "LocationCategory": "Shrine",
    "LocationName": "Dungeon105",
    "Pattern": "MainField",
    "IsFirstVisit": False,
    "system_report_tag": 2175206328
}

### OS

Windows 11 Pro 23H3

### Ryujinx version

1.1.1359

### Game version

1.2.0

### CPU

AMD Ryzen 5 5600X

### GPU

NVIDIA GTX 1660

### RAM

32GB 3200MT/s

### List of applied mods

60 fps mod can me use to make the game run at noemal speed but it's not mandatory.

### Additional context?

I tried diffrent AA and switching from Vulkan to OpenGL, I've seen no diffrences.
The `ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...` line is a freeze that occurs on game withou mods and while loading the world from start menu.

**Comment by MetrosexualGarbodor** [comment]
Not an emulator issue. Ryujinx will use what it can use.
