### ISSUE TITLE
Not an emulator issue. Ryujinx will use what it can use.

### ISSUE THREAD

**Issue by SikinoGaming** [Ryujinx/Ryujinx#7114]
Not an emulator issue. Ryujinx will use what it can use.

_Originally posted by @MetrosexualGarbodor in https://github.com/Ryujinx/Ryujinx/issues/7113#issuecomment-2252676296_

My GPU nor CPU are at 100% (they are both at 50%), this is why I created this issue. My RAM and VRAM are also not full so my hardware is not limiting the game. I tried disabling VSync in Splatoon and the game runs a 300fps and GPU hits 100% and CPU 80%, so this is why i think Ryujinx have a problem emulating Zeldas.
P.S: I'm a dev so I can help Ryujinx if you let me express myself and don't close the issue instantly without arguing.

**Comment by SikinoGaming** [comment]
I used NVIDIA's Alt + R and Task Manager to see this and i also seen that it shows 100fps but Ryujinx tell me 40-50 fps

**Comment by MetrosexualGarbodor** [comment]
Again, not an emulator issue. You are emulating a console that has 4 cores, therefore if you want 100% usage, you want a CPU with 4 cores (which would perform worse). The performance you are having is expected for a 5600x. The limiting factor is GPU emulation for these games, which have behaviour that is not nice to emulate.

If you would like to discuss contributing to the emulator, please refer to the development channel on [Discord](https://discord.gg/368RUv7Z).
