### ISSUE TITLE
[Regression] Multi-packed games/XCI files: included updates & DLCs within XCI files get ignored by 1.1.1350 and newer

### ISSUE THREAD

**Issue by Aris-t2** [Ryujinx/Ryujinx#7117]
### Description of the issue

- games multi-packed inside a single xci file (game + update + dlc)
- Ryujinx only loads basic game version "0 btw. 1.0.0" ignoring any included updates oder dlcs
- the issue occurs since 1.1.1350, going back to 1.1.1349 works fine, the issue is not present there

### Reproduction steps

Test any multi-packed game with 1.1.1350 and to 1.1.1349. You will notice game updates and DLCs are getting ignored. The version is set back to "0 btw. 1.0.0" inside emulators titlebar and within game titlescreen for example.

The issue was also described here: https://github.com/Ryujinx/Ryujinx/issues/7044
However the issue was closed, but was not fixed. As of today the issue is still present in current 1.1.1361

A potential fix here https://github.com/Ryujinx/Ryujinx/pull/7055#issuecomment-2237473915 does not fix this issue.

This happens to all games, not just the one within this example:

1.1.1349 shows games version 3.0.1
![image](https://github.com/user-attachments/assets/0a8f8f54-0840-4335-a48c-8a347b131aa0)

1.1.1350 shows game version 1.0.0
![image](https://github.com/user-attachments/assets/70fa76d5-f045-496a-b8bd-08c8d5c1eab4)

### Log file

[Ryujinx_1.1.0+b69c501_2024-07-27_15-52-07.log](https://github.com/user-attachments/files/16400420/Ryujinx_1.1.0%2Bb69c501_2024-07-27_15-52-07.log)

Log from using this build: https://github.com/Ryujinx/Ryujinx/pull/7055#issuecomment-2237473915

### OS

Windows 11

### Ryujinx version

1.1.1350

### CPU

i7-14700

### GPU

GTX 4080

### RAM

32

### List of applied mods

no mods applied during tests

**Comment by ekuland** [comment]
Did... you reapply these updates and dlcs from their respective menus?

**Comment by piplup55** [comment]
the issue you linked is unrelated, that was for 3D all stars/other games that were affected by the same issue (mario kart isn't one of them), after 1.1.1350 you need to apply the updates and dlc the same way you would for a nsp game

**Comment by zhegeshijiehuiyouai** [comment]
I've encountered the same issue. Versions 1.1.1350 and later fail to correctly recognize The Legend of Zelda: Breath of the Wild XCI files with two DLCs. The game version reverts to 1.0.0, making it impossible to use cheats or switch to Chinese. Reverting to version 1.1.149 or earlier resolves the problem. This bug is definitely caused by the 1.1.150 update:
Add support for multi-game XCIs (second try).
Implements loader support for XCI packages that contain multiple title entries.
Fixes recognition of XCI files that contain title updates alongside the base game.
I hope the developers can resolve this issue.

**Comment by Aris-t2** [comment]
Shame on me for not checking this. I did not know we have to enable title updates manually since 1.1.150.

@zhegeshijiehuiyouai 
This works for me:
![image](https://github.com/user-attachments/assets/328d2f83-2e5d-48b6-bfb9-3c64c2adf7e9)
![image](https://github.com/user-attachments/assets/08fa9469-a889-4093-b1f7-fe95b07169b0)



This issue can be closed.

**Comment by redomCL** [comment]
> the issue you linked is unrelated, that was for 3D all stars/other games that were affected by the same issue (mario kart isn't one of them), after 1.1.1350 you need to apply the updates and dlc the same way you would for a nsp game

install nsp upd can be used,but xci include upd is invaild  start by 1.1.1350,this  feature has been removed since 1.1.1350？
