### ISSUE TITLE
PS5 CONTOLLER NOT DETECTED ON ALL PLATFORMS 

### ISSUE THREAD

**Issue by Hawlton** [Ryujinx/Ryujinx#7124]
### Description of the issue

RYUJINX IS INCAPABLE OF DETECTING PS5 DUALSENSE CONTROLLERS ON LINUX AND WINDOWS.
TRIED MULTIPLE PS5 CONTROLLERS IN BT AND USB-C. THIS IS THE LATEST FLATPAK VERSION.
I CAN CONFIRM THAT PS5 CONTROLLERS WERE WORKING PERFECTLY AS LATE AS  7/25/2024.
OTHER CONTROLLERS HAVE NOT BEEN TESTED.

### Reproduction steps

AFTER CONNECTING MY PS5 CONTROLLER TO MY PC BY BLUETOOTH AND USB-C,
FOUND THAT ALL APPLICATIONS (DOLPHIN, STEAM, ECT...) COULD DETECT PS5 CONTROLLER BUT
RYUJINX ONLY HAS "DISABLED" AND "ALL KEYBOARDS" AS AN OPTION FOR INPUT DEVICE.

PREVIOUSLY, PS5 CONTROLLERS WERE RECOGNIZED WHEN THEY WERE PLUGGED IN VIA USB-C

### Log file

--- End of stack trace from previous location ---
   at Avalonia.FreeDesktop.DBusCallQueue.Process() (IBusX11TextInputMethod #32109549)
00:05:02.920 |E| UI : [Error] [IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #32109549)
00:05:02.920 |E| UI : [Error] [IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/IBus/InputContext_76”
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.QueueOnErrorAsync(Exception e) (IBusX11TextInputMethod #32109549)

### OS

LINUX 6.9.9

### Ryujinx version

1.1.1361

### CPU

15-12600K

### GPU

RTX 3060

### RAM

16GB 3200MHZ

### List of applied mods

NONE

### Additional context?

I'M GOING TO CLONE THE REPOSITORY AND ATTEMPT TO FIX THIS MYSELF.
NOT BEING ABLE TO DETECT AN INPUT DEVICE IS UNACCEPTABLE.

**Comment by GamerzHell9137** [comment]
Since nothing was added in the past 3 days i think the devs sneaked into your pc and disabled your PS5 controllers.
Not 100% sure but its always a possibility.

**Comment by Hawlton** [comment]
All I know is if every other application on my PC can detect my Ps5 controller with no problems, then that confirms without any shadow of a doubt that this is the fault of ryujinx.

**Comment by GamerzHell9137** [comment]
Exactly! It can't be any other software interfering with the communication between Ryujinx and controller or like Steam being opened or Windows issues.

**Comment by Hawlton** [comment]
That's not how udev works. Tried running through steaminput, still didn't work.

**Comment by Hawlton** [comment]
UPDATE: AFTER REINSTALLING THE RYUJINX FLATPAK 4-5 TIMES MY CONTROLLER APPEARS. 
I WILL DEFINITELY DIGGING INTO THE SOURCE CODE AFTER THIS. CONTROLLER DETECTION ON LINUX IS ABYSMAL.

**Comment by Candygoblen123** [comment]
Hello, please stop screaming at us. Ryujinx is experimental software, and issues like this one are to be expected.

Ryujinx uses SDL for its controller support, a library used by a significant amount of games for their controller support. Chances are, your controller isn’t being detected by SDL properly.

**Comment by Hawlton** [comment]
SORRY IF I CAME OFF AS SCREAMING BUT CAPS IS BETTER AT DRAWING ATTENTION TO THINGS.
DOLPHIN ALSO USES SDL AND IS ABLE TO IDENTIFY SDL/0/PS5 JUST FINE.

**Comment by Hawlton** [comment]
UPDATE: I CANNOT REPRODUCE  THE ISSUE IN A LIVE USB ENVIRONMENT. I WILL LOOK FURTHER INTO THIS AND TRY TO DETERMINE WHAT IS THE CAUSE IS.

**Comment by stonerl** [comment]
> SORRY IF I CAME OFF AS SCREAMING BUT CAPS IS BETTER AT DRAWING ATTENTION TO THINGS.
> 

No it isn't. It is hard to read and plain annoying.

**Comment by DisBot404** [comment]
> > SORRY IF I CAME OFF AS SCREAMING BUT CAPS IS BETTER AT DRAWING ATTENTION TO THINGS.
> 
> No it isn't. It is hard to read and plain annoying.

no, no let them scream

**Comment by Hawlton** [comment]
I FOUND THE PROBLEM AND FIXED IT BUT SINCE I'M SO ANNOYING I THINK ILL CLOSE THE ISSUE AND KEEP THE SOLUTION TO MYSELF.

**Comment by MetrosexualGarbodor** [comment]
[OP has been permanently banned for trolling]
