### ISSUE TITLE
Super Mario Maker 2 Crash Loader

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#713]
Mario Maker Crash loader Ryujinx Master #712 follow full logs
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/3336290/Ryujinx.log)

**Comment by AcK77** [comment]
Please open an issue here https://github.com/Ryujinx/Ryujinx-Games-List/issues/new and follow the template, thanks.
