### ISSUE TITLE
Can't load anything

### ISSUE THREAD

**Issue by GMan918** [Ryujinx/Ryujinx#7135]
### Description of the issue

Whenever I try to load one of my games like Super Mario Wonder, it crashes without even launching it.

### Reproduction steps

Just download it from the patrion link and try to load a game.

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2024-07-31_02-36-33.log](https://github.com/user-attachments/files/16438029/Ryujinx_1.1.0-ldn3.1.3_2024-07-31_02-36-33.log)

### OS

Windows 11

### Ryujinx version

1.1.0

### Game version

1.0.0

### CPU

I7-1355U

### GPU

IrisXe Integrated Graphics

### RAM

16GB

**Comment by piplup55** [comment]
Super Mario Bros. Wonder does not have LDN. It has single system multiplayer and some services that require Nintendo Switch Online. As we do not connect to NSO in any way, these cannot be used.
The game does not work on the LDN build as it is too old. Use [master.](https://ryujinx.org/download)
If you want to play multiplayer, we suggest using Parsec.
