### ISSUE TITLE
Discord invite expired

### ISSUE THREAD

**Issue by GolfingSuccess** [Ryujinx/Ryujinx#715]
[This](https://discordapp.com/invite/VkQYXAZ) invite is no longer valid, but I have an NSP that doesn't work with Ryujinx. Can the link please be fixed? I don't have any other place to post this, so...

**Comment by Thog** [comment]
The link on the readme is valid, use this one.

**Comment by GolfingSuccess** [comment]
[This one](https://discordapp.com/invite/N2FmfVc)? Nope, it doesn't work either.

**Comment by Yvar192** [comment]
It works perfectly fine for me. You might've been banned

**Comment by GolfingSuccess** [comment]
@Yvar192 But I've never joined that server before, how could've I been banned?

**Comment by Yvar192** [comment]
![Not sure, might be an IP ban? As i said, works perfectly on my end](https://cdn.discordapp.com/attachments/535579789248036874/594452897308213270/Screenshot_20190629-110238.png)

**Comment by GolfingSuccess** [comment]
@Yvar192 I get that screen too, although it says "rad" instead of "Dr.Hacknik", but I get the "Invite Invalid" screen after I click "Accept Invite".

**Comment by GolfingSuccess** [comment]
Alright, I think I found the issue: for some weird reason, I was logged out of Discord, and, instead of letting me log in, it outright rejected the invite. After I logged in, it accepted it. That's... totally weird.
