### ISSUE TITLE
[Bug] Broken shadows and water in Mario Golf when using Vulkan

### ISSUE THREAD

**Issue by clebbington** [Ryujinx/Ryujinx#7152]
### Description of the issue

Shadows are flickering and water shader is broken in Mario Golf: Super Rush on macOS.

![Screenshot 2024-08-03 at 1 24 40 AM](https://github.com/user-attachments/assets/7592b07f-4fe4-47f4-bab3-de76a789cd7c)

Tested on my friend's WIndows 11 laptop and had the same issue when using Vulkan. Switching to OpenGL fixed the issue on his laptop, but isn't an option on my Mac.

### Reproduction steps

Load game and start a match in Spiky Palms. Directional shadows flicker and the water reflections have blocky artifacts

### Log file

[Ryujinx_1.1.1364_2024-08-03_01-34-48.log](https://github.com/user-attachments/files/16478220/Ryujinx_1.1.1364_2024-08-03_01-34-48.log)

### OS

macOS 15.0

### Ryujinx version

1.1.1364

### Game version

3.0.0

### CPU

M1 Pro

### RAM

16GB

**Comment by gdkchan** [comment]
Fixed by #7226.
