### ISSUE TITLE
[Bug] DarkStar One - Switch Edition crashes emulator when any item is selected on a station.

### ISSUE THREAD

**Issue by Aionir** [Ryujinx/Ryujinx#7153]
### Description of the issue

When attempting to select an item (News, Terminal, etc.), the emulator crashes to desktop. Logs report that an opcode is undefined.

### Reproduction steps

Start the game. Select new game. Skip intros. Once at the starter station try selecting any of the options. Crash.

### Log file

[Ryujinx_1.1.1364_2024-08-03_12-58-17.log](https://github.com/user-attachments/files/16482308/Ryujinx_1.1.1364_2024-08-03_12-58-17.log)

### OS

Windows 10

### Ryujinx version

1.1.1364

### Game version

1.0.1

### CPU

AMD Ryzen 7 2700X

### GPU

GeForce 1080Ti

### RAM

16GB

**Comment by makigumo** [comment]
Related https://github.com/Ryujinx/Ryujinx/issues/4054

**Comment by Aionir** [comment]
Still getting crashes on 1375... am I missing something?
