### ISSUE TITLE
android.gui IGraphicBufferProducer: 2 (SetBufferCount) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#716]
android.gui IGraphicBufferProducer: 2 (SetBufferCount) is not implemented.

## Service description:
Unknown

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/180
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/251

**Comment by B3astTech** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/537

**Comment by Thog** [comment]
Fixed by #981
