### ISSUE TITLE
[Feature Request] Add support for the NSZ and XCZ file formats

### ISSUE THREAD

**Issue by KoB-Kirito** [Ryujinx/Ryujinx#7168]
### Overview

NSZ is an open source MIT licensed python aplication to lossles compress/decompress NSP files in order to save a lot of storage.
It **saves** about **~50%** of **disk space** making it worth a consideration imho.

### Smaller details

Thread explaining everything:
https://gbatemp.net/threads/nsz-homebrew-compatible-nsp-xci-compressor-decompressor.550556/

Results:
https://gbatemp.net/threads/nsz-title-compression-results.549831/

Github:
https://github.com/nicoboss/nsz

### Nature of request

Add file type / (de-)compression support.

### Why would this feature be useful?

Cutting the file size of your backups by half saves money on sd cards.

**Comment by MutantAura** [comment]
There are no plans to support this format.
