### ISSUE TITLE
am ICommonStateGetter: 66 (SetCpuBoostMode) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#717]
am ICommonStateGetter: 66 (SetCpuBoostMode) is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#SetCpuBoostMode)
```
Takes an input u32 CpuBoostMode (only modes 0 and 1 are valid) and passes it to SetCpuBoostMode.
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/180

**Comment by Thog** [comment]
Closed by #743
