### ISSUE TITLE
Ryujinx does not start

### ISSUE THREAD

**Issue by ttttux** [Ryujinx/Ryujinx#7172]
### Description of the issue

Whenever I try to start the emulator, it doesn't.

It says ResultFsPartitionSignatureVerificationFailed, I don't know why, I only have 2 ext4 drives, if that helps solve the problem.

### Reproduction steps

I am not sure, I get the warning, that Ryujinx doesn't support Wayland, so maybe test it with Wayland, it has worked perfectly fine for me on Wayland before tho.

### Log file

[Ryujinx_1.1.1352_2024-08-07_10-10-58.log](https://github.com/user-attachments/files/16520513/Ryujinx_1.1.1352_2024-08-07_10-10-58.log)

### OS

Arch Linux (Kernel 6.10.1-arch1-1)

### Ryujinx version

1.1.1352

### CPU

AMD Ryzen 7 5700X (16) @ 3.400GHz

### GPU

AMD Radeon RX 6700 XT

### RAM

16GB

### List of applied mods

TOTK optimizer

**Comment by piplup55** [comment]
update your ryujinx, this issue was fixed awhile ago
