### ISSUE TITLE
[Bug]crash

### ISSUE THREAD

**Issue by EvenWen1215** [Ryujinx/Ryujinx#7186]
### Description of the issue

run totk crash

### Reproduction steps

run totk and crash

### Log file

[Ryujinx_1.1.1373_2024-08-09_16-58-43.log](https://github.com/user-attachments/files/16558881/Ryujinx_1.1.1373_2024-08-09_16-58-43.log)

### OS

win11

### Ryujinx version

last

### Game version

1.2.0

### CPU

12100f

### GPU

970

### RAM

32

**Comment by ekuland** [comment]
`LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!`

Your game dump is corrupted. Redump it from your switch. Join the discord for further support.
