### ISSUE TITLE
am ILibraryAppletCreator: 11 (CreateTransferMemoryStorage) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#719]
am ILibraryAppletCreator: 11 (CreateTransferMemoryStorage) is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#CreateTransferMemoryStorage) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::am::service::ILibraryAppletCreator(11))
```
Takes an input TransferMemory copy-handle, an input u8 bool, and an s64 size, returns an #IStorage.

The user-process creates the TransferMemory with permissions=0.

The TransferMemory is mapped, which can then be accessed via #IStorageAccessor. The input bool controls whether writing to the storage is allowed: #Write will throw an error if this flag is not set.
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/185
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/53

**Comment by jduncanator** [comment]
This was closed in #826
