### ISSUE TITLE
[Bug] Ryujinx freezing immediately on starting up any game

### ISSUE THREAD

**Issue by JadeJuno** [Ryujinx/Ryujinx#7213]
### Description of the issue

When trying to open any game, either just double-clicking on its icon or by right-clicking and choosing the "Run Application" option, the window freezes, and on interacting with the window again it fades to white and goes into a "Not Responding" window status.

While typing this bug report (which took me a couple minutes as I got distracted), the emulator finally got restored, but it's currently stuck in a "Loading (game name)" screen, with no other info than a looping loading bar animation. 

### Reproduction steps

1. Open Ryujinx app
2. Open any game, either double-clicking it or right-clicking and choosing the "Run Application" option.
3. See the window freeze. If using the right-click method, the context menu might even stay after switching to other windows.

### Log file

[Ryujinx_1.1.1376_2024-08-17_19-28-37.log](https://github.com/user-attachments/files/16646733/Ryujinx_1.1.1376_2024-08-17_19-28-37.log)
(Note: I turned on the "Developer Options" on the "Logging" tag shortly after the emulator freezing, so it's not constantly "verbose")

### OS

Windows 10

### Ryujinx version

1.1.1376

### Game version

Irrelevant (happens on any game)

### GPU

Nvidia RTX 3060

### RAM

16 GB

### Additional context?

The emulator used to work perfectly like a week ago. I just updated, so I suspect it might have something to do with the latest update?

**Comment by MetrosexualGarbodor** [comment]
Do not enable developer logs unless explicitly told to by a developer. 

People with third party antivirus software installed usually have similar issues, so I'd recommend getting rid of any if it exists in your system. For further support, please join Discord.
