### ISSUE TITLE
[Bug] black screen

### ISSUE THREAD

**Issue by molberts** [Ryujinx/Ryujinx#7214]
### Description of the issue

when i try to open a game, the only thing that appears is a black screen with no sound

### Reproduction steps

when i try to open a game, the only thing that appears is a black screen with no sound

### Log file

![Captura de pantalla 2024-08-18 033201](https://github.com/user-attachments/assets/75294a60-7c1e-4137-9022-45a22898cbac)

### OS

windows 11

### Ryujinx version

1.1.1376

**Comment by MetrosexualGarbodor** [comment]
Update the game
