### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zeekx** [Ryujinx/Ryujinx#7215]
### Description of the issue

Crash every time when lunch a game

### Reproduction steps

select any game, then run it

### Log file

[Ryujinx_1.1.1376_2024-08-18_14-26-36.log](https://github.com/user-attachments/files/16647424/Ryujinx_1.1.1376_2024-08-18_14-26-36.log)

### OS

Mac OS Intel 14.6.1 (23G93)

### Ryujinx version

1.1.1376

### List of applied mods

None

**Comment by zeekx** [comment]
Game FPS: 0.00; FIFO: 0.00%

**Comment by ekuland** [comment]
After ripping out all the debug logs, this is an empty log. No game boot. Intel on macs is only _technically_ kinda supported by the fact that they run the same os as apple silicon macs. Boot a different OS.

Also not following the template.
