### ISSUE TITLE
[Bug] Cult of The Lamb crashing when opening after adding The Pilgram Pack 

### ISSUE THREAD

**Issue by Hiiii366** [Ryujinx/Ryujinx#7232]
### Description of the issue

After adding the DLC, and running the game, the game just crashes. 

### Reproduction steps

Add Pilgram Pack DLC
Run the game

### Log file

[Ryujinx_1.1.1379_2024-08-21_15-29-33.log](https://github.com/user-attachments/files/16697834/Ryujinx_1.1.1379_2024-08-21_15-29-33.log)

### OS

Windows 10

### Ryujinx version

1.1.1378

### Game version

1.4.3

**Comment by MetrosexualGarbodor** [comment]
Your log is empty. Please join Discord for general support.
