### ISSUE TITLE
[Bug] TOTK 1.2.1 crash in Hyrule Field - Ryujinx version 1.1.1379

### ISSUE THREAD

**Issue by thiagodolabsdevops** [Ryujinx/Ryujinx#7233]
### Description of the issue

After the very first part of TOTK (1.2.1), in Hyrule Field, the game just crash. Restart the game or clean the shader cache didn't worked.

### Reproduction steps

Reach Hyrule field after send the Master Sword to the past and go straight ahead to the next objective. The game will crash in no time.

### Log file

[Ryujinx_1.1.1379.log](https://github.com/user-attachments/files/16700975/Ryujinx_1.1.1379.log)

### OS

MacOS Sonoma 14.6.1

### Ryujinx version

1.1.1379

### Game version

1.2.1

### CPU

Apple M3 Pro

### GPU

Apple M3 Pro

### RAM

18GB

### List of applied mods

No mods or patches

**Comment by MetrosexualGarbodor** [comment]
macOS crash reports are not useful, Ryujinx logs are in File > Open Ryujinx folder. Please join Discord for general support.
