### ISSUE TITLE
Refresh Button for "Games Loaded" Resets All Games Version When Clicked

### ISSUE THREAD

**Issue by lexyeal** [Ryujinx/Ryujinx#7249]
### Description of the issue

When I click the Refresh Icon/Button, next to "xx/xx Games Loaded" all games version in my library got reset back to version 1.0.0

### Reproduction steps

1. Launch Ryujinx
2. Hover to Refresh Button/Icon
3. Click Refresh Button/Icon
4. All loaded games' version reset back 1.0.0

### Log file

[Ryujinx_1.1.1379_2024-08-26_22-05-01.log](https://github.com/user-attachments/files/16750929/Ryujinx_1.1.1379_2024-08-26_22-05-01.log)
[Ryujinx_1.1.1379_2024-08-26_22-45-20.log](https://github.com/user-attachments/files/16750930/Ryujinx_1.1.1379_2024-08-26_22-45-20.log)
[Ryujinx_1.1.1379_2024-08-26_21-41-36.log](https://github.com/user-attachments/files/16750931/Ryujinx_1.1.1379_2024-08-26_21-41-36.log)

### OS

Windows 11

### Ryujinx version

1.1.1379

**Comment by lexyeal** [comment]
+++ adding screenshots for reference
![image](https://github.com/user-attachments/assets/9ef700fe-2d82-487d-a2d5-1302cedb5324)

**Comment by MetrosexualGarbodor** [comment]
Can't reproduce. 
https://github.com/user-attachments/assets/b7dfeb73-9a3b-408d-9539-c532c8749cab

**Comment by lexyeal** [comment]
I tried to reproduce, seems the issue isn't recurring for my side anymore:
[screen-capture-Ryujinx-Issue-Fixed.webm](https://github.com/user-attachments/assets/114bcf78-4c2d-4bf5-8cc6-b97a0b5ce142)

I will close this ticket, apologies for the confusion. Thanks!
