### ISSUE TITLE
Don't have the prod.keys

### ISSUE THREAD

**Issue by Crockscheats** [Ryujinx/Ryujinx#7257]
### Description of the issue

I don't have the prod.keys i tried to do the tutorial but nothing

### Reproduction steps

1 opened ryujinx
2 go to the system folder
3 check for prod.keys

### Log file

00:00:00.085 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.088 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.099 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.100 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.101 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.330 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.331 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.334 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.341 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.341 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.341 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.341 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.341 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.343 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.344 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.344 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.344 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.344 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.344 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.344 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.345 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.345 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.348 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.348 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.348 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.348 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.349 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.564 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1380
00:00:00.570 |N| Application Print: Operating System: Microsoft Windows 10.0.26120 (X64)
00:00:00.570 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz ; 8 logical
00:00:00.573 |N| Application Print: RAM: Total 7.7 GiB ; Available 1.1 GiB
00:00:00.578 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.579 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

wi 11

### Ryujinx version

1.1.1380

### RAM

8GB

### List of applied mods

nothing

### Additional context?

no

**Comment by MetrosexualGarbodor** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/Keys
