### ISSUE TITLE
[Bug ] In Hogwarts Legacy, Version 1.0.2 in Vulkan mode the game fps is amost always at 0fps in cutscenes. Any fix for this  ?

### ISSUE THREAD

**Issue by krishna134** [Ryujinx/Ryujinx#7258]
### Description of the issue

In Hogwarts Legacy, Version 1.0.2 in Vulkan mode the game fps is amost always at 0fps in cutscenes. Any fix for this ?

### Reproduction steps

In Hogwarts Legacy, Version 1.0.2 in Vulkan mode the game fps is amost always at 0fps in cutscenes. Any fix for this ?

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.1380 

### Game version

1.0.2

### CPU

i5-10400f

### GPU

GTX 1650

### RAM

16GB

**Comment by IsaacMarovitz** [comment]
Duplicate of #6905
