### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by m-chomiczewski** [Ryujinx/Ryujinx#7259]
### Description of the issue

Mario Kart 8 Deluxe crashes the emulator on load

### Reproduction steps

start Mario Kart 8 Deluxe, observe the emulator crash

### Log file

00:00:00.032 |I| Gpu : Backend Threading (Auto): True
00:00:00.330 |N| Application LoadGuestApplication: Using Firmware Version: 18.0.0
00:00:00.330 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.350 |I| ModLoader QueryContentsDir: Searching mods for Application 0100152000022000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.350 |I| ModLoader QueryContentsDir: Searching mods for Application 0100152000022000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.352 |I| Loader Load: Loading rtld...
00:00:00.357 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.357 |I| Loader Load: Loading main...
00:00:00.438 |I| Loader PrintRoSectionInfo: main:
    Module: E:\home\Project\TurboS_labo\App\Rom\NX32\Product\TurboS.nss
    SDK Libraries: SDK MW+Nintendo+PiaCommon-5_6_4
                   SDK MW+Nintendo+Pia-5_6_4
                   SDK MW+Nintendo+NEX-4_3_2-apptrbs
                   SDK MW+Nintendo+NintendoSDK_gfx-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_G3d-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Atk-4_4_0-Release
                   SDK MW+Nintendo+PiaInet-5_6_4
                   SDK MW+Nintendo+PiaNat-5_6_4
                   SDK MW+Nintendo+PiaLan-5_6_4
                   SDK MW+Nintendo+PiaSession-5_6_4
                   SDK MW+Nintendo+PiaTransport-5_6_4
                   SDK MW+Nintendo+PiaLocal-5_6_4
                   SDK MW+Nintendo+NintendoSDK_libcurl-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Font-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-4_4_0-Release
                   SDK MW+Nintendo+NEX_MM-4_3_2
                   SDK MW+Nintendo+NEX_DS-4_3_2
                   SDK MW+Nintendo+NEX_RK-4_3_2
                   SDK MW+Nintendo+NintendoSDK_libz-4_4_0-Release
00:00:00.438 |I| Loader Load: Loading subsdk0...
00:00:00.457 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-4_4_0-Release
00:00:00.457 |I| Loader Load: Loading sdk...
00:00:00.487 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 4.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-4_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-4_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-4_4_0-Release
00:00:00.572 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.580 |I| Loader LoadNsos: Loading image 0 at 0x0000000000700000...
00:00:00.581 |I| Loader LoadNsos: Loading image 1 at 0x0000000000704000...
00:00:00.585 |I| Loader LoadNsos: Loading image 2 at 0x000000000149a000...
00:00:00.587 |I| Loader LoadNsos: Loading image 3 at 0x0000000001a68000...
00:00:00.591 |I| ModLoader LoadCheats: Build ids found for application 0100152000022000:
    392D5F620063DCF173BD5C4EA2DE7D46733A7184000000000000000000000000
    37E682117C50D7B015162017F378DF7200000000000000000000000000000000
    EA3F2A9B705EEF46ED08414F88C49ECF2559B4FB000000000000000000000000
    F0D9307B48E4E8F147A40E44A9CBC555D4C6148F000000000000000000000000
00:00:00.594 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.684 |I| Loader Start: Application Loaded: Mario Kart 8 Deluxe v1.6.0 [0100152000022000] [32-bit]
00:00:00.732 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:01.211 |N| GUI.RenderThread Gpu PrintGpuInformation: AMD AMD Radeon RX 6900 XT (Vulkan v1.3.280, Driver v2.0.302)
00:00:01.218 |I| GPU.MainThread Gpu LoadShaders: Loading 963 shaders from the cache...
00:00:02.188 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.734 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:02.805 |S| HLE.OsThread.47 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.893 |S| HLE.OsThread.47 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.905 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.913 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:03.003 |S| HLE.OsThread.47 ServicePctl Initialize: Stubbed. 
00:00:04.735 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:05.059 |S| HLE.OsThread.4 ServiceNv FinishInitialize: Stubbed. 
00:00:05.120 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.603 |S| HLE.OsThread.4 ServiceNv InitializeEx: Stubbed. 
00:00:05.737 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.810 |S| HLE.OsThread.4 ServiceNv SetNvMapFd: Stubbed. 
00:00:05.811 |S| HLE.OsThread.4 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:05.812 |S| HLE.OsThread.4 ServiceNv AllocObjCtx: Stubbed. 
00:00:05.814 |S| HLE.OsThread.4 ServiceNv SetTimeout: Stubbed. 
00:00:05.817 |S| HLE.OsThread.4 ServiceNv SetErrorNotifier: Stubbed. 
00:00:05.818 |S| HLE.OsThread.4 ServiceNv SetUserData: Stubbed. 
00:00:05.821 |S| HLE.OsThread.4 ServiceNv SetPriority: Stubbed. 
00:00:05.833 |S| HLE.OsThread.4 ServiceNv ZcullBind: Stubbed. 
00:00:06.097 |S| HLE.OsThread.3 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:06.108 |S| HLE.OsThread.3 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 0}
00:00:06.119 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:06.127 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:06.131 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadIdType: Stubbed. 5 Players: Player1,Player2,Player3,Player4,Handheld
00:00:06.318 |S| HLE.OsThread.47 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72080821221203968}
00:00:06.345 |S| HLE.OsThread.3 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:06.735 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Handheld'
00:00:06.737 |I| HLE.OsThread.47 ServiceAm SetTerminateResult: Result = 0x0007d402 (ResultFsTargetNotFound (2002-1002)).
00:00:06.835 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Mario Kart 8 Deluxe, PID: 127
   0x0000000001ab2148	sdk:0x4a148	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   0x0000000001ab21b0	sdk:0x4a1b0	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   0x0000000001ad6bf4	sdk:0x6ebf4	nn::fs::MountSaveData(char const*, nn::fs::UserId):0x0104
   0x0000000001bac5b0	sdk:0x1445b0	nn::fs::MountSaveData(char const*, nn::account::Uid const&):0x0044
   0x0000000000f117d4	main:0x80d7d4	

00:00:06.836 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x000000000219f5c0
	X[05]:	0x000000000219f5c0
	X[06]:	0x000000000219f5c0
	X[07]:	0x0000000000000000
	X[08]:	0x00000000003089c0 (SP:-0x3089c0)
	X[09]:	0x00000000012fb63b
	X[10]:	0x00000000013bf110
	X[11]:	0x00000000003089b8 (SP:-0x3089b8)
	X[12]:	0x0000000001ab31b0 (sdk:0x4b1b0)	=> nn::diag::detail::Abort()
	X[13]:	0x00000000003089b8 (SP:-0x3089b8)
	X[14]:	0x0000000001ab31c8 (sdk:0x4b1c8)	=> nn::diag::detail::Abort():0x0018
	X[15]:	0x0000000000000000
	X[16]:	0x0000000000000000
	X[17]:	0x0000000000000000
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000000000000000
	LR:	0x0000000000000000
	SP:	0x0000000000000000
	PC:	0x0000000001b2884c (sdk:0xc084c)	=> 

00:00:06.843 |W| HLE.GuestThread.48 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.843 |W| HLE.GuestThread.53 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.843 |W| HLE.GuestThread.49 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.844 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.844 |W| HLE.GuestThread.55 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.844 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.844 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:06.889 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1899
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break32(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\obj\Release\net8.0\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1795
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch32(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\obj\Release\net8.0\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3236
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 34
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1380

### Game version

1.6.0

### CPU

AMD Ryzen 5 5600X

### GPU

AMD Radeon RX 6900 XT (Vulkan v1.3.280, Driver v2.0.302)

### RAM

32GB

### Additional context?

same happens with Super Smasch Bros. Ultimate

**Comment by MetrosexualGarbodor** [comment]
The emulator can't find your save directories. Check for permission issues.

In the future please use Discord for support.
