### ISSUE TITLE
[Bug] ToTK Crashing in Ranch Ruins Cave

### ISSUE THREAD

**Issue by Vetnas** [Ryujinx/Ryujinx#7263]
### Description of the issue

Whilst playing TOTK, I've started to experience crashing once I've finished the sky islands and am now on the ground exploring. Surprisingly, the crash is happening in a specific spot in Ranch Ruins Cave. I've been checking to see what others have tried and so far I've attempted recompressing shaders and swapping from vulkan to openGL (Separately from eachother to try and isolate a fix but no dice).
![image](https://github.com/user-attachments/assets/943d59e1-4e0c-4b42-9822-3a2c1a17119b)
As you reach the slope just above links head in the picture ^^ the game freezes for a moment and crashes. This crash is consistent and replicable as it's happened 5 times to me over the course of half an hour.

**SIDE NOTE** In the log file area i could not actually put in the large log file as its **8.3GB** (i cant even open it using notepad) but i did put in the log file that seems to show (to my knowledge) the logs of myself entering the cave and killing the Horablin. I can't read logs for the life of me so its only an uneducated assumption.

### Reproduction steps

Enter Ranch Ruins Cave, kill the horablin on the ceiling of the cave and make your way up to the right (past the hole on the left). As you reach the opening, on the slope the crash seems consistent.

### Log file

[Ryujinx_1.1.1382_2024-09-01_21-34-43.log](https://github.com/user-attachments/files/16828790/Ryujinx_1.1.1382_2024-09-01_21-34-43.log)

### OS

Windows 11

### Ryujinx version

18.1.0

### Game version

1.2.0

### CPU

12th Gen Intel i5 - 12600KF

### GPU

NVIDIA GEFORCE RTX 2080 SUPER

### RAM

32GB

### List of applied mods

DynamicFPS (suited for 1.2.0)
DynamicFPS - 60FPS option

**Comment by piplup55** [comment]
your game file is [corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), redump it from your switch
