### ISSUE TITLE
[Bug] Ryujinx Version 1.1.1385 Crashing on Game Launch (macOS Sonoma 14.6.1)

### ISSUE THREAD

**Issue by Lrdnd** [Ryujinx/Ryujinx#7276]
### Description of the issue

     Crash every games at launching

### Reproduction steps

Hello Ryujinx Support Team,

I’m experiencing an issue with Ryujinx version 1.1.1385 on macOS Sonoma 14.6.1. Every time I try to launch any game, the emulator crashes immediately. I’ve already attempted to disable the Game Mode, but it didn’t resolve the issue.

Could you please assist in troubleshooting this problem? I would appreciate any guidance or suggestions you can provide.

Thank you for your support.

Best regards,

### Log file

Date/Time:        2024-09-03 17:46:21.730 +0200
End time:         2024-09-03 17:46:35.634 +0200
OS Version:       macOS 14.6.1 (Build 23G93)
Architecture:     arm64e
Report Version:   49
Incident Identifier: 3C84C424-50B3-4757-980C-FA2564EC926E

Data Source:      Stackshots
Shared Cache:     BB3DF3D3-38BD-304C-9233-E43DE95F1903 slid base address 0x187404000, slide 0x7404000 (System Primary)
Shared Cache:     4FBCE036-4B8B-3F24-954D-E2C0E9F9CC90 slid base address 0x7ff803f28000, slide 0x3f28000 (Rosetta)
Shared Cache:     0C2DD6B0-863D-3E0A-BC10-5889134A1A45 slid base address 0x18ff6c000, slide 0xff6c000 (DriverKit)

Command:          Ryujinx
Path:             /Applications/Ryujinx.app/Contents/MacOS/Ryujinx
Identifier:       org.ryujinx.Ryujinx
Version:          1.1 (1.1.0)
Is First Party:   No
Beta Identifier:  D96850FC-FAF3-5D5C-AABE-A87DDBD5155D
Architecture:     x86_64 (translated)
Parent:           launchd [1]
PID:              11804
Time Since Fork:  20s

Event:            hang
Duration:         13.90s
Duration Sampled: 2.10s (process was unresponsive for 12 seconds before sampling)
Steps:            21 (100ms sampling interval)

Hardware model:   MacBookPro18,3
Active cpus:      8
HW page size:     16384
VM page size:     16384
Boot args:        kext-dev-mode=1 -arm64e_preview_abi

Time Since Boot:  115191s
Time Awake Since Boot: 11714s
Time Since Wake:  2092s

Fan speed:        0 rpm
Total CPU Time:   3.765s (5.9G cycles, 6.8G instructions, 0.87c/i)
Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  218.01 GB/460.43 GB, low space threshold 3072 MB
Vnodes Available: 53.96% (135335/250797)

Preferred User Language: fr-FR
Country Code:     FR
Keyboards:        French
OS Cryptex File Extents: 1

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting

### OS

  Sonoma 14.6

### Ryujinx version

1.1.1385 

### Game version

firmware 18.0.0

### CPU

M1 pro

### GPU

M1 pro

### RAM

16

**Comment by MetrosexualGarbodor** [comment]
Don't use Rosetta. In the future please use Discord for troubleshooting.
