### ISSUE TITLE
[Bug] Ryujinx completely messes with my Windows OS

### ISSUE THREAD

**Issue by DaddyDiegoBrando** [Ryujinx/Ryujinx#7284]
### Description of the issue

As the title says. I've had ryujinx running for months now without issues and even yesterday i was able to use it to play games. Now when I try to open the EMULATOR APP, it messes with my OS. Giving me error messages like "Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between (another app) and other desktop customisation software or Windows. the other app being a live wallpaper app which tbf isn't the best but that's besides the point. It keeps popping this error up over and over and whenever I press the windows key, that will bug out too and will constantly loop between opening and closing. I haven't done ANYTHING nor installed anything within the past few weeks so there's not much information i can give to replicate the bug. I have no idea what is causing this. I will do a fresh install of ryujinx and i will update the situation

https://github.com/user-attachments/assets/eae7bdff-bc11-4e13-97e3-7273f9261d33

### Reproduction steps

I opened the emulator and it just started going haywire. nothing else i can do to describe what was done

### Log file

[Ryujinx_1.1.1385_2024-09-04_21-17-03.log](https://github.com/user-attachments/files/16880634/Ryujinx_1.1.1385_2024-09-04_21-17-03.log)

### OS

Windows 11

### Ryujinx version

1.1.1385

### CPU

i9-11900H

### GPU

NVIDIA RTX 3060 Laptop

### RAM

16GB

### Additional context?

I have Transluscent TB and Lively wallpaper as customisation apps installed and both apps will crash alongside windows getting all buggy with me

**Comment by Candygoblen123** [comment]
Does the fresh install have the wallpaper and stuff, or is it stock windows 11

**Comment by DaddyDiegoBrando** [comment]
no i meant a fresh ryujinx install. but yes i still do have the wallpaper apps, which havent given me an emulator issue before

**Comment by Candygoblen123** [comment]
Try uninstalling the other wallpaper apps and see if the behavior persists.

**Comment by DaddyDiegoBrando** [comment]
crap, yeah im in the insider programme so that could explain it. ive opted to unenroll my device after the next latest official build and ill update when it happens. Thank You!

**Comment by DaddyDiegoBrando** [comment]
I have come back to thank you for helping me. I rolled back to an official update of windows 11 and that solved the issue. I cant thank you enough!
