### ISSUE TITLE
[Bug] Ryujinx Now crashing explorer, jerking movements with mouse and etc.

### ISSUE THREAD

**Issue by dece870717** [Ryujinx/Ryujinx#7286]
### Description of the issue

Have no idea whats going on but I try to open it and background starts flashing black, mouse movements are jerky and slow, explorer seems to be in state of constant crashing, program is totally unusable. All alternative Switch emulators work fine. (EDIT: Older versions are doing the same so it must be something with my setup, but still odd that this is the only emulator or even application that's doing this.

Video capture https://drive.google.com/file/d/1e8zxxNL0BSSqt2qeD0nAF1GUIXiT_wtJ/view?usp=sharing

### Reproduction steps

Have no idea!

### Log file

Logs
00:00:00.158 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.162 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.162 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.163 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.163 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.163 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.164 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2782
00:00:00.164 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.165 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.165 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.165 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.166 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.166 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.166 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.166 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.166 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.166 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.166 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.166 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.166 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.166 |I| Configuration LogValueChange: AudioBackend set to: Dummy
00:00:00.166 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.167 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.167 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.167 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.167 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.169 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.171 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1385
00:00:00.174 |N| Application Print: Operating System: Microsoft Windows 10.0.22635 (X64)
00:00:00.174 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i7-13700K ; 24 logical
00:00:00.175 |N| Application Print: RAM: Total 31.7 GiB ; Available 24.3 GiB
00:00:00.177 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.177 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

Windows 11 Pro

### Ryujinx version

Ryujinx_1.1.1385

### Game version

irrelevant

### CPU

i7-13700K

### GPU

Nvidian RTX 4070 Ti

### RAM

12GB

### List of applied mods

I've deleted the entire appdata folder for Ryujinx and its done nothing to change anything.

**Comment by MetrosexualGarbodor** [comment]
https://github.com/Ryujinx/Ryujinx/issues/7284#issuecomment-2330076192
