### ISSUE TITLE
[Bug] Ryujinx is flagged as a virus by Dr web

### ISSUE THREAD

**Issue by i0x404** [Ryujinx/Ryujinx#7302]
### Description of the issue

Dr Web keeps flagging ryujinx as a virus and deleting the executable

### Reproduction steps

.

### Log file

.

### OS

Windows

### Ryujinx version

1.1.1385

**Comment by MetrosexualGarbodor** [comment]
Not a Ryujinx issue, stop using third party antivirus software.
