### ISSUE TITLE
[Bug] Latin American Spanish Bug

### ISSUE THREAD

**Issue by dokkoriax** [Ryujinx/Ryujinx#7308]
### Description of the issue

Whenever i try to use Latin American Spanish in the system settings, the game Unicorn Overlord USA v1.0.5 starts in English, instead of Spanish. The problem can be solved partially if i select European Spanish. But some games have both languages (European and Latin American Spanish). I have encountered this bug since a year ago, thinking it would be resolved. So, i decided to report it.

### Reproduction steps

Open Options - Settings - System:

System Region: USA, System Language: Latin American Spanish

Open a Game such as Unicorn Overlord USA v1.0.5, and the game loads in English instead of Spanish. My Switch Lite is with Latin American Spanish Setting, and when the game loads, you can see the game in Spanish Correctly. A workaround to the bug is If i select European Spanish (Spanish) in Settings-System in Ryujinx, and the game loads in Spanish Correctly.

### Log file

[Ryujinx_1.1.1386_2024-09-13_13-16-25.log](https://github.com/user-attachments/files/16998543/Ryujinx_1.1.1386_2024-09-13_13-16-25.log)

### OS

Windows 11

### Ryujinx version

1.1.1386

### Game version

1.0.5

### CPU

AMD Ryzen 9 5900HS with Radeon Graphics

### GPU

RTX 3080 Laptop GPU

### RAM

RAM: Total 47.4 GiB ; Available 32 GiB

**Comment by piplup55** [comment]
this is not a bug, the game does not support the requested language
```00:00:06.035 |I| HLE.OsThread.47 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using AmericanEnglish```

**Comment by gdkchan** [comment]
It might be a bug if the Switch does actually fallback to European Spanish if Latin American Spanish is not supported. I'm not sure if it does that, though.
