### ISSUE TITLE
[Bug] Breath of the wild crashes upon capturing any terminal in divine beast vah naboris!

### ISSUE THREAD

**Issue by drakeshadeslayer** [Ryujinx/Ryujinx#7315]
### Description of the issue

so whenever capturing any terminal in divine beast vah naboris after getting the map, it will crash as soon as you finish the dialogue. im unable to continue the game due to this game breaking bug.

### Reproduction steps

get map of divine beast>capture any terminal within divine beast vah naboris>game crashes after finishing the dialogue stating there are number of terminals left.

### Log file

[Ryujinx_1.1.1388_2024-09-15_20-25-57.log](https://github.com/user-attachments/files/17008085/Ryujinx_1.1.1388_2024-09-15_20-25-57.log)

### OS

windows 11

### Ryujinx version

1.1.1388

### Game version

1.60

### CPU

AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz

### GPU

AMD Radeon RX 5500

### RAM

32GB

**Comment by ekuland** [comment]
> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!

Your game dump is corrupted redump it and the update.
