### ISSUE TITLE
[Bug] Pokemon Legends Arceus Cheats don't work

### ISSUE THREAD

**Issue by i0x404** [Ryujinx/Ryujinx#7317]
### Description of the issue

Hello,
I've been using another switch emulator to play pokemon legends arceus, but due to that emulator stopped development I had to switch to ryujinx than I found out that cheats don't work as they were before (none of them), the game is the same I didn't update it and cheat still work on that other switch emu but not ryujinx.

### Reproduction steps

Just adding the cheats (without even enabling them) gives the error in the log file.
When I enable any cheat the emulator slows down a lot an the cheats doesn't even work.

### Log file

[Ryujinx_1.1.1388_2024-09-16_02-35-40.log](https://github.com/user-attachments/files/17020262/Ryujinx_1.1.1388_2024-09-16_02-35-40.log)

### OS

Windows 10

### Ryujinx version

1.1.388

### Game version

PLA v1.1.1

**Comment by ekuland** [comment]
There are a lot of broken cheats being loaded,
you seem to be pausing and trying to enable cheats which doesn't work, they have to be enabled before you boot the game.
Nothing else seems wrong besides the slow hardware.

And if it works without the cheats, but has issues with them...

**Comment by i0x404** [comment]
the same "broken" cheats works well with y*zu, and I said that before even trying to enable them I get errors just when booting the game. and I tried to enable them before I start but they don't work they just slow down the emulation which never happened with y*zu.
