### ISSUE TITLE
[Bug] Minimum SDK?

### ISSUE THREAD

**Issue by Tatsh** [Ryujinx/Ryujinx#7324]
### Description of the issue

We want to [add the latest version](https://github.com/gentoo/gentoo/pull/38621) to Gentoo's repository but currently we cannot release 8.0.401 of the .NET SDK. With the 8.0.108 SDK, a lot of CS0535 errors appear. What caused the requirement to be bumped up to >8.0.108? Is there a simple change to make it build with the older SDK?

### Reproduction steps

1. Build project with .NET SDK 8.0.108

### Log file

See errors here: [build.log](https://github.com/user-attachments/files/17042378/build.log)

### OS

Linux

### Ryujinx version

1.1.388

**Comment by Ati1707** [comment]
> What caused the requirement to be bumped up to >8.0.108?

.NET 8 release. Basically (almost)every new major release offers some sort of performance improvement or feature that can be helpful for the emulator.
Example of the performance improvement by migrating to .NET 8:
https://github.com/Ryujinx/Ryujinx/pull/5887#issuecomment-1804555894

**Comment by TSRBerry** [comment]
Are you able to downgrade the `Microsoft.CodeAnalysis.CSharp` dependency in [Directory.Packages.props](https://github.com/Ryujinx/Ryujinx/blob/master/Directory.Packages.props) and get it to build that way?

**Comment by Tatsh** [comment]
@TSRBerry that did it. Thanks!
