### ISSUE TITLE
[Bug] Ryujinx restarts explorer.exe after last update (Windows 11)

### ISSUE THREAD

**Issue by BearLV** [Ryujinx/Ryujinx#7327]
### Description of the issue

Launching Ryujinx on newest update (1.1.1393) makes explorer.exe crash and restart loop. Everything is very laggy. I have opened games like Pokemon Let's Go, Pikachu! and there seems to be no problems other than compiling shaders. After exiting Ryujinx everything turns back to normal. Task manager shows that explorer tries to come up back closes after a second. Also if you try to open file explorer, it closes down in a second. 

### Reproduction steps

Launch Ryujinx 1.1.1393 on Windows 11 computer and wait a second. 

### Log file

[Ryujinx_1.1.1393_2024-09-18_18-30-09.log](https://github.com/user-attachments/files/17046586/Ryujinx_1.1.1393_2024-09-18_18-30-09.log)
[Ryujinx_1.1.1393_2024-09-18_18-36-42.log](https://github.com/user-attachments/files/17046587/Ryujinx_1.1.1393_2024-09-18_18-36-42.log)
[Ryujinx_1.1.1393_2024-09-18_18-39-51.log](https://github.com/user-attachments/files/17046588/Ryujinx_1.1.1393_2024-09-18_18-39-51.log)

### OS

Windows 11 Pro 23H2 

### Ryujinx version

1.1.1393

### Game version

any

### CPU

AMD Ryzen 5 2600

### GPU

MSI AMD Radeon RX 5700XT Mech OC

### RAM

32 GB 3200mhz XMP enabled.

### List of applied mods

none

### Additional context?

System has newest updates, nothing is overclocked. Just the RAM with XMP profile in BIOS. 

I will try to reinstall this version right now. If this happens again, I will try to install older version of Ryujinx.

**Comment by ekuland** [comment]
Windows 11... Insider builds?
There is a known issue with the insider builds themselves that explorer crashes.

**Comment by BearLV** [comment]
I tried to look and didn't see anything for similar post. 
Is there any way to fix this or rolling back to older version is my best chance?
By the way, thank you for the fast reply.

**Comment by ekuland** [comment]
This is a _**windows insider**_ issue - this issue has been occurring on any build on insider. As far as I know you can only roll out of insider on the next update to it, or by nuking your windows install.

**Comment by BearLV** [comment]
Oh, I didn't even thought of that. 
Strange That I have installed insider for more than a year and this is first time happening. 
By the way, reinstall didn't help. Installed older version 1.1.1392 and Ryujinx doesn't launch fully, after terminal shows Ryujinx windows and it instantly becomes unresponsive. Doesn't seem to become responsive again. I will try to roll back few versions and find where the last working version for me is. 
Thank you for your fast responses.

**Comment by BearLV** [comment]
I don't see any versions that runs which is very strange. 
Waiting for new upgrade seems to will be taking a long time. I better just reinstall Windows. 
Can I ask where is the savegame files located?
I would like not to lose my savegames. 
Thank you.

**Comment by ekuland** [comment]
Just backup your entire %appdata%\Ryujinx folder tbh.
Please join [the discord](https://discord.gg/ryujinx) for any further support.
