### ISSUE TITLE
[Bug] Prince of Persia: The lost Crown with the Mask of Darkness DLC Crashing on UBISOFT logo

### ISSUE THREAD

**Issue by veex93** [Ryujinx/Ryujinx#7328]
### Description of the issue

The game is Crashing on the first screen while using the new Mask of Darkness DLC

With only the update 1.4, the games works.

EDit: Forgot to mention that i updated the Firmware to 1.7.1 and the Keys.

### Reproduction steps

Just start the game with the DLC

### Log file

[Ryujinx_1.1.1394_2024-09-18_17-39-35.log](https://github.com/user-attachments/files/17050284/Ryujinx_1.1.1394_2024-09-18_17-39-35.log)

### OS

Windows 10

### Ryujinx version

1.1.1394

### Game version

1.4

### CPU

R5 5600

### GPU

RTX 3060ti

### RAM

32Gb

### Additional context?

I have depression and i'm smelly

**Comment by hachiman316** [comment]
Did you find a fix? I have integrated graphics with the same issue.

**Comment by Ribiru19** [comment]
Me, too. Tried it in both Yuzu and Ryujinx. The file may be broken.

**Comment by hachiman316** [comment]
Do other people have it working on their high end system? If so then it might not be possible to play the DLC. I never managed to boot into MP Remastered from  play game to actual gameplay

**Comment by Rombolian** [comment]
I had the same issue, but it works for me after updating firmware and keys to v18.0

**Comment by piplup55** [comment]
according to the log you posted you are missing keys, redump your keys and dlc from your switch, if you still have this issue you can try title overide (hold R when booting a game) or join the [discord](https://discord.gg/ryujinx) for further support

**Comment by hachiman316** [comment]
Worked for me..yippe.. Update the firmware and keys to 18.00

**Comment by veex93** [comment]
> according to the log you posted you are missing keys

Welp... For some reason the past me made TWO Ryujinx folders, and with you pointing that out, i could snuff it

So my Keys were on the C:\ Folder I made. and not the Appdata.

Now with the Keys and updated Firmware to the 18.1.0, it's Working for now.

Thx for pointing that out @piplup55, cheers!
