### ISSUE TITLE
[Feature Request] Bypass gyroscope requirements for certain games

### ISSUE THREAD

**Issue by watermel0l** [Ryujinx/Ryujinx#7330]
### Overview

some games require gyroscope input to finish a level or continue with a storyline. People playing with a gyrosocpe-less controller or a keyboard experience an issue. 

### Smaller details

dunno

### Nature of request

spoofing gyro input without required hardware

### Why would this feature be useful?

This is useful for people who play with their keyboard or gyroless controller

**Comment by MutantAura** [comment]
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3749
