### ISSUE TITLE
[Bug]Pokemon Sword is crashing just after the Game Freak logo flashes on screen

### ISSUE THREAD

**Issue by SkinnyDog3353096** [Ryujinx/Ryujinx#7341]
### Description of the issue

As the game is loading the shaders will compile and the game wil start to open and just after the logo leaves the screen the game exits and ryujinx brings up a crash report.

### Reproduction steps

Open Pkmn Sword through ryujinx and wait for it to load and then it will exit.

### Log file

No log file was created when these crashes happened.

### OS

MacOS 14.5

### Ryujinx version

1.1.1398

### Game version

1.0.0

### CPU

M2

### GPU

M2

### RAM

16GB

### List of applied mods

none

**Comment by MetrosexualGarbodor** [comment]
Please join Discord for support and don't disable logging.
