### ISSUE TITLE
[Bug] Don't open

### ISSUE THREAD

**Issue by rut3k4** [Ryujinx/Ryujinx#7342]
### Description of the issue

it doesn't open, it just open this page

### Reproduction steps

open ryujinx 

### Log file

![error](https://github.com/user-attachments/assets/b82bdc3a-75f3-4240-8228-4ec2921752ce)

### OS

windows 10

### Ryujinx version

1.1.139

### Game version

no

### CPU

¡7-6700

### GPU

NVIDIA RTX 2070

### RAM

16GB

### List of applied mods

none

### Additional context?

i used a save editor for the totk and it ryujinx dind't open, I deleted it to see if the error dissappeared but is still there

**Comment by GamerzHell9137** [comment]
For support queries join [Discord ](https://discord.gg/VkQYXAZ)
