### ISSUE TITLE
[Feature Request] Emulate eshop in Ryujinx

### ISSUE THREAD

**Issue by birdmanmandbir** [Ryujinx/Ryujinx#7351]
### Overview

Can we emulate the eShop in Ryujinx? If so, we could legally download our purchased digital games and DLCs directly from the eShop. This would make Ryujinx a complete digital version of the Switch.

### Smaller details

I don't know

### Nature of request

In light of the recent lawsuit from Nintendo(Mig, LiberiaShop, Yuzu), emulate eShop on Ryujinx would offer a legal and straightforward way for players to access their digital games directly.

### Why would this feature be useful?

It makes the switch emulator easier to access and reduces the risk of lawsuits.

**Comment by MetrosexualGarbodor** [comment]
There are no plans to connect to Nintendo servers, no matter the use case.
