### ISSUE TITLE
[Bug]Can not  use Intel UHD Graphics to play switch sports

### ISSUE THREAD

**Issue by lggramz990** [Ryujinx/Ryujinx#7356]
### Description of the issue

I hope Ryujinx can be improved by Intel UHD Graphics to play switch sports only use OpenGL api.When i open the game,it is normal，but text displayed as black blocks.After entering the selection menu the simulator crashes.

### Reproduction steps

open the game

### Log file

[Ryujinx_1.1.1385_2024-09-25_13-44-42.log](https://github.com/user-attachments/files/17126145/Ryujinx_1.1.1385_2024-09-25_13-44-42.log)

### OS

window11

### Ryujinx version

1.1.1385

### Game version

1.5.0

### CPU

i3 12100

### GPU

UHD730

### RAM

32GB DDR4

**Comment by ekuland** [comment]
This game does not work without changes to the emulator that aren't complete. 

Please post game specific issues on their thread in the gamelist, if not already there.

[Game post here.](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4079)
[Needed changes here.](https://github.com/Ryujinx/Ryujinx/pull/4047)
