### ISSUE TITLE
[Bug] The Legend of Zelda : Echoes of Wisdom - Black rendering

### ISSUE THREAD

**Issue by pacoa-kdbg** [Ryujinx/Ryujinx#7360]
### Description of the issue

Rendering is not right, fire is fine 
![image](https://github.com/user-attachments/assets/93999bf9-2d38-49ad-93cd-5c1a4db74cdf)

### Reproduction steps

RDNA3 (8840U) 
Bazzite 
Install the game and launch it using Vulkan

### Log file

[Ryujinx_1.1.1398_2024-09-25_15-59-11.log](https://github.com/user-attachments/files/17139465/Ryujinx_1.1.1398_2024-09-25_15-59-11.log)

### OS

Bazzite

### Ryujinx version

1.1.1398

### Game version

1.0.1

### CPU

Ryzen 7 8840U

### GPU

780M

### RAM

32GB

**Comment by GamerzHell9137** [comment]
If its not a regression then issues like these are reported on the compatibility list of the game.

https://github.com/Ryujinx/Ryujinx-Games-List/issues/5070

**Comment by pacoa-kdbg** [comment]
Closing this in favor of the "Compatibility list"

**Comment by GamerzHell9137** [comment]
> Closing this in favor of the "Compatibility list"

Click on the close button below.
