### ISSUE TITLE
[Bug]TOTK game crashes as I approach hyrule castle

### ISSUE THREAD

**Issue by CrackedTurnip** [Ryujinx/Ryujinx#7381]
### Description of the issue

Everytime i go towards the direction of hyrule castle, game just freezes then crashes. In the logs there is this error constantly coming up: " Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation."

### Reproduction steps

Go in the direction of hyrule castle

### Log file

[Ryujinx_1.1.1402_2024-09-30_18-02-48.log](https://github.com/user-attachments/files/17197015/Ryujinx_1.1.1402_2024-09-30_18-02-48.log)
[Ryujinx_1.1.1402_2024-09-30_18-08-23.log](https://github.com/user-attachments/files/17197016/Ryujinx_1.1.1402_2024-09-30_18-08-23.log)
[Ryujinx_1.1.1402_2024-09-30_18-13-49.log](https://github.com/user-attachments/files/17197017/Ryujinx_1.1.1402_2024-09-30_18-13-49.log)

### OS

Windows 11

### Ryujinx version

1.1.1398

### CPU

i5-8500

### RAM

32GB

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use Discord for help.
