### ISSUE TITLE
[Feature Request] change store location

### ISSUE THREAD

**Issue by sentix001** [Ryujinx/Ryujinx#7384]
### Overview

Can you pls make ryujinx store saves and gamedata in its own folder like ryujinx us with nvmes space is very important i store the program in an external drive

### Smaller details

Na

### Nature of request

Na

### Why would this feature be useful?

Na

**Comment by ekuland** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#portable-mode

**Comment by sentix001** [comment]
You da man
