### ISSUE TITLE
am IApplicationFunctions: 102 (SetApplicationCopyrightVisibility) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#780]
am IApplicationFunctions: 102 (SetApplicationCopyrightVisibility) is not implemented

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#SetApplicationCopyrightVisibility)
```
Takes an input u8 bool, no output.

Sets the visibility for the image set by #SetApplicationCopyrightImage, in screenshots. By default it's visible.
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/181

**Comment by AcK77** [comment]
Resolved in #921
