### ISSUE TITLE
Per sysmodule IPC buffer sizes

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx#805]
At the moment, all IPC services share the same response buffer size, [`0x1000`](https://github.com/Ryujinx/Ryujinx/pull/803). Whilst this covers 99% of cases, most of the time it's much larger than is actually needed, and sometimes too small.

It seems the official Switch firmware has a set of "fixed" response buffer sizes for each sysmodule, hardcoded in the binary. We should either adopt these on a per module basis, or alternatively find a way to dynamically allocate the response buffer based on the data that needs to fill it.

Thanks to @AcK77, a short list of the response buffer sizes follows:

```
Loader   -> 0x400
Spl      -> 0x800
Hid      -> 0x200
Settings -> 0x100
Ldn      -> 0x1000
NvDrv    -> 0x8000
```

**Comment by AcK77** [comment]
Fixed since #4188, now migrated services have some constants.
