### ISSUE TITLE
Asynchronous GPU

### ISSUE THREAD

**Issue by Ghostotakoi** [Ryujinx/Ryujinx#816]
i have seen in many other emulators like yuzu or rpcs3 they have implemented some kind of Asynchronous GPU to improve the performance making parallel computing on the GPU side, there is any way to implement this on ryujinix? May be on a future? or whenever you guys find the way to do it.

**Comment by gdkchan** [comment]
What exactly are you calling "Asynchronous GPU"? If it's just the processing of gpu commands on a separate thread, to prevent the GPU thread from being blocked while they are processed, then it is already supported (and always enabled).

**Comment by Ghostotakoi** [comment]
@gdkchan sorry I have no how emulators works I just thought it should increase performance, recently you guys have archived an amazing graphical accuracy I am really exited about ryujinix future and wishing the best sadly ryujinix is still far behind of the yuzu performance, not that far tho but having even more graphical accuracy. that's why I thought that some kind of async gpu might slightly increase the performance but if is already implemented then, sorry about my ignorance. I'm closing this issue.
