### ISSUE TITLE
[Linux] Silent crash at boot with non English locale systems

### ISSUE THREAD

**Issue by Leopard1907** [Ryujinx/Ryujinx#817]
Tested on: 1.0.3197 ( non-dev)

Since there is no issue template , i will just write it as clearly as i can.

When you try to boot Ryujinx app it will silently crash on non English locales.

Terminal output when this happens:

`Unhandled exception. System.TypeInitializationException: The type initializer for 'GLib.Object' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Specialized, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Collections.Specialized, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GLib.AbiStruct..ctor(List`1 fields)
   at GLib.Object..cctor()

   --- End of inner exception stack trace ---
   at GLib.Object..ctor(IntPtr raw)
   at GLib.Application..ctor(IntPtr raw)
   at Gtk.Application..ctor(String application_id, ApplicationFlags flags)
   at Ryujinx.Program.Main(String[] args)
İptal edildi (çekirdek döküldü)`

Booting app with LC_ALL=C variable let it successfully boot.

Various documents about it:

http://man7.org/linux/man-pages/man7/locale.7.html

https://doc.qt.io/qt-5/qcoreapplication.html#locale-settings

So it would be good to add a safe value to avoid such problems.

Tested on Mint 19.2 ( Ubuntu 18.04 based )

**Comment by EmulationFanatic** [comment]
@Leopard1907 does this still happen on current builds?

**Comment by LiveLM** [comment]
Just tested 1.0.6774 with a non English locale (pt_BR.UTF-8 UTF-8), Ryujinx starts  up and plays games just fine.

**Comment by Leopard1907** [comment]
As of `Ryujinx Version: 1.0.6787` it is ( booting with variable mentioned above) not needed anymore. Boots just fine on a non English (`tr_TR.utf8`) locale. Closing.
