### ISSUE TITLE
How to deal with this problem

### ISSUE THREAD

**Issue by kokosplok** [Ryujinx/Ryujinx#827]
![1](https://user-images.githubusercontent.com/57860340/69006242-47da6d00-0967-11ea-848a-27da056256c9.png)
### Required by:
Pokémon Sword

**Comment by ReaperOfSouls1909** [comment]
Dump system archives aka nand

**Comment by kokosplok** [comment]
> Dump system archives aka nand

![1](https://user-images.githubusercontent.com/57860340/69009029-4a9b8900-098c-11ea-9266-7b6909415530.png)
have done but without effect

**Comment by emmauss** [comment]
You don't have all your archives. Please dump a complete nand from your switch. Also, the issue tracker is not where you post issues on how to use Ryujinx, please use the discord server for that.

**Comment by kokosplok** [comment]
> 您没有所有的档案。请从交换机中转储完整的nand。另外，问题跟踪器也不是发布有关如何使用Ryujinx的问题的地方，请为此使用Discord服务器。

thx ,sorry,i don't know about it.it's my new use of github

**Comment by emmauss** [comment]
no problem, that's how we manage issues, just ask on our server https://discord.gg/N2FmfVc
