### ISSUE TITLE
Run Switch Games Natively on Jetson Nano

### ISSUE THREAD

**Issue by leocodeninja** [Ryujinx/Ryujinx#828]
My Jetson Nano uses the same exact CPU architecture (Arm64) and uses a GPU with the exact architecture as the Switch. Mine has less CUDA cores though.

How would I port the emulator to my Jetson Nano and allow it to run switch games natively? What type of OS does the switch use?

**Comment by bukyapavankumar** [comment]
Horizon os

**Comment by leocodeninja** [comment]
The Nintendo Switch's Kernel, Horizon/NX , is an example of a microkernel, tailored for their specific use-case, and is in wide use[0]. It is, sadly, closed source, however it has been reverse engineered. Their IPC API is, I believe, pretty smart and elegant:
- There is a per-thread IPC zone of 0x100 bytes. When doing IPC, the request is serialized and put into this. If bigger data than 0x100 bytes is necessary, pointers are passed around, and the Kernel maps it into the process servicing the call. - svcSendSyncRequest is used to call an IPC. It is a synchronous API that will block until the process servicing the call replies to it. - svcReplyAndReceive is used to receive an IPC request and reply to a request, and then wait until a new one is received. The syscalls are "merged" into a single one to avoid the syscall overhead: Almost all svcReply will be followed by an svcReceive, so merging them into a single call makes a lot of sense.

You can find more information about the SVCs at [1] and the IPC layout at [2].

[0] Preempting the "I thought the switch used BSD": wikipedia was wrong, the OS is completely custom, and the kernel is tailor-made

https://news.ycombinator.com/item?id=17534593

**Comment by leocodeninja** [comment]
So if Nvidia where to create a FreeBSD driver for the Nano then switch software could run on it?

**Comment by jduncanator** [comment]
Whilst theoretically possible, a lot of work would need to go into making the platforms compatible. There is more to it than just the hardware matching.

It also wouldn't make sense to port Ryujinx directly to the Jetson Nano, as like you mentioned the hardware being so similar, a hypervisory approach may be better suited.

This is offtopic for the Ryujinx issue tracker. Feel free to ask questions on our Discord, but the crux of the answer is: _No, it's not possible without a **lot** of work_
