### ISSUE TITLE
fatal:u is not implemented thus far.

### ISSUE THREAD

**Issue by tommai78101** [Ryujinx/Ryujinx#83]
Somehow, fatal:u is not implemented. I can understand that fatal:u may not be needed to be implemented, because, it's an actual crash on the target hardware system.

I am hoping that if fatal:u is implemented, there may be some way to see how it is triggering the fatal:u service on the Switch.

The hint I got for seeing a fatal:u is because I'm allocating too much memory on the Switch. But it shouldn't take up too much (25MB at most).

If you have a way to implement fatal:u, that's all I'm reporting about.

**Comment by zoltx23** [comment]
There is most likely a way to catch the program and throw an exception when `fatul:u` is triggered. I am not sure if this is already the case. But it should be, and if it does it'll tell you what caused it (most of the time.)

**Comment by tommai78101** [comment]
Most likely yes, but stepping through the code reveals it just skips most of the modules, and just check if the name is `fatal:u` or not. I'm not quite sure where to set a breakpoint in the code to see where it starts triggering a `fatal:u`. Unless there's a way to see what is triggering it before it interjects with a `fatal:u` string in the name?

**Comment by emmauss** [comment]
if anyone aint working on this yet, I want to take it up.

**Comment by AcK77** [comment]
You feel free to take it ;)! I don’t have plan to implement it!

**Comment by emmauss** [comment]
@tommai78101 if it is homebrew you are trying to use, can upload the nro?

**Comment by tommai78101** [comment]
@emmauss Hello, please wait until I get home from work, which is about 6 hours from now. Sorry for the delay.

**Comment by tommai78101** [comment]
@emmauss Hello again, here is your NRO file for testing.

[fatal_u_test.zip](https://github.com/gdkchan/Ryujinx/files/1926004/fatal_u_test.zip)

**Comment by emmauss** [comment]
i tested it, and your nro throws fatal:u 1 `ThrowFatalWithPolicy` . it is not yet documeted, and the only thing i am sure of is the error code.

**Comment by tommai78101** [comment]
I see. Now I'm curious about the policy... :+1:
