### ISSUE TITLE
Pokemon sword/Ryujnix

### ISSUE THREAD

**Issue by AE89** [Ryujinx/Ryujinx#844]
Ryujnix does not boot.I can't open ryujnix

**Comment by AcK77** [comment]
Hi, this github is for development only. In that case I close this issue.
Feel free to ask for help in our support channel on our Discord server.
Thanks.

**Comment by AE89** [comment]
what means thread?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
15/12/19
21:04:56

Missatge de Ac_K <notifications@github.com> del dia dg., 15 de des. 2019 a
les 20:59:
