### ISSUE TITLE
Support NV_viewport_swizzle

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#862]
The switch GPU support something know as viewport swizzle. It seems to be only supported on NVIDIA GPU. On OpenGL, it is the `NV_viewport_swizzle` extension (more info can be found by reading the extension https://www.khronos.org/registry/OpenGL/extensions/NV/NV_viewport_swizzle.txt).

Currently the GPU only support Y flipping of the viewport Y component, by using ARB_clip_control origin changes.

Currently it performs that check here: https://github.com/Ryujinx/Ryujinx/blob/18814d44b2e19f7a93ed48ef4799ced585d071e9/Ryujinx.Graphics.OpenGL/Pipeline.cs#L722

Ideally, we should remove that check and implement it properly, that is, support swizzle/negation of all the viewport components. When `NV_viewport_swizzle` is supported, we can just call the respective OpenGL function. When it's not supported, it can be emulated on shaders, by passing the information on uniforms, but that could have some perf impact.

Currently it's unknown if/which games do any use of this for anything other than Y-flipping of the viewport. The following games are know to use it with NegateY:

- Axiom Verge
- Celeste

**Comment by Thog** [comment]
Implemented in https://github.com/Ryujinx/Ryujinx/pull/1277
