### ISSUE TITLE
Enable and test GL_EXT_polygon_offset_clamp 

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#865]
When the extension is supported, we can call this directly:
https://github.com/Ryujinx/Ryujinx/blob/18814d44b2e19f7a93ed48ef4799ced585d071e9/Ryujinx.Graphics.OpenGL/Pipeline.cs#L475

We should check if the extension is supported, and if so, do this call, if not, do the one without the clamp parameter and print a warning if clamp != 0 since that is not supported without the extension. The warning should be ideally a lazy warning, that is, print only once, regardless of how many times the funciton is actually called.

Currently there are no know games using it with clamp != 0, so we may need to write a test for this case ourselves.

**Comment by Thog** [comment]
Fixed by https://github.com/Ryujinx/Ryujinx/pull/1429.
