### ISSUE TITLE
Support for Android TV

### ISSUE THREAD

**Issue by ElderJames** [Ryujinx/Ryujinx#940]
It would be awesome if it ran on Android TV!

**Comment by AcK77** [comment]
Hi, for now we don’t plan to port the emulator to Android. Maybe someone will take care of that one day. Until that I close the issue because it’s too early in the project to think about this kind of features.
Feel free to ask for more informations on our Discord server.
Thanks.

**Comment by AyderProgramic** [comment]
If you want a Nintendo switch emulator on Android, then you can pay attention to the "skyline emulator" emulator, this emulator has the only purpose, so that it works on Android
https://github.com/skyline-emu/skyline

**Comment by alexanderadam** [comment]
I just wanted to add that there's [a (closed) Android TV issue for Skyline](https://github.com/skyline-emu/skyline/issues/202) in case anyone is looking for playing Switch games on Android TV.

**Comment by sakuka47** [comment]
With the shield tv, I know how to stream ryujinx and play with a controller (recognized as xbox360 controller), on Android or even on my phone with moonlight
