### ISSUE TITLE
Feature request Add possiblity to load games from Windows Network share

### ISSUE THREAD

**Issue by ruthan** [Ryujinx/Ryujinx#949]
Hello,
i tried present build, but when i try to load game, in left menu, i dont need possiblity to load games form network patch.
  I like it for share my images across more computers, most of emulators supports, it nice space safer.. especially on notebooks.

**Comment by AnderGomez14** [comment]
There is a trick to open the path in the file dialog. Just click CTRL+L and you will be able to enter the path to the file you want. Example: 
![image](https://user-images.githubusercontent.com/11394877/77596819-5f20fc80-6efd-11ea-9400-98e8145cc899.png)
You are here, if you press CTRL+L: 
![image](https://user-images.githubusercontent.com/11394877/77596876-82e44280-6efd-11ea-93c3-60ee9c8988c7.png)

There you can enter the path to the game file

**Comment by EmulationFanatic** [comment]
This is possible already as noted in comments.

**Comment by ruthan** [comment]
Possible by trick, make it properly pleas, its not intuitive at all..

**Comment by Thog** [comment]
@ruthan we do not have control over this file picker. If you want this to be improved, I redirect you to GTK issue tracker.

**Comment by ruthan** [comment]
Ok, but make sense let it opened, as blocked by 3rd party issue or something like that.
