### ISSUE TITLE
It is for 32bit only ? 

### ISSUE THREAD

**Issue by azoreseuropa** [Ryujinx/Ryujinx#969]
My Catalina require 64bit only and it wont let me.

**Comment by ReaperOfSouls1909** [comment]
Ryujinx is 64bit but you have to open through terminal ./Ryjinx cmd

**Comment by AcK77** [comment]
Hi, 
Ryujinx GitHub is for development only.
Feel free to ask for help in our support channel on our Discord server.
In that case I close this issue.
Thanks.
