### ISSUE TITLE
Libretro port of Ryujinx

### ISSUE THREAD

**Issue by FinixFighter** [Ryujinx/Ryujinx#973]
Hi! I was wondering if there are any plans of porting Ryujinx to libretro, so that it can be added to Retroarch as a core. :)

**Comment by jduncanator** [comment]
Hey @FinixFighter.

There are some longer term plans, and I’m currently in the process of rearchitecting a large portion of Ryujinx that would allow this transition and implementation of a libretro version.

I don’t really have any ETA’s or progress report to give you at the moment, but it’s definitely in my crosshairs and we are making progress towards it at the moment.

I’ll keep you updated with progress if anything changes.

Thanks for the suggestion!

**Comment by PrismFlux** [comment]
Hey! :) 
What's the progress so far?  Or is it not a priority anymore?

**Comment by jduncanator** [comment]
> Hey! :)
> What's the progress so far? Or is it not a priority anymore?

This has been put on the backburner for some other projects that would gain more immediate benefit. It was also evident that undertaking a large refactoring of the Ryujinx project, as I was aiming to do, isn't really a good idea, nor feasible, whilst the project is in such a state of flux, constantly moving and having things changed.

Once the project reaches a point we can consider "stable", then I'll revisit this. Until then, I have no immediate plans to continue working on this.

**Comment by PrismFlux** [comment]
Ok,  I appreciate the quick answer :)

**Comment by mmtmn** [comment]
Hey, so thanks so much for having this still open! Any luck with it all?

**Comment by Owen-sys** [comment]
any updates since then

**Comment by Thog** [comment]
Hello there,

Considering the amount of drama and harassment that many friends from the emulation developer community have suffered from because of RetroArch, I think it's fair to say that it is not something the Ryujinx team want to happen here.

As such, **we do not wish any integrations with RetroArch or its community**.

Best Regards,

Mary

**Comment by Shituation** [comment]
What a pity, especially when your emulator lacks gamepad exit bindings. I play with a gamepad so I play mostly at a distance. Its inconvenient to have to go to the pc to exit the emu. I was hoping there was a retroarch core since RA fixes that lacking feature for most modern emulators nowadays. 🙁
