### ISSUE TITLE
Feature request Add support for updates and DLC installing

### ISSUE THREAD

**Issue by ANIMEFANATIC91** [Ryujinx/Ryujinx#990]
Hi, I wanted to ask if you could add the possibility to install updates and dlcs from nsp or xci files directly in the emulator, instead of using nsc builder to do it,

**Comment by Ghostotakoi** [comment]
they are on it https://github.com/Ryujinx/Ryujinx/pull/569 requesting to close.

**Comment by gdkchan** [comment]
This does not support loading updates or DLC from a separate file.
