### ISSUE TITLE
XC2 Docked Hits a muselc assert and crashs

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#991]
[Xenoblade Docked Crash.log](https://github.com/Ryujinx/Ryujinx/files/4333395/Xenoblade.Docked.Crash.log)

**Comment by AcK77** [comment]
This should goes in https://github.com/Ryujinx/Ryujinx-Games-List/issues/159 since it's a game specific issue. In this case I close the issue. 
Thanks.
